[id='cofiguring-random-number-proc_{context}']
= Configuring the random number generator

Many heuristics and metaheuristics depend on a pseudorandom number generator for move selection, to resolve score ties, probability based move acceptance, and so on. During solving, the same random instance is reused to improve reproducibility, performance, and uniform distribution of random values.

A random seed is a number used to initialize a pseudorandom number generator.

.Procedure
. Optional: To change the random seed of a random instance, specify a `randomSeed`:
+
[source,xml,options="nowrap"]
----
<solver xmlns="https://www.optaplanner.org/xsd/solver" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.optaplanner.org/xsd/solver https://www.optaplanner.org/xsd/solver/solver.xsd">
  <randomSeed>0</randomSeed>
  ...
</solver>
----

. Optional: To change the pseudorandom number generator implementation, specify a value for the `randomType` property listed in the solver configuration file below, where `<RANDOM_NUMBER_GENERATOR>` is a pseudorandom number generator:
+
[source,xml,options="nowrap",subs="attributes+"]
----
<solver xmlns="https://www.optaplanner.org/xsd/solver" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.optaplanner.org/xsd/solver https://www.optaplanner.org/xsd/solver/solver.xsd">
  <randomType><RANDOM_NUMBER_GENERATOR></randomType>
  ...
</solver>
----
+
The following pseudorandom number generators are supported:

* `JDK` (default): Standard random number generator implementation (`java.util.Random`)
* `MERSENNE_TWISTER`: Random number generator implementation by http://commons.apache.org/proper/commons-math/userguide/random.html[Commons Math]
* `WELL512A`, `WELL1024A`, `WELL19937A`, `WELL19937C`, `WELL44497A` and `WELL44497B`: Random number generator implementation by http://commons.apache.org/proper/commons-math/userguide/random.html[Commons Math]

For most use cases, the value of the `randomType` property has no significant impact on the average quality of the best solution on multiple data sets.
//If you want to confirm this on your use case, use the benchmarker.

