[id='logback-proc_{context}']
= Using Logback to log OptaPlanner solver activity
Logback is the recommended logging frameworkd to use with {PLANNER_SHORT}. Use Logback to log OptaPlanner solver activity.

.Prerequisites
* You have an OptaPlanner project.

.Procedure

. Add the following Maven dependency to your {PLANNER_SHORT} project's `pom.xml` file:
+
NOTE: You do not need to add an extra bridge dependency.
+
[source,xml,options="nowrap"]
----
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.x</version>
    </dependency>
----

. Configure the logging level on the `org.optaplanner` package in your `logback.xml` file as shown in the following example where `<LEVEL>` is a logging level listed in xref:logback-proc_{context}[].
+
[source,xml,options="nowrap"]
----
<configuration>

  <logger name="org.optaplanner" level="<LEVEL>"/>

  ...

</configuration>
----
. Optional: If you have a multitenant application where multiple `Solver` instances might be running at the same time, separate the logging of each instance into separate files:
.. Surround the `solve()` call with  http://logback.qos.ch/manual/mdc.html[Mapped Diagnostic Context] (MDC):
+
[source,java,options="nowrap"]
----
        MDC.put("tenant.name",tenantName);
        MySolution bestSolution = solver.solve(problem);
        MDC.remove("tenant.name");
----

.. Configure your logger to use different files for each `${tenant.name}`.
For example, use a `SiftingAppender` in the `logback.xml` file:
+
[source,xml,options="nowrap"]
----
  <appender name="fileAppender" class="ch.qos.logback.classic.sift.SiftingAppender">
    <discriminator>
      <key>tenant.name</key>
      <defaultValue>unknown</defaultValue>
    </discriminator>
    <sift>
      <appender name="fileAppender.${tenant.name}" class="...FileAppender">
        <file>local/log/optaplanner-${tenant.name}.log</file>
        ...
      </appender>
    </sift>
  </appender>
----
+
[NOTE]
====
When running multiple solvers or one multithreaded solve,
most appenders, including the console, cause congestion with `debug` and `trace` logging.
Switch to an async appender to avoid this problem or turn off `debug` logging.
====

. If OptaPlanner doesn't recognize the new level, temporarily add the system property `-Dlogback._LEVEL_=true` to troubleshoot.

