[id='adjust-data-dir-proc_{context}']

= Update the data directory

You can update the data directory that OptaWeb Vehicle Routing  uses if you want to use a different data directory. The default data directory is `$HOME/.optaweb-vehicle-routing`.

.Prerequisites
* OptaWeb Vehicle Routing has been successfully built with Maven as described in xref:download-ref-imp-proc_{context}[].

.Procedure
* To use a different data directory, add the directory's absolute path to the `.DATA_DIR_LAST` file in the current data directory.
* To change country codes associated with a region, edit the corresponding file in the `country_codes` directory, in the current data directory.
+
For example, if you downloaded an OSM file for Scotland and the script fails to guess the country code, set the content of `country_codes/scotland-latest` to GB.

* To remove a region, delete the corresponding OSM file from `openstreetmap` directory in the data directory and delete the region's directory in the `graphhopper` directory.
