[id='run-locally-qs-proc_{context}']

= Run the OptaWeb Vehicle Routing runLocally.sh script in quick start mode

The easiest way to get started with OptaWeb Vehicle Routing is to run the `runLocally.sh` script without any arguments.

.Prerequisites
* OptaWeb Vehicle Routing has been successfully built with Maven as described in xref:download-ref-imp-proc_{context}[].

* Internet access is available.


.Procedure
. Enter the following command in the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts/optaweb-{OPTAPLANNER_BOM_VERSION}/{URL_COMPONENT_VRP}` directory.
+
[source]
----
 ./runLocally.sh
----
 . If prompted to create the `.optaweb-vehicle-routing` directory, enter `y`. You are prompted to create this directory the first time you run the script.
 . If prompted to download an OSM file, enter `y`. The first time that you run the script, OptaWeb Vehicle Routing downloads the Belgium OSM file.
+
The application starts after the OSM file is downloaded.
. To open the OptaWeb Vehicle Routing user interface, enter the following URL in a web browser:
+
[source]
----
http://localhost:8080
----

NOTE: The first time that you run the script, it will take  a few minutes to start because the OSM file must be imported by GraphHopper and stored as a road network graph.
The next time you run the `runlocally.sh` script, load times will be significantly faster.
