[id='run-locally-interactive-proc_{context}']

= Run the OptaWeb Vehicle Routing runLocally.sh script in interactive mode

Use interactive mode to see the list of downloaded OSM files and country codes assigned to each region.
You can use the interactive mode to download additional OSM files from Geofabrik without visiting the website and choosing a destination for the download.


.Prerequisites
* OptaWeb Vehicle Routing has been successfully built with Maven as described in xref:download-ref-imp-proc_{context}[].
* Internet access is available.

.Procedure
. Change directory to `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts/optaweb-{OPTAPLANNER_BOM_VERSION}/{URL_COMPONENT_VRP}`.
. Enter the following command to run the script in interactive mode:
+
[source]
----
./runLocally.sh -i
----
. At the `Your choice` prompt, enter `d` to display the download menu. A list of previously downloaded regions appears followed by a list of regions that you can download.
. Optional: Select a region from the list of previously downloaded regions:
.. Enter the number associated with a region in the list of downloaded regions.
.. Press the Enter key.
. Optional: Download a region:
.. Enter the number associated with the region that you want to download. For example, to select the map of Europe, enter `5`.
.. To download the map, enter `d` then press the Enter key.
.. To download a specific region within the map, enter `e` then enter the number associated with the region that you want to download, and press the Enter key.
+

[WARNING]
.Using large OSM files
====
For the best user experience, use smaller regions such as individual European or US states.
Using OSM files larger than 1 GB will require significant RAM size and take a lot of time (up to several hours) for the initial processing.
====
+
The application starts after the OSM file is downloaded.

. To open the OptaWeb Vehicle Routing user interface, enter the following URL in a web browser:
+
[source]
----
http://localhost:8080
----
