[id='vrp-frontend-proc_{context}']

= Working with the OptaWeb Vehicle Routing front-end module

////
- PatternFly, Leaflet
- Npm, React, Redux, TypeScript, ESLint, Cypress, `ncu`
- Chrome, plugins
- Docker
////

The front-end project was bootstrapped with https://create-react-app.dev/[Create React App].
Create React App provides a number of scripts and dependencies that help with development and with building the application for production.

.Prerequisites
* The OptaWeb Vehicle Routing starter application has been downloaded and extracted. For information, see xref:download-ref-imp-proc_{context}[].

.Procedure
. On Fedora, enter the following command to set up the development environment:
+
[source,shell]
----
sudo dnf install npm
----
+
See https://docs.npmjs.com/downloading-and-installing-node-js-and-npm[Downloading and installing Node.js and npm] for more information about installing npm.

. Change directory to `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts/optaweb-{OPTAPLANNER_BOM_VERSION}/{URL_COMPONENT_VRP}/optaweb-vehicle-routing-frontend`.

. Install `npm` dependencies:
+
[source,shell]
----
npm install
----
+
Unlike Maven, the `npm` package manager installs dependencies in `node_modules` under the project directory and does that only when you execute `npm install`.
Whenever the dependencies listed in `package.json` change, for example when you pull changes to the master branch, you must execute `npm install` before you run the development server.

. Enter the following command to run the development server:
+
[source,shell]
----
npm start
----

. If it does not open automatically, open `\http://localhost:3000/` in a web browser.
+
By default, the `npm start` command attempts to open this URL in your default browser.
+
[NOTE]
====
If you do not want the `npm start` command to open a new browser tab each time you run it, export the  `BROWSER=none` environment variable. You can use `.env.local` file to make this preference permanent.
To do that, enter the following command:

[source,shell]
----
echo BROWSER=none >> .env.local
----
====
+
The browser refreshes the page whenever you make changes in the front-end source code.
The development server process running in the terminal picks up the changes as well and prints compilation and lint errors to the console.

. Enter the following command to run tests:
+
[source]
----
npm test
----

. Change the value of the `REACT_APP_BACKEND_URL` environment variable to specify the location of the back-end project to be used by `npm` when you execute  `npm start` or `npm run build`, for example:
+
[source]
----
REACT_APP_BACKEND_URL=http://10.0.0.123:8081
----
+
NOTE: Environment variables are hard coded inside the JavaScript bundle during the `npm` build process, so you must specify the back-end location before you build and deploy the front end.
+
To learn more about the React environment variables, see https://create-react-app.dev/docs/adding-custom-environment-variables/[_Adding Custom Environment Variables_].

. To build the front end, enter one of the following commands:
+
[source]
----
./mvnw install
----
+
[source]
----
mvn install
----
