[id='vrp-con_{context}']

= What is OptaWeb Vehicle Routing?
//We try to avoid empty headings where you have a heading followed directly by a sub-heading so I promoted this section and removed Introduction.

The main purpose of many businesses is to transport various types of cargo.
The goal of these businesses is to deliver a piece of cargo from the loading point to a destination and use its vehicle fleet in the most efficient way. One of the main objectives is to minimize travel costs which are measured in either time or distance.

//ifdef::COMMUNITY[]
//This type of optimization problem is referred to as the https://www.optaplanner.org/learn/useCases/vehicleRoutingProblem.html[vehicle routing problem] (VRP) and has many variations.
//endif::COMMUNITY[]


This type of optimization problem is referred to as the vehicle routing problem (VRP) and has many variations.


//ifdef::COMMUNITY[]
//https://www.optaplanner.org/[OptaPlanner]
//endif::COMMUNITY[]

{PLANNER} can solve many of these vehicle routing variations and provides solution examples.
{PLANNER} enables developers to focus on modeling business rules and requirements instead of learning https://en.wikipedia.org/wiki/Constraint_programming[constraint programming] theory.
OptaWeb Vehicle Routing expands {PLANNER}'s vehicle routing capabilities by providing a reference implementation that answers questions such as these:

* Where do I get the distances and travel times?
* How do I visualize the solution on a map?
* How do I build an application that runs in the cloud?

You can get up and running with OptaWeb Vehicle Routing in just a few steps.
In this chapter you will download the OptaWeb Vehicle Routing distribution archive containing a binary build of OptaWeb Vehicle Routing.
You will then use a Bash script to run the binary without having to build the project.
