[id='vrp-run-openshift-proc_{context}']

= Run OptaWeb Vehicle Routing on {OPENSHIFT}

Linux users can use the `runOnOpenShift.sh` Bash script to install OptaWeb Vehicle Routing on {OPENSHIFT}.

NOTE:  The `runOnOpenShift.sh` script does not run on macOS.

//You can use Red Hat CodeReady Containers to set up a single-node OpenShift 4 cluster on your local computer. CodeReady Containers provides a minimal preconfigured OpenShift cluster for development and testing purposes. It is delivered as a Red Hat Enterprise Linux virtual machine.

.Prerequisites

* You have access to an OpenShift cluster and the OpenShift command-line interface (`oc`) has been installed. For information about {OpenShift}, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html-single/installing/index[_Installing OpenShift Container Platform_].
* OptaWeb Vehicle Routing has been successfully built with Maven as described in xref:download-ref-imp-proc_{context}[].
* Internet access is available.

.Procedure
. Log in to or start a {OPENSHIFT} cluster.

////
.. Add the OpenShift command-line interface (`oc`) to your `$PATH`:
+
[source,shell]
----
eval $(crc oc-env)
----

.. Log in as the `developer` user:
+
[source,shell]
----
oc login -u developer -p developer https://api.crc.testing:6443
----
////
.. Enter the following command where `<PROJECT_NAME>` is the name of your new project:
+
[source]
----
oc new-project <PROJECT_NAME>
----
.. If necessary, change directory to `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts/optaweb-{OPTAPLANNER_BOM_VERSION}/{URL_COMPONENT_VRP}`.

.. Enter the following command to execute the `runOnOpenShift.sh` script and download an OpenStreetMap (OSM) file:
+
[source]
----
./runOnOpenShift.sh <OSM_FILE_NAME> <COUNTRY_CODE_LIST> <OSM_FILE_DOWNLOAD_URL>
----
+
In this command, replace the following variables:

* `<OSM_FILE_NAME>`: The name of a file downloaded from `<OSM_FILE_DOWNLOAD_URL>`.
* `<COUNTRY_CODE_LIST>`: A comma-separated list of country codes used to filter geosearch queries. For a list of country codes, see https://www.iso.org/iso-3166-country-codes.html[_ISO 3166 Country Codes_].
* `<OSM_FILE_DOWNLOAD_URL>`: The URL of an OSM data file in PBF format accessible from OpenShift. The file will be downloaded during backend startup and saved as `/deployments/local/<OSM_FILE_NAME>`.
+
In the following example, OptaWeb Vehicle Routing downloads the OSM map of Central America (`central-america-latest.osm.pbf`) and searches in the countries Belize (BZ) and Guatemala (GT).
+
[source]
----
./runOnOpenShift.sh central-america-latest.osm.pbf BZ,GT http://download.geofabrik.de/europe/central-america-latest.osm.pbf
----

NOTE: For help with the `runOnOpenShift.sh` script, enter `./runOnOpenShift.sh --help`.
