[id='vrp-create-route-proc_{context}']

= Creating a route

To create an optimal route, use the *Demo* tab of the OptaWeb Vehicle Routing user interface.

.Prerequisites
* OptaWeb Vehicle Routing is running and you have access to the user interface.

.Procedure
. In OptaWeb Vehicle Routing, click *Demo* to open the *Demo* tab.
. Use the blue minus and plus buttons above the map to set the number of vehicles. Each vehicle has a default capacity of 10.
. Use the plus button in a square on the map to zoom in as required.
+
[NOTE]
====
Do not double-click to zoom in.
A double click also creates a location.
====
+
. Click a location for the depot.
. Click other locations on the map for delivery points.
. If you want to delete a location:
.. Hover the mouse cursor over the location to see the location name.
.. Find the location name in the list in the left part of the screen.
.. Click the *X* icon next to the name.

Every time you add or remove a location or change the number of vehicles, the application creates and displays a new optimal route.
If the solution uses several vehicles, the application shows the route for every vehicle in a different color.
