[id='vrp-backend-con_{context}']

= The OptaWeb Vehicle Routing back-end module

The back-end module contains a server-side application that uses {PLANNER} to optimize vehicle routes.
Optimization is a CPU-intensive computation that must avoid any I/O operations in order to perform to its full potential.
Because one of the chief objectives is to minimize travel cost, either time or distance, OptaWeb Vehicle Routing keeps the travel cost information in RAM memory.
While solving, {PLANNER_SHORT} needs to know the travel cost between every pair of locations entered by the user.
This information is stored in a structure called the _distance matrix_.

When you enter a new location, OptaWeb Vehicle Routing calculates the travel cost between the new location and every other location that has been entered so far, and stores the travel cost in the distance matrix.
The travel cost calculation is performed by the https://github.com/graphhopper/graphhopper[GraphHopper] routing engine.

The back-end module implements the following additional functionality:

* Persistence
* WebSocket connection for the front end
* Data set loading, export, and import

To learn more about the back-end code architecture, see xref:backend-architecture-con_{context}[].
