[id='vrp-update-deployed-changes-proc_{context}']

= Updating the deployed OptaWeb Vehicle Routing application with local changes

After you deploy your OptaWeb Vehicle Routing application on {OPENSHIFT}, you can update the back end and front end.

.Prerequisites
* OptaWeb Vehicle Routing has been successfully built with Maven and deployed on OpenShift.

.Procedure
* To update the back end, perform the following steps:

. Change the source code and build the back-end module with Maven.
. Change directory to `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts/optaweb-{OPTAPLANNER_BOM_VERSION}/{URL_COMPONENT_VRP}`.
. Enter the following command to start the OpenShift build:
+
[source,shell]
----
oc start-build backend --from-dir=. --follow
----

* To update the front end, perform the following steps:

. Change the source code and build the front-end module with the `npm` utility.
. Change directory to `sources/optaweb-vehicle-routing-frontend`.
. Enter the following command to start the OpenShift build:
+
[source,shell]
----
oc start-build frontend --from-dir=docker --follow
----
