[id='vrp-backend-config-proc_{context}']

= Changing OptaWeb Vehicle Routing back-end module system property values

You can temporarily or permanently override the default system property values of the OptaWeb Vehicle Routing back-end module.

The OptaWeb Vehicle Routing back-end module system properties are stored in the `/src/main/resources/application.properties` file. This file is under version control. Use it to permanently store default configuration property values and to define Quarkus profiles.

.Prerequisites
* The OptaWeb Vehicle Routing starter application has been downloaded and extracted. For information, see xref:download-ref-imp-proc_{context}[].

.Procedure

* To temporarily override a default system property value, include the `-D<PROPERTY>=<VALUE>` argument when you run the `mvn` or `java` command, where `<PROPERTY>` is the name of the property that you want to change and `<VALUE>` is the value that you want to temporarily assign to that property. The following example shows how to temporarily change the value of the `quarkus.http.port` system property to `8181` when you use Maven to compile a Quarkus project in `dev` mode:
+
[source]
----
mvn compile quarkus:dev -Dquarkus.http.port=8181
----
+
This temporarily changes the value of the property stored in the `/src/main/resources/application.properties` file.

* To change a configuration value permanently, for example to store a configuration that is specific to your development environment, copy the contents of the `env-example` file to the `optaweb-vehicle-routing-backend/.env` file.
+
This file is excluded from version control and therefore it does not exist when you clone the repository. You can make changes in the `.env` file without affecting the Git working tree.

.Additional resources
For a complete list of OptaWeb Vehicle Routing configuration properties, see xref:backend-properties-ref_{context}[].
