[id='proc-business-central-creating-users_{context}']
= Creating users
User privileges and settings are controlled by the roles assigned to a user and the groups that a user belongs to. You can create any number of users in {CENTRAL}.

[NOTE]
====
Do not create a user called `unknown` in {PROCESS_ENGINE} or {KIE_SERVER}. The `unknown` user account is a reserved system name with superuser access. The `unknown` user account performs tasks related to the SLA violation listener when there are no users logged in.
====

.Procedure
. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Users*.
. Click *New user*, enter a user name, and then click *Next*.
. To assign roles to the user, click the *Roles* tab, click *Add Roles*, select the desired roles, and click *Add to selected roles*.
. Optional: To assign groups to the user, click the *Groups* tab, click *Add to groups*, select the desired groups, and click *Add to selected groups*.
. Click *Create*.
. Click *Yes* to set a password for the user, enter a desired password, and click *Change*.

[NOTE]
====
The user must have at least one role to access {CENTRAL}.
====
