[id='assembly-custom-tasks-and-work-item-handlers']
= Custom tasks and work item handlers
ifdef::context[:parent-context: {context}]
// Context attribute is assembly specific and enables module reuse between assemblies.
:context: custom-tasks

// Purpose statement for the assembly
As a business rules developer, you can create custom tasks and work item handlers to execute custom code within your process flows and extend the operations available for use in {PRODUCT}. You can use custom tasks to develop operations that {PRODUCT} does not directly provide and include them in process diagrams. Custom tasks and work item handlers support {CENTRAL}, standalone editors, and Visual Studio Code (VSCode). This chapter describes how to use {CENTRAL} to create, manage, and deploy custom tasks and work item handlers.

In {CENTRAL}, each task in a process diagram has a `WorkItemDefinition` Java class with an associated `WorkItemHandler` Java class. You can define a `WorkItemDefinition` using an MVFLEX Expression Language (MVEL) map as part of a MVEL list in a `.wid` file. Place the `.wid` file in the `global` directory under the project root or in the directory of the BPMN file. The work item handler contains Java code registered with {CENTRAL} and implements `org.kie.api.runtime.process.WorkItemHandler`.

The Java code of the work item handler is executed when the task is triggered. You can customize and register a work item handler to execute your own Java code in custom tasks.

.Prerequisites
* {CENTRAL} is deployed and is running on a web or application server.
* You are logged in to {CENTRAL}.
* Maven is installed.
* The host has access to the Internet. The build process uses the Internet for downloading Maven packages from external repositories.
* Your system has access to the Red Hat Maven repository either locally or online

include::{jbpm-dir}/BPMN2/manage-service-tasks-proc.adoc[leveloffset=+1]

include::{jbpm-dir}/BPMN2/custom-tasks-creating-work-item-handler-projects-proc.adoc[leveloffset=+1]

include::{jbpm-dir}/BPMN2/custom-tasks-work-item-handler-project-customization-con.adoc[leveloffset=+1]

include::{jbpm-dir}/BPMN2/custom-tasks-work-item-definitions-con.adoc[leveloffset=+1]

include::{jbpm-dir}/BPMN2/custom-tasks-deploying-custom-tasks-proc.adoc[leveloffset=+1]

include::{jbpm-dir}/BPMN2/custom-tasks-registering-custom-tasks-proc.adoc[leveloffset=+1]

include::{jbpm-dir}/BPMN2/custom-tasks-placing-custom-tasks-proc.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
