[id='assembly-pmml-models']
= Designing a decision service using PMML models
ifdef::context[:parent-context: {context}]
// Context attribute is assembly specific and enables module reuse between assemblies.
:context: pmml-models

// Purpose statement for the assembly
As a business rules developer, you can use Predictive Model Markup Language (PMML) to define statistical or data-mining models that you can integrate with your decision services in {PRODUCT}. {PRODUCT} includes consumer conformance support of PMML 4.2.1 for Regression, Scorecard, Tree, and Mining models. {PRODUCT} does not include a built-in PMML model editor, but you can use an XML or PMML-specific authoring tool to create PMML models and then integrate them with your {PRODUCT} projects.

For more information about PMML, see the DMG http://dmg.org/pmml/pmml-v4-4-1.html[PMML specification].

[NOTE]
====
You can also design your decision service using Decision Model and Notation (DMN) models and include your PMML models as part of your DMN service. For information about DMN support in {PRODUCT} {PRODUCT_VERSION}, see the following resources:

* {URL_GETTING_STARTED}#assembly-getting-started-decision-services[_{GETTING_STARTED_DECISION_SERVICE}_] (step-by-step tutorial with a DMN decision service example)
* {URL_DEVELOPING_DECISION_SERVICES}#dmn-included-models-pmml-proc_dmn-models[_{DMN_MODELS}_] (overview of DMN support and capabilities in {PRODUCT})
====

// Modules - concepts, procedures, refs, etc.
include::{shared-dir}/KIE/Overview/decision-authoring-assets-ref.adoc[leveloffset=+1]

include::{drools-dir}/PMML/pmml-con.adoc[leveloffset=+1]

include::{drools-dir}/PMML/pmml-conformance-con.adoc[leveloffset=+2]

include::{drools-dir}/PMML/pmml-model-example-ref.adoc[leveloffset=+1]

include::{drools-dir}/PMML/pmml-support-con.adoc[leveloffset=+1]

include::{drools-dir}/PMML/pmml-naming-conventions-trusty-con.adoc[leveloffset=+2]

include::{drools-dir}/PMML/pmml-naming-conventions-legacy-con.adoc[leveloffset=+2]

include::{drools-dir}/PMML/pmml-extensions-ref.adoc[leveloffset=+3]

include::{drools-dir}/PMML/pmml-invocation-options-con.adoc[leveloffset=+1]

include::{drools-dir}/PMML/pmml-invocation-embedded-trusty-proc.adoc[leveloffset=+2]

include::{drools-dir}/PMML/pmml-invocation-embedded-proc.adoc[leveloffset=+2]

include::{drools-dir}/PMML/pmml-invocation-helper-classes-ref.adoc[leveloffset=+3]

include::{drools-dir}/PMML/pmml-invocation-kie-server-proc.adoc[leveloffset=+2]

== Additional resources
* http://dmg.org/pmml/pmml-v4-4-1.html[PMML specification]
* {URL_DEPLOYING_AND_MANAGING_SERVICES}#assembly-packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_]
* {URL_DEPLOYING_AND_MANAGING_SERVICES}#assembly-kie-apis[_{KIE_APIS}_]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
