[id='bpmn-connecting-ref_{context}']
= BPMN2 connecting objects in process designer
Connecting objects create an association between two BPMN2 elements. When a connecting object is directed, the association is sequential and indicates that one of the elements is executed immediately before the other, within an instance of the process. Connecting objects can start and end at the top, bottom, right, or left of the process elements being associated. The OMG BPMN2 specification allows you to use your discretion, placing connecting objects in a way that makes the process behavior easy to understand and follow.

BPMN2 supports two main types of connecting objects:

* Sequence flows: Connect elements of a process and define the order in which those elements are executed within an instance.
* Association flows: Connect the elements of a process without execution semantics. Association flows can be undirected or unidirectional.

NOTE: The new process designer supports only undirected association flows. The legacy designer supports one direction and Unidirectional flows.
