= Data Sets


The data set functionality in Business Central defines how to access and parse data.
Data sets serve as a source of data that can be displayed by the Dashbuilder displayer.
You can add the Dashbuilder displayers to a custom perspective in the Plugin Management perspective.
Note that the data set perspective is visible only to users of the Administrator group.

== Managing Data Sets


To add a data set definition:

. Log into Business Central and click *Extensions* -> *Data Sets*.
. Click *New Data Set*.
. Select the provider type and click *Next*. Currently, the following provider types are supported:
* Java Class {ndash} generate a data set from a Java class.
* SQL {ndash} generate a data set from an ANSI-SQL compliant database.
* CSV {ndash} generate a data set from a remote or local CSV file.
* Elasticsearch {ndash} generate a data set from Elasticsearch nodes.

[NOTE]
====
Elasticsearch data set integration support is limited to commercially reasonable efforts.
For details, see https://access.redhat.com/solutions/710953[What is commercially reasonable support?]. 
====

. Complete the *Data Set Creation Wizard* and click *Test*.
. Depending on what provider you chose, the configuration steps will differ. Once you complete the steps, click *Save* to create a data set definition.


To edit a data set:

. Log into Business Central and click *Extensions* -> *Data Sets*.
. In *Data Set Explorer*, click on an existing data set and click *Edit*.
. *Data Set Editor* opens. You can edit your data set in three tabs. Note that some of the tabs differ based on the provider type you chose. The following applies to the _CSV_ data provider.
* *CSV Configuration* {ndash} allows you to change the name of your data set definition, the source file, the separator, and other properties.
* *Preview* {ndash} after you click *Test* in the *CSV Configuration* tab, the system executes the data set lookup call and if the data is available, you will see a preview. Notice two subtabs:
** *Data columns* {ndash} allows you to customize what columns are part of your data set definition.
** *Filter* {ndash} allows you to add a new filter.
* *Advanced* {ndash} allows you to manage:
** Caching {ndash} see <<_caching_bpms>> for more information.
** Cache life-cycle {ndash} see <<_refresh_bpms>> for more information.


[[_caching_bpms]]
== Caching


{PRODUCT} data set functionality provides two cache levels:

* Client level
* Back end level


[float]
=== Client Cache


When turned on, the data set is cached in a web browser during the look-up operation.
Consequently, further look-up operations do not perform any request to the backend.

[float]
=== Backend Cache


When turned on, the data set is cached by the {PRODUCT} engine.
This reduces the number of requests to the remote storage system.

[NOTE]
====
The Java and CSV data providers rely on back-end caching.
As a result, back-end cache settings are not always visible in the *Advanced*
 tab of the *Data Set Explorer*.
====

[[_refresh_bpms]]
== Data Refresh


The refresh features allow you to invalidate cached data set data after a specified interval of time.
The *Refresh on stale data* feature invalidates cached data when the back-end data changes.
