[[_chap_graphic_resources]]
= Graphic Resources

Red Hat JBoss Dashboard Builder
 uses the following components to define the environment appearance and thus separate the presentation resources from content and data:

* Skins define a set of style sheets, images, and icons
* Region layouts define layouts of regions for pages
* Envelopes define an HTML template used as page frames


[float]
== Graphic Resources Definitions


All graphics components are deployed as zip files as part of the Red Hat JBoss Dashboard Builder in the `$DEPLOYMENT_LOCATION/dashbuilder.war/WEB-INF/etc/` directory.

Every component definition contains the following:

* properties file that defines the name of the component for individual supported locales, the name of the css file to be applied on the component, and mapping of file to individual component elements
* JSP, HTML, CSS files, and image and icon resources referenced from the properties file


When creating custom graphic resources, it is recommended to download one of the existing components and modify it as necessary.
This will prevent unnecessary mistakes in your definition.

[[_adding_graphic_resources]]
== Working With Graphic Resources


. On the top menu, click the *General configuration* button.
. Under the *Graphic resources* node on the left, click the component type you want to work with (*Skins* , *Layouts* , *Envelopers*). The window on the right will display the content relevant for the given component type.
. On the right, you can now do the following:
+
.. Upload a new component: you need to provide a unique ID for the component and the resource zip file. Then click *Add*.
.. Download a component definition or preview the component: in the table below the Add view, click the respective icon in the *Actions* column.
