[[_chap_managing_assets]]
= Managing Assets

[[_versions_and_storage]]
== Versions and Storage

Business rules, process definition files, and other assets and resources created in Business Central are stored in Artifact Repository (Knowledge Store), that is accessed by the
ifdef::BPMS[]
Intelligent Process Server.
endif::BPMS[]
ifdef::BRMS[]
Realtime Execution Server.
endif::BRMS[]

Knowledge Store is a centralized repository for your business knowledge.
It connects multiple repositories (currently only GIT repositories are supported) so that you can access them from a single environment while allowing you to store different kinds of knowledge and artifacts in different locations.
Business Central provides a web front-end that allows users to view and update the store content.
You can access the Knowledge Store from the unified environment of {PRODUCT} in the *Project Editor* and *Project Explorer* under the *Authoring Perspective*.

GIT is a distributed version control system and it implements revisions as commit objects.
Every time you commit your changes into a repository this creates a new commit object in the GIT repository.
Similarly, the user can also copy an existing repository.
This copying process is typically called cloning and the resulting repository can be referred to as clone.
Every clone contains the full history of the collection of files and a cloned repository has the same content as the original repository.
