[id='config-process-form-designer']
= Configuring a process in the forms designer *Modeler?*

You can generate forms automatically from process variables and task definitions and later modify the forms using the form editor.
In runtime, forms receive data from process variables, display it to the user, capture user input, and update the process variables with the new values.
To configure a process in Form Modeler, do the following:

. Create process variables to store the form input. Variables can be of a simple type, like `String`, or a complex type. You can define complex variables using Data Modeler, or create them in any Java integrated development environment (Java IDE) as regular plain Java objects.
. Declare the process variables in the *Editor for Variable Property* window of the *variables definition* property of the business process.
. Determine which variables you want to set as input parameters for the task, which will receive response from the form. After you create the variables, map the variables to inputs by setting *Data Input Assignments* and *Data Output Assignments* for a Human Task. To do so, use the *Data I/O* form of the *Assignments* property.
