[id='constraints-con_{context}']
= Constraints

A constraint is a boolean expression that is evaluated when an element containing a constraint is executed. You can use constraints in various parts of your process, such as in a diverging gateway.

{PRODUCT} supports two types of constraints, including:

* *Code constraints*: Constraints that are defined in Java, Javascript, Drools, or MVEL. Code constraints can access the data in the working memory, including the global and process variables. The following code constraint examples contain `person` as a variable in a process:
+
.Example Java code constraint
+
[source]
----
return person.getAge() > 20;
----
+
.Example MVEL code constraint
+
[source]
----
return person.age > 20;
----
+
.Example Javascript code constraint
+
[source]
----
person.age > 20
----

* *Rule constraints*: Constraints that are defined in the form of DRL rule conditions. Rule constraints can access the data in the working memory, including global variables. However, rule constraints cannot access the variables directly in a process but using a process instance. To retrieve the reference of the parent process instance, use the `processInstance` variable of the type `WorkflowProcessInstance`.
+
NOTE: You can insert a process instance into the session and update it if necessary, for example, using Java code or an on-entry, on-exit, or explicit action in your process.

+
The following example shows a rule constraint, searching for a person with the same name as the value of the `name` variable in the process.
+
.Example rule constraint with process variable assignment
+
[source]
----
processInstance : WorkflowProcessInstance()
Person( name == ( processInstance.getVariable("name") ) )
# add more constraints here ...
----
