[id='define-role-based-access']
= Customizing role-based branch access
You can customize contributor role permissions for each branch of a project. For example, you can set *Read*, *Write*, *Delete*, and *Deploy* access for each role assigned to a branch.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects*.
. To add a new contributor:
.. Click on the project name and then click the *Contributors* tab.
.. Click *Add Contributor*.
.. Select the role name from the *admin* pull-down menu, for example, *analyst*.
.. Select the *Contributor* role type from the *Owner* pull-down menu.
.. Click *Ok*.
. To customize role-based branch access for an existing contributor:
.. Click *Settings* -> *Branch Management*.
.. Select the branch name from the *Branch Management* pull-down menu.
.. In the *Role Access* section, select or deselect the permissions check boxes to specify role-based branch access for each available role type.
.. Click *Save* and click *Save* again to confirm your changes.
