[id='deploy-bus-proc']
= Deploying a business process in {CENTRAL}
After you design your business process in {CENTRAL}, you can build and deploy your project in {CENTRAL} to make the process available to {KIE_SERVER}.

.Prerequisites
* {KIE_SERVER} is deployed and connected to {CENTRAL}.
ifdef::DM,PAM[]
For more information about {KIE_SERVER} configuration, see {URL_INSTALLING_AND_CONFIGURING}#assembly-install-on-eap[_{INSTALLING_ON_EAP}_].
endif::[]

.Procedure

. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects*.
. Click the project that you want to deploy.
. Click *Deploy*.
+
--
[NOTE]
====
You can also select the *Build & Install* option to build the project and publish the KJAR file to the configured Maven repository without deploying to a {KIE_SERVER}. In a development environment, you can click *Deploy* to deploy the built KJAR file to a {KIE_SERVER} without stopping any running instances (if applicable), or click *Redeploy* to deploy the built KJAR file and replace all instances. The next time you deploy or redeploy the built KJAR, the previous deployment unit (KIE container) is automatically updated in the same target {KIE_SERVER}. In a production environment, the *Redeploy* option is disabled and you can click *Deploy* only to deploy the built KJAR file to a new deployment unit (KIE container) on a {KIE_SERVER}.

To configure the {KIE_SERVER} environment mode, set the `org.kie.server.mode` system property to `org.kie.server.mode=development` or `org.kie.server.mode=production`. To configure the deployment behavior for a corresponding project in {CENTRAL}, go to project *Settings* -> *General Settings* -> *Version* and toggle the *Development Mode* option. By default, {KIE_SERVER} and all new projects in {CENTRAL} are in development mode. You cannot deploy a project with *Development Mode* turned on or with a manually added `SNAPSHOT` version suffix to a {KIE_SERVER} that is in production mode.
====

To review project deployment details, click *View deployment details* in the deployment banner at the top of the screen or in the *Deploy* drop-down menu. This option directs you to the *Menu* -> *Deploy* -> *Execution Servers* page.
--
