[id='modify-ui-form-modeler']

= Modifying (or customizing?) the UI style in Form Modeler

JBPM-5743 Add css layout customization - It is not possible to customize the layout using css-forms as it was in the old form-modeler.

BAPL-1159 [GSS-RFE] Modify the UI style in the Form Modeler
1. Proposed title of this feature request
Modify the UI style in the Form Modeler.
2. Who is the customer behind the request?
Account: Citigroup and acct 411070
TAM customer: yes
CSM customer: yes
Strategic: yes
3. What is the nature and description of the request?
Modifying the UI style of Form Controls or the CSS of the pages in the new Form Modeler.
4. Why does the customer need this? (List the business requirements here)
The customer would like to modify the UI style such as changing the size and font of Form Controls or modify the CSS of the pages.
5. How would the customer like to achieve this?
Customize the layout using css-forms as it was in the old Form Builder.
6. For each functional requirement listed, specify how Red Hat and the customer can test to confirm the requirement is successfully implemented.
7. Is there already an existing RFE upstream or in Red Hat Bugzilla?
https://issues.jboss.org/browse/JBPM-5743
8. Does the customer have any specific timeline dependencies and which release would they like to target (i.e. RHEL5, RHEL6)?
No
9. Is the sales team involved in this request and do they have any additional input?
No
10. List any affected packages or components.
Form Builder
11. Would the customer be able to assist in testing this functionality if implemented?
Yes
