[id='proc-create-process-data-object_{context}']

= Creating data object

Data objects represent, for example, documents used in a process in physical and digital form. Data objects appear as a page with a folded top right corner. The following procedure is a generic overview of creating a data object.

[NOTE]
====
In {PRODUCT_PAM} {PRODUCT_VERSION_LONG}, limited support for data objects is provided that excludes support for data inputs, data outputs, and associations.
====

.Procedure
. Create a business process.
. In the process designer, select the *Artifacts -> Data Object* from the tool palette.
. Either drag and drop a data object onto the process designer canvas or click a blank area of the canvas.
. If necessary, in the upper-right corner of the screen, click the *Properties* icon.
. Add or define the data object information listed in the following table as required.
+
.Data object parameters
[cols="30%,70%", options="header"]
|===
|Label
|Description

| *Name*
| The name of the data object. You can also double-click the data object shape to edit the name.

| *Metadata Attributes*
a| Add any custom metadata attribute name and value that you want to use for custom event listeners, such as a listener to implement some action when a metadata attribute is present.

The *Metadata Attributes* enable the new `metaData` extensions to BPMN diagrams and modify the behavior of the overall data object.

| *Type*
a| Select a type of the data object.

IMPORTANT: When you define a data type for a data object, you can use the same data type for other data type fields in *Properties*, such as *Imports* and *Data Assignments*.

|===

. Click *Save*.
