// IMPORTANT: For 1.10 and later, save each version release notes as its own module file in the release-notes folder that this `ReleaseNotesKogito<version>.adoc` file is in, and then include each version release notes file in the chap-kogito-release-notes.adoc after Additional resources of {PRODUCT} deployment on {OPENSHIFT} section, in the following format:
//include::release-notes/ReleaseNotesKogito<version>.adoc[leveloffset=+1]

[id="ref-kogito-rn-new-features-1.11_{context}"]
= New features in {PRODUCT} 1.11

[role="_abstract"]
The following sections describe some of the new features or enhancements in {PRODUCT} 1.11.

== {PRODUCT} runtimes

=== Support for {PRODUCT} Spring Boot starters

You can now add {PRODUCT} Spring Boot starters to your Spring Boot project and get started with {PRODUCT} quickly. For more information about {PRODUCT} Spring Boot starters, see {URL_CREATING_RUNNING}#ref-kogito-spring-boot-starter_kogito-creating-running[_Starters for your {PRODUCT} project_].

=== Renamed ArtifactId of {PRODUCT} messaging add-ons
The following {PRODUCT} messaging add-ons are renamed:

.Quarkus
|===
|Old ArtifactId | New ArtifactId

|kogito-addons-quarkus-cloudevents | kogito-addons-quarkus-messaging
|kogito-addons-quarkus-cloudevents-multi | kogito-addons-quarkus-messaging
|kogito-addons-quarkus-events-smallrye | kogito-addons-quarkus-events-process
|===

.Spring Boot
|===
|Old ArtifactId | New ArtifactId

| kogito-addons-springboot-cloudevents | kogito-addons-springboot-messaging
| kogito-addons-springboot-events-kafka | kogito-addons-springboot-events-process-kafka
|===

=== Renamed ArtifactId of {PRODUCT} Spring Boot archetype

The name of the {PRODUCT} Spring Boot archetype ArtifactId is changed from `kogito-springboot-archetype` to `kogito-spring-boot-archetype`.

To create a new Spring Boot based project using the archetype, see the instructions on {URL_CREATING_RUNNING}#chap-kogito-creating-running[_{CREATING_RUNNING}_].

=== Removed {PRODUCT} Quarkus archetype

The {PRODUCT} Quarkus archetype (`kogito-quarkus-archetype`) is no longer available. To create a new Quarkus based project, please revisit updated instructions on {URL_CREATING_RUNNING}#chap-kogito-creating-running[_{CREATING_RUNNING}_].

=== Breaking change on metrics name provided by {PRODUCT} Prometheus monitoring add-ons

The metrics name provided by {PRODUCT} Prometheus monitoring add-ons (`kogito-addons-quarkus-monitoring-prometheus` or `kogito-addons-springboot-monitoring-prometheus`) are changed as follows:

.Prometheus monitoring add-ons
|===
|Add-on |Changed to

|`kie_process_instance_started_total`
|`kogito_process_instance_started_total`

|`kie_process_instance_sla_violated_total`
|`kogito_process_instance_sla_violated_total`

|`kie_process_instance_completed_total`
|`kogito_process_instance_completed_total`

|`kie_process_instance_running_total`
|`kogito_process_instance_running_total`

|`kie_process_instance_duration_seconds`
|`kogito_process_instance_duration_seconds`

|`kie_work_item_duration_seconds`
|`kogito_work_item_duration_seconds`
|===

WARNING: You must review any of your configured tools such as Grafana in which the names of the metrics are used.

For more information about how to use these metrics, see {URL_CONFIGURING_KOGITO}#proc-prometheus-metrics-monitoring_kogito-configuring[_Enabling Prometheus metrics monitoring in Kogito_].

=== Renamed ArtifactId of {PRODUCT} Spring Boot BOM

The name of the {PRODUCT} Spring Boot BOM ArtifactId is changed from `kogito-springboot-bom` to `kogito-spring-boot-bom`.
For instructions on how to create a new Spring Boot based project, see the instructions on {URL_CREATING_RUNNING}#chap-kogito-creating-running[_{CREATING_RUNNING}_].

== {PRODUCT} Operator and CLI

=== Improved/new bla bla

Description

== {PRODUCT} supporting services

=== Ability to add Metadata Attributes to all nodes and events

You can now add *Metadata Attributes* property to all the nodes and events in the BPMN editor. The *Metadata Attributes* property is a key-value definition that you can use for custom event listeners. For more information about *Metadat Attributes* property, see {URL_PROCESS_SERVICES}#chap-kogito-developing-process-services[_{PROCESS_SERVICES}_].

=== {PRODUCT} Data Index service recommends upgraded version of Infinispan

Starting from {PRODUCT} 1.11.0, you must upgrade the Infinispan version to 12.1.7 or later to prevent the issues regarding results returned in paginated queries.

=== {PRODUCT} Data Index service supports new Gateway API

A new set of GraphQL queries and mutations are supported to perform the following operations on different {PRODUCT} services:

* Abort a process instance
* Retry a process instance
* Skip a process instance

For more information, see xref:proc-data-index-service-runtime-connection_kogito-configuring[].

=== {PRODUCT} Data Index service API queries extended to retrieve data from {PRODUCT} runtime services
The {PRODUCT} Data Index service API queries are now extended to retrieve process instance diagram and process instance nodes from runtimes {PRODUCT} services. For more information, see {URL_CONFIGURING_KOGITO}#con-data-index-service_kogito-configuring[_{PRODUCT} Data Index Service_]. 

- The process instance diagram
- The process instance available Nodes from the process definition

=== Processes and decisions integration in {PRODUCT}

{PRODUCT} enables the integration of processes and decisions. There are different ways to integrate the processes and decisions including:

* Embedded method
* Remote method

For more information about processes and decisions integration, see {URL_PROCESS_SERVICES}#con-process-decisions-integration_kogito-developing-process-services[_Processes and decisions integration in {PRODUCT}_].

== {PRODUCT} tooling

=== Improved/new bla bla

Description
