[id='error-list-cleanup-proc_{context}']
= Cleaning up the error list

The {PROCESS_ENGINE} stores execution errors in the `ExecutionErrorInfo` database table. If you want to clean up the table and remove errors permanently, you can schedule a job with the `org.jbpm.executor.commands.ExecutionErrorCleanupCommand` command.

The command deletes execution errors that are associated with completed or aborted process instances.

.Procedure

. In {CENTRAL}, select *Menu* -> *Manage* -> *Jobs*.
. In the top right of the screen, click *New Job*.
. Type any identifier for the job into the *Business Key* field.
. In the *Type* field, enter `org.jbpm.executor.commands.ExecutionErrorCleanupCommand`.
. Select a *Due On* time for the job to be completed:
** To run the job immediately, select the `Run now` option.
** To run the job at a specific time, select `Run later`. A date and time field appears next to the `Run later` option. Click the field to open the calendar and schedule a specific time and date for the job.
. Click the *Advanced* tab.
. Add any of the following parameters as necessary:
* `DateFormat`: The format for dates in parameters. If not set, `yyyy-MM-dd` is used, as in the pattern of the `SimpleDateFormat` class.
* `EmfName`: Name of the custom entity manager factory to be used for queries.
* `SingleRun`: Schedules the job for a single execution. If set to `true`, the job runs once and is not scheduled for repeated execution.
* `NextRun`: Schedules the job for repeated execution in a time period. The value must be a valid time expression, for example, `1d`, `5h`, `10m`.
* `OlderThan`: Deletes only errors that are older than a set date. The value must be a date.
* `OlderThanPeriod`: Deletes only errors that are older than a given time period, compared to the current time. The value must be a valid time expression, for example, `1d`, `5h`, `10m`.
* `ForProcess`: Deletes only errors that are related to a process definition. The value must be the identifier of the process definiton.
* `ForProcessInstance`: Deletes only errors that are related to a process instance. The value must be the identifier of the process instance.
* `ForDeployment`: Deletes only errors that are related to a deployment identifier. The value must be the deployment identifier.
