[id='manage-execution-errors-proc-{context}']
= Managing execution errors

By definition, every process error that is detected and stored is unacknowledged and must be handled by someone or something (in case of automatic error recovery). You can view a filtered list of errors that were or were not acknowledged. Acknowledging an error saves the user information and time stamp for traceability.

.Procedure
. In {CENTRAL}, select *Menu* -> *Manage* -> *Execution Errors*.
. Select an error from the list to open the *Details* tab. The *Details* tab displays information about the error or errors.
. Click the *Acknowledge* button to acknowledge the error. You can view acknowledged errors later by selecting *Yes* on the *Acknowledged* filter in the *Manage Execution Errors* page.
+
If the error is related to a task, a *Go to Task* button is displayed.
. Optional: Click the *Go to Task* button, if applicable, to view the associated job information in the *Manage Tasks* page.
+
In the *Manage Tasks* page, you can restart, reschedule, or retry the corresponding task.
