[id='case-management-close-case-proc-{context}']
= Closing a case in the Showcase application

A case instance is complete when no more activities need to be performed and the business goal has been achieved. After a case is complete, you can close the case to indicate that the case is complete and that no further work is required. When you close a case, consider adding a specific comment about why you are closing the case. If needed, you can reopen the case later with the same case ID.

You can use the Showcase application to close a case instance at any time. From Showcase, you can easily view the details of the case or leave a comment before closing it.

.Prerequisites
* You are logged in to the Showcase application and are the owner or administrator for a case instance that you want to close.

.Procedure
. In the Showcase application, locate the case instance you want to close from the list of case instances.
. To close the case without viewing the details first, click *Close*.
. To close the case from the case details page, click the case in the list to open it.
+
From the case overview page you can add comments to the case and verify that you are closing the correct case based on the case information.
. Click *Close* to close the case.
. Click *Back to Case List* in the upper-left corner of the page to return to the Showcase case list view.
. Click the drop-down list next to *Status* and select *Canceled* to view the list of closed and canceled cases.
