[id='assembly_custom-tasks-and-work-item-handlers']

include::_artifacts/document-attributes.adoc[]

= Custom tasks and work item handlers in {CENTRAL}
// Context attribute is assembly specific and enables module reuse between assemblies.
:doctype: book
:imagesdir: _images
:context: custom-tasks
include::_artifacts/author-group.adoc[]

// Purpose statement for the assembly
As a business rules developer, you can create custom tasks and work item handlers in {CENTRAL} to execute custom code within your process flows and extend the operations available for use in {PRODUCT}. You can use custom tasks to develop operations that {PRODUCT} does not directly provide and include them in process diagrams.

In {CENTRAL}, each task in a process diagram has a `WorkItem` Java class with an associated `WorkItemHandler` Java class. The work item handler contains Java code registered with {CENTRAL} and implements `org.kie.api.runtime.process.WorkItemHandler`.

The Java code of the work item handler is executed when the task is triggered. You can customize and register a work item handler to execute your own Java code in custom tasks.

.Prerequisites
* {CENTRAL} is deployed and is running on a web or application server.
* You are logged in to {CENTRAL}.
* Maven is installed.
* The host has access to the Internet. The build process uses the Internet for downloading Maven packages from external repositories.
* Your system has access to the Red Hat Maven repository either locally or online

include::{enterprise-dir}/admin-and-config/manage-service-tasks-proc.adoc[leveloffset=+1]

include::{enterprise-dir}/admin-and-config/custom-tasks-creating-work-item-handler-projects-proc.adoc[leveloffset=+1]

include::{enterprise-dir}/admin-and-config/custom-tasks-work-item-handler-project-customization-con.adoc[leveloffset=+1]

include::{enterprise-dir}/admin-and-config/custom-tasks-work-item-definitions-con.adoc[leveloffset=+1]

include::{enterprise-dir}/admin-and-config/custom-tasks-deploying-custom-tasks-proc.adoc[leveloffset=+1]

include::{enterprise-dir}/admin-and-config/custom-tasks-registering-custom-tasks-proc.adoc[leveloffset=+1]

include::{enterprise-dir}/admin-and-config/custom-tasks-placing-custom-tasks-proc.adoc[leveloffset=+1]

// Versioning info
include::_artifacts/versioning-information.adoc[]
