[[_jbpmgettingstarted]]
= Getting Started

If you would like to take a quick tutorial that will guide you through most of the components using a simple example, take a look at the
<<_jbpminstaller,Installer Chapter>>.
This will teach you how to download and use the installer to create a demo setup, including most of the components.
It uses a simple example to guide you through the most important features.
Screencasts are available to help you out as well.

If you like to read more information first, the following chapters first focus on the core engine (API, BPMN 2.0, etc.).
Further chapters will then describe the other components and other more complex topics like domain-specific processes,
flexible processes, etc. After reading the core chapters, you should be able to jump to other chapters that you might find interesting.

You can also start playing around with some examples that are offered in a separate download.
Check out the <<JBPMExamples,Examples chapter>> to see how to start playing with these.

After reading through these chapters, you should be ready to start creating your own processes and integrate the engine with your application.
These processes can be started from the installer or be started from scratch.

include::GettingStarted/Downloads-section.adoc[leveloffset=+1]
include::GettingStarted/Community-section.adoc[leveloffset=+1]
include::GettingStarted/Sources-section.adoc[leveloffset=+1]
include::{shared-dir}/GettingInvolved-section.adoc[leveloffset=+1]
include::GettingStarted/Questions-section.adoc[leveloffset=+1]

