// IMPORTANT: For 1.10 and later, save each version release notes as its own module file in the release-notes folder that this `ReleaseNotesKogito<version>.adoc` file is in, and then include each version release notes file in the chap-kogito-release-notes.adoc after Additional resources of {PRODUCT} deployment on {OPENSHIFT} section, in the following format:
//include::release-notes/ReleaseNotesKogito<version>.adoc[leveloffset=+1]

[id="ref-kogito-rn-new-features-1.17_{context}"]
= New features in {PRODUCT} 1.17

[role="_abstract"]
The following sections describe some of the new features or enhancements in {PRODUCT} 1.17.

== {PRODUCT} runtimes

=== Ability to use PostgreSQL persistence using 'with-console' example applications

You can now use https://github.com/kiegroup/kogito-examples/tree/main/kogito-quarkus-examples/process-usertasks-quarkus-with-console[process-usertasks-quarkus-with-console] and https://github.com/kiegroup/kogito-examples/tree/main/kogito-quarkus-examples/process-usertasks-timer-quarkus-with-console[process-usertasks-timer-quarkus-with-console] example applications to use Infinispan or PostgreSQL persistence and to see {PRODUCT} Management and Task consoles, {PRODUCT} Data Index, and {PRODUCT} Jobs services.

=== Support for Oracle Database for {PRODUCT} services

You can now use Oracle Database for your {PRODUCT} services. Oracle is added as a new kind of persistence and can be configured to interact with the {PRODUCT} Data Index Service.

=== Runtime support for DMN Specification v1.4

Starting from {PRODUCT} 1.16.0, runtime support for DMN Specification v1.4 in the Drools DMN Engine is available.

== {PRODUCT} Operator and CLI

=== Improved/new bla bla

Description

== {PRODUCT} supporting services

=== Improved/new bla bla

Description

== {PRODUCT} tooling

=== Improved/new bla bla

Description
