[id='drools-ecj']

== Descope Eclipse Java Compiler

The {DECISION_ENGINE} relies on the in-memory compilation to generate the Java sources automatically. When it comes to the executable rule model, the automatic generation of Java sources has become more relevant. The {DECISION_ENGINE} used to perform the in-memory compilation using Eclipse Java Compiler (default) or using the compiler provided by the JDK since Java 7.

To better modularize the {DECISION_ENGINE} and descope the optional features, the Eclipse Java Compiler and its specific implementation code is moved to an individual module named `drools-ecj`. The new module `drools-ecj` is not available in the class path and the {DECISION_ENGINE} performs all the required in-memory compilation using the native Java compiler. When the `drools-ecj` is added in the class path, then the Eclipse Java Compiler performs as the default compiler without any additional configuration.

A dependency to `drools-ecj` is also added in the `drools-engine-classic` module, which maintains all legacy functions of the {DECISION_ENGINE}.
