[id='drools-ecj']

== Descope Eclipse Java Compiler

The {DECISION_ENGINE} relies on the in-memory compilation to generate the Java sources automatically. When it comes to the executable rule model, the automatic generation of Java sources has become more relevant. The {DECISION_ENGINE} used to perform the in-memory compilation using Eclipse Java Compiler (default) or using the compiler provided by the JDK since Java 7.

To better modularize the {DECISION_ENGINE} and descope the optional features, the Eclipse Java Compiler and its specific implementation code is moved to an individual module named `drools-ecj`. By default, the `drools-compiler` module is dependent on the `drools-ecj` module to make the {DECISION_ENGINE} backward compatible. However, the {DECISION_ENGINE} can also work without this dependency.  Excluding the `drools-ecj` module from the class path, enables the {DECISION_ENGINE} to automatically switch to the native Java compiler and perform all the required in-memory compilation.

The reason to keep the Eclipse Java Compiler as a default compiler is that the compiler provided by the JDK is slower and does not perform well in a modularized environment, such as OSGi or JBoss modules. 
