[[_chap_about_this_guide]]
= About This Guide

This guide is intended for users who are implementing a standalone Red Hat JBoss BRMS solution or the complete Red Hat JBoss BPM Suite solution. It discusses the following topics:

* Detailed Architecture of Red Hat JBoss BRMS and Red Hat JBoss BPM Suite.
* Detailed description of how to author, test, debug, and package simple and complex business rules and processes using Integrated Development environment (IDE).
* Red Hat JBoss BRMS runtime environment.
* Domain specific languages (DSLs) and how to use them in a rule.
* Complex event processing.

This guide comprises the following sections:

. _Overview_
+
This section provides detailed information on Red Hat JBoss BRMS and Red Hat JBoss BPM suite, their architecture, key components. It also discusses the role of Maven in project building and deploying.
. _All About Rules_
+
This section provides details on all you have to know to author rules with Red Hat JBoss Developer Studio. It describes the rule algorithms, rule structure, components, advanced conditions, constraints, commands, Domain Specific Languages and Complex Event Processing. It provides details on how to use the various views, editors, and perspectives that Red Hat JBoss Developer Studio offers.
. _All About Processes_
+
This section describes what comprises a business process and how you can author and test them using Red Hat JBoss Developer Studio.
. _KIE_
+
This section highlights the KIE API with detailed description of how to create, build, deploy, and run KIE projects.
. _Appendix_
+
This section comprises important reference material such as key knowledge terms, and examples.

[[_audience]]
== Audience

This book has been designed to be understood by:

* Author of rules and processes who are responsible for authoring and testing business rules and processes using Red Hat JBoss Developer Studio.
* Java application developers responsible for developing and integrating business rules and processes into Java and Java EE enterprise applications.

[[_prerequisites]]
== Prerequisites

Users of this guide must meet one or more of the following prerequisites:

* Basic Java/Java EE programming experience
* Knowledge of the Eclipse IDE, Maven, and GIT
