[[_chap_case_management]]
= Case Management

WARNING: In {PRODUCT} 7.0, the Case Management API will be completely redesigned.

== Introduction

Business Process Management (BPM) is a management practice for automating tasks that are repeatable and have a common pattern. However, many applications in the real world cannot be described completely from start to finish (including all possible paths, deviations, and exceptions). Moreover, using a process-centric approach in certain cases may lead to complex solutions that are hard to maintain. Sometimes business users need more flexible and adaptive business processes, without the overly complex solutions. In such cases, human actors play an important role in solving complex problems. Case Management is for such tasks collaborative and dynamic tasks that require human actions. Case Management focuses on problem resolution for unpredictable process instances as opposed to the efficiency oriented approach of Business Process Management for routine predictable tasks.

Instead of trying to model a process from start to finish, the Case Management approach supports giving the end user the flexibility to decide what must happen at runtime. In its most extreme form for example, Case Management does not even require any process definition at all. Whenever a new case comes in, the end user can decide what to do next based on all the case data.

This does not necessarily mean that there is no role of BPM in Case Management. Even at its most extreme form where no process is modelled up front, you may still need a lot of the other features that the BPM system provides. For example,  BPM features like audit logs, monitoring, coordinating various services, human interaction (such as using task forms), and analysis play a crucial role in Case Management as well. There can also be cases where a more structured business process evolves from Case Management. Thus, a flexible BPM system enables you to decide how and where you can apply it.

== Use Cases

Here are some common use cases of Case Management:

* Clinical decision support is a great use case for Case Management approach. Care plans are used to describe how patients must be treated in specific circumstances, but people like general practitioners still need to have the flexibility to add additional steps and deviate from the proposed plan, as each case is unique. A care plan with tasks to be performed when a patient who has high blood pressure can be designed with this approach. While a large part of the process is still well-structured, the general practitioner can decide which tasks must be performed as part of the sub-process. The practitioner also has the ability to add new tasks during that period, tasks that were not defined as part of the process, or repeat tasks multiple times. The process uses an ad-hoc sub-process to model this kind of flexibility, possibly augmented with rules or event processing to help in deciding which fragments to execute.
* An internet provider can use this approach to handle internet connectivity cases. Instead of having a set process from start to end, the case worker can choose from a number of actions based on the problem at hand. The case worker is responsible for selecting what to do next and can even add new tasks dynamically.

== Case Management in Red Hat JBoss BPM Suite

Red Hat JBoss BPM Suite provides a new wrapper API called `casemgmt` that focuses on exposing the Case Management concepts. These explain how Case Management can be mapped with the existing constructs inside Red Hat JBoss BPM Suite:

[float]
==== Case Definition

A case definition is a very flexible high level process synonymous to the Ad-Hoc process in Red Hat JBoss BPM Suite. You can define a default empty Ad-Hoc process for maximum flexibility to use when loaded in `RuntimeManager`. For a more complex case definition, you can define an Ad-Hoc process that may include milestones, predefined tasks to be accomplished and case roles to specify the roles of case participants.

[float]
==== Case Instance

In an Ad-Hoc process definition, a case instance is created that allows the involved roles to create new tasks. You can create a new case instance for an empty case as below:

[source,java]
----
ProcessInstance processInstance = caseMgmtService.startNewCase("CaseName");
----

During the start of a new case, the parameter `Case Name` is set as a process variable `name`.

Alternatively, you can create a case instance the same way as new process instance:

[source,java]
----
ProcessInstance processInstance =
  runtimeEngine.getKieSession().startProcess("CaseUserTask", params);
----

[float]
==== Case File

A case file contains all the information required for managing a case. A case file comprises several case file items each representing a piece of information.

[float]
==== Case Context

Case context is the audit and related information about a case execution. A case context can be identified based on the unique case id. The `CaseMgmtUtil` class is used to get active tasks, subprocesses, and  nodes. The `AuditService` class is used to get a list of passed nodes, and anything that is possible to do with processes. And the `getCaseData()` and `setCaseData()` of case file are used to get and set the `dynamic` process variables.

[float]
==== Milestones

You can define milestones in a case definition and track a cases progress at runtime. A number of events can be captured from processes and tasks executions. Based on these events, you can define milestones in a case definition and track a case's progress at runtime. The `getAchievedMilestones()` is used to get all achieved milestones. The task names of milestones must be `Milestone`.

[float]
==== Case Role
You can define roles for a case definition and keep track of which users participate with the case in which role at runtime. Case roles are defined in the case definitions as below:

[source,xml]
----
<extensionElements>
  <tns:metaData name="customCaseRoles">
    <tns:metaValue>
      responsible:1,accountable,consulted,informed
    </tns:metaValue>
  </tns:metaData>
    <tns:metaData name="customDescription">
    <tns:metaValue>
      #{name}
    </tns:metaValue>
    </tns:metaData>
</extensionElements>
----

The number represents the maximum of users in this role. In the example above, only one user is assigned to role responsible. You can add users to case roles as follows:

[source,java]
----
caseMgmtService.addUserToRole(caseId, "responsible", responsiblePerson);
----

The case roles cannot be used as groups for Human Tasks. The Human Task has to be assigned to some user with the case role, hence a user  is selected in the case role based on some heuristics (random):

[source,java]
----
public String getRandomUserInTheRole(long pid, String role) {
  
  String[] users = caseMgmtService.getCaseRoleInstanceNames(pid).get(role);
  Random rand = new Random();
  int n = 0;
  
  if (users.length > 1) {
    n = rand.nextInt(users.length - 1);
  }
  
  return users[n];
}
----

[float]
==== Dynamic Nodes

This involves creating dynamic process task, human task, and case task.

* _Human Task_: The Human Task service inside Red Hat JBoss BPM Suite that implements the WS-HumanTask specification (defined by the OASIS group) already provides this functionality and can be fully integrate with. This service takes care of the task lifecycle and allows you to access the internal task events.
* _Process Task_: You can use normal process definitions and instances to be executed as part of a case by correlating them with the case ID.
* _Case Task_: Just like how you can provide business processes to be executed from another process, you can provide the same feature for executing cases from inside another case.
* _Work Task_: The work task with defined work item handler.
