[id='dev-studio-clone-remote-git-repo-proc']
= Cloning a remote Git repository
You can clone a git repository to use with Red Hat JBoss Developer Studio.

.Procedure
. Select the server from the *Server* tab and click the start icon to start your server.
. Start the Secure Shell server, if not running already, by using the following command. The command is Linux and Mac specific only. On these platforms, if `sshd` has already been started, this command fails. In that case, you may safely ignore this step.
+
[source]
----
/sbin/service sshd start
----
. In Red Hat JBoss Developer Studio , select *File* -> *Import...* and navigate to the Git folder. Open the Git folder to select *Projects from Git* and click *Next*.
. Select the repository source as *Clone URI* and click *Next*.
. Enter the details of the Git repository in the next window and click *Next*.
. Select the branch you wish to import in the following window and click *Next*.
. To define the local storage for this project, enter (or select) a non-empty directory, make any configuration changes and click *Next*.
. Import the project as a general project in the following window and click *Next*.
. Name the project and click *Finish*.
