[id='dev-studio-plug-in-install-proc']
= Installing Red Hat JBoss Developer Studio plug-ins

The Red Hat JBoss Developer Studio plug-ins for {PRODUCT}  are based on the community version of the plug-ins. For this reason, the {PRODUCT} plug-in is called the Drools plug-in.

//Get the latest Red Hat JBoss Developer Studio from the https://access.redhat.com[Red Hat Customer //Portal]. The {PRODUCT} plug-ins for Red Hat JBoss Developer Studio are available using the update site.

.Procedure
. Download the {PRODUCT} plug-ins for Red Hat JBoss Developer Studio:
.. Log in to the https://access.redhat.com[Red Hat Customer Portal].
.. Click *DOWNLOADS* at the top of the page.
.. On the *Product Downloads* page that opens, navigate to the JBOSS DEVELOPMENT AND MANAGEMENT section, and click *Red Hat JBoss Developer Studio*.
.. On the *Software Downloads* page, download *Red Hat JBoss Developer Studio Integration Stack 11.3.0 Update Site Zip* (`devstudio-integration-stack-11.3.0.GA-updatesite.zip`).
//. Unzip the `devstudio-11.3.0.GA-updatesite-core.zip` file.
. Start Red Hat JBoss Developer Studio by selecting *Red Hat JBoss Developer Studio* from the Start menu.
. Click *Help* -> *Install New Software*.
. Click *Add* to display the *Add Repository* box.
. Enter a name in the *Name* field, for example, `devstudio-11.3.0.GA`.
. Click *Archive*, select the `devstudio-11.3.0.GA-updatesite-core.zip` file, and click *OK*.
//+
//`https://devstudio.jboss.com/11/stable/updates/integration-stack`
. In the Install window, select *JBoss Business Process and Rule Development* from the list, click *Next*, and then click *Next* again.
. Read the license agreement, accept it, and click *Finish*.
. Restart Red Hat JBoss Developer Studio after the installation process finishes.
