[id='dev-studio-plug-in-install-proc']
== Installing Red Hat JBoss Developer Studio plug-ins

Red Hat JBoss Developer Studio provides plug-ins with tools and interfaces for Red Hat Red Hat Decision Manager. These plugins are based on the community version of these products. For this reason, the Red Hat Decision Manager plug-in is called the Drools plug-in.

Get the latest Red Hat JBoss Developer Studio from the https://access.redhat.com[Red Hat Customer Portal]. The Red Hat JBoss BRMS and Red Hat JBoss BPM Suite plug-ins for Red Hat JBoss Developer Studio are available using the update site.

.Installing Red Hat JBoss BRMS and Red Hat JBoss BPM Suite Plug-ins in Red Hat JBoss Developer Studio
. Start Red Hat JBoss Developer Studio.
. Click *Help* -> *Install New Software*.
. Click *Add* to enter the *Add Repository* menu.
. Provide a name next to the *Name* field and add the following URL in the *Location* field: `https://devstudio.jboss.com/11/stable/updates/integration-stack/`.
. Click *OK*.
. Select the *JBoss Business Process and Rule Development* feature from the available options, click *Next* and then *Next* again.
. Read the license and accept it by selecting the appropriate radio button, and click *Finish*.
. Restart Red Hat JBoss Developer Studio after the installation process finishes.
