[id='dm-server-configure-proc']
= Configuring the {PRODUCT} server

You can configure Red Hat JBoss Developer Studio to run the {PRODUCT} server.

.Prerequisite
* Red Hat JBoss Developer Studio
* {Product} install with the Red Hat JBoss Developer Studio plug-ins

.Procedure
. To open the Drools view, click *Window* -> *Open Perspective* -> *Other*, select *Drools*, select specific views, and click *OK*.
. Click *Window* -> *Show View* -> *Other...* and select *Server* -> *Servers* to add the server view.
. Right click the *Servers* panel and select *New* -> *Server* to open the server menu.
. Click *JBoss Enterprise Middleware* -> *JBoss Enterprise Application Platform 7.1+* and click *Next* to define the server.
. Set the home directory by clicking the *Browse* button. Navigate to the{EAP} directory where {PRODUCT} is installed.
+
To configure the {PRODUCT} server, select the {EAP} directory where {PRODUCT} is installed.
. Provide a name for the server in the *Name* field, ensure that the configuration file is set, and click *Finish*.
