[id='maven-repo-using-proc']

= Setting Maven dependencies in your project

{PRODUCT} projects are designed to be used with a {PRODUCT} Maven repository, available online or downloaded from the Red Hat Customer Portal. When you create a project, {CENTRAL} uses the Maven repositories that are configured for {CENTRAL}. However, you can use the Maven global or user settings dto direct all {PRODUCT} projects to retrieve dependencies from the public {PRODUCT} repository by modifying the following files:

* The Maven `settings.xml` file. This file is included with the Maven repository available for download from the Red Hat Customer Portal. 
* The Maven Project Object Model (POM) file (`pom.xml`).

The URL for the online {PRODUCT} Maven repository is `https://maven.repository.redhat.com/ga/`. 

Complete the steps in the following procedure to download the {PRODUCT} Maven repository.

.Procedure
. Log in to the https://access.redhat.com[Red Hat Customer Portal].
. Click *DOWNLOADS* at the top of the page.
. On the *Product Downloads* page that opens, navigate to the JBOSS INTEGRATION AND AUTOMATION section, and click *{PRODUCT}*.
. On the *Software Downloads* page, download *Red Had Process Automation Manager 7.0.0 Maven Repository* (`rhpam-7.0.0.Beta02-maven-repository.zip`).

For more information about Maven repositories, see the https://maven.apache.org/[Apache Maven Project] documentation.



