[id='maven-managing-dependencies-proc']
= Configure the Maven POM file
To use the correct Maven dependencies in your {PRODUCT} project, you must add relevant bill of materials (BOM) files to the project's `pom.xml` file. When you add the BOM files, the correct versions of transitive dependencies from the provided Maven repositories are included in the project.

For more information, see https://access.redhat.com/solutions/3405361[What is the mapping between RHPAM product and maven library version?].

.Procedure

. Declare the BOM in the `pom.xml` file. For example:
+
====
[source,xml]
----
<dependencyManagement>
 <dependencies>
  <dependency>
   <groupId>org.jboss.bom.rhpam</groupId>
   <artifactId>rhpam-platform-bom</artifactId>
   <version>7.0.0.Final-redhat-3</version>
//comment: check before release
   <type>pom</type>
   <scope>import</scope>
  </dependency>
 </dependencies>
</dependencyManagement>
<dependencies>
<!-- Your dependencies -->
</dependencies>
----
====
+


. Declare dependencies needed for your project in the `<dependencies>` tag.

* For a basic {PRODUCT_PAM} project, declare the following dependencies:
+
[id='_embedded_jbpm_engine_dependencies']
.Embedded jBPM Engine Dependencies
[source,xml]
----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-kie-services</artifactId>
</dependency>

<!-- Dependency needed for default WorkItemHandler implementations. -->
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-core</artifactId>
</dependency>

<!-- Logging dependency. You can use any logging framework compatible with slf4j. -->
<dependency>
  <groupId>ch.qos.logback</groupId>
  <artifactId>logback-classic</artifactId>
  <version>${logback.version}</version>
</dependency>

<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-api</artifactId>
</dependency>
----

* For a {PRODUCT_PAM} project that uses CDI, declare the following dependencies:
+
[id='_cdi_enabled_jbpm_engine_dependencies']
.CDI-Enabled jBPM Engine dependencies 
[source,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-api</artifactId>
</dependency>

<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-kie-services</artifactId>
</dependency>

<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-services-cdi</artifactId>
</dependency>
----

* For a basic {PRODUCT_DM} project, declare the following dependencies:
+
[id='_embedded_drools_engine_dependencies']
.Embedded Drools Engine Dependencies
[source,xml]
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-compiler</artifactId>
</dependency>

<!-- Dependency for persistence support. -->
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-persistence-jpa</artifactId>
</dependency>

<!-- Dependencies for decision tables, templates, and scorecards.
For other assets, declare org.drools:drools-workbench-models-* dependencies. -->
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-decisiontables</artifactId>
</dependency>
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-templates</artifactId>
</dependency>
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-scorecards</artifactId>
</dependency>

<!-- Dependency for loading KJARs from a Maven repository using KieScanner. -->
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-ci</artifactId>
</dependency>

----
+
* To use the {KIE_SERVER}, declare the following dependencies:
+
[id='_client_application_intelligent_process_server_dependencies']
.Client Application {KIE_SERVER} Dependencies
[source,xml]
----
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-client</artifactId>
</dependency>
<dependency>
    <groupId>org.kie.server</groupId>
    <artifactId>kie-server-api</artifactId>
</dependency>

<!-- Dependency for Red Hat JBoss BRMS functionality. -->
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-core</artifactId>
</dependency>

<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-api</artifactId>
</dependency>
----

* To create a remote client for {PRODUCT_PAM} or {PRODUCT_DM}, declare the following dependencies:
+
.Client Dependencies
[source,xml]
----
<dependency>
  <groupId>org.uberfire</groupId>
  <artifactId>uberfire-rest-client</artifactId>
</dependency>
----
+
. When creating a JAR file that includes assets, for example rules and process definitions, specify the packaging type for your Maven project as `kjar` and use `org.kie:kie-maven-plugin` to process the `kjar` packaging type. In the following example, `${kie.version}` is the Maven library version listed in https://access.redhat.com/solutions/3405361[What is the mapping between RHPAM product and maven library version?]:
+
[source,xml]
----

<packaging>kjar</packaging>
<build>
 <plugins>
  <plugin>
   <groupId>org.kie</groupId>
   <artifactId>kie-maven-plugin</artifactId>
   <version>${kie.version}</version>
   <extensions>true</extensions>
  </plugin>
 </plugins>
</build>
----





