[id='rest-api-repository-calls-ref_{context}']
= Repository Calls

Repository calls are calls to the Knowledge Store that allow you to manage its Git repositories and their projects.

The following repository calls are provided:

[GET] /repositories::
Returns a list of repositories in the Knowledge Store.

ifdef::PAM[]
+
.Response of Repository Call
====
[source]
----
[
  {
    "name": "bpms-assets",
    "description": "generic assets",
    "userName": null,
    "password": null,
    "requestType": null,
    "gitURL": "git://bpms-assets"
  },
  {
    "name": "loanProject",
    "description": "Loan processes and rules",
    "userName": null,
    "password": null,
    "requestType": null,
    "gitURL": "git://loansProject"
  }
]
----
====
endif::PAM[]


ifdef::DM[]
+
.Response of Repository Call
====
[source]
----
[
  {
    "name": "bpms-assets",
    "description": "generic assets",
    "userName": null,
    "password": null,
    "requestType": null,
    "gitURL": "git://brms-assets"
  },
  {
    "name": "loanProject",
    "description": "Loan processes and rules",
    "userName": null,
    "password": null,
    "requestType": null,
    "gitURL": "git://loansProject"
  }
]
----
====
endif::DM[]

[GET] /repositories/_REPOSITORY_NAME_::
Returns information about a specific repository.

[DELETE] /repositories/_REPOSITORY_NAME_::
Removes a repository.

[POST] /repositories/::
Creates or clones a repository defined by a JSON entity.
+
--
.JSON Entity with Details about Repository to Be Cloned
====
[source]
----
{
  "name": "myClonedRepository",
  "organizationalUnitName": "example",
  "description": "",
  "userName": "",
  "password": "",
  "requestType": "clone",
  "gitURL": "git://localhost/example-repository"
}
----
====

.JSON Entity with Details about Repository to Be Created
====
[source]
----
{
  "name": "myCreatedRepository",
  "organizationalUnitName": "example",
  "description": "",
  "userName": "",
  "password": "",
  "requestType": "create",
  "gitURL": "git://localhost/example-repository"
}
----
====

[IMPORTANT]
====
Make sure you always include the `organizationalUnitName` key-value pair in your query and that the specified organization unit exists before you create or clone the repository.
====
--

[GET] /repositories/_REPOSITORY_NAME_/projects/::
Returns a list of projects in a specific repository as a JSON entity.
+
.JSON Entity with Details about Existing Projects
====
[source]
----
[ {
  "name" : "my-project-name",
  "description" : "A project to illustrate a REST output.",
  "groupId" : "com.acme",
  "version" : "1.0"
}, {
  "name" : "yet-another-project-name",
  "description" : "Yet another project to illustrate a REST output.",
  "groupId" : "com.acme",
  "version" : "2.2.1"
} ]
----
====

[POST] /repositories/_REPOSITORY_NAME_/projects/::
Creates a project in a repository.
+
.Request Body That Defines Project to Be Created
====
[source]
----
{
  "name" : "NewProject",
  "description" : "Description of the new project.",
  "groupId" : "org.redhat.test",
  "version" : "1.0.0"
}
----
====

[DELETE] /repositories/_REPOSITORY_NAME_/projects/_PROJECT_NAME_::
Removes a project in a repository.