[id='security-management-sec-provider.adoc']
= Security Provider

A security environment is usually provided by the use of a realm. Realms are used to restrict access to the different application’s resources. Realms contains information about the users, groups, roles, permissions and any other related information.

Typically, application security is delegated to the container security mechanism, which consumes a particular realm at same time. It is important to consider that  several realm implementations exist. For example Wildfly provides a realm based on the `application-users.properties/application-roles.properties` files, Tomcat provides a realm based on the `tomcat-users.xml` file, and so on.  The security realm can be different for each installation.

Because of the potential for different security realms that must be supported, the security module provides a well defined API with some default built-in security providers. For more information about the security API, see the Uberfire http://uberfireframework.org/docs/security/authorizationAPI.html[Authorization API Management] page.

A security provider is the formal name given to a concrete user and group management service implementation for a specific realm. The user and group management features available will depend on the configured security provider. If the built-in providers do not provide the structure that you require for your application’s security realm, you can  build and register your own provider.