[id='security-management-war-enabling']
= Enabling Security Management Features in a WAR Distribution

This section describes how to enable the security management features in an existing WAR distribution.

.Procedure
. Ensure that the following libraries are present in WEB-INF/lib:
+
* WEB-INF/lib/uberfire-security-management-api-<version>.jar
* WEB-INF/lib/uberfire-security-management-backend-<version>.jar
. Copy the the security provider library to WEB-INF/lib for example:
----
WEB-INF/lib/uberfire-security-management-wildfly-?.jar
----
If the provider requires additional libraries, copy them as well (read each provider’s documentation for more information).
Replace the entire contents of the WEB-INF/classes/security-management.properties file, or if not present, create it. The settings present on this file depend on the concrete implementation used. Please read each provider’s documentation for more information.
COMMENT: Replace with what?
If deploying on Wildfly or EAP, check if the WEB-INF/jboss-deployment-structure.xml file requires any update (read each provider’s documentation for more information).
COMMENT: The provider’s documenation link just goes to the Uberfire doc repo.
