[id='kieserver-upgrade-proc']
= Upgrading a {KIE_SERVER}

You can upgrade a BRMS 6.4 KIE Server to {PRODUCT} {PRODUCT_VERSION} {KIE_SERVER} by installing the new server on the same host. You can use existing KJAR files. However, for optimal performance, upgrade and rebuild the projects.

.Procedure
. Install {PRODUCT} {PRODUCT_VERSION} {KIE_SERVER} on the same host as a BRMS 6.4 KIE Server. Use a separate JBoss EAP installation. For instructions, see {URL_INSTALLING_DM_ON_PREMISE}[{INSTALLING_DM_ON_PREMISE}].
. Configure the {PRODUCT} {PRODUCT_VERSION} {KIE_SERVER} to bind to the same port as the BRMS 6.4 KIE Server. (The default settings are the same).
. Configure the {KIE_SERVER} to use a Maven repository that contains your decision services (KJAR files). Use one of the following approaches:
+
--
* Use the same KJAR files as of the BRMS 6.4 KIE Server. To copy the Maven configuration, copy the value of the `kie.maven.settings.custom` system property from the old version `$EAP_home/standalone/configuration/standalone.xml` file to the same file in the new version.  
* Upgrade your decision services to the new version. For instructions, see <<projects-central-migrating-proc>> and <<projects-java-migrating-proc>>. Upload the new KJAR files to a Maven repository. Then configure the {KIE_SERVER} to use the repository:
--
+
.. Create a `settings.xml` file for the Maven repository
.. In the `$EAP_home/standalone/configuration/standalone.xml` file for {PRODUCT} {PRODUCT_VERSION} {KIE_SERVER}, under the `<system-properties>` tag, set the `kie.maven.settings.custom property` to the full pathname of the `settings.xml` file, for example:
+
[source,xml]
----
<property name="kie.maven.settings.custom" value="/opt/custom-config/settings.xml"/>
----
+
In this case, you need to change the version of the KJAR files. Change the version of the services that you start accordingly. You can still use the same container name to ensure maximum compatibility with existing clients. 
. Stop the BRMS 6.4 KIE Server.
. Start the {PRODUCT} {PRODUCT_VERSION} {KIE_SERVER}.
. Use the API to start the necessary decision services. For instructions, see {URL_PACKAGING_DEPLOYING_DECISION_SERVICE}[{PACKAGING_DEPLOYING_DECISION_SERVICE}].

.Result
The {PRODUCT} {PRODUCT_VERSION} {KIE_SERVER} operates on the same URLs and provides the same services as the BRMS 6.4 KIE Server. 

You might need to change client applications that use the REST API in order to adapt to the following API change:

* The ServiceResponse wrapper was removed from the Planner service responses.

IMPORTANT: You can also configure the {KIE_SERVER} to connect to a {CENTRAL}. The {CENTRAL} can manage several {KIE_SERVERS} and deploy the same or different decision services on them. For instructions, see {URL_PACKAGING_DEPLOYING_DECISION_SERVICE}[{PACKAGING_DEPLOYING_DECISION_SERVICE}].
 