[id='migration-overview-con']
= Migration overview

ifdef::DM[]
If you use {PRODUCT_OLD} version 6.4 and install {PRODUCT} version {PRODUCT_VERSION}, you need to migrate the applications that you created (now called _decision services_) and possibly your server environment to the new product. Red Hat provides migration and upgrade tools wherever possible to facilitate migration.

The following are the main changes in {PRODUCT} {PRODUCT_VERSION} that affect product migration:

* *New repository structure for {CENTRAL} project data:* Decision services that you created in {CENTRAL} with {PRODUCT_OLD} 6.4 must be migrated using the {CENTRAL} migration tool provided with this release to accommodate a new data structure. Project data is restructured in {PRODUCT} {PRODUCT_VERSION} so that each space (previously organizational unit) contains repositories that correspond to individual projects, instead of multiple projects in a single repository as in {PRODUCT_OLD} 6.4. This improved structure means that you do not need to create and manage repositories in the new {CENTRAL} and can focus on developing decision services.
* *Upgraded database schema:* {PRODUCT} {PRODUCT_VERSION} contains updates to the database schema for optimal performance with the new {CENTRAL} and {KIE_SERVER}. The database configured for {PRODUCT_OLD} 6.4 must be updated using one of the upgrade scripts provided with this release to accommodate the change.

As a result of these changes, migration paths are available for {CENTRAL} distributions and for environments with Java projects moving to {PRODUCT} {PRODUCT_VERSION}.
endif::DM[]

ifdef::BA[]
If you use {PRODUCT_OLD} version 6.4 and install {PRODUCT} version {PRODUCT_VERSION}, you need to migrate the applications that you created (now called _decision services_) and possibly your server environment to the new product. Red Hat provides migration and upgrade tools wherever possible to facilitate migration, but in some cases, manual migration or asset re-creation is required.

The following are the main changes in {PRODUCT} {PRODUCT_VERSION} that affect product migration:

* *New repository structure for {CENTRAL} project data:* Decision services that you created in {CENTRAL} with {PRODUCT_OLD} 6.4 must be migrated using the {CENTRAL} migration tool provided with this release to accommodate a new data structure. Project data is restructured in {PRODUCT} {PRODUCT_VERSION} so that each space (previously organizational unit) contains repositories that correspond to individual projects, instead of multiple projects in a single repository as in {PRODUCT_OLD} 6.4. This improved structure means that you do not need to create and manage repositories in the new {CENTRAL} and can focus on developing decision services.
* *No execution server capabilities in {CENTRAL}:* In {PRODUCT} {PRODUCT_VERSION}, {CENTRAL} no longer has execution server capabilities nor any remote Java API endpoints. Instead, the {KIE_SERVER} performs all execution and runtime functions and {CENTRAL} is used for application development and management only. Therefore, any {CENTRAL} environments that are currently used as an execution server must be migrated to the new {CENTRAL} and {KIE_SERVER} environments to retain live tasks and process instances in {PRODUCT} {PRODUCT_VERSION}. If any remote client applications use the remote Java API to interact with the {CENTRAL} execution server, these API references must be redirected to the {KIE_SERVER} API.
* *Upgraded database schema:* {PRODUCT} {PRODUCT_VERSION} contains updates to the database schema for optimal performance with the new {CENTRAL} and {KIE_SERVER}. The database configured for {PRODUCT_OLD} 6.4 must be updated using one of the upgrade scripts provided with this release to accommodate the change.

As a result of these changes, the following migration paths are available, depending on your {PRODUCT_OLD} 6.4 environment:

* Migrating to {PRODUCT} {PRODUCT_VERSION} when {CENTRAL} is not execution server
* Migrating to {PRODUCT} {PRODUCT_VERSION} when {CENTRAL} is execution server
* Migrating to {PRODUCT} {PRODUCT_VERSION} when {CENTRAL} is not used at all (Java projects)
endif::BA[]

IMPORTANT: If you are using a version of {PRODUCT_OLD} older than 6.4, migrate your projects to version 6.4 before migrating to 7.0. For migration instructions, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_bpm_suite/6.4/html-single/migration_guide/index[Red Hat JBoss BPM Suite 6.4 Migration Guide]

For more information about updates and new features in this release, see the Release notes for {PRODUCT} {PRODUCT_VERSION}.
//@link: Add link to BA 7 release notes.
