[id='_chap_roles_and_users']
= Roles and Users

[id='_defining_roles']
== Defining Roles

Before starting the server and logging onto Business Central, you will need to create some user accounts. This section describes the different user roles that are used in {PRODUCT}:

* `admin`: The users with `admin` role are the administrators of the application. Administrators can manage users, manage the repositories (create and clone), and have full access to make the required changes in the application. Admins have access to all areas within the system.
ifdef::PAM[]
* `developer`: A developer has access to almost all features and can manage rules, models, process flows, forms, and dashboards. They can manage the asset repository, they can create, build and deploy projects and they can even use Red&nbsp;Hat JBoss&nbsp;Developer&nbsp;Studio to view processes. Only certain administrative functions like creating and cloning a new repository are hidden for the developer role.
endif::PAM[]
* `analyst`: An `analyst` role has access to all high-level features to model
ifdef::PAM[]
and execute their
endif::PAM[]
projects. However, *Authoring* -> *Administration* access is unavailable to users with the `analyst` role. Certain lower-level features targeted towards developers, like the *Deployment* -> *Artifact Repository* view are not accessible for this role. However, the *Build & Deploy* button is available for the analyst role while using the Project Editor.
ifdef::PAM[]
* `user`: User or a business user work on the business task lists that are used to operate a certain process. A user with this role can access the dashboard and manage processes.
* `manager`: A manager is a viewer of the system and is interested in statistics around the business processes and their performance, business indicators, and other reporting of the system. A user with this role has access to the BAM only.
endif::PAM[]

NOTE: Enter the above mentioned roles during the user creation process.

[id='_creating_the_users']
== Creating Users

To start adding new users, you will need to run the `add-user.sh` script on a Unix system or the `add-user.bat` file on a Windows system from the EAP `bin` directory.

.Procedure: Creating New Users
. Go to the EAP `bin` directory.
. On a Unix system, run the following command:
+
----
./add-user.sh
----
+
On a Windows system, run:
+
----
./add-user.bat
----
. Enter `b` to select the application user and press *Enter*.
. Accept the default realm (ApplicationRealm) by pressing *Enter*.
. At the user name prompt, enter the user name and confirm. For example: `helloworlduser`.
+
[IMPORTANT]
====
Make sure that the selected user name does _not_ conflict with any known title of a role or a group.

For example, if there is a role called `admin`, you should _not_ create a user with the user name `admin`.
====
. Create the user password at the password prompt and reenter the password. For example: `Helloworld@123`.
+
[NOTE]
====
The password should be at least 8 characters in length and should contain upper and lower case alphabetic characters (A-Z, a-z), at least one numerical character (0-9) and at least one special character (for example ~ ! @ # $ % ^ * ( ) - _ + =).
====
. Enter a comma-separated list of roles the user will need at the roles prompt (see <<_defining_roles>>).
+
ifdef::PAM[]
Note that Business Central users need to have at least the `analyst` role, while the Dashboard Builder users need to have the `admin` role assigned. Roles should be entered as a comma-separated list.
endif::PAM[]
ifdef::DM[]
Note that Business Central users need to have the `analyst` or the `admin` role assigned.
endif::DM[]
. Confirm that you want to add the user.
. Enter `yes` at the next prompt to enable clustering in the future.
