[#assembly_installing_on_eap]
= {PRODUCT} on EAP

Red Hat JBoss Enterprise Application Platform 7.0 (JBoss EAP 7) is a certified implementation of the Java Enterprise Edition 7 (Java EE 7) Full and Web profile specifications. JBoss EAP provides preconfigured options for features such as high-availability clustering, messaging, and distributed caching. It also enables users to write, deploy, and run applications using the various APIs and services that JBoss EAP provides.

Unlike previous versions of {PRODUCT}, the installation of version {PRODUCT_VERSION} {RELEASE} on EAP consists of multiple deployable ZIP files, each for one component of the product, to provide additional flexibility.

For information on how to install {EAP} 7.0.7 on your computer, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html-single/installation_guide/[{EAP} Installation Guide].

include::eap-business-central-install-proc.adoc[leveloffset=+1]

include::eap-execution-server-download-install-proc.adoc[leveloffset=+1]
NOTE: This section describes configuring Business Central and the Execution Server in the same container. In production environments, they are usually run in different containers.

include::eap-users-create-proc.adoc[leveloffset=+1]
include::eap-execution-server-configure-proc.adoc[leveloffset=+1]
include::eap-bxms-run-proc.adoc[leveloffset=+1]

