[id='ba-dm-supported-platforms-ref']
= Supported platforms 

You can install {PRODUCT} on different combinations of servers, as listed in this section. In development environments, {CENTRAL} and {KIE_SERVER} are often installed on the same server. However, Red Hat recommends that in production environments you install {CENTRAL} and {KIE_SERVER} on different servers.

The instructions in this document explain how to install {PRODUCT} on {EAP} 7.1 and Red Hat JBoss Web Server 3.1 with Tomcat 8 on premise. For information about installing on the Red Hat OpenShift Container Platform, see {URL_DM_ON_OPENSHIFT}[_{deploying_red_hat_decision_manager_on_red_hat_openshift_container_platform}_]

{PRODUCT} {PRODUCT_VERSION} is supported on the following platforms:

[width="40%",frame="topbot",options="header"]
|====
| Operating system   | Application Container                                | Version
| RHEL 7             | {EAP_LONG} (EAP)                                     | 7.1.0
| RHEL 7             | Red Hat OpenShift Container Platform                 | 3.6


|====

{KIE_SERVER} {PRODUCT_VERSION} is supported on the following platforms:

[width="40%",frame="topbot",options="header"]
|====
| Operating system   | Application Container                                | Version
| RHEL 7             | {EAP_LONG} (EAP)                                     | 7.1.0
|     | Red Hat JBoss Web Server                 | 3.1
| RHEL 7             | Red Hat OpenShift Container Platform                 | 3.6
| Microsoft Windows Server 2016    | IBM WebSphere Application Server                | 9.0
| Microsoft Windows Server 2016    | Oracle WebLogic Server                 | 12c R2
|====