
[id='bxms_installing_con']
[preface]
= Introduction

NOTE: This guide provides basic information about installing and running {PRODUCT} {PRODUCT_VERSION} {RELEASE}. The information contained here is subject to change before the General Availability release.

ifdef::BA[]
{PRODUCT} is an open source business process management suite that combines Business Process Management and Business Rules Management and enables business and IT users to create, manage, validate, and deploy business processes and rules.
endif::[]

ifdef::DM[]
{PRODUCT} is an open source decision management platform that combines Business Rules Management and Complex Event Processing. It automates business decisions and makes that logic available to the entire business.
endif::[]

{PRODUCT} uses a centralized repository for storing all resources. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic and business processes without requiring assistance from IT personnel.

ifdef::BA[To accommodate the Business Rules component, {PRODUCT} includes integrated Red Hat JBoss BRMS.]
