[id='clustering-artemis-activate-proc_{context}']
= Installing Red Hat JBoss AMQ Broker 7.1

[NOTE]
====
If you do not have a subscription for Red Hat JBoss AMQ Broker, you can use the embedded JMS broker in {EAP}. To do this, install {EAP} and edit the `domain.xml` file as described in <<clustering-dm-install-proc_{context}>>.
====
 
AMQ Broker is a full-featured, message-oriented middleware broker based on ActiveMQ Artemis.  It offers specialized queueing behaviors, message persistence, and manageability. Core messaging is provided by Apache ActiveMQ Artemis with support for different messaging styles such as publish-subscribe, point-to-point, and store-and-forward. It supports multiple protocols and client languages.  AMQ Broker supports clustering and high availability through shared store or shared nothing state replication.

Install and configure Red Hat JBoss AMQ Broker on one node of the cluster.

[NOTE]
====
This procedure describes how to set up Red Hat JBoss AMQ Broker for a simplified, non-high availability environment. For high availability production environments, see https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/clustering_fault-tolerance_and_messaging_patterns_with_red_hat_jboss_amq_7/index[_Clustering, fault-tolerance, and messaging patterns with Red Hat JBoss AMQ 7_].
====

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* Product: AMQ  Broker
* Version: 7.1.0

. Download *Red Hat JBoss AMQ Broker 7.1.0* (`amq-broker-7.1.0-bin.zip`).
. Unzip the `amq-broker-7.1.0-bin.zip` archive. 
. Enter the following command to create and run an AMQ Broker instance, where `<AMQ_HOME>` is the top-level directory of the unzipped the `amq-broker-7.1.0-bin.zip` archive and `<AMQ_BROKER_USER>` and `<AMQ_BROKER_PWD>` is a user name and password combination of your choice:
+
[source]
----
$ <AMQ_HOME>/bin/artemis create --user <AMQ_BROKER_USER> --password <AMQ_BROKER_PWD> --role admin --allow-anonymous y <AMQ_HOME>/instances/mybroker
----
+
This command creates an AMQ Broker user with the `admin` role and a broker in the `<AMQ_HOME>/instances/mybroker` folder. This broker allows anonymous users to connect to the broker from `localhost`.  

. Enter one of the following commands to start AMQ Broker:
+
* On Linux or UNIX-based systems, enter:
+
[source]
----
<AMQ_INSTANCE>/bin/artemis run
----
+
* On Windows, enter:
+
[source]
----
<AMQ_INSTANCE>\bin\artemisbat run
----


