[id='clustering-con']
= Clustering with {PRODUCT} 
ifdef::DM[]
for design-time development environments
endif::[]  

COMMENT: Need to revise and explain the differences between clustering for development and clustering for runtime.

[NOTE]
====
This section is specifically intended for {CENTRAL} 
ifdef::DM[]
development
endif::[]  
environments where you want to cluster the Git repository. It is not necessary to create a clustered environment for {KIE_SERVER} production environments.

COMMENT: This text is from the DM 7.0 clustering section. We need to revise as required and change the focus of the section.
====

Red Hat recommends that you consider clustering two or more computers to create a high availability clustered environment for design-time development environments. Doing this enhances collaboration and provides high availability.

For example, if clustering is configured and Developer X is authoring rules on {CENTRAL} Node1  then Developer Y, who is working on {CENTRAL} Node2, can see the rules authored by Developer X as they are created. Furthermore, all of the developers working on individual nodes of the cluster will see the same synchronized content.

In addition, clustering provides high availability in the rules development environment. If Developer X is working on Node1 and that node fails, Developer X's work is preserved and visible on any other node of the cluster.

The following sections describe how to create a clustered {PRODUCT} environment.