[id='clustering-create-dev-proc']
= Installing {EAP} 7.1 and repackaging {PRODUCT} for a clustered environment

Complete the steps in this section to download and install {EAP} 7.1 and download and repackage {PRODUCT} {PRODUCT_VERSION}. 

Then, configure {EAP} 7.1 for a clustered environment with Elasticsearch and the Artemis Java messaging server (JMS) broker resource adapter integrated with {EAP}. The Artemis JMS broker resource adapter enables your applications to communicate with any messaging provider. It specifies how components such as message-driven beans, Enterprise JavaBeans, and servlets can send or receive messages.

[NOTE] 
====
These steps describe a basic cluster configuration. For more complex configurations, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/configuration_guide[_Red Hat JBoss EAP 7.1 Configuration Guide_].
====
.Prerequisites
*Elasticsearch is installed as described in <<clustering-elasticsearch-proc_{context}>>.
*An NFS server with a mounted partition is available.

.Procedure
. Install {EAP} 7.1 on each node of the cluster:
.. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product: Enterprise Application Platform*
* *Version: 7.1*
.. Click *Download* next to *Red Hat JBoss Enterprise Application Platform 7.1.0*. (`JBEAP-7.1.0/jboss-eap-7.1.0.zip`).
.. Extract the `jboss-eap-7.1.0.zip` file. In the following steps, `_EAP_HOME_` is the `jboss-eap-7.1/jboss-eap-7.1` directory.
. On the cluster node where the {EAP} domain controller will be started, navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal, and select the product and version from the drop-down options:
* *Product: {PRODUCT}*
* *Version: {PRODUCT_VERSION}*
* *Download  {PRODUCT} 7.0.0 {CENTRAL} Deployable for {EAP} 7* (`{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`).
. Extract the 
ifdef::DM[]
`{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`
endif::[]  
ifdef::PAM[]
`{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`
endif::[] 
file to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.

. Repackage the `business-central.war` file:
.. Navigate to the `TEMP_DIR_/{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-eap7-deployable/jboss-eap-7.1` directory.
.. Select the contents of the  `_TEMP_DIR_/{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-eap7-deployable/jboss-eap-7.1` directory and create the `business-central.zip` file.
..  Rename `business-central.zip` file to `business-central.war`. This is the file that you will use to deploy {CENTRAL} on the cluster nodes.
.. If desired, copy the new `business-central.war` file to a location that is more convenient to deploy from.

. On the  of the cluster, in the `_EAP_HOME_/domain/configuration/domain.xml` file, make the following changes for each server group in the `server-groups` element:

.. Specify the `server-group name` and `jvm` name.
.. To enable high availability, change the `profile` to `"full-ha"` and the `socket-binding-group` to `"full-ha-sockets"`.
.. To prevent {CENTRAL} from running out of memory, increase the JVM maximum heap size to `1500m`.
+
[source]
----
<server-group name="some-server-group" profile="full-ha">
    <jvm name="some-jvm">
        <heap size="1000m" max-size="1500m"/>
    </jvm>
    <socket-binding-group ref="full-ha-sockets"/>
</server-group>
----
. On the  of the cluster, in the `_EAP_HOME_/domain/configuration/domain.xml` file, edit or add the following properties to the `<system-properties>` element and replace the following placeholders:
* `<NIOGIT_DIR>` is the location of Git repositories stored under `.niogit`, on an NFS mounted partition accessible to a {EAP} user.
* `<ELASTICSEARCH_NODE_IP>` is the IP addresses where Elasticseach is installed.
* `<JMS_USER>` is a {EAP} application user. It is the user that {CENTRAL} uses to connect to the  embedded JMS broker. 
* `<JMS_USER_PASSWORD>` is the password for `<JMS_USER>`.
+
[source,xml]
----
<system-properties>
  <property name="org.uberfire.nio.git.dir" value="
      <NIOGIT_DIR>"/> 
  <property name="appformer-jms-connection-mode" value="JNDI"/>
  <property name="appformer-jms-username" value="<JMS_USER>  "/>
  <property name="appformer-jms-password" value="<JMS_USER_PASSWORD>"/>
  <property name="org.appformer.ext.metadata.elastic.port" value="9300"/>
  <property name="org.appformer.ext.metadata.elastic.host" 
      value="<ELASTICSEARCH_NODE_IP>"/>
  <property name="org.appformer.ext.metadata.elastic.cluster" 
      value="kie-cluster"/>
  <property name="org.appformer.ext.metadata.elastic.retries" value="10"/>
  <property name="appformer-jms-connection-factory" value="java:/ConnectionFactory"/> 
</system-properties>
----
.  On the  of the cluster, in the `_EAP_HOME_/domain/configuration/domain.xml` file, in the `<subsystem xmlns="urn:jboss:domain:messaging-activemq:2.0">` element, make the following changes:
.. Replace `<cluster password="${jboss.messaging.cluster.password:CHANGE ME!!}"/>` with `<cluster user="<CLUSTER_USER>" password="<CLUSTER_PWD>"/>` where `<CLUSTER_USER>` is the user used by EAP to form a messaging cluster and `<CLUSTER_PWD>` is the password for that user.
.. In the `security-setting` element , add the role of the `<JMS_USER>` to a new `role-name` element, for example:
+
[source]
----
<security-setting name="#">
    <role name="guest" send="true" consume="true" create-non-durable-queue="true" delete-non-durable-queue="true"/>
    <role name="admin" send="true" consume="true" create-non-durable-queue="true" delete-non-durable-queue="true"/>
</security-setting>
----
. Complete the following steps on each node of the cluster:
.. In the `_EAP_HOME_/domain/configuration/host.xml` file `<servers>` element, in the `main-server-group`, add the servers that will be part of the cluster.
.. In the `host.xml` file, add the the system properties listed in
ifdef::PAM[]
<<_cluster_properties_pam>>
endif::PAM[]
ifdef::DM[]
<<_cluster_properties_BRMS>>
endif::DM[]
to each server in the `main-server-group`.
+
ifdef::PAM[]
[id='_cluster_properties_pam']
.Cluster node properties
[cols="1,1,2", frame="all", options="header"]
|===
|Property Name
|Value
|Description

|`jboss.node.name`
|_node name_
|Node name unique within the cluster (optional).

|`org.uberfire.nio.git.daemon.host`
|_node name_
|The name of the daemon host machine in a physical cluster.

|`org.uberfire.nio.git.daemon.port`
|_port number_
|Port used by the VFS repo to accept client connections. The port must be unique for each cluster member.

|`org.uberfire.nio.git.ssh.host`
|_SSH host node name_
|The name of the SSH host machine in a physical cluster.

|`org.uberfire.nio.git.ssh.port`
|_port number_
|The unique port number for ssh access to the GIT repo for a cluster running on physical machines.

|`org.uberfire.nio.git.ssh.hostport` and `org.uberfire.nio.git.daemon.hostport`
|_SSH host port_ and _daemon host port_
|In a virtualized environment, the outside port to be used.

|`org.appformer.ext.metadata.elastic.cluster`
|_Elasticsearch cluster name_
|The name of the Elasticsearch cluster

|`org.appformer.ext.metadata.elastic.port`
|_Elasticsearch port number_
|The Elasticsearch port

|`org.appformer.ext.metadata.elastic.host`
|_Elasticsearch node IP address_
|The IP address of the Elasticsearch node

|`org.appformer.ext.metadata.elastic.retries`
|10
|The number of attempts to connect to Elasticsearch
|===
endif::PAM[]
ifdef::DM[]
+
[id='_cluster_properties_BRMS']
.Cluster Node Properties
[cols="1,1,2", frame="all", options="header"]
|===
|Property Name
|Value
|Description

|jboss.node.name
|nodeOne
|Node name unique within the cluster.

|org.uberfire.nio.git.daemon.port
|9418
|Port used by the VFS repo to accept client connections. The port must be unique for each cluster member.

|org.uberfire.nio.git.ssh.port
|8003
|The unique port number for ssh access to the Git repo for a cluster running on physical machines.

|org.uberfire.nio.git.daemon.host
|nodeOne
|The name of the daemon host machine in a physical cluster.

|org.uberfire.nio.git.ssh.host
|nodeOne
|The name of the SSH host machine in a physical cluster.
|===
endif::DM[]
+
ifdef::PAM[]
The following examples demonstrate how to configure a three node cluster in the `host.xml` file:
+
.Cluster nodeOne Configuration 
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeOne"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeOne"/>
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.host" value="nodeOne"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodeone"
           boot-time="false"/>
</system-properties>
----
====
endif::PAM[]
+
ifdef::PAM[]

.Cluster nodeTwo Configuration
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeTwo"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeTwo" />
 <property name="org.uberfire.nio.git.daemon.port" value="9419" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9419"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8004" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.hostport" value="8004" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.host" value="nodeTwo" />
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodetwo"
           boot-time="false"/>
</system-properties>
----
====
endif::PAM[]
+
ifdef::PAM[]

.Cluster nodeThree Configuration
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeThree"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeThree" />
 <property name="org.uberfire.nio.git.daemon.port" value="9420" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9420"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8005" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.hostport" value="8005" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.host" value="nodeThree" />

 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodethree"
           boot-time="false"/>
</system-properties>
----
====
endif::PAM[]
ifdef::DM[]

.Cluster nodeOne Configuration
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeOne" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodeone"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeOne" />
 <property name="org.uberfire.nio.git.ssh.host" value="nodeOne" />
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
           boot-time="false"/>
</system-properties>
----
====
endif::DM[]
+
ifdef::DM[]

.Cluster nodeTwo Configuration
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeTwo" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodetwo"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeTwo" />
 <property name="org.uberfire.nio.git.ssh.host" value="nodeTwo" />
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
           boot-time="false"/>
</system-properties>
----
====
endif::DM[]
+
ifdef::DM[]

.Cluster nodeThree Configuration
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeThree" boot-time="false"/>
 <property 
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodethree"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeThree" />
 <property name="org.uberfire.nio.git.ssh.host" value="nodeThree" />
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.hostport" value="9418"
           boot-time="false"/>
</system-properties>
----
====
endif::DM[]

