[id='clustering-ks-runtime-standalone-proc']
= Clustering {KIE_SERVER} for a runtime environment
In a runtime environment, {KIE_SERVER} runs rules and processes that support business decisions. The primary benefit of clustering a {KIE_SERVER} runtime environment is load balancing. If activity on one node of the cluster increases, that activity can be shared among the other nodes of the cluster to improve performance.

.Prerequiste
* An NFS server with a mounted partition accessible to a {EAP} user is available.

.Procedure
. Set up a {EAP} 7.1 cluster as described in  https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/configuring_a_red_hat_jboss_eap_7_cluster/[_Configuring a {EAP} 7 Cluster_].
. Install {KIE_SERVER} on each node of the cluster as decribed in _Installing and configuring {PRODUCT} on {EAP} 7.1_.
. If your environment is connected to Smart Router, on the java process running Smart Router do the following:

.. Enable the {KIE_SERVER} watcher service system property:
+
[source]
----
org.kie.server.router.config.watcher.enabled=true
----
.. In the `org.kie.server.router.repo` property, specify the absolute path to the NFS storage where the memory configuration is stored:
+
[source]
----
org.kie.server.router.repo=<absolute_path_to_NFS_storage>
----

. If your environment is managed by the headless {PRODUCT} controller, on the java process running the headless {PRODUCT} controller, do the following:

.. Enable the {KIE_SERVER} watcher service system property:
+
[source]
----
org.kie.server.controller.templatefile.watcher.enabled=true
----
.. In the `org.kie.server.controller.templatefile` property, specify the absolute path to the NFS storage where the memory configuration is stored:
+
[source]
----
org.kie.server.controller.templatefile=<absolute_path_to_NFS_storage>
----