[id='clustering-elasticsearch-proc_{context}']
= Setting up Elasticsearch
Elasticsearch is a highly scalable open source full-text search and analytics engine. It enables you to store, search, and analyze high volumes of data quickly and in near real time.  In a {PRODUCT} clustered environment, it enables you to perform complex and efficient searches across cluster nodes. 

Set up Elasticsearch on one node of the cluster.

[NOTE]
====
This procedure describes how to set up Elasticseach for a simplified, non-high availability environement. For high availability production environments, see the https://www.elastic.co/guide/en/elasticsearch/guide/current/deploy.html[Production Deployment] section of the Elasticsearch documentation.
====

.Procedure
. Download and unzip the  https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.5.zip[Elasticsearch] installation file on one node of the cluster. 
. Replace the contents of the `elasticsearch/config/elasticsearch.yml` file as follows, where `<ELASTICSEARCH_NODE_IP>` is the IP address of the node of the cluster where you unzipped the Elasticsearch file:
+
[source]
----
cluster.name: kie-cluster
transport.host: <ELASTICSEARCH_NODE_IP>>
http.host: <ELASTICSEARCH_NODE_IP>
transport.tcp.port: 9300
discovery.zen.minimum_master_nodes: 1
----
. Run Elasticsearch:
+
* On Linux or UNIX-based systems, enter:
+
`_ELASTICSEARCH_HOME_/bin/elasticsearch`
+
On Windows, enter:
+
`_ELASTICSEARCH_HOME_\bin\elasticsearch.bat`
