[id='clustering-dev-con']
= Clustering {PRODUCT} for a development (authoring) environment

Developers use {PRODUCT} to author rules and processes that assist users with decision making. The primary benefit of clustering {PRODUCT} development environments is high availability. If clustering is configured and Developer X is working on Node1 and that node fails, Developer X's work is preserved and visible on any other node of the cluster.

Most development environments consist of {CENTRAL} for creating rules and processes and at least one {KIE_SERVER} to test those rules and processes. 

[NOTE]
====
You can also use this configuration for runtime environments if you want to use {CENTRAL} to manage the {KIE_SERVERS} in the cluster.
====

To create a {PRODUCT} clustered development environment, download and extract {EAP} 7.1 and {PRODUCT} {PRODUCT_VERSION}. Then, configure {EAP} 7.1 for a domain-mode cluster, including Elasticsearch and the Artemis Java messaging server (JMS) broker resource adapter integrated with {EAP}. Finally, start the cluster and install {CENTRAL} on each cluster node.

Elasticsearch is a highly scalable open source full-text search and analytics engine. It enables you to store, search, and analyze high volumes of data quickly and in near-real time.  In a {PRODUCT} clustered environment, it enables you to perform complex and efficient searches across cluster nodes.  

The Artemis JMS broker resource adapter enables your applications to communicate with any messaging provider. It specifies how components such as message-driven beans, Enterprise JavaBeans, and servlets can send or receive messages.


