[id='controller-eap-install-proc']

= Installing the headless Process Automation Manager controller

You can install the headless Process Automation Manager controller and use the REST API or the {KIE_SERVER} Java Client API to interact with it.

.Prerequisites
* A backed up {EAP} installation version 7.1 or higher is available. The base directory of the {EAP} installation is referred to as `__EAP_HOME__`. 
* Sufficient user permissions to complete the installation are granted.

.Procedure
. Download the `rhpam-7.0-controller-ee7.zip` file by clicking *Download* next to *{PRODUCT} 7.0.0 Add Ons* on the Product Downloads page of the https://access.redhat.com[Red Hat Customer Portal].
. Unzip the `rhpam-7.0.0.Beta02-add-ons.zip` file. The `rhpam-7.0-controller-ee7.zip` file is in the unzipped directory.
. Extract the `rhpam-7.0-controller-ee7` archive to a temporary directory. steps `__TEMP_DIR__`.
. Copy the `__TEMP_DIR__/rhpam-7.0-controller-ee7/controller.war` directory to `__EAP_HOME__/standalone/deployments/`.
+
WARNING: Ensure the names of the headless Process Automation Manager controller deployments you are copying do not conflict with your existing deployments in the {EAP} instance.
. Copy the contents of the `__TEMP_DIR__/rhpam-7.0-controller-ee7/SecurityPolicy/` directory to `__EAP_HOME__/bin`. When asked to overwrite files, select *Yes*.
. In the `__EAP_HOME__/standalone/deployments/` directory, create an empty file named `controller.war.dodeploy`. This file ensures that the headless Process Automation Manager controller is automatically deployed when the server starts.

