[id='controller-eap-configure-proc']
= Configuring {KIE_SERVER} and the standalone {KIE_SERVER} Controller

If {KIE_SERVER} will be managed by the standalone {KIE_SERVER} Controller, you must edit the `standalone.xml` file in both the {KIE_SERVER} and standalone {KIE_SERVER} Controller installations, as described in this section.


.Prerequisites
* {KIE_SERVER} installed in an  `__EAP_HOME__` as described in one of the following sections:
+
** <<installer-run-proc>>
** <<installer-run-cli-proc>>
** <<assembly_installing-on-eap-deployable>>
* The Controller installed in an  `__EAP_HOME__`
+
[NOTE]
====
Red Hat recommends that you install {KIE_SERVER} and the standalone {KIE_SERVER} Controller on different servers in production environments. However, if you install {KIE_SERVER} and the standalone {KIE_SERVER} Controller on the same server, for example in a development environment, make these changes in the shared `standalone.xml` file. 
====
* On {KIE_SERVER} nodes, a user with the `kie-server` role
* On the Controller server nodes, a user with the `kie-server` role
+
For more information, see <<eap-users-create-proc>>.

.Procedure
. In the Controller  `__EAP_HOME__/standalone/configuration/standalone.xml` file, add the following properties to the `<system-properties>` section and replace `<USERNAME>` and `<USER_PWD>` with the credentials of a user with the `kie-server` role:
+
[source,xml]
----
   <property name="org.kie.server.user" value="<USERNAME>"/>
   <property name="org.kie.server.pwd" value="<USER_PWD>"/>
----
. In the {KIE_SERVER}  `__EAP_HOME__/standalone/configuration/standalone.xml` file, add the following properties to the `<system-properties>` section:
+
[source,xml]
----
  <property name="org.kie.server.controller.user" value="<CONTROLLER_USER>"/>
  <property name="org.kie.server.controller.pwd" value="<CONTROLLER_PWD>"/>
  <property name="org.kie.server.id" value="<KIE_SERVER_ID>"/>
  <property name="org.kie.server.location" value="http://<HOST>:<PORT>/kie-server/services/rest/server"/>
  <property name="org.kie.server.controller" value="<CONTROLLER_URL>"/>
----
. In this file, replace the following values:
* Replace `<CONTROLLER_USER>` and `<CONTROLLER_PWD>` with the credentials of a user with the `kie-server` role.
* Replace `<KIE_SERVER_ID>` with the ID or name of the {KIE_SERVER} installation, for example, `rhdm700-decision-server-1`.
* Replace `<HOST>` with the ID or name of the {KIE_SERVER} host, for example, `localhost` or `192.7.8.9`.
* Replace `<PORT>` with the port of the {KIE_SERVER} host, for example, `8080`.
+ 
[NOTE]
====
The `org.kie.server.location` property specifies the location of {KIE_SERVER}.
====

* Replace `<DECISION_CENTRAL_URL>` with the URL of the standalone {KIE_SERVER} Controller. Decision Server connects to this URL during startup. 





