[id='controller-jws-install-proc']
= Installing the headless Process Automation Manager controller

You can configure Process Server to run in managed or unmanaged mode. If Process Server is unmanaged, you must manually create and maintain containers. If Process Server is managed, the standalone {PRODUCT_SHORT} controller manages the Process Server configuration and you interact with the controller to create and maintain containers.

The standalone Process Server controller is integrated with Business Central. If you install Business Central, use the *Execution Server* page to create and maintain containers. However, if you do not install {CENTRAL}, you can install the standalone {PRODUCT_SHORT} controller and use the REST API or the Process Server Java Client API to interact with it.

.Prerequisites
* A Red Hat JBoss Web Server 3.1 with Tomcat 8 or higher server installation is available. The base directory of the JBoss Web Server installation is referred to as `__JWS_HOME__`. 
* Sufficient user permissions to complete the installation are granted.
* The 
ifdef::PAM[]
`rhpam-7.0-controller-jws.zip` file is downloaded. 
endif::PAM[]
ifdef::DM[]
`rhdm-7.0-controller-jws.zip` file is downloaded.
endif::DM[]
To download this file:
+
--
.. Click *Download* next to *{PRODUCT} 7.0.0 Add Ons* on the *Product Downloads* page of the https://access.redhat.com[Red Hat Customer Portal].
.. Unzip the
ifdef::PAM[]
`{PRODUCT_FILE}-add-ons.zip` file.  
endif::PAM[]
ifdef::DM[]
`{PRODUCT_FILE}-add-ons.zip` file.  
endif::DM[]
This file is in the unzipped directory.
--

.Procedure
. Extract the 
ifdef::PAM[]
`rhpam-7.0-controller-jws.zip` 
endif::PAM[]
ifdef::DM[]
`rhdm-7.0-controller-jws.zip`
endif::DM[]
 archive to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the 
ifdef::PAM[]
`__TEMP_DIR__/rhpam-7.0-controller-jws.zip/controller.war`
endif::PAM[]
ifdef::DM[]
`__TEMP_DIR__/rhdm-7.0-controller-jws.zip/controller.war`
endif::DM[]
 directory to the `_JWS_HOME_/tomcat8/webapps` directory.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the Red Hat JBoss Web Server instance.
. Remove the `.war` extensions from the `controller.war` folder.
. Copy the contents of the 
ifdef::PAM[]
`__TEMP_DIR__/rhpfam-7.0-controller-jws/SecurityPolicy/`
endif::PAM[]
ifdef::DM[]
`__TEMP_DIR__/rhdm-7.0-controller-jws/SecurityPolicy/`
endif::DM[]
 directory to `__JWS_HOME__/bin`. When asked to overwrite files, select *Yes*.
. Add the `kie-server` role and user to the `_JWS_HOME_/tomcat8/conf/tomcat-users.xml` file. In the following example,  `<USERNAME>` and `<PASSWORD>` is a user and password combination of your choice:
+
[source]
----
<role rolename="kie-server"/>
<user username="<USER_NAME>" password="<PASSWORD>" roles="kie-server"/>
----

. In the `_JWS_HOME_/tomcat8/bin` directory of the instance running {KIE_SERVER}, create a readable `setenv.sh` file with the following content:
+
`CATALINA_OPTS="-Xmx1024m -Dorg.jbpm.server.ext.disabled=true -Dorg.jbpm.ui.server.ext.disabled=true -Dorg.jbpm.case.server.ext.disabled=true -Dorg.kie.server.controller.user=<CONTROLLER_USER> -Dorg.kie.server.controller.pwd=<CONTROLLER_PWD> -Dorg.kie.server.id=<KIE_SERVER_ID> -Dorg.kie.server.location=http://<HOST>:<PORT>/kie-server/services/rest/server -Dorg.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller"` 
. In the `_JWS_HOME_/tomcat8/bin` directory of the instance running the headless Process Automation Manager controller, create a readable `setenv.sh` file with the following content:
+
`CATALINA_OPTS="-Dorg.kie.server.user=<USERNAME> -Dorg.kie.server.pwd=<USER_PWD>"` 
+
. To start the headless Process Automation Manager controller, enter one of the following commands in the `_JWS_HOME_/tomcat8/bin` directory:
+
** On Linux or UNIX-based systems:
+
[source,bash]
----
$ ./startup.sh
----
** On Windows:
+
[source,bash]
----
startup.bat
----
. After a few minutes, review the the `_JWS_HOME_/tomcat8/logs` directory and correct any errors.
. To verify that the controller is working on Red Hat JBoss Web Server, enter the following command. In this command, replace `<CONTROLLER>` and `<CONTROLLER_PWD>` with the values in the `tomcat-users.xml` file. The output of this command provides information about the {KIE_SERVER} instance.
+
[source]
----
curl -X GET "http://<HOST>:<PORT>/controller/rest/controller/management/servers" -H  "accept: application/xml" -u '<CONTROLLER>:<CONTROLLER_PWD>'
----

[NOTE]
====
Alternatively, you can use the {KIE_SERVER} Java API Client to access the headless Process Automation Manager controller.
====
