[id='dm-roles-con']
= Roles and users

Before starting the server and logging in to {CENTRAL}, you must create at least one user and assign that user the `admin` role. After you log in to {CENTRAL}, you can create additional users and assign them the `admin` or `analyst` role.

* `admin`: The users with `admin` role are the administrators of the application. Administrators can manage users, manage the repositories (create and clone), and have full access to make the required changes in the application. Users with `admin` role have access to all areas within the system.

* `analyst`: An `analyst` role has access to all high-level features to model projects. However, *Authoring* -> *Administration* access is unavailable to users with the `analyst` role. Certain lower-level features targeted towards developers, like the *Deployment* -> *Artifact Repository* view are not accessible for this role. However, the *Build & Deploy* button is available for the analyst role while using the Project Editor.
