[id='eap-dm-install-proc']
= Installing {CENTRAL} using the deployable zip file
{CENTRAL} is a web console that enables you to perform the following tasks over individual components in a unified web-based environment:

* Create, manage, and edit your rules and related assets.
* Manage connected Decision Servers and their containers.

.Prerequisites
* A backed up {EAP} installation, version 7.1 or higher. 
* Sufficient user permissions to complete the installation.
* The following file, downloaded from Product Downloads page of the https://access.redhat.com[Red Hat Customer Portal]:
+
`rhdm-7.0.0.GA-decision-central-eap7-deployable.zip`

.Procedure
. Extract the `rhdm-7.0.0.GA-decision-central-eap7-deployable.zip` file to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the contents of the `__TEMP_DIR__/rhdm-7.0.0.GA-decision-central-eap7-deployable/jboss-eap-7.1` directory to `__EAP_HOME__`. When asked to overwrite files or merge directories, select *Yes*.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the {EAP} instance.

