[id='eap-dm-install-proc']
= {CENTRAL} ZIP file installation

{CENTRAL} is a web console that enables you to perform the following tasks over individual components in a unified web-based environment:

* Create, manage, and edit your rules and related assets.
* Manage connected {KIE_SERVER} instances and their containers.

.Prerequisites
* A backed up {EAP} installation, version 7.1 or higher. The base directory of the {EAP} installation is referred to as `__EAP_HOME__`. 
* Sufficient user permissions to complete the installation.
* The following file, downloaded as described in
<<install-download-proc_{context}>>:
+
ifdef::DM[]
`rhdm-7.0.0.GA-decision-central-eap7-deployable.zip`
endif::[]  
ifdef::PAM[]
`rhpam-7.0.0.GA-business-central-eap7-deployable.zip`
endif::[]

.Procedure
. Extract the 
ifdef::DM[]
`rhdm-7.0.0.GA-decision-central-eap7-deployable.zip`
endif::[]  
ifdef::PAM[]
`rhpam-7.0.0.GA-business-central-eap7-deployable.zip`
endif::[] 
file to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the contents of the 
ifdef::DM[]
`__TEMP_DIR__/rhdm-7.0.0.GA-decision-central-eap7-deployable/jboss-eap-7.1`
endif::[]  
ifdef::PAM[]
`__TEMP_DIR__/rhpam-7.0.0.GA-business-central-eap7-deployable/jboss-eap-7.1`
endif::[]
directory to `__EAP_HOME__`. When asked to overwrite files or merge directories, select *Yes*.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the {EAP} instance.

