[id='eap_execution_server_download_install_proc']

= Downloading and Installing Execution Server

Execution Server provides the runtime environment for business assets and accesses the data stored in the assets repository (Knowledge Store).

.Prerequisites
* {EAP} 7.0.8 installed on your hard drive. The base directory of the EAP installation is referred to as `__EAP_HOME__`.
* The following file, which you should have received with this document:
+
ifdef::BA[`jboss-bpmsuite-7.0.0.LA-execution-server-ee7.zip`]
ifdef::DM[`jboss-brms-7.0.0.LA-execution-server-ee7.zip`]

.Procedure
. Extract the `jboss-bpmsuite-7.0.0.LA-execution-server-ee7.zip` archive to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the `__TEMP_DIR__/jboss-bpmsuite-7.0.0.LA-execution-server-ee7/jboss-bpmsuite-7.0-execution-server-ee7/kie-execution-server.war` directory to `__EAP_HOME__/standalone/deployments/`.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the {EAP} instance.
. Copy the contents of the `__TEMP_DIR__/jboss-bpmsuite-7.0.0.LA-execution-server-ee7/jboss-bpmsuite-7.0-execution-server-ee7/SecurityPolicy/` to `__EAP_HOME__/bin`. When asked to overwrite files, select *Yes*.
. In the `__EAP_HOME__/standalone/deployments/` directory, create an empty file named `kie-execution-server.war.dodeploy`. This file ensures that Execution Server is automatically deployed when the server starts.

