[[eap_execution_server_download_install_proc]]

= Downloading and Installing Execution Server

Execution Server provides the runtime environment for business assets and accesses the data stored in the assets repository (Knowledge Store).

.Prerequisites
* {EAP} 7.0.7 installed on your hard drive. The base directory of the EAP installation is referred to as `__EAP_HOME__`.
* The following file, which you should have received with this document:
** Execution Server: `jboss-brms-bpmsuite-7.0.0.Beta02-execution-server-ee7.zip`

.Procedure
. Extract the `jboss-brms-bpmsuite-7.0.0.Beta02-execution-server-ee7.zip` archive to an arbitrary directory, here referred to as `__TEMP_DIR__`.
. Copy the `__TEMP_DIR__/jboss-brms-bpmsuite-7.0.0.Beta02-execution-server-ee7/kie-execution-server.war` directory into `__EAP_HOME__/standalone/deployments/`.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not collide with your existing deployments in the {EAP} instance.
. Copy the contents of the `__TEMP_DIR__/jboss-brms-bpmsuite-7.0.0.Beta02-execution-server-ee7/SecurityPolicy/` to `__EAP_HOME__/bin`. When asked to overwrite files, select *Yes*.
. In the `__EAP_HOME__/standalone/deployments/` directory, create an empty file named `kie-execution-server.war.dodeploy`. This file ensures that the Execution Server is automatically deployed when the server starts.

