[id='eap-dm-install-proc']
= Installing {CENTRAL} using the deployable zip file
{CENTRAL} is a web console that enables you to perform the following tasks over individual components in a unified web-based environment:

* Create, manage, and edit your processes.
* Run, manage, and monitor process instances.
* Generate reports and manage the tasks produced.
* Create new tasks and notifications.

.Prerequisites

* A backed up {EAP} installation, version 7.1 or higher. 
* Sufficient user permissions to complete the installation.
* The following file, downloaded from Product Downloads page of the https://access.redhat.com[Red Hat Customer Portal]:
+
`rhdm-7.0.0.CR1-decision-central-eap7-deployable.zip`

.Procedure
. Extract the `rhdm-7.0.0.CR1-decision-central-eap7-deployable.zip` file to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the contents of the `__TEMP_DIR__/jboss-bpmsuite-7.0-business-central-eap7/jboss-eap-7.0` directory to `__EAP_HOME__`. When asked to overwrite files or merge directories, select *Yes*.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the {EAP} instance.

