
= Downloading and installing {CENTRAL}
{CENTRAL} is a web console that enables you to perform the following tasks over individual components in a unified web-based environment:

* Create, manage, and edit your processes.
* Run, manage, and monitor process instances.
* Generate reports and manage the tasks produced.
* Create new tasks and notifications.

.Prerequisites
* {EAP} 7.1 is installed on your hard drive. The base directory of the {EAP} installation is referred to as `__EAP_HOME__`.
* The following file is downloaded from the *Product Downloads* page of the https://access.redhat.com[Red Hat Customer Portal]
+
`jboss-bpmsuite-7.0.0.{URL_COMPONENT_CENTRAL}-eap7.zip`

.Procedure
. Extract the `jboss-bpmsuite-7.0.0.{URL_COMPONENT_CENTRAL}-eap7.zip` file to a temporary directory. steps `__TEMP_DIR__`.
. Copy the contents of the `__TEMP_DIR__/jboss-bpmsuite-7.0-{URL_COMPONENT_CENTRAL}-eap7/jboss-eap-7.0` directory to `__EAP_HOME__`. When asked to overwrite files or merge directories, select *Yes*.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the {EAP} instance.

