[id='install-dc-standalone-proc']
= Installing standalone {CENTRAL}

You can use the {CENTRAL} standalone JAR file to install {CENTRAL} in a WildFly Swarm environment. This installation method does not require a separate server installation.

.Procedure

. Download the {CENTRAL} standalone JAR file from the https://access.redhat.com[Red Hat Customer Portal].
. Create a `yaml` configuration file as described in http://docs.wildfly-swarm.io/2017.12.1/#configuring-an-application-using-yaml[WildFly Swarm Documentation].
. In a terminal window, navigate to the directory where you downloaded the installer file and enter the following command:
+
[source,subs="attributes+"]
----
java -jar {PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-standalone.jar -s
application-config.yaml
----
+
In this command, `application-config.yaml` is the `yaml` configuration file that you created in step 2.

In addition, you can set any properties supported by {CENTRAL} by including the `-D<property>=<value>` parameter in the installation command, for example:

[source,subs="attributes+"]
----
java -jar {PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-standalone.jar -s
application-config.yaml -D<property>=<value> -D<property>=<value>
----

See <<install-standalone-properties-con>> for more information.
