[id='installing-con_{context}']
= About {PRODUCT} 

ifeval::["{context}" == "install-on-eap"]
{EAP_LONG} ({EAP}) 7.1 is a certified implementation of the Java Enterprise Edition 7 (Java EE 7) full and web profile specifications. {EAP} provides preconfigured options for features such as high availability, clustering, messaging, and distributed caching. It also enables users to write, deploy, and run applications using the various APIs and services that {EAP} provides.
endif::[]
ifeval::["{context}" == "install-on-jws"]
Red Hat JBoss Web Server is an enterprise ready web server designed for medium and large applications, based on Tomcat 8. Red Hat JBoss Web Server provides organizations with a single deployment platform for Java Server Pages (JSP) and Java Servlet technologies, PHP, and CGI.
endif::[]
{PRODUCT} consists of {CENTRAL} and {KIE_SERVER}. 
ifeval::["{context}" == "install-on-jws"]
On a Red Hat JBoss Web Server installation, you can install {KIE_SERVER} and the {CENTRAL} controller. Alternatively, you can run the standalone {CENTRAl} JAR file.
endif::[]

The instructions in this document explain how to install {PRODUCT} on 
ifeval::["{context}" == "install-on-eap"]
{EAP} 7.1
endif::[]
ifeval::["{context}" == "install-on-jws"]
Red Hat JBoss Web Server 3.1
endif::[]  
on premise. For other types of {PRODUCT} installations, see the following documents:
COMMENT: URLS will be updated when available.

ifeval::["{context}" == "install-on-eap"]
* {URL_INSTALL_ON_JWS}[_{INSTALL_ON_JWS}_]
endif::[]
ifeval::["{context}" == "install-on-jws"]
* {URL_INSTALL_ON_EAP}[_{INSTALL_ON_EAP}_]
endif::[] 
* {URL_INSTALLING_DS_ON_WAS}[_{INSTALLING_DS_ON_WAS}_]
* {URL_INSTALLING_DS_ON_WLS}[_{INSTALLING_DS_ON_WLS}_]
* {URL_DM_ON_OPENSHIFT}[_{DM_ON_OPENSHIFT}_]
* {URL_INSTALLING_PLANNER}[_{INSTALLING_PLANNER}_]

For information on supported components, see the following documents:

* https://access.redhat.com/solutions/3405361[What is the mapping between RHPAM product and maven library version?]
* https://access.redhat.com/articles/3405381[Red Hat Process Automation Manager 7 Supported Configurations]

[NOTE]
====
This section describes installing 
ifeval::["{context}" == "install-on-eap"]
{CENTRAL} 
endif::[]
ifeval::["{context}" == "install-on-jws"]
the {CENTRAL} controller
endif::[]
and {KIE_SERVER} on the same server. Red Hat recommends installing 
ifeval::["{context}" == "install-on-eap"]
{CENTRAL} 
endif::[]
ifeval::["{context}" == "install-on-jws"]
the {CENTRAL} controller
endif::[]
and {KIE_SERVER} on different servers in production environments.
====
