[id='installer-controller-eap-proc_{context}']
= Using the installer to configure {KIE_SERVER} with the {CENTRAL} Controller

You can use the installer in interactive or CLI mode to install {CENTRAL} and {KIE_SERVER}, and then configure {KIE_SERVER} with the {CENTRAL} Controller.

.Prerequisites
* Two computers with backed up {EAP} 7.1 or higher server installations are available.
* Sufficient user permissions to complete the installation are granted.

.Procedure
. On the first computer, run the installer in interactive mode or CLI mode. See one of the following sections for more information:
+
* <<installer-run-proc_{context}>>
* <<installer-run-cli-proc_{context}>>
. On the Component Selection page, deselect {KIE_SERVER}. 
. Complete the {CENTRAL} installation.
. On the second computer, run the installer in interactive mode or CLI mode. 
. On the Component Selection page, deselect {CENTRAL}. 
. On the Configure Runtime Environment page, select *Perform Advanced Configuration*.
. Select *Customize {KIE_SERVER} properties*, and click *Next*.
. On the Process Server Properties Configuration page, click *New Server Configuration* to add a {KIE_SERVER} and specify a unique name for that {KIE_SERVER}. This name will appear in {CENTRAL} and enable you to distinguish between different {KIE_SERVER}s.