[id='installer-run-proc']
= Installing {PRODUCT} using the installer

The installer for {PRODUCT} is an executable JAR file. You can use it to install {PRODUCT} in an existing {EAP} 7.1 or Red Hat JBoss Server 3.1 Tomcat 8 server installation.

[NOTE]
====
For security reasons, you should run the installer as a non-root user.
====
[NOTE]
====
When running the installer on Windows, you may be prompted to provide administrator credentials during the installation. To prevent this, add the `izpack.mode=privileged` option to the installation command:

[source]
----
java -Dizpack.mode=privileged -jar rhdm-installer-7.0.0.CR1.jar
----

Furthermore, when running the installer with a 32-bit Java Virtual Machine, you can encounter memory limitations. To solve the issue, run:

[source]
----
java -XX:MaxHeapSize=4g -jar rhdm-installer-7.0.0.CR1.jar
----
====

.Prerequisite

* A backed up {EAP} 7.1 or higher or Red Hat JBoss Web Server 3.1 with Tomcat 8 or higher server installation. 
+
[NOTE]
====
If you are using Red Hat JBoss Web Server 3.1, you must use a fresh ZIP installation:
COMMENT: Can you be more specific?
====

* Sufficient user permissions to complete the installation.
* The JAR binary inlcuded in `$PATH` environment variable. On Red Hat Enterprise Linux, it is included in the `java-$_JAVA_VERSION_-openjdk-devel` package.

.Procedure
. In a terminal window, navigate to the directory where you downloaded the installer file and enter the following command:
+
[source]
----
java -jar rhdm-installer-7.0.0.GA.jar
----

+
The graphical installer will execute and display a splash screen and a license agreement page.

. Click *I accept the terms of this license agreement* and click *Next*.
. Specify the {EAP} 7.1 or Red Hat JBoss 3.1 Web Server with Tomcat 8 server home, where you want to install {PRODUCT} and click *Next*.
. Select the components that you want to install and click *Next*.
+
You cannot install {CENTRAL} on Red Hat JBoss 3.1 Web Server with Tomcat 8. However, you can install the {CENTRAL} controller. COMMENT: Need more information about the controller. What is it? Why would I install it?
+
[NOTE]
====
It is possible install {CENTRAL} and {KIE_SERVER} in the same server. However, for production environments you should install them on different servers. To do this, run the installer twice.
====
+
. Create the Decision Manager admin user and click *Next*.  
+
[NOTE]
====
Make sure that the selected user name is not the same as an existing user, role, or group. For example,do not create a user with the user name `admin`.

The password must have at least eight characters and must contain at least one number and one non-alphanumeric character, but not & (ampersand).
====
+
Make a note of the user name and password. You will need them to access {CENTRAL} or {KIE_SERVER} (or both).
. On the Component Installation page, click *Next* to start the installation. The Component Installation page lists the components that you will install.

. When the installation has completed, click *Next* on the *Processing Finished* page. On the next page,you will see the message *Installation has completed successfully*.

. If desired, click *Generate Installation Script and Properties File* to save the installation data in an XML file, then click *Done*. You can use this file to automatically install {PRODUCT} on the same type of server. Note that you must change the `installpath` parameter in the XML file to specify the path of new server that you want to install {PRODUCT} on. Enter the following command to perform an installation with the XML file:
+
[source]
----
java -jar rhdm-installer-7.0.0.GA.jar <path-to-file>
----

You have successfully installed {PRODUCT} using the installer. If you installed only {CENTRAL}, repeat these steps to install {KIE_SERVER} on a separate server.

To start {PRODUCT}, enter one of the following commands:

* On {EAP} 7.1, enter:
+
[source]
----
EAP_HOME/bin/.standalone.sh
----

* On Red Hat JBoss Web Server 3.1 with Tomcat 8, enter:
+
[source]
----
JWS_HOME/bin/./startup.sh
----
