[id='install-testing-proc']
= Verifying the {PRODUCT} installation

After you have installed {PRODUCT}, create an asset to verify that the installation is working.

.Procedure
. Enter  the following command to start {KIE_SERVER}:
+
[source]
----
EAP_HOME/bin/standalone.sh
----

. In a web browser, enter `localhost:8080/decision-central`. If {PRODUCT} has been configured to run from a domain name, substitute `localhost` for the domain name, for example:
+
http://www.example.com:8080/decision-central
+
If {PRODUCT} has been configured to run in a cluster, substitute `localhost` for the IP address of a particular node, for example:
+
`http://<node_IP_address>:8080/decision-central`
. Enter the admin user credentials that you created during installation. The {CENTRAL} home page appears.
. Select *Menu* -> *Design* -> *Projects*.
. Click *Try Samples*.
. Click *mortages*. The Assets window appears.
. Click *Create New Asset*.
. Select *Data Object*.
. Enter MyDataObject in the *Name* field and click *OK*.
. Click *Spaces* -> *myteam* -> *mortgages* and confirm that MyDataObject is in the list of assets.
. If you are verifying a clustered installation, enter the following URL, where `<node_IP_address>` is the address of different node. Enter same credentials that you used with the {CENTRAL} where you created the MyDataObject asset.
+
`http://<node_IP_address>:8080/decision-central`
. Select *Menu*-> *Design* -> *Projects*.
. Select the *mortgages* project.
. Verify that MyDataObject is in the asset list.
. Delete MyDataObject.



