[id='install-download-proc_{context}']
= Downloading the {PRODUCT} installation files

Depending on your environment and installation requirements, download a {PRODUCT} distribution.

.Procedure
. Log in to the https://access.redhat.com[Red Hat Customer Portal].
. Click *DOWNLOADS* at the top of the page.
. On the *Product Downloads* page that opens, navigate to the JBOSS INTEGRATION AND AUTOMATION section, and click *{PRODUCT}*.
. On the *Software Downloads* page, download one of the following product distributions:
* To use the installer to install {PRODUCT} on 
ifeval::["{context}" == "install-on-eap"]
{EAP} 7.1
endif::[]
ifeval::["{context}" == "install-on-jws"]
Red Hat JBoss Web Server 3.1
endif::[]  
, download *{PRODUCT} 7.0.0 Installer* 
ifdef::PAM[]
(`rhpam-installer-7.0.0.Beta02.jar`).
endif::PAM[]
ifdef::DM[]
(`rhdm-installer-7.0.0.Beta02.jar`). 
endif::DM[]
The installer graphical user interface steps you through the installation process.
ifeval::["{context}" == "install-on-eap"]
* To install {PRODUCT} on {EAP} 7.1 using the deployable zip files, download:
** *{PRODUCT} 7.0.0 {KIE_SERVER} for All Supported EE7 Containers*
ifdef::PAM[]
(`rhpam-7.0.0.Beta02-kie-server-ee7.zip`)
endif::PAM[]
ifdef::DM[]
(`rhdm-7.0.0.Beta02-kie-server-ee7.zip`)
endif::DM[]
ifdef::PAM[]
** *{PRODUCT} 7.0.0 {CENTRAL} Deployable for {EAP} 7* 
(`rhpam-7.0.0.Beta02-business-central-eap7-deployable.zip`)
endif::PAM[]
endif::[]
ifeval::["{context}" == "install-on-jws"]
* To install {KIE_SERVER} on Red Hat JBoss Web Server 3.1 using the deployable zip file, download *{PRODUCT} 7.0.0 Add Ons*. 
ifdef::PAM[]
(`rhpam-7.0.0.Beta02-add-ons.zip`).
endif::PAM[]
ifdef::DM[]
(`rhdm-7.0.0.Beta02-add-ons.zip`).
endif::DM[]
endif::[] 
+
The ZIP files do not require a graphical user interface so you can install {PRODUCT} using SSH.
* To run {CENTRAL} without needing to deploy it to an application server, download *{PRODUCT} 7.0.0 Decision Central Standalone* 
ifdef::PAM[]
(`rhpam-7.0.0.Beta02-decision-central-standalone.jar`).
endif::PAM[]
ifdef::DM[]
(`rhdm-7.0.0.Beta02-decision-central-standalone.jar`).
endif::DM[]

//ifdef::PAM[]
//* To install {CENTRAL} Monitoring, download *{PRODUCT} 7.0.0 {CENTRAL} Monitoring* 
//(`rhpam-7.0.0.Beta02-monitoring-ee7.zip`).
//endif::PAM[]








 