[id='installing-con_{context}']
= About {PRODUCT} 

ifdef::PAM[]
{PRODUCT} is the Red Hat middleware platform for creating business automation applications and microservices. It enables enterprise business and IT users to document, simulate, manage, automate, and monitor business processes and policies. It is designed to empower business and IT users to collaborate more effectively, so business applications can be changed easily and quickly.
endif::[]  
ifdef::DM[]
{PRODUCT} is an open source decision management platform that combines business rules management, complex event processing, Decision Model & Notation (DMN) execution, and Business Optimizer for solving planning problems. It automates business decisions and makes that logic available to the entire business.

Business assets such as rules, decision tables, and DMN models are stored in a central repository. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.
endif::[]  

ifeval::["{context}" == "install-on-eap"]
{EAP_LONG} ({EAP}) 7.1 is a certified implementation of the Java Enterprise Edition 7 (Java EE 7) full and web profile specifications. {EAP} provides preconfigured options for features such as high availability, clustering, messaging, and distributed caching. It also enables users to write, deploy, and run applications using the various APIs and services that {EAP} provides.
endif::[]
ifeval::["{context}" == "install-on-jws"]
Red Hat JBoss Web Server is an enterprise ready web server designed for medium and large applications, based on Tomcat 8. Red Hat JBoss Web Server provides organizations with a single deployment platform for Java Server Pages (JSP) and Java Servlet technologies, PHP, and CGI.
endif::[]

ifeval::["{context}" == "install-on-jws"]
On a Red Hat JBoss Web Server installation, you can install {KIE_SERVER} and the {CENTRAL} controller. Alternatively, you can run the standalone {CENTRAl} JAR file.
endif::[]

The instructions in this document explain how to install {PRODUCT} in a 
ifeval::["{context}" == "install-on-eap"]
{EAP} 7.1 server instance.
endif::[]
ifeval::["{context}" == "install-on-jws"]
Red Hat JBoss Web Server 3.1 server instance.
endif::[]
For instruction on how to install {PRODUCT} in other environments, see the following documents:

//ifeval::["{context}" == "install-on-eap"]
//* {URL_INSTALL_ON_JWS}[_{INSTALL_ON_JWS}_]
//endif::[]
ifeval::["{context}" == "install-on-jws"]
* _INSTALLING AND CONFIGURING RED HAT PROCESS AUTOMATION MANAGER ON EAP 7.1_
endif::[]
* {URL_INSTALLING_KIE_ON_WAS}[_{INSTALLING_KIE_ON_WAS}_]
* {URL_INSTALLING_KIE_ON_WLS}[_{INSTALLING_KIE_ON_WLS}_]
// Comment: Confirm these stories:
* {URL_DEPLOYING_AUTHORING_ON_OPENSHIFT}[_{DEPLOYING_AUTHORING_ON_OPENSHIFT}_]
* {URL_DEPLOYING_IMMUTABLE_ON_OPENSHIFT}[_{DEPLOYING_IMMUTABLE_ON_OPENSHIFT}_]
* {URL_DEPLOYING_MANAGED_ON_OPENSHIFT}[_{DEPLOYING_MANAGED_ON_OPENSHIFT}_]


ifdef::PAM[]
For information on supported components, see the following documents:
// Comment: DM versions?
* https://access.redhat.com/solutions/3405361[What is the mapping between RHPAM product and maven library version?]
* https://access.redhat.com/articles/3405381[Red Hat Process Automation Manager 7 Supported Configurations]
endif::[]  
ifdef::DM[]
For information on supported components, see https://access.redhat.com/articles/3354301[_Red Hat Decision Manager 7 Supported Configurations_].
endif::[]  

