[id='install-standalone-properties-con']
= Supported properties
* `org.uberfire.nio.git.dir`: Location of the directory .niogit. Default: working directory
* `org.uberfire.nio.git.dirname`: Name of the Git directory. Default: .niogit
* `org.uberfire.nio.git.daemon.enabled`: Enables/disables Git daemon. Default: true
* `org.uberfire.nio.git.daemon.host`: If the Git daemon is enabled, it uses this property as local host identifier. Default`: localhost
* `org.uberfire.nio.git.daemon.port`: If the Git daemon is enabled, it uses this property as port number. Default: 9418
* `org.uberfire.nio.git.ssh.enabled`: Enables/disables ssh daemon. Default: true
* `org.uberfire.nio.git.ssh.host`: If the ssh daemon is enabled, it uses this property as local host identifier. Default: localhost
* `org.uberfire.nio.git.ssh.port`: If the ssh daemon is enabled, it uses this property as port number. Default: 8001
* `org.uberfire.nio.git.ssh.cert.dir`: Location of the directory .security where local certificates will be stored. Default: working directory
* `org.uberfire.nio.git.ssh.passphrase`: Passphrase to access your Operating Systems public keystore when cloning Git repositories with scp style URLs; e.g. git@github.com:user/repository.git.
* `org.uberfire.nio.git.ssh.algorithm`: Algorithm used by SSH. Default: DSA
+
[NOTE]
====
If you plan to use RSA or any algorithm other than DSA, make sure you setup properly your Application Server to use Bouncy Castle JCE library.
====
* `org.uberfire.metadata.index.dir`: Place where Lucene .index folder will be stored. Default: working directory
* `org.uberfire.ldap.regex.role_mapper`: Regex pattern used to map LDAP principal names to application role name. Note that the variable role must be part of the pattern because it is substituted by the application role name when matching a principal value to role name. Default: Not used.
* `org.uberfire.sys.repo.monitor.disabled`: Disable configuration monitor (do not disable unless you know what you’re doing). Default: false
* `org.uberfire.secure.key`: Password used by password encryption. Default`: org.uberfire.admin
* `org.uberfire.secure.alg`: Crypto algorithm used by password encryption. Default: PBEWithMD5AndDES
* `org.uberfire.domain`: security-domain name used by uberfire. Default: ApplicationRealm
* `org.guvnor.m2repo.dir`: Place where Maven repository folder will be stored. Default: working-directory/repositories/kie
* `org.guvnor.project.gav.check.disabled`: Disable GAV checks. Default: false
* `org.kie.demo`: Enables external clone of a demo application from GitHub.
* `org.kie.build.disable-project-explorer`: Disable automatic build of selected Project in Project Explorer. Default: false
* `org.kie.verification.disable-dtable-realtime-verification`: Disables the realtime validation and verification of decision tables. Default: false
* `org.kie.workbench.controller`: URL for connecting with a Kie Server Controller, for example: `ws://localhost:8080/kie-server-controller/websocket/controller`.
