[id='install-download-proc']
= Downloading the {PRODUCT} installation files

Depending on your environment and installation requirements, download a {PRODUCT} distribution.

.Procedure
. Log in to the https://access.redhat.com[Red Hat Customer Portal].
. Click *DOWNLOADS* at the top of the page.
. On the *Product Downloads* page that opens, navigate to the JBOSS INTEGRATION AND AUTOMATION section, and click *{PRODUCT}*.
. On the *Software Downloads* page, if necessary select *BRMS* from the Product menu and *7.0* from the *Version* menu.
. Download one of the following product distributions:
* To use the installer to install {PRODUCT} on {EAP} 7.1 or {KIE_SERVER} on Red Hat JBoss Web Server 3.1, download *{PRODUCT} 7.0.0 Installer* (`rhdm-installer-7.0.0.GA.jar`).
* To install {PRODUCT} on {EAP} 7.1 using the deployable zip files, download:
** *{PRODUCT} 7.0.0 {KIE_SERVER} for All Supported EE7 Containers* (`rhdm-7.0.0.GA-kie-server-ee7.zip`)
** *{PRODUCT} 7.0.0 {CENTRAL} Deployable for {EAP} 7* (`rhdm-7.0.0.GA-kie-server-ee7.zip`)
* To run {CENTRAL} without needing to deploy it to an application server, download *{PRODUCT} 7.0.0 Decision Central Standalone* (`rhdm-7.0.0.GA-decision-central-standalone.jar`)
* To install {KIE_SERVER} on Red Hat JBoss Web Server 3.1 using the deployable zip file, download *{PRODUCT} 7.0.0 Add Ons* (`rhdm-7.0.0.GA-add-ons.zip`)

.Next steps
Go to one of the following sections:

* <<assembly_installing-using-installer>>
* <<assembly_installing-on-eap-deployable>>
* <<run-dc-standalone-proc>>


 