[id='installer-run-cli-proc']
= Installing {PRODUCT} using the installer in CLI mode

You can run the installer for {PRODUCT} through the command-line interface (CLI). 

[NOTE]
====
For security reasons, you should run the installer as a non-root user.
====

.Prerequisite
* A backed up {EAP} 7.1 or higher or Red Hat JBoss Web Server 3.1 with Tomcat 8 or higher server installation
* Sufficient user permissions to complete the installation
+
[NOTE]
====
If you are installing {KIE_SERVER} on Red Hat JBoss Web Server 3.1, ensure that you are logged in with a user that has write permission for Tomcat 8.
====
* The JAR binary inlcuded in `$PATH` environment variable. On Red Hat Enterprise Linux, it is included in the `java-$_JAVA_VERSION_-openjdk-devel` package.
+
[NOTE]
====
{PRODUCT} is designed to work with UTF-8 encoding. If a different encoding system is used by the underlying JVM, unexpected errors might occur. To ensure UTF-8 is used by the JVM, use the following `"-Dfile.encoding=UTF-8"` system property.
====

.Procedure
. In a terminal window, navigate to the directory where you downloaded the installer file and enter the following command:
+
[source]
----
java -jar rhdm-installer-7.0.0.GA.jar -console

----
+
The command-line interactive process will start and display the End-User License Agreement. 
+
[source]
----
press 1 to continue, 2 to quit, 3 to redisplay.
----
. Read the license agreement then enter `1` and press Enter to continue:
+
[source]
----
Specify the home directory of one of the following servers:  Red Hat JBoss EAP 7.1 or Tomcat 8
[/home/user/RHDM-7.0.0/jboss-eap-7.1]
----
+
. Enter the parent directory of an existing {EAP} 7.1  or Red Hat JBoss Web Server 3.1 with Tomcat 8 installation.
+
The installer will verify the location of the installation at the location provided. Enter `1` to confirm and continue.
+
[NOTE]
====
It is possible to install Decision Manager and {KIE_SERVER} on the same server. However, Red Hat recommends installing {CENTRAL} and {KIE_SERVER} on different servers in production environments.
====
. Follow the instructions in the installer to complete the installation.
+
[NOTE]
====
When you create the user name and password, make sure that the specified user name does not conflict with any known title of a role or a group. For example, if there is a role called `admin`, you should not create a user with the user name `admin`.

The password must have at least eight characters and must contain at least one number and one non-alphanumeric character (_not_ including the character `&`).

Make a note of the user name and password. You will need them to access {CENTRAL} and {KIE_SERVER}.
====

+
. When the installation has completed, you will see this message:
+
[source]
----
Would you like to generate an automatic installation script and properties file?
----
. Enter `y` to create an XML file that contains the installation data, or `n` to complete the installation. If you enter `y`, you are prompted to specify a path for the XML file. 
. Enter a path or press the Enter key to accept the suggested path.

You have successfully installed {PRODUCT}. If you installed only {CENTRAL}, repeat these steps to install {KIE_SERVER} on a separate server.