[#openshift_temp_bpmsuite_s2i_install_proc]

= Using the OpenShift Application Template for {PRODUCT} with Source-to-Image
Use this template to install {PRODUCT} {PRODUCT_VERSION} {RELEASE} with Source-to-Image (S2I) (Ephemeral plus https) in your OpenShift project. 

.Prerequisites
* An OpenShift product image installed as described in <<openshift_image_install_proc>>.
* The `jboss-bpmsuite-7.0.0.Beta02-openshift.zip` file, available from the site that contains this document, extracted to your hard drive.

.Procedure
. Change directory to the `jboss-bpmsuite-7.0.0.Beta02-openshift/application-template` directory.
. Copy the path of the `bpmsuite70-executionserver-s2i.json` file.
. Enter the following command from the directory that contains the OpenShift CLI:
+
[source,bash]
----
$ oc process -n <bpms-project> -f <template-path> -v IMAGE_STREAM_NAMESPACE=<bpms-project> -v 
KIE_ADMIN_USER=<kie-admin-user> -v 
KIE_ADMIN_PWD=<kie-admin-user-pw> -v 
KIE_SERVER_CONTROLLER_USER=<kie-server-controller-user> -v 
KIE_SERVER_CONTROLLER_PWD=<kie-server-controller-pwd> -v 
KIE_SERVER_USER=<kie-server-user> -v 
KIE_SERVER_PWD=<kie-server-user-pw> -v 
HORNETQ_CLUSTER_PASSWORD=<hornetq-cluster-admin-pw> -v
HTTPS_SECRET=<server-keystore-secret-name> -v
HTTPS_KEYSTORE=<server-keystore-filename> -v
GENERIC_WEBHOOK_SECRET=<generic-webhook-secret> -v
GITHUB_WEBHOOK_SECRET=<github-webhook-secret> -v
| oc create -n <bpms-project> -f - 

----
In this command, replace the following variables:
* Replace `<bpms-project>` with the name of your project.
* Replace `<template-path>` with the path of the `bpmsuite70-executionserver-s2i.json` file.
* Replace `<kie-admin-user>` with the {PRODUCT} administrator user name.
* Replace `<kie-admin-user-pw>` with a password for the {PRODUCT} administrator user.
* Replace `<kie-server-controller-user>` with the {PRODUCT}  server controller user.
* Replace `<kie-server-controller-pwd>` with a password for the {PRODUCT}  server controller.
* Replace `<kie-server-user>` with the name of a KIE server user.
* Replace `<kie-server-user-pw>` with the password for the KIE server user.
* Replace `<hornetq-cluster-admin-pw>` with the password of the Hornet Q administrator.
* Replace `<server-keystore-secret-name>` with the name of the secret containing the keystore file.
* Replace `<server-keystore-filename>` with the name of the keystore file within the secret.
* Replace `<generic-webhook-secret>` with the generic build trigger secret.
* Replace `<github-webhook-secret>` with the GitHub trigger secret.
+

[NOTE]
====
View the `bpmsuite70-executionserver-s2i.json` file for a list of all of the available parameters and their attributes. 
====

