[#openshift_image_install_proc]

= Installing the OpenShift Product Image
After you have uploaded your product image file to an external Docker repository or an internal OpenShift registry, you must use the OpenShift CLI to install the product image file in OpenShift.

.Prerequisites
* Access to an OpenShift environment.
* The OpenShift CLI installed on your computer, available from the
https://access.redhat.com/downloads/content/290/ver=3.6/rhel---7/3.6.173.0.5/x86_64/product-software[Download Red Hat OpenShift Container Platform] page on the Red Hat Customer Portal.
* The `jboss-bpmsuite-7.0.0.Beta02-openshift.zip` file, available from the site that contains this document, extracted to your hard drive.
* An OpenShift product image uploaded to either and external Docker repository or an internal OpenShift registry. For more information, see <<openshift_ext_repo_create_proc>> and <<openshift_int_reg_create_proc>>.

.Procedure
. Use the OpenShift CLI to log in to your OpenShift environment.
. Enter the following command to create a new OpenShift project that will contain Red Hat BPM Suite, where `<bpms-project>` is the name of your new project:
+
[source,bash]
----
$ oc new-project <bpms-project>
----
. If your product image is located in an external Docker repository, enter the following command to create image streams in your project, where `<image-streams-path>` is the path to the `application-template\image_streams.json` file in the `zip` archive that you downloaded:
+
[source,bash]
----
$ oc create -f <image-streams-path>/image_streams.json -n <bpms-project>
----
An image stream provides the location of binaries to be installed into OpenShift. If your product image is in the internal registry, you do not need to update the `image_streams.json` file.
+
. Use one of the following procedures to install a template:
+
* <<openshift_temp_businesscentral_monitoring_install_proc>>
* <<#openshift_temp_businesscentral_monitoring_smart_router_install_proc>>
* <<openshift_temp_businesscentral_mysql_install_proc>>
* <<openshift_temp_executionserver_install_proc>>
* <<openshift_temp_executionserver_postgresql_install_proc>>
* <<openshift_temp_bpmsuite_s2i_install_proc>>
* <<openshift_temp_bpmsuite_mysql_install_proc>>
* <<openshift_temp_bpmsuite_mysql_persistent_install_proc>>


