[id='openshift-ba-dm-con']
= Installing on OpenShift
OpenShift Container Platform is a platform as a service (PaaS) offering from Red Hat that brings together Docker and Kubernetes, and provides an API to manage these services. With OpenShift, you can create and manage containers that enable you to scale your stateless {PRODUCT} services so that you can reduce resource overheads.

With {PRODUCT} {RELEASE}, the {PRODUCT} on OpenShift files are provided in the `jboss-bpmsuite-7.0.0.LA-openshift.zip` file. This file contains the following directories and contents:

* The `application-template` directory contains OpenShift templates.
* The `BPMS-7.0.0.GA` directory contains productized binaries which you can use to build your own images.
*  The `openshift-image-source` directory contains scripts that can be used to create OpenShift images based on previous Docker images.
* The `standalone-image-source` directory contains scripts that can be used to create Docker images without any OpenShift dependencies.
* The top-level directory contains OpenShift-BPMS product image TAR files.

There are two ways to make the product image TAR files available in OpenShift:

* Upload the product image TAR file to an external Docker registry.
* Upload the product image directly to the OpenShift internal registry.
