[#openshift_ext_repo_create_proc]

= Uploading the Product Image to an External Docker Registry
The simplest way to make your product image available to OpenShift is to upload it to an external Docker registry. After you have uploaded your product image, you can use an image stream file to upload it to any OpenShift instance that you have access to.

.Prerequisites
* You are logged in to an external Docker registry.
* You have downloaded and unzipped the `jboss-bpmsuite-7.0.0.Beta02-openshift.zip` file on your local hard drive.

.Procedure
. Enter the following command where `<product-image-path>` is the path to the product image TAR file in the top-level directory of the unzipped `jboss-bpmsuite-7.0.0.Beta02-openshift.zip` file:
+
[source,bash]
----
$ docker load -i <product-image-path>
----
This command uploads the product image to the local Docker registry.
+
. Enter the following command to update the Docker registry meta data with the source of your product image:
+
[source,bash]
----
$ docker tag docker-registry.engineering.redhat.com/jboss-bpmsuite-7/<product-image-name> <docker-IP>:<docker port>/<image-registry-name> 
----
Replace the variables in this command as follows:
* `<product-image-name>` is the name of the product image that you uploaded to the local Docker registry (the name of the TAR file without the `.tar` extension).
* `<docker-IP>` is the external Docker registry IP address.
* `<docker-port>` is the external Docker registry port.
* `<image-registry-name>` is a name that you give the external registry that you will use for the image, for example `bpmsuite70-smartrouter-openshift:1.0.Beta02`.
+
. Enter the following command to push the image to the external registry that you created in the previous step:
+
[source,bash]
----
$ docker push <docker-IP>:<docker_port>/<image-registry-name> 
----
+
. Open the `bpmsuite-image-stream.json` file in a text editor, then  replace the value of the `dockerImageRepository` attribute with the path to the external Docker registry, `<docker-IP>:<docker_port>/<image-registry-name>`.

.Next Step
Follow the instructions in <<openshift_image_install_proc>>.



