[id='patches-applying-proc']

= Applying patch updates to {PRODUCT}

Patch updates of {PRODUCT} typically include the latest security updates and bug fixes. Scheduled patch updates contain all previously released patch updates for that minor version of the product, so you do not need to apply each patch update incrementally in order to apply the latest update. For example, you can update {PRODUCT} {PRODUCT_VERSION}.0 or {PRODUCT_VERSION}.1 to {PRODUCT} {PRODUCT_VERSION}.2. However, to keep your {PRODUCT} distribution current with the latest fixes, apply patch updates to {PRODUCT} as they become available in the Red Hat Customer Portal.

Automated patch tools are often provided with patch releases to facilitate updating certain components of {PRODUCT}, such as {CENTRAL}, {KIE_SERVER}, and the headless Process Automation Manager controller. Other {PRODUCT} artifacts, such as the {ENGINE} and standalone {CENTRAL}, are released as new artifacts with each patch update and you must re-install them to apply the update.

NOTE: Only updates for {PRODUCT} are included in {PRODUCT} patch updates. Patches to {EAP} must be applied using {EAP} patch distributions. For more information about {EAP} patching, see the {EAP} https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html/patching_and_upgrading_guide/[Patching and upgrading guide].

.Prerequisite
Your {PRODUCT} and {KIE_SERVER} instances are not running. Do not apply patch updates while you are running an instance of {PRODUCT} or {KIE_SERVER}.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options.
+
--
Example:

* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}.1
--
. Click *Patches*, download *{PRODUCT} [VERSION] Patch Update*, and extract the downloaded `{PRODUCT_INIT}-$VERSION-patch.zip` file to a temporary directory.
+
This patch update tool automates the update of certain components of {PRODUCT}, such as {CENTRAL}, {KIE_SERVER}, and the headless Process Automation Manager controller. Use this update tool first to apply updates and then install any other patch updates or new release artifacts that are relevant to your {PRODUCT} distribution.
+
. If you want to preserve any files from being updated by the patch update tool, navigate to the extracted `{PRODUCT_INIT}-$VERSION-patch` folder, open the `blacklisted.txt` file, and add the relative paths to the files that you do not want to be updated.
+
--
When a file is listed in the `blacklist.txt` file, the patch update script does not replace the file with the new version but instead leaves the file in place and in the same location adds the new version with a `.new` suffix. If you blacklist files that are no longer being distributed, the patch update tool creates an empty marker file with a `.removed` suffix. You can then choose to retain, merge, or delete these new files manually.

Example files to be excluded in `blacklisted.txt` file:
[source]
----
WEB-INF/web.xml  // Custom file
styles/base.css  // Obsolete custom file kept for record
----

The contents of the blacklisted file directories after the update:
[source]
----
$ ls WEB-INF
web.xml web.xml.new
----

[source]
----
$ ls styles
base.css base.css.removed
----
--
. In your command terminal, navigate to the temporary directory where you extracted the `{PRODUCT_INIT}-$VERSION-patch.zip` file and run the `apply-updates` script in the following format:
+
--
IMPORTANT: Make sure that your {PRODUCT} and {KIE_SERVER} instances are not running before you apply patch updates. Do not apply patch updates while you are running an instance of {PRODUCT} or {KIE_SERVER}.

On Linux or Unix-based systems:
[source]
----
$ ./apply-updates.sh $DISTRO_PATH $DISTRO_TYPE
----

On Windows:
[source]
----
$ ./apply-updates.bat $DISTRO_PATH $DISTRO_TYPE
----

The `$DISTRO_PATH` portion is the path to the relevant distribution directory and the `$DISTRO_TYPE` portion is the type of distribution that you are updating with this patch.

The following distribution types are supported in {PRODUCT} patch update tool:

* `{URL_COMPONENT_CENTRAL}-eap7-deployable`: Updates {CENTRAL} (`{URL_COMPONENT_CENTRAL}.war`)
* `kie-server-ee7`: Updates {KIE_SERVER} (`kie-server.war`)
ifdef::DM[]
* `kie-server-jws`: Updates {KIE_SERVER} on Red Hat JBoss Web Server (`kie-server.war`)
endif::DM[]
* `controller-ee7`: Updates the headless Process Automation Manager controller (`controller.war`)
ifdef::DM[]
* `controller-jws`: Updates the headless Process Automation Manager controller on Red Hat JBoss Web Server (`controller.war`)
endif::DM[]

Example patch update to {CENTRAL} and {KIE_SERVER} for a full {PRODUCT} distribution on {EAP}:
[source,subs="attributes+"]
----
./apply-updates.sh ~EAP_HOME/standalone/deployments/{URL_COMPONENT_CENTRAL}.war {URL_COMPONENT_CENTRAL}-eap7-deployable

./apply-updates.sh ~EAP_HOME/standalone/deployments/kie-server.war kie-server-ee7
----

Example patch update to headless Process Automation Manager controller, if used:
[source]
----
./apply-updates.sh ~EAP_HOME/standalone/deployments/controller.war controller-ee7
----

The patch update script creates a `backup` folder in the extracted `{PRODUCT_INIT}-$VERSION-patch` folder with a copy of the specified distribution, and then proceeds with the update.
--
. After the update tool completes, return to the *Software Downloads* page of the Red Hat Customer Portal where you downloaded the patch update tool and install any other patch updates or new release artifacts that are relevant to your {PRODUCT} distribution.
+
For files that already exist in your {PRODUCT} distribution, such as `.jar` files for the {ENGINE} or other add-ons, replace the existing version of the file with the new version from the Red Hat Customer Portal.
. If you use the standalone *{PRODUCT} {PRODUCT_VERSION_LONG} Maven Repository* artifact (`{PRODUCT_FILE}-maven-repository.zip`), such as in air-gap environments, download *{PRODUCT} [VERSION] Incremental Maven Repository* and extract the downloaded `{PRODUCT_INIT}-$VERSION-incremental-maven-repository.zip` file to your existing `~/maven-repository` directory to update the relevant contents.
+
--
Example:
ifdef::DM[]
[source,subs="attributes+"]
----
$ unzip -o rhdm-7.0.1-incremental-maven-repository.zip -d $REPO_PATH/rhdm-7.0.0.GA-maven-repository/maven-repository/
----
endif::DM[]
ifdef::PAM[]
[source]
----
$ unzip -o rhpam-7.0.1-incremental-maven-repository.zip -d $REPO_PATH/rhpam-7.0.0-maven-repository/maven-repository/
----
endif::PAM[]
--
. After you finish applying all relevant updates, start {PRODUCT} and {KIE_SERVER} and log in to {CENTRAL}.
. Verify that all project data is present and accurate in {CENTRAL}, and in the top-right corner of the {CENTRAL} window, click your profile name and click *About* to verify the updated product version number.
+
If you encounter any patching errors or notice any missing data in {CENTRAL}, you can restore the contents in the `backup` folder within the `{PRODUCT_INIT}-$VERSION-patch` folder to revert the patch update tool changes. You can also re-install the relevant release artifacts from your previous version of {PRODUCT} in the Red Hat Customer Portal. After restoring your previous distribution, you can try again to run the patch update.
