[id='patches-notifications-proc']

= Enabling {PRODUCT} notifications in the Red Hat Customer Portal

You can enable notifications in the Red Hat Customer Portal to receive {PRODUCT} updates and announcements. These notifications inform you of updated or added documentation, product releases, and patch updates related to {PRODUCT}. With notifications enabled, you can more readily apply product updates to {PRODUCT} as they become available in the Red Hat Customer Portal to keep your {PRODUCT} distribution current with the latest enhancements and fixes.

.Prerequisite
You have a Red Hat Customer Portal account and are logged in.

.Procedure
. In the top-right corner of the Red Hat Customer Portal window, click your profile name and click *Notifications*.
. Select the *Notifications* tab and click *Manage Notifications*.
. Next to *Follow*, select *Products* from the drop-down menu, and then select *{PRODUCT}* from the next drop-down menu that appears.
. Click *Save Notification* to finish.

You can add notifications for any other products as needed in the same way.
