[id='product-versioning-con']

= {PRODUCT} versioning

{PRODUCT} versions are designated with a numerical `Major.Minor.Patch` format, such as `7.2.1`. In this example, the major release is `7.x.x`, the minor release is `7.2.x`, and the patch release is `7.2.1`. Major releases often require data migration, while minor release upgrades and patch updates are typically managed with upgrade and update tools provided with the {PRODUCT} release artifacts.

The following are descriptions of major, minor, and patch releases for {PRODUCT}:

Major release migrations::

Major releases of {PRODUCT} include substantial enhancements, security updates, bug fixes, and possibly redesigned features and functions. Data migration may be required when an application is moved from one major release to another major release, such as from {PRODUCT_OLD} 6.4 to {PRODUCT} 7.0. Automated migration tools are often provided with new major versions of {PRODUCT} to facilitate migration, but some manual effort is occasionally required for certain data and configurations. The supported migration paths are specified in product announcements and documentation.
+
For example, for information about migrating from {PRODUCT_OLD} 6.4 to {PRODUCT} {PRODUCT_VERSION}, see {URL_MIGRATING_6.4_TO_7.X}[_{MIGRATING_6.4_TO_7.X}_]

Minor release upgrades::

Minor releases of {PRODUCT} include enhancements, security updates, and bug fixes. Data migration is not typically required when an application is upgraded to the next minor release, such as from {PRODUCT} 7.0 to {PRODUCT} 7.1. Automated upgrade tools are often provided with new minor versions of {PRODUCT} to facilitate upgrading.
+
Minor release upgrades currently do not apply to {PRODUCT} {PRODUCT_VERSION}.

Patch updates::

Patch updates of {PRODUCT} typically include the latest security updates and bug fixes. A patch update tool is provided with new patch releases to update the product version to the newer patch release, such as from {PRODUCT} {PRODUCT_VERSION}.0 or {PRODUCT_VERSION}.1 to {PRODUCT} {PRODUCT_VERSION}.2. Scheduled patch updates contain all previously released patch updates for that minor version of the product, so you do not need to apply each patch update incrementally in order to apply the latest update. Occasionally, unscheduled patch updates may be released outside the normal update cycle of the existing product. These may include security or other updates provided by Red Hat Global Support Services (GSS) to fix specific issues, and may not be cumulative updates.

To keep your {PRODUCT} distribution current with the latest enhancements and fixes, apply product updates to {PRODUCT} as they become available in the Red Hat Customer Portal. For information about enabling product notifications, see xref:patches-notifications-proc[].
