[id='run-standalone-properties-con']
= Supported properties

When you install standalone {CENTRAL}, you can use the properties listed in this section in the following command:
[source,subs="attributes+"]
----
java -jar {PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-standalone.jar -s application-config.yaml -D<property>=<value> -D<property>=<value>
----
In this command, `<property>` is a property from the following list and `<value>` is a value that you assign to that property:

* `org.uberfire.nio.git.dir`: Location of the {KIE_SERVER} Git directory.
* `org.uberfire.nio.git.dirname`: Name of the {KIE_SERVER} Git directory. Default value: `.niogit`.
* `org.uberfire.nio.git.daemon.enabled`: Enables or disables the Git daemon. Default value: `true`.
* `org.uberfire.nio.git.daemon.host`: If the Git daemon is enabled, it uses this property as the local host identifier. Default value: `localhost`.
* `org.uberfire.nio.git.daemon.port`: If the Git daemon is enabled, it uses this property as the port number. Default value: `9418`.
* `org.uberfire.nio.git.ssh.enabled`: Enables or disables the SSH daemon. Default value: `true`.
* `org.uberfire.nio.git.ssh.host`: If the SSH daemon enabled, it uses this property as the local host identifier. Default value: `localhost`.
* `org.uberfire.nio.git.SSH.port`: If the SSH daemon is enabled, it uses this property as the port number. Default value: `8001`.
* `org.uberfire.nio.git.ssh.cert.dir`: Location of the `.security` directory where local certificates are stored. Default: the working directory.
* `org.uberfire.nio.git.ssh.passphrase`: Pass phrase used to access the public key store of your operating system when cloning git repositories with SCP style URLs. Example: `git@github.com:user/repository.git`.
* `org.uberfire.nio.git.ssh.algorithm`: Algorithm used by SSH. Default value: `DSA`.
+
[NOTE]
====
If you plan to use RSA or any algorithm other than DSA, make sure you set up your application server to use the Bouncy Castle JCE library.
====
* `org.uberfire.metadata.index.dir`: Place where the Lucene `.index` directory is stored. Default: the working directory.
* `org.uberfire.ldap.regex.role_mapper`: Regex pattern used to map LDAP principal names to the application role name. Note that the variable role must be part of the pattern because it is substituted by the application role name when matching a principal value to a role name. Default: Not used.
* `org.uberfire.sys.repo.monitor.disabled`: Disables the configuration monitor. Do not disable unless you are sure. Default value: `false`.
* `org.uberfire.secure.key`: Password used by password encryption. Default value: `org.uberfire.admin`.
* `org.uberfire.secure.alg`: Crypto algorithm used by password encryption. Default value: `PBEWithMD5AndDES`.
* `org.uberfire.domain`:  Security-domain name used by uberfire. Default value: `ApplicationRealm`.
* `org.guvnor.m2repo.dir`: Place where the Maven repository folder is stored. Default value: `<working-directory>/repositories/kie`.
* `org.guvnor.project.gav.check.disabled`: Disables group ID, artifact ID, and version (GAV) checks. Default value: `false`.
* `org.kie.example`: Enables external cloning of a demo application from GitHub.
* `org.kie.build.disable-project-explorer`: Disables automatic build of a selected project in Project Explorer. Default value: `false`.
* `org.kie.verification.disable-dtable-realtime-verification`: Disables the real-time validation and verification of decision tables. Default value: `false`.
* `org.kie.server.controller`: URL for connecting with a Kie Server Controller, for example: `ws://localhost:8080/{URL_COMPONENT_CENTRAL}/websocket/controller`.
* `org.kie.server.user`: User name used to connect with the {KIE_SERVER} nodes from the controller. This property is only required when using this {CENTRAL} installation as a controller.
* `org.kie.server.pwd`: Password used to connect with the {KIE_SERVER} nodes from the controller. This property is only required when using this {CENTRAL} installation as a controller.
