[id='bus-app-config-jpa_{context}']
= Configuring business applications for JPA

The Java Persistence API (JPA) is a standard technology that enables you to map objects to relational databases. Hibernate is one of the most popular JPA implementations. Because Process Automation Manager and Decision manager use Hibernate as the database access layer, you must configure JPA for your business application if you use the H2 database.

[NOTE]
====
If you want to use a MySQL or PostgreSQL database with your business appplication, see <<bus-app-config-data-source_{context}>>. In that case, you do not need to configure your business application for JPA.
====

.Prerequisite
* You have a `<business-application>.zip` file that you created using the http://start.jbpm.org[business applications]  web site.
* You want to use the default H2 database with this business application.

.Procedure
. Unzip the `<business-application>.zip` file and navigate to the `<business-application>/<business-application>-service/src/main/resources` folder.
. Open the `application.properties` file in a text editor.
. Find the following parameters in the `application.properties` file and verify that they have the values shown:
+
[source, bash]
----
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
----
. If your business application has business automation capabilities, you can add entities to the entity manager factory by adding a comma-separated listed of packages:
+
[source, bash]
----
spring.jpa.properties.entity-scan-packages=org.jbpm.springboot.samples.entities
----
+ 
Business applications with business automation capabilities create an entity manager factory based on the `persistence.xml` that comes with Process Automation Manager. All entities found in the `org.jbpm.springboot.samples.entities` package are automatically added to the entity manager factory and used the same as any other JPA entity in the application.
[See Also]
====
For more information about configuring JPA, see the  https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle[_Spring Boot Reference Guide_].
====
