[id='bus-apps-run-managed_{context}']

= Running business applications in development mode

Development (managed) mode enables developers to work on a {PRODUCT} business application business assets project and dynamically deploy changes to the business application without the need to restart it. In addition, development mode provides a complete monitoring environment for business automation capabilities, for example process instances, tasks, and jobs.

.Prerequisites
* You have a Spring Boot business application.
* You configured the business application.
* {CENTRAL} is installed and running.

.Procedure
. Navigate to the `<BUSINESS-APPLICATION>/<BUSINESS-APPLICATION>-service` folder, where `<BUSINESS-APPLICATION>` is the name of your Spring Boot project.
. Enter one of the following commands:
+
.Managed launch options
[cols="50%,50%"]
|===
|Command
|Description

|`./launch-dev.sh clean install`
|Launches in development mode on Linux or UNIX.

|`./launch-dev.bat clean install`
|Launches in development mode on Windows.

|`./launch-dev.sh clean install -Pmysql`
|Launches in development mode on Linux or UNIX if you have configured the application with a MySQL database.

|`./launch-dev.bat clean install -Pmysql`
|Launches in development mode on Windows if you have configured the application with a MySQL database.

|`./launch-dev.sh clean install -Ppostgres`
|Launches in development mode on Linux or UNIX if you have configured the application with a postgreSQL database.

|`./launch-dev.bat clean install -Ppostgres`
|Launches in development mode on Windows if you have configured the application with a PostgreSQL database.

|===
+
The `clean install` argument directs Maven to build a fresh installation. The projects are then built in the following order:
+
* Data model
* Business assets
* Service
+
The first time that you run the script, it might take a while to build the project because all dependencies of the project are downloaded. At the end of the build, the application starts.
. Enter the following command to access your business application:
+
[source]
----
http://localhost:8090/
----
. Enter the credentials `user`/`user`  or `kieserver`/`kieserver1!`. After the business application starts, it connects to the {CONTROLLER} and is visible in *Menu* -> *Deploy* -> *Execution Servers* in {CENTRAL}.
