[id='bus-app-keycloak_{context}']
= Configuring the business application with Red Hat Single-On

You can use Red Hat Single Sign-On (RH SSO) to enable single sign-on between your services and to have a central place to configure and manage your users and roles. 

.Prerequisite
You have a `<business-application>.zip` file that you created using the http://start.jbpm.org[business applications] web site.

.Procedure
. Follow the instrucfollow official documentation at http://keycloak.org[keycloak.org]
* Configure RH SSO once started
** Use default master realm or create new one
** Create client named springboot-app and set its AccessType to public
** Set Valid redirect URI and Web Origin according to your local setup - with default setup they should be set to
** Valid Redirect URIs: http://localhost:8090/*
** Web Origins: http://localhost:8090
** Create realm roles that are used in the application
** Create users used in the application and assign roles to them
* Configure dependencies in service project pom.xml

[source, xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.keycloak.bom</groupId>
      <artifactId>keycloak-adapter-bom</artifactId>
      <version>${version.org.keycloak}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

  ....

<dependency>
  <groupId>org.keycloak</groupId>
  <artifactId>keycloak-spring-boot-starter</artifactId>
</dependency>
----



* Configure application.properties

[source, bash]
----
# keycloak security setup
keycloak.auth-server-url=http://localhost:8100/auth
keycloak.realm=master
keycloak.resource=springboot-app
keycloak.public-client=true
keycloak.principal-attribute=preferred_username
keycloak.enable-basic-auth=true
----

These are the steps to configure you business application to use RH SSO as
authentication and authorisation service.

