[id='bus-app-user-group_{context}']
= Configuring business application user group providers

With {PRODUCT}, you can manage human-centric activities. To provide integration with user and group repositories, there are two KIE API entry points available:

* `UserGroupCallback`: Responsible for verifying whether a user or group exists and for collecting groups for a specific user
* `UserInfo`: Responsible for collecting additional information about users and groups, for example email addresses and preferred language

You can configure both of these components by providing alternative code, either code provided out of the box or custom developed code.

For the `UserGroupCallback` component, retain the default implementation because it is based on the security context of the application. For this reason, it does not matter which backend store is used for authentication and authorisation (for example, RH-SSO). It will be automatically used as a source of information for collecting user and group information.

Because `UserInfo` must collect more advanced information, it is a separate component. 

.Prerequisites
* You have a `<business-application>.zip` file that you created using the http://start.jbpm.org[business application] web site and that contains a business automation project.

.Procedure
. To provide an alternative implementation of `UserGroupCallback`, add the following code to the Application class or a separate class annotated with `@Configuration`:

+
[source, java]
----
@Bean(name = "userGroupCallback")
public UserGroupCallback userGroupCallback(IdentityProvider identityProvider) throws IOException {
    return new MyCustomUserGroupCallback(identityProvider);
}
----
. To provide an alternative implementation of `UserInfo`, add the following code to the Application class or a separate class annotated with `@Configuration`:
+
[source, java]
----
@Bean(name = "userInfo")
public UserInfo userInfo() throws IOException {
    return new MyCustomUserInfo();
}
----