[id='bus-app-rh-sso_{context}']
= Configuring the business application with {RH-SSO}

Most organizations provide user and group details through single sign-on (SSO) tokens. You can use {RH-SSO} (RHSSO) to enable single sign-on between your services and to have a central place to configure and manage your users and roles.

.Prerequisites
* You have a Spring Boot application ZIP file that you created using the http://start.jbpm.org[business applications] website.

.Procedure
. Download and install RHSSO. For instructions, see the https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/{RH-SSO_VERSION}/html/getting_started_guide/[_{RH-SSO} Getting Started Guide_].
. Configure RHSSO:
.. Either use the default master realm or create a new realm.
+
A realm manages a set of users, credentials, roles, and groups. A user belongs to and logs into a realm. Realms are isolated from one another and can only manage and authenticate the users that they control.
.. Create the `springboot-app` client and set the `AccessType` to public.
.. Set a valid redirect URI and web origin according to your local setup, as shown in the following example:
+
* Valid redirect URIs: `\http://localhost:8090/*`
* Web origin: `\http://localhost:8090`
.. Create realm roles that are used in the application.
.. Create users that are used in the application and assign roles to them.
. Add the following element and property to the Spring Boot project `pom.xml` file, where `<KEYCLOAK_VERSION>` is the version of Keycloak that you are using:
+
[source, xml]
----
<properties>
  <version.org.keycloak><KEYCLOAK_VERSION></version.org.keycloak>
</properties>
----
. Add the following dependencies to the Spring Boot project `pom.xml` file:
+
[source, xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.keycloak.bom</groupId>
      <artifactId>keycloak-adapter-bom</artifactId>
      <version>${version.org.keycloak}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

  ....

<dependency>
  <groupId>org.keycloak</groupId>
  <artifactId>keycloak-spring-boot-starter</artifactId>
</dependency>
----

. In your Spring Boot project directory, open the `business-application-service/src/main/resources/application.properties` file and add the following lines:
+
[source]
----
# keycloak security setup
keycloak.auth-server-url=http://localhost:8100/auth
keycloak.realm=master
keycloak.resource=springboot-app
keycloak.public-client=true
keycloak.principal-attribute=preferred_username
keycloak.enable-basic-auth=true
----
. Modify the `business-application-service/src/main/java/com/company/service/DefaultWebSecurityConfig.java` file to ensure that Spring Security works correctly with RHSSO:
+
[source, java]
----
import org.keycloak.adapters.KeycloakConfigResolver;
import org.keycloak.adapters.springboot.KeycloakSpringBootConfigResolver;
import org.keycloak.adapters.springsecurity.authentication.KeycloakAuthenticationProvider;
import org.keycloak.adapters.springsecurity.config.KeycloakWebSecurityConfigurerAdapter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.core.authority.mapping.SimpleAuthorityMapper;
import org.springframework.security.core.session.SessionRegistryImpl;
import org.springframework.security.web.authentication.session.RegisterSessionAuthenticationStrategy;
import org.springframework.security.web.authentication.session.SessionAuthenticationStrategy;

@Configuration("kieServerSecurity")
@EnableWebSecurity
public class DefaultWebSecurityConfig extends KeycloakWebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);
        http
        .csrf().disable()
        .authorizeRequests()
            .anyRequest().authenticated()
            .and()
        .httpBasic();
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        KeycloakAuthenticationProvider keycloakAuthenticationProvider = keycloakAuthenticationProvider();
        SimpleAuthorityMapper mapper = new SimpleAuthorityMapper();
        mapper.setPrefix("");
        keycloakAuthenticationProvider.setGrantedAuthoritiesMapper(mapper);
        auth.authenticationProvider(keycloakAuthenticationProvider);
    }

    @Bean
    public KeycloakConfigResolver KeycloakConfigResolver() {
       return new KeycloakSpringBootConfigResolver();
    }

    @Override
    protected SessionAuthenticationStrategy sessionAuthenticationStrategy() {
        return new RegisterSessionAuthenticationStrategy(new SessionRegistryImpl());
    }
}
----
