[id='bus-app-create_{context}']
= Creating a business application

You can use the https://start.jbpm.org[business application] web site to quickly and easily create business applications using the Spring Boot framework. Doing this by-passes the need to install and configure the Business Automation product.

.Procedure
. Enter the following URL in a web browser:
+
[source]
----
https://start.jbpm.org 
----

. Click *Configure your business application*.
. Select one of the following options and click *Next*:
+
* *Business Automation*: Creates a Process Automation Manager application. Includes features for process management, case management, decision management, and optimization.
* *Decision Management*: Creates a Decision Manager application. Includes decision rules and rules-related features.
* *Business Optimization*: Creates a Business Optimizer application. Includes planning problems and solutions-related features.
. Enter a package and application name.
. From the *Version* menu, select *Enterprise {PRODUCT_VERSION}* and click *Next*.
+
[NOTE]
====
You must select *Enterprise {PRODUCT_VERSION}* to create a Red Hat Business Automation business application.
====
. Select the project types that you want to include in your project. You can include more than one project type.
+
* *Business Assets*: Contains business processes, rules, and forms and are easily imported into Business Central or Decision Central (depending on the application type).  Select *Dynamic Assets* instead if you want to add adaptive and dynamic assets such as cases.
* *Data Model*: Provides common data structures that are shared between the service projects and business assets projects. This enables proper encapsulation, promotes reuse, and reduces shortcuts. Each service project can expose its own public data model.
* *Service*: Includes business logic that operates your business.
. Click *Generate business application*.
+
The `<business-application>.zip` file downloads, where `<business-application>` is the name that you entered in the *Application Name* box.
