[id='bus-apps-import_{context}']
= Importing business assets projects into and deploying from Business Central and Decision Central
Comment: Does this apply to Decision Central as well? 

You can import a business assets project that is part of a Red Hat Business Automation business application into Business Central or Decision Central and then deploy that project to a running service instance.

.Prerequistes
* You have a `<business-application>.zip` file that contains a business assets project, that you created using the http://start.jbpm.org[business applications] web site.
* {PRODUCT} {CENTRAL} is installed.

.Procedure
. Navigate to the `<business-application>/<business-application>-kjar` folder.
. Execute the following following commands to initialize the Git repository for your project:
+
[source]
----
$ git init
$ git add -A
$ git commit -m "Initial project structure"
----

. Log in to {CENTRAL} and go the *Projects* page.
. Select *Import Project* and enter following URL:
+
[source]
----
 file:///<business-application-path>/<business-application-name>-kjar
----
 
. Click *Import* and confirm project to be imported.
. After the business assets project is imported into {CENTRAL}, open the project and click *Add Assets* to add assets such as business processes, rules, and decision tables to your business assets project.
. Click *Deploy* on your project page to deploy your project to a running server.
. Use the *Process Definitions* and *Process Instance* perspectives of {CENTRAL}
to interact with your newly deployed business assets.