[id='bus_app_{context}']
= {PRODUCT} Spring Boot business applications

Spring Framework is a Java platform that provides comprehensive infrastructure support for developing Java applications. Spring Boot is a lightweight framework based on Spring Boot starters. Spring Boot starters are `pom.xml` files that contain a set of dependency descriptors that you can include in your Spring Boot project.

{PRODUCT} Spring Boot business applications are flexible, UI-agnostic logical groupings of individual services that provide certain business capabilities. Business applications are based on Spring Boot starters. They are usually deployed separately and can be versioned individually. A complete business application enables a domain to achieve specific business goals, for example, order management or accommodation management. After you create and configure your business application, you can deploy it to an existing service or to the cloud, through OpenShift.

Business applications can contain one or more of the following projects and more than one project of the same type:

* Business assets (KJAR): Contains business processes, rules, and forms and are easily imported into {CENTRAL}.
* Data model: Data model projects provide common data structures that are shared between the service projects and business assets projects. This enables proper encapsulation, promotes reuse, and reduces shortcuts. Each service project can expose its own public data model.
* Dynamic assets: Contains assets that you can use with case management.
* Service: A deployable project that provides the actual service with various capabilities. It includes the business logic that operates your business. In most cases, a service  project includes business assets and data model projects. A business application can split services into smaller component service projects for better manageability.
