[id='bus-app-quartz_{context}']
= Configuring the business application for a cluster using Quartz

If you plan to run your application in a cluster, you must configure the Quartz timer service.

.Prerequisites
* You have a Spring Boot business application service file that you created using the Maven archetype command. For more information, see xref:bus-app-create_{context}[].

.Procedure

. Create the `quartz.properties` file and add the following content:
+
[source, bash]
----
#============================================================================
# Configure Main Scheduler Properties
#============================================================================
org.quartz.scheduler.instanceName = SpringBootScheduler
org.quartz.scheduler.instanceId = AUTO
org.quartz.scheduler.skipUpdateCheck=true
org.quartz.scheduler.idleWaitTime=1000
#============================================================================
# Configure ThreadPool
#============================================================================
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 5
org.quartz.threadPool.threadPriority = 5
#============================================================================
# Configure JobStore
#============================================================================
org.quartz.jobStore.misfireThreshold = 60000
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreCMT
org.quartz.jobStore.driverDelegateClass=org.jbpm.process.core.timer.impl.quartz.DeploymentsAwareStdJDBCDelegate
org.quartz.jobStore.useProperties=false
org.quartz.jobStore.dataSource=myDS
org.quartz.jobStore.nonManagedTXDataSource=notManagedDS
org.quartz.jobStore.tablePrefix=QRTZ_
org.quartz.jobStore.isClustered=true
org.quartz.jobStore.clusterCheckinInterval = 5000
#============================================================================
# Configure Datasources
#============================================================================
org.quartz.dataSource.myDS.connectionProvider.class=org.jbpm.springboot.quartz.SpringConnectionProvider
org.quartz.dataSource.myDS.dataSourceName=quartzDataSource
org.quartz.dataSource.notManagedDS.connectionProvider.class=org.jbpm.springboot.quartz.SpringConnectionProvider
org.quartz.dataSource.notManagedDS.dataSourceName=quartzNotManagedDataSource
----

+
[NOTE]
====
Data source names in the Quartz configuration file refer to Spring beans. The connection provider must be set to `org.jbpm.springboot.quartz.SpringConnectionProvider`
to enable integration with Spring-based data sources.
====
. To enable the Quartz clustered timers and set the path of the `quartz.properties` file that you created in the previous step, include the following properties in the `<BUSINESS-APPLICATION>/<BUSINESS-APPLICATION>-service/src/main/resourcesapplication.properties` file, where `<BUSINESS-APPLICATION>` is the name of your Spring Boot project.
+
[source, bash]
----
jbpm.quartz.enabled=true
jbpm.quartz.configuration=quartz.properties
----
. Create a managed and an unmanaged data source by adding the following content to the `<BUSINESS-APPLICATION>/<BUSINESS-APPLICATION>-service/src/main/resources/application.properties` file:
+
[source, bash]
----
# enable to use database as storage
jbpm.quartz.db=true

quartz.datasource.name=quartz
quartz.datasource.username=sa
quartz.datasource.password=sa
quartz.datasource.url=jdbc:h2:./target/spring-boot-jbpm;MVCC=true
quartz.datasource.driver-class-name=org.h2.Driver

# used to configure connection pool
quartz.datasource.dbcp2.maxTotal=15

# used to initialize quartz schema
quartz.datasource.initialization=true
spring.datasource.schema=classpath*:<QUARTZ_TABLES_H2>.sql
spring.datasource.initialization-mode=always
----
+
In the preceding example, replace `<QUARTZ_TABLES_H2>` with the name of a Quartz H2 database schema script. The last three lines of the preceding configuration initialize the
database schema.

By default, Quartz requires two data sources:

* Managed data source to participate in the transaction of the {DECISION_ENGINE}
ifdef::PAM[]
or {PROCESS_ENGINE}
endif::[]
* Unmanaged data source to look up timers to trigger without any transaction handling

{PRODUCT} business applications assume that the Quartz database (schema) will be co-located with {PRODUCT} tables and therefore produce data sources used for transactional operations for Quartz.

The other (non transactional) data source must be configured but it should point
to the same database as the main data source.
