[id='bus-apps-import_{context}']
= Importing and deploying business assets projects in {CENTRAL}

You can import a business assets project that is part of a {PRODUCT} business application into {CENTRAL} and then deploy that project to a business application.

.Prerequisites
* You have a business application project running in development mode.
* {PRODUCT} {CENTRAL} is installed.

.Procedure
. Navigate to the `<BUSINESS-APPLICATION>/<BUSINESS-APPLICATION>-kjar` folder, where `<BUSINESS-APPLICATION>` is the name of your Spring Boot project.
. Execute the following following commands to initialize the Git repository for your project:
+
[source]
----
$ git init
$ git add -A
$ git commit -m "Initial project structure"
----

. Log in to {CENTRAL} and go to *Menu* -> *Design* -> *Projects*.
. Select *Import Project* and enter the following URL:
+
[source]
----
 file:///<business-application-path>/<business-application-name>-kjar
----

. Click *Import* and confirm the project to be imported.
. After the business assets project is imported into {CENTRAL}, open the project and click *Add Assets* to add assets such as
ifdef::PAM[]
business processes to your business assets project.
endif::PAM[]
ifdef::DM[]
rules and decision tables to your business assets project.
endif::DM[]
. Click *Deploy* on your project page to deploy your project to a running business application.
+
[NOTE]
====
You can also select the *Build & Install* option to build the project and publish the KJAR file to the configured Maven repository without deploying to a {KIE_SERVER}. In a development environment, you can click *Deploy* to deploy the built KJAR file to a {KIE_SERVER} without stopping any running instances (if applicable), or click *Redeploy* to deploy the built KJAR file and replace all instances. The next time you deploy or redeploy the built KJAR, the previous deployment unit (KIE container) is automatically updated in the same target {KIE_SERVER}. In a production environment, the *Redeploy* option is disabled and you can click *Deploy* only to deploy the built KJAR file to a new deployment unit (KIE container) on a {KIE_SERVER}.

To configure the {KIE_SERVER} environment mode, set the `org.kie.server.mode` system property to `org.kie.server.mode=development` or `org.kie.server.mode=production`. To configure the deployment behavior for a corresponding project in {CENTRAL}, go to project *Settings* -> *General Settings* -> *Version* and toggle the *Development Mode* option. By default, {KIE_SERVER} and all new projects in {CENTRAL} are in development mode. You cannot deploy a project with *Development Mode* turned on or with a manually added `SNAPSHOT` version suffix to a {KIE_SERVER} that is in production mode.
====

. To review project deployment details, click *View deployment details* in the deployment banner at the top of the screen or in the *Deploy* drop-down menu. This option directs you to the *Menu* -> *Deploy* -> *Execution Servers* page.
ifdef::PAM,JBPM[]
. To interact with your newly deployed business assets, go to *Menu* -> *Manage* -> *Process Definitions* and *Process Instances*.
endif::[]
