[id='bus-app-create_{context}']
= Creating a Spring Boot business application from Maven archetypes

You can use Maven archetypes to create business applications that use the Spring Boot framework. Doing this by-passes the need to install and configure {PRODUCT}.

.Prerequisites
* Apache Maven 3.8 or higher
//please confirm the minimum release

.Procedure
Enter one of the following commands to create your Spring Boot business application project. In these commands, replace `<project>` with the name of your project:

* To create a business asset application:
+
[source,subs="attributes+"]
----
mvn archetype:generate -B -DarchetypeGroupId=org.kie -DarchetypeArtifactId=kie-model-archetype -DarchetypeVersion={COMMUNITY_VERSION_FINAL} -DgroupId=com.company -DartifactId=<project. -Dversion=1.0-SNAPSHOT -Dpackage=com.company.model
----
+
This command creates `org.kie:kie-kjar-archetype:{COMMUNITY_VERSION_FINAL}`.

* To create a data model asset application:
+
[source,subs="attributes+"]
----
mvn archetype:generate -B -DarchetypeGroupId=org.kie -DarchetypeArtifactId=kie-kjar-archetype -DarchetypeVersion={COMMUNITY_VERSION_FINAL} -DgroupId=com.company -DartifactId=<project> -Dversion=1.0-SNAPSHOT -Dpackage=com.company.model
----
+
This command creates `org.kie:kie-kjar-archetype:{COMMUNITY_VERSION_FINAL}`.

* To create a service application:
+
[source,subs="attributes+"]
----
mvn archetype:generate -B -DarchetypeGroupId=org.kie -DarchetypeArtifactId=kie-service-spring-boot-archetype-DarchetypeVersion={COMMUNITY_VERSION_FINAL} -DgroupId=com.company -DartifactId=<project> -Dversion=1.0-SNAPSHOT -Dpackage=com.company.model
----
+
This command creates `org.apache.maven.archetypes:maven-archetype-quickstart:1.3`.
