[id='bus-app-user-group_{context}']
= Configuring business application user group providers

Business automation capability supports the management of human-centric activities. To provide integration with user and group repositories, there are two KIE API entry points available:

* `UserGroupCallback`: Responsible for verifying whether a user or group exists and for collecting groups for a specific user
* `UserInfo`: Responsible for collecting additional information about users and groups, for example email addresses and preferred language

Both of these components can be configured by providing alternative code, either code provided out of the box or custom developed code.

For the `UserGroupCallback` component, it is recommended that you retain the default implementation because it is based on the security context of the application. It uses the back-end store, for example RH-SSO, for authentication and authorization and as source of information for collecting user and group information.

Because `UserInfo` must collect more advanced information, it is a separate component. 

.Prerequisites
* You have a `<business-application>.zip` file that you created using the http://start.jbpm.org[business application] web site and that contains a business automation project.

.Procedure
. To provide an alternative implementation of `UserGroupCallback`, add the following code to the Application class or a separate class annotated with `@configuration`:

+
[source, java]
----
@Bean(name = "userGroupCallback")
public UserGroupCallback userGroupCallback(IdentityProvider identityProvider) throws IOException {
    return new MyCustomUserGroupCallback(identityProvider);
}
----
. To provide an alternative implementation of `UserInfo`, add the following code to the Application class or a separate class annotated with `@configuration`:
+
[source, java]
----
@Bean(name = "userInfo")
public UserInfo userInfo() throws IOException {
    return new MyCustomUserInfo();
}
----