[id='openshift-springboot-proc_{context}']
= Running a SpringBoot business application on {OPENSHIFT}

To run your {PRODUCT} SpringBoot business application on {OPENSHIFT}, create an immutable image and push this image to your {OPENSHIFT} environment.

ifdef::PAM[]
Optionally, you can also use {CENTRAL} Monitoring to monitor the execution of business processes in your application.
endif::PAM[]

.Prerequisites

* You have developed a {PRODUCT} SpringBoot business application. For instructions about creating the application, see xref:bus-app-create_{context}[].
* If necessary, you have configured Spring security for the application. For instructions about configuring Spring security, see xref:bus-app-security-con_{context}[].
* You have completed any necessary additional Spring configuration for the business application. For instructions about Spring configuration for your business application, see xref:bus-app-configure-con_{context}[].
* You created a single JAR file for the business application. For instructions about creating a single JAR file for your SpringBoot business application, see xref:creating-self-contained-image-proc_{context}[].
* You are logged on to your {OPENSHIFT} environment using the `oc` command and the required project is active.
ifdef::PAM[]
* If you want to use {CENTRAL} Monitoring, you have installed {CENTRAL} Monitoring using the operator. Use the same namespace to deploy {CENTRAL} Monitoring and your business application.
+
[IMPORTANT]
====
You must configure {CENTRAL} Monitoring to use the controller startup strategy. To enable the controller strategy on {CENTRAL} Monitoring, in the *Console* tab of the operator configuration, add a `KIE_SERVER_CONTROLLER_OPENSHIFT_ENABLED` environment variable and set it to `false`.
====
endif::PAM[]

.Procedure

. Outside the business application project directories, create an `ocp-image` directory with the following subdirectories:
+
----
ocp-image
|--/root
  |--/opt
    |-- /spring-service
----
+
. Copy the single JAR file for your business application into the `root/opt/spring-service` subdirectory. For example:
+
----
cd ../business-application-service
cp target/business-application-service-1.0-SNAPSHOT.jar ../ocp-image/root/opt/spring-service/
----
+
. In the `ocp-image` directory, create a `Dockerfile` file with the following content:
+
----
FROM registry.access.redhat.com/ubi8/openjdk-11:latest
COPY root /
EXPOSE 8090
WORKDIR /opt/spring-service/
CMD ["sh","-c", "java ${JAVA_OPTIONS} -Dorg.kie.server.mode=PRODUCTION -jar /opt/spring-service/<FILENAME>.jar"]
----
+
Replace `<FILENAME>.jar` with the name of the single JAR file for your business application.
+
ifdef::PAM[]
Alternatively, if you want to configure communication with {CENTRAL} Monitoring, use the following content for `Dockerfile`:
+
----
FROM registry.access.redhat.com/ubi8/openjdk-11:latest
COPY root /
EXPOSE 8090
WORKDIR /opt/spring-service/
CMD ["sh","-c", "java ${JAVA_OPTIONS} -Dorg.kie.server.location=${KIESERVER_LOCATION} -Dorg.kie.server.controller=${KIESERVER_CONTROLLERS} -Dorg.kie.server.controller.user=${KIE_SERVER_CONTROLLER_USER} -Dorg.kie.server.controller.pwd=${KIE_SERVER_CONTROLLER_PWD} -Dorg.kie.server.mode=PRODUCTION -jar /opt/spring-service/<FILENAME>.jar"]
----
+
Replace `<FILENAME>.jar` with the name of the single JAR file for your business application.
+
endif::PAM[]
. To build the initial image and deploy it in your {OPENSHIFT} environment, complete the following steps:
.. To build the image, run the following commands in the `ocp-image` directory:
+
----
oc new-build --binary --strategy=docker --name openshift-kie-springboot
oc start-build openshift-kie-springboot --from-dir=. --follow
----
+
Optional: replace `openshift-kie-springboot` with a custom application name in these commands and all subsequent commands.
+
.. To deploy the image in the {OPENSHIFT} environment, run the following command:
+
----
oc new-app openshift-kie-springboot
----
+
ifdef::PAM[]
Alternatively, to deploy the image and configure it to communicate with {CENTRAL} Monitoring, run the following command:
+
----
oc new-app openshift-kie-springboot -e KIESERVER_LOCATION=http://<LOCATION>:<PORT>/rest/server -e KIESERVER_CONTROLLERS=ws://<BC-HOSTNAME>:<BC-PORT>/websocket/controller -e KIE_SERVER_CONTROLLER_USER=USER -e KIE_SERVER_CONTROLLER_PWD=PASSWORD
----
+
In this command, replace the following values:
+
** `<LOCATION>` with the fully qualified host name for accessing your service. {CENTRAL} Monitoring accesses the service to retrieve process information and displays a URL for the service with this host name
** `<PORT>` with the port for accessing your service, for example, `8090`
** `<BC-HOSTNAME>` with the host name for accessing the {CENTRAL} Monitoring instance. If your application is deployed in the same project/namespace as the {CENTRAL} Monitoring instance, use the service name for {CENTRAL} Monitoring, for example, `myapp-rhpamcentrmon`. Otherwise, you can use use the fully qualified host name of a route for the {CENTRAL} Monitoring instance.
** `<BC-PORT>` with the port of the {CENTRAL} Monitoring instance, for example, `8080`
** `<USER>` with the username of a user configured on the {CENTRAL} Monitoring instance
** `<PASSWORD>` with the password of the user configured on the {CENTRAL} Monitoring instance
+
[NOTE]
====
This configuration uses unsecured HTTP communication for your service. If you configure your Spring Boot business application with a valid SSL certificate, you can replace `http:` with `https:` to use secure HTTPS communication. For more information about configuring SSL on Spring Boot, see https://docs.spring.io/spring-boot/docs/{SPRING_BOOT_VERSION}.RELEASE/reference/html/howto.html#howto-configure-ssl[Spring Boot documentation].
====
+
[NOTE]
====
If you want to view process information from {CENTRAL} Monitoring, you must ensure that the user that is logged into {CENTRAL} Monitoring can also be authenticated with your service using the same password.
====
+
endif::PAM[]
.. Optional: To expose the route for the image, run the following command:
+
----
oc expose service/openshift-kie-springboot --port=8090
----
+
. If you already built and deployed the image and need to update it, for example if you built the JAR file for a new version of {PRODUCT} or of Spring Boot, run the following command in the `ocp-image` directory:
+
----
oc start-build openshift-kie-springboot --from-dir=. --follow
----
