[id='spring-boot-jms-audit-proc_{context}']
= Replicating JMS audit data

You can replicate {KIE_SERVER} audit data in an external database so that you can improve the performance of your Spring Boot application by deleting the audit data from your application schema. This process uses a JMS message broker, for example ActivMQ or Artemis.

When an event occurs in {KIE_SERVER}, the record of that event is stored in the {KIE_SERVER} database schema and it is sent to the message broker, which contains an exact replica of the {KIE_SERVER} database schema. The database in the broker is appended with new transactions when they occur.

NOTE: Only audit data is stored in the message broker. No other data is replicated.

.Prerequistes

.Procedure
. Open the Spring Boot application's `pom.xml` file in a text editor.
. Add the following dependencies to the `pom.xml` file:
+
* {KIE_SERVER} Spring Boot audit dependency
+
[source, xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-server-spring-boot-autoconfiguration-audit-replication</artifactId>
  <version>${version.org.kie}</version>
</dependency>
----
* Advanced Message Queuing Protocal (AMQP) dependency:
+
[source, xml]
----
<dependency>
			<groupId>org.amqphub.spring</groupId>
			<artifactId>amqp-10-jms-spring-boot-starter</artifactId>
			<version>2.2.6</version>
		</dependency>
----
* JMS pool dependency:
+
[source, xml]
----
<dependency>
  <groupId>org.messaginghub</groupId>
  <artifactId>pooled-jms</artifactId>
</dependency>
----
. To configure {KIE_SERVER} audit replication to use queues, complete the following tasks:
+
.. Add the following lines to your Spring Boot application's `application.properties` file where `<PORT>` is the port that your message broker listens on and  `<USERNAME>` and `<PASSWORD` are the login credentials for the message broker:
+
[source]
----
kieserver.audit-replication.producer=true
kieserver.audit-replication.queue=audit-queue
amqphub.amqp10jms.remote-url=amqp://localhost:<PORT>
amqphub.amqp10jms.username=<USERNAME>
amqphub.amqp10jms.password=<PASSWORD>
amqphub.amqp10jms.pool.enabled=true
----
.. Add the following lines to the `application.properties` file of the service that will consume the message broker data, where `<PORT>` is the port that your message broker listens on and  `<USERNAME>` and `<PASSWORD>` are the login credentials for the message broker:
+
[source]
----
kieserver.audit-replication.consumer=true
kieserver.audit-replication.queue=audit-queue
amqphub.amqp10jms.remote-url=amqp://localhost:<PORT>
amqphub.amqp10jms.username=<USERNAME>
amqphub.amqp10jms.password=<PASSWORD>
amqphub.amqp10jms.pool.enabled=true
----
. To configure {KIE_SERVER} audit replication to use topics, complete the following tasks:
+
.. Add the following lines to your Spring Boot application's `application.properties` file where `<PORT>` is the port that your message broker listens on and  `<USERNAME>` and `<PASSWORD` are the login credentials for the message broker:
+
[source]
----
kieserver.audit-replication.producer=true
kieserver.audit-replication.topic=audit-topic
spring.jms.pub-sub-domain=true
amqphub.amqp10jms.remote-url=amqp://localhost:<PORT>
amqphub.amqp10jms.username=<USERNAME>
amqphub.amqp10jms.password=<PASSWORD>
amqphub.amqp10jms.pool.enabled=true
----
.. Add the following lines to the `application.properties` file of the service that will consume the message broker data, where `<PORT>` is the port that your message broker listens on and  `<USERNAME>` and `<PASSWORD>` are the login credentials for the message broker:
+
[source]
----
kieserver.audit-replication.consumer=true
kieserver.audit-replication.topic=audit-topic::jbpm
kieserver.audit-replication.topic.subscriber=jbpm
spring.jms.pub-sub-domain=true
amqphub.amqp10jms.remote-url=amqp://localhost:<PORT>
amqphub.amqp10jms.username=<USERNAME>
amqphub.amqp10jms.password=<PASSWORD>
amqphub.amqp10jms.pool.enabled=true
amqphub.amqp10jms.clientId=jbpm
----
. To configure your application to be read-only so that users can query the replicated audit data but not change anything, add the following line to the `application.properties` file:
+
[source]
----
org.kie.server.rest.mode.readonly=true
----
