[id='spring-boot-persistence-proc_{context}']
= Configuring pluggable variable persistence

You can provide an arbitrary entity manager for configured process variable persistence in your {PRODUCT} Spring Boot application. To do this, add named beans during the object marshalling strategy resolution. This enables you to configure a second entity manager factory based on a second data source qualifier. Note that this configuration will not interfere with the primary data source.

.Prerequisites

* You have an existing {PRODUCT} Spring Boot project.

.Procedure

. Add a customized entity manager JavaBean to your java class. The following example shows an entity manager Java Bean called `auditEntityManager` for a Java Persistence API (JPA) data source:
+
[source, java]
----
    @Bean(name = "auditEntityManager")
    @ConditionalOnMissingBean(name = "auditEntityManager")
    public LocalContainerEntityManagerFactoryBean entityManagerFactory(@Qualifier("jpaAuditDataSource") DataSource dataSource, JpaProperties jpaProperties) {
        return EntityManagerFactoryHelper.create(applicationContext,
                                                 dataSource,
                                                 jpaProperties,
                                                 "custom-persistent-unit",
                                                 "classpath:/META-INF/persistence.xml");
    }
----
The `auditEntityManager` becomes an implicit context parameter when the parameters are resolved during MVFLEX Expression Language (MVEL) evaluation.

. Add the following marshalling stragegy to the `kie-deployment-descriptor.xml` file:
+
[source, xml]
----
 <marshalling-strategy>
    <resolver>mvel</resolver>
    <identifier>new org.drools.persistence.jpa.marshaller.JPAPlaceholderResolverStrategy(auditEntityManager)
    </identifier>
    <parameters/>
    </marshalling-strategy>
----

.Additional resources

* For more information about persistence, see the "_Persisting process variables in a separate database schema in {PRODUCT_PAM}_" section in {URL_MANAGING_SETTINGS}#process-variables-persist-proc_execution-server[_{MANAGING_KIE_SERVER}_].
