[id='Exporting-dashbuilder-data-proc_{context}']

ifdef::PAM,JBPM[]

= Exporting {CENTRAL} dashboard data

You can export dashboard data such as data sets, pages, and navigation from {CENTRAL} as a ZIP file.

.Procedure
. In {CENTRAL}, select the *Admin* icon in the upper-right corner of the screen and select *Dashbuilder Data Transfer*.

. To export the dashboard data, complete any of the following tasks:
+
--
If you want to export all of the dashboard data as a ZIP file, complete the following tasks:

... On the *Dashbuilder Data Transfer* page, click *Export all*.
+
An `export.zip` file containing all of the dashboard data is downloaded. The `export.zip` file structure is separated by data type, as shown in the following example:
+
[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
dashbuilder/perspectives/page1/perspective_layout
dashbuilder/perspectives/page1/perspective_layout.plugin
dashbuilder/perspectives/page2/perspective_layout
dashbuilder/perspectives/page2/perspective_layout.plugin
dashbuilder/perspectives/readme.md
dashbuilder/navigation/navigation/navtree.json
dashbuilder/navigation/readme.md
VERSION
----


If you want to export the customized user created and provide dashboard data as a ZIP file, complete the following tasks:

... On the *Dashbuilder Data Transfer* page, click *Custom export*.
... Select the datasets and pages that you want to include in a ZIP file in the *Export Wizard* panel and click *Next*.
+
The *Export Wizard* panel validates the selected data sets and pages. The summary of the data sets and pages is available on the panel.
+
NOTE: Navigation is always included in the exported ZIP file.

... If your export is ready, click *Download*.
+
An `export.zip` file containing customized dashboard data is downloaded.
+
NOTE: You must select the associated pages and data sets in the *Export Wizard* panel. If you fail to select both data sets and pages, then an error is generated and you cannot download the `export.zip` file. Therefore, you must select at least one page.

... Click *Finish*.

--

endif::[]

ifdef::DM[]

= Exporting dashboard data

You can export all the dashboard data such as datasets from {CENTRAL} as a ZIP file.

.Procedure
. In {CENTRAL}, select the *Admin* icon in the upper-right corner of the screen and select *Dashbuilder Data Transfer*.
. On the *Dashbuilder Data Transfer* page, click *Export all*.

+
An `export.zip` file containing all dashboard data is downloaded. The `export.zip` file structure is separated by data type, as shown in the following example:
+
[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
VERSION
----

endif::DM[]
