[id='Importing-dashbuilder-data-proc_{context}']

ifdef::PAM,JBPM[]

= Importing Dashbuilder data

You can import Dashbuilder-related data to {CENTRAL} from a ZIP file if the archive is structured in the same way as the following example:

[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
dashbuilder/perspectives/page1/perspective_layout
dashbuilder/perspectives/page1/perspective_layout.plugin
dashbuilder/perspectives/page2/perspective_layout
dashbuilder/perspectives/page2/perspective_layout.plugin
dashbuilder/perspectives/readme.md
dashbuilder/navigation/navigation/navtree.json
dashbuilder/navigation/readme.md
VERSION
----

.Procedure
. In {CENTRAL}, select the *Admin* icon in the upper-right corner of the screen and select *Dashbuilder Data Transfer*.
+
WARNING: You must import Dashbuilder data to a clean installation of {PRODUCT} in order to avoid overwriting data on an existing system.

. On the *Dashbuilder Data Transfer* page, click the *Choose File* icon.

. Navigate to the ZIP file you want to import and select the file.

. Click the *Upload* icon.

. Click *Import*.

endif::[]

ifdef::DM[]

= Importing Dashbuilder data

You can import Dashbuilder data to {CENTRAL} from a ZIP file if the archive is structured in the same way as the following example:

[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
VERSION
----

.Procedure
. In {CENTRAL}, select the *Admin* icon in the upper-right corner of the screen and select *Dashbuilder Data Transfer*.
+
WARNING: You should only import Dashbuilder data to a clean installation of {PRODUCT} in order to avoid overwriting data on an existing system.

. On the *Dashbuilder Data Transfer* page, click the *Choose File* icon.

. Navigate to the ZIP file you want to import and select the file.

. Click the *Upload* icon.

. Click *Import*.

endif::DM[]
