[[_jbpmreleasenotes790]]

= New and Noteworthy in jBPM 7.9.0
:imagesdir: ..

The following features were added to jBPM 7.9

== Installation of work items directly from service repository

Service repository that has been improved a lot over the last two releases received another feature - install work items into existing workbench.
This then allows to have the project directly prepared for work items without a need to install it from within jBPM designer.

To read more have a look at http://mswiderski.blogspot.com/2018/07/easy-workitem-installation-jbpm.html[this article].


== Running the service repository on Heroku

Another feature added to the service repository was the ability to deploy the springboot repository war on Heroku.

For more information see https://github.com/kiegroup/jbpm-work-items/blob/master/repository-springboot/README.md#running-the-repository-on-heroku[this documentation]

== Service repository rest service

When using the sevice repository springboot or wildfly deployments in addition to the numerous workitems hosted users
now have a rest api available to query information about these workitems.

The rest service include following end points:

[source, text]
----
/repository/rest/services
/repository/rest/services/{name}
/repository/rest/services/{name}/parameters
/repository/rest/services/{name}/results
/repository/rest/services/{name}/mavendepends
/rest/services/category/{category}
/rest/servicetriggers
/rest/servicetriggers/count
/rest/serviceactions
/rest/serviceactions/count
----

== SpringBoot jBPM auto configuration update

SpringBoot auto configuration for jBPM (and KIE Server that uses jBPM extension) has been improved to allow to use custom entities as part
of the EntityManagerFactory used by the execution engine. That enables colocation of business logic and business assets.

It's enough to provide a bean that will override entityManagerFactory bean that comes with jBPM auto configuration.

[source, java]
----
@Bean("entityManagerFactory")
 public LocalContainerEntityManagerFactoryBean entityManagerFactory(JpaProperties jpaProperties, DataSource dataSource){
     LocalContainerEntityManagerFactoryBean factoryBean = new LocalContainerEntityManagerFactoryBean();
     factoryBean.setPersistenceUnitName(PERSISTENCE_UNIT_NAME);
     factoryBean.setPersistenceXmlLocation(PERSISTENCE_XML_LOCATION);
     factoryBean.setJtaDataSource(dataSource);
     factoryBean.setJpaPropertyMap(jpaProperties.getProperties());

     factoryBean.setPersistenceUnitPostProcessors(new PersistenceUnitPostProcessor() {
         @Override
         public void postProcessPersistenceUnitInfo(MutablePersistenceUnitInfo pui) {
             pui.addManagedClassName("org.jbpm.springboot.samples.entities.Person");
         }
     });

     return factoryBean;
 }

----

== Performance baseline for jBPM 7

Wondering how good jBPM performs when it comes to execution? http://mswiderski.blogspot.com/2018/07/performance-baseline-for-jbpm-7-780.html[Here is a very interesting study] describing
base performance of jBPM execution through KIE Server.

== Creation of indexes for all database tables

With the update to JPA 2.1 all jBPM entities received an update to declare index creation information.
This results in a better query performance overall.

== Process Designer

This release allows the user to enable/disable _HiDPI_ via system preferences, that results on performance improvements for users with non HiDPI screens.

It also improves the performance and user experience by adding support for image strips, on both _canvas_ and _DOM_ side, making all icons appear instantaneously on all browsers and all components.

Also some other issues has been fixed. The most relevant ones are:

* Fixed issues when changing between different element types, restricted the available morphing types for tasks, sub-processes and events
* Fixed issues related to boundary events
* Fixed issues when saving properties for the _ad-hoc_ and _multiple instance_ sub-process
