[id='business-central-system-properties-ref_{context}']
= {CENTRAL} system properties

The {CENTRAL} system properties listed in this section are passed to `standalone*.xml` files.
ifdef::PAM,DM[]
To install standalone {CENTRAL}, you can use the listed properties in the following command:
[source,subs="attributes+"]
----
java -jar {PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-standalone.jar -s application-config.yaml -D<property>=<value> -D<property>=<value>
----
In this command, `<property>` is a property from list and `<value>` is a value that you assign to that property.
endif::[]

Git directory::

Use the following properties to set the location and name for the {CENTRAL} Git directory:

* `org.uberfire.nio.git.dir`: Location of the {CENTRAL} Git directory.
* `org.uberfire.nio.git.dirname`: Name of the {CENTRAL} Git directory. Default value: `.niogit`.
* `org.uberfire.nio.git.ketch`: Enables or disables Git ketch.
* `org.uberfire.nio.git.hooks`: Location of the Git hooks directory.

Git over HTTP::

Use the following properties to configure access to the Git repository over HTTP:

* `org.uberfire.nio.git.proxy.ssh.over.http`: Specifies whether SSH should use an HTTP proxy. Default value: `false`.
* `http.proxyHost`: Defines the host name of the HTTP proxy. Default value: `null`.
* `http.proxyPort`: Defines the host port (integer value) of the HTTP proxy. Default value: `null`.
* `http.proxyUser`: Defines the user name of the HTTP proxy.
* `http.proxyPassword`: Defines the user password of the HTTP proxy.
* `org.uberfire.nio.git.http.enabled`: Enables or disables the HTTP daemon. Default value: `true`.
* `org.uberfire.nio.git.http.host`: If the HTTP daemon is enabled, it uses this property as the host identifier. This is an informative property that is used to display how to access the Git repository over HTTP.  The HTTP still relies on the servlet container. Default value: `localhost`.
* `org.uberfire.nio.git.http.hostname`: If the HTTP daemon is enabled, it uses this property as the host name identifier. This is an informative property that is used to display how to access the Git repository over HTTP.  The HTTP still relies on the servlet container. Default value: `localhost`.
* `org.uberfire.nio.git.http.port`: If the HTTP daemon is enabled, it uses this property as the port number. This is an informative property that is used to display how to access the Git repository over HTTP.  The HTTP still relies on the servlet container. Default value: `8080`.

Git over HTTPS::

Use the following properties to configure access to the Git repository over HTTPS:

* `org.uberfire.nio.git.proxy.ssh.over.https`: Specifies whether SSH uses an HTTPS proxy. Default value: `false`.
* `https.proxyHost`: Defines the host name of the HTTPS proxy. Default value: `null`.
* `https.proxyPort`: Defines the host port (integer value) of the HTTPS proxy. Default value: `null`.
* `https.proxyUser`: Defines the user name of the HTTPS proxy.
* `https.proxyPassword`: Defines the user password of the HTTPS proxy.
* `user.dir`: Location of the user directory.
* `org.uberfire.nio.git.https.enabled`: Enables or disables the HTTPS daemon. Default value: `false`
* `org.uberfire.nio.git.https.host`: If the HTTPS daemon is enabled, it uses this property as the host identifier. This is an informative property that is used to display how to access the Git repository over HTTPS.  The HTTPS still relies on the servlet container. Default value: `localhost`.
* `org.uberfire.nio.git.https.hostname`: If the HTTPS daemon is enabled, it uses this property as the host name identifier. This is an informative property that is used to display how to access the Git repository over HTTPS.  The HTTPS still relies on the servlet container. Default value: `localhost`.
* `org.uberfire.nio.git.https.port`: If the HTTPS daemon is enabled, it uses this property as the port number. This is an informative property that is used to display how to access the Git repository over HTTPS.  The HTTPS still relies on the servlet container. Default value: `8080`.

JGit::

* `org.uberfire.nio.jgit.cache.instances`: Defines the JGit cache size.
* `org.uberfire.nio.jgit.cache.overflow.cleanup.size`: Defines the JGit cache overflow cleanup size.
* `org.uberfire.nio.jgit.remove.eldest.iterations`: Enables or disables whether to remove eldest JGit iterations.
* `org.uberfire.nio.jgit.cache.evict.threshold.duration`: Defines the JGit evict threshold duration.
* `org.uberfire.nio.jgit.cache.evict.threshold.time.unit`: Defines the JGit evict threshold time unit.

Git daemon::

Use the following properties to enable and configure the Git daemon:

* `org.uberfire.nio.git.daemon.enabled`: Enables or disables the Git daemon. Default value: `true`.
* `org.uberfire.nio.git.daemon.host`: If the Git daemon is enabled, it uses this property as the local host identifier. Default value: `localhost`.
* `org.uberfire.nio.git.daemon.hostname`: If the Git daemon is enabled, it uses this property as the local host name identifier. Default value: `localhost`
* `org.uberfire.nio.git.daemon.port`: If the Git daemon is enabled, it uses this property as the port number. Default value: `9418`.
* `org.uberfire.nio.git.http.sslVerify`: Enables or disables SSL certificate checking for Git repositories. Default value: `true`.
+
NOTE: If the default or assigned port is already in use, a new port is automatically selected. Ensure that the ports are available and check the log for more information.

Git SSH::

Use the following properties to enable and configure the Git SSH daemon:

* `org.uberfire.nio.git.ssh.enabled`: Enables or disables the SSH daemon. Default value: `true`.
* `org.uberfire.nio.git.ssh.host`: If the SSH daemon enabled, it uses this property as the local host identifier. Default value: `localhost`.
* `org.uberfire.nio.git.ssh.hostname`: If the SSH daemon is enabled, it uses this property as local host name identifier. Default value: `localhost`.
* `org.uberfire.nio.git.ssh.port`: If the SSH daemon is enabled, it uses this property as the port number. Default value: `8001`.
+
NOTE: If the default or assigned port is already in use, a new port is automatically selected. Ensure that the ports are available and check the log for more information.

* `org.uberfire.nio.git.ssh.cert.dir`: Location of the `.security` directory where local certificates are stored. Default value: Working directory.
* `org.uberfire.nio.git.ssh.idle.timeout`: Sets the SSH idle timeout.
* `org.uberfire.nio.git.ssh.passphrase`: Pass phrase used to access the public key store of your operating system when cloning git repositories with SCP style URLs. Example: `git@github.com:user/repository.git`.
* `org.uberfire.nio.git.ssh.algorithm`: Algorithm used by SSH. Default value: `RSA`.
* `org.uberfire.nio.git.gc.limit`: Sets the GC limit.
* `org.uberfire.nio.git.ssh.ciphers`: A comma-separated string of ciphers. The available ciphers are `aes128-ctr`, `aes192-ctr`, `aes256-ctr`, `arcfour128`, `arcfour256`, `aes192-cbc`, `aes256-cbc`. If the property is not used, all available ciphers are loaded.
* `org.uberfire.nio.git.ssh.macs`: A comma-separated string of message authentication codes (MACs). The available MACs are `hmac-md5`, `hmac-md5-96`, `hmac-sha1`, `hmac-sha1-96`, `hmac-sha2-256`, `hmac-sha2-512`. If the property is not used, all available MACs are loaded.
+
NOTE: If you plan to use RSA or any algorithm other than DSA, make sure you set up your application server to use the Bouncy Castle JCE library.

{KIE_SERVER} nodes and {CONTROLLER}::

Use the following properties to configure the connections with the {KIE_SERVER} nodes from the {CONTROLLER}:

* `org.kie.server.controller`: The URL is used to connect to the {CONTROLLER}. For example, `ws://localhost:8080/{URL_COMPONENT_CENTRAL}/websocket/controller`.
* `org.kie.server.user`: User name used to connect to the {KIE_SERVER} nodes from the {CONTROLLER}. This property is only required when using this {CENTRAL} installation as a {CONTROLLER}.
* `org.kie.server.pwd`: Password used to connect to the {KIE_SERVER} nodes from the {CONTROLLER}. This property is only required when using this {CENTRAL} installation as a {CONTROLLER}.

Maven and miscellaneous::

Use the following properties to configure Maven and other miscellaneous functions:

* `kie.maven.offline.force`: Forces Maven to behave as if offline. If true, disables online dependency resolution. Default value: `false`.
+
NOTE: Use this property for {CENTRAL} only. If you share a runtime environment with any other component, isolate the configuration and apply it only to {CENTRAL}.

* `org.uberfire.gzip.enable`: Enables or disables Gzip compression on the `GzipFilter` compression filter. Default value: `true`.
* `org.kie.workbench.profile`: Selects the {CENTRAL} profile. Possible values are `FULL` or `PLANNER_AND_RULES`. A prefix `FULL_` sets the profile and hides the profile preferences from the administrator preferences. Default value: `FULL`
* `org.appformer.m2repo.url`: {CENTRAL} uses the default location of the Maven repository when looking for dependencies. It directs to the Maven repository inside {CENTRAL}, for example, `\http://localhost:8080/business-central/maven2`. Set this property before starting {CENTRAL}. Default value: File path to the inner `m2` repository.
* `appformer.ssh.keystore`: Defines the custom SSH keystore to be used with {CENTRAL} by specifying a class name. If the property is not available, the default SSH keystore is used.
* `appformer.ssh.keys.storage.folder`: When using the default SSH keystore, this property defines the storage folder for the user’s SSH public keys. If the property is not available, the keys are stored in the {CENTRAL} `.security` folder.
* `appformer.experimental.features`: Enables the experimental features framework. Default value: `false`.
* `org.kie.demo`: Enables an external clone of a demo application from GitHub.

* `org.uberfire.metadata.index.dir`: Place where the Lucene `.index` directory is stored. Default value: Working directory.
* `org.uberfire.ldap.regex.role_mapper`: Regex pattern used to map LDAP principal names to the application role name. Note that the variable role must be a part of the pattern as the application role name substitutes the variable role when matching a principle value and role name.
* `org.uberfire.sys.repo.monitor.disabled`: Disables the configuration monitor. Do not disable unless you are sure. Default value: `false`.
* `org.uberfire.secure.key`: Password used by password encryption. Default value: `org.uberfire.admin`.
* `org.uberfire.secure.alg`: Crypto algorithm used by password encryption. Default value: `PBEWithMD5AndDES`.
* `org.uberfire.domain`: Security-domain name used by uberfire. Default value: `ApplicationRealm`.
* `org.guvnor.m2repo.dir`: Place where the Maven repository folder is stored. Default value: `<working-directory>/repositories/kie`.
* `org.guvnor.project.gav.check.disabled`: Disables group ID, artifact ID, and version (GAV) checks. Default value: `false`.
* `org.kie.build.disable-project-explorer`: Disables automatic build of a selected project in Project Explorer. Default value: `false`.
* `org.kie.builder.cache.size`: Defines the cache size of the project builder. Default value: `20`.
* `org.kie.verification.disable-dtable-realtime-verification`: Disables the real-time validation and verification of decision tables. Default value: `false`.

{CONTROLLER}::

Use the following properties to configure how to connect to the {CONTROLLER}:

* `org.kie.workbench.controller`: The URL used to connect to the {CONTROLLER}, for example, `ws://localhost:8080/kie-server-controller/websocket/controller`.
* `org.kie.workbench.controller.user`: The {CONTROLLER} user. Default value: `kieserver`.
* `org.kie.workbench.controller.pwd`: The {CONTROLLER} password. Default value: `kieserver1!`.
* `org.kie.workbench.controller.token`: The token string used to connect to the {CONTROLLER}.
+
ifdef::DROOLS,JBPM[]
NOTE: For more information about how to use token-based authentication, see xref:usingTokenBasedAuthentication[].
endif::[]

Java Cryptography Extension KeyStore (JCEKS)::

Use the following properties to configure JCEKS:

* `kie.keystore.keyStoreURL`: The URL used to load a Java Cryptography Extension KeyStore (JCEKS). For example, `\file:///home/kie/keystores/keystore.jceks.`
* `kie.keystore.keyStorePwd`: The password used for the JCEKS.
* `kie.keystore.key.ctrl.alias`: The alias of the key for the default REST {CONTROLLER}.
* `kie.keystore.key.ctrl.pwd`: The password of the alias for the default REST {CONTROLLER}.

Rendering::

Use the following properties to switch between {CENTRAL} and {KIE_SERVER} rendered forms:

* `org.jbpm.wb.forms.renderer.ext`: Switches the form rendering between {CENTRAL} and {KIE_SERVER}. By default, the form rendering is performed by {CENTRAL}. Default value: `false`.
* `org.jbpm.wb.forms.renderer.name`: Enables you to switch between {CENTRAL} and {KIE_SERVER} rendered forms. Default value: `workbench`.
