[[_wb.releasenotesworkbench.7.7.0.final]]
= New and Noteworthy in KIE Workbench 7.7.0

== Connecting to a remote Kie Server Controller

When running a Workbench instance, there is now greater flexibility to decide how Kie Server instances will be managed.
Previously, whenever a Workbench is started, it would always start an embedded Kie Server Controller. This setup is still available
but now there is also an option to not start this service and instead connect to a remote Kie Server Controller.
This allows a more fine grained deployment model where it's possible to decide the best approach for a specific scenario.

To switch between these modes, a key system property is used: *org.kie.workbench.controller*. By default, the Workbench
will continue to start the embedded service if this system property is missing. Otherwise, it will try to connect to the remote
service and also ensure that none of the embedded services are started.

It is important to note that only Web Socket connection protocol is available to use when connecting to remote Kie Server Controller.

For more details regarding all possible system configs regarding user name, password, token and secured password via key store,
please refer to <<_wb.systemproperties, Workbench system properties>>.



