= Core Engine
:imagesdir: ..


The core jBPM engine is the heart of the project.
It's a light-weight workflow engine that executes your business processes.
It can be embedded as part of your application or deployed as a service (possibly in the cloud).  Its most important features are the following:

* Solid, stable core engine for executing your process instances.
* Native support for the latest BPMN 2.0 specification for modeling and executing business processes.
* Strong focus on performance and scalability.
* Light-weight (can be deployed on almost any device that supports a simple Java Runtime Environment; does not require any web container at all).
* (Optional) pluggable persistence with a default JPA implementation.
* Pluggable transaction support with a default JTA implementation.
* Implemented as a generic process engine, so it can be extended to support new node types or other process languages.
* Listeners to get notified about various events.
* Ability to migrate running process instances to a new version of their process definition

The core engine can also be integrated with a few other (independent) core services: 

* The human task service can be used to manage human tasks when human actors need to participate in the process. It is fully pluggable and the default implementation is based on the WS-HumanTask specification and manages the life cycle of the tasks, task lists, task forms, and some more advanced features like escalation, delegation, rule-based assignments, etc.
* The history log can store all information about the execution of all the processes in the engine. This is necessary if you need access to historic information as runtime persistence only stores the current state of all active process instances. The history log can be used to store all current and historic states of active and completed process instances. It can be used to query for any information related to the execution of process instances, for monitoring, analysis, etc.
