[id='ba-dm-rn-tech-preview-con']
= Technology preview

This section lists features that are in technology preview in {PRODUCT} {PRODUCT_VERSION}. 

[IMPORTANT]
====
These features are for Technology Preview only. Technology Preview features
are not supported with Red Hat production service level agreements (SLAs), might
not be functionally complete, and Red Hat does not recommend to use them for
production. These features provide early access to upcoming product features,
enabling customers to test functionality and provide feedback during the
development process.
For more information on Red Hat Technology Preview features support scope,
see https://access.redhat.com/support/offerings/techpreview/.
====

== Technology preview features
* Aliases - You can use aliases instead of container IDs in the remote REST APIs of the Planner Server.
* Application lifecycle automation - Part of {PRODUCT} and disabled by default.
* Content Management System (CMS) Perspective - Part of {PRODUCT} and disabled by default.
* OpenShift Container Platform - Comprised of {KIE_SERVER}, {PLANNER}server, and {CENTRAL}.
** Provisioning user interface - Enables you to provision a server on OpenShift while running the selected project build from Decision Central. It is part of {PRODUCT} and disabled by default.
** Clustering for the OpenShift development environment - enables high availability while authoring.
//https://issues.jboss.org/browse/BAPL-896
** Monitoring console - Enables you to manage containers, process instances, tasks, dashboards, and other runtime capabilities. No authoring capabilities are available.
* Predictive Model Markup Language (PMML) - The PMML feature is fully implementated for the following predictive model types:
** Decision tree
** Regression
** Scorecard
+
PMML has a partial implementation of the Mining Model type; with the following model sub-types available:
** Select All
** Select First
** Model Chaining
* Multithreaded execution - Solves a single data set by partitioning across multiple threads. It is turned off by default and can be enabled either with a KieBaseConfiguration option or with a system property as explained in http://docs.jboss.org/drools/release/7.5.0.Final/drools-docs/html_single/#_multithreaded_rule_engine[Drools Documentation]
* Rule Units - Rule Units represent a declarative approach to partitioning a rule set in to smaller units, binding different data sources to those units, and the execution of the individual unit. A Rule Unit is comprised of data sources, global variables, and rules.#
* Red Hat JBoss Web Server
**You can use the installer to install {PRODUCT} on Red Hat JBoss Web Server with Tomcat 9.
COMMENT: I am assuming that this is the case - that JWS will still be an option in the installer.
** You can use Narayana to configure JDBC data sources for {KIE_SERVER}.
* Integration with Red Hat JBoss Fuse - Enables you to connect disparate applications, services, or devices in real time.
* Executable model - Provides a pure Java-based representation of a rule set, together with a convenient Java DSL to programmatically create such model. 
//https://issues.jboss.org/browse/BXMSDOC-2588

== Technology Preview experimental features
COMMENT: I have left this section in for review. Please let me know what needs to be removed.
The following Technology Preview features are experimental and may require additional API changes:

=== Enabling Application Lifecycle Automation and Provisioning User Interface
{PRODUCT} settings allow you to enable the Application Lifecycle Automation and Provisioning User Interface features.

. Go to *Settings* -> *Roles* -> *admin*.
. Expand *Pages* and click the *Read* field to enable *Deployments*.

=== Enabling the Content Management System (CMS) Perspective
{PRODUCT} settings allow you to enable the CMS Perspective.

. Go to *Settings* -> *Roles* -> *admin*.
. Expand *Pages* and click the *Read* field to enable *Page Authoring*.

=== Enabling Predictive Model Markup Language (PMML)
This feature uses a single configuration option, org.drools.compiler.compiler.PMMLCompiler. The valid values for this configuration option are:

* org.kie.pmml.pmml_4_2.PMML4Compiler - This value should be used for the majority of cases where PMML support is desired.
* org.drools.pmml.pmml_4_2.PMML4Compiler - This value provides backwards compatibility, and should only be used in cases where there is a reliance on the older drools-pmml and drools-scorecards modules.