[id='ba-dm-rn-tech-preview-con']
= Technical preview

This section lists features that are in technical preview in {PRODUCT} {PRODUCT_VERSION}. Where they are listed in the documentation these features also have a note similar to the following:

[IMPORTANT]
====
This feature a Technology Preview feature only. Technology Preview features
are not supported with Red Hat production service level agreements (SLAs), might
not be functionally complete, and Red Hat does not recommend to use them for
production. These features provide early access to upcoming product features,
enabling customers to test functionality and provide feedback during the
development process.
For more information on Red Hat Technology Preview features support scope,
see https://access.redhat.com/support/offerings/techpreview/
====

* Application Lifecycle Automation - Part of {PRODUCT} and disabled by default. DEV how do we enable?
* Content Management System (CMS) Perspective - Part of {PRODUCT} and disabled by default. DEV how do we enable?
* Decision Model and Notation (DMN) Authoring - Part of {PRODUCT} and disabled by default. DEV how do we enable?
* Decision Model and Notation (DMN) Profiles - Does this require steps to enable?
* Multithreaded Execution - Does this require steps to enable?
* Predictive Model Markup Language (PMML) - Does this require steps to enable?
* Provisioning UI - Part of {PRODUCT} and disabled by default. DEV how do we enable?
* Rule Units - Does this require steps to enable?

.Enabling Application Lifecycle Automation
. Go to *Settings* -> *Roles*.

.Enabling the Content Management System (CMS) Perspective
. Go to *Settings* -> *Roles*.

.Enabling Decision Model and Notation (DMN) Authoring
. Go to *Settings* -> *Roles*.

.Enabling the Provisioning UI
. Go to *Settings* -> *Roles*.
