[id='ba-dm-rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

.{CENTRAL} fails to deploy on {EAP} with space in its path [https://issues.jboss.org/browse/RHDM-371[RHDM-371]]

Steps to reproduce:

. Download the latest {EAP} and {CENTRAL}.
. Unzip {EAP} and place a space in the new directory name.
. Finish the setup and run `./standalone.sh`.

Expected result: {CENTRAL} should be deployed.

Actual result: {CENTRAL} fails to deploy and an error appears in the console log.

Workaround: Do not specify a directory that contains any spaces.

._Loading assets_ pop-up displayed indefinitely after deleting a project [https://issues.jboss.org/browse/RHDM-382[RHDM-382]]

Steps to reproduce:

. Log in to {CENTRAL}.
. Go to *Projects -> Try samples -> optacloud -> OK*
. Wait a few seconds for the assets to be indexed.
. Go to *Settings -> Delete project*.

Expected result: An empty project list should be displayed.

Actual result: *Loading assets* pop-up is displayed indefinitely. Unable to click on anything while the pop-up is displayed.

Workaround: Refresh the browser.

.Repositories are created when other users open a new space in cluster [https://issues.jboss.org/browse/RHDM-385[RHDM-385]]

Steps to reproduce:

. Create a new space and open the space.
. Open the space as a different user in the cluster.

Expected result: The space opened by a different user should use the same repository.

Actual result: A new repository is created in the cluster for every user.

Workaround: None

.{PRODUCT} installation fails with new {EAP} installation [https://issues.jboss.org/browse/RHDM-394[RHDM-394]]

Steps to reproduce:

. Install Oracle JDK 1.8.
. Use the {EAP} installer to install {EAP} 7.1 with default configurations.
. Use {PRODUCT} installer to install {PRODUCT} with default configurations, and specify an install directory name (such as ``~/EAP-7.1.0...`).

Expected result: {PRODUCT} should be installed with the newly installed {EAP}.

Actual result: {PRODUCT} installation fails.

Workaround: Install {EAP} 7.1.0 using the zip distribution.
