[id='ba-dm-rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.


== {CENTRAL}

=== High availability
High availability and clustering for {CENTRAL} is now configured with JMS and NFS storage.

=== Stunner
Stunner replaces the Process Designer. It provides many new features, including:
* Support for multiple selection (operations with multiple elements)
* Cut, copy, and paste capabilities
* Support for shape size constraints
* Improved BPMN2 support

=== Improved navigation

.{PRODUCT} Home page
The {PRODUCT} Home page has been redesigned for easier navigation.

=== Case management 
A case project is a type of project in {CENTRAL} that is configured for case management. Case management is an extension of business process management (BPM) that enables you to handle dynamic and ad hoc activities. It handles one-off situations where the process cannot be predicted in advance. For more information, see _Getting started with case process_.
//@link

=== Decision Model and Notation models
You can use Decision Model and Notation (DMN) to model a decision service graphically in a decision requirements diagram (DRD). This diagram traces business decisions from start to finish, with each decision node drawing logic from DMN model decision elements such as decision tables.

=== Guided Decision Table
* Guided Decision Table has a new wizard for creating and editing columns.
* Hit policies are now available. Hit policies determine the order in which rules (rows) in a guided decision table are applied.
* New support to display multiple linked guided decision tables in the Guided Decision Table designer has been added.

=== Projects Metrics dashboard
A new dashboard is available for every project listed in the Projects perspective. The Projects Metrics dashboard displays all of your project contribution metrics in one place. This new dashboard replaces the Contributors page, which was part of the Authoring group.

=== Team Metrics dashboard
The Team Metrics dashboard shows all of the project metrics for a team in a single page. This new dashboard replaces the older Contributors page, which was part of the Authoring group.

=== Form Modeler
The new Form Modeler is the default forms engine. This new version improves the forms engine stability and provides several bug fixes.

=== New columns available on process instances, tasks, and jobs
The following columns have been added to the corresponding perspectives:

* Process instance list perspective: Last update and correlation key.
* Task list: Last update, correlation key (of the associated process instance ID), process instance description (of the associated process instance).
* Jobs perspective: Name of the associated process (if any), ID of the associated process instance (if any), Description of the associated process instance (if any).

=== Advanced search filter
You can now search for specific data by using the *Search* tab on the Jobs, Process Instances, Task Administration, and Execution Errors perspectives. For information about the new search feature, see the "Using the advanced search filter pages" section of the _{PRODUCT} {RELEASE} User Guide_.

=== New Task List and Task Administration perspectives
The former Task List perspective has been divided into the Task List and Task Administration perspectives. The Task List perspective is used by task operators to work with their assigned (or potentially assigned) tasks. The Task Administration perspective is used by administrators to manage tasks assigned to other users. This perspective is only available for users with admin or process-admin roles. It is similar to the Admin filter tab on the former Task List perspective.

=== Error Handling
While running a process instance or a job, the system now detects and stores execution errors such as exceptions after the maximum number of retries has been exceeded. If an error occurs, the system generates an event that contains the following data:

--
[cols="1,2",options="header"]
|===
| Data
| Fields

.3+| Process model
| processModelID
| processModelVersion
| processModelName

.2+| Process instance that has failed
| processInstanceID
| customProcessID

.5+| Activity that has failed
| activityID
| activityName
| activityType
| iteration
| status

.2+| Error data
| errorMessage: Message with the error that has occurred.
| errorStack: Stack with error detail.
|===
--

The process instance list includes a new column that displays the number of errors per process instance which are not marked as acknowledged. When you select the column, a window appears which enables you to navigate to the new Error perspective.

The Execution Errors perspective lists any errors that occur during process instances or executor service jobs on a Decision Server. Use this perspective to help troubleshoot issues. It is visible to users with the admin and process-admin roles.

=== Improved validation in the deployment descriptor editor

The deployment descriptor editor in Business Central has been improved to validate data entered for the following:

* Work item handlers
* Event listeners
* Marshalling strategies
* Globals
* Environment entries
* Configuration

The deployment descriptor editor performs the validation when a build is invoked or manually when a user clicks *Validate*.

=== Job creation
The Job creation interface has been modified to enable you to start the job immediately or schedule it to be executed later.

== Process Engine

=== Red Hat WildFly Swarm

=== Process API and task administration API
A process administration API and task administration API have been introduced to simplify some of the more complex administrator use cases.
You can use the process administration API to do the following:

* Retrieve all process definition nodes
* Cancel node instances
* Retrigger node instances
* Update the timer (absolute or relative)
* List timer instances
* Trigger nodes

You can use the task administration API to do the following:

* Add and remove potential owners and excluded owners and business administrators
* Add and remove task inputs and outputs
* List, create, and cancel escalations and notifications

=== UserTaskService 
UserTaskService updates task metadata and variables in single operation. This feature is available through KIE Server REST and JMS API.

=== Advanced task routing
When tasks are assigned to a group of users, you can use pluggable task assignment strategies to automatically assign tasks to a suitable individual immediately. This enables more efficient task allocation, based on all properties associated with the task. For example, potential owners and task priority but also task data that includes information such as geography, required skills, and so on. You can use business rules to define the assignment logic, making it easy to customize this to your needs.

=== Business rule task fire limit
The business rule task has been enhanced to limit the number of fired rules. This avoids situations where rules run into an infinite loop and make the server completely unresponsive. The fire default fire limit is 10000.
//https://issues.jboss.org/browse/BXMSDOC-2016

=== NoSQL integration
//https://issues.jboss.org/browse/BAPL-496
Initial integration with NoSQL has been introduced. This is based on additional emitters that can be implemented to receive notifications when the process engine executes processes. This this enables users to plug in their own emitters that will be responsible for sending data to externals data stores. Note that this is an integration and not a replacement of the persistence layer of jBPM. 

=== Quartz improvements
The Quartz scheduler service has been improved to fetch jobs only for deployments (kie containers) that are currently available in the running system. 

== {KIE_SERVER}
The {KIE_SERVER} (also known as kie-server) has been extended to support core engine features and offers a remote API for these operations. In addition the following architectural changes were introduced.

=== Separate {CENTRAL} from execution server
{CENTRAL} now delegates all of its requests to the execution server. The main advantage is that {CENTRAL} can now be used to monitor any set of execution servers. By linking the execution server to {CENTRAL}, the process and task monitoring UIs in {CENTRAL} can now connect to this execution server and show all relevant information. When multiple independent execution servers are used, you can either connect to a specific one or use the smart router to aggregate information across multiple servers. 

=== Smart router
Smart router (also known as kie-server-router) includes the following enhancements:

* Smart router  can be used as a proxy to help manage multiple independent process execution servers.
* When the controller is not available during smart router start up, a retry mechanism is in place to connect to the controller as soon as it becomes available.
* A retry mechanism is in place for times when the controller is not available and there are updates to be sent to the controller.
* When a {KIE_SERVER} does not respond to a request, it is removed from the list of active servers. Subsequent requests will not target it. The now inactive server is put on a list to be verified. After verification, it is added back to the active servers list.

=== Aliases
You can now use aliases instead of container IDs in the remote REST APIs of the execution server.

//=== {PRODUCT} Monitoring web application
//This release includes a new distribution `war` file that enables you to build custom cloud images. Use the {PRODUCT} Monitoring web application with {KIE_SERVER} instances to manage containers, process instances, tasks, dashboards, and other runtime capabilities in the cloud. Unlike the standard {PRODUCT} distribution, no authoring capabilities are available.
//
//[NOTE]
//====
//For on-premise deployments, use the standard {PRODUCT} `war` file.
//====

=== Work Item archetype

To help users build custom service tasks (work items), {PRODUCT} comes with the Work Item archetype that generates the majority of items required to build a custom service task.  The archetype includes the following:

* A Work Item Definition (WID) file
* The Work Item Handler implementation class
* The Work Item Handler test class

The Maven assembly (zip) packages everything at build time so it can be consumed by the Service Repository and therefore be used from within the Web Designer.

=== KIE Server Maven plugins
KIE Server has been enhanced with additional Maven plugins that enable interaction with the KIE Server and KIE Controller REST API directly from within a build. This interaction facilitates easier integration with CI/CD pipelines when building KJars so they can be directly deployed to the execution environment (both managed and unmanaged KIE Servers).

== {PLANNER}

=== @PlanningPin
To pin down an assignment and force {PLANNER} to leave it untouched, add the @PlanningPin annotation on a planning entity’s boolean property and make it true for those entities that are immovable.

=== Conference scheduling
You can assign each conference talk to a time slot and a room. Timeslots can overlap. Save data in or extract data from an `*.xlsx` file that can be edited with LibreOffice or Microsof Excel.

=== PlannerBenchmark
PlannerBenchmark has a new method benchmarkAndShowReportInBrowser() to automatically open the benchmark report in the default browser after the benchmark has finished.

=== Guided decision tables integration
{PLANNER} now integrates with the Guided Decision Table designer. Modify the score with built-in {PLANNER} actions that can be accessed in the Action BRL fragment column type. The Workbench examples now include the dinnerparty project, which uses a guided decision table to define score constraints.

=== Guided rule editor integration
{PLANNER} now integrates with the guided rule editor. You can modify the score with a built-in {PLANNER} action.

=== Real-time planning
{KIE_SERVER} now has an interface that enables you to update a problem data set while the solver is running. Use the Java client or REST interface to submit your ProblemFactChange implementations.

=== Multi-threaded partitioned search 
{PLANNER} now has out-of-the box support for solving a single data set by partitioning across multiple threads. This enhancement makes use of multiple CPU cores for a single problem. Partitioned search can implement geo-fencing for Vehicle Routing use cases.

=== Solution interface
The Solution interface is deprecated. Your solution class requires only the `@PlanningSolution` annotation.

=== Score type
You no longer need to define the score type in the solver configuration. {PLANNER} now determines it automatically from the domain model.

=== Enhanced solver editor
The {PLANNER} editor screen now supports adding all termination types, including composite termination. The phase configuration section enables you to tweak Construction Heuristic settings and select the local search algorithm to optimize your planning problem.

=== Difficulty comparator definition
The {PLANNER} domain editor can now specify a planning entity difficulty. Navigate through the object hierarchy and define the sorting attributes. Several construction heuristic algorithms use this information to construct a better initial solution.

=== {PLANNER} execution server
The {PLANNER} execution server now supports real-time planning.

== New component names
The following components have been renamed in {PRODUCT} {PRODUCT_VERSION}:

.Renamed components
--
[cols="1,2",grid="all",options="header"]
|===
| Red Hat JBoss BPM Suite
| {PRODUCT} (RHPAM)

| Red Hat JBoss BPM Suite
| Red Hat Process Automation Manager


| Business Resource Planner
| {PLANNER}

| Guided Decision Table editor
| Guided Decision Table designer

//| Realtime Decision Server
//| Decision Server

| KIE Execution Server
| {KIE_SERVER} (for Process Automation Manager capabilities), Planner Server (for Business Optimization capabilities), KIE Server (represents both {KIE_SERVER} and Planner servers )

| Organizational units
| Spaces

| Drools engine, Rules engine
| Decision engine

|===
--


