[id='ba-dm-rn-tech-preview-con']
= Technical preview

This section lists features that are in technical preview in {PRODUCT} {PRODUCT_VERSION}. Where they are listed in the documentation these features also have a note similar to the following: You will see the following note where technical preview features are referred to in the documentation:

[IMPORTANT]
====
This feature a Technology Preview feature only. Technology Preview features
are not supported with Red Hat production service level agreements (SLAs), might
not be functionally complete, and Red Hat does not recommend to use them for
production. These features provide early access to upcoming product features,
enabling customers to test functionality and provide feedback during the
development process.
For more information on Red Hat Technology Preview features support scope,
see https://access.redhat.com/support/offerings/techpreview/
====

== Technical preview features
* Aliases - You can use aliases instead of container IDs in the remote REST APIs of the Planner Server.
* Application Lifecycle Automation - Part of {PRODUCT} and disabled by default.
* Content Management System (CMS) Perspective - Part of {PRODUCT} and disabled by default.
* OpenShift Container Platform - Comprised of the Decision Server, Planner Server, and Decision Central.
* Provisioning User Interface - Enables you to provision a server on OpenShift while running the selected project build from Decision Central. It is part of {PRODUCT} and disabled by default.
* Decision Model and Notation (DMN) Profiles
//DMN Authoring - The person you are looking for is Michael Anstis, but also to my knowledge this is indeed not included in the Decision Central/Workbench for v7.0
//DMN Profiles - This is quite an internal-mechanism/advanced thing for now, in my view.
//One reason a user might want to be aware of DMNProfile, is in relation with Signavio as we implemented a DMNProfile to cover partially of their custom/proprietary DMN constructs. But as we don't have anyone yet in Signavio to confirm and test our implementation, I would prefer not to mention this Signavio DMNProfile in our documentation until the work is complete. Another reason a user might need this, is to disable our helper functions and have the engine 100% adherent to the DMN specification. This feature can be disabled using the system/kmodule property "org.kie.dmn.strictConformance" set to true. A final reason a developer might need this, is to plug-in their own extension, but this is advanced and documented on the directly API.
* Predictive Model Markup Language (PMML) - The PMML feature is fully implementated for the following predictive model types:
** Decision Tree
** Regression
** Scorecard
+
PMML has a partial implementation of the Mining Model type; with the following model sub-types available:
** Select All
** Select First
** Model Chaining

== Technical preview experimental features
The following Technology Preview features are experimental and may require additional API changes:
* Executable Model
* Multithreaded Execution - Solves a single data set by partitioning across multiple threads. It is turned off by default and can be enabled either with a KieBaseConfiguration option or with a system property as explained here http://docs.jboss.org/drools/release/7.5.0.Final/drools-docs/html_single/#_multithreaded_rule_engine
* Rule Units - Rule Units represent a declarative approach to partitioning a rule set in to smaller units, binding different data sources to those units, and the execution of the individual unit. A Rule Unit is comprised of data sources, global variables, and rules.

//There isn't any specific option to be enabled to start using this feature. It's sufficient to declare the unit to which the rules belong at the beginning of the drl file and trigger the execution through a RuleUnitExecutor instead of using a KieSession. You can find more detail about this here http://docs.jboss.org/drools/release/7.5.0.Final/drools-docs/html_single/#_rule_units_2

//Mario Fusco - Hi Michele, I agree with Lukas' comment: Rule units, Multithreaded engine and Executable model are all experimental features even if with different levels of maturity. In particular while the first 2 are ready to be used (even if we don't provide any support for them yet) the Executable model is still a work in progress. It is not completed and not really usable at the moment. I don't know if it makes sense to underline this difference (or mentioning the Executable model at all at this stage). I'm also CC'ing Mark Proctor in case he has something to add to this. Regards, Mario
//Mark Proctor-to me, Mario, Lukas
//Yes leave them in them in the experimental list, but do emphasise that while these have a degree of stability in them (shouldn't crash), we need more time to have potential API changes.
//Mark Proctor - Yes, they are experimental and subject to api changes. The are maturing beta quality features.

.Enabling Application Lifecycle Automation and Provisioning User Interface
{PRODUCT} settings allow you to enable the Application Lifecycle Automation and Provisioning User Interface features.

. Go to *Settings* -> *Roles* -> *admin*.
. Expand *Pages* and click the *Read* field to enable *Deployments*.

.Enabling the Content Management System (CMS) Perspective
{PRODUCT} settings allow you to enable the CMS Perspective.

. Go to *Settings* -> *Roles* -> *admin*.
. Expand *Pages* and click the *Read* field to enable *Page Authoring*.

.Enabling Predictive Model Markup Language (PMML)
This feature uses a single configuration option, org.drools.compiler.compiler.PMMLCompiler. The valid values for this configuration option are:

* org.kie.pmml.pmml_4_2.PMML4Compiler - This value should be used for the majority of cases where PMML support is desired.
* org.drools.pmml.pmml_4_2.PMML4Compiler - This value provides backwards compatibility, and should only be used in cases where there is a reliance on the older drools-pmml and drools-scorecards modules.
