[id='ba-dm-rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

.Process Designer morphing issues [https://issues.jboss.org/browse/RHPAM-430[RHPAM-430]]

* It is possible to morph from a sub-process into a certain task type, but it is not possible to morph back to a sub-process. You should be able to:
**Morph between task types and re-usable subprocesses
**Morph between embedded and ad-hoc subprocesses
* When morphing an embedded sub-process into a task an exception appears and the diagram is not updated
* If you morph the sub-process with content, the content is hidden after morphing. You must reopen the process to see the content again.

.Process Designer editors are very slow with Google Chrome on Linux [https://issues.jboss.org/browse/RHPAM-922[RHPAM-922]]

Steps to reproduce: Open three Process Designer editors in Google Chrome on Linux.

Expected result: All instances of Process Designer perform at the same level, regardless of the number of editors open.

Actual result: The first two editors that were opened perform as usual, but the third and all subsequent editor are very slow, even if you will close first two editors.


.Stunner: It is not possible to append a node inside an embedded subprocess. [https://issues.jboss.org/browse/RHPAM-426[RHPAM-426]]
Steps to reproduce:

. Create a process with an embedded subprocess.
. Add a start event to the embedded subprocess.
. Activate the start event and try to append any node using the *Context* menu.

Expected Result: The node is added to the subprocess.

Actual Result: The following error appears and the node is not added to the subprocess:
`Error Command execution failed`

.The Embedded Authoring perspective is broken if you use a parameter-controlled URL. [https://issues.jboss.org/browse/RHPAM-11[RHPAM-11]]

It is possible to embed editors to hide the path to projects. However, this feature is not working in the Authoring perspective if you use a parameter-controlled URL.

.[Project Oriented] Standalone perspectives are broken [https://issues.jboss.org/browse/RHPAM-503[RHPAM-503]]

Steps to reproduce:
1. Run kie-wb (e.g. you can use cargo configuration in kie-wb-distrubution)
$ cd kie-wb-distributions/kie-wb-tests/kie-wb-tests-gui
$ mvn cargo:run -Pkie-wb,wildfly10

2. Navigate standalone authoring perspective by pasting the following URLs in the browser address bar:
http://localhost:8080/kie-wb/kie-wb.jsp?standalone=true&perspective=AuthoringPerspective
http://localhost:8080/kie-wb/kie-wb.jsp?standalone=true&perspective=AuthoringPerspective&header=AppNavBar

3. Login using username=admin, password=admin1234;

Actual result - modal with error displayed every time.
Expected result - it should be possible to browse / open project assets.

.kie-server Container creation doesn't load the latest SNAPSHOT for the first time. 2nd creation does [https://issues.jboss.org/browse/RHPAM-282[RHPAM-282]]
,

.The system property org.jbpm.rm.init.timer should be set as false by default in jbpm ejb timer service. [https://issues.jboss.org/browse/RHPAM-611[RHPAM-611]]
,

.Autoclaim feature of Swimlane does not work under specific circumstances [https://issues.jboss.org/browse/RHPAM-283[RHPAM-283]]
,

.Product repo is missing javassist artifact [https://issues.jboss.org/browse/RHPAM-225[RHPAM-225]]
,

.Stunner - copy of timer is created when copying name to doc [https://issues.jboss.org/browse/RHPAM-755[RHPAM-755]]
,

.Newly created persistable data objects are not automatically added to the list of Project Persistable Data Objects [https://issues.jboss.org/browse/RHPAM-938[RHPAM-938]]
,

.Unable to close standalone editor after some change [https://issues.jboss.org/browse/RHPAM-976[RHPAM-976]]
,

.Guided Rule - Save in standalone mode throws an error [https://issues.jboss.org/browse/RHPAM-990[RHPAM-990]]
,

.GetTasksByProcessInstanceIdCommand ignores userId parameter [https://issues.jboss.org/browse/RHPAM-522[RHPAM-522]]
,

.Stunner - Cannot edit element names inline [https://issues.jboss.org/browse/RHPAM-444[RHPAM-444]]

https://issues.jboss.org/browse/RHPAM-1099
,
