
[id='ba-dm-rn-intro-con']

= About {PRODUCT}

ifdef::BA[]
{PRODUCT} is an open source business process management suite that combines business process management and business rules management. It enables business and IT users to create, manage, validate, and deploy business processes and rules.

{PRODUCT} uses a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic and business processes without requiring assistance from IT personnel.


{PRODUCT} {PRODUCT_VERSION} {Release} with integrated {PRODUCT} further expands the product capabilities by providing an enhanced user experience, a simplified process design workflow, case management capabilities, an improved comprehensive dashboard, and optimized task handling and collaboration features.

endif::BA[]

ifdef::DM[]

{PRODUCT} is an open source decision management platform that combines business rules management and complex event processing. It automates business decisions and makes that logic available to the entire business.

{PRODUCT} uses a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.

{PRODUCT} {PRODUCT_VERSION} {Release} further expands the product capabilities by providing an enhanced user experience, a simplified process design workflow, case management capabilities, an improved comprehensive dashboard, and optimized task handling and collaboration features.

The list of supported configurations for {PRODUCT} is available at the https://access.redhat.com/articles/705183[Red Hat Customer Portal]. COMMENT: current?
endif::DM[]

