
[[_chap_introduction]]
= Introduction

[[_jboss_brms]]
== About {PRODUCT}

ifdef::BPMS[]
Red Hat JBoss BPM Suite is an open source business process management suite that combines Business Process Management and Business Rules Management and enables business and IT users to create, manage, validate, and deploy Business Processes and Rules.

Red Hat JBoss BRMS and Red Hat JBoss BPM Suite use a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic and business processes without requiring assistance from IT personnel.

To accommodate Business Rules component, Red Hat JBoss BPM Suite includes integrated Red Hat JBoss BRMS.

The list of supported configurations for Red Hat JBoss BPM Suite is available at the https://access.redhat.com/articles/704703[Red Hat Customer Portal].
endif::BPMS[]

ifdef::BRMS[]
Red Hat JBoss BRMS is an open source decision management platform that combines Business Rules Management and Complex Event Processing. It automates business decisions and makes that logic available to the entire business.

Red Hat JBoss BRMS uses a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.

The list of supported configurations for Red Hat JBoss BRMS is available at the https://access.redhat.com/articles/705183[Red Hat Customer Portal].
endif::BRMS[]

== What Is New in {PRODUCT} 6.4

{PRODUCT} 6.4 is a minor release over the previous version 6.3. Noteworthy new features and improvements in this release are described below.

=== User Interface Improvements

ifdef::BPMS[]
* Enum is now available as a type in Data Modeler in Business Central. 
endif::BPMS[]

* The {KIE_SERVER} now allows filtering the containers based on status and GAV (Maven Group ID, Artifact ID, and version). For more information, see the {URL_DEVELOPMENT_GUIDE}#containers[Containers] and {URL_DEVELOPMENT_GUIDE}#unmanaged_intelligent_process_server_environment[Unmanaged Intelligent Process Server Environment] sections of the _{DEVELOPMENT_GUIDE}_.

* The guided rule editor now enables you to use formulas for composite field constraints. When adding constraints to a pattern, the *Multiple Field Constraint* selection (*All of (and)* and *Any of (or)*) supports the use of formulas in addition to expressions. For more information, see the {URL_USER_GUIDE}#when_constraints_in_the_guided_rule_template[WHEN Conditions in Guided Rule Templates] section of the _{USER_GUIDE}_.

ifdef::BPMS[]
* The process designer now allows you to perform copy and paste operations across different processes. For more information, see the {URL_USER_GUIDE}#sect_designing_a_process[Designing Process] section of the _{USER_GUIDE}_.
* Business Central can now be used to visualize and work with tasks and process instances running on {A_KIE_SERVER} instance. For more information, see the {URL_ADMIN_GUIDE}#unified_execution_servers[Unified Execution Servers] section of the _{ADMIN_GUIDE}_.

endif::BPMS[]

ifdef::BPMS[]
=== Core

* Red Hat JBoss EAP 7 is supported and can be installed using only the deployable zip installation option. Support for {PRODUCT} components on Red Hat JBoss EAP 7 is available in the following order:
** Runtime engines embeddable and fully functional inside a Java EE application deployed on Red Hat JBoss EAP 7.
** Execution servers running inside Red Hat JBoss EAP 7 container.
** Business Central deployed and fully functional on Red Hat JBoss EAP 7.

* The REST API of Intelligent Process Server was extended by operations for saving a user task and retrieving the saved content of the user task when needed to complete the user task. For more information, see the {URL_DEVELOPMENT_GUIDE}#user_tasks[Managing User Tasks] section of the _{DEVELOPMENT_GUIDE}_.

* Intelligent Process Server Client integration with JMS has been enhanced with the *Fire and forget* interaction option. Previously, the JMS requests were blocking input and output, holding the connection until the server side processing is done. With the *Fire and forget* option, messages get delivered to the server only if the transaction that invoked the server client was committed successfully. For more information, see {URL_DEVELOPMENT_GUIDE}#rest_api_overview[Intelligent Process Server Java Client API Overview] chapter in the _{DEVELOPMENT_GUIDE}_.

* Task variables can now be accessed from within a task event listener. For more information, see the {URL_DEVELOPMENT_GUIDE}#task_event_listener[Accessing Task Variables Using TaskEventListener] section of the _{DEVELOPMENT_GUIDE}_.

* Business Central now provides automatic installation of the specified services from the service repository for process designer. For more information, see the {URL_USER_GUIDE}#sect_service_repository[Service Repository] section of the _{USER_GUIDE}_.

* {PRODUCT} now supports process instance migration from one runtime manager to another. Process instance migration enables you to upgrade an active process instance to a newer version of the process definition.
If the active nodes have changed, you can perform node mapping of active node instances within a process instance. For more information, see the {URL_DEVELOPMENT_GUIDE}#process_instance_migration[Process Instance Migration] section of the _{DEVELOPMENT_GUIDE}_.

* The Intelligent Process Server and Business Central can now be run using the same data source so that the work with process instances and tasks on the Intelligent Process Server is visualized in Business Central. You can configure the Intelligent Process Server to run with the same data source as Business Central using the installer. For the deployable package and packages of third-party JavaEE containers, the system properties are pre-configured but commented out. For more information, see the {URL_ADMIN_GUIDE}#unified_execution_servers[Unified Execution Servers] section of the _{ADMIN_GUIDE}_.
endif::BPMS[]


=== Integration and Miscellaneous

* The Google Chrome browser version 54.0.2840.7 is now supported. 

* Support for Russian and Traditional Chinese is no longer available for {PRODUCT} 6.4.

* Support for Java Development Kit (JDK) version 6 is no longer available for {PRODUCT} 6.4.

* Red Hat JBoss Developer Studio Integration Stack 10.0.0.GA supports {PRODUCT} 6.4.

* Red Hat JBoss Fuse 6.3 integration pack now includes and supports {PRODUCT} 6.4.

* The Update-04 for JBoss Operations Network (JON) 3.3 plugin is available for use with {PRODUCT} 6.4.

* Spring integration has been upgraded from Spring 3.x to 4.3.

* KieScanner support is now available in Blueprint integration. For more information, see the {URL_ADMIN_GUIDE}#chap_integration_with_aries_blueprint[Integration with Aries Blueprint] chapter of the _{ADMIN_GUIDE}_.

* Error messages while uploading spreadsheet as multi-bytes name have been improved. Asset names in error messages are now in a human-readable format and are easy to troubleshoot.

