[[_chap_known_issues]]
= Known Issues

These are the known issues for {PRODUCT} 6.4:

When all next moves are not doable, optaplanner get stuck in step and if termination is not based on time, it cycles forever [https://issues.jboss.org/browse/RHBRMS-1726[RHBRMS-1726]]::
If the {PLANNER} is in a state where all the entities are immovable, it gets stuck and only time based termination can terminate it. To workaround this issue, call the `Solver.terminateEarly()` method to break the cycle.

ifdef::BPMS[]
Installer doesn't recognize EAP 7+ [https://issues.jboss.org/browse/RHBPMS-4269[RHBPMS-4269]]::
Installer cannot be used for installing Red Hat JBoss BPM Suite on Red Hat JBoss EAP 7. To install Red Hat JBoss BPM Suite on Red Hat JBoss EAP 7, use the deployable zip installation option.
endif::BPMS[]

ifdef::BPMS[]
Unable to extract update patch file on Windows [https://issues.jboss.org/browse/RHBPMS-1267[RHBPMS-1267]]::
The Red Hat JBoss BPM Suite patch zip file cannot be opened on Windows 7 with the Windows Explorer application. You can use third-party tools or the `jar.exe -xvf <archived-patch-file>` command to extract the zip file.
endif::BPMS[]

ifdef::BPMS[]
java.io.FileNotFoundException is thrown every time jBPM Designer is opened when Business Central is deployed on WebSphere [https://issues.jboss.org/browse/RHBPMS-40[RHBPMS-40]]::
Opening a process definition in Business Central deployed on the WebSphere application server results in `FileNotFoundException` errors in the server log. There is currently no workaround for this issue.
endif::BPMS[]

ifdef::BPMS[]
Designer new commits doesn't appear in "Latests Version" control [https://issues.jboss.org/browse/RHBPMS-290[RHBPMS-290]]::
The `Latest Version` control does not reflect changes committed in processes or forms in Business Central. There is currently no workaround for this issue.
endif::BPMS[]

ifdef::BPMS[]
Transaction issues with Timer catch event [https://issues.jboss.org/browse/RHBPMS-4448[RHBPMS-4448]]::
If your application server is using the EJB executor to handle timer events, processes using singleton strategy may result in exceptions with the container managed transactions.  This is caused by the EJB executor completing transaction outside of the KIE Session, which causes a race condition with another thread working with the same KIE Session.
To work around this issue, use an executor bundled with Red Hat JBoss BPM Suite, which is aware of the singleton runtime strategy. To activate the bundled executor, set the system property `org.kie.timer.ejb.disabled` to `true`.
+
Alternatively, you can use the per process instance strategy where a new transaction is created for every invocation, or use the Quartz scheduler.
endif::BPMS[]

ifdef::BPMS[]
Start timer continue starting process instances after deactivating of deployment [https://issues.jboss.org/browse/RHBPMS-4389[RHBPMS-4389]]::
When you deactivate a deployment, the start event timers of its processes continue to fire and create new process instances. There is currently no workaround for this issue.
endif::BPMS[]

ifdef::BPMS[]
Container is not started when being created [https://issues.jboss.org/browse/RHBPMS-4375[RHBPMS-4375]]::
A container created using REST API or Business Central shows as `Started` in the `Status` field. However, it is not started until you explicitly stop and start it again in Business Central or make the following REST call:
+
[source]
----
POST http://localhost:8080/business-central/rest/controller/management/servers/default-kieserver/containers/org.jboss:integration:2.0.0-SNAPSHOT/status/started
----
+
endif::BPMS[]

ifdef::BPMS[]
The `org.javassist:javassist:jar:3.19.0.GA-redhat-1` artifact used in `optaplanner-core` is missing from the Red Hat JBoss BPM Suite artifact repository. A workaround for this issue is to import the `jboss-integration-platform-bom` BOM.
endif::BPMS[]

Use of "contains" operator does not add values from enumeration with quotes in Guided Rules etc. [https://issues.jboss.org/browse/RHBRMS-2577[RHBRMS-2577]]::
When using enumeration for a field in guided rules, guided decision tables, or guided decision templates, the resulting rule does not contain the selected value from the enumeration drop down within quotes ("") resulting in validation errors. There is currently no workaround for this issue.

ifdef::BPMS[]
It is not possible to create Business Process on Windows server with I18n Business Process names [https://issues.jboss.org/browse/RHBPMS-2000[RHBPMS-2000]]::
endif::BPMS[]

ifdef::BPMS[]
dashbuilder: Static data set definitions in WEB-INF/datasets dir not loaded on JWS3 (tomcat 8) [https://issues.jboss.org/browse/RHBPMS-850[RHBPMS-850]]::
When Business Central is deployed on JBoss Web Server 3, the static data set definitions in `WEB-INF/datasets` are not loaded and no error messages appear in the log. There is currently no workaround for this issue.
endif::BPMS[]

ifdef::BPMS[]
Container resolved release id version is not changed after auto updated by scanner [https://issues.jboss.org/browse/RHBPMS-4437[RHBPMS-4437]]::
When a container is set to be auto updated by a scanner, the scanner does not replace the container when a new container version is deployed. There is currently no workaround for this issue.
endif::BPMS[]

ifdef::BPMS[]
If you change Business Central localization log out is required [https://issues.jboss.org/browse/RHBPMS-4425[RHBPMS-4425]]::
If you switch localization of Business Central, your language setting is not persistent. Opening the Business Central application in a new browser tab or window results in English settings. There is currently no workaround for this issue.
endif::BPMS[]

ifdef::BPMS[]
Jobs: Queued tab displays jobs in status DONE [https://issues.jboss.org/browse/RHBPMS-4246[RHBPMS-4246]]::
The jobs listed under the *Queued* tab in Business Central sometimes display as `DONE` in the *Status* column. This happens when you restore default filters and select the *Queued* tab immediately after that.
endif::BPMS[]

ifdef::BPMS[]
Business Central remote JMS client support for EAP7 [https://issues.jboss.org/browse/RHBPMS-4198[RHBPMS-4198]]::
Red Hat JBoss BPM Suite supports Business Central remote JMS clients on EAP 6.4 only.
endif::BPMS[]

ifdef::BPMS[]
AccessControlException when acessing Timeline [https://issues.jboss.org/browse/RHBPMS-4493[RHBPMS-4493]]::
Starting Business Central on Red Hat JBoss EAP 7 with the security manager enabled throws the `AccessControlException` error when you access your timeline. A workaround for this issue in a Linux environment is to add the following permissions to your `kie.policy` file:
+
[source]
----
permission java.io.FilePermission "/etc/gitconfig","read";
permission java.io.FilePermission "${user.home}/.gitconfig","read";
----
+
endif::BPMS[]

ifdef::BPMS[]
[GSS](6.4.z)Endpoint /history/clear not responsive [https://issues.jboss.org/browse/RHBPMS-4447[RHBPMS-4447]]::
The Business Central server may stop responding when clearing its history with more than 100 000 records in the log tables. To work around the issue, delete the tables directly in the database or use `LogCleanupCommand` from within a process that can accept different parameters in the Intelligent Process Server. Alternatively, for the Business Central server, register the asynchronous Work Item Handler, use it to call `LogCleanupCommand` and start the process using the KIE runtime API. 
endif::BPMS[]

ifdef::BPMS[]
Quartz timer retry issue [https://issues.jboss.org/browse/RHBPMS-4431[RHBPMS-4431]]::
Database or network issues may cause the quartz trigger to fail for more than five times. This may result in the process workflow stopping, or the Quartz trigger deletion. There is no workaround for this issue.
endif::BPMS[]

ifdef::BPMS[]
Forms new commits doesn't appear in "Latests Version" control [https://issues.jboss.org/browse/RHBPMS-4239[RHBPMS-4239]]::
The `Latest Version` control does not reflect changes committed in Business Central. There is currently no workaround for this issue.
endif::BPMS[]

ifdef::BPMS[]
Remove Russian and Chinese (Traditional) from language dropdown [https://issues.jboss.org/browse/RHBPMS-4430[RHBPMS-4430]]::
The Dashbuilder does not list *Simplified Chinese* in the language drop down list. To work around this issue, set the following system property into the application server:
+
[source]
----
LocaleManager.installedLocaleIds=en,es,de,fr,pt,ja,zh
----
+
Alternatively, you can start your server and set this property as a command line parameter. 
endif::BPMS[]

ifdef::BPMS[]
Null Pointer exception occurs for Business Process with empty Embedded SubProcess [https://issues.jboss.org/browse/RHBPMS-4514[RHBPMS-4514]]::
Simulating processes with empty embedded subprocess throw NullPointerException. There is currently no workaround for this issue.
endif::BPMS[]

Backward-incompatible change in ModifyCommand [https://issues.jboss.org/browse/RHBRMS-2703[RHBRMS-2703]]::
The JAXB marshalled form of `org.drools.core.command.runtime.rule.ModifyCommand` is now backward incompatible. If you are manually creating an XML for marshalled command, you must modify the attributes annotated by JAXB for marshalling in the XML. For more information, see the {URL_MIGRATION_GUIDE}#migrating_to_6.4[Migrating from 6.X to 6.4] section of the _{MIGRATION_GUIDE}_.

ifdef::BPMS[]
Dashbuilder must use the same datasource as Business Central [https://issues.jboss.org/browse/RHBPMS-4517[RHBPMS-4517]]::
Configuring different datasources for Business Central and Dashbuilder may lead to Dashbuilder having no visibility to default tables, processes and tasks started on Business Central. There is currently no workaround for these issues arising due to configuring separate datasources for Business Central and Dashbuilder.
endif::BPMS[]
