
[id='rn-intro-con']

= Product overview

ifdef::PAM[]
{PRODUCT} is an open-source business automation platform that combines business process management (BPM), case management, business rules management, and resource planning. It enables business and IT users to create, manage, validate, and deploy business processes, cases, and business rules.

{PRODUCT} uses a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic and business processes without requiring assistance from IT personnel.

{PRODUCT} 7.0 further expands the product capabilities by providing an enhanced user experience, a simplified process design work flow, case management capabilities, an improved comprehensive dashboard, and optimized task-handling and collaboration features.

{PRODUCT} is fully supported on OpenShift and can be installed on various platforms.

endif::PAM[]

ifdef::DM[]

{PRODUCT} is an open-source decision management platform that combines business rules management, complex event processing, Decision Model & Notation (DMN) execution, and Business Optimizer for solving planning problems. It automates business decisions and makes that logic available to the entire business.

Business assets such as rules, decision tables, and DMN models are stored in a central repository. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.

{PRODUCT} is fully supported on OpenShift and can be installed on various platforms.

//The list of supported configurations for {PRODUCT} is available at the https://access.redhat.com/articles/705183[Red Hat Customer Portal]. *<MH>Replace with the correct link and uncomment paragraph. Don and Prakash are to to provide this link, which is part of the https://docs.google.com/document/d/1W5Uyxfohv-C5J8zyjcuN7ogaTsNaP3JCXhHLAN43uIs/edit doc, located in the Supported Configuration page:
//https://access.redhat.com/site/articles/704703
//https://access.redhat.com/site/articles/705183
//row</MH>*
endif::DM[]


[NOTE]
====
{PRODUCT} now requires Java 8 or higher.
====

