[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

.Process Designer morphing issues [https://issues.jboss.org/browse/RHPAM-430[RHPAM-430]]

* It is possible to morph from a sub-process into a certain task type, but it is not possible to morph back to a sub-process. You should be able to:
** Morph between task types and re-usable sub-processes
** Morph between embedded and ad-hoc sub-processes
* After morphing an embedded sub-process to a task, any nodes that were contained inside the sub-process are not removed. This prevents you from saving the diagram. You must delete the task to continue.

.Process Designer instances are very slow with Google Chrome on Linux [https://issues.jboss.org/browse/RHPAM-922[RHPAM-922]]

Step to reproduce: Open three Process Designer instances in Google Chrome on Linux.

Expected result: All instances of Process Designer perform at the same level, regardless of the number of instances open.

Actual result: The first two instances that were opened perform as usual, but the third and all subsequent instances are very slow, even if you will close the first two instances.

Workaround: Set the value of `chrome://flags/#force-color-profile` to sRGB.

.With Process Designer, ensure embedded sub-processes have enough storage [https://issues.jboss.org/browse/RHPAM-426[RHPAM-426]]

When using the context menu to add nodes to an embedded sub-process, this operation fails if there is not enough space in the embedded sub-process to add the node.  You must first make the embedded sub-process bigger.

.With Process Designer, a copy of the timer is created when you copy text from a name field to a documentation field [https://issues.jboss.org/browse/RHPAM-755[RHPAM-755]]

When your mouse is over the canvas, keyboard shorts perform actions related to the canvas, not the forms. A copy of the timer is created on the canvas if you copy text from a name field to a documentation field. In addition, you cannot change the cursor position. If you try to move the cursor using arrow keys, the timer event is moved on the canvas.

Steps to reprduce:

. Add a task to canvas.
. Open the properties form for the task.
. Select the contents of the *Name* field on the task.
. Move the mouse over the canvas without clicking.
. Click *Delete* to remove the contents of the *Name* field.

Expected result: Only the contents of the *Name* field are deleted.

Actual result: The selected task is deleted from the canvas as well as the contents of the *Name* field.

.With Process Designer, you cannot edit element or event names inline [https://issues.jboss.org/browse/RHPAM-444[RHPAM-444]]

Step to reproduce: Double-click the task name text.

Expected result: You can change the task name.

Actual result: Nothing happens and no input appears.

Workaround: Resize the node, then edit the element or event name.

.Business Central does not deploy if the EAP home contains a space in the name [https://issues.jboss.org/browse/RHPAM-1099[RHPAM-1099]]

Steps to reproduce:

. Install {EAP} in a directory that contains a space.
. Start Business Central.

Expected result: Business Central deploys.

Actual result: Business Central does not deploy and an error is recorded in the server log.

.Project-oriented standalone pages are broken [https://issues.jboss.org/browse/RHPAM-503[RHPAM-503]]

The standalone designers and pages are currently broken.

.Newly created persistable data objects are not automatically added to the list of Project Persistable Data Objects [RHPAM-938]

Issue: Newly created persistable data objects are not automatically added to the list of *Project Persistable Data Objects* in the Persistence designer. 

Workaround: Click *Add all project's persistable data objects* to update the list.

.Saving a guided rule in standalone mode produces an error [https://issues.jboss.org/browse/RHPAM-990[RHPAM-990]]

Steps to reproduce:

. Open an example Mortgages project.
. Open the guided rules asset in standalone mode.
. Click *Save*.

Expected result: The project is saved.

Actual result: An error occurs.

.Serialization of KieBase/package is not supported [https://issues.jboss.org/browse/RHPAM-2574[RHPAM-2574]]

Serialization of KieBase/package is not supported in {PRODUCT} {PRODUCT_VERSION}. For more information, see https://access.redhat.com/solutions/3216951[Is serialization of kbase/package supported in BRMS 6/BPM Suite 6/RHDM 7?].

.Smart Router Servers view error [https://issues.jboss.org/browse/RHPAM-1029[RHPAM-1029]]

If a Smart Router is registered in the controller and you select one of the deployment units on the Smart Router in the *Servers* view, an error occurs. Do not manage deployment units on the Smart Router. Instead, manage the server configurations of the connected {KIE_SERVERS} directly.

.Cannot use spaces in passwords [https://issues.jboss.org/browse/RHPAM-1135[RHPAM-1135]]

Do not use passwords containing spaces if the password will be used as a parameter in the startup script, for example do not use `test space!`.

//.Error when {PRODUCT} is configured with an Oracle database [https://issues.jboss.org/browse/RHPAM-1270[RHPAM-1270]]
//
//If {PRODUCT} is configured to use an Oracle database, every restart after the first start-up produces Oracle errors ORA-00955 and ORA-02275 in the `server.log file`. You can safely ignore these errors, however if you use the `Dhibernate.hbm2ddl.auto=none` property, these errors will not occur.