[id='service-testing-overview-con']
= Overview

While developing or enhancing a decision service in {CENTRAL}, you might need to test it and ensure that it is producing the correct output. 

Rule sets can become complicated and changes might sometimes lead to unexpected results. To avoid this problem, it is important to run the decision service on predefined input information and make sure that the output matches expectations.

To test your decision service in {CENTRAL}, create _Test Scenarios_. In a Test Scenario, you can enter a set of facts on which the rules can be used, the method to run, and the expected result. 

At any time during the development process in {CENTRAL} you can run one test scenario or all test scenarios together. The system fires the rules as necessary. It reports an error if the actual result is different from the expected result. You do not have to compile or deploy your decision service to apply test scenarios.

After deploying a decision service on a {KIE_SERVER}, you can test it in two ways:

* Create an application that calls the service and complete tests using an application testing framework, such as TestNG.
* Use a web interface of the {KIE_SERVER} to make calls to its API and view results.
