[id='_assets_con']
= Asset overview

Business rules, process definition files, and other assets and resources created in {CENTRAL} are stored in the Artifact Repository (Knowledge Store) that is accessed by the {KIE_SERVER}.

The Knowledge Store is a centralized repository for your business knowledge. It connects multiple GIT repositories so that you can access them from a single environment while storing different kinds of knowledge and artifacts in different locations. GIT is a distributed version control system and it implements revisions as commit objects. Every time you save your changes to a repository this creates a new commit object in the GIT repository. Similarly, the user can also copy an existing repository. This copying process is typically called cloning and the resulting repository can be referred to as clone. Every clone contains the full history of the collection of files and a cloned repository has the same content as the original repository.

{CENTRAL} provides a web front-end that enables you to view and update the stored content. To access Knowledge Store assets, go to *Menu* -> *Design* -> *Projects* in {CENTRAL} and click the project name.
