[id='deploy-app-process']
= Deploying the *MortgageApprovalProcess* process application

The following chapter instructs you how to build and deploy a new instance of the *Mortgage_Process* application in {PRODUCT}.

.Prerequisites
* {KIE_SERVER} is deployed and connected to {CENTRAL}.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* -> *Mortgage_Process*.
. Click *Deploy*.
+
* If no KIE container (deployment unit) is included with the project name, a container with default values is automatically created.
* If an older version of the project is already deployed, go to the project settings and change the project version. When finished, save the change and click *Deploy*. This deploys a new version of the same project with the latest changes in place, alongside the older version(s).
+
[NOTE]
====
You can also select the *Build & Install* option to build the project and publish the KJAR file to the configured Maven repository without deploying to a {KIE_SERVER}. In a development environment, you can click *Deploy* to deploy the built KJAR file to a {KIE_SERVER} without stopping any running instances (if applicable), or click *Redeploy* to deploy the built KJAR file and replace all instances. The next time you deploy or redeploy the built KJAR, the previous deployment unit (KIE container) is automatically updated in the same target {KIE_SERVER}. In a production environment, the *Redeploy* option is disabled and you can click *Deploy* only to deploy the built KJAR file to a new deployment unit (KIE container) on a {KIE_SERVER}.

To configure the {KIE_SERVER} environment mode, set the `org.kie.server.mode` system property to `org.kie.server.mode=development` or `org.kie.server.mode=production`. To configure the deployment behavior for a corresponding project in {CENTRAL}, go to project *Settings* -> *General Settings* -> *Version* and toggle the *Development Mode* option. By default, {KIE_SERVER} and all new projects in {CENTRAL} are in development mode. You cannot deploy a project with *Development Mode* turned on or with a manually added `SNAPSHOT` version suffix to a {KIE_SERVER} that is in production mode.
====

. To review project deployment details, click *View deployment details* in the deployment banner at the top of the screen or in the *Deploy* drop-down menu. This option directs you to the *Menu* -> *Deploy* -> *Execution Servers* page.
