[id='overview_business_process']
= Overview

{CENTRAL} enables you to automate your business processes. A business process is a diagram that describes the order in which a series of steps must be executed and consists of predefined nodes and connections. Each node represents one step in the process while the connections specify how to transition from one node to another.

For example, a bank offers a housing mortgage loan service. Using {CENTRAL}, the housing mortgage department of the bank creates a complete business process for the mortgage loan.

When a customer wants to buy a new property using credit, the following steps occur:

. The customer contacts a broker at the bank who assists in filing for a mortgage loan.
. The broker collects information about the property and the customer, such as the salary of the customer, social security number, the property sale price, and the requested loan amount.
. The broker then submits a request on behalf of the customer.

Whenever a customer submits a request, a new process instance is created. This ensures consistency in the quality of evaluating each request, provides complete visibility into the status of each request, and makes the process efficient and effective.
