[id='process-instances-filters-proc']
= Filtering process instances using default filters
Filter process instances by attributes such as *State*, *Errors*, *Filter By*, *Name*, *Start Date*, and *Last update*.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Manage* -> *Process Instances*.
. On the *Manage Process Instances* page, click the filter icon on the left of the page to expand the *Filters* pane.
+
This pane lists the following process attributes which you can use to filter process instances:
+
* *State*: Filter process instances based on their state (*Active*, *Aborted*, *Completed*, *Pending*, and *Suspended*).
* *Errors*: Filter process instances by errors.
* *Filter By*: Filter process instances based on *Id*, *Initiator*, *Correlation Key*, or *Description* attribute.
+
... Select the required attribute.
... Enter the search query in the text field below.
... Click *Apply*.
+

* *Name*: Filter process instances by definition names.
* *Definition Id*: Filter process instances by process definition IDs.
* *Deployment Id*: Filter process instances by process deployment IDs.
* *Parent Process Instance Id*: Filter process instances by parent process instance IDs.
* *SLA Compliance*: Filter process instances by SLA compliance states.
* *Start Date*: Filter process instances by creation dates.
* *Last update*: Filter process instances by last modified dates.
