[[_welcome]]
= Introduction

== Introduction

KIE (Knowledge Is Everything) is an umbrella project introduced to bring our related technologies together under one roof.
It also acts as the core shared around for our projects. So expect to see it a lot.

KIE is then a container of the following different but related projects offering a complete portfolio of solutions for business
automation and management:

1. *Drools* is a business rule management system with a forward-chaining and backward-chaining inference based rules engine,
allowing fast and reliable evaluation of business rules and complex event processing. A rule engine is also a fundamental
building block to create an expert system which, in artificial intelligence, is a computer system that emulates the decision-making
ability of a human expert.
2. *jBPM* is a flexible Business Process Management suite allowing you to model your business goals by describing
the steps that need to be executed to achieve those goals.
3. *OptaPlanner* is a constraint solver that optimizes use cases such as employee rostering, vehicle routing, task assignment
and cloud optimization.
4. *Drools Workbench* is is a full featured web application for the visual composition of custom business rules and processes.
5. *UberFire* is a web based workbench framework inspired by Eclipse Rich Client Platform.

include::GettingInvolved-section.adoc[leveloffset=+1]
include::Install-section.adoc[leveloffset=+1]

