[id='drl-rules-other-con']
= Other methods for creating DRL rules

As an alternative to creating and managing DRL rules within the {CENTRAL} interface, you can create DRL rule files in external standalone projects using Red Hat Developer Studio, Java objects, or Maven archetypes. These standalone projects can then be integrated as knowledge JAR (KJAR) dependencies in existing {PRODUCT} projects in {CENTRAL}. The DRL files in your standalone project must contain at minimum the required `package` specification, `import` lists, and `rule` definitions. Any other DRL components, such as global variables and functions, are optional. All data objects related to a DRL rule must be included with your standalone DRL project or deployment.

////
// Notes from Michael Anstis, for future expansion whenever we create a separate doc for IDEs, etc.

The resultant "Project" would be completely separate from Business Central. The Project could be compiled into a KJAR from Eclipse and used as a dependency in the workbench (exposing the Data Object) for authoring or the KJAR could be deployed to KIE Server and the rules operate as usual (for KIE Server deployments).. IDK where else you may talk about these concepts so it might be enough to state here that the project can be re-used if compiled into a KJAR.

The common theme is that all three examples really show how to use Drools in a standalone/embedded mode completely outside of Business Central and KIE Server. IF the example projects you describe are compiled into a KJAR it can then be uploaded to BC, added as a dependency to another Project and the DO re-used for authoring. The same KJAR can be deployed to KIE Server either via REST or BC and rules executed however both are probably out of the scope of the DRL Editor and the examples here; which I take to be more of a "getting started with Drools without using Business Central".
////
