[id='rules_facts_proc']
= Narrowing Facts Using Package White List

You can narrow down the facts available during rule creation and modification by adding the facts to the `package-names-white-list` file in your project. This file is a text file that accepts single package names on each line. By adding a group of facts to this file, you can speed up the loading process as you create rules.

.Procedure
. Go to *Menu* -> *Design* -> *Projects*, click the project name, and select any existing asset.
. In *Project Explorer*, click the gear icon and select *Repository View*.
. Click *`package-names-white-list`* to open the file.
+
By default (when the file is empty), all the facts within the project itself are visible while those from the project's dependencies are restricted.
. Add any file names to this list that you want to include in your rule editor.
+
Packages can contain wildcards, as in the following examples:
+
--
* `com.redhat.finance`: Allows facts from _only_ the [package]``com.redhat.finance`` package. Thus, [class]``com.redhat.finance.Person`` and [class]``com.redhat.finance.Salary`` are allowed, but [class]``com.redhat.finance.senior.Management`` are not allowed.
* `com.redhat.finance.*`: Allows facts from the sub-packages of the [package]``com.redhat.finance`` package __only__. Thus, [class]``com.redhat.finance.senior.Management`` and [class]``com.redhat.finance.junior.Management`` are allowed, but _not_ [class]``com.redhat.finance.Person``.
* `com.redhat.finance.**`: This is a combination of the above two rules. Allows [class]``com.redhat.finance.Person`` and [class]``com.redhat.finance.senior.Management`` and even, [class]``com.redhat.finance.really.senior.Management`` classes.
--
+
You can include specific packages from a dependency by adding appropriate entries into the `package-names-white-list`
 file. You can also include or remove all packages from specific dependencies. For more information, see **dependencies_add_proc,Adding Dependencies.
