[[JBPMExamples]]
= Examples

== Introduction

ifdef::PRODUCT-ONLY[]
This chapter provides a walkthrough of a pre-made Red Hat JBoss BPM Suite example project.
In this chapter, you will: 

* Import a number of pre-made example projects into your JBoss BPM Suite. 
* Learn about the Human Resources Example. 
* Build and deploy the example project. 
* Instantiate and explore the project. 

The project, together with many other example projects, can be imported through https://github.com/kiegroup/jbpm-playground[github].
To learn how to import projects through github, see JBoss BPM Suite Getting Started Guide. 
endif::PRODUCT-ONLY[]

ifdef::COMMUNITY-ONLY[]
The web-based workbench by default will install two sample repositories that contain various sample projects that help you getting started.
This section shows different examples that can be found in the jbpm-playground repository (also available here: https://github.com/kiegroup/jbpm-playground). All these examples are high level and business oriented.

If you want to contribute with these examples please get in touch with any member of the jBPM/Drools Team.
endif::COMMUNITY-ONLY[]

include::Examples/Importing-section.adoc[leveloffset=+1]
include::Examples/HumanResources-section.adoc[leveloffset=+1]

== Examples zip

A zip file of examples can also be downloaded from the downloads page, containing various examples that can be opened in the Eclipse-based Developers Tools.
Simply download and unzip the examples artefact and import into your Eclipse workspace.

