[id='taskservicefactorybean-ref_{context}']

= `TaskServiceFactoryBean` bean

The `TaskServiceFactoryBean` factory bean produces an instance of `TaskService` based on given properties. You must provide the following mandatory properties: 

* Entity manager factory
* Transaction manager

The transaction manager must be the Spring transaction manager, because persistence and transaction support is configured based on this transaction manager.

Optionally, you can provide an `EntityManager` instance instead of creating a new instance from `EntityManagerFactory`, for example, you might use a shared entity manager from Spring.

You can also set additional optional properties for the task service instance:

* `userGroupCallback`: The implementation of `UserGroupCallback` that the task service must use, the default value is `MVELUserGroupCallbackImpl`
* `userInfo`: The implementation of `UserInfo` that the task service must use, the default value is `DefaultUserInfo`
* `listener`: A list of `TaskLifeCycleEventListener` listeners which must be notified upon various operations on tasks

This factory bean creates a single instance of the task service. By design, this instance must be shared across all beans in the Spring environment.
