[id='case-management-dynamic-service-task-API-proc']
= Creating a dynamic service task using the REST API

Service tasks are generally less complex than user tasks, although they might need more data to execute properly. Service tasks require following information:

* `name`: The name of the activity.
* `nodeType`: The type of node that will be used to find the work item handler.
* `data`: The map of the data to properly deal with execution.

You can create a dynamic service task during case run time with the same endpoint as a user task, but with a different body payload.

Use the following procedure use the Swagger REST API to create a dynamic service task for the IT Orders sample project available in {CENTRAL} . The same endpoint can be used for REST API without Swagger.

.Prerequisite 
You are logged in to {CENTRAL} and an IT Orders case instance has been started using the Showcase application. For more information about using Showcase, see 
ifeval::["{context}" == "case-management-design"]
xref:case-management-showcase-application-con-case-management-design[_Case management Showcase application_].
endif::[]


.Procedure 

. In a web browser, open the following URL:
+
`http://localhost:8080/kie-server/docs`
. Open the list of available endpoints under *Case instances :: Case Management*.
. Click click the following `POST` method endpoint to open the details: 
+
`/server/containers/{id}/cases/instances/{caseId}/stages/{caseStageId}/tasks`
+
. Click *Try it out* and complete the following parameters:
+
.Parameters
[cols="40%,60%",options="header"]
|===
|Name| Description
|`id` | `itorders`
|`caseId` | `IT-0000000001`
|===
+
body::
+
[source]
----
{
 "name" : "InvokeService",
 "data" : {
   "Parameter" : "Fixed hardware spec",
   "Interface" : "org.jbpm.demo.itorders.services.ITOrderService",
   "Operation" : "printMessage",
   "ParameterType" : "java.lang.String"      
  }, 
 "nodeType" : "Service Task"
}
----
. In the Swagger application, click *Execute* to create the dynamic task.


In this example, a Java-based service is executed. It consists of an interface with the public class `org.jbpm.demo.itorders.services.ITOrderService`, public `printMessage` method with a single `String` argument. Upon execution, the parameter value is passed to the method for execution.

Numbers and names and other types of data given to create service tasks depend on the implementation of a service task's handler. In the provided example, the `org.jbpm.process.workitem.bpmn2.ServiceTaskHandler` handler is used.

NOTE: For any custom service tasks, ensure the handler is registered in the deployment descriptor in the *Work Item Handlers* section, where the name is same as the `nodeType` used for creating a dynamic service task.

