[id='case-management-close-case-using-API-proc-{context}']
= Closing a case using the {KIE_SERVER} REST API

You can use a REST API request to close a case instance. {PRODUCT} includes the Swagger client, which includes endpoints and documentation for REST API requests. Alternatively, you can use the same endpoints to make API calls using your preferred client or Curl.

.Prerequisites 
* A case instance has been started using Showcase. 
* You are able to authenticate API requests as a user with the `admin` role.

.Procedure
. Open the Swagger REST API client in a web browser:
+
`localhost:8080/kie-server/docs`
. Under *Case Instances :: Case Management*, open the `POST` request with the following endpoint:
+
`/server/containers/{id}/cases/instances/{caseId}`
. Click *Try it out* and fill in the required parameters:
+
.Parameters
[cols="40%,60%",options="header"]
|===
|Name| Description
|`id` | `itorders`
|`caseId` | `IT-0000000001`
|===
. Optionally, you can include a comment to be included in the case file. To leave a comment, type it into the `body` text field as a `String`. 
. Click *Execute* to close the case.
. To confirm the case is closed, open the Showcase application and change the case list status to *Closed*.


