[id='ejb-implementations-ref_{context}']
= Implementations for EJB services

As an extension of {PROCESS_ENGINE} core services, EJB services provide EJB-based execution semantics and are based on various EJB-specific features.

* `DeploymentServiceEJBImpl` is implemented as an EJB singleton with container-managed concurrency. Its lock type is set to `write`.
* `DefinitionServiceEJBImpl` is implemented as an EJB singleton with container-managed concurrency. Its overall lock type is set to `read` and for the `buildProcessDefinition()` method the lock type is set to `write`.
* `ProcessServiceEJBImpl` is implemented as a stateless session bean.
* `RuntimeDataServiceEJBImpl` is implemented as an EJB singleton. For the majority of methods the lock type is set to `read`. For the following methods the lock type is set to `write`:
** `onDeploy()`
** `onUnDeploy()`
** `onActivate()`
** `onDeactivate()`
* `UserTaskServiceEJBImpl` is implemented as a stateless session bean.

[discrete]
= Transactions

The EJB container manages transactions in EJB services. For this reason, you do not need to set up any transaction manager or user transaction within your application code.

[discrete]
= Identity provider

The default identity provider is based on the `EJBContext` interface and relies on caller principal information for both name and roles. The `IdentityProvider` interface provides two methods related to roles:

* `getRoles()` returns an empty list, because the `EJBContext` interface does not provide an option to fetch all roles for a particular user
* `hasRole()` delegates to the `isCallerInRole()` method of the context

To ensure that valid information is available to the EJB environment, you must follow standard JEE security practices to authenticate and authorize users. If no authentication or authorization is configured for EJB services, an anonymous user is always assumed.

If you use a different security model, you can use CDI-style injection for the `IdentityProvider` object for EJB services. In this case, create a valid CDI bean that implements the `org.kie.internal.identity.IdentityProvider` interface and make this bean available for injection with your application. This implementation will take precedence over the `EJBContext`-based identity provider.


[discrete]
= Deployment synchronization
Deployment synchronization is enabled by default and attempts to synchronize any deployments every 3 seconds. It is implemented as an EJB singleton with container-managed concurrency. Its lock type is set to `write`. It uses the EJB timer service to schedule synchronization jobs.


[discrete]
= EJB scheduler service
The {PROCESS_ENGINE} uses the scheduler service to handle time-based activities such as timer events and deadlines. When running in an EJB environment, the {PROCESS_ENGINE} uses a scheduler based on the EJB timer service. It registers this scheduler for all `RuntimeManager` instances.

You might need to use a configuration specific to an application server to support cluster operation.

[discrete]
= `UserGroupCallback` and `UserInfo` implementation selection

The required implementation of `UserGroupCallback` and `UserInfo` interfaces might differ for various applications. These interfaces can not be injected with EJB directly. You can use the following system properties to select existing implementations or use custom implementations of these interfaces for the {PROCESS_ENGINE}:


* `org.jbpm.ht.callback`: This property selects the implementation for the `UserGroupCallback` interface:
** `mvel`: The default implementation, typically used for testing.
** `ldap`: The LDAP-based implementation. This implementation requires additional configuration in the `jbpm.usergroup.callback.properties` file.
** `db`: The database-based implementation. This implementation requires additional configuration in the `jbpm.usergroup.callback.properties` file.
** `jaas`: An implementation that requests user information from the container.
** `props`: A simple property-based callback. This implementation requires an additional properties file that contains all users and groups.
** `custom`: A custom implementation. You must provide the fully-qualified class name of the implementation in the `org.jbpm.ht.custom.callback` system property.

* `org.jbpm.ht.userinfo`: This property selects the implementation for the `UserInfo` interface:
** `ldap`: The LDAP-based implementation. This implementation requires additional configuration in the `jbpm-user.info.properties` file.
** `db`: The database-based implementation. This implementation requires additional configuration in the `jbpm-user.info.properties` file.
** `props`: A simple property-based implementation. This implementation requires an additional properties file that contains all user information.
** `custom`: A custom implementation. You must provide the fully-qualified class name of the implementation in the `org.jbpm.ht.custom.userinfo` system property.

Typically, set the system properties in the startup configuration of the application server  or JVM. You can also set the properties in the code before using the services. For example, you can provide a custom `@Startup` bean that configures these system properties.

ifdef::DROOLS,JBPM,OP[]
You can find an example application that utilizes EJB services https://github.com/jsvitak/jbpm-6-examples/tree/master/rewards-basic[here].
endif::DROOLS,JBPM,OP[]
