
= Spring

jBPM can be configured in many ways with Spring though the two most frequently used approaches are:



* direct use of runtime manager API
* use of jbpm services

While both approaches are tested and valid, which one to choose is a matter of the system functionality.
Before selecting one of the approaches the most important question to ask is:

Will my system run multiple runtime managers at the same time?

If the answer to this question is no, then go ahead with direct Runtime Manager API as it will be the simplest way to use jBPM within your application.
But when the answer is yes, then go ahead with jbpm services as they encapsulate runtime manager API with best practices by providing dynamic runtime environment for your BPM logic - also known as execution server.

== Direct use of Runtime Manager API

This is the standard (and the simplest) way to get up and running with jBPM in your application.
You only configure it once and run as part of the application.
With the RuntimeManager usage, both {PROCESS_ENGINE} and task service will be managed in complete synchronization, meaning there is no need from end user to deal with "plumbing" code to make these two work together.

To provide spring based way of setting up jBPM, few factory beans where added:



* org.kie.spring.factorybeans.RuntimeEnvironmentFactoryBean
* org.kie.spring.factorybeans.RuntimeManagerFactoryBean
* org.kie.spring.factorybeans.TaskServiceFactoryBean

FactoryBeans provide standard way to configure Spring application spring xml though there are not custom spring xml tags equivalent for them.

=== RuntimeEnvironmentFactoryBean

Factory responsible for producing instances of RuntimeEnvironment that are consumed by RuntimeManager upon creation.
It allows to create following types of RuntimeEnvironment (that mainly means what is configured by default):

* DEFAULT - default (most common) configuration for RuntimeManager
* EMPTY - completely empty environment to be manually populated
* DEFAULT_IN_MEMORY - same as DEFAULT but without persistence of the runtime engine
* DEFAULT_KJAR - same as DEFAULT but knowledge asset are taken from KJAR identified by releaseid or GAV
* DEFAULT_KJAR_CL - build directly from classpath that consists kmodule.xml descriptor

Mandatory properties depends on the selected type but knowledge information must be given for all types.
That means that one of the following must be provided:

* knowledgeBase
* assets
* releaseId
* groupId, artifactId, version

Next for DEFAULT, DEFAULT_KJAR, DEFAULT_KJAR_CL persistence needs to be configured:

* entity manager factory
* transaction manager

Transaction Manager must be Spring transaction manager as based on its presence entire persistence and transaction support is configured.
Optionally EntityManager can be provided to be used instead of always creating new one from EntityManagerFactory - e.g.
when using shared entity manager from Spring.
All other properties are optional and are meant to override the default given by type of the environment selected.

=== RuntimeManagerFactoryBean

FactoryBean responsible for creation of RuntimeManager instances of given type based on provided runtimeEnvironment.
Supported types:

* SINGLETON
* PER_REQUEST
* PER_PROCESS_INSTANCE

where default is SINGLETON when no type is specified.
Every runtime manager must be uniquely identified thus identifier is a mandatory property.
All instances created by this factory are cached to be able to properly dispose them using destroy method (close()).

=== TaskServiceFactoryBean

Creates instance of TaskService based on given properties.
Following are mandatory properties that must be provided:

* entity manager factory
* transaction manager

Transaction Manager must be Spring transaction manager as based on its presence entire persistence and transaction support is configured.
Optionally EntityManager can be provided to be used instead of always creating new one from EntityManagerFactory - e.g.
when using shared entity manager from Spring.
In addition to the above, there are optional properties that can be set on task service instance:

* userGroupCallback - implementation of UserGroupCallback to be used, defaults to MVELUserGroupCallbackImpl
* userInfo - implementation of UserInfo to be used, defaults to DefaultUserInfo
* listener - list of TaskLifeCycleEventListener that will be notified upon various operations on tasks

This factory creates a single instance of task service only as it's intended to be shared across all other beans in the system.

=== Configuring a sample run time manager with a spring application

The following is an example of a complete spring configuration for a single run time manager within a spring application.

. Configuring the entity manager factory and the transaction manager
+
[source,xml]
----
<bean id="jbpmEMF" class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean">
  <property name="persistenceUnitName" value="org.jbpm.persistence.spring.jta"/>
</bean>

<bean id="jbpmEM" class="org.springframework.orm.jpa.support.SharedEntityManagerBean">
  <property name="entityManagerFactory" ref="jbpmEMF"/>
</bean>

<bean id="narayanaUserTransaction" factory-method="userTransaction" class="com.arjuna.ats.jta.UserTransaction" />

<bean id="narayanaTransactionManager" factory-method="transactionManager" class="com.arjuna.ats.jta.TransactionManager" />

<bean id="jbpmTxManager" class="org.springframework.transaction.jta.JtaTransactionManager">
  <property name="transactionManager" ref="narayanaTransactionManager" />
  <property name="userTransaction" ref="narayanaUserTransaction" />
</bean>
----
+
As a result of these settings, you have the following ready persistence configuration:

*** JTA transaction manager (backed by Narayana JTA - for unit tests or servlet containers)
*** entity manager factory for persistence unit named org.jbpm.persistence.spring.jta

. Configure resource that we are going to use - business process
+
[source,xml]
----
<bean id="process" factory-method="newClassPathResource" class="org.kie.internal.io.ResourceFactory">
  <constructor-arg>
    <value>jbpm/processes/sample.bpmn</value>
  </constructor-arg>
</bean>
----
+
this configures single process that will be available for execution - sample.bpmn that will be taken from class path.
This is the simplest way to get your processes included when trying out jbpm.

. Configure RuntimeEnvironment with our infrastructure (entity manager, transaction manager, resources)
+
[source,xml]
----
<bean id="runtimeEnvironment" class="org.kie.spring.factorybeans.RuntimeEnvironmentFactoryBean">
  <property name="type" value="DEFAULT"/>
  <property name="entityManagerFactory" ref="jbpmEMF"/>
  <property name="transactionManager" ref="jbpmTxManager"/>
  <property name="assets">
    <map>
      <entry key-ref="process"><util:constant static-field="org.kie.api.io.ResourceType.BPMN2"/></entry>
    </map>
  </property>
</bean>
----
+
that gives us a default runtime environment ready to be used to create an instance of a RuntimeManager.

. Create RuntimeManager with the environment we just setup
+
[source,xml]
----
<bean id="runtimeManager" class="org.kie.spring.factorybeans.RuntimeManagerFactoryBean" destroy-method="close">
  <property name="identifier" value="spring-rm"/>
  <property name="runtimeEnvironment" ref="runtimeEnvironment"/>
</bean>
----
+
with just four steps you are ready to execute your processes with Spring and jBPM 6, utilizing EntityManagerFactory and JTA transaction manager.
+
Complete Spring configuration files for different strategies can be found
https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-spring/src/test/resources/jbpm/jta-emf/[here].


This is just one configuration setup that jBPM 6 supports - JTA transaction manager and EntityManagerFactory, others are:

* JTA and SharedEntityManager
* Local Persistence Unit and EntityManagerFactory
* Local Persistence Unit and SharedEntityManager

If your application is configured with Local Persistence Unit and is also utilizing AuditService for querying jBPM history related data, then it's necessary to add _org.kie.api.runtime.EnvironmentName.USE_LOCAL_TRANSACTIONS_ environment entry to the RuntimeEnvironment, for example:

[source,xml]
----
<bean id="runtimeEnvironment" class="org.kie.spring.factorybeans.RuntimeEnvironmentFactoryBean">
...
    <property name="environmentEntries" ref="env" />
  </bean>
  ...

  <util:map id="env" key-type="java.lang.String" value-type="java.lang.Object">
		<entry>
			<key>
				<util:constant
					static-field="org.kie.api.runtime.EnvironmentName.USE_LOCAL_TRANSACTIONS" />
			</key>
			<value>true</value>
		</entry>
	</util:map>
----

For more details about difference configuration options look at the example https://github.com/kiegroup/droolsjbpm-integration/tree/master/kie-spring/src/test/resources/jbpm[configuration files] and https://github.com/kiegroup/droolsjbpm-integration/tree/master/kie-spring/src/test/java/org/kie/spring/jbpm[test cases].

== jBPM services with Spring

In case more dynamic nature is required in your Spring application then it would be more appropriate to build the so-called execution server based on jbpm services.
jBPM services has been designed in a way to make them framework agnostic and in case framework specific addons are required they will be brought by additional module.
So the code logic of the services is embedded in jbpm-kie-services.
These are pure java services and by that can be easily consumed by Spring application.

Dynamic nature means that processes (And other assets like data model, rules, forms, etc) can be added and removed without restarting application.

There is almost no code involved to completely configure jBPM services in spring besides single interface that needs to be implemented - IdentityProvider that depends on your security configuration.
One built with Spring Security can be like following though it might not cover all features one can have for Spring application.

[source,java]
----
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.kie.internal.identity.IdentityProvider;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;

public class SpringSecurityIdentityProvider implements IdentityProvider {

	public String getName() {

		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth != null && auth.isAuthenticated()) {
			return auth.getName();
		}
		return "system";
	}

	public List<String> getRoles() {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth != null && auth.isAuthenticated()) {
			List<String> roles = new ArrayList<String>();

			for (GrantedAuthority ga : auth.getAuthorities()) {
				roles.add(ga.getAuthority());
			}

			return roles;
		}

		return Collections.emptyList();
	}

	public boolean hasRole(String role) {
		return false;
	}

}
----

=== Configure jBPM services in Spring application

As usual, the first thing to start with is transaction configuration:

[source,xml]
----
<context:annotation-config />
<tx:annotation-driven />
<tx:jta-transaction-manager />

<bean id="transactionManager" class="org.springframework.transaction.jta.JtaTransactionManager" />
----

Next configuration of JPA and persistence follows:

[source,xml]
----
<bean id="entityManagerFactory" class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean" depends-on="transactionManager">
   <property name="persistenceXmlLocation" value="classpath:/META-INF/jbpm-persistence.xml" />
</bean>
----

Configure security and user/group information providers

[source,xml]
----
<util:properties id="roleProperties" location="classpath:/roles.properties" />

<bean id="userGroupCallback" class="org.jbpm.services.task.identity.JBossUserGroupCallbackImpl">
  <constructor-arg name="userGroups" ref="roleProperties"></constructor-arg>
</bean>

<bean id="identityProvider" class="org.jbpm.spring.SpringSecurityIdentityProvider"/>
----

Configure runtime manager factory that is Spring context aware and by that can interact with spring container in the correct way and supporting services (transactional command service and task service)
[source,xml]
----
<bean id="runtimeManagerFactory" class="org.kie.spring.manager.SpringRuntimeManagerFactoryImpl">
  <property name="transactionManager" ref="transactionManager"/>
  <property name="userGroupCallback" ref="userGroupCallback"/>
</bean>

<bean id="transactionCmdService" class="org.jbpm.shared.services.impl.TransactionalCommandService">
  <constructor-arg name="emf" ref="entityManagerFactory"></constructor-arg>
</bean>

<bean id="taskService" class="org.kie.spring.factorybeans.TaskServiceFactoryBean" destroy-method="close">
  <property name="entityManagerFactory" ref="entityManagerFactory"/>
  <property name="transactionManager" ref="transactionManager"/>
  <property name="userGroupCallback" ref="userGroupCallback"/>
  <property name="listeners">
    <list>
      <bean class="org.jbpm.services.task.audit.JPATaskLifeCycleEventListener">
        <constructor-arg value="true"/>
      </bean>
    </list>
  </property>
</bean>
----

Configure jBPM services as spring beans

[source,xml]
----
<!-- definition service -->
<bean id="definitionService" class="org.jbpm.kie.services.impl.bpmn2.BPMN2DataServiceImpl"/>

<!-- runtime data service -->
<bean id="runtimeDataService" class="org.jbpm.kie.services.impl.RuntimeDataServiceImpl">
  <property name="commandService" ref="transactionCmdService"/>
  <property name="identityProvider" ref="identityProvider"/>
  <property name="taskService" ref="taskService"/>
</bean>

<!-- deployment service -->
<bean id="deploymentService" class="org.jbpm.kie.services.impl.KModuleDeploymentService" depends-on="entityManagerFactory" init-method="onInit">
  <property name="bpmn2Service" ref="definitionService"/>
  <property name="emf" ref="entityManagerFactory"/>
  <property name="managerFactory" ref="runtimeManagerFactory"/>
  <property name="identityProvider" ref="identityProvider"/>
  <property name="runtimeDataService" ref="runtimeDataService"/>
</bean>

<!-- process service -->
<bean id="processService" class="org.jbpm.kie.services.impl.ProcessServiceImpl" depends-on="deploymentService">
  <property name="dataService" ref="runtimeDataService"/>
  <property name="deploymentService" ref="deploymentService"/>
</bean>

<!-- user task service -->
<bean id="userTaskService" class="org.jbpm.kie.services.impl.UserTaskServiceImpl" depends-on="deploymentService">
  <property name="dataService" ref="runtimeDataService"/>
  <property name="deploymentService" ref="deploymentService"/>
</bean>

<!-- register runtime data service as listener on deployment service so it can receive notification about deployed and undeployed units -->
<bean id="data" class="org.springframework.beans.factory.config.MethodInvokingFactoryBean" depends-on="deploymentService">
  <property name="targetObject" ref="deploymentService"></property>
  <property name="targetMethod"><value>addListener</value></property>
  <property name="arguments">
  <list>
      <ref bean="runtimeDataService"/>
  </list>
  </property>
</bean>
----

And this is all that is needed to build fully featured execution server with Spring and jBPM services.
A complete Spring web application with this setup can be found https://github.com/mswiderski/spring-jbpm-app[here].
