[[_drools.releasenotesdrools.6.4.0]]
= What is New and Noteworthy in Drools 6.4.0
:imagesdir: ..

== Better Java 8 compatibility


It is now possible to use Java 8 syntax (lambdas and method references) in the Right Hand Side (then) part of a rule.

== More robust incremental compilation


The incremental compilation (dynamic rule-base update) had some relevant flaws when one or more rules with a subnetwork (rules with complex existential patterns) were involved, especially when the same subnetwork was shared among different rules.
This issue required a partial rewriting of the existing incremental compilation algorithm, followed by a complete audit that has also been validated by brand new test suite made by more than 20,000 test cases only in this area.

== Improved multi-threading behaviour


Engine's code dealing with multi-threading has been partially rewritten in order to remove a large number of synchronisation points and improve stability and predictability.
In particular this new implementation allows a clearer separation and better interaction between the User thread (performing the insert/update/delete actions on the session), the Engine thread (doing the proper rules evaluation) and the Timer one (performing time-based actions like events expiration).

This improvement has been made possible by the new phreak algorithm introduced with Drools 6.
In fact with in the ReteOO algorithm the network evaluation is performed during the User insert/update/delete action, meaning that each user action locks the entire engine.
Conversely with phreak the insert/update/delete is separated and the network evaluation happens when fireAllRules or fireUntilHalt is called.

More in detail this improvement has been made by 2 parts.
First of all a new thread-safe queue has been added to store all user actions as commands.
This queue is populated by the User thread while its entries are flushed and processed by the Engine thread during the rules evaluations phase.
The second part introduced a state machine coordinating the User, Timer and Engine threads and then providing a clearer and self-documenting way to model their interactions.

== OOPath improvements

[WARNING]
====
This feature is experimental
====


OOPath has been introduced with Drools 6.3.0.
In Drools 6.4.0 it has been enhanced to support the following features: 

* A constraint can also have a beckreference to an object of the graph traversed before the currently iterated one. For example the following OOPath:
+

[source]
----
Student( $grade: /plan/exams/grades{ result > ../averageResult } )
----
+
will match only the grades having a result above the average for the passed exam.
* A constraint can also recursively be another OOPath as it follows:
+

[source]
----
Student( $exam: /plan/exams{ /grades{ result > 20 } } )
----
* It is also possible to use the `?/` separator instead of the `/` one. As in the following example:
+

[source]
----
Student( $grade: /plan/exams{ course == "Big Data" }?/grades )
----
+
By doing so the engine will react to a change made to an exam, or if an exam is added to the plan, but not if a new grade is added to an existing exam.
Of course if a OOPath chunk is not reactive, all remaining part of the OOPath from there till the end of the expression will be non-reactive as well.
For instance the following OOPath
+

[source]
----
Student( $grade: ?/plan/exams{ course == "Big Data" }/grades )
----
+
will be completely non-reactive.
For this reason it is not allowed to use the `?/` separator more than once in the same OOPath so an expression like:
+

[source]
----
Student( $grade: /plan?/exams{ course == "Big Data" }?/grades )
----
+
will cause a compile time error.
