[id='ref_kogito-app-examples']

= {PRODUCT} example applications

{PRODUCT} includes several example applications with {PRODUCT} services to help you develop your own applications. The following list describes some of the examples provided with {PRODUCT}. For the full list of examples and instructions for using them, see the https://github.com/kiegroup/kogito-examples[kogito-examples] page in GitHub.

* `dmn-quarkus-example`: A decision service that uses DMN to determine driver penalty and suspension based on traffic violations
* `drools-quarkus-example`: A set of decision services that use DRL and XLS spreadsheet decision tables to determine a person's adult status, for deployment locally or on OpenShift
* `drools-quarkus-unit-example`: A set of decision services that use DRL with rule units to determine a person's adult status, for deployment locally or on OpenShift
* `drools-polyglot-example`: A scenario that uses plain Java or JavaScript to define a business rule as a demonstration of GraalVM capabilities with Drools
* `ruleunit-quarkus-example` and `ruleunit-springboot-example`: A decision service (on Quarkus or Spring Boot) that  uses DRL with rule units to validate a loan application and that exposes REST operations to view application status
* `jbpm-quarkus-helloworld`: A Hello World process service on Quarkus
* `jbpm-quarkus-example` and `jbpm-springboot-example`: A process service (on Quarkus or Spring Boot) for ordering items and that exposes REST operations to create new orders or to list and delete active orders
* `onboarding-example`: A combination of a process service and two decision services that use DMN and DRL for onboarding new employees
