[id='assembly_integrating-fuse']

include::_artifacts/document-attributes.adoc[]

= Integrating {FUSE_LONG} with {PRODUCT}
// Context attribute is assembly specific and enables module reuse between assemblies.
:doctype: book
:imagesdir: _images
:context: fuse
include::_artifacts/author-group.adoc[]

// Purpose statement for the assembly
As a system administrator, you can integrate {PRODUCT} with {FUSE_LONG} on Apache Karaf and {EAP_LONG} to facilitate communication between integrated services.


// Modules - concepts, procedures, refs, etc.

include::{enterprise-dir}/fuse/fuse-con.adoc[leveloffset=+1]

include::{enterprise-dir}/fuse/ba-engines-karaf-con.adoc[leveloffset=+1]

//include::{enterprise-dir}/fuse/ba-fuse-xml-con.adoc[leveloffset=+1]

include::{enterprise-dir}/fuse/ba-karaf-xml-install-proc.adoc[leveloffset=+2]

include::{enterprise-dir}/fuse/installing-ba-fuse-karaf-maven-proc.adoc[leveloffset=+2]

include::{enterprise-dir}/fuse/ba-karaf-xml-uninstall-proc.adoc[leveloffset=+2]

== {PRODUCT} Camel components
{PRODUCT} Camel components react to business events and call {PRODCUT} services from Camel routes.

=== KIE-Camel component
COMMENT: Describe what it is and how it can be used (short example), installation in Karaf, installation in EAP). Ivo, can you give me this information?  The section that follows is " INSTALLING RED HAT PROCESS AUTOMATION MANAGER ON RED HAT JBOSS EAP WITH FUSE". Is that still relevant?

include::{enterprise-dir}/fuse/installing-on-fuse-eap-proc.adoc[leveloffset=+2]

=== Installing the kie-Camel component in Karaf
=== Camel-jBPM component
Ivo: he one supported on SpringBoot, describe what it is and how it can be used (short example).

Emily: Not possible to include with the 7.4 release because is isn't available yet (through FUSE).

=== jBPM-Workitems-Camel
COMMENT: Describe what it is and how it can be used (short example) - I don't know what it is but it is in the current doc as a Camel component. Need context/overview of what this is, the purpose of it. Might be able to get from Maciej.




== {PRODUCT} Camel service tasks
COMMENT: Calls Camel routes from business processes.

include::{enterprise-dir}/fuse/fuse-connectors-con.adoc[leveloffset=+3]

include::{enterprise-dir}/admin-and-config/manage-service-tasks-proc.adoc[leveloffset=+3]

//== Next steps
//* {URL_TESTING_DECISION_SERVICE}[_{TESTING_DECISION_SERVICE}_]
//* {URL_PACKAGING_DEPLOYING_PROJECT}[_{PACKAGING_DEPLOYING_PROJECT}_]

// Versioning info
include::_artifacts/versioning-information.adoc[]
