[id='case-management-role-authorization-proc-{context}']
= Role authorization

Roles are authorized to perform specific case management tasks when starting a new case instance using the Showcase application or the REST API.

Use the following procedure to start a new IT Orders case using the REST API.

.Prerequisites
* The *IT_Orders* sample project has been imported in {CENTRAL} and deployed to {KIE_SERVER}.


.Procedure

. Create a `POST` REST API call with the following endpoint:
+
`\http://host:port/kie-server/services/rest/server/containers/itorders/cases/itorders.orderhardware/instances`
+
* `itorders`: The container alias that has been deployed to {KIE_SERVER}.
* `itorders.orderhardware`: The name of the case definition.

. Provide the following role configuration in the request body:
+
--
[source,java]
----
{
  "case-data" : {  },
  "case-user-assignments" : {
    "owner" : "cami",
    "manager" : "cami"
  },
  "case-group-assignments" : {
    "supplier" : "IT"
 }
}
----

This starts a new case with defined roles, as well as autostart activities, which are started and ready to be worked on. Two of the roles are user assignments (`owner` and `manager`) and the third is a group assignment (`supplier`).

After the case instance is successfully started, the case instance returns the `IT-0000000001` case ID.
--

For information about how to start a new case instance using the Showcase application, see {URL_DEVELOPING_PROCESS_SERVICES}#assembly-showcase-application[_{SHOWCASE_APPLICATION_CASE_MANAGEMENT}_].
