[id='codeready-studio-setting-jbpm-runtime-environment-proc']
= Installing JBoss BPM Suite runtime environment

In order to create Red Hat JBoss BPM Suite projects in Red Hat CodeReady Studio, it is necessary to install the {PRODUCT} runtime environment.

A runtime environment is a collection of JAR files that represent a specific release of the software and includes the required libraries for compiling and running your business asset.

.Prerequisites
* Red Hat CodeReady Studio is installed.

.Procedure
. Download the {DECISION_ENGINE}:
.. Log in to the https://access.redhat.com[Red Hat Customer Portal].
.. Click *DOWNLOADS* at the top of the page.
.. On the *Product Downloads* page that opens, navigate to the *INTEGRATION AND AUTOMATION* section, and click *{PRODUCT}*.
.. On the *Software Downloads* page, download *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Add-Ons* (`{PRODUCT_FILE}-add-ons.zip`).
.. Extract `{PRODUCT_FILE}-add-ons.zip` and then extract the jBPM runtime environment JAR files located in `{PRODUCT_FILE}-add-ons/{PRODUCT_FILE}-{URL_COMPONENT_DECISION_ENGINE}.zip`.
. From the Red Hat CodeReady Studio menu, click *Window* -> *Preferences*.
. Click *jBPM* -> *Installed jBPM Runtimes*, and then click *Add*.
. In the name field, enter a name for the new runtime environment.
. Click *Browse* and navigate to the directory where you extracted the runtime environment files.
. Click *OK* to register the selected runtime environment in Red Hat CodeReady Studio.
. To set the runtime environment as the default jBPM run time, select the check box beside the runtime environment name.
. Click *Apply and Close*. If you have existing projects, you are prompted to restart Red Hat CodeReady Studio to update the runtime environment.
