[id='codeready-studio-plug-in-install-proc']
= Installing {CODEREADY_STUDIO} plug-ins

The {CODEREADY_STUDIO} plug-ins for {PRODUCT} are based on the community version of the plug-ins.
ifdef::JBPM,DROOLS[]
For this reason, the {PRODUCT} plug-ins are called the jBPM and Drools plug-ins.
endif::[]
ifdef::DM,PAM[]
For this reason, the {PRODUCT} plug-in is called the Drools plug-in.
endif::[]

//Get the latest {CODEREADY_STUDIO} from the https://access.redhat.com[Red Hat Customer //Portal]. The {PRODUCT} plug-ins for {CODEREADY_STUDIO} are available using the update site.

.Procedure
. Download the {PRODUCT} plug-ins for {CODEREADY_STUDIO}:
.. Log in to the https://access.redhat.com[Red Hat Customer Portal].
.. Click *DOWNLOADS* at the top of the page.
.. On the *Product Downloads* page that opens, navigate to the *RUNTIMES* section, and click *Red Hat Developer Studio*.
.. On the *Software Downloads* page, from the *Version* list select *12.11.0*, and then download *{CODEREADY_STUDIO} Integration Stack 12.11.0 Update Site Zip* (`devstudio-integration-stack-12.11.0.GA-updatesite.zip`).
//. Unzip the `devstudio-integration-stack-12.0.0.GA-updatesite.zip` file.
. To start {CODEREADY_STUDIO}, select {CODEREADY_STUDIO} from the *Start* menu.
. Click *Help* -> *Install New Software*.
. Click *Add* to display the *Add Repository* window.
. Enter a name in the *Name* field, for example, `devstudio-12.11.0.GA`.
. Click *Archive*, navigate to the `devstudio-integration-stack-12.11.0.GA-updatesite.zip` file, select the file, and then click *OK*.
. Click *Add*.
//+
//`https://devstudio.jboss.com/12/stable/updates/integration-stack`
. In the *Install* window, select *JBoss Business Process and Rule Development* from the *Available Software* list, click *Next*, and click *Next* again.
. Read the license agreements, click *I accept the terms of the license agreements* to accept the license agreements, and then click *Finish*.
. After the installation process has been completed, click *Restart Now* in the *Software Updates* window to restart {CODEREADY_STUDIO}.
