[id='codeready-studio-creating-BPM-project-proc']
= Creating a Red Hat JBoss BPM Suite project
You can create and manage a Red Hat JBoss BPM Suite project in Red Hat CodeReady Studio.

.Prerequisites
* Red Hat CodeReady Studio is installed with the {PRODUCT} plug-ins.
* {PRODUCT} runtime environment is installed.

.Procedure
. In Red Hat CodeReady Studio, from the main menu, click *File* -> *New* -> *Project*.
. In the search field, enter `jBPM Project`, select *jBPM Project*, and then click *Next*.
. Select the second option to create a project with a {PRODUCT} example, and then click *Next*.
. In the *Project name* field, enter a name for the project.
. Select the *Also include a sample JUnit test for the process* check box.
. Click *Finish*.
. Complete the following steps to test the project:
.. Navigate to the `src/main/java` directory and expand the `com.sample` package.
.. Right click `ProcessTest.java` and select *Run As* -> *JUnit Test*.
+
The output is displayed in the console tab.
