[id='codeready-studio-install-proc']
= Installing Red Hat CodeReady Studio

Red Hat CodeReady Studio is an integrated development environment (IDE) based on Eclipse. It integrates tooling and run time components by combining Eclipse, Eclipse Tooling, and {EAP_LONG}. Red Hat CodeReady Studio provides plug-ins with tools and interfaces for {PRODUCT}.

.Procedure
. Download Red Hat CodeReady Studio:
.. Log in to the https://access.redhat.com[Red Hat Customer Portal].
.. Click *DOWNLOADS* at the top of the page.
.. On the *Product Downloads* page, navigate to the JBOSS DEVELOPMENT AND MANAGEMENT section, and click *Red Hat Developer Studio*.
.. On the *Software Downloads* page, download *Red Hat CodeReady Studio 12.13.0 Stand-alone Installer* (`devstudio-12.13.0.GA-installer-standalone.jar`).
. In a terminal window, navigate to the directory where you downloaded the installer JAR file and enter the following command:
+
[source]
----
java -jar devstudio-12.13.0.GA-installer-standalone.jar
----
. Follow the instructions in the installer to complete the installation.
+
For more information, see the https://access.redhat.com/documentation/en-us/red_hat_codeready_studio/12.13/html/installation_guide/[_Red Hat CodeReady Studio Installation Guide_].

[IMPORTANT]
====
Because of an issue in the way multi-byte rule names are handled, you must ensure that the instance of Red Hat CodeReady Studio is started with the file encoding set to `UTF-8`. You can do this by editing the `$_DS_HOME_/studio/codereadystudio.ini` file and adding the following property: `"-Dfile.encoding=UTF-8"`.
====
