[id='dev-studio-installing-runtime-environments-proc']
= Installing {PRODUCT} runtime environments

In order to create {PRODUCT} projects in Red Hat Developer Studio, it is necessary to install the {PRODUCT} runtime environment.

A runtime environment is a collection of JAR files that represent a specific release of the software and includes the required libraries for compiling and running your business asset.

.Prerequisite
Red Hat Developer Studio is installed.

.Procedure
. Download the {ENGINE}:
.. Log in to the https://access.redhat.com[Red Hat Customer Portal].
.. Click *DOWNLOADS* at the top of the page.
.. On the *Product Downloads* page that opens, navigate to the JBOSS DEVELOPMENT AND MANAGEMENT section, and click *{PRODUCT}*.
.. On the *Software Downloads* page, download *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons* (`{PRODUCT_FILE}-add-ons.zip`).
.. Extract `{PRODUCT_FILE}-add-ons.zip` and then extract the Drools runtime environment JAR files located in `{PRODUCT_FILE}-add-ons/{PRODUCT_FILE}-{URL_COMPONENT_ENGINE}.zip`.
. From the Red Hat Developer Studio menu, click *Window* -> *Preferences*.
. Click *Drools* -> *Installed Drools Runtimes*, and then click *Add*.
. In the name field, enter a name for the new runtime environment.
. Click *Browse* and navigate to the directory where you extracted the runtime environment files.
. Click *OK* to register the selected runtime environment in Red Hat Developer Studio.
. To set the runtime environment as the default Drools run time, select the check box beside the runtime environment name.
. Click *Apply and Close*. If you have existing projects, you are prompted to restart Red Hat Developer Studio to update the runtime environment.
