[id='entando-app-building-proc_{context}']

= Building pages with {PRODUCT} asset data in Entando

After you integrate your {KIE_SERVERS} in Entando, you can use BPM widgets in Entando to build pages with asset data from {PRODUCT}.

.Prerequisites
* One or more {KIE_SERVERS} containing your project data have been configured in Entando App Builder.
* All necessary page models and pages have been set up in Entando App Builder. For instructions, see link:https://central.entando.com/en/documentation.page[_Getting Started with Entando App Builder 5.0_].
* You are logged in to the Entando Admin Console.

.Procedure
. In the Entando Admin Console, go to *Page Designer* -> *Page Tree*.
. Next to the page in which you want to add {PRODUCT} data, click the icon in the *Actions* column and click *Edit*.
. Review all existing page data and ensure that the most appropriate *Page Model* is specified. For example, you can use the provided *BPM layout* page model or any custom page model that is available on your system. To create or modify page models, go to *UX Patterns* -> *Page Models*.
. Click *Save and configure*.
+
The application page is displayed with frames where widgets can be placed according to the defined page model. Available widgets are displayed on the right side of the screen. Widgets listed under *Entando Red Hat BPM connector* are the BPM-specific widgets that enable you to implement {PRODUCT} data in pages.
. Select and drag a BPM widget from the widget menu onto a frame on the page.
. In the widget configuration window that appears, specify the following details that apply to this widget. Options vary based on the type of widget.
+
* *knowledgeSource:* Select the {KIE_SERVER} from which data will be pulled for this widget.
* *deployment-unit:* Select the deployment unit (KIE container) that contains the project with the relevant data for this widget.
* *Channel:* Select the data channel that will be used by this widget. Widgets that share information should be on the same channel. For example, you can use the *BPM-Case instance selector* widget to select a specific case instance and share that selection on a defined channel, and then use the *BPM-Case progress status* widget to read that case selection from the same defined channel to display a progress bar.
. Click *Save* to save the widget configurations.
. Continue dragging, dropping, and configuring widgets as needed to populate the page.
. Click *Preview* to preview page data, and click *Publish* to publish the page.
. After you finish building your pages with {PRODUCT} data, review your published pages to validate the content. To access the published page link, return to the *Page Designer* -> *Page Tree* page and for each page, click the icon in the *Actions* column and click *Details*. Click the globe icon and view the published page in a web browser.

For more information about building applications in Entando, see link:https://central.entando.com/en/documentation.page[_Getting Started with Entando App Builder 5.0_].
