[id='entando-app-building-proc_{context}']

= Building pages with {PRODUCT} asset data in Entando

After you integrate your {KIE_SERVERS} in Entando, you can use {PRODUCT} widgets in Entando to build pages with asset data from {PRODUCT}.

.Prerequisites
* One or more {KIE_SERVERS} containing your project data have been configured in Entando App Builder.
* All necessary page models and pages have been set up in Entando App Builder. For instructions, see link:http://docs.entando.com/[_Getting Started with Entando App Builder_].
* You are logged in to the Entando Admin Console.

.Procedure
. In the Entando Admin Console, go to *Page Designer* -> *Page Tree*.
. Next to the page in which you want to add {PRODUCT} data, click the icon in the *Actions* column and click *Edit*.
. Review all existing page data and ensure that the most appropriate *Page Model* is specified. You can create or modify page models in *UX Patterns* -> *Page Models*.
. Click *Save and configure*.
+
The application page is displayed with frames where widgets can be placed according to the defined page model. Available widgets are displayed on the right side of the screen. Widgets listed under *Entando Red Hat PAM connector* are the BPM-specific widgets that enable you to implement {PRODUCT} data in pages.
. Select and drag a {PRODUCT} widget from the widget menu onto a frame on the page.
. In the widget configuration window that appears, specify the details that apply to the widget. Options vary based on the type of widget.
+
* *knowledgeSource:* Select the {KIE_SERVER} from which data will be pulled for this widget.
* *deployment-unit:* Select the deployment unit (KIE container) that contains the project with the relevant data for this widget.
* *Channel:* Select the data channel that will be used by this widget. Widgets that share information should be on the same channel. For example, you can use the *PAM-Case instance selector* widget to select a specific case instance and share that selection on a defined channel, and then use the *PAM-Case progress status* widget to read that case selection from the same defined channel to display a progress bar.
. Click *Save* to save the widget configurations.
. Continue dragging, dropping, and configuring widgets as needed to populate the page.
. Click *Preview* to preview page data, and click *Publish* to publish the page.
. After you finish building your pages with {PRODUCT} data, review your page details to validate the content. To access the page details, return to *Page Designer* -> *Page Tree* and for each page, click the icon in the *Actions* column and click *Details* -> *Info*.

For more information about building applications in Entando, see link:http://docs.entando.com/[_Getting Started with Entando App Builder_].
