[id='sso-user-manage-proc']
= Enabling user and group management for RH-SSO
This section describes how you can configure {CENTRAL} to manage users and groups stored in RH-SSO.

.Procedure
Set the following system properties to enable user management:

* `org.uberfire.ext.security.management.api.userManagementServices=KCAdapterUserManagementService`
* `org.uberfire.ext.security.management.keycloak.authServer=http://localhost:8180/auth`

You can set these system properties in the following ways:

* Set the system properties in your `standalone-full.xml` file:
+
[source]
----
<property name="org.uberfire.ext.security.management.api.userManagementServices" value="KCAdapterUserManagementService"/>
<property name="org.uberfire.ext.security.management.keycloak.authServer" value="http://localhost:8180/auth"/>
----
* Set the system properties when starting {CENTRAL}:
+
[source]
----
./bin/standalone.sh -Dorg.uberfire.ext.security.management.api.userManagementServices=KCAdapterUserManagementService -Dorg.uberfire.ext.security.management.keycloak.authServer=http://localhost:8180/auth
----
* Replace the entire contents of the `WEB-INF/classes/security-management.properties` file with the following content:
+
[source]
----
org.uberfire.ext.security.management.api.userManagementServices=KCAdapterUserManagementService
org.uberfire.ext.security.management.keycloak.authServer=http://localhost:8180/auth
----
+
NOTE: If the `WEB-INF/classes/security-management.properties` file does not exist, create it.
