[id='sso-kie-server-client-adapter-proc']
= Installing and configuring {KIE_SERVER} with the client adapter

After you install RH-SSO, you must install the RH-SSO client adapter for {EAP} and configure it for {KIE_SERVER}.

.Prerequisites

* {KIE_SERVER} is installed in a {EAP} {EAP_VERSION} server, as described in {URL_INSTALLING_AND_CONFIGURING}#assembly-install-on-eap[_{INSTALLING_ON_EAP}_].
* RH-SSO is installed as described in <<sso-realm-proc>>.
* At least one user with the `kie-server` role has been added to RH-SSO as described in <<sso-user-add-proc>>.

[NOTE]
====
If you deployed {KIE_SERVER} to a different application server than {CENTRAL}, install and configure RH-SSO on your second server as well.
====

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* *Product:* {RH-SSO}
* *Version:* {RH-SSO_VERSION}
. Download *{RH-SSO} {RH-SSO_VERSION} Client Adapter for JBoss EAP 7* (`rh-sso-{RH-SSO_VERSION_LONG}-eap7-adapter.zip` or the latest version).
. Extract and install the adapter zip file. For installation instructions, see the "JBoss EAP Adapter" section of the https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/{RH-SSO_VERSION}/html-single/securing_applications_and_services_guide/#jboss_adapter[_Red Hat Single Sign On Securing Applications and Services Guide_].
. Go to `_EAP_HOME_/standalone/configuration` and open the `standalone-full.xml` file.
. Delete the `<single-sign-on/>` element from both of the files.
. Navigate to `_EAP_HOME_/standalone/configuration` directory in your {EAP} installation and edit the `standalone-full.xml` file to add the RH-SSO subsystem configuration. For example:
+
. Navigate to `_EAP_HOME_/standalone/configuration` in your {EAP} installation and edit the `standalone-full.xml` file to add the RH-SSO subsystem configuration. For example:
+
--
[source,xml,subs="attributes+"]
----
<subsystem xmlns="urn:jboss:domain:keycloak:1.1">
  <secure-deployment name="kie-server.war">
     <realm>demo</realm>
     <realm-public-key>MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrVrCuTtArbgaZzL1hvh0xtL5mc7o0NqPVnYXkLvgcwiC3BjLGw1tGEGoJaXDuSaRllobm53JBhjx33UNv+5z/UMG4kytBWxheNVKnL6GgqlNabMaFfPLPCF8kAgKnsi79NMo+n6KnSY8YeUmec/p2vjO2NjsSAVcWEQMVhJ31LwIDAQAB</realm-public-key>
     <auth-server-url>http://localhost:8180/auth</auth-server-url>
     <ssl-required>external</ssl-required>
     <resource>kie-execution-server</resource>
     <enable-basic-auth>true</enable-basic-auth>
     <credential name="secret">03c2b267-7f64-4647-8566-572be673f5fa</credential>
     <principal-attribute>preferred_username</principal-attribute>
  </secure-deployment>
</subsystem>

<system-properties>
  <property name="org.kie.server.sync.deploy" value="false"/>
</system-properties>
----

In this example:

* `secure-deployment name` is the name of your application WAR file.
* `realm` is the name of the realm that you created for the applications to use.
* `realm-public-key` is the  public key of the realm you created. You can find the key in the *Keys* tab in the *Realm settings* page of the realm you created in the RH-SSO Admin Console. If you do not provide a value for this public key, the server retrieves it automatically.
* `auth-server-url` is the  URL for the RH-SSO authentication server.
* `resource` is the name for the server client that you created.
* `enable-basic-auth` is the setting to enable basic authentication mechanism, so that the clients can use both token-based and basic authentication approaches to perform the requests.
* `credential name` is the secret key of the server client you created. You can find the key in the *Credentials* tab on the *Clients* page of the RH-SSO Admin Console.
* `principal-attribute` is the login name of the user. If you do not provide this value, your User Id is displayed in the application instead of your user name.
--
+

. Save your configuration changes.
. Use the following command to restart the {EAP} server and run {KIE_SERVER}.
+
[source,subs="attributes+"]
----
EXEC_SERVER_HOME/bin/standalone.sh -c standalone-full.xml -Dorg.kie.server.id=<ID> -Dorg.kie.server.user=<USER> -Dorg.kie.server.pwd=<PWD> -Dorg.kie.server.location=<LOCATION_URL> -Dorg.kie.server.controller=<CONTROLLER_URL> -Dorg.kie.server.controller.user=<CONTROLLER_USER> -Dorg.kie.server.controller.pwd=<CONTOLLER_PASSWORD>
----
+
For example:
+
[source,subs="attributes+"]
----
EXEC_SERVER_HOME/bin/standalone.sh -c standalone-full.xml -Dorg.kie.server.id=kieserver1 -Dorg.kie.server.user=kieserver -Dorg.kie.server.pwd=password -Dorg.kie.server.location=http://localhost:8080/kie-server/services/rest/server -Dorg.kie.server.controller=http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/controller -Dorg.kie.server.controller.user=kiecontroller -Dorg.kie.server.controller.pwd=password
----
+
. When {KIE_SERVER} is running, enter the following command to check the server status, where `<KIE_SERVER_USER>` is a user with the `kie-server` role and `<PASSWORD>` is the password for that user:
+
[source,subs="attributes+"]
----
curl http://<KIE_SERVER_USER>:<PASSWORD>@localhost:8080/kie-server/services/rest/server/
----
