[id='sso-realm-proc']
= Installing and configuring RH-SSO

A realm is a security policy domain defined for a web or application server. Security realms are used to restrict access for different application resources. You should create a new realm whether your RH-SSO instance is private or shared with other products. You can keep the master realm as a place for super administrators to create and manage the realms in your system. If you are integrating with an RH-SSO instance that is shared with other product installations to achieve single sign-on with those applications, all of those applications must use the same realm. To create an RH-SSO realm, download, install, and configure RH-SSO {RH-SSO_VERSION}.

[NOTE]
====
If {CENTRAL} and {KIE_SERVER} are installed on different servers, complete this procedure on both servers.
====

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* *Product:* {RH-SSO}
* *Version:* {RH-SSO_VERSION}
. Download *{RH-SSO} {RH-SSO_VERSION}.0 Server* (`rh-sso-{RH-SSO_VERSION}.0.zip`) and the latest server patch.
. To install and configure a basic RH-SSO standalone server, follow the instructions in the https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/{RH-SSO_VERSION}/html-single/getting_started_guide/[_Red Hat Single Sign On Getting Started Guide_]. For advanced settings for production environments, see the https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/{RH-SSO_VERSION}/html-single/server_administration_guide/[_Red Hat Single Sign On Server Administration Guide_].
+
[NOTE]
====
If you want to run both RH-SSO and {PRODUCT} servers on the same system, ensure that you avoid port conflicts by taking one of the following actions:

* Update the `_RHSSO_HOME_/standalone/configuration/standalone-full.xml` file and set the port offset to 100. For example:
+
[source]
----
<socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:100}">
----

* Use an environment variable to set the port offset when running the server:
+
[source]
----
bin/standalone.sh -Djboss.socket.binding.port-offset=100
----
====
