[id='sso-kie-server-client-proc']
= Creating the {KIE_SERVER} client on RH-SSO
Use the RH-SSO Admin Console to create a {KIE_SERVER} client in an exiting realm.

.Prerequisites

* {KIE_SERVER} is installed in a {EAP} 7.1 server, as described in {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].
* RH-SSO is installed as described in <<sso-realm-proc>>.
* At lease one user with the `kie-server` role has been added to RH-SSO as described in <<sso-user-add-proc>>.

.Procedure
. In the RH-SSO Admin Console, open the security realm that you created in <<sso-realm-proc>>.
. Click *Clients* and click *Create*.
+
The *Add Client* page opens.
+
. On the *Add Client* page, provide the required information to create a {KIE_SERVER} client for your realm, then click *Save*. For example:
+
* *Client ID*: kie-execution-server
* *Root URL*: http://_localhost_:8080/kie-server
* *Client protocol*: openid-connect
+
. The new client *Access Type* is set to `public` by default. Change it to `confidential` and click *Save* again.
. Navigate to the *Credentials* tab and copy the secret key. The secret key is required to configure the `kie-execution-server` client. 