[id='sso-client-adapter-proc']
= Installing the RH-SSO client adapter for {CENTRAL}

After you install RH-SSO, you must install the RH-SSO client adapter for {EAP} and configure it for {CENTRAL}.

.Prerequisites
* {CENTRAL} is installed in a {EAP} {EAP_VERSION} instance, as described in {URL_INSTALLING_AND_CONFIGURING}#assembly-install-on-eap[_{INSTALLING_ON_EAP}_].
* RH-SSO is installed as described in <<sso-realm-proc>>.
* A user with the `admin` role has been added to RH-SSO as described in <<sso-user-add-proc>>.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* *Product:* {RH-SSO}
* *Version:* {RH-SSO_VERSION}
. Select the *Patches* tab.
. Download *{RH-SSO} {RH-SSO_VERSION} Client Adapter for EAP 7* (`rh-sso-{RH-SSO_VERSION_LONG}-eap7-adapter.zip` or the latest version).
. Extract and install the adapter zip file. For installation instructions, see the "JBoss EAP Adapter" section of the https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/{RH-SSO_VERSION}/html-single/securing_applications_and_services_guide[_Red Hat Single Sign On Securing Applications and Services Guide_].
+
NOTE: Install the adapter with the `-Dserver.config=standalone-full.xml` property.

. Navigate to the `_EAP_HOME_/standalone/configuration` directory in your {EAP} installation and open the `standalone-full.xml` file in a text editor.
. Add the system properties listed in the following example to `<system-properties>`:
+
--
[source,xml,subs="attributes+"]
----
<system-properties>
  <property name="org.jbpm.workbench.kie_server.keycloak" value="true"/>
  <property name="org.uberfire.ext.security.management.api.userManagementServices" value="KCAdapterUserManagementService"/>
  <property name="org.uberfire.ext.security.management.keycloak.authServer" value="http://localhost:8180/auth"/>
</system-properties>
----
--
+
. Optional: If you want to use client roles, add the following system property:
+
--
[source,xml,subs="attributes+"]
----
  <property name="org.uberfire.ext.security.management.keycloak.use-resource-role-mappings" value="true"/>
----

By default, the client resource name is `kie`. The client resource name must be the same as the client name that you used to configure the client in RH-SSO. If you want to use a custom client resource name, add the following system property:

[source,xml,subs="attributes+"]
----
  <property name="org.uberfire.ext.security.management.keycloak.resource" value="customClient"/>
----

Replace `customClient` with the client resource name.
--
+
. Add the RH-SSO subsystem configuration. For example:
+
[source,xml,subs="attributes+"]
----
<subsystem xmlns="urn:jboss:domain:keycloak:1.1">
 <secure-deployment name="{URL_COMPONENT_CENTRAL}.war">
   <realm>demo</realm>
   <realm-public-key>MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrVrCuTtArbgaZzL1hvh0xtL5mc7o0NqPVnYXkLvgcwiC3BjLGw1tGEGoJaXDuSaRllobm53JBhjx33UNv+5z/UMG4kytBWxheNVKnL6GgqlNabMaFfPLPCF8kAgKnsi79NMo+n6KnSY8YeUmec/p2vjO2NjsSAVcWEQMVhJ31LwIDAQAB</realm-public-key>
   <auth-server-url>http://localhost:8180/auth</auth-server-url>
   <ssl-required>external</ssl-required>
   <enable-basic-auth>true</enable-basic-auth>
   <resource>kie</resource>
   <credential name="secret">759514d0-dbb1-46ba-b7e7-ff76e63c6891</credential>
   <principal-attribute>preferred_username</principal-attribute>
 </secure-deployment>
</subsystem>
----
+
In this example:

* `secure-deployment name` is the name of your application's WAR file.
* `realm` is the name of the realm that you created for the applications to use.
* `realm-public-key` is the public key of the realm you created. You can find the key in the *Keys* tab in the *Realm settings* page of the realm you created in the RH-SSO Admin Console. If you do not provide a value for `realm-public-key`, the server retrieves it automatically.
* `auth-server-url` is the  URL for the RH-SSO authentication server.
* `enable-basic-auth` is the  setting to enable basic authentication mechanism, so that the clients can use both token-based and basic authentication approaches to perform the requests.
* `resource` is the name for the client that you created. To use client roles, set the client resource name that you used when configuring the client in RH-SSO.
* `credential name` is the  secret key for the client you created. You can find the key in the *Credentials* tab on the *Clients* page of the RH-SSO Admin Console.
* `principal-attribute` is the login name of the user. If you do not provide this value, your User Id is displayed in the application instead of your user name.
+
[NOTE]
====
The RH-SSO server converts the user names to lower case. Therefore, after integration with RH-SSO, your user name will appear in lower case in {PRODUCT}. If you have user names in upper case hard coded in business processes, the application might not be able to identify the upper case user.
====
+
If you want to use client roles, also add the following setting under `<secure-deployment>`:
+
[source,xml,subs="attributes+"]
----
<use-resource-role-mappings>true</use-resource-role-mappings>
----
+
. The Elytron subsystem provides a built-in policy provider based on JACC specification. To enable the JACC manually in the `standalone.xml` or in the file where Elytron is installed, do any of the following tasks:

* To create the policy provider, enter the following commands in the management command-line interface (CLI) of {EAP}:
+
--
[source]
----
/subsystem=undertow/application-security-domain=other:remove()
/subsystem=undertow/application-security-domain=other:add(http-authentication-factory="keycloak-http-authentication")
/subsystem=ejb3/application-security-domain=other:write-attribute(name=security-domain, value=KeycloakDomain)
----
--
+
For more information about the {EAP} management CLI, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/{EAP_VERSION}/html-single/management_cli_guide/index[_Management CLI Guide_] for {EAP}.

* Navigate to the `_EAP_HOME_/standalone/configuration` directory in your {EAP} installation.
  Locate the Elytron and undertow subsystem configurations in the `standalone.xml` and `standalone-full.xml` files and enable JACC. For example:
+
--
[source,xml,subs="attributes+"]
----
<subsystem xmlns="urn:jboss:domain:undertow:12.0" ... >
...
  <application-security-domains>
    <application-security-domain name="other" http-authentication-factory="keycloak-http-authentication"/>
  </application-security-domains>
----

[source,xml,subs="attributes+"]
----
<subsystem xmlns="urn:jboss:domain:ejb3:9.0">
...
  <application-security-domains>
      <application-security-domain name="other" security-domain="KeycloakDomain"/>
  </application-security-domains>
----

[NOTE]
====
To use the Elytron subsystem, you must disable JACC in the legacy `security` subsystem. To disable JACC in the legacy subsystem, enter the following command in the {EAP} management CLI:

----
/subsystem=security:write-attribute(name=initialize-jacc, value=false)
----

For more information about disabling JACC in the legacy security subsystem, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html-single/development_guide/index#enabling_jacc_using_elytron[_Development Guide_] for {EAP}.
====
--
. Navigate to `_EAP_HOME_/bin/` and enter the following command to start the {EAP} server:
+
--
[source]
----
./standalone.sh -c standalone-full.xml
----
--

[NOTE]
====
You can also configure the RH-SSO adapter for {CENTRAL} by updating your application's WAR file to use the RH-SSO security subsystem. However, Red Hat recommends that you configure the adapter through the RH-SSO subsystem. Doing this updates the {EAP} configuration instead of applying the configuration on each WAR file.
====
