[id='sso-int-con']
= Integration Options

{RH-SSO} (RH-SSO) is a single sign-on solution that you can use to secure your browser applications with your REST web services and Git access.

When you integrate {PRODUCT} with RH-SSO, you create an SSO and identity management (IDM) environment for {PRODUCT}. The session management feature of RH-SSO enables you to use a single authentication for different {PRODUCT} environments on the internet.

The following chapters describe how you can integrate RH-SSO with {PRODUCT}:

* *xref:sso-central-proc_integrate-sso[]*
+
To authenticate {PRODUCT} through an RH-SSO server, you must secure both the {PRODUCT} web client ({CENTRAL}) and remote services through RH-SSO.This integration enables you to connect to {PRODUCT} through RH-SSO using either {CENTRAL} or a remote service consumer.

* *xref:sso-kie-server-con_integrate-sso[]*
+
To authenticate {KIE_SERVER} through an RH-SSO server, you must secure the remote services provided by {KIE_SERVER}. Doing this enables any remote {PRODUCT} service consumer (user or a service) to authenticate through RH-SSO. Note that {KIE_SERVER} does not have a web interface.

* *xref:sso-third-party-proc_integrate-sso[]*
+
If {CENTRAL} or {KIE_SERVER} are using RH-SSO, third-party clients must authenticate themselves using RH-SSO. After authentication, they can consume the remote service endpoints provided by {CENTRAL} and {KIE_SERVER}, such as the REST API or remote file system services.

To facilitate LDAP integration with {PRODUCT}, consider using RH-SSO with LDAP. For information, see the "LDAP and Active Directory" section of the https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/{RH-SSO_VERSION}/html-single/server_administration_guide[_{RH-SSO} Server Administration Guide_].
