[id='sso-central-client-create-proc']
= Creating the {Central} client for RH-SSO

After the RH-SSO server starts, use the RH-SSO Admin Console to create the {Central} client for RH-SSO.

.Procedure
. Enter `\http://localhost:8180/auth/admin` in a web browser to open the RH-SSO Admin Console  and log in using the admin credentials that you created while installing RH-SSO.
+
[NOTE]
====
If you are configuring RH-SSO with {OPENSHIFT}, enter the URL that is exposed by the RH-SSO routes. Your OpenShift administrator can provide this URL if necessary.
====
+
When you login for the first time, you can set up the initial user on the new user registration form.
. In the RH-SSO Admin Console, click the *Realm Settings* menu item.
. On the *Realm Settings* page, click *Add Realm*.
+
The *Add realm* page opens.

. On the *Add realm* page, provide a name for the realm and click *Create*.
. Click the *Clients* menu item and click *Create*.
+
The *Add Client* page opens.

. On the *Add Client* page, provide the required information to create a new client for your realm. For example:
* *Client ID*: kie
* *Client protocol*: openid-connect
* *Root URL*: `http://_localhost_:8080/{URL_COMPONENT_CENTRAL}`
+
[NOTE]
====
If you are configuring RH-SSO with {OPENSHIFT}, enter the URL that is exposed by the {KIE_SERVER} routes. Your OpenShift administrator can provide this URL if necessary.
====
+
. Click *Save* to save your changes.
+
After you create a new client, its *Access Type* is set to `public` by default. Change it to `confidential`.
+
The RH-SSO server is now configured with a realm with a client for {CENTRAL} applications and running and listening for HTTP connections at [parameter]``localhost:8180``. This realm provides different users, roles, and sessions for {CENTRAL} applications.
+
[NOTE]
====
The RH-SSO server client uses one URL to a single {URL_COMPONENT_CENTRAL} deployment. The following error message might be displayed if there are two or more deployment configurations:

We are sorry... `Invalid parameter: redirect_uri`

To resolve this error, append `/pass:[*]` to the *Valid Redirect URIs* field in the client configuration.

On the *Configure* page, go to *Clients* > *kie* > *Settings*, and append the *Valid Redirect URIs* field with `/*`, for example:

----
http://localhost:8080/business-central/*
----
====
