[id='dev-studio-clone-remote-git-repo-proc']
= Cloning a remote Git repository
You can clone a git repository to use with Red Hat JBoss Developer Studio.

.Prerequisites
* Red Hat JBoss Developer Studio is installed with the {PRODUCT} plug-ins.
* You have access permission for the remote Git repository that you want to clone.

.Procedure
. In Red Hat JBoss Developer Studio, select the server from the *Server* tab and click the start icon to start the server.
. Enter the following command in a terminal to start the secure shell server, if it is not running already. 
+
[source]
----
/sbin/service sshd start
----
+
[NOTE]
====
This command is specific to Linux and Apple Macintosh. On these platforms, if `sshd` has already been started, this command fails. If this happens, you may safely ignore this step.
====
. In Red Hat JBoss Developer Studio , select *File* -> *Import...* and navigate to the Git folder. 
. Open the Git folder, select *Projects from Git*, and click *Next*.
. Select the repository source as *Clone URI* and click *Next*.
. Enter the details of the Git repository and click *Next*.
. Select the branch you want to import and click *Next*.
. To define the local storage for this project, enter or select a non-empty directory, make any configuration changes, and click *Next*.
. Import the project as a general project in the following window and click *Next*.
. Name the project and click *Finish*.
