[id='entando-pages-con_{context}']

= Page models and pages in Entando

In Entando App Builder, page models define the available frames and overall layout for the application pages that you create. The page model that you assign to a page determines the location and type of widgets that you can add to a page. Widgets are the building blocks for your application pages.

Page models are defined by two configuration elements:

* JSON Configuration
* Template

The JSON configuration is JSON-formatted text in which you define the frames list that will make up that model of the page. The template defines the look and feel of the rendered page model. The template is written in Velocity Template Language (VTL) to incorporate dynamic content in a web page. VTL supports statements and directives, references and comments, access to exposed java objects and methods, and other resources to design optimal application pages.

Entando App Builder 5.0 includes a default *BPM layout* page model that is ideal for building pages that integrate {PRODUCT} data in your Entando pages. You can create any custom BPM page models as needed in *UX Patterns -> Page Models*.

For more information about creating Entando App Builder page models and pages, see link:https://central.entando.com/en/documentation.page[_Getting Started with Entando App Builder 5.0_].
