[id='sso-client-adapter-create']
= Creating and configuring the RH-SSO client adapter for BAM

After you have created a realm client for {PRODUCT} and set up the RH-SSO client adapter for {EAP}, you can repeat the same steps to integrate BAM with RH-SSO. After successful integration of RH-SSO with BAM, you can navigate within {PRODUCT} and BAM without having to re-login.

.Procedure
. In the RH-SSO Admin Console, open the security realm that you created.
. Click the *Clients* menu item and click *Create*.
+
The *Add Client* page opens.

. On the *Add Client* page, provide the required information to create a new BAM client for your realm. For example:
* *Client ID*: dashbuilder
* *Root URL*: http://_localhost_:8080/dashbuilder
* *Client protocol*: openid-connect
+
After you create a new client, its *Access Type* is set to `public` by default. Change it to `confidential`. 
+
. Configure the RH-SSO client adapter for BAM. To do so, navigate to `_EAP_HOME_/standalone/configuration` in your {EAP} installation and edit `standalone.xml` to add the RH-SSO subsystem configuration. For example:
+
--
[source,xml]
----
<secure-deployment name="dashbuilder.war">
  <realm>demo</realm>
  <realm-public-key>MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrVrCuTtArbgaZzL1hvh0xtL5mc7o0NqPVnYXkLvgcwiC3BjLGw1tGEGoJaXDuSaRllobm53JBhjx33UNv+5z/UMG4kytBWxheNVKnL6GgqlNabMaFfPLPCF8kAgKnsi79NMo+n6KnSY8YeUmec/p2vjO2NjsSAVcWEQMVhJ31LwIDAQAB</realm-public-key>
  <auth-server-url>http://localhost:8180/auth</auth-server-url>
  <ssl-required>external</ssl-required>
  <resource>dashbuilder</resource>
  <enable-basic-auth>true</enable-basic-auth>
  <credential name="secret">e92ec68d-6177-4239-be05-28ef2f3460ff</credential>
  <principal-attribute>preferred_username</principal-attribute>
</secure-deployment>
----

Here,

* `secure-deployment name`: The name of the BAM war file being deployed.
* `realm-public-key`: The public key of the realm you created.
* `resource`: The name of the client that you created for BAM (dashbuilder).
* `enable-basic-auth`: The setting to enable basic authentication mechanism, so that the clients can use both token-based and basic authentication approaches to perform the requests.
* `credential name`: The secret key for the client you created for BAM. You can find the key in the *Credentials* tab on the *Clients* page of the RH-SSO Admin Console.
* `principal-attribute`: The login name of the user. If you do not provide this value, your User Id is displayed in the application instead of your user name.
--
+

. Restart the {EAP} server and open http://localhost:8080/dashbuilder in a web browser to access BAM. Log in to BAM using your RH-SSO admin user credentials.
+
You can now access both the applications ({PRODUCT} and BAM) without having to re-login.

