[id='ba-roles-con']
= Roles and users

Before starting the server and logging in to {CENTRAL}, you must create the `admin` role. This section describes the different user roles that are used in {PRODUCT}:

* `admin`: The users with `admin` role are the administrators of the application. Administrators can manage users, manage the repositories (create and clone), and have full access to make the required changes in the application. Admins have access to all areas within the system.
ifdef::PAM[]
* `developer`: A developer has access to almost all features and can manage rules, models, process flows, forms, and dashboards. They can manage the asset repository, they can create, build and deploy projects and they can even use Red&nbsp;Hat JBoss&nbsp;Developer&nbsp;Studio to view processes. Only certain administrative functions like creating and cloning a new repository are hidden for the developer role.
endif::PAM[]
* `analyst`: An `analyst` role has access to all high-level features to model
ifdef::PAM[]
and execute their
endif::PAM[]
projects. However, *Authoring* -> *Administration* access is unavailable to users with the `analyst` role. Certain lower-level features targeted towards developers, like the *Deployment* -> *Artifact Repository* view are not accessible for this role. However, the *Build & Deploy* button is available for the analyst role while using the Project Editor.
ifdef::PAM[]
* `user`: User or a business user work on the business task lists that are used to operate a certain process. A user with this role can access the dashboard and manage processes.
* `manager`: A manager is a viewer of the system and is interested in statistics around the business processes and their performance, business indicators, and other reporting of the system. A user with this role has access to the BAM only.
endif::PAM[]

NOTE: Enter the above mentioned roles during the user creation process.
