[id='cluster-custom-config-proc']

= Clustering {PRODUCT} on {EAP}

When using {EAP} clustering, a single {EAP} domain controller exists with other {EAP} slaves connecting to it as management users. You can deploy {CENTRAL} as a management user on a domain controller, and the WAR deployments will be distributed to other members of the {EAP} cluster.

.Prerequisite
* A {EAP} cluster is available. 

.Procedure

. Define the data source driver.
+
.PostgreSQL Driver Definition
====
[source,xml]
----
<driver name="postgres" module="org.postgresql">
  <xa-datasource-class>org.postgresql.xa.PGXADataSource</xa-datasource-class>
</driver>
----
====
+
Ensure that the data sources contain schemas. If your data source does not contain schemas, ensure your nodes start one at a time.

.
// change on purpose - cd = change directory
. Change to `_EAP_HOME_/bin` and start the application server in domain mode:
+
On UNIX systems:
+
----
./domain.sh
----
+
On Windows:
+
----
./domain.bat
----

. Check that the nodes are available.

Deploy the {CENTRAL} application to your servers:

ifdef::PAM[]
. Change the predefined persistence of the application to the required database (PostgreSQL): in `persistence.xml` change the following:
+
.. `jta-data-source` name to the source defined on the application server (`java:jboss/datasources/psbpmsDS`).
.. Hibernate dialect to be match the data source dialect (`org.hibernate.dialect.PostgreSQLDialect`).

. Log in as the management user to the server *Administration* console of your domain and add the new deployments using the *Runtime view* of the console. Once the deployment is added to the domain, assign it to the correct server group (`main-server-group`).
endif::PAM[]

ifdef::DM[]
* Log in as the management user to the server *Administration* console of your domain and add the new deployments using the *Runtime view* of the console. Once the deployment is added to the domain, assign it to the correct server group (`main-server-group`).
endif::DM[]

[NOTE]
====
Make sure to explicitly check deployment unit readiness with every cluster member.

When a deployment unit is created on a cluster node, it takes some time before it is distributed among all cluster members. Deployment status can be checked using the UI and REST, however, if the query goes to the node where the deployment was originally issued, the answer is `deployed`. Any request targeting this deployment unit sent to a different cluster member fails with `DeploymentNotFoundException`.
====

ifdef::PAM[]
[id='_exec_server']
