[id='components-con']
= {PRODUCT} components

{PRODUCT} is made up of {CENTRAL}, {KIE_SERVER}, and {PLANNER}.

* {CENTRAL} is the graphical user interface where you create and manage business rules. You can install {CENTRAL} in a {EAP} instance or on the Red Hat OpenShift Container Platform (OpenShift). 
+
{CENTRAL} is also available as a standalone JAR file. You can use the {CENTRAL} standalone JAR file to run {CENTRAL} without needing to deploy it to an application server.
* {KIE_SERVER} is the server where rules and other artifacts are stored. It is used to instantiate and execute rules and solve planning problems. You can install {KIE_SERVER} in a {EAP} instance, on OpenShift, in an Oracle WebLogic server instance, or an IBM WebSphere Application Server instance. 
+
You can configure Process Server to run in managed or unmanaged mode. If Process Server is unmanaged, you must manually create and maintain containers. If Process Server is managed, the Process Automation Manager controller manages the Process Server configuration and you interact with the controller to create and maintain containers.
+
The Process Automation Manager controller is integrated with Business Central. If you install Business Central, use the Execution Server page to create and maintain containers. However, if you do not install Business Central, you can install the headless Process Automation Manager controller and use the REST API or the Process Server Java Client API to interact with it.
+ 
* {PLANNER} is a lightweight, embeddable planning engine that optimizes planning
problems. It helps Java programmers solve planning problems efficiently, and it combines
optimization heuristics and metaheuristics with efficient score calculations.


