[id='decision_tables_upload_proc']
= Uploading decision tables

After you define your rules in an external XLS or XLSX file, you can upload the file as a decision table in your project in {CENTRAL}.

IMPORTANT: You should typically upload only one decision table spreadsheet, containing all necessary `RuleTable` definitions, per rule package in {CENTRAL}. You can upload separate decision table spreadsheets for separate packages, but uploading multiple decision table spreadsheets in the same package can cause compilation errors from conflicting `RuleSet` or `RuleTable` attributes and is therefore not recommended.

.Procedure
. Go to *Menu* -> *Design* -> *Projects* and click the project name.
. Click *Add Asset* -> *Decision Table (Spreadsheet)*.
. Enter an informative *Decision Table* name and select the appropriate *Package*.
. Select the file type (*xls* or *xlsx*), click the *Choose File* icon, and select the spreadsheet. Click *Ok* to upload.
. In the decision tables designer, click *Validate* in the upper-right toolbar to validate the table. If the table validation fails, open the XLS or XLSX file and address any syntax errors. For syntax help, see xref:decision-tables-defining-proc[].

.Converting a decision table spreadsheet to a guided decision table
[NOTE]
====
To convert an uploaded decision table spreadsheet to a guided decision table, click *Convert* in the upper-right toolbar in the decision tables designer. Converting the spreadsheet to a guided decision table enables you to edit the table data directly in {CENTRAL}. For more information about guided decision tables, see {URL_GUIDED_DECISION_TABLES}[_{GUIDED_DECISION_TABLES}_].
====
