= Sliding Time Windows
:imagesdir: ../..


Sliding Time Windows allow the user to write rules that will only match events occurring in the last X time units.

For instance, if the user wants to consider only the Stock Ticks that happened in the last 2 minutes, the pattern would look like this:

[source]
----
StockTick() over window:time( 2m )
----


Drools uses the "over" keyword to associate windows to patterns.

On a more elaborate example, if the user wants to sound an alarm in case the average temperature over the last 10 minutes read from a sensor is above the threshold value, the rule would look like:

.aggregating values over time windows
====
[source]
----
rule "Sound the alarm in case temperature rises above threshold"
when
    TemperatureThreshold( $max : max )
    Number( doubleValue > $max ) from accumulate(
        SensorReading( $temp : temperature ) over window:time( 10m ),
        average( $temp ) )
then
    // sound the alarm
end
----
====


The engine will automatically disregard any SensorReading older than 10 minutes and keep the calculated average consistent.

[IMPORTANT]
====
Please note that time based windows are considered when calculating the interval an event remains in the working memory before being expired, but an event falling off a sliding window does not mean by itself that the event will be discarded from the working memory, as there might be other rules that depend on that event.
The engine will discard events only when no other rules depend on that event and the expiration policy for that event type is fulfilled. 
====
