= Audit Log


In many cases it will be useful (if not necessary) to store information _about_ the execution of process instances, so that  this information can be used afterwards.
For example, sometimes we  want to verify which actions have been executed for a particular process  instance, or in general, we want to be able to monitor and analyze  the efficiency of a particular process.

However, storing history information in the runtime database  can result in the database rapidly increasing in size, not to mention  the fact that monitoring and analysis queries might influence the performance  of your runtime engine.
This is why process execution history information  can be stored separately.

This history log of execution information is created based on  events that the {PROCESS_ENGINE} generates during execution.
This is possible because the jBPM runtime engine provides a generic mechanism  to listen to events.
The necessary information can easily be extracted  from these events and then persisted to a database.
Filters can also be  used to limit the scope of the logged information.

== The jBPM Audit data model


The jbpm-audit module contains an event listener that stores process-related information in a database using JPA.
The data model itself contains three entities, one for process instance  information, one for node instance information, and one for (process)  variable instance information.

The `ProcessInstanceLog` table contains the basic log information about a process instance.

.ProcessInstanceLog
[cols="1,1,1", options="header"]
|===
| Field
| Description
| Nullable

|``id``
|The primary key and id of the log entity
|NOT NULL

|``duration``
|Actual duration of this process instance since its start date
|

|``end_date``
|When applicable, the end date of the process instance
|

|``externalId``
|Optional external identifier used to correlate to some elements - e.g. deployment id
|

|``user_identity``
|Optional identifier of the user who started the process instance
|

|``outcome``
|The outcome of the process instance, for instance error code in case
of process instance was finished with error event
|

|``parentProcessInstanceId``
|The process instance id of the parent process instance if any
|

|``processid``
|The id of the process
|

|``processinstanceid``
|The process instance id
|NOT NULL

|``processname``
|The name of the process
|

|``processversion``
|The version of the process
|

|``start_date``
|The start date of the process instance
|

|``status``
|The status of process instance that maps to process instance state
|
|===


The `NodeInstanceLog` table contains more information about which  nodes were actually executed inside each process instance.
Whenever a node instance  is entered from one of its incoming connections or is exited through one of its outgoing connections, that information is stored in this table.

.NodeInstanceLog
[cols="1,1,1", options="header"]
|===
| Field
| Description
| Nullable

|``id``
|The primary key and id of the log entity
|NOT NULL

|``connection``
|Actual identifier of the sequence flow that led to this node instance
|

|``log_date``
|The date of the event
|

|``externalId``
|Optional external identifier used to correlate to some elements - e.g. deployment id
|

|``nodeid``
|The node id of the corresponding node in the process definition
|

|``nodeinstanceid``
|The node instance id
|

|``nodename``
|The name of the node
|

|``nodetype``
|The type of the node
|

|``processid``
|The id of the process that the process instance is executing
|

|``processinstanceid``
|The process instance id
|NOT NULL

|``type``
|The type of the event (0 = enter, 1 = exit)
|NOT NULL

|``workItemId``
|Optional - only for certain node types - The identifier of work item
|
|===


The `VariableInstanceLog` table contains information about changes  in variable instances.
The default is to only generate log entries when (after) a variable changes.
It's also possible to log entries before the variable (value) changes.

.VariableInstanceLog
[cols="1,1,1", options="header"]
|===
| Field
| Description
| Nullable

|``id``
|The primary key and id of the log entity
|NOT NULL

|``externalId``
|Optional external identifier used to correlate to some elements - e.g. deployment id
|

|``log_date``
|The date of the event
|

|``processid``
|The id of the process that the process instance is executing
|

|``processinstanceid``
|The process instance id
|NOT NULL

|``oldvalue``
|The previous value of the variable at the time that the log is made
|

|``value``
|The value of the variable at the time that the log is made
|

|``variableid``
|The variable id in the process definition
|

|``variableinstanceid``
|The id of the variable instance
|
|===


The `AuditTaskImpl` table contains information about tasks that can be used for queries.

.AuditTaskImpl
[cols="1,1,1", options="header"]
|===
| Field
| Description
| Nullable

|``id``
|The primary key and id of the task log entity
|

|``activationTime``
|Time when this task was activated
|

|``actualOwner``
|Actual owner assigned to this task - only set when task is claimed
|

|``createdBy``
|User who created this task
|

|``createdOn``
|Date when task was created
|

|``deploymentId``
|Deployment id this task is part of
|

|``description``
|Description of the task
|

|``dueDate``
|Due date set on this task
|

|``name``
|Name of the task
|

|``parentId``
|Parent task id
|

|``priority``
|Priority of the task
|

|``processId``
|Process definition id that this task belongs to
|

|``processInstanceId``
|Process instance id that this task is associated with
|

|``processSessionId``
|KieSession id used to create this task
|

|``status``
|Current status of the task
|

|``taskId``
|Identifier of task
|

|``workItemId``
|Identifier of work item assigned on process side to this task id
|
|===


The `BAMTaskSummary` table that collects information about tasks that is used by BAM engine to build charts and dashboards.

.BAMTaskSummary
[cols="1,1,1", options="header"]
|===
| Field
| Description
| Nullable

|``id``
|The primary key and id of the log entity
|NOT NULL

|``createdDate``
|Date when task was created
|

|``duration``
|Duration since task was created
|

|``endDate``
|Date when task reached end state (complete, exit, fail, skip)
|

|``processinstanceid``
|The process instance id
|

|``startDate``
|Date when task was started
|

|``status``
|Current status of the task
|

|``taskId``
|Identifier of the task
|

|``taskName``
|Name of the task
|

|``userId``
|User id assigned to the task
|
|===


The `TaskVariableImpl` table contains information about task variable instances.

.TaskVariableImpl
[cols="1,1,1", options="header"]
|===
| Field
| Description
| Nullable

|``id``
|The primary key and id of the log entity
|NOT NULL

|``modificationDate``
|Date when the variable was modified last time
|

|``name``
|Name of the task
|

|``processid``
|The id of the process that the process instance is executing
|

|``processinstanceid``
|The process instance id
|

|``taskId``
|Identifier of the task
|

|``type``
|Type of the variable - either input or output of the task
|

|``value``
|Variable value
|
|===


The `TaskEvent` table contains information about changes  in task instances.
Operations such as claim, start, stop etc are stored here to provide a timeline view of events that happened to the given task.

.TaskEvent
[cols="1,1,1", options="header"]
|===
| Field
| Description
| Nullable

|``id``
|The primary key and id of the log entity
|NOT NULL

|``logTime``
|LDate when this event was saved
|

|``message``
|Log event message
|

|``processinstanceid``
|The process instance id
|

|``taskId``
|Identifier of the task
|

|``type``
|Type of the event - corresponds to life cycle phases of the task
|

|``userId``
|User id assigned to the task
|

|``workItemId``
|Identifier of work item that the task is assigned to
|===

== Storing Process Events in a Database


To log process history information in a database like this, you need to register the logger on your session like this:

[source,java]
----
KieSession ksession = ...;
ksession.addProcessEventListener(AuditLoggerFactory.newInstance(Type.JPA, ksession, null));

// invoke methods one your session here
----


To specify the database where the information should be stored, modify the file [path]_persistence.xml_
 file to include the audit log classes as well (ProcessInstanceLog, NodeInstanceLog and VariableInstanceLog), as shown below.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<persistence
  version="2.0"
  xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd
  http://java.sun.com/xml/ns/persistence/orm http://java.sun.com/xml/ns/persistence/orm_2_0.xsd"
  xmlns="http://java.sun.com/xml/ns/persistence"
  xmlns:orm="http://java.sun.com/xml/ns/persistence/orm"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <persistence-unit name="org.jbpm.persistence.jpa" transaction-type="JTA">
    <provider>org.hibernate.ejb.HibernatePersistence</provider>
    <jta-data-source>jdbc/jbpm-ds</jta-data-source>
    <mapping-file>META-INF/JBPMorm.xml</mapping-file>
    <class>org.drools.persistence.info.SessionInfo</class>
    <class>org.jbpm.persistence.processinstance.ProcessInstanceInfo</class>
    <class>org.drools.persistence.info.WorkItemInfo</class>
    <class>org.jbpm.persistence.correlation.CorrelationKeyInfo</class>
    <class>org.jbpm.persistence.correlation.CorrelationPropertyInfo</class>
    <class>org.jbpm.runtime.manager.impl.jpa.ContextMappingInfo</class>

    <class>org.jbpm.process.audit.ProcessInstanceLog</class>
    <class>org.jbpm.process.audit.NodeInstanceLog</class>
    <class>org.jbpm.process.audit.VariableInstanceLog</class>

    <properties>
      <property name="hibernate.dialect" value="org.hibernate.dialect.H2Dialect"/>
      <property name="hibernate.max_fetch_depth" value="3"/>
      <property name="hibernate.hbm2ddl.auto" value="update"/>
      <property name="hibernate.show_sql" value="true"/>
      <property name="hibernate.connection.release_mode" value="after_transaction"/>
      <property name="hibernate.transaction.jta.platform" value="org.hibernate.service.jta.platform.internal.JBossStandAloneJtaPlatform"/>
    </properties>
  </persistence-unit>
</persistence>
----


All this information can easily be queried and used in a lot of different use cases, ranging from creating a history log for one specific process instance to analyzing the performance of all instances of a specific process.

This audit log should only be considered a default implementation.
We don't know what information you need to store for analysis afterwards, and for performance reasons it is recommended to only store the relevant data.
Depending on your use cases, you might define your own data model for storing the information you need, and use the process event listeners to extract that information.

== Storing Process Events in a JMS queue for further processing


Process events are stored in the database synchronously and within the same transaction as actual process instance execution.
That obviously takes some time especially in highly loaded systems and might have some impact on the database when both history log and runtime data are kept in the same database.
To provide an alternative option for storing process events, a JMS based logger has been provided.
It can be configured to submit messages to JMS queue instead of directly persisting them in the database.
It can be configured to be transactional as well to avoid issues with inconsistent data in case of {PROCESS_ENGINE} transaction is rolled back. 

[source,java]
----

ConnectionFactory factory = ...;
Queue queue = ...;
StatefulKnowledgeSession ksession = ...;
Map<String, Object> jmsProps = new HashMap<String, Object>();
jmsProps.put("jbpm.audit.jms.transacted", true);
jmsProps.put("jbpm.audit.jms.connection.factory", factory);
jmsProps.put("jbpm.audit.jms.queue", queue);
ksession.addProcessEventListener(AuditLoggerFactory.newInstance(Type.JMS, ksession, jmsProps));

// invoke methods one your session here
----


This is just one of the possible ways to configure JMS audit logger, see javadocs for AuditLoggerFactory for more details.

== Variables auditing


Process and task variables are stored in audit tables by default although there are stored in simplest possible way - by creating string representation of the variable - variable.toString(). In many cases this is enough as even for custom classes used as variables users can implement custom toString() method that produces expected "view" of the variable. 

Though this might not cover all needs, especially when there is a need for efficient queries by variables (both task and process). Let's take as an example a Person object that has the following structure:


[source,java]
----
public class Person implements Serializable {

    private static final long serialVersionUID = -5172443495317321032L;
    private String name;
    private int age;   
    
    public Person(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public int getAge() {
        return age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return "Person [name=" + name + ", age=" + age + "]";
    }        
}
----

while at first look this seems to be sufficient as the toString() methods provide human readable 
format it does not make it easy to be searched by. As searching through strings like 
"Person [name="john", age="34"] to find people with age 34 would make database query very inefficient.

To solve the problem variable audit has been based on VariableIndexers that are responsible for 
extracting relevant parts of the variable that will be stored in audit log. 

[source,java]
----

/**
 * Variable indexer that allows to transform variable instance into other representation (usually string)
 * to be able to use it for queries.
 *
 * @param <V> type of the object that will represent indexed variable
 */
public interface VariableIndexer<V> {

    /**
     * Tests if given variable shall be indexed by this indexer
     * 
     * NOTE: only one indexer can be used for given variable
     * 
     * @param variable variable to be indexed
     * @return true if variable should be indexed with this indexer
     */
    boolean accept(Object variable);
    
    /**
     * Performs index/transform operation of the variable. Result of this operation can be
     * either single value or list of values to support complex type separation.
     * For example when variable is of type Person that has name, address phone indexer could 
     * build three entries out of it to represent individual fields:
     * person = person.name
     * address = person.address.street
     * phone = person.phone
     * that will allow more advanced queries to be used to find relevant entries.
     * @param name name of the variable
     * @param variable actual variable value 
     * @return
     */
    List<V> index(String name, Object variable);
}
----

By default (indexer that takes the `toString()`) will produce single audit entry for single 
variable, so it's one to one relationship. But that's not the only option: indexers (as can be 
seen in the interface) returns list of objects that are the outcome of single variable indexation.

To make our person queries more efficient we could build custom indexer that would take `Person`
instance and index it into separate audit entries one representing name and the other representing 
age. 

[source,java]
----

public class PersonTaskVariablesIndexer implements TaskVariableIndexer {

    @Override
    public boolean accept(Object variable) {
        if (variable instanceof Person) {
            return true;
        }
        return false;
    }

    @Override
    public List<TaskVariable> index(String name, Object variable) {
        
        Person person = (Person) variable;
        List<TaskVariable> indexed = new ArrayList<TaskVariable>();
        
        TaskVariableImpl personNameVar = new TaskVariableImpl();
        personNameVar.setName("person.name");
        personNameVar.setValue(person.getName());
        
        indexed.add(personNameVar);
        
        TaskVariableImpl personAgeVar = new TaskVariableImpl();
        personAgeVar.setName("person.age");
        personAgeVar.setValue(person.getAge()+"");
        
        indexed.add(personAgeVar);
        
        return indexed;
    }

}
----

That indexer will then be used to index Person class only and rest of variables will be indexed 
with default (toString()) indexer.  Now when we want to find process instances or tasks that have 
person with age 34 we simple refer to it as

* variable name: person.age
* variable value: 34

There is not even need to use like based queries so database can optimize the query and make it
efficient even with big set of data. 

*Building and registering custom indexers*

Indexers are supported for both process and task variables.
though they are supported by different interfaces as they do produce different type of objects representing audit view of the variable.
Following are the interfaces to be implemented to build custom indexers:

* process variables: `org.kie.internal.process.ProcessVariableIndexer`
* task variables: `org.kie.internal.task.api.TaskVariableIndexer`

Implementation is rather simple, just two methods to be implemented

* accept - indicates what types are handled by given indexer. Note that only one indexer can 
  index given variable, so the first that accepts it will perform the work
* index - actually does the work to index variables depending on custom requirements

Once the implementation is done, it should be packaged as jar file and following file needs to be included:

* for process variables: `META-INF/services/org.kie.internal.process.ProcessVariableIndexer` with 
  list of FQCN that represent the process variable indexers (single class name per line in that file)
* for task variables: `META-INF/services/org.kie.internal.task.api.TaskVariableIndexer` with list 
  of FQCN that represent the task variable indexers (single class name per line in that file)

Indexers are discovered by ServiceLoader mechanism and thus the META-INF/services files need.
All found indexers will be examined whenever process or task variable is about to be indexed.

Only the default (`toString()` based) indexer is not discovered but added explicitly as last 
indexer to allow custom ones to take the precedence over it.

