[id='auditlog-con_{context}']
= The persistent audit log

The {PROCESS_ENGINE} can store information about the execution of process instances, including the successive historical states of the instances.

This information can be useful in many cases. For example, you might want to verify which actions have been executed for a particular process instance or to monitor and analyze the efficiency of a particular process.

However, storing history information in the runtime database would result in the database rapidly increasing in size and would also affect the performance of the persistence layer. Therefore, history log information is stored separately.

The {PROCESS_ENGINE} creates a log based on  events that it generates during execution of processes. It uses the event listener mechanism to receive events and extract the necessary information, then persists this information to a database. The `jbpm-audit` module contains an event listener that stores process-related information in a database using JPA.

You can use filters to limit the scope of the logged information.