[id='ref-kogito-rn-new-features_{context}']
= New features in {PRODUCT} {PRODUCT_VERSION}

The following sections describe some of the new features or enhancements in {PRODUCT} {PRODUCT_VERSION}.

== {PRODUCT} runtimes

=== {PRODUCT} Management add-on new REST endpoint for retrieving all the nodes from a giving process.

Information about nodes from Business Process Model and Notation (BPMN) process models is now available using the following Management add-on REST endpoint:

`[GET] /management/processes/__PROCESS_ID__/nodes`

.Example REST endpoint
`\http://localhost:8080/management/processes/orders/nodes`

This information includes the node `id`, `name`, `type`, and `uniqueId`, as shown in the following REST response body:

.Example response (JSON)
[source,json]
----
[
  {
    "name": "End",
    "id": 1,
    "type": "EndNode",
    "uniqueId": "1"
  },
  {
    "name": "Start",
    "id": 8,
    "type": "StartNode",
    "uniqueId": "8"
  }
]
----
--

For more information about the {PRODUCT} Management Add On, see
ifdef::KOGITO[]
{URL_PROCESS_SERVICES}#con-bpmn-process-management-addon[_{PROCESS_SERVICES}_].
endif::[]
ifdef::KOGITO-COMM[]
xref:con-bpmn-process-management-addon[].
endif::[]

== {PRODUCT} Operator and CLI

=== Improved/new bla bla

Description

== {PRODUCT} supporting services

=== Improved/new bla bla

Description

== {PRODUCT} tooling

=== Improved/new bla bla

Description
