[id='wb-employee-rostering-solver-termination-configuration-proc']
= Configure Solver termination for the employee rostering project

You can configure the Solver to terminate after a specified amount of time. By default, the planning engine is given an unlimited time period to solve a problem instance.

The employee rostering sample project is set up to run for 30 seconds.

.Prerequisite
You have created all relevant assets for the employee rostering project and created the `EmployeeRosteringSolverConfig` solver configuration in {CENTRAL} as described in <<wb-employee-rostering-solver-configuration-proc>>.

.Procedure
. Open the `EmployeeRosteringSolverConfig` from the *Assets* perspective. This will open the *Solver configuration* designer.
. In the *Termination* section, click *Add* to create new termination element within the selected logical group.
. Select the `Time spent` termination type from the drop-down list. This is added as an input field in the termination configuration.
. Use the arrows next to the time elements to adjust the amount of time spent to 30 seconds.
. Click *Validate* in the upper-right corner to check the *Score Director Factory* configuration is correct. If validation fails, address any problems described in the error message, and try again to validate until the configuration passes.
. Click *Save* to save the Solver configuration.
