[id='interacting-with-processes-filtering-finding-tasks-proc']
= Filtering tasks using default or advanced filters

{Central} provides built-in filters to help you search tasks. You can filter tasks by attributes such as *Status*, *Filter By*, *Process Definition Id*, and *Created On*. It is also possible to create custom task filters using the *Advanced Filters* option. The newly created custom filter is added to the *Saved Filters* pane, which is accessible by clicking on the star icon on the left of the *Task Inbox* page.

[float]
== Filtering tasks using default filters

.Procedure
. Go to *Menu* -> *Track* -> *Task Inbox*.
. On the *Task Inbox* page, click the filter icon on the left of the page to expand the *Filters* pane.
+
This pane lists the following task attributes which you can use to filter tasks:
+
.. *Status*: Filter tasks based on their status.
.. *Filter By*: Filter tasks based on *Id*, *Task*, *Correlation Key*, *Actual Owner*, or *Process Instance Description* attribute.
... Select the required attribute.
... Enter the search query in the text field below.
... Click *Apply*.
.. *Process Definition Id*: Filter tasks based on process definition ids.
.. *Created On*: Filter tasks based on their creation date.

You can use the *Advanced Filters* option available at the bottom of the *Filters* pane to create custom filters in {CENTRAL}.

[float]
== Filtering tasks using advanced filters

.Procedure
. Go to *Menu* -> *Track* -> *Task Inbox*.
. On the *Task Inbox* page, click the filter icon on the left of the page to expand the *Filters* pane.
. In the *Filters* pane, click *Advanced Filters*.
. In the *New filtered list* window, enter the name and description, and click *Add New*.
. Select an attribute from the *Select column* drop-down list, for example, *Name*. The content of the drop-down changes to *Name != value1*.
. Click the drop-down again and choose the required logical query. For the *Name* attribute, choose *equals to*.
. Change the value of the text field to the name of the task you want to filter.
+
[NOTE]
====
The name must match the value defined in the business process of the project.
====
+
. Click *Ok* and the tasks are filtered according to the filter definition.
. Click *Save Filters*.
. In the *Save As* window, enter the name of the filter and click *Save*.
+
You can view the custom filter by clicking on the star icon on the left of the page to open the *Saved Filters* pane.
