// IMPORTANT: For 1.10 and later, save each version release notes as its own module file in the release-notes folder that this `ReleaseNotesKogito<version>.adoc` file is in, and then include each version release notes file in the chap-kogito-release-notes.adoc after Additional resources of {PRODUCT} deployment on {OPENSHIFT} section, in the following format:
//include::ReleaseNotesKogito.<version>/ReleaseNotesKogito.<version>.adoc[leveloffset=+1]

[id="ref-kogito-rn-new-features-1.23_{context}"]
= New features in {PRODUCT} 1.23

[role="_abstract"]
The following sections describe some of the new features or enhancements in {PRODUCT} 1.23.


== {PRODUCT} runtimes

=== {PRODUCT} runtime persistence allows to use Java serialization instead protobuf definitions

Starting from {PRODUCT} 1.23.0, runtime persistence will allow using Java objects serialization instead of custom marshallers and protobuf definitions.
To enable this feature, set `kogito.persistence.proto.marshaller=false` in your application.properties file.
This mode requires all the process variables using custom data types to implement `java.io.Serializable` and it is not compatible with data persisted using
protobuf definitions.

For more information, see {URL_PROCESS_SERVICES}#con-persistence_kogito-developing-process-services[Persistence in {PRODUCT} services].

////
== {PRODUCT} Operator and CLI

=== Improved/new bla bla

Description

== {PRODUCT} supporting services

=== Improved/new bla bla

Description

== {PRODUCT} tooling

=== Improved/new bla bla

Description
////
