
= Ejb
:imagesdir: ..

jBPM since version 6.2 provides out of the box integration layer with Enterprise Java Beans (EJB) for both local and remote interaction. 

Ejb services are brought by following modules:

* jbpm-services-ejb-api
+
API module that extends jbpm-services-api with EJB specific interfaces and objects

* jbpm-services-ejb-impl
+
EJB extension to core services

* jbpm-services-ejb-timer
+
jBPM Scheduler Service implementation backed by EJB Timer Service

* jbpm-services-ejb-client
+
EJB remote client implementation for remote interaction, provides JBoss AS support out of the box


EJB layer is based on jbpm services and thus provides almost same capabilities as the core module though there are some imiliations when it comes to remote interfaces.
Main difference is for the DeploymentService that has been limited for remote ejb service to following methods:

* deploy
* undeploy
* activate
* deactivate
* isDeployed

Main rationale behind is to avoid returning runtime objects such as RuntimeManager over EJB remote as it won't bring any value because it will be "disconnected" state.

All other services do provide exact same set of functionality as core module.

== Ejb services implementation

Ejb services as an extension of core services provide EJB based execution semantic and based on various EJB specific features.

* DeploymentServiceEJBImpl
+
is implemented as ejb singleton with container managed concurrency and lock type set to write

* DefinitionServiceEJBImpl 
+
is implemented as ejb singleton with container managed concurrency with overall lock type set to read, except buildProcessDefinition method that has lock type set to write

* ProcessServiceEJBImpl
+
is implemented as stateless session bean

* RuntimeDataServiceEJBImpl
+
is implemented as ejb singleton with mojority of methods with lock type read, except following that are with lock type write:

*** onDeploy
*** onUnDeploy
*** onActivte
*** onDeactivate

* UserTaskServiceEJBImpl
+
is implemented as stateless session bean


*Transactions*

Transaction is managed by EJB container thus there is no need to setup any sort of transaction manager or user transaction within application code.



*Identity provider*

Identity provider by default is backed by EJBContext and will rely on caller principal information for both name and roles.
When inspecting IdentityProvider interface there are two methods related to roles:

* getRoles
+
this method returns empty list due to the fact EJBContext does not provide options to fetch all roles for given user

* hasRole
+
this method will delegate to context's isCallerInRole method


This means that ejb must be secured according to JEE security practices to authentiate and authorize users so valid information will be available.
In case no authentication/authorization is configured for EJB services an anonymous user is always assumed.

In addition to that, EJB services acept CDI sytly injection for IdentityProvider in case another (non ejb) security model is used.
Simply create valid CDI bean that implements org.kie.internal.identity.IdentityProvider and make it available for injection with application and such implementation will take precedence over EJBContext based identity provider.



*Deployment synchronization*

Deployment synchronization is enabled by default and will attempt to synchronize any deployments every 3 seconds.
It is implemented as ejb singleton with container managed concurrency and lock type set to write.
Under the covers it utilizes EJB TimerService to schedule the synchronization jobs.



*EJB Scheduler Service*

jBPM uses scheduler service to deal with time based activities such as timer events, deadlines, etc.
When running in EJB environment and EJB Timer Service based scheduler will be used.
It will be automatically registered for all instances of RuntimeManager.
When it comes to cluster support application server specific configuration might be required.



*UserGroupCallback and UserInfo selection*

UserGroupCallback and UserInfo might differ for various applications and thus should be sort of pluggable.
With EJB we could not make it directly available for injections as they could not be injected with common type so there is another mechanism that allows to select one of provided out of the box implementation or to give a custom one.
This mechanism is based on ssytem properties:

* org.jbpm.ht.callback
+
specify what implementation of user group callback will be selected

*** mvel - default mostly used for testing
*** ldap - ldap backed implementation - requires additional configuration via jbpm.usergroup.callback.properties file
*** db - data base backed implementation - requires additional configuration via jbpm.usergroup.callback.properties file
*** jaas - delegates to container to fetch information about user data
*** props - simple property based callback - requires additional file that will keep all information (users and groups)
*** custom - custom implementation that requires to have additional system property set (FQCN of the implementation) - org.jbpm.ht.custom.callback

* org.jbpm.ht.userinfo
+
specify what implementation of UserInfo shall be used, one of:

*** ldap - backed by ldap - requires configuration via jbpm-user.info.properties file
*** db - backed by data base - requires configuration via jbpm-user.info.properties file
*** props - backed by simple property file
*** custom - custom implementation that requires to have additional system property set (FQCN of the implementation) - org.jbpm.ht.custom.userinfo


System properties can either be added to the startup configuration of the server (jvm) which is recommended or be set programmatically before services will be used - for example with custom @Startup bean that will configure it properly for selected callback and user info.

A example application that utilizes EJB services can be found https://github.com/jsvitak/jbpm-6-examples/tree/master/rewards-basic[here].

== Local interface

Local EJB services are brought via dedicated local interfaces that extends core services:

* org.jbpm.services.ejb.api.DefinitionServiceEJBLocal
* org.jbpm.services.ejb.api.DeploymentServiceEJBLocal
* org.jbpm.services.ejb.api.ProcessServiceEJBLocal
* org.jbpm.services.ejb.api.RuntimeDataServiceEJBLocal
* org.jbpm.services.ejb.api.UserTaskServiceEJBLocal

These interfaces should be used as injection points and shall be annotated with @EJB:

[source,java]
----
@EJB
private DefinitionServiceEJBLocal bpmn2Service;
	
@EJB
private DeploymentServiceEJBLocal deploymentService;
	
@EJB
private ProcessServiceEJBLocal processService;
	
@EJB
private RuntimeDataServiceEJBLocal runtimeDataService;
----

Once injected operations can be invoked on them as with core modules, there are no restrictions to their usage. 

== Remote interface

Remote EJB services are defined as dedicated remote interfaces that extends core services:

* org.jbpm.services.ejb.api.DefinitionServiceEJBRemote
* org.jbpm.services.ejb.api.DeploymentServiceEJBRemote
* org.jbpm.services.ejb.api.ProcessServiceEJBRemote
* org.jbpm.services.ejb.api.RuntimeDataServiceEJBRemote
* org.jbpm.services.ejb.api.UserTaskServiceEJBRemote

These can be used similar way as local interfaces except for handling custom types.
Custom types can be defined:

* globally
+
such types are available on application classpath - included in the enterprise application

* locally to the deployment unit
+
such types are declared as project (kjar) dependency and are resolved on deployment time
 Globally available types do not require any special handling as they will be available for EJB container when remote requests are handled - marshalling of incoming data.
Though local custom types won't be visible by default to EJB container as they are not on application classpath.
Thus special handling of such types is required.

EJB services provides easy yet rather powerful mechanism to resolve the issue - it comes with two additional types:

* org.jbpm.services.ejb.remote.api.RemoteObject
+
Serializable wrapper class for single value parameters

* org.jbpm.services.ejb.remote.api.RemoteMap
+
Dedicated java.util.Map implementation to simplify remote invocation of service methods that accept custom object input.
This map is backed by an internal map that holds already serialized content to avoid additional serialization on sending time.
That removes the burden of ensuring that container will know about all custom data model classes as part of global classpath. 
+
This implementation does not support all methods that are usually not used when sending data.
It shall be considered only as a wrapper only and not actual and complete implementation of a map.


These special objects will perform eager serialization to bytes using ObjectInputStream to remove the need of serialization from the EJB client/container.
Though it might be worse in case of performance it does overcome much more complecated handling of class loaders on EJB container side to allow use of custom types defined in the project.

Here is an example code needed to work with local types and remote EJB:

[source,java]
----
// start a process with custom types via remote EJB

Map<String, Object> parameters = new RemoteMap();
Person person = new org.jbpm.test.Person("john", 25, true);
parameters.put("person", person);

Long processInstanceId = processService.startProcess(deploymentUnit.getIdentifier(), "custom-data-project.work-on-custom-data", parameters);

// fetch task data and complete task with custom types via remote EJB
Map<String, Object> data = userTaskService.getTaskInputContentByTaskId(taskId);
        
Person fromTaskPerson = data.get("_person");
fromTaskPerson.setName("John Doe");
        
RemoteMap outcome = new RemoteMap();
outcome.put("person_", fromTaskPerson);
        
userTaskService.complete(taskId, "john", outcome);
----

Similar way RemoteObject can be used for example to send evnet to process instance:

[source,java]
----
// send event with custom type via remote EJB
Person person = new org.jbpm.test.Person("john", 25, true);

RemoteObject myObject = new RemoteObject(person);

processService.signalProcessInstance(processInstanceId, "MySignal", myObject);
----

These illustrates how to wrap custom data when interacting with remote EJB services.
Next section will introduce how to make a connection to a remote service vai client code.

=== Remote EJB client

Remote client support is provided by implemetation of ClientServiceFactory interface that is facede for application server specific code:

[source,java]
----
/**
 * Generic service factory used for remote look ups that are usually container specific.
 *
 */
public interface ClientServiceFactory {
	
	/**
	 * Returns unique name of given factory implementation
	 * @return
	 */
	String getName();

	/**
	 * Returns remote view of given service interface from selected application
	 * @param application application identifier on the container
	 * @param serviceInterface remote service interface to be found
	 * @return
	 * @throws NamingException
	 */
	<T> T getService(String application, Class<T> serviceInterface) throws NamingException;
}
----

Implementations can be dynamically registered using ServiceLoader mechanism and by default there is only one available for JBoss AS/EAP/Wildfly.
Each ClientServiceFactory must provide name which will be used to register it within the client registry so it can be then easily looked up.

Here is a code used to get hold of default JBoss based remote client:

[source,java]
----
// get hold of valid client service factory
ClientServiceFactory factory = ServiceFactoryProvider.getProvider("JBoss");

// application is the name known to application server aka module name
String application = "sample-war-ejb-app";

// get given service out of the factory
DeploymentServiceEJBRemote deploymentService = factory.getService(application, DeploymentServiceEJBRemote.class);
----

With service available all know to its interface methods are ready to be used.

When working with JBoss AS and remote client you can add following maven dependency to bring in all EJB client libraries:

[source,xml]
----
<dependency>
  <groupId>org.jboss.as</groupId>
  <artifactId>jboss-as-ejb-client-bom</artifactId>
  <version>7.2.0.Final</version> <!-- use valid version for the server you run on -->
  <optional>true</optional>
  <type>pom</type>
</dependency>
----
