[id='executing_processes']
= Executing the *Mortgage Process*
Now that you have deployed the project, you can execute the project's defined functionality. For this tutorial you will input data in to a mortgage application form acting as the mortgage broker. The MortgageApprovalProcess business process will run and will determine whether or not the applicant has offered an acceptable down payment based on the decision rules that you defined earlier. The business process will either end the rule testing or request that the applicant increase the down payment to proceed. If the application passes the business rule testing, the bank's approver will review the application and either approve or deny the loan.

.Prerequisites

 * The {KIE_SERVER} is deployed and connected to the {PRODUCT}
 * The *Mortgage Process* application has been deployed
 * The user or users working on the tasks must be members of the following groups:
 ** *approver* - For the *Qualify* task
 ** *broker* - For the *Correct Data* and *Increase Down Payment* tasks
 ** *manager* - For the *Final Approval* task

.Procedure

. Log in to {PRODUCT} and click *Menu* -> *Manage* -> *Process Definitions*.
. Click any where in the *MortgageApprovalProcess* row to view the process details.
. Click the *Diagram* tab to view the business process diagram in the editor.
. Click on the *X* in the upper-right corner to close the editor.
. Click *New Process Instance* to open the *Application* form and input the following values in to the form fields:

* *Down Payment*: `30000`
* *Years of amortization*: `10`
* *Name*: `Ivo`
* *Annual Income*: `60000`
* *SSN*: `123456789`
* *Age of property*: `8`
* *Address of property*: `Brno`
* *Locale*: `Rural`
* *Property Sale Price*: `50000`

. Click *Submit* to start a new process instance. After starting the process instance, the *Instance Details* view opens.
. Click on the *Diagram* tab to view the process flow within the process diagram. The state of the process will be highlighted as it moves through each task.
. Click *Menu* -> *Track* -> *Task Inbox*. This will take you to the *Qualify* form.
. As the approver, you will review the *Qaulify* task information, and if approved, select *Is mortgage application in limit?* and click *Complete*.
. In the *Task Inbox*, click any where in the *Final Approval* row to open the *Final Approval* task.
. Click *Claim* to claim responsibility for the task, then click *Complete* to finalize the loan approval process.

NOTE: The *Save* and *Release* buttons are only used to either pause the approval process and save the instance if you are waiting on a field value, or to release the task for another user to modify.
