[[_drools.releasenotesdrools.7.0.0]]
= What is New and Noteworthy in Drools 7.0.0

== Multithreaded rule engine

Historically Rete has always been a sequential algorithm and even if Phreak, its evolution introduced in Drools 6, allowed
some degree of parallelization, this possibility wasn't concretely leveraged yet. In Drools 7 is finally possible to make
the engine to evaluate more rules in parallel. This is achieved by partitioning the Rete/Phreak in independent partitions
and evaluating them in parallel.

This feature is off by default, but it's possible to create a parallel KieBase by enabling it via the ``KieBaseConfiguration`` as it follows:

[source]
----
KieServices ks = KieServices.Factory.get();
KieBaseConfiguration kieBaseConf = ks.newKieBaseConfiguration();
kieBaseConf.setOption(MultithreadEvaluationOption.YES);
KieBase kieBase = kieContainer.newKieBase(kieBaseConf);
----

or alternatively through the system property:

[source]
----
drools.multithreadEvaluation = true
----

[WARNING]
====
Rules using salience or agenda-group are currently not supported by the parallel engine. In case they are present inside
the rule base and compiler emits a warning and automatically switches back using the single threaded implementation.
====

== Type preserving accumulate functions

In Drools 6 when using the ``sum`` function inside an accumulate pattern the result was always a Double regardless of the
field type on which the sum was performed. This caused the following 3 problems:

* Loss of precision: the sum of a long `1881617265586265321L` will incorrectly return `1.88161726558626534E18`.
The BigDecimal sum of `0.09` and `0.01` will also be incorrect.

* Loss of performance: summing with a Double total is significantly slower than summing with a Long or an Integer.

* Leaked complexity: it enforced the user to pattern matching on Double, or more generically (suggested choice) on Number,
while it may be expected that the result of summing on a field of type Integer would be an Integer as well.

Conversely Drools 7 preserves the type of the expression on which the sum is executed, so it will be possible to directly
match on that type as in:

[source]
----
Long(...) from accumulate(..., sum($p.getLongWeight()))
----

== OOPath improvements

[WARNING]
====
This feature is experimental
====

OOPath has been introduced with Drools 6.3.0.
In Drools 7.0.0 the support for standard Java Collection has been enhanced, with a dedicated implementation for `List` and `Set`,
as specialized `ReactiveList` and `ReactiveSet`; a `ReactiveCollection` is also available.
This also includes out of the box reactive support when performing mutable operations through their `Iterator` and `ListIterator`.

.Example:
[source,java]
----
public class School extends AbstractReactiveObject {
    private String name;
    private final List<Child> children = new ReactiveList<Child>(); // <1>

    public void setName(String name) {
        this.name = name;
        notifyModification(); // <2>
    }
    
    public void addChild(Child child) {
        children.add(child); // <3>
        // no need to call notifyModification() here.
    }
----
<1> Using specialized `ReactiveList` for reactive support over standard Java `List`.
<2> Usually `notifyModification()` is required to be called when a field is changed for reactive support
<3> but in the case of `ReactiveList` this is handled automatically, like every other mutating operations performed over the field `children`.

TIP: As a best-practice, it is recommended to declare reactive collection fields `final` as per the example shown.

=== OOPath Maven plug-in

The Kie Maven plug-in offers a new goal `injectreactive` to instrument bytecode and automatically inject reactivity support for standard cases.

The `injectreactive` goal is disabled by default, and can be enabled via Maven plug-in configuration `instrument-enabled` settings.

.Example:
[source,xml]
----
<groupId>org.kie</groupId>
<artifactId>kie-maven-plugin</artifactId>
<extensions>true</extensions>
<configuration>
    <instrument-enabled>true</instrument-enabled> <!--1-->
</configuration>
----
<1> Enable the `injectreactive` goal.

The `injectreactive` goal will instrument bytecode pertaining to the Maven project build's output directory `${project.build.outputDirectory}`.

It is possible to limit the scope of the goal to a specific package or hierarchy of packages via Maven plug-in 
configuration `instrument-packages` settings list.
.Example:
[source,xml]
----
<groupId>org.kie</groupId>
<artifactId>kie-maven-plugin</artifactId>
<extensions>true</extensions>
<configuration>
    <instrument-enabled>true</instrument-enabled> 
    <instrument-packages>
        <instrumentPackage>to.instrument</instrumentPackage> <!--1-->
        <instrumentPackage>org.drools.compiler.xpath.tobeinstrumented.*</instrumentPackage> <!--2-->
    </instrument-packages>
</configuration>
----
<1> Limit scope of instrumentation specifically to `to.instrument` package only.
<2> Limit scope of instrumentation to `org.drools.compiler.xpath.tobeinstrumented` and its children packages.

The plug-in will instrument bytecode for every field assignment under the following standard cases: 

* a field assignment will also trigger `notifyModification()`
* wrap any field defined as List with a `ReactiveList`
* wrap any field defined as Set with a `ReactiveSet`
* wrap any field defined as Collection with a `ReactiveCollection`

NOTE: In order for a field of type List/Set to be wrapped correctly, the field member of the java class must be declared specifically using either 
`java.util.Collection`, `java.util.List` or `java.util.Set`
(declaring for instance a field as `java.util.ArrayList` will not be instrumented with the specialized reactive collections).

WARNING: It is not recommended to mix manual support for reactivity (implemented manually) and the bytecode instrumentation Maven plug-in; it is better envisaged to keep the two scopes distinct, for instance by making use of the plug-in configuration to instrument only specific packages as documented above.

The following section present detailed examples of the plug-in instrumentation.

==== Instrumentation of field assignments

A field assignment like in the following example:

.Original:
[source,java]
----
public class Toy {
    private String owner;
    ...
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
}
----

will be instrumented by intercepting the field assignment and triggering the `notifyModification()`:

.Result:
[source,java]
----
public class Toy implements ReactiveObject {
    private String owner;
    ...

    public void setOwner(final String owner) {
        this.$$_drools_write_owner(owner);
    }

    public void $$_drools_write_owner(final String owner) {
        this.owner = owner;
        ReactiveObjectUtil.notifyModification((ReactiveObject) this);
    }
}
----

Please notice this instrumentation applies only if the field is not a `Collection`.

In the case the field assignment is referring a `List` or a `Set`, the instrumentation will wrap the assignment with a `ReactiveList` or ``ReactiveSet` accordingly; for example:

.Original:
[source,java]
----
public class School {
    private final String name;
    private final List<Child> children = new ArrayList<Child>();
    ...

    public School(String name) {
        this.name = name;
    }

    public List<Child> getChildren() {
        return children;
    }
}
----

will be instrumented by intercepting and wrapping with `ReactiveList`:

.Result:
[source,java]
----
public class School implements ReactiveObject {
    private final String name;
    private final List<Child> children;

    public School(final String name) {
        this.$$_drools_write_children(new ArrayList());
        this.name = name;
    }

    public List<Child> getChildren() {
        return this.children;
    }
    
    public void $$_drools_write_children(final List list) {
        this.children = (List<Child>) new ReactiveList(list);
    } 
----

== Breaking changes

The KieSession option to control when timed rules have to be automatically executed has been renamed into `TimedRuleExecutionOption` fixing a typing mistake in its name which affected previous releases; the property has been aligned into `drools.timedRuleExecution`.

[cols="3", options="header"] 
.Name changes
|===
| 
|previous releases
|version `7.0.0.Final`

|KieSession option
|`TimedRuleExectionOption`
|`TimedRuleExecutionOption`

|property
|`drools.timedRuleExection`
|`drools.timedRuleExecution`