[id="con-apache-maven-plug-ins-and-quarkus_{context}"]

= Apache Maven and {QUARKUS}

Apache Maven is a distributed build automation tool used in Java application development to create, manage, and build software projects. Maven uses standard configuration files called Project Object Model (POM) files to define projects and manage the build process. POM files describe the module and component dependencies, build order, and targets for the resulting project packaging and output using an XML file. This ensures that the project is built in a correct and uniform manner.

.Maven repositories
A Maven repository stores Java libraries, plug-ins, and other build artifacts. The default public repository is the Maven 2 Central Repository, but repositories can be private and internal within a company to share common artifacts among development teams. Repositories are also available from third parties.

You can use the online Maven repository with your Quarkus projects or you can download the {QUARKUS} Maven repository.

.Maven plug-ins
Maven plug-ins are defined parts of a POM file that achieve one or more goals. Quarkus applications use the following Maven plug-ins:

* Quarkus Maven plug-in (`quarkus-maven-plugin`): Enables Maven to create Quarkus projects, supports the generation of uber-JAR files, and provides a development mode.

* Maven Surefire plug-in (`maven-surefire-plugin`): Used during the test phase of the build lifecycle to execute unit tests on your application. The plug-in generates text and XML files that contain the test reports.
