[id="code-quarkus-redhat-com-proc_{context}"]
= Creating a {QUARKUS} Maven project using code.quarkus.redhat.com

[role="_abstract"]
You can use the `code.quarkus.redhat.com` website to generate a {PLANNER} Quarkus Maven project and automatically add and configure the extensions that you want to use in your application. In addition, `code.quarkus.redhat.com` automatically manages the configuration parameters required to compile your project into a native executable.

This section walks you through the process of generating an OptaPlanner Maven project and includes the following topics:

 * Specifying basic details about your application.
 * Choosing the extensions that you want to include in your project.
 * Generating a downloadable archive with your project files.
 * Using the custom commands for compiling and starting your application.

.Prerequisites
* You have a web browser.

.Procedure

. Open `https://code.quarkus.redhat.com` in your web browser:
. Specify details about your project:
. Enter a group name for your project.
The format of the name follows the Java package naming convention, for example,
`com.example`.
. Enter a name that you want to use for Maven artifacts generated from your project, for example `code-with-quarkus`.
// Perhaps quarkus-school-time-table?
. Select *Build Tool* > *Maven* to specify that you want to create a Maven project. The build tool that you choose determines the items:

*** The directory structure of your generated project
*** The format of configuration files used in your generated project
*** The custom build script and command for compiling and starting your application that `code.quarkus.redhat.com` displays for you after you generate your project
+
[NOTE]
====
Red Hat provides support for using `code.quarkus.redhat.com` to create OptaPlanner Maven projects only. Generating Gradle projects is not supported by Red Hat.
====
. Enter a version to be used in artifacts generated from your project. The default value of this field is `1.0.0-SNAPSHOT`. Using link:https://semver.org/[semantic versioning] is recommended, but you can use a different type of versioning if you prefer.
. Enter the package name of artifacts that the build tool generates when you package your project.
+
According to the Java package naming conventions the package name should match the group name that you use for your project, but you can specify a different name.
+
[NOTE]
====
The `code.quarkus.redhat.com` website automatically uses the latest release of OptaPlanner. You can manually change the BOM version in the `pom.xml` file after you generate your project.
====

. Select the following extensions to include as dependencies:
+
* RESTEasy JAX-RS (quarkus-resteasy)
* RESTEasy Jackson (quarkus-resteasy-jackson)
* OptaPlanner AI constraint solver(optaplanner-quarkus)
* OptaPlanner Jackson (optaplanner-quarkus-jackson)
+
Red Hat provides different levels of support for individual extensions on the list, which are indicated by labels next to the name of each extension:

** _SUPPORTED_ extensions are fully supported by Red Hat for use in enterprise applications in production environments.
** _TECH-PREVIEW_ extensions are subject to limited support by Red Hat in production environments under the link:https://access.redhat.com/support/offerings/techpreview[Technology Preview Features Support Scope].
** _DEV-SUPPORT_ extensions are not supported by Red Hat for use in production environments, but the core functionalities that they provide are supported by Red Hat developers for use in developing new applications.
** _DEPRECATED_ extension are planned to be replaced with a newer technology or implementation that provides the same functionality.
+
Unlabeled extensions are not supported by Red Hat for use in production environments.

. Select _Generate your application_ to confirm your choices and display the overlay screen with the download link for the archive that contains your generated project. The overlay screen also shows the custom command that you can use to compile and start your application.

. Select *Download the ZIP* to save the archive with the generated project files to your system.

. Extract the contents of the archive.

. Navigate to the directory that contains your extracted project files:
+
[source,bash,options="nowrap",subs="+quotes,attributes+"]
----
cd <directory_name>
----

. Compile and start your application in development mode:
+
[source,bash,options="nowrap",subs="+quotes,attributes+"]
----
./mvnw compile quarkus:dev
----
