[id='examples-download-proc']
= Downloading {PLANNER} examples

You can download the {PLANNER} examples as a part of the {PRODUCT} add-ons package available on the Red Hat Customer Portal.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* Product: {PRODUCT_SHORT}
* Version: {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION} Add Ons*.
. Extract the `{PRODUCT_FILE}-add-ons.zip` file. The extracted `add-ons` folder contains the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_PLANNING_ENGINE}.zip` file.
. Extract the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_PLANNING_ENGINE}.zip` file.

.Result
The extracted `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_PLANNING_ENGINE}` directory contains example source code under the following subdirectories:

* `examples/sources/src/main/java/org/optaplanner/examples`
* `examples/sources/src/main/resources/org/optaplanner/examples`
