[id="proc-online-maven_{context}"]

= Configuring the Maven settings.xml file for the online repository

You can use the online Maven repository with your Maven project by configuring your user `settings.xml` file. This is the recommended approach. Maven settings used with a repository manager or repository on a shared server provide better control and manageability of projects.

NOTE: When you configure the repository by modifying the Maven `settings.xml` file, the changes apply to all of your Maven projects.

.Procedure

. Open the Maven `~/.m2/settings.xml` file in a text editor or integrated development environment (IDE).
+
NOTE: If there is not a `settings.xml` file in the `~/.m2/` directory, copy the `settings.xml` file from the `$MAVEN_HOME/.m2/conf/` directory into the `~/.m2/` directory.

. Add the following lines to the `<profiles>` element of the `settings.xml` file:
+
[source,xml,subs=attributes+]
----
<!-- Configure the Maven repository -->
<profile>
  <id>red-hat-enterprise-maven-repository</id>
  <repositories>
    <repository>
      <id>red-hat-enterprise-maven-repository</id>
      <url>https://maven.repository.redhat.com/ga/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>red-hat-enterprise-maven-repository</id>
      <url>https://maven.repository.redhat.com/ga/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>
</profile>
----
+
. Add the following lines to the `<activeProfiles>` element of the `settings.xml` file and save the file.

+
[source,xml]
----
<activeProfile>red-hat-enterprise-maven-repository</activeProfile>
----
