[id='optimizer-running-the-examples-in-an-IDE-proc']
= Running the {PLANNER} examples in an IDE (IntelliJ, Eclipse, or Netbeans)

If you use an integrated development environment (IDE), such as IntelliJ, Eclipse, or Netbeans, you can run your downloaded {PLANNER_SHORT} examples within your development environment.

.Prerequisites
* You have downloaded and extracted the {PLANNER_SHORT} examples as described in <<examples-download-proc>>.

.Procedure
. Open the {PLANNER_SHORT} examples as a new project:
.. For IntelliJ or Netbeans, open `examples/sources/pom.xml` as the new project. The Maven integration guides you through the rest of the installation. Skip the rest of the steps in this procedure.
.. For Eclipse, open a new project for the `/examples/binaries` directory, located under the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_PLANNING_ENGINE}` directory.
//Please confirm.
. Add all the JAR files that are in the `binaries` directory to the classpath, except for the `examples/binaries/optaplanner-examples-{MAVEN_ARTIFACT_VERSION}.jar` file.
. Add the Java source directory `src/main/java` and the Java resources directory `src/main/resources`, located under the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_PLANNING_ENGINE}/examples/sources/` directory.
. Create a run configuration:
+
* Main class: `org.optaplanner.examples.app.OptaPlannerExamplesApp`
* VM parameters (optional): `-Xmx512M -server -Dorg.optaplanner.examples.dataDir=examples/sources/data`
* Working directory: `examples/sources`
. Run the run configuration.
