[id='optimizer-engine-installation-proc']
= Installing the {PLANNING_ENGINE} in your application

{PLANNER} can be installed using Maven or other applications, such as Gradle, Ivy, or Buildr.

.Prerequisites

* The {PRODUCT} has been downloaded and installed from the https://access.redhat.com[Red Hat Customer Portal]. For installation options, see {URL_INSTALLING_AND_CONFIGURING}#assembly-planning[_{PLANNING_INSTALL}_].

.Procedure
. Get the {PLANNER} `optaplanner-core` JARs at the https://maven.repository.redhat.com/ga/optaplanner[Red Hat JBoss Maven Repository].
. Identify the latest version by checking the https://maven.repository.redhat.com/ga/org/optaplanner[Red Hat JBoss Maven Repository].
. Add a dependency to `optaplanner-core` in your project's `pom.xml`:
+

[source,xml,subs="attributes+"]
----

  <dependency>
      <groupId>org.optaplanner</groupId>
      <artifactId>optaplanner-core</artifactId>
      <version>{MAVEN_ARTIFACT_VERSION}</version>
  </dependency>
----
. Optional: Add any other {PLANNING_ENGINE} modules that you require, such as the `optaplanner-persistence-jpa` or `optaplanner-persistence-xstream` integration modules. For more information about how to configure {PLANNER} for use with other Java technologies, see the http://docs.optaplanner.org/latest/optaplanner-docs/html_single/#integration[Optaplanner] documentation.

[NOTE]
====
The `optaplanner-benchmark` module is included as part of the {PLANNING_ENGINE}, however, it is recommended to be used as a separate module, as demonstrated in the this https://github.com/kiegroup/optashift-employee-rostering/tree/master/optashift-employee-rostering-benchmark[Employee Rostering module]. This is to avoid leaking the `optaplanner-benchmark` into the `.war` file.
====

Alternatively, if you are using Ant (without Ivy) you can install the {PLANNING_ENGINE} by copying all of the JARs from the downloaded ZIP's `binaries` directory. Manually verify that your classpath does not contain duplicate JARs.

[NOTE]
====
The downloaded .zip file `binaries` directory contains far more JARs then `optaplanner-core` actually uses.
It also contains the JARs used by other modules, such as `optaplanner-benchmark`.

Check the Maven repository `pom.xml` files to determine the minimal dependency set for a specific version of a specific module.
====
