[id='proc-quarkus-junit-testing_{context}']


= Testing your Quarkus application with JUnit

After you compile your school timetable project, test your application with the JUnit 5 framework to ensure that it runs as expected. There are two test dependencies in the {ProductName} project generated `pom.xml` file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-junit5</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <scope>test</scope>
</dependency>
----

The `quarkus-junit5` dependency is required for testing because it provides the `@QuarkusTest` annotation that controls the JUnit 5 testing framework. The `rest-assured` dependency is not required but because it provides a convenient way to test HTTP endpoints, it is integrated as well. It automatically sets the correct URL so no configuration is required.

NOTE: These tests use the REST-assured framework, but you can use a different library if you prefer.


.Prerequisites
* You have compiled the school timetable project.

.Procedure
. Set the version of the Surefire Maven plug-in:
+
[source,xml,subs=attributes+]
----
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>${surefire-plugin.version}</version>
    <configuration>
       <systemProperties>
         <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
       </systemProperties>
    </configuration>
</plugin>
----
+
The default Surefire Maven plugin version does not support JUnit 5.
. Set the `java.util.logging` system property to make sure tests use the correct log manager.


. Edit the `src/test/java/org/acme/quickstart/GreetingResourceTest.java` file to match the following content:
+
[source,java]
----
package org.acme.quickstart;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import java.util.UUID;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
public class GreetingResourceTest {

    @Test
    public void testHelloEndpoint() {
        given()
          .when().get("/hello")
          .then()
             .statusCode(200)
             .body(is("hello"));
    }

    @Test
    public void testGreetingEndpoint() {
        String uuid = UUID.randomUUID().toString();
        given()
          .pathParam("name", uuid)
          .when().get("/hello/greeting/{name}")
          .then()
            .statusCode(200)
            .body(is("hello " + uuid));
    }

}
----
+
NOTE: By using the `QuarkusTest` runner, you instruct JUnit to start the application before starting the tests.

. To run these tests from Maven, enter the following command:
+
[source,shell,subs=attributes+]
----
./mvnw test
----
+
NOTE: You can also run the test from your IDE. If you do this, make sure to stop the application first.
+
By default, tests run on port `8081` so they do not conflict with the running application. In {ProductName}, the `RestAssured` dependency is configured to use this port. If you want to use a different client, use the `@TestHTTPResource` annotation to directly inject the URL of the tested application into a field on the `Test` class. This field can be of the type
`string`, `URL` or `URI`. You can also provide the test path in this annotation. For example, to test
a servlet mapped to `/myservlet`, add the following lines to your test:
+
[source,java]
----
@TestHTTPResource("/myservlet")
URL testUrl;
----
. If necessary, specify the test port in the `quarkus.http.test-port` configuration property.

NOTE: {ProductName} also creates a system
property called `test.url` that is set to the base test URL for situations where you cannot use injection.
