[id='proc-quarkus-creating-proj_{context}']


= Creating a {QUARKUS} Maven project using the Maven plug-in

You can get up and running with a {PLANNER} and Quarkus application using Apache Maven and the Quarkus Maven plug-in.

////
NOTE: If you prefer, you can create a Quakus OptaPlanner project as described in xref:optaplanner-quarkus-con_getting-started-optaplanner[].
////

.Procedure

. In a command terminal, enter the following command to verify that Maven is using JDK {OPTAPLANNER_JDK_VERSION} and that the Maven version is  {OPTAPLANNER_MAVEN_VERSION} or higher:
+
[source]
----
mvn --version
----

. If the preceding command does not return JDK {OPTAPLANNER_JDK_VERSION}, add the path to JDK {OPTAPLANNER_JDK_VERSION} to the PATH environment variable and enter the preceding command again.

. To generate the project, enter one of the following commands:
+
NOTE: Apple macOS and Microsoft Windows are not supported production environments.
+
* If you are using Linux or Apple macOS, enter the following command:
+
[source,shell,subs=attributes+]
----
mvn io.quarkus:quarkus-maven-plugin:{QUARKUS_BOM}:create \
    -DprojectGroupId=com.example \
    -DprojectArtifactId=optaplanner-quickstart  \
    -Dextensions="resteasy,resteasy-jackson,optaplanner-quarkus,optaplanner-quarkus-jackson" \
    -DplatformGroupId=com.redhat.quarkus \
    -DplatformVersion={QUARKUS_BOM} \
    -DnoExamples
----
+
This command create the following elements in the `./optaplanner-quickstart` directory:
+
** The Maven structure
** Example `Dockerfile` file in `src/main/docker`
** The application configuration file
+
.Properties used in the mvn `io.quarkus:quarkus-maven-plugin:{QUARKUS_BOM}:create` command
[cols="30%,70%", options="header"]
|===
h| Property
h| Description

| `projectGroupId`
| The group ID of the project.

| `projectArtifactId`
| The artifact ID of the project.

| `extensions`
| A comma-separated list of Quarkus extensions to use with this project. For a full list of Quarkus extensions, enter `mvn quarkus:list-extensions` on the command line.

| `platformGroupId`
| The Group ID of the target platform.

| `platformVersion`
| The version of the platform that you want the project to use.

| `noExamples`
| Creates a project with the project structure but without tests or classes.

|===
+
The values of the `projectGroupID` and the `projectArtifactID` properties are used to generate the project version. The default project version is `1.0.0-SNAPSHOT`. The values of the `platformGroupId` and `platformVersion` properties are used by `quarkus-universe-bom` to manage project dependencies.

. Review the `quarkus-resteasy` dependency in the `pom.xml` file. This dependency enables you to develop REST applications:
+
[source,xml]
----
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-resteasy</artifactId>
    </dependency>
----
