[id='spring-boot-ref-download-proc_{context}']

= Downloading and building the Spring Boot school timetable quick start

If you want to see a completed example of the school timetable project for {PLANNER} with Spring Boot product, download the starter application from the Red Hat Customer Portal.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* *Product:* {PRODUCT_PAM_SHORT}
* *Version:* {PRODUCT_VERSION_LONG}
. Download *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Kogito and OptaPlanner 8 Decision Services Quickstarts* (`{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts.zip`).
. Extract the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts.zip` file.
. Download the *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Kogito and OptaPlanner 8 Decision Services Maven Repositroy* (`{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-maven-repository.zip`).
. Extract the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-maven-repository.zip` file.
. Copy the contents of the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-maven-repository/maven-repository` subdirectory into the `~/.m2/repository` directory.
. Navigate to the `optaplanner-quickstarts-{OPTAPLANNER_BOM_VERSION}/technology/java-spring-boot` directory.
. Enter the following command to build the Spring Boot school timetabling project:
+
[source]
----
mvn clean install -DskipTests
----

. To build the Spring Boot school timetabling project, enter the following command:
+
[source]
----
mvn spring-boot:run -DskipTests
----

. To view the project, enter the following URL in a web browser:
+
[source]
----
http://localhost:8080/
----
