[id='spring-boot-ref-download-proc_{context}']

= Downloading and building the Spring Boot school timetable quick start

If you want to see a completed example of the school timetable project for {PLANNER} with Spring Boot product, download the starter application from the Red Hat Customer Portal.

.Procedure
. Navigate to the {PRODUCT_DOWNLOAD_LINK}[IBM Business Automation Manager Open Editions {ENTERPRISE_VERSION} downloads] page  and follow the instructions to download *{PRODUCT} {PRODUCT_VERSION} - Kogito and OptaPlanner 8 Decision Services Quickstarts* (`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-ORB.Zip`).
. Extract the `{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-ORB.Zip` file.
. Download the *{PRODUCT} {PRODUCT_VERSION} - Kogito and OptaPlanner 8 Decision Services Maven Repositroy* (`{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-maven-repository.zip`).
. Extract the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-maven-repository.zip` file.
. Copy the contents of the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-maven-repository/maven-repository` subdirectory into the `~/.m2/repository` directory.
. Navigate to the `optaplanner-quickstarts-{OPTAPLANNER_BOM_VERSION}/technology/java-spring-boot` directory.
. Enter the following command to build the Spring Boot school timetabling project:
+
[source]
----
mvn clean install -DskipTests
----

. To build the Spring Boot school timetabling project, enter the following command:
+
[source]
----
mvn spring-boot:run -DskipTests
----

. To view the project, enter the following URL in a web browser:
+
[source]
----
http://localhost:8080/
----
