[id='spring-boot-ref-download-proc_{context}']

= Downloading and building the Spring Boot school timetable quick start

If you want to see a completed example of the school timetable project for {PLANNER} with Spring Boot product, download the starter application from the Red Hat Customer Portal.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* Product: {PRODUCT}
* Version: {PRODUCT_VERSION}
. Download *Decision Services Quick Starts* (`kogito-1.5.0-decision-services-quickstarts.zip`).
. Download *{PRODUCT} {PRODUCT_VERSION} Maven Repository* (`kogito-1.5.0-maven-repository.zip`).
. Extract the `kogito-1.5.0-maven-repository.zip` file.
. Copy the contents of the `kogito-1.5.0.GA-maven-repository/maven-repository` subdirectory into the `~/.m2/repository` directory.
. Extract the `kogito-1.5.0-decision-services-quickstarts.zip` file. This archive contains the `kogito-examples-1.5.0.redhat-00001` directory.
. Navigate to the `optaplanner-quickstarts-8.5.0.Final-redhat-00001/spring-boot-school-timetabling` directory.
. Enter the following command to build the Spring Boot school timetabling project:
+
[source]
----
mvn clean install -DskipTests
----

. To build the Spring Boot school timetabling project, enter the following command:
+
[source]
----
mvn spring-boot:run -DskipTests
----

. To view the project, enter the following URL in a web browser:
+
[source]
----
http://localhost:8080/
----
