[id="vaccination-scheduler-package-proc_{context}"]

= Package and run the OptaPlanner vaccination appointment scheduler

When you have completed development work on the OptaPlanner vaccination appointment scheduler in `quarkus:dev` mode, run the application as a conventional jar file.

.Prerequisites
* You have downloaded the OptaPlanner vaccination appointment scheduler quick start. For more information, see xref:vaccination-scheduler-download-proc_{context}[].

.Procedure
. Navigate to the `/use-cases/vaccination-scheduling` directory.

. To compile the OptaPlanner vaccination appointment scheduler, enter the following command:
+
[source, shell]
----
$ mvn package
----

. To run the compiled OptaPlanner vaccination appointment scheduler, enter the following command:
+
[source, shell]
----
$ java -jar ./target/*-runner.jar
----
+
[NOTE]
====
To run the application on port 8081, add `-Dquarkus.http.port=8081` to the preceding command.
====

. To start the OptaPlanner vaccination appointment scheduler, enter the following URL in a web browser.
+
[source]
----
http://localhost:8080/
----
