[id="vaccination-scheduler-download-proc_{context}"]

= Downloading and running the OptaPlanner vaccination appointment scheduler

Download the OptaPlanner vaccination appointment scheduler quick start archive, start it in Quarkus development mode, and view the application in a browser. Quarkus development mode enables you to make changes and update your application while it is running.


.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

** *Product:* {PRODUCT_PAM_SHORT}
** *Version:* {PRODUCT_VERSION_LONG}
. Download *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Kogito and OptaPlanner 8 Decision Services Quickstarts* (`{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts.zip`).
. Extract the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts.zip` file.
. Navigate to the `optaplanner-quickstarts-{OPTAPLANNER_BOM_VERSION}` directory.
. Navigate to the `optaplanner-quickstarts-{OPTAPLANNER_BOM_VERSION}/use-cases/vaccination-scheduling` directory.

. Enter the following command to start the OptaPlanner vaccination appointment scheduler in development mode:
+
[source, shell]
----
$ mvn quarkus:dev
----

. To view the OptaPlanner vaccination appointment scheduler, enter the following URL in a web browser.
+
[source]
----
http://localhost:8080/
----

. To run the OptaPlanner vaccination appointment scheduler, click *Solve*.
. Make changes to the source code then press the F5 key to refresh your browser. Notice that the changes that you made are now available.
