[id='proc-management-console-security_{context}']
= Enabling {PRODUCT} Management Console security with OpenID Connect

For Quarkus-based {PRODUCT} services, you can use the https://quarkus.io/guides/security-openid-connect[Quarkus OpenID Connect adapter] with the {PRODUCT} Management Console to enable the console to interact with the {PRODUCT} Data Index Service using bearer token authorization. These tokens are issued by OpenID Connect and OAuth 2.0 compliant authorization servers such as https://www.keycloak.org/about.html[Keycloak].

IMPORTANT: This procedure applies only when you are using a locally cloned copy of the https://github.com/kiegroup/kogito-apps/tree/master/management-console[{PRODUCT} Management Console] repository in GitHub.

.Prerequisites
* You have cloned the https://github.com/kiegroup/kogito-apps/tree/master/management-console[{PRODUCT} Management Console] repository from GitHub.

.Procedure
In a command terminal, navigate to the local clone of the {PRODUCT} Management Console repository and enter the following command to run the application with security enabled:

.Run the Management Console with security enabled
[source]
----
mvn clean compile quarkus:dev -Dkogito.auth.enabled=true
----

IMPORTANT: Ensure that the service is not started at the same port as the security server. You can change the port by adding `-Dquarkus.http.port=__PORT_NUMBER__` to the start-up properties.

If the `kogito.auth.enabled=true` setting is not added, the OpenID Connect extension is disabled.

The `src/main/resources/application.properties` file of the Management Console project contains the following default security properties and values:

.Default security properties for the Management Console
[source]
----
kogito.auth.enabled=false
kogito.auth.keycloak.url=http://localhost:8280
kogito.auth.keycloak.realm=kogito
kogito.auth.keycloak.client.id=kogito-console-quarkus
----

If needed, you can replace any property definitions with those of your specific environment, especially the following properties:

* `kogito.auth.keycloak.url`: The base URL of the OpenID Connect (OIDC) server, such as `https://localhost:8280`. All other OIDC server page and service URLs are derived from this URL. If you work with Keycloak OIDC server, ensure that the base URL is in the following format: `https://__HOST__:__PORT__`.
* `kogito.auth.keycloak.realm`: The realm identifier.
* `kogito.auth.keycloak.client.id`: The client ID of the application. Each application has a client ID that is used to identify the application.
