ifdef::context[:parent-context: {context}]

[id='assembly-patching-and-upgrading']
= Patching and upgrading {PRODUCT} {PRODUCT_VERSION}

// Context attribute is assembly specific and enables module reuse between assemblies.
:context: patching-upgrading

// Purpose statement for the assembly
As an {PRODUCT} user, you can apply updates to {PRODUCT} as they become available on the IBM Support pageto keep your {PRODUCT} distribution current with the latest enhancements and fixes. Red Hat provides update tools and product notifications for new product releases so you can more readily apply helpful updates to {PRODUCT} and {KIE_SERVER}.

.Prerequisites
* {PRODUCT} {PRODUCT_VERSION} is installed. For installation options, see {URL_INSTALLING_AND_CONFIGURING}#assembly-planning[_{PLANNING_INSTALL}_].
+
[NOTE]
====
If you are using Red Hat Process Automation Manager 7.10 and you want to upgrade to {PRODUCT} {PRODUCT_VERSION}, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.10/html-single/installing_and_configuring_red_hat_process_automation_manager/index#assembly-patching-and-upgrading[_Patching and upgrading Red Hat Process Automation Manager 7.10_].

If you are using Red Hat Process Automation Manager 7.11 or higher, follow the instructions in https://www.ibm.com/support/pages/node/6830111[_Migrating from Red Hat Process Automation Manager and Decision Manager 7.x to IBM Business Automation Manager Open Editions 8.0_].
====

include::{enterprise-dir}/installation/product-versioning-con.adoc[leveloffset=+1]

//include::{enterprise-dir}/installation/patches-notifications-proc.adoc[leveloffset=+1]

include::{enterprise-dir}/installation/patches-applying-proc.adoc[leveloffset=+1]

// include::{shared-dir}/KIE/BuildDeployUtilizeAndRun/executable-model-upgrading-proc.adoc[leveloffset=+1]


// Consolidated with patch tool in 7.1, but may change.
//include::{enterprise-dir}/installation/upgrading-minor-release-proc.adoc[leveloffset=+1]

== Additional resources
* {URL_INSTALLING_AND_CONFIGURING}#assembly-planning[_{PLANNING_INSTALL}_]
* https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.10/html-single/installing_and_configuring_red_hat_process_automation_manager/index#assembly-patching-and-upgrading[_Patching and upgrading Red Hat Process Automation Manager 7.10_]
* {URL_RELEASE_NOTES}[_{RELEASE_NOTES}_]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
