[id='assembly-process-engine']
= {PROCESS_ENGINE_CAP} in {PRODUCT}
ifdef::context[:parent-context: {context}]
// Context attribute is assembly specific and enables module reuse between assemblies.
:context: process-engine

// Purpose statement for the assembly
As a business process analyst or developer, your understanding of the {PROCESS_ENGINE} in {PRODUCT} can help you design more effective business assets and a more scalable process management architecture. The {DECISION_ENGINE} is the {PRODUCT} component that stores, processes, and evaluates data to execute business rules and to reach the decisions that you define. This document describes concepts and functions of the {PROCESS_ENGINE} to consider as you create your business process management system and process services in {PRODUCT}.

// Modules - concepts, procedures, refs, etc.
include::{jbpm-dir}/Overview/processengine-overview-con.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
