[id='assembly-optimizer-migration-8_{context}']
= Upgrading your {PLANNER} projects to OptaPlanner 8

If you have OptaPlanner projects that you created with the OptaPlanner 7 or earlier pubic API and you want to upgrade your project code to OptaPlanner 8, review the information in this guide. This guide also includes changes to implementation classes which are outside of the pubic API.

The OptaPlanner public API is a subset of the OptaPlanner source code that enables you to interact with OptaPlanner through Java code. So that you can upgrade to higher OptaPlanner versions within the same major release, OptaPlanner follows https://semver.org/[semantic versioning]. This means that you can upgrade from OptaPlanner 7.44 to OptaPlanner 7.48 for example without breaking your code that uses the OptaPlanner public API. The OptaPlanner public API classes are compatible within the versions of a major OptaPlanner release. However, when Red Hat releases a new major release, disrupting changes are sometimes introduced to the public API.

OptaPlanner 8 is a new major release and some of the changes to the public API are not are not compatible with earlier versions of OptaPlanner. OptaPlanner 8 will be the foundation for the 8.x series for the next few years. The changes to the public API that are not compatible with earlier versions that were required for this release were made for the long term benefit of this project.


.{PRODUCT} and {PLANNER} versions
[cols="1,2", options="header"]
|===

|{PRODUCT_SHORT}
|OptaPlanner

|7.7
|7.33

|7.8
|7.39

|7.9
|7.44

|7.10
|7.48

|7.11
|8.5

|===


Every upgrade note has a label that indicates how likely it is that your code will be affected by that change. The following table describes each label:

.Upgrade impact labels
[cols="1,2", options="header"]
|===

|Label
|Impact

|Major
|Likely to affect your code.

|Minor
|Unlikely to affect your code, especially if you followed the examples, unless you have customized the code extensively.

|===


Any changes that are not compatible with earlier versions of OptaPlanner are annotated with the *Public API* tag.

include::{enterprise-dir}/optimizer/optaplanner-7-ref.adoc[leveloffset=+1]

include::{enterprise-dir}/optimizer/optaplanner-8-ref.adoc[leveloffset=+1]
