[id='assembly-openshift-operator']
= Deploying a {PRODUCT} environment on {OPENSHIFT} using Operators
ifdef::context[:parent-context: {context}]
// Context attribute is assembly specific and enables module reuse between assemblies.
:context: openshift-operator

// Purpose statement for the assembly
As a system engineer, you can deploy a {PRODUCT} environment on {OPENSHIFT} version 4 to provide an infrastructure to develop or execute
ifdef::DM[]
services
endif::DM[]
ifdef::PAM[]
services, process applications,
endif::PAM[]
and other business assets. You can use OpenShift Operators to deploy the environment defined in a structured YAML file and to maintain and modify this environment as necessary.

.Prerequisites

* A {OPENSHIFT} version 4 environment is available. For the exact versions of {OPENSHIFT} that the current release supports, see https://access.redhat.com/articles/3405381[Red Hat Process Automation Manager 7 Supported Configurations].
* The OpenShift project for the deployment is created.
* You are logged into the project using the OpenShift web console.
* The following resources are available on the OpenShift cluster. Depending on the application load, higher resource allocation might be necessary for acceptable performance.
** For an authoring environment, 4 gigabytes of memory and 2 virtual CPU cores for the {CENTRAL} pod. In a high-availability deployment, these resources are required for each replica and two replicas are created by default. 
ifdef::PAM[]
** For a production or immutable environment, 2 gigabytes of memory and 1 virtual CPU core for each replica of the {CENTRAL} Monitoring pod.
endif::PAM[]
** 2 gigabytes of memory and 1 virtual CPU core for each replica of each {KIE_SERVER} pod.
** In a high-availability authoring deployment, additional resources according to the configured defaults are required for the 
ifdef::PAM[]
MySQL, Red Hat AMQ, and Red Hat Data Grid 
endif::PAM[]
ifdef::DM[]
Red Hat AMQ, and Red Hat Data Grid
endif::DM[]
pods.
* Dynamic persistent volume (PV) provisioning is enabled. Alternatively, if dynamic PV provisioning is not enabled,  enough persistent volumes must be available. By default, the deployed components require the following PV sizes:
ifdef::PAM[]
** Each {KIE_SERVER} deployment by default requires one 1Gi PV for the database. You can change the database PV size. You can deploy multiple {KIE_SERVERS}; each requires a separate database PV. This requirement does not apply if you use an external database server.
endif::PAM[]
** By default, {CENTRAL} requires one 1Gi PV. You can change the PV size for {CENTRAL} persistent storage.
ifdef::PAM[]
** {CENTRAL} Monitoring requires one 64Mi PV.
** Smart Router requires one 64Mi PV.
endif::PAM[]
* If you intend to scale any of the {CENTRAL}
ifdef::PAM[]
or {CENTRAL} Monitoring
endif::PAM[]
pods, your OpenShift environment supports persistent volumes with `ReadWriteMany` mode. If your environment does not support this mode, you can use NFS to provision the volumes. For information about access mode support in OpenShift public and dedicated clouds, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/storage/understanding-persistent-storage#pv-access-modes_understanding-persistent-storage[Access Modes].

include::{enterprise-dir}/openshift/ba-openshift-overview-con.adoc[leveloffset=+1]
include::{enterprise-dir}/openshift/architecture-authoring-con.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/dm-openshift-prepare-con.adoc[leveloffset=+1]
include::{enterprise-dir}/openshift/registry-authentication-proc.adoc[leveloffset=+2]
:secrettarget: kie
include::{enterprise-dir}/openshift/secrets-secrettarget-create-proc.adoc[leveloffset=+2]
:secrettarget: central
include::{enterprise-dir}/openshift/secrets-secrettarget-create-proc.adoc[leveloffset=+2]
:secrettarget: amq
include::{enterprise-dir}/openshift/secrets-secrettarget-create-proc.adoc[leveloffset=+2]
ifdef::PAM[]
:secrettarget: smartrouter
include::{enterprise-dir}/openshift/secrets-secrettarget-create-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/externaldb-build-proc.adoc[leveloffset=+2]
endif::PAM[]
include::{enterprise-dir}/openshift/githooks-prepare-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/readwritemany-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/environment-immutable-source-extract-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/restricted-network-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/offline-repo-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/operator-con.adoc[leveloffset=+1]
include::{enterprise-dir}/openshift/operator-subscribe-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/operator-environment-deploy-assy.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/operator-modify-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/jvm-settings-ref.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/customimage-con.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/customimage-rpm-proc.adoc[leveloffset=+3]
include::{enterprise-dir}/openshift/customimage-jar-proc.adoc[leveloffset=+3]
ifdef::PAM[]
include::{enterprise-dir}/openshift/customimage-smartrouter-proc.adoc[leveloffset=+3]
endif::PAM[]
include::{enterprise-dir}/openshift/migration-ocp3-4-assy.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
