[id='assembly-ba-artificial-intelligence']
= Integrating artificial intelligence with {PRODUCT}
ifdef::context[:parent-context: {context}]

:context: artificial-intelligence

As a business rules develope...

[NOTE]


.Prerequisites



When you think about artificial intelligence, machine learning and big data might come to mind. But artificial intelligence encompasses a range of tools that can be combined to solve very different problems.
* Robotics: The integration of technology, science, and engineering that produces machines that can perform tasks that are performed by humans.
* Machine learning: The ability of a collection of algorithms to 'learn' or improve when exposed to data without being explicitly programmed to do so.
* Natural Language Processing: A subset of machine learning that processes human speech.
* Mathematical optimization: The use of conditions and constraints to find the optimal solution to a problem.
* Digital decisioning: The use of a combination of artificial intelligence tools to make business decision based on defined criteria and a series of machine and human tasks.

While science fiction is filled with what is referred to as pure AI, machines that perform better than the people and cannot be distinguished from them and learn and evolve without human intervention or control, pure AI is decades away. Meanwhile, we have pragmatic AI which is a lot less frightening and much more useful to use today. Pragmatic AI is a collection of AI technologies that combined provide business solutions to problems such as predicting customer behavior, providing automated customer service, and helping customers make purchasing decisions. Unlike pure AI, pragmatic AI needs humans to help learn and adapt itself to business challenges.

Industry  Research


{PRODUCT} uses pragmatic AI to drive decisions in a predictive and automated fashion.

Train example
Online shopping example






Combination of AI technologies

Combine three types of AI to create a solution. ML (extract information from data analysis) + DD (Model the human knowledge and experience) + MO (Solve complex problems to better resource allocation).



Business automation with machine learning

  CMMN
  BPMN2
  DMN - integrates with PMML
  PMML


Predictive Decision Automation

include::{shared-dir}/KIE/Overview/decision-authoring-assets-ref.adoc[leveloffset=+1]



ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
