[id='assembly-decision-tables']
= Designing a decision service using spreadsheet decision tables
ifdef::context[:parent-context: {context}]
// Context attribute is assembly specific and enables module reuse between assemblies.
:context: decision-tables

// Purpose statement for the assembly
As a business analyst or business rules developer, you can define business rules in a tabular format in spreadsheet decision tables and then upload the spreadsheets to your project in {CENTRAL}. These rules are compiled into Drools Rule Language (DRL) and form the core of the decision service for your project.

[NOTE]
====
You can also design your decision service using Decision Model and Notation (DMN) models instead of rule-based or table-based assets. For information about DMN support in {PRODUCT} {PRODUCT_VERSION}, see the following resources:

* {URL_GETTING_STARTED}#assembly-getting-started-decision-services[_{GETTING_STARTED_DECISION_SERVICE}_] (step-by-step tutorial with a DMN decision service example)
* {URL_DEVELOPING_DECISION_SERVICES}#assembly-dmn-models[_{DMN_MODELS}_] (overview of DMN support and capabilities in {PRODUCT})
====

.Prerequisites
* The space and project for the decision tables have been created in {CENTRAL}. Each asset is associated with a project assigned to a space. For details, see {URL_GETTING_STARTED}#assembly-getting-started-decision-services[_{GETTING_STARTED_DECISION_SERVICE}_].

// Modules - concepts, procedures, refs, etc.
include::{shared-dir}/KIE/Overview/decision-authoring-assets-ref.adoc[leveloffset=+1]

include::{drools-dir}/AuthoringAssets/decision-tables-con.adoc[leveloffset=+1]

include::{enterprise-dir}/project-data/data-objects-con.adoc[leveloffset=+1]

include::{enterprise-dir}/project-data/data-objects-create-proc.adoc[leveloffset=+2]

include::{drools-dir}/AuthoringAssets/decision-tables-use-case-con.adoc[leveloffset=+1]

include::{drools-dir}/AuthoringAssets/decision-tables-defining-proc.adoc[leveloffset=+1]

include::{drools-dir}/AuthoringAssets/decision-tables-rule-set-entries-ref.adoc[leveloffset=+2]

include::{drools-dir}/AuthoringAssets/decision-tables-rule-table-entries-ref.adoc[leveloffset=+2]

include::{drools-dir}/AuthoringAssets/decision-tables-attributes-ref.adoc[leveloffset=+2]

include::{drools-dir}/AuthoringAssets/decision-tables-upload-proc.adoc[leveloffset=+1]

include::{drools-dir}/AuthoringAssets/decision-tables-convert-proc.adoc[leveloffset=+1]

include::{enterprise-dir}/admin-and-config/assets-executing-proc.adoc[leveloffset=+1]

== Next steps
* {URL_DEVELOPING_DECISION_SERVICES}#assembly-test-scenarios[_{TESTING_DECISION_SERVICE}_]
* {URL_DEPLOYING_AND_MANAGING_SERVICES}#assembly-packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
