[id='kieserver-central-deploy-proc']
= Deploying {CENTRAL} and {KIE_SERVER}

You can deploy {CENTRAL} on the OpenShift infrastructure together with {KIE_SERVER}. In this case, you can use {CENTRAL} to manage the {KIE_SERVER} and to develop new rules.

.Procedure
. In the OpenShift Web UI, select *Add to Project > Browse Catalog*, search for `decision`, and then select the *Red Hat Decision Manager 7.0 applications (Persistent with https)* template.
** If this template is not available, download the `rhdm70-full.yaml` file from {URL_BASE_GITHUB_DM}/templates . Select *Add to Project >  Import YAML / JSON* and then select or paste the `rhdm70-full.yaml` file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
. Set the following mandatory parameters:
** *Application Name*: the name of the OpenShift application. It is used in the default URLs for {CENTRAL} and {KIE_SERVER}.
** *Decision Central Server Certificate Name*: the name of the certificate in the keystore that you created in <<secrets-central-create-proc>>.
** *Decision Central Server Keystore Password*: the password for the keystore that you created in <<secrets-central-create-proc>>.
** *KIE Server Certificate Name*: the name of the certificate in the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server Keystore Password*: the password for the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server ID*: the name of the server template on the {CENTRAL} that the {KIE_SERVER} is to join. Set this parameter to any value. If you do not set it and then the {KIE_SERVER} pod is restarted or scaled, each new instance of the server might join a new template. 
** *ImageStream Namespace*: the namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-proc>>), the namespace is `openshift`. If you have installed the image streams file, the namespace is the name of the OpenShift project.
+
You can also set other parameters as necessary.
+
IMPORTANT: if you change the *KIE Admin User* or *KIE Admin Password* parameters and do not change the Maven repository settings, you must set the *Maven Repository user name* and *Maven repository password* parameters to the same values as *KIE Admin User* and *KIE Admin Password*.
+
. Click *Create*.
