[id='kieserver-nos2i-deploy-proc']
= Deploying {KIE_SERVER} without using Source to Image (S2I)


You can deploy {KIE_SERVER} on the OpenShift infrastructure without {CENTRAL} and without S2I. In this case, {KIE_SERVER} can pick up a decision service from a Maven repository. You can configure the {KIE_SERVER} to load a service automatically; alternatively, you can manage the {KIE_SERVER} using {CENTRAL}, a controller, or the API.

.Before you begin

Ensure that the Maven repository for your decision service is available.

If you are planning to use {CENTRAL} or a management console, ensure that it is installed and record its settings for controlling a KIE server.

.Procedure
. In the OpenShift Web UI, select *Add to Project -> Browse Catalog*, search for `decision`, and then select the *Red Hat Decision Manager Execution Server 7.0 (Ephemeral with https)* template.
** If this template is not available, download the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page for {PRODUCT} {PRODUCT_VERSION}. Extract the `rhdm70-kieserver.yaml`. Select *Add to Project ->  Import YAML / JSON* and then select or paste the `rhdm70-kieserver.yaml` file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
. Set the following mandatory parameters:
** *Application Name*: The name of the OpenShift application. It is used in the default URLs for {CENTRAL} and {KIE_SERVER}.
** *KIE Server Certificate Name*: The name of the certificate in the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server Keystore Password*: The password for the keystore that you created in <<secrets-kie-create-proc>>.
** *ImageStream Namespace*: The name of the OpenShift project.
+
You can also set other parameters as necessary. In particular:
+
* If you want to set the Maven repository for retrieving the decision service, set the following parameters to point to the repository:
+
*** *Maven repository URL*
*** *Maven repository username*
*** *Maven repository password*
+
* If you want to configure the {KIE_SERVER} to load a decision service automatically, set the following parameter:
*** *KIE Server Container Deployment*: The identifying information of the decision service (KJAR file). The format is: `<containerId>=<groupId>:<artifactId>:<version>`. You can provide two or more KJAR files using the `|` separator, for example: `containerId=groupId:artifactId:version|c2=g2:a2:v2`. The {KIE_SERVER} pulls the files from the Maven repository.
+
* If you want to use {CENTRAL} deployed on the same OpenShift infrastructure to manage the {KIE_SERVER}, set the following parameter:
*** *KIE server controller service*: The OpenShift service name for the {CENTRAL}
*** *KIE server controller user*: a user name for logging onto the {CENTRAL}
*** *KIE server controller password*: The password for logging onto the {CENTRAL}
*** *KIE Server ID*: The name of the server template on the {CENTRAL} that this server is to join.
+
* If you want to use {CENTRAL} or a controller to manage the {KIE_SERVER}, set the protocol, host, and port parameters according to the URL that you use to access the web user interface of the {CENTRAL} or according to the configuration of the controller:
+
*** *KIE server controller protocol* (http or https)
*** *KIE server controller host*
*** *KIE server controller port*
*** *KIE server controller user*: a user name for logging onto the {CENTRAL} or controller
*** *KIE server controller password*: The password for logging onto the {CENTRAL} or controller
*** *KIE Server ID*: The name of the server template on the {CENTRAL} or controller that this server is to join.
+
. Click *Create*.
