[id='secrets-central-create-proc']
= Creating the secrets for {CENTRAL}

If you are planning to deploy {CENTRAL} in your OpenShift environment, you must create an SSL certificate for {CENTRAL} and provide it to your OpenShift environment as a secret. Do not use the same certificate and keystore for {CENTRAL} and for {KIE_SERVER}.

.Procedure
. Generate an SSL keystore with a private and public key for SSL encryption for {CENTRAL}. In a production environment, generate a valid signed certificate that matches the expected URL of the {CENTRAL}. Save the keystore in a file named `keystore.jks`. Record the name of the certificate and the password of the keystore file.
+
See https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.1/html-single/Security_Guide/index.html#Generate_a_SSL_Encryption_Key_and_Certificate[Generate a SSL Encryption Key and Certificate] for more information on how to create a keystore with self-signed or purchased SSL certificates.
+
. Use the `oc` command to generate a secret named `decisioncentral-app-secret` from the new keystore file:
+
[subs="verbatim,macros"]
----
$ oc create secret generic decisioncentral-app-secret --from-file=keystore.jks
----
+
. Create a service account named `decisioncentral-service-account`:
+
[subs="verbatim,macros"]
----
$ oc create serviceaccount decisioncentral-service-account
----
+
. Add the secret to the service account:
+
[subs="verbatim,macros"]
----
$ oc secret add sa/decisioncentral-service-account secret/decisioncentral-app-secret
----
