[id='secrets-kie-create-proc']
= Creating the secrets for {KIE_SERVER}

OpenShift uses objects called `Secrets` to hold sensitive information, such as passwords or keystores. See the https://access.redhat.com/documentation/en/openshift-enterprise/version-3.2/developer-guide/#dev-guide-secrets[Secrets chapter] in the OpenShift documentation for more information.

You must create an SSL certificate for {KIE_SERVER} and provide it to your OpenShift environment as a secret.

NOTE: You do not need to create the secrets object if you are planning to deploy a {KIE_SERVER} using source to image (S2I) without support for HTTPS.


.Procedure
. Generate an SSL keystore with a private and public key for SSL encryption for {KIE_SERVER}. In a production environment, generate a valid signed certificate that matches the expected URL of the {KIE_SERVER}. Save the keystore in a file named `keystore.jks`. Record the name of the certificate and the password of the keystore file. 
+
See https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.1/html-single/Security_Guide/index.html#Generate_a_SSL_Encryption_Key_and_Certificate[Generate a SSL Encryption Key and Certificate] for more information on how to create a keystore with self-signed or purchased SSL certificates.
+
. Use the `oc` command to generate a secret named `kieserver-app-secret` from the new keystore file:
+
[subs="verbatim,macros"]
----
$ oc create secret generic kieserver-app-secret --from-file=keystore.jks
----
+
. Create a service account named `kieserver-service-account`:
+
[subs="verbatim,macros"]
----
$ oc create serviceaccount kieserver-service-account
----
+
. Add the secret to the service account:
+
[subs="verbatim,macros"]
----
$ oc secret add sa/kieserver-service-account secret/kieserver-app-secret
----
