[id='interacting-with-processes-tasks-advanced-filters-proc']
= Filtering tasks using advanced filters

You can create custom task filters using the *Advanced Filters* option in {CENTRAL}.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Track* -> *Task Inbox*.
. On the *Task Inbox* page, click the advanced filters icon on the left of the page to expand the *Advanced Filters* panel.
. In the *Advanced Filters* panel, enter the filter name and description, and click *Add New*.
. Select an attribute from the *Select column* drop-down list, such as *Name*. The content of the drop-down changes to *Name != value1*.
. Click the drop-down again and choose the required logical query. For the *Name* attribute, choose *equals to*.
. Change the value of the text field to the name of the task you want to filter.
+
[NOTE]
====
The name must match the value defined in the business process of the project.
====
+
. Click *Save* and the tasks are filtered according to the filter definition.
. Click the star icon to open the *Saved Filters* pane.
+
In the *Saved Filters* pane, you can view the saved advanced filters.
