[id='interacting-with-processes-process-instances-special-filter-proc']
= Defining special filters for process instances

You can use the *Advanced* filters option in {CENTRAL} to create special filters for process instances. When you create a special filter over the column `processId`, you can view the process instance variables of the process as columns using *Show/hide columns*.

.Procedure
. In {CENTRAL}, click *Menu* -> *Manage* -> *Process Instances*.
. On the *Manage Process Instances* page, click the *Advanced Filters* icon.
. In the *Advanced Filters* pane, enter the name and description of the filter, and click *Add New*.
. From the *Select column* list, select the `processId` attribute. The value will change to *processId != value1*.
. From the *Select column* list, select *equals to* for the logical query.
. In the text field, enter the name of the process id.
. Click *Save* and the filter is applied on the current process instance list.
. Click *Show/hide columns* on the upper right of the process instances list and the process instance variables of the specified process id will be displayed.
. Click the star icon to open the *Saved Filters* pane.
+
In the *Saved Filters* pane, you can view all the saved advanced filters.
