[id='interacting-with-processes-process-instances-basic-filters-proc']
= Filtering process instances using basic filters

{CENTRAL} provides basic filters for filtering and searching through process instances based on their attributes such as *State*, *Errors*, *Filter By*, *Name*, *Start Date*, and *Last update*.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Manage* -> *Process Instances*.
. On the *Manage Process Instances* page, click the filter icon on the left of the page to expand the *Filters* pane and select the filters you want to use:
+
* *State*: Filter process instances based on their state (*Active*, *Aborted*, *Completed*, *Pending*, and *Suspended*).
* *Errors*: Filter process instances that contain at least one or no errors.
* *Filter By*: Filter process instances based on *Id*, *Initiator*, *Correlation Key*, or *Description* attribute.
* *Name*: Filter process instances based on process definition name.
* *Definition ID*: The ID of the instance definition.
* *Deployment ID*: The ID of the instance deployment.
* *SLA Compliance*: SLA compliance status (*Aborted*, *Met*, *N/A*, *Pending*, and *Violated*).
* *Parent Process ID*: The ID of the parent process instance.
* *Start Date*: Filter process instances based on their creation date.
* *Last update*: Filter process instances based on their last modified date.

You can also use the *Advanced Filters* option to create custom filters in {CENTRAL}.
