[id='process-instance-details-con-{context}']
= Process instance management

You can view all process instances under *Menu* -> *Manage* -> *Process Instances*. Each row in the *Manage Process Instances* list represents a process instance from a particular process definition. Each execution is differentiated from all the others by the internal state of the information that the process is manipulating.

Click any one of the process instances and view the corresponding details.

The process instance page provides several tabs with runtime information related to the process:

* The *Instance Details* tab: This provides you a quick overview about what is going on inside the process. It displays the current state of the instance and the current activity that is being executed. On a subprocess *Instance Details* tab, click the *Parent Process Instance* field to navigate to the parent process *Instance Details* tab for the parent process associated with the subprocess. 
* The *Process Variables* tab: This displays all of the process variables that are being manipulated by the instance, with the exception of the variables that contain documents. Additionally, you can edit the process variable value and view its history.
* The *Documents* tab: This displays process documents if the process contains a variable of the type *org.jbpm.Document*. This enables easy access, download, and manipulation of the attached documents.
* The *Logs* tab: This displays process instance logs for the respective end users. For more information, see  {URL_INTERACTING_PROCESSES_TASKS}#interacting-with-processes-viewing-process-instance-history-log-proc[_{INTERACTING_PROCESSES_TASKS}_].
* The *Diagram* tab: This tracks the progress of the process instance through the BPMN2 diagram. The node or nodes of the process flow that are in progress are highlighted in red. You can also use the links in the *Parent Process Instance* panel or *Sub Process Instance* panel on the left to navigate between the parent and subprocess *Diagram* tab.


ifdef::PAM[]
For information on user credentials and conditions to be met to access {KIE_SERVER} runtime data, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].
endif::PAM[]
