[id='bpmn-support']
= {PRODUCT} support for BPMN2

{PRODUCT} enables you to execute processes defined using the BPMN 2.0 XML format to model, execute, manage, and monitor your business processes. The full BPMN 2.0 specification also includes details on how to represent items such as choreographies and collaboration. However {PRODUCT} uses only the parts of the specification that can be used to specify executable processes. This includes almost all elements and attributes as defined in the "Common Executable" subclass of the BPMN2 specification, extended with some additional elements and attributes. 


.Legend
[width="50%", cols="2"]
|===
h|Key h| Meaning
|S | Stunner Editor Supported
|L | Legacy Editor Supported 
|N | Not Supported
|===

.Support Matrix
[cols="7"]
|===
h|Element Name 2+h| Catching            2+h| Throwing          2+h| Non-interrupting
h|               h| Start h| Intermediate h| End h| Intermediate h| Start h| Intermediate
|None             | S,L    |               | S,L  |               |        |
|Message          | S,L    | S,L           | S,L  | S,L           | L      | S,L
|Timer            | S,L    | S,L           |      |               | L      | S,L
|Error            | S,L    | S,L           | S,L  |               | L      | S,L
|Escalation       | S,L    | S,L           | S,L  | S,L           | L      | S,L
|Escalation       | S,L    | S,L           | S,L  | S,L           | L      | S,L
|Cancel           |        | N             | N    |               |        |    
|Compensation     | S,L    | S,L           | S,L  | S,L           |        |    
|Conditional      | S,L    | S,L           |      |               | L      | S,L   
|Link             |        | N             |      | N             |        |       
|Signal           | S,L    | S,L           | S,L  | S,L           | L      | S,L
|Terminate        |        |               | S,L  |               |        |       
|Multiple         | N      | N             | N    | N             | N      | N     
|Parallel Multi.  | N      | N             |      |               | N      | N     

|===

For more information about the background and applications of BPMN2, see the 
https://www.omg.org/spec/BPMN/2.0/About-BPMN/[OMG Business Process Model and Notation (BPMN) Version 2.0] specification.