= Data

Data are items that represent models of information within a process flow. {PRODUCT} supports the use of the following BPMN2 data elements:

.End events
[cols="2"]
|===
h| 
h|


| 
|

| 
|

| 
|


|===
.Data Objects
Legacy editor: SUPPORTED
New editor: SUPPORTED

Data objects are visualizations of process or sub-process data models. Within {PRODUCT}, data objects are created external to any process or rule and can be referenced by both processes and rules. They are not represented as icon elements in {PRODUCT}, but appear in text-based locations such as the *Process Variable* attributes in a process or as part of the *Data Objects* tab in guided rules and guided decision tables.

.Data Inputs
Legacy editor: SUPPORTED
New editor: SUPPORTED
BPMN 2.0 Reference: page 211
Data inputs reference information provided to a process. Information of this type may or may not produce anything, and the process is not required to make use of any defined Data Inputs. Within {PRODUCT}, data inputs are part of an *Assignments* attribute.

.Data Outputs
Legacy editor: SUPPORTED
New editor: SUPPORTED
BPMN 2.0 Reference: page 211
Data outputs reference information produced by a process. Information of this type may be newly created, or may be stored in existing data objects. Data outputs are not required to be a transformation. A data input can be passed untouched as a data output in {RHPAM} if desired. Within {PRODUCT}, data outputs are part of an *Assignments* attribute.
