[id='bpmn-con']
= Business Process Business Process Modeling and Notation Version 2.0
The Business Process Business Process Modeling and Notation Version 2.0 (BPMN2) specification is an Object Management Group (OMG) specification that defines standards for graphically representing a business process, defines execution semantics for the elements and provide an XML format of process definitions source. 

Executable processes in BPMN2 consist of different types of nodes connected using sequence flows. The BPMN 2.0 specification defines three main types of nodes:
* Events: Used to model the occurrence one of the following event types:
** Start event: Indicates the start of the process.
** End event: Defines the end of the process or subflow.
** Intermediate event: Indicates events that might occur during the execution of the process.
* Activities: Define the different actions that must be performed during the execution of the process. 
* Gateways: Used to define multiple paths in the process.

{PRODUCT} enables you to execute processes defined using the BPMN 2.0 XML format to model, execute, manage and monitor your business processes. The full BPMN 2.0 specification also includes details on how to represent items such as choreographies and collaboration. However {PRODUCT} uses only the parts of the specification that can be used to specify executable processes. This includes almost all elements and attributes as defined in the "Common Executable" subclass of the BPMN2 specification, extended with some additional elements and attributes. For more information about the background and applications of BPMN2, see the https://www.omg.org/spec/BPMN/2.0/About-BPMN/[OMG Business Process Model and Notation (BPMN) Version 2.0] specification.

= Process designer events 
Events are triggers that impact a business process. Every process must have at least one start event with no incoming and exactly one outgoing flow.

* Start events
+
Indicate the beginning of a business process.

* End events
+
Indicate the completion of a business process.

* Intermediate events
+
Drive the flow of a business process.