= Sub-Processes

You can understand a sub-process as a compound activity or a __process in a process__.
When reached during execution, the element context is instantiated and the encapsulated process triggered. Note that, if you use a Terminating End Event inside a sub-process, the entire process instance that contains the sub-process is terminated, not just the sub-process. A sub-process ends when there are no more active elements in it.

The following sub-process types are supported:

* Ad-Hoc sub-process, which has no strict element execution order.
* Embedded sub-process, which is a part of the parent process execution and shares its data.
* Reusable sub-process, which is independent from its parent process.
* Event sub-process, which is only triggered on a start event or a timer.

Note that any sub-process type can be a multi-instance sub-process.

.Embedded Sub-Process


An embedded sub-process encapsulates a part of the process.

It must contain a start event and at least one end event. Note that the element allows you to define local sub-process variables, that are accessible to all elements inside this container.

[[_adhoc_sub_process]]
.AdHoc Sub-Process
COMMENT: edit 
"`An Ad-Hoc Sub-Process is a specialized type of Sub-Process that is a group of Activities that have no REQUIRED sequence relationships. A set of Activities can be defined for the Process, but the sequence and number of performances for the Activities is determined by the performers of the Activities. footnote:[Business Process Model and Notation (BPMN). Version 2.0, OMG Document Number: formal/2011-01-03 http://www.omg.org/spec/BPMN/2.0]`"


An Ad-Hoc Sub-Process or Process contains a number of embedded inner Activities and is intended to be executed with a more flexible ordering compared to the typical routing of Processes. Unlike regular Processes, it does not contain a complete, structured BPMN diagram descriptioni.e., from Start Event to End Event. Instead the Ad-Hoc Sub-Process contains only Activities, Sequence Flows, Gateways, and Intermediate Events. An Ad-Hoc Sub-Process MAY also contain Data Objects and Data Associations. The Activities within the Ad-Hoc Sub- Process are not REQUIRED to have incoming and outgoing Sequence Flows. However, it is possible to specify Sequence Flows between some of the contained Activities. When used, Sequence Flows will provide the same ordering constraints as in a regular Process. To have any meaning, Intermediate Events will have outgoing Sequence Flows and they can be triggered multiple times while the Ad-Hoc Sub-Process is active.



* Attributes
+
*AdHocCompletionCondition*
+
When this condition evaluates to `true`, the execution finishes.
+
*AdHocOrdering*
+
Enables you to choose paralel or sequential execution of elements inside of the sub-process. 
+
*Variable Definitions*
+
Enables you to define process variables available only for elements of the sub-process.


[[_multiple_instances]]
.Multi-instance Sub-Process

A Multiple Instances Sub-Process is instantiated multiple times when its execution is triggered. The instances are created in a sequential manner, that means a new sub-process instance is created only after the previous instance has finished.

A Multiple Instances Sub-Process has one incoming connection and one outgoing connection.


* Attributes
+
*MI collection input*
A collection to be iterated through. It is used to create individual instances of given activity. The sub-process will be run with each element of this collection.
+
*MI collection output*
A collection of the sub-process execution results.
+
*MI completion condition*
An MVEL expression evaluated at the end of every instance. When evaluated as `true`, the sub-process is evaluated as finished and the sub-process's outgoing flow is taken. Possible remaining sub-process instances are cancelled.
+
*MI data input*
A variable name for each element from the collection that will be used in the process. 
+
*MI data output*
An optional variable name for the collection of the results. 

[[_event_sub_process]]
.Event Sub-Process


An event sub-process becomes active when its start event gets triggered. It can interrupt the parent process context or run in parallel to it.

With no outgoing or incoming connections, only an event or a timer can trigger the sub-process. The sub-process is not part of the regular control flow.
Although self-contained, it is executed in the context of the bounding sub-process.

Use an event sub-process within a process flow to handle events that happen outside of the main process flow.
For example, while booking a flight, two events may occur:

* Cancel booking (interrupting).
* Check booking status (non-interrupting).

Both these events can be modeled using the event sub-process.