= Sub-Processes

You can understand a sub-process as a compound activity or a __process in a process__.
When reached during execution, the element context is instantiated and the encapsulated process triggered. Note that, if you use a Terminating End Event inside a sub-process, the entire process instance that contains the sub-process is terminated, not just the sub-process. A sub-process ends when there are no more active elements in it.

The following sub-process types are supported:

* Ad-Hoc sub-process, which has no strict element execution order.
* Embedded sub-process, which is a part of the parent process execution and shares its data.
* Reusable sub-process, which is independent from its parent process.
* Event sub-process, which is only triggered on a start event or a timer.

Note that sub-process can be part of a multi-instance sub-process. COMMENT: separate icon.

.Embedded Sub-Process


An embedded sub-process encapsulates a part of the process.

It must contain a start event and at least one end event. Note that the element allows you to define local sub-process variables, that are accessible to all elements inside this container.

[[_adhoc_sub_process]]
.AdHoc Sub-Process

An Ad-Hoc Sub-Process or Process contains a number of embedded inner Activities and is intended to be executed with a more flexible ordering compared to the typical routing of Processes. Unlike regular Processes, it does not contain a complete, structured BPMN diagram descriptioni.e., from start event to End Event. Instead the Ad-Hoc Sub-Process contains only Activities, Sequence Flows, Gateways, and Intermediate Events. An Ad-Hoc Sub-Process MAY also contain Data Objects and Data Associations. The Activities within the Ad-Hoc Sub- Process are not REQUIRED to have incoming and outgoing Sequence Flows. However, it is possible to specify Sequence Flows between some of the contained Activities. When used, Sequence Flows will provide the same ordering constraints as in a regular Process. To have any meaning, Intermediate Events will have outgoing Sequence Flows and they can be triggered multiple times while the Ad-Hoc Sub-Process is active.


.Reusable sub-process
Reusable subprocesses appear collapsed within the containing process, and its elements are not visible until a plus sign at the lower edge of the rounded rectangle is clicked.

[[_multiple_instances]]
.Multi-instance Sub-Process

A Multiple Instances Sub-Process is instantiated multiple times when its execution is triggered. The instances are created in a sequential manner, that means a new sub-process instance is created only after the previous instance has finished.

A Multiple Instances Sub-Process has one incoming connection and one outgoing connection.


[[_event_sub_process]]
.Event Sub-Process


An event sub-process becomes active when its start event gets triggered. It can interrupt the parent process context or run in parallel to it.

With no outgoing or incoming connections, only an event or a timer can trigger the sub-process. The sub-process is not part of the regular control flow.
Although self-contained, it is executed in the context of the bounding sub-process.

Use an event sub-process within a process flow to handle events that happen outside of the main process flow.
For example, while booking a flight, two events may occur:

* Cancel booking (interrupting).
* Check booking status (non-interrupting).

Both these events can be modeled using the event sub-process.