[id='controller-java-clients-ref_{context}']
= Supported {CONTROLLER} Java clients

The following are some of the Java client services available in the `org.kie.server.controller.client` package of your {PRODUCT} distribution. You can use these services to interact with related resources in the {CONTROLLER} similarly to the {CONTROLLER} REST API.

* `KieServerControllerClient`: Used as the entry point for communicating with the {CONTROLLER}
* `RestKieServerControllerClient`: Implementation used to interact with {KIE_SERVER} templates and KIE containers in REST protocol (found in `~/org/kie/server/controller/client/rest`)
* `WebSocketKieServerControllerClient`: Implementation used to interact with {KIE_SERVER} templates and KIE containers in WebSocket protocol (found in `~/org/kie/server/controller/client/websocket`)

For the full list of available {CONTROLLER} Java clients,
ifdef::DM,PAM[]
download the *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Source Distribution* from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Red Hat Customer Portal] and navigate to `~/{PRODUCT_FILE}-sources/src/droolsjbpm-integration-$VERSION/kie-server-parent/kie-server-controller/kie-server-controller-client/src/main/java/org/kie/server/controller/client`.
endif::[]
ifdef::DROOLS,JBPM,OP[]
see the Java client API source in https://github.com/kiegroup/droolsjbpm-integration/tree/main/kie-server-parent/kie-server-controller/kie-server-controller-client/src/main/java/org/kie/server/controller/client[GitHub].
endif::[]
