[id='controller-rest-api-endpoints-ref_{context}']
= Supported {CONTROLLER} REST API endpoints

The {CONTROLLER} REST API provides endpoints for interacting with {KIE_SERVER} templates (configurations), {KIE_SERVER} instances (remote servers), and associated KIE containers (deployment units). The {CONTROLLER} REST API base URL is `\http://SERVER:PORT/CONTROLLER/rest/`. All requests require HTTP Basic authentication or token-based authentication for the `rest-all` user role if you installed {CENTRAL} and you want to use the built-in {CONTROLLER}, or the `kie-server` user role if you installed the {HEADLESS_CONTROLLER} separately from {CENTRAL}.

For the full list of {CONTROLLER} REST API endpoints and descriptions, use one of the following resources:

* http://jbpm.org/learn/documentation.html[Controller REST API] on the jBPM Documentation page (static)
* Swagger UI for the {CONTROLLER} REST API at `\http://SERVER:PORT/CONTROLLER/docs` (dynamic, requires running {CONTROLLER})
+
[NOTE]
====
By default, the Swagger web interface for the {CONTROLLER} is enabled by the `org.kie.workbench.swagger.disabled=false` system property. To disable the Swagger web interface for the {CONTROLLER}, set this system property to `true`.

If you are using the {CONTROLLER} built in to {CENTRAL}, the Swagger page associated with the {CONTROLLER} is identified as the "{CENTRAL} API" for {CENTRAL} REST services. If you are using the {HEADLESS_CONTROLLER} without {CENTRAL}, the Swagger page associated with the {HEADLESS_CONTROLLER} is identified as the "Controller API". In both cases, the {CONTROLLER} REST API endpoints are the same.
====
