[id='kie-server-rest-api-endpoints-ref_{context}']
= Supported {KIE_SERVER} REST API endpoints

The {KIE_SERVER} REST API provides endpoints for the following types of resources in {PRODUCT}:

* {KIE_SERVER} and KIE containers
* KIE session assets (for runtime commands)
* DMN assets
* Planning solvers
ifdef::PAM,JBPM[]
* Processes
* Process images
* Process and task forms
* Tasks
* Cases
* Documents
* Jobs
* Queries for processes, tasks, and cases
* Custom queries
endif::PAM,JBPM[]

The {KIE_SERVER} REST API base URL is `\http://SERVER:PORT/kie-server/services/rest/`. All requests require HTTP Basic authentication or token-based authentication for the `kie-server` user role.

For the full list of {KIE_SERVER} REST API endpoints and descriptions, use one of the following resources:

* http://jbpm.org/learn/documentation.html[Execution Server REST API] on the jBPM Documentation page (static)
* Swagger UI for the {KIE_SERVER} REST API at `\http://SERVER:PORT/kie-server/docs` (dynamic, requires running {KIE_SERVER})
+
NOTE: By default, the Swagger web interface for {KIE_SERVER} is enabled by the `org.kie.swagger.server.ext.disabled=false` system property. To disable the Swagger web interface in {KIE_SERVER}, set this system property to `true`.

ifdef::PAM,JBPM[]
For API access to process images, the system property `<storesvgonsave enabled="true"/>` must be configured for your {PRODUCT} project in `$SERVER_HOME/standalone/deployments/{URL_COMPONENT_CENTRAL}.war/org.kie.workbench.KIEWebapp/profiles/jbpm.xml`. This property is set to `true` by default. If the API is not working with process images, set it to `true` in the file, restart your {KIE_SERVER}, modify the relevant process and save it, and then build and deploy your project. This property enables SVG images to be stored so that they can be retrieved by the {KIE_SERVER} REST API.
endif::[]
