[id='kie-server-rest-api-custom-queries-endpoints-con_{context}']
= Custom queries

You can use custom query endpoints to create and access custom queries in {PRODUCT}. Custom queries can request any data from the {PRODUCT} database.

A number of custom queries are included in {PRODUCT}. You can use these queries to access complete lists of process instances and user tasks.

When running a custom query, you must provide the name of a _query mapper_ in the `mapper` parameter. A mapper maps SQL query results into objects for a JSON response. You can implement your own query result mappers or use the mappers provided with {PRODUCT}. The query mappers in {PRODUCT} are similar to other object-relational mapping (ORM) providers, such as Hibernate, which maps tables to entities.

For example, if a custom query returns process instance data, you can use the `org.jbpm.kie.services.impl.query.mapper.ProcessInstanceQueryMapper` mapper, also registered as `ProcessInstances`. If a custom query returns human task data, you can use the `org.jbpm.kie.services.impl.query.mapper.UserTaskInstanceQueryMapper` mapper, also registered as `UserTasks`. You can also use other mappers that provide additional information.

For a list of query mappers that are included in {PRODUCT}, see the https://github.com/kiegroup/jbpm/tree/{COMMUNITY_VERSION_FINAL}/jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper[GitHub repository].
