[id='kie-server-rest-api-requests-swagger-proc_{context}']
= Sending requests with the {KIE_SERVER} REST API using the Swagger interface

The {KIE_SERVER} REST API supports a Swagger web interface that you can use instead of a standalone REST client or curl utility to interact with your KIE containers and business assets (such as business rules, processes, and solvers) in {PRODUCT} without using the {CENTRAL} user interface.

NOTE: By default, the Swagger web interface for {KIE_SERVER} is enabled by the `org.kie.swagger.server.ext.disabled=false` system property. To disable the Swagger web interface in {KIE_SERVER}, set this system property to `true`.

.Prerequisites
* {KIE_SERVER} is installed and running.
* You have `kie-server` user role access to {KIE_SERVER}.

.Procedure
. In a web browser, navigate to `\http://SERVER:PORT/kie-server/docs`, such as `\http://localhost:8080/kie-server/docs`, and log in with the user name and password of the {KIE_SERVER} user with the `kie-server` role.
. In the Swagger page, select the relevant API endpoint to which you want to send a request, such as *KIE Server and KIE containers* -> *[GET] /server/containers* to retrieve KIE containers from {KIE_SERVER}.
. Click *Try it out* and provide any optional parameters by which you want to filter results, if needed.
. In the *Response content type* drop-down menu, select the desired format of the server response, such as *application/json* for JSON format.
. Click *Execute* and review the {KIE_SERVER} response.
+
--
Example server response (JSON):

[source,json]
----
{
  "type": "SUCCESS",
  "msg": "List of created containers",
  "result": {
    "kie-containers": {
      "kie-container": [
        {
          "container-id": "itorders_1.0.0-SNAPSHOT",
          "release-id": {
            "group-id": "itorders",
            "artifact-id": "itorders",
            "version": "1.0.0-SNAPSHOT"
          },
          "resolved-release-id": {
            "group-id": "itorders",
            "artifact-id": "itorders",
            "version": "1.0.0-SNAPSHOT"
          },
          "status": "STARTED",
          "scanner": {
            "status": "DISPOSED",
            "poll-interval": null
          },
          "config-items": [],
          "container-alias": "itorders"
        }
      ]
    }
  }
}
----
--
. For this example, copy or note the project `group-id`, `artifact-id`, and `version` (GAV) data from one of the deployed KIE containers returned in the response.
. In the Swagger page, navigate to the *KIE Server and KIE containers* -> *[PUT] /server/containers/{containerId}* endpoint to send another request to deploy a new KIE container with the copied project GAV data. Adjust any request details according to your use case.
. Click *Try it out* and enter the following components for the request:
+
--
* *containerId*: Enter the ID of the new KIE container, such as `MyContainer`.
* *body*: Set the *Parameter content type* to the desired request body format, such as *application/json* for JSON format, and add a request body with the configuration items for the new KIE container:

[source,json]
----
{
  "config-items": [
    {
      "itemName": "RuntimeStrategy",
      "itemValue": "SINGLETON",
      "itemType": "java.lang.String"
    },
    {
      "itemName": "MergeMode",
      "itemValue": "MERGE_COLLECTIONS",
      "itemType": "java.lang.String"
    },
    {
      "itemName": "KBase",
      "itemValue": "",
      "itemType": "java.lang.String"
    },
    {
      "itemName": "KSession",
      "itemValue": "",
      "itemType": "java.lang.String"
    }
  ],
  "release-id": {
    "group-id": "itorders",
    "artifact-id": "itorders",
    "version": "1.0.0-SNAPSHOT"
  },
  "scanner": {
    "poll-interval": "5000",
    "status": "STARTED"
  }
}
----
--
. In the *Response content type* drop-down menu, select the desired format of the server response, such as *application/json* for JSON format.
. Click *Execute* and review the {KIE_SERVER} response.
+
--
Example server response (JSON):

[source,json]
----
{
  "type": "SUCCESS",
  "msg": "Container MyContainer successfully deployed with module itorders:itorders:1.0.0-SNAPSHOT.",
  "result": {
    "kie-container": {
      "container-id": "MyContainer",
      "release-id": {
        "group-id": "itorders",
        "artifact-id": "itorders",
        "version": "1.0.0-SNAPSHOT"
      },
      "resolved-release-id": {
        "group-id": "itorders",
        "artifact-id": "itorders",
        "version": "1.0.0-SNAPSHOT"
      },
      "status": "STARTED",
      "scanner": {
        "status": "STARTED",
        "poll-interval": 5000
      },
      "config-items": [],
      "messages": [
        {
          "severity": "INFO",
          "timestamp": {
            "java.util.Date": 1540584717937
          },
          "content": [
            "Container MyContainer successfully created with module itorders:itorders:1.0.0-SNAPSHOT."
          ]
        }
      ],
      "container-alias": null
    }
  }
}
----

If you encounter request errors, review the returned error code messages and adjust your request accordingly.

ifdef::PAM,JBPM[]
.REST API requests for process instances
[NOTE]
====
For REST API requests that send complex data objects to the process instance endpoint `/server/containers/{containerId}/processes/{processId}/instances`, ensure that you include either the fully qualified class name (such as `com.myspace.Person`) or the simple class name (such as `Person`) in the request body. The class name is required for the request body to be mapped to the correct business object in {PRODUCT}. If you exclude the class name from the request, {KIE_SERVER} does not unmarshall the object to the expected type.

.Correct request body for process instance
[source,json]
----
{
  "id": 4,
  "lease": {
    "com.myspace.restcall.LeaseModel": {
      "annualRent": 109608,
      "isAutoApproved": false
    }
  }
}
----

.Incorrect request body for process instance
[source,json]
----
{
  "id": 4,
  "lease": {
    "annualRent": 109608,
    "isAutoApproved": false
  }
}
----
====
endif::[]
--
