[id='kie-server-java-clients-ref_{context}']
= Supported {KIE_SERVER} Java clients

The following are some of the Java client services available in the `org.kie.server.client` package of your {PRODUCT} distribution. You can use these services to interact with related resources in {KIE_SERVER} similarly to the {KIE_SERVER} REST API.

* `KieServicesClient`: Used as the entry point for other {KIE_SERVER} Java clients, and used to interact with KIE containers
* `JobServicesClient`: Used to schedule, cancel, re-queue, and get job requests
* `RuleServicesClient`: Used to send commands to the server to perform rule-related operations, such as executing rules or inserting objects into the KIE session
<<<<<<< HEAD
////
* `SolverServicesClient`: Used to perform all {PLANNER} operations, such as getting the solver state and the best solution, or disposing a solver
////
=======
ifndef::DM,PAM[]
* `SolverServicesClient`: Used to perform all {PLANNER} operations, such as getting the solver state and the best solution, or disposing a solver
endif::[]
>>>>>>> 689fa946d (BXMSDOC-8517 removed Business Optimizer)
ifdef::PAM,JBPM[]
* `ProcessServicesClient`: Used to start, signal, and abort processes or work items
* `QueryServicesClient`: Used to query processes, process nodes, and process variables
* `UserTaskServicesClient`: Used to perform all user-task operations, such as starting, claiming, or canceling a task, and to query tasks by a specified field, such as by user or by process instances ID
* `UIServicesClient`: Used to get String representation of forms (XML or JSON) and of a process image (SVG)
* `ProcessAdminServicesClient`: Provides an interface for operations with process instances (found in `~/org/kie/server/client/admin`)
* `UserTaskAdminServicesClient`: Provides an interface for operations with user tasks (found in `~/org/kie/server/client/admin`)
endif::[]

The `getServicesClient` method provides access to any of these clients:

[source,java]
----
RuleServicesClient rulesClient = kieServicesClient.getServicesClient(RuleServicesClient.class);
----

For the full list of available {KIE_SERVER} Java clients,
ifdef::DM,PAM[]
download the *{PRODUCT} {PRODUCT_VERSION} - Source Distribution* from the {PRODUCT_DOWNLOAD_LINK}[IBM Business Automation Manager Open Editions {ENTERPRISE_VERSION} downloads] page  and navigate to `~/{PRODUCT_FILE}-sources/src/droolsjbpm-integration-$VERSION/kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client`.
endif::[]
ifdef::DROOLS,JBPM,OP[]
see the Java client API source in https://github.com/kiegroup/droolsjbpm-integration/tree/master/kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client[GitHub].
endif::[]
