// To reuse this module, ifeval the title to be more specific as needed.

[id='kie-server-rest-api-forms-ref_{context}']
= Process and task forms

// The {KIE_SERVER} REST API supports the following endpoints for retrieving process and task forms. The {KIE_SERVER} REST API base URL is `\http://SERVER:PORT/kie-server/services/rest/`. All requests require HTTP Basic authentication or token-based authentication for the `kie-server` user role.

== [GET] /server/containers/{containerId}/forms/processes/{processId}

Returns the form information for a specified process definition.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the process definition is located
|String
|Required

|`processId`
|ID of the process definition for which you are retrieving the form
|String
|Required

|`lang`
|Language of the form to be retrieved (default: `en`)
|String
|Optional

|`filter`
|Filters the process form according to the `lang` option selected, when set to `true` (default: `null`)
|Boolean
|Optional

|`type`
|Type of form to be retrieved, `FORM`, `FRM`, `FTL`, or `ANY` (default: `ANY`)
|String
|Optional

|`marshallContent`
|Marshalls the form content according to the HTTP header used for the request when set to `true`, for XML (JAXB, XSTREAM) or JSON format, or marshalls the form content in JSON when set to `false` or `null` (default: `true`)
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/evaluation_1.0.0-SNAPSHOT/forms/processes/evaluation?lang=en&filter=true&type=ANY&marshallContent=true
----

.Example server response (JSON)
[source,json]
----
{
  "id": "d1e6dd47-b24c-4f93-ba25-337832926113",
  "name": "evaluation-taskform.frm",
  "model": {
    "processName": "Evaluation",
    "processId": "evaluation",
    "name": "process",
    "properties": [
      {
        "name": "employee",
        "typeInfo": {
          "type": "BASE",
          "className": "java.lang.String",
          "multiple": false
        },
        "metaData": {
          "entries": [
            {
              "name": "field-readOnly",
              "value": false
            }
          ]
        }
      },
      {
        "name": "initiator",
        "typeInfo": {
          "type": "BASE",
          "className": "java.lang.String",
          "multiple": false
        },
        "metaData": {
          "entries": [
            {
              "name": "field-readOnly",
              "value": false
            }
          ]
        }
      },
      {
        "name": "performance",
        "typeInfo": {
          "type": "BASE",
          "className": "java.lang.Integer",
          "multiple": false
        },
        "metaData": {
          "entries": [
            {
              "name": "field-readOnly",
              "value": false
            }
          ]
        }
      },
      {
        "name": "reason",
        "typeInfo": {
          "type": "BASE",
          "className": "java.lang.String",
          "multiple": false
        },
        "metaData": {
          "entries": [
            {
              "name": "field-readOnly",
              "value": false
            }
          ]
        }
      }
    ],
    "formModelType": "org.kie.workbench.common.forms.jbpm.model.authoring.process.BusinessProcessFormModel"
  },
  "fields": [
    {
      "maxLength": 100,
      "placeHolder": "Employee",
      "id": "field_740177746345817E11",
      "name": "employee",
      "label": "Employee",
      "required": true,
      "readOnly": false,
      "validateOnChange": true,
      "binding": "employee",
      "standaloneClassName": "java.lang.String",
      "code": "TextBox",
      "serializedFieldClassName": "org.kie.workbench.common.forms.fields.shared.fieldTypes.basic.textBox.definition.TextBoxFieldDefinition"
    },
    {
      "placeHolder": "Reason",
      "rows": 4,
      "id": "field_282038126127015E11",
      "name": "reason",
      "label": "Reason",
      "required": true,
      "readOnly": false,
      "validateOnChange": true,
      "binding": "reason",
      "standaloneClassName": "java.lang.String",
      "code": "TextArea",
      "serializedFieldClassName": "org.kie.workbench.common.forms.fields.shared.fieldTypes.basic.textArea.definition.TextAreaFieldDefinition"
    }
  ],
  "layoutTemplate": {
    "version": 2,
    "name": "evaluation-taskform.frm",
    "style": "FLUID",
    "layoutProperties": {},
    "rows": [
      {
        "height": "12",
        "layoutColumns": [
          {
            "span": "12",
            "height": "12",
            "rows": [],
            "layoutComponents": [
              {
                "dragTypeName": "org.kie.workbench.common.forms.editor.client.editor.rendering.EditorFieldLayoutComponent",
                "properties": {
                  "field_id": "field_740177746345817E11",
                  "form_id": "d1e6dd47-b24c-4f93-ba25-337832926113"
                }
              }
            ]
          }
        ]
      },
      {
        "height": "12",
        "layoutColumns": [
          {
            "span": "12",
            "height": "12",
            "rows": [],
            "layoutComponents": [
              {
                "dragTypeName": "org.kie.workbench.common.forms.editor.client.editor.rendering.EditorFieldLayoutComponent",
                "properties": {
                  "field_id": "field_282038126127015E11",
                  "form_id": "d1e6dd47-b24c-4f93-ba25-337832926113"
                }
              }
            ]
          }
        ]
      }
    ]
  }
}
----


== [GET] /server/containers/{containerId}/forms/tasks/{taskInstanceId}

Returns the form information for a specified task instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the process definition is located
|String
|Required

|`taskInstanceId`
|ID of the task instance for which you are retrieving the form
|String
|Required

|`lang`
|Language of the form to be retrieved (default: `en`)
|String
|Optional

|`filter`
|Filters the process form according to the `lang` option selected, when set to `true` (default: `null`)
|Boolean
|Optional

|`type`
|Type of form to be retrieved, `FORM`, `FRM`, `FTL`, or `ANY` (default: `ANY`)
|String
|Optional

|`marshallContent`
|Marshalls the form content according to the HTTP header used for the request when set to `true`, for XML (JAXB, XSTREAM) or JSON format, or marshalls the form content in JSON when set to `false` or `null` (default: `true`)
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/evaluation_1.0.0-SNAPSHOT/forms/tasks/24?lang=en&filter=true&type=ANY&marshallContent=true
----

.Example server response (JSON)
[source,json]
----
{
  "id": "47078d21-7da5-4d3f-8355-0fcd78b09f39",
  "name": "PerformanceEvaluation-taskform.frm",
  "model": {
    "taskName": "PerformanceEvaluation",
    "processId": "evaluation",
    "name": "task",
    "properties": [
      {
        "name": "BusinessAdministratorId",
        "typeInfo": {
          "type": "BASE",
          "className": "java.lang.String",
          "multiple": false
        },
        "metaData": {
          "entries": [
            {
              "name": "field-readOnly",
              "value": true
            }
          ]
        }
      },
      {
        "name": "reason",
        "typeInfo": {
          "type": "BASE",
          "className": "java.lang.String",
          "multiple": false
        },
        "metaData": {
          "entries": [
            {
              "name": "field-readOnly",
              "value": true
            }
          ]
        }
      },
      {
        "name": "performance",
        "typeInfo": {
          "type": "BASE",
          "className": "java.lang.Integer",
          "multiple": false
        },
        "metaData": {
          "entries": [
            {
              "name": "field-readOnly",
              "value": false
            }
          ]
        }
      }
    ],
    "formModelType": "org.kie.workbench.common.forms.jbpm.model.authoring.task.TaskFormModel"
  },
  "fields": [
    {
      "placeHolder": "Reason",
      "rows": 4,
      "id": "field_332058348325587E12",
      "name": "reason",
      "label": "Reason",
      "required": false,
      "readOnly": true,
      "validateOnChange": true,
      "binding": "reason",
      "standaloneClassName": "java.lang.String",
      "code": "TextArea",
      "serializedFieldClassName": "org.kie.workbench.common.forms.fields.shared.fieldTypes.basic.textArea.definition.TextAreaFieldDefinition"
    },
    {
      "placeHolder": "Performance",
      "maxLength": 100,
      "id": "field_336003622256354E12",
      "name": "performance",
      "label": "Performance",
      "required": true,
      "readOnly": false,
      "validateOnChange": true,
      "binding": "performance",
      "standaloneClassName": "java.lang.Integer",
      "code": "IntegerBox",
      "serializedFieldClassName": "org.kie.workbench.common.forms.fields.shared.fieldTypes.basic.integerBox.definition.IntegerBoxFieldDefinition"
    }
  ],
  "layoutTemplate": {
    "version": 2,
    "name": "PerformanceEvaluation-taskform.frm",
    "style": "FLUID",
    "layoutProperties": {},
    "rows": [
      {
        "height": "12",
        "layoutColumns": [
          {
            "span": "12",
            "height": "12",
            "rows": [],
            "layoutComponents": [
              {
                "dragTypeName": "org.kie.workbench.common.forms.editor.client.editor.rendering.EditorFieldLayoutComponent",
                "properties": {
                  "field_id": "field_332058348325587E12",
                  "form_id": "47078d21-7da5-4d3f-8355-0fcd78b09f39"
                }
              }
            ]
          }
        ]
      },
      {
        "height": "12",
        "layoutColumns": [
          {
            "span": "12",
            "height": "12",
            "rows": [],
            "layoutComponents": [
              {
                "dragTypeName": "org.kie.workbench.common.forms.editor.client.editor.rendering.EditorFieldLayoutComponent",
                "properties": {
                  "field_id": "field_336003622256354E12",
                  "form_id": "47078d21-7da5-4d3f-8355-0fcd78b09f39"
                }
              }
            ]
          }
        ]
      }
    ]
  }
}
----
