[id='kie-server-extensions-con_{context}']

= {KIE_SERVER} capabilities and extensions

The capabilities in {KIE_SERVER} are determined by plug-in extensions that you can enable, disable, or further extend to meet your business needs. {KIE_SERVER} supports the following default capabilities and extensions:

.{KIE_SERVER} capabilities and extensions
[cols="20%,20%,60%" options="header"]
|===
|Capability name
|Extension name
|Description

|`KieServer`
|`KieServer`
|Provides the core capabilities of {KIE_SERVER}, such as creating and disposing KIE containers on your server instance

|`BRM`
|`Drools`
|Provides the Business Rule Management (BRM) capabilities, such as inserting facts and executing business rules

ifdef::PAM,JBPM[]
|`BPM`
|`jBPM`
|Provides the Business Process Management (BPM) capabilities, such as managing user tasks and executing business processes

|`BPM-UI`
|`jBPM-UI`
|Provides additional user-interface capabilities related to business processes, such as rendering XML forms and SVG images in process diagrams

|`CaseMgmt`
|`Case-Mgmt`
|Provides the case management capabilities for business processes, such as managing case definitions and milestones
endif::[]

|`BRP`
|`OptaPlanner`
|Provides the Business Resource Planning (BRP) capabilities, such as implementing solvers

|`DMN`
|`DMN`
|Provides the Decision Model and Notation (DMN) capabilities, such as managing DMN data types and executing DMN models

|`Swagger`
|`Swagger`
|Provides the Swagger web-interface capabilities for interacting with the {KIE_SERVER} REST API
|===

To view the supported extensions of a running {KIE_SERVER} instance, send a `GET` request to the following REST API endpoint and review the XML or JSON server response:

.Base URL for GET request for {KIE_SERVER} information
[source]
----
http://SERVER:PORT/kie-server/services/rest/server
----

.Example JSON response with {KIE_SERVER} information
ifdef::PAM,JBPM[]
[source,json,subs="attributes+"]
----
{
  "type": "SUCCESS",
  "msg": "Kie Server info",
  "result": {
    "kie-server-info": {
      "id": "test-kie-server",
      "version": "7.26.0.20190818-050814",
      "name": "test-kie-server",
      "location": "http://localhost:8080/kie-server/services/rest/server",
      "capabilities": [
        "KieServer",
        "BRM",
        "BPM",
        "CaseMgmt",
        "BPM-UI",
        "BRP",
        "DMN",
        "Swagger"
      ],
      "messages": [
        {
          "severity": "INFO",
          "timestamp": {
            "java.util.Date": 1566169865791
          },
          "content": [
            "Server KieServerInfo{serverId='test-kie-server', version='7.26.0.20190818-050814', name='test-kie-server', location='http:/localhost:8080/kie-server/services/rest/server', capabilities=[KieServer, BRM, BPM, CaseMgmt, BPM-UI, BRP, DMN, Swagger]', messages=null', mode=DEVELOPMENT}started successfully at Sun Aug 18 23:11:05 UTC 2019"
          ]
        }
      ],
      "mode": "DEVELOPMENT"
    }
  }
}
----
endif::[]
ifdef::DM,DROOLS,OP[]
[source,json,subs="attributes+"]
----
{
  "type": "SUCCESS",
  "msg": "Kie Server info",
  "result": {
    "kie-server-info": {
      "id": "test-kie-server",
      "version": "7.26.0.20190818-050814",
      "name": "test-kie-server",
      "location": "http://localhost:8080/kie-server/services/rest/server",
      "capabilities": [
        "KieServer",
        "BRM",
        "BRP",
        "DMN",
        "Swagger"
      ],
      "messages": [
        {
          "severity": "INFO",
          "timestamp": {
            "java.util.Date": 1566169865791
          },
          "content": [
            "Server KieServerInfo{serverId='test-kie-server', version='7.26.0.20190818-050814', name='test-kie-server', location='http:/localhost:8080/kie-server/services/rest/server', capabilities=[KieServer, BRM, BRP, DMN, Swagger]', messages=null', mode=DEVELOPMENT}started successfully at Sun Aug 18 23:11:05 UTC 2019"
          ]
        }
      ],
      "mode": "DEVELOPMENT"
    }
  }
}
----
endif::[]

To enable or disable {KIE_SERVER} extensions, configure the related `*.server.ext.disabled` {KIE_SERVER} system property. For example, to disable the `BRM` capability, set the system property `org.drools.server.ext.disabled=true`. For all {KIE_SERVER} system properties, see
ifdef::DROOLS,JBPM,OP[]
xref:kie-server-system-properties-ref_{context}[].
endif::[]
ifdef::DM,PAM[]
xref:kie-server-system-properties-ref_{context}[].
endif::[]

By default, {KIE_SERVER} extensions are exposed through REST or JMS data transports and use predefined client APIs. You can extend existing {KIE_SERVER} capabilities with additional REST endpoints, extend supported transport methods beyond REST or JMS, or extend functionality in the {KIE_SERVER} client.

This flexibility in {KIE_SERVER} functionality enables you to adapt your {KIE_SERVER} instances to your business needs, instead of adapting your business needs to the default {KIE_SERVER} capabilities.

ifdef::DM,PAM[]
IMPORTANT: If you extend {KIE_SERVER} functionality, Red Hat does not support the custom code that you use as part of your custom implementations and extensions.
endif::[]
