// To reuse this module, ifeval the title to be more specific as needed.

[id='kie-server-rest-api-case-instances-ref_{context}']
= Case instances

//The {KIE_SERVER} REST API supports the following endpoints for managing case instances. The {KIE_SERVER} REST API base URL is `\http://SERVER:PORT/kie-server/services/rest/`. All requests require HTTP Basic authentication or token-based authentication for the `kie-server` user role.

== [GET] /server/containers/{containerId}/cases/definitions

Returns case definitions in a specified KIE container.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case definitions reside
|String
|Required

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/definitions?page=0&pageSize=10&sort=name&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "definitions": [
    {
      "name": "Order for IT hardware",
      "id": "itorders.orderhardware",
      "version": "1.0",
      "case-id-prefix": "IT",
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "adhoc-fragments": [
        {
          "name": "Prepare hardware spec",
          "type": "HumanTaskNode"
        },
        {
          "name": "Milestone 1: Order placed",
          "type": "MilestoneNode"
        },
        {
          "name": "Milestone 2: Order shipped",
          "type": "MilestoneNode"
        },
        {
          "name": "Milestone 3: Delivered to customer",
          "type": "MilestoneNode"
        },
        {
          "name": "Hardware spec ready",
          "type": "MilestoneNode"
        },
        {
          "name": "Manager decision",
          "type": "MilestoneNode"
        }
      ],
      "roles": {
        "owner": 1,
        "manager": 1,
        "supplier": 2
      },
      "milestones": [
        {
          "milestone-name": "Milestone 1: Order placed",
          "milestone-id": "_DCD97847-6E3C-4C5E-9EE3-221C04BE42ED",
          "milestone-mandatory": false
        },
        {
          "milestone-name": "Milestone 2: Order shipped",
          "milestone-id": "_343B90CD-AA19-4894-B63C-3CE1906E6FD1",
          "milestone-mandatory": false
        },
        {
          "milestone-name": "Milestone 3: Delivered to customer",
          "milestone-id": "_52AFA23F-C087-4519-B8F2-BABCC31D68A6",
          "milestone-mandatory": false
        },
        {
          "milestone-name": "Hardware spec ready",
          "milestone-id": "_483CF785-96DD-40C1-9148-4CFAFAE5778A",
          "milestone-mandatory": false
        },
        {
          "milestone-name": "Manager decision",
          "milestone-id": "_79953D58-25DB-4FD6-94A0-DFC6EA2D0339",
          "milestone-mandatory": false
        }
      ],
      "stages": []
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/definitions/{caseDefId}

Returns information about a specified case definition.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case definition is located
|String
|Required

|`caseDefId`
|ID of the case definition to be retrieved (example: `itorders.orderhardware`)
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "name": "Order for IT hardware",
  "id": "itorders.orderhardware",
  "version": "1.0",
  "case-id-prefix": "IT",
  "container-id": "itorders_1.0.0-SNAPSHOT",
  "adhoc-fragments": [
    {
      "name": "Prepare hardware spec",
      "type": "HumanTaskNode"
    },
    {
      "name": "Milestone 1: Order placed",
      "type": "MilestoneNode"
    },
    {
      "name": "Milestone 2: Order shipped",
      "type": "MilestoneNode"
    },
    {
      "name": "Milestone 3: Delivered to customer",
      "type": "MilestoneNode"
    },
    {
      "name": "Hardware spec ready",
      "type": "MilestoneNode"
    },
    {
      "name": "Manager decision",
      "type": "MilestoneNode"
    }
  ],
  "roles": {
    "owner": 1,
    "manager": 1,
    "supplier": 2
  },
  "milestones": [
    {
      "milestone-name": "Milestone 1: Order placed",
      "milestone-id": "_DCD97847-6E3C-4C5E-9EE3-221C04BE42ED",
      "milestone-mandatory": false
    },
    {
      "milestone-name": "Milestone 2: Order shipped",
      "milestone-id": "_343B90CD-AA19-4894-B63C-3CE1906E6FD1",
      "milestone-mandatory": false
    },
    {
      "milestone-name": "Milestone 3: Delivered to customer",
      "milestone-id": "_52AFA23F-C087-4519-B8F2-BABCC31D68A6",
      "milestone-mandatory": false
    },
    {
      "milestone-name": "Hardware spec ready",
      "milestone-id": "_483CF785-96DD-40C1-9148-4CFAFAE5778A",
      "milestone-mandatory": false
    },
    {
      "milestone-name": "Manager decision",
      "milestone-id": "_79953D58-25DB-4FD6-94A0-DFC6EA2D0339",
      "milestone-mandatory": false
    }
  ],
  "stages": []
}
----

== [GET] /server/containers/{containerId}/cases/instances

Returns case instances in a specified KIE container.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instances reside
|String
|Required

|`status`
|Open (`1`), closed (`2`), or cancelled (`3`) case instances (default: `1`, open)
|Array [integer]
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances?status=open&page=0&pageSize=10&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "instances": [
    {
      "case-id": "IT-0000000006",
      "case-description": "Order for IT hardware",
      "case-owner": "baAdmin",
      "case-status": 1,
      "case-definition-id": "itorders.orderhardware",
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "case-started-at": 1540474204152,
      "case-completed-at": null,
      "case-completion-msg": "",
      "case-sla-compliance": 0,
      "case-sla-due-date": null,
      "case-file": null,
      "case-milestones": null,
      "case-stages": null,
      "case-roles": null
    },
    {
      "case-id": "IT-0000000007",
      "case-description": "Order for IT hardware 2",
      "case-owner": "baAdmin",
      "case-status": 1,
      "case-definition-id": "itorders.orderhardware",
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "case-started-at": 1540474204152,
      "case-completed-at": null,
      "case-completion-msg": "",
      "case-sla-compliance": 0,
      "case-sla-due-date": null,
      "case-file": null,
      "case-milestones": null,
      "case-stages": null,
      "case-roles": null
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/instances/{caseId}

Returns information about a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance to be retrieved (example: `IT-0000000006`)
|String
|Required

|`withData`
|Returns case instance data when set to `true` (default: `false`)
|Boolean
|Optional

|`withRoles`
|Returns case instance user and group roles when set to `true` (default: `false`)
|Boolean
|Optional

|`withMilestones`
|Returns case instance milestones when set to `true` (default: `false`)
|Boolean
|Optional

|`withStages`
|Returns case instance stages when set to `true` (default: `false`)
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006?withData=true&withRoles=true&withMilestones=false&withStages=false
----

.Example server response (JSON)
[source,json]
----
{
  "case-id": "IT-0000000006",
  "case-description": "Order for IT hardware",
  "case-owner": "baAdmin",
  "case-status": 1,
  "case-definition-id": "itorders.orderhardware",
  "container-id": "itorders_1.0.0-SNAPSHOT",
  "case-started-at": 1540474204152,
  "case-completed-at": null,
  "case-completion-msg": "",
  "case-sla-compliance": 0,
  "case-sla-due-date": null,
  "case-file": {
    "case-data": {},
    "case-user-assignments": {},
    "case-group-assignments": {},
    "case-data-restrictions": {}
  },
  "case-milestones": null,
  "case-stages": null,
  "case-roles": [
    {
      "name": "owner",
      "users": [
        "baAdmin"
      ],
      "groups": []
    },
    {
      "name": "manager",
      "users": [
        "baAdmin"
      ],
      "groups": []
    },
    {
      "name": "supplier",
      "users": [],
      "groups": [
        "IT"
      ]
    }
  ]
}
----

== [POST] /server/containers/{containerId}/cases/instances/{caseId}

Closes a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance to be closed (example: `IT-0000000006`)
|String
|Required

|*body*
|Optional comment as a String entry (example: `"Updated case with new ad hoc fragment."`)
|String
|Optional
|===

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Case IT-0000000006 successfully closed."
    }
  ]
}
----

== [POST] /server/containers/{containerId}/cases/{caseDefId}/instances/{caseId}

Reopens a closed case instance for a specified case definition.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseDefId`
|ID of the case definition for which you are reopening the case instance
|String
|Required

|`caseId`
|ID of the case instance to be reopened (example: `IT-0000000006`)
|String
|Required

|*body*
|Optional map containing a case file specification (`"caseFile_hwSpec": "#{caseFile_hwSpec}"`), case user or case group role assignments (`case-user-assignments`), or any other components of the reopened case instance
|Request body
|Optional
|===

.Example request body (JSON)
[source,json]
----
{
  "case-data": {},
  "caseFile_hwSpec": "#{caseFile_hwSpec}",
  "case-user-assignments": {
    "owner": "cami",
    "manager": "cami"
  },
  "case-group-assignments": {
    "supplier": "IT"
  }
}
----

*<@Maciej/@Tiho: The server responds with only the new case ID (example: IT-0000000007). It should respond more fully and say something like the response below.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Case instance IT-0000000006 successfully reopened."
    }
  ]
}
----

== [DELETE] /server/containers/{containerId}/cases/instances/{caseId}

Aborts or permanently destroys a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance to be closed (example: `IT-0000000006`)
|String
|Required

|`destroy`
|Permanently destroys the case instance when set to `true` (default: `false`)
|Boolean
|Optional
|===

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Case IT-0000000006 successfully destroyed."
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/{caseDefId}/instances

Returns case instances for a specified case definition.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instances reside
|String
|Required

|`caseDefId`
|ID of the case definition for which you are retrieving case instances
|String
|Required

|`status`
|Open (`1`), closed (`2`), or cancelled (`3`) case instances (default: `1`, open)
|Array [integer]
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/itorders.orderhardware/instances?page=0&pageSize=10&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "instances": [
    {
      "case-id": "IT-0000000006",
      "case-description": "Order for IT hardware",
      "case-owner": "baAdmin",
      "case-status": 1,
      "case-definition-id": "itorders.orderhardware",
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "case-started-at": 1540474204152,
      "case-completed-at": null,
      "case-completion-msg": "",
      "case-sla-compliance": 0,
      "case-sla-due-date": null,
      "case-file": null,
      "case-milestones": null,
      "case-stages": null,
      "case-roles": null
    }
  ]
}
----

== [POST] /server/containers/{containerId}/cases/{caseDefId}/instances

Starts a new case instance for a specified case definition.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instances reside
|String
|Required

|`caseDefId`
|ID of the case definition for which you are starting a case instance
|String
|Required

|*body*
|Optional map containing a case file specification (`"caseFile_hwSpec": "#{caseFile_hwSpec}"`), case user or case group role assignments (`case-user-assignments`), or any other components of the new case instance
|Request body
|Optional
|===

.Example request body (JSON)
[source,json]
----
{
  "case-data": {},
  "caseFile_hwSpec": "#{caseFile_hwSpec}",
  "case-user-assignments": {
    "owner": "cami",
    "manager": "cami"
  },
  "case-group-assignments": {
    "supplier": "IT"
  }
}
----

*<@Maciej/@Tiho: The server responds with only the new case ID (example: IT-0000000007). It should respond more fully and say something like the response below.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Case instance IT-0000000007 successfully created."
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/instances/{caseId}/milestones

Returns milestones for a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are retrieving milestones (example: `IT-0000000006`)
|String
|Required

|`achievedOnly`
|Returns only achieved milestones when set to `true` (default: `true`)
|Boolean
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/milestones?achievedOnly=false&page=0&pageSize=10
----

.Example server response (JSON)
[source,json]
----
{
  "milestones": [
    {
      "milestone-name": "Milestone 1: Order placed",
      "milestone-id": "1",
      "milestone-achieved": false,
      "milestone-achieved-at": null,
      "milestone-status": "Available"
    },
    {
      "milestone-name": "Hardware spec ready",
      "milestone-id": "2",
      "milestone-achieved": false,
      "milestone-achieved-at": null,
      "milestone-status": "Available"
    },
    {
      "milestone-name": "Manager decision",
      "milestone-id": "3",
      "milestone-achieved": false,
      "milestone-achieved-at": null,
      "milestone-status": "Available"
    },
    {
      "milestone-name": "Milestone 2: Order shipped",
      "milestone-id": "_343B90CD-AA19-4894-B63C-3CE1906E6FD1",
      "milestone-achieved": false,
      "milestone-achieved-at": null,
      "milestone-status": "Available"
    },
    {
      "milestone-name": "Milestone 3: Delivered to customer",
      "milestone-id": "_52AFA23F-C087-4519-B8F2-BABCC31D68A6",
      "milestone-achieved": false,
      "milestone-achieved-at": null,
      "milestone-status": "Available"
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/instances/{caseId}/stages

Returns milestones for a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instances reside
|String
|Required

|`caseId`
|ID of the case instance for which you are retrieving stages (example: `IT-0000000006`)
|String
|Required

|`activeOnly`
|Returns only active stages when set to `true` (default: `true`)
|Boolean
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT5/cases/instances/IT-0000000006/stages?activeOnly=false&page=0&pageSize=10
----

*<@Maciej/@Tiho: Example JSON response, instead of the generic sample below. I'm struggling to create working example stages.>*

.Example server response (JSON)
[source,json]
----
{
  "stages": [
    {
      "stage-name": "string",
      "stage-id": "string",
      "stage-status": "string",
      "adhoc-fragments": [
        {
          "name": "string",
          "type": "string"
        }
      ],
      "active-nodes": [
        {
          "node-instance-id": 0,
          "node-name": "string",
          "process-instance-id": 0,
          "work-item-id": 0,
          "container-id": "string",
          "start-date": "2018-10-25T18:34:44.456Z",
          "node-id": "string",
          "node-type": "string",
          "node-connection": "string",
          "node-completed": true,
          "reference-id": 0,
          "sla-compliance": 0,
          "sla-due-date": "2018-10-25T18:34:44.456Z"
        }
      ]
    }
  ]
}
----

== [POST] /server/containers/{containerId}/cases/instances/{caseId}/tasks/{nodeName}

Triggers a specified ad hoc fragment in a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance associated with the ad hoc fragment (example: `IT-0000000006`)
|String
|Required

|`nodeName`
|Name of the ad hoc fragment node within the case instance to be triggered (example: `Prepare hardware spec`)
|String
|Required

|*body*
|Optional map containing updated case data when triggering the ad hoc fragment (such as transferal of case ownership to a specified user or group)
|Request body
|Optional
|===

.Example POST endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/tasks/Prepare%20hardware%20spec
----

.Example request body (JSON)
[source,json]
----
{
  "case-data": {},
  "caseFile_hwSpec": "#{caseFile_hwSpec}",
  "case-user-assignments": {
    "owner": "cami",
    "manager": "cami"
  },
  "case-group-assignments": {
    "supplier": "IT"
  }
}
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Node `Prepare hardware spec` successfully triggered."
    }
  ]
}
----

== [POST] /server/containers/{containerId}/cases/instances/{caseId}/stages/{caseStageId}/tasks/{nodeName}

Triggers a specified ad hoc fragment in the specified stage of a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance associated with the ad hoc fragment (example: `IT-0000000006`)
|String
|Required

|`caseStageId`
|ID of the stage of the case instance containing the ad hoc fragment to be triggered (example: `Order delivery`)
|String
|Required

|`nodeName`
|Name of the ad hoc fragment node within the stage of the case instance to be triggered (example: `Prepare hardware spec`)
|String
|Required

|*body*
|Optional map containing updated case data when triggering the ad hoc fragment (such as transferal of case ownership to a specified user or group)
|Request body
|Optional
|===

.Example POST endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/stages/Order%20delivery/tasks/Prepare%20hardware%20spec
----

.Example request body (JSON)
[source,json]
----
{
  "case-data": {},
  "caseFile_hwSpec": "#{caseFile_hwSpec}",
  "case-user-assignments": {
    "owner": "cami",
    "manager": "cami"
  },
  "case-group-assignments": {
    "supplier": "IT"
  }
}
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Node `Prepare hardware spec` successfully triggered."
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/instances/{caseId}/comments

Returns comments from a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are retrieving comments (example: `IT-0000000006`)
|String
|Required

|`sort`
|Sort column for results
|String
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT6/cases/instances/IT-0000000006/comments?page=0&pageSize=10
----

.Example server response (JSON)
[source,json]
----
{
  "comments": [
    {
      "id": "f15419b6-1967-479b-8509-066f579c59e1",
      "author": "baAdmin",
      "text": "Updated case with new ad hoc fragment.",
      "added-at": {
        "java.util.Date": 1540494739762
      },
      "restricted-to": [
        "owner"
      ]
    }
      {
        "id": "2b072823-7448-4819-9560-01165bc7e805",
        "author": "baAdmin",
        "text": "Removed hardware preparation requirement.",
        "added-at": {
          "java.util.Date": 1540494802456
        },
        "restricted-to": [
          "supplier"
        ]
    }
  ]
}
----

== [POST] /server/containers/{containerId}/cases/instances/{caseId}/comments

Adds a comment to a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance to be updated (example: `IT-0000000006`)
|String
|Required

|`author`
|User name of the comment author
|String
|Optional

|`restrictedTo`
|User or group roles permitted to view the comment (such as `owner`, `manager`, or `supplier`)
|String
|Optional

|*body*
|Case instance comment as a String entry
|String
|Required
|===

.Example POST endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/comments?author=baAdmin&restrictedTo=owner
----

.Example request body (JSON)
[source,json]
----
"Updated case with new ad hoc fragment."
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Comment 2b072823-7448-4819-9560-01165bc7e805 successfully added to case instance."
    }
  ]
}
----

== [PUT] /server/containers/{containerId}/cases/instances/{caseId}/comments/{caseCommentId}

Updates a specified comment in a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance to be updated (example: `IT-0000000006`)
|String
|Required

|`caseCommentId`
|ID of the case instance comment to be updated (example: `2b072823-7448-4819-9560-01165bc7e805`)
|String
|Required

|`author`
|User name of the comment author
|String
|Optional

|`restrictedTo`
|User or group roles permitted to view the comment (such as `owner`, `manager`, or `supplier`)
|String
|Optional

|*body*
|Updated case instance comment as a String entry
|String
|Required
|===

.Example POST endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/comments/2b072823-7448-4819-9560-01165bc7e805?author=baAdmin&restrictedTo=owner
----

.Example request body (JSON)
[source,json]
----
"Updated case with new stage."
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Comment 2b072823-7448-4819-9560-01165bc7e805 successfully updated."
    }
  ]
}
----

== [DELETE] /server/containers/{containerId}/cases/instances/{caseId}/comments/{caseCommentId}

Deletes a specified comment in a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance to be updated (example: `IT-0000000006`)
|String
|Required

|`caseCommentId`
|ID of the case instance comment to be deleted (example: `2b072823-7448-4819-9560-01165bc7e805`)
|String
|Required
|===

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Comment 2b072823-7448-4819-9560-01165bc7e805 successfully deleted."
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/instances/{caseId}/caseFile

Returns data from the case files of a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are retrieving case file data (example: `IT-0000000006`)
|String
|Required

|`name`
|One or more data item names to be retrieved (example: `hwSpec`)
|Array [string]
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/caseFile?name=milestone-id&name=hwSpec&name=milestone-name&name=name
----

.Example server response (JSON)
[source,json]
----
{
  "milestone-id": "_DCD97847-6E3C-4C5E-9EE3-221C04BE42ED",
  "hwSpec": "This is my case file.",
  "milestone-name": "Milestone 1: Order placed",
  "name": "Prepare hardware spec"
}
----

== [POST] /server/containers/{containerId}/cases/instances/{caseId}/caseFile

Adds data as case files in a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are adding case file data (example: `IT-0000000006`)
|String
|Required

|`restrictedTo`
|User or group roles permitted to view the data (such as `owner`, `manager`, or `supplier`)
|String
|Optional

|*body*
|Map containing case file data in a `key: value` format
|Request body
|Required
|===

*<@Maciej/@Tiho: Is this example request okay? It works, but not sure it's typical or what it should be.>*

.Example request body (JSON)
[source,json]
----
{
  "milestone-id": "_DCD97847-6E3C-4C5E-9EE3-221C04BE42ED",
  "hwSpec": "This is my case file.",
  "milestone-name": "Milestone 1: Order placed",
  "name": "Prepare hardware spec"
}
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Case files successfully added."
    }
  ]
}
----

== [DELETE] /server/containers/{containerId}/cases/instances/{caseId}/caseFile

Deletes one or more specified case file data items from a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are deleting case file data (example: `IT-0000000006`)
|String
|Required

|`dataId`
|One or more data item names to be deleted from the case file (example: `hwSpec`)
|Array [string]
|Required
|===

.Example DELETE endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/caseFile?dataId=milestone-name
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Case file data successfully deleted."
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/instances/{caseId}/caseFile/{dataId}

Returns the value of a specified case file data item in a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance from which you are retrieving a case file data item (example: `IT-0000000006`)
|String
|Required

|`dataId`
|Data item name to be retrieved from the case file
|Array [string]
|Required
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/caseFile/hwSpec
----

.Example server response (JSON)
[source,json]
----
"Content from hardware specification (`hwSpec`) case file."
----

== [POST] /server/containers/{containerId}/cases/instances/{caseId}/caseFile/{dataId}

Adds a single data item as a case file in a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are adding a case file data item (example: `IT-0000000006`)
|String
|Required

|`dataId`
|Data item name to be added as a case file
|String
|Required

|`restrictedTo`
|User or group roles permitted to view the data item (such as `owner`, `manager`, or `supplier`)
|String
|Optional

|*body*
|Data item content of any type
|Request body
|Required
|===

.Example POST endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/caseFile/hwSpecNew?restrictedTo=owner
----

.Example request body (JSON)
[source,json]
----
"New content for hardware specification (`hwSpec`) case file."
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Case file successfully added."
    }
  ]
}
----

== [POST] /server/containers/{containerId}/cases/instances/{caseId}/tasks

Adds a dynamic user task or service task to the specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance to which you are adding a dynamic task (example: `IT-0000000006`)
|String
|Required

|*body*
|Map containing the dynamic task `name`, `subject`, `actors`, and other components of the new task
|Request body
|Required
|===

.Example POST endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/caseFile/hwSpecNew?restrictedTo=owner
----

.Example request body (JSON)
[source,json]
----
{
  "name": "RequestManagerApproval",
  "data": {
    "reason": "Fixed hardware spec",
    "caseFile_hwSpec": "#{caseFile_hwSpec}"
  },
  "subject": "Ask for manager approval again",
  "actors": "manager",
  "groups": ""
}
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Task successfully created."
    }
  ]
}
----

== [POST] /server/containers/{containerId}/cases/instances/{caseId}/stages/{caseStageId}/tasks

Adds a dynamic user task or service task to the specified stage in a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance to which you are adding a dynamic task (example: `IT-0000000006`)
|String
|Required

|`caseStageId`
|ID of the stage of the case instance to which you are adding a dynamic task (example: `Order delivery`)
|String
|Required

|*body*
|Map containing the dynamic task `name`, `subject`, `actors`, and other components of the new task
|Request body
|Required
|===

.Example POST endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/stages/Order%20delivery/tasks
----

.Example request body (JSON)
[source,json]
----
{
  "name": "RequestManagerApproval",
  "data": {
    "reason": "Fixed hardware spec",
    "caseFile_hwSpec": "#{caseFile_hwSpec}"
  },
  "subject": "Ask for manager approval again",
  "actors": "manager",
  "groups": ""
}
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Task successfully created."
    }
  ]
}
----

== [POST] /server/containers/{containerId}/cases/instances/{caseId}/stages/{caseStageId}/processes/{processId}

Adds a dynamic sub-process to the specified stage in a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance to which you are adding a dynamic sub-process (example: `IT-0000000006`)
|String
|Required

|`caseStageId`
|ID of the stage of the case instance to which you are adding a dynamic task (example: `Order delivery`)
|String
|Required

|`processId`
|ID of the sub-process to be added to the stage of the case instance (example: `itorders-data.place-order`)
|String
|Required

|*body*
|Map containing the dynamic sub-process data
|Request body
|Required
|===

.Example POST endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/stages/Order%20delivery/processes/itorders-data.place-order
----

.Example request body (JSON)
[source,json]
----
{
 "placedOrder" : "Manually"
}
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "subprocess itorders-data.place-order successfully added to stage."
    }
  ]
}
----

== [POST] /server/containers/{containerId}/cases/instances/{caseId}/processes/{processId}

Adds a dynamic sub-process to a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance to which you are adding a dynamic sub-process (example: `IT-0000000006`)
|String
|Required

|`processId`
|ID of the sub-process to be added to the case instance (example: `itorders-data.place-order`)
|String
|Required

|*body*
|Map containing the dynamic sub-process data
|Request body
|Required
|===

.Example POST endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/stages/Order%20delivery/processes/itorders-data.place-order
----

.Example request body (JSON)
[source,json]
----
{
 "placedOrder" : "Manually"
}
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "subprocess itorders-data.place-order successfully added to case instance."
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/instances/{caseId}/adhocfragments

Returns ad hoc fragments for a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are retrieving ad hoc fragments (example: `IT-0000000006`)
|String
|Required
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/adhocfragments
----

.Example server response (JSON)
[source,json]
----
{
  "fragments": [
    {
      "name": "Prepare hardware spec",
      "type": "HumanTaskNode"
    },
    {
      "name": "Milestone 1: Order placed",
      "type": "MilestoneNode"
    },
    {
      "name": "Milestone 2: Order shipped",
      "type": "MilestoneNode"
    },
    {
      "name": "Milestone 3: Delivered to customer",
      "type": "MilestoneNode"
    },
    {
      "name": "Hardware spec ready",
      "type": "MilestoneNode"
    },
    {
      "name": "Manager decision",
      "type": "MilestoneNode"
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/instances/{caseId}/processes/instances

Returns process instances in a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are retrieving process instances (example: `IT-0000000006`)
|String
|Required

|`status`
|Active (`1`), completed (`2`), or aborted (`3`) process instances (default: `1`, active)
|Array [integer]
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/processes/instances?page=0&pageSize=10&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "process-instance": [
    {
      "process-instance-id": 26,
      "process-id": "itorders.orderhardware",
      "process-name": "Order for IT hardware",
      "process-version": "1.0",
      "process-instance-state": 1,
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "initiator": "baAdmin",
      "start-date": {
        "java.util.Date": 1540474204152
      },
      "process-instance-desc": "Order for IT hardware",
      "correlation-key": "IT-0000000006",
      "parent-instance-id": -1,
      "sla-compliance": 0,
      "sla-due-date": null,
      "active-user-tasks": null,
      "process-instance-variables": null
    },
    {
      "process-instance-id": 34,
      "process-id": "itorders-data.place-order",
      "process-name": "place-order",
      "process-version": "1.0",
      "process-instance-state": 1,
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "initiator": "baAdmin",
      "start-date": {
        "java.util.Date": 1540504523492
      },
      "process-instance-desc": "Order IT-0000000006",
      "correlation-key": "IT-0000000006:itorders-data.place-order:1540504523491",
      "parent-instance-id": 26,
      "sla-compliance": 0,
      "sla-due-date": null,
      "active-user-tasks": null,
      "process-instance-variables": null
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/instances/{caseId}/nodes/instances

Returns node instances for a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are retrieving node instances (example: `IT-0000000006`)
|String
|Required

|`completed`
|Returns only completed nodes when set to `true` (default: `false`)
|Boolean
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000006/nodes/instances?completed=false&page=0&pageSize=10
----

.Example server response (JSON)
[source,json]
----
{
  "node-instance": [
    {
      "node-instance-id": 0,
      "node-name": "Prepare hardware spec",
      "process-instance-id": 26,
      "work-item-id": 35,
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "start-date": {
        "java.util.Date": 1540474204152
      },
      "node-id": "_BFA6002D-0917-42CE-81AD-2A15EC814684",
      "node-type": "HumanTaskNode",
      "node-connection": null,
      "node-completed": false,
      "reference-id": null,
      "sla-compliance": 0,
      "sla-due-date": null
    },
    {
      "node-instance-id": 1,
      "node-name": "Milestone 1: Order placed",
      "process-instance-id": 26,
      "work-item-id": null,
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "start-date": {
        "java.util.Date": 1540474204156
      },
      "node-id": "_DCD97847-6E3C-4C5E-9EE3-221C04BE42ED",
      "node-type": "MilestoneNode",
      "node-connection": null,
      "node-completed": false,
      "reference-id": null,
      "sla-compliance": 0,
      "sla-due-date": null
    },
    {
      "node-instance-id": 3,
      "node-name": "Manager decision",
      "process-instance-id": 26,
      "work-item-id": null,
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "start-date": {
        "java.util.Date": 1540474204156
      },
      "node-id": "_79953D58-25DB-4FD6-94A0-DFC6EA2D0339",
      "node-type": "MilestoneNode",
      "node-connection": null,
      "node-completed": false,
      "reference-id": null,
      "sla-compliance": 0,
      "sla-due-date": null
    },
    {
      "node-instance-id": 4,
      "node-name": "Prepare hardware spec",
      "process-instance-id": 26,
      "work-item-id": 41,
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "start-date": {
        "java.util.Date": 1540492717247
      },
      "node-id": "_BFA6002D-0917-42CE-81AD-2A15EC814684",
      "node-type": "HumanTaskNode",
      "node-connection": null,
      "node-completed": false,
      "reference-id": null,
      "sla-compliance": 0,
      "sla-due-date": null
    },
    {
      "node-instance-id": 5,
      "node-name": "[Dynamic] RequestManagerApproval",
      "process-instance-id": 26,
      "work-item-id": 45,
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "start-date": {
        "java.util.Date": 1540502553944
      },
      "node-id": "0",
      "node-type": "Human Task",
      "node-connection": null,
      "node-completed": false,
      "reference-id": null,
      "sla-compliance": 0,
      "sla-due-date": null
    },
    {
      "node-instance-id": 6,
      "node-name": "[Dynamic] Sub Process",
      "process-instance-id": 26,
      "work-item-id": null,
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "start-date": {
        "java.util.Date": 1540504523490
      },
      "node-id": "0",
      "node-type": "SubProcessNode",
      "node-connection": null,
      "node-completed": false,
      "reference-id": 34,
      "sla-compliance": 0,
      "sla-due-date": null
    },
    {
      "node-instance-id": 1,
      "node-name": "Place order",
      "process-instance-id": 34,
      "work-item-id": 46,
      "container-id": "itorders_1.0.0-SNAPSHOT",
      "start-date": {
        "java.util.Date": 1540504523493
      },
      "node-id": "_FCADC388-8A68-40E1-94A7-4F8A7D2B21C2",
      "node-type": "HumanTaskNode",
      "node-connection": "_384EFF84-BB14-4917-89C3-32DF4ACA1878",
      "node-completed": false,
      "reference-id": null,
      "sla-compliance": 0,
      "sla-due-date": null
    }
  ]
}
----

== [GET] /server/containers/{containerId}/cases/instances/{caseId}/roles

Returns role assignments for a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are retrieving role assignments (example: `IT-0000000006`)
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "role-assignments": [
    {
      "name": "owner",
      "users": [
        "baAdmin"
      ],
      "groups": []
    },
    {
      "name": "manager",
      "users": [
        "baAdmin"
      ],
      "groups": []
    },
    {
      "name": "supplier",
      "users": [],
      "groups": [
        "IT"
      ]
    }
  ]
}
----

== [PUT] /server/containers/{containerId}/cases/instances/{caseId}/roles/{caseRoleName}

Assigns a specified case role to a specified user and group for a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are assigning roles (example: `IT-0000000006`)
|String
|Required

|`caseRoleName`
|Name of the case role to be assigned (such as `owner`, `manager`, or `supplier`)
|String
|Required

|`user`
|Name of the user to whom the case role will be assigned
|String
|Required

|`group`
|Name of the group to whom the case role will be assigned
|String
|Required
|===

*<@Maciej/@Tiho: Both `user` and `group` are required, but it should be one or the other or optionally both, right? And same with the DELETE endpoint. Some roles, like `owner` and `manager`, support only one user, so this request fails when you supply both a user and group to be assigned. Note that for task instances, we use a single `entityId` parameter, where you can supply a comma-separated list of names (user or group, in this case).>*

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000007/roles/supplier?user=baAdmin&group=IT
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Case role successfully assigned."
    }
  ]
}
----

== [DELETE] /server/containers/{containerId}/cases/instances/{caseId}/roles/{caseRoleName}

Removes an assigned case role from a specified user and group for a specified case instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`containerId`
|ID of the KIE container where the case instance is located
|String
|Required

|`caseId`
|ID of the case instance for which you are removing assigned roles (example: `IT-0000000006`)
|String
|Required

|`caseRoleName`
|Name of the case role to be removed (such as `owner`, `manager`, or `supplier`)
|String
|Required

|`user`
|Name of the user to whom the case role will be unassigned
|String
|Required

|`group`
|Name of the group to whom the case role will be unassigned
|String
|Required
|===

.Example DELETE endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/containers/itorders_1.0.0-SNAPSHOT/cases/instances/IT-0000000007/roles/supplier?user=baAdmin&group=IT
----

*<@Maciej/@Tiho: The request works but the server responds "undocumented". Need to update the server so that it responds with the following, or similar.>*

.Example server response (JSON)
[source,json]
----
{
  "response": [
    {
      "type": "SUCCESS",
      "msg": "Case role successfully removed from assigned user or group."
    }
  ]
}
----
