// To reuse this module, ifeval the title to be more specific as needed.

[id='kie-server-rest-api-task-queries-ref_{context}']
= Task queries

// The {KIE_SERVER} REST API supports the following endpoints for querying task instances. The {KIE_SERVER} REST API base URL is `\http://SERVER:PORT/kie-server/services/rest/`. All requests require HTTP Basic authentication or token-based authentication for the `kie-server` user role.

== [GET] /server/queries/tasks/instances/pot-owners

Returns tasks with a user defined as a potential owner.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`status`
|Task status (such as `Created`, `InProgress`, `Completed`)
|Array [string]
|Optional

|`groups`
|One or more group names
|Array [string]
|Optional

|`user`
|User ID to be used for the query instead of an authenticated user (only when bypass authenticated user is enabled with system property `org.kie.server.bypass.auth.user` set to `true`)
|String
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional

|`filter`
|Custom filter for task data
|String
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/queries/tasks/instances/pot-owners?groups=&user=John&page=0&pageSize=10&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "task-summary": [
    {
      "task-id": "2",
      "task-name": "Self Evaluation",
      "task-subject": "",
      "task-description": "Please perform a self-evalutation.",
      "task-status": "Ready",
      "task-priority": "0",
      "task-is-skippable": "false",
      "task-created-by": "John",
      "task-created-on": "2016-04-05T15:09:14.206+02:00",
      "task-activation-time": "2016-04-05T15:09:14.206+02:00",
      "task-proc-inst-id": "2",
      "task-proc-def-id": "evaluation",
      "task-container-id": "myContainer",
      "task-parent-id": "-1"
    },
    {
      "task-id": "1",
      "task-name": "Self Evaluation",
      "task-subject": "",
      "task-description": "Please perform a self-evalutation.",
      "task-status": "InProgress",
      "task-priority": "0",
      "task-is-skippable": "false",
      "task-actual-owner": "kiesu",
      "task-created-by": "John",
      "task-created-on": "2016-04-05T15:05:06.508+02:00",
      "task-activation-time": "2016-04-05T15:05:06.508+02:00",
      "task-proc-inst-id": "1",
      "task-proc-def-id": "evaluation",
      "task-container-id": "myContainer",
      "task-parent-id": "-1"
    }
  ]
}
----

== [GET] /server/queries/tasks/instances/admins

Returns task instances assigned to business administrators.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`status`
|Task status (such as `Created`, `InProgress`, `Completed`)
|Array [string]
|Optional

|`user`
|User ID to be used for the query instead of an authenticated user (only when bypass authenticated user is enabled with system property `org.kie.server.bypass.auth.user` set to `true`)
|String
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/queries/tasks/instances/admins?user=John&page=0&pageSize=10&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "task-summary": [
    {
      "task-id": "2",
      "task-name": "Self Evaluation",
      "task-subject": "",
      "task-description": "Please perform a self-evalutation.",
      "task-status": "Ready",
      "task-priority": "0",
      "task-is-skippable": "false",
      "task-created-by": "John",
      "task-created-on": "2016-04-05T15:09:14.206+02:00",
      "task-activation-time": "2016-04-05T15:09:14.206+02:00",
      "task-proc-inst-id": "2",
      "task-proc-def-id": "evaluation",
      "task-container-id": "myContainer",
      "task-parent-id": "-1"
    }
  ]
}
----

== [GET] /server/queries/tasks/instances/owners

Returns task instances that the querying user owns.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`status`
|Task status (such as `Created`, `InProgress`, `Completed`)
|Array [string]
|Optional

|`user`
|User ID to be used for the query instead of an authenticated user (only when bypass authenticated user is enabled with system property `org.kie.server.bypass.auth.user` set to `true`)
|String
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/queries/tasks/instances/owners?page=0&pageSize=10&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "task-summary": [
    {
      "task-id": "2",
      "task-name": "Self Evaluation",
      "task-subject": "",
      "task-description": "Please perform a self-evalutation.",
      "task-status": "Ready",
      "task-priority": "0",
      "task-is-skippable": "false",
      "task-created-by": "Jane",
      "task-created-on": "2016-04-05T15:09:14.206+02:00",
      "task-activation-time": "2016-04-05T15:09:14.206+02:00",
      "task-proc-inst-id": "2",
      "task-proc-def-id": "evaluation",
      "task-container-id": "myContainer",
      "task-parent-id": "-1"
    }
  ]
}
----

== [GET] /server/queries/tasks/instances

Returns all task instances.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`user`
|User ID to be used for the query instead of an authenticated user (only when bypass authenticated user is enabled with system property `org.kie.server.bypass.auth.user` set to `true`)
|String
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/queries/tasks/instances?user=John&page=0&pageSize=10&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "task-summary": [
    {
      "task-id": "2",
      "task-name": "Self Evaluation",
      "task-subject": "",
      "task-description": "Please perform a self-evalutation.",
      "task-status": "Ready",
      "task-priority": "0",
      "task-is-skippable": "false",
      "task-created-by": "John",
      "task-created-on": "2016-04-05T15:09:14.206+02:00",
      "task-activation-time": "2016-04-05T15:09:14.206+02:00",
      "task-proc-inst-id": "2",
      "task-proc-def-id": "evaluation",
      "task-container-id": "myContainer",
      "task-parent-id": "-1"
    },
    {
      "task-id": "1",
      "task-name": "Self Evaluation",
      "task-subject": "",
      "task-description": "Please perform a self-evalutation.",
      "task-status": "InProgress",
      "task-priority": "0",
      "task-is-skippable": "false",
      "task-actual-owner": "kiesu",
      "task-created-by": "John",
      "task-created-on": "2016-04-05T15:05:06.508+02:00",
      "task-activation-time": "2016-04-05T15:05:06.508+02:00",
      "task-proc-inst-id": "1",
      "task-proc-def-id": "evaluation",
      "task-container-id": "myContainer",
      "task-parent-id": "-1"
    }
  ]
}
----

== [GET] /server/queries/tasks/instances/{taskInstanceId}/events

Returns events for a specified task instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`taskInstanceId`
|ID of the task instance for which you are retrieving events
|Integer
|Required

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/queries/tasks/instances/4/events?page=0&pageSize=10&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "task-event-instance": [
    {
      "task-event-id": 4,
      "task-id": 4,
      "task-event-type": "STARTED",
      "task-event-user": "Mortgage_Process.MortgageApprovalProcess",
      "task-event-date": {
        "java.util.Date": 1539623679130
      },
      "task-process-instance-id": 4,
      "task-work-item-id": 4,
      "task-event-message": null
    }
  ]
}
----

== [GET] /server/queries/tasks/instances/{taskInstanceId}

Returns information about a specified task instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`taskInstanceId`
|ID of the task instance to be retrieved
|Integer
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "task-id": 1,
  "task-priority": 0,
  "task-name": "Self Evaluation",
  "task-subject": null,
  "task-description": "Please perform a self-evalutation.",
  "task-type": null,
  "task-form": null,
  "task-status": "Ready",
  "task-actual-owner": "kiesu",
  "task-created-by": "Jane",
  "task-created-on": {
    "java.util.Date": 1539623679113
  },
  "task-activation-time": {
    "java.util.Date": 1539623679113
  },
  "task-expiration-time": null,
  "task-skippable": null,
  "task-workitem-id": null,
  "task-process-instance-id": 4,
  "task-parent-id": null,
  "task-process-id": "Mortgage_Process.MortgageApprovalProcess",
  "task-container-id": "mortgage-process_1.0.0-SNAPSHOT",
  "task-pot-owners": "Jane",
  "task-excl-owners": null,
  "task-business-admins": "John",
  "task-input-data": null,
  "task-output-data": null
}
----

== [GET] /server/queries/tasks/instances/workitem/{workItemId}

Returns task instances with a specified work item.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`workItemId`
|ID of the work item by which you are retrieving task instances
|Integer
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "task-id": 1,
  "task-priority": 0,
  "task-name": "Self Evaluation",
  "task-subject": null,
  "task-description": "Please perform a self-evalutation.",
  "task-type": null,
  "task-form": null,
  "task-status": "Ready",
  "task-actual-owner": "kiesu",
  "task-created-by": "Jane",
  "task-created-on": {
    "java.util.Date": 1539623679113
  },
  "task-activation-time": {
    "java.util.Date": 1539623679113
  },
  "task-expiration-time": null,
  "task-skippable": null,
  "task-workitem-id": null,
  "task-process-instance-id": 4,
  "task-parent-id": null,
  "task-process-id": "Mortgage_Process.MortgageApprovalProcess",
  "task-container-id": "mortgage-process_1.0.0-SNAPSHOT",
  "task-pot-owners": "Jane",
  "task-excl-owners": null,
  "task-business-admins": "John",
  "task-input-data": null,
  "task-output-data": null
}
----

== [GET] /server/queries/tasks/instances/process/{processInstanceId}

Returns task instances associated with a specified process instance.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`processInstanceId`
|ID of the process instance for which you are retrieving task instances
|Integer
|Required

|`status`
|Task status (such as `Created`, `InProgress`, `Completed`)
|Array [string]
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/queries/tasks/instances/process/6?page=0&pageSize=10&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "task-summary": [
    {
      "task-id": 10,
      "task-name": "Qualify",
      "task-subject": "",
      "task-description": "",
      "task-status": "Ready",
      "task-priority": 0,
      "task-is-skippable": false,
      "task-actual-owner": null,
      "task-created-by": null,
      "task-created-on": {
        "java.util.Date": 1539811220726
      },
      "task-activation-time": {
        "java.util.Date": 1539811220726
      },
      "task-expiration-time": null,
      "task-proc-inst-id": 6,
      "task-proc-def-id": "Mortgage_Process.MortgageApprovalProcess",
      "task-container-id": "mortgage-process_1.0.0-SNAPSHOT",
      "task-parent-id": -1
    }
  ]
}
----

== [GET] /server/queries/tasks/instances/variables/{variableName}

Returns task instances with a specified variable.

.Request parameters
[cols="25%,45%,15%,15%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`variableName`
|Name of the variable by which you are retrieving task instances
|String
|Required

|`varValue`
|Full variable value (example, `baAdmin`) or wildcard variable value (example, `ba%`) by which you are filtering results
|String
|Optional

|`status`
|Task status (such as `Created`, `InProgress`, `Completed`)
|Array [string]
|Optional

|`page`
|Page number at which to start (default: `0`)
|Integer
|Optional

|`pageSize`
|Number or results per page (default: `10`)
|Integer
|Optional

|`sort`
|Sort column for results
|String
|Optional

|`sortOrder`
|Ascending (`true`) or descending (`false`) sort order for results
|Boolean
|Optional
|===

.Example GET endpoint with parameters
[source]
----
http://localhost:8080/kie-server/services/rest/server/queries/tasks/instances/variables/initiator?varValue=ba%25&page=0&pageSize=10&sortOrder=true
----

.Example server response (JSON)
[source,json]
----
{
  "task-summary": [
    {
      "task-id": "2",
      "task-name": "Self Evaluation",
      "task-subject": "",
      "task-description": "Please perform a self-evalutation.",
      "task-status": "Ready",
      "task-priority": "0",
      "task-is-skippable": "false",
      "task-created-by": "John",
      "task-created-on": "2016-04-05T15:09:14.206+02:00",
      "task-activation-time": "2016-04-05T15:09:14.206+02:00",
      "task-proc-inst-id": "2",
      "task-proc-def-id": "evaluation",
      "task-container-id": "myContainer",
      "task-parent-id": "-1"
    },
    {
      "task-id": "1",
      "task-name": "Self Evaluation",
      "task-subject": "",
      "task-description": "Please perform a self-evalutation.",
      "task-status": "InProgress",
      "task-priority": "0",
      "task-is-skippable": "false",
      "task-actual-owner": "kiesu",
      "task-created-by": "John",
      "task-created-on": "2016-04-05T15:05:06.508+02:00",
      "task-activation-time": "2016-04-05T15:05:06.508+02:00",
      "task-proc-inst-id": "1",
      "task-proc-def-id": "evaluation",
      "task-container-id": "myContainer",
      "task-parent-id": "-1"
    }
  ]
}
----
