[id='performance-tuning-kie-server-ref_{context}']

= Performance tuning considerations with {KIE_SERVER}

The following key concepts or suggested practices can help you optimize {KIE_SERVER} performance. These concepts are summarized in this section as a convenience and are explained in more detail in the cross-referenced documentation, where applicable. This section will expand or change as needed with new releases of {PRODUCT}.

Ensure that development mode is enabled during development::
You can set {KIE_SERVER} or specific projects in {CENTRAL} to use `production` mode or `development` mode. By default, {KIE_SERVER} and all new projects in {CENTRAL} are in development mode. This mode provides features that facilitate your development experience, such as flexible project deployment policies, and features that optimize {KIE_SERVER} performance during development, such as disabled duplicate GAV detection. Use development mode until your {PRODUCT} environment is established and completely ready for production mode.
+
--
For more information about configuring the environment mode or duplicate GAV detection, see the following resources:

ifdef::DM,PAM[]
* xref:configuring-environment-mode-proc_execution-server[]
* {URL_DEPLOYING_AND_MANAGING_SERVICES}#project-duplicate-GAV-con_packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_]
endif::[]
ifdef::DROOLS,JBPM,OP[]
* <<_development_streamline_lifecycle>>
* <<_duplicate_gav_detection>>
endif::[]
--

Adapt {KIE_SERVER} capabilities and extensions to your specific needs::
The capabilities in {KIE_SERVER} are determined by plug-in extensions that you can enable, disable, or further extend to meet your business needs. By default, {KIE_SERVER} extensions are exposed through REST or JMS data transports and use predefined client APIs. You can extend existing {KIE_SERVER} capabilities with additional REST endpoints, extend supported transport methods beyond REST or JMS, or extend functionality in the {KIE_SERVER} client.
+
--
This flexibility in {KIE_SERVER} functionality enables you to adapt your {KIE_SERVER} instances to your business needs, instead of adapting your business needs to the default {KIE_SERVER} capabilities.

For information about enabling, disabling, or extending {KIE_SERVER} capabilities, see
ifdef::DM,PAM[]
xref:kie-server-extensions-con_execution-server[].
endif::[]
ifdef::DROOLS,JBPM,OP[]
xref:kie-server-extensions-con_kie-apis[].
endif::[]
--
