[id='prometheus-monitoring-con_{context}']

= Prometheus metrics monitoring in {PRODUCT}

Prometheus is an open-source systems monitoring toolkit that you can use with {PRODUCT} to collect and store metrics related to the execution of business rules, processes, Decision Model and Notation (DMN) models, and other {PRODUCT} assets. You can access the stored metrics through a REST API call to the {KIE_SERVER}, through the Prometheus expression browser, or using a data-graphing tool such as Grafana.

You can configure Prometheus metrics monitoring for an on-premise {KIE_SERVER} instance, for {KIE_SERVER} on Spring Boot, or for a {KIE_SERVER} deployment on {OPENSHIFT}.

For the list of available metrics that {KIE_SERVER} exposes with Prometheus,
ifdef::DM,PAM[]
download the *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Source Distribution* from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Red Hat Customer Portal] and navigate to `~/{PRODUCT_FILE}-sources/src/droolsjbpm-integration-$VERSION/kie-server-parent/kie-server-services/kie-server-services-prometheus/src/main/java/org/kie/server/services/prometheus`.
endif::[]
ifdef::DROOLS,JBPM,OP[]
see the https://github.com/kiegroup/droolsjbpm-integration/tree/main/kie-server-parent/kie-server-services/kie-server-services-prometheus[{KIE_SERVER} Prometheus Extension] page in GitHub.
endif::[]

ifdef::DM,PAM[]
IMPORTANT: Red Hat support for Prometheus is limited to the setup and configuration recommendations provided in Red Hat product documentation.
endif::[]
