[id='securing-passwords-proc_{context}']

= Securing passwords with a keystore

You can use a keystore to encrypt passwords that are used for communication between {CENTRAL} and {KIE_SERVER}. You should encrypt both controller and {KIE_SERVER} passwords. If {CENTRAL} and {KIE_SERVER} are deployed to different application servers then both application servers should use the keystore.

Use Java Cryptography Extension KeyStore (JCEKS) for your keystore because it supports symmetric keys. Use KeyTool, which is part of the JDK installation, to create a new JCEKS.

[NOTE]
====
If {KIE_SERVER} is not configured with JCEKS, {KIE_SERVER} stores passwords in configuration parameters in unsecured text files.
====

.Prerequisites

* {KIE_SERVER} is installed in
ifdef::DROOLS,JBPM,OP[]
{WILDFLY}.
endif::[]
ifdef::DM,PAM[]
ifeval::["{context}" == "install-on-eap"]
{EAP}.
endif::[]
ifeval::["{context}" == "install-on-jws"]
{JWS}.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
{TOMCAT}.
endif::[]
ifeval::["{context}" == "dsps-on-was"]
{WAS}.
endif::[]
ifeval::["{context}" == "dsps-on-wls"]
{WLS}.
endif::[]
endif::[]
* Java 8 or higher is installed.

.Procedure
. In the
ifdef::DROOLS,JBPM,OP[]
{WILDFLY}.
endif::[]
ifdef::DM,PAM[]
ifeval::["{context}" == "install-on-eap"]
{EAP}.
endif::[]
ifeval::["{context}" == "install-on-jws"]
{JWS}.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
{TOMCAT}.
endif::[]
ifeval::["{context}" == "dsps-on-was"]
{WAS}.
endif::[]
ifeval::["{context}" == "dsps-on-wls"]
{WLS}.
endif::[]
endif::[]
 home directory, enter the following command to create a {KIE_SERVER} user with the `kie-server` role and specify a password. In the following example, replace `<USER>` and `<PASSWORD>` with the user and password of your choice.
+
ifdef::DROOLS,JBPM,OP[]
[source,bash]
----
$<WILDFLY_HOME>/add-user.sh -a -e -u <USER> -p "<PASSWORD>" -g kie-server
----
endif::[]
ifdef::DM,PAM[]
ifeval::["{context}" == "install-on-eap"]
[source,bash]
----
$<EAP_HOME>/add-user.sh -a -e -u <USER> -p "<PASSWORD>" -g kie-server
----
endif::[]
ifeval::["{context}" == "install-on-jws"]
[source,bash]
----
$<JWS_HOME>/add-user.sh -a -e -u <USER> -p "<PASSWORD>" -g kie-server
----
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
[source,bash]
----
$<TOMCAT_HOME>/add-user.sh -a -e -u <USER> -p "<PASSWORD>" -g kie-server
----
endif::[]
ifeval::["{context}" == "dsps-on-was"]
[source,bash]
----
$<WAS_HOME>/add-user.sh -a -e -u <USER> -p "<PASSWORD>" -g kie-server
----
endif::[]
ifeval::["{context}" == "dsps-on-wls"]
[source,bash]
----
$<WLS_HOME>/add-user.sh -a -e -u <USER> -p "<PASSWORD>" -g kie-server
----
endif::[]
endif::[]
+
. To use KeyTool to create a JCEKS, enter the following command in the Java 8 home directory:
+
[source,bash]
----
$<JAVA_HOME>/bin/keytool -importpassword -keystore <KEYSTORE_PATH> -keypass <ALIAS_KEY_PASSWORD> -alias <PASSWORD_ALIAS> -storepass <KEYSTORE_PASSWORD> -storetype JCEKS
----
+
In this example, replace the following variables:

* `<KEYSTORE_PATH>`: The path where the keystore will be stored
* `<KEYSTORE_PASSWORD>`: The keystore password
* `<ALIAS_KEY_PASSWORD>`: The password used to access values stored with the alias
* `<PASSWORD_ALIAS>`: The alias of the entry to the process

. When prompted, enter the password for the {KIE_SERVER} user that you created.
. Set the following system properties in the
ifdef::DROOLS,JBPM,OP[]
`WILDFLY_HOME/standalone/configuration/standalone-full.xml`
endif::[]
ifdef::DM,PAM[]
ifeval::["{context}" == "install-on-eap"]
`EAP_HOME/standalone/configuration/standalone-full.xml`
endif::[]
ifeval::["{context}" == "install-on-jws"]
`JWS_HOME/standalone/configuration/standalone-full.xml`
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`TOMCAT_HOME/standalone/configuration/standalone-full.xml`
endif::[]
ifeval::["{context}" == "dsps-on-was"]
`WAS_HOME/standalone/configuration/standalone-full.xml`
endif::[]
ifeval::["{context}" == "dsps-on-wls"]
`WLS_HOME/standalone/configuration/standalone-full.xml`
endif::[]
endif::[]
 file and replace the placeholders as listed in the table that follows:
+
[source,xml]
----
    <system-properties>
        <property name="kie.keystore.keyStore_URL" value="<PATH>">
        <property name="kie.keystore.keyStorePwd" value="<KEYSTORE_PWD>"/>
        <property name="kie.keystore.key.server.alias" value="<KEY_SERVER_ALIAS>"/>
        <property name="kie.keystore.key.server.pwd" value="<KEY_SERVER_PWD>"/>
        <property name="kie.keystore.key.ctrl.alias" value="<KEY_CONTROL_ALIAS>"/>
        <property name="kie.keystore.key.ctrl.pwd" value="<KEY_CONTROL_PWD>"/>
    </system-properties>
----
+
.System properties used to load a {KIE_SERVER} JCEKS
[cols="40%,30%,40%", frame="all", options="header"]
|===
| System property
| Placeholder
| Description

| `kie.keystore.keyStore_URL`
| `<PATH>`
| Path for the JCEKS that you want to use, for example `file:///home/kie/keystores/keystore.jceks`

| `kie.keystore.keyStorePwd`
| `<KEYSTORE_PWD>`
| Password for the JCEKS

| `kie.keystore.key.server.alias`
| `<KEY_SERVER_ALIAS>`
| Alias of the key for REST services where the password is stored

| `kie.keystore.key.server.pwd`
| `<KEY_SERVER_PWD>`
| Password of the alias for REST services with the stored password

| `kie.keystore.key.ctrl.alias`
| `<KEY_CONTROL_ALIAS>`
| Alias of the key for default REST Process Automation Controller where password is stored

| `kie.keystore.key.ctrl.key.ctrl.pwd`
| `<KEY_CONTROL_PWD>`
| Password of the alias for default REST  Process Automation Controller with the stored password

|===

. Start {KIE_SERVER} to verify the configuration.
