[id='securing-passwords-proc_{context}']

= Generating a JCEKS for KIE Server

Kie Server uses passwords to authenticate users. For increased security, you can store Kie Server passwords in a keystore. Because it supports symmetics keys, you must use a Java Cryptography Extension KeyStore (JCEKS) with KIE Server. Use KeyTool, which is part of the JDK installation, to create a new keystore.

[NOTE]
====
If KIE Server is not configured with JCEKS, KIE Server stores passwords in configuration parameters in unsecured text files.
====

.Prerequisites
* KIE Server is installed on Red Hat EAP.
* Jave 8 or higher is installed.

.Procedure
. In the Red Hat EAP home directory, enter the following command to create a KIE Server user with the `kie-server` role and specify a password. In the following example, replace `<USER>` and `<PASSWORD>` with the user and password of your choice.
+
[source,bash]
----
$<EAP_HOME>/add-user.sh -a -e -u <USER> -p "<PASSWORD>" -g kie-server
----
+
. To use KeyTool to create a JCEKS, enter the following command in the Java 8 home directory:
+
[source,bash]
----
${JAVA_HOME}/bin/keytool -importpassword -keystore <KEYSTORE_URL> -keypass <ALIAS_KEY_PASSWORD> -alias <PASSWORD_ALIAS> -storepass <KEYSTORE_PASSWORD> -storetype JCEKS
----
+
In this example, replace the following variables:

* `<KEYSTORE_URL>`: A URL for the keystore
* `<ALIAS_KEY_PASSWORD>`: The keystore password
* `<PASSWORD_ALIAS>`: ??
* `<KEYSTORE_PASSWORD>`: The keystore password

. When prompted, enter the password for the KIE Server user that you created.
. Set the following system properties in the `EAP_HOME/standalone/configuration/standalone-full.xml` file and replace the placeholders as listed in the table that follows:
+
[source,xml]
----
    <system-properties>
        <property name="kie.keystore.keyStoreURL" value="<URL>">
        <property name="kie.keystore.keyStorePwd" value="<KEYSTORE_PWD>"/>
        <property name="kie.keystore.key.server.alias" value="<KEY_SERVER_ALIAS>"/>
        <property name="kie.keystore.key.server.pwd" value="<KEY_SERVER_PWD>"/>
        <property name="kie.keystore.key.ctrl.alias" value="<KEY_CONTROL_ALIAS>"/>
        <property name="kie.keystore.key.ctrl.pwd" value="<KEY_CONTROL_PWD>"/>
    </system-properties>
----
+
.System properties used to load a Kie Server JCEKS
[cols="40%,30%,40%", frame="all", options="header"]
|===
| System property
| Placeholder
| Description

| `kie.keystore.keyStoreURL`
| `<URL>`
| URL for the JCEKS that you want to use

| `kie.keystore.keyStorePwd`
| `<KEYSTORE_PWD>`
| Password for the JCEKS

| `kie.keystore.key.server.alias`
| `<KEY_SERVER_ALIAS>`
| Alias of the key for REST services where the password is stored

| `kie.keystore.key.server.pwd`
| `<KEY_SERVER_PWD>`
| Password of the alias for REST services with the stored password

| `kie.keystore.key.ctrl.alias`
| `<KEY_CONTROL_ALIAS>`
| Alias of the key for default REST Process Automation Controller where password is stored

| `kie.keystore.key.ctrl.keyStorePwd`
| `<KEY_CONTROL_PWD>`
| Password of the alias for default REST  Process Automation Controller with the stored password

|===

. Start KIE Server to verify the configuration.
