[id='controller-wls-was-environment-set-proc_{context}']
= Setting system properties for the {HEADLESS_CONTROLLER}

After you install the {HEADLESS_CONTROLLER}, set the system properties listed in this section on your application server or servers to enable proper interaction with the {HEADLESS_CONTROLLER}.

[NOTE]
====
For optimal results, install {KIE_SERVER} and the {HEADLESS_CONTROLLER} on different servers in production environments. In development environments, you can install {KIE_SERVER} and the {HEADLESS_CONTROLLER} on the same server. In either case, be sure to make these property changes on all application servers where the {HEADLESS_CONTROLLER} is installed.
====

.Prerequisites
* {KIE_SERVER} and the {HEADLESS_CONTROLLER} are installed on the application server instance.

.Procedure
. Specify the following JVM property values on the application server instance where the {HEADLESS_CONTROLLER} is installed:
+
[cols="40,60", options="header"]
.Required properties for the {HEADLESS_CONTROLLER}
|===
|Name
|Requirement

|`org.kie.server.user`
|A user with the `kie-server` role

|`org.kie.server.pwd`
|The password for the user specified in the `org.kie.server.user` property
|===

. Specify the following JVM property values on the application server instance where {KIE_SERVER} is installed:
+
--
[cols="40,60", options="header"]
.Required properties for {KIE_SERVER} when {HEADLESS_CONTROLLER} is installed
|===
|Name
|Requirement

|`org.kie.server.controller.user`
|A user with the `kie-server` role

|`org.kie.server.controller.pwd`
|The password for the user specified for the `org.kie.server.controller.user` property

|`org.kie.server.id`
|The ID or name of the {KIE_SERVER} installation, such as `rhdm700-decision-server-1`

|`org.kie.server.location`
|The URL of {KIE_SERVER}, `\http://<HOST>:<PORT>/kie-server/services/rest/server`

|`org.kie.server.controller`
|The URL of the {HEADLESS_CONTROLLER}, `\http://<HOST>:<PORT>/controller/rest/controller`
|===

`<HOST>` is the ID or name of the {KIE_SERVER} host, for example, `localhost` or `192.7.8.9`.

`<PORT>` is the port number of the {KIE_SERVER} host, for example, `7001`.
--
