[id='wls-jms-factory-create-proc']
= Create JMS connection factories

To enable messaging with {KIE_SERVER}, you must create certain JMS connection factories for sending and receiving messages.

.Prerequisites
* You have created a JMS server.
* You have created a JMS module.

.Procedure
. In the WebLogic Administration Console, navigate to *Services* -> *Messaging* -> *JMS Modules* to see a list of JMS modules.
. Select your previously created module and click *New* to create a new JMS resource.
. Select *Connection Factory* and click *Next*.
. For each of rthe equired connection factories listed in the following table, enter the name of the connection factory (for example, `KIE.SERVER.REQUEST`) and the JNDI name (for example, `jms/cf/KIE.SERVER.REQUEST`) and click *Next*. The connection factory automatically selects the servers assigned to the JMS Module as the default.
+
[cols="25,35,40", options="header"]
.Required JMS connection factories for {KIE_SERVER}
|===
|Name
|Default value
|Used for

|`KIE.SERVER.REQUEST`
|`jms/cf/KIE.SERVER.REQUEST`
| Sending all requests to {KIE_SERVER}

|`KIE.SERVER.RESPONSE`
|`jms/cf/KIE.SERVER.RESPONSE`
| Receiving all responses produced by {KIE_SERVER}

ifdef::PAM[]
|`KIE.SERVER.EXECUTOR`
|`jms/cf/KIE.SERVER.EXECUTOR`
| {KIE_SERVER} executor services
endif::PAM[]
|===

. Click *Finish* to add the connection factory, and repeat for each required factory.
