[id='wls-install-start-proc']
= Installing and running {WEBLOGIC}

{WEBLOGIC} must be installed and running for you to apply many of the configurations that accommodate {KIE_SERVER}. This section describes how to install and start {WEBLOGIC} in a standalone {WEBLOGIC} domain.

For the most up-to-date and detailed installation instructions, see the http://www.oracle.com/technetwork/middleware/weblogic/documentation/index.html[{WEBLOGIC} product page].

[NOTE]
====
If you are already running an instance of {WEBLOGIC} that uses the same listener port as the one to be used by the server you are starting, you must stop the first server before starting the second server.
====

.Procedure
. Download {WEBLOGIC} 12.2.1.3.0 or later from the {WEBLOGIC} http://www.oracle.com/technetwork/middleware/weblogic/downloads/index.html[Downloads page].
. Sign in to the target system and verify that a certified JDK already exists on your system. The installer requires a certified JDK. For system requirements, see http://www.oracle.com/technetwork/middleware/ias/downloads/fusion-requirements-100147.html[Oracle Fusion Middleware Systems Requirements and Specifications]. To download the JDK, see the 'About JDK Requirements for an Oracle Fusion Middleware Installation' section in the  https://docs.oracle.com/en/middleware/lifecycle/12.2.1.3/asins/preparing-oracle-fusion-middleware-installation.html#GUID-A3738BBA-5FD1-425B-91EB-7CB22187C700[Planning an Installation of Oracle Fusion Middleware].
. Go to the directory where you downloaded the installation program.
. Launch the installation program by running `java -jar` from the JDK directory on your system. See the following examples:
+
--
On UNIX-based operating systems:

[source]
----
/home/Oracle/jdk/jdk1.8.0_131/bin/java -jar fmw_12.2.1.3.0_wls_generic.jar
----

On Windows operating systems:

[source]
----
C:\Program Files\Java\jdk1.8.0_131\bin\java -jar fmw_12.2.1.3.0_wls_generic.jar
----
Be sure to replace the JDK location in these examples with the actual JDK location on your system.
--
. Follow the installation wizard prompts to complete the installation.
. After the installation is complete, navigate to the domain directory in the command terminal, `_WLS_HOME_/user_projects/<DOMAIN_NAME>`. For example:
+
[source]
----
WLS\user_projects\mydomain
----
. Enter one of the following commands to start {WEBLOGIC}:
+
--
On UNIX-based operating systems:

[source]
----
startWebLogic.sh
----
On Windows operating systems:

[source]
----
startWebLogic.cmd
----

The startup script displays a series of messages, and finally displays a message similar to the following:

[source]
----
<Dec 8, 2017 3:50:42 PM PDT> <Notice> <WebLogicServer> <000360> <Server started in RUNNING mode>
----
--
. Open the following URL in a web browser:
+
--
[source]
----
http://<HOST>:<PORT>/console
----

`<HOST>` is the system name or IP address of the host server.

`<PORT>` is the address of the port on which the host server is listening for requests (7001 by default).

For example, to start the Administration Console for a local instance of {WEBLOGIC} running on your system, enter the following URL in a web browser:

[source]
----
http://localhost:7001/console/
----

If you started the Administration Console using secure socket layer (SSL), you must add `s` after `http`, as follows:
`\https://<HOST>:<PORT>/console`
--
. When the login page of the WebLogic Administration Console appears, enter your administrative credentials.
