[id='ref-kogito-rn-new-features_{context}']
= New features in {PRODUCT} {PRODUCT_VERSION}

The following sections describe some of the new features or enhancements in {PRODUCT} {PRODUCT_VERSION}.

== {PRODUCT} runtimes

=== Improved/new bla bla

Description

== {PRODUCT} Operator and CLI

=== Improved/new bla bla

Description

== {PRODUCT} supporting services

=== {PRODUCT} Data Index Service support for MongoDB persistence storage

You can now configure the {PRODUCT} Data Index Service to use https://www.mongodb.com/[MongoDB] for persistence storage instead of the default Infinispan-based persistence storage.

With this enhancement, the https://repository.jboss.org/org/kie/kogito/data-index-service/[`data-index-service`] artifact is deprecated and the following new artifacts are available:

* https://repository.jboss.org/org/kie/kogito/data-index-service-infinispan/[`data-index-service-infinispan`]: Use this artifact to run the Data Index Service with Infinispan persistence storage.
* https://repository.jboss.org/org/kie/kogito/data-index-service-mongodb/[`data-index-service-mongodb`]: Use this artifact to run the Data Index Service with MongoDB persistence storage.

For more information about using the {PRODUCT} Data Index Service with MongoDB, see
ifdef::KOGITO[]
{URL_CONFIGURING_KOGITO}#proc-data-index-service-mongodb_kogito-configuring[_{CONFIGURING_KOGITO}_].
endif::[]
ifdef::KOGITO-COMM[]
xref:proc-data-index-service-mongodb_kogito-configuring[].
endif::[]

== {PRODUCT} tooling

=== Improved/new bla bla

Description
