[id='assembly_openshift-immutable]

include::product-shared-docs/document-attributes.adoc[]

= Deploying a {PRODUCT} {PRODUCT_VERSION} environment on {OPENSHIFT} using Automation Broker
// Context attribute is assembly specific and enables module reuse between assemblies.
:imagesdir: topics/product-shared-docs/images
:context: openshift-ansible-playbook
include::product-shared-docs/author-group.adoc[]

// Purpose statement for the assembly
As a system engineer, you can deploy a {PRODUCT} environment on {OPENSHIFT} to provide an 
infrastructure to develop or execute processes and other business assets. You can use
the Automation Broker to deploy the environment in an interactive process, setting all
parameters as necessary. A {PRODUCT} Ansible Playbook for the Automation Broker is available.

.Prerequisites

* At least four gigabytes of memory are available in the OpenShift environment.
* The OpenShift project for the deployment is created.
* You have logged in to the project using the OpenShift web console and using the `oc` command.
* Dynamic persistent volume (PV) provisioning is enabled. Alternatively, enough persistent volumes are available. By default, the following sizes are required:
** Each deployed replicated set of {KIE_SERVER} pods requires one 1Gi PV for the database.
** {CENTRAL} requires one 1Gi PV.
** {CENTRAL} Monitoring requires one 64Mi PV.
** Smart Router requires one 64Mi PV.
* If you intend to scale any of the {CENTRAL} or {CENTRAL} Monitoring pods, your OpenShift environment supports persistent volumes with ReadWriteMany mode.
+
IMPORTANT: ReadWriteMany mode is not supported on OpenShift Online and OpenShift Dedicated.

include::product-assembly_pam-on-openshift/ba-openshift-overview-con.adoc[leveloffset=+1]
include::product-assembly_dm-on-openshift/dm-openshift-prepare-con.adoc[leveloffset=+1]
include::product-assembly_dm-on-openshift/imagestreams-file-install-proc.adoc[leveloffset=+2]
include::product-assembly_pam-on-openshift/glusterfs-reconfig-proc.adoc[leveloffset=+2]
include::product-assembly_pam-on-openshift/apb-deploy-proc.adoc[leveloffset=+1]
include::product-assembly_pam-on-openshift/apb-deprovision-proc.adoc[leveloffset=+1]

// Versioning info
include::product-shared-docs/versioning-information.adoc[]
