[[_chap_dashbuilder_first_steps]]
= Creating your first dashboard

The purpose of this chapter is NOT to provide a full detailed explanation of the tooling, but to guide you through the key steps to get your first dashboards created.
The following section will provide basic information about how to configure the system to retrieve information from existing databases or files, create new indicators and manage different dashboards. 

For this guide, it's assumed the simple installation has been done, with the standard set of examples and user and role configuration.
It's important to notice this configuration **MUST NOT be used in production**, since it provides default security credentials. 

[NOTE]
====
Please, read the previous chapters to figure out how to get the application up and running 
====

The procedure to create a brand new dashboard is pretty simple as we will see in the following sections.
That procedure is composed of 3 main stages: 

. Get the data we want to manipulate.
. Create key performance indicators on top of such data.
. Create a new dashboard and drag&drop the new KPIs on it. 

include::DataProviders/CreateDataProvider-section.adoc[leveloffset=+1]
include::KPIs/CreateKPI-section.adoc[leveloffset=+1]
include::Dashboards/ComposeDashboard-section.adoc[leveloffset=+1]

