
[[_chap_dashbuilder_import_export]]
= Import & Export

Dashbuilder provides import and export functionality in order to move application assets between environments.

These assets can be:

* **Workspaces**: By exporting and importing workspaces you can move your set of pages with a given look and feel between installations.
* **Key performance indicators and data providers**: By exporting and importing KPIs you can move your indicators and their data providers between installations.
* **Data sources**: By exporting and importing data sources you can move your external connection configurations between installations.


In general, asset *export* must be done using the __Web User Interface__.
There exist a panel for exporting each type of asset.

On the other hand, asset *import* can be done in two ways:

* Using the __Web User Interface__.
+ 
There are panels for importing each type of asset.
* Using the __Deployment Scanner__.
+ 
It allows to place your exported assets in a given folder inside the web application.
On application startup it scans the deployments folder and imports the assets found.
+ 
Using the _Deployment Scanner_ allows for the automatic deployment of assets on application start up and does not require the user intervention either.
+ 
It's important to note that assets are imported only at deploy time, not during application runtime.


The following sections describe how to perform import and export for each kind of asset.

include::ImportExport/Workspaces-section.adoc[leveloffset=+1]
include::ImportExport/KPI-section.adoc[leveloffset=+1]
include::ImportExport/DataSources-section.adoc[leveloffset=+1]

