[id='impact-analysis']
= Impact Analysis

[WARNING]
====
This feature is experimental and subject to change.
====

Impact Analysis analyzes the relationships between rules and generates a graph. If you specify a rule to be changed, it analyzes rules impacted by the change so they are rendered in the graph.

The graph supports DOT, SVG, PNG formats and also simple text output.

== Usage

You can find an example usage in `ExampleUsageTest.java` under `drools-impact-analysis/drools-impact-analysis-itests`

Configure a dependency.

[source,xml]
----
    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-impact-analysis-graph-graphviz</artifactId>
      <version>${drools.version}</version>
    </dependency>
----

Create a `KieFileSystem` to store your assets as usual. Then call `KieBuilder.buildAll(ImpactAnalysisProject.class)`. You can get `AnalysisModel`.

[source,java]
----
      // set up KieFileSystem
      ...
      KieBuilder kieBuilder = KieServices.Factory.get().newKieBuilder(kfs).buildAll(ImpactAnalysisProject.class);
      ImpactAnalysisKieModule analysisKieModule = (ImpactAnalysisKieModule) kieBuilder.getKieModule();
      AnalysisModel analysisModel = analysisKieModule.getAnalysisModel();
----

Convert the `AnalysisModel` to `Graph` using `ModelToGraphConverter`.

[source,java]
----
      ModelToGraphConverter converter = new ModelToGraphConverter();
      Graph graph = converter.toGraph(analysisModel);
----

Specify a rule which you plan to change. `ImpactAnalysisHelper` will produce a sub graph which contains the changed rule and impacted rules.

[source,java]
----
      ImpactAnalysisHelper impactFilter = new ImpactAnalysisHelper();
      Graph impactedSubGraph = impactFilter.filterImpactedNodes(graph, "org.drools.impact.analysis.example.PriceCheck_11");
----

Generate a graph image using `GraphImageGenerator`. You can choose the format from DOT, SVG and PNG.

[source,java]
----
      GraphImageGenerator generator = new GraphImageGenerator("example-impacted-sub-graph");
      generator.generateSvg(impactedSubGraph);
----

Simple text output is also available using TextReporter. You can choose the format from HierarchyText and FlatText.

[source,java]
----
      String hierarchyText = TextReporter.toHierarchyText(impactedSubGraph);
      System.out.println(hierarchyText);
----

== Tips

* Typical use case is to view an impacted sub graph. Red node is a changed rule. Yellow nodes are impacted rules. Solid arrow represents positive impact, where the source rule activates the target rule. Dashed arrow represents negative impact, where the source rule deactivates the target rule. Dotted arrow represents unknown impact, where the source rule may activate or deactivate the target rule.

image::ImpactAnalysis/impactAnalysis1.svg[align="center"]

* Whole graph could be too large if you have many rules.
* You can collapse the graph based on rule name prefix (= RuleSet in spreadsheet) using `GraphCollapsionHelper`. It will help you to see the overview. You can also use `ImpactAnalysisHelper` to the collapsed graph.

[source,java]
----
      Graph collapsedGraph = new GraphCollapsionHelper().collapseWithRuleNamePrefix(graph);
      Graph impactedCollapsedSubGraph = impactFilter.filterImpactedNodes(collapsedGraph, "org.drools.impact.analysis.example.PriceCheck");
----

* You can filter the relations by giving positiveOnly to true for `ModelToGraphConverter`, `ImpactAnalysisHelper` and `GraphCollapsionHelper` constructor. So you can view only positive relations.

[source,java]
----
      ModelToGraphConverter converter = new ModelToGraphConverter(true);
      Graph graph = converter.toGraph(analysisModel);
      ImpactAnalysisHelper impactFilter = new ImpactAnalysisHelper(true);
      Graph impactedSubGraph = impactFilter.filterImpactedNodes(graph, "org.drools.impact.analysis.example.PriceCheck_11");
----

* If the number of rules is very large, text output would be useful. `[*]`` is a changed rule. `[+]`` is impacted rules. A rule with parentheses means a circular reference so it doesn't render further.

[source]
----
--- toHierarchyText ---
Inventory shortage[+]
PriceCheck_11[*]
  StatusCheck_12[+]
  (Inventory shortage)
  StatusCheck_13[+]
  StatusCheck_11[+]
    (PriceCheck_11)

--- toFlatText ---
Inventory shortage[+]
PriceCheck_11[*]
StatusCheck_11[+]
StatusCheck_12[+]
StatusCheck_13[+]
----
