[id='_chap_eap_migration']
= Red Hat JBoss EAP Migration

== Migrating Red Hat JBoss BPM Suite from Red Hat JBoss EAP 6.4.x to 7.0 

Deploying Red Hat JBoss BRMS or Red Hat JBoss BPM Suite on Red Hat JBoss EAP 7 requires changes to the project BOM files. To upgrade your container from Red Hat JBoss EAP 6.4 to Red Hat JBoss EAP 7, configure the Intelligent Process Server or the Realtime Decision Server in the following way:

* If using JMS, change the provider URL(`java.naming.provider.url`) for `InitialContext`, which is used to look up JMS queues. Change the remoting port from `4447` to `8080` (EAP 7 uses `http-remoting`). For example:
[source]
----
    final Properties env = new Properties();
    ...
    env.put(Context.PROVIDER_URL, "http-remoting://<server ip>:8080");
    ...
    InitialContext context = new InitialContext(env);
----

Additionally, change the JMS dependency BOM to: 
[source]
----
       <dependency>
          <groupId>org.jboss.eap</groupId>
          <artifactId>wildfly-jms-client-bom</artifactId>
          <version>7.0.2.GA-redhat-1</version>
          <type>pom</type>
        </dependency>
----

* If using remote JMS client for Business Central, change the protocol from `remote` to `http-remoting` and port from `4447` to `8080`. Also, use ActiveMQ Artemis client library (`org.apache.activemq:artemis-jms-client` artifact). 

For more information on migration from Red Hat JBoss EAP 6.4 to Red Hat JBoss EAP 7.0, see the https://access.redhat.com/documentation/en/red-hat-jboss-enterprise-application-platform/7.0/paged/migration-guide/chapter-5-application-migration-changes[Application Migration Changes] chapter of the _Red Hat JBoss EAP Migration Guide_. 

