[id='_chap_why_migrate']
= Why Migrate?


Migrating to JBoss BRMS/{PRODUCT} 6 from BRMS 5.x branch means that you get the following new features: 



* A higher performance rule engine based on the Drools 6 community project. 
* Improved rule authoring tools and an enhanced, integrated user interface. 
* A common defined methodology for building and deployment using Maven as the basis for repository management. 
* A heuristic planning engine based on the OptaPlanner community project. 
* Use of the PHREAK algorithm to handle a larger number of rules and facts. 
* New Data Modeler that replaces the declarative Fact Model Editor 
* And many more stability, usability and functional improvements. 

Note that {PRODUCT} 6 is now the superset that includes a version of the Red Hat JBoss BRMS 6.
Red Hat JBoss BRMS 6 by itself does not include business process management capabilities. 

Being backwards compatible with JBoss BRMS 5.x branch, migrating to Red Hat JBoss BRMS 6 means that your rules created with BRMS 5.x will still execute on BRMS 6 without changes.
A migration tool is also provided with the 6 branch to facilitate migration of the content of a JBoss BRMS 5.x repository to Red Hat JBoss BRMS/{PRODUCT} 6.
Note, however, that BPMN2 process models created with JBoss BRMS 5.x will not execute on Red Hat JBoss BRMS 6. 
