[id='migration-update-remote-api-proc']
= Replace API references to {CENTRAL} execution server

In {PRODUCT} {PRODUCT_VERSION}, {CENTRAL} no longer has execution server capabilities nor any API endpoints related to the execution server. Instead, the {KIE_SERVER} performs all execution and runtime functions and {CENTRAL} is used only for designing and managing decision services. Therefore, if any of your applications interact with the {CENTRAL} execution server through the remote Java API (`kie-remote-client`) or through direct REST API calls (`/business-central/rest/`), you must update these API references to redirect to {KIE_SERVER}.

.Procedure
. In your application code for remote Java clients, replace any instances of the following legacy package and module for {CENTRAL} with the new package and module for {KIE_SERVER}. This replaces references to the remote Java API with references to {KIE_SERVER}.
+
--
Legacy {CENTRAL} package and module:
[source,java]
----
org.kie.remote.client
kie-remote-client
----

New {KIE_SERVER} package and module:
[source,java]
----
org.kie.server.client
kie-server-client
----
--
. Wherever applicable in your application code, replace any legacy REST API calls to {CENTRAL} in the format `http://<SERVER>:<PORT>/business-central/rest/<ENDPOINT>` with the new corresponding REST API calls to {KIE_SERVER} in the format `http://<SERVER>:<PORT>/kie-server/services/rest/server/<ENDPOINT>`.
+
--
The endpoints may differ between the legacy {CENTRAL} REST API calls and the corresponding {KIE_SERVER} REST API calls. To view the new endpoints for the corresponding {KIE_SERVER} API calls, start your {KIE_SERVER} instance and go to `http://<SERVER>:<PORT>/kie-server/docs` in a web browser (example: http://localhost:8080/kie-server/docs). Use the endpoints in this page to replace your legacy {CENTRAL} REST API calls.

NOTE: You do not need to update any {CENTRAL} Controller endpoints, which are in the format `http://<SERVER>:<PORT>/business-central/rest/controller`. The {CENTRAL} Controller is not affected by this API change.

The following example is an update to a REST API call for tasks.

Legacy {CENTRAL} REST API call:
[source]
----
http://localhost:8080/business-central/rest/tasks
----

New {KIE_SERVER} REST API call (from `http://<SERVER>:<PORT>/kie-server/docs`):
[source]
----
http://localhost:8080/kie-server/services/rest/server/queries/tasks/instances
----

NOTE: If {KIE_SERVER} is deployed in a separate {EAP} or other instance or has been moved to a new location, the server and port locations may differ from {CENTRAL}.

--

*<@Maciej (1 of 2): Is this whole section correct now, in your opinion? Especially step 2?>*
