[id='migration-verify-execution-server-proc']

= Verifying the migration in {CENTRAL}

After you have completed all data migration and have configured and started the new {KIE_SERVER}, verify that the migration was successful in the new {CENTRAL} for {PRODUCT} {PRODUCT_VERSION}.

.Prerequisites
* Project data from {PRODUCT_OLD} has been migrated using the {CENTRAL} migration tool.
* The database configured for {PRODUCT_OLD} has been upgraded.
* All references to the remote Java API in any remote client applications have been redirected to the {KIE_SERVER}.
* The new {KIE_SERVER} has been configured and started.

.Procedure
. After the server starts, log in to {CENTRAL} for {PRODUCT} {PRODUCT_VERSION} and navigate to *Menu -> Deploy -> Execution Servers*.
. Select the server template that you created previously and verify that the server is now listed under *Remote Servers* and that each associated *KIE container* is validated.
. Navigate to *Menu -> Manage -> Process Instances* and verify that all live process instances have been migrated.
. Navigate to *Menu -> Manage -> Task Lists* and verify that all live tasks have been migrated.
