[id='migration-java-dependencies-proc']

= Update Java project dependencies

You must update several dependencies in your Java projects to prepare them for migration to {PRODUCT} {PRODUCT_VERSION}.

.Prerequisite
The Maven repository for {PRODUCT} {PRODUCT_VERSION} has been downloaded from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Red Hat Customer Portal] and made available to the local Maven installation (as a local or remote repository).

.Procedure
. Open the `pom.xml` file of the project and remove the `<version>` tag from any dependencies under the following groups:
* `org.kie`
* `org.drools`
* `org.jbpm`
* `org.optaplanner`
. Add the following dependency under the `<dependencies>` tag within the `<dependencyManagement>` section:
+
ifdef::DM[]
[source,xml]
----
<dependency>
  <groupId>org.jboss.bom</groupId>
  <artifactId>rhdm-platform-bom</artifactId>
  <version>${rhdm.version}</version>
  <scope>import</scope>
  <type>pom</type>
</dependency>
----
endif::DM[]
ifdef::PAM[]
[source,xml]
----
<dependency>
  <groupId>org.jboss.bom</groupId>
  <artifactId>rhpam-platform-bom</artifactId>
  <version>${rhpam.version}</version>
  <scope>import</scope>
  <type>pom</type>
</dependency>
----
endif::PAM[]
+
The `${{PRODUCT_INIT}.version}` is the version of the `org.jboss.bom:{PRODUCT_INIT}-platform-bom` artifact in the Maven repository for {PRODUCT} {PRODUCT_VERSION}. You can view the version of the artifact by entering the repository and navigating to the `maven-repository/org/jboss/bom/{PRODUCT_INIT}/{PRODUCT_INIT}-platform-bom` directory. The name of the only sub-directory in this directory is the version. For example: `7.0.0.GA-redhat-1`.
. If your code uses any Drools CDI annotations (`@KReleaseId` , `@KContainer`, `@KBase`, `@KSession`), also add the following dependency:
+
[source,xml]
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-cdi</artifactId>
</dependency>
----
+
This dependency is necessary because the CDI extension for processing the annotations is now defined using a separate module. Without this dependency, the annotations do not work.
. Replace the legacy `jbpm-workitems` dependency (if applicable) with one or more of the new dependencies. The new dependencies that you choose depend on the work items that your code uses.
+
--
Legacy `jbpm-workitems` dependency:

[source,xml]
----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems</artifactId>
</dependency>
----

New `jbpm-workitems` dependency options:

[source,xml]
----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-core</artifactId>
</dependency>
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-bpmn2</artifactId>
</dependency>
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-email</artifactId>
</dependency>
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-jms</artifactId>
</dependency>
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-rest</artifactId>
</dependency>
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-webservice</artifactId>
</dependency>
----
--
. Replace the legacy `org.guvnor` dependency (if applicable) with the new `org.uberfire` dependency.
+
--
Legacy `org.guvnor` dependency:

[source,xml]
----
<dependency>
  <groupId>org.guvnor</groupId>
  <artifactId>guvnor-rest-client</artifactId>
</dependency>
----

New `org.uberfire` dependency:

[source,xml]
----
<dependency>
  <groupId>org.uberfire</groupId>
  <artifactId>uberfire-rest-client</artifactId>
</dependency>
----
--
ifdef::PAM[]
. Replace the legacy `org.kie.remote` dependency (if applicable) with the new `org.kie.server` dependency.
+
--
Legacy `org.kie.remote` dependency:
[source,xml]
----
<dependency>
  <groupId>org.kie.remote</groupId>
  <artifactId>kie-remote-client</artifactId>
</dependency>
----

New `org.kie.server` dependency:

[source,xml]
----
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-client</artifactId>
</dependency>
----
This dependency is necessary because {CENTRAL} no longer has execution server capabilities nor API endpoints related to the execution server.
--
endif::PAM[]
. Update the version of the project artifact and save the `pom.xml` file.
