[id='migration-live-instances-proc']
= Migrating live tasks and process instances

In {PRODUCT} {PRODUCT_VERSION}, {CENTRAL} no longer has execution server capabilities nor any REST API endpoints. Instead, the {KIE_SERVER} performs all execution and runtime functions and {CENTRAL} is used for application development and management only. As a result of this change, the {CENTRAL} environment in {PRODUCT_OLD} must be migrated to the new {CENTRAL} and {KIE_SERVER} environments in {PRODUCT} {PRODUCT_VERSION} to retain live tasks and process instances. {CENTRAL} data must also be migrated using the {CENTRAL} migration tool provided with this release.

.Prerequisites
* {PRODUCT} {PRODUCT_VERSION} with a {CENTRAL} distribution is installed on the same host as {PRODUCT_OLD}. For installation options, see Planning the {PRODUCT} {PRODUCT_VERSION} installation.
//@link: Add link to insall planning doc.
* All {CENTRAL} project data is backed up, as a precaution.

.Procedure
. Log in to the new {CENTRAL} for {PRODUCT} {PRODUCT_VERSION}. This distribution of {CENTRAL} does not yet contain your project data or live instances, but needs to be prepared for the execution server migration.
. Navigate to *Menu -> Deploy -> Execution Servers -> New Server Template* and define a new server template (example, `myserver`). This template will be used by the new {KIE_SERVER} to manage your existing project deployments on the execution server.
. Select the new template, click *Add Container*, and add a container for each of the projects deployed on the execution server. Name each container with the exact deployment ID for the deployed project (example, `org.jbpm:HR:1.5`).
+
You can find deployment IDs in the execution server REST API for {PRODUCT_OLD} 6.4 at
`http://<HOST>:<PORT>/kie-execution-server/services/rest/server/jobs`.
+
IMPORTANT: Each KIE container name in the server template must match exactly the deployment ID for the deployed project on the execution server. If they do not match, then the deployed instances will not be migrated to the new {KIE_SERVER} properly.

. Close {CENTRAL} and stop your application server instance ({EAP}, WildFly, or other application server) based on how you started it.
+
--
Example:
[source]
----
$ ~/$APP_SERVER_HOME/bin/jboss-cli.sh --connect command=:shutdown
----
--
. Use the {CENTRAL} migration tool provided with {PRODUCT} {PRODUCT_VERSION} to migrate all {CENTRAL} data from {PRODUCT_OLD} to the new {CENTRAL}. For instructions, see xref:migration-tool-7.0-proc[].
. After you migrate {CENTRAL} data, navigate to the `{PRODUCT_FILE}-add-ons` folder that you downloaded and extracted in the process of using the migration tool and extract the `{PRODUCT_INIT}-{PRODUCT_VERSION}-upgrade-scripts.zip` sub-folder. This folder contains database upgrade scripts that are required for applying changes to the database model made in {PRODUCT} {PRODUCT_VERSION}.
. Log on to the database configured for your current {CENTRAL} execution server for {PRODUCT_OLD} and run the relevant {PRODUCT} upgrade script, according to the supported database type.
. Navigate to the {PRODUCT} {PRODUCT_VERSION} `bin` directory and start the new {KIE_SERVER} with the following properties. Adjust the specific properties according to your environment.
+
--
[source]
----
$ ~/RHBA_HOME/bin/standalone.sh - c server-config=standalone-full.xml <1>
-Djboss.socket.binding.port-offset=150 <2>
-Dorg.kie.server.id=myserver <3>
-Dorg.kie.server.controller=http://localhost:8080/business-central/rest/controller <4>
-Dorg.kie.server.location=http://localhost:8230/kie-server/services/rest/server <5>
-Dorg.kie.server.persistence.dialect=org.hibernate.dialect.PostgreSQLDialect <6>
-Dorg.kie.server.persistence.ds=java:jboss/datasources/psjbpmDS <7>
----
<1> Start command with `standalone-full.xml` server profile
<2> Port offset to avoid port conflicts when running on the same machine as {CENTRAL}
<3> Server ID that must match server template name defined in {CENTRAL}
<4> Controller location, {CENTRAL} URL with `/rest/controller` suffix
<5> {KIE_SERVER} location with port offset (offset of 150 in this example)
<6> Hibernate dialect to be used
<7> JNDI name of the data source used for your previous {PRODUCT_OLD} database

{KIE_SERVER} connects to the new {CENTRAL} and collects the list of KIE containers to be deployed.
--
. After the server starts, log in to {CENTRAL} for {PRODUCT} {PRODUCT_VERSION} and navigate to *Menu -> Deploy -> Execution Servers*.
. Select the server template you created previously and verify that the server is now listed under *Remote Servers* and that each *KIE container* is validated.
. Navigate to *Menu -> Manage -> Process Instances* and verify that all live process instances have been migrated.
. Navigate to *Menu -> Manage -> Tasks Administration* and verify that all live tasks have been migrated.
