[id='migration-execution-server-prep-proc']
= Prepare {CENTRAL} for migration

Before you can migrate project data from {PRODUCT_OLD} 6.4, you must add to the new {CENTRAL} a server configuration and deployment units (KIE containers) corresponding to {PRODUCT_OLD} 6.4 process deployments.

.Procedure
. Start {PRODUCT_OLD} according to your installation (for example, `$JBOSS_HOME/bin/standalone.sh`) and log in to {CENTRAL}.
. Navigate to *Deploy -> Process Deployments* and note the *Deployment* identifier and other details for your deployments. This information will be required when you prepare the new {CENTRAL} in {PRODUCT} {PRODUCT_VERSION} for migration.
. Close {CENTRAL} and stop {PRODUCT_OLD} 6.4 according to your installation.
. Start {PRODUCT} {PRODUCT_VERSION} according to your installation (for example,
ifdef::PAM[]
`$RHPAM_HOME/bin/standalone.sh -c standalone-full.xml`)
endif::PAM[]
ifdef::DM[]
`$RHDM_HOME/bin/standalone.sh -c standalone-full.xml`)
endif::DM[]
and log in to the new {CENTRAL}. This distribution of {CENTRAL} does not yet contain your project data or live instances, but needs to be prepared for the execution server migration.
. Navigate to *Menu -> Deploy -> Execution Servers -> New Server Configuration* and define a new server configuration (for example, `myserver`). This server configuration will be used by the new {KIE_SERVER} to manage the deployments currently on the {CENTRAL} execution server for {PRODUCT_OLD} 6.4.
. Select the new server configuration, click *Add Deployment Unit*, and add a deployment unit (KIE container) for each of the deployments on the execution server. Name each deployment unit with the exact deployment identifier from {PRODUCT_OLD} 6.4 (for example, `org.jbpm:HR:1.5`).
+
IMPORTANT: Each deployment unit name in the server configuration must match exactly the deployment identifier for the deployment on the execution server. If they do not match, the deployed instances will not be migrated properly to the new {KIE_SERVER}.

. Close {CENTRAL} and stop both {PRODUCT_OLD} 6.4 (if not stopped already) and {PRODUCT} {PRODUCT_VERSION} server instances based on how you started them.
+
--
Example:
[source]
----
$ ~/$EAP_HOME/bin/jboss-cli.sh --connect command=:shutdown
----
--
