[id='migration-tool-7.0-con_{context}']
= Use the {CENTRAL} migration tool

{PRODUCT} {PRODUCT_VERSION} contains a modified data structure and other feature changes that do not support a direct data migration from {PRODUCT_OLD} 6.4. Therefore, Red Hat provides a migration tool that enables you to migrate project data and configurations from {PRODUCT_OLD} 6.4 to {PRODUCT} {PRODUCT_VERSION}. You can run the migration tool on the `.niogit` directory of your {CENTRAL} distribution or on an external Git repository. The migration tool prepares your {CENTRAL} data for the new data structure and features supported in {PRODUCT} {PRODUCT_VERSION}.


////
// Old way to install tool, before zip distro. Retaining temporarily. (Stetson, 27 Mar 2018)
. In your terminal application, clone the `kie-wb-common` https://github.com/kiegroup/kie-wb-common[GitHub project] to a local directory:
+
[source]
----
$ ~/$REPO_DIR/git clone https://github.com/kiegroup/kie-wb-common.git
----
. In the cloned `kie-wb-common` directory, navigate to `kie-wb-common/kie-wb-common-cli/kie-wb-common-cli/kie-wb-common-cli-migration-tool` and run the following command:
+
[source]
----
mvn clean install
----
+
. After the installation completes, navigate to the newly created `target` directory within the tool folder and unzip the `kie-wb-common-cli-migration-tool-$VERSION-dist.zip` file to a desired installation directory.



// Importing projects,not needed but retaining temporarily.
. In {CENTRAL}, navigate to *Menu* -> *Design* -> *Projects* and select or create the space into which you want to import the projects. The default space is *MySpace*.
. Click the three vertical dots in the upper-right corner of the screen and select *Import Project*.
. For the *Repository URL*, enter the path to one of the repositories in your `.niogit` directory in the following format:
+
--
[source]
----
file:///$NIOGIT_DIR/$REPOSITORY.git
----
For example, if the location of the `.niogit` directory is `/opt/eap7.0/bin/.niogit` and you want to import a project from the `repository1` repository, you would enter the following path:

[source]
----
file://opt/eap7.0/bin/.niogit/repository1.git
----
--
. Click *Import*, select the project to import, and click *Import*.
. After the importing and indexing is complete, repeat these importing steps for each repository that you want to add to {PRODUCT} {PRODUCT_VERSION}.

.`NoRemoteRepositoryException`
[NOTE]
====
If during the import a `NoRemoteRepositoryException` error appears, you can temporarily remove the repository remotes in your terminal.

For example:

[subs="verbatim,macros"]
----
$ ~/opt/eap7.0/bin/.niogit/repository1.git
$ git remote -v
origin  https://github.com/guvnorngtestuser1/guvnorng-playground (fetch)
origin  https://github.com/guvnorngtestuser1/guvnorng-playground (push)
$ git remote remove origin
----

Then import the projects again. You can add the remotes in the new repository later if necessary (`git remote add $REPOSITORY_URL`).
====
////
