[id='migration-upgrade-database-proc']

= Upgrading your database

{PRODUCT} {PRODUCT_VERSION} contains updates to the database schema for optimal performance with the new {CENTRAL} and {KIE_SERVER}. You must update the database configured for {PRODUCT_OLD} 6.4 using one of the upgrade scripts provided with this release to accommodate the change.

.Prerequisites
* The *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons* distribution has been downloaded from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Red Hat Customer Portal] and extracted to a temporary directory.
* The database has been backed up, as a precaution.

.Procedure
. Navigate to the extracted `{PRODUCT_FILE}-add-ons` folder in your temporary directory and extract the `{PRODUCT_INIT}-{PRODUCT_VERSION}-upgrade-scripts.zip` sub-folder. This folder contains database upgrade scripts that are required for applying changes to the database model made in {PRODUCT} {PRODUCT_VERSION}.
. Log on to the database configured for your current {PRODUCT_OLD} 6.4 instance and run the relevant {PRODUCT} upgrade script, according to the supported database type.
. If you use Quartz as your scheduling service, additionally run the `quartz-upgrade.sql` script provided in the same database upgrade folder. This script updates your Quartz version to 2.2.3 in compliance with {PRODUCT} {PRODUCT_VERSION} requirements.
