[id='migration-verify-proc_{context}']

ifeval::["{context}" == "non-exec-server"]
= Verify the migration in {CENTRAL}

After you use the {CENTRAL} migration tool to migrate project data and you upgrade your {PRODUCT_OLD} 6.4 database, verify that the migration was successful in the new {CENTRAL} for {PRODUCT} {PRODUCT_VERSION}.

.Prerequisites
* Project data from {PRODUCT_OLD} 6.4 has been migrated using the {CENTRAL} migration tool.
* The database configured for {PRODUCT_OLD} has been upgraded.

.Procedure
. Start {PRODUCT} {PRODUCT_VERSION} depending on your installation.
+
Example: Installation with {EAP}
+
[source]
----
$ ~/$EAP_HOME/bin/standalone.sh -c standalone-full.xml
----
. Log in to {CENTRAL} with your credentials and navigate to *Menu -> Design -> Projects*.
. Verify that all projects have been migrated and select each project to verify the migrated project assets.
. For each project, click *Build* and then *Deploy* in the upper-right corner of the project window to validate the migrated project data and the configured {KIE_SERVER}.
endif::[]

ifeval::["{context}" == "exec-server"]
= Verify the migration in {CENTRAL}

After you have completed all data migration and have configured and started the new {KIE_SERVER}, verify that the migration was successful in the new {CENTRAL} for {PRODUCT} {PRODUCT_VERSION}.

.Prerequisites
* Project data from {PRODUCT_OLD} 6.4 has been migrated using the {CENTRAL} migration tool.
* The {PRODUCT_OLD} 6.4 database to be used with {PRODUCT} {PRODUCT_VERSION} has been upgraded.
* All API references to {CENTRAL} execution server in application code have been redirected to the {KIE_SERVER}.
* The new {KIE_SERVER} has been configured and started.

.Procedure
. After {KIE_SERVER} server starts, log in to {CENTRAL} for {PRODUCT} {PRODUCT_VERSION} and navigate to *Menu -> Deploy -> Execution Servers*.
. Select the server configuration that you created previously and verify that the server is now listed under *Remote Servers* and that each associated *Deployment Unit* is validated.
. Navigate to *Menu -> Manage -> Process Instances* and verify that all live process instances have been migrated.
. Navigate to *Menu -> Manage -> Tasks* and verify that all live tasks have been migrated.
. Navigate to *Menu -> Design -> Projects*, verify that all projects have been migrated, and select each project to verify the migrated project assets.
. For each project, click *Build* and then *Deploy* in the upper-right corner of the project window to validate the migrated project data and the configured {KIE_SERVER}.
endif::[]

ifeval::["{context}" == "java-projects"]
= Verify the Java project migration

After you have migrated all Java project data and have upgraded the relevant database, rebuild the Java project to verify successful migration.

.Prerequisites
* Java project dependencies have been updated.
* The {PRODUCT_OLD} 6.4 database to be used with {PRODUCT} {PRODUCT_VERSION} has been upgraded.
* Maven 3.x or later is installed.
* Java 8 or later is installed.

.Procedure
. Rebuild each Java project using a regular Maven build.
+
[source]
----
$ mvn clean install
----
. Review all project data in each build to confirm successful migration.
+
If you encounter build errors, verify that the project dependencies have been updated correctly. To review other product changes that may have impacted your Java project, see xref:migration-other-changes-con[].
endif::[]
