[id='migration-logic-changes-ref']
= Logic changes in {PRODUCT} {PRODUCT_VERSION}

Note the following logic changes in {PRODUCT} {PRODUCT_VERSION}:

* In {PRODUCT_OLD}, when a rule executes the sum function in an accumulate pattern, the result always returns as a double data type regardless of the data type of the inputs. {PRODUCT} {PRODUCT_VERSION} preserves the data type of the inputs on which the sum is executed. This enhancement provides a more accurate result from the sum function. In the following example, the result type of the accumulate function is `Long` instead of `double`:
+
[source,java]
----
Long(...) from accumulate(..., sum($p.getLongWeight()))
----
+
If the rules in your {PRODUCT_OLD} 6.4 project include the sum function in an accumulate pattern, search for these functions and review them. These functions return a double data type in {PRODUCT_OLD} 6.4, but will return the data type of the input values in {PRODUCT} {PRODUCT_VERSION}.
* When no fact matches the accumulate pattern, `min` and `max` accumulate functions in {PRODUCT} {PRODUCT_VERSION} do not return `+/-Integer.MAX_VALUE`, but return `null`. Therefore, unlike in {PRODUCT_OLD} 6.4, the accumulate in the rule is not matched and the rule does not fire in {PRODUCT} {PRODUCT_VERSION}.
