[id='migration-about-con']

= About Patches, Updates, Upgrades, and Migrations

When you move from one Red Hat JBoss BRMS or Red Hat JBoss BPM Suite version to another, your Red Hat JBoss environment must be updated or upgraded (or both), then, if necessary, you must migrate your data.  This section describes the differences between patches, updates, upgrades, and migrations. Patches, upgrades, and updates usually require little or no work by the user, while migrations can involve a lot of work by the user. 

.Patches
Red Hat JBoss BRMS and Red Hat JBoss BPM Suite periodically provide individual patches that contain bug and security fixes. Patches are released outside of the scheduled product update cycle. The patch file name contains the jira or bug reference at the end, as follows:

--
`jar_name-version.Final-redhat-_version-BZ-0000000`
--

.Updates
Planned updates are cumulative updates of an existing product, which include all previously developed updates for that version of the product. Updates include bug fixes, security fixes, and new features and can include several patches. They increment the release by the third digit, for example from 6.0.0 to 6.0.1.

.Upgrades
An upgrade is when an application is moved from one major release to another, for example, from Red Hat JBoss BRMS 6.0 to Red Hat JBoss BRMS 6.1. 

.Migrations
Migrations involve moving data and other artifacts to a separate software environment. When a move requires an update or upgrade as well as a migration, the process is referred to as migrating. Migrations usually include upgrades or updates. 

This guide provides instructions for moving between various versions of Red Hat JBoss BRMS and Red Hat JBoss BPM Suite. Patch updates are not covered in this guide. For information about patches, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_bpm_suite/6.4/html-single/installation_guide/[_Red Hat JBoss BPM Suite Installation Guide_].