[id='migration-execution-server-con']
= Migrating {CENTRAL} as design environment and execution server

In {PRODUCT} {PRODUCT_VERSION}, {CENTRAL} no longer has execution server capabilities nor any API endpoints related to the execution server. Instead, the {KIE_SERVER} performs all execution and runtime functions and {CENTRAL} is used for application development and management only. Therefore, if you use {CENTRAL} to design business assets and to manage live tasks and process instances through the built-in execution server, then follow the steps in this section to migrate to {PRODUCT} {PRODUCT_VERSION}.

If you use {CENTRAL} as a design environment only, with no execution server functionality, follow the migration steps in xref:migration-non-execution-server-con[]. A separate migration path is required when {CENTRAL} is not used as an execution server.

.Prerequisites
* {PRODUCT} {PRODUCT_VERSION} is installed on a separate instance from {PRODUCT_OLD} 6.4 (on {EAP} or other instance). For installation options, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].
* All {CENTRAL} data for {PRODUCT_OLD} 6.4, including a database used with it (if applicable), has been fully backed up. This is a precaution in case of problems during migration.
