[id='migration-projects-manual-proc']

= Migrating projects manually

If you encounter errors that you cannot resolve when using Red Hat's project migration tool, you can manually restructure your `.niogit` directory for {PRODUCT_OLD} 6.4 and import each project repository individually to {PRODUCT} {PRODUCT_VERSION}.

.Prerequisite
* {CENTRAL} is not running for either {PRODUCT_OLD} 6.4 or {PRODUCT} {PRODUCT_VERSION}.
* All {CENTRAL} project data is backed up, as a precaution.

.Procedure
. Navigate to the `.niogit` directory of your current {CENTRAL} distribution for {PRODUCT_OLD} and open one of the `$RESPOSITORY.git` repository folders.
. Clone the repository into a new folder, as a precaution:
+
[source]
----
$ git clone git $REPOSITORY_PATH $FOLDER
----
. In the cloned folder, find a project that you want to migrate and copy the directory to another folder.
. Initialize the copied project as a new Git repository
[source]
----
git init && git commit -A -m 'Copy project X'`
----
. Start {PRODUCT} {PRODUCT_VERSION} depending on your installation (for example, `$EAP_HOME/bin/standalone.sh -c standalone-full.xml`) and log in with your credentials.
. In {CENTRAL}, navigate to *Menu* -> *Design* -> *Projects* and select or create the space into which you want to import the projects. The default space is *MySpace*.
. Click the three vertical dots in the upper-right corner of the screen and select *Import Project*.
. For the *Repository URL*, enter the path to one of the repositories in your `.niogit` directory in the following format:
+
--
[source]
----
file:///$NIOGIT_DIR/$REPOSITORY.git
----
For example, if the location of the `.niogit` directory is `/opt/eap7.0/bin/.niogit` and you want to import a project from the `repository1` repository, you would enter the following path:

[source]
----
file://opt/eap7.0/bin/.niogit/repository1.git
----
--
. Click *Import*, select the project to import, and click *Import*.
. After the importing and indexing is complete, repeat these importing steps for each repository that you want to add to {PRODUCT} {PRODUCT_VERSION}.

.`NoRemoteRepositoryException`
[NOTE]
====
If during the import a `NoRemoteRepositoryException` error appears, you can temporarily remove the repository remotes in your terminal.

For example:

[subs="verbatim,macros"]
----
$ ~/opt/eap7.0/bin/.niogit/repository1.git
$ git remote -v
origin  https://github.com/guvnorngtestuser1/guvnorng-playground (fetch)
origin  https://github.com/guvnorngtestuser1/guvnorng-playground (push)
$ git remote remove origin
----

Then import the projects again. You can add the remotes in the new repository later if necessary (`git remote add $REPOSITORY_URL`).
====
