[id='migration-configure-kie-server-proc']
= Configure and start {KIE_SERVER}

After you have migrated all {CENTRAL} data and have upgraded the relevant database, configure and start the new {KIE_SERVER} to transfer the execution server functionality and apply the migrated changes.

.Prerequisites
* Project data from {PRODUCT_OLD} 6.4 has been migrated using the {CENTRAL} migration tool.
* The {PRODUCT_OLD} 6.4 database to be used with {PRODUCT} {PRODUCT_VERSION} has been upgraded.
* All API references to {CENTRAL} execution server in application code have been redirected to the {KIE_SERVER}.

.Procedure
Navigate to the {PRODUCT} {PRODUCT_VERSION} `bin` directory and start the new {KIE_SERVER} with the following properties. Adjust the specific properties according to your environment.

[source]
----
$ ~/EAP_HOME/bin/standalone.sh - c server-config=standalone-full.xml <1>
-Dorg.kie.server.id=myserver <2>
-Dorg.kie.server.controller=http://localhost:8080/business-central/rest/controller <3>
-Djboss.socket.binding.port-offset=150 <4>
-Dorg.kie.server.location=http://localhost:8230/kie-server/services/rest/server <5>
-Dorg.kie.server.persistence.dialect=org.hibernate.dialect.PostgreSQLDialect <6>
-Dorg.kie.server.persistence.ds=java:jboss/datasources/psjbpmDS <7>
----
<1> Start command with `standalone-full.xml` server profile
<2> Server ID that must match the server template name defined in {CENTRAL}
<3> Controller location, {CENTRAL} URL with `/rest/controller` suffix
<4> Port offset for {KIE_SERVER} location, to avoid port conflicts (not needed if {KIE_SERVER} already uses a separate port)
<5> {KIE_SERVER} location (including defined port offset, if applicable)
<6> Hibernate dialect to be used
<7> JNDI name of the data source used for your previous {PRODUCT_OLD} database

*<@Maciej (2 of 2): Are #4 and #5 in the above properties correct now? Regarding {KIE_SERVER} location. These properties all correct overall now?>*

{KIE_SERVER} connects to the new {CENTRAL} and collects the list of KIE containers to be deployed.
