[id='migration-troubleshooting-ref_{context}']

ifeval::["{context}" == "non-exec-server"]
= Troubleshooting {CENTRAL} migration problems

If you encounter problems with your {CENTRAL} migration to {PRODUCT} {PRODUCT_VERSION}, review the following troubleshooting suggestions:

* If any project data is missing from {CENTRAL}, ensure that the `.niogit` directory for {PRODUCT} {PRODUCT_VERSION} contains the restructured data and is in the correct installation location for {PRODUCT} {PRODUCT_VERSION} (for example, `~/$EAP_HOME/bin/`).
* If projects fail to build in {CENTRAL}, open the project `pom.xml` file and remove the `http://localhost:8080/business-central/maven2/` repository, if present. This repository can prevent projects from building properly in {PRODUCT} {PRODUCT_VERSION}.
+
--
*<@Alex: Why would this repo be present, i.e., where does it come from? Why is it an issue in PAM/DM? And what if users have a project they need in this repo? We tell them to just remove it, but no one can tell me why this repo is problematic and what users should do if it has important contents. Thoughts?>*

Example repository to be removed from `pom.xml` file:

[source]
----
<repository>
  <id>guvnor-m2-repo</id>
  <name>Guvnor M2 Repo</name>
  <url>http://localhost:8080/business-central/maven2/</url>
</repository>
----
--
* If projects fail to deploy to {KIE_SERVER}, review your {KIE_SERVER} installation and configuration. For more information, see Planning the {PRODUCT} {PRODUCT_VERSION} installation.
//@link: Update install link above.
* If you encounter other migration problems, review xref:migration-other-changes-con[].
* If you cannot resolve migration problems, complete the migration process again on a new {PRODUCT} {PRODUCT_VERSION} installation.
endif::[]

ifeval::["{context}" == "exec-server"]
= Troubleshooting {CENTRAL} migration problems

If you encounter problems with your {CENTRAL} migration to {PRODUCT} {PRODUCT_VERSION}, review the following troubleshooting suggestions:

* If any project data is missing from {CENTRAL}, ensure that the `.niogit` directory for {PRODUCT} {PRODUCT_VERSION} contains the restructured data and is in the correct installation location for {PRODUCT} {PRODUCT_VERSION} (for example, `~/$EAP_HOME/bin/`).
* If projects fail to build in {CENTRAL}, open the project `pom.xml` file and remove the `http://localhost:8080/business-central/maven2/` repository, if present. This repository can prevent projects from building properly in {PRODUCT} {PRODUCT_VERSION}.
+
--
Example repository to be removed from `pom.xml` file:

[source]
----
<repository>
  <id>guvnor-m2-repo</id>
  <name>Guvnor M2 Repo</name>
  <url>http://localhost:8080/business-central/maven2/</url>
</repository>
----
--
* If projects fail to deploy to {KIE_SERVER}, review your {KIE_SERVER} installation and configuration. For installation information, see Planning the {PRODUCT} {PRODUCT_VERSION} installation. For configuration information, see xref:migration-configure-kie-server-proc[].
//@link: Update install link above.
* If you encounter other migration problems, review xref:migration-other-changes-con[].
* If you cannot resolve migration problems, complete the migration process again on a new {PRODUCT} {PRODUCT_VERSION} installation.
endif::[]
