[id='migration-tool-niogit-7.0-proc_{context}']

= Using the migration tool on a `.niogit` directory

The `.niogit` directory of your {CENTRAL} distribution contains all {CENTRAL} data. You can use the {CENTRAL} migration tool on your `.niogit` directory to prepare project data and system configurations for migration to {PRODUCT} {PRODUCT_VERSION}.

.Prerequisites
* {CENTRAL} is not running for either {PRODUCT_OLD} 6.4 or {PRODUCT} {PRODUCT_VERSION}.
* Java 8 is installed and is available on the path where the project migration tool will be installed.

.Procedure
. Locate the `bin/.niogit` directory in your current {CENTRAL} distribution for {PRODUCT_OLD} 6.4 and locate the same directory in your new {PRODUCT} {PRODUCT_VERSION} installation.
+
--
Example:
[source]
----
$ ~/$JBOSS_HOME/bin/.niogit
----

ifdef::PAM[]
[source]
----
$ ~/$RHPAM_HOME/bin/.niogit
----
endif::PAM[]
ifdef::DM[]
[source]
----
$ ~/$RHDM_HOME/bin/.niogit
----
endif::DM[]
--
. In your command terminal, copy the `.niogit` directory from your current {CENTRAL} distribution for {PRODUCT_OLD} 6.4 to the `bin` folder of the new {PRODUCT} {PRODUCT_VERSION} installation directory:
+
--
ifdef::PAM[]
[source]
----
cp -r /$JBOSS_HOME/bin/.niogit  /$RHPAM_HOME/bin/
----
endif::PAM[]
ifdef::DM[]
[source]
----
cp -r /$JBOSS_HOME/bin/.niogit  /$RHDM_HOME/bin/
----
endif::DM[]

The copied `.niogit` folder is the directory that the migration tool will prepare for {PRODUCT} {PRODUCT_VERSION}. The original `.niogit` folder remains in your {PRODUCT_OLD} 6.4 installation and will not be modified by the migration tool in this procedure.
--
. In the {PRODUCT} {PRODUCT_VERSION} `bin` directory, delete the `.index` directory. You must delete this folder because {PRODUCT} {PRODUCT_VERSION} comes with certain updates that are not compatible with {PRODUCT_OLD} 6.4. The `bin` directory will be re-indexed after the migration when you start {PRODUCT} {PRODUCT_VERSION}.
. Note the path to the copied `.niogit` directory for {PRODUCT} {PRODUCT_VERSION}. The path will be required when you run the migration tool.
. If you have specific `dependencies`, `repositories`, or `pluginRepositories` that you want to add, remove, or update as part of the project migration, create a `pom-migration.json` file containing these elements. When you run the migration tool, the tool will prompt you if you want to include this file in the migration.
+
--
The `pom-migration.json` file requires the following sections:

* `"dependencies":[]`
* `"repositories-add":[]`
* `"repositories-remove":[]`
* `"repositories-update-urls":[]`
* `"pluginRepositories-add":[]`
* `"pluginRepositories-remove":[]`
* `"pluginRepositories-update-urls":[]`


If any of these elements do not apply to your project, include them as empty sections to prevent parsing errors.

Example `pom-migration.json` file:

[source,json,subs="attributes+"]
----
{
  "dependencies":[

    {"groupId":"junit", "artifactId":"junit", "version":"4.12", "scope":"test"},
    {"groupId":"com.thoughtworks.xstream", "artifactId":"xstream", "version":"4.12", "scope":"test"}

  ],

  "repositories-add":[
    {
      "id":"jboss-public-repository-group",
      "name":"JBoss Public Repository Group",
      "url":"http://repository.jboss.org/nexus/content/groups/public/",
      "releasesEnabled":true,
      "releasesUpdatePolicy":"never",
      "snapshotEnabled":true,
      "snapshotUpdatePolicy":"never"
    },
    {
      "id":"kie-internal-staging-repository-group",
      "name":"KIE Internal Staging Repositories",
      "url":"https://origin-repository.jboss.org/nexus/content/groups/kie-internal-group",
      "releasesEnabled":true,
      "releasesUpdatePolicy":"never",
      "snapshotEnabled":false,
      "snapshotUpdatePolicy":"never"
    }
  ],

  "repositories-remove":[
    {
      "id":"productization-repository", "url":"http://download.lab.bos.redhat.com/brewroot/repos/jb-ip-6.1-build/latest/maven/"
    }
  ],

  "repositories-update-urls":[
    {
      "id":"guvnor-m2-repo", "url":"http://localhost:8080/{URL_COMPONENT_CENTRAL}/maven3/"
    }
  ],

  "pluginRepositories-add":[

    {
      "id":"jboss-public-repository-group",
      "name":"JBoss Public Repository Group",
      "url":"http://repository.jboss.org/nexus/content/groups/public/",
      "releasesEnabled":true,
      "releasesUpdatePolicy":"never",
      "snapshotEnabled":true,
      "snapshotUpdatePolicy":"never"
    },
    {
      "id":"kie-internal-staging-repository-group",
      "name":"KIE Internal Staging Repositories",
      "url":"https://origin-repository.jboss.org/nexus/content/groups/kie-internal-group",
      "releasesEnabled":true,
      "releasesUpdatePolicy":"never",
      "snapshotEnabled":false,
      "snapshotUpdatePolicy":"never"
    }

  ],
  "pluginRepositories-remove":[],
  "pluginRepositories-update-urls":[]
}
----

Example `pom-migration.json` file with `dependencies` only:

[source,json]
----
{
  "dependencies":[

    {"groupId":"junit", "artifactId":"junit", "version":"4.12", "scope":"test"},
    {"groupId":"com.thoughtworks.xstream", "artifactId":"xstream", "version":"4.12", "scope":"test"}

  ],
  "repositories-add":[],
  "repositories-remove":[],
  "repositories-update-urls":[],
  "pluginRepositories-add":[],
  "pluginRepositories-remove":[],
  "pluginRepositories-update-urls":[]
}
----
--
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons* and extract the downloaded `{PRODUCT_FILE}-add-ons.zip` file to a temporary directory.
. In the extracted `{PRODUCT_FILE}-add-ons` folder, extract the `{PRODUCT_INIT}-{PRODUCT_VERSION}-migration-tool.zip` sub-folder. The migration tool is in the `bin` directory.
. In your command terminal, navigate to the temporary directory where you extracted the `{PRODUCT_INIT}-{PRODUCT_VERSION}-migration-tool` folder and run the migration tool. The `${PRODUCT_INIT_CAP}_NIOGIT_DIR` portion is the path to the `.niogit` directory that you previously copied to the {PRODUCT} {PRODUCT_VERSION} installation.
+
--
On Linux or UNIX-based systems:
[source]
ifdef::PAM[]
----
$ cd $INSTALL_DIR/rhpam-7.0-migration-tool/bin
$ ./migration-tool.sh -t $RHPAM_NIOGIT_DIR
----
endif::PAM[]
ifdef::DM[]
----
$ cd $INSTALL_DIR/rhdm-7.0-migration-tool/bin
$ ./migration-tool.sh -t $RHDM_NIOGIT_DIR
----
endif::DM[]

On Windows:
[source]
ifdef::PAM[]
----
$ cd $INSTALL_DIR\rhpam-7.0-migration-tool\bin
$ migration-tool.bat -t $RHPAM_NIOGIT_DIR
----
endif::PAM[]
ifdef::DM[]
----
$ cd $INSTALL_DIR\rhdm-7.0-migration-tool\bin
$ migration-tool.bat -t $RHDM_NIOGIT_DIR
----
endif::DM[]

In the command prompt that appears, the following options are displayed:

* *Project structure migration*: Migrates the {PRODUCT_OLD} 6.4 project repository structure to the new project-oriented structure used in {PRODUCT} {PRODUCT_VERSION}.
* *System configuration directory structure migration*: Migrates the `system.git` repository structure used in {PRODUCT_OLD} 6.4 to the new structure used in {PRODUCT} {PRODUCT_VERSION}. This migration option requires the project structure migration to be executed first.
ifdef::PAM[]
* *Forms migration*: Migrates forms created in the {PRODUCT_OLD} 6.4 forms designer to the new forms designer. This migration option requires the project structure migration and system configuration directory structure migration to be executed first.
* *POMs migration:* Updates `pom.xml` files with dependencies required for {PRODUCT} {PRODUCT_VERSION}. This migration option requires the project structure migration, system configuration directory structure migration, and forms migration to be executed first.
endif::PAM[]
ifdef::DM[]
* *POMs migration:* Updates `pom.xml` files with dependencies required for {PRODUCT} {PRODUCT_VERSION}. This migration option requires the project structure migration and system configuration directory structure migration to be executed first.
endif::DM[]
* *All:* Runs all migration options in sequence.
* *Exit:* Exits the migration tool.
--
. Select the option to run *All* migrations in sequence.
+
NOTE: If you prefer to run one migration option at a time, select and run the first individual migration option. After the tool runs, re-run the {CENTRAL} migration tool and select the next individual migration option in the sequence.
+

. Enter `yes` each time you are prompted to run a specific migration option.
+
For the POMs migration option, if you want to include a path to an external `pom-migration.json` file that you created previously, enter `yes` when prompted and enter the path.
+
. After the tool finishes running, enter the option to *Exit* the migration tool.
+
The `.niogit` directory structure is now compatible with {CENTRAL} in {PRODUCT} {PRODUCT_VERSION}. Project directories are in separate repositories and all other related configurations have been migrated. You can navigate to the new `.niogit` directory to inspect the restructured contents.
