[id='migration-non-execution-server-con']
ifdef::DM[]
= Migrating {CENTRAL} data

You must migrate your {CENTRAL} data from {PRODUCT_OLD} 6.4 to {PRODUCT} {PRODUCT_VERSION} using the {CENTRAL} migration tool provided with this release to accommodate a new data structure in {PRODUCT} {PRODUCT_VERSION}. You must also update the database configured for {PRODUCT_OLD} 6.4 using one of the upgrade scripts provided with this release to accommodate a database schema change {PRODUCT} {PRODUCT_VERSION}.
endif::DM[]

ifdef::BA[]
= Migrating {CENTRAL} used as design environment only

Follow the migration steps in this section if you use {CENTRAL} to design decision services but do not use {CENTRAL} as an execution server with live tasks and process instances in {PRODUCT_OLD} 6.4.

If you use {CENTRAL} as both a designing environment and an execution server with live tasks and process instances, follow the migration steps in xref:migration-execution-server-con[]. A separate migration path is required to transfer execution server functionality to the {KIE_SERVER} for {PRODUCT} {PRODUCT_VERSION}, in addition to {CENTRAL} data.
endif::BA[]

.Prerequisites
* {PRODUCT} {PRODUCT_VERSION} is installed on a separate instance from {PRODUCT_OLD} (on {EAP} or other option). For installation options, see Planning the {PRODUCT} {PRODUCT_VERSION} installation.
//@link: Add link to insall planning doc.
* All {CENTRAL} data for {PRODUCT_OLD} 6.4, including a database used with it (if applicable), has been fully backed up. This is a precaution in case of problems during migration.
