[id='migration-verify-non-execution-server-proc']
= Verify the migration in {CENTRAL}

After you use the {CENTRAL} migration tool to migrate project data and you upgrade your {PRODUCT_OLD} 6.4 database, verify that the migration was successful in the new {CENTRAL} for {PRODUCT} {PRODUCT_VERSION}.

.Prerequisites
* Project data from {PRODUCT_OLD} 6.4 has been migrated using the {CENTRAL} migration tool.
* The database configured for {PRODUCT_OLD} has been upgraded.

.Procedure
. Start {PRODUCT} {PRODUCT_VERSION} depending on your installation.
+
Example: Installation with {EAP}
+
[source]
----
$ ~/$EAP_HOME/bin/standalone.sh
----
. Log in to {CENTRAL} with your credentials and review your projects and assets to ensure that the migration was successful.
+
If any project data is missing, ensure that the `.niogit` directory for {PRODUCT} {PRODUCT_VERSION} contains the restructured data and is in the correct installation location for {PRODUCT} {PRODUCT_VERSION} (example: `~/$EAP_HOME/bin/`).
+
If you cannot resolve migration problems, follow the migration process again on a new {PRODUCT} {PRODUCT_VERSION} installation.
