[id='environment-managed-modify-proc']
= Modifying a template for a managed environment

To adjust the managed environment to your needs, you need to modify the `rhpam70-sit.yaml` or `rhpam70-prod.yaml` template before deploying the environment.

By default, the templates create two replicated {KIE_SERVER} pods. You can deploy separate processes on each of the pods. To add more replicated {KIE_SERVER} pods, you need to modify the template before deploying the environment.

By default, the templates create a PostgreSQL pod to provide the database server for each replicated {KIE_SERVER}. If you prefer to use PostgreSQL or to use an external server (outside the OpenShift project), you need to modify the template before deploying the environment.

For the `rhpam70-prod.yaml` template you can also adjust the initial number of replicas for {CENTRAL} Monitoring.

include::modifytemplate-intro.adoc[]

Note that named blocks can be nested.

.Procedure

* If you want to add more replicated {KIE_SERVER} pods, repeat the following actions for every additional pod:
. Pick a number for the new pod. The default pods have the numbers `1` and `2`, so you can use `3` for the first new pod, then `4` and so on.
. Copy the following blocks of the file, marked with comments from `BEGIN` to `END`, into the end of the file:
*** `KIE server services 1`
*** `PostgreSQL service 1`
*** `KIE server routes 1`
*** `KIE server deployment config 1`
*** `PostgreSQL deployment config 1`
*** `PostgreSQL persistent volume claim 1`
. In the new copies, replace all instances of `-1` with the new pod number, for example, `-3`.

* If you want to use MySQL instead of PostgreSQL, replace several blocks of the file, marked with comments from `BEGIN` to `END`, with blocks from the `rhpam70-kieserver-postgresql.yaml` file, then modify some of the newly added blocks: 

. Replace the block named `MySQL database parameters` with the block named `PosgreSQL database parameters`. (Take this block and all subsequent replacement blocks from the `rhpam70-kieserver-postgresql.yaml` file.)
+
Repeat the following actions for every replicated {KIE_SERVER} pod number, for example, `1` and `2` in the unmodified template. `N` refers to the pod number, for example, `1`. 

*** Replace the block named `PosgreSQL service N` with the block named `MySQL service`.
*** Replace the block named `PosgreSQL driver settings N` with the block named `MySQL driver settings`.
*** Replace the block named `PosgreSQL deployment config N` with the block named `MySQL deployment config`.
*** Replace the block named `PosgreSQL persistent volume claim N` with the block named `MySQL persistent volume claim`.
*** In all the newly added blocks, make the following replacements manually, where `N` is the pod number:
**** `-mysql` with `-mysql-N`, _except_ in `-mysql-pvol` and in `-mysql-claim`
**** `-mysql-claim` with `-mysql-claim-N`

* If you want to use an external database server, replace several blocks of the file, marked with comments from `BEGIN` to `END`, with blocks from the `rhpam70-kieserver-externaldb.yaml` file, remove some blocks, and modify some of the newly added blocks: 

. Replace the block named `MySQL database parameters` with the block named `External database parameters`. (Take this block and all subsequent replacement blocks from the `rhpam70-kieserver-external.yaml` file.) 
+
Repeat the following actions for every replicated {KIE_SERVER} pod number, for example, `1` and `2` in the unmodified template. `N` refers to the pod number, for example, `1`. 

*** Remove the block named `PosgreSQL service N`
*** Remove the block named `PosgreSQL deployment config N` 
*** Remove the block named `PosgreSQL persistent volume claim N` 
*** Replace the block named `PosgreSQL driver settings N` with the block named `External database driver settings`.
*** In the new `External database driver settings` block, if any of the following values are different for different {KIE_SERVER} pods in the infrastructure, set the values for this particular pod:
**** `RHPAM_USERNAME`: The user name for logging in to the database server
**** `RHPAM_PASSWORD`: The password for logging in to the database server
**** `RHPAM_XA_CONNECTION_PROPERTY_URL`: The full URL for logging in to the database server
**** `RHPAM_SERVICE_HOST`: The host name of the database server
**** `RHPAM_DATABASE`: The database name

NOTE: The standard {KIE_SERVER} image includes drivers for MySQL and PostgreSQL external database servers.

* If you want to change the number of replicas initially created for {CENTRAL} Monitoring, on the line below the comment `## Replicas for Business Central Monitoring`, change the number of replicas to the desired value.

