[id='_business_central_login_proc']
= Logging in to {CENTRAL}
ifdef::PAM[]
After you have successfully installed and configured {EAP} and {Product}, and have started the {EAP} server, you can then access {CENTRAL} from a web browser to begin creating or managing business processes and rules.

.Prerequisites
* {EAP} is installed as described in the _{EAP} Installation Guide_ in the Red Hat https://access.redhat.com/products/red-hat-jboss-enterprise-application-platform/#getstarted[Customer Portal].
* {PRODUCT} is installed and users are configured as described in the {URL_INSTALLATION_GUIDE}#installing_red_hat_jboss_bpm_suite[_{INSTALLATION_GUIDE}_].
endif::PAM[]

ifdef::DM[]
After you have successfully installed and configured {EAP} and {Product}, and have started the {EAP} server, you can then access {CENTRAL} from a web browser to begin creating or managing business processes and rules.

.Prerequisites
* {EAP} is installed as described in the _{EAP} Installation Guide_ in our https://access.redhat.com/products/red-hat-jboss-enterprise-application-platform/#getstarted[Customer Portal].
* {PRODUCT} is installed and users are configured as described in the {URL_INSTALLATION_GUIDE}#installing_red_hat_jboss_brms[_{INSTALLATION_GUIDE}_].
endif::DM[]

.Procedure
. In a terminal application, navigate to `__EAP_HOME__/bin`.
. Run the standalone configuration:
** On Linux or UNIX-based systems:
+
[source,bash]
----
$ ./standalone.sh
----
** On Windows:
+
[source,bash]
----
standalone.bat
----
. In a web browser, open the URL `localhost:8080/business-central`. If the user interface has been configured to run from a domain name, substitute `localhost` for the domain name, for example:
+
http://www.example.com:8080/business-central

. Enter the user credentials that you created during installation. For example, enter the user name
ifdef::PAM[]
`bpmsAdmin`
endif::[]
ifdef::DM[]
`brmsAdmin`
endif::[]
and the password `password@1`.

If the web page is not found or fails to load, check your command line interface to ensure that the {EAP} has finished running successfully, then try to log in again. If the problem persists, ensure that the login credentials match those that you created during installation.
