[id='_business_central_con']
= {CENTRAL}

ifdef::PAM[]
{CENTRAL} is the web-based user interface for both {PRODUCT_PAM} and {PRODUCT_DM}. {CENTRAL} enables business analysts, developers, and administrators to manage business processes, process instances, reports, user tasks, notifications, and other business rule assets.

{CENTRAL} integrates the following tools:

* _Process Designer_ and other editors for modeling processes and their resources (such as an item editor, work item editor, or data model editor), as well as process model simulation tools  (see <<_chap_process_designer>>)
* _Rules Modeler_ for designing Business Rules models and their resources (see the Red Hat JBoss BRMS documentation)
* _Task client_ for managing and creating User Tasks (see <<_sect_user_tasks>>)
* _Process Manager_ for managing process instances (see <<_sect_process_instances>>)
* _Dashboard Builder_, the business activity monitoring (BAM) component, for monitoring and reporting (see <<_chap_red_hat_jboss_dashboard_builder>>)
* _Business Asset Manager_ for accessing the Knowledge Repository resources, building, and deploying business assets (see xref:projects-con_chap-project[].)

endif::PAM[]

ifdef::DM[]
{CENTRAL} is the web-based user interface for both {PRODUCT_DM} 6 and {PRODUCT_PAM} 6. {CENTRAL} allows business analysts, rule experts, developers, and rule administrators to manage rules in a multiuser environment and implement changes in a controlled fashion. {CENTRAL} has been combined with the core drools engine and other tools for optimal performance.

{CENTRAL} is most useful in the following cases:

* Users need to manage versions or deployment of rules.
* Multiple users of different skill levels need to access and edit rules.
* You need an infrastructure to manage rules.

{CENTRAL} has the following main features:

* Multiple types of rule editors (GUI, text) including:
** Guided Rule Editor
** Rule Templates
** Decision Tables
* Store multiple rule "assets" together as a package
* Domain Specific Language support
* Complex Event Processing support
* Version control (historical assets)
* Testing of rules
* Validation and verification of rules
* Categorization
* Build and deploy, including assembly of assets into a binary package for use with a ChangeSet or KnowledgeBuilder
* REST API to manipulate assets
endif::DM[]
