[id='kie-server-unified-execution-servers-proc']
= Unified Execution Servers

Since {PRODUCT} version 6.4, it is possible to configure both Business Central and the {KIE_SERVER} to use the same data source. This enables you to work with your processes using both applications. In such a setup, it is recommended to use Business Central for operations that require a graphical user interface and the {KIE_SERVER} for all remote calls.

When configuring unified execution servers, the {KIE_SERVER} must be managed by Business Central according to <<_managed_decision_server>>, and the following system properties need to be set:

* On Red Hat JBoss EAP, modify the `<system-properties>` section in:
** `_EAP_HOME_/standalone/configuration/standalone*.xml` for standalone mode.
** `_EAP_HOME_/domain/configuration/domain.xml` for domain mode.
* On Red Hat JBoss Web Server, see <<_decision_server_tomcat>>.
* On {WEBSPHERE}, see the {URL_IBM_GUIDE}#add_custom_jvm_properties[Adding Custom JVM Properties] section of the _{IBM_GUIDE}_.
* On {WEBLOGIC}, see the {URL_ORACLE_GUIDE}#setting_environment_variables[Setting Environment Variables] section of the _{ORACLE_GUIDE}_.


.JVM Properties for Unified Execution Servers
[cols="1,1,1a", options="header"]
|===
| Property
| Value
| Note

| `org.kie.server.persistence.ds`
| Example: `java:jboss/datasources/ExampleDS`
| The example data source works on Red Hat JBoss EAP only, and should be used strictly for evaluation purposes. It is the default configuration for Red Hat JBoss EAP. For a production environment, use a different, suitable data source.

| `org.kie.server.persistence.dialect`
| Example: `org.hibernate.dialect.H2Dialect`
| The example value works for the `java:jboss/datasources/ExampleDS` data source. Select a dialect based on your data source.

| `org.kie.executor.jms.queue`
| `queue/KIE.SERVER.EXECUTOR`
| Job executor JMS queue for {KIE_SERVER}.

|===

[WARNING]
====
The following restrictions apply:

* The Container ID must be the same as the deployment unit ID.
* The *SINGLETON* runtime strategy cannot be used.
* Triggering the execution of a part of a single process instance, between two safe points, on both the execution servers results in a successful execution on the first execution server only. The other execution server will throw an exception and will not modify the process data in the database.

Do not deploy both Business Central and Intelligent Process Server in the same application server in a production environment. Deploying both Business Central and Intelligent Process Server in the same application server is only applicable for development environments. Furthermore, unified execution settings require the exact same configurations (such as database, scheduler, executor, KJAR deployments, and so on) regardless of whether the deployment uses a single application server or not.
====
