[id='_installing_different_containers']
= Installing {KIE_SERVER} in Other Containers

[id='_decision_server_tomcat']
== Red Hat JBoss Web Server 2.__X__/3.__X__, Tomcat 8.__X__/9.__X__

Use the following procedure to install the {KIE_SERVER} in a Tomcat container.

. Follow the steps described in section
ifdef::PAM[]
{URL_INSTALLATION_GUIDE}#sect_the_generic_deployable_bundle_installation[Generic Deployable Bundle Installation]
endif::PAM[]
ifdef::DM[]
{URL_INSTALLATION_GUIDE}#installing_jboss_brms_on_jboss_ews_2[Installing Red Hat JBoss BRMS on Red Hat JBoss Web Server]
endif::DM[]
of _{INSTALLATION_GUIDE}_ to download and extract the generic deployable archive containing `kie-execution-server.war`.

. Configure users and roles. Make sure that the `__TOMCAT_HOME__/conf/tomcat-users.xml` file contains the following role and user definition. The user name and password should be unique, however, the role must be defined as `kie-server`:
+
[source,xml]
----
<role rolename="kie-server"/>
<user username="serveruser" password="my.s3cr3t.pass" roles="kie-server"/>
----

. Start the server: run `__TOMCAT_HOME__/bin/startup.sh` or in a Windows system `__TOMCAT_HOME__/bin/startup.bat`. To make sure that the application was deployed successfully, see Tomcat logs in the `__TOMCAT_HOME__/logs` directory. See <<_bootstrap_switches>> for the list of bootstrap switches that can be used to properly configure the instance. For example:
+
[source]
----
$ ./startup.sh -Dorg.kie.server.id=first-kie-server -Dorg.kie.server.location=http://localhost:8080/kie-execution-server/services/rest/server
----

. To verify that the server is running, open `http://__SERVER__:__PORT__/kie-execution-server/services/rest/server/` in a web browser and enter the user name and the password specified before. You should see a simple XML message with basic information about the server.

[IMPORTANT]
====
It is not possible to use the JMS interface if the {KIE_SERVER} was installed on Tomcat or any other web container. The web container version of the WAR file contains only the REST interface.
====
