[id='maven-repo-using-proc']

= Setting Maven dependencies in your project

Projects contain the business assets that you develop in {PRODUCT} and are assigned to a space (for example, `myproject` within `myteam`). Projects also contain configuration files such as a Maven project object model file (`pom.xml`), which contains build, environment, and other information about the project, and a KIE module descriptor file (kmodule.xml), which contains the KIE Base and KIE Session configuration for the assets in the project.

In {PRODUCT}, each project is packaged as a Knowledge JAR (KJAR) file and deployed to a {KIE_SERVER} that runs the decision services, process applications, and other deployable assets (collectively referred to as services) from that KJAR file. These services are consumed at run time through an instantiated KIE container, or deployment unit. Project KJAR files are stored in a Maven repository and identified by three values: `GroupId`, `ArtifactId`, and `Version` (GAV). Projects are packaged automatically in {PRODUcT} as KJAR files with assigned GAV values.

You can use an external Maven repository (for example, Nexus) to set up an integration process. You can configure Business Central to push project files into the external repository instead of the built-in repository. You can still use Business Central to deploy projects on a test Process Server. However, in this process, other Process Servers (for example, staging and production) are not connected to Business Central. Instead, they retrieve the project KJAR files and any necessary dependencies from your Maven repository. You can progress the KJAR versions through your repository as necessary, in line with the integration process that you want to implement.

When you set up a {KIE_SERVER}, you can configure access to a Maven repository and then you can use the REST API of the server to load and start a KIE container (deployment unit) with the services from the project. 
{PRODUCT} projects are designed to be used with a {PRODUCT} Maven repository, available online or downloaded from the Red Hat Customer Portal. When you create a project, {CENTRAL} uses the Maven repositories that are configured for {CENTRAL}. However, you can use the Maven global or user settings to direct all {PRODUCT} projects to retrieve dependencies from the public {PRODUCT} repository by modifying the following files:

* The Maven `settings.xml` file. This file is included with the Maven repository available for download from the Red Hat Customer Portal. 
* The Maven project object model (POM) file (`pom.xml`).

The URL for the online {PRODUCT} Maven repository is `https://maven.repository.redhat.com/ga/`. 




