[id='using-server-templates']
= Using Server Templates

The Business Central management console allows you to manage multiple Intelligent Process Server instances through the *Server Templates* page, which can be access by clicking *Deploy* -> *Execution Servers*. The management console allows servers to integrate with Business Central for execution in two ways:

. Server management (that maintains server templates), allowing you to know what servers are available and their location.
. Intelligent Process Server client that interacts with remote servers.

Server management is used to collect information about:

* Server templates wherever a project is to be deployed, regardless of whether or not any remote servers exist. 
* Remote servers whenever Intelligent Process Server interaction is required, for example, start and `GET` operations. 

Where multiple server templates are available, you can choose which server template to interact with by selecting the corresponding box on the Server Templates screen. It is not important which server instance is to be used for the request, as long as one is available. Server templates that do not have any remote servers available will not be visible on the list of server templates. Where only one server template exists, it becomes the default for both deployment and runtime operations.

Use the following procedure to build and deploy server templates in process management.

*Prerequisite*

Import the project you want to work with into Business Central.

.Procedure

. Select the project to be deployed.
+
From the *Authoring* -> *Project Authoring* page, select the project you want to deploy.

. Build and deploy.
+
Click the *Build & Deploy* button in the top right corner of the *Project Authoring* page.
+
When the project is built and deployed, the following occurs depending on the number of templates used:

* ** One Template: **
** The template is selected as default.
** The artifact name is used as the container ID.
** The container is started by default.

* ** Multiple Templates: ** 
+
**An additional menu that allows you to select:**
+
** Container ID.
** Server template.
** Start container option.


. View running process instances.
+
You can now view and interact with the running process instances by selecting *Process Management* -> *Process Instances* from the Business Central menu.

