[id='security-management']
= Security Management

{PRODUCT} {RELEASE} introduces enhanced security features for Business Central that enable administrators to specify the home perspective for users, as well as control access to assets. For a detailed description of these new features, see the "Business Central Settings" section of the _{PRODUCT} User Guide_.

The set of permissions assigned to every user, role, and group is called the authorization or security policy. Every application contains a security policy which is used each time the system checks a permission. The security policy is stored in the `.niogit` file in the `security.git` repository.

The following files, located in the `WEB-INF/classes` directory under the application’s WAR structure, contain the default settings for new groups and specific roles:

[cols="1,2", options="header"]
.New group and role security policies
|===
|File |Sample content

|New group

`security-policy.properties`
|`default.permission.perspective.read=false
default.permission.perspective.read.HomePerspective=true
default.permission.perspective.create=false`

|Admin role

`security-module-admin.properties`
|`role.admin.permission.perspective.read=true
role.admin.permission.perspective.read.Dashboard=false`

|Analyst role

`security-module-analyst.properties`
|`role.analyst.permission.perspective.read=true
role.analyst.permission.perspective.read.Dashboard=false`

|Developer role

`security-module-developer.properties`
|`role.developer.permission.perspective.create=true
role.developer.permission.perspective.delete=true`

|Manager role

`security-module-manager.properties`
|`role.manager.permission.dashboard.manage=true
role.manager.permission.jar.download=false`

|Process Admin role

`security-module-process-admin.properties`
|`role.process-admin.permission.perspective.read.Tasks=true
role.process-admin.permission.perspective.read.TaskAdmin=true`

|User role

`security-module-user.properties`
|`role.user.permission.perspective.read.ProcessDefinitions=true
role.user.permission.perspective.read.ProcessInstances=true`

|===

The application's security policy is based on these property files. It is not possible to specify a security policy for a specific user. Users inherit the security policies of the roles and groups that they are assigned. You can specify the priority of a setting in the Security perspective. The priority is used if a role or group setting conflicts with another role or group assigned to a user.
