[id='security-management-install-proc.adoc']
= Security management installation and setup

{PRODUCT} provides two pre-installed security providers:

* Wildfly 11 / EAP 7 distribution - Both distributions use the Wildfly security provider configured for the use of the default `application-users.properties` `and application-roles.properties` default realm files.
* Tomcat distribution - This distribution uses the Tomcat security provider configured for the use of the `tomcat-users.xml` default realm file.

Review each provider’s documentation  and apply the concrete settings for the target deployment environment.
COMMENT: Where is this documentation? What does 'concrete' mean here.

Whether using a custom security provider or one of the available distributions, consider the following installation options:

* Enable the security management feature in an existing WAR distribution.
* Set up an installation in an existing or new project.

[NOTE]
====
If no security provider is installed, there will be no available user interface for managing the security realm. After a security provider is installed and setup, the user and group management features are automatically enabled in the Security perspective. For information about the Security perspective,  see the "Business Central Settings" section of the _{PRODUCT} User Guide_. 
====
