[id='proc-infinispan-persistence-enabling_{context}']
= Enabling Infinispan persistence for {PRODUCT} services

You can enable persistence for your {PRODUCT} services using https://infinispan.org/[Infinispan] to persist data, such as active process nodes and process instance variables, so that the data is preserved across application restarts. For {PRODUCT} persistence with Infinispan, you must have a an Infinispan Server installed and running in order to enable persistence.

.Prerequisites
* https://infinispan.org/[Infinispan Server] 11.0 or later is installed and running. For information about Infinispan installation and configuration, see the https://infinispan.org/documentation/[Infinispan documentation].

.Procedure
. Add the following dependencies to the `pom.xml` file of your {PRODUCT} project:
+
--
.On Quarkus
[source,xml,subs="attributes+,+quotes"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>infinispan-persistence-addon</artifactId>
  <version>__{PRODUCT_INIT_CAP}_VERSION__</version>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-infinispan-client</artifactId>
</dependency>
----

.On Spring Boot
[source,xml,subs="attributes+,+quotes"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>infinispan-persistence-addon</artifactId>
  <version>__{PRODUCT_INIT_CAP}_VERSION__</version>
</dependency>
<dependency>
  <groupId>org.infinispan</groupId>
  <artifactId>infinispan-spring-boot-starter-remote</artifactId>
  <version>__INFINISPAN_SPRING_BOOT_VERSION__</version>
</dependency>
----
--
. Add following property to the `src/main/resources/application.properties` file in your {PRODUCT} project to configure the connection to the Infinispan Server.
+
--
Replace the server host and port information according to your Infinispan Server installation.

.On Quarkus
[source]
----
quarkus.infinispan-client.server-list=localhost:11222
----

.On Spring Boot
[source]
----
infinispan.remote.server-list=127.0.0.1:11222
----
--

NOTE: As an alternative to enabling Infinispan persistence explicitly in {PRODUCT} services, you can use the {PRODUCT} Operator to install the Infinispan infrastructure and enable persistence for the service during deployment on OpenShift. For more information about enabling Infinispan persistence with the {PRODUCT} Operator, see
ifdef::KOGITO[]
{URL_DEPLOYING_ON_OPENSHIFT}#con-kogito-operator-with-infinispan_kogito-deploying-on-openshift[_{DEPLOYING_ON_OPENSHIFT}_].
endif::[]
ifdef::KOGITO-COMM[]
xref:con-kogito-operator-with-infinispan_kogito-deploying-on-openshift[].
endif::[]

For example {PRODUCT} services with Infinispan persistence, see the following example applications in GitHub:

* https://github.com/kiegroup/kogito-examples/tree/stable/process-infinispan-persistence-quarkus[`process-infinispan-persistence-quarkus`]: Example on Quarkus
* https://github.com/kiegroup/kogito-examples/tree/stable/process-infinispan-persistence-springboot[`process-infinispan-persistence-springboot`]: Example on Spring Boot
