[id='proc-jobs-service-security_{context}']
= Enabling {PRODUCT} Jobs Service security with OpenID Connect

For Quarkus-based {PRODUCT} services, you can use the https://quarkus.io/guides/security-openid-connect[Quarkus OpenID Connect adapter] with the {PRODUCT} Jobs Service to enable security using bearer token authorization. These tokens are issued by OpenID Connect and OAuth 2.0 compliant authorization servers such as https://www.keycloak.org/about.html[Keycloak].

IMPORTANT: This procedure applies only when you are using a locally cloned copy of the https://github.com/kiegroup/kogito-apps/tree/master/jobs-service[{PRODUCT} Jobs Service] repository in GitHub.

.Prerequisites
* You have cloned the https://github.com/kiegroup/kogito-apps/tree/master/jobs-service[{PRODUCT} Jobs Service] repository from GitHub.

.Procedure
. In a command terminal, navigate to the local clone of the {PRODUCT} Jobs Service repository and enter the following command to run the application with the required security properties:
+
--
.Run the Jobs Service with security properties
[source]
----
mvn clean compile quarkus:dev  -Dquarkus.profile=keycloak
----

The Jobs Service contains a Quarkus profile to encapsulate the security configuration, so if the service requires enabled security, you can specify the `quarkus.profile=keycloak` property at build time to enable the needed security. If the `keycloak` Quarkus profile is not added, the OpenID Connect extension is disabled.
--
. Navigate to the `src/main/resources/application.properties` file of the Jobs Service project and add the following properties:
+
--
.Required security properties in `applications.properties` file
[source]
----
%keycloak.quarkus.oidc.enabled=true
%keycloak.quarkus.oidc.tenant-enabled=true
%keycloak.quarkus.oidc.auth-server-url=http://localhost:8280/auth/realms/kogito
%keycloak.quarkus.oidc.client-id=kogito-jobs-service
%keycloak.quarkus.oidc.credentials.secret=secret
%keycloak.quarkus.http.auth.policy.role-policy1.roles-allowed=confidential
%keycloak.quarkus.http.auth.permission.roles1.paths=/*
%keycloak.quarkus.http.auth.permission.roles1.policy=role-policy1
----

NOTE: The `quarkus.oidc.enabled` only can be changed at build time, as can be seen in https://quarkus.io/guides/security-openid-connect#quarkus-oidc_configuration[Quarkus Oidc Configuration].
In case we need to enable/disable security at runtime, we can use the property `quarkus.oidc.tenant-enabled` for
that purpose.
The property `quarkus.oidc.enabled` would be set to true in build time, and the `quarkus.oidc.tenant-enabled` would be used to enable/disable authentication.

IMPORTANT: This support have been added to {PRODUCT} Job service configuration to allow enabling/disabling security on runtime.

Replace any property definitions with those of your specific environment, especially the following properties:

* `quarkus.oidc.auth-server-url`: The base URL of the OpenID Connect (OIDC) server, such as `https://localhost:8280/auth`. All other OIDC server page and service URLs are derived from this URL. If you work with Keycloak OIDC server, ensure that the base URL is in the following format: `https://__HOST__:__PORT__/auth/realms/__KEYCLOAK_REALM__`.
* `quarkus.oidc.client-id`: The client ID of the application. Each application has a client ID that is used to identify the application.
* `quarkus.oidc.credentials.secret`: The client secret for the application.
--
. In the same `application.properties` file, also configure the resources to be exposed and the required permissions for accessing the resources.
+
--

NOTE:  To enable security using quarkus.oidc.tenant-enabled property, the `quarkus.http.auth.permission' path and policy have to be also
well configured, specifying how the authentication have to be applied.

This example configuration enables only users with role `confidential` to access any endpoint.

For more information about configuring endpoints and permissions, see https://quarkus.io/guides/security#authorization-of-web-endpoints-using-configuration[Authorization of Web Endpoints using configuration] in the Quarkus documentation.

--
