[[_drools.releasenotesdrools.7.9.0]]

= What is New and Noteworthy in Drools 7.9

== Moved ExecutableCommand to KIE public API

Drools internal `ExecutableCommand` interface has been moved to KIE public API. It's now possible to create custom
executable commands without rely on internal interface.

A deprecated internal `ExecutableCommand` interface still exists for backward compatibility and will be removed in a
future release.

WARNING: Existing custom commands based on old internal interface that override `canRunInTransaction()` method will no
longer compile due to this change.

== Alpha Network Compiler

Drools now supports an optimization on evaluating alpha nodes which involves generating an intermediate class that gets compiled to evaluate the constraint faster.

It's highly experimental and it's supposed to work only with the new executable model system. To enable it use `drools.alphaNetworkCompiler` configuration key in the `KieModuleModel` configuration.

----
<kmodule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.drools.org/xsd/kmodule">
  <configuration>
    <property key="drools.alphaNetworkCompiler" value="true"/>
  </configuration>
</kmodule>
----

WARNING: The current implementation has problems with incremental compilation so don't use it together.