[[_drools.releasenotesdrools.7.12.0]]

= What is New and Noteworthy in Drools 7.12

== End of support for `drools-rhq-plugin` component

The `drools-rhq-plugin` component for monitoring {PRODUCT} using JBoss Operations Network is no longer supported because it is underutilized and has become outdated.

== Support for executable models in DMN projects

You can now use the `kie-maven-plugin` build component to generate DMN executable model classes and compile them in a {PRODUCT} project (`kjar`). This support increases compile time, run time, and development time for your DMN projects.

In a command terminal, navigate to your Maven project directory and run the following command to build the project from an executable model:

--
[source]
----
mvn clean install -DgenerateDMNModel=<VALUE>
----

Replace `<VALUE>` with one of three values:

* `YES`: Generates the executable model corresponding to the DMN files in the original project.
* `NO`: Does not generate the executable model.

For information about using executable rule models in Maven and Java projects, see <<executable-model-con_pmml-models>>.
