[[_drools.releasenotesdrools.7.7.0]]

= New and Noteworthy in Drools 7.7
:context: N&N-7.7

= Executable rule models for more efficient rule packaging

Executable rule models are embeddable models that provide a Java-based representation of a rule set for execution at build time. The executable model is a more efficient alternative to the standard asset packaging in {PRODUCT} and enables KIE containers and KIE bases to be created more quickly, especially when you have large lists of DRL (Drools Rule Language) files and other {PRODUCT} assets.

To enable executable rule models in your {PRODUCT} project, add the following dependency to your project:

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-model-compiler</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
----

After you add the dependency, to build your project from an executable model, run the following command:

[source]
----
mvn clean install -DgenerateModel=YES
----

For more information about executable rule models and execution options, see xref:executable-model-con_packaging-deploying[].
