[id='assembly_installing-dm-on-premise']

include::product-shared-docs/document-attributes.adoc[]

= Installing Decision Manager on Premise
// Context attribute is assembly specific and enables module reuse between assemblies.
:imagesdir: topics/product-shared-docs/images
:context: installing-dm-on-premise
include::product-shared-docs/author-group.adoc[]

// Purpose statement for the assembly
As a business analyst, you can use guided decision tables to define business rules in a wizard-led tabular format. These rules are compiled into Drools Rule Language (DRL) and form the core of the decision service for your project.

Red Hat JBoss Enterprise Application Platform 7.0 (JBoss EAP 7) is a certified implementation of the Java Enterprise Edition 7 (Java EE 7) Full and Web profile specifications. JBoss EAP provides preconfigured options for features such as high-availability clustering, messaging, and distributed caching. It also enables users to write, deploy, and run applications using the various APIs and services that JBoss EAP provides.

[NOTE]
====
This section describes configuring Business Central and Execution Server in the same container. In production environments, they are usually run in different containers.
====

Unlike previous versions of {PRODUCT}, the installation of version {PRODUCT_VERSION} {RELEASE} on EAP consists of multiple deployable ZIP files, each for one component of the product, to provide additional flexibility.

For information on how to install {EAP} 7.0.8 on your computer, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html-single/installation_guide/[{EAP} Installation Guide].

include::product-installation-guide/ba-dm-installing-con.adoc[leveloffset=+1]
include::product-installation-guide/ba-dm-supported-platforms-ref.adoc[leveloffset=+2]
include::product-installation-guide/ba-dm-supported-component-versions-ref.adoc[leveloffset=+2]
include::product-installation-guide/assembly_installing-on-eap.adoc[leveloffset=+1]

include::product-shared-docs/versioning-information.adoc[]
