[id='assembly_guided-decision-tables']

include::product-shared-docs/document-attributes.adoc[]

= Integrating {PRODUCT} applications in Entando DXP Platform
// Context attribute is assembly specific and enables module reuse between assemblies.
:imagesdir: topics/product-shared-docs/images
:context: integrating-with-entando
include::product-shared-docs/author-group.adoc[]

// Purpose statement for the assembly
As a business rules developer, you can integrate the applications you have built in {PRODUCT} with Entando App Builder 5.0. Entando provides an open-source, low-code Digital Experience (DXP) Platform for building modern web, mobile, and IoT applications. With Entando, you can create a custom user experience around your {PRODUCT} business assets and expand your application development strategy.

.Prerequisites
* Entando App Builder 5.0 is installed. For instructions, see Getting started with Entando App Builder.
* All necessary page models and pages have been set up in Entando App Builder. For instructions, see Getting started with Entando App Builder.
* {PRODUCT} {PRODUCT_VERSION} is installed. For installation options, see Planning a {PRODUCT} installation.
* A project with business assets has been created in {PRODUCT} and deployed to a {KIE_SERVER}. For instructions, see Packaging and deploying a project.
//@link: Add doc links above.

// Modules - concepts, procedures, refs, etc.
include::product-user-guide/entando-con.adoc[leveloffset=+1]

include::product-user-guide/entando-widgets-con.adoc[leveloffset=+1]

include::product-user-guide/entando-integrating-proc.adoc[leveloffset=+1]

include::product-user-guide/entando-app-building-proc.adoc[leveloffset=+1]

////
== Next steps
Customizing UI components in Entando
//@link: Doc link not yet available from Entando.
////

// Versioning info
include::product-shared-docs/versioning-information.adoc[]
