// IMPORTANT: For 1.10 and later, save each version release notes as its own module file in the release-notes folder that this `ReleaseNotesKogito<version>.adoc` file is in, and then include each version release notes file in the chap-kogito-release-notes.adoc after Additional resources of {PRODUCT} deployment on {OPENSHIFT} section, in the following format:
//include::release-notes/ReleaseNotesKogito<version>.adoc[leveloffset=+1]

[id="ref-kogito-rn-new-features-1.20_{context}"]
= Breaking changes in {PRODUCT} 1.20

== {PRODUCT} runtimes

=== Specific extension for decision table files

Historically all files with `.xls`, `.xlsx` and `.csv` extension are considered decision tables and parsed as such. In general this is a too strong assumption, breaking projects containing random Excel files that are not decision tables and generating spurious compile time errors. To prevent this problem this policy has been changed, considering and processing files as decision tables only if their extension is prepended with `.drl`. In other words only files with extensions `.drl.xls`, `.drl.xlsx` and `.drl.csv` will be compiled as decision tables.