[[_sect_formmodeler_formlayout]]
= Customizing form layout


When you need an extra customization level and have more control over the HTML that is displayed.
The form modeler provides the ability to edit the HTML directly. 

To use this functionality, the user have to specify that in the '`Form properties`' tab, 'Custom form layout' option and save. 

Now the form is displayed with the custom HTML.
To access this HTML editing, we click on the icon 'Edit' 

The HTML editor is displayed; the HTML code will define how the form has to be shown.
In this editor the user can directly create the HTML i locate the fields and labels with the syntax described below: 

$field{fieldName} for field identified fieldName

$label{fieldName} for field identified fieldName label

These expressions will be replaced by the field or label rendering when the form will be shown.

Form modeler also provides two ways to help in the form HTML creation.

* 'Insert form elements'
+ 
Two select: one for the fields and another for the labels.
Clicking on that, the field or label text is added to HTML.
These selects only show the form fields haven`'t been added yet. 
* 'Generate template based on'
+ 
This functionality generates the HTML using all fields (default, alignment fields or Not aligned) depending on the selected value and overwrite the HTML. 
