[id='maven-deployment']
= Using an external Maven repository to deploy a decision service

You can use an external Maven repository (for example, Nexus) to set up an integration process. You can configure {CENTRAL} to push decision service files into the external repository instead of the built-in repository.

You can still use {CENTRAL} to deploy decision services on a test {KIE_SERVER}. However, in this process, other {KIE_SERVER} (for example, staging and production) are not connected to {CENTRAL}. Instead, they retrieve the decision service KJAR files and any necessary dependencies from your Maven repository. You can progress the KJAR versions through your repository as necessary, in line with the integration process that you want to implement.

If you deploy a {KIE_SERVER} on OpenShift, you can configure it to load and start a decision service from a Maven repository automatically. 

If you deploy a {KIE_SERVER} on premises, you can configure access to a Maven repository when setting up the server. Then you can use the REST API of the server to load and start a decision service from the repository. A Maven project and a Java client library for automating the API calls are available.
