[id='service-deploy-manage-central-proc']
= Managing deployment of decision services in {CENTRAL}

You can use {CENTRAL} to manage deployment of decision services on one or more {KIE_SERVERS}. Each {KIE_SERVER} must be configured to connect to the {CENTRAL}.

A decision service always runs in a _container_ on a {KIE_SERVER}. You can create containers and start them on {KIE_SERVERS}; when you build and deploy a project, the container is created automatically. A container is always created in a particular server template.

You can also start, stop, and delete containers.

== Creating a container 

You can create a container from a decision service that was previously built in {CENTRAL}.

.Procedure

. In the main menu, click *Execution servers*.
. Under *Server templates*, select a template. 
. Under *KIE Containers*, click *Add Container*.
. {CENTRAL} displays a dialog. In the table in the dialog, select a GAV and click the *Select* button next to the GAV.
. If you want to start the service immediately, select the *Start container?* box.
. Click the *Finish* button.

.Result
A container is created for the service. This container is placed on the {KIE_SERVERS} that are configured for this server template. If you have selected *Start container?*, the service is started.

== Managing containers
When a container is started, the service in the container is available for use. You can start, stop, or remove containers with decision services as necessary.

.Procedure

. In the main menu, click *Execution servers*.
. Under *Server templates*, select a template. 
. Under *KIE Containers*, select a container.
. Click the *Start*, *Stop*, or *Remove* button.

IMPORTANT: You cannot remove a container that is running. To remove a running container, stop it and then remove it.

