[id='service-gav-setting-proc']
= Setting the Group ID, Artifact ID, and Version (GAV) values in a decision service 

When developing a decision service in {CENTRAL}, you can set the GAV in the project settings screen. 

These values are the identifier for the decision service in a Maven repository. In any deployment method the decision service is identitied by the GAV. This means that if you build a new version without changing the GAV, it automatically displaces the old version in a Maven repository and on any Decision Servers. However, if you change any value in the GAV (usually the version), the result is seen as a different artifact and can exist alongside the old version.

.Procedure
. In the main menu, click *Projects*. 
. Click the project name.
** Alternatively, click the *Add Project* button to create a new project.
. Click the *Settings* button.
. Modify the *Group ID*, *Artifact ID*, or *Version* fields as necessary. If you have deployed the decision service and are developing a new version, usually you need to increase the version number.
. Click the *Save* button.