// IMPORTANT: For 1.10 and later, save each version release notes as its own module file in the release-notes folder that this `ReleaseNotesKogito<version>.adoc` file is in, and then include each version release notes file in the chap-kogito-release-notes.adoc after Additional resources of {PRODUCT} deployment on {OPENSHIFT} section, in the following format:
//include::ReleaseNotesKogito.<version>/ReleaseNotesKogito.<version>.adoc[leveloffset=+1]

[id="ref-kogito-rn-new-features-1.24_{context}"]
= New features in {PRODUCT} 1.24

[role="_abstract"]
The following sections describe some of the new features or enhancements in {PRODUCT} 1.24.


== {PRODUCT} runtimes

=== {PRODUCT} change in DMN/Decisions code generated OAS/Swagger type names

In previous versions of {PRODUCT}, model-specific OAS/Swagger type names generated from DMN/Decisions models used a number-based format, for example `InputSet1`, `InputSet2`, etc.
However, this format has some limitations impacting external clients and external plugins across evolutions of the Kogito application being developed. For example, adding or removing DMN/Decisions models from your Kogito application does not guarantee a stable naming and ordering across evolutions of your Kogito application.

Starting from {PRODUCT} 1.24.0, the model-specific OAS/Swagger type names by default will now be based on the names of the DMN/Decisions models themselves, for example `InputSetLoan`, `InputSetValidation`, etc.
In the case two DMN/Decisions models share the same name, it will automatically fallback to the previous number-based format; in addition, the number-based format strategy now accounts for the DMN/Decisions models to be ordered by their namespace and name, to maximise stable naming results in the OAS/Swagger definitions file.

No change is required from a Kogito application development perspective.

We hope this is an effective convenience improvement, while integrating your Kogito-based application with external tools, clients, plugins.
For more information, see https://issues.redhat.com/browse/KOGITO-7154[KOGITO-7154].

////
== {PRODUCT} Operator and CLI

=== Improved/new bla bla

Description

== {PRODUCT} supporting services

=== Improved/new bla bla

Description

== {PRODUCT} tooling

=== Improved/new bla bla

Description
////
