[id='executing_process']
= Executing the *pizzaPlace* order process
Now that you have deployed the project, you can execute the project's defined functionality. For this example, you will

.Prerequisites

 * The {KIE_SERVER} is deployed and connected to the {PRODUCT}
 * You have deployed the *pizzaPlace* process

.Procedure

. Log in to {PRODUCT} and click *Menu* -> *Manage* -> *Process Definitions*.
. Click any where in the *pizzaPlace* row to view the process details.
. Click the *Diagram* tab to view the business process diagram in the editor.
. Click on the *X* in the upper-right corner to close the editor.
. Click *New Process Instance* to open the order form and input

. Click *Submit* to start a new process instance. After starting the process instance, the *Instance Details* view opens.
. Click on the *Diagram* tab to view the process flow within the process diagram. The state of the process will be highlighted as it moves through each task.
. Click *Menu* -> *Track* -> *Task Inbox*. This will take you to the order form.
