[id='glusterfs-reconfig-proc']
= Changing GlusterFS configuration

Check whether your OpenShift environment uses GlusterFS to provide permanent storage volumes. If it uses GlusterFS, to ensure optimal performance, tune your GlusterFS storage by changing the storage class configuration.

.Procedure

. To check whether your environment uses GlusterFS, run the following command:
+
[subs="verbatim,macros"]
----
oc get storageclass 
----
+
In the results, check whether the `(default)` marker is on the storage class that lists `glusterfs`. For example, in the following output the default storage class is `gluster-container`, which does list `glusterfs`:
+
[subs="verbatim,macros"]
----
NAME              PROVISIONER                       AGE
gluster-block     gluster.org/glusterblock          8d
gluster-container (default) kubernetes.io/glusterfs 8d
----
+
If the result has a default storage class that does not list `glusterfs` or if the result is empty, you do not need to make any changes. In this case, skip the rest of this procedure.

. To save the configuration of the default storage class into a YAML file, run the following command:
+
[subs="verbatim,macros"]
----
oc get storageclass <class_name> -o yaml >storage_config.yaml
----
+
Where `class-name` is the name of the default storage class. For example:
+
[subs="verbatim,macros"]
----
oc get storageclass gluster-container -o yaml >storage_config.yaml
----
+
. Edit the `storage_config.yaml` file:
.. Remove the lines with the following keys:
** `creationTimestamp`
** `resourceVersion`
** `selfLink`
** `uid`
.. On the line with the `volumeoptions` key, add the following two options: `features.cache-invalidation on, performance.nl-cache on`. For example:
+
[subs="verbatim,macros"]
----
volumeoptions: client.ssl off, server.ssl off, features.cache-invalidation on, performance.nl-cache on
----
+
. To remove the existing default storage class, run the following command:
+
[subs="verbatim,macros"]
----
oc delete storageclass <class_name>
----
+
Where `class-name` is the name of the default storage class. For example:
+
[subs="verbatim,macros"]
----
oc delete storageclass gluster-container
----
+
. To re-create the storage class using the new configuration, run the following command:
+
[subs="verbatim,macros"]
----
oc create -f storage_config.yaml
----
