[id='additional-server-managed-deploy-assy']
= Deploying an additional managed {KIE_SERVER} for an authoring or managed environment

ifdef::context[:parent-context: {context}]
:context: additional-server-managed
:LOCAL_CENTRAL: {CENTRAL}
:what_deploying: an additional managed {KIE_SERVER}
:what_deploying_brief: an additional managed {KIE_SERVER}

You can deploy an additional managed {KIE_SERVER} to an authoring or managed environment.  Deploy the server in the same project as the {LOCAL_CENTRAL} deployment.

If you deployed a single authoring environment using the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring.yaml` template, you must enable the `OpenShiftStartupStrategy` setting for your environment for the {LOCAL_CENTRAL} to connect to the {KIE_SERVER}. For instructions about enabling the `OpenShiftStartupStrategy` setting, see <<startupstrategy-enable-proc>>. You do not need to complete this procedure for a high-availability authoring environment.

The {KIE_SERVER} loads services from a Maven repository. You must configure the server to use either the {CENTRAL} built-in repository or an external repository.

The server starts with no loaded services. Use {LOCAL_CENTRAL} or the REST API of the {KIE_SERVER} to deploy and undeploy services on the server.

include::template-deploy-start-proc.adoc[leveloffset=+1]
include::template-deploy-mandatory-proc.adoc[leveloffset=+1]
include::template-deploy-namespace-proc.adoc[leveloffset=+1]
include::template-deploy-connectcentral-proc.adoc[leveloffset=+1]
include::template-deploy-nopubnet-proc.adoc[leveloffset=+1]
include::template-deploy-rhsso-proc.adoc[leveloffset=+1]
include::template-deploy-ldap-proc.adoc[leveloffset=+1]
include::template-deploy-prometheus-proc.adoc[leveloffset=+1]
include::template-deploy-complete-proc.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
