[id='apb-deploy-proc']
= Deploying a {PRODUCT} environment using the Automation Broker

To deploy a {PRODUCT} environment using the Automation Broker, you must find the Ansible Playbook in the OpenShift catalog, run it, and set the parameters as required. 

.Procedure

. In the OpenShift Web UI, select *Add to Project -> Browse Catalog*.

. In the search field, type *{PRODUCT}*.

. Select the *{PRODUCT} {PRODUCT_VERSION} APB* catalog entry.

. Click *Next*.

. Select the required architecture elements, as described on the screen, and click the *Next* button.
+
IMPORTANT: If you want to deploy an environment with immutable servers and a monitoring infrastructure, you must first install the *Immutable Server - Monitor* option and then the *Immutable Server - KIE Process Server* option.

. Enter the parameters as described on the screen. In most cases, the default values lead to a working deployment; you can modify them as necessary. You must enter the following settings:
+
** For the *Immutable Server - Monitor* option:
+
*** The *Maven repository URL* field. You must provide a Maven repository with the same versions of all the artifacts that are deployed on any monitored immutable servers.
*** The *Admin password* field. You must record the administrative user name and password to configure monitored servers to connect to {CENTRAL} Monitoring.
+
** For the *Immutable Server - KIE Process Server* option:
*** The *KIE Server Container Deployment*, *Git Repository URL*, and *Git Repository Reference* fields. These settings determine the source code that the deployment process builds and deploys on the {KIE_SERVER}.
*** If you deployed the *Immutable Server - Monitor* option and want to connect the server to the monitoring infrastructure:
**** Under *Router integration*, the service name of the `rhpam-immutable-mon-smartrouter` service.
**** Under *Controller integration*, the service name of the `rhpam-immutable-mon-rhpamcentrmon` service and the admin username and password that you set in the *Immutable Server - KIE Process Server* option.
+
[IMPORTANT]
====
Avoid each of the following combinations of settings. These combinations produce an invalid environment.

* *Process server*>**Database type** `H2` and *Process server*>**Number of replicas** exceeding `1`.
* *Process server*>**Database type** `External` and *Process server*>**Sets of Process Servers** exceeding `1`.
* *Red Hat - Single Sign-On* configured and  *Process server*>**Sets of Process Servers** exceeding `1`.
====
+
. Click *Next* to commence deployment.
+
After deploying the environment, you can access it using the HTTPS routes displayed in the OpenShift Web console. HTTP requests are redirected to HTTPS.

IMPORTANT: After deploying the service, you can scale the {KIE_SERVER} pods up and down as necessary. Do not scale the database pods.
