[id='customimage-bc-githooks-proc_{context}']
:componentimage: businesscentral
:component: {CENTRAL}
= Creating a custom {CENTRAL} image with Git hooks

You can create a custom {CENTRAL} image that embeds Git hooks. In an authoring environment, you can use Git hooks to facilitate interaction between the internal Git repository of {CENTRAL} and an external Git repository. 

[NOTE]
====
You can also provide Git hooks using a persistent volume or configuration map. For instructions about this method of providing Git hooks, see xref:operator-deploy-central-proc[].
====

.Procedure

. Prepare the necessary Git hooks script files. This example shows one script file names `pre-commit`. You cam use as many files as necessary. Ensure that the execute permission is set for all script files.
. If necessary, prepare an `.ssh` directory to enable access to the Git repository using SSH keys. 
include::customimage-download-step.adoc[]
. Create a `Dockerfile` that defines a custom image based on the base image. The file must copy the script files into the `/opt/kie/data/git/hooks/` directory. If you prepared an `.ssh` directory, the file must copy it into the `/home/jboss` directory. The following example shows the content of the `Dockerfile` file:
+
[subs="attributes,verbatim,macros,quotes"]
----
FROM registry.redhat.io/{PRODUCT_INIT}-7/{PRODUCT_INIT}-businesscentral-rhel8:{ENTERPRISE_VERSION_LONG}
COPY pre-commit /opt/kie/data/git/hooks/
COPY .ssh /home/jboss/.ssh/
----
+
include::customimage-build-step.adoc[]
include::customimage-verify-partstep.adoc[]
In the shell prompt for the image, list the contents of the `/opt/kie/data/git/hooks/` directory:
+
[subs="attributes,verbatim,macros,quotes"]
----
[jboss@c2fab36b778e ~]$ ls /opt/kie/data/git/hooks/
pre-commit
[jboss@c2fab36b778e ~]$ exit
----
+
include::customimage-push-step.adoc[]

.Next steps

include::customimage-nextsteps.adoc[]

During the same deployment, under *GitHooks*, in the *Mount path* field enter `/opt/kie/data/git/hooks/`. Do not enter anything in the fields under *GitHooks Configuration object*.

For instructions about deploying {CENTRAL} using the operator, see xref:operator-deploy-central-proc[].