[id='customimage-smartrouter-proc_{context}']
:componentimage: smartrouter
:component: Smart Router
= Creating a custom Smart Router image with an additional JAR file to implement custom routing

By default, Smart Router routes requests based on the container alias. If several {KIE_SERVERS} provide a service with the same container alias, Smart Router balances the load between them.

In some cases, custom routing functionality is required. You can create a custom class to implement the custom routing and then create a custom Smart Router image with the class. You can push this image into your custom registry and then use it to deploy Smart Router.

.Prerequisites

* A JDK and Apache Maven are installed.
* The project for deploying {PRODUCT} is created in your {OPENSHIFT} environment
* You know the route for the {OPENSHIFT} image registry and have the permission to push images into the registry. For instructions about configuring the registry, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html/registry/index[_Registry_] in {OPENSHIFT} product documentation.

.Procedure

. Download the `{PRODUCT_FILE}-container-sources.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.
. Extract the contents of the file and change to the `/src/rhpam-7-openshift-image/quickstarts/router-ext` directory.
. Modify the sample source of the router extension in this directory as necessary. The existing code implements simple routing based on the version of the container.
. Build the source code with Maven:
+
[subs="attributes,verbatim,macros,quotes"]
----
mvn clean package
----
+
The build process generates the following JAR file: `target/router-ext-0.0.1-SNAPSHOT.jar` 
+
. Create a working directory for creating the custom image, copy the generated JAR file into the directory, and then change to the directory, for example:
+
[subs="attributes,verbatim,macros,quotes"]
----
mkdir /tmp/smartrouter
cp target/router-ext-0.0.1-SNAPSHOT.jar /tmp/smartrouter
cd /tmp/smartrouter
----
+
include::customimage-download-step.adoc[]
. Extract the `openshift-launch.sh` file from the official Smart Router image:
+
[subs="attributes,verbatim,macros,quotes"]
----
podman run --rm registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8:7.9.0 \
   cat /opt/rhpam-smartrouter/openshift-launch.sh > openshift-launch.sh
----
+
. Edit the `openshift-launch.sh` file. In the last line of the file, find the `exec` instruction that looks like the following text:
+
[subs="attributes,verbatim,macros,quotes"]
----
exec ${JAVA_HOME}/bin/java ${SHOW_JVM_SETTINGS} ${JAVA_OPTS} ${JAVA_OPTS_APPEND} ${JAVA_PROXY_OPTIONS} "${D_ARR[@]}" -jar /opt/${JBOSS_PRODUCT}/${KIE_ROUTER_DISTRIBUTION_JAR}
----
+
Change the instruction to the following text:
+
[subs="attributes,verbatim,macros,quotes"]
----
exec ${JAVA_HOME}/bin/java ${SHOW_JVM_SETTINGS} "${D_ARR[@]}" \
    -cp /opt/${JBOSS_PRODUCT}/router-ext-0.0.1-SNAPSHOT.jar:/opt/${JBOSS_PRODUCT}/${KIE_ROUTER_DISTRIBUTION_JAR} \
    org.kie.server.router.KieServerRouter
----
+
This change adds the extension JAR file to the Java Class Path.
+
. Create a `Dockerfile` file that defines a custom image based on the base image. The following example shows the content of the `Dockerfile` file:
+
[subs="attributes,verbatim,macros,quotes"]
----
FROM registry.redhat.io/{PRODUCT_INIT}-7/{PRODUCT_INIT}-smartrouter-rhel8:{ENTERPRISE_VERSION_LONG}
RUN rm -rfv /opt/rhpam-smartrouter/openshift-launch.sh
COPY openshift-launch.sh  /opt/rhpam-smartrouter/openshift-launch.sh
COPY router-ext-0.0.1-SNAPSHOT.jar /opt/rhpam-smartrouter/router-ext-0.0.1-SNAPSHOT.jar

USER root
RUN chown jboss. /opt/rhpam-smartrouter/router-ext-0.0.1-SNAPSHOT.jar /opt/rhpam-smartrouter/openshift-launch.sh
RUN chmod +x /opt/rhpam-smartrouter/openshift-launch.sh
USER 185
----
+
This file includes the following actions:
+
** Add the JAR file and the new `openshift-launch.sh` file
** Change the current user to `root`
** Set the necessary permissions for the `openshift-launch.sh` file
** Revert to `USER 185`, the {EAP} user 
+
. Log in to your {OPENSHIFT} cluster with the `oc` command.
. Log in to the {OPENSHIFT} cluster registry with the `podman login` command.
. Build the custom image using the `Dockerfile`. Tag the image for your {OPENSHIFT} cluster registry and your project namespace. Use a custom name for the image and the same version tag as the version of the base image. To build the image, enter the following command:
+
[subs="attributes,verbatim,macros,quotes"]
----
podman build . --tag _registry-route_/project-name_/_image-name_:{ENTERPRISE_VERSION_LONG} 
----
+
For example:
+
[subs="attributes,verbatim,macros,quotes"]
----
podman build . --tag route-openshift-image-registry.openshift.example.com/{PRODUCT_INIT}-project/{PRODUCT_INIT}-{componentimage}-rhel8-custom:{ENTERPRISE_VERSION_LONG}
----
+
. After the build completes, run the image and verify that the customization was successful. Enter the following command:
+
[subs="attributes,verbatim,macros,quotes"]
----
podman run _registry-route_/_project-name_/_image-name_:{ENTERPRISE_VERSION_LONG}
----
+
For example:
+
[subs="attributes,verbatim,macros,quotes"]
----
podman run route-openshift-image-registry.openshift.example.com/{PRODUCT_INIT}-project/{PRODUCT_INIT}-{componentimage}-rhel8-custom:{ENTERPRISE_VERSION_LONG}
----
+
Ensure that the output mentions the custom service, as in the following example:
+
[subs="attributes,verbatim,macros,quotes"]
----
INFO: Using 'LatestVersionContainerResolver' container resolver and restriction policy 'ByPassUserNotAllowedRestrictionPolicy'
----
+
. Push the custom image into the registry:
+
[subs="attributes,verbatim,macros,quotes"]
----
podman push _registry-route_/_project-name_/_image-name_:{ENTERPRISE_VERSION_LONG}
----
+
For example:
+
[subs="attributes,verbatim,macros,quotes"]
----
podman push route-openshift-image-registry.openshift.example.com/{PRODUCT_INIT}-project/{PRODUCT_INIT}-{componentimage}-rhel8-custom:{ENTERPRISE_VERSION_LONG}
----

.Next steps

When deploying {PRODUCT}, set the following values in the *Smart Router* tab:

* *Image context*: The project name, for example, `{PRODUCT_INIT}-project`
* *Image*: The custom image name, for example, `{PRODUCT_INIT}-smartrouter-rhel8-custom`

For instructions about deploying the Smart Router using the operator, see xref:operator-deploy-smartrouter-proc_{context}[].

[NOTE]
====
You can also use a custom tag instead of the current version tag. However, if you use the current version tag, you can later create an image for a new version using the version tag for it. Then, when you upgrade the {PRODUCT} version, the new image is included automatically. For instructions about upgrading the {PRODUCT} version, see xref:operator-modify-proc_{context}[].

If you use a custom tag, when deploying {PRODUCT}, in the *Smart Router* tab set the *Image Tag* value to the custom tag. 
====