[id="dashbuilder-standalone-proc_{context}"]
= Deploying Dashbuilder Standalone on {OPENSHIFT}

You can use Dashbuilder Standalone to view dashboards in OpenShift that were created in and exported from {CENTRAL}. This is useful for reviewing business metrics in environments that do not have Business Central. Use the Dashbuilder Standalone operator to deploy Dashbuilder Standalone on {OPENSHIFT} separately from other services.

.Prerequisites
* Dashbuilder Standalone is available in the OpenShift registry.
* You have prepared your OpenShift environment as described in
ifeval::["{context}" == "creating-custom-pages"]
{URL_DEPLOYING_ON_OPENSHIFT}#assembly-openshift-operator[_{DEPLOYING_OPENSHIFT_OPERATOR}_].
endif::[]
ifeval::["{context}" == "openshift-operator"]
xref:operator-con_openshift-operator[]
endif::[]

* You have created and exported a dashboard in {CENTRAL}.

.Procedure
. On the Operator *Installation* page, enter a name for your application in the *Application name* field.
. In the *Environment* field, enter a name for your environment, for example `rhpam-standalone-dashbuilder`.
. Click *Next*.
. Optional: On the *Security* page, configure LDAP or {RH-SSO}.
. On the *Components* page, select *Dashbuilder* from the *Components* list.
. To add a {KIE_SERVER} data set, complete the following tasks:
+
[NOTE]
====
You can add additional {KIE_SERVER} data sets by repeating this step.
====
.. Click *Add new {KIE_SERVER} DataSets*.
.. In the *DataSet name* field, enter `kieserver-1`.
.. In the *Kie Server Location* field, enter the location of your {KIE_SERVER}, for example `https://my-kie-server:80/services/rest/server`.
.. To set your credentials, complete one of the following tasks:
* If you do not have a token set, in the *Username* and *Password* fields, enter your username and password. Leave the *Token* field blank.
* If you have a token, in the *Token* field, enter your token. Leave the *Username* and *Password* fields blank.
+
The custom resource example:
+
----
apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: standalone-dashbuilder
spec:
  environment: rhpam-standalone-dashbuilder
  objects:
    dashbuilder:
      config:
        kieServerDataSets:
          - name: kieserver-1
            location: 'https://my-kie-server:80/services/rest/server'
            user: kieserverAdmin
            password: kieserverAdminPwd
            replaceQuery: true
----

. To add a {KIE_SERVER} template, complete the following tasks:
+
[NOTE]
====
You can add additional {KIE_SERVER} templates by repeating this step.
====
.. Click *Add new {KIE_SERVER} Templates*.
.. In the *Template name* field, enter a name for your template, for example `kieserver-template`.
.. In the *{KIE_SERVER} Location* field, enter the location of your {KIE_SERVER}, for example `https://my-other-kie-server:80/services/rest/server`.
.. To set your credentials, complete one of the following tasks:
* If you do not have a token set, in the *Username* and *Password* fields, enter your username and password. Leave the *Token* field blank.
* If you have a token, in the *Token* field, enter your token. Leave the *Username* and *Password* fields blank.
+
----
apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: standalone-dashbuilder
spec:
  environment: rhpam-standalone-dashbuilder
  objects:
    dashbuilder:
      config:
        kieServerDataSets:
          - name: kieserver-1
            location: 'https://my-kie-server:80/services/rest/server'
            user: kieserverAdmin
            password: kieserverAdminPwd
            replaceQuery: true
        kieServerTemplates:
          - name: kieserver-template
            location: 'https://my-another-kie-server:80/services/rest/server'
            user: user
            password: pwd
            replaceQuery: true
----
. Optional: To set a custom hostname for the external route, enter a domain in the *Custom hostname to be used on the Dashbuilder external Route* field, formatted as in the following example:
+
----
`dashbuilder.example.com`
----
+
[NOTE]
====
The custom hostname must be valid and resolvable.

To change the custom hostname, you can modify the `routeHostname` property.
====
. Optional: To enable and set the Edge termination route, complete the following steps:
.. Under *Change route termination*, select *Enable Edge termination*.
.. Optional: In the *Key* field, enter the private key.
.. Optional: In the *Certificate* field, enter the certificate.
.. Optional: In the *CaCertificate* field, enter the CaCertificate.
