[id='environment-managed-deploy-proc']
// definitions for RH-SSO include
:kieandcentral:
:multiplekie:
:LOCAL_CENTRAL: {CENTRAL} Monitoring
:modifylink: environment-managed-modify-proc
= Deploying a managed environment

Deploy a managed environment using the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-prod.yaml` template file. You can extract the file from the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file. You can download this file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.

If you want to modify the environment defined by the template file, see <<environment-managed-modify-proc>>.

.Procedure

. Use one of the following methods to deploy the template:
* In the OpenShift Web UI, select *Add to Project -> Import YAML / JSON* and then select or paste the template file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
* To use the OpenShift command line console, prepare the following command line:
+
[subs="attributes,verbatim,macros"]
----
oc new-app -f <template-file-name> -p {CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET={CENTRAL_ONEWORD}-app-secret -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret -p KIE_SERVER_ROUTER_HTTPS_SECRET=smartrouter-app-secret -p MAVEN_REPO_URL=<maven-repo-url>
----
+
In this command line:
+
** Replace `<template-file-name>` with the full pathname of the template file that you have modified.
** Replace `<maven-repo-url>` with the a URL for a Maven repository where the necessary KJAR files are available.
** Use as many `-p PARAMETER=value` pairs as needed to set the required parameters. You can view the template file to see descriptions for all parameters.
+
. Set the following parameters as necessary:
** *{CENTRAL} Server Keystore Secret Name* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET`): The name of the secret for {CENTRAL}, as created in <<secrets-central-create-proc>>.
** *KIE Server Keystore Secret Name* (`KIE_SERVER_HTTPS_SECRET`): The name of the secret for {KIE_SERVER}, as created in <<secrets-kie-create-proc>>.
** *Smart Router Keystore Secret Name* (`KIE_SERVER_ROUTER_HTTPS_SECRET`): The name of the secret for Smart Router, as created in <<secrets-smartrouter-create-proc>>.
** *Application Name* (`APPLICATION_NAME`): The name of the OpenShift application. It is used in the default URLs for {CENTRAL} and {KIE_SERVER}. OpenShift uses the application name to create a separate set of deployment configurations, services, routes, labels, and artifacts. You can deploy several applications using the same template into the same project, as long as you use different application names.
** *Maven repository URL* (`MAVEN_REPO_URL`): A URL for a Maven repository. You must upload all the processes (KJAR files) that are to be deployed in your environment into this repository.
** *Maven repository username* (`MAVEN_REPO_USERNAME`): The username for the Maven repository.
** *Maven repository password* (`MAVEN_REPO_PASSWORD`): The username for the Maven repository.
** *{CENTRAL} Server Certificate Name* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-central-create-proc>>.
** *{CENTRAL} Server Keystore Password* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-central-create-proc>>.
** *Smart Router Certificate Name* (`KIE_SERVER_ROUTER_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-smartrouter-create-proc>>.
** *Smart Router Keystore Password* (`KIE_SERVER_ROUTER_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-smartrouter-create-proc>>.
** *KIE Server Certificate Name* (`KIE_SERVER_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server Keystore Password* (`KIE_SERVER_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server Mode* (`KIE_SERVER_MODE`): In the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-prod.yaml` template the default value is `PRODUCTION`; in this mode, you can not deploy `SNAPSHOT` versions of KJAR artifacts and can not change versions of an artifact in an existing container. (To deploy a new version with `PRODUCTION` mode, you can create a new container on the same {KIE_SERVER}). To deploy `SNAPSHOT` versions or to change versions of an artifact in an existing container, set this parameter to `DEVELOPMENT`. 
** *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`): The namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-proc>>), the namespace is `openshift`. If you have installed the image streams file, the namespace is the name of the OpenShift project.
** *{CENTRAL} Monitoring Container Replicas* (`{CENTRAL_CAPITAL_UNDER}_MONITORING_CONTAINER_REPLICAS`): The number of replicas initially created for {CENTRAL} Monitoring. If you do not want to use a high-availability configuration for {CENTRAL} Monitoring, set this number to 1.
** *Smart Router Container Replicas* (`SMART_ROUTER_CONTAINER_REPLICAS`): The number of replicas initially created for Smart Router.
** *KIE Server Container Replicas* (`KIE_SERVER_CONTAINER_REPLICAS`): The number of replicas initially created for each of the {KIE_SERVERS}.
+
You can also set the following user names and passwords:
** *KIE Admin User* (`KIE_ADMIN_USER`) and *KIE Admin Password* (`KIE_ADMIN_PWD`): The user name and password for the administrative user in {LOCAL_CENTRAL}.
** *KIE Server User* (`KIE_SERVER_USER`) and *KIE Server Password* (`KIE_SERVER_PWD`): The user name and password that a client application must use to connect to any of the {KIE_SERVERS}.
include::ldap_rhsso.adoc[]
+
include::offline-params.adoc[]
include::externaldb-params.adoc[]
. Complete the creation of the environment. Depending on the method that you are using:
* In the OpenShift Web UI, click *Create*.
** If the `This will create resources that may have security or project behavior implications` message appears, click *Create Anyway*.
* Complete and run the command line.
