[id='environment-managed-con']
= Fixed managed server environment
You can deploy a fixed managed server environment that, in a single deployment, includes several different pods running {KIE_SERVER}. No processes are initially loaded on the servers. The database servers are, by default, also run in pods. Each {KIE_SERVER} pod can be separately scaled as necessary.

A pod with {CENTRAL} Monitoring and a pod with Smart Router are also deployed. You must use {CENTRAL} Monitoring to deploy, load, and unload processes on your {KIE_SERVERS}. You can also use it to view monitoring information.

Smart Router is a single endpoint that can receive calls from client applications to any of your processes and route each call automatically to the server that runs the process.

You cannot easily add or remove {KIE_SERVERS} at a later time.

You must provide a Maven repository with the processes (KJAR files) that you want to deploy on the servers. Your integration process must ensure that the required versions of the processes are uploaded to the Maven repository. You can use {CENTRAL} in a development environment to create the processes and upload them to the Maven repository.
