[id='environment-immutable-source-extract-proc']
= Extracting the source code from {CENTRAL} for use in an S2I build

If you are using {CENTRAL} for authoring services, you can extract the source code for your service and place it into a separate Git repository, such as GitHub or an on-premise installation of GitLab, for use in the S2I build.

.Procedure

. Use the following command to extract the source code:
+
--
[subs="attributes,verbatim,macros"]
----
git clone https://<{URL_COMPONENT_CENTRAL}-host>:443/git/<MySpace>/<MyProject>
----

In this command, replace the following variables:

** `<{URL_COMPONENT_CENTRAL}-host>` with the host on which {CENTRAL} is running
** `<MySpace>` with the name of the {CENTRAL} space in which the project is located
** `<MyProject>` with the name of the project

[NOTE]
====
To view the full Git URL for a project in {CENTRAL}, click *Menu* -> *Design* -> *_<MyProject>_* -> *Settings*.
====

[NOTE]
====
If you are using self-signed certificates for HTTPS communication, the command might fail with an `SSL certificate problem` error message. In this case, disable SSL certificate verification in `git`, for example, using the `GIT_SSL_NO_VERIFY` environment variable:

[subs="attributes,verbatim,macros"]
----
env GIT_SSL_NO_VERIFY=true git clone https://<{URL_COMPONENT_CENTRAL}-host>:443/git/<MySpace>/<MyProject>
----
====
--
+
. Upload the source code to another Git repository, such as GitHub or GitLab, for the S2I build. 
