[id='environment-trial-proc_{context}']
= Deploying a trial environment

The procedure to deploy a trial environment is minimal. There are no required settings and all passwords are set to a single value. The default password is `RedHat`.

.Procedure

. Download the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.
. Extract the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-trial-ephemeral.yaml` template file.
. Use one of the following methods to deploy the template:
* In the OpenShift Web UI, select *Add to Project -> Import YAML / JSON* and then select or paste the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-trial-ephemeral.yaml` file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
* To use the OpenShift command line console, prepare the following command line:
+
[subs="attributes,verbatim,macros"]
----
oc new-app -f <template-path>/{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-trial-ephemeral.yaml
----
+
In this command line, replace `<template-path>` with the path to the downloaded template file.
. Optionally, set any parameters as described in the template. A typical trial deployment requires only the following parameter:
** *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`): The namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-proc_{context}>>), the namespace is `openshift`. If you installed the image streams file, the namespace is the name of the OpenShift project.
. Complete the creation of the environment, depending on the method that you are using:
* In the OpenShift Web UI, click *Create*.
** A `This will create resources that may have security or project behavior implications` pop-up message might be displayed. If it is displayed, click *Create Anyway*.
* Complete and run the command line.
