[id='environment-authoring-single-proc']
= Deploying a single authoring environment

To deploy a single authoring environment, use the `rhpam-70-authorimg.yaml` template file. You can download this file from `{URL_BASE_GITHUB_PAM}/templates`.

.Procedure

. Use one of the following methods to deploy the template:
.. In the OpenShift Web UI, select *Add to Project -> Import YAML / JSON* and then select or paste the `rhpam-70-authorimg.yaml` file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
.. To use the OpenShift command line console, prepare the following command line:
+
[subs="verbatim,macros"]
----
oc process -n <project-name> -f <template-path>/hpam-70-authorimg.yaml -v ATTRIBUTE=value -V ATTRIBUTE=value... | oc create -n <project-name> -f -
----
+
In this command line:
+
* Replace `<project-name>` with the name of your project
* Replace `<template-path>` with the path to the downloaded template file.
* Use as many `ATTRIBUTE=value` pairs as needed to set the required attributes. You can view the template file to see descriptions for the attributes.
+
. Set the following mandatory attributes:
** *Application Name* (`APPLICATION_NAME`): The name of the OpenShift application. It is used in the default URLs for {CENTRAL} and {KIE_SERVER}.
** *Business Central Server Certificate Name* (`BUSINESS_CENTRAL_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-central-create-proc>>.
** *Business Central Server Keystore Password* (`BUSINESS_CENTRAL_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-central-create-proc>>.
** *KIE Server Certificate Name* (`KIE_SERVER_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server Keystore Password* (`KIE_SERVER_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server ID* (`KIE_SERVER_ID`): The name of the server template on the {CENTRAL} that the {KIE_SERVER} is to join. Set this parameter to any value. If you do not set it and then the {KIE_SERVER} pod is restarted or scaled, each new instance of the server might join a new template. 
** *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`): The namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-proc>>), the namespace is `openshift`. If you have installed the image streams file, the namespace is the name of the OpenShift project.
+
You can also set other parameters as necessary.
. Complete the creation of the environment. Depending on the metod that you are using:
.. In the OpenShift Web UI, click *Create*.
.. Complete and run the command line.
