[id='environment-immutable-con_{context}']
= Environment with immutable servers
You can deploy an environment that includes one or more pods running _immutable_ {KIE_SERVER} with preloaded services.
ifdef::PAM[The database servers are, by default, also run in pods.]
Each {KIE_SERVER} pod can be separately scaled as necessary.

On an immutable {KIE_SERVER}, any services must be loaded onto the server at the time the image is created. You cannot deploy or undeploy services on a running immutable {KIE_SERVER}. The advantage of this approach is that {KIE_SERVER} with the services in it runs like any other containerized service and does not require specialized management. {KIE_SERVER} runs like any other pod on the OpenShift environment; you can use any container-based integration workflows as necessary.

When you create a {KIE_SERVER} image, you can build your services using S2I (Source to Image). Provide a Git repository with the source of your services and other business assets; if you develop the services or assets in {CENTRAL}, copy the source into a separate repository for the S2I build. OpenShift automatically builds the source, installs the services into the {KIE_SERVER} image, and starts the containers with the services.

If you are using {CENTRAL} for authoring services, you can extract the source for your process and place it into a separate Git repository (such as GitHub or an on-premise installation of GitLab) for use in the S2I build.

Alternatively, you can create a similar {KIE_SERVER} deployment using services that are already built as KJAR files. In this case, you must provide the services in a Maven repository. You can use the built-in repository of the {CENTRAL} or your own repository (for example, a Nexus deployment). When the server pod starts, it retrieves the KJAR services from the Maven repository. Services on the pod are never updated or changed. At every restart or scaling of the pod, the server retrieves the files from the repository, so you must ensure they do not change on the Maven repository to keep the deployment immutable.

With both methods of creating immutable images, no further management of the image is required. If you want to use a new version of a service, you can build a new image.

ifdef::PAM[]
Optionally, you can add {CENTRAL} Monitoring and Smart Router to your environment. Use {CENTRAL} Monitoring to start, stop, and monitor services on {KIE_SERVERS}.
endif::PAM[]
