[id='environment-authoring-ha-modify-proc_{context}']
= Modifying the template for the High Availability authoring environment

By default, the high-availability authoring template creates a MySQL pod to provide the database server for {KIE_SERVER}. If you prefer to use PostgreSQL or to use an external server (outside the OpenShift project), you need to modify the template before deploying the environment.

You can also modify the High Availability authoring template to change the number of replicas initially created for {CENTRAL}.

include::modifytemplate-intro.adoc[]

.Procedure

Edit the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring-ha.yaml` template file to make any of the following changes as necessary.

* If you want to use PostgreSQL instead of MySQL, replace several blocks of the file, marked with comments from `BEGIN` to `END`, with blocks from the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-postgresql.yaml` file:

. Replace the block named `MySQL database parameters` with the block named `PostgreSQL database parameters`. (Take this block and all subsequent replacement blocks from the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-postgresql.yaml` file.)
. Replace the block named `MySQL service` with the block named `PostgreSQL service`.
. Replace the block named `MySQL driver settings` with the block named `PostgreSQL driver settings`.
. Replace the block named `MySQL deployment config` with the block named `PostgreSQL deployment config`.
. Replace the block named `MySQL persistent volume claim` with the block named `PostgreSQL persistent volume claim`.

* If you want to use an external database server, replace several blocks of the file, marked with comments from `BEGIN` to `END`, with blocks from the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-externaldb.yaml` file, and also remove some blocks:
. Replace the block named `MySQL database parameters` with the block named `External database parameters`. (Take this block and all subsequent replacement blocks from the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-externaldb.yaml` file.)
. Replace the block named `MySQL driver settings` with the block named `External database driver settings`.
. Remove the following blocks of the file, marked with comments from `BEGIN` to `END`:
** `MySQL service`
** `MySQL deployment config`
** `MySQL persistent volume claim`

IMPORTANT: The standard {KIE_SERVER} image includes drivers for MySQL, MariaDB, and PostgreSQL external database servers. If you want to use another database server, you must build a custom {KIE_SERVER} image. For instructions, see <<externaldb-build-proc_{context}>>.

* If you want to change the number of replicas initially created for {CENTRAL}, on the line below the comment `## Replicas for {CENTRAL}`, change the number of replicas to the desired value.
