[id='environment-immutable-con']
= Environment with immutable servers
You can deploy an environment that includes one or more pods running {KIE_SERVER} with preloaded services. 
ifdef::PAM[The database servers are, by default, also run in pods.] 
Each {KIE_SERVER} pod can be separately scaled as necessary.

In this case, any services (KJAR files) must be loaded onto a {KIE_SERVER} at the time the image is created. You cannot load or unload services on a running {KIE_SERVER}. The advantage of this approach is that the {KIE_SERVER} with the services in it runs like any other containerized service and does not require specialized management. The {KIE_SERVER} runs like any other pod on the OpenShift environment; you can use any container-based integration workflows as necessary. 

ifdef::PAM[]
Optionally, you can also deploy a pod with {CENTRAL} Monitoring and a pod with Smart Router. You can use {CENTRAL} Monitoring to start and stop (but not deploy) services on your {KIE_SERVERS} and to view monitoring data. 

Smart Router is a single endpoint that can receive calls from client applications to any of your services and route each call automatically to the server that actually runs the process.

endif::PAM[]
When you create a {KIE_SERVER} image, you can build your services using S2I (Source to Image). Provide a Git repository with the source of your services and other business assets; if you develop the services or assets in {CENTRAL}, copy the source into a separate repository for the S2I build. OpenShift automatically builds the source, installs the process into the {KIE_SERVER} image, and starts the process. 

If you are using {CENTRAL} for authoring services, you can extract the source for your process and place it into a separate Git repository (such as GitHub or an on-premise installation of GitLab) for use in the S2I build.

Alternatively, you can create a similar {KIE_SERVER} deployment using services that are already built as KJAR files. In this case, you must provide the services in a Maven repository; you can use the built-in repository of the {CENTRAL} or your own repository (for example, a Nexus deployment). The KJAR files are retrieved from the Maven repository during the startup of the pod and not updated or changed after that. The files are retrieved at every restart or scaling of the pod, so you must ensure they do not change on the Maven repository to keep the deployment immutable.

With both methods of creating immutable images, no further management of the image is required. If you want to use a new version of a service, you can build a new image.

ifdef::PAM[]
If you want to use {CENTRAL} Monitoring, you must install the Monitoring and Smart Router template _before_ creating any {KIE_SERVER} images. You must also provide a Maven repository. Your integration process must ensure that all the versions of KJAR files built into any {KIE_SERVER} image are also available in the Maven repository.
endif::PAM[]
