[id='environment-immutable-monitoring-proc']
// definitions for RH-SSO include
:centralonly:
// centralonly must be undefined at end of file
:LOCAL_CENTRAL: {CENTRAL} Monitoring
= Deploying monitoring and Smart Router for an environment with immutable servers

If you want to use {CENTRAL} Monitoring and Smart Router for an environment with immutable servers, you must deploy them before deploying any {KIE_SERVERS}. If you do not want to use these components, skip this procedure.

To deploy {LOCAL_CENTRAL} and Smart Router for an environment with immutable servers, use the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-prod-immutable-monitor.yaml` template file. You can extract this file from the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file. You can download the file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.

.Procedure

. Use one of the following methods to deploy the template:
* In the OpenShift Web UI, select *Add to Project -> Import YAML / JSON* and then select or paste the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-prod-immutable-monitor.yaml` file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
* To use the OpenShift command line console, prepare the following command line:
+
[subs="attributes,verbatim,macros"]
----
oc new-app -f <template-path>/{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-prod-immutable-monitor.yaml -p {CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET={CENTRAL_ONEWORD}-app-secret -p KIE_SERVER_ROUTER_HTTPS_SECRET=smartrouter-app-secret
----
+
In this command line:
+
** Replace `<template-path>` with the path to the downloaded template file.
** Use as many `-p PARAMETER=value` pairs as needed to set the required parameters. You can view the template file to see descriptions for all parameters.
+
. Set the following parameters as necessary:
** *{CENTRAL} Server Keystore Secret Name* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET`): The name of the secret for {CENTRAL}, as created in <<secrets-central-create-proc>>.
** *Smart Router Keystore Secret Name* (`KIE_SERVER_ROUTER_HTTPS_SECRET`): The name of the secret for Smart Router, as created in <<secrets-smartrouter-create-proc>>.
** *Application Name* (`APPLICATION_NAME`): The name of the OpenShift application. It is used in the default URLs for {LOCAL_CENTRAL} and Smart Router. OpenShift also uses the application name to create a separate set of deployment configurations, services, routes, labels, and artifacts. You can deploy several applications using the same template into the same project, as long as you use different application names.
** *Maven repository URL* (`MAVEN_REPO_URL`): A URL for a Maven repository. You must upload all the processes (KJAR files) that are to be deployed in your environment into this repository.
** *Maven repository username* (`MAVEN_REPO_USERNAME`): The username for the Maven repository.
** *Maven repository password* (`MAVEN_REPO_PASSWORD`): The username for the Maven repository.
** *{CENTRAL} Server Certificate Name* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-central-create-proc>>.
** *{CENTRAL} Server Keystore Password* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-central-create-proc>>.
** *Smart Router Certificate Name* (`KIE_SERVER_ROUTER_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-smartrouter-create-proc>>.
** *Smart Router Keystore Password* (`KIE_SERVER_ROUTER_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-smartrouter-create-proc>>.
** *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`): The namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-proc>>), the namespace is `openshift`. If you have installed the image streams file, the namespace is the name of the OpenShift project.
+
You can also set other parameters as necessary.
include::ldap_rhsso.adoc[]
. Complete the creation of the environment, depending on the method that you are using:
* In the OpenShift Web UI, click *Create*.
** If the `This will create resources that may have security or project behavior implications` message appears, click *Create Anyway*.
* Complete and run the command line.
+
. Record the suggested command line that is displayed. This command line includes the parameters that you must set when deploying the immutable servers.

:centralonly!:
