[id='environment-authoring-single-proc']
// definitions for RH-SSO include
:kieandcentral:
:LOCAL_CENTRAL: {CENTRAL}
:modifylink: environment-authoring-single-modify-proc
ifdef::PAM[]
= Deploying a single authoring environment

To deploy a single authoring environment, use the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring.yaml` template file.
endif::PAM[]
ifdef::DM[]
= Deploying single {CENTRAL} and one {KIE_SERVER} in an authoring or managed server environment

To deploy single {CENTRAL} and one {KIE_SERVER} in an authoring or managed server environment, use the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring.yaml` template file.
endif::DM[]
You can extract this file from the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file. You can download the file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.

ifdef::PAM[]
If you want to modify the environment defined by the template file, see <<environment-authoring-single-modify-proc>>.
endif::PAM[]

.Procedure

. Use one of the following methods to deploy the template:
* In the OpenShift Web UI, select *Add to Project -> Import YAML / JSON* and then select or paste the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring.yaml` file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
* To use the OpenShift command line console, prepare the following command line:
+
[subs="attributes,verbatim,macros"]
----
oc new-app -f <template-path>/{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring.yaml -p {CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET={CENTRAL_ONEWORD}-app-secret -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret
----
+
In this command line:
+
** Replace `<template-path>` with the path to the downloaded template file.
** Use as many `-p PARAMETER=value` pairs as needed to set the required parameters. You can view the template file to see descriptions for all parameters.
+
. Set the following parameters as necessary:
+
include::authoring-params.adoc[]
. Complete the creation of the environment, depending on the method that you are using:
* In the OpenShift Web UI, click *Create*.
** If the `This will create resources that may have security or project behavior implications` message appears, click *Create Anyway*.
* Complete and run the command line.

:kieandcentral!:
