[id='environment-authoring-managed-con']
= Authoring or managed server environment
You can deploy an environment for creating and modifying services using {CENTRAL} and for running them in {KIE_SERVERS} managed by {CENTRAL}. This environment consists of {CENTRAL} and one or more {KIE_SERVERS}.

You can use {CENTRAL} both to develop services and to deploy them to one or several {KIE_SERVERS}. For example, you can deploy test versions of services to one {KIE_SERVER} and production versions to another {KIE_SERVER}.

To avoid accidentally deploying wrong versions to a production {KIE_SERVER}, you can create separate environments to author services (_authoring environment_) and to manage deployment of production services (_managed server environment_). You can use a shared external Maven repository between these environments, so that services developed in the authoring environment are available in the managed server environment. However, the procedures to deploy these environments are the same.

Depending on your needs, you can deploy either a single or high-availability (HA) {CENTRAL}. A single {CENTRAL} pod is not replicated; only a single copy of {CENTRAL} is used. In an HA {CENTRAL} deployment, you can scale {CENTRAL}.

An HA {CENTRAL} provides maximum reliability and responsiveness for authoring services, but has higher memory and storage requirements and also requires support for persistent volumes with ReadWriteMany mode.

[IMPORTANT]
====
In {PRODUCT} {PRODUCT_VERSION}, high-availability {CENTRAL} functionality is for Technology Preview only. For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
====

You can scale {KIE_SERVER} pods as necessary in any version of the authoring or managed server environment.

To deploy an authoring or managed server environment, first deploy the single or high-availability {CENTRAL} and a single {KIE_SERVER} using the authoring template.

To add additional {KIE_SERVERS}, you can deploy the {KIE_SERVER} template in the same project.
