[id='environment-managed-con']
= Managed server environment
You can deploy a managed server environment that includes several different pods running {KIE_SERVER}. By default, no processes are initially loaded on the servers. The database servers are, by default, also run in pods. Each {KIE_SERVER} pod can be separately scaled as necessary.

A pod with {CENTRAL} Monitoring and a pod with Smart Router are also deployed. You must use {CENTRAL} Monitoring to deploy, load, and unload processes on your {KIE_SERVERS}; you can also use it  to view monitoring information. 

Smart Router is a single endpoint that can receive calls from client applications to any of your processes and route each call automatically to the server that actually runs the process.

You must provide a Maven repository with the processes (KJAR files) that you want to deploy on the servers. Your integration process must ensure that the required versions of the processes are uploaded to the Maven repository. You can use {CENTRAL} in a development environment to create the processes and upload them to the Maven repository.

{PRODUCT} includes two base templates for managed environments:

* `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-sit.yaml` is a typical staging environment. It includes two {KIE_SERVER} pods (with database pods), Smart Router, and {CENTRAL} monitoring.

* `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-prod.yaml` is a typical production environment. It includes two {KIE_SERVER} pods (with database pods), Smart Router in a high-availability configuration, and {CENTRAL} monitoring in a high-availability configuration.

To deploy a managed environment, pick one of the templates, modify it according to your needs if necessary, and then deploy it.
