[id='freeform-server-immutable-deploy-assy']
= Deploying an immutable {KIE_SERVER} for a freeform environment

ifdef::context[:parent-context: {context}]
:context: freeform-server-immutable
:LOCAL_CENTRAL: {CENTRAL} Monitoring
:what_deploying: an immutable {KIE_SERVER}


You can add an immutable {KIE_SERVER} to a freeform environment. by default, this server uses a PostgreSQL database server in a pod. To use a MySQL database server in a pod or an external database server, you can modify the template.

Deploy the server in the same project as the {LOCAL_CENTRAL} deployment.

When you deploy an immutable {KIE_SERVER}, the deployment procedure retrieves the source code for any services that must run on this server, builds the services, and includes them in the server image.

You cannot deploy or undeploy services on a running immutable {KIE_SERVER}. You can use {LOCAL_CENTRAL} to view monitoring information. The {KIE_SERVER} runs like any other pod on the OpenShift environment; you can use any container-based integration workflows as necessary. 

include::template-deploy-start-proc.adoc[leveloffset=+1]
include::template-deploy-mandatory-proc.adoc[leveloffset=+1]
include::template-deploy-optionalmaven-proc.adoc[leveloffset=+1]
include::template-deploy-nopubnet-proc.adoc[leveloffset=+1]
include::template-deploy-rhsso-proc.adoc[leveloffset=+1]
include::template-deploy-ldap-proc.adoc[leveloffset=+1]
include::template-deploy-externaldb-proc.adoc[leveloffset=+1]
include::template-deploy-complete-proc.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
