[id='freeform-con']
= Freeform server environment

You can deploy a freeform server environment that includes several different pods running {KIE_SERVER}. These {KIE_SERVERS} can run different services for staging or production purposes. You can add and remove servers as necessary at any time. 

The freeform environment includes a pod with {CENTRAL} Monitoring; use it to monitor and, when necessary, manage the execution of services on {KIE_SERVERS}. This environment does not include Smart Router.

You can deploy two types of {KIE_SERVERS}: managed and immutable. Each {KIE_SERVER} can be separately scaled as necessary.

On a _managed_ {KIE_SERVER}, by default no services are initially loaded. Use {CENTRAL} Monitoring or the REST API of the {KIE_SERVER} to deploy and undeploy processes on the server. You can also configure the {KIE_SERVER} to load and deploy a service at startup.

You must provide a Maven repository with the processes (KJAR files) that you want to deploy on the servers. Your integration process must ensure that the required versions of the processes are uploaded to the Maven repository. You can use {CENTRAL} in a development environment to create the processes and upload them to the Maven repository.

On an _immutable_ {KIE_SERVER}, any services must be loaded onto the server at the time the image is created. You cannot deploy or undeploy services on a running immutable {KIE_SERVER}. The advantage of this approach is that the {KIE_SERVER} with the services in it runs like any other containerized service and does not require specialized management. The {KIE_SERVER} runs like any other pod on the OpenShift environment; you can use any container-based integration workflows as necessary. 

Immutable {KIE_SERVERS} build services from source during deployment. You must make the source available in a Git repository.

You can use {CENTRAL} Monitoring to view monitoring information for all {KIE_SERVERS} in the environment, including immutable servers.

Each {KIE_SERVER} uses a database server. Usually, the database servers also run in pods, although you can set up a {KIE_SERVER} to use an external database server. 
