[id='githooks-proc_{context}']
= (Optional) Providing the Git hooks directory

If you deploy an authoring enviropnent and configure the `GIT_HOOKS_DIR` parameter, you must provide a directory of Git hooks and must mount this directory on the {CENTRAL} deployment.

The typical use of Git hooks is interaction with an upstream repository. To enable Git hooks to push commits into an upstream repository, you must also provide a secret key that corresponds to a public key configured on the upstream repository.

.Prerequisites

* You deployed a {PRODUCT} authoring environment using templates
* You set the `GIT_HOOKS_DIR` parameter in the deployment

.Procedure

. If interaction with an upstream repository using SSH authentication is required, complete the following steps to prepare and mount a secret with the necessary files:
.. Prepare the `id_rsa` file with a private key that matches a public key stored in the repository.
.. Prepare the `known_hosts` file with the correct name, address, and public key for the repository.
.. Create a secret with the two files using the `oc` command, for example:
+
[subs="attributes,verbatim,macros"]
----
oc create secret git-hooks-secret --from-file=id_rsa=id_rsa --from-file=known_hosts=known_hosts
----
+
.. Mount the secret in the SSH key path of the {CENTRAL} deployment, for example:
+
[subs="attributes,verbatim,macros"]
----
oc set volume dc/<myapp>-{PRODUCT_INIT}centr --add --type secret --secret-name git-hooks-secret --mount-path=/home/jboss/.ssh --name=ssh-key
----
+
Replace `<myapp>` with the application name that you set when configuring the template.
+
. Create the Git hooks directory. For instructions, see the https://git-scm.com/docs/githooks[Git hooks reference documentation].
+
For example, a simple Git hooks directory can provide a post-commit hook that pushes the changes upstream. If the project was imported into {CENTRAL} from a repository, this repository remains configured as the upstream repository. Create a file named `post-commit` with permission values `755` and the following content:
+
[subs="attributes,verbatim,macros"]
----
git push
----
+
[NOTE]
====
A `pre-commit` script is not supported in {CENTRAL}. Use a `post-commit` script.
====
+
. Supply the Git hooks directory to the {CENTRAL} deployment. You can use a configuration map or a persistent volume.
.. If the Git hooks consist of one or several fixed script files, use a configuration map. Complete the following steps:
... Change into the Git hooks directory that you have created.
... Create an OpenShift configuration map from the files in the directory. Run the following command:
+
[subs="attributes,verbatim,macros"]
----
oc create configmap git-hooks --from-file=<file_1>=<file_1> --from-file=<file_2>=<file_2> ...
----
+
Replace `file_1`, `file_2`, and so on with Git hook script file names. Example:
+
[subs="attributes,verbatim,macros"]
----
oc create configmap git-hooks --from-file=post-commit=post-commit
----
+
... Mount the configuration map on the {CENTRAL} deployment in the path that you have configured:
+
[subs="attributes,verbatim,macros"]
----
oc set volume dc/<myapp>-{PRODUCT_INIT}centr --add --type configmap --configmap-name git-hooks  --mount-path=<git_hooks_dir> --name=git-hooks
----
+
Replace `<myapp>` with the application name that was set when configuring the template and `<git_hooks_dir>` is the value of `GIT_HOOKS_DIR` that was set when configuring the template.
+
.. If the Git hooks consist of long files or depend on binaries, such as executable or KJAR files, use a persistence volume. You must create a persistent volume, create a persistent volume claim and associate the volume with the claim, transfer files to the volume, and mount the volume in the `_myapp_-{PRODUCT_INIT}centr` deployment configuration (replace _myapp_ with the application name). For instructions about creating and mounting persistence volumes, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/developer_guide/dev-guide-persistent-volumes[Using persistent volumes]. For instructions about copying files onto a persistent volume, see https://blog.openshift.com/transferring-files-in-and-out-of-containers-in-openshift-part-3/[Transferring files in and out of containers].
+
. Wait a few minutes, then review the list and status of pods in your project. Because {CENTRAL} does not start until you provide the Git hooks directory, {KIE_SERVER} might not start at all. To see if {KIE_SERVER} has started, check the output of the following command:
+
[subs="attributes,verbatim,macros"]
----
oc get pods
----
+
If a working {KIE_SERVER} pod is not present, start it:
+
[subs="attributes,verbatim,macros"]
----
oc rollout latest dc/<myapp>-kieserver
----
+
Replace `<myapp>` with the application name that was set when configuring the template.
