[id='glusterfs-reconfig-proc_{context}']
= Changing GlusterFS configuration

If you are deploying an authoring environment, you must check whether your OpenShift environment uses GlusterFS to provide permanent storage volumes. If it uses GlusterFS, to ensure optimal performance of {CENTRAL}, you must tune your GlusterFS storage by changing the storage class configuration.

.Procedure

. To check whether your environment uses GlusterFS, enter the following command:
+
[subs="attributes,verbatim,macros"]
----
oc get storageclass
----
+
In the results, check whether the `(default)` marker is on the storage class that lists `glusterfs`. For example, in the following output the default storage class is `gluster-container`, which does list `glusterfs`:
+
[subs="attributes,verbatim,macros"]
----
NAME              PROVISIONER                       AGE
gluster-block     gluster.org/glusterblock          8d
gluster-container (default) kubernetes.io/glusterfs 8d
----
+
If the result has a default storage class that does not list `glusterfs` or if the result is empty, you do not need to make any changes. In this case, skip the rest of this procedure.

. To save the configuration of the default storage class into a YAML file, enter the following command:
+
[subs="attributes,verbatim,macros"]
----
oc get storageclass <class-name> -o yaml >storage_config.yaml
----
+
Replace `<class-name>` with the name of the default storage class. Example:
+
[subs="attributes,verbatim,macros"]
----
oc get storageclass gluster-container -o yaml >storage_config.yaml
----
+
. Edit the `storage_config.yaml` file:
.. Remove the lines with the following keys:
** `creationTimestamp`
** `resourceVersion`
** `selfLink`
** `uid`
.. If you are planning to use {CENTRAL} only as a single pod, without high-availability configuration, on the line with the `volumeoptions` key, add the following options:
+
[subs="attributes,verbatim,macros"]
----
features.cache-invalidation on
performance.nl-cache on
----
+
For example:
+
`volumeoptions: client.ssl off, server.ssl off, features.cache-invalidation on, performance.nl-cache on`
+
.. If you are planning to use {CENTRAL} in a high-availability configuration, on the line with the `volumeoptions` key, add the following options:
+
[subs="attributes,verbatim,macros"]
----
features.cache-invalidation on
nfs.trusted-write on
nfs.trusted-sync on
performance.nl-cache on
performance.stat-prefetch off
performance.read-ahead off
performance.write-behind off
performance.readdir-ahead off
performance.io-cache off
performance.quick-read off
performance.open-behind off
locks.mandatory-locking off
performance.strict-o-direct on
----
+
For example:
+
`volumeoptions: client.ssl off, server.ssl off, features.cache-invalidation on, nfs.trusted-write on, nfs.trusted-sync on, performance.nl-cache on, performance.stat-prefetch off, performance.read-ahead off, performance.write-behind off, performance.readdir-ahead off, performance.io-cache off, performance.quick-read off, performance.open-behind off, locks.mandatory-locking off, performance.strict-o-direct on`
+
. To remove the existing default storage class, enter the following command:
+
[subs="attributes,verbatim,macros"]
----
oc delete storageclass <class-name>
----
+
Replace `<class-name>` with the name of the default storage class. Example:
+
[subs="attributes,verbatim,macros"]
----
oc delete storageclass gluster-container
----
+
. To re-create the storage class using the new configuration, enter the following command:
+
[subs="attributes,verbatim,macros"]
----
oc create -f storage_config.yaml
----
