[id='imagestreams-file-install-proc']
= Ensuring the availability of image streams 

You must ensure that the image streams that are required for the deployment are available in your OpenShift environment. Some versions of the OpenShift environment include the necessary image streams. You must check if they are available. If they are not available, you must install the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-image-streams.yaml` file.

.Procedure
. Run the following commands:
+
ifdef::DM[]
[subs="attributes,verbatim,macros"]
----
$ oc get imagestreamtag -n openshift | grep {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-decisioncentral-openshift
$ oc get imagestreamtag -n openshift | grep {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-openshift
----
endif::DM[]
ifdef::PAM[]
[subs="attributes,verbatim,macros"]
----
$ oc get imagestreamtag -n openshift | grep {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-businesscentral
$ oc get imagestreamtag -n openshift | grep {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver
----
endif::PAM[]
+
If the outputs of both commands are not empty, the required image streams are available and no further action is required.
+
. If the output of one or both of the commands is empty, download the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page. Extract the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-image-streams.yaml` file from it.
ifeval::["{context}"=="openshift-ansible-playbook"]
Using the `oc` command, log on to the OpenShift environment as an administrative user.
endif::[]
Complete one of the following actions:
+
** Run the following command:
+
ifeval::["{context}"!="openshift-ansible-playbook"]
[subs="attributes,verbatim,macros"]
----
$ oc create -f {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-image-streams.yaml
----
endif::[]
ifeval::["{context}"=="openshift-ansible-playbook"]
[subs="attributes,verbatim,macros"]
----
$ oc create -f {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-image-streams.yaml -n openshift
----
endif::[]
+
** Using the OpenShift Web UI, select *Add to Project -> Import YAML / JSON*, then choose the file or paste its contents.
