[id='monitoring-deploy-assy']
= Deploying {CENTRAL} Monitoring and Smart Router for an environment with immutable servers

ifdef::context[:parent-context: {context}]
:context: monitoring
:LOCAL_CENTRAL: {CENTRAL} Monitoring
:what_deploying: monitoring and Smart Router for an environment with immutable servers
:what_deploying_brief: monitoring and Smart Router

You can deploy {CENTRAL} Monitoring and Smart Router for an environment with immutable servers.

You can use {CENTRAL} Monitoring to start and stop (but not deploy) services on your {KIE_SERVERS} and to view monitoring data. The {CENTRAL} Monitoring automatically discovers any {KIE_SERVERS} in the same namespace, including immutable {KIE_SERVERS} and managed {KIE_SERVERS}. This feature requires the `OpenShiftStartupStrategy` setting, which is enabled by default for all {KIE_SERVERS} except those deployed in a fixed managed infrastructure. For instructions about deploying managed {KIE_SERVERS} with the `OpenShiftStartupStrategy` setting enabled, see {URL_DEPLOYING_MANAGED_FREEFORM_ON_OPENSHIFT}[_{DEPLOYING_MANAGED_FREEFORM_ON_OPENSHIFT}_].

Smart Router is a single endpoint that can receive calls from client applications to any of your services and route each call automatically to the server that runs the service.

If you want to use {CENTRAL} Monitoring, you must provide a Maven repository. Your integration process must ensure that all the versions of KJAR files built into any {KIE_SERVER} image are also available in the Maven repository.

include::template-deploy-start-proc.adoc[leveloffset=+1]
include::template-deploy-mandatory-proc.adoc[leveloffset=+1]
include::template-deploy-namespace-proc.adoc[leveloffset=+1]
// include::template-deploy-nopubnet-proc.adoc[leveloffset=+1]
include::template-deploy-rhsso-proc.adoc[leveloffset=+1]
include::template-deploy-ldap-proc.adoc[leveloffset=+1]
include::template-deploy-complete-proc.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
