[id='offline-repo-proc']
= Preparing a Maven mirror repository for offline use

If your {OPENSHIFT} environment does not have outgoing access to the public Internet, you must prepare a Maven repository with a mirror of all the necessary artifacts and make this repository available to your environment.

You do not need to complete this procedure if your {OPENSHIFT} environment is connected to the Internet.

.Prerequisites

* A computer that has outgoing access to the public Internet.

.Procedure

ifeval::["{context}"=="openshift-immutable"]
. Prepare a Maven release repository to which you can write. The repository must allow read access without authentication. Your OpenShift environment must have access to this repository. You can deploy a Nexus repository manager in the OpenShift environment. For instructions about setting up Nexus on OpenShift, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/developer_guide/tutorials#nexus-setting-up-nexus[Setting up Nexus]. Use this repository as a mirror repository.
ifdef::PAM[]
If you are planning to create immutable servers from KJAR services or to deploy {CENTRAL} Monitoring,
endif::PAM[]
ifdef::DM[]
If you are planning to create immutable servers from KJAR services,
endif::DM[]
place your services in this repository as well. You must configure this repository as the external Maven repository. You cannot configure a separate mirror repository in an immutable environment.
endif::[]
ifeval::["{context}"!="openshift-immutable"]
. Prepare a Maven release repository to which you can write. The repository must allow read access without authentication. Your OpenShift environment must have access to this repository. You can deploy a Nexus repository manager in the OpenShift environment. For instructions about setting up Nexus on OpenShift, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/developer_guide/tutorials#nexus-setting-up-nexus[Setting up Nexus]. Use this repository as a separate mirror repository.
+
Alternatively, if you use a custom external repository (for example, Nexus) for your services, you can use the same repository as a mirror repository.
endif::[]
+
. On the computer that has an outgoing connection to the public Internet, complete the following steps:
.. Download the latest version of the http://release-engineering.github.io/offliner/[Offliner tool].
.. Download the `{PRODUCT_FILE}-offliner.txt` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.
.. Enter the following command to download the required artifacts using the Offliner tool:
+
[subs="attributes,verbatim,macros"]
----
java -jar offliner-<version>.jar -r https://maven.repository.redhat.com/ga/ -d /home/user/temp rhpam-7.3.1-offliner.txt
----
+
Replace `/home/user/temp` with an empty temporary directory on the computer and `<version>` with the version of the Offliner tool.
.. Upload all artifacts from the temporary directory to the Maven mirror repository that you prepared. You can use the https://github.com/simpligility/maven-repository-tools/tree/master/maven-repository-provisioner[Maven Repository Provisioner] utility to upload the artifacts.
. If you developed any services outside {CENTRAL} and they have additional dependencies, upload the dependencies to the mirror repository. If you developed the services as Maven projects, you can use the following steps to prepare these dependencies automatically. Complete the steps on the computer that has an outgoing connection to the public Internet.
.. Clear the local Maven cache directory (`~/.m2/repository`).
.. Build the source of your projects using the `mvn clean install` command.
.. For every project, enter the following command to ensure that Maven downloads all runtime dependencies for all the artifacts generated by the project:
+
[subs="attributes,verbatim,macros"]
----
mvn -e -DskipTests dependency:go-offline -f /path/to/project/pom.xml --batch-mode -Djava.net.preferIPv4Stack=true
----
+
Replace `/path/to/project/pom.xml` with the correct path to the `pom.xml` file of the project.
+
.. Upload all artifacts from the local Maven cache directory (`~/.m2/repository`) to the Maven mirror repository that you prepared. You can use the https://github.com/simpligility/maven-repository-tools/tree/master/maven-repository-provisioner[Maven Repository Provisioner] utility to upload the artifacts.
