[id='offline-repo-proc']
:offline_onprem!:
ifeval::["{context}"=="install-on-eap"]
:offline_onprem:
endif::[]
ifeval::["{context}"=="install-on-jws"]
:offline_onprem:
endif::[]
ifeval::["{context}"=="install-on-tomcat"]
:offline_onprem:
endif::[]

= Preparing a Maven mirror repository for offline use

If your
ifdef::offline_onprem[]
{PRODUCT} deployment
endif::offline_onprem[]
ifndef::offline_onprem[]
{OPENSHIFT} environment
endif::offline_onprem[]
does not have outgoing access to the public Internet, you must prepare a Maven repository with a mirror of all the necessary artifacts and make this repository available to your environment.

[NOTE]
====
You do not need to complete this procedure if your
ifdef::offline_onprem[]
{PRODUCT} deployment
endif::offline_onprem[]
ifndef::offline_onprem[]
{OPENSHIFT} environment
endif::offline_onprem[]
is connected to the Internet.
====

.Prerequisites

* A computer that has outgoing access to the public Internet is available.

.Procedure

ifndef::offline_onprem[]
ifeval::["{context}"=="openshift-immutable"]
. Configure a Maven release repository to which you have write access. The repository must allow read access without authentication and your OpenShift environment must have network access to this repository. You can deploy a Nexus repository manager in the OpenShift environment. For instructions about setting up Nexus on OpenShift, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/developer_guide/tutorials#nexus-setting-up-nexus[Setting up Nexus]. Use this repository as a mirror repository.
ifdef::PAM[]
If you are planning to create immutable servers from KJAR services or to deploy {CENTRAL} Monitoring,
endif::PAM[]
ifdef::DM[]
If you are planning to create immutable servers from KJAR services,
endif::DM[]
place your services in this repository as well. You must configure this repository as the external Maven repository. You cannot configure a separate mirror repository in an immutable environment.
endif::[]
ifeval::["{context}"!="openshift-immutable"]
. Configure a Maven release repository to which you have write access. The repository must allow read access without authentication and your OpenShift environment must have network access to this repository.
+
You can deploy a Nexus repository manager in the OpenShift environment. For instructions about setting up Nexus on OpenShift, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/developer_guide/tutorials#nexus-setting-up-nexus[Setting up Nexus] in the {OPENSHIFT} 3.11 documentation. 
ifeval::["{context}"=="openshift-operator"]
The documented procedure is applicable to {OPENSHIFT} version 4.
endif::[]
Use this repository as a separate mirror repository.
+
Alternatively, if you use a custom external repository (for example, Nexus) for your services, you can use the same repository as a mirror repository.
endif::[]
+
endif::offline_onprem[]
. On the computer that has an outgoing connection to the public Internet, complete the following steps:
.. Download the latest version of the http://release-engineering.github.io/offliner/[Offliner tool].
.. Download the `{PRODUCT_FILE}-offliner.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.
.. Extract the contents of the `{PRODUCT_FILE}-offliner.zip` file into any directory.
.. Change to the directory and enter the following command:
+
[subs="attributes,verbatim,macros"]
----
./offline-repo-builder.sh offliner.txt 
----
+
This command creates a `repository` subdirectory and downloads the necessary artifacts into this subdirectory. 
+
If a message reports that some downloads have failed, run the same command again. If downloads fail again, contact Red Hat support.
ifndef::offline_onprem[]
.. Upload all artifacts from the `repository` subdirectory to the Maven mirror repository that you prepared. You can use the Maven Repository Provisioner utility, available from the https://github.com/simpligility/maven-repository-tools/tree/master/maven-repository-provisioner[Maven repository tools] Git repository, to upload the artifacts.
endif::offline_onprem[]
. If you developed services outside {CENTRAL} and they have additional dependencies, add the dependencies to the mirror repository. If you developed the services as Maven projects, you can use the following steps to prepare these dependencies automatically. Complete the steps on the computer that has an outgoing connection to the public Internet.
.. Create a backup of the local Maven cache directory (`~/.m2/repository`) and then clear the directory.
.. Build the source of your projects using the `mvn clean install` command.
.. For every project, enter the following command to ensure that Maven downloads all runtime dependencies for all the artifacts generated by the project:
+
[subs="attributes,verbatim,macros"]
----
mvn -e -DskipTests dependency:go-offline -f /path/to/project/pom.xml --batch-mode -Djava.net.preferIPv4Stack=true
----
+
Replace `/path/to/project/pom.xml` with the correct path to the `pom.xml` file of the project.
+
ifndef::offline_onprem[]
.. Upload all artifacts from the local Maven cache directory (`~/.m2/repository`) to the Maven mirror repository that you prepared. You can use the Maven Repository Provisioner utility, available from the https://github.com/simpligility/maven-repository-tools/tree/master/maven-repository-provisioner[Maven repository tools] Git repository, to upload the artifacts.
endif::offline_onprem[]
ifdef::offline_onprem[]
.. Copy the contents of the local Maven cache directory (`~/.m2/repository`) to the `repository` subdirectory that was created.
. Copy the contents of the `repository` subdirectory to a directory on the computer on which you deployed {PRODUCT}. This directory becomes the offline Maven mirror repository.
. Create and configure a `settings.xml` file for your {PRODUCT} deployment, according to instructions in
ifeval::["{context}"=="install-on-eap"]
<<maven-external-configure-proc_install-on-eap>>.
endif::[]
ifeval::["{context}"=="install-on-jws"]
<<maven-settings-configuration-ref>>.
endif::[]
ifeval::["{context}"=="install-on-tomcat"]
<<maven-settings-configuration-ref>>.
endif::[]
. Make the following changes in the `settings.xml` file:
** Under the `<profile>` tag, if a `<repositories>` or `<pluginRepositores>` tag is absent, add the tags as necessary.
** Under `<repositories>` add the following sequence:
+
[source,xml]
----
<repository>
  <id>offline-repository</id>
  <url>file:///path/to/repo</url>
  <releases>
    <enabled>true</enabled>
  </releases>
  <snapshots>
    <enabled>false</enabled>
  </snapshots>
</repository>
----
+
Replace `/path/to/repo` with the full path to the local Maven mirror repository directory.
** Under `<pluginRepositories>` add the following sequence:
+
[source,xml]
----
<repository>
  <id>offline-plugin-repository</id>
  <url>file:///path/to/repo</url>
  <releases>
    <enabled>true</enabled>
  </releases>
  <snapshots>
    <enabled>false</enabled>
  </snapshots>
</repository>
----
+
Replace `/path/to/repo` with the full path to the local Maven mirror repository directory.
ifeval::["{context}"=="install-on-eap"]
+
. Set the `kie.maven.offline.force` property for {CENTRAL} to `true`. For instructions about setting properties for {CENTRAL}, see <<business-central-system-properties-ref>>.
endif::[]
endif::offline_onprem[]
