[id='openshift-usage-ref']
= OpenShift usage quick reference

To deploy, monitor, manage, and undeploy {PRODUCT} templates on {OPENSHIFT}, you can use the OpenShift Web console or the `oc` command. 

For instructions about using the Web console, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html-single/getting_started/#getting-started-developers-console[Create and build an image using the Web console].

For detailed instructions about using the `oc` command, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/cli_reference/[CLI Reference]. The following commands are likely to be required:

* To create a project, use the following command:
+
[subs="attributes,verbatim,macros"]
----
$ oc new-project <project-name>
----
+
For more information, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html-single/developer_guide/#create-a-project-using-the-cli[Creating a project using the CLI].

* To deploy a template (create an application from a template), use the following command:
+
[subs="attributes,verbatim,macros"]
----
$ oc new-app -f <template-name> -p <parameter>=<value> -p <parameter>=<value> ...
----
For more information, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html-single/developer_guide/#using-the-cli[Creating an application using the CLI].

* To view a list of the active pods in the project, use the following command:
+
[subs="attributes,verbatim,macros"]
----
$ oc get pods
----
 
* To view the current status of a pod, including information whether or not the pod deployment has completed and it is now in a running state, use the following command:
+
[subs="attributes,verbatim,macros"]
----
$ oc describe pod <pod-name>
----
+
You can also use the `oc describe` command to view the current status of other objects. For more information, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/cli_reference/cli-reference-basic-cli-operations#application-modification-cli-operations[Application modification operations].
 
* To view the logs for a pod, use the following command:
+
[subs="attributes,verbatim,macros"]
----
$ oc logs <pod-name>
----
 
* To view deployment logs, look up a `DeploymentConfig` name in the template reference and enter the following command:
[subs="attributes,verbatim,macros"]
+
----
$ oc logs -f dc/<deployment-config-name>
----
+
For more information, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html-single/developer_guide/#viewing-deployment-logs[Viewing deployment logs].

* To view build logs, look up a `BuildConfig` name in the template reference and enter the command:
+
[subs="attributes,verbatim,macros"]
----
$ oc logs -f bc/<build-config-name>
----
+
For more information, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html-single/developer_guide/#accessing-build-logs[Accessing build logs].

* To scale a pod in the application, look up a `DeploymentConfig` name in the template reference and enter the command:
+
[subs="attributes,verbatim,macros"]
----
$ oc scale dc/<deployment-config-name> --replicas=<number>
----
+
For more information, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html-single/developer_guide/#scaling[Manual scaling].

* To undeploy the application, you can delete the project by using the command:
+
[subs="attributes,verbatim,macros"]
----
$ oc delete project <project-name>
----
+
Alternatively, you can use the `oc delete` command to remove any part of the application, such as a pod or replication controller. For details, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/cli_reference/cli-reference-basic-cli-operations#application-modification-cli-operations[Application modification operations].
