[id='operator-deploy-smartrouter-proc_{context}']
= Setting Smart Router configuration for the environment

By default, the deployed environment does not include Smart Router. You can add a Smart Router to the environment. You can also set configuration options for the Smart Router.

.Prerequisites

* You completed basic configuration of a {PRODUCT} environment using {operator_name} in the installer wizard according to the instructions in <<operator-deploy-basic-proc_{context}>>.

.Procedure
. If the *Installation*, *Security*, *Console*, or *KIE Servers* tab is open, click *Next* until you view the *Smart Router* tab.
. Click *Set Smart Router* to add Smart Router to the environment and to configure Smart Router.
. If you have created a custom Smart Router image according to the instructions in xref:customimage-smartrouter-proc_{context}[], set the following values:
** *Image context*: The project name, for example, `{PRODUCT_INIT}-project`
** *Image*: The custom image name, for example, `{PRODUCT_INIT}-smartrouter-rhel8-custom`
+
If you used a custom tag for the image, set the *Image tag* field to this tag.
+
. If you created the secret for Smart Router according to the instructions in <<secrets-smartrouter-create-proc_{context}>>, enter the name of the secret in the *Secret* field.
. Optional: To configure {KIE_SERVER} for decision management only capabilities so that jBPM and case management features are disabled, select *Execute Kie Server only with Decisions capabilities*.
. Optional: Enter the number of replicas for the Smart Router in the *Replicas* field.
. Optional: To set a custom hostname for the external route, enter a domain in the *Custom hostname to be used on the Smart Router external Route* field, formatted as in the following example:
+
----
`smartrouter.example.com`
----
+
[NOTE]
====
The custom hostname must be valid and resolvable.

To change the custom hostname, you can modify the `routeHostname` property.
====
. Optional: To enable and set the Edge termination route, complete the following steps:
.. Under *Change route termination*, select *Enable Edge termination*.
.. Optional: In the *Key* field, enter the private key.
.. Optional: In the *Certificate* field, enter the certificate.
.. Optional: In the *CaCertificate* field, enter the CaCertificate.

. Optional: Enter requested and maximum CPU and memory limits in the fields under *Resource quotas*.
. Optional: Set the logging level using an environment variable:
.. Click *Add new Environment variable*.
.. In the *Name* field, enter `LOG_LEVEL`.
.. In the *Value* field, enter a Java logging level. For a list of the available logging levels, see https://cr.openjdk.java.net/~iris/se/11/latestSpec/api/java.logging/java/util/logging/Level.html[class Level].
.. Optional: Set different logging levels for components by package name:
... Click *Add new Environment variable*.
... In the *Name* field, enter `LOG_LEVEL`.
... In the *Value* field, enter packages and logging levels for them, formatted as in the following example:
+
----
com.example.abc=FINEST,com.example.def=SEVERE,com.example.xyz=FINE
----

.Next steps

If you want to deploy the Process Instance Migration service, continue to deploy the service. Otherwise, click *Finish* and then click *Deploy* to deploy the environment.
