[id='operator-deploy-smartrouter-proc_{context}']
= Setting Smart Router configuration for the environment

By default, the deployed environment does not include Smart Router. You can add a Smart Router to the environment. You can also set configuration options for the Smart Router.

.Prerequisites

* You completed basic configuration of a {PRODUCT} environment using {operator_name} in the installer wizard according to the instructions in <<operator-deploy-basic-proc_{context}>>.

.Procedure
. If the *Installation*, *Security*, *Console*, or *KIE Servers* tab is open, click *Next* until you view the *Smart Router* tab.
. Click *Set Smart Router* to add Smart Router to the environment and to configure Smart Router.
. If you have created a custom Smart Router image according to the instructions in xref:customimage-smartrouter-proc_{context}[], set the following values:
** *Image context*: The project name, for example, `{PRODUCT_INIT}-project`
** *Image*: The custom image name, for example, `{PRODUCT_INIT}-smartrouter-rhel8-custom`
+
If you used a custom tag for the image, set the *Image tag* field to this tag.
+
. If you created the secret for Smart Router according to the instructions in <<secrets-smartrouter-create-proc_{context}>>, enter the name of the secret in the *Secret* field.
. Optionally, enter the number of replicas for the Smart Router in the *Replicas* field.
. Optionally, enter requested and maximum CPU and memory limits in the fields under *Resource quotas*.

.Next steps

If you want to deploy the Process Instance Migration service, continue to deploy the service. Otherwise, click *Finish* and then click *Deploy* to deploy the environment.
