[id='operator-createapp-proc_{context}']
= Deploying a {PRODUCT} environment using the operator

After subscribing to the operator, you can _create an application_ to deploy an environment.

.Procedure

. Enter your project in the OpenShift Web cluster console.
. In the OpenShift Web console navigation panel, select *Operators* and then *Subscriptions*.
. Click the name of the subscription that contains `businessautomation`. Information about this subscription is displayed.
. Under the *Installed version* heading, click the version name of the subscription. An overview of the subscription is displayed.
. Click *Create KieApp*. A YAML source is displayed.
. Set the *name* field to an application name that is unique in the project.
. Set the *environment* field to the required environment type. Each of the types is a default deployment pattern. You can modify the pattern by editing this YAML source; you can also modify the deployment after it is completed. The following types are available:

ifdef::PAM[]
** `rhpam-trial`: A trial environment that you can set up quickly and use to evaluate or demonstrate developing and running assets. Includes {CENTRAL} and a {KIE_SERVER}. This environment does not use any persistent storage, and any work you do in the environment is not saved.
** `rhpam-production`: An environment for running existing services for staging and production purposes. This environment includes {CENTRAL} Monitoring, Smart Router, and two groups of {KIE_SERVER} pods. You can deploy and undeploy services on every such group and also scale the group up or down as necessary. Use {CENTRAL} Monitoring to deploy, run, and stop the services and to monitor their execution.
** `rhpam-production-immutable`: An alternate environment for running existing services for staging and production purposes. This environment includes {CENTRAL} Monitoring. You can configure one or more {KIE_SERVER} replicated pods that build a service from source. In this environment, when you deploy a {KIE_SERVER} pod, it builds an image that loads and starts a service or group of services. You cannot stop any service on the pod or add any new service to the pod. If you want to use another version of a service or modify the configuration in any other way, you deploy a new server image and displace the old one. In this system, {KIE_SERVER} runs like any other pod on the OpenShift environment. You can use any container-based integration workflows and do not need to use any other tools to manage the pods.
** `rhpam-authoring`: An environment for creating and modifying services using {CENTRAL}. It consists of pods that provide {CENTRAL} for the authoring work and a {KIE_SERVER} for test execution of the services.
** `rhpam-authoring-ha`: An environment for creating and modifying services using {CENTRAL}. It consists of pods that provide {CENTRAL} for the authoring work and a {KIE_SERVER} for test execution of the services. This version of the authoring environment supports scaling the {CENTRAL} pod to ensure high availability.
endif::PAM[]
ifdef::DM[]
** `rhdm-trial`: A trial environment that you can set up quickly and use to evaluate or demonstrate developing and running assets. Includes {CENTRAL} and a {KIE_SERVER}. This environment does not use any persistent storage, and any work you do in the environment is not saved.
** `rhdm-authoring`: An environment for creating and modifying services using {CENTRAL}. It consists of pods that provide {CENTRAL} for the authoring work and a {KIE_SERVER} for test execution of the services. You can also use this environment to run services for staging and production purposes. You can add {KIE_SERVERS} to the environment and they are managed by the same {CENTRAL}.
** `rhdm-authoring-ha`: An environment for creating and modifying services using {CENTRAL}. It consists of pods that provide {CENTRAL} for the authoring work and a {KIE_SERVER} for test execution of the services. This version of the authoring environment supports scaling the {CENTRAL} pod to ensure high availability.
** `rhdm-production-immutable`: An alternate environment for running existing services for staging and production purposes. You can configure one or more {KIE_SERVER} replicated pods that build a service from source. In this environment, when you deploy a {KIE_SERVER} pod, it builds an image that loads and starts a service or group of services. You cannot stop any service on the pod or add any new service to the pod. If you want to use another version of a service or modify the configuration in any other way, you deploy a new server image and displace the old one. In this system, {KIE_SERVER} runs like any other pod on the OpenShift environment. You can use any container-based integration workflows and do not need to use any other tools to manage the pods.
endif::DM[]

+
. Add lines to the YAML source to modify the environment, using the snippets listed in this document as a reference:
** The following snippet adds an immutable {KIE_SERVER} pod that builds a service from source. You must add at least one copy of this snippet when creating an immutable environment.
+
[subs="attributes,verbatim,macros"]
----
  objects:
    servers:
      - build:
          kieServerContainerDeployment: <deployment>
          gitSource:
            uri: <url>
            reference: <branch>
            contextDir: <directory>
----
+
Replace the following values:
+
*** `<deployment>`: The identifying information of the decision service (KJAR file) that is built from your source. The format is `<containerId>=<groupId>:<artifactId>:<version>`. You can provide two or more KJAR files using the `|` separator, for example `containerId=groupId:artifactId:version|c2=g2:a2:v2`. The Maven build process must produce all these files from the source in the Git repository.
*** `<url>`: The URL for the Git repository that contains the source for your decision service.
*** `<branch>`: The branch in the Git repository.
*** `<directory>`: The path to the source within the project downloaded from the Git repository.
+
ifdef::PAM[]
** The following snippet configures the number and settings of {KIE_SERVERS} that are managed by {CENTRAL} or {CENTRAL} Monitoring in your environment, as well as a Smart Router. Six servers, under three different name sets, are included in the snippet.
+
[subs="attributes,verbatim,macros"]
----
apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: server-config
spec:
  environment: <environment_type>
  objects:
    console:
      env:
        - name: MY_VALUE
          value: "example"
    servers:
      # Kieserver sets will be named sequentially server-config-kieserver1, server-config-kieserver1-2
      - deployments: 2
        # Env variables that will be added to all the kie servers in this set
        env:
          - name: MY_VALUE
            value: "example"
        # Override default memory limits for all the kie servers in this set
        resources:
          limits:
            memory: 2Gi
      # Kieserver sets will be named sequentially server-config-kieserver2, server-config-kieserver2-2
      - deployments: 2
        # Env variables that will be added to all the kie servers in this set
        env:
          - name: MY_VALUE
            value: "example"
      # Kieserver sets will be named sequentially server, server-2
      - name: server
        deployments: 2
        env:
          - name: MY_VALUE
            value: "example"
        # Override default memory limits for all the kie servers in this set
        resources:
          limits:
            memory: 2Gi
  smartRouter:
    env:
      - name: MY_VALUE
        value: "example"
----
endif::PAM[]
ifdef::DM[]
** The following snippet configures the number and settings of {KIE_SERVERS} that are managed by an existing {CENTRAL} in your environment. Six servers, under three different name sets, are included in the snippet.
+
[subs="attributes,verbatim,macros"]
----
apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: server-config
spec:
  environment: <environment_type>
  objects:
    console:
      env:
        - name: MY_VALUE
          value: "example"
    servers:
      # Kieserver sets will be named sequentially server-config-kieserver1, server-config-kieserver1-2
      - deployments: 2
        # Env variables that will be added to all the kie servers in this set
        env:
          - name: MY_VALUE
            value: "example"
        # Override default memory limits for all the kie servers in this set
        resources:
          limits:
            memory: 2Gi
      # Kieserver sets will be named sequentially server-config-kieserver2, server-config-kieserver2-2
      - deployments: 2
        # Env variables that will be added to all the kie servers in this set
        env:
          - name: MY_VALUE
            value: "example"
      # Kieserver sets will be named sequentially server, server-2
      - name: server
        deployments: 2
        env:
          - name: MY_VALUE
            value: "example"
        # Override default memory limits for all the kie servers in this set
        resources:
          limits:
            memory: 2Gi
----
endif::DM[]
+
Replace `<environment_type>` with the type of environment that you want to configure.
+
ifdef::PAM[]
** The following snippet configures {KIE_SERVERS}, a {CENTRAL} or {CENTRAL} Monitoring, and a Smart Router using existing secrets for HTTPS communication, as required for a production environment. In this example, two servers are created with the `server-a-keystore` secret. (For instructions about creating the secrets, see <<secrets-central-create-proc_{context}>>, <<secrets-kie-create-proc_{context}>>, and <<secrets-smartrouter-create-proc_{context}>>.)
+
[subs="attributes,verbatim,macros"]
----
apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: keystore-config
spec:
  environment: <environment_type>
  objects:
    console:
      keystoreSecret: console-keystore
    servers:
      - name: server-a
        deployments: 2
        keystoreSecret: server-a-keystore
      - name: server-b
        keystoreSecret: server-b-keystore
    smartRouter:
      keystoreSecret: smartrouter-keystore
----
endif::PAM[]
ifdef::DM[]
** The following snippet configures {KIE_SERVERS} and a {CENTRAL} using existing secrets for HTTPS communication, as required for a production environment. In this example, two servers are created with the `server-a-keystore` secret. (For instructions about creating the secrets, see <<secrets-central-create-proc_{context}>> and <<secrets-kie-create-proc_{context}>>.)
+
[subs="attributes,verbatim,macros"]
----
apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: keystore-config
spec:
  environment: <environment_type>
  objects:
    console:
      keystoreSecret: console-keystore
    servers:
      - name: server-a
        deployments: 2
        keystoreSecret: server-a-keystore
      - name: server-b
        keystoreSecret: server-b-keystore
----
endif::DM[]
+
Replace `<environment_type>` with the type of environment that you want to configure.
+
** The following snippet sets the password for the administrator user (`admin`) and the application name (`app2`):
+
[subs="attributes,verbatim,macros"]
----
  commonConfig:
    adminPassword: password
    applicationName: app2
----
+
** The following snippet sets up LDAP authentication. The parameters correspond to the settings of the LdapExtended Login module of {EAP}. For instructions about using these settings, see https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html-single/login_module_reference/#ldapextended_login_module[LdapExtended Login Module].
+
[subs="attributes,verbatim,macros"]
----
auth:
  ldap:
    url: ldaps://myldap.example.com
    bindDN: uid=admin,ou=users,ou=example,ou=com
    bindCredential: s3cret
    baseCtxDN: ou=users,ou=example,ou=com
    baseFilter: (uid={0})
    searchScope: SUBTREE_SCOPE
    roleAttributeID: memberOf
    rolesCtxDN: ou=groups,ou=example,ou=com
    roleFilter: (memberOf={1})
    defaultRole: guest
  roleMapper:
    rolesProperties: /conf/roleMapper.properties
    replaceRole: true
----
+
If the LDAP server does not define all the roles required for your deployment, you can map LDAP groups to {PRODUCT} roles. To enable LDAP role mapping, set the `rolesProperties` value to the fully qualified path name of a file that defines role mapping, for example, `/opt/eap/standalone/configuration/rolemapping/rolemapping.properties`. You must provide this file and mount it at this path in all applicable deployment configurations. For instructions about providing this file, see <<rolemapping-proc_{context}>>.
+
If the `replaceRole` parameter is set to `true`, mapped roles replace the roles defined on the LDAP server. It the parameter is set to `false`, both mapped roles and roles defined on the LDAP server are set as user application roles. The default setting is `false`.
. After completing the modification of the YAML source, click *Create* to create the application.

[NOTE]
====
You can view other configuration samples, for example, for servers that use different database servers, at https://github.com/kiegroup/kie-cloud-operator/tree/1.0.1/deploy/examples
====
