[id='operator-deploy-security-proc_{context}']
= Setting the security configuration of the environment

After you set the basic configuration of a {PRODUCT} environment using {operator_name}, you can optionally configure authentication (security) settings for the environment.

.Prerequisites

* You completed basic configuration of a {PRODUCT} environment using {operator_name} in the installer wizard according to the instructions in <<operator-deploy-basic-proc_{context}>>.
* If you want to use RH-SSO or LDAP for authentication, you created users with the correct roles in your authentication system. You must create at least one administrative user (for example, `adminUser`) with the `kie-server,rest-all,admin` roles. This user must have the user name and password that you configured on the *Installation* tab.
* If you want to use RH-SSO authentication, you created the clients in your RH-SSO system for all components of your environment, specifying the correct URLs. This action ensures maximum control. Alternatively, the deployment can create the clients.

.Procedure
. If the *Installation* tab is open, click *Next* to view the *Security* tab.
. In the *Authentication mode* list, select one of the following modes:
** `Internal`: You configure the initial administration user when deploying the environment. The user can use {CENTRAL} to set up other users as necessary.
** `RH-SSO`: {PRODUCT} uses {RH-SSO} for authentication.
** `LDAP`: {PRODUCT} uses LDAP for authentication
. Complete the security configuration based on the *Authentication mode* that you selected.
+
--

If you selected `RH-SSO`, configure RH-SSO authentication:

.. In the *RH-SSO URL* field, enter the RH-SSO URL.
.. In the *Realm* field, enter the RH-SSO realm name.
.. If you did not create RH-SSO clients for components of your environment enter the credentials of an administrative user for your RH-SSO system in the *SSO admin user* and *SSO admin password* fields.
.. If your RH-SSO system does not have a proper signed SSL certificate, select the *Disable SSL cert validation* box.
.. If you want to change the RH-SSO principal attribute used for the user name, in the *Principal attribute* field enter the name of the new attribute.

If you selected `LDAP`, configure LDAP authentication:

.. In the *LDAP URL* field, enter the LDAP URL.
.. Configure LDAP parameters that correspond to the settings of the LdapExtended Login module of {EAP}. For instructions about using these settings, see https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html/login_module_reference/login_modules_with_external_identity_store#ldapextended_login_module[LdapExtended Login Module].
+
[NOTE]
====
If you want to enable LDAP failover, you can set two or more LDAP server addresses in the `AUTH_LDAP_URL` parameter, separated by a space.
====

--
. If you selected `RH-SSO` or `LDAP`, if your RH-SSO or LDAP system does not define all the roles required for your deployment, you can map authentication system roles to {PRODUCT} roles.
+
To enable role mapping, you must provide a role mapping configuration file in an OpenShift configuration map or secret object in the project namespace. The file must contain entries in the following format:
+
[subs="attributes,verbatim,macros"]
----
ldap_role = product_role1, product_role2...
----
+
For example:
+
[subs="attributes,verbatim,macros"]
----
admins = kie-server,rest-all,admin
----
+
To enable the use of this file, make the following changes:
+
.. Under *RoleMapper*, in the *Roles properties file* field, enter the fully qualified path name of the role mapping configuration file, for example, `/opt/eap/standalone/configuration/rolemapping/rolemapping.properties`.
.. If you want to replace roles defined in the authentication system with roles that you define in the mapping file, select the *Replace roles* box. Otherwise, both the roles defined in RH-SSO or LDAP and the roles defined in the configuration file are available.
.. In the fields under *RoleMapper Configuration object*, select the *Kind* of the object that provides the file (`ConfigMap` or `Secret`) and enter the *Name* of the object. This object is automatically mounted on {CENTRAL} and {KIE_SERVER} pods in the path that you specified for the role mapping configuration file.
. Configure other passwords, if necessary:
** *AMQ password* and *AMQ cluster password* are passwords for interaction with ActiveMQ using the JMS API.
** *Keystore password* is the password for the keystore files used in secrets for HTTPS communication. Set this password if you created secrets according to instructions in <<secrets-kie-create-proc_{context}>> or <<secrets-central-create-proc_{context}>>.
** *Database password* is the password for database server pods that are a part of the environments.


.Next steps

If you want to deploy the environment with the default configuration of all components, click *Finish* and then click *Deploy* to deploy the environment. Otherwise, continue to set configuration parameters for
ifdef::PAM[{CENTRAL}, {KIE_SERVERS}, and Smart Router.]
ifdef::DM[{CENTRAL} and {KIE_SERVERS}.]
