[id='operator-deploy-pim-proc']
= Setting Process Instance Migration configuration for the environment

You can use the operator to deploy the Process Instance Migration (PIM) service. You can use the PIM service to define the migration between two different process definitions, known as a migration plan. You can apply the migration plan to the running process instances in a specific {KIE_SERVER}. 

The PIM service uses a database server for its operation.

.Prerequisites

* You completed basic configuration of a {PRODUCT} environment using {operator_name} in the installer wizard according to the instructions in <<operator-deploy-basic-proc>>.

.Procedure
. If the *Installation*, *Security*, *Console*, *KIE Servers*, or *Smart Router* tab is open, click *Next* until you view the *Process Instance Migration* tab.
. Click *Set Process Instance Migration* to add PIM to the environment and to configure PIM.
. In the *Database type* field, select the database that the PIM service must use. The following values are available:
** `mysql`: A MySQL server, created in a separate pod.
** `postgresql`: A PostgreSQL server, created in a separate pod. Use this setting unless you have a specific reason to use any other setting.
** `h2`: A built-in `h2` database engine that does not require a separate pod.
** `external`: An external database server. MySQL, PostgreSQL, and MariaDB dataase servers are supported.
. If you selected any database type except `external`, a Persistent Volume Claim will be created to store the database. Optionally, set configuration parameters of the persistent volume to create:
** In the *Size* field, enter the size of the persistence volume
** In the *StorageClass name* field, enter the storage class name for the persistent volume
. If you selected the `external` database type, provide the following information in additional fields:
.. *Driver*: Enter the database server driver, depending on the server type:
+
*** `mysql`
*** `postgresql`
*** `mariadb`
+
.. *Dialect*: Enter the Hibernate dialect for the server, depending on the server type. The common settings are:
+
*** `org.hibernate.dialect.MySQL5InnoDBDialect`
*** `org.hibernate.dialect.MySQL8Dialect` 
*** `org.hibernate.dialect.MariaDB102Dialect`
*** `org.hibernate.dialect.PostgreSQL95Dialect`
*** `org.hibernate.dialect.PostgresPlusDialect` (used for EntrepriseDB Postgres Advanced Server)
+
For a complete list of supported dialects, see Table A.7 in https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html-single/developing_hibernate_applications/index#hibernate_properties[Hibernate properties] in the {EAP} documentation.
+
.. *Host*: Enter the host name of the external database server.
.. *Port*: Enter the port number of the external database server.
.. *Jdbc URL*: Enter the JDBC URL for the external database server.
.. *NonXA*: Select this box if you want to configure the data source in non-XA mode.
.. *JNDI name*: Enter the JNDI name that the application uses for the data source.
.. *User name* and *Password*: Enter the user name and password for the external database server.
.. *Background validation*: Optionally, select this box to enable background SQL validation and enter the background validation interval.
.. Optionally, set the minimum and maximum connection pool sizes, valid connection checker class, and exception sorter class for the database server.

.Next steps

Click *Finish* and then click *Deploy* to deploy the environment.

For instructions about using the PIM service, see {URL_MANAGING_PROCESSES}/process-instance-migration-con#process-instance-migration-con[Process Instance Migration] in _{MANAGING_PROCESSES}_.
