[id='operator-deploy-basic-proc']
= Setting the basic configuration of the environment

After you start to deploy a {PRODUCT} environment using {operator_name}, you must select the type of the environment and set other basic configuration.

.Prerequisites

* You started to deploy a {PRODUCT} environment using {operator_name} and accessed the installer wizard according to the instructions in <<operator-deploy-start-proc>>.

.Procedure
. In the *Application Name* field, enter a name for the OpenShift application. This name is used in the default URLs for all components.
. In the *Environment* list, select the type of environment. This type determines the default configuration; you can modify this configuration as necessary. The following types are available for {PRODUCT}:
ifdef::PAM[]
** `rhpam-trial`: A trial environment that you can set up quickly and use to evaluate or demonstrate developing and running assets. Includes {CENTRAL} and a {KIE_SERVER}. This environment does not use any persistent storage, and any work you do in the environment is not saved.
** `rhpam-authoring`: An environment for creating and modifying services using {CENTRAL}. It consists of pods that provide {CENTRAL} for the authoring work and a {KIE_SERVER} for test execution of the services.
** `rhpam-authoring-ha`: An environment for creating and modifying services using {CENTRAL}. It consists of pods that provide {CENTRAL} for the authoring work and a {KIE_SERVER} for test execution of the services. This version of the authoring environment supports scaling the {CENTRAL} pod to ensure high availability.
+
[IMPORTANT]
====
In {PRODUCT} {ENTERPRISE_VERSION}, high-availability {CENTRAL} functionality deployment using the operator is for Technology Preview only. For more information about Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope]. For a fully supported high-availabilityAvailability deployment, use the high-availability authoring template on {OPENSHIFT} version 3.11. For instructions about deploying this template, see
ifdef::PAM[]
{URL_DEPLOYING_AUTHORING_ON_OPENSHIFT}[_{DEPLOYING_AUTHORING_ON_OPENSHIFT}_].
endif::PAM[]
ifdef::DM[]
{URL_DEPLOYING_AUTHORING_MANAGED_ON_OPENSHIFT}[_{DEPLOYING_AUTHORING_MANAGED_ON_OPENSHIFT}_].
endif::DM[]
====
+
** `rhpam-production`: An environment for running existing services for staging and production purposes. This environment includes {CENTRAL} Monitoring, Smart Router, and two groups of {KIE_SERVER} pods. You can deploy and undeploy services on every such group and also scale the group up or down as necessary. Use {CENTRAL} Monitoring to deploy, run, and stop the services and to monitor their execution.
** `rhpam-production-immutable`: An alternate environment for running existing services for staging and production purposes. This environment includes {CENTRAL} Monitoring. You can configure one or more {KIE_SERVER} pods that build a service from source and replicate each pod as necessary. In this environment, when you deploy a {KIE_SERVER} pod, it builds an image that loads and starts a service or group of services. You cannot stop any service on the pod or add any new service to the pod. If you want to use another version of a service or modify the configuration in any other way, you deploy a new server image to replace the old one. In this system, the {KIE_SERVER} runs like any other pod on the OpenShift environment. You can use any container-based integration workflows and you do not need to use any other tools to manage the pods.
endif::PAM[]
ifdef::DM[]
** `rhdm-trial`: A trial environment that you can set up quickly and use to evaluate or demonstrate developing and running assets. Includes {CENTRAL} and a {KIE_SERVER}. This environment does not use any persistent storage, and any work you do in the environment is not saved.
** `rhdm-authoring`: An environment for creating and modifying services using {CENTRAL}. It consists of pods that provide {CENTRAL} for the authoring work and a {KIE_SERVER} for test execution of the services. You can also use this environment to run services for staging and production purposes. You can add {KIE_SERVERS} to the environment and they are managed by the same {CENTRAL}.
** `rhdm-authoring-ha`: An environment for creating and modifying services using {CENTRAL}. It consists of pods that provide {CENTRAL} for the authoring work and a {KIE_SERVER} for test execution of the services. This version of the authoring environment supports scaling the {CENTRAL} pod to ensure high availability.
+
[IMPORTANT]
====
In {PRODUCT} {ENTERPRISE_VERSION}, high-availability {CENTRAL} functionality is for Technology Preview only. For more information about Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
+
** `rhdm-production-immutable`: An alternate environment for running existing services for staging and production purposes. You can configure one or more {KIE_SERVER} replicated pods that build a service from source. In this environment, when you deploy a {KIE_SERVER} pod, it builds an image that loads and starts a service or group of services. You cannot stop any service on the pod or add any new service to the pod. If you want to use another version of a service or modify the configuration in any other way, you deploy a new server image and displace the old one. In this system, the {KIE_SERVER} runs like any other pod on the OpenShift environment. You can use any container-based integration workflows and do not need to use any other tools to manage the pods.
endif::DM[]
+
. If you want to enable automatic upgrades to new versions, select the *Enable Upgrades* box. If this box is selected, when a new patch version of {PRODUCT} {ENTERPRISE_VERSION} becomes available, the operator automatically upgrades your deployment to this version. All services are preserved and normally remain available throughout the upgrade process.
+
If you also want to enable the same automatic upgrade process when a new minor version of {PRODUCT} 7.x becomes available, select the *Include minor version upgrades* box.
+
[NOTE]
====
Disable automatic updates if you want to use a custom image for any component of {PRODUCT}.
====
+
. If you want to use a custom image registry, under *Custom registry*, enter the URL of the registry in the *Image registry* field. If this registry does not have a properly signed and recognized SSL certificate, select the *Insecure* box.
. Under *Admin user*, enter the user name and password for the administrative user for {PRODUCT} in the *Username* and *Password* fields. 
+
[IMPORTANT]
====
If you use RH-SSO or LDAP authentication, the same user must be configured in your authentication system with the `kie-server,rest-all,admin` roles for {PRODUCT}.
====
. If you want to use a custom version tag for images, complete the following steps:
.. Click *Next* to access the *Security* tab.
.. Scroll to the bottom of the window.
.. Enter the image tag in the *Image tag* field.

.Next steps

If you want to deploy the environment with the default configuration, click *Finish* and then click *Deploy* to deploy the environment. Otherwise, continue to set other configuration parameters.
