[id='operator-deploy-central-proc']
= Setting the {CENTRAL} configuration of the environment

After you set the basic and security configuration of a {PRODUCT} environment using {operator_name}, you can optionally configure settings for the {CENTRAL} or {CENTRAL} Monitoring component of the environment.

ifdef::DM[]
Do not change these settings for an immutable server environment, as this environment does not include {CENTRAL} or {CENTRAL} Monitoring.
endif::DM[]

.Prerequisites

* You completed basic configuration of a {PRODUCT} environment using {operator_name} in the installer wizard according to the instructions in xref:operator-deploy-basic-proc[].
* If you want to use RH-SSO or LDAP for authentication, you completed security configuration according to the instructions in xref:operator-deploy-security-proc[].

.Procedure
. If the *Installation* or *Security* tab is open, click *Next* until you view the *Console* tab.
. If you created the secret for {CENTRAL} according to the instructions in <<secrets-central-create-proc>>, enter the name of the secret in the *Secret* field.
. Optionally, configure Git hooks.
+
In an authoring environment, you can use Git hooks to facilitate interaction between the internal Git repository of {CENTRAL} and an external Git repository. If you want to use Git hooks, you must prepare a Git hooks directory in an OpenShift configuration map, secret, or persistent volume claim object in the project namespace. Alternatively, you can create a custom {CENTRAL} image with the directory, as described in xref:customimage-bc-githooks-proc_{context}[]. 
+
To use a Git hooks directory, make the following changes:
+
.. Under *GitHooks*, in the *Mount path* field, enter a fully qualified path for the directory, for example, `/opt/kie/data/git/hooks`.
.. If you did not use a custom image, in the fields under *GitHooks Configuration object*, select the *Kind* of the object that provides the file (`ConfigMap`, `Secret`, or `PersistentVolumeClaim`) and enter the *Name* of the object. This object is automatically mounted on the {CENTRAL} pods in the path that you specified for the Git hooks directory.
. Optionally, enter the number of replicas for {CENTRAL} or {CENTRAL} monitoring in the *Replicas* field. Do not change this number in a `{PRODUCT_INIT}-authoring` environment.
. Optionally, enter requested and maximum CPU and memory limits in the fields under *Resource quotas*.
. If you want to customize the configuration of the Java virtual machine on the {CENTRAL} pods, select the *Enable JVM configuration* box and then enter information in any of the fields under *Enable JVM configuration*. All fields are optional. For the JVM parameters that you can configure, see <<jvm-settings-ref>>.
. If you selected RH-SSO authentication, configure RH-SSO for {CENTRAL}:
.. Enter the client name in the *Client name* field and the client secret in the *Client secret* field. If a client with this name does not exist, the deployment attempts to create a new client with this name and secret.
.. If the deployment is to create a new client, enter the HTTP and HTTPS URLs that will be used for accessing the {KIE_SERVER} into the *SSO HTTP URL* and *SSO HTTPS URL* fields. This information is recorded in the client.
. Optionally, depending on your needs, set environment variables. To set an environment variable, click *Add new Environment variable*, then enter the name and value for the variable in the *Name* and *Value* fields.
ifdef::PAM[]
** In a `rhpam-production` or `rhpam-production-immutable` environment, if you want {CENTRAL} Monitoring to run in a simplified mode that does not use a file system, set the `ORG_APPFORMER_SIMPLIFIED_MONITORING_ENABLED` to `true`.
+
In the simplified mode, {CENTRAL} Monitoring does not require a persistent volume claim. You can use this mode in environments that do not support `ReadWriteMany` access to persistent storage. You can not use {CENTRAL} Monitoring in the simplified mode to design custom dashboards.
+
endif::PAM[]
** If you want to use an external Maven repository, set the following variables:
*** `MAVEN_REPO_URL`: The URL for the Maven repository
*** `MAVEN_REPO_ID`: An identifier for the Maven repository, for example, `repo-custom`
*** `MAVEN_REPO_USERNAME`: The user name for the Maven repository
*** `MAVEN_REPO_PASSWORD` The password for the Maven repository
+
[IMPORTANT]
====
In an authoring environment, if you want {CENTRAL} to push a project into an external Maven repository, you must configure this repository during deployment and also configure exporting to the repository in every project. For information about exporting {CENTRAL} projects to an external Maven repository, see {URL_PACKAGING_DEPLOYING_PROJECT}#maven-external-export-proc_packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].
====
+
** If your OpenShift environment does not have a connection to the public Internet, configure access to a Maven mirror that you set up according to <<offline-repo-proc>>. Set the following variables:
*** `MAVEN_MIRROR_URL`: The URL for the Maven mirror repository that you set up in <<offline-repo-proc>>. This URL must be accessible from a pod in your OpenShift environment.
*** `MAVEN_MIRROR_OF`: The value that determines which artifacts are to be retrieved from the mirror. For instructions about setting the `mirrorOf` value, see https://maven.apache.org/guides/mini/guide-mirror-settings.html[Mirror Settings] in the Apache Maven documentation. The default value is `external:*`. With this value, Maven retrieves every required artifact from the mirror and does not query any other repositories.
+
If you configure an external Maven repository (`MAVEN_REPO_URL`), change `MAVEN_MIRROR_OF` to exclude the artifacts in this repository from the mirror, for example, `external:*,!repo-custom`. Replace `repo-custom` with the ID that you configured in `MAVEN_REPO_ID`.
+
If your authoring environment uses a built-in {CENTRAL} Maven repository, change `MAVEN_MIRROR_OF` to exclude the artifacts in this repository from the mirror: `external:*,!repo-{PRODUCT_INIT}centr`.
+
** In some authoring environments, you might need to ensure that several users can deploy services on the same {KIE_SERVER} at the same time. By default, after deploying a service onto a {KIE_SERVER} using {CENTRAL}, the user needs to wait for some seconds before more services can be deployed. To remove this limitation, you can configure the environment to use the _controller strategy_. Do not make this change unless a specific need for it exists; if you decide to enable controller strategy, make this change on {CENTRAL} and on all {KIE_SERVERS} in the same environment.
+
[NOTE]
====
Do not enable the controller strategy in an environment with a high-availability {CENTRAL}. In such environments the controller strategy does not function correctly. 
====
+
To enable the controller strategy on {CENTRAL}, set the  `KIE_SERVER_CONTROLLER_OPENSHIFT_ENABLED` environment variable to `false`.

//** In an authoring environment, to configure a Git hooks directory, set the following variable:
//*** `GIT_HOOKS_DIR`: The fully qualified path to a Git hooks directory, for example, `/opt/eap/standalone/data/kie/git/hooks`. You must provide the content of this directory and mount it at the specified path. For instructions about providing and mounting the Git hooks directory, see <<githooks-proc>>.

.Next steps

If you want to deploy the environment with the default configuration of
ifdef::PAM[]
{KIE_SERVERS}, without Smart Router, and without Process Instance Migration,
endif::PAM[]
ifdef::DM[]
{KIE_SERVERS},
endif::DM[]
click *Finish* and then click *Deploy* to deploy the environment. Otherwise, continue to set configuration parameters for 
ifdef::PAM[]
{KIE_SERVERS} and Smart Router.
endif::PAM[]
ifdef::DM[]
{KIE_SERVERS}.
endif::DM[]
