[id='operator-deploy-security-proc_{context}']
= Setting the security configuration of the environment

After you set the basic configuration of a {PRODUCT} environment using {operator_name}, you can optionally configure authentication (security) settings for the environment.

.Prerequisites

* You completed basic configuration of a {PRODUCT} environment using {operator_name} in the installer wizard according to the instructions in <<operator-deploy-basic-proc_{context}>>.
* If you want to use RH-SSO or LDAP for authentication, you created users with the correct roles in your authentication system. You must create at least one administrative user (for example, `adminUser`) with the `kie-server,rest-all,admin` roles. This user must have the user name and password that you configured on the *Installation* tab.
* If you want to use RH-SSO authentication, you created the clients in your RH-SSO system for all components of your environment, specifying the correct URLs. This action ensures maximum control. Alternatively, the deployment can create the clients.

.Procedure
. If the *Installation* tab is open, click *Next* to view the *Security* tab.
. In the *Authentication mode* list, select one of the following modes:
** `Internal`: You configure the initial administration user when deploying the environment. You can create a post-configuration script to add users in the Elytron security subsystem. For instructions about creating a post-configuration script, see xref:jboss-postconfigure-proc_{context}[].
** `RH-SSO`: {PRODUCT} uses {RH-SSO} for authentication.
** `LDAP`: {PRODUCT} uses LDAP for authentication
. Complete the security configuration based on the *Authentication mode* that you selected:
+
--

If you selected `RH-SSO`, configure RH-SSO authentication:

.. In the *RH-SSO URL* field, enter the RH-SSO URL.
.. In the *Realm* field, enter the RH-SSO realm name.
.. If you did not create RH-SSO clients for components of your environment enter the credentials of an administrative user for your RH-SSO system in the *SSO admin user* and *SSO admin password* fields.
.. If your RH-SSO system does not have a proper signed SSL certificate, select the *Disable SSL cert validation* box.
.. If you want to change the RH-SSO principal attribute used for the user name, in the *Principal attribute* field enter the name of the new attribute.

If you selected `LDAP`, configure LDAP authentication:

[IMPORTANT]
====
The `baseFilter` field is a legacy LDAP search filter used to locate the context of the user to authenticate. The input `username` or `userDN` obtained from the login module callback is substituted into the filter anywhere a `{0}` expression is used. A common example for the search filter is `(uid={0})`. For Elytron based subsystems, this property should be configured only with the search filter parameter, without any search expression. For example, search for `uid` instead of `(uid={0})`.
====
.. In the *LDAP URL* field, enter the LDAP URL.
.. Set LDAP parameters. These parameters configure LDAP authentication using the Elytron subsystem of {EAP}. For more information about using the Elytron subsystem of {EAP} with LDAP, see https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/{EAP_VERSION}/html/how_to_configure_identity_management/elytron_secure_apps#elytron_ldap_auth_app[Configure Authentication with an LDAP-Based Identity Store].
+
[NOTE]
====
If you want to enable LDAP failover, you can set two or more LDAP server addresses in the `AUTH_LDAP_URL` parameter, separated by a space.
====

--
. If you selected `RH-SSO` or `LDAP`, if your RH-SSO or LDAP system does not define all the roles required for your deployment, you can map authentication system roles to {PRODUCT} roles.
+
To enable role mapping, you must provide role mapping either as a single configuration string or as a role mapping configuration file. If you use a file for role mapping configuration, you must provide the file in an OpenShift configuration map or secret object in the project namespace.
+
The string must use the `role=role1,role2;another-role=role2` pattern, for example `admins=kie-server,rest-all,admin;developers=kie-server,rest-all`.
+
The file must contain entries in the following format:
+
[subs="attributes,verbatim,macros"]
----
ldap_role=product_role1, product_role2...
----
+
For example:
+
[subs="attributes,verbatim,macros"]
----
admins=kie-server,rest-all,admin
----
+
To enable the use of this string or file, make the following changes:
+
.. Under *RoleMapper*, in the *Roles properties file* field, enter the role configuration string or the fully qualified path name of the role mapping configuration file, for example `/opt/eap/standalone/configuration/rolemapping/rolemapping.properties`.
.. Optional: Select the *Roles keep mapped* box or the *Roles keep non mapped* box. If you define role mapping, by default only the roles that you define in the mapping are available. If you want to keep the original roles that are defined in the authentication system and that your mapping maps to other roles, select the *Roles keep mapped* box. If you want to keep the original roles that are defined in the authentication system and not mentioned in your mapping,select the *Roles keep non mapped* box.
.. If you are using a role configuration file, configure the fields under *RoleMapper Configuration object*:
*** Under the *Kind* label, select the kind of the object that provides the file (`ConfigMap` or `Secret`).
*** In the *Name* field, enter the name of the object. This object is automatically mounted on {CENTRAL} and {KIE_SERVER} pods in the path that you specified for the role mapping configuration file.
+
. Configure other passwords, if necessary:
** *AMQ password* and *AMQ cluster password* are passwords for interaction with ActiveMQ using the JMS API.
** *Keystore password* is the password for the keystore files used in secrets for HTTPS communication. Set this password if you created secrets according to instructions in <<secrets-kie-create-proc_{context}>> or <<secrets-central-create-proc_{context}>>.
** *Database password* is the password for database server pods that are a part of the environments.

.Next steps

If you want to deploy the environment with the default configuration of all components, click *Finish* and then click *Deploy* to deploy the environment. Otherwise, continue to set configuration parameters for
ifdef::PAM[{CENTRAL}, {KIE_SERVERS}, and Smart Router.]
ifdef::DM[{CENTRAL} and {KIE_SERVERS}.]
