[id='operator-deploy-central-proc_{context}']
= Setting the {CENTRAL} configuration of the environment

After you set the basic and security configuration of a {PRODUCT} environment using {operator_name}, you can optionally configure settings for the {CENTRAL}
ifdef::PAM[]
or {CENTRAL} Monitoring
endif::PAM[]
component of the environment.

All environment types except `{PRODUCT_INIT}-production-immutable` include this component.

ifdef::PAM[]
By default, the `{PRODUCT_INIT}-production-immutable` environment does not include {CENTRAL} Monitoring. To include {CENTRAL} Monitoring in this environment, you must set the number of replicas for the {CENTRAL} Monitoring pod in the *Replicas* field or make any other change to the {CENTRAL} configuration fields.
endif::PAM[]
ifdef::DM[]
Do not change these settings for the `{PRODUCT_INIT}-production-immutable` environment, as this environment does not include {CENTRAL} or {CENTRAL} Monitoring.
endif::DM[]

.Prerequisites

* You completed basic configuration of a {PRODUCT} environment using {operator_name} in the installer wizard according to the instructions in xref:operator-deploy-basic-proc_{context}[].
* If you want to use RH-SSO or LDAP for authentication, you completed security configuration according to the instructions in xref:operator-deploy-security-proc_{context}[].

.Procedure
. If the *Installation* or *Security* tab is open, click *Next* until you view the *Console* tab.
. If you created the secret for {CENTRAL} according to the instructions in <<secrets-central-create-proc_{context}>>, enter the name of the secret in the *Keystore secret* field.
. Optional: If you want to use a custom image for the {CENTRAL} deployment, complete the following additional steps:
.. Set the custom registry in the *Installation* tab. If you do not set the custom registry, the installation uses the default Red Hat registry. For more information about setting the custom registry value, see xref:operator-deploy-basic-proc_{context}[].
.. In the *Console* tab, set the following fields:
**** *Image context*: The context of the image in the registry.
**** *Image*: The name of the image.
**** *Image tag*: The tag of the image. If you do not set this field, the installation uses the `latest` tag.
+
For example, if the full address of the image is `registry.example.com/mycontext/mycentral:1.0-SNAPSHOT`, set the custom registry to `registry.example.com`, the *Image context* field to `mycontext`, the *Image* field to `mycentral`, and the *Image tag* field to `1.0-SNAPSHOT`.
+
. Optional: To set a custom hostname for the external route, enter a domain in the *Custom hostname to be used on the {CENTRAL} external Route* field, formatted as in the following example:
+
----
`businesscentral.example.com`
----
+
[NOTE]
====
The custom hostname must be valid and resolvable.

To change the custom hostname, you can modify the `routeHostname` property.
====
+
. Optional: To enable and set the Edge termination route, complete the following steps:
.. Under *Change route termination*, select *Enable Edge termination*.
.. Optional: In the *Key* field, enter the private key.
.. Optional: In the *Certificate* field, enter the certificate.
.. Optional: In the *CaCertificate* field, enter the CaCertificate.
+
. Optional: Configure Git hooks.
+
In an authoring environment, you can use Git hooks to facilitate interaction between the internal Git repository of {CENTRAL} and an external Git repository. If you want to use Git hooks, you must prepare a Git hooks directory in an OpenShift configuration map, secret, or persistent volume claim object in the project namespace. You can also prepare a secret with the SSH key and known hosts files for Git SSH authentication. For instructions about preparing Git hooks, see xref:githooks-prepare-proc_{context}[].
+
To use a Git hooks directory, make the following changes:
+
.. Under *GitHooks*, in the *Mount path* field, enter a fully qualified path for the directory, for example, `/opt/kie/data/git/hooks`.
.. In the fields under *GitHooks Configuration object*, select the *Kind* of the object that provides the file (`ConfigMap`, `Secret`, or `PersistentVolumeClaim`) and enter the *Name* of the object. This object is automatically mounted on the {CENTRAL} pods in the path that you specified for the Git hooks directory.
. Optional: In the *SSH secret* field enter the name of the secret with the SSH key and known hosts files.
. Optional: To configure {KIE_SERVER} for decision management only capabilities so that jBPM and case management features are disabled, select *Execute Kie Server only with Decisions capabilities*.
. Optional: Enter the number of replicas for {CENTRAL} or {CENTRAL} monitoring in the *Replicas* field. Do not change this number in a `{PRODUCT_INIT}-authoring` environment.
. Optional: To set the {CENTRAL} persistent volume size `pvSize`, on the *Console component* page, enter the desired size in the *Persistent Volume Size* field. The default size is 1Gi for {CENTRAL} and 64Mb for {CENTRAL} Monitoring.
. Optional: Enter requested and maximum CPU and memory limits in the fields under *Resource quotas*.
. If you want to customize the configuration of the Java virtual machine on the {CENTRAL} pods, select the *Enable JVM configuration* box and then enter information in any of the fields under *Enable JVM configuration*. All fields are optional. For the JVM parameters that you can configure, see <<jvm-settings-ref_{context}>>.
. If you selected RH-SSO authentication, configure RH-SSO for {CENTRAL}:
.. Enter the client name in the *Client name* field and the client secret in the *Client secret* field. If a client with this name does not exist, the deployment attempts to create a new client with this name and secret.
.. If the deployment is to create a new client, enter the HTTP and HTTPS URLs that will be used for accessing {CENTRAL} into the *SSO HTTP URL* and *SSO HTTPS URL* fields. This information is recorded in the client.
. Optional: If you are configuring a high-availability environment, set the user name and password for the DataGrid component in the *DataGrid username* and *DataGrid password* fields. By default, the user name is `infinispan` and the password is generated automatically.
. Optional: Depending on your needs, set environment variables. To set an environment variable, click *Add new Environment variable*, then enter the name and value for the variable in the *Name* and *Value* fields.
ifdef::PAM[]
** In a `rhpam-production` or `rhpam-production-immutable` environment, if you want {CENTRAL} Monitoring to run in a simplified mode that does not use a file system, set the `ORG_APPFORMER_SIMPLIFIED_MONITORING_ENABLED` to `true`.
+
In the simplified mode, {CENTRAL} Monitoring does not require a persistent volume claim. You can use this mode in environments that do not support `ReadWriteMany` access to persistent storage. You can not use {CENTRAL} Monitoring in the simplified mode to design custom dashboards.
+
endif::PAM[]
** Optional: If you want to configure the proxy settings, use the following environment variables:
*** `https_proxy`: The location of the https proxy. This takes precedence over `HTTPS_PROXY`, `http_proxy`, and `HTTP_PROXY`, and is used for both Maven builds and Java runtime. For example: `myuser:mypass@127.0.0.1:8080`.
*** `HTTPS_PROXY`: The location of the https proxy. This takes precedence over `http_proxy` and `HTTP_PROXY`, and is used for both Maven builds and Java runtime. For example: `myuser@127.0.0.1:8080`.
*** `http_proxy`: The location of the http proxy. This takes precedence over `HTTP_PROXY` and is used for both Maven builds and Java runtime. For example: `http://127.0.0.1:8080`.
*** `HTTP_PROXY`: The location of the http proxy. This is used for both Maven builds and Java runtime. For example: `127.0.0.1:8080`.
*** `no_proxy`: A comma separated lists of hosts, IP addresses, or domains that can be accessed directly. This takes precedence over `NO_PROXY` and is used for both Maven builds and Java runtime. For example: `*.example.com`.
*** `NO_PROXY`: A comma separated lists of hosts, IP addresses, or domains that can be accessed directly. This is used for both Maven builds and Java runtime. For example: `foo.example.com,bar.example.com`.
+
** If you want to use an external Maven repository, set the following variables:
*** `MAVEN_REPO_URL`: The URL for the Maven repository
*** `MAVEN_REPO_ID`: An identifier for the Maven repository, for example, `repo-custom`
*** `MAVEN_REPO_USERNAME`: The user name for the Maven repository
*** `MAVEN_REPO_PASSWORD` The password for the Maven repository
+
[IMPORTANT]
====
In an authoring environment, if you want {CENTRAL} to push a project into an external Maven repository, you must configure this repository during deployment and also configure exporting to the repository in every project. For information about exporting {CENTRAL} projects to an external Maven repository, see {URL_DEPLOYING_AND_MANAGING_SERVICES}#maven-external-export-proc_packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].
====
+
** If your OpenShift environment does not have a connection to the public Internet, configure access to a Maven mirror that you set up according to <<offline-repo-proc_{context}>>. Set the following variables:
*** `MAVEN_MIRROR_URL`: The URL for the Maven mirror repository that you set up in <<offline-repo-proc_{context}>>. This URL must be accessible from a pod in your OpenShift environment.
*** `MAVEN_MIRROR_OF`: The value that determines which artifacts are to be retrieved from the mirror. For instructions about setting the `mirrorOf` value, see https://maven.apache.org/guides/mini/guide-mirror-settings.html[Mirror Settings] in the Apache Maven documentation. The default value is `external:*`. With this value, Maven retrieves every required artifact from the mirror and does not query any other repositories.
+
If you configure an external Maven repository (`MAVEN_REPO_URL`), change `MAVEN_MIRROR_OF` to exclude the artifacts in this repository from the mirror, for example, `external:*,!repo-custom`. Replace `repo-custom` with the ID that you configured in `MAVEN_REPO_ID`.
+
If your authoring environment uses a built-in {CENTRAL} Maven repository, change `MAVEN_MIRROR_OF` to exclude the artifacts in this repository from the mirror: `external:*,!repo-{PRODUCT_INIT}centr`.
+
** In some cases, you might want to persist the Maven repository cache for {CENTRAL}. By default, the cache is not persisted, so when you restart or scale a {CENTRAL} pod, all Maven artifacts are downloaded again and all projects within {CENTRAL} must be built again. If you enable persistence for the cache, the download is not necessary and startup time can improve in some situations. However, significant additional space on the {CENTRAL} persistence volume is required.
+
To enable persistence for the Maven repository cache, set the `KIE_PERSIST_MAVEN_REPO` environment variable to `true`.
+
If you set `KIE_PERSIST_MAVEN_REPO` to `true`, you can optionally set a custom path for the cache using the `KIE_M2_REPO_DIR` variable. The default path is `/opt/kie/data/m2`. Files in the `/opt/kie/data` directory tree are persisted.

.Next steps

If you want to deploy the environment with the default configuration of
ifdef::PAM[]
{KIE_SERVERS}, without Smart Router, and without Process Instance Migration,
endif::PAM[]
ifdef::DM[]
{KIE_SERVERS},
endif::DM[]
click *Finish* and then click *Deploy* to deploy the environment. Otherwise, continue to set configuration parameters for
ifdef::PAM[]
{KIE_SERVERS} and Smart Router.
endif::PAM[]
ifdef::DM[]
{KIE_SERVERS}.
endif::DM[]
