[id='operator-deploy-security-proc']
= Setting the security configuration of the environment

After you set the basic configuration of a {PRODUCT} environment using {operator_name}, you can optionally configure authentication (security) settings for the environment.

.Prerequisites

* You completed basic configuration of a {PRODUCT} environment using {operator_name} in the installer wizard according to the instructions in <<operator-deploy-basic-proc>>.
* If you want to use RH-SSO or LDAP for authentication, you created users with the correct roles in your authentication system. You must create at least the following users:
** An administrative user (for example, `adminUser`) with the `kie-server,rest-all,admin` roles
** A user named `controllerUser` with the `kie-server,rest-all,guest` roles.
** A user named `executionUser` with the `kie-server,rest-all,guest` roles.
* If you want to use RH-SSO authentication, you created the clients in your RH-SSO system for all components of your environment, specifying the correct URLs. This action ensures maximum control. Alternatively, the deployment can create the clients.

.Procedure
. If the *Installation* tab is open, click *Next* to view the *Security* tab.
. In the *Authentication mode* list, select one of the following modes:
** `Internal`: You configure the initial users when deploying the environment. The user can use {CENTRAL} to set up other users as necessary.
** `RH-SSO`: {PRODUCT} uses Red Hat Single Sign-On for authentication.
** `LDAP`: {PRODUCT} uses LDAP for authentication
. Complete the security configuration based on the *Authentication mode* that you selected.
+
--
If you selected `Internal`, you can optionally set the *KIE Server password* field. Applications can use the `executionUser` user name with this password to send REST API requests to {KIE_SERVERS} in this environment.

If you selected `RH-SSO`, configure RH-SSO authentication:

.. In the *RH-SSO URL* field, enter the RH-SSO URL.
.. In the *Realm* field, enter the RH-SSO realm name.
.. If you did not create RH-SSO clients for components of your environment enter the credentials of an administrative user for your RH-SSO system in the *SSO admin user* and *SSO admin password* fields.
.. If your RH-SSO system does not have a proper signed SSL certificate, select the *Disable SSL cert validation* box.
.. If you want to change the RH-SSO principal attribute used for the user name, in the *Principal attribute* field enter the name of the new attribute.
.. In the *Controller password* field, enter the password that you configured in RH-SSO for the `controllerUser` user.
.. In the *KIE Server password* field, enter the password that you configured in RH-SSO for the `executionUser` user.

If you selected `LDAP`, configure LDAP authentication:

.. In the *LDAP URL* field, enter the LDAP URL.
.. Configure LDAP parameters that correspond to the settings of the LdapExtended Login module of {EAP}. For instructions about using these settings, see https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html-single/login_module_reference/#ldapextended_login_module[LdapExtended Login Module].
.. In the *Controller password* field, enter the password that you configured in LDAP for the `controllerUser` user.
.. In the *KIE Server password* field, enter the password that you configured in LDAP for the `executionUser` user.
--
. Configure other passwords, if necessary:
** *AMQ password* and *AMQ cluster password* are passwords for interaction with ActiveMQ using the JMS API.
** *Maven password* is the password for `mavenUser`. If your environment includes {CENTRAL}, you can use this user to access the built-in Maven repository.
** *Keystore password* is the password for the keystore files used in secrets for HTTPS communication. Set this password if you created secrets according to instructions in <<secrets-kie-create-proc>> or <<secrets-central-create-proc>>.
** *Database password* is the password for database server pods that are a part of the environments.
//. If your RH-SSO or LDAP system does not define all the roles required for your deployment, you can map authentication system roles to {PRODUCT} roles. To enable role mapping, enter the fully qualified path name of a file that defines role mapping, for example, `/opt/eap/standalone/configuration/rolemapping/rolemapping.properties`, in the *Roles properties file* field. You must provide this file and mount it at this path in all applicable deployment configurations; for instructions, see <<rolemapping-proc>>.
//+
//By default, both the roles that you define in the mapping file and the roles defined in the authentication system are used. If you want to replace roles defined in the authentication system with roles that you define in the mapping file, select the *Replace roles* box.

.Next steps

If you want to deploy the environment with the default configuration of all components, click *Finish* and then click *Deploy* to deploy the environment. Otherwise, continue to set configuration parameters for {CENTRAL}, {KIE_SERVERS}, and Smart Router.
