[id='secrets-kie-create-proc']
= Creating the secrets for {KIE_SERVER}

OpenShift uses objects called `Secrets` to hold sensitive information, such as passwords or keystores. See the https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/developer_guide/dev-guide-secrets[Secrets chapter] in the OpenShift documentation for more information.

ifeval::["{context}"!="openshift-ansible-playbook"]
You must create an SSL certificate for {KIE_SERVER} and provide it to your OpenShift environment as a secret.
endif::[]
ifeval::["{context}"=="openshift-ansible-playbook"]
{KIE_SERVER} uses an SSL certificate to provide HTTPS access. The deployment can create a sample secret automatically. However, in production environments you must create an SSL certificate for {KIE_SERVER} and provide it to your OpenShift environment as a secret.
endif::[]

ifeval::["{context}"=="openshift-immutable"]
ifdef::DM[]
NOTE: You do not need to create the secrets object if you are planning to deploy only {KIE_SERVERS} without support for HTTPS.
endif::DM[]
endif::[]

.Procedure
. Generate an SSL keystore with a private and public key for SSL encryption for {KIE_SERVER}. In a production environment, generate a valid signed certificate that matches the expected URL of the {KIE_SERVER}. Save the keystore in a file named `keystore.jks`. Record the name of the certificate and the password of the keystore file. 
+
See https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.1/html-single/Security_Guide/index.html#Generate_a_SSL_Encryption_Key_and_Certificate[Generate a SSL Encryption Key and Certificate] for more information on how to create a keystore with self-signed or purchased SSL certificates.
+
. Use the `oc` command to generate a secret named `kieserver-app-secret` from the new keystore file:
+
[subs="attributes,verbatim,macros"]
----
$ oc create secret generic kieserver-app-secret --from-file=keystore.jks
----
