[id='secrets-central-create-proc']
= Creating the secrets for {CENTRAL}

:CAN_AUTOCREATE!:
ifeval::["{context}"!="openshift-ansible-playbook"]
:CAN_AUTOCREATE:
endif::[]
ifeval::["{context}"!="openshift-operator"]
:CAN_AUTOCREATE:
endif::[]

If you are planning to deploy {CENTRAL}
ifdef::PAM[]
or {CENTRAL} Monitoring
endif::PAM[]
in your OpenShift environment, 
ifndef::CAN_AUTOCREATE[]
you must create an SSL certificate for {CENTRAL} and provide it to your OpenShift environment as a secret.
endif::CAN_AUTOCREATE[]
ifdef::CAN_AUTOCREATE[]
note that this component uses an SSL certificate to provide HTTPS access. The deployment can create a sample secret automatically. However, in production environments you must create an SSL certificate for {CENTRAL} and provide it to your OpenShift environment as a secret.
endif::CAN_AUTOCREATE[]
Do not use the same certificate and keystore for {CENTRAL} and {KIE_SERVER}.

.Procedure
. Generate an SSL keystore with a private and public key for SSL encryption for {CENTRAL}. In a production environment, generate a valid signed certificate that matches the expected URL of the {CENTRAL}. Save the keystore in a file named `keystore.jks`. Record the name of the certificate and the password of the keystore file.
+
For more information on how to create a keystore with self-signed or purchased SSL certificates, see https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.1/html-single/Security_Guide/index.html#Generate_a_SSL_Encryption_Key_and_Certificate[Generate a SSL Encryption Key and Certificate].
+
. Use the `oc` command to generate a secret named `{CENTRAL_ONEWORD}-app-secret` from the new keystore file:
+
[subs="attributes,verbatim,macros"]
----
$ oc create secret generic {CENTRAL_ONEWORD}-app-secret --from-file=keystore.jks
----
