[id='secrets-employeerostering-create-proc']
= Creating the secrets for Employee Rostering

You must create an SSL certificate for HTTPS access to the Employee Rostering application and provide it to your OpenShift environment as a secret.

.Procedure
. Generate an SSL keystore with a private and public key for SSL encryption for the Employee Rostering application. In a production environment, generate a valid signed certificate that matches the expected URL of the application. Save the keystore in a file named `keystore.jks`. Record the name of the certificate and the password of the keystore file.
+
See https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.1/html-single/Security_Guide/index.html#Generate_a_SSL_Encryption_Key_and_Certificate[Generate a SSL Encryption Key and Certificate] for more information on how to create a keystore with self-signed or purchased SSL certificates.
+
. Use the `oc` command to generate a secret named `optaweb-employee-rostering-app-secret` from the new keystore file:
+
[subs="attributes,verbatim,macros"]
----
$ oc create secret generic optaweb-employee-rostering-app-secret --from-file=keystore.jks
----
