[id='secrets-{secrettarget}-create-proc']
ifeval::["{secrettarget}"=="kie"]
:secrettarget_verbose: {KIE_SERVER}
:appsecret_name: kieserver-app-secret
endif::[]
ifeval::["{secrettarget}"=="central"]
:secrettarget_verbose: {CENTRAL}
:appsecret_name: {CENTRAL_ONEWORD}-app-secret
endif::[]
ifeval::["{secrettarget}"=="smartrouter"]
:secrettarget_verbose: Smart Router
:appsecret_name: smartrouter-app-secret
endif::[]
ifeval::["{secrettarget}"=="employeerostering"]
:secrettarget_verbose: the Employee Rostering application
:appsecret_name: optaweb-employee-rostering-app-secret
endif::[]
ifeval::["{secrettarget}"=="amq"]
:secrettarget_verbose: the AMQ broker connection
:appsecret_name: broker-app-secret
endif::[]

:CAN_AUTOCREATE!:
:OPENSHIFT4!:
ifeval::["{context}"=="openshift-ansible-playbook"]
:CAN_AUTOCREATE:
endif::[]
ifeval::["{context}"=="openshift-operator"]
:CAN_AUTOCREATE:
:OPENSHIFT4:
endif::[]
ifeval::["{secrettarget}"=="amq"]
:CAN_AUTOCREATE!:
endif::[]


= Creating the secrets for {secrettarget_verbose}

ifeval::["{secrettarget}"=="kie"]
OpenShift uses objects called _secrets_ to hold sensitive information such as passwords or keystores. For more information about OpenShift secrets, see
ifdef::OPENSHIFT4[] 
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/builds/creating-build-inputs#builds-secrets-overview_creating-build-inputs[What is a secret] 
endif::OPENSHIFT4[] 
ifndef::OPENSHIFT4[] 
the https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/developer_guide/dev-guide-secrets[Secrets chapter]
endif::OPENSHIFT4[] 
in the OpenShift documentation.
endif::[]

ifeval::["{secrettarget}"=="amq"]
If you want to connect any {KIE_SERVER} to an AMQ broker and to use SSL for the AMQ broker connection, you must create an SSL certificate for the connection and provide it to your OpenShift environment as a secret.
endif::[]
ifeval::["{secrettarget}"!="amq"]
ifndef::CAN_AUTOCREATE[]
You must create an SSL certificate for HTTP access to {secrettarget_verbose} and provide it to your OpenShift environment as a secret.
endif::CAN_AUTOCREATE[]
ifdef::CAN_AUTOCREATE[]
In order to provide HTTPS access, {secrettarget_verbose} uses an SSL certificate. The deployment can create a sample secret automatically. However, in production environments you must create an SSL certificate for {secrettarget_verbose} and provide it to your OpenShift environment as a secret.
endif::CAN_AUTOCREATE[]

ifeval::["{secrettarget}"=="central"]
Do not use the same certificate and keystore for {CENTRAL} and {KIE_SERVER}.
endif::[]
ifeval::["{secrettarget}"=="smartrouter"]
Do not use the same certificate and keystore for Smart Router as the ones used for {KIE_SERVER} or {CENTRAL}.
endif::[]
endif::[]


.Procedure
. Generate an SSL keystore with a private and public key for SSL encryption for {KIE_SERVER}. For more information on how to create a keystore with self-signed or purchased SSL certificates, see https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.1/html-single/Security_Guide/index.html#Generate_a_SSL_Encryption_Key_and_Certificate[Generate a SSL Encryption Key and Certificate].
+
[NOTE]
====
In a production environment, generate a valid signed certificate that matches the expected URL for {secrettarget_verbose}. 
====
+
. Save the keystore in a file named `keystore.jks`. 
. Record the name of the certificate. The default value for this name in {PRODUCT} configuration is `jboss`.
. Record the password of the keystore file. The default value for this name in {PRODUCT} configuration is `mykeystorepass`. 
. Use the `oc` command to generate a secret named `{appsecret_name}` from the new keystore file:
+
[subs="attributes,verbatim,macros"]
----
$ oc create secret generic {appsecret_name} --from-file=keystore.jks
----
