[id='secret-adminuser-create-proc_{context}']
:INCLUDECENTRAL: {CENTRAL}
ifdef::PAM[]
:INCLUDECENTRAL: {CENTRAL} or {CENTRAL} Monitoring
endif::PAM[]

= Creating the secret for the administrative user

You must create a generic secret that contains the user name and password for a {PRODUCT} administrative user account. This secret is required for deploying {PRODUCT} using any template except the trial template.

The secret must contain the user name and password as literals. The key name for the user name is `KIE_ADMIN_USER`. The key name for the password is `KIE_ADMIN_PWD`.

If you are using multiple templates to deploy components of {PRODUCT}, use the same secret for all these deployments. The components utilize this user account to communicate with each other.

If your environment includes {INCLUDECENTRAL}, you can also use this user account to log in to {INCLUDECENTRAL}.

[IMPORTANT]
====
If you use RH-SSO or LDAP authentication, the same user with the same password must be configured in your authentication system with the `kie-server,rest-all,admin` roles for {PRODUCT}.
====

.Procedure

// the name is rhpam-credentials even for RHDM - this is the example value used in templates
Use the `oc` command to generate a generic secret named `kie-admin-user-secret` from the user name and password:

[subs="attributes,verbatim,macros"]
----
$ oc create secret generic rhpam-credentials --from-literal=KIE_ADMIN_USER=adminUser --from-literal=KIE_ADMIN_PWD=adminPassword
----

In this command, replace _adminPassword_ with the password for the administrative user. Optionally, you can replace _adminUser_ with another user name for the administrative user.
