[id='server-immutable-kjar-deploy-assy']
= Deploying an immutable {KIE_SERVER} from KJAR services

ifdef::context[:parent-context: {context}]
:context: server-immutable-kjar
ifdef::PAM[]
:LOCAL_CENTRAL: {CENTRAL} or {CENTRAL} Monitoring
endif::PAM[]
ifdef::DM[]
:LOCAL_CENTRAL: {CENTRAL}
endif::DM[]
:what_deploying: an immutable {KIE_SERVER} from KJAR services
:what_deploying_brief: an immutable {KIE_SERVER} from KJAR services

You can deploy an immutable {KIE_SERVER} using services that are already built as KJAR files.

You must provide the services in a Maven repository. You can use the built-in repository of the {CENTRAL} or your own repository (for example, a Nexus deployment). When the server pod starts, it retrieves the KJAR services from the Maven repository. Services on the pod are never updated or changed. At every restart or scaling of the pod, the server retrieves the files from the repository, so you must ensure they do not change on the Maven repository to keep the deployment immutable.

You cannot deploy or undeploy services on a running immutable {KIE_SERVER}. You can use {LOCAL_CENTRAL} to view monitoring information. The {KIE_SERVER} runs like any other pod on the OpenShift environment; you can use any container-based integration workflows as necessary.

ifdef::PAM[]
By default, this server uses a PostgreSQL database server in a pod. To use a MySQL database server in a pod or an external database server, you can modify the template.
endif::PAM[]

If a {LOCAL_CENTRAL} is deployed in the same namespace, it discovers the immutable {KIE_SERVER} automatically. You can use {LOCAL_CENTRAL} to start and stop (but not deploy) services on the immutable {KIE_SERVER} and to view monitoring data.

include::template-deploy-start-proc.adoc[leveloffset=+1]
include::template-deploy-mandatory-proc.adoc[leveloffset=+1]
include::template-deploy-namespace-proc.adoc[leveloffset=+1]
include::template-deploy-connectcentral-proc.adoc[leveloffset=+1]
include::template-deploy-nopubnet-proc.adoc[leveloffset=+1]
include::template-deploy-rhsso-proc.adoc[leveloffset=+1]
include::template-deploy-ldap-proc.adoc[leveloffset=+1]
ifdef::PAM[]
include::template-deploy-externaldb-proc.adoc[leveloffset=+1]
endif::PAM[]
include::template-deploy-prometheus-proc.adoc[leveloffset=+1]
include::template-deploy-complete-proc.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
