[id='server-immutable-s2i-deploy-assy']
= Deploying an immutable {KIE_SERVER} using an S2I build

ifdef::context[:parent-context: {context}]
:context: server-immutable-s2i
:what_deploying: an immutable {KIE_SERVER} using an S2I build
:what_deploying_brief: an immutable {KIE_SERVER} using S2I
ifdef::PAM[]
:LOCAL_CENTRAL: {CENTRAL} or {CENTRAL} Monitoring
endif::PAM[]
ifdef::DM[]
:LOCAL_CENTRAL: {CENTRAL}
endif::DM[]

You can deploy an immutable {KIE_SERVER} using an S2I build. When you deploy the server, the deployment procedure retrieves the source code for any services that must run on this server, builds the services, and includes them in the server image.

You cannot deploy or undeploy services on a running immutable {KIE_SERVER}. You can use {LOCAL_CENTRAL} to view monitoring information. The {KIE_SERVER} runs like any other pod on the OpenShift environment; you can use any container-based integration workflows as necessary.

You can enable JMS capabilities of the immutable {KIE_SERVER}. With JMS capabilities you can interact with the server through JMS API using an external AMQ message broker.

ifdef::PAM[]
By default, this server uses a PostgreSQL database server in a pod. To use a MySQL database server in a pod or an external database server, you can modify the template.
endif::PAM[]

If a {LOCAL_CENTRAL} is deployed in the same namespace, it discovers the immutable {KIE_SERVER} automatically. You can use {LOCAL_CENTRAL} to start and stop (but not deploy) services on the immutable 
ifdef::PAM[]
{KIE_SERVER} and to view monitoring data.
endif::PAM[]
ifdef::DM[]
{KIE_SERVER}.
endif::DM[]

include::template-deploy-start-proc.adoc[leveloffset=+1]
include::template-deploy-mandatory-proc.adoc[leveloffset=+1]
include::template-deploy-namespace-proc.adoc[leveloffset=+1]
include::template-deploy-connectcentral-proc.adoc[leveloffset=+1]
include::template-deploy-optionalmaven-proc.adoc[leveloffset=+1]
include::template-deploy-nopubnet-proc.adoc[leveloffset=+1]
include::template-deploy-amq-proc.adoc[leveloffset=+1]
include::template-deploy-rhsso-proc.adoc[leveloffset=+1]
include::template-deploy-ldap-proc.adoc[leveloffset=+1]
ifdef::PAM[]
include::template-deploy-externaldb-proc.adoc[leveloffset=+1]
endif::PAM[]
include::template-deploy-prometheus-proc.adoc[leveloffset=+1]
include::template-deploy-complete-proc.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
