[id='startupstrategy-enable-proc']
= Enabling the `OpenShiftStartupStrategy` setting to connect additional {KIE_SERVERS} to {CENTRAL}

In an environment deployed using {PRODUCT} authoring templates, {CENTRAL} manages one {KIE_SERVER}.  
ifdef::PAM[]
If you use the high-avalability authoring template or if you modified the single authoring template to use a database server other than an embedded H2 database, you
endif::PAM[]
ifdef::DM[]
You
endif::DM[]
can scale the {KIE_SERVER} pod, but all the copies execute the same services.

You can connect additional {KIE_SERVERS} to {CENTRAL}. However, if you deployed a single authoring environment using the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring.yaml`, you must enable the `OpenShiftStartupStrategy` setting in the environment. When `OpenShiftStartupStrategy` is enabled, {CENTRAL} automatically discovers {KIE_SERVERS} in the same namespace and these {KIE_SERVERS} can be configured to connect to the {CENTRAL}.

With the `OpenShiftStartupStrategy` setting, when a user deploys a service to the {KIE_SERVER}, the {KIE_SERVER} deployment is rolled out again. Users can not deploy another service to the same {KIE_SERVER} until the roll-out completes. Because the roll-out might take noticeable time, the `OpenShiftStartupStrategy` setting might not be suitable for some authoring environments. 

Do not complete this procedure if you deployed a high-availability authoring environment using the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring-ha.yaml` template. In this environment, the `OpenShiftStartupStrategy` setting is enabled by default.

Do not complete this procedure unless you want to connect additional {KIE_SERVERS} to {CENTRAL}.

[NOTE]
====
In {PRODUCT} version 7.7.0 only, the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring-ha.yaml` template did not enable the `OpenShiftStartupStrategy` setting. If you deployed this version, you must complete this procedure to enable the `OpenShiftStartupStrategy` setting. The high-availability authoring environment requires this setting for the stable operation of a single {KIE_SERVER} or of multiple {KIE_SERVERS}.
====


.Prerequisites

* You deployed an authoring environment using the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring.yaml` template. Alternatively, you deployed an authoring environment using the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring-ha.yaml` template in {PRODUCT} version 7.7.0 only.
* You are logged in to the OpenShift project where the environment is deployed using the `oc` tool.

.Procedure

. Enter the following command to view the deployment configurations that are deployed in the project:
+
[subs="attributes,verbatim,macros"]
----
$ oc get dc
----
+
. In the output of the command, find the deployment configuration names for the {CENTRAL} and {KIE_SERVER} pods:
** The name of the deployment configuration for {CENTRAL} is `__myapp__-{PRODUCT_INIT}centr`. Replace `__myapp__` with the application name of the environment, which is set in the `APPLICATION_NAME` parameter of the template.
** The name of the deployment configuration for {KIE_SERVER} is `__myapp__-kieserver`. Replace `__myapp__` with the application name.
+
. Enter the following commands to enable the `OpenShiftStartupStrategy` setting on the pods:
+
[subs="attributes,verbatim,macros,quotes"]
----
$ oc env __myapp__-{PRODUCT_INIT}centr KIE_SERVER_CONTROLLER_OPENSHIFT_ENABLED=true
$ oc env __myapp__-kieserver KIE_SERVER_STARTUP_STRATEGY=OpenShiftStartupStrategy
----
+
In these commands, replace `__myapp__-{PRODUCT_INIT}centr` with the {CENTRAL} deployment configuration name and `__myapp__-kieserver` with the {KIE_SERVER} deployment configuration name.
. When you enable the `OpenShiftStartupStrategy` setting, by default {CENTRAL} discovers only {KIE_SERVERS} that are deployed with the same value of the `APPLICATION_NAME` parameter as the authoring template. If you want to connect {KIE_SERVERS} with any other application names to the {CENTRAL}, enter the following command:
+
[subs="attributes,verbatim,macros,quotes"]
----
$ oc env __myapp__-{PRODUCT_INIT}centr KIE_SERVER_CONTROLLER_OPENSHIFT_GLOBAL_DISCOVERY_ENABLED=true
----
+
In this command, replace `__myapp__-{PRODUCT_INIT}centr` with the {CENTRAL} deployment configuration name.


