[id='template-deploy-start-multi-{context}-proc']
:startlink: <<template-deploy-start-multi-{context}-proc>>
= Starting configuration of the template for {what_deploying_brief}
:template_add_params: 
ifeval::["{context}"=="freeform-server-managed"]
:template_add_params: -p KIE_SERVER_STARTUP_STRATEGY=OpenShiftStartupStrategy
To deploy a managed {KIE_SERVER} for a freeform environment, 
endif::[]
use one of the following template files:

* `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-postgresql.yaml` to use a PostgreSQL pod for persistent storage. Use this template unless there is a sufficient reason to use another template.

* `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-mysql.yaml` to use a MySQL pod for persistent storage. 

* `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-externaldb.yaml` to use an external database server for persistent storage.
+
IMPORTANT: The standard {KIE_SERVER} image for an external database server includes drivers for MySQL and PostgreSQL external database servers. If you want to use another database server, you must build a custom {KIE_SERVER} image. For instructions, see <<externaldb-build-proc>>.

.Procedure

. Download the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page.

. Extract the required template file.

. Use one of the following methods to start deploying the template:
* To use the OpenShift Web UI, in the OpenShift application console select *Add to Project -> Import YAML / JSON* and then select or paste the required template file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
* To use the OpenShift command line console, prepare the following command line:
+
[subs="attributes,verbatim,macros"]
----
oc new-app -f <template-path>/<template-file-name>.yaml -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret {template_add_params}
----
+
In this command line, make the following changes:
+
** Replace `<template-path>` with the path to the downloaded template file.
** Replace `<template-file-name>` with the name of the template file.
** Use as many `-p PARAMETER=value` pairs as needed to set the required parameters. 

.Next steps

Set the parameters for the template. Follow the steps in <<template-deploy-mandatory-{context}-proc>> to set common parameters. You can view the template file to see descriptions for all parameters.
