[id='template-deploy-nopubnet-{context}-proc']
= Configuring access to a Maven mirror in an environment without a connection to the public Internet for {what_deploying_brief}

When configuring the template to deploy {what_deploying}, if your OpenShift environment does not have a connection to the public Internet, you must configure access to a Maven mirror that you set up according to <<offline-repo-proc>>.

.Prerequisite

You started the configuration of the template, as described in {startlink}.

.Procedure

To configure access to the Maven mirror, set the following parameters:

** *Maven mirror URL* (`MAVEN_MIRROR_URL`): The URL for the Maven mirror repository that you set up in <<offline-repo-proc>>. This URL must be accessible from a pod in your OpenShift environment.
** *Maven mirror of* (`MAVEN_MIRROR_OF`): The value that determines which artifacts are to be retrieved from the mirror. For instructions about setting the `mirrorOf` value, see https://maven.apache.org/guides/mini/guide-mirror-settings.html[Mirror Settings] in the Apache Maven documentation. The default value is `external:*`. With this value, Maven retrieves every required artifact from the mirror and does not query any other repositories.
+
*** If you configure an external Maven repository (`MAVEN_REPO_URL`), change `MAVEN_MIRROR_OF` to exclude the artifacts in this repository from the mirror, for example, `external:*,!repo-custom`. Replace `repo-custom` with the ID that you configured in `MAVEN_REPO_ID`. 
*** If you configure a built-in {CENTRAL} Maven repository (`BUSINESS_CENTRAL_MAVEN_SERVICE`), change `MAVEN_MIRROR_OF` to exclude the artifacts in this repository from the mirror: `external:*,!repo-{PRODUCT_INIT}centr`. 
*** If you configure both repositories, change `MAVEN_MIRROR_OF` to exclude the artifacts in both repositories from the mirror: `external:*,!repo-{PRODUCT_INIT}centr,!repo-custom`. Replace `repo-custom` with the ID that you configured in `MAVEN_REPO_ID`. 

.Next steps

If necessary, set additional parameters. 

To complete the deployment, follow the procedure in <<template-deploy-complete-{context}-proc>>.
