[id='template-deploy-connectcentral-{context}-proc']
= Configuring information about a {LOCAL_CENTRAL} instance for {what_deploying_brief}


:central_monitor_maven!:
ifeval::["{context}"=="server-immutable-kjar"]
:central_monitor_maven:
endif::[]
ifeval::["{context}"=="freeform-server-managed"]
:central_monitor_maven:
To enable a connection from the {LOCAL_CENTRAL} instance that you deployed to the {KIE_SERVER},
endif::[]
ifeval::["{context}"!="freeform-server-managed"]
If you want to enable a connection from a {LOCAL_CENTRAL} instance in the same namespace to the {KIE_SERVER},
endif::[]
you must configure information about the {LOCAL_CENTRAL} instance.


.Prerequisites

* You started the configuration of the template, as described in {startlink}.

.Procedure

. Set the following parameters:
* *Name of the {CENTRAL} service* (`{CENTRAL_CAPITAL_UNDER}_SERVICE`): The OpenShift service name for the {LOCAL_CENTRAL}.
ifeval::["{context}"=="additional-server-managed"]
+
. Configure access to the Maven repository from which the server must load services. You must configure the same repository that the {LOCAL_CENTRAL} uses.
** If the {LOCAL_CENTRAL} uses its own built-in repository, set the following parameters:
*** *Name of the Maven service hosted by {CENTRAL}* (`{CENTRAL_CAPITAL_UNDER}_MAVEN_SERVICE`): The OpenShift service name for the {LOCAL_CENTRAL}.
*** *Username for the Maven service hosted by {CENTRAL}* (`{CENTRAL_CAPITAL_UNDER}_MAVEN_USERNAME`): The user name for the built-in Maven repository of the {LOCAL_CENTRAL}. Enter the user name that you configured for the {LOCAL_CENTRAL} as `{CENTRAL_CAPITAL_UNDER}_MAVEN_USERNAME`.
*** *Password to access the Maven service hosted by {CENTRAL}* (`{CENTRAL_CAPITAL_UNDER}_MAVEN_PASSWORD`): The password for the built-in Maven repository of the {LOCAL_CENTRAL}. Enter the password that you configured for the {LOCAL_CENTRAL} as `{CENTRAL_CAPITAL_UNDER}_MAVEN_PASSWORD`.
** If you configured the {LOCAL_CENTRAL} to use an external Maven repository, set the following parameters:
*** *Maven repository URL* (`MAVEN_REPO_URL`): A URL for the external Maven repository that {LOCAL_CENTRAL} uses.
*** *Maven repository ID* (`MAVEN_REPO_ID`): An identifier for the Maven repository. The default value is `repo-custom`.
*** *Maven repository username* (`MAVEN_REPO_USERNAME`): The user name for the Maven repository.
*** *Maven repository password* (`MAVEN_REPO_PASSWORD`): The password for the Maven repository.
endif::[]
ifdef::central_monitor_maven[]
. Ensure that the following settings are set to the same value as the same settings for the {LOCAL_CENTRAL}:
*** *Maven repository URL* (`MAVEN_REPO_URL`): A URL for the external Maven repository from which services must be deployed.
*** *Maven repository username* (`MAVEN_REPO_USERNAME`): The user name for the Maven repository.
*** *Maven repository password* (`MAVEN_REPO_PASSWORD`): The password for the Maven repository.
endif::central_monitor_maven[]

.Next steps

If necessary, set additional parameters.

To complete the deployment, follow the procedure in <<template-deploy-complete-{context}-proc>>.
