[id='template-deploy-externaldb-{context}-proc']
= Setting parameters for using an external database server for {what_deploying_brief}
// modifylink is an internal variable based on context
:modifylink!:

ifeval::["{context}"=="server-immutable-s2i"]
:modifylink: <<environment-immutable-modify-proc>>
endif::[]

ifeval::["{context}"=="fixed"]
:modifylink: <<environment-managed-modify-proc>>
endif::[]

ifeval::["{context}"=="authoring"]
:modifylink: <<environment-authoring-single-modify-proc>> or <<environment-authoring-ha-modify-proc>>
endif::[]



ifndef::modifylink[]
If you are using the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-externaldb.yaml` template to use an external database server for the {KIE_SERVER},
endif::modifylink[]
ifdef::modifylink[]
If you modified the template to use an external database server for the {KIE_SERVER}, as described in {modifylink},
endif::modifylink[]
complete the following additional configuration when configuring the template to deploy {what_deploying}.

.Prerequisites

* You started the configuration of the template, as described in {startlink}.

.Procedure
. Set the following parameters:
+
** *KIE Server External Database Driver* (`KIE_SERVER_EXTERNALDB_DRIVER`): The driver for the server, depending on the server type:
+
*** `mysql`
*** `postgresql`
*** `mariadb`
*** `mssql`
*** `db2`
*** `oracle`
*** `sybase`
+
** *KIE Server External Database User* (`KIE_SERVER_EXTERNALDB_USER`) and KIE Server External Database Password (`KIE_SERVER_EXTERNALDB_PWD`): The user name and password for the external database server
** *KIE Server External Database URL* (`KIE_SERVER_EXTERNALDB_URL`): The JDBC URL for the external database server
** *KIE Server External Database Host* (`KIE_SERVER_EXTERNALDB_SERVICE_HOST`) and  *KIE Server External Database Port* (`KIE_SERVER_EXTERNALDB_SERVICE_PORT`): The host name and port number of the external database server. You can set these parameters as an alternative to setting the `KIE_SERVER_EXTERNALDB_URL` parameter.
** *KIE Server External Database Dialect* (`KIE_SERVER_EXTERNALDB_DIALECT`): The Hibernate dialect for the server, depending on the server type. The common settings are:
+
*** `org.hibernate.dialect.MySQL5InnoDBDialect`
*** `org.hibernate.dialect.MySQL8Dialect` 
*** `org.hibernate.dialect.MariaDB10Dialect`
*** `org.hibernate.dialect.PostgreSQL94Dialect`
*** `org.hibernate.dialect.PostgresPlusDialect` (used for EntrepriseDB Postgres Advanced Server)
*** `org.hibernate.dialect.SQLServer2012Dialect` (used for MS SQL)
*** `org.hibernate.dialect.DB2Dialect`
*** `org.hibernate.dialect.Oracle10gDialect`
*** `org.hibernate.dialect.SybaseASE15Dialect`
+
For a complete list of supported dialects, see Table A.7 in https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html-single/developing_hibernate_applications/index#hibernate_properties[Hibernate properties] in the {EAP} documentation.
+
** *KIE Server External Database name* (`KIE_SERVER_EXTERNALDB_DB`): The database name to use on the external database server
** *JDBC Connection Checker class* (`KIE_SERVER_EXTERNALDB_CONNECTION_CHECKER`): The name of the JDBC connection checker class for the database server. Without this information, a database server connection cannot be restored after it is lost, for example, if the database server is rebooted.
** *JDBC Exception Sorter class* (`KIE_SERVER_EXTERNALDB_EXCEPTION_SORTER`): The name of the JDBC exception sorter class for the database server. Without this information, a database server connection cannot be restored after it is lost, for example, if the database server is rebooted.
+
. If you created a custom image for using an external database server, as described in <<externaldb-build-proc>>, set the following parameters:
** *Drivers Extension Image* (`EXTENSIONS_IMAGE`): The ImageStreamTag definition of the extension image, for example, `jboss-kie-db2-extension-openshift-image:11.1.4.4`
** *Drivers ImageStream Namespace* (`EXTENSIONS_IMAGE_NAMESPACE`): The namespace to which you uploaded the extension image, for example, `openshift` or your project namespace.
. If you are using a MySQL version 8 external database server, enable the `mysql_native_password` plugin and use it for authentication. For instructions about this pluding, see https://dev.mysql.com/doc/refman/8.0/en/native-pluggable-authentication.html[Native Pluggable Authentication] in the _MySQL 8.0 Reference Manual_. 
+
If you are using a MySQL version 8 image provided by Red Hat on {OPENSHIFT}, to enable the plugin, set the `MYSQL_DEFAULT_AUTHENTICATION_PLUGIN` environment variable to `mysql_native_password`.
+
If you created users on the MySQL version 8 server before enabling the `mysql_native_password` plugin, you must update the `mysql-user` table after you enable the plugin.

.Next steps

If necessary, set additional parameters.

To complete the deployment, follow the procedure in <<template-deploy-complete-{context}-proc>>.
