[id='template-deploy-optionalmaven-{context}-proc']
= Setting an optional Maven repository for {what_deploying_brief}

When configuring the template to deploy {what_deploying},
ifeval::["{context}"=="server-immutable-s2i"]
if your source build includes dependencies that are not available on the public Maven tree and require a separate custom Maven repository,
endif::[]
ifeval::["{context}"=="authoring"]
if you want to place the built KJAR files into an external Maven repository,
endif::[]
you must set parameters to access the repository.

.Prerequisites

* You started the configuration of the template, as described in {startlink}.

.Procedure

To configure access to a custom Maven repository, set the following parameters:

* *Maven repository URL* (`MAVEN_REPO_URL`): The URL for the Maven repository.
* *Maven repository ID* (`MAVEN_REPO_ID`): An identifier for the Maven repository. The default value is `repo-custom`.
* *Maven repository username* (`MAVEN_REPO_USERNAME`): The username for the Maven repository.
* *Maven repository password* (`MAVEN_REPO_PASSWORD`): The password for the Maven repository.

.Next steps

If necessary, set additional parameters.

To complete the deployment, follow the procedure in <<template-deploy-complete-{context}-proc>>.

ifeval::["{context}"=="authoring"]
[IMPORTANT]
====
To export built KJAR files from your projects in {CENTRAL} to the external Maven repository, you must also modify the `pom.xml` file in every project. For instructions about modifying the `pom.xml` file for this purpose, see {URL_DESIGNING_BUSINESS_PROCESSES}#export-project-to-maven[_{DESIGNING_BUSINESS_PROCESSES}_].
====
endif::[]
