[id='template-deploy-centralmavenpwd-{subcontext}-proc']
= Specifying credentials to access the built-in Maven repository for {what_deploying_brief}

When configuring the template to deploy {what_deploying}, if you want to use the Maven repository that is built into {CENTRAL} and to connect additional {KIE_SERVERS} to the {CENTRAL}, you must configure credentials for accessing this Maven repository. You can then use these credentials to configure the {KIE_SERVERS}.

Also, if you are configuring RH-SSO or LDAP authentication, you must set the credentials for the built-in Maven repository to a user name and password configured in RH-SSO or LDAP. This setting is required so that {KIE_SERVER} can access the Maven repository.

.Prerequisites

* You started the configuration of the template, as described in {startlink}.

.Procedure

To configure credentials for the built-in Maven repository, set the following parameters:

* *Username for the Maven service hosted by {CENTRAL}* (`{CENTRAL_CAPITAL_UNDER}_MAVEN_USERNAME`): The user name for the built-in Maven repository.
* *Password for the Maven service hosted by {CENTRAL}* (`{CENTRAL_CAPITAL_UNDER}_MAVEN_PASSWORD`): The password for the built-in Maven repository.

.Next steps

If necessary, set additional parameters.

To complete the deployment, follow the procedure in <<template-deploy-complete-{subcontext}-proc>>.
