[id='template-overview-con']
= OpenShift template reference information

{PRODUCT} provides the following OpenShift templates. To access the templates, download and extract the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat customer portal.

ifdef::PAM[]
ifeval::["{context}"=="openshift-authoring"]
* `rhpam76-authoring.yaml` provides a {CENTRAL} and a {KIE_SERVER} connected to the {CENTRAL}. The {KIE_SERVER} uses an H2 database with persistent storage. You can use this environment to author processes, services, and other business assets. For details about this template, see <<rhpam76-authoring-ref>>.

* `rhpam76-authoring-ha.yaml` provides a high-availability {CENTRAL}, a {KIE_SERVER} connected to the {CENTRAL}, and a MySQL instance that the {KIE_SERVER} uses. You can use this environment to author processes, services, and other business assets. For details about this template, see <<rhpam76-authoring-ha-ref>>.
endif::[]

ifeval::["{context}"=="openshift-managed"]
* `rhpam76-prod.yaml` provides a high-availability {CENTRAL} Monitoring instance, a Smart Router, two distinct {KIE_SERVERS} connected to the {CENTRAL} and to the Smart Router, and two PostgreSQL instances. Each {KIE_SERVER} uses its own PostgreSQL instance. You can use this environment to execute business assets in a production or staging environment. You can configure the number of replicas for each component. For details about this template, see <<rhpam76-prod-ref>>.
endif::[]

ifeval::["{context}"=="openshift-immutable"]
* `rhpam76-prod-immutable-monitor.yaml` provides a {CENTRAL} Monitoring instance and a Smart Router that you can use with immutable {KIE_SERVERS}. When you deploy this template, OpenShift displays the settings that you must then use for deploying the `rhpam76-prod-immutable-kieserver.yaml` template. For details about this template, see <<rhpam76-prod-immutable-monitor-ref>>.

* `rhpam76-prod-immutable-kieserver.yaml` provides an immutable {KIE_SERVER}. When you deploy this template, a source-to-image (S2I) build is triggered for one or several services that are to run on the {KIE_SERVER}. The {KIE_SERVER} can optionally be configured to connect to the {CENTRAL} Monitoring and Smart Router provided by `rhpam76-prod-immutable-monitor.yaml`. For details about this template, see <<rhpam76-prod-immutable-kieserver-ref>>.

* `rhpam76-prod-immutable-kieserver-amq.yaml` provides an immutable {KIE_SERVER}. When you deploy this template, a source-to-image (S2I) build is triggered for one or several services that are to run on the {KIE_SERVER}. The {KIE_SERVER} can optionally be configured to connect to the {CENTRAL} Monitoring and Smart Router provided by `rhpam76-prod-immutable-monitor.yaml`. This version of the template includes JMS integration. For details about this template, see <<rhpam76-prod-immutable-kieserver-amq-ref>>.


* `rhpam76-kieserver-externaldb.yaml` provides a {KIE_SERVER} that uses an external database. You can configure the {KIE_SERVER} to connect to a {CENTRAL}. Also, you can copy sections from this template into another template to configure a {KIE_SERVER} in the other template to use an external database. For details about this template, see <<rhpam76-kieserver-externaldb-ref>>.

* `rhpam76-kieserver-mysql.yaml` provides a {KIE_SERVER} and a MySQL instance that the {KIE_SERVER} uses. You can configure the {KIE_SERVER} to connect to a {CENTRAL}. Also, you can copy sections from this template into another template to configure a {KIE_SERVER} in the other template to use MySQL and to provide the MySQL instance. For details about this template, see <<rhpam76-kieserver-mysql-ref>>.

* `rhpam76-kieserver-postgresql.yaml` provides a {KIE_SERVER} and a PostgreSQL instance that the {KIE_SERVER} uses. You can configure the {KIE_SERVER} to connect to a {CENTRAL}. Also, you can copy sections from this template into another template to configure a {KIE_SERVER} in the other template to use PostgreSQL and to provide the PostgreSQL instance. For details about this template, see <<rhpam76-kieserver-mysql-ref>>.
endif::[]

ifeval::["{context}"=="openshift-trial"]
* `rhpam76-trial-ephemeral.yaml` provides a {CENTRAL} and a {KIE_SERVER} connected to the {CENTRAL}. This environment uses an ephemeral configuration without any persistent storage. For details about this template, see <<rhpam76-trial-ephemeral-ref>>.
endif::[]

ifeval::["{context}"=="openshift-freeform"]
* `rhpam76-managed.yaml` provides a high-availability {CENTRAL} Monitoring instance, a {KIE_SERVER}, and a PostgreSQL instance that the {KIE_SERVER} uses. `OpenShiftStartupStrategy` is enabled, ensuring that the {CENTRAL} Monitoring instance can connect to other {KIE_SERVER} instances in the same project automatically, as long as these instances have OpenShiftStartupStrategy enabled as well.

For reference information about other templates used in this environment, see {URL_DEPLOYING_IMMUTABLE_ON_OPENSHIFT}/template-overview-con#template-overview-con[the reference section in _{DEPLOYING_IMMUTABLE_ON_OPENSHIFT}_].
endif::[]
endif::PAM[]
ifdef::DM[]
ifeval::["{context}"=="openshift-authoring-managed"]
* `rhdm76-authoring.yaml` provides a {CENTRAL} and a {KIE_SERVER} connected to the {CENTRAL}. You can use this environment to author services and other business assets or to run them in staging or production environments. For details about this template, see <<rhdm76-authoring-ref>>.

* `rhdm76-authoring-ha.yaml` provides a high-availability {CENTRAL} and a {KIE_SERVER} connected to the {CENTRAL}. You can use this environment to author services and other business assets or to run them in staging or production environments. For details about this template, see <<rhdm76-authoring-ha-ref>>.

* `rhdm76-kieserver.yaml` provides a {KIE_SERVER}. You can configure the {KIE_SERVER} to connect to a {CENTRAL}. In this way, you can set up a staging or production environment in which one {CENTRAL} manages several distinct {KIE_SERVERS}. For details about this template, see <<rhdm76-kieserver-ref>>.
endif::[]

ifeval::["{context}"=="openshift-immutable"]
* `rhdm76-prod-immutable-kieserver.yaml` provides an immutable {KIE_SERVER}. Deployment of this template includes a source-to-image (S2I) build for one or several services that are to run on the {KIE_SERVER}. For details about this template, see <<rhdm76-prod-immutable-kieserver-ref>>.

* `rhdm76-prod-immutable-kieserver-amq.yaml` provides an immutable {KIE_SERVER}. Deployment of this template includes a source-to-image (S2I) build for one or several services that are to run on the {KIE_SERVER}. This version of the template includes JMS integration. For details about this template, see <<rhdm76-prod-immutable-kieserver-amq-ref>>.
endif::[]

ifeval::["{context}"=="openshift-trial"]
* `rhdm76-trial-ephemeral.yaml` provides a {CENTRAL} and a {KIE_SERVER} connected to the {CENTRAL}. This environment uses an ephemeral configuration without any persistent storage. For details about this template, see <<rhdm76-trial-ephemeral-ref>>.
endif::[]

endif::DM[]
