[id='template-deploy-namespace-{context}-proc']
= Configuring the image stream namespace for {what_deploying_brief}

If you created image streams in a namespace that is not `openshift`, you must configure the namespace in the template.

If all image streams were already available in your {OPENSHIFT} environment, you can skip this procedure.

.Prerequisites

* You started the configuration of the template, as described in {startlink}.

.Procedure

ifeval::["{context}"=="authoring"]
. If
endif::[]
ifeval::["{context}"!="authoring"]
If
endif::[]
you installed an image streams file according to instructions in <<imagestreams-file-install-proc>>, set the *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`) parameter to the name of your OpenShift project.

ifeval::["{context}"=="authoring"]
. If you are deploying a high-availability authoring environment and installed an image streams file for AMQ scaledown controller image streams according to instructions in <<imagestreams-file-install-amq-proc>>, set the *AMQ Scaledown Controller ImageStream Namespace* (`AMQ_SCALEDOWN_CONTROLLER_IMAGE_STREAM_NAMESPACE`) parameter to the name of your OpenShift project.
endif::[]
