[id='template-deploy-mandatory-{context}-proc']
= Setting required parameters for {what_deploying_brief}

// local variables depending on the assembly context
:params_central!:
:params_central_startupstrategy!:
:params_kieserver!:
:params_kieserver_s2i!:
:params_smartrouter!:
:params_kieserver_container_deployment!:
:params_multideploy!:
:params_mandatory_maven!:
:maven_single_server!:
:mode_production_template!:
:mode_template_word!:

ifeval::["{context}"=="freeform-monitor"]
:params_central:
:params_central_startupstrategy:
:params_kieserver:
:params_mandatory_maven:
:mode_production_template: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-managed.yaml
:mode_template_word: template
endif::[]

ifeval::["{context}"=="authoring"]
:params_central:
:params_kieserver:
endif::[]


ifeval::["{context}"=="monitoring"]
:params_central:
:params_central_startupstrategy:
:params_mandatory_maven:
:params_smartrouter:
endif::[]


ifeval::["{context}"=="freeform-server-managed"]
:params_kieserver:
:params_multideploy:
:params_mandatory_maven:
:maven_single_server:
:mode_production_template: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-*.yaml
:mode_template_word: templates
endif::[]

ifeval::["{context}"=="fixed"]
:params_central:
:params_kieserver:
:params_multideploy:
:params_mandatory_maven:
:maven_single_server:
:mode_production_template: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-*.yaml
:mode_template_word: templates
:params_smartrouter:
endif::[]


ifeval::["{context}"=="additional-server-managed"]
:params_kieserver:
:params_multideploy:
:mode_production_template: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver.yaml
:mode_template_word: template
endif::[]



ifeval::["{context}"=="server-immutable-s2i"]
:params_kieserver:
:params_kieserver_s2i:
:params_multideploy:
endif::[]

ifeval::["{context}"=="server-immutable-kjar"]
:params_kieserver:
:params_kieserver_container_deployment:
:params_multideploy:
:params_mandatory_maven:
:maven_single_server:
:mode_production_template: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-*.yaml
:mode_template_word: templates
endif::[]


When configuring the template to deploy {what_deploying}, you must set the following parameters in all cases.

.Prerequisites

* You started the configuration of the template, as described in {startlink}.

.Procedure

. Set the following parameters:
** *Credentials secret* (`CREDENTIALS_SECRET`): The name of the secret containing the administrative user credentials, as created in <<secret-adminuser-create-proc>>.
ifdef::params_central[]
** *{LOCAL_CENTRAL} Server Keystore Secret Name* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET`): The name of the secret for {CENTRAL}, as created in <<secrets-central-create-proc>>.
endif::params_central[]
ifdef::params_kieserver[]
** *KIE Server Keystore Secret Name* (`KIE_SERVER_HTTPS_SECRET`): The name of the secret for {KIE_SERVER}, as created in <<secrets-kie-create-proc>>.
endif::params_kieserver[]
ifdef::params_smartrouter[]
** *Smart Router Keystore Secret Name* (`KIE_SERVER_ROUTER_HTTPS_SECRET`): The name of the secret for Smart Router, as created in <<secrets-smartrouter-create-proc>>.
endif::params_smartrouter[]
ifdef::params_central[]
** *{LOCAL_CENTRAL} Server Certificate Name* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-central-create-proc>>.
** *{LOCAL_CENTRAL} Server Keystore Password* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-central-create-proc>>.
endif::params_central[]
ifdef::params_kieserver[]
** *KIE Server Certificate Name* (`KIE_SERVER_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server Keystore Password* (`KIE_SERVER_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-kie-create-proc>>.
endif::params_kieserver[]
ifdef::params_smartrouter[]
** *Smart Router Certificate Name* (`KIE_SERVER_ROUTER_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-smartrouter-create-proc>>.
** *Smart Router Keystore Password* (`KIE_SERVER_ROUTER_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-smartrouter-create-proc>>.
endif::params_smartrouter[]
** *Application Name* (`APPLICATION_NAME`): The name of the OpenShift application. It is used in the default URLs for {CENTRAL} Monitoring and {KIE_SERVER}. OpenShift uses the application name to create a separate set of deployment configurations, services, routes, labels, and artifacts.
ifdef::params_multideploy[]
You can deploy several applications using the same template into the same project, as long as you use different application names. Also, the application name determines the name of the server configuration (server template) that the {KIE_SERVER} joins on {LOCAL_CENTRAL}. If you are deploying several {KIE_SERVERS}, you must ensure each of the servers has a different application name.
endif::params_multideploy[]
ifdef::params_central_startupstrategy[]
** *Enable KIE server global discovery* (`KIE_SERVER_CONTROLLER_OPENSHIFT_GLOBAL_DISCOVERY_ENABLED`): Set this parameter to `true` if you want {LOCAL_CENTRAL} to discover all {KIE_SERVERS} with the `OpenShiftStartupStrategy` in the same namespace. By default, {LOCAL_CENTRAL} discovers only {KIE_SERVERS} that are deployed with the same value of the `APPLICATION_NAME` parameter as {LOCAL_CENTRAL} itself.
endif::params_central_startupstrategy[]
ifdef::params_mandatory_maven[]
** *Maven repository URL* (`MAVEN_REPO_URL`): A URL for a Maven repository. You must upload all the processes (KJAR files) that are to be deployed
ifndef::maven_single_server[]
on any {KIE_SERVERS} in your environment
endif::maven_single_server[]
ifdef::maven_single_server[]
on the {KIE_SERVER}
endif::maven_single_server[]
into this repository.
** *Maven repository ID* (`MAVEN_REPO_ID`): An identifier for the Maven repository. The default value is `repo-custom`.
** *Maven repository username* (`MAVEN_REPO_USERNAME`): The user name for the Maven repository.
** *Maven repository password* (`MAVEN_REPO_PASSWORD`): The password for the Maven repository.
endif::params_mandatory_maven[]
ifdef::params_kieserver_container_deployment[]
** *KIE Server Container Deployment* (`KIE_SERVER_CONTAINER_DEPLOYMENT`): The identifying information of the decision services (KJAR files) that the deployment must pull from the Maven repository. The format is `<containerId>=<groupId>:<artifactId>:<version>` or, if you want to specify an alias name for the container, `<containerId>(<aliasId>)=<groupId>:<artifactId>:<version>`. You can provide two or more KJAR files using the `|` separator, as illustrated in the following example: 
+
[source]
----
containerId=groupId:artifactId:version|c2(alias2)=g2:a2:v2 
----
+
endif::params_kieserver_container_deployment[]
ifdef::params_kieserver_s2i[]
** *KIE Server Container Deployment* (`KIE_SERVER_CONTAINER_DEPLOYMENT`): The identifying information of the decision service (KJAR file) that the deployment must pull from the local or external repository after building your source. The format is `<containerId>=<groupId>:<artifactId>:<version>` or, if you want to specify an alias name for the container, `<containerId>(<aliasId>)=<groupId>:<artifactId>:<version>`. You can provide two or more KJAR files using the `|` separator, as illustrated in the following example:
+
[source]
----
containerId=groupId:artifactId:version|c2(alias2)=g2:a2:v2 
----
+ 
//If the `KIE_SERVER_CONTAINER_DEPLOYMENT` value is not defined, the server discovers the group ID, artifact ID, and version of the artifacts by inspecting the `pom.xml` file of your project and uses the artifact ID as the container ID. 
To avoid duplicate container IDs, the artifact ID must be unique for each artifact built or used in your project.
** *Git Repository URL* (`SOURCE_REPOSITORY_URL`): The URL for the Git repository that contains the source for your services.
** *Git Reference* (`SOURCE_REPOSITORY_REF`): The branch in the Git repository.
** *Context Directory* (`CONTEXT_DIR`): The path to the source within the project downloaded from the Git repository.
** *Artifact Directory* (`ARTIFACT_DIR`): The path within the project that contains the required binary files (KJAR files and any other necessary files) after a successful Maven build. Normally this directory is the target directory of the build. However, you can provide prebuilt binaries in this directory in the Git repository.
endif::params_kieserver_s2i[]
ifdef::mode_production_template[]
** *KIE Server Mode* (`KIE_SERVER_MODE`): In the `{mode_production_template}` {mode_template_word} the default value is `PRODUCTION`. In `PRODUCTION` mode, you cannot deploy `SNAPSHOT` versions of KJAR artifacts on the {KIE_SERVER} and cannot change versions of an artifact in an existing container. To deploy a new version with `PRODUCTION` mode, create a new container on the same {KIE_SERVER}. To deploy `SNAPSHOT` versions or to change versions of an artifact in an existing container, set this parameter to `DEVELOPMENT`.
endif::mode_production_template[]
** *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`): The namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-proc>>), the namespace is `openshift`. If you have installed the image streams file, the namespace is the name of the OpenShift project.

.Next steps

If necessary, set additional parameters.

To complete the deployment, follow the procedure in <<template-deploy-complete-{context}-proc>>.
