[id='template-overview-con_{context}']
= OpenShift template reference information

{PRODUCT} provides the following OpenShift templates. To access the templates, download and extract the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat customer portal.

ifdef::PAM[]
* `rhpam79-authoring.yaml` provides a {CENTRAL} and a {KIE_SERVER} connected to the {CENTRAL}. The {KIE_SERVER} uses an H2 database with persistent storage. You can use this environment to author processes, services, and other business assets. For details about this template, see <<rhpam79-authoring-ref_{context}>>.
* `rhpam79-authoring-ha.yaml` provides a high-availability {CENTRAL}, a {KIE_SERVER} connected to the {CENTRAL}, and a MySQL instance that the {KIE_SERVER} uses. You can use this environment to author processes, services, and other business assets. For details about this template, see <<rhpam79-authoring-ha-ref_{context}>>.
* `rhpam79-prod-immutable-monitor.yaml` provides a {CENTRAL} Monitoring instance and a Smart Router that you can use with immutable {KIE_SERVERS}. When you deploy this template, OpenShift displays the settings that you must then use for deploying the `rhpam79-prod-immutable-kieserver.yaml` template. For details about this template, see <<rhpam79-prod-immutable-monitor-ref_{context}>>.
* `rhpam79-prod-immutable-kieserver.yaml` provides an immutable {KIE_SERVER}. When you deploy this template, a source-to-image (S2I) build is triggered for one or several services that are to run on the {KIE_SERVER}. The {KIE_SERVER} can optionally be configured to connect to the {CENTRAL} Monitoring and Smart Router provided by `rhpam79-prod-immutable-monitor.yaml`. For details about this template, see <<rhpam79-prod-immutable-kieserver-ref_{context}>>.
* `rhpam79-prod-immutable-kieserver-amq.yaml` provides an immutable {KIE_SERVER}. When you deploy this template, a source-to-image (S2I) build is triggered for one or several services that are to run on the {KIE_SERVER}. The {KIE_SERVER} can optionally be configured to connect to the {CENTRAL} Monitoring and Smart Router provided by `rhpam79-prod-immutable-monitor.yaml`. This version of the template includes JMS integration. For details about this template, see <<rhpam79-prod-immutable-kieserver-amq-ref_{context}>>.
* `rhpam79-kieserver-externaldb.yaml` provides a {KIE_SERVER} that uses an external database. You can configure the {KIE_SERVER} to connect to a {CENTRAL}. Also, you can copy sections from this template into another template to configure a {KIE_SERVER} in the other template to use an external database. For details about this template, see <<rhpam79-kieserver-externaldb-ref_{context}>>.
* `rhpam79-kieserver-mysql.yaml` provides a {KIE_SERVER} and a MySQL instance that the {KIE_SERVER} uses. You can configure the {KIE_SERVER} to connect to a {CENTRAL}. Also, you can copy sections from this template into another template to configure a {KIE_SERVER} in the other template to use MySQL and to provide the MySQL instance. For details about this template, see <<rhpam79-kieserver-mysql-ref_{context}>>.
* `rhpam79-kieserver-postgresql.yaml` provides a {KIE_SERVER} and a PostgreSQL instance that the {KIE_SERVER} uses. You can configure the {KIE_SERVER} to connect to a {CENTRAL}. Also, you can copy sections from this template into another template to configure a {KIE_SERVER} in the other template to use PostgreSQL and to provide the PostgreSQL instance. For details about this template, see <<rhpam79-kieserver-mysql-ref_{context}>>.
* `rhpam79-managed.yaml` provides a high-availability {CENTRAL} Monitoring instance, a {KIE_SERVER}, and a PostgreSQL instance that the {KIE_SERVER} uses. `OpenShiftStartupStrategy` is enabled, ensuring that the {CENTRAL} Monitoring instance can connect to other {KIE_SERVER} instances in the same project automatically, as long as these instances have OpenShiftStartupStrategy enabled as well.
* `rhpam79-prod.yaml` provides a high-availability {CENTRAL} Monitoring instance, a Smart Router, two distinct {KIE_SERVERS} connected to the {CENTRAL} and to the Smart Router, and two PostgreSQL instances. Each {KIE_SERVER} uses its own PostgreSQL instance. You can use this environment to execute business assets in a production or staging environment. You can configure the number of replicas for each component. For details about this template, see <<rhpam79-prod-ref_{context}>>.
* `rhpam79-trial-ephemeral.yaml` provides a {CENTRAL} and a {KIE_SERVER} connected to the {CENTRAL}. This environment uses an ephemeral configuration without any persistent storage. For details about this template, see <<rhpam79-trial-ephemeral-ref_{context}>>.
endif::PAM[]
ifdef::DM[]
* `rhdm79-authoring.yaml` provides a {CENTRAL} and a {KIE_SERVER} connected to the {CENTRAL}. You can use this environment to author services and other business assets or to run them in staging or production environments. For details about this template, see <<rhdm79-authoring-ref_{context}>>.
* `rhdm79-authoring-ha.yaml` provides a high-availability {CENTRAL} and a {KIE_SERVER} connected to the {CENTRAL}. You can use this environment to author services and other business assets or to run them in staging or production environments. For details about this template, see <<rhdm79-authoring-ha-ref_{context}>>.
* `rhdm79-kieserver.yaml` provides a {KIE_SERVER}. You can configure the {KIE_SERVER} to connect to a {CENTRAL}. In this way, you can set up a staging or production environment in which one {CENTRAL} manages several distinct {KIE_SERVERS}. For details about this template, see <<rhdm79-kieserver-ref_{context}>>.
* `rhdm79-prod-immutable-kieserver.yaml` provides an immutable {KIE_SERVER}. Deployment of this template includes a source-to-image (S2I) build for one or several services that are to run on the {KIE_SERVER}. For details about this template, see <<rhdm79-prod-immutable-kieserver-ref_{context}>>.
* `rhdm79-prod-immutable-kieserver-amq.yaml` provides an immutable {KIE_SERVER}. Deployment of this template includes a source-to-image (S2I) build for one or several services that are to run on the {KIE_SERVER}. This version of the template includes JMS integration. For details about this template, see <<rhdm79-prod-immutable-kieserver-amq-ref_{context}>>.
* `rhdm79-trial-ephemeral.yaml` provides a {CENTRAL} and a {KIE_SERVER} connected to the {CENTRAL}. This environment uses an ephemeral configuration without any persistent storage. For details about this template, see <<rhdm79-trial-ephemeral-ref_{context}>>.
endif::DM[]
