[id='template-deploy-ldap-{context}-proc']
= Setting parameters for LDAP authentication for {what_deploying_brief}

If you want to use LDAP authentication, complete the following additional configuration when configuring the template to deploy {what_deploying}.

[IMPORTANT]
====
Do not configure LDAP authentication and RH-SSO authentication in the same deployment.
====

.Prerequisites

* You created user names and passwords for {PRODUCT} in the LDAP system. For a list of the available roles, see <<roles-users-con>>.  
+
You must create a user with the username and password configured in the secret for the administrative user, as described in <<secret-adminuser-create-proc>>. This user must have the `kie-server,rest-all,admin` roles.
* You started the configuration of the template, as described in {startlink}.

.Procedure
. Set the `AUTH_LDAP*` parameters of the template. These parameters correspond to the settings of the `LdapExtended` Login module of {EAP}. For instructions about using these settings, see https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html-single/login_module_reference/#ldapextended_login_module[LdapExtended login module].
+
If the LDAP server does not define all the roles required for your deployment, you can map LDAP groups to {PRODUCT} roles. To enable LDAP role mapping, set the following parameters:
+
** *RoleMapping rolesProperties file path* (`AUTH_ROLE_MAPPER_ROLES_PROPERTIES`): The fully qualified path name of a file that defines role mapping, for example, `/opt/eap/standalone/configuration/rolemapping/rolemapping.properties`. You must provide this file and mount it at this path in all applicable deployment configurations; for instructions, see <<rolemapping-proc>>.
** *RoleMapping replaceRole property* (`AUTH_ROLE_MAPPER_REPLACE_ROLE`): If set to `true`, mapped roles replace the roles defined on the LDAP server; if set to `false`, both mapped roles and roles defined on the LDAP server are set as user application roles. The default setting is `false`.

.Next steps

If necessary, set additional parameters.

To complete the deployment, follow the procedure in <<template-deploy-complete-{context}-proc>>.
