[id='template-deploy-mandatory-{context}-proc']
= Setting required parameters for {what_deploying_brief}

// local variables depending on the assembly context
:params_central!:
:params_kieserver!:
:params_kieserver_s2i!:
:params_kieserver_container_deployment!:
:params_startup_strategy_first!:
:params_multideploy!:
:params_mandatory_maven!:
:params_serveruser_startupstrategy!:
:mode_production_template!:
:mode_production_template_word!:

ifeval::["{context}"=="freeform-monitor"]
:params_central:
:params_kieserver:
:params_mandatory_maven:
:mode_production_template: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-managed.yaml
:mode_production_template_word: template
endif::[]

ifeval::["{context}"=="freeform-server-managed"]
:params_kieserver:
:params_kieserver_container_deployment:
:params_startup_strategy_first:
:params_multideploy:
:params_mandatory_maven:
:params_serveruser_startupstrategy:
:mode_production_template: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-*.yaml
:mode_production_template_word: templates
endif::[]

ifeval::["{context}"=="freeform-server-immutable"]
:params_kieserver:
:params_kieserver_s2i:
:params_startup_strategy_first:
:params_multideploy:
:params_serveruser_startupstrategy:
endif::[]

When configuring the template to deploy {what_deploying}, you must set the following parameters in all cases. 

.Prerequisite

You started the configuration of the template, as described in {startlink}.

.Procedure

. Set the following parameters:
ifdef::params_startup_strategy_first[]
** *KIE Server Startup Strategy* (`KIE_SERVER_STARTUP_STRATEGY`). This parameter must be set to `OpenShiftStartupStrategy` to ensure that an OpenShift enabled {LOCAL_CENTRAL} connects to the {KIE_SERVER} automatically, using an OpenShift API.
endif::params_startup_strategy_first[]
ifdef::params_central[]
** *{LOCAL_CENTRAL} Server Keystore Secret Name* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET`): The name of the secret for {CENTRAL}, as created in <<secrets-central-create-proc>>.
endif::params_central[]
ifdef::params_kieserver[]
** *KIE Server Keystore Secret Name* (`KIE_SERVER_HTTPS_SECRET`): The name of the secret for {KIE_SERVER}, as created in <<secrets-kie-create-proc>>.
endif::params_kieserver[]
ifdef::params_central[]
** *{LOCAL_CENTRAL} Server Certificate Name* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-central-create-proc>>. 
** *{LOCAL_CENTRAL} Server Keystore Password* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-central-create-proc>>.
endif::params_central[]
ifdef::params_kieserver[]
** *KIE Server Certificate Name* (`KIE_SERVER_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server Keystore Password* (`KIE_SERVER_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-kie-create-proc>>.
endif::params_kieserver[]
** *Application Name* (`APPLICATION_NAME`): The name of the OpenShift application. It is used in the default URLs for {CENTRAL} Monitoring and {KIE_SERVER}. OpenShift uses the application name to create a separate set of deployment configurations, services, routes, labels, and artifacts. 
ifdef::params_multideploy[]
You can deploy several applications using the same template into the same project, as long as you use different application names. Also, the application name determines the name of the server configuration (server template) on the {LOCALCENTRAL} that the {KIE_SERVER} is to join. If you are deploying several {KIE_SERVERS}, you must ensure each of the servers has a different application name.
endif::params_multideploy[]
ifdef::params_mandatory_maven[]
** *Maven repository URL* (`MAVEN_REPO_URL`): A URL for a Maven repository. You must upload all the processes (KJAR files) that are to be deployed on managed {KIE_SERVERS} in your environment into this repository.
** *Maven repository username* (`MAVEN_REPO_USERNAME`): The username for the Maven repository.
** *Maven repository password* (`MAVEN_REPO_PASSWORD`): The password for the Maven repository.
endif::params_mandatory_maven[]
ifdef::params_kieserver_s2i[]
** *KIE Server Container Deployment* (`KIE_SERVER_CONTAINER_DEPLOYMENT`): The identifying information of the decision service (KJAR file) that is built from your source. The format is: `<containerId>=<groupId>:<artifactId>:<version>`. You can provide two or more KJAR files using the `|` separator, for example: `containerId=groupId:artifactId:version|c2=g2:a2:v2`. The Maven build process must produce all these files from the source in the Git repository.
** *Git Repository URL* (`SOURCE_REPOSITORY_URL`): The URL for the Git repository that contains the source for your decision service.
** *Git Reference* (`SOURCE_REPOSITORY_REF`): The branch in the Git repository
** *Context Directory* (`CONTEXT_DIR`): The path to the source within the project downloaded from the Git repository
** *Artifact Directory* (`ARTIFACT_DIR`): The path within the project that contains the required binary files (KJAR files and any other necessary files) after a successful Maven build. Normally this directory is the target directory of the build. However, you can provide prebuilt binaries in this directory in the Git repository
endif::params_kieserver_s2i[]
ifdef::mode_production_template[]
** *KIE Server Mode* (`KIE_SERVER_MODE`): In the `{mode_production_template}` {mode_production_template_word} the default value is `PRODUCTION`; in this mode, you can not deploy `SNAPSHOT` versions of KJAR artifacts on the {KIE_SERVER} and can not change versions of an artifact in an existing container. (To deploy a new version with `PRODUCTION` mode, you can create a new container on the same {KIE_SERVER}). To deploy `SNAPSHOT` versions or to change versions of an artifact in an existing container, set this parameter to `DEVELOPMENT`. 
endif::mode_production_template[]
** *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`): The namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-proc>>), the namespace is `openshift`. If you have installed the image streams file, the namespace is the name of the OpenShift project.
ifdef::params_central[]
ifeval::["{LOCAL_CENTRAL}"=="{CENTRAL} Monitoring"]
** *{LOCAL_CENTRAL} Container Replicas* (`{CENTRAL_CAPITAL_UNDER}_MONITORING_CONTAINER_REPLICAS`): The number of replicas initially created for {CENTRAL} Monitoring. If you do not want to use a high-availability configuration for {CENTRAL} Monitoring, set this number to 1.
endif::[]
// this next one is available only in managed and prod templates. Temporarily put under Central,
// but when adding other templates, need to review the conditioning
** *KIE Server Container Replicas* (`KIE_SERVER_CONTAINER_REPLICAS`): The number of replicas initially created for the {KIE_SERVER}.
endif::params_central[]
ifdef::params_kieserver_container_deployment[]
+
. If you want to deploy and start services from the Maven repository at the startup of the {KIE_SERVER}, set the following parameter. Note that in this case, {LOCAL_CENTRAL} is not able to deploy and undeploy services on this {KIE_SERVER}.
** *KIE Server Container Deployment* (`KIE_SERVER_CONTAINER_DEPLOYMENT`): The identifying information of the decision services (KJAR files) that the deployment must pull from the Maven repository. The format is: `<containerId>=<groupId>:<artifactId>:<version>`. You can provide two or more KJAR files using the `|` separator, for example: `containerId=groupId:artifactId:version|c2=g2:a2:v2`.
endif::params_kieserver_container_deployment[]
+
. Set the following user names and passwords. By default, the deployment automatically generates the passwords.
** *KIE Admin User* (`KIE_ADMIN_USER`) and *KIE Admin Password* (`KIE_ADMIN_PWD`): The user name and password for the administrative user in {CENTRAL} Monitoring.
ifdef::params_kieserver[]
** *KIE Server User* (`KIE_SERVER_USER`) and *KIE Server Password* (`KIE_SERVER_PWD`): The user name and password that a client application must use to connect to any of the {KIE_SERVERS}.
ifeval::["{context}"=="freeform-monitor"]
You must set the user name and password and record them, so you can use the same credentials when deploying additional {KIE_SERVERS}.
endif::[]
ifdef::params_serveruser_startupstrategy[]
To enable the {LOCAL_CENTRAL} connection to this {KIE_SERVER}, you must set these parameters to the same values as the same parameters for the {LOCAL_CENTRAL} deployment that you set in <<template-deploy-mandatory-freeform-monitor-proc>>.  
endif::params_serveruser_startupstrategy[]


endif::params_kieserver[]
ifeval::["{context}"=="freeform-monitor"]
+
. Ensure the following parameters retain their default values:
** *Enable OpenShift Integration* (`KIE_WORKBENCH_CONTROLLER_OPENSHIFT_ENABLED`): This parameter must be set to `true` to enable OpenShift integration for the {LOCAL_CENTRAL}. With OpenShift integration, the {LOCAL_CENTRAL} connects to all {KIE_SERVERS} in the same namespace automatically if OpenShift Startup Strategy is enabled on the {KIE_SERVERS}. The default value is `true`. Do not change this value.
** *KIE Server Startup Strategy* (`KIE_SERVER_STARTUP_STRATEGY`): This parameter must be set to `OpenShiftStartupStrategy` to ensure that the OpenShift enabled {LOCAL_CENTRAL} connects to the {KIE_SERVER} automatically, using an OpenShift API. The default value is `OpenShiftStartupStrategy`. Do not change this value.
endif::[]

.Next steps

If necessary, set additional parameters. 

To complete the deployment, follow the procedure in <<template-deploy-complete-{context}-proc>>.
