[id='template-deploy-start-{context}-proc']
:startlink: <<template-deploy-start-{context}-proc>>
= Starting configuration of the template for {what_deploying_brief}

:template_name!:
:template_add_params:
:modifylink!:
:modifytype:
:single_template_file:

:server_template_files!:
ifeval::["{context}"=="freeform-monitor"]
:template_add_params: {CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET={CENTRAL_ONEWORD}-app-secret -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret
:template_name: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-managed.yaml
endif::[]

ifeval::["{context}"=="monitoring"]
:template_add_params: {CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET={CENTRAL_ONEWORD}-app-secret
:template_name: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-immutable-monitor.yaml
endif::[]

ifeval::["{context}"=="authoring"]
:template_add_params: {CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET={CENTRAL_ONEWORD}-app-secret -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret
:single_template_file!:
endif::[]


ifeval::["{context}"=="server-immutable-s2i"]
:template_name: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-prod-immutable-kieserver.yaml
:template_add_params: -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret
ifdef::PAM[]
:modifylink: environment-immutable-modify-proc
:modifytype: fixed
endif::PAM[]
endif::[]

ifeval::["{context}"=="fixed"]
:template_name: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-prod
:template_add_params: {CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET={CENTRAL_ONEWORD}-app-secret -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret
:modifylink: environment-managed-modify-proc
:modifytype: fixed
endif::[]


ifeval::["{context}"=="freeform-server-managed"]
// a PAM-only entry
:single_template_file!:
:server_template_files:
:template_add_params: -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret
endif::[]
ifeval::["{context}"=="additional-server-managed"]
// a DM-only entry
:template_name: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver.yaml
:template_add_params: -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret
endif::[]
ifeval::["{context}"=="server-immutable-kjar"]
ifdef::PAM[]
:single_template_file!:
:server_template_files:
endif::PAM[]
ifdef::DM[]
:template_name: {PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver.yaml
endif::DM[]
:template_add_params: -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret
endif::[]

ifdef::single_template_file[]
To deploy {what_deploying}, use the `{template_name}` template file.
endif::single_template_file[]

ifdef::server_template_files[]
:template_name: <template-file-name>.yaml
To deploy {what_deploying}, use one of the following template files:

* `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-postgresql.yaml` to use a PostgreSQL pod for persistent storage. Use this template unless you have a specific reason to use another template.

* `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-mysql.yaml` to use a MySQL pod for persistent storage.

* `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver-externaldb.yaml` to use an external database server for persistent storage.
+
IMPORTANT: The standard {KIE_SERVER} image for an external database server includes drivers for MySQL and PostgreSQL external database servers. If you want to use another database server, you must build a custom {KIE_SERVER} image. For instructions, see <<externaldb-build-proc>>.
endif::server_template_files[]

ifeval::["{context}"=="authoring"]
:template_name: <template-file-name>.yaml
If you want to deploy a single authoring environment, use the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring.yaml` template file.
ifdef::PAM[]
By default, the single authoring template uses the H2 database with permanent storage. If you prefer to create a MySQL or PostgreSQL pod or to use an external database server (outside the OpenShift project), modify the template before deploying the environment. For instructions about modifying the template, see <<environment-authoring-single-modify-proc>>.
endif::PAM[]

If you want to deploy a high-availability authoring environment, use the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring-ha.yaml` template file.
ifdef::PAM[]
By default, the high-availability authoring template creates a MySQL pod to provide the database server for the {KIE_SERVER}. If you prefer to use PostgreSQL or to use an external server (outside the OpenShift project) you need to modify the template before deploying the environment. You can also modify the template to change the number of replicas initially created for {CENTRAL}. For instructions about modifying the template, see <<environment-authoring-ha-modify-proc>>.
endif::PAM[]
endif::[]

.Procedure

. Download the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.

ifdef::single_template_file[]
. Extract the `{template_name}` template file.
endif::single_template_file[]
ifndef::single_template_file[]
. Extract the required template file.
endif::single_template_file[]

ifeval::["{modifytype}"=="single-kie-server"]
. By default, the {KIE_SERVER} uses a PostgreSQL database server in a pod. To use a MySQL database server in a pod or an external database server, modify the template as described in <<{modifylink}>>.
endif::[]
ifeval::["{modifytype}"=="fixed"]
. By default, the template includes two {KIE_SERVERS}. Each of the serves uses a PostgreSQL database server in a pod. To change the number of {KIE_SERVERS} or to use a MySQL database server in a pod or an external database server, modify the template as described in <<{modifylink}>>.
endif::[]

. Use one of the following methods to start deploying the template:
* To use the OpenShift Web UI, in the OpenShift application console select *Add to Project -> Import YAML / JSON* and then select or paste the `{template_name}` file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
* To use the OpenShift command line console, prepare the following command line:
+
[subs="attributes,verbatim,macros"]
----
oc new-app -f <template-path>/{template_name} -p {template_add_params}
----
+
In this command line, make the following changes:
+
** Replace `<template-path>` with the path to the downloaded template file.
ifndef::single_template_file[]
** Replace `<template-file-name>` with the name of the template file.
endif::single_template_file[]
** Use as many `-p PARAMETER=value` pairs as needed to set the required parameters.

.Next steps

Set the parameters for the template. Follow the steps in <<template-deploy-mandatory-{context}-proc>> to set common parameters. You can view the template file to see descriptions for all parameters.
