[id='template-overview-con_{context}']
= OpenShift template reference information

{PRODUCT} provides the following OpenShift templates. To access the templates, download and extract the `{PRODUCT_FILE}-openshift-templates.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat customer portal.

ifdef::PAM[]
* `rhpam713-trial-ephemeral.yaml` provides a {CENTRAL} instance and a {KIE_SERVER} instance connected to the {CENTRAL} instance. This environment uses an ephemeral configuration without any persistent storage. For details about this template, see <<rhpam713-trial-ephemeral-ref_{context}>>.
* `rhpam713-authoring.yaml` provides a {CENTRAL} instance and a {KIE_SERVER} instance connected to the {CENTRAL} instance. the {KIE_SERVER} instance uses an H2 database with persistent storage. You can use this environment to author processes, services, and other business assets. For details about this template, see <<rhpam713-authoring-ref_{context}>>.
* `rhpam713-authoring-ha.yaml` provides a high-availability {CENTRAL}, a {KIE_SERVER} instance connected to the {CENTRAL} instance, and a MySQL instance that the {KIE_SERVER} instance uses. You can use this environment to author processes, services, and other business assets. For details about this template, see <<rhpam713-authoring-ha-ref_{context}>>.
* `rhpam713-prod-immutable-monitor.yaml` provides a {CENTRAL} Monitoring instance and a Smart Router that you can use with immutable {KIE_SERVERS}. When you deploy this template, OpenShift displays the settings that you must then use for deploying the `rhpam713-prod-immutable-kieserver.yaml` template. For details about this template, see <<rhpam713-prod-immutable-monitor-ref_{context}>>.
* `rhpam713-prod-immutable-kieserver.yaml` provides an immutable {KIE_SERVER} instance. When you deploy this template, a source-to-image (S2I) build is triggered for one or several services that are to run on the {KIE_SERVER} instance. the {KIE_SERVER} instance can optionally be configured to connect to the {CENTRAL} Monitoring instance and Smart Router provided by `rhpam713-prod-immutable-monitor.yaml`. For details about this template, see <<rhpam713-prod-immutable-kieserver-ref_{context}>>.
* `rhpam713-prod-immutable-kieserver-amq.yaml` provides an immutable {KIE_SERVER} instance. When you deploy this template, a source-to-image (S2I) build is triggered for one or several services that are to run on the {KIE_SERVER} instance. the {KIE_SERVER} instance can optionally be configured to connect to the {CENTRAL} Monitoring instance and Smart Router provided by `rhpam713-prod-immutable-monitor.yaml`. This version of the template includes JMS integration. For details about this template, see <<rhpam713-prod-immutable-kieserver-amq-ref_{context}>>.
* `rhpam713-kieserver-externaldb.yaml` provides a {KIE_SERVER} instance that uses an external database. You can configure the {KIE_SERVER} instance to connect to a {CENTRAL} instance. Also, you can copy sections from this template into another template to configure a {KIE_SERVER} instance in the other template to use an external database. For details about this template, see <<rhpam713-kieserver-externaldb-ref_{context}>>.
* `rhpam713-kieserver-mysql.yaml` provides a {KIE_SERVER} instance and a MySQL instance that the {KIE_SERVER} instance uses. You can configure the {KIE_SERVER} instance to connect to a {CENTRAL} instance. Also, you can copy sections from this template into another template to configure a {KIE_SERVER} instance in the other template to use MySQL and to provide the MySQL instance. For details about this template, see <<rhpam713-kieserver-mysql-ref_{context}>>.
* `rhpam713-kieserver-postgresql.yaml` provides a {KIE_SERVER} instance and a PostgreSQL instance that the {KIE_SERVER} instance uses. You can configure the {KIE_SERVER} instance to connect to a {CENTRAL} instance. Also, you can copy sections from this template into another template to configure a {KIE_SERVER} instance in the other template to use PostgreSQL and to provide the PostgreSQL instance. For details about this template, see <<rhpam713-kieserver-postgresql-ref_{context}>>.
* `rhpam713-managed.yaml` provides a high-availability {CENTRAL} Monitoring instance, a {KIE_SERVER} instance, and a PostgreSQL instance that the {KIE_SERVER} instance uses. `OpenShiftStartupStrategy` is enabled, ensuring that the {CENTRAL} Monitoring instance can connect to other {KIE_SERVER} instances in the same project automatically, as long as these instances have OpenShiftStartupStrategy enabled as well. For details about this template, see <<rhpam713-managed-ref_{context}>>.
* `rhpam713-prod.yaml` provides a high-availability {CENTRAL} Monitoring instance, a Smart Router, two distinct {KIE_SERVERS} connected to the {CENTRAL} instance and to the Smart Router, and two PostgreSQL instances. Each {KIE_SERVER} uses its own PostgreSQL instance. You can use this environment to execute business assets in a production or staging environment. You can configure the number of replicas for each component. For details about this template, see <<rhpam713-prod-ref_{context}>>.
endif::PAM[]
ifdef::DM[]
* `rhdm713-trial-ephemeral.yaml` provides a {CENTRAL} instance and a {KIE_SERVER} instance connected to the {CENTRAL} instance. This environment uses an ephemeral configuration without any persistent storage. For details about this template, see <<rhdm713-trial-ephemeral-ref_{context}>>.
* `rhdm713-authoring.yaml` provides a {CENTRAL} instance and a {KIE_SERVER} instance connected to the {CENTRAL} instance. You can use this environment to author services and other business assets or to run them in staging or production environments. For details about this template, see <<rhdm713-authoring-ref_{context}>>.
* `rhdm713-authoring-ha.yaml` provides a high-availability {CENTRAL} and a {KIE_SERVER} instance connected to the {CENTRAL} instance. You can use this environment to author services and other business assets or to run them in staging or production environments. For details about this template, see <<rhdm713-authoring-ha-ref_{context}>>.
* `rhdm713-kieserver.yaml` provides a {KIE_SERVER} instance. You can configure the {KIE_SERVER} instance to connect to a {CENTRAL} instance. In this way, you can set up a staging or production environment in which one {CENTRAL} manages several distinct {KIE_SERVERS}. For details about this template, see <<rhdm713-kieserver-ref_{context}>>.
* `rhdm713-prod-immutable-kieserver.yaml` provides an immutable {KIE_SERVER} instance. Deployment of this template includes a source-to-image (S2I) build for one or several services that are to run on the {KIE_SERVER} instance. For details about this template, see <<rhdm713-prod-immutable-kieserver-ref_{context}>>.
* `rhdm713-prod-immutable-kieserver-amq.yaml` provides an immutable {KIE_SERVER} instance. Deployment of this template includes a source-to-image (S2I) build for one or several services that are to run on the {KIE_SERVER} instance. This version of the template includes JMS integration. For details about this template, see <<rhdm713-prod-immutable-kieserver-amq-ref_{context}>>.
endif::DM[]
