[id='controller-was-goup-proc_{context}']
= Creating and mapping the `controller` role

After {KIE_SERVER} is installed, you must create the `kie-server` role and `kie-server` group, then map the `kie-server` role to the `kie-server` group before you run {KIE_SERVER}.

.Prerequisites
* {KIE_SERVER} is installed on the {WEBSPHERE} instance.
* All {KIE_SERVER} nodes contain a user with the `kie-server` role.
* All {HEADLESS_CONTROLLER} nodes contain a user with the `kie-server` role.


.Procedure
. In the WebSphere Integrated Solutions Console, click *Users and Groups* -> *Manage Groups*.
. In the *Manage Groups* screen, click *Create*.
. In the *Create a Group* screen, enter `kie-server` in the *Group name* box.
. To create a user to add to the `kie-server` group, click *Users and Groups* -> *Manage Users*.
. In the *Create a User* screen, complete the required information.
. Click *Group Membership*.
. In the *Group Membership* screen, click `kie-server`, move it to *Mapped To*, and click *Close*.
. On the  *Create a User* screen click *Create* to create.
. Under *Detail Properties*, click *Security Role to User/Group Mapping*.
. Select the `kie-server` role and click *Map Groups* to search for the `kie-server` group.
