[id='controller-wls-was-verify-proc_{context}']
= Verifying the installation
After you install the {HEADLESS_CONTROLLER} and define the required system properties and role requirements on the application server, verify that the {HEADLESS_CONTROLLER} works correctly.

.Prerequisites
* {KIE_SERVER} and the {HEADLESS_CONTROLLER} are installed on the application server instance.
* You have set all required system properties and role requirements for the {HEADLESS_CONTROLLER} on the application server.

.Procedure
In your command terminal, enter the following command to verify that the {HEADLESS_CONTROLLER} is working:

[source]
----
curl -X GET "http://<HOST>:<PORT>/controller/rest/controller/management/servers" -H  "accept: application/xml" -u '<CONTROLLER>:<CONTROLLER_PWD>'
----

`<HOST>` is the ID or name of the headless Process Automation Manager controller host, for example, `localhost` or `192.7.8.9`.

`<PORT>` is the port number of the headless Process Automation Manager controller host, for example, `7001`.

`<CONTROLLER>` and `<CONTROLLER_PWD>` are the user credentials that you created in this section.

The command should return information about the {KIE_SERVER} instance.

[NOTE]
====
Alternatively, you can use the {KIE_SERVER} Java API Client to access the {HEADLESS_CONTROLLER}.
====

If the {HEADLESS_CONTROLLER} is not running, stop and restart the application server instance and try again to access the {HEADLESS_CONTROLLER} URL or API.
