[id='controller-was-mapping-proc_{context}']
= Mapping the {HEADLESS_CONTROLLER} group and role

After the {HEADLESS_CONTROLLER} is installed, in the WebSphere Integrated Solutions Console, you must create the `kie-server` group and then map the `kie-server` role to the `kie-server` group.

.Prerequisites
* The {HEADLESS_CONTROLLER} is installed on the {WEBSPHERE} instance.
//* All {KIE_SERVER} nodes contain a user with the `kie-server` role. If you
//* All {HEADLESS_CONTROLLER} nodes contain a user with the `kie-server` role.

.Procedure
. In the WebSphere Integrated Solutions Console, create the `kie-server` group and a user for that group, as described in xref:kie-server-was-goup-proc[_Creating the {KIE_SERVER} group and role_].

. Navigate to *Applications* -> *Application Types* -> *WebSphere Enterprise Applications* and select the newly installed {HEADLESS_CONTROLLER}.
. Under *Detail Properties*, click *Security Role to User/Group Mapping*.
. Select the `kie-server` role and click *Map Groups* to search for the `kie-server` group.
. Move the `kie-server` group from the *Available* list to the *Selected* list and click *OK*.
+
This mapping gives the previously created administrator user access to {PRODUCT_SHORT}.
+
. Click *Save* to complete the mapping.
