[id='controller-was-install-proc']
= Installing and running the {HEADLESS_CONTROLLER} with {WEBSPHERE}

To use the {KIE_SERVER} REST API or Java Client API to interact with {KIE_SERVER}, install the {HEADLESS_CONTROLLER} with {WEBSPHERE}. The {HEADLESS_CONTROLLER} manages {KIE_SERVER} configuration in a centralized way so that you can use the {HEADLESS_CONTROLLER} to create and maintain containers and perform other server-level tasks.

[NOTE]
====
For optimal results, install {KIE_SERVER} and the {HEADLESS_CONTROLLER} on different servers in production environments. In development environments, you can install {KIE_SERVER} and the {HEADLESS_CONTROLLER} on the same server.
====

.Prerequisites
* The {WEBSPHERE} instance is configured as described in xref:was-configure-proc[].
* {KIE_SERVER} is installed on the {WEBSPHERE} instance.
* You have sufficient user permissions to complete the installation.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons*.
. Extract the downloaded `{PRODUCT_FILE}-add-ons.zip` file to a temporary directory.
. Extract the `{PRODUCT_FILE}-add-ons.zip` file to a temporary directory. In the following examples this directory is called `_TEMP_DIR_`.
. Extract the `{PRODUCT_FILE}-add-ons/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7.zip` file.

. Repackage the `controller.war` directory:
.. Navigate to the `_TEMP_DIR_/{PRODUCT_FILE}-add-ons/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7/controller.war` directory.
.. Select the contents of the  `_TEMP_DIR_/{PRODUCT_FILE}-add-ons/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7/controller.war` directory and create the `controller.zip` file.
..  Rename `controller.zip` to `controller.war`. This is the file that you will use to deploy the {HEADLESS_CONTROLLER}.
.. If desired, copy the new `controller.war` file to a location that is more convenient to deploy from.

. In the WebSphere Integrated Solutions Console, navigate to *Applications* -> *Application Types* -> *WebSphere Enterprise Applications*.
. Click *Install*.
. Navigate to the `controller.war` file that you repackaged and select it to upload.
. Select *Fast Path* and click *Next*.
+
The *Install New Application* wizard opens.
+
. Change the *Application Name* to `controller` and click *Next*.
. Map the {HEADLESS_CONTROLLER} modules to servers according to your specific requirements and click *Next*.
. For *Bind Listeners for Message-Driven Beans*, select *Activation Specification* for both beans, enter `jms/activation/KIE.SERVER.REQUEST` in the *Target Resource JNDI Name* field, and enter the `jms/cf/KIE.SERVER.REQUEST` JNDI name for the `KIE.SERVER.REQUEST` connection factory.
. In the *Map Virtual Hosts for Web Modules* section, keep the default values and click *Next*.
. Set the context root to `controller`.
. In the *Metadata for Modules* section, keep the default values and click *Next*.
. Click *Finish* to install the {HEADLESS_CONTROLLER} and click *Save* to save the changes to the master configuration.
