[id='kie-server-was-install-proc']
= Installing and running {KIE_SERVER} with {WEBSPHERE}

After you have configured all required system properties in {WEBSPHERE}, you can install {KIE_SERVER} with {WEBSPHERE_SHORT} to streamline {PRODUCT} application management.

.Prerequisites
* An {WEBSPHERE} instance is configured as described in xref:was-configure-proc[].

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product:* {PRODUCT_PAM_SHORT}
* *Version:* {PRODUCT_VERSION_LONG}
. Download *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} {KIE_SERVER} for All Supported EE7 Containers*.
. Extract the
ifdef::PAM[]
`{PRODUCT_FILE}-kie-server-ee7.zip`
endif::PAM[]
ifdef::DM[]
`{PRODUCT_FILE}-kie-server-ee7.zip`
endif::DM[]
 archive to a temporary directory. In the following examples this directory is called `_TEMP_DIR_`.
. Repackage the `kie-server.war` directory:
.. Navigate to the `_TEMP_DIR_/{PRODUCT_FILE}-kie-server-ee7/kie-server.war` directory.
.. Select the contents of the  `_TEMP_DIR_/{PRODUCT_FILE}-kie-server-ee7/kie-server.war` directory and create the `kie-server.zip` file.
..  Rename `kie-server.zip` to `kie-server.war`. This is the file that you will use to deploy {KIE_SERVER}.
.. Optional: Copy the new `kie-server.war` file to a location that is more convenient to deploy from.

. In the WebSphere Integrated Solutions Console, navigate to *Applications* -> *Application Types* -> *WebSphere Enterprise Applications*.
. Click *InstCll*.
. Navigate to the `kie-server.war` file that you repackaged and select it to upload.
. Select *Fast Path* and click *Next*.
+
The *Install New Application* wizard opens.
+
. Change the *Application Name* to `kie-server` and click *Next*.
. Map the {KIE_SERVER} modules to servers according to your specific requirements and click *Next*.
. For *Bind Listeners for Message-Driven Beans*, select *Activation Specification* for both beans, enter `jms/activation/KIE.SERVER.REQUEST` in the *Target Resource JNDI Name* field, and enter the `jms/cf/KIE.SERVER.REQUEST` JNDI name for the `KIE.SERVER.REQUEST` connection factory.
. In the *Map Virtual Hosts for Web Modules* section, keep the default values and click *Next*.
. Set the context root to `kie-server`.
. In the *Metadata for Modules* section, keep the default values and click *Next*.
. Click *Finish* to install {KIE_SERVER} and click *Save* to save the changes to the primary configuration.
