[id='kie-server-was-mapping-proc_{context}']
= Mapping the {KIE_SERVER} group and role

After {KIE_SERVER} is installed, you must map the `kie-server` role to the `kie-server` group in the WebSphere Integrated Solutions Console to run {KIE_SERVER}.

.Prerequisites
* {KIE_SERVER} is installed on the {WEBSPHERE} instance.
* {WEBSPHERE} has the `kie-server` group with at least one user.
//* All {HEADLESS_CONTROLLER} nodes contain a user with the `kie-server` role.

.Procedure
. In the WebSphere Integrated Solutions Console, navigate to *Applications* -> *Application Types* -> *WebSphere Enterprise Applications* and select the newly installed `kie-server` application.
. Under *Detail Properties*, click *Security Role to User/Group Mapping*.
. Select the `kie-server` role and click *Map Groups* to search for the `kie-server` group.
. Move the `kie-server` group from the *Available* list to the *Selected* list and click *OK*.
+
This mapping gives users in the {WEBSPHERE} `kie-server` group access to {KIE_SERVER}.
+
. Click *Save* to complete the mapping.
