[id='was-jms-queues-create-proc']
= Create JMS queues

JMS queues are the destination end points for point-to-point messaging. You must create certain JMS queues to enable JMS messaging with {KIE_SERVER}.

.Prerequisites
* You have created a service bus for {WEBSPHERE}.

.Procedure
. In the WebSphere Integrated Solutions Console, navigate to *Resources* -> *JMS* -> *Queues*.
. Select the correct scope and click *New*.
. Select the *Default Messaging Provider* option and click *OK*.
. For each of the following required queues, enter the name of the queue (for example, `KIE.SERVER.REQUEST`) and the JNDI name (for example, `jms/KIE.SERVER.REQUEST`), and then select the service bus from the *Bus Name* drop-down list.
. From the *Queue Name* drop-down list, select the *Create Service Integration Bus Destination*, enter a unique identifier, and select the bus member that you created previously.
. Click *Apply* and *Save* to save the changes to the master configuration, and repeat for each required queue.
