[id='was-configure-embedded-engine-proc']
ifdef::PAM[]
= Configuring an embedded {PROCESS_ENGINE} and {DECISION_ENGINE} in {WEBSPHERE}
endif::[]

ifdef::DM[]
= Configuring an embedded {DECISION_ENGINE} in {WEBSPHERE}
endif::[]

ifdef::PAM[]
An embedded engine is a light-weight work flow and rule engine that enables you to execute your decisions and business processes. An embedded engine can be part of a {PRODUCT_PAM} application or it can be deployed as a service through OpenShift, Kubernetes, and Docker. You can embed an engine in a {PRODUCT_PAM} application through the API or as a set of contexts and dependency injection (CDI) services.
endif::[]
ifdef::DM[]
A {DECISION_ENGINE} is a light-weight rule engine that enables you to execute your decisions and business processes. A decision engine can be part of a {PRODUCT_DM} application or it can be deployed as a service through OpenShift, Kubernetes, and Docker. You can embed a {DECISION_ENGINE} in a {PRODUCT_DM} application through the API or as a set of contexts and dependency injection (CDI) services.
endif::[]

ifdef::PAM[]
If you intend to use an embedded engine with your {PRODUCT_PAM} application, you must add Maven dependencies to your project by adding the {PRODUCT_BA} bill of materials (BOM) files to the project’s `pom.xml` file. The {PRODUCT_BA} BOM applies to both {PRODUCT_DM} and {PRODUCT_PAM}. For more information about the {PRODUCT_BA} BOM, see https://access.redhat.com/solutions/3405361[What is the mapping between Red Hat Process Automation Manager and the Maven library version?].
endif::[]
ifdef::DM[]
If you intend to use an embedded engine with your {PRODUCT_DM} application, you must add Maven dependencies to your project by adding the {PRODUCT_BA} bill of materials (BOM) files to the project’s `pom.xml` file. The {PRODUCT_BA} BOM applies to a {PRODUCT_DM}. For more information about the {PRODUCT_BA} BOM, see https://access.redhat.com/solutions/3363991[What is the mapping between Red Hat Decision Manager and the Maven library version?].
endif::[]

.Procedure

. Declare the {PRODUCT_BA} BOM in the `pom.xml` file:
+
====
[source,xml,subs="attributes+"]
----
<dependencyManagement>
 <dependencies>
  <dependency>
   <groupId>com.redhat.ba</groupId>
   <artifactId>ba-platform-bom</artifactId>
   <version>{BOM_VERSION}</version>
   <type>pom</type>
   <scope>import</scope>
  </dependency>
 </dependencies>
</dependencyManagement>
<dependencies>
<!-- Your dependencies -->
</dependencies>
----
====
+
. Declare dependencies required for your project in the `<dependencies>` tag. After you import the product BOM into your project, the versions of the user-facing product dependencies are defined so you do not need to specify the `<version>` sub-element of these `<dependency>` elements. However, you must use the `<dependency>` element to declare dependencies which you want to use in your project.
+
* For a basic {PRODUCT} project, declare the following dependencies, depending on the features that you want to use:
+
ifdef::PAM[]
[id='_embedded_jbpm_engine_dependencies']
.Embedded {PROCESS_ENGINE} dependencies
[source,xml,subs="attributes+"]
----
<!-- Public KIE API -->
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-api</artifactId>
</dependency>

<!-- Core dependencies for {PROCESS_ENGINE} -->
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-flow</artifactId>
</dependency>

<dependency>
  <artifactId>jbpm-flow-builder</artifactId>
</dependency>

<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-bpmn2</artifactId>
</dependency>

<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-runtime-manager</artifactId>
</dependency>

<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-persistence-jpa</artifactId>
</dependency>

<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-query-jpa</artifactId>
</dependency>

<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-audit</artifactId>
</dependency>

<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-kie-services</artifactId>
</dependency>

<!-- Dependency needed for default WorkItemHandler implementations. -->
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-core</artifactId>
</dependency>

<!-- Logging dependency. You can use any logging framework compatible with slf4j. -->
<dependency>
  <groupId>ch.qos.logback</groupId>
  <artifactId>logback-classic</artifactId>
  <version>${logback.version}</version>
</dependency>
----

* For a {PRODUCT} project that uses CDI, you typically declare the following dependencies:
+
[id='_cdi_enabled_jbpm_engine_dependencies']
.CDI-enabled {PROCESS_ENGINE} dependencies
[source,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-api</artifactId>
</dependency>

<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-kie-services</artifactId>
</dependency>

<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-services-cdi</artifactId>
</dependency>
----
endif::[]
+
[id='_embedded_drools_engine_dependencies']
.Embedded {DECISION_ENGINE} dependencies
[source,xml]
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-compiler</artifactId>
</dependency>

<!-- Dependency for persistence support. -->
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-persistence-jpa</artifactId>
</dependency>

<!-- Dependencies for decision tables, templates, and scorecards.
For other assets, declare org.drools:business-central-models-* dependencies. -->
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-decisiontables</artifactId>
</dependency>
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-templates</artifactId>
</dependency>
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-scorecards</artifactId>
</dependency>

<!-- Dependency for loading KJARs from a Maven repository using KieScanner. -->
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-ci</artifactId>
</dependency>

----
+
* To use the {KIE_SERVER}, declare the following dependencies:
+
[id='_client_application_intelligent_process_server_dependencies']
.Client application {KIE_SERVER} dependencies
[source,xml]
----
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-client</artifactId>
</dependency>

----

* To create a remote client for {PRODUCT}, declare the following dependency:
+
.Client dependency
[source,xml]
----
<dependency>
  <groupId>org.uberfire</groupId>
  <artifactId>uberfire-rest-client</artifactId>
</dependency>
----
+
* When creating a JAR file that includes assets, such as rules and process definitions, specify the packaging type for your Maven project as `kjar` and use `org.kie:kie-maven-plugin` to process the `kjar` packaging type located under the `<project>` element. In the following example, `${kie.version}` is the Maven library version listed in
ifdef::PAM[]
https://access.redhat.com/solutions/3405361[What is the mapping between Red Hat Process Automation Manager and the Maven library version?]:
endif::[]
ifdef::DM[]
https://access.redhat.com/solutions/3363991[What is the mapping between Red Hat Decision Manager and the Maven library version?]:
endif::[]
+
[source,xml]
----
<packaging>kjar</packaging>
<build>
 <plugins>
  <plugin>
   <groupId>org.kie</groupId>
   <artifactId>kie-maven-plugin</artifactId>
   <version>${kie.version}</version>
   <extensions>true</extensions>
  </plugin>
 </plugins>
</build>
----

+
ifdef::PAM[]
. If you use a {PROCESS_ENGINE} or {DECISION_ENGINE} with persistence support in your project, you must declare the following hibernate dependencies in the `dependencyManagement` secion of your `pom.xml` file by copying the `version.org.hibernate-4ee7` property from the {PRODUCT_BA} BOM file:
+
[id='hibernate_dependencies_with_process_engine_and_decision_engine']
.Hibernate dependencies
[source,xml]
----
<!-- hibernate dependencies -->
<dependencyManagement>
  <dependencies>
    <dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-entitymanager</artifactId>
    <version>${version.org.hibernate-4ee7}</version>
    </dependency>

    <dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-core</artifactId>
    <version>${version.org.hibernate-4ee7}</version>
    </dependency>
  </dependencies>
</dependencyManagement>
----
endif::[]
+
ifdef::DM[]
. If you use a {DECISION_ENGINE} with persistence support in your project, you must declare the following hibernate dependencies in the `dependencyManagement` secion of your `pom.xml` file by copying the `version.org.hibernate-4ee7` property from the {PRODUCT_BA} BOM file:
+
[id='hibernate_dependencies_with_decision_engine']
.Hibernate dependencies in {DECISION_ENGINE} with persistence
[source,xml]
----
<!-- hibernate dependencies -->
<dependencyManagement>
  <dependencies>
    <dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-entitymanager</artifactId>
    <version>${version.org.hibernate-4ee7}</version>
    </dependency>

    <dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-core</artifactId>
    <version>${version.org.hibernate-4ee7}</version>
    </dependency>
  </dependencies>
</dependencyManagement>
----
endif::[]
