[[ds-artifact-repository-mirrors-section]]
= Artifact Repository Mirrors

// Define required 'bcname' attribute for xpaas_maven_mirror_url.adoc page
:bcname: ds

// Include the Artifact Repository Mirrors section
// (MAVEN_MIRROR_URL variable usage information)
include::../../topics/product-shared-docs/xpaas_maven_mirror_url.adoc[bcname]

= Application Template Parameters

[cols="2*", options="header"]
|===
|Variable
|Description
|*APPLICATION_NAME*
|The name for the application (required).

|*KIE_CONTAINER_DEPLOYMENT*
|The KIE Containers to deploy (required). Example: containerId=groupId:artifactId:version

|*MYSQL_LOWER_CASE_TABLE_NAMES*
|Sets how the table names are stored and compared.

|*AMQ_SECRET*
|The name of a secret containing SSL related files. If no value is specified, a random password is generated.

|*SOURCE_REPOSITORY_URL*
|Git source URI for application.

|*SOURCE_REPOSITORY_REF*
|Git branch/tag reference.

|*CONTEXT_DIR*
|Path within Git project to build; empty for root project directory.

|*KIE_SERVER_USER*
|The user name to access the KIE Server REST or JMS interface.

|*KIE_SERVER_PASSWORD*
|The password to access the KIE Server REST or JMS interface. Must be different than username; must not be root, admin, or administrator; must contain at least 8 characters, 1 alphabetic character(s), 1 digit(s), and 1 non-alphanumeric symbol(s).
|===

[[ds-endpoints]]
= Endpoints

Clients can access {xpaasproduct-shortname} via multiple endpoints; by default the provided templates include support for REST, HornetQ, and ActiveMQ.

[[ds-rest]]
== REST

Clients can use the https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_BRMS/6.3/html-single/User_Guide/index.html#The_REST_API_for_Managing_the_Realtime_Decision_Server[REST API] in various ways:

[[ds-browser]]
=== Browser

. Current server state: \http://host/kie-server/services/rest/server
. List of containers: \http://host/kie-server/services/rest/server/containers
. Specific container state: \http://host/kie-server/services/rest/server/containers/HelloRulesContainer

[[ds-java]]
=== Java

[source,java]
----
// HelloRulesClient.java
KieServicesConfiguration config = KieServicesFactory.newRestConfiguration(
  "http://host/kie-server/services/rest/server", "kieserverUser", "kieserverPassword");
config.setMarshallingFormat(MarshallingFormat.XSTREAM);
RuleServicesClient client =
  KieServicesFactory.newKieServicesClient(config).getServicesClient(RuleServicesClient.class);
ServiceResponse<String> response = client.executeCommands("HelloRulesContainer", myCommands);
----

[[ds-command-line]]
=== Command Line

[source,bash]
----
# request.sh
#!/bin/sh
curl -X POST \
  -d @request.xml \
  -H "Accept:application/xml" \
  -H "X-KIE-ContentType:XSTREAM" \
  -H "Content-Type:application/xml" \
  -H "Authorization:Basic a2llc2VydmVyOmtpZXNlcnZlcjEh" \
  -H "X-KIE-ClassType:org.drools.core.command.runtime.BatchExecutionCommandImpl" \
http://host/kie-server/services/rest/server/containers/instances/HelloRulesContainer
----

[source,xml]
----
<!-- request.xml -->
<batch-execution lookup="HelloRulesSession">
  <insert>
    <org.openshift.quickstarts.decisionserver.hellorules.Person>
      <name>errantepiphany</name>
    </org.openshift.quickstarts.decisionserver.hellorules.Person>
  </insert>
  <fire-all-rules/>
  <query out-identifier="greetings" name="get greeting"/>
</batch-execution>
----

[[ds-jms]]
== JMS

Client can also use the Java Messaging Service, as demonstrated below:

[[ds-java-hornetq]]
=== Java (HornetQ)

[source,java]
----
// HelloRulesClient.java
Properties props = new Properties();
props.setProperty(Context.INITIAL_CONTEXT_FACTORY,
  "org.jboss.naming.remote.client.InitialContextFactory");
props.setProperty(Context.PROVIDER_URL, "remote://host:4447");
props.setProperty(Context.SECURITY_PRINCIPAL, "kieserverUser");
props.setProperty(Context.SECURITY_CREDENTIALS, "kieserverPassword");
InitialContext context = new InitialContext(props);
KieServicesConfiguration config =
  KieServicesFactory.newJMSConfiguration(context, "hornetqUser", "hornetqPassword");
config.setMarshallingFormat(MarshallingFormat.XSTREAM);
RuleServicesClient client =
  KieServicesFactory.newKieServicesClient(config).getServicesClient(RuleServicesClient.class);
ServiceResponse<String> response = client.executeCommands("HelloRulesContainer", myCommands);
----

[[ds-java-activemq]]
=== Java (ActiveMQ)

[source,java]
----
// HelloRulesClient.java
props.setProperty(Context.INITIAL_CONTEXT_FACTORY,
  "org.apache.activemq.jndi.ActiveMQInitialContextFactory");
props.setProperty(Context.PROVIDER_URL, "tcp://host:61616");
props.setProperty(Context.SECURITY_PRINCIPAL, "kieserverUser");
props.setProperty(Context.SECURITY_CREDENTIALS, "kieserverPassword");
InitialContext context = new InitialContext(props);
ConnectionFactory connectionFactory = (ConnectionFactory)context.lookup("ConnectionFactory");
Queue requestQueue = (Queue)context.lookup("dynamicQueues/queue/KIE.SERVER.REQUEST");
Queue responseQueue = (Queue)context.lookup("dynamicQueues/queue/KIE.SERVER.RESPONSE");
KieServicesConfiguration config = KieServicesFactory.newJMSConfiguration(
  connectionFactory, requestQueue, responseQueue, "activemqUser", "activemqPassword");
config.setMarshallingFormat(MarshallingFormat.XSTREAM);
RuleServicesClient client =
  KieServicesFactory.newKieServicesClient(config).getServicesClient(RuleServicesClient.class);
ServiceResponse<String> response = client.executeCommands("HelloRulesContainer", myCommands);
----

[[ds-troubleshooting]]
= Troubleshooting

In addition to viewing the OpenShift logs, you can troubleshoot a running Decision Server xPaaS Image container by viewing its logs.  These are outputted to the container's standard out, and are accessible with the following command:

----
$ oc logs -f <pod_name>
----

[NOTE]
By default, the OpenShift Decision Server xPaaS image does not have a file log handler configured. Logs are only sent to the container's standard out.
