[id='kiebase-mutability-option']

= New `KieBaseMutabilityOption`

By default, a `KieBase` at runtime can be updated dynamically and incrementally with all the running `KieSessions` that are created from that `KieBase`.  However, the running `KieSessions` need additional synchronization points to make the dynamic update possible and consistent. Therefore, a new `KieBaseMutabilityOption` is introduced to optionally disable the possibility of performing an incremental update on a given `KieBase`.

The new `KieBaseMutabilityOption` consists of two values including `ALLOWED` and `DISABLED`.  The default value of `KieBaseMutabilityOption` is `ALLOWED`. However, when an incrementally update of the `KieBase` is not required, then set the value of `KieBaseMutabilityOption` as `DISABLED` to avoid the performance costs caused by the previously mentioned synchronization points. It is possible to set this option either in the `kmodule.xml` file for a specific `KieBase` or using the following system property for all KIE bases.

.Example `kmodule.xml` file
[source,xml]
----
<kbase name="KBase1" mutability="disabled">
----

.System property for KieBaseMutabilityOption
[source,java]
----
drools.kieBaseMutability=disabled
----
