= Streams Support
:imagesdir: ..


Most CEP use cases have to deal with streams of events.
The streams can be provided to the application in various forms, from JMS queues to flat text files, from database tables to raw sockets or even through web service calls.
In any case, the streams share a common set of characteristics:

* events in the stream are ordered by a timestamp. The timestamp may have different semantics for different streams but they are always ordered internally.
* volumes of events are usually high.
* atomic events are rarely useful by themselves. Usually meaning is extracted from the correlation between multiple events from the stream and also from other sources.
* streams may be homogeneous, i.e. contain a single type of events, or heterogeneous, i.e. contain multiple types of events.


Drools generalized the concept of a stream as an "entry point" into the engine.
An entry point is for drools a gate from which facts come.
The facts may be regular facts or special facts like events.

In Drools, facts from one entry point (stream) may join with facts from any other entry point or event with facts from the working memory.
Although, they never mix, i.e., they never lose the reference to the entry point through which they entered the engine.
This is important because one may have the same type of facts coming into the engine through several entry points, but one fact that is inserted into the engine through entry point A will never match a pattern from a entry point B, for example.

include::StreamsSupport/DeclaringAndUsingStreams-section.adoc[leveloffset=+1]

