= Temporal Reasoning
:imagesdir: ..


Temporal reasoning is another requirement of any CEP system.
As discussed previously, one of the distinguishing characteristics of events is their strong temporal relationships.

Temporal reasoning is an extensive field of research, from its roots on Temporal Modal Logic to its more practical applications in business systems.
There are hundreds of papers and thesis written and approaches are described for several applications.
Drools once more takes a pragmatic and simple approach based on several sources, but specially worth noting the following papers:

[bibliography]
- [[[ALLEN81]]] Allen, J.F.. _An Interval-based Representation of Temporal Knowledge_. 1981.
- [[[ALLEN83]]] Allen, J.F.. _Maintaining knowledge about temporal intervals_. 1983.
- [[[BENNE00]]] Bennet, Brandon and Galton, Antony P.. _A Unifying Semantics for Time and Events_. 2005.
- [[[YONEK05]]] Yoneki, Eiko and Bacon, Jean. _Unified Semantics for Event Correlation Over Time and Space in Hybrid Network Environments_. 2005.

Drools implements the Interval-based Time Event Semantics described by Allen, and represents Point-in-Time Events as Interval-based evens with duration 0 (zero).

[NOTE]
====
For all temporal operator intervals, the "*" (star) symbol is used to indicate _positive infinity_ and the "-*" (minus star) is used to indicate __negative infinity__.
====

include::TemporalReasoning/TemporalOperators-section.adoc[leveloffset=+1]

