[[_drools.releasenotesdrools.6.5.0]]
= What is New and Noteworthy in Drools 6.5.0
:imagesdir: ..

== Configurable ThreadFactory


Some runtime environments (like for example Google App Engine) don't allow to directly create new Threads.
For this reason it is now possible to plug your own ThreadFactory implementation by setting the system property **drools.threadFactory** with its class name.
For instance if you implemented your Google App Engine compatible ThreadFactory with the class ``com.user.project.GoogleAppEngineThreadFactory`` you can make Drools to use it by setting:

[source]
----
drools.threadFactory = com.user.project.GoogleAppEngineThreadFactory
----

== Use of any expressions as input for a query


It is now possible to use as input argument for a query both the field of a fact as in:

[source]
----
query contains(String $s, String $c)
    $s := String( this.contains( $c ) )
end

rule PersonNamesWithA when
    $p : Person()
    contains( $p.name, "a"; )
then
end
----

and more in general any kind of valid expression like in:

[source]
----
query checkLength(String $s, int $l)
    $s := String( length == $l )
end

rule CheckPersonNameLength when
    $i : Integer()
    $p : Person()
    checkLength( $p.name, 1 + $i + $p.age; )
then
end
----

== Update with modified properties

Property reactivity has been introduced to avoid unwanted and useless (re)evaluations and allow the engine to react only to
modification of properties actually constrained or bound inside of a given pattern. However this feature is automatically available
only for modifications performed inside the consequence of a rule. Conversely a programmatic update is unaware of the object's
properties that have been changed, so it is unable of using this feature.

To overcome this limitation it is now possible to optionally specify in an update statement the names of the properties that
have been changed in the modified object as in the following example:

[source]
----
Person me = new Person("me", 40);
FactHandle meHandle = ksession.insert( me );

me.setAge(41);
me.setAddress("California Avenue");
ksession.update( meHandle, me, "age", "address" );
----

== Monitoring framework improvements

A new type of MBean has been introduced in order to provide monitoring of the KieContainers, and the JMX MBeans hierarchical structure have been revisited to reflect the relationship with the related MBeans of the KieBases.
The JMX objectnaming has been normalized to reflect the terminology used in the Kie API.
A new type of MBean has been introduced in order to provide monitoring for Stateless KieSession, which was not available in previous releases.

[cols="3", options="header"]
.JMX objectname changes
|===
|MBean
|before `6.5.x`
|from `6.5.0.Final`

|KieContainer
|n/a
|`org.kie:kcontainerId=_{kcontainerId}_`

|KieBase
|`org.drools.kbases:type=_{kbaseId}_`
|`org.kie:kcontainerId=_{kcontainerId}_,kbaseId=_{kbaseId}_`

|KieSession (stateful)
|`org.drools.kbases:type=_{kbaseId}_,group=Sessions,sessionId=_{ksessionId}_`
|`org.kie:kcontainerId=_{kcontainerId}_,kbaseId=_{kbaseId}_,ksessionType=Stateful,ksessionName=_{ksessionName}_`

|Stateless KieSession
|n/a
|`org.kie:kcontainerId=_{kcontainerId}_,kbaseId=_{kbaseId}_,ksessionType=Stateless,ksessionName=_{ksessionName}_`
|===

The KieSession MBeans consolidate the statistics data for all sessions instantiated under the same name.

KieSession created via `JPAKnowledgeService`, will be monitored under a KieSession MBean having constant `{ksessionName}` valorized to `persistent`; this MBean is not managed by the KieContainer directly, hence it requires to be manually deregistered from JMX, when monitoring is no longer needed.

The new JMX objectnaming scheme now enforces proper JMX quoting for IDs, e.g.: `org.kie:kcontainerId="2cb55f40-f220-432a-aba8-7940c18bf108",kbaseId="KBase1"`

The old DroolsManagementAgent (which was registered on JMX under `org.drools:type=DroolsManagementAgent`) is no longer necessary, hence no longer registered on JMX.

The KieSession MBeans now have proper JMX `CompositeData` and `TabularData` support, where applicable. The KieSession MBeans continue to support all process-related aggregated statistics monitoring, but no longer display start/end dates for each process instances: auditing and logging support is available in jBPM for this scope. 

The Drools RHQ/JON plug-in have been changed to reflect all the above mentioned changes, in addition to specific bug-fixing aiming to display hierarchical nesting correctly.
