[[_drools.releasenotesdrools.7.7.0]]

= What is New and Noteworthy in Drools 7.7
:imagesdir: ..

== Executable Model

The purpose of the executable model is to provide a pure Java-based representation of a rule set, together with a convenient
Java DSL to programmatically create such model. The model is low level and designed for the user to provide all the information
it needs, such as the lambda’s for the index evaluation. This keeps it fast and avoids building in too many assumptions at this
level. It is expected higher level representations can layer on in the future, that may be more end-user focused. This work also
highly compliments the unit work, which provides a java-oriented way to provide data and control orchestration.

=== Details

This model is generic enough to be independent from Drools but can be compiled into a plain Drools knowledge base. For this
reason the implementation of the executable model has been split in 2 subprojects:

. *drools-canonical-model* is the canonical representation of a rule set model which is totally independent from Drools
. *drools-model-compiler* compiles the canonical model into Drools internal data structures making it executable by the engine

The introduction of the executable model brings a set of benefits in different areas:

* *Compile time*: in Drools 6 a kjar contained the list of drl files and other Drools artifacts defining the rule base together
with some pre generated classes implementing the constraints and the consequences. Those drl files needed to be parsed and
compiled from scratch, when the kjar is downloaded from the Maven repository and installed in a KieContainer, making this
process quite slow especially for large rules sets. Conversely it is now possible to package inside the kjar the Java classes
implementing the executable model of the project rule base and recreate the KieContainer and its KieBases out of it in a much
faster way. The kie-maven-plugin automatically generates the executable model sources from the drl files during the compilation
process.
* *Runtime*: in the executable model all constraints are defined as Java lambda expressions. The same lambdas are also used
for constraints evaluation and this allows to get rid of both mvel for interpreted evaluation and the jitting process transforming
the mvel-based constraints in bytecode, resulting in a slow warming up process.
* *Future research*: the executable model will allow to experiment new features of the rule engine without the need of encoding
them in the drl format and modify the drl parser to support them.

=== Executable Model DSLs

One goal while designing the first iteration of the DSL for the executable model was to get rid of the notion of pattern and
to consider a rule as a flow of expressions (constraints) and actions (consequences). For this reason we called it Flow DSL.
Some examples of this DSL are available here.

However after having implemented the Flow DSL it became clear that the decision of avoiding the explicit use of patterns
obliged us to implement some extra-logic that had both a complexity and a performance cost, since in order to properly
recreate the data structures expected by the Drools compiler it is necessary to put together the patterns out of those
apparently unrelated expressions.

For this reason it has been decided to reintroduce the patterns in a second DSL that we called Pattern DSL. This allowed
to bypass that algorithm grouping expressions that has to fill an artificial semantic gap and that is also time consuming
at runtime. We believe that both DSLs are valid for different use cases and then we decided to keep and support both. In
particular the Pattern DSL is safer and faster (even if more verbose) so this will be the DSL that will be automatically
generated when creating a kjar through the kie-maven-plugin. Conversely the Flow DSL is more succinct and closer to the
way how an user may want to programmatically define a rule in Java and we planned to make it even less verbose by generating
in an automatic way through a post processor the parts of the model defining the indexing and property reactivity. In other
terms we expect that the Pattern DSL will be written by machines and the Flow DSL eventually by human.

=== Programmatic Build

As evidenced by the test cases linked in the former section it is possible to programmatically define in Java one or more
rules and then add them to a Model with a fluent API

[source]
----
Model model = new ModelImpl().addRule( rule );
----

Once you have this model, which as explained is totally independent from Drools algorithms and data structures, it’s possible
to create a KieBase out of it as it follows

[source]
----
KieBase kieBase = KieBaseBuilder.createKieBaseFromModel( model );
----

Alternatively, it is also possible to create an executable model based kieproject by starting from plain drl files, adding
them to a KieFileSystem as usual

[source]
----
KieServices ks = KieServices.Factory.get();
KieFileSystem kfs = ks.newKieFileSystem()
                      .write( "src/main/resources/r1.drl", createDrl( "R1" ) );
KieBuilder kieBuilder = ks.newKieBuilder( kfs );
----

and then building the project using a new overload of the buildAll() method that accepts a class specifying which kind of
project you want to build

[source]
----
kieBuilder.buildAll( ExecutableModelProject.class );
----

Doing so the KieBuilder will generate the executable model (based on the Pattern DSL) and then the resulting KieSession

[source]
----
KieSession ksession = ks.newKieContainer(ks.getRepository()
                                           .getDefaultReleaseId())
                        .newKieSession();
----

will work with lambda expression based constraint as described in the first section of this document. In the same way it is
also possible to generate the executable model from the Flow DSL by passing a different project class to the KieBuilder

[source]
----
kieBuilder.buildAll( ExecutableModelFlowProject.class );
----

but, for what explained when discussing the 2 different DSLs, it is better to use the pattern-based one for this purpose.

=== Kie Maven Plugin
In order to generate a kjar embedding the executable model using the kie-maven-plugin it is necessary to add the dependencies
related to the two formerly mentioned projects implementing the model and its compiler in the pom.xml file:

[source]
----
<dependencies>
 <dependency>
   <groupId>org.drools</groupId>
   <artifactId>drools-model-compiler</artifactId>
 </dependency>
 <dependency>
   <groupId>org.drools</groupId>
   <artifactId>drools-canonical-model</artifactId>
 </dependency>
</dependencies>
----

also add the plugin to the plugin section

[source]
----
<build>
 <plugins>
   <plugin>
     <groupId>org.kie</groupId>
     <artifactId>kie-maven-plugin</artifactId>
     <version>${project.version}</version>
     <extensions>true</extensions>
   </plugin>
 </plugins>
</build>
----

An example of a pom.xml file already prepared to generate the executable model is available here. By default the kie-maven-plugin
still generates a drl based kjar, so it is necessary to run the plugin with the following argument:

[source]
----
-DgenerateModel=<VALUE>
----

Where <VALUE> can be one of three values:

[source]
----
YES
NO
WITHDRL
----

Both YES and WITHDRL will generate and add to the kjar use the Java classes implementing the executable model corresponding
to the drl files in the original project with difference that the first will exclude the drl files from the generated kjar,
while the second will also add them. However in this second case the drl files will play only a documentation role since the
KieBase will be built from the executable model regardless.