[id='assembly_openshift-operator']

include::_artifacts/document-attributes.adoc[]

= Deploying a {PRODUCT} environment on {OPENSHIFT} using Operators
// Context attribute is assembly specific and enables module reuse between assemblies.
:doctype: book
:imagesdir: _images
:context: openshift-operator
include::_artifacts/author-group.adoc[]

// Purpose statement for the assembly
As a system engineer, you can deploy a {PRODUCT} environment on {OPENSHIFT} to provide an infrastructure to develop or execute processes and other business assets. You can use OpenShift Operators to deploy the environment defined in a structured YAML file and to maintain and modify this environment as necessary.

[NOTE]
====
This functionality is currently for Technology Preview only. For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
====

.Prerequisites

* At least four gigabytes of memory are available in the OpenShift environment.
* The OpenShift Operator Framework is installed and started in the OpenShift environment.
* The OpenShift project for the deployment is created.
* You are logged in to the project using the OpenShift web console. 
* Dynamic persistent volume (PV) provisioning is enabled. Alternatively, if dynamic PV provisioning is not enabled,  enough persistent volumes must be available. By default, the following sizes are required:
ifdef::PAM[]
** Each deployed replicated set of {KIE_SERVER} pods, by default, requires one 1Gi PV for the database. You can change the database PV size. You can deploy multiple immutable servers; each requires a separate database PV. This requirement does not apply if you use an external database server.
endif::PAM[]
** By default, {CENTRAL} requires one 1Gi PV. You can change the PV size for {CENTRAL} persistent storage.
ifdef::PAM[]
** {CENTRAL} Monitoring requires one 64Mi PV.
** Smart Router requires one 64Mi PV.
endif::PAM[]
* If you intend to scale any of the {CENTRAL} 
ifdef::PAM[]
or {CENTRAL} Monitoring
endif::PAM[]
pods, your OpenShift environment supports persistent volumes with `ReadWriteMany` mode.
+
[IMPORTANT]
====
`ReadWriteMany` mode is not supported on OpenShift Online and OpenShift Dedicated.
====

include::{enterprise-dir}/openshift/ba-openshift-overview-con.adoc[leveloffset=+1]
include::{enterprise-dir}/openshift/dm-openshift-prepare-con.adoc[leveloffset=+1]
include::{enterprise-dir}/openshift/registry-authentication-proc.adoc[leveloffset=+2]
:secrettarget: kie
include::{enterprise-dir}/openshift/secrets-secrettarget-create-proc.adoc[leveloffset=+2]
:secrettarget: central
include::{enterprise-dir}/openshift/secrets-secrettarget-create-proc.adoc[leveloffset=+2]
ifdef::PAM[]
:secrettarget: smartrouter
include::{enterprise-dir}/openshift/secrets-secrettarget-create-proc.adoc[leveloffset=+2]
// include::{enterprise-dir}/openshift/externaldb-build-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/glusterfs-reconfig-proc.adoc[leveloffset=+2]
endif::PAM[]
include::{enterprise-dir}/openshift/operator-con.adoc[leveloffset=+1]
include::{enterprise-dir}/openshift/operator-subscribe-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/operator-createapp-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/operator-modify-proc.adoc[leveloffset=+2]
include::{enterprise-dir}/openshift/rolemapping-proc.adoc[leveloffset=+2]


// Versioning info
include::_artifacts/versioning-information.adoc[]
