[id='build-deploy-branches-proc']

= Building and deploying projects
After your project is developed, you can build the project from the specified branch in {CENTRAL} and deploy it to the configured {KIE_SERVER}.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name.
. In the upper-right corner, click *Deploy* to build the project and deploy it to {KIE_SERVER}. If the build fails, address any problems described in the *Alerts* panel at the bottom of the screen. For more information about project deployment options, see {URL_PACKAGING_DEPLOYING_PROJECT}[_{PACKAGING_DEPLOYING_PROJECT}_].

[NOTE]
You can also select the *Build & Install* option to build the project and publish the KJAR file to the configured Maven repository without deploying to a {KIE_SERVER}. This option is equivalent to running `mvn clean install` for your project in the command terminal. In a development environment, you can click *Deploy* to deploy the built KJAR file to a {KIE_SERVER} without aborting any running instances (if applicable), or click *Redeploy* to deploy the built KJAR file and abort any running instances. In a production environment, the *Redeploy* option is disabled and you can click *Deploy* only to deploy the built KJAR file to a new deployment unit (KIE container) on a {KIE_SERVER}.

To enable development mode in {CENTRAL}, go to project *Settings* -> *General Settings* -> *Version* and toggle the *Development Mode* option. Do not use *Development Mode* or manually add the `SNAPSHOT` version suffix for a production environment.

To review project deployment details (if applicable), go to *Menu* -> *Deploy* -> *Execution Servers*.
