[id='preview-editor-layout-con']
= Test Scenarios (Preview) editor layout

The preview editor introduces a tabular layout which will guide you in defining a scenario template and all the associated test cases. The editor’s layout consists of a table which has a header and the individual rows. The header is also known as test scenario template and the individual rows are called test scenarios definitions.

The test scenario template or header has the following two parts:
* *Given* data object field(s) - represents the input information
* *Expected* data object field(s) - represents the information whose values are checked based on the given information and which also constitutes the expected result.

The test scenarios definitions represent the separate test cases of a template.

You can access the *Project Explorer* from the left panel of the editor whereas from the right panel you can access the *Test Tools* and the *Test Report*. You can use the test tools to configure the data object mappings (*Test Editor*) or for accessing the cheat sheet (*Scenario Cheatsheet*) that contain notes which you can use as reference.
