[id='project-build-deploy-maven-proc_{context}']
= Packaging and deploying a {PRODUCT} project in Maven

If you want to deploy a Maven project outside of {CENTRAL} to a configured {KIE_SERVER}, you can edit the project `pom.xml` file to package your project as a KJAR file and add a `kmodule.xml` file with the KIE base and KIE session configurations for the assets in your project.

.Prerequisites
* You have a Mavenized project that contains {PRODUCT} business assets.
* {KIE_SERVER} is installed and `kie-server` user access is configured. For installation options, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].

.Procedure
. In the `pom.xml` file of your Maven project, set the packaging type to `kjar` and add the `kie-maven-plugin` build component:
+
--
[source,xml,subs="attributes+"]
----
<packaging>kjar</packaging>
...
<build>
  <plugins>
    <plugin>
      <groupId>org.kie</groupId>
      <artifactId>kie-maven-plugin</artifactId>
      <version>${{PRODUCT_INIT}.version}</version>
      <extensions>true</extensions>
    </plugin>
  </plugins>
</build>
----

The `kjar` packaging type activates the `kie-maven-plugin` component to validate and pre-compile artifact resources. The `<version>` is the Maven artifact version for {PRODUCT} currently used in your project (for example, {MAVEN_ARTIFACT_VERSION}). These settings are required to properly package the Maven project for deployment.

ifdef::DM,PAM[]
[NOTE]
====
Instead of specifying a {PRODUCT} `<version>` for individual dependencies, consider adding the {PRODUCT_BA} bill of materials (BOM) dependency to your project `pom.xml` file. The {PRODUCT_BA} BOM applies to both {PRODUCT_DM} and {PRODUCT_PAM}. When you add the BOM files, the correct versions of transitive dependencies from the provided Maven repositories are included in the project.

Example BOM dependency:

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>com.redhat.ba</groupId>
  <artifactId>ba-platform-bom</artifactId>
  <version>{BOM_VERSION}</version>
  <scope>import</scope>
  <type>pom</type>
</dependency>
----

For more information about the {PRODUCT_BA} BOM, see
ifdef::PAM[]
https://access.redhat.com/solutions/3405361[What is the mapping between Red Hat Process Automation Manager and the Maven library version?].
endif::[]
ifdef::DM[]
https://access.redhat.com/solutions/3363991[What is the mapping between Red Hat Decision Manager and the Maven library version?].
endif::[]
====
endif::DM,PAM[]
--
. Add the following dependencies to the `pom.xml` file to generate an executable rule model from your rule assets:
+
--
* `drools-canonical-model`: Enables an executable canonical representation of a rule set model that is independent from {PRODUCT}
* `drools-model-compiler`: Compiles the executable model into {PRODUCT} internal data structures so that it can be executed by the {DECISION_ENGINE}

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-canonical-model</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>

<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-model-compiler</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
----

Executable rule models are embeddable models that provide a Java-based representation of a rule set for execution at build time. The executable model is a more efficient alternative to the standard asset packaging in {PRODUCT} and enables KIE containers and KIE bases to be created more quickly, especially when you have large lists of DRL (Drools Rule Language) files and other {PRODUCT} assets.

For more information about executable rule models, see {URL_DRL_RULES}#executable-model-con_drl-rules[_{DRL_RULES}_].

To enable Decision Model and Notation (DMN) executable models for DMN assets in your project (if applicable), also add the `kie-dmn-core` dependency in the `pom.xml` file:

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-dmn-core</artifactId>
  <scope>provided</scope>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
----
--
. In the `~/resources` directory of your Maven project, create a `META-INF/kmodule.xml` metadata file with at least the following content:
+
--
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<kmodule xmlns="http://www.drools.org/xsd/kmodule">
</kmodule>
----

This `kmodule.xml` file is a KIE module descriptor that is required for all {PRODUCT} projects. You can use the KIE module to define one or more KIE bases and one or more KIE sessions from each KIE base.

For more information about `kmodule.xml` configuration, see xref:project-kmodule-configure-proc_packaging-deploying[].
--
. In the relevant resource in your Maven project, configure a `.java` class to create a KIE container and a KIE session to load the KIE base:
+
--
[source,java]
----
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;

public void testApp() {

  // Load the KIE base:
  KieServices ks = KieServices.Factory.get();
  KieContainer kContainer = ks.getKieClasspathContainer();
  KieSession kSession = kContainer.newKieSession();

}
----

In this example, the KIE container reads the files to be built from the class path for a `testApp` project. The `KieServices` API enables you to access all KIE building and runtime configurations.

You can also create the KIE container by passing the project `ReleaseId` to the `KieServices` API. The `ReleaseId` is generated from the `GroupId`, `ArtifactId`, and `Version` (GAV) values in the project `pom.xml` file.

[source,java]
----
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;

public void testApp() {

  // Identify the project in the local repository:
  ReleaseId rid = new ReleaseId();
  rid.setGroupId("com.sample");
  rid.setArtifactId("my-app");
  rid.setVersion("1.0.0");

  // Load the KIE base:
  KieServices ks = KieServices.Factory.get();
  KieContainer kContainer = ks.newKieContainer(rid);
  KieSession kSession = kContainer.newKieSession();

}
----
--
. In a command terminal, navigate to your Maven project directory and run the following command to build the project from an executable model:
+
--
[source]
----
mvn clean install -DgenerateModel=<VALUE>
----

The `-DgenerateModel=<VALUE>` property enables the project to be built as a model-based KJAR instead of a DRL-based KJAR, so that rule assets are built in an executable rule model.

Replace `<VALUE>` with one of three values:

* `YES`: Generates the executable model corresponding to the DRL files in the original project and excludes the DRL files from the generated KJAR.
* `WITHDRL`: Generates the executable model corresponding to the DRL files in the original project and also adds the DRL files to the generated KJAR for documentation purposes (the KIE base is built from the executable model regardless).
* `NO`: Does not generate the executable model.

Example build command:

[source]
----
mvn clean install -DgenerateModel=YES
----

For DMN executable models, run the following command:

[source]
----
mvn clean install -DgenerateDMNModel=YES
----

If the build fails, address any problems described in the command line error messages and try again to validate the files until the build is successful.
--
. After you successfully build and test the project locally, deploy the project to the remote Maven repository:
+
[source]
----
mvn deploy
----
