[id='project-duplicate-GAV-manage-proc_{context}']
= Managing duplicate GAV detection settings in {CENTRAL}

{CENTRAL} users with the `admin` role can modify the list of repositories that are checked for duplicate `GroupId`, `ArtifactId`, and `Version` (GAV) values for a project.

NOTE: Duplicate GAV detection is disabled for projects in *Development Mode*. To enable duplicate GAV detection in {CENTRAL}, go to project *Settings* -> *General Settings* -> *Version* and toggle the *Development Mode* option to *OFF* (if applicable).

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name.
. Click the project *Settings* tab and then click *Validation* to open the list of repositories.
. Select or clear any of the listed repository options to enable or disable duplicate GAV detection.
+
In the future, duplicate GAVs will be reported for only the repositories you have enabled for validation.
+
[NOTE]
====
To disable this feature, set the `org.guvnor.project.gav.check.disabled` system property to `true` for {CENTRAL} at system startup:

[source]
----
$ ~/EAP_HOME/bin/standalone.sh -c standalone-full.xml
-Dorg.guvnor.project.gav.check.disabled=true
----
====
