[id='project-build-deploy-central-proc_{context}']
= Building and deploying a project in {CENTRAL}

After your project is developed, you can build the project in {CENTRAL} and deploy it to the configured {KIE_SERVER}. Projects in {CENTRAL} are packaged automatically as KJARs with all necessary components when you build and deploy the projects.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name.
. In the upper-right corner, click *Deploy* to compile the project and deploy it to a {KIE_SERVER}. To compile the project without deploying it to {KIE_SERVER}, click *Build*.
+
[NOTE]
====
For development purposes, you can select the *Build and Install* option to compile the project and publish the KJAR file to the configured Maven repository without deploying to a {KIE_SERVER}. This option is equivalent to running `mvn clean install` for your project in the command terminal. You can also click *Deploy* to deploy the compiled KJAR file to a {KIE_SERVER} without aborting any running instances (if applicable), or click *Redeploy* to deploy the compiled KJAR file and abort any running instances.

To enable development mode in {CENTRAL}, go to project *Settings* -> *General Settings* -> *Version* and toggle the *Development Mode* option. Do not use *Development Mode* or manually add the `SNAPSHOT` version suffix for a production environment.
====
+
If only one {KIE_SERVER} is connected to {CENTRAL}, or if all connected {KIE_SERVERS} are in the same server configuration, the services in the project are started automatically in a deployment unit (KIE container).
+
If multiple server configurations are available, a deployment dialog is displayed in {CENTRAL}, prompting you to specify server and deployment details.
+
. If the deployment dialog appears, verify or set the following values:
* *Deployment Unit Id / Deployment Unit Alias:* Verify the name and alias of the deployment unit (KIE container) running the service within the {KIE_SERVER}. You normally do not need to change these settings.
* *Server Configuration:* Select the server configuration for deploying this project. You can later deploy it to other configured servers without rebuilding the project.
* *Start Deployment Unit?:* Verify that this box is selected to start the deployment unit (KIE container). If you clear this box, the service is deployed onto the server but not started.
