[id='project-build-deploy-central-proc_{context}']
= Building and deploying a project in {CENTRAL}

After your project is developed, you can build the project in {CENTRAL} and deploy it to the configured {KIE_SERVER}. Projects in {CENTRAL} are packaged automatically as KJARs with all necessary components when you build and deploy the projects.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name.
. In the upper-right corner, click *Deploy* to build the project and deploy it to a {KIE_SERVER}. To compile the project without deploying it to {KIE_SERVER}, click *Build*.
+
[NOTE]
====
You can also select the *Build & Install* option to build the project and publish the KJAR file to the configured Maven repository without deploying to a {KIE_SERVER}. In a development environment, you can click *Deploy* to deploy the built KJAR file to a {KIE_SERVER} without stopping any running instances (if applicable), or click *Redeploy* to deploy the built KJAR file and stop any running instances. The next time you deploy or redeploy the built KJAR, the previous deployment unit (KIE container) is automatically updated in the same target {KIE_SERVER}. In a production environment, the *Redeploy* option is disabled and you can click *Deploy* only to deploy the built KJAR file to a new deployment unit (KIE container) on a {KIE_SERVER}.

To configure the {KIE_SERVER} environment mode, set the `org.kie.server.mode` system property to `org.kie.server.mode=development` or `org.kie.server.mode=production`. To configure the deployment behavior for a corresponding project in {CENTRAL}, go to project *Settings* -> *General Settings* -> *Version* and toggle the *Development Mode* option. By default, {KIE_SERVER} and all new projects in {CENTRAL} are in development mode. You cannot deploy a project with *Development Mode* turned on or with a manually added `SNAPSHOT` version suffix to a {KIE_SERVER} that is in production mode.
====
+
If only one {KIE_SERVER} is connected to {CENTRAL}, or if all connected {KIE_SERVERS} are in the same server configuration, the services in the project are started automatically in a deployment unit (KIE container).
+
If multiple server configurations are available, a deployment dialog is displayed in {CENTRAL}, prompting you to specify server and deployment details.
+
. If the deployment dialog appears, verify or set the following values:
* *Deployment Unit Id / Deployment Unit Alias:* Verify the name and alias of the deployment unit (KIE container) running the service within the {KIE_SERVER}. You normally do not need to change these settings.
* *Server Configuration:* Select the server configuration for deploying this project. You can later deploy it to other configured servers without rebuilding the project.
* *Start Deployment Unit?:* Verify that this box is selected to start the deployment unit (KIE container). If you clear this box, the service is deployed onto the server but not started.
