[id='project-kmodule-properties-ref_{context}']
= KIE module configuration properties

The optional `<configuration>` element in the KIE module descriptor file (`kmodule.xml`) of your project defines property `key` and `value` pairs that you can use to further customize your `kmodule.xml` file.

.Example configuration property in a `kmodule.xml` file
[source,xml]
----
<kmodule>
  ...
  <configuration>
    <property key="drools.dialect.default" value="java"/>
    ...
  </configuration>
  ...
</kmodule>
----

The following are the `<configuration>` property keys and values supported in the KIE module descriptor file (`kmodule.xml`) for your project:

drools.dialect.default::
Sets the default Drools dialect.
+
--
Supported values: `java`, `mvel`

[source,xml]
----
<property key="drools.dialect.default"
  value="java"/>
----
--

drools.accumulate.function.$FUNCTION::
Links a class that implements an accumulate function to a specified function name, which allows you to add custom accumulate functions into the {DECISION_ENGINE}.
+
--
[source,xml]
----
<property key="drools.accumulate.function.hyperMax"
  value="org.drools.custom.HyperMaxAccumulate"/>
----
--

drools.evaluator.$EVALUATION::
Links a class that implements an evaluator definition to a specified evaluator name so that you can add custom evaluators into the {DECISION_ENGINE}. An evaluator is similar to a custom operator.
+
--
[source,xml]
----
<property key="drools.evaluator.soundslike"
  value="org.drools.core.base.evaluators.SoundslikeEvaluatorsDefinition"/>
----
--

drools.dump.dir::
Sets a path to the {PRODUCT} `dump/log` directory.
+
--
[source,xml]
----
<property key="drools.dump.dir"
  value="$DIR_PATH/dump/log"/>
----
--

drools.defaultPackageName::
Sets a default package for the business assets in your project.
+
--
[source,xml]
----
<property key="drools.defaultPackageName"
  value="org.domain.pkg1"/>
----
--

drools.parser.processStringEscapes::
Sets the String escape function. If this property is set to `false`, the `\n` character will not be interpreted as the newline character.
+
--
Supported values: `true` (default), `false`

[source,xml]
----
<property key="drools.parser.processStringEscapes"
  value="true"/>
----
--

drools.kbuilder.severity.$DUPLICATE::
Sets a severity for instances of duplicate rules, processes, or functions reported when a KIE base is built. For example, if you set `duplicateRule` to `ERROR`, then an error is generated for any duplicated rules detected when the KIE base is built.
+
--
Supported key suffixes: `duplicateRule`, `duplicateProcess`, `duplicateFunction`

Supported values: `INFO`, `WARNING`, `ERROR`

[source,xml]
----
<property key="drools.kbuilder.severity.duplicateRule"
  value="ERROR"/>
----
--

drools.propertySpecific::
Sets the property reactivity of the {DECISION_ENGINE}.
+
--
Supported values: `DISABLED`, `ALLOWED`, `ALWAYS`

[source,xml]
----
<property key="drools.propertySpecific"
  value="ALLOWED"/>
----
--

drools.lang.level::
Sets the DRL language level.
+
--
Supported values: `DRL5`, `DRL6`, `DRL6_STRICT` (default)

[source,xml]
----
<property key="drools.lang.level"
  value="DRL_STRICT"/>
----
--









////
drools.dialect.default::
Sets the default Drools dialect.
+
[cols="20%,80%", options="header"]
|===
| Supported values
| Example

|`java`, `mvel`
a|
[source,xml]
----
<property key="drools.dialect.default"
  value="java"/>
----
|===

drools.accumulate.function.$FUNCTION::
Links a class that implements an accumulate function to a specified function name, which allows you to add custom accumulate functions into the {DECISION_ENGINE}.
+
[cols="20%,80%", options="header"]
|===
| Supported values
| Example

| Any accumulate function name
a|
[source,xml]
----
<property key="drools.accumulate.function.hyperMax"
  value="org.drools.custom.HyperMaxAccumulate"/>
----
|===

drools.evaluator.$EVALUATION::
Links a class that implements an evaluator definition to a specified evaluator name so that you can add custom evaluators into the {DECISION_ENGINE}. An evaluator is similar to a custom operator.

+
[cols="20%,80%", options="header"]
|===
| Supported values
| Example

| Any evaluator definition name
a|
[source,xml]
----
<property key="drools.evaluator.soundslike"
  value="org.drools.core.base.evaluators.SoundslikeEvaluatorsDefinition"/>
----
|===

drools.dump.dir::
Sets a path to the {PRODUCT} `dump/log` directory.
+
[cols="20%,80%", options="header"]
|===
| Supported values
| Example

| Desired path to `dump/log` directory
a|
[source,xml]
----
<property key="drools.dump.dir"
  value="$DIR_PATH/dump/log"/>
----
|===

drools.defaultPackageName::
Sets a default package for business assets.
+
[cols="20%,80%", options="header"]
|===
| Supported values
| Example

| Desired package name
a|
[source,xml]
----
<property key="drools.defaultPackageName"
  value="org.domain.pkg1"/>
----
|===

drools.parser.processStringEscapes::
Sets the String escape function. If this property is set to `false`, the `\n` character will not be interpreted as the newline character.
+
[cols="20%,80%", options="header"]
|===
| Supported values
| Example

a| `true`, `false`
Default: `true`
a|
[source,xml]
----
<property key="drools.parser.processStringEscapes"
  value="true"/>
----
|===

drools.kbuilder.severity.$SEVERITY::
Sets a severity for duplicate rules, processes, or functions reported when a KIE base is built. For example, if you set `duplicateRule` to `ERROR`, then an error is generated for any duplicated rules detected when the KIE base is built.
+
[cols="20%,20%, 60%", options="header"]
|===
| Supported keys
| Supported values
| Example

| `duplicateRule`, `duplicateProcess`, and `duplicateFunction`
a| `INFO`, `WARNING`, `ERROR`
Default: `INFO`
a|
[source,xml]
----
<property key="drools.kbuilder.severity.duplicateRule"
  value="ERROR"/>
----
|===

drools.propertySpecific::
Sets the property reactivity of the {DECISION_ENGINE}. Possible values are `DISABLED`, `ALLOWED`, and `ALWAYS`.
+
[cols="20%,80%", options="header"]
|===
| Supported values
| Example

| `DISABLED`, `ALLOWED`, `ALWAYS`
a|
[source,xml]
----
<property key="drools.propertySpecific"
  value="ALLOWED"/>
----
|===

drools.lang.level::
Sets the DRL language level.
+
[cols="20%,80%", options="header"]
|===
| Supported values
| Example

a| `DRL5`, `DRL6`, `DRL6_STRICT`
Default: `DRL6_STRICT`
a|
[source,xml]
----
<property key="drools.lang.level"
  value="DRL_STRICT"/>
----
|===
////
