[id='project-kmodule-configure-proc_{context}']
= Configuring a KIE module descriptor file

A KIE module is a Maven project or module with an additional metadata file `META-INF/kmodule.xml`. All {PRODUCT} projects require a `kmodule.xml` file in order to be properly packaged and deployed. This `kmodule.xml` file is a KIE module descriptor that defines the KIE base and KIE session configurations for the assets in a project. A KIE base is a repository that contains all
ifdef::DM[]
rules and other business assets
endif::DM[]
ifdef::PAM[]
rules, processes, and other business assets
endif::PAM[]
in {PRODUCT} but does not contain any runtime data. A KIE session stores and executes runtime data and is created from a KIE base or directly from a KIE container if you have defined the KIE session in the `kmodule.xml` file.

If you create projects outside of {CENTRAL}, such as independent Maven projects or projects within a Java application, you must configure the KIE module descriptor settings in an appended `kmodule.xml` file or directly in your Java application in order to build and deploy the projects.

.Procedure
. In the `~/resources/META-INF` directory of your project, create a `kmodule.xml` metadata file with at least the following content:
+
--
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<kmodule xmlns="http://www.drools.org/xsd/kmodule">
</kmodule>
----

This empty `kmodule.xml` file is sufficient to produce a single default KIE base that includes all files found under your project `resources` path. The default KIE base also includes a single default KIE session that is triggered when you create a KIE container in your application at build time.

The following example is a more advanced `kmodule.xml` file:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<kmodule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.drools.org/xsd/kmodule">
  <configuration>
      <property key="drools.evaluator.supersetOf" value="org.mycompany.SupersetOfEvaluatorDefinition"/>
  </configuration>
  <kbase name="KBase1" default="true" eventProcessingMode="cloud" equalsBehavior="equality" declarativeAgenda="enabled" packages="org.domain.pkg1">
    <ksession name="KSession1_1" type="stateful" default="true" />
    <ksession name="KSession1_2" type="stateful" default="true" beliefSystem="jtms" />
  </kbase>
  <kbase name="KBase2" default="false" eventProcessingMode="stream" equalsBehavior="equality" declarativeAgenda="enabled" packages="org.domain.pkg2, org.domain.pkg3" includes="KBase1">
    <ksession name="KSession2_1" type="stateless" default="true" clockType="realtime">
      <fileLogger file="debugInfo" threaded="true" interval="10" />
      <workItemHandlers>
        <workItemHandler name="name" type="new org.domain.WorkItemHandler()" />
      </workItemHandlers>
      <listeners>
        <ruleRuntimeEventListener type="org.domain.RuleRuntimeListener" />
        <agendaEventListener type="org.domain.FirstAgendaListener" />
        <agendaEventListener type="org.domain.SecondAgendaListener" />
        <processEventListener type="org.domain.ProcessListener" />
      </listeners>
    </ksession>
  </kbase>
</kmodule>
----

This example defines two KIE bases. Specific `packages` of rule assets are included with both KIE bases. When you specify packages in this way, you must organize your rule files in a folder structure that reflects the specified packages. Two KIE sessions are instantiated from the `KBase1` KIE base, and one KIE session from `KBase2`. The KIE session from `KBase2` is a `stateless` KIE session, which means that data from a previous invocation of the KIE session (the previous session state) is discarded between session invocations. That KIE session also specifies a file (or a console) logger, a `WorkItemHandler`, and listeners of the three supported types shown: `ruleRuntimeEventListener`, `agendaEventListener` and `processEventListener`. The `<configuration>` element defines optional properties that you can use to further customize your `kmodule.xml` file.

As an alternative to manually appending a `kmodule.xml` file to your project, you can use a `KieModuleModel` instance within your Java application to programatically create a `kmodule.xml` file that defines the KIE base and a KIE session, and then add all resources in your project to the KIE virtual file system `KieFileSystem`.

.Creating `kmodule.xml` programmatically and adding it to `KieFileSystem`
[source,java]
----
import org.kie.api.KieServices;
import org.kie.api.builder.model.KieModuleModel;
import org.kie.api.builder.model.KieBaseModel;
import org.kie.api.builder.model.KieSessionModel;
import org.kie.api.builder.KieFileSystem;

KieServices kieServices = KieServices.Factory.get();
KieModuleModel kieModuleModel = kieServices.newKieModuleModel();

KieBaseModel kieBaseModel1 = kieModuleModel.newKieBaseModel("KBase1")
  .setDefault(true)
  .setEqualsBehavior(EqualityBehaviorOption.EQUALITY)
  .setEventProcessingMode(EventProcessingOption.STREAM);

KieSessionModel ksessionModel1 = kieBaseModel1.newKieSessionModel("KSession1_1")
  .setDefault(true)
  .setType(KieSessionModel.KieSessionType.STATEFUL)
  .setClockType(ClockTypeOption.get("realtime"));

KieFileSystem kfs = kieServices.newKieFileSystem();
kfs.writeKModuleXML(kieModuleModel.toXML());
----
--
. After you configure the `kmodule.xml` file either manually or programmatically in your project, retrieve the KIE bases and KIE sessions from the KIE container to verify the configurations:
+
--
[source,java]
----
KieServices kieServices = KieServices.Factory.get();
KieContainer kContainer = kieServices.getKieClasspathContainer();

KieBase kBase1 = kContainer.getKieBase("KBase1");
KieSession kieSession1 = kContainer.newKieSession("KSession1_1"),
    kieSession2 = kContainer.newKieSession("KSession1_2");

KieBase kBase2 = kContainer.getKieBase("KBase2");
StatelessKieSession kieSession3 = kContainer.newStatelessKieSession("KSession2_1");
----

If `KieBase` or `KieSession` have been configured as `default="true"` in the `kmodule.xml` file, as in the previous `kmodule.xml` example, you can retrieve them from the KIE container without passing any names:

[source,java]
----
KieContainer kContainer = ...

KieBase kBase1 = kContainer.getKieBase();
KieSession kieSession1 = kContainer.newKieSession(),
    kieSession2 = kContainer.newKieSession();

KieBase kBase2 = kContainer.getKieBase();
StatelessKieSession kieSession3 = kContainer.newStatelessKieSession();
----

To increase or decrease the maximum number of KIE modules or artifact versions that are cached in the {DECISION_ENGINE}, you can modify the values of the following system properties in your {PRODUCT} distribution:

* `kie.repository.project.cache.size`: Maximum number of KIE modules that are cached in the {DECISION_ENGINE}. Default value: `100`
* `kie.repository.project.versions.cache.size`: Maximum number of versions of the same artifact that are cached in the {DECISION_ENGINE}. Default value: `10`

For the full list of KIE repository configurations,
ifdef::DM,PAM[]
download the *{PRODUCT} [VERSION] Source Distribution* ZIP file from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Red Hat Customer Portal] and navigate to `~/{PRODUCT_FILE}-sources/src/drools-$VERSION/drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/KieRepositoryImpl.java`.
endif::[]
ifdef::DROOLS,JBPM,OP[]
see the {PRODUCT} https://github.com/kiegroup/drools/blob/master/drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/KieRepositoryImpl.java[KieRepositoryImpl.java] page on GitHub.
endif::[]
--

For more information about the `kmodule.xml` file, download the *{PRODUCT} [VERSION] Source Distribution* ZIP file from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Red Hat Customer Portal] (if not downloaded already) and see the `kmodule.xsd` XML schema located at `$FILE_HOME/{PRODUCT_INIT}-$VERSION-sources/kie-api-parent-$VERSION/kie-api/src/main/resources/org/kie/api/`.

ifdef::DM[]
[NOTE]
====
`KieBase` or `KiePackage` serialization is not supported in {PRODUCT} {PRODUCT_VERSION}. For more information, see https://access.redhat.com/solutions/3216951[Is serialization of kbase/package supported in BRMS 6/BPM Suite 6/RHDM 7?].
====
endif::[]
