[id='assembly-kogito-release-notes']
include::_artifacts/document-attributes.adoc[]

= Release notes for {PRODUCT} {PRODUCT_VERSION}
// Context attribute is assembly specific and enables module reuse between assemblies.
:doctype: book
:imagesdir: _images
:context: kogito-release-notes
include::_artifacts/author-group.adoc[]

// Purpose statement for the assembly
These release notes highlight some of the new features, fixed issues, and known issues in {PRODUCT} {PRODUCT_VERSION}. These release notes are not comprehensive. For the complete list of new features, fixed issues, and known issues in {PRODUCT} {PRODUCT_VERSION}, see the release notes page in https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12322421&version=12345302[Atlassian Jira].

[IMPORTANT]
====
{PRODUCT} is currently available for Development Preview. Development Preview releases contain features and APIs that might not be fully tested and that might change in the final GA version. Users are discouraged from using Development Preview software in production or for business-critical workloads.  Because this is not production-ready software, users are not able to open support tickets. To learn more about {PRODUCT}, please contact your Red Hat representative or send an email to Kogito-earlyaccess@redhat.com. Red Hat will address reported issues at its own discretion.
====

include::{kogito-dir}/creating-running/con-kogito-automation.adoc[leveloffset=+1]
include::{kogito-dir}/release-notes/ref-kogito-rn-key-features.adoc[leveloffset=+1]
//@comment: The following sections to be used soon. (Stetson, 27 Apr 2020)
include::{kogito-dir}/release-notes/0.11.0/ref-kogito-rn-new-features.adoc[leveloffset=+1]
include::{kogito-dir}/release-notes/0.11.0/ref-kogito-rn-fixed-issues.adoc[leveloffset=+1]
include::{kogito-dir}/release-notes/0.11.0/ref-kogito-rn-known-issues.adoc[leveloffset=+1]

== Additional resources
* {URL_CREATING_RUNNING}[_{CREATING_RUNNING}_]
* {URL_DEPLOYING_ON_OPENSHIFT}[_{DEPLOYING_ON_OPENSHIFT}_]
* {URL_DECISION_SERVICES}[_{DECISION_SERVICES}_]
* {URL_PROCESS_SERVICES}[_{PROCESS_SERVICES}_]
* {URL_CONFIGURING_KOGITO}[_{CONFIGURING_KOGITO}_]

// Versioning info
include::_artifacts/versioning-information.adoc[]
