[id='configure-min-inflate-rate']

= New `drools.excelParser.minInflateRatio` property for decision tables parser

The Apache POI project, which the {DECISION_ENGINE} uses to parse decision tables, introduced a security enhancement that limits the ratio between the compressed and uncompressed size of a spreadsheet to 0.01. The purpose of this enhancement is to block all maliciously formatted documents that, when uncompressed, could result in excessive memory usage while still allowing to process almost all valid documents.

For certain decision tables, this limit could be too strict and could prevent the parsing of valid spreadsheets. Therefore, {PRODUCT} now provides a new system property `drools.excelParser.minInflateRatio` that you can configure to lower this limit and allow the parsing of such decision tables.

For more information about spreadsheet decision tables in {PRODUCT}, see
ifdef::DM,PAM[]
{URL_DEVELOPING_DECISION_SERVICES}#assembly-decision-tables[_{DECISION_ENGINE_DOC}_].
endif::[]
ifdef::DROOLS,JBPM,OP[]
xref:decision-tables-con_decision-tables[].
endif::[]
