[id='ref-kogito-rn-new-features_{context}']
= New features in {PRODUCT} {PRODUCT_VERSION}

The following sections describe some of the new features or enhancements in {PRODUCT} {PRODUCT_VERSION}.

== {PRODUCT} runtimes

ifdef::KOGITO-COMM[]
=== Improved GraphQL security in the {PRODUCT} Data Index Service

When you enable security in the {PRODUCT} Data Index Service, you can now also configure the GraphQL interface endpoint and authentication requirements. The Data Index Service also now uses multi-tenant configuration to support `web-app` and `service` application types at the same time in different endpoints.

For more information about enabling security in the {PRODUCT} Data Index, see xref:proc-data-index-service-security_kogito-configuring[].

//@comment: Link for enterprise if/when needed: {URL_CONFIGURING_KOGITO}#proc-data-index-service-security_kogito-configuring[_{CONFIGURING_KOGITO}_]  (Stetson, 30 June 2020)
endif::[]

Description

== {PRODUCT} Operator and CLI

=== New Custom Resource (CR) "KogitoBuild"

Now it's possible to have build and deployment of a custom Kogito service doing separately within the Operator. This way one can elect which type of build its needed: binary, source to image or from file (DMN, BPMN or DRL). Please see https://github.com/kiegroup/kogito-cloud-operator/blob/master/examples/process-quarkus-example-runtime-build.yaml[this example] for more information of how to link builds with service deployment on OpenShift.

== Integration with Kubernetes Event API

Now when a Kubernetes resource is deployed, users can see in the Events console additional information about created resources without having to rely on the Operator pod's log. In the future we intend to improve this integration by providing more meaningful information about the operator controlled resources.

== {PRODUCT} supporting services

=== Improved/new bla bla

Description

== {PRODUCT} tooling

=== DMN included models in the {PRODUCT} DMN modeler in VSCode

The {PRODUCT} Decision Model and Notation (DMN) modeler in VSCode contains a new *Included Models* tab that you can use to include other DMN models from your project in a specified DMN file. When you include a DMN model within another DMN file, you can reuse the decision requirements diagram (DRD) nodes and logic of the included model in that DMN file. This enhancement helps you more efficiently integrate DMN logic between different DMN models in your project.

For more information about DMN included models in {PRODUCT}, see
ifdef::KOGITO[]
{URL_DECISION_SERVICES}#proc-dmn-included-models-dmn_dmn-models[_{DECISION_SERVICES}_].
endif::[]
ifdef::KOGITO-COMM[]
xref:proc-dmn-included-models-dmn_dmn-models[].
endif::[]

=== Improved/new bla bla

Description
