[id='ref-kogito-rn-new-features_{context}']
= New features in {PRODUCT} {PRODUCT_VERSION}

The following sections describe some of the new features or enhancements in {PRODUCT} {PRODUCT_VERSION}.

== {PRODUCT} runtimes

ifdef::KOGITO-COMM[]
=== Improved GraphQL security in the {PRODUCT} Data Index Service

When you enable security in the {PRODUCT} Data Index Service, you can now also configure the GraphQL interface endpoint and authentication requirements. The Data Index Service also now uses multi-tenant configuration to support `web-app` and `service` application types at the same time in different endpoints.

For more information about enabling security in the {PRODUCT} Data Index, see xref:proc-data-index-service-security_kogito-configuring[].

//@comment: Link for enterprise if/when needed: {URL_CONFIGURING_KOGITO}#proc-data-index-service-security_kogito-configuring[_{CONFIGURING_KOGITO}_]  (Stetson, 30 June 2020)
endif::[]

Description

== {PRODUCT} Operator and CLI

=== Improved/new bla bla

Description

== {PRODUCT} supporting services

=== Improved/new bla bla

Description

== {PRODUCT} tooling

=== DMN included models in the {PRODUCT} DMN modeler in VSCode

The {PRODUCT} Decision Model and Notation (DMN) modeler in VSCode contains a new *Included Models* tab that you can use to include other DMN models from your project in a specified DMN file. When you include a DMN model within another DMN file, you can reuse the decision requirements diagram (DRD) nodes and logic of the included model in that DMN file. This enhancement helps you more efficiently integrate DMN logic between different DMN models in your project.

For more information about DMN included models in {PRODUCT}, see
ifdef::KOGITO[]
{URL_DECISION_SERVICES}#proc-dmn-included-models-dmn_dmn-models[_{DECISION_SERVICES}_].
endif::[]
ifdef::KOGITO-COMM[]
xref:proc-dmn-included-models-dmn_dmn-models[].
endif::[]

=== Improved/new bla bla

Description
