[id='ref-kogito-rn-new-features_{context}']
= New features in {PRODUCT} {PRODUCT_VERSION}

The following sections describe some of the new features or enhancements in {PRODUCT} {PRODUCT_VERSION}.

== {PRODUCT} runtimes

=== BPMN support updates

The following Business Process Model and Notation (BPMN) components have been added in {PRODUCT}:

* *Ad hoc subprocess*: Contains embedded inner activities and is intended to be executed with a more flexible ordering compared to the typical routing of processes
* *Milestone*: Represents a single point of achievement within a process instance, typically for triggering other tasks or tracking the progress of the process

For more information about BPMN support in {PRODUCT}, see
ifdef::KOGITO[]
{URL_PROCESS_SERVICES}[_{PROCESS_SERVICES}_].
endif::[]
ifdef::KOGITO-COMM[]
xref:chap-kogito-developing-process-services[].
endif::[]

=== CloudEvents support for BPMN milestones

Information about milestones from Business Process Model and Notation (BPMN) process models is now included in https://cloudevents.io/[CloudEvents] messaging in {PRODUCT} services. This information includes the milestone `id`, `name`, and `status`, as shown in the following CloudEvents response body:

.CloudEvents response body with milestones information
[source,json]
----
{
  "data": {
    "endDate": "2019-08-20T19:26:02.092Z[UTC]",
    "id": "c2fa5c5e-3002-44c7-aef7-bce82297e3fe",
    "parentInstanceId": "f8868a2e-1bbb-47eb-93cf-fa46ff9dbfee",
    "processId": "hotelBooking",
    "processName": "HotelBooking",
    "rootInstanceId": "f8868a2e-1bbb-47eb-93cf-fa46ff9dbfee",
    "rootProcessId": "travels",
    "startDate": "2019-08-20T19:26:02.091Z[UTC]",
    "state": 2,
    "milestones": [
      {
        "id": "_18950AC4-664B-465E-B99E-766D38D362BF",
        "name": "AutoStartMilestone",
        "status": "AVAILABLE"
      }
    ]
  },
  "id": "b50a3dd4-a955-49c4-a055-f30a4d768f87",
  "kogitoParentProcessinstanceId": "f8868a2e-1bbb-47eb-93cf-fa46ff9dbfee",
  "kogitoProcessId": "hotelBooking",
  "kogitoProcessinstanceId": "c2fa5c5e-3002-44c7-aef7-bce82297e3fe",
  "kogitoProcessinstanceState": "2",
  "kogitoRootProcessId": "travels",
  "kogitoRootProcessinstanceId": "f8868a2e-1bbb-47eb-93cf-fa46ff9dbfee",
  "kogitoAddons": "jobs-management,prometheus-monitoring,process-management",
  "specversion": "0.3",
  "time": "2019-08-20T21:26:02.110668+02:00[Europe/Warsaw]",
  "type": "ProcessInstanceEvent",
  "source": "/hotelBooking"
}
----

ifdef::KOGITO-COMM[]
=== New code scaffolding feature to create custom {PRODUCT} project code

WARNING: This feature is experimental and might be substantially modified or removed in a future release. This feature also requires a special project setup. The generated code uses APIs that in {PRODUCT} are not final and will not function the same way in future releases.

{PRODUCT} now supports code scaffolding to enable you to generate your {PRODUCT} project code to a specified user directory and then customize the code as needed. With code scaffolding, you generate your {PRODUCT} project with the {PRODUCT} Maven archetype as usual, but you disable the project ability to automatically regenerate the project code and explicitly instruct {PRODUCT} to generate the code in a custom target directory. The code is generated one time in the specified target directory and is not regenerated at build time unless you explicitly request it.

For more information about code scaffolding in {PRODUCT}, see xref:proc-kogito-creating-project-custom_kogito-creating-running[].

//@comment: Ref for enterprise if/when the time comes: {URL_CREATING_RUNNING}#proc-kogito-creating-project-custom_kogito-creating-running[_{CREATING_RUNNING}_].  (Stetson, 26 June 2020)
endif::[]

== {PRODUCT} Operator and CLI

=== New `KogitoBuild` custom resource

The {PRODUCT} Operator now supports a `KogitoBuild` custom resource that you can use to build {PRODUCT} services separately before deploying them. When you use this custom resource, you can also specify the type of OpenShift Source-to-Image (S2I) build, such as from binary, from a remote Git repository, or from a local file (DMN, BPMN, or DRL).

For an example configuration that uses the `KogitoBuild` custom resource to link builds with service deployments on OpenShift, see the https://github.com/kiegroup/kogito-cloud-operator/blob/master/examples/process-quarkus-example-runtime-build.yaml[`process-quarkus-example-runtime-build.yaml`] example file.

== Integration with the Events API

When the {PRODUCT} Operator deploys a new resource, you can now view additional information about the created resources in the Kubernetes or OpenShift Events console without having to rely on the log of the {PRODUCT} Operator pod. This integration will be improved in a future release to provide more meaningful information about the operator controlled resources.

== {PRODUCT} supporting services

=== {PRODUCT} Data Index Service support for BPMN milestones

The {PRODUCT} Data Index Service now enables you to retrieve milestone information as part of the `ProcessInstances` object in GraphQL. You can filter results by milestone `id`, `name`, and `status`, as shown in the following GraphQL queries:

.Supported GraphQL query format for retrieving milestone information
[source]
----
{
  ProcessInstances {
    milestones {
      id
      name
      status
  }
}}
----

.Example GraphQL query for process instances by milestone name
[source]
----
{
  ProcessInstances(where: {milestones: {name: {equal: "AMilestoneName"}}}) {
    id
  }
}
----

.Example GraphQL query for process instances by milestone status
[source]
----
{
  ProcessInstances(where: {milestones: {status: {in: [AVAILABLE, ACTIVE] }}}) {
    id
  }
}
----

For more information about using the {PRODUCT} Data Index Service to query application data, see
ifdef::KOGITO[]
{URL_CONFIGURING_KOGITO}#con-data-index-service_kogito-configuring[_{CONFIGURING_KOGITO}_].
endif::[]
ifdef::KOGITO-COMM[]
xref:con-data-index-service_kogito-configuring[].
endif::[]

ifdef::KOGITO-COMM[]
=== Improved GraphQL security in the {PRODUCT} Data Index Service

When you enable security in the {PRODUCT} Data Index Service, you can now also configure the GraphQL interface endpoint and authentication requirements. The Data Index Service also now uses multi-tenant configuration to support `web-app` and `service` application types at the same time in different endpoints.

For more information about enabling security in the {PRODUCT} Data Index, see xref:proc-data-index-service-security_kogito-configuring[].

//@comment: Link for enterprise if/when needed: {URL_CONFIGURING_KOGITO}#proc-data-index-service-security_kogito-configuring[_{CONFIGURING_KOGITO}_]  (Stetson, 30 June 2020)
endif::[]

== {PRODUCT} tooling

=== DMN included models in the {PRODUCT} DMN modeler in VSCode

The {PRODUCT} Decision Model and Notation (DMN) modeler in VSCode contains a new *Included Models* tab that you can use to include other DMN models from your project in a specified DMN file. When you include a DMN model within another DMN file, you can reuse the decision requirements diagram (DRD) nodes and logic of the included model in that DMN file. This enhancement helps you more efficiently integrate DMN logic between different DMN models in your project.

For more information about DMN included models in {PRODUCT}, see
ifdef::KOGITO[]
{URL_DECISION_SERVICES}#proc-dmn-included-models-dmn_dmn-models[_{DECISION_SERVICES}_].
endif::[]
ifdef::KOGITO-COMM[]
xref:proc-dmn-included-models-dmn_dmn-models[].
endif::[]

=== DMN guided tour in the {PRODUCT} DMN modeler in online viewer

The {PRODUCT} Decision Model and Notation (DMN) modeler in the Business Modeler online viewer provides a new guided tour when you open the modeler for the first time. The DMN guided tour shows the main modeler features and workflows to help you get started. You can dismiss the guided tour prompts at any time and the prompts do not appear again.

=== Improvements to {PRODUCT} business modelers

The {PRODUCT} business modelers, including VSCode, desktop, online, and Chrome extensions, include the following notable improvements:

* Keyboard shortcut support for Linux, Windows, and Mac operating systems. To view available shortcuts, click the keyboard icon in the lower-left corner of the BPMN or DMN canvas in any {PRODUCT} business modeler.
* Support for undo, redo, and asynchronous save in all {PRODUCT} business modelers. This improvement also provides Is Dirty indicators that help you avoid losing unsaved data.
