[id='ref-kogito-rn-new-features_{context}']
= New features in {PRODUCT} {PRODUCT_VERSION}

The following sections describe some of the new features or enhancements in {PRODUCT} {PRODUCT_VERSION}.

== {PRODUCT} runtimes

ifdef::KOGITO-COMM[]
=== Improved GraphQL security in the {PRODUCT} Data Index Service

When you enable security in the {PRODUCT} Data Index Service, you can now also configure the GraphQL interface endpoint and authentication requirements. The Data Index Service also now uses multi-tenant configuration to support `web-app` and `service` application types at the same time in different endpoints.

For more information about enabling security in the {PRODUCT} Data Index, see xref:proc-data-index-service-security_kogito-configuring[].

//@comment: Link for enterprise if/when needed: {URL_CONFIGURING_KOGITO}#proc-data-index-service-security_kogito-configuring[_{CONFIGURING_KOGITO}_]  (Stetson, 30 June 2020)
endif::[]

Description

== {PRODUCT} Operator and CLI

=== Improved/new bla bla

Description

== {PRODUCT} supporting services

=== Improved/new bla bla

Description

== {PRODUCT} tooling

=== DMN included models in the {PRODUCT} DMN modeler in VSCode

The {PRODUCT} Decision Model and Notation (DMN) modeler in VSCode contains a new *Included Models* tab that you can use to include other DMN models from your project in a specified DMN file. When you include a DMN model within another DMN file, you can reuse the decision requirements diagram (DRD) nodes and logic of the included model in that DMN file. This enhancement helps you more efficiently integrate DMN logic between different DMN models in your project.

For more information about DMN included models in {PRODUCT}, see
ifdef::KOGITO[]
{URL_DECISION_SERVICES}#proc-dmn-included-models-dmn_dmn-models[_{DECISION_SERVICES}_].
endif::[]
ifdef::KOGITO-COMM[]
xref:proc-dmn-included-models-dmn_dmn-models[].
endif::[]

=== DMN guided tour in the {PRODUCT} DMN modeler in online viewer

The {PRODUCT} Decision Model and Notation (DMN) modeler in the Business Modeler online viewer provides a new guided tour when you open the modeler for the first time. The DMN guided tour shows the main modeler features and workflows to help you get started. You can dismiss the guided tour prompts at any time and the prompts do not appear again.

=== Improvements to {PRODUCT} business modelers

The {PRODUCT} business modelers, including VSCode, desktop, online, and Chrome extensions, include the following notable improvements:

* Keyboard shortcut support for Linux, Windows, and Mac operating systems. To view available shortcuts, click the keyboard icon in the lower-left corner of the BPMN or DMN canvas in any {PRODUCT} business modeler.
* Support for undo, redo, and asynchronous save in all {PRODUCT} business modelers. This improvement also provides Is Dirty indicators that help you avoid losing unsaved data.
