[id='decision-examples-central-con_{context}']

= Example projects and business assets in {CENTRAL}

{CENTRAL} contains example projects with example business assets that you can use as a reference for the
ifdef::DM,DROOLS[]
rules or other assets
endif::[]
ifdef::PAM,JBPM[]
rules, processes, or other assets
endif::[]
that you create in your own {PRODUCT} projects. Each sample project is designed differently to demonstrate
ifdef::DM,DROOLS[]
decision management or business optimization
endif::[]
ifdef::PAM,JBPM[]
process automation, decision management, or business optimization
endif::[]
assets and logic in {PRODUCT}.

The following example projects are available in {CENTRAL}:

ifdef::PAM,JBPM[]
* *Evaluation_Process*: (Process automation) Example evaluation process using business process assets. Evaluates employees based on performance.
* *Mortgage_Process*: (Process automation) Example loan approval process using business process and decision assets. Determines loan eligibility based on applicant data and qualifications.
* *IT_Orders*: (Process automation and case management) Example ordering case using business process and case management assets. Places an IT hardware order based on needs and approvals.
//* *Traffic Violation*: (Process Automation) Example traffic violations process using business process and DMN assets. Determines the traffic violation type and calculates the fine based on the violation type.
endif::[]
* *Mortgages*: (Decision management) Example loan approval process using decision assets. Determines loan eligibility based on applicant data and qualifications.
* *Employee_Rostering*: (Business optimization) Example employee rostering optimization using decision and solver assets. Assigns employees to shifts based on skills.
* *OptaCloud*: (Business optimization) Example resource allocation optimization using decision and solver assets. Assigns processes to computers with limited resources.
