[id='decision-examples-central-proc_{context}']

= Accessing example projects and business assets in {CENTRAL}

You can use the example projects in {CENTRAL} to explore example business assets as a reference for the rules or other assets that you create in your own {PRODUCT} projects.

.Prerequisites
* {CENTRAL} is installed and running. For installation options, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click *Try Samples*.
+
If a project already exists, click the three vertical dots in the upper-right corner of the *Projects* page and click *Try Samples*.
. Review the descriptions for each sample project to determine which project you want to explore. Each sample project is designed differently to demonstrate
ifdef::DM,DROOLS,OP[]
decision management or business optimization
endif::[]
ifdef::PAM,JBPM[]
process automation, decision management, or business optimization
endif::[]
assets and logic in {PRODUCT}.
. Select one or more sample projects and click *Ok* to add the projects to your space.
. In the *Projects* page of your space, select one of the new example projects to view the example assets for that project.
. Select each example asset to explore how the project is designed to achieve the specified goal or workflow.
. In the upper-right corner of the project *Assets* page, click *Build* to build the sample project or *Deploy* to build the project and then deploy it to {KIE_SERVER}.
+
To review project deployment details (if applicable), go to *Menu* -> *Deploy* -> *Execution Servers*.
