[id='decision-examples-central-con_{context}']

= Sample projects and business assets in {CENTRAL}

{CENTRAL} contains sample projects with business assets that you can use as a reference for the
ifdef::DM,DROOLS[]
rules or other assets
endif::[]
ifdef::PAM,JBPM[]
rules, processes, or other assets
endif::[]
that you create in your own {PRODUCT} projects. Each sample project is designed differently to demonstrate
ifdef::DM,DROOLS[]
decision management or business optimization
endif::[]
ifdef::PAM,JBPM[]
process automation, decision management, or business optimization
endif::[]
assets and logic in {PRODUCT}.

NOTE: Red Hat does not provide support for the sample code included in the {PRODUCT} distribution.

The following sample projects are available in {CENTRAL}:

//ifdef::PAM,JBPM[]
//* *Traffic Violation*: (Process Automation) Example traffic violations process using business process and DMN assets. Determines the traffic violation type and calculates the fine based on the violation type.
//endif::[]
* *Course_Scheduling*: (Business optimization) Course scheduling and curriculum decision process. Assigns lectures to rooms and determines a student's curriculum based on factors such as course conflicts and class room capacity.
* *Dinner_Party*: (Business optimization) Guest seating optimization using guided decision tables. Assigns guest seating based on each guest's job type, political beliefs, and known relationships.
* *Employee_Rostering*: (Business optimization) Employee rostering optimization using decision and solver assets. Assigns employees to shifts based on skills.
* *Evaluation_Process*: (Process automation) Evaluation process using business process assets. Evaluates employees based on performance.
* *IT_Orders*: (Process automation and case management) Ordering case using business process and case management assets. Places an IT hardware order based on needs and approvals.
* *Mortgages*: (Decision management with rules) Loan approval process using rule-based decision assets. Determines loan eligibility based on applicant data and qualifications.
* *Mortgage_Process*: (Process automation) Loan approval process using business process and decision assets. Determines loan eligibility based on applicant data and qualifications.
* *OptaCloud*: (Business optimization) Resource allocation optimization using decision and solver assets. Assigns processes to computers with limited resources.
* *Traffic_Violation*: (Decision management with DMN) Traffic violation decision service using a Decision Model and Notation (DMN) model. Determines driver penalty and suspension based on traffic violations.
