[id='running-examples-proc']
= Running examples

The following examples are small Java/Drools applications which demonstrate various features and design patterns of Drools. They are meant to be executed from your IDE so that you can explore how the rules and code function as well as how to view audit/debug logs. 


.Prerequisites

* Java and Maven are installed.

ifdef::DM,PAM[]
* JBoss Developer Studio (IDE) is installed.
endif::[]
ifdef::DROOLS,JBPM,OP[]
* Eclipse with JBoss Tools plugin (IDE) is installed.
endif::[]


.Procedure

ifdef::DM,PAM[]
. Download and unzip the *{PRODUCT} {PRODUCT_VERSION_LONG} Source Distribution* from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Red Hat Customer Portal].
endif::[]
ifdef::DROOLS,JBPM,OP[]
. Download and unzip the {PRODUCT} source from https://github.com/kiegroup/drools/archive/master.zip[Drools Github Repository]. _(To run "Conway’s Game Of Life" example, you'll also need to download and unzip the {PRODUCT} source from https://github.com/kiegroup/droolsjbpm-integration/archive/master.zip[Drools and jBPM Integration Github Repository])._
endif::[]

. Open your IDE and go to *File → Import* then select *Maven → Existing Maven Projects*.

. Click on *Browse*, navigate to the location the files were unzipped, select `\drools-examples` (or `\droolsjbpm-integration-examples` for "Conway's Game Of Life" example), and click *Finish*. 
 
. Navigate to the example package which you want to run and find the Java class which has the `main` method.

. Right-click the Java class and select *Run As → Java Application* to run the project.
