[id='assembly_optimizer-running-employee-rostering']

include::product-shared-docs/document-attributes.adoc[]

= Running the employee roster sample for Business Optimizer
// Context attribute is assembly specific and enables module reuse between assemblies.
:imagesdir: topics/product-shared-docs/images
:context: running-employee-rostering
include::product-shared-docs/author-group.adoc[]


// Purpose statement for the assembly
As a business rules developer, you can test and interact with the {PLANNER} functionality using the preconfigured `employee-rostering` sample project included in the {PRODUCT} distribution.

.Prerequisite
{PRODUCT} has been downloaded, configured for {PLANNER} and deployed in {CENTRAL}. For more information about the required configuration, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.0/html-single/getting_started_with_decision_services/[_{GETTING_STARTED_DECISION_SERVICE}_] and {URL_INSTALLING_PLANNER}[_INSTALLING_PLANNER_].

//@link-GS: For PAM patch, replace the hard link above with the URL attr so that it reads, "see {URL_GETTING_STARTED_DECISION_SERVICE}[_{GETTING_STARTED_DECISION_SERVICE}_]".
