= My First Business Application

== What will you do

You will build a simple but fully functional business application.
Once you build it you will explore basic services exposed by the application.

== What do you need

* About 10 minutes of your time
* Java (JDK) 8 or later
* Maven 3.5.x
* Access to the Internet

== What should I do

To get started with business applications the easiest way is to generate it using maven archetype commands. Please refer <<../../jbpm-docs/src/main/asciidoc/BusinessApplications/CreateApplication-section.adoc#_sect_BA_create_application, Create your business application section>>.

Now the directory  will consists of three projects

* business-application-model
* business-application-kjar
* business-application-service

Go into `business-application-service` directory. There you will find launch scripts
(for both linux/unix and windows).

`./launch.sh clean install` for Linux/Unix

`./launch.bat clean install` for Windows

Execute one applicable to your operating system and wait for it to finish.

NOTE: It might take quite some time (depending on your network) as it will
download bunch of dependencies required to execute both build and application itself.

== Results

Once the build and launch is complete you can open your browser
http://localhost:8090[http://localhost:8090] to see your first business
application up and running.

It presents with a welcome screen that is mainly for verification purpose
to illustrate that application started successfully.

You can point the browser to http://localhost:8090/rest/server[http://localhost:8090/rest/server]
to see the actual Business Automation capability services

NOTE: By default all REST endpoints (url pattern /rest/*) are secured and require
authentication. Default user that can be used to logon is `user` with password `user`

Business Automation service supports three types of data format

* XML (JAXB based)
* JSON
* XML (XStream based)

To display Business Automation capability service details in different format set HTTP headers

* Accept: application/json for JSON format
* Accept: application/xml for XML (JAXB based) format
* X-KIE-ContentType: XSTREAM for XML (XStream based) format

== Summary

Congratulations! you have just built and started your first business application.

== Source code of the tutorial

https://github.com/business-applications/01-tutorial-first-business-application[Here] is the complete source code of the tutorial.
