[id='rn-7.12-known-issues-ref']
= Known issues in {PRODUCT} {ENTERPRISE_VERSION_LONG}

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

.In the test scenarios table, `today()` and `now()` functions are not evaluated correctly [https://issues.redhat.com/browse/RHDM-1816[RHDM-1816]]

Issue: In the test scenarios table, `today()` and `now()` functions are not evaluated correctly. For example, the `string(today())` function should produce output similar to `2021-05-11` but instead it displays a null value.

Steps to reproduce:

Import the `check-today-1.dmn` and `check-today-test-1.scesim` files attached in the [https://issues.redhat.com/browse/RHDM-1816[RHDM-1816]] issue and check the results.

Workaround: None.

ifdef::PAM[]

== Form modeler

.When you create and open a form in the form modeler, you receive a recursion handling issue [https://issues.redhat.com/browse/RHPAM-4107[RHPAM-4107]]

Issue: In the form modeler, when you try to create and open a form, you receive an error message about a recursion handling issue

Steps to reproduce:

. Create a data object called *A1* and enter the field values as *id:String* and *aField:A1*.
. Create a custom form as *Form1* for the *A1* data object.
. Select *aField* and drag it to the canvas and set *Form1* as its nested form.
. Click *Save*.
. Reopen the editor.
+
You receive an error message.

Workaround: None.

endif::PAM[]

== {KOGITO}

.Unable to run the tests for {KOGITO} examples with scenario simulations [https://issues.redhat.com/browse/RHPAM-4068[RHPAM-4068]]

Issue: It is not possible to run the tests for {KOGITO} examples which contain scenario simulation dependency. The Surefire plugin fails with an exception.

The following two modules in the {KOGITO} examples fail because there is a mismatch of JUnit version dependency:

* `dmn-pmml-quarkus-example`
* `dmn-quarkus-example`

These examples are included in the `sources.zip` and `kogito-quickstarts.zip` files.

Steps to reproduce:

. Download the {KOGITO} examples.
. Execute the `mvn clean install` command for `dmn-quarkus-example` or `dmn-pmml-quarkus-example`.

Workaround: Override the transitive JUnit dependency of `kogito-scenario-simulation` file and use the version `4.13.1.redhat-00001`.


== {KIE_SERVER}

.When you initialize Swagger on WebSphere, you receive an `IllegalArgumentException` error [https://issues.redhat.com/browse/RHPAM-3949[RHPAM-3949]]

Issue: When you use the {KIE_SERVER} Swagger extension on WebSphere, {KIE_SERVER} is unavailable and it returns the HTTP 500 error with an `IllegalArgumentException` exception.

Steps to reproduce:

. Start {KIE_SERVER} with basic configuration on WebSphere.
. Try to access the `http://localhost:9080/kie-server/services/rest/server` URL.
+
You receive the HTTP 500 error.

Workaround: Disable Swagger UI by setting the value of the `org.kie.swagger.server.ext.disabled` system property to `true`.

== DMN designer

.Elbow lines for object connections do not work [https://issues.redhat.com/browse/RHDM-1856[RHDM-1856]]

Issue: You can adjust the DMN connections shape by adding control point to it. However this feature does not work for connections with the text annotation nodes.

Steps to reproduce for {KOGITO}:

. Enter https://sandbox.kie.org/#/ in a browser.
. Import the `association.dmn` file attached in the [https://issues.redhat.com/browse/RHDM-1856[RHDM-1856]] issue.
. In the *Import* field, upload the `association.dmn` file.
. Run the project.

Steps to reproduce for {CENTRAL}:

. Open an existing project or create a new one.
. Import the `association.dmn` file attached in the [https://issues.redhat.com/browse/RHDM-1856[RHDM-1856]] issue.
. Build the project and observe the results.

Workaround: None.
