[id='rn-781-known-issues-ref']
= Known issues in {PRODUCT} 7.8.1

This section lists known issues with {PRODUCT} 7.8.1.

== {CENTRAL}

.A system error occurs when you add a deployment unit [https://issues.redhat.com/browse/RHPAM-3111[RHPAM-3111]]

Issue: When you add a deployment unit and manually enter GAV values, you receive an unexpected system error.

Steps to reproduce:

. In {CENTRAL}, go to *Menu → Deploy → Execution Servers*.
. Under *Deployment Units*, click *Add Deployment Unit*.
. Enter the non existent GAV values manually.
. Select the *Start Deployment Unit?* check box to start the service.
. Click *Finish*.
+
You receive an unexpected system error.

Workaround: None.

.The wait spinner is not present when you add a deployment unit, manually enter GAV values, and confirm the alert window [https://issues.redhat.com/browse/RHPAM-3114[RHPAM-3114]]

Issue: The wait spinner is not present even after confirming the alert window. You can still modify the GAV values while the deployment is in the progress.

Steps to reproduce:

. In {CENTRAL}, go to *Menu → Deploy → Execution Servers*.
. Under *Deployment Units*, click *Add Deployment Unit*.
. Enter the non existent GAV values manually.
. Select the *Start Deployment Unit?* check box to start the service.
. Click *Finish*.
. In the *Save Container Spec* alert window, click *OK*.
+
The alert window disappears and you can still modify the GAV values while the deployment is in the progress.

Expected result: The wait spinner is present after confirming the alert window.

Actual result: The wait spinner is not present even after confirming the alert window.

Workaround: None.

.When you apply constraint to a DMN data type, you receive an error alert window in the scenario simulation [https://issues.redhat.com/browse/RHDM-1435[RHDM-1435]]

Issue: When you apply constraint to a DMN data type, you receive *Wrong column mapping* error alert window in the scenario simulation.

Steps to reproduce:

. In {CENTRAL}, go to *Menu → Design → Projects*.
. Click *Try samples*.
. Open *Traffic_Violation* project.
. Open *Traffic Violation* DMN file and select *Data Types* tab.
. To modify the `tViolation` data type, click `tViolation`.
. To add the constraints to the `tViolation` data type, click the edit icon, click *Add Constraints*.
. Select *Enumeration* from the *Select constraint type* pull-down menu and add `50`, `90`, and, `130` in the fields.
. Click *OK*, then click the check mark to the right of the `tViolation` data type to save your changes.
. Click *Save* and close the DMN editor.
. Open *Violation Scenarios* test scenario.
+
you receive *Wrong column mapping* error alert window.

Workaround:

. From the Test Scenario designer toolbar on the upper-right, click *Export* and export the `.CSV` file.
. Click the affected property column header.
. Select the property from the *Test Tools* panel again.
. Confirm the alert window for deleting the values.
. Import the originally exported `.CSV` file.

.You cannot save a file when you try to rename the package from the source code [https://issues.redhat.com/browse/RHPAM-3119[RHPAM-3119]]

Issue: When you try to rename the package from the source code and close the editor right away before the reload is complete, you receive *Unsaved changes* alert window even after the data object is already saved in the new package.

Steps to reproduce:

. Open {CENTRAL}.
. Open any project.
. Create a data object.
. In the *Source* tab of a data object, change the package name.
. Click *Save*.
. In the *Information* alert window, click *+ Yes, Move* and confirm the changes.
+
You can see the *Item successfully renamed* notification.
. Close the editor quickly.
+
You receive *Unsaved changes* alert window.

Workaround: None.

ifdef::PAM[]

== Process designer

.Case management properties are missing in case definition [https://issues.redhat.com/browse/RHPAM-3131[RHPAM-3131]]

Issue: In *Properties* panel, case management properties are missing in case definition.

Steps to reproduce:

. Create a case project.
. Create a case definition.
. Open *Properties* panel and add any case management property.

Expected result: Case management section is present in *Properties* panel.

Actual result: Case management section is not present in *Properties* panel.

Workaround: Set the Adhoc property to `true`. To reflect the changes, save the changes, close the case and reopen the *Properties* panel.

endif::[]

== Form modeler

.Document upload feature does not work on Windows [https://issues.redhat.com/browse/RHPAM-3117[RHPAM-3117]]

Issue: In Windows, with the *Document* form field, you cannot upload documents that are required as part of a form or process.

Steps to reproduce:

. Set the document marshalling strategy.
. Create a document variable in the business process.
. Map the task inputs and outputs to the document variable.

Expected result: Document upload feature is working on Windows.

Actual result: Document upload feature is not working on Windows.

Workaround: None.
