[id='rn-7.13.1-known-issues-ref']
= Known issues in {PRODUCT} 7.13.1

This section lists known issues with {PRODUCT} 7.13.1.

== {CENTRAL}

.Unable to deploy {CENTRAL} using JDK version 11.0.16 [https://issues.redhat.com/browse/RHPAM-4497[RHPAM-4497]]

Issue: It is not possible to deploy {CENTRAL} if your installation uses JDK version 11.0.16.

Actual result: {CENTRAL} does not deploy when launched.

Expected result: {CENTRAL} deploys successfully.

Workaround: Use a previous JDK version such as 11.0.5 or earlier.

== Form Modeler

.Date type process variable is empty when the process is started using {CENTRAL} form with the `showTime` set to `false` [https://issues.redhat.com/browse/RHPAM-4514[RHPAM-4514]]

Issue: When you use the default form rendering in {CENTRAL} and the process variable field has `showTime=false`, the started process instance shows that the variable is empty. The affected types are `java.time.LocalDateTime`, `java.time.LocalDate`, `java.time.LocalTime`, and `java.util.Date`.

Steps to reproduce:

. Define the process variable with a specific type.
. Generate a form.
. Open a form and set `showTime=false` for a specified field.
. Deploy the project.
. Open the process form.
. Specify the value in the process form.
. Check the process instance variables. The value for the specified variable is empty.

Workaround: None.

.Form in KIE Server with a `java.util.Date` field does not allow the time to be inserted [https://issues.redhat.com/browse/RHPAM-4513[RHPAM-4513]]

Issue: When a process has a variable of type `java.util.Date`, the generated form, if the `showTime` attribute is `true`, does not allow inserting the time part. Then after submitting the `Date` variable shows all zeros in the time part of the datatype.

Workaround: None.

ifdef::PAM[]

== Process Designer

.BPMN2 files in XML editor have a *Properties* panel that contains a data from other processes [https://issues.redhat.com/browse/RHPAM-4468[RHPAM-4468]]

Issue: If two processes are open, where one process is open in the XML editor (a legacy process with the BPMN2 extension) and one process is open in the new process designer, the properties in the *Properties* panel, as well as the diagram in the *Explore Diagram* window from the new process designer, are shown in the XML editor of the other process. The XML editor should not have any *Properties* or *Diagram* panel.

Steps to reproduce:

. Open any new process designer process.
. Do not close the process.
. Open the legacy process, for example `legacy.bpmn2`, in the XML editor.
. Open the *Properties* panel.
Actual result: The *Properties* and *Explore diagram* from a new process designer process are shown in the XML editor panel.

Expected result: No *Properties* or *Explore diagram* panels are present in the XML editor.

Workaround: None.

.A custom data object in multiple variables causes an error in a case project [https://issues.redhat.com/browse/RHPAM-4422[RHPAM-4422]]

Issue: The custom data object in the multiple variables causes an error in a case project. You receive a UI exception with the following error:

[source]
----
Uncaught exception: Exception caught: Duplicate value: CustomDataObject [com.myspace.caseproject] Caused by: Duplicate value: CustomDataObject [com.myspace.caseproject]
----

Steps to reproduce:

. Create a case definition in a case project.
. Create a custom data object in the same project.
. Add a `procVar` process variable and `caseVar` case file variable with the same `CustomDataObject` type.
. Save the changes.
. Create a multiple instance node or a *Data Object* on the canvas.
. In the multiple instance node, set *MI Collection input/output* and try to change the *Data Input/Output* type.
. In the *Data Object* on the canvas, try to change the data type.

Actual result:

* On a Chrome browser: It is not possible to set the type with the first click. The custom type is chosen.
* On a Firefox browser: An unexpected error occurs.

Expected result: It is possible to set the type correctly. No errors occur.

Workaround: None.

endif::[]

== {OPENSHIFT}

.PostgreSQL 13 Pod won't start because of an incompatible data dirctory [https://issues.redhat.com/browse/RHPAM-4464[RHPAM-4464]]

Issue: When you start a PostgreSQL pod after you upgrade the operator, the pod fails to start and you receive the following message:

`Incompatible data directory. This container image provides
PostgreSQL '13', but data directory is of
version '10'.
This image supports automatic data directory upgrade from
'12', please carefully consult image documentation
about how to use the '$POSTGRESQL_UPGRADE' startup option.`

Workaround:

. Check the version of PostgreSQL:
+
[source]
----
$ postgres -V
----

. If the PostgreSQL version returned is 12.x or earlier, upgrade PostgreSQL:
+
[cols="30%,15%,55%" frame="all", options="header"]
|===
| {PRODUCT} version
| PostgreSQL version
| Upgrade instructions

| 7.13.1 | 7.10 | Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/12#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 12.x.

| 7.13.2 | 7.10 | 1. Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/12#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 12.x.

2. Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/13#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 13.x.

| 7.13.2 | 7.12 |
Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/13#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 13.x.
|===

. Verify that PostpreSQL has been upgraded to your required version:
+
[source]
----
$ postgres -V
----
