[id='rn-790-known-issues-ref']
= Known issues in {PRODUCT} {ENTERPRISE_VERSION_LONG}

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

.Package list fails to populate default package for imported projects [https://issues.redhat.com/browse/RHPAM-3209[RHPAM-3209]]

Issue: When a project contains many packages, and you try to create a new asset, the list of packages take some time to populate.

Steps to reproduce:

. Import a project which contains many packages.
. Go to the project page.
. Click *Add Asset*.
+
The *Assets* window appears.
. Add any asset in the project.
. In the pop-up window, check the *Package* drop-down list.
+
You receive *Nothing selected* option for some time.

Expected result: Package list is populating default package for imported projects.

Actual result: Package list is not populating default package for imported projects.

Workaround:

* Make sure you have identical paths in both `src/java` and `src/resources`. In your Git repository, insert `.gitkeep` files to retain the empty folder structure.
* In the asset pop-up window, manually select the *<default>* option in the *Package* drop-down list..

.Collection editor is not opening for DRL based test scenarios [https://issues.redhat.com/browse/RHDM-1464[RHDM-1464]]

Issue: DRL based test scenario throws an unexpected error when you open a collection editor for a list of some datatypes.

Workaround: None.

.You cannot add a deployment unit when you create a container for the first time [https://issues.redhat.com/browse/RHPAM-3254[RHPAM-3254]]

Issue: You cannot add a deployment unit when you create a container for the first time, and you receive an unexpected system error.

Steps to reproduce:

. In {CENTRAL}, go to *Menu → Deploy → Execution Servers*.
. Under *Deployment Units*, click *Add Deployment Unit*.
. Enter the GAV values manually.
. Select the *Start Deployment Unit?* check box to start the service.
. Click *Finish*.
+
You receive an unexpected system error.

Workaround: None.

ifdef::PAM[]

.Unable to navigate from child process instance to parent process instance [https://issues.redhat.com/browse/RHPAM-3227[RHPAM-3227]]

Issue: You cannot navigate from child process instance to parent process instance but possible to navigate from parent process instance to child process instance.

Steps to reproduce:

. In {CENTRAL}, create parent process and child process relationship.
. Start the process instance and make it active.
. Notice that, you cannot navigate from child process instance to parent process instance.

Expected result: When there is an active process instance, there must be a link to navigate from child process instance to parent process instance and vice-versa.

Actual result: You cannot navigate from a child process instance to the parent process instance.

Workaround: None.

endif::[]

.The deployment unit fields are missing when you add a new deployment unit [https://issues.redhat.com/browse/RHPAM-3213[RHPAM-3213]]

Issue: When you add a deployment unit, fields that are available under *Add Deployment Unit* are missing.

Steps to reproduce:

. In {CENTRAL}, go to *Menu → Deploy → Execution Servers*.
. Under *Deployment Units*, click *Add Deployment Unit*.
+
Deployment unit fields are missing.

Workaround: Deployment unit fields appear only if you navigate to *Process Configuration* and come back.

ifdef::PAM[]

== Form modeler

.`DocumentCollection` output parameter does not work in generated forms [https://issues.redhat.com/browse/RHPAM-3252[RHPAM-3252]]

Issue: If documents are configured as output variable only, for example, documents are uploaded as a part of the user task, then the input parameter of `DocumentColletion` type is not present and the default value `""` (empty string) is sent to `DocumentCollection`, and also you receive an exception.

Steps to reproduce:

. Deploy the project attached in the https://issues.redhat.com/browse/RHPAM-3252[RHPAM-3252] issue.
. Create a new process instance.
. Enter the following endpoint URL:
+
[source]
----
http://<host>:<port>/kie-server/services/rest/server/containers/\{containerId}/forms/tasks/\{taskInstanceId}/content\
----

You receive an exception.

Workaround: None.

endif::[]

ifdef::PAM[]
== Process Designer

.Data objects in Assignments disappear once you save the process [https://issues.redhat.com/browse/RHPAM-3212[RHPAM-3212]]

Issue: Data objects which are present in *Assignments* disappear once you save the process.

Steps to reproduce:

. Create a data object.
. Create a user task.
. Click the *Properties* icon on the upper-right side of the screen to open the *Properties* panel.
. Expand *Implementation/Execution* and select *Assignments* to open the *Data I/O* window.
. Next to *Data Inputs and Assignments*, click *Add* and select a *Source* value.
. Next to *Data Outputs and Assignments*, click *Add* and select a *Target* value.
. Close the *Assignments* and save the process.
. Open the *Assignments* sub-section.

Expected result: *Source* and *Target* fields are empty.

Actual result: *Source* and *Target* fields are set to data object.

Workaround: Deselect the task and then select the task again.

.A new rule flow group is not reflected in business rule task properties [https://issues.redhat.com/browse/RHPAM-3195[RHPAM-3195]]

Issue: When you create a new rule flow group, the change is not reflected in business rule task's property.

Steps to reproduce:

. Create a business process.
+
Do not close the process.
. Create a `testrule.rdrl` file containing `testgroup` as ruleflow-group.
. Select *Business Rule* in created process.
. Expand *Implementation/Execution* and select *Rule Flow Group* drop-down list.

Expected result: The *Rule Flow Group* drop-down list contains ruleflow-group that is specified in DRL file. For example, `testgroup`.

Actual result: The *Rule Flow Group* drop-down list is empty.

Workaround: Deselect the business rule task and then select the business rule task again.

.Edited rule flow group is not reflected in business rule task properties [https://issues.redhat.com/browse/RHPAM-3194[RHPAM-3194]]

Issue: When you edit a rule flow group, the change is not reflected in business rule task's property.

Steps to reproduce:

. Create a business process.
+
Do not close the process.
. Create a `testrule.rdrl` file containing `testgroup` as ruleflow-group.
. Open a `testrule.rdrl` file and change the `testgroup` to `testgroup-renamed`.
. Save the changes.
. Select *Business Rule* in created process.
. Expand *Implementation/Execution* and select *Rule Flow Group* drop-down list.

Expected result: The *Rule Flow Group* drop-down list contains edited `testgroup-renamed` value.

Actual result: The *Rule Flow Group* drop-down list contains `testgroup` value.

Workaround: Deselect the business rule task and then select the business rule task again.

.The cursor position is different in Firefox browser when you use an inline text editor [https://issues.redhat.com/browse/RHPAM-3171[RHPAM-3171]]

Issue: When you use an inline text editor, the cursor position is different in Firefox browser in comparison with Google Chrome browser and Kogito VSCode extension.

Steps to reproduce:
Perform the following steps using both Firefox and Google Chrome browser.

. Create any node.
. Double-click the node to activate inline text editor.

Expected result: The cursor is on the same position in Firefox browser in comparison with Google Chrome browser.

Actual result: The cursor is on the different position in Firefox browser in comparison with Google Chrome browser.

Workaround: None.

.Editing text using an inline text editor is displayed over *Properties* panel or expanded palette [https://issues.redhat.com/browse/RHPAM-3172[RHPAM-3172]]

Issue: When you place any task, sub-process, or text annotation in the *Properties* panel and start editing its name by using an inline text editor, the text is visible over the *Properties* panel.

Steps to reproduce:

. Create any node.
. Ensure that the *Properties* panel is open and tool palette is expanded.
. Move the node under the *Properties* panel or the expanded area of the tool palette in a way that you can still click on the node.
. Double-click the node to activate inline text editor.
. Enter any text.

Expected result: The node is not editable or the text is shown next to the *Properties* panel or the tool palette and it is entirely visible.

Actual result: The text is visible over the *Properties* panel.

Workaround: None.

.You cannot create or open Case Management (Preview) asset [https://issues.redhat.com/browse/RHPAM-3281[RHPAM-3281]]

Issue: When you create or open Case Management (Preview) asset, you receive a runtime exception.

Steps to reproduce:

. Create a case project.
. Create a new Case Management (Preview) asset.

Expected result: You can successfully create or open a Case Management (Preview) asset.

Actual result: You receive a runtime exception when you create or open a Case Management (Preview) asset.

Workaround: None.

.Not all illegal characters are removed from data object name [https://issues.redhat.com/browse/RHPAM-3250[RHPAM-3250]]

Issue: When you create a data object with a name containing illegal characters, you receive a warning message after saving, closing, and saving it again.

Steps to reproduce:

. Create a data object with `~!@#$%^&*()_+`10-={}[]:"|;'\<>?,./°ľščťžýáíéúä!ô§ň` name.
. Save, close, and reopen the process.
. Move the node and save the process again.

Expected result: All illegal characters are removed when the process is saved and reopened.

Actual result: You receive a warning message.

Workaround: None.

.Scrolling of the Properties panel stops when the cursor is over a script area [https://issues.redhat.com/browse/RHPAM-3208[RHPAM-3208]]

Issue: When the cursor is over a script area, scrolling of the *Properties* panel stops.

Steps to reproduce:

. Create a user task.
. Expand *Implementation/Execution* section.
. Scroll down and keep scrolling until it stops.

Expected result: Scrolling stops working when the scrollbar is at the bottom of the page.

Actual result: Scrolling stops working when the cursor is over the *On Entry Action* field.

Workaround: If the cursor is outside the text area, the main scrollbar is always activated.

.Text area used for script task is cropped and shifted [https://issues.redhat.com/browse/RHPAM-3207[RHPAM-3207]]

Issue: Text area used for script task is cropped and shifted when you enter many lines of code. Also, the vertical scrollbar is shifted.

Steps to reproduce:

. Create a script task.
. Expand *Implementation/Execution* section.
. In *Script* text area, enter many lines of code.

Expected result: Text area used for script task is not cropped and shifted.

Actual result: Text area used for script task is cropped and shifted.

Workaround: None.

.When an inline text editor is active, you cannot activate any property immediately [https://issues.redhat.com/browse/RHPAM-3198[RHPAM-3198]]

Issue: It is not possible to activate any property immediately in the *Properties* panel when an inline editor is active.

Steps to reproduce:

. Create any node.
. Ensure that *Properties* panel is open.
. Double-click on the node to activate the inline text editor.
. Click on any property from the *Properties* panel.

Expected result: You can edit the property when an inline text editor is active.

Actual result: You cannot edit the property when an inline text editor is active.

Workaround: When you follow the steps to reproduce, click on the property again.

.You cannot use an inline text editor when a node is near the left canvas border [https://issues.redhat.com/browse/RHPAM-3167[RHPAM-3167]]

Issue: You cannot use an inline text editor when a node is near the left canvas border. This issue is applicable to events, gateways, and data object.

Steps to reproduce:

. Create any node.
. Place it near to the left canvas border.
. Double-click on the node.

Expected result: An inline text editor is active and you can edit the node name.

Actual result: An inline text editor is not active and you cannot edit the node name.

Workaround: None.

.The edited node is see-through when you use an inline text editor [https://issues.redhat.com/browse/RHPAM-3166[RHPAM-3166]]

Issue: The edited node is see-through when you use an inline text editor.

Steps to reproduce:

. Create an embedded subprocess.
. Change the name of the subprocess to a long text. For example, over 300 characters.
. Create any node inside the subprocess and place it over the text of the subprocess.
. Edit the node name using an inline text editor.

Expected result: The text is readable and the edited node is not see-through.

Actual result: The text is not readable because the edited node is see-through.

Workaround: None.

== Process engine

.When the SLA on user task is executed, you receive `No session found for context` error [https://issues.redhat.com/browse/RHPAM-3233[RHPAM-3233]]

Issue: When the service level agreement (SLA) on user task is executed on container with `PER_PROCESS_INSTANCE` runtime strategy, you receive `No session found for context` error.

Steps to reproduce:

. Clone the https://github.com/kiegroup/droolsjbpm-integration[droolsjbpm-integration] project.
. Open `SLAComplianceIntegrationTest.java` file from the cloned project.
. Comment out all the tests except `testSLAonUserTaskViolated()`.
. Open the terminal on `kie-server-integ-tests-jbpm/` folder and execute the test using following command:
+
[source]
----
mvn clean install -Pwildfly -Dit.test=SLAComplianceIntegrationTest
----
. Check the logs on the terminal.
+
Once the test execution starts, you receive a `No session found for context` error.

endif::[]

== DMN designer

.Decision service is missing `inputData` element in model with multiple DRDs [https://issues.redhat.com/browse/RHDM-1483[RHDM-1483]]

Issue: When you reuse a decision component by adding it into a decision service node in a model containing multiple decision requirement diagrams (DRDs), the `inputData` element is missing from the resulting decision service node.

Steps to reproduce:

. Define multiple decision requirement diagrams (DRDs).
. In a DRD, define some decisions with inputs.
. In another DRD, define decision service and reuse the decision components from the previous DRD.
+
Do not duplicate the inputs.
. Build and deploy the decision service.
. Do any of the following tasks:

* Evaluate the decision to see the error reported in the description.
* Verify the DMN source and see that `inputData` element is missing from the decision service .

Workaround: Add an `inputData` element manually into the resulting `decisionService` element.

.DMN editor does not detect the changes from the Decision Navigator view [https://issues.redhat.com/browse/RHDM-1482[RHDM-1482]]

Issue: DMN editor does not detect changes in the file when a decision requirement diagram (DRD) is renamed or removed from the *Decision Navigator* view.

Steps to reproduce:

. Rename a DRD from the *Decision Navigator* view.
. Click *Save*.
+
You receive *You have no unsaved changes* alert window.
. Close the DMN editor.
+
You receive *You have no unsaved changes* alert window.
. Reopen the DMN editor.
+
The name of the DRD is still the same.

Workaround: Make a different change to the file which then enforces save or discard action.

.The constraint value is missing in a decision table [https://issues.redhat.com/browse/RHDM-1460[RHDM-1460]]

Issue: The constraint value is missing while defining a decision table.

Steps to reproduce:

. Create a DMN file with decision.
. Define a decision table.
. Set the first column type as a number.
. Save the asset.
. Close the editor.
. Reopen the asset.
. Go to the decision table.
. Select the input with type as a number.
. Open the *Properties* panel.
. Set the constraint in the *Constraint value* field.
. Select the output column.
. Select the input column again.
. Verify that the constraint value is missing.

Workaround: None.


.The undo and redo operations do not work properly when you delete a node in decision requirements graph (DRG) [https://issues.redhat.com/browse/RHDM-1459[RHDM-1459]]

Issue: In a model containing multiple decision requirement diagrams (DRDs), the undo and redo operations do not work properly when you delete a node in the decision requirements graph (DRG).

Steps to reproduce:

. Move the node to a DRD.
. Navigate to DRG.
. Delete the node from the DRG.
. Undo the changes.

Expected result: You can perform the undo and redo operations in DRG.

Actual result: You receive an error. When you confirm, the DRG is broken.

Workaround: None.

.The undo and redo operations are lost when you switch between the diagrams [https://issues.redhat.com/browse/RHDM-1458[RHDM-1458]]

Issue: In a model containing multiple decision requirement diagrams (DRDs), the undo and redo operations are lost when you switch between the diagrams.

Steps to reproduce:

. Open a DMN file with two or more decision requirement diagrams (DRDs).
. Make some changes. For example, move a node in one diagram.
. Switch to another diagram.
. Click *Undo* or press *Ctrl+Z*.
+
The undo and redo operations are lost and nothing changes.

Workaround: None.

.In {CENTRAL}, the DMN editor is unable to save the changes in the Properties panel [https://issues.redhat.com/browse/RHDM-1456[RHDM-1456]]

Issue: When you change the name property in the *Properties* panel, try to save the changes, and reopen the editor, the DMN editor is unable to save the changes.

Steps to reproduce:

. Create a DMN file.
. Change the name of the DMN file in the *Properties* panel.
. Click *Save*.
+
You receive *You have no unsaved changes* alert window.
. Close the DMN editor.
. Reopen the asset and check the the *Properties* panel.
+
The changes are not saved.

Workaround: None.

.DMN editor is reporting unsaved changes in the DMN files when there are no changes [https://issues.redhat.com/browse/RHDM-1453[RHDM-1453]]

Issue: When you open a DMN file in {CENTRAL} and try to close the file without any changes, the DMN editor reports unsaved changes in the DMN files.

Steps to reproduce:

. In Business Central, go to *Menu → Design → Projects*.
. Click *Try samples*.
. Open *Traffic_Violation* project.
. Open *Traffic Violation* DMN file.
. Close the editor.
+
You receive an *Unsaved changes* error pop-up.

Workaround: None.

== Decision engine

.`testDoubleNaN` fails after jitting on `TypeCoercionTest` [https://issues.redhat.com/browse/RHDM-1470[RHDM-1470]]

Issue: You receive an `AssertionError` error in `org.drools.modelcompiler.TypeCoercionTest#testDoubleNaN` when a constraint is jitted.

Steps to reproduce:

. Run the following command in `org.drools.modelcompiler` module:
+
[source]
----
mvn clean install -Dtest=org.drools.modelcompiler.TypeCoercionTest#testDoubleNaN* -Ddrools.jittingThreshold=0
----

Workaround: None.

== High-availability {CENTRAL} on premise

.You cannot create multiple processes at the same time [https://issues.redhat.com/browse/RHPAM-3202[RHPAM-3202]]

Issue: When you create multiple processes at the same time, you receive an error message and multiple processes are not created.

Steps to reproduce:

. Create multiple processes at the same time.
+
You receive an *Activity not found* error.

Workaround: None.

.When you create a project, base-kie-project is created instead of the real name of the project [https://issues.redhat.com/browse/RHPAM-3193[RHPAM-3193]]

Issue: When you create a project, a project with the name *base-kie-project* is created instead of the real name of the created project.

Steps to reproduce:

. Create multiple projects with multiple users in the same space.
+
The *base-kie-project* project is created.

Workaround: Delete and recreate the project or rename the project name from *Settings* tab.

.You cannot create multiple projects at the same time [https://issues.redhat.com/browse/RHPAM-3192[RHPAM-3192]]

Issue: When you create multiple projects at the same time, you receive an error message and multiple projects are not created.

Steps to reproduce:

. Create multiple projects at the same time.
+
You receive an error.

Workaround: None.
