[id='rn-BAMOE-8.0.2-known-issues-ref']
= Known limitations in {PRODUCT} 8.0.2

This section lists known limitations with {PRODUCT} 8.0.1.

[NOTE]
====
Review the information on the https://www.ibm.com/support/pages/node/6596921[IBM Business Automation Manager Open Editions {ENTERPRISE_VERSION} known limitations] page for limitations identified after release.
====

== {OPENSHIFT}

.PostgreSQL 13 Pod won't start because of an incompatible data dirctory [https://issues.redhat.com/browse/RHPAM-4464[RHPAM-4418]]

Issue: When you start a PostgreSQL pod after you upgrade the operator, the pod fails to start and you receive the following message:

`Incompatible data directory. This container image provides
PostgreSQL '13', but data directory is of
version '10'.
This image supports automatic data directory upgrade from
'12', please carefully consult image documentation
about how to use the '$POSTGRESQL_UPGRADE' startup option.`

Workaround:

. Check the version of PostgreSQL:
+
[source]
----
$ postgres -V
----

. If the PostgreSQL version returned is 12.x or earlier, upgrade PostgreSQL:
+
[cols="30%,15%,55%" frame="all", options="header"]
|===
| {PRODUCT} version
| PostgreSQL version
| Upgrade instructions

| 8.0.1 | 7.10 | Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/12#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 12.x.

| 8.0.2 | 7.10 | 1. Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/12#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 12.x.

2. Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/13#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 13.x.

| 8.0.2 | 7.12 |
Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/13#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 13.x.
|===

. Verify that PostpreSQL has been upgraded to your required version:
+
[source]
----
$ postgres -V
----
