[id='rn-BAMOE-8.0.1-known-issues-ref']
= Known limitations in {PRODUCT} 8.0.1
This section lists known limitations with {PRODUCT} 8.0.1.

[NOTE]
====
Review the information on the https://www.ibm.com/support/pages/node/6596921[IBM Business Automation Manager Open Editions {ENTERPRISE_VERSION} known limitations] page for limitations identified after release.
====

== {CENTRAL}

.Unable deploy {CENTRAL} using JDK version 11.0.16 [https://issues.redhat.com/browse/RHPAM-4497[RHPAM-4497]]

Issue: It is not possible to deploy {CENTRAL} if your installation uses JDK version 11.0.16.

Actual result: {CENTRAL} does not deploy when launched.

Expected result: {CENTRAL} deploys successfully.

Workaround: Use a previous JDK version such as 11.0.5 or earlier.

== Form Modeler

.Date type process variable is empty when the process is started using {CENTRAL} form with the `showTime` set to `false` [https://issues.redhat.com/browse/RHPAM-4514[RHPAM-4514]]

Issue: When you use the default form rendering in {CENTRAL} and the process variable field has `showTime=false`, the started process instance shows that the variable is empty. The affected types are `java.time.LocalDateTime`, `java.time.LocalDate`, `java.time.LocalTime`, and `java.util.Date`.

Steps to reproduce:

. Define the process variable with a specific type.
. Generate a form.
. Open a form and set `showTime=false` for a specified field.
. Deploy the project.
. Open the process form.
. Specify the value in the process form.
. Check the process instance variables. The value for the specified variable is empty.

Workaround: None.

.Form in KIE Server with a `java.util.Date` field does not allow to insert time part [https://issues.redhat.com/browse/RHPAM-4513[RHPAM-4513]]

Issue: When a process has a variable of the type `java.util.Date` and the value of the `showTime` attribute is `true`, in the generated form the process does not allow the time to be inserted. The `Date` variable shows all zeros in the time part of the data type.

Workaround: None.

== Installer

.[UI] Installer contains "Business Optimizer support" [https://issues.redhat.com/browse/RHPAM-4555[RHPAM-4555]]

Issue: The {PRODUCT} installer contains an option for Business Optimizer support.

Steps to reproduce:

. Download the `bamoe-installer-8.0.1.jar` file.
. Run `java -jar bamoe-installer-8.0.1.jar`.
. On the *Component Installation* screen, select *Use Custom Configuration for Server Configuration*.

Actual result: On the *KIE Server Properties Configuration* screen, the *Enable Business Optimizer support* option is present.

Expected result: On the *KIE Server Properties Configuration* screen, the *Enable Business Optimizer support* option is not present.

Workaround: None.


== Process Designer

.Bpmn2 files in XML editor have *Properties* panel that contains a data from other processes [https://issues.redhat.com/browse/RHPAM-4468[RHPAM-4468]]

Issue: If two processes are open, where one process is open in the XML editor (legacy process with bpmn2 extension) and one process is open in the new process designer, the properties in the *Properties* panel, as well as the diagram in the *Explore Diagram* window from the new process designer, are shown in the XML editor of the other process. The XML editor should not have any *Properties* or *Diagram* panel.

Steps to reproduce:

. Open any new process designer process.
. Do not close the process.
. Open the legacy `legacy.bpmn2` process in the XML editor and open the *Properties* panel.

Actual result: The *Properties* and *Explore diagram* from a new process designer process are shown in the XML editor panel.

Expected result: No *Properties* or *Explore diagram* panels are present in the XML editor.

Workaround: None.

.Custom data object in the multiple variables causes an error in a case project [https://issues.redhat.com/browse/RHPAM-4422[RHPAM-4422]]

Issue: The custom data object in the multiple variables causes an error in a case project. You receive a UI exception with the following error:

[source]
----
Uncaught exception: Exception caught: Duplicate value: CustomDataObject [com.myspace.caseproject] Caused by: Duplicate value: CustomDataObject [com.myspace.caseproject]
----

Steps to reproduce:

. Create a case definition in a case project.
. Create a custom data object in the same project.
. Add a `procVar` process variable and `caseVar` case file variable with the same `CustomDataObject` type.
. Save the changes.
. Create a multiple instance node or a *Data Object* on the canvas.
. In the multiple instance node, set *MI Collection input/output* and try to change the *Data Input/Output* type. In the *Data Object* on canvas, try to change the data type.

Actual result:

* On a Chrome browser: It is not possible to set the type with the first click. The custom type is chosen.
* On a Firefox browser: An unexpected error occurs.

Expected result: It is possible to set the type properly. No errors occur.

Workaround: None.

== Red Hat Fuse integration
.Optaplanner dependencies were not removed from features file [https://issues.redhat.com/browse/RHPAM-4545[RHPAM-4545]]

Issue: OptaPlanner JAR files are still referenced as dependencies in Fuse features files, even though OptaPlanner is no longer available. If you try to install `kie-server-client` or `kie-camel` by feature file in Fuse, the installation fails because the dependencies do not exist.

Workaround: Instead of using the Karaf OSGI feature files for {PRODUCT} and Fuse integration, directly communicate with Kie Server services with Rest calls. Note that OSGI integration is deprecated and therefore not recommended.

== Migration

.Wrong SQL Statements in Upgrade Script to BAMOE 8.0.1 [https://issues.redhat.com/browse/RHPAM-4540[RHPAM-4540]]

Issue: A merge for the fix to RHPAM-4540 was performed in the wrong order. This caused the wrong SQL statements to be added to the upgrade scripts for the following databases:

* Oracle
* MS SQL Server
* Postgres
* Postgres Plus/EDB
* Sybase

NOTE: This issue only affects the upgrade scripts. You can use the scripts located in the `ddl-scripts` folder to perform a new installation.

Workaround:
To upgrade, use the corresponding DDL scripts located at https://github.com/kiegroup/jbpm/tree/7.67.x/jbpm-db-scripts/src/main/resources/db/upgrade-scripts (scripts `rhpam-7.13-to-7.13.1.sql`). These upgrade scripts resolve this issue as well as the issue described in https://issues.redhat.com/browse/RHPAM-4253[RHPAM-4253].

== Red Hat build of OptaPlanner

.kie-bom contains optaplanner dependencies [https://issues.redhat.com/browse/RHPAM-4556[RHPAM-4556]]

Issue: The {PRODUCT} `org.kie-kie-parent-7.67.2.Final-8.0.1/kie-bom/pom.xml` sources file contains dependency management for the following components:

* `kie-server-services-optaplanner`
* `kie-server-rest-optaplanner`
* `kie-server-spring-boot-starter-optaplanner`

Workaround: None.

.Archtype with appType=planner in kie-archetypes [https://issues.redhat.com/browse/RHPAM-4557[RHPAM-4557]]

Issue: The `org.kie-kie-api-parent-7.67.2.Final-8.0.1/kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy` file
contains `<artifactId>kie-server-spring-boot-starter-optaplanner</artifactId>`
that will generate a project with a Red Hat build of OptaPlanner Spring Boot starter.

Actual result: If you try to compile the OptaPlanner Spring Boot starter, it will fail because there are no OptaPlanner artifacts.

Expected result:  The `org.kie-kie-api-parent-7.67.2.Final-8.0.1/kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy` file should not contain `<artifactId>kie-server-spring-boot-starter-optaplanner</artifactId>`.

Workaround: Do not compile the Red Hat build of OptaPlanner Spring Boot starter.

== {OPENSHIFT}

.PostgreSQL 13 Pod won't start because of an incompatible data dirctory [https://issues.redhat.com/browse/RHPAM-4464[RHPAM-4418]]

Issue: When you start a PostgreSQL pod after you upgrade the operator, the pod fails to start and you receive the following message:

`Incompatible data directory. This container image provides
PostgreSQL '13', but data directory is of
version '10'.
This image supports automatic data directory upgrade from
'12', please carefully consult image documentation
about how to use the '$POSTGRESQL_UPGRADE' startup option.`

Workaround:

. Check the version of PostgreSQL:
+
[source]
----
$ postgres -V
----

. If the PostgreSQL version returned is 12.x or earlier, upgrade PostgreSQL:
+
[cols="30%,15%,55%" frame="all", options="header"]
|===
| {PRODUCT} version
| PostgreSQL version
| Upgrade instructions

| 8.0.1 | 7.10 | Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/12#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 12.x.

| 8.0.2 | 7.10 | 1. Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/12#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 12.x.

2. Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/13#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 13.x.

| 8.0.2 | 7.12 |
Follow the instructions in https://github.com/sclorg/postgresql-container/tree/master/13#upgrading-database-by-switching-to-newer-postgresql-image-version[Upgrading database (by switching to newer PostgreSQL image version)] to upgrade to PostgreSQL 13.x.
|===

. Verify that PostpreSQL has been upgraded to your required version:
+
[source]
----
$ postgres -V
----
