[id='rn-deprecated-issues-ref']

= Deprecated components

The components listed in this section have been deprecated.

ifdef::DM[]

== Unified product deliverable and deprecation of {PRODUCT} distribution files

In Red Hat Process Automation Manager 7.13 release, the distribution files for {PRODUCT} will be replaced with Red Hat Process Automation Manager files. Note that there will not be any change to the {PRODUCT} subscription and the support entitlements and fees will remain the same. {PRODUCT} is a subset of Red Hat Process Automation Manager, and {PRODUCT} subscribers will continue to receive full support for the decision management and optimization capabilities. The business process management (BPM) capabilities are exclusive to Red Hat Process Automation Manager and will be available for use by {PRODUCT} subscribers but with development support services only. {PRODUCT} subscribers can upgrade to a full Red Hat Process Automation Manager subscription at any time to receive full support for BPM features.

endif::DM[]

<<<<<<< HEAD
=======
== Red Hat Enterprise Linux 7

Support for Red Hat Enterprise Linux 7 is deprecated in {PRODUCT} and features and will be removed in a future release.

== Support for JDK 8

Support for JDK 8 is deprecated in {PRODUCT} and might be removed in a future release.

ifdef::PAM[]
For a complete list of supported JDK configurations, see https://access.redhat.com/articles/3405381[Red Hat Process Automation Manager 7 Supported Configurations].
endif::PAM[]

ifdef::DM[]
For a complete list of supported JDK configurations, see https://access.redhat.com/articles/3354301[Red Hat Decision Manager 7 Supported Configurations].
endif::DM[]

>>>>>>> 689fa946d (BXMSDOC-8517 removed Business Optimizer)
== Legacy kie-pmml dependency

The legacy `kie-pmml` dependency is deprecated in {PRODUCT} {ENTERPRISE_VERSION} and will be replaced in a future {PRODUCT} release.
For more information, see {URL_DEVELOPING_DECISION_SERVICES}#assembly-pmml-models[_{PMML_MODELS}_].

== Support for the RuleUnit API

The {PRODUCT} RuleUnit API is deprecated due to incompatibility with the Kogito RuleUnit API.

==  Legacy Test Scenarios tool
The legacy Test Scenarios tool is deprecated. It will be removed in a future {PRODUCT} release. Use the new Test Scenarios designer instead.

ifdef::PAM[]

== Legacy process designer
The legacy process designer in {CENTRAL} is deprecated. The legacy process designer does not receive any new enhancements or features. If you intend to use the new process designer, start migrating your processes to the new designer and create new processes in the new process designer. For information about migrating projects to the new designer, see {URL_DEPLOYING_AND_MANAGING_SERVICES}#migrating-from-legacy-designer-proc[{MANAGING_PROJECTS}].

endif::PAM[]
