[id='rn-deprecated-issues-ref']

= Deprecated components

The components listed in this section have been deprecated.

ifdef::DM[]

== Unified product deliverable and deprecation of {PRODUCT} distribution files

In Red Hat Process Automation Manager 7.13 release, the distribution files for {PRODUCT} will be replaced with Red Hat Process Automation Manager files. Note that there will not be any change to the {PRODUCT} subscription and the support entitlements and fees will remain the same. {PRODUCT} is a subset of Red Hat Process Automation Manager, and {PRODUCT} subscribers will continue to receive full support for the decision management and optimization capabilities. The business process management (BPM) capabilities are exclusive to Red Hat Process Automation Manager and will be available for use by {PRODUCT} subscribers but with development support services only. {PRODUCT} subscribers can upgrade to a full Red Hat Process Automation Manager subscription at any time to receive full support for BPM features.

endif::DM[]

== Legacy kie-pmml dependency

The legacy `kie-pmml` dependency is deprecated in {PRODUCT} {ENTERPRISE_VERSION} and will be replaced in a future {PRODUCT} release.
For more information, see {URL_DEVELOPING_DECISION_SERVICES}#assembly-pmml-models[_{PMML_MODELS}_].

== Support for the RuleUnit API

The {PRODUCT} RuleUnit API is deprecated due to incompatibility with the Kogito RuleUnit API.

==  Legacy Test Scenarios tool
The legacy Test Scenarios tool is deprecated. It will be removed in a future {PRODUCT} release. Use the new Test Scenarios designer instead.

== Support for HACEP

High available (HA) event-driven decisioning, including Complex Event Processing (CEP), is deprecated due to end of support for {AMQ_STREAMS} 1.x.

== Support for OSGi framework integration
Support for integration with the OSGi framework is deprecated. It does not receive any new enhancements or features and will be removed in a future release. The decision and process engine integration with the OSGi framework is currently incompatible in Fuse version 7.8.
