[id='rn-deprecated-issues-ref']
= Deprecated and removed components

The components listed in this section have been deprecated or removed.

==  Legacy Test Scenarios tool
The legacy Test Scenarios tool was deprecated with {PRODUCT} 7.3.0. It will be removed in a future {PRODUCT} release. Use the new Test Scenarios designer instead.

== Legacy process designer
The legacy process designer in {CENTRAL} is removed in {PRODUCT} 7.6.0. The legacy process designer will not receive any new enhancements or features. If you intend to use the new process designer, start migrating your processes to the new designer. Create all new processes in the new process designer. For information about migrating projects to the new designer, see {URL_MANAGING_PROJECTS}#migrating-from-legacy-designer-proc[{MANAGING_PROJECTS}].

== Support for {OPENSHIFT} 3.x
Starting with the 7.5 release of {PRODUCT}, support for {OPENSHIFT} 3.x, including using all templates to install {PRODUCT}, is deprecated. Support for {OPENSHIFT} 3.x will be removed in a future {PRODUCT} release. Consider deploying {PRODUCT} using the operator on {OPENSHIFT} 4.x.

== Supported languages
Starting with the 7.7 release, the {PRODUCT} user interface will be localized in English, Spanish, French, and Japanese only. Support for other languages that exist in the product will be deprecated.
