[id='rn-deprecated-issues-ref']

= Deprecated components

The components listed in this section have been deprecated.

== {PLANNER_SHORT} 7

Both {PLANNER_SHORT} 7 and {PLANNER_SHORT} 8 are included with {PRODUCT} {PRODUCT_VERSION}, but {PLANNER_SHORT} 7 is deprecated and might be removed in a future release. For information about migrating your {PLANNER_SHORT} 7 projects to {PLANNER_SHORT} 8, see {URL_DEVELOPING_SOLVERS}#assembly-optimizer-migration-8_{context}[_{PLANNER8_MIGRATION}_].

== {PLANNER_SHORT} tooling components in {CENTRAL}

The following {PLANNER_SHORT} tooling in {CENTRAL} is part of {PLANNER_SHORT} 7. It is deprecated and might be removed in a future release.

* Data modeler annotations
* Guided rule editor actions for {PLANNER_SHORT} score modification
* Solver assets

== Support for JDK 8

Support for JDK 8 is deprecated from {PRODUCT} and might be removed in a future release.

ifdef::PAM[]
For a complete list of supported JDK configurations, see https://access.redhat.com/articles/3405381[Red Hat Process Automation Manager 7 Supported Configurations].
endif::PAM[]

ifdef::DM[]
For a complete list of supported JDK configurations, see https://access.redhat.com/articles/3354301[Red Hat Decision Manager 7 Supported Configurations].
endif::DM[]

== Legacy `kie-pmml` dependency

The legacy `kie-pmml` dependency was deprecated with {PRODUCT} 7.10.0 and will be replaced in a future {PRODUCT} release.
For more information, see {URL_DEVELOPING_DECISION_SERVICES}#assembly-pmml-models[_{PMML_MODELS}_].

== Support for OSGi framework integration

Support for integration with the OSGi framework is deprecated in {PRODUCT}. It does not receive any new enhancements or features and will be removed in a future release. The decision and process engine integration with the OSGi framework is currently incompatible in {FUSE} version 7.8. If you intend to use the OSGi framework, continue to use {PRODUCT} version 7.9 with {FUSE} version 7.7 until {FUSE} version 7.9 is available and certified.

== Support for the RuleUnit API

The {PRODUCT} RuleUnit API is now deprecated due to incompatibility with the Kogito RuleUnit API.

==  Legacy Test Scenarios tool
The legacy Test Scenarios tool was deprecated in {PRODUCT} version 7.3.0. It will be removed in a future {PRODUCT} release. Use the new Test Scenarios designer instead.

== Support for {OPENSHIFT} 3.x
From {PRODUCT} version 7.5, images and templates for {OPENSHIFT} 3.x are deprecated. The deprecated images and templates are not supported with new features but remain available until the end of {OPENSHIFT} version 3.x support. For more information about the full support lifecycle phase for {OPENSHIFT} version 3.x, see https://access.redhat.com/support/policy/updates/openshift_noncurrent[Red Hat OpenShift Container Platform Life Cycle Policy (non-current versions)].

Consider deploying {PRODUCT} using the operator on {OPENSHIFT} 4.x.

ifdef::PAM[]

== Legacy process designer
The legacy process designer in {CENTRAL} was deprecated in {PRODUCT} 7.6.0. The legacy process designer does not receive any new enhancements or features. If you intend to use the new process designer, start migrating your processes to the new designer and create new processes in the new process designer. For information about migrating projects to the new designer, see {URL_DEPLOYING_AND_MANAGING_SERVICES}#migrating-from-legacy-designer-proc[{MANAGING_PROJECTS}].

endif::PAM[]
