[id='rn-deprecated-issues-ref']
= Deprecated components

The components listed in this section have been deprecated or removed.


//== Installation

ifdef::PAM[]
== Legacy process designer
The legacy process designer in {CENTRAL} is deprecated in {PRODUCT} 7.4.0. It will be removed in a future {PRODUCT} release. The legacy process designer will not receive any new enhancements or features. If you intend to use the new process designer, start migrating your processes to the new designer. Create all new processes in the new process designer. For information about migrating to the new designer, see {URL_MANAGING_PROJECTS}#migrating-from-legacy-designer-proc[_{MANAGING_PROJECTS}_].

endif::PAM[]

== Legacy Test Scenarios tool
The legacy Test Scenarios tool was deprecated with {PRODUCT} 7.3.0. It will be removed in a future {PRODUCT} release. Use the new Test Scenarios designer instead.

== Google Charts
In {PRODUCT} 7.3.0, the `https://c3js.org/[C3]` chart library replaced the Google Charts library as the default chart library in {CENTRAL}. With {PRODUCT} 7.4.0, Google Charts is no longer available in {CENTRAL}.
