[id='rn-deprecated-issues-ref']

= Deprecated components

The components listed in this section have been deprecated.

==  Legacy Test Scenarios tool
The legacy Test Scenarios tool was deprecated in {PRODUCT} 7.3.0. It will be removed in a future {PRODUCT} release. Use the new Test Scenarios designer instead.

== Support for {OPENSHIFT} 3.x
From {PRODUCT} version 7.5, images and templates for {OPENSHIFT} 3.x are deprecated. The deprecated images and templates are not supported with new features but remain available until the end of {OPENSHIFT} version 3.x support. For more information about the full support lifecycle phase for {OPENSHIFT} version 3.x, see https://access.redhat.com/support/policy/updates/openshift_noncurrent[Red Hat OpenShift Container Platform Life Cycle Policy (non-current versions)].

Consider deploying {PRODUCT} using the operator on {OPENSHIFT} 4.x.

== Legacy process designer
The legacy process designer in {CENTRAL} was deprecated in {PRODUCT} since 7.6.0. The legacy process designer will not receive any new enhancements or features. If you intend to use the new process designer, start migrating your processes to the new designer. and create new processes in the new process designer. For information about migrating projects to the new designer, see {URL_MANAGING_PROJECTS}#migrating-from-legacy-designer-proc[{MANAGING_PROJECTS}].

ifdef::PAM[]
== Support for Entando AppBuilder
From August 31st, 2020, {PRODUCT} {ENTERPRISE_VERSION} will no longer include entitlements for Entando AppBuilder. Red Hat will not provide the support for Entando AppBuilder thereafter. The feature references and documentation will not be available from 7.9 release.
endif::[]
