[id='rn-deprecated-issues-ref']
= Deprecated and removed components

The components listed in this section have been deprecated or removed.

== Incremental Maven repository
The incremental Maven repository has been removed from the {PRODUCT} {PRODUCT_VERSION} distribution in favor of the full {PRODUCT} {PRODUCT_VERSION} Maven Repository available from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required).

==  Legacy Test Scenarios tool
The legacy Test Scenarios tool was deprecated with {PRODUCT} 7.3.0. It will be removed in a future {PRODUCT} release. Use the new Test Scenarios designer instead.

//BAPL-1388

== Support for {OPENSHIFT} 3.x
Starting with the 7.5 release of {PRODUCT}, support for {OPENSHIFT} 3.x, including installation using all templates and using the Automation Broker (Ansible Playbook) is deprecated. Support for {OPENSHIFT} 3.x will be removed in a future {PRODUCT} release. Consider deploying {PRODUCT} using the Operator.
