
[id='rn-intro-con']

= Product overview

ifdef::PAM[]
{PRODUCT} is an open-source business automation platform that combines business process management (BPM), case management, business rules management, and resource planning. It enables business and IT users to create, manage, validate, and deploy business processes, cases, and business rules.

{PRODUCT} uses a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic and business processes without requiring assistance from IT personnel.

{PRODUCT} {PRODUCT_VERSION} provides increased stability, several fixed issues, and new features.

{PRODUCT} is fully supported on {OPENSHIFT} and can be installed on various platforms.

endif::PAM[]

ifdef::DM[]

{PRODUCT} is an open-source decision management platform that combines business rules management, complex event processing, Decision Model & Notation (DMN) execution, and {PLANNER} for solving planning problems. It automates business decisions and makes that logic available to the entire business.

Business assets such as rules, decision tables, and DMN models are stored in a central repository. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.

{PRODUCT} {PRODUCT_VERSION} provides increased stability, several fixed issues, and new features.

{PRODUCT} is fully supported on {OPENSHIFT} and can be installed on various platforms.
endif::DM[]


[NOTE]
====
{PRODUCT} requires Java 11 or later.
====

For information about the support policy for {PRODUCT}, see the https://access.redhat.com/articles/3639591[_Release maintenance plan for Red Hat Decision Manager 7.x and Red Hat Process Automation Manager 7.x_].
