[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.


ifdef::DM[]

endif::[]

== {CENTRAL}

.You cannot add a new group in {CENTRAL} integrated with RH-SSO [https://issues.jboss.org/browse/RHPAM-2036[RHPAM-2036]]

Issue: The following exception occurs when you try to add a new group in {CENTRAL} if {CENTRAL} is integrated with RH-SSO 7.3.0:
[source]
----
java.lang.NoSuchMethodError:org.keycloak.representations.idm.RoleRepresentation.setScopeParamRequired(Ljava/lang/Boolean;)
----

Steps to reproduce:

. Open {CENTRAL}.
. Open the *Admin* page.
. Open *Groups*.
. Try to create a new group.


Expected result: The new group is created.

Actual result: A dialog box with the listed exception appears.

Workaround: Add the group in RH-SSO instead of adding it in {CENTRAL}.


.When you create an asset, the package drop-down button does not appear immediately [https://issues.jboss.org/browse/RHPAM-2133[RHPAM-2133]]

Issue: When you create an asset, the package drop-down button is invisible and an error about package selection appears.

Steps to reproduce:

. Create a project in {CENTRAL}.
. Try to create a business process.

Expected result: The package drop-down button is visible and you can create the business process.

Actual result: The package drop-down button is initially invisible and it appears after several seconds.

Workaround: Wait until the package drop-down button is visible or reopen the dialog window for asset creation.

ifdef::PAM[]



== Process designer

.Human task comments are not retained when a process instance is finished [https://issues.jboss.org/browse/RHPAM-2258[RHPAM-2258]]

Issue: Human task comments are retained and visible only while the respective process instance is running. When the process instance is completed or aborted, comments from human tasks disappear even though the tasks are still visible in {CENTRAL}.

Steps to reproduce:

. Start a process instance with two consecutive human tasks.
. Comment on the first human task.
. Claim, start, and complete the first task.
. Check the *Comments* tab of the human task to confirm that the comments are retained for the completed task.
. Abort the process instance or complete the task preventing the instance from finishing.
. Navigate to the log file for the first task again.

Expected result: Data about the first task is available in the *Comments* tab of the human task .

Actual result: The first task is still available in {CENTRAL} but no data is available in the log file.

Workaround: None.


.Greater than (>) and less than (<) symbols in data types break a process [https://issues.jboss.org/browse/RHPAM-2193[RHPAM-2193]]

Issue: If you place greater than (>) and less than (<) symbols in a data type for a process variable,  you cannot reopen the process. The XML editor appears instead.

Steps to reproduce:

. Create a process and add the `list1:java.util.List<String>` process variable.
. Save and reopen the process.

Expected result: The process opens.

Actual result: The process does not open.

Workaround: None.


.If a case task actor is invalid, the resulting BPMN file is also invalid [https://issues.jboss.org/browse/RHPAM-2240[RHPAM-2240]]

Issue: The new process designer sometimes generates an invalid XML file. A user task with an actor assigned is generated as a a `potentialOwner` element in the XSD file.

[source]
----
<bpmn2:potentialOwner id="5058b718-8866-4ccd-b793-d5ebf48de5a2">
<bpmn2:resourceAssignmentExpression id="_gN_feI4_Eem2-an8Fwu06w">
<bpmn2:formalExpression id="_gN_feY4_Eem2-an8Fwu06w">manager</bpmn2:formalExpression>
</bpmn2:resourceAssignmentExpression>
</bpmn2:potentialOwner>
----

The id of the `potentialOwner` element is missing an underscore at the beginning, which means that if the first element is a number, this is now an invalid ID.

Tasks that have `ioSpecification` should always define an `inputSet` and `outputSet`, even if those are empty.

Steps to reproduce:

Create a user task with no output mapping. This will generate the following output:

[source]
----
<bpmn2:ioSpecification id="_rEnOQY5AEem2-an8Fwu06w">
<bpmn2:dataInput id="38B29C0C-6BD8-4275-ACCE-D5D97DEBB2CB_TaskNameInputX" drools:dtype="Object" itemSubjectRef="_38B29C0C-6BD8-4275-ACCE-D5D97DEBB2CB_TaskNameInputXItem" name="TaskName"/>
<bpmn2:dataInput id="38B29C0C-6BD8-4275-ACCE-D5D97DEBB2CB_SkippableInputX" drools:dtype="Object" itemSubjectRef="_38B29C0C-6BD8-4275-ACCE-D5D97DEBB2CB_SkippableInputXItem" name="Skippable"/>
<bpmn2:inputSet id="_rEnOQo5AEem2-an8Fwu06w">
<bpmn2:dataInputRefs>_38B29C0C-6BD8-4275-ACCE-D5D97DEBB2CB_TaskNameInputX</bpmn2:dataInputRefs>
<bpmn2:dataInputRefs>_38B29C0C-6BD8-4275-ACCE-D5D97DEBB2CB_SkippableInputX</bpmn2:dataInputRefs>
</bpmn2:inputSet>
</bpmn2:ioSpecification>
----

Expected result: The output includes an empty `outputSet` attribute.

Actual result: The output does not include an `outputSet` attribute.

Workaround: None.


.Nodes and distribution lines do not fully align horizontally [https://issues.jboss.org/browse/RHPAM-2241[RHPAM-2241]]

Issue: It is difficult to precisely align some nodes horizontally.


Steps to reproduce:

. Create a process.
. Try to align a node and connector horizontally.

Expected result: The node and connector are aligned.

Actual result: The node and connector are not aligned.

Workaround: None.

.The multiple instance properties of a multiple instance subprocess are not visible for nodes inside of a multiple instance subprocess [https://issues.jboss.org/browse/RHPAM-2257[RHPAM-2257]]

Issue: If you model a process with a multiple instance subprocess as a multiple instance node, the multiple instance Data Input and multiple instance Data Output variables are not visible for nodes inside of the multiple instance subprocess.

Steps to reproduce:

. Create a multiple instance subprocess for execution by selecting the multiple instance collection input/output from an existing process level list and setting new variables for multiple instance data input and output.
. Add a user task inside of the multiple instance subprocess.
. Try to configure  a user task so that is uses multiple instance data input/output.

Expected result: The new variables for multiple instance data input and output are listed in the data I/O editor *Source* and *Target* fields and you can use the new variables for multiple instance data input and output.

Actual result: The new variables for multiple instance data input and output are not listed in the data I/O editor *Source* and *Target* fields.

Workaround: To use variables for multiple instance data input and output, define them in *Process Data* -> *Process Variables* before creating the multiple instance subprocess for execution.

.Data output associations do not work correctly when they are declared twice [https://issues.jboss.org/browse/RHPAM-2242[RHPAM-2242]]

Issue: If the data output variable associated with a user task is declared twice, it is not stored in the resulting XML file.

Steps to reproduce:

. In {CENTRAL}, create a user task.
. Open the *Properties* panel.
. Expand the *Implementation/Execution* section.
. Click *Assignments*.
. In the *Data Outputs and Assignment* area, add a data output variable twice by using the same variable name.

Expected result: Two variables with the same name are stored in the BPMN XML file.

Actual result: The variables are not stored in the resulting BPMN XML file (XML) so when the process runs or loads, the data output assignments are missing.

Workaround: None.

== {PROCESS_ENGINE_CAP}
.Task operations are slow [https://issues.jboss.org/browse/RHPAM-2259[RHPAM-2259]]

Issue: Task operations such as *Start*, *Complete*, or *Claim* are noticeably slower when the {KIE_SERVER} API or `UserTaskService` is used. This issue appeared when a join was added to the `getTaskInstanceById` query. The performance of these operations will be restored to the previous state in a future patch release.


endif::[]

== {OPENSHIFT}
.Validation sub-element is missing for data sources [https://issues.jboss.org/browse/RHPAM-2226[RHPAM-2226]]

Issue: If you create a custom template for deploying {KIE_SERVER} on {OPENSHIFT}
and the server uses a MySQL or PostgreSQL database, {KIE_SERVER} data sources do not contain the validation sub-element where connection checkers and exception sorters are defined.

Steps to reproduce:

. Create a custom template for deploying {KIE_SERVER} on {OPENSHIFT}
with a MySQL or PostgreSQL database.
. View the contents of the template file.

Expected result: The template contains the expected data sources.

Actual result: The template does not contain the expected data sources.

Work around:

Add the following environment variables and values to your templates:

* For MySQL:
+
[source]
----
name: RHPAM_CONNECTION_CHECKER
value: "org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLValidConnectionChecker"
name: RHPAM_EXCEPTION_SORTER
value: "org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLExceptionSorter"
----

* For PostgreSQL:
+
[source]
----
name: RHPAM_CONNECTION_CHECKER
value: "org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker"
name: RHPAM_EXCEPTION_SORTER
value: "org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter"
----


== Test scenarios

.Test scenarios designer can not access the parent data object fields [https://issues.jboss.org/browse/RHDM-1014[RHDM-1014]]

Issue: Test scenarios designer cannot access a parent data object field, even if the field has public `getter` and `setter` attributes.

Steps to reproduce:

. Create a scenario with a field that is declared in the parent class.
. Run the scenario.
. Click *View Alerts* and review any alerts.

Expected result: The scenario runs successfully.

Actual result: The scenario fails because it cannot access the data object in the parent class.


Workaround: Include the data object in the child class.

.Rule-based test scenarios that contain maps of simple types fail [https://issues.jboss.org/browse/RHDM-1015[RHDM-1015]]

Issue: All rule-based test scenarios that contain a map of simple types as a cell value, for example `Map<String` or `String`, fail.

Steps to reproduce:

. Create a scenario.
. Create a map with a simple type value, for example `Map<String, String>`.
. Run the scenario.

Expected result: The scenario runs successfully.

Actual result: The scenario fails.

Workaround: None.
