[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

.Cannot upload a spreadsheet that contains a large decision table [https://issues.jboss.org/browse/RHDM-488[RHDM-488]]

Issue: If you try to upload a spreadsheet that contains a large decision table into {CENTRAL}, an out of memory error appears in the `error.log` file.

Steps to reproduce:

. Create a spreadsheet that contains a large decision table.
. Create a new project in {CENTRAL}.
. Click *Add Asset* and then select *Spreadsheet Decision Table*.`
. Attach the spreadsheet that contains the large decision table.
. Review the server `error.log` file.

Actual result: An out of memory error appears in the `error.log` file.

Workaround: None.

== {KIE_SERVER}

.Cannot deploy a KJAR with a PMML asset to a {KIE_SERVER} Spring Boot starter on Windows [https://issues.jboss.org/browse/RHDM-852[RHDM-852]]

Issue: If a KJAR contains a PMML asset, you cannot deploy it as a container on a {KIE_SERVER} that is running the `kie-server-spring-boot-starter` Spring Boot starter on Microsoft Windows.

Steps to reproduce:

. Create a KJAR that contains a PMML asset.
. Start `kie-server-spring-boot-starter` on Windows.
. Deploy the KJAR to a {KIE_SERVER} that is running the `kie-server-spring-boot-starter` Spring Boot starter on Microsoft Windows.

Expected result: The KJAR is deployed successfully.

Actual result: The KJAR cannot be deployed.

Workaround: None.

