[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== Installer
.References to {EAP} 7.1 in the {PRODUCT} installer console [https://issues.jboss.org/browse/RHPAM-803[RHPAM-803]]

Issue: When you run the {PRODUCT} installer from the terminal, there are references to {EAP} 7.1. 

Workaround: When you see {EAP} 7.1, read as {EAP} 7.2.

.WIP: The controller URL is not updated in XML files when only kie-server is being installed [https://issues.jboss.org/browse/RHPAM-1781[RHPAM-1781]]

Issue: When you run the {PRODUCT} installer, and you specify a URL for the controller, the URL is not updated in the {EAP} `standalone.xml` file.

Steps to reproduce:

. Run the {PRODUCT} installer.
. Specify an {EAP} installation for container.
. Select only Process Server to install.
. Select Advanced Configuration and update controller URL.
. Complete the installation.
. Open the {EAP} `standalone.xml` file and find the controller URL.

Expected result: The value of the controller URL property is the URL that you entered during installation.

Actual result: The value of the controller URL property is the default value.

.WIP: Severe exceptions during startup occur due to missing libraries after {PRODUCT} installation on JWS 5.0 [https://issues.jboss.org/browse/RHDM-808[RHDM-808]]

Issue: If you install {PRODUCT} on Red Hat JBoss Web Server 5.0.1, severe exceptions occur when you start {PRODUCT}.

Steps to reproduce:
. Use the installer to install {PRODUCT} on Red Hat JBoss Web Server 5.0.1 and accept the default settings.
. Run `./startup.sh`.

Expected result: {PRODUCT} starts.

Actual result: Exceptions appear in the log files.

== {CENTRAL}

.WIP: {PRODUCT} integrated with Red Hat Single Sign-On ignores user SSH key when working with Git [https://issues.jboss.org/browse/RHPAM-1683[RHPAM-1683]]

Issue: With {PRODUCT} on {EAP} 7.2 integrated with Red Hat Single Sign-On, if you try to clone a project that has an SSH key set using ssh with set ssh-key, you are not able to clone it without password. The ssh key is ignored.

Steps to reproduce:

. Integrate a {PRODUCT} installation with Red Hat Single Sign-On, as described in 
. Use the {PRODUCT} *Admin* -> *SSH Keys* page to add an SSH key.
. Enter the following command in a terminal to add a private SSH key to your `ssh-agent`, where `<SSH-KEY-PATH>` is the path to the SSH key key that you created in the previous step:
+
[source]
----
$ ssh-add <SSH-KEY-PATH>
----
. Use SSH to clone the project, for example:
+
[source]
----
ssh://user@localhost:8001/space/project
----

Expected result: The project is cloned.

Actual result: You cannot clone the project unless you have the SSH key password.


.Several Errai projects contain XSD-invalid `pom.xml` file [https://issues.jboss.org/browse/RHPAM-1742[RHPAM-1742]]
Issue: Maven repository validation identified the following `pom.xml` files in the Errai project which are invalid according to Maven POM XSD:
[source]
----
org/jboss/errai/errai-ioc/4.4.1.Final-redhat-00001/errai-ioc-4.4.1.Final-redhat-00001.pom.xml
org/jboss/errai/errai-navigation/4.4.1.Final-redhat-00001/errai-navigation-4.4.1.Final-redhat-00001.pom.xml
org/jboss/errai/errai-security-server/4.4.1.Final-redhat-00001/errai-security-server-4.4.1.Final-redhat-00001.pom.xml
org/jboss/errai/errai-security-client/4.4.1.Final-redhat-00001/errai-security-client-4.4.1.Final-redhat-00001.pom.xml
org/jboss/errai/errai-common/4.4.1.Final-redhat-00001/errai-common-4.4.1.Final-redhat-00001.pom
----

Workaround: None.

.`kie-soup-dataset-elasticsearch` is an  XSD-invalid `pom.xml` file [https://issues.jboss.org/browse/RHPAM-1743[RHPAM-1743]]
Issue: Maven repository validation identified the `kie-soup-dataset-elasticsearch` `pom.xml` fileas invalid according to Maven POM XSD.

Workaround: None.

.Two `ClassNotFoundExceptions` errors are thrown the first time you open the {CENTRAL} *Data Sources* perspective [https://issues.jboss.org/browse/RHPAM-1741[RHPAM-1741]]
Issue: When you got to the {CENTRAL} *Data Sources* perspective for the first time after a clean installation, the following `ClassNotFoundExceptions` errors appear in the `server.log` file:
[source]
----
org.guvnor.structure.repositories.NewBranchEvent
org.guvnor.structure.repositories.RepositoryUpdatedEvent
----
Steps to reproduce:

. Install {PRODUCT}.
. Log in to {CENTRAL} with the `admin` role.
. Go to *Admin* -> *Datasources*.

Actual result: As soon as you click the *Data Sources* perspective, two errors appear in {EAP} console.

Expected result: No errors appear.

Workaround: Restart {CENTRAL} and go to *Admin* -> *Datasources*. These errors only appear the first time the perspective is clicked after installation.

.WIP: NullPointerException error is thrown when resolving a branch [https://issues.jboss.org/browse/RHPAM-1701[RHPAM-1701]]
Issue: In a {PRODUCT} on premise cluster installation, several NPE errors occur sin the UI and in `sever.log` file.

Workaround: None.

.{PRODUCT} 7.0 and earlier repositories can be imported into {CENTRAL} [https://issues.jboss.org/browse/RHPAM-1768[RHPAM-1768]]
Issue: {PRODUCT} 7.0 and earlier repositories (old structure repositories) that contain more than one project can be imported into {CENTRAL} even though they are not supported. When these repositories are imported, the are not fully migrated and will not perform as expected. 

Steps to reproduce:

. In {PRODUCT} 7.0.0 or earlier, create a repository with two projects.
. Copy repository location from the `.niogit` directory.
. Open {PRODUCT} 7.2.0.
. Click *Library* -> *Import Project*.
. Paste the repository location  select both projects. 

Actual result: The projects are imported but will not perform as expected.

Workaround: Do not import {PRODUCT} 7.0 and earlier repositories (old structure repositories) that contain more than one project.

.A TimeoutException error occurs when logging in to a clustered {CENTRAL} [https://issues.jboss.org/browse/RHPAM-1749[RHPAM-1749]]
Issue: On a clustered {CENTRAL} instance, when logging in to {CENTRAL} an exception is thrown.

Steps to reproduce:

. Create a {CENTRAL} cluster configuration that uses ElasticSearch, AMQ Broker, and has two standalone {CENTRAL} nodes.
. Uncomment the `<distributable/>` tag on both {CENTRAL} nodes.
. Log in to {CENTRAL} on one of the nodes. 

Actual result: An exception is thrown.

Workaround: See the workaround in the https://access.redhat.com/solutions/2776221[JBoss EAP 7 does not process requests for a session in parallel] article.

.WIP: Bulk abort throws an exception when called on several subprocess instances [https://issues.jboss.org/browse/RHPAM-1761[RHPAM-1761]]

Issue: If you have a process with two subprocesses running at the same time and you call bulk abort on both the subprocesses and the parent process instances, you receive an error.

Steps to reproduce:
. Create a process with two subprocess, then start the process and both subprocesses.
. Go to process instances and perform a bulk abort.

Expected result: The process and subprocesses stop running.

Actual result: The following error occurs:
[source]
----
Unable to complete your request. The following exception occurred: "Could not find process instance with id "[26, 25, 24]"".

----

== OpenShift

.Various errors occur when starting clustered {CENTRAL} on OpenShift [https://issues.jboss.org/browse/RHPAM-1747[RHPAM-1747]]

Issue: When clustered {CENTRAL} is started on OpenShift using the `rhpam72-authoring-ha.yaml` template, {CENTRAL} sometimes throws various exceptions that cause the pod to restart or the deployment to fail.

Steps to reproduce:

. Use the `rhpam72-authoring-ha.yaml` template to deploy {PRODUCT} {PRODUCT_VERSION} images on OpenShift .
. Check the {CENTRAL} log files.

Expected result: There are no errors in the log files.

Actual result: Errors appear in the log files, the pod to restarts, or the deployment fails.

Workaround: None.

== {KIE_SERVER}
.A container is removed from the UI even though it was not possible to stop it [https://issues.jboss.org/browse/RHPAM-1698[RHPAM-1698]]

Issue: A container cannot be stopped if it is blocked by an active process instance. However if you attempt to stop a blocked container from the UI, the action throws and exception and the container disappears.

Steps to reproduce:

. Create a project with a process.
. Deploy the project and start the process.
. Go to the *Execution Servers* page and stop the container.

Actual result: The container is removed from the UI even though it is still running.

== Process designer
.WIP: Process designer nested subprocess is not created well and validation fails [https://issues.jboss.org/browse/RHPAM-1732[RHPAM-1732]]

Issue: When a process containing subprocesses is created and saved, the process validation fails.
COMMENT: Please clarify 'process of the figure'.

Steps to reproduce:

. Create the process of the figure.
. Click *Save*.

Expected result: The process and subprocesses are saved.

Actual result: The following validation error appears even though all sequence flows have their source and target within the process.
[source]
----
Sequence flow connectors cannot exceed the embbedded subprocess' bounds. Both source and target nodes must be in same parent process.
----

ifdef::PAM[]
== Maven Repository
.WIP: Missing JWS dependencies in offline maven repo distribution [https://issues.jboss.org/browse/RHPAM-1715[RHPAM-1715]]

Issue: The following key dependencies required to install {KIE_SERVER} on Red Hat JBoss Web Server are missing from the offline Maven repository:
[sources]
----
org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec
org.jboss.integration:narayana-tomcat
org.jboss:jboss-transaction-spi
org.jboss.logging:jboss-logging
----

Workaround:
. Install {PRODUCT} on Red Hat JBoss Web Server.
. In a terminal, change directory to the `<JWS-HOME>/jws-5.0/tomcat/lib` direcory.
. Copy the following files to the offline Maven repository COMMENT: can we be more specific about the directory?:
[source]
----
narayana-tomcat-1.0.0.Final-redhat-1.jar 
jboss-transaction-spi-7.6.0.Final-redhat-1.jar 
----
endif::[]
COMMENT:
Waiting for confirmation to include:
https://issues.jboss.org/browse/RHPAM-1697
https://issues.jboss.org/browse/RHPAM-1554
https://issues.jboss.org/browse/RHPAM-1759
https://issues.jboss.org/browse/RHPAM-1773