[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

.You cannot upload a spreadsheet that contains a large decision table [https://issues.jboss.org/browse/RHDM-488[RHDM-488]]

Issue: If you try to upload a spreadsheet that contains a large decision table into {CENTRAL}, an out-of-memory error appears in the `error.log` file.

Steps to reproduce:

. Create a spreadsheet that contains a large decision table.
. Create a new project in {CENTRAL}.
. Click *Add Asset* and then select *Spreadsheet Decision Table*.
. Attach the spreadsheet that contains the large decision table.
. Review the server `error.log` file.

Actual result: An out-of-memory error appears in the `error.log` file.

Workaround: None.

.An unexpected error occurs if you delete a project that contains a business process [https://issues.jboss.org/browse/RHPAM-1943[RHPAM-1943]]

Issue: If you delete a project that contains a business process, an unexpected error occurs.

Steps to reproduce:

. Create a project in {CENTRAL}.
. Add a business process asset to the project.
. Save the business process asset.
. Delete the business process asset.

Expected result: The business process asset is deleted.

Actual result: An error occurs.

Workaround: None.

ifdef::PAM[]
.The palette of an existing process is not in sync with project settings changes [https://issues.jboss.org/browse/RHPAM-1925[RHPAM-1925]]

Issue: If you enable or disable a service task in the *Administration* page  or install or uninstall a service task in the project's settings *Service tasks* section, when you open the process the palette displays the original state of the service task. If you install a service task, the service task is not shown in the palette. If you uninstall a service task, the service task is still shown in the palette.

Steps to reproduce:

. Create a project.
. Create a process called P1.
. In the project's settings, install a new service task.
. Create a process called P2.
. Verify that the service task is present in the palette of process P2.
. Create a process using the newly added task.
. Go to process P1.
. Examine the palette and observe that the service task is not available.
. Go to the project's settings and uninstall the service task.
. Go to process P2.
. Examine the palette and observe that the service task is still present in the diagram and available in the palette.

Expected result: The palette reflects the state of the process.

Actual result: The palette is out of sync with the state of the process.

Workaround: After you install or uninstall an item in the service repository, close and reopen the process designer editor. 

endif::PAM[]

== Installer
.The controller URL is not updated in the standalone.xml file if only {KIE_SERVER} is installed [https://issues.jboss.org/browse/RHPAM-1781[RHPAM-1781]]

Issue: When you run the {PRODUCT} installer and you specify a URL for the controller, the URL is not updated in the {EAP} `standalone.xml` and `standalone-full.xml` files.

Steps to reproduce:

. Run the {PRODUCT} installer.
. Specify an {EAP} installation for container.
. Select only Process Server to install.
. Select *Advanced Configuration* and update controller URL.
. Complete the installation.
. Open the {EAP} `standalone.xml` or  `standalone-full.xml` file and find the controller URL.

Expected result: The value of the controller URL property is the URL that you entered during installation.

Actual result: The value of the controller URL property is the default value.

Workaround: Manually update the value of the controller URL property in the {EAP} `standalone.xml` and  `standalone-full.xml` file.


== {KIE_SERVER}

.You cannot deploy a KJAR with a PMML asset to a {KIE_SERVER} Spring Boot starter on Windows [https://issues.jboss.org/browse/RHDM-852[RHDM-852]]

Issue: If a KJAR contains a PMML asset, you cannot deploy it as a container on a {KIE_SERVER} that is running in the `kie-server-spring-boot-starter` Spring Boot starter on Microsoft Windows.

Steps to reproduce:

. Create a KJAR that contains a PMML asset.
. Start `kie-server-spring-boot-starter` on Windows.
. Deploy the KJAR to a {KIE_SERVER} that is running the `kie-server-spring-boot-starter` Spring Boot starter on Microsoft Windows.

Expected result: The KJAR is deployed successfully.

Actual result: The KJAR cannot be deployed.

Workaround: None.

== OpenShift

.User password is displayed in the Readiness and Liveness probes [https://issues.jboss.org/browse/RHPAM-1829[RHPAM-1829]][https://issues.jboss.org/browse/RHDM-848[RHDM-848]]

Issue: If you deploy {PRODUCT} on OpenShift, the user password is displayed in both the Readiness and Liveness probes.

Workaround: None.

== {PLANNER}

.`ScoreCalculationCountLimit` termination does not work with multi-threaded solving [https://issues.jboss.org/browse/RHDM-740[RHDM-740]]

Issue: {PLANNER} configured with the score calculation count termination (`ScoreCalculationCountLimit`) does not terminate. The score calculation count termination is primarily used for testing.

Workaround: Use another type of termination.

//ifdef::PAM[]
//== Smart Router

//.With IBM Java, Smart Router with HTTPS enabled causes the `NoSuchAlgorithmException` exception [https://issues.jboss.org/browse/RHPAM-1576[RHPAM-1576]]

//Issue: With IBM Java, when Smart Router is started with HTTPS enabled the `NoSuchAlgorithmException` exception occurs.
//endif::PAM[]
