[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

.You cannot upload a spreadsheet that contains a large decision table [https://issues.jboss.org/browse/RHDM-488[RHDM-488]]

Issue: If you try to upload a spreadsheet that contains a large decision table into {CENTRAL}, an out of memory error appears in the `error.log` file.

Steps to reproduce:

. Create a spreadsheet that contains a large decision table.
. Create a new project in {CENTRAL}.
. Click *Add Asset* and then select *Spreadsheet Decision Table*.`
. Attach the spreadsheet that contains the large decision table.
. Review the server `error.log` file.

Actual result: An out of memory error appears in the `error.log` file.

Workaround: None.

.An unexpected error occurs if you delete a project that contains a business process [https://issues.jboss.org/browse/RHPAM-1943[RHPAM-1943]]

Steps to reproduce:

. Create a project in {CENTRAL}.
. Add a business process asset to the project.
. Save the business process asset.
. Delete the business process asset.

Expected result: The business process asset is deleted.

Actual result: An error occurs.

Workaround: None.

== Installer

.You cannot deploy a KJAR with a PMML asset to a {KIE_SERVER} Spring Boot starter on Windows [https://issues.jboss.org/browse/RHDM-1973[RHDM-1973]]

Issue: If you use the installer to install {PRODUCT} on {EAP}, the installer installs the contents of `rhpam-7.3.0-kie-server-ee7.zip` instead of the contents of `rhpam-7.3.0-kie-server-ee8.zip`.

Expected result:  The contents of `rhpam-7.3.0-kie-server-ee8.zip` are installed.

Actual result: The contents of `rhpam-7.3.0-kie-server-ee7.zip` are installed.

Workaround: None.

== {KIE_SERVER}

.You cannot deploy a KJAR with a PMML asset to a {KIE_SERVER} Spring Boot starter on Windows [https://issues.jboss.org/browse/RHDM-852[RHDM-852]]

Issue: If a KJAR contains a PMML asset, you cannot deploy it as a container on a {KIE_SERVER} that is running the `kie-server-spring-boot-starter` Spring Boot starter on Microsoft Windows.

Steps to reproduce:

. Create a KJAR that contains a PMML asset.
. Start `kie-server-spring-boot-starter` on Windows.
. Deploy the KJAR to a {KIE_SERVER} that is running the `kie-server-spring-boot-starter` Spring Boot starter on Microsoft Windows.

Expected result: The KJAR is deployed successfully.

Actual result: The KJAR cannot be deployed.

Workaround: None.

ifdef::PAM[]
== Process designer

.You cannot open process designer in the most recent version of Internet Explorer [https://issues.jboss.org/browse/RHPAM-852[RHPAM-852]]

Issue: If you update Internet Explorer 11 and then open a business process in the process designer, the process designer freezes.

Steps to reproduce:

. Update Internet Explorer to the latest version.
. Start {CENTRAL}.
. Open a business process in the process designer.

Expected result: The process opens with no issues.

Actual result: The process does not open and the process designer freezes.

Workaround: Start the server with the `-Ddesigner.useolddataassignments=true` argument to bypass this issue.
endif::PAM[]

== OpenShift

.User password is displayed in the Readiness and Liveness probes [https://issues.jboss.org/browse/RHPAM-1829[RHPAM-1829]]

Issue: If you deploy {PRODUCT} on OpenShift, the user password is displayed in both the Readiness and Liveness probes.

Workaround: None.

== {PLANNER}

.The `ScoreCalculationCountLimit` termination with multi-threaded solving freezes the `TennisBenchmarkTest` [https://issues.jboss.org/browse/RHPAM-852[RHPAM-852]]

Issue: {PLANNER} configured with the score calculation count termination does not terminate. The score calculation count termination is primarily used for testing.

Workaround: Use another type of termination.

== Smart Router

.Smart Router with HTTPS enabled causes the `NoSuchAlgorithmException` exception [https://issues.jboss.org/browse/RHPAM-1576[RHPAM-1576]]

Issue: When Smart Router is started with HTTPS enabled the `NoSuchAlgorithmException` exception occurs.

