[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== {OPENSHIFT}
.In a high-availability authoring environment, when one user imports a project, another user is unable to see it [https://issues.jboss.org/browse/AF-2062[AF-2062]]

Issue: When multiple users connect to a high-availability {CENTRAL} and one of them creates a project, another user can not see the project.

Steps to reproduce:
. Log in to {CENTRAL} as two different users (A and B) from two different hosts or browsers.
. As user A and as user B, open the same space.
. As user A, import a project using an external Git repository URL.

Expected result: As user B, you can see the imported project in the space.

Actual result: As user B, you can not see the imported project in the space.

Workaround: As user B, reload the space.

.In a high-availability authoring environment, role changes in {CENTRAL} are not saved [https://issues.jboss.org/browse/AF-2162[AF-2162]]

Issue: If you configure a role change in high-availability {CENTRAL}, the change can be lost after a time and the roles reset to defaults.

Workaround: Configure the role change again.

.In a high-availability authoring environment, an imported project in {CENTRAL} appears multiple times [https://issues.jboss.org/browse/AF-2179[AF-2179]]

Issue: If you import a sample project in high-availability {CENTRAL}, the project can appear in the list several times. Some copies might not have all of the assets. The environment can slow down when this issue occurs.

Workaround: Ensure one copy has all of the assets, then remove all other copies. If {CENTRAL} performance is slow, restart all of the nodes connected to it.
