[id='rn-kogito-productize-features-ref']
= {KOGITO} features included with {PRODUCT}

{KOGITO} is a cloud-native business automation technology for building cloud-ready business applications. {KOGITO} in {PRODUCT} is optimized for a hybrid cloud environment and adapts to your domain and tooling needs. The core objective of {KOGITO} is to help you mold a set of decisions into your own domain-specific cloud-native set of services.

This section highlights the {KOGITO} features included with {PRODUCT}.

== Ability to migrate {CENTRAL} projects to {KOGITO} microservices projects

You can now migrate your existing {CENTRAL} projects developed using DMN, PMML, or DRL to {KOGITO} microservices projects. For more information, see {URL_GETTING_STARTED_KOGITO_MICROSERVICES}#assembly-getting-started-migration-to-kogito-microservices[_{MIGRATION_KOGITO_SERVICES}_].

== Support for Spring Boot starters

You can now add Spring Boot starters to your {KOGITO} project to get started with {KOGITO} quickly. For more information, see {URL_GETTING_STARTED_KOGITO_MICROSERVICES}[_{GETTING_STARTED_KOGITO_MICROSERVICES}_].
