[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

.When you log out and log back in to {CENTRAL}, the language switches to English instead of the desired language selected from[https://issues.redhat.com/browse/RHPAM-2779[RHPAM-2779]]

Issue: In {CENTRAL}, when you select a desired language from the *Languages* drop-down menu and log out and log back in to {CENTRAL}, the language switches to English instead of the selected language.

Steps to reproduce:

. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Languages*.
. Select *French* from the *Languages* drop-down menu.
. Click *Ok*.
. Log out from the {CENTRAL}.
. Log in again to {CENTRAL}.
. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Languages*.

Expected result: A modal dialog with languages opens up.

Actual result: {CENTRAL} is reloaded and the language switches to English instead of French.

Workaround: Go to {CENTRAL} again, select the *Admin* icon in the top-right corner of the screen, select *Languages* and set the desired language.

ifdef::PAM[]
.An error occurs during a WAR file deployment with invalid jandex index files in {CENTRAL} [https://issues.redhat.com/browse/RHPAM-2742[RHPAM-2742]]
endif::[]

ifdef::DM[]
.An error occurs during a WAR file deployment with invalid jandex index files in {CENTRAL} [https://issues.redhat.com/browse/RHDM-1267[RHDM-1267]]
endif::[]

Issue: When you deploy {CENTRAL} or {KIE_SERVER} `WAR` files to {EAP} or Thorntail, an invalid jandex index files error occurs with the following message:

----
WFLYSRV0002: Could not read provided index: /content/kie-server.war/WEB-INF/lib/kubernetes-client-4.6.0.jar/META-INF/jandex.idx
----

.The alerts panel mix the messages from multiple projects instead of showing messages related just to the opened project [https://issues.redhat.com/browse/RHDM-1243[RHDM-1243]]

Issue: You can see alert messages from multiple projects instead of showing messages related just to the opened project in the *Alerts* panel.

Steps to reproduce:

. Start {CENTRAL}.
. Open *MySpace*.
. Add a project as a-project.
. Add a DMN asset as a-model.
. Add a decision node as A-Decision but do not specify its expression.
. Click *Save* to save the a-model.
. Return to *MySpace*.
. Add a project as b-project.
. Add a DMN asset as b-model.
. Add a decision node as B-Decision but do not specify its expression.
. Click *Save* to save the b-model.

Expected result: The *Alerts* panel do not mix messages from multiple projects.

Actual result: The *Alerts* mix messages from multiple projects.

Workaround: None

.Dashbuilder Data Transfer feature does not work on Windows [https://issues.redhat.com/browse/RHPAM-2751[RHPAM-2751]]

Issue: The dashbuilder data transfer feature does not work on Windows. You can not export and import the dashbuilder related data in {CENTRAL}.

Steps to reproduce:

. Start {CENTRAL} on Windows.
. Select the *Admin* icon in the top-right corner of the screen and select *Dashbuilder Data Transfer*.
. Try to export or import some data.

Expected result: You can export or import dashboard data on Windows.

Actual result: You can not export or import dashboard data on Windows.

Workaround: None

ifdef::PAM[]

== Process Designer

.If you try to migrate a process with a custom data type containing `<` `>` characters, you receive a warning message [https://issues.redhat.com/browse/RHPAM-2772[RHPAM-2772]]

Issue: It is not possible to migrate process with a custom data type containing `<` `>` characters. You receive an empty error message in the *Migrate Diagram* window.

Steps to reproduce:

. Create a process in the legacy process designer.
. Define a process variable with the name and custom data type containing `<` `>` characters.
. Migrate the process to the new process designer.

Expected result: You can migrate the process to the new process designer. In case the process is broken, you can see an error message telling you that you cannot migrate the process.

Actual result: Warnings are shown that you cannot migrate the process.

Workaround: Remove `<` and `>` characters from custom type of all process variable definitions before you start the migration.

.If you use the '^' character in Notifications subject while creating an user task break a process [https://issues.redhat.com/browse/RHPAM-2763[RHPAM-2763]]

Issue: In the the process designer, if you use the `^` character in *Notifications* subject in user task it break a process.

Steps to reproduce:

. Create an user task.
. Click *Notifications* to specify notifications associated with the user task.
. Enter the subject `^` in the *Notifications*.
. Click *Save*.
. Save and reopen the process.

Expected result: The Process Designer editor is opened and the process is not broken.

Actual result: The process is broken. System error pop-up window is shown.

Workaround: Do not use `^` character in Notifications subject.

.Called element in reusable sub process is not populated [https://issues.redhat.com/browse/RHPAM-2760[RHPAM-2760]]

Issue: In the process designer, reusable sub process is not populated in the Called element drop-down list.

Steps to reproduce:

. Create process A.
. Create process B.
. Create reusable sub process in process B.
. Click *Called element* property.

Expected result: Called element property is populated.

Actual result: Called element property is not populated.

Workaround: Deactivate the Reusable sub-process and activate it again.

.An error occurs when editing the process during restoring the other process [https://issues.redhat.com/browse/RHPAM-2757[RHPAM-2757]]

Issue: In the process designer, While editing the process when you try to restore other process an error message is shown.

Steps to reproduce:

. Create process A and do not close this process.
. Create process B.
. Make the change in process B and click *Save*.
. Click *Latest version* and select *Version 1*
+
Do not click *Restore*.
. With the help of drop-down, open the process A.
. Make the changes in process A.

Expected result: No error messages are shown.

Actual result: An error message is shown.

Workaround: Finish restoring the previous version by clicking *Restore* before you start editing other processes.

.You can not remove the case file and global variables [https://issues.redhat.com/browse/RHPAM-2643[RHPAM-2643]]

Issue: When editing a case definition in process designer, you can add case file variables in the *Case Management* section, but you cannot delete them. It is also not possible to delete the global variables as well.

Steps to reproduce:

. Create a case project.
. Create a case definition.
. In the *Properties* panel add a case file variable in the *Case Management* section.
. Add global variable in the *Properties* panel.
. Try to delete the case file variable and global variable.

Expected result: A button with bin icon is shown next to each variable. Once the bin icon is clicked, the variable is removed.

Actual result: It is not possible to delete variables. The bin icon is missing to delete the variables.

Workaround:

. Download the process or a case.
. Locate the case file variable and global variable in the downloaded `.bpmn` file and delete them.
. Delete the process or a case from {CENTRAL}.
. Import previously downloaded and edited `.bpmn` file back to {CENTRAL}.

.Ruleflow group is not populated [https://issues.redhat.com/browse/RHPAM-2740[RHPAM-2740]]

Issue: In the process designer, Ruleflow group is not populated. It should be populated with all the rule flow groups defined in the project.

Steps to reproduce:

. Create a new DRL file containing a rule-flow-group.
. Create a new process.
. Activate the Business Rule task.
. Click *Rule flow Group* property of the Business Rule task.

Expected result: All the rule flow groups from the project are listed in the *Rule Flow Group* drop-down menu.

Actual result: The *Rule flow Group* drop-down list is empty.

Workaround:

. Click on the canvas.
. Click *Rule flow Group* drop-down list again.

endif::[]

== Installer

.In {PRODUCT} installer, {JWS} 5.1 is referenced in the installation path [https://issues.redhat.com/browse/RHPAM-2745[RHPAM-2745]]

Issue: When you run the {PRODUCT} installer the installation path step references {JWS} 5.1 instead of {JWS} {JWS_VERSION}.

== DMN Designer

.Node data type is lost after drag and drop in data type editor [https://issues.redhat.com/browse/RHDM-1269[RHDM-1269]]

Issue: In DMN diagram, nodes are referenced to some custom DMN data type, and when this custom data type is edited, the reference in the node diagram is lost and node refers to `<Undefined>` data type.

Steps to reproduce:

. Create a new DMN diagram.
. Add two custom data types.
. Add one node to the DMN diagram.
. Set the node as output type to one of created custom data types.
. Reorder the custom defined data types by drag and drop feature.
. Return to node definition, its data type will be lost.

Expected result: The type is one of the custom data types.

Actual result: The node refers to `<Undefined>` data type.

Workaround: Set the data type of the node after reordering custom data types.

.DMN Designer convert java class with invalid DMN identifier [https://issues.redhat.com/browse/RHDM-1231[RHDM-1231]]

Issue: When you try to convert a java class to DMN data type while the java class contains field name, then it is an invalid identifier for DMN and you will receieve an error.
