[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

== Installer

.When installing {KIE_SERVER} and {CENTRAL} using the {PRODUCT} installer, the default placeholder for the controller URL should contain {URL_COMPONENT_CENTRAL} [https://issues.jboss.org/browse/RHPAM-1774[RHPAM-1774]]
Issue: If you use the {PRODUCT} installer to install both {CENTRAL} and {KIE_SERVER}, on the Advanced Configuration page the default value for {KIE_SERVER} is incorrect.

Steps to reproduce:

. Use the installer to install {PRODUCT} on {EAP}.
. Accept all default selections.
. On the Advanced Configuration page, select *Configure Process Server*.

Expected result: The value of the {KIE_SERVER} URL is `\http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/controller`.

Actual result: The value of the {KIE_SERVER} URL is `\http://localhost:8080/controller/rest/controller`

Workaround: After you complete the installation, change `\http://localhost:8080/controller/rest/controller` to `\http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/controller` in the the {EAP} `standalone.xml` and `standalone-full.xml` files.

.The controller URL is not updated in the standalone.xml file if only {KIE_SERVER} is installed [https://issues.jboss.org/browse/RHPAM-1781[RHPAM-1781]]

Issue: When you run the {PRODUCT} installer and you specify a URL for the controller, the URL is not updated in the {EAP} `standalone.xml` and `standalone-full.xml` files.

Steps to reproduce:

. Run the {PRODUCT} installer.
. Specify an {EAP} installation for container.
. Select only Process Server to install.
. Select Advanced Configuration and update controller URL.
. Complete the installation.
. Open the {EAP} `standalone.xml` or  `standalone-full.xml` file and find the controller URL.

Expected result: The value of the controller URL property is the URL that you entered during installation.

Actual result: The value of the controller URL property is the default value.

Workaround: Manually update the value of the controller URL property in the {EAP} `standalone.xml` and  `standalone-full.xml` file.

== {CENTRAL}
.Red Hat Decision Central 7.0 and earlier and BRMS 6.4 and earlier repositories can be imported into {CENTRAL} [https://issues.jboss.org/browse/RHPAM-1768[RHPAM-1768]]

Issue: Red Hat Decision Central 7.0 and earlier and BRMS 6.4 and earlier repositories (old structure repositories) that contain more than one project can be imported into {CENTRAL} even though they are not supported. When these repositories are imported, the are not fully migrated and will not perform as expected.
 
Steps to reproduce:

. In {PRODUCT} 7.0.0 or earlier, create a repository with two projects.
. Copy repository location from the `.niogit` directory.
. Open {PRODUCT} 7.2.0.
. Click *Library* -> *Import Project*.
. Paste the repository location  select both projects. 

Actual result: The projects are imported but will not perform as expected.

Workaround: Use the patching and upgrading tool to import Red Hat Decision Central 7.0 and earlier and BRMS 6.4 and earlier repositories, as described in {URL_PATCHING_UPGRADING}[_{PATCHING_UPGRADING}_].

   
.A TimeoutException error occurs when logging in to a clustered {CENTRAL} [https://issues.jboss.org/browse/RHPAM-1749[RHPAM-1749]]
Issue: On a clustered {CENTRAL} instance, when logging in to {CENTRAL} an exception is thrown.

Steps to reproduce:
    
. Create a {CENTRAL} cluster configuration that uses ElasticSearch, AMQ Broker, and has two standalone {CENTRAL} nodes.
. Uncomment the `<distributable/>` tag on both {CENTRAL} nodes.
. Log in to {CENTRAL} on one of the nodes. 

Actual result: An exception is thrown.
    
Workaround: See the workaround in the https://access.redhat.com/solutions/2776221[JBoss EAP 7 does not process requests for a session in parallel] article.
    

.{PRODUCT} integrated with Red Hat Single Sign-On ignores user SSH key when working with Git [https://issues.jboss.org/browse/RHPAM-1683[RHPAM-1683]]

Issue: With {PRODUCT} integrated with Red Hat Single Sign-On, if you try to clone a project created by a user that has an SSH key set, you cannot clone it without the SSH key password. The ssh key is ignored.

Steps to reproduce:

. Integrate a {PRODUCT} installation with Red Hat Single Sign-On, as described in {URL_INTEGRATING_SSO}[_{INTEGRATING_SSO}_].
. Use the {PRODUCT} *Admin* -> *SSH Keys* page to add a public SSH key.
. Enter the following command in a terminal to add a private SSH key to your `ssh-agent`, where `<SSH-KEY-PATH>`  is the path to the SSH private key:
+
[source]
----
$ ssh-add <SSH-KEY-PATH>
----
. Use SSH to clone the project, for example:
+
[source]
----
git clone ssh://user@localhost:8001/space/project
----

Expected result: The project is cloned.

Actual result: You cannot clone the project unless you use the user's password.

.Several Errai projects contain XSD-invalid `pom.xml` file [https://issues.jboss.org/browse/RHPAM-1742[RHPAM-1742]]
Issue: Maven repository validation identified the following `pom.xml` files in the Errai project which are invalid according to Maven POM XSD:
[source]
----
org/jboss/errai/errai-ioc/4.4.1.Final-redhat-00001/errai-ioc-4.4.1.Final-redhat-00001.pom.xml
org/jboss/errai/errai-navigation/4.4.1.Final-redhat-00001/errai-navigation-4.4.1.Final-redhat-00001.pom.xml
org/jboss/errai/errai-security-server/4.4.1.Final-redhat-00001/errai-security-server-4.4.1.Final-redhat-00001.pom.xml
org/jboss/errai/errai-security-client/4.4.1.Final-redhat-00001/errai-security-client-4.4.1.Final-redhat-00001.pom.xml
org/jboss/errai/errai-common/4.4.1.Final-redhat-00001/errai-common-4.4.1.Final-redhat-00001.pom
----

Workaround: None.

.`kie-soup-dataset-elasticsearch` is an  XSD-invalid `pom.xml` file [https://issues.jboss.org/browse/RHPAM-1743[RHPAM-1743]]
Issue: Maven repository validation identified the `kie-soup-dataset-elasticsearch` `pom.xml` fileas invalid according to Maven POM XSD.

Workaround: None.

.Two `ClassNotFoundExceptions` errors are thrown the first time you open the {CENTRAL} *Data Sources* perspective [https://issues.jboss.org/browse/RHPAM-1741[RHPAM-1741]]

Issue: When you got to the {CENTRAL} *Data Sources* perspective for the first time after a clean installation, the following `ClassNotFoundExceptions` errors appear in the `server.log` file:
[source]
----
org.guvnor.structure.repositories.NewBranchEvent
org.guvnor.structure.repositories.RepositoryUpdatedEvent
----

Steps to reproduce:

. Log in to {CENTRAL} with the `admin` role.
. Go to *Admin* -> *Datasources*.

Actual result: As soon as you click the *Data Sources* perspective, two errors appear in {EAP} console.

Expected result: No errors appear.

Workaround: Restart {CENTRAL} and go to *Admin* -> *Datasources*. These errors only appear the first time the perspective is clicked after installation.

== {KIE_SERVER}

.A container is removed from the UI even though it was not possible to stop it [https://issues.jboss.org/browse/RHPAM-1698[RHPAM-1698]]

Issue: A container cannot be stopped if it is blocked by an active process instance. However if you attempt to stop a blocked container from the UI, the action throws and exception and the container disappears.

Steps to reproduce:

. Create a project with a process.
. Deploy the project and start the process.
. Go to the *Execution Servers* page and stop the container.

Actual result: The container is removed from the UI even though it is still running.
 
 ifdef::PAM[]
== Maven repository
.Missing JWS dependencies in offline maven repo distribution [https://issues.jboss.org/browse/RHPAM-1715[RHPAM-1715]]

Issue: The following key dependencies required to install {KIE_SERVER} on {JWS} are missing from the offline Maven repository. 

[source]
----
org.jboss.integration:narayana-tomcat
org.jboss:jboss-transaction-spi
----

If you are you are performing a manual installation, you must copy the files described in the workaround.

Workaround:

. Use the installer to install {PRODUCT} on {JWS}.
. In a terminal, change directory to the `<JWS-HOME>/jws-5.0/tomcat/lib` directory where the installer installed {PRODUCT}.
. Copy the following files from the `<JWS-HOME>/jws-5.0/tomcat/lib` directory to the `<JWS-HOME>/jws-5.0/tomcat/lib` directory of the target {JWS} location.
+
[source]
----
narayana-tomcat-1.0.0.Final-redhat-1.jar 
jboss-transaction-spi-7.6.0.Final-redhat-1.jar 
----
endif::PAM[]

== OpenShift
.Various errors occur when starting clustered {CENTRAL} on OpenShift [https://issues.jboss.org/browse/RHPAM-1747[RHPAM-1747]]

Issue: When clustered {CENTRAL} is started on OpenShift using the `rhpam72-authoring-ha.yaml` template, {CENTRAL} sometimes throws various exceptions that cause the pod to restart or the deployment to fail.

Steps to reproduce:

. Use the `rhpam72-authoring-ha.yaml` template to deploy {PRODUCT} {PRODUCT_VERSION} images on OpenShift .
. Check the {CENTRAL} log files.

Expected result: There are no errors in the log files.

Actual result: Errors appear in the log files, the pod to restarts, or the deployment fails.

Workaround: None.

ifdef::PAM[]
== Form modeler
.Dates in Multiple Subform show wrong time zone [https://issues.jboss.org/browse/RHPAM-1697[RHPAM-1697]]

Issue: For time zones that observe daylight savings time, the value of `LocalDateTime` in the *Multiple Subform* widget shows the wrong time by one hour. 


== Process designer
.When a process containing subprocesses is created and saved, the process validation fails [https://issues.jboss.org/browse/RHPAM-1732[RHPAM-1732]]

Issue: When a process containing subprocesses is created and saved, the process validation fails.

Steps to reproduce:

. Create a process with at least one subprocess.
. Click *Save*.

Expected result: The process and subprocesses are saved.

Actual result: The following validation error appears even though all sequence flows have their source and target within the process:
[source]
----
Sequence flow connectors cannot exceed the embbedded subprocess' bounds. Both source and target nodes must be in same parent process.
----
endif::PAM[]
