[id='rn-kogito-productize-features-ref']
= Kogito productized features in {PRODUCT}

== Support for {KOGITO} microservices in {PRODUCT}

{PRODUCT} now provides support for the following {KOGITO} microservices that you can use to build cloud-native applications that adapt to your business domain and tooling:

* Layering on https://access.redhat.com/products/quarkus[{QUARKUS}] or https://access.redhat.com/products/spring-boot[Spring Boot] to enable developers to run {KOGITO} microservices on their preferred cloud-native application development stack
* Automated decision-making capabilities based on rule units to run within defined business constraints
* Example applications containing various types of {KOGITO} decision microservices on https://access.redhat.com/products/quarkus[{QUARKUS}] or https://access.redhat.com/products/spring-boot[Spring Boot] to help you develop your applications

For more information about getting started with {KOGITO} in {PRODUCT}, see {URL_GETTING_STARTED_KOGITO_MICROSERVICES}#assembly-getting-started-kogito-microservices[_{GETTING_STARTED_KOGITO_MICROSERVICES}_].

== Support for {KOGITO} JVM Quarkus runtime

{PRODUCT} now supports {KOGITO} JVM Quarkus runtime images.

For more information, see {URL_GETTING_STARTED_KOGITO_MICROSERVICES}#assembly-deploying-kogito-microservices-on-openshift[_{GETTING_STARTED_KOGITO_MICROSERVICES}_].

== Support for {KOGITO} builder images for {QUARKUS} and Spring Boot

{PRODUCT} now includes {KOGITO} builder images for {QUARKUS} and Spring Boot.

For more information, see {URL_GETTING_STARTED_KOGITO_MICROSERVICES}#assembly-deploying-kogito-microservices-on-openshift[_{GETTING_STARTED_KOGITO_MICROSERVICES}_].
