[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.


== {CENTRAL}

.Cannot close the standalone editor [https://issues.jboss.org/browse/RHPAM-976[RHPAM-976]]

Issue: If you make a change in a standalone editor, you cannot close the editor until you save your changes.

Steps to reproduce:

. Open a standalone editor.
. Make a change to asset.
. Try to close the editor.

Expected result: The editor closes.

Actual result: The editor does not close.

Workaround: Save any changes before closing the editor.

.In guided rules, guided decision tables, and guided decision templates, the use of the "contains" operator does not add values from enumerations that have quotes. [https://issues.jboss.org/browse/RHDM-25[RHDM-25]]

Issue: When enumeration is used for a string field of a fact in guided rules, guided decision tables, and guided decision templates, the resultant rule does not wrap the selected value from the enumeration drop down in quotes ("") and a validation error occurs. 

ifdef::PAM[]
.Process designer instances are very slow with Google Chrome on Linux [https://issues.jboss.org/browse/RHPAM-922[RHPAM-922]]

Step to reproduce: Open three process designer instances in Google Chrome on Linux.

Expected result: All instances of process designer perform at the same level, regardless of the number of instances open.

Actual result: The first two instances that were opened perform as usual, but the third and all subsequent instances are very slow, even if you close the first two instances.

Workaround: Set the value of `chrome://flags/#force-color-profile` to sRGB.

endif::[]

.Project cannot be built and deployed in {CENTRAL} when connected to a snapshot Maven repo [https://issues.jboss.org/browse/RHPAM-1544[RHPAM-1544]]

Steps to reproduce:

. Start the local Nexus repository.
. Install {EAP} with {CENTRAL}.
. Set the value of the `kie.maven.settings.custom` system property to `settings.xml` which will point to the Nexus snapshot repository.
. Start {EAP}, log in to {EAP}, and try to create a project.

Actual result: An error appears.

Workaround: Remove the snapshot Maven repository from the `settings.xml` file used by {CENTRAL}.

== OpenShift

.Opening Case Modeler (legacy) throws a JSON exception [https://issues.jboss.org/browse/RHPAM-1431[RHPAM-1431]]

Steps to reproduce:

. Install Red Hat Single Sign-On in OpenShift.
. Create a realm.
. Install {PRODUCT} in OpenShift.
. Open the IT-Orders orders hardware case definition.

Actual result: An error occurs and the application restarts.

ifdef::DM[]
//== {CENTRAL}
== {KIE_SERVER}
.Execution errors: Details cannot be loaded from Sybase 16.0 [https://issues.jboss.org/browse/RHPAM-1567[RHDM-1567]]

Issue: If you select a Sybase 16.0 error from the list of execution errors, the *Details* panel opens but no data is displayed and the following error appears:

[source]
----
An unexpected error happened. Please try again in a few moments.
----

//== {PLANNER}
endif::[]