[id='rn-support-ref']
= Support and compatibility

This section highlights supported version updates in {PRODUCT} {PRODUCT_VERSION}.

== Support for Firefox 78 ESR

{PRODUCT} now supports Firefox 78 ESR browser.

== Support for {DATAGRID} {DATAGRID_VERSION}

{PRODUCT} now supports {DATAGRID} {DATAGRID_VERSION}.

== Support for {AMQ_STREAMS} {AMQ_STREAMS_VERSION}

{PRODUCT} now supports {AMQ_STREAMS} {AMQ_STREAMS_VERSION}.

== Support for {AMQ} {AMQ_VERSION}

{PRODUCT} now supports {AMQ} {AMQ_VERSION}.

== Support for High-availability authoring on {EAP} on premise

Configuration of {CENTRAL} on {EAP} for high-availability (HA) on premise is fully supported.

For more information about installing and configuring {PRODUCT} in a {EAP} clustered environment, see {URL_INSTALLING_AND_CONFIGURING}#assembly-clustering-eap[_{INSTALLING_ON_EAP_CLUSTER}_].

== Support for {JWS} {JWS_VERSION}

You can now install {PRODUCT} on {JWS} {JWS_VERSION}. For more information about installing {PRODUCT} on {JWS} {JWS_VERSION}, see {URL_INSTALLING_AND_CONFIGURING}#assembly-install-on-jws[_{INSTALLING_ON_JWS}_].

== {CODEREADY_STUDIO} integration

You can now integrate {CODEREADY_STUDIO} {CODEREADY_STUDIO_VERSION} with {PRODUCT}. For more information about integrating {CODEREADY_STUDIO} {CODEREADY_STUDIO_VERSION} with {PRODUCT}, see {URL_INTEGRATING}#assembly-integrating-codeready-studio[_{INTEGRATING_CRS}_].

== {FUSE_LONG} integration

{FUSE_LONG} 7.7 is supported on {EAP} 7.2, whereas {PRODUCT} is supported on {EAP} {EAP_VERSION}. To ensure a stable deployment environment, install {FUSE} and {PRODUCT} on different instances of {EAP} according to the supported {EAP} versions.
For more information, see {URL_INTEGRATING}#assembly-integrating-fuse[_{INTEGRATING_FUSE}_]
