[id='rn-support-ref']
= Support and compatibility

This section highlights supported version updates in {PRODUCT} {PRODUCT_VERSION}.

== Fuse integration

{FUSE_LONG} 7.6 is supported on {EAP} 7.2, whereas {PRODUCT} is supported on {EAP} {EAP_VERSION}. To ensure a stable deployment environment, install {FUSE} and {PRODUCT} on different instances of {EAP} according to the supported {EAP} versions.

== Support for {EAP_LONG} {EAP_VERSION}
You can now install {PRODUCT} on {EAP_LONG} {EAP_VERSION}. For more information about installing {PRODUCT} on {EAP_LONG} {EAP_VERSION}, see {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].

== Support for {JWS} {JWS_VERSION}
You can now install {PRODUCT} on {JWS} {JWS_VERSION}. For more information about installing {PRODUCT} on {JWS} {JWS_VERSION}, see {URL_INSTALLING_ON_JWS}[_{INSTALLING_ON_JWS}_].

ifdef::PAM[]

== Support for MySQL 8.0
You can now deploy {PRODUCT} with a MySQL 8.0 data source. For more information, see {URL_INSTALLING_ON_EAP}/index#eap-data-source-add-proc[Configuring JDBC data sources for KIE Server] in the {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_] guide.

== Support for Microsoft SQL Server 2017
{PRODUCT} deployments now supports Microsoft SQL Server 2017 as an external database server for the {KIE_SERVER}.

== Support for Oracle Database 19c
{PRODUCT} deployments now supports Oracle Database 19c as an external database server for the {KIE_SERVER}.

== Support for PostgreSQL 11 and EnterpriseDB Postgres Advanced Server 11
{PRODUCT} deployments now support PostgreSQL 11 and EnterpriseDB Postgres Advanced Server 11 as an external database servers for the {KIE_SERVER}.

endif::PAM[]
