[id='rn-tech-preview-con']
= Technology preview

This section lists features that are in technology preview in {PRODUCT} {PRODUCT_VERSION}. {CENTRAL} includes an experimental features administration page which is disabled by default. To enable this page, set the value of the `appformer.experimental.features` property to `true`.

[IMPORTANT]
====
These features are for Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
====
* New Decision Model and Notation (DMN) designer in {CENTRAL}. You can use the new DMN designer in {CENTRAL} to design DMN decision requirements diagrams (DRDs) and define decision logic for a complete and functional DMN decision model. {PRODUCT} {PRODUCT_VERSION} provides both design and runtime support for DMN 1.2 models at conformance level 3, and includes enhancements and fixes to FEEL and DMN model components to optimize the experience of implementing DMN decision services with {PRODUCT}. For more information about DMN support in {PRODUCT} {PRODUCT_VERSION}, see {URL_DMN_MODELS}[_{DMN_MODELS}_].
* Optaweb employee rostering.
* High-availability authoring on {EAP} (on premise and OpenShift). Configuration of {CENTRAL} for high availability is currently tech preview. Search and messaging technology used to enable search feature is considered an implementation detail. {PRODUCT} may choose to replace that technology in the future while preserving the capability offered.
* A new Test Scenario (Preview) editor that enables you to add test scenarios to verify the accuracy of previously created rules, decision tables, and so on. 


