[id='rn-tech-preview-con']
= Technology preview

This section lists features that are in Technology Preview in {PRODUCT} {PRODUCT_VERSION}. {CENTRAL} includes an experimental features administration page that is disabled by default. To enable this page, set the value of the `appformer.experimental.features` property to `true`.

[IMPORTANT]
====
These features are for Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
====

ifdef::PAM[]

== Prediction Service API

You can use the prediction service API to provide a prediction service that assists with user tasks. The prediction service can use artificial intelligence (AI). For example, you can use the Predictive Model Markup Language (PMML) models or Statistical Machine Intelligence and Learning Engine (SMILE) to implement the service.

endif::PAM[]

== Deploying a high-availability authoring environment on {OPENSHIFT} 4.x
You can deploy a high-availability {PRODUCT} authoring environment on {OPENSHIFT} 4.x using the operator.

== OpenShift operator installer wizard
An installer wizard is provided in the {OPENSHIFT} operator for {PRODUCT}. You can use the wizard to deploy a {PRODUCT} environment on {OPENSHIFT} with the operator.

== Authoring perspective customization

You can perform the following tasks to customize the {CENTRAL} authoring perspective:

* Open a {CENTRAL} project directly using an URL path parameter, without going through a list of spaces and projects.
* Hide or show the project toolbar, *Metrics* tab, and *Change Request* tab according to your requirements.
* Enhance the pagination.
* Customize the number of assets present on the project screen.

== {PLANNER} new constraint collectors

In order to provide a full implementation of some pre-existing OptaPlanner examples using the Constraint Streams API, the standard library of constraint collectors has been extended to include the following constraint collectors:

* One constraint collector takes point values such as dates, orders them on a number line, and makes groups of consecutive values with breaks between the groups available downstream.
* Another constraint collector takes interval values such as shifts, creates clusters of consecutive and possibly overlapping values with breaks between clusters, and makes the clusters available downstream.

These new collectors are in technology preview.  Their interfaces, names, and functionality are subject to change. They have been placed in an experimental package outside of the public API  to encourage public feedback before they become an officially supported part of the OptaPlanner public API.

== {KOGITO} and Kafka integration

{KOGITO} decision microservices integration with managed Kafka by using the `org.kie.kogito:kogito-addons-{quarkus|springboot}-events-decisions` event-driven add-on is now available as technology preview. On {QUARKUS}, you can add the `io.quarkus:quarkus-kubernetes-service-binding` dependency to the application to handle the service binding created by the managed Kafka. On Spring boot, you must add the `mappings` field to the created service binding which must contain the required environment variables needed by the application. Another solution is to use the custom configuration maps available in the {KOGITO} operator.

ifdef::PAM[]

== Support for Quarkiverse File Vault and keystore files with the Process Instance Migration Keystore Vault

You can use the Quarkiverse File Vault extension to store credentials as keystore files and use the `file` method to use the keystore files with the Process Instance Migration (PIM) Keystore Vault.

endif::PAM[]
