[id='rn-tech-preview-con']
= Technology preview

This section lists features that are in technology preview in {PRODUCT} {PRODUCT_VERSION}.

[IMPORTANT]
====
These features are for Technology Preview only. Technology Preview features
are not supported with Red Hat production service level agreements (SLAs), might
not be functionally complete, and Red Hat does not recommend to use them for
production. These features provide early access to upcoming product features,
enabling customers to test functionality and provide feedback during the
development process.
For more information on Red Hat Technology Preview features,
see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
====

== Technology preview features

* Aliases: You can use aliases instead of container IDs in the remote REST APIs of the Planner Server.
* Application lifecycle automation: Part of {PRODUCT} and disabled by default.
//* Content Management System (CMS) page: Part of {PRODUCT} and disabled by default.
* Embedded jBPM use case with a DBCP datasource.
* High-availability authoring on {EAP} (on premise). Configuration of {CENTRAL} for high availability is currently tech preview. Search and messaging technology used to enable search feature is considered an implementation detail. {PRODUCT} may choose to replace that technology in the future while preserving the capability offered.
//* OpenShift Container Platform: Provisioning user interface: Enables you to provision a server on OpenShift while running the selected project build from Decision Central. It is part of {PRODUCT} and disabled by default.
* Clustering for the OpenShift development environment: Enables high-availability while authoring.
//https://issues.jboss.org/browse/BAPL-896
//* Monitoring console: Enables you to manage containers, process instances, tasks, dashboards, and other runtime capabilities. No authoring capabilities are available.
* Predictive Model Markup Language (PMML): The PMML feature is fully implementated for the following predictive model types:
** Decision tree
** Regression
** Scorecard
+
PMML has a partial implementation of the Mining Model type. The Select All, Select First, and Model Chaining sub-types are available.

* Multi-threaded execution: Solves a single data set by partitioning across multiple threads. It is turned off by default and can be enabled either with a KieBaseConfiguration option or with a system property as explained in http://docs.jboss.org/drools/release/7.5.0.Final/drools-docs/html_single/#_multi-threaded_rule_engine[Drools Documentation]
* Rule Units: Rule Units represent a declarative approach to partitioning a rule set into smaller units, binding different data sources to those units, and the execution of the individual unit. A Rule Unit consists of data sources, global variables, and rules.
* Executable model: Provides a pure Java-based representation of a rule set, together with a convenient Java DSL to programmatically create such model.
//https://issues.jboss.org/browse/BXMSDOC-2588
* Elasticsearch is available with this release, however it is currently in technical preview.

== Technology Preview experimental features
The following Technology Preview features are experimental and may require additional API changes.

=== Enabling Application Lifecycle Automation and Provisioning User Interface
{PRODUCT} settings allow you to enable the Application Lifecycle Automation and Provisioning User Interface features.

.Procedure
. Go to *Settings*-> *Roles*-> *admin*.
. Expand *Pages* and click the *Read* field to enable *Deployments*.


=== Enabling Predictive Model Markup Language (PMML)
This feature uses a single configuration option, `org.drools.compiler.compiler.PMMLCompiler` which has the following valid options:

* `org.kie.pmml.pmml_4_2.PMML4Compiler`: This value should be used for the majority of cases where PMML support is desired.
* `org.drools.pmml.pmml_4_2.PMML4Compiler`: This value provides backward compatibility, and should only be used in cases where there is a reliance on the older drools-pmml and drools-scorecards modules.
