[id='rn-tech-preview-con']
= Technology preview

This section lists features that are in technology preview in {PRODUCT} {PRODUCT_VERSION}. {CENTRAL} includes an experimental features administration page which is disabled by default. To enable this page, set the value of the `appformer.experimental.features` property to `true`.

[IMPORTANT]
====
These features are for Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
====

//==  Red Hat JBoss Data Grid 

//Red Hat JBoss Data Grid replaces Elasticsearch as the distributed highly scaleable full-text search and analytics engine for {PRODUCT} {PRODUCT_VERSION_LONG} clustered environments on {EAP_LONG} {EAP_VERSION}. 
 
//Red Hat Data Grid is built from the Infinispan open-source software project and contains indexing capabilities that enable you to store, search, and analyze high volumes of data quickly and in near-real time. In a {PRODUCT} clustered environment, it enables you to perform complex and efficient searches across cluster nodes.
== High-availability authoring on {EAP} (on premise and with OpenShift) 
Configuration of {CENTRAL} for high availability is currently technology preview. Search and messaging technology used to enable search feature is considered an implementation detail. {PRODUCT} may choose to replace that technology in the future while preserving the capability offered.
 
== Prometheus monitoring and metrics for business rules and Decision Model and Notation (DMN) models
Prometheus is an open-source systems monitoring and alerting toolkit that you can use with {PRODUCT} to store metrics related to the execution of rules or DMN models, and then analyze the metrics using a data-graphing tool, such as Grafana.

--
To enable the Prometheus extension in {KIE_SERVER}, set the `org.kie.prometheus.server.ext.disabled` system property to `false` and add the following dependencies to the `pom.xml` file of your Maven project:
 
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-services-prometheus</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
 
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-rest-prometheus</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
----
 
On Spring Boot, configure the following key in the `application.properties` system property:
 
[source,xml]
----
kieserver.drools.enabled=true
kieserver.dmn.enabled=true
kieserver.prometheus.enabled=true
----
 
To configure Prometheus to scrape metrics from {KIE_SERVER}, add the following settings to the `prometheus.yaml` file:
--
 [source,yaml]
----
scrape_configs:
metrics_path: /rest/metrics
static_configs:
- targets: ['localhost:8090']
----
Replace the `targets` value with the location of your {KIE_SERVER} or {KIE_SERVERS}.

ifdef::PAM[]
== Case modeler
Case modeler now provides the option to model a case as a sequence of stages so it is simple to define a case model at high-level. Case modeling supports three types of tasks: human tasks, sub-processes, and sub-cases. 

[NOTE]
====
The case modeler in {PRODUCT} {PRODUCT_VERSION} is a Technology Preview feature and is disabled by default in {CENTRAL}. To enable the case modeler preview in {CENTRAL}, in the upper-right corner of the window click *Settings* -> *Roles*, select a role from the left panel, click *Editors* -> *(New) Case Modeler* -> *Read*, and then click *Save* to save the changes.
====
endif::PAM[]
