[id='rn-tech-preview-con']
= Technology preview

This section lists features that are in Technology Preview in {PRODUCT} {PRODUCT_VERSION}. {CENTRAL} includes an experimental features administration page that is disabled by default. To enable this page, set the value of the `appformer.experimental.features` property to `true`.

[IMPORTANT]
====
These features are for Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
====

== Deployment on restricted networks
You can use Operator Lifecycle Management to deploy {PRODUCT} on restricted networks that do not have a connection to the public Internet.

== Deploying a high-availability authoring environment on {OPENSHIFT} 4.x
You can deploy a high-availability {PRODUCT} authoring environment on {OPENSHIFT} 4.x using the operator.

ifdef::PAM[]
== Case modeler
Case modeler in {CENTRAL} now includes the new process designer. It provides the option to model a case as a sequence of stages so it is simple to define a case model at high-level. Case modeling supports three types of tasks: human tasks, sub-processes, and sub-cases.

[NOTE]
====
The case modeler in {PRODUCT} {PRODUCT_VERSION} is a Technology Preview feature and is disabled by default in {CENTRAL}. To enable the case modeler preview in {CENTRAL}, in the upper-right corner of the window click *Settings* -> *Roles*, select a role from the left panel, click *Editors* -> *(New) Case Modeler* -> *Read*, and then click *Save* to save the changes.
====

== Process instance migration as a standalone service
Process instance migration is now available as a standalone service that contains a user interface and a back end, and packaged as a Thorntail uber JAR. The process instance migration service enables you to define the migration between two different process definitions, known as a migration plan. You can apply the migration plan to the running process instances in a specific {KIE_SERVER}.

For more information about the process instance migration standalone service, see the https://github.com/kiegroup/droolsjbpm-integration/tree/master/process-migration-service[Process Instance Migration Service] page in GitHub.

== Prediction Service API

You can use the Prediction Service API to provide a prediction service that assists with human tasks. The prediction service can use AI. For example, you can use Predictive Model Markup Language (PMML) models or Statistical Machine Intelligence and Learning Engine (SMILE) to implement the service.

endif::PAM[]

== Constraint Streams API

You can use the Constraint Streams API as an alternative to the Drools Rules Language (DRL) to program incremental score calculations in plain Java. The Constraint Streams API is fast, scalable, and debuggable. You can use any IDE to develop and debug solvers using the Constraint Streams API. It uses deltas that enable the engine to redo only necessary calculations. It also supports justifications, so you can review the reason a solution was reached in order to debug the solver. Note that the Constraint Streams API fully supports the NQueens, Task assigning, and Flight Crew Scheduling use cases.

== OpenShift operator installer wizard
An installer wizard is provided in the OpenShift operator for {PRODUCT}. You can use the wizard to deploy a {PRODUCT} environment on {OPENSHIFT} with the Operator.
