[id='rn-tech-preview-con']
= Technology preview

This section lists features that are in technology preview in {PRODUCT} {PRODUCT_VERSION}. {CENTRAL} includes an experimental features administration page which is disabled by default. To enable this page, set the value of the `appformer.experimental.features` property to `true`.

[IMPORTANT]
====
These features are for Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
====

== Decision Model and Notation (DMN) designer
The Decision Model and Notation (DMN) designer in {CENTRAL} is now fully supported in {PRODUCT} {PRODUCT_VERSION}. You can use the new DMN designer in {CENTRAL} to design DMN decision requirements diagrams (DRDs) and define decision logic for a complete DMN decision model. {PRODUCT} {PRODUCT_VERSION} provides both design and runtime support for DMN 1.2 models at conformance level 3, and includes enhancements and fixes to FEEL and DMN model components to optimize the experience of implementing DMN decision services with {PRODUCT}. 
 
The improved DMN designer also includes the following notable enhancements:
 
* New support for decision service nodes in DRDs
* Automatic layout for imported DRDs
* Improved DMN data types and constraints
* Improved DRD validation when assets are saved or built
 
For more information about DMN support in {PRODUCT} {PRODUCT_VERSION}, see the following resources:

* {URL_DMN_MODELS}[_{DMN_MODELS}_]
* {URL_GETTING_STARTED_DECISION_SERVICE}[_{GETTING_STARTED_DECISION_SERVICE}_]

== Prometheus monitoring and metrics for business rules and Decision Model and Notation (DMN) models
Prometheus is an open-source systems monitoring and alerting toolkit that you can use with {PRODUCT} to store metrics related to the execution of rules or DMN models, and then analyze the metrics using a data-graphing tool, such as Grafana.

--
To enable the Prometheus extension in {KIE_SERVER}, set the `org.kie.prometheus.server.ext.disabled` system property to `false` and add the following dependencies to the `pom.xml` file of your Maven project:
 
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-services-prometheus</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
 
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-rest-prometheus</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
----
 
On Spring Boot, configure the following key in the `application.properties` system property:
 
[source,xml]
----
kieserver.drools.enabled=true
kieserver.dmn.enabled=true
kieserver.prometheus.enabled=true
----
 
To configure Prometheus to scrape metrics from {KIE_SERVER}, complete the following steps:

. Add the following settings to the `prometheus.yaml` file:
+
[source,yaml]
----
scrape_configs:
    metrics_path: /rest/metrics
    static_configs:
      - targets: ['localhost:8090']
----
. Replace the `targets` value with the location of your {KIE_SERVER} or {KIE_SERVERS}.
--