[id='rn-tech-preview-con']
= Technology preview

This section lists features that are in technology preview in {PRODUCT} {PRODUCT_VERSION}. {CENTRAL} includes an experimental features administration page which is disabled by default. To enable this page, set the value of the `appformer.experimental.features` property to `true`.

[IMPORTANT]
====
These features are for Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
====

== Prometheus monitoring and metrics for business rules and Decision Model and Notation (DMN) models
Prometheus is an open-source systems monitoring and alerting toolkit that you can use with {PRODUCT} to store metrics related to the execution of rules or DMN models, and then analyze the metrics using a data-graphing tool, such as Grafana.

--
To enable the Prometheus extension in {KIE_SERVER}, set the `org.kie.prometheus.server.ext.disabled` system property to `false` and add the following dependencies to the `pom.xml` file of your Maven project:
 
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-services-prometheus</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
 
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-rest-prometheus</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
----
 
On Spring Boot, configure the following key in the `application.properties` system property:
 
[source,xml]
----
kieserver.drools.enabled=true
kieserver.dmn.enabled=true
kieserver.prometheus.enabled=true
----
 
To configure Prometheus to scrape metrics from {KIE_SERVER}, complete the following steps:

. Add the following settings to the `prometheus.yaml` file:
+
[source,yaml]
----
scrape_configs:
    metrics_path: /rest/metrics
    static_configs:
      - targets: ['localhost:8090']
----
. Replace the `targets` value with the location of your {KIE_SERVER} or {KIE_SERVERS}.
--

== OpenShift operator

{PRODUCT} now includes an OpenShift operator. You can use the operator to deploy {PRODUCT} on {OPENSHIFT} if you installed the OpenShift Operator Framework. You can use a YAML file to configure the deployment and the Operator Framework ensures that the deployment remains coherent with the YAML description at all times. You can change the configuration of the deployment at any time using YAML.