[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

=== {CENTRAL} UI updates

The following list provides a summery of {CENTRAL} UI updates:

* Ability to filter process instances by the parent process instance ID
* Ability to rearrange the order of columns on the Task Inbox page

=== Change requests

You can now submit a change request from one branch to another branch of the same project.

=== Removing a service task

If you configured service tasks in the administration menu of {CENTRAL}, you can now remove any of these service tasks.

=== Test Scenarios

The test scenarios designer in {CENTRAL} is now available with the new features supported in {PRODUCT} {PRODUCT_VERSION}.

* If the same data is shared by multiple test scenarios, you can use the *Background* tab to define them once for rules-based as well as DMN-based test scenarios. You can add and define the `GIVEN` data, which is common for the dedicated test scenario simulation, based on the available data objects.

* In rule-based test scenarios, you can use the MVEL expression with the prefix *#* to call a java method to a property or instance header cell during test scenarios execution.  

=== Generic error dialog improvement in {CENTRAL}

A generic error dialog is a pop-up window that notifies users about different runtime errors that are produced in {CENTRAL}.
The following list provides a summary of generic error dialog enhancements:

* When an error is generated, the error is logged in the server logs. You can fetch and retrieve the generated errors if required.
* You can see the stack trace of the generated error in the popup itself.
* To suppress the error notifications temporarily, select the *Don't show this message again for* checkbox and select the time duration from the drop-down list. However, the error messages are still logged in the server logs.
* It provides an error ID to fetch the error details if required.

=== Decision Model and Notation (DMN) designer improvements

The Decision Model and Notation (DMN) designer in {CENTRAL} includes the following notable enhancements:

* Automatic layout and decision service enhancements. You can now select *Perform automatic layout* in the DMN designer toolbar if a DMN model that you import into {CENTRAL} is not automatically formatted during the import. When automatic layout is applied to an imported DMN model, the DMN designer retains the height and width of each DMN node instead of using the default size of 100x50 pixels. Also, the nodes inside of an imported decision service node are not reordered outside of the decision service node as they were in previous releases. If you delete a decision service node from a decision requirements diagram (DRD), the nodes inside of the decision service are not deleted as they were in previous releases.
* Improved layout for data type rows in the *Data Types* tab. You can now drag data type elements between parent data types.
* Support for {CENTRAL} data objects as DMN data types. You can now import existing data objects in {CENTRAL} as DMN data types in the DMN designer. To import existing data objects as DMN data types, go to *Data types* -> *Import data object* in the DMN designer.

For more information about DMN support in {PRODUCT} {PRODUCT_VERSION}, see the following resources:

* {URL_DMN_MODELS}[_{DMN_MODELS}_]
* {URL_GETTING_STARTED_DECISION_SERVICE}[_{GETTING_STARTED_DECISION_SERVICE}_]

=== High-availability {CENTRAL}

High-availability (HA) deployment of {CENTRAL} is now supported on premises (using {EAP}) and on {OPENSHIFT} version 3.11.

In {PRODUCT} version 7.6, HA deployment of {CENTRAL} is supported with certain limitations:

* If a {CENTRAL} instance fails while a user is using it, the user might receive an error message. In this case, the user is redirected to another pod. If {CENTRAL} is configured to use Red Hat Single Sign-on, logging on again is not required. 

* If a {CENTRAL} instance fails during a user operation, data that was not committed (saved) might be lost. 

* If a {CENTRAL} instance fails while the instance is creating a project, an unusable project might be created. 

* If a {CENTRAL} instance fails while the instance is creating an asset, the asset might be created but not indexed so it cannot be used. To make the asset indexed, the user can open the asset in {CENTRAL} and save it again.

ifdef::PAM[]
== Process designer

=== Process designer updates
The following list provides a summary of process designer updates:

* UI enhancements that guide first-time users on adding the first process nodes on the canvas
* Performance improvements, including improvements in load time, node selection, and copy and paste

== Support for case management capabilities
Process designer in {CENTRAL} fully supports case management capabilities.

For more information about case management support in process designer, see the following resources:

* {URL_DESIGNING_CASES}[_{DESIGNING_CASES}_]
* {URL_GETTING_STARTED_CASES}[_{GETTING_STARTED_CASES}_]
* {URL_SHOWCASE_APPLICATION_CASE_MANAGEMENT}[_{SHOWCASE_APPLICATION_CASE_MANAGEMENT}_]

== Process engine

=== Assigning roles for operations
You can now assign required security roles for specific types of operations, for example `execute` or `view`, on a process.
endif::PAM[]

=== API support for requesting all sub-cases that belong to a parent case

In the process engine, when using case management, you can now use the API to request a list of all sub-cases immediately belonging to a parent case or a list of sub-cases belonging to a parent case and to all its sub-cases.

== {PLANNER}

=== {PLANNER} updates

The following list provides a summery of {PLANNER} updates:

* A script that deploys OptaWeb Vechicle Route Planning (VRP) to {OPENSHIFT} from source.
* Move selectors that understand entity sequences.
* Support for ReactJs and SpringBoot with OptaWeb Employee Rostering.
* Constraint Streams API full support for the the NQueens, Task assigning, and Flight Crew. 
* Scheduling use cases. Note that other features of the API are still technology preview.

== {OPENSHIFT}

=== Support for AMQ configuration in operator deployment

When deploying {PRODUCT} on {OPENSHIFT} using the operator, you can now configure {KIE_SERVER} to support the JMS API using an external AMQ message broker.

ifdef::PAM[]
== Smart Router
=== Smart Router authentication

Smart Router now provides authentication for {KIE_SERVER} instances by using a system property flag. To configure Smart Router authentication you must define and apply the credentials to Smart Router by using the `addUser` and `removeUser` commands. {KIE_SERVER} uses these credentials to authenticate against Smart Router. The parameters are `username` and `password`. The default `username` is the user's {KIE_SERVER} ID. The credentials are stored in hash format in a file and custom identity providers can be used.endif::PAM[]
endif::PAM[]

