[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

== Reference implementations

The high available event-driven decisioning reference implementations are improved.

.No root access in the container required for HA CEP services
When implementing high available event-driven decisioning in {PRODUCT}, the HA CEP (high-availability complex event processing) services do not require root access within the container.

.On-the-fly KJAR updating of HA CEP services
When implementing high available event-driven decisioning in {PRODUCT}, you can update KJAR HA CEP services without removing and redeploying the HA CEP solution. The content of working memory is preserved.

== {CENTRAL}

=== Maven archetype support in {CENTRAL}

Maven archetype support is now available in {CENTRAL}. To access this functionality, select the *Admin* icon in the top-right corner of the screen and select the *Archetypes* option on the {CENTRAL} *Settings* page. The following list provides a summary of Maven archetypes enhancements:

* You can list, add, validate, set a default, and delete the archetypes.
* You can use them as a template when creating a new project in {CENTRAL}.
* To manage all available archetypes in spaces, go to *Design* -> *<your_space>* -> *Settings* in {CENTRAL}.

ifdef::PAM[]
For more information about archetypes management, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html-single/configuring_business_central_settings_and_properties/index#managing-business-central-archetype-con[Configuring Business Central settings and properties].
endif::PAM[]
ifdef::DM[]
For more information about archetypes management, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.7/html-single/configuring_business_central_settings_and_properties/index#managing-business-central-archetype-con[Configuring Business Central settings and properties].
endif::DM[]

=== Test Scenarios

The test scenarios designer in {CENTRAL} is now available with the new features supported in {PRODUCT} {PRODUCT_VERSION}.

* In DMN-based as well as rule-based test scenarios, it is now possible to define the value of a collection like a list or a map by using an expression in both *GIVEN* and *EXPECT* columns. To add an expression,  you can now choose *Define list* from the collection editor.
* You can now use the {KIE_SERVER} REST API to execute the test scenarios externally. It executes the test scenarios against the deployed project. This functionality is disabled by default, use `org.kie.scenariosimulation.server.ext.disabled` system property to enable it.

ifdef::PAM[]
For more information about test scenarios designer in {CENTRAL}, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html-single/testing_a_decision_service_using_test_scenarios/index#test-designer-list-map-add-remove-item-proc[Testing a decision service using test scenarios].
endif::PAM[]
ifdef::DM[]
For more information about test scenarios designer in {CENTRAL}, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.7/html-single/testing_a_decision_service_using_test_scenarios/index#test-designer-list-map-add-remove-item-proc[Testing a decision service using test scenarios].
endif::DM[]

=== Ability to create a project from empty repositories

You can now create a new project in {CENTRAL} by importing an empty GitHub or GitLab external repository.

=== Squash commit on change requests

You can now squash multiple commits into a single commit and add the commit to a target branch for a change request.
ifdef::PAM[]
For more information about change requests in {CENTRAL}, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html/managing_projects_in_business_central/change-requests-con_managing-projects#reviewing-change-requests-proc_managing-projects[Managing projects in Business Central].
endif::PAM[]
ifdef::DM[]
For more information about change requests in {CENTRAL}, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.7/html/managing_projects_in_business_central/change-requests-con_managing-projects#reviewing-change-requests-proc_managing-projects[Managing projects in Business Central].
endif::DM[]

ifdef::PAM[]

=== Navigation from subprocess instance to parent process instance using the process instance page in {CENTRAL}

The process instance page in {CENTRAL} is now available with new navigation features for the parent and subprocess instance.

* In the *Instance Details* tab, you can now click the *Parent Process Instance ID* field to navigate to the parent *Instance Details* tab.
* In the *Diagram* tab, you can now see a new menu containing links of the parent process and subprocess to navigate between the subprocess and parent process *Diagram* tab.

For more information about process instance management, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html/managing_and_monitoring_business_processes_in_business_central/process-instance-details-con-managing-and-monitoring-processes[Managing and monitoring business processes in Business Central].

endif::PAM[]

=== Code completion for FEEL expressions in Decision Model and Notation (DMN) designer

When typing a FEEL expression in the boxed literal expression editor, you can now see FEEL functions appear as suggestions that you can apply to complete the expression if required.

=== Decision Model and Notation (DMN) designer improvements

The Decision Model and Notation (DMN) designer in {CENTRAL} includes the following notable enhancements:

* New visual indication for the data type nesting levels in a project allowing users to quickly reference nesting details without leaving the editor.
* Zero values are hidden in the *Data Type constraints* wizard to eliminate wasted screen space.
* Improved visual and functional support for the search component placeholder.
* Support for drag and drop to reorder data types.

ifdef::PAM[]

=== New `CaseLogCleanupCommand` command

Starting with {PRODUCT} {ENTERPRISE_VERSION}, support for the `CaseLogCleanupCommand` command to clean up cases based on different parameters.

endif::PAM[]

=== Support for branch management and performing Maven actions on branches using the REST API

Users can now manage branches and perform Maven action on branches using the REST API:

Return all branches in a specific project and space:
----
[GET] /spaces/{spaceName}/projects/{projectName}/branches::
----

Add a specific branch to a specific project and space:
----
[POST] /spaces/{spaceName}/projects/{projectName}/branches::
----

Delete a specific branch from a specific project and space:
----
[DELETE] /spaces/{spaceName}/projects/{projectName}/branches/{branchName}::
----

Compile a specific branch in a specific project and space. If `branchName` is not specified, then the request defaults to using the master branch.
----
[POST] /spaces/{spaceName}/projects/{projectName}/branches/{branchName}/maven/compile::
----

Install a specific branch in a specific project and space. If `branchName` is not specified, then the request defaults to using the master branch.
----
[POST] /spaces/{spaceName}/projects/{projectName}/branches/{branchName}/maven/install::
----

Test a specific branch in a specific project and space. If `branchName` is not specified, then the request defaults to using the master branch.
----
[POST] /spaces/{spaceName}/projects/{projectName}/branches/{branchName}/maven/test::
----

Deploy a specific branch in a specific project and space. If `branchName` is not specified, then the request defaults to using the master branch.
----
[POST] /spaces/{spaceName}/projects/{projectName}/branches/{branchName}/maven/deploy::
----

ifdef::PAM[]
For more information about REST API for {CENTRAL} spaces and projects, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html-single/interacting_with_red_hat_process_automation_manager_using_kie_apis/index#knowledge-store-rest-api-branches-ref_kie-apis[Interacting with Red Hat Process Automation Manager using KIE APIs].
endif::PAM[]
ifdef::DM[]
For more information about REST API for {CENTRAL} spaces and projects, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.7/html-single/interacting_with_red_hat_decision_manager_using_kie_apis/index#knowledge-store-rest-api-branches-ref_kie-apis[Interacting with Red Hat Decision Manager using KIE APIs].
endif::DM[]

=== Support for DMN 1.3

{PRODUCT} {PRODUCT_VERSION} is now DMN 1.3 ready.

=== Supported languages

Starting with the 7.7 release, the {PRODUCT} user interface is now localized in Spanish and French in addition to English and Japanese.

== {DECISION_ENGINE_CAP}

=== Default support for executable rule models in the `kie-maven-plugin` plugin

Rule assets in {PRODUCT} are built from executable rule models by default with the standard `kie-maven-plugin` plugin. Executable rule models are embedded models that provide a Java-based representation of a rule set for execution at build time. The executable model is a more efficient alternative to the standard asset packaging in previous versions of {PRODUCT} and enables KIE containers and KIE bases to be created more quickly, especially when you have large lists of DRL (Drools Rule Language) files and other {PRODUCT} assets.

If you are upgrading to {PRODUCT} {PRODUCT_VERSION} from a previous version of the product and you have not already enabled executable rule models, you must add the required dependency to your existing {PRODUCT} projects so that your rule assets are built from executable models in {PRODUCT} {PRODUCT_VERSION}.

For instructions on enabling executable rule models when upgrading to {PRODUCT} {PRODUCT_VERSION}, see
ifdef::DM,PAM[]
{URL_PATCHING_UPGRADING}#executable-model-upgrading-proc_patching-upgrading[_{PATCHING_UPGRADING}_].
endif::[]
ifdef::DROOLS,JBPM,OP[]
xref:executable-model-upgrading-proc_packaging-deploying[].
endif::[]

For more information about executable rule models, see
ifdef::DM,PAM[]
{URL_PACKAGING_DEPLOYING_PROJECT}#executable-model-con_packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].
endif::[]
ifdef::DROOLS,JBPM,OP[]
xref:executable-model-con_packaging-deploying[].
endif::[]

== Integration
ifdef::PAM[]

=== Spring Boot applications

Spring Boot applications now provide Spring bean support for the `notificationlistener` class.

endif::[]

== {PLANNER}

=== Added Spring Boot starter

{PLANNER}
now includes a Spring Boot starter. You can use the Spring Boot starter to avoid common issues with class loading and use `application.properties` to overwrite the solver configuration. The `solverConfig.xml` file is no longer required because the starter automatically detects `@PlanningSolution` and `@PlanningEntity` annotations.
The constraint streams API is improved. You can now modify your streams using the `groupBy()` building block.

ifdef::PAM[]
For more information, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html-single/creating_red_hat_process_automation_manager_business_applications_with_spring_boot/index[Creating Red Hat Process Automation Manager business applications with Spring Boot].
endif::PAM[]
ifdef::DM[]
For more information, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.7/html-single/creating_red_hat_decision_manager_business_applications_with_spring_boot/index[Creating Red Hat Decision Manager business applications with Spring Boot].
endif::DM[]

=== SolverManager

You can use SolverManager as wrapper for one or more Solver instances to simplify planning REST API and other enterprise services. The `solve(…​)` methods differ from the normal `Solver.solve(…​)` method:

* `SolverManager.solve(…​)` schedules a problem for asynchronous solving without blocking the calling thread. This avoids timeout issues of HTTP and other technologies. It returns immediately.
* `SolverManager.solve(…​)` solves multiple planning problems of the same domain, in parallel.

SolverManager supports batch solving and solving that displays the progress to the end-user:
----
public class TimeTableService {
    private SolverManager<TimeTable, Long> solverManager;

    // Returns immediately, ok to expose as a REST service
    public void solve(Long timeTableId) {
        solverManager.solveAndListen(timeTableId,
            // Called once, when solving starts
            this::findById,
            // Called multiple times, for every best solution change
            this::save);
    }
    public TimeTable findById(Long timeTableId) {...}
    public void save(TimeTable timeTable) {...}
    public void stopSolving(Long timeTableId) {
        solverManager.terminateEarly(timeTableId);
    }
}
----

== {OPENSHIFT}

=== Support for Git hooks in operator deployment on {OPENSHIFT}

When deploying {PRODUCT} on {OPENSHIFT} using the operator, you can configure Git hooks to enable interaction between the built in Git repository of {CENTRAL} and other repositories.

ifdef::PAM[]
For more information, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html/deploying_a_red_hat_process_automation_manager_environment_on_red_hat_openshift_container_platform_using_operators/operator-con#operator-deploy-central-proc[Deploying a Red Hat Process Automation Manager environment on Red Hat OpenShift Container Platform using Operators].
endif::PAM[]
ifdef::DM[]
For more information, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.7/html-single/deploying_a_red_hat_decision_manager_environment_on_red_hat_openshift_container_platform_using_operators/index#operator-deploy-central-proc[Deploying a Red Hat Decision Manager environment on Red Hat OpenShift Container Platform using Operators].
endif::DM[]

=== Support for role mapping in operator deployment on {OPENSHIFT}

When deploying {PRODUCT} on {OPENSHIFT} using the operator and using RH-SSO or LDAP authentication, you can configure role mapping to link roles defined in {PRODUCT} to different roles defined in RH-SSO or LDAP.

ifdef::PAM[]
For more information about role mapping in operator deployment on {OPENSHIFT}, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html/deploying_a_red_hat_process_automation_manager_environment_on_red_hat_openshift_container_platform_using_operators/operator-con#operator-deploy-security-proc[Deploying a Red Hat Process Automation Manager environment on Red Hat OpenShift Container Platform using Operators].
endif::PAM[]
ifdef::DM[]
For more information about role mapping in operator deployment on {OPENSHIFT}, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.7/html/deploying_a_red_hat_decision_manager_environment_on_red_hat_openshift_container_platform_using_operators/operator-con#operator-deploy-security-proc[Deploying a Red Hat Decision Manager environment on Red Hat OpenShift Container Platform using Operators].
endif::DM[]

ifdef::PAM[]

=== Support for external database drivers in operator deployment on {OPENSHIFT}

When deploying {PRODUCT} on {OPENSHIFT} using the operator and configuring a {KIE_SERVER} to use an external database server, you can configure the use of an Oracle, Sybase, DB2, or MS SQL server.

For more information, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html/deploying_a_red_hat_process_automation_manager_environment_on_red_hat_openshift_container_platform_using_operators/operator-con#operator-deploy-kieserver-proc[Deploying a Red Hat Process Automation Manager environment on Red Hat OpenShift Container Platform using Operators].

endif::PAM[]

=== Support for JVM configuration in operator deployment on {OPENSHIFT}

When deploying {PRODUCT} on {OPENSHIFT} using the operator, you can set custom JVM configuration for {CENTRAL} and {KIE_SERVER} pods.

ifdef::PAM[]
For more information about JVM configuration in operator deployment on {OPENSHIFT}, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html/deploying_a_red_hat_process_automation_manager_environment_on_red_hat_openshift_container_platform_using_operators/operator-con#operator-deploy-central-proc[Deploying a Red Hat Process Automation Manager environment on Red Hat OpenShift Container Platform using Operators].
endif::PAM[]
ifdef::DM[]
For more information about JVM configuration in operator deployment on {OPENSHIFT}, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.7/html/deploying_a_red_hat_decision_manager_environment_on_red_hat_openshift_container_platform_using_operators/operator-con#operator-deploy-central-proc[Deploying a Red Hat Decision Manager environment on Red Hat OpenShift Container Platform using Operators].
endif::DM[]

=== Deploying an authoring environment on {OPENSHIFT} without ReadWriteMany support

When deploying {PRODUCT} on {OPENSHIFT}, you can deploy an authoring environment if your {OPENSHIFT} infrastructure does not provision persistent modules that support the ReadWriteMany mode.

ifdef::PAM[]
For more information, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html/deploying_a_red_hat_process_automation_manager_authoring_environment_on_red_hat_openshift_container_platform/index[Deploying a Red Hat Process Automation Manager authoring environment on Red Hat OpenShift Container Platform].
endif::PAM[]

=== A single built-in user account for communication between {CENTRAL} and {KIE_SERVER}

{PRODUCT} now uses a single built-in administrative user account for communication between {CENTRAL} and {KIE_SERVER}. You no longer need to configure multiple built-in user accounts.

ifdef::PAM[]
For more information, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html/deploying_a_red_hat_process_automation_manager_authoring_environment_on_red_hat_openshift_container_platform/dm-openshift-prepare-con#secret-adminuser-create-proc[Deploying a Red Hat Process Automation Manager authoring environment on Red Hat OpenShift Container Platform].
endif::PAM[]

=== Support for concurrent service deployment on a {KIE_SERVER} in a {PRODUCT} authoring environment on {OPENSHIFT}

If you deploy a {PRODUCT} authoring environment on {OPENSHIFT} 3.x using templates, you can deploy several services on the same {KIE_SERVER} concurrently, without needing to wait for a deployment to complete before you can start the next deployment. This functionality is provided by the *ControllerBasedStartupStrategy* setting that applies to communication between {CENTRAL} and {KIE_SERVER}. You can also enable this strategy when deploying on {OPENSHIFT} 4.x using the operator.

ifdef::PAM[]
For more information, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html/deploying_a_red_hat_process_automation_manager_authoring_environment_on_red_hat_openshift_container_platform/environment-authoring-con[Deploying a Red Hat Process Automation Manager authoring environment on Red Hat OpenShift Container Platform].
endif::PAM[]
ifdef::DM[]
For more information, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.7/html/deploying_a_red_hat_decision_manager_authoring_or_managed_server_environment_on_red_hat_openshift_container_platform/environment-authoring-con[Deploying a Red Hat Decision Manager authoring or managed server environment on Red Hat OpenShift Container Platform].
endif::DM[]

=== Support for deploying {PRODUCT} on {OPENSHIFT} 4.3

Deploying {PRODUCT} using the operator on {OPENSHIFT} 4.3 is now supported.

ifdef::PAM[]
For more information about deploying {PRODUCT} on {OPENSHIFT} 4.3, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/html/deploying_a_red_hat_process_automation_manager_environment_on_red_hat_openshift_container_platform_using_operators/index[Deploying a Red Hat Process Automation Manager environment on Red Hat OpenShift Container Platform using Operators].
endif::PAM[]
ifdef::DM[]
For more information about deploying {PRODUCT} on {OPENSHIFT} 4.3, see https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.7/html/deploying_a_red_hat_decision_manager_environment_on_red_hat_openshift_container_platform_using_operators/index[Deploying a Red Hat Decision Manager environment on Red Hat OpenShift Container Platform using Operators].
endif::DM[]

=== {EAP} version updated to 7.2.6

In {PRODUCT} images for {OPENSHIFT}, the {EAP} version is updated to 7.2.6.
