[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

=== Multiple GIT branch support 
{CENTRAL} now provides multiple GIT branch support which enables you to work on multiple source branches interchangeably.  On the *Project* page, select the branch menu on the breadcrumb to access this feature.

ifdef::PAM[]
=== New event nodes
The Process Designer interface includes new conditional and escalation nodes to improve business process authoring capabilities.

Conditional events define an event that is triggered if a given condition is evaluated to `true`. The following conditional events have been added in {PRODUCT} {PRODUCT_VERSION}: 

* Start Conditional event
* Intermediate Conditional event

Escalation events are used to communicate from a subprocess to a parent process. An escalation event is non critical and execution continues. The following escalation events have been added in {PRODUCT} {PRODUCT_VERSION}:

* Start Escalation event
* Catch Intermediate Escalation event
* Throw Intermediate Escalation event
* End Escalation event
endif::[]

== {KIE_SERVER}

=== Decision Model and Notation (DMN) models
{PRODUCT} {PRODUCT_VERSION} includes full runtime support for DMN 1.2 models at conformance level 3. {PRODUCT} {PRODUCT_VERSION} currently does not include a built-in DMN model designer, but you can design your DMN models using a third-party DMN authoring tool and include them in your {PRODUCT} projects for deployment and execution. A DMN model designer will be added to {PRODUCT} in the near future.

For more information about DMN support in {PRODUCT} {PRODUCT_VERSION}, see {URL_DMN_MODELS}[_{DMN_MODELS}_].

ifdef::PAM[]
=== Case Management Model Notation (CMMN) support
CMMN 1.1 is now supported. You can use {CENTRAL} to import, view, and modify the content of `.cmmn` files. When authoring a project, you can import your case management model and then select it from the asset list to view or modify in the standard XML editor.

The following CMMN 1.1 constructs are currently available:

* Tasks (human task, process task, decision task, case task)
* Discretionary tasks (same as above)
* Stages
* Milestones
* Case file items
* Sentries (entry and exit)

Required, repeat, and manual activation tasks are currently not supported. Sentries for individual tasks are limited to entry criteria while entry and exit criteria are supported for stages and milestones. Decision task maps by default to DMN decision. Event listeners are not supported.
endif::[]

=== Executable rule models
Executable rule models are embeddable models that provide a Java-based representation of a rule set for execution at build time. The executable model is a more efficient alternative to the standard asset packaging in {PRODUCT} and enables KIE containers and KIE bases to be created more quickly, especially when you have large lists of DRL (Drools Rule Language) files and other {PRODUCT} assets.

For more information about executable rule models in {PRODUCT} {PRODUCT_VERSION}, see {URL_DRL_RULES}#executable-model-con_execute-rules["Executable rule models" in _{DRL_RULES}_].

=== Predictive Modeling Markup Language (PMML) models
{PRODUCT} {PRODUCT_VERSION} now supports the following PMML 4.2.1 model types:

* Regression models
* Scorecard models
* Tree models
* Mining models (with sub-types `modelChain`, `selectAll`, and `selectFirst`)

More PMML model types and Mining model sub-types will be supported as they become available.

For more information about PMML support in {PRODUCT} {PRODUCT_VERSION}, see {URL_PMML_MODELS}[_{PMML_MODELS}_].

=== Spring Boot support
You can use the following Spring Boot starters to bootstrap your projects with Spring Boot:

* {CENTRAL} process management - embedded engine
** `groupId: org.kie`
** `artifactId: jbpm-spring-boot-starter-basic`

* Fully featured {KIE_SERVER} 
** `groupId: org.kie`
** `artifactId: kie-server-spring-boot-starter`

* Rules and Descisions {KIE_SERVER} 
** `groupId: org.kie`
** `artifactId: kie-server-spring-boot-starter-drools`

* Rules and Descisions, Process and Cases {KIE_SERVER} 
** `groupId: org.kie`
** `artifactId: kie-server-spring-boot-starter-jbpm`

* Planning {KIE_SERVER} 
** `groupId: org.kie`
** `artifactId: kie-server-spring-boot-starter-optaplanner`

ifdef::PAM[]
== Smart Router
Support for HTTPS is now available with Smart Router.
endif::[]

== {PLANNER}

=== Multithreaded incremental solving
{PLANNER} now supports multithreaded incremental solving. The solving process can now run on several CPU cores in parallel while remaining fully reproducible through repeated runs. Depending on the task, using four cores can increase the speed by a factor of three or more compared to solving on a single core. You do not need to modify the task source to use multithreaded incremental solving.

=== Employee Rostering
The Employee Rostering starter application has been significantly improved:

* You can now create a new tenant so you can use the application with your own real-world data and enter this data starting from a blank slate.
* The user interface was improved, including notifications and performance.
* You can now select the week to view instead of scrolling through long time periods.
