[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

=== {CENTRAL} UI updates
The following list provides a summary of the Business Central UI updates:

* Ability to customize rule name and view *Rule Name* column in a guided decision table
* Ability to specify default values for the new rows in a guided decision table
* Ability to process multiple worksheet decision tables in a spreadsheet workbook

For more information, see {URL_GUIDED_DECISION_TABLES}[_{GUIDED_DECISION_TABLES}_] and {URL_SPREADSHEET_DECISION_TABLES}[_{SPREADSHEET_DECISION_TABLES}_].

=== Enhancement to export to excel
Support for expressions, multiple BRL columns, and rule order hit policy is now available when a guided decision table is exported to excel.
For more information, see {URL_GUIDED_DECISION_TABLES}[_{GUIDED_DECISION_TABLES}_].

=== Code completion for FEEL expressions improvement in Decision Model and Notation (DMN) designer
When typing a FEEL expression in the boxed literal expression editor, you can now see node names appear as suggestions that you can apply to complete the expression if required.

=== Support for metadata attributes in BPMN modeler
You can now use *Metadata Attributes* property and manage the generic attributes of a business process. For more information, see {URL_BPMN2_REFERENCE_GUIDE}[_{BPMN2_REFERENCE_GUIDE}_].

ifdef::PAM[]

=== Support for variable tagging in processes
The {PRODUCT} process designer now supports variable tagging for the business processes including `required`, `readonly`, `restricted`, and `customTags` tags.
For more information, see {URL_DESIGNING_BUSINESS_PROCESSES}[_{DESIGNING_BUSINESS_PROCESSES}_].

=== Business Keys for case management
{PRODUCT} {ENTERPRISE_VERSION} includes additional support for further customizing the case identifier generation. For more information, see {URL_DESIGNING_CASES}[_{DESIGNING_CASES}_].

=== Full support for process instance migration
Users can apply their migration plan to the running process instance in a specific KIE Server. For more information, see {URL_MANAGING_PROCESSES}[_{MANAGING_PROCESSES}_].

=== View reusable subprocess from the parent process
{PRODUCT}{ENTERPRISE_VERSION} provides support to view reusable subprocess from the parent process. Reusable subprocesses appear collapsed within the parent process. You can double-click on the reusable subprocess node to open its diagram from the parent process diagram.
For more information, see {URL_MANAGING_PROCESSES}[_{MANAGING_PROCESSES}_].

=== Prediction service for task augmentation
The prediction service for task augmentation is integrated with Open Data Hub Artificial intelligence (AI) and Machine learning (ML) services. There is a proof of concept (POC) available for Fraud Detection.

endif::PAM[]

=== Support for Security Management actions and updating space components using the REST API
You can now perform *Security Management* actions and update space components using the REST API:

* Update `description`, `owner`, and `defaultGroupId` of a space
+
[source]
----
[PUT] /spaces
----

* Return all groups in {CENTRAL}
+
[source]
----
[GET] /groups
----

* Create a group in {CENTRAL}
+
[source]
----
[POST] /groups
----

* Delete a specified group from {CENTRAL}
+
[source]
----
[DELETE] /groups/{groupName}
----

* Return all roles in {CENTRAL}
+
[source]
----
[GET] /roles
----

* Return all users in {CENTRAL}
+
[source]
----
[GET] /users
----

* Return all groups assigned to a specified user
+
[source]
----
[GET] /users/{userName}/groups
----

* Return all roles assigned to a specified user
+
[source]
----
[GET] /users/{userName}/roles
----

* Create a specified user with specified roles and groups
+
[source]
----
[POST] /users
----

* Change the password of a specified user
+
[source]
----
[Post] /users/{userName}/changePassword
----

* Delete a specified user from {CENTRAL}
+
[source]
----
[DELETE] /users/{userName}
----

* Override the existing groups assigned to a specified user with new groups
+
[source]
----
[POST] /users/{userName}/groups
----

* Override the existing roles assigned to a specified user with new roles
+
[source]
----
[POST] /users/{userName}/roles
----

* Return all permissions granted to a specified group
+
[source]
----
[GET] /groups/{groupName}/permissions
----

* Return all permissions granted to a specified role
+
[source]
----
[GET] /roles/{roleName}/permissions
----

* Return all permissions granted to a specified user
+
[source]
----
[GET] /users/{userName}/permissions
----

* Update the permissions of a specified group
+
[source]
----
[Post] /groups/{groupName}/permissions
----

* Update the permissions of a specified role
+
[source]
----
[Post] /roles/{roleName}/permissions
----

For more information, see {URL_KIE_APIS}[_{KIE_APIS}_].

=== Test Scenarios
The test scenarios designer in {CENTRAL} now supports the enumeration data type in rule-based test scenarios.

== {DECISION_ENGINE_CAP}

=== Executable model lambda externalization optimization
The new executable model optimization improves memory consumption at runtime. It rewrites how the lambdas are generated that are used in the executable model. The lambda externalization is enabled by default. To disable the lambda externalization, use the following key:

[source]
----
 -Ddrools.externaliseCanonicalModelLambda=false
----
For more information, see {URL_DECISION_ENGINE_DOC}[_{DECISION_ENGINE_DOC}_].

ifdef::PAM[]

== {PROCESS_ENGINE_CAP}

=== Start a business process from a specific node
You can now start a business process from a specific node after the business process is terminated.

=== New notification listener properties
{PRODUCT} {ENTERPRISE_VERSION} includes two new jBPM properties. These `org.kie.jpbm.notification_listeners.include` and `org.kie.jpbm.notification_listeners.exclude` properties are used to enable and disable notification listeners.

=== OR operator for custom queries
{PRODUCT} {ENTERPRISE_VERSION} includes an OR operator to define query filters.

endif::PAM[]

== {PLANNER}

=== {PLANNER} Constraint Streams API
The Constraint Streams API is now fully supported.

=== Automatic {KIE_SERVER} task assigning
{KIE_SERVER} optimization and business process management capabilities are integrated so human tasks that belong to a process can be automatically assigned to users based on continuous schedule optimization planning.

=== Vehicle route planning starter application
The vehicle route planning starter application includes user interface improvements, server error reporting, and a new run script.

== {OPENSHIFT}

=== Support for deployment on {OPENSHIFT} 4.5
You can now deploy {PRODUCT} on {OPENSHIFT} 4.5.

=== Custom image creation for {KIE_SERVER} on {OPENSHIFT}
You can now create and use custom {KIE_SERVER} images with additional JAR or RPM packages.
For more information about creating custom images, see {URL_DEPLOYING_OPENSHIFT_OPERATOR}/customimage-con_openshift-operator#customimage-con_openshift-operator[Creating custom images for {KIE_SERVER}] in _{DEPLOYING_OPENSHIFT_OPERATOR}_.

=== SSH authentication for Git hooks on {OPENSHIFT} 4.x
When configuring Git hooks for {CENTRAL} on {OPENSHIFT} 4.x, you can now configure SSH authentication for access to custom Git repositories.
For more information about preparing Git hooks for deployment, see {URL_DEPLOYING_OPENSHIFT_OPERATOR}/dm-openshift-prepare-con#githooks-prepare-proc-openshift-operator[Preparing Git hooks] in _{DEPLOYING_OPENSHIFT_OPERATOR}_.

=== Metering labels for images in {OPENSHIFT}
{PRODUCT} images for {OPENSHIFT} now have labels that enable the use of OpenShift metering. For more information about using metering, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html/metering/index[_Metering_] in {OPENSHIFT} documentation.

ifdef::PAM[]

=== Support for deploying production environments on {OPENSHIFT} 4.x without ReadWriteMany access to a persistent volume
You can now deploy a production environment for {PRODUCT} on {OPENSHIFT} 4.x with a simplified version of {CENTRAL} monitoring that does not require ReadWriteMany access to a persistent volume.
For more information about deploying {PRODUCT} on {OPENSHIFT} 4.x, see {URL_DEPLOYING_OPENSHIFT_OPERATOR}/operator-con#operator-environment-deploy-assy[Deploying a {PRODUCT} environment using the operator] in _{DEPLOYING_OPENSHIFT_OPERATOR}_.

=== Process instance migration service on {OPENSHIFT} 4.x
You can now deploy the Process Instance Migration (PIM) service on {OPENSHIFT} 4.x. You can use the PIM service to define the migration between two different process definitions, known as a migration plan. You can then apply the migration plan to the running process instances in a specific {KIE_SERVER}.

For more information about deploying {PRODUCT} on {OPENSHIFT} 4.x, see {URL_DEPLOYING_OPENSHIFT_OPERATOR}/operator-con#operator-environment-deploy-assy[Deploying a {PRODUCT} environment using the operator] in _{DEPLOYING_OPENSHIFT_OPERATOR}_.
[NOTE]
====
Process Instance Migration (PIM) service currently use the limited database support on {OPENSHIFT}. The support for external databases will be added in the future release.
====
endif::PAM[]
