[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

ifdef::DM[]

== Unified product deliverable and deprecation of {PRODUCT} distribution files

In the {PRODUCT_PAM} 7.13 release, the distribution files for {PRODUCT} will be replaced with {PRODUCT_PAM} files. Note that there will not be any change to the {PRODUCT} subscription and the support entitlements and fees will remain the same. {PRODUCT} is a subset of {PRODUCT_PAM}, and {PRODUCT} subscribers will continue to receive full support for the decision management and optimization capabilities. The business process management (BPM) capabilities are exclusive to {PRODUCT_PAM} and will be available for use by {PRODUCT} subscribers but with development support services only. {PRODUCT} subscribers can upgrade to a full {PRODUCT_PAM} subscription at any time to receive full support for BPM features.

{PRODUCT} container images are now deprecated with unified deliverables. {PRODUCT} subscribers can upgrade or install the latest {PRODUCT_PAM} images from version {ENTERPRISE_VERSION} onward instead.

endif::DM[]

== Ability to only enable decision management components and functionality

You can now configure the deployment to only enable decision management related components and functionality so that jBPM and case management features are disabled.

== Ability to change the route termination and enable edge termination

During configuration of the environment, you can now change the route termination, enable edge termination, and set optional credentials.

== Ability to use a custom registry and specific images
You can now configure the custom registry to use specific images during the configuration of the environment.

ifdef::PAM[]

== Ability to output error logs of Eager initialization of Kafka emitters

You can now set the `org.kie.jbpm.event.emitters.eagerInit` property to `true` to output the error log when {KIE_SERVER} starts and initializes the Kafka emitter.

endif::PAM[]

== Ability to use a secret for Admin user during KieApp configuration

You can now use a secret containing the credentials for the Admin user during KieApp configuration.

ifdef::PAM[]

== Process Designer

=== Ability to set the priority of a task as a process variable in {CENTRAL}

It is now possible to set the priority of a task as an MVEL expression.

== {PROCESS_ENGINE_CAP}

=== Support for exploded installation of Spring Boot business automation applications

It is now possible to get support for exploded installations of Spring Boot business automation applications. If the application working directory is not the default directory, you can set it with the `org.kie.maven.resolver.folder=/my-workspace/` variable. Note that for the Spring Boot image you must copy this variable into the `JAVA_TOOL_OPTIONS: "-Dorg.kie.maven.resolver.folder=..."` environment variable.

=== Ability to remove the process ID from the EJB timer column

It is now possible to remove the process ID from the EJB timer column. You can now correlate `process-instance-id` and `ejb-timer-id`.

endif::PAM[]

== DMN Designer

=== Drools DMN Engine support for DMN Specification v1.4

{PRODUCT} now provides runtime support for DMN Specification v1.4 in the Drools DMN engine.

== {PLANNER}

=== {PLANNER} solver with Micrometer

Additional metrics are available for monitoring the {PLANNER_SHORT} solver with Micrometer.

ifdef::PAM[]

== Spring Boot

The `start.jpbm.org` website is no longer available. To create Spring Boot business applications use Maven archetype commands.

endif::PAM[]

== {OPENSHIFT}

=== Custom host name routes
You can now set custom host names for external routes by using the `routeHostname` property.

=== Improved SSL configurability
You can now enable or disable SSL in the operator and expose the SSL route.

=== Default configuration for cross domain resource sharing (CORS)
You can now specify whether to use a default or user-customized CORS configuration.
