[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

== Installation and upgrades

=== Consolidated {PRODUCT} update tool
Previously, {PRODUCT} patch updates and minor release upgrades were applied with separate patch and upgrade tools. With this release, you can use the new `{PRODUCT_INIT}-$VERSION-update.zip` update tool to apply both patch updates and minor release upgrades to {PRODUCT} {PRODUCT_VERSION}. Patch updates of {PRODUCT}, such as an update from version {PRODUCT_VERSION} to {PRODUCT_VERSION}.1, include the latest security updates and bug fixes. Minor release upgrades of {PRODUCT}, such as an upgrade from version {PRODUCT_VERSION}.x to 7.2, include enhancements, security updates, and bug fixes.

ifdef::PAM[]
You can use the new update tool to upgrade from {PRODUCT} 7.0.x to {PRODUCT} {PRODUCT_VERSION}.
endif::PAM[]
For information about using the {PRODUCT} update tool, see {URL_PATCHING_UPGRADING}[_{PATCHING_UPGRADING}_].

ifdef::DM[]
IMPORTANT: To upgrade from {PRODUCT} 7.0.x to {PRODUCT_VERSION}, you must use a {CENTRAL} migration tool provided with the {PRODUCT} {PRODUCT_VERSION} release to accommodate an improved project data structure in {PRODUCT} {PRODUCT_VERSION}. For migration instructions, see {URL_MIGRATING_70_TO_7X}[_{MIGRATING_70_TO_7X}_].
endif::[]

ifdef::DM[]
=== Tomcat 9 support
{PRODUCT} is now available for JBoss Web Server 5.0 with support for Tomcat 9.
endif::[]

== {CENTRAL}

=== Multiple GIT branch support
{CENTRAL} now provides multiple GIT branch support which enables you to work on multiple source branches interchangeably. On the project's page, select the branch drop-down menu in the library breadcrumbs to access this feature.

ifdef::PAM[]
== Process designer

=== New event nodes
The process designer interface includes new conditional and escalation nodes to improve business process authoring capabilities.

Conditional events define an event that is triggered if a given condition is evaluated to `true`. The following conditional events have been added in {PRODUCT} {PRODUCT_VERSION}:

* Start Conditional event
* Intermediate Conditional event

Escalation events can be used to communicate from a subprocess to a parent process or another subprocess. For example, when using a Start Escalation event, which is only available for triggering an in-line event subprocess, communication is from a parent process to a subprocess.

An escalation event is non critical (the execution is not suspended) and execution continues at the location that the even occurred. The following escalation events have been added in {PRODUCT} {PRODUCT_VERSION}:

* Start Escalation event
* Catch Intermediate Escalation event
* End Escalation event
endif::[]

== {KIE_SERVER}

=== Swagger interface for {CONTROLLER} REST API

{PRODUCT} {PRODUCT_VERSION} provides a Swagger web interface for the {CONTROLLER} REST API. You can use this Swagger interface instead of a standalone REST client or curl utility to interact with your {KIE_SERVER} templates (configurations), {KIE_SERVER} instances (remote servers), and associated KIE containers (deployment units) in {PRODUCT}.

To access the Swagger interface for the {CONTROLLER} REST API, you can either start {CENTRAL}, which contains a built-in {CONTROLLER}, or run the {HEADLESS_CONTROLLER} application and navigate to `\http://SERVER:PORT/CONTROLLER/docs` in a web browser.

Example Swagger URLs:

* `\http://localhost:8080/{URL_COMPONENT_CENTRAL}/docs` (for a {CONTROLLER} in {CENTRAL})
* `\http://localhost:8080/my-controller/docs` (for a {HEADLESS_CONTROLLER})

For more information about the {CONTROLLER} REST API, see {URL_KIE_APIS}[_{KIE_APIS}_].

=== Decision Model and Notation (DMN) models
{PRODUCT} {PRODUCT_VERSION} provides both design and runtime support for DMN 1.2 models at conformance level 3, and includes enhancements and fixes to FEEL and DMN model components to optimize the experience of implementing DMN decision services with {PRODUCT}. You can design your DMN models directly in {CENTRAL} or import existing DMN models into your {PRODUCT} projects for deployment and execution.

For more information about DMN support in {PRODUCT} {PRODUCT_VERSION}, see {URL_DMN_MODELS}[_{DMN_MODELS}_].

=== Executable models in Decision Model and Notation (DMN) projects
In {PRODUCT} {PRODUCT_VERSION}, you can now use the `kie-maven-plugin` build component to generate DMN executable model classes and compile them in a {PRODUCT} project (KJAR file). DMN executable model classes are similar to executable rule models used for rule assets. This support enables DMN decision table logic in DMN projects to be evaluated more efficiently.

To enable executable models in DMN projects, add the required `kie-dmn-core` dependency in the `pom.xml` file:

[source,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-dmn-core</artifactId>
  <scope>provided</scope>
</dependency>
----

To build a DMN project with DMN model compilation enabled, navigate to your Maven project directory in a command terminal and run the following command:

[source]
----
mvn clean install -DgenerateDMNModel=YES
----

Alternatively, you can define the DMN model property directly in the `pom.xml` file:

[source,xml]
----
<project>
  ...
  <properties>
    <generateDMNModel>YES</generateDMNModel>
  </properties>
  ...
</project>
----

For more information about configuring executable models for your Maven or Java project, see {URL_PACKAGING_DEPLOYING_PROJECT}#project-build-deploy-maven-proc_packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].

ifdef::PAM[]
=== Case Management Model Notation (CMMN) support
CMMN 1.1 is now supported. You can use {CENTRAL} to import, view, and modify the content of `.cmmn` files. When authoring a project, you can import your case management model and then select it from the asset list to view or modify in the standard XML editor.

The following CMMN 1.1 constructs are currently available:

* Tasks (human task, process task, decision task, case task)
* Discretionary tasks (same as above)
* Stages
* Milestones
* Case file items
* Sentries (entry and exit)

Required, repeat, and manual activation tasks are currently not supported. Sentries for individual tasks are limited to entry criteria while entry and exit criteria are supported for stages and milestones. Decision task maps by default to DMN decision. Event listeners are not supported.
endif::[]

=== Predictive Modeling Markup Language (PMML) models
{PRODUCT} {PRODUCT_VERSION} supports the following PMML 4.2.1 model types:

* Regression models
* Scorecard models
* Tree models
* Mining models (with sub-types `modelChain`, `selectAll`, and `selectFirst`)

More PMML model types and Mining model sub-types will be supported as they become available.

For more information about PMML support in {PRODUCT} {PRODUCT_VERSION}, see {URL_PMML_MODELS}[_{PMML_MODELS}_].

=== Spring Boot support
You can use the following Spring Boot starters to bootstrap your projects with Spring Boot:

ifdef::PAM[]
* {CENTRAL} process management - embedded engine
** `groupId: org.kie`
** `artifactId: jbpm-spring-boot-starter-basic`
endif::[]
* Fully featured {KIE_SERVER}
** `groupId: org.kie`
** `artifactId: kie-server-spring-boot-starter`

* Rules and decisions {KIE_SERVER}
** `groupId: org.kie`
** `artifactId: kie-server-spring-boot-starter-drools`
ifdef::PAM[]
* Rules and decisions, processes and cases {KIE_SERVER}
** `groupId: org.kie`
** `artifactId: kie-server-spring-boot-starter-jbpm`
endif::[]
* Planning {KIE_SERVER}
** `groupId: org.kie`
** `artifactId: kie-server-spring-boot-starter-optaplanner`

ifdef::PAM[]
== Smart Router

=== Support for HTTPS
Support for HTTPS is now available with Smart Router.
endif::[]

== {PLANNER}

=== Multithreaded incremental solving
{PLANNER} now supports multithreaded incremental solving. The solving process can now run on several CPU cores in parallel while remaining fully reproducible through repeated runs. Depending on the task, using four cores can increase the speed by a factor of three or more compared to solving on a single core. You do not need to modify the task source to use multithreaded incremental solving.

=== Employee Rostering
The Employee Rostering starter application has been significantly improved:

* You can now create a new tenant so you can use the application with your own real-world data and enter this data starting from a blank slate.
* The user interface was improved, including notifications and performance.
* You can now select the week to view instead of scrolling through long time periods.
