[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

== Reference implementations

Three reference implementations are available that you can use as starter applications. They are provided in the *{PRODUCT} {PRODUCT_VERSION_LONG} Reference Implementations* download, available on the {PRODUCT} Software Downloads page in the Red Hat Customer Portal.

.Employee Rostering reference implementation
The employee rostering reference implementation enables you to create an application that assigns employees to shifts on various positions in an organization. For example, you can use the application to distribute shifts in a hospital between nurses, guard duty shifts across a number of locations, or shifts on an assembly line between workers.

.High available event-driven decisioning reference implementation
A reference implementation for high available event-driven decisioning on {OPENSHIFT} is available. You can customize this reference implementation to deploy {PRODUCT_DROOLS} engine code that requires stateful processing, including rules developed with complex event processing, in an OpenShift environment. Doing this enables the {DECISION_ENGINE} to process complex event series with high availability.

.Vehicle route planning reference implementation
The vehicle route planning reference implementation enables you to create an application that solves a vehicle route planning problem with real-world maps, roads, and vehicles delivering goods to locations, each with a specific capacity. For more information, see the read me file in the vehicle routing ZIP file, included in the reference implementation download.

== {CENTRAL}

=== Decision Model and Notation (DMN) designer improvements

The Decision Model and Notation (DMN) designer in {CENTRAL} includes the following notable enhancements:

* New *Documentation* tab that you can use to generate a report of your DMN model. You can print or download the report as an HTML file for offline use.
* PMML support in DMN included models. You can now use the *Included Models* tab in the DMN designer to include Predictive Model Markup Language (PMML) models from your project in a specified DMN file. When you include a PMML model within a DMN file, you can invoke that PMML model as a boxed function expression for a DMN decision node or business knowledge model node.
* Support for JPMML execution of PMML models included in DMN models. For PMML models that you include in DMN models, you can use either the `kie-pmml` compiler or the full PMML specification implementation with the Java Evaluator API for PMML (JPMML) for PMML execution.
+
IMPORTANT: Red Hat supports integration with the Java Evaluator API for PMML (JPMML) for PMML execution in {PRODUCT}. However, Red Hat does not support the JPMML libraries directly. If you include JPMML libraries in your {PRODUCT} distribution, see the https://openscoring.io/[Openscoring.io] licensing terms for JPMML.

For more information about DMN support in {PRODUCT} {PRODUCT_VERSION}, see the following resources:

* {URL_DMN_MODELS}[_{DMN_MODELS}_]
* {URL_GETTING_STARTED_DECISION_SERVICE}[_{GETTING_STARTED_DECISION_SERVICE}_]

=== Ability to convert a guided decision table to a spreadsheet decision table

You can convert a guided decision table in {CENTRAL} to an XLS spreadsheet decision table file for offline reference and file sharing. The guided decision table must be an extended entry guided decision table in order to be converted. The conversion tool does not support limited entry guided decision tables. To convert a guided decision table, navigate to the guided decision table asset that you want to convert and in the upper-right toolbar of the guided decision tables designer, click *Convert to XLS*.

WARNING: Guided decision tables and spreadsheet decision tables are different decision table formats that support different features. Any supported features that differ between the two decision table formats are modified or lost when you convert one decision table format to the other.

ifdef::PAM[]
=== Bulk reassignment supported for tasks in {CENTRAL}

In the *Task Inbox* and *Tasks* pages in {CENTRAL}, you can now perform bulk reassignment over multiple tasks in a single operation. To reassign tasks in bulk, select two or more tasks, click the *Bulk Actions* menu in the upper-right corner of the window, and select *Bulk Reassign*.

In the *Tasks reassignment* window, enter the user identifier of the user to reassign the tasks to, and click *Delegate*. For each task selected, a notification is displayed showing the reassignment result.

=== Bulk actions supported for tasks in {CENTRAL}

In the  *Task Inbox* and *Tasks* pages in {CENTRAL}, you can now perform bulk actions over multiple tasks in a single operation. To update tasks in bulk, select two or more tasks, click the *Bulk Actions* menu in the upper-right corner of the window, and select one of the following bulk actions:

* *Bulk Claim*
* *Bulk Release*
* *Bulk Resume*
* *Bulk Suspend*

If a specified bulk action is not permitted based on the task status, a notification is displayed and the operation is not executed on that task.

=== Process designer
The following list provides a summary of process designer updates:

* Support for feature parity when you migrate legacy business processes to the new process designer
* Support for designer parser round-trip for unsupported elements, such as importing models exported by ARIS BPM diagrams, even if they contain elements that are not supported by {PRODUCT}
* A new text annotation BPMN2 element that enables you to retain existing text annotations when you port external processes to the new process designer
* Support for ISO8601 expressions for user task notifications

endif::PAM[]

=== Import and export Dashbuilder data in {CENTRAL}

You can now import and export Dashbuilder data as ZIP files. To import and export Dashbuilder data, select the *Admin* icon in the upper-right corner of the {CENTRAL} window and select *Dashbuilder Data Transfer*.

=== Test scenarios

The test scenarios designer in {CENTRAL} is now available with the new features supported in {PRODUCT} {PRODUCT_VERSION}.

*  View coverage reports for rule-based models. The test scenarios designer displays the test coverage statistics in the *Coverage Report* panel on the right side of the test scenarios designer.

* Download coverage reports for rule-based and DMN-based models. You can now download the test scenario coverage reports in CSV format.

* You can run test scenarios with stateless KIE sessions. To configure a stateless KIE session, expand the *Settings* panel of the test scenario and select or clear the *Stateless Session* check box to indicate whether or not the KIE session is stateless or not.

NOTE: The test scenario `scesim` file format is not public. You can only edit the `scesim` file using the test scenario editor.


== {KIE_SERVER}

=== Ability to configure the queue size for the {PLANNING_ENGINE} in a {KIE_SERVER}

You can now configure the queue size for the {PLANNING_ENGINE}
in a {KIE_SERVER}. The queue size determines how many solver requests can be enqueued to wait for processing while the engine is working on other requests. If the queue is full, new requests are rejected. The default queue size is equal to the number of active CPU cores. To change the queue size, set the `org.optaplanner.server.ext.thread.pool.queue.size` system property for the {KIE_SERVER}.

== {OPENSHIFT}

=== Automatic minor and patch version updates in operator deployments on {OPENSHIFT}

When you deploy {PRODUCT} on {OPENSHIFT} using the Business Automation operator, you can now enable automatic minor and patch version updates.

If you enable automatic patch updates, when a new version becomes available all components of your deployment are updated automatically. Normally, there is no interruption in service.

=== Support for configuring aliases in {OPENSHIFT}

You can now configure container aliases for services running on immutable {KIE_SERVERS} on {OPENSHIFT}. If you use Smart Router, it automatically routes requests to {KIE_SERVERS} based on the alias name specified in the requests.

//== {PLANNER}
