[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

== {CENTRAL}

=== Support for multiple diagrams in DMN models

For complex DMN models, you can now use the DMN designer in {CENTRAL} to design multiple DMN decision requirements diagrams (DRDs) that represent parts of the overall decision requirements graph (DRG) for a DMN decision model. This improvement enables you to better organize DMN decision models with many decision requirements by dividing the model into smaller nested DRDs.

For more information about creating DMN models with multiple diagrams, see {URL_DEVELOPING_DECISION_SERVICES}#assembly-dmn-models[_{DMN_MODELS}_].

ifdef::PAM[]

=== Dashbuilder runtime
Dashbuilder runtime is a new add-on standalone web application, distributed as a `WAR` to run the dashboards on {EAP}. If you have access to dashbuilder runtime, you can explore the dashboards created in {CENTRAL}. The following list provides a summary of dashbuilder runtime updates:

* After creating dashboards using datasets and pages, you can export these dashboards from {CENTRAL} using *custom export*.
* You can import, access, and run the dashboards that are exported from {CENTRAL} in dashbuilder runtime.
* Dashbuilder runtime accesses the {KIE_SERVER} REST API to run the queries from imported {KIE_SERVER} datasets.
* Dashbuilder runtime provides embedded capabilities that allow you to set a specific dashboard from an instance of dashbuilder runtime on your web applications.
* In Dashbuilder runtime, you can import multiple dashboards in a single dashbuilder runtime instance.
* You can create and add external components that can be a part of the dashboard page.

=== Enhanced search capabilities
{PRODUCT} {ENTERPRISE_VERSION} provides enhanced search capabilities, including flexible search criteria for tasks, process instances, and cases. For more information, see {URL_DEVELOPING_PROCESS_SERVICES}#assembly-designing-and-building-cases[_{DESIGNING_CASES}_].

=== Ability to configure emails in the task notification
You can now directly add email addresses to send task notification emails. For more information, see {URL_DEVELOPING_PROCESS_SERVICES}#assembly-interacting-with-processes[_{DESIGNING_BUSINESS_PROCESSES}_].

== Entando AppBuilder
Entando AppBuilder is now officially removed from the {PRODUCT} 7.9. {PRODUCT} no longer includes entitlements for Entando AppBuilder. The feature references and documentation is not be available from the 7.9 release.

endif::PAM[]

ifdef::PAM[]

== Process Designer

=== Process designer updates
The following list provides a summary of process designer updates:

* Ability to add data objects in a process diagram
* Ability to add Kafka work item in a process diagram to send events to a Kafka topic
* Ability to double-click any diagram node to edit its name using the new inline text editor
* Ability to view highlighted syntax when writing a script in Java, JavaScript, and MVEL
* Ability to use multiple connections for a task or an event using `jbpm.enable.multi.con` system property

For more information, see {URL_DEVELOPING_PROCESS_SERVICES}#assembly-designing-business-processes[_{DESIGNING_BUSINESS_PROCESSES}_].

=== Support for link intermediate events

You can now use link events in the process designer to connect different parts of your process. The new link events include an intermediate throwing and catching link event. For more information, see {URL_DEVELOPING_PROCESS_SERVICES}#assembly-designing-business-processes[_{DESIGNING_BUSINESS_PROCESSES}_].

endif::PAM[]

== {DECISION_ENGINE_CAP}

=== Descope traits in {DECISION_ENGINE}

The traits functionality and its specific implementation code is moved to an individual module named `drools-traits`. To use traits, you can import the `drools-traits` module to Maven. The existing implementation is not supported in the executable rule model.

=== New `drools-metric` module for {DECISION_ENGINE} performance analysis

A new module named `drools-metric` is added, which can assist in the performance analysis of the {DECISION_ENGINE}.

For more information, see {URL_DEVELOPING_DECISION_SERVICES}#assembly-drl-rules[_{DRL_RULES}_].

ifdef::PAM[]

== {PROCESS_ENGINE_CAP}

=== Support for process fluent API
You can now create a business process using the process fluent API. Following is a basic example of creating a business process using fluent API:

[source, java]
----
ProcessBuilderFactory factory = ProcessBuilderFactories.get();
Process process = factory
    // start process definition
    .processBuilder(processId)
    // package and name
    .packageName(packageName)
    .name(processName)
    .setMetadata("pepe", true)
    // start node
    .startNode(1).name("Start").done()
    // script node in Java language that prints "action"
    .actionNode(2).name("Action")
    .action(Dialect.JAVA,
            "System.out.println(\"Action\");").done()
    // end node
    .endNode(3).name("End").done()
    // connections
    .connection(1, 2)
    .connection(2, 3)
    .build();
----

For more information about process fluent API, see {URL_DEPLOYING_AND_MANAGING_SERVICES}#assembly-kie-apis[_{KIE_APIS}_].

endif::[]

== {PLANNER}

=== Using {PLANNER} with Spring Boot

You can follow the example in {URL_DEVELOPING_SOLVERS}#assembly-business-optimizer-springboot[{PLANNER_WITH_SPRING_BOOT}] to create a school timetable.

=== Employee Rostering rotation pattern redesign

The rotation pattern on the Employee Rostering Rotation window has been redesigned for ease of use. For more information, see {URL_DEVELOPING_SOLVERS}#assembly-optimizer-modifying-ER-template-IDE[_{RUNNING_ROSTER_FOR_PLANNER_IDE}_].

== Spring Boot

ifdef::PAM[]

=== Replicating audit data in a JMS message broker

You can now replicate {KIE_SERVER} audit data to a Java Message Service (JMS) message broker, for example, activeMQ or Artemis, After replicating the data, you can dump the data in an external database schema so that you can improve the performance of your Spring Boot application by deleting the audit data from your application schema.

For more information, see {URL_INTEGRATING}#assembly-springboot-business-apps[_{CREATING_SPRING_BOOT_APPLICATIONS}_].

=== Support for `bytea` column type

You can now create a PostgreSQL schema that uses the `bytea` column type instead of the `oid` column type by setting the value of the `org.kie.persistence.postgresql.useBytea` property to `true`.

For more information, see {URL_INTEGRATING}#assembly-springboot-business-apps[{CREATING_SPRING_BOOT_APPLICATIONS}].

endif::[]

=== Self-contained {PRODUCT} Spring Boot JAR file

You can create a self-contained {PRODUCT} Spring Boot JAR file that contains multiple versions of the same KJAR file.

For more information, see {URL_INTEGRATING}#assembly-springboot-business-apps[_{CREATING_SPRING_BOOT_APPLICATIONS}_].

== {OPENSHIFT}

=== Support for {OPENSHIFT} version 4.6

{PRODUCT} now supports {OPENSHIFT} version 4.6. In order to support this version, necessary changes in the operator bundle format are made.
{OPENSHIFT} version 4.6 provides an extended update support. For more information, see https://access.redhat.com/support/policy/updates/openshift-eus?extIdCarryOver=true&sc_cid=701f2000001OH7iAAG[Red Hat OpenShift Extended Update Support (EUS) Overview].

IMPORTANT: {PRODUCT} {PRODUCT_VERSION} is supported only on {OPENSHIFT} version 3.11 and {OPENSHIFT} version 4.6 EUS. Due to the internal changes of the operator and API version, {OPENSHIFT} version 4.5 is not supported and this makes an exception to the general support policy for the Red Hat Middleware products.
For more information, see https://access.redhat.com/articles/5115291[Support of Red Hat Middleware products and components on Red Hat OpenShift].

=== Support for LDAP failover

When using LDAP authentication, {PRODUCT} on {OPENSHIFT} now supports failover to a different LDAP server if a server becomes unavailable.

For more information, see {URL_DEPLOYING_ON_OPENSHIFT}#operator-deploy-security-proc_openshift-operator[_{DEPLOYING_OPENSHIFT_OPERATOR}_] and {URL_DEPLOYING_ON_OPENSHIFT}#template-deploy-ldap-openshift-templates-authoring-proc[_{DEPLOYING_OPENSHIFT_TEMPLATES}_].

=== Integration with new versions of products

{PRODUCT} on {OPENSHIFT} now supports integration with the following new product versions:

* {AMQ} {AMQ_VERSION}
* {AMQ_BROKER_LONG} {AMQ_BROKER_VERSION}
* {RH-SSO} 7.4.1
* {DATAGRID} {DATAGRID_VERSION}

ifdef::PAM[]

=== Support for a customized Smart Router image

{PRODUCT} on {OPENSHIFT} now supports customized Smart Router images. You can extend Smart Router to provide routing specific to the needs of your environment.

For more information, see {URL_DEPLOYING_ON_OPENSHIFT}#customimage-smartrouter-proc_openshift-operator[_{DEPLOYING_OPENSHIFT_OPERATOR}_].

=== Logging level configuration for Smart Router

You can now configure the logging level for Smart Router when deploying {PRODUCT} on {OPENSHIFT}.

For more information, see {URL_DEPLOYING_ON_OPENSHIFT}#operator-deploy-smartrouter-proc_openshift-operator[_{DEPLOYING_OPENSHIFT_OPERATOR}_].

endif::PAM[]

=== Support for deploying an unmanaged {KIE_SERVER} on {OPENSHIFT} using the operator

You can now deploy {PRODUCT} on {OPENSHIFT} using the operator with a {KIE_SERVER} that is not managed by {CENTRAL} monitoring.

For more information, see {URL_DEPLOYING_ON_OPENSHIFT}#operator-deploy-central-proc_openshift-operator[_{DEPLOYING_OPENSHIFT_OPERATOR}_].
