[id='rn-whats-new-con']
= New features

This section highlights new features in {PRODUCT} {PRODUCT_VERSION}.

== Installation and upgrades

=== Installer
You can install {PRODUCT} on Red Hat JBoss Web Server 5.0.1 or higher.

You can install {PRODUCT} on {EAP} {EAP_VERSION}.

== Business application generator
You can use the http://start.jbpm.org website to generate a {PRODUCT} business application based on Spring Boot starters. After you create and configure your business application, you can deploy it to an existing service or to the cloud, through OpenShift.

== {CENTRAL}
=== Experimental properties administration page
{CENTRAL} now includes an experimental features administration page which is disabled and hidden by default. When enabled, this page displays a list of experimental features that are in technology preview. You can enable or disable individual features from this page. To enable the experimental features administration page , set the value of the `appformer.experimental.features` property to `true`.

== Process engine
=== ElasticSearch connector for runtime events
This connector enables you to easily integrate with ElasticSearch to push data from the process engine and take advantage of the searching capabilities of the ElasticSearch server.

ifdef::PAM[]
== Process designer


endif::[]

== {KIE_SERVER}

=== Swagger interface for {CONTROLLER} REST API

{PRODUCT} {PRODUCT_VERSION} provides a Swagger web interface for the {CONTROLLER} REST API. You can use this Swagger interface instead of a standalone REST client or curl utility to interact with your {KIE_SERVER} templates (configurations), {KIE_SERVER} instances (remote servers), and associated KIE containers (deployment units) in {PRODUCT}.

To access the Swagger interface for the {CONTROLLER} REST API, you can either start {CENTRAL}, which contains a built-in {CONTROLLER}, or run the {HEADLESS_CONTROLLER} application and navigate to `\http://SERVER:PORT/CONTROLLER/docs` in a web browser.

Example Swagger URLs:

* `\http://localhost:8080/{URL_COMPONENT_CENTRAL}/docs` (for a {CONTROLLER} in {CENTRAL})
* `\http://localhost:8080/my-controller/docs` (for a {HEADLESS_CONTROLLER})

For more information about the {CONTROLLER} REST API, see {URL_KIE_APIS}[_{KIE_APIS}_].

=== Decision Model and Notation (DMN) models
{PRODUCT} {PRODUCT_VERSION} provides both design and runtime support for DMN 1.2 models at conformance level 3, and includes enhancements and fixes to FEEL and DMN model components to optimize the experience of implementing DMN decision services with {PRODUCT}. You can design your DMN models directly in {CENTRAL} or import existing DMN models into your {PRODUCT} projects for deployment and execution.

For more information about DMN support in {PRODUCT} {PRODUCT_VERSION}, see {URL_DMN_MODELS}[_{DMN_MODELS}_].

=== Executable models in Decision Model and Notation (DMN) projects
In {PRODUCT} {PRODUCT_VERSION}, you can now use the `kie-maven-plugin` build component to generate DMN executable model classes and compile them in a {PRODUCT} project (KJAR file). DMN executable model classes are similar to executable rule models used for rule assets. This support enables DMN decision table logic in DMN projects to be evaluated more efficiently.

To enable executable models in DMN projects, add the required `kie-dmn-core` dependency in the `pom.xml` file:

[source,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-dmn-core</artifactId>
  <scope>provided</scope>
</dependency>
----

To build a DMN project with DMN model compilation enabled, navigate to your Maven project directory in a command terminal and run the following command:

[source]
----
mvn clean install -DgenerateDMNModel=YES
----

Alternatively, you can define the DMN model property directly in the `pom.xml` file:

[source,xml]
----
<project>
  ...
  <properties>
    <generateDMNModel>YES</generateDMNModel>
  </properties>
  ...
</project>
----

For more information about configuring executable models for your Maven or Java project, see {URL_PACKAGING_DEPLOYING_PROJECT}#project-build-deploy-maven-proc_packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].



== Decision engine

=== Rule units

{PRODUCT} {PRODUCT_VERSION} now supports rule units that you can use to partition a rule set into smaller units, bind different data sources to those units, and then execute the individual unit. A rule unit consists of data sources, global variables, and rules.

You can define a rule unit by implementing the `RuleUnit` interface as shown in the following example:

.Example rule unit class
[source,java]
----
package org.mypackage.myunit;

public static class AdultUnit implements RuleUnit {
    private int adultAge;
    private DataSource<Person> persons;

    public AdultUnit( ) { }

    public AdultUnit( DataSource<Person> persons, int age ) {
        this.persons = persons;
        this.age = age;
    }

    // A DataSource of Persons in this rule unit
    public DataSource<Person> getPersons() {
        return persons;
    }

    // A global variable valid in this rule unit
    public int getAdultAge() {
        return adultAge;
    }

    // --- life cycle methods

    @Override
    public void onStart() {
        System.out.println("AdultUnit started.");
    }

    @Override
    public void onEnd() {
        System.out.println("AdultUnit ended.");
    }
}
----

For more information about rule units, see the http://docs.jboss.org/drools/release/latestFinal/drools-docs/html_single/#rule-units-con[Drools Documentation].

=== Multithreaded evaluation in the decision engine

In {PRODUCT} {PRODUCT_VERSION}, the decision engine can now evaluate more business rules in parallel by dividing the RETE and PHREAK pattern-matching algorithms in independent partitions and evaluating them in parallel.

Multithreaded evaluation is disabled by default in {PRODUCT}. To enable multithreaded evaluation for a parallel KIE base, use one of the following options:

* Enable multithreaded evaluation with `KieBaseConfiguration`:
+
[source]
----
KieServices ks = KieServices.Factory.get();
KieBaseConfiguration kieBaseConf = ks.newKieBaseConfiguration();
kieBaseConf.setOption(MultithreadEvaluationOption.YES);
KieBase kieBase = kieContainer.newKieBase(kieBaseConf);
----

* Enable the multithreaded evaluation system property:
+
[source]
----
drools.multithreadEvaluation = true
----

[WARNING]
====
Rules using queries, salience, or agenda groups are currently not supported by the parallel decision engine. If these rule elements are present in the KIE base, the compiler emits a warning and automatically switches back to single-threaded evaluation. However, in some cases, the decision engine might not detect the unsupported rule elements and rules might be evaluated incorrectly. For example, the decision engine might not detect when rules rely on implicit salience given by rule ordering inside the DRL file, resulting in incorrect evaluation due to the unsupported salience attribute.
====

=== Ability to declaratively set calendars in a KIE session

In {PRODUCT} {PRODUCT_VERSION}, you can now declaratively set one or more calendars on a KIE session through the `kmodule.xml` configuration file, as shown in the following example:

[source,xml]
----
<ksession name="KSession1">
  <calendars>
    <calendar name="monday" type="org.domain.Monday"/>
  </calendars>
</ksession>
----

The type is the name of the class that implements the `org.kie.api.time.Calendar` interface.

ifdef::PAM[]
== Smart Router

endif::[]

== {PLANNER}
