
= Business Exceptions


Business Exceptions are exceptions that are designed and managed in the BPMN2 specification of a business process.
In other words, Business Exceptions are exceptions which happen at the process  or workflow level, and are not related to the technical components.

Many of the elements in BPMN2 related to Business Exceptions are related to _Compensation_ and __Business Transactions__.
Compensation, in particular, is complexer than many other parts of the BPMN2 specification.

Full support for _compensation_ and _business
      transactions_ is expected with the release of jBPM 6.1 or 6.2.
Once that has been implemented, this section will contain more information about using those BPMN2 features with  jBPM.

== Business Exceptions elements in BPMN2


The following attempts to briefly describe Compensation and Business Transaction related  elements in BPMN2.
For more complete information about these elements and their uses, see  the BPMN2 specification, Bruce Silver's book [path]_BPMN Method and Style_
 or any of  the other available books about the use of BPMN2.

.BPMN2 Exception Handling Elements
[cols="1,1", frame="all", options="header"]
|===
| BPMN2 Element types
| Description

|Errors
|

Error Events can be used to signal when a process has encountered an unexpected  situation: signalling an error is often called _throwing_ an error.

Boundary Error Events in a different part of the process can then be used to  _catch_ the error and initiate a sequence of activities to handle the  exception.

Errors themselves can be extended with extra information that is passed from the  throwing to catching event.
This is done with the use of an Item Definition.

|Compensation
|

Exception handling activities _associated_ with the normal  activities in a Business Transaction are triggered by __Compensation 
                  Events__.

There are 3 types of compensation events: Intermediate (a.k.a.
Boundary) (catch) events, Start (catch) events, and Intermediate or End (throw) events.

Compensation Boundary (catch) events may only be attached to activities (e.g.
tasks) that could  cause an exception.
These Boundary events are then _associated_ (not linked!) with a Task that will be executed if the Boundary event catches a (thrown) Compensation signal.

Start (catch) events are used when defining an __Compensation Event SubProcess__,  which requires them in order to be able to catch a (thrown) Compensation signal. 

Compensation Intermediate and End events are used in order to throw Compensation Events.
These events often follow decision nodes that determine whether the workflow executed up to that point has  succeeded.
If not, the path including the Intermediate or End Event is chosen in order to trigger Compensatoin for the activities that did not succeed.
|===


BPMN2 contains a number of constructs to model exceptions in business processes.
There are several advantages to doing exception handling at the business process level (as opposed to  handling it with code): 

* _Transparency_
+
** Being able to quickly see what happens in exceptional situations means that  the results and performance of a process is more easily monitored and measured.
** It also increases how easily a process can be implemented as well as how  maintainable a process definition is.
* _Business Logic Isolation_
+
** Again, the idea behind using a business process is to isolate the business logic  from the technical code. This simplifies the complexity of the system and increases how  quickly you can create new business processes and change existing ones.
** Implementing exception handling at a technical level often takes more time because it's often complexer and specific to a system.


== Designing a workflow with Business Exceptions


Where are business exceptions likely to occur? There is academic research on this, but some  possible examples are: 

* When an interaction with an external party or 3rd party system does not go as planned
* When you can not fully check the the input data in your process (like a client's address information, 
  for example)
* In general, if there are parts of your process that are particularly dependent on one of the following, 
  a business exception will be a good idea: 
** Company policy or policy governing certain (in-house) procedures
** Laws governing the business process (such as age requirements, for example)
