
= Overview

Before moving on to an example, this section explains what custom work items and custom work item handlers are.

[[_sec.workitemdefinition.overview]]
== Work Item Definitions

In short, we use the term _custom work item_ when we're describing a node  in your process that represents a domain-specific task and as such, contains extra properties and  is handled by a `WorkItemHandler` implementation.

Because it's a domain-specific __task__, that means that a _custom 
work item_ is equivalent to a `<task>` or ``<task>``-type  node in BPMN2.
However, a _``__WorkItem__``_ is also Java class instance  that's used when a `WorkItemHandler` instance is called to complete the task or work  item.

Depending on the BPMN2 editor you're using, you can create a custom work item definition in  one of two ways:  

* If you're using __Designer__, then this means creating a MVEL based  definition and adding the definition in Designer itself. A description of this can be found in the <<_sec.designer.workitems>>  section in the <<_ch.designer>> chapter. Once this is done, a new service node will appear on the BPMN 2.0 palette.
* If you're using the _Eclipse BPMN 2.0 modeler plugin_ (which can  be found http://eclipse.org/bpmn2-modeler/[here]), then you'll can modify  the BPMN2 `<task>` or ``<task>``-type element to work with  `WorkItemHandler` implementations. See the <<_sec.eclipse.task_nodes>> section in the <<_ch.eclipse_bpmn_plugin>> chapter.


[[_sec.workitemhandler.overview]]
== Work Item Handlers

A _work item handler_ is a Java class used to execute (or abort) work  items.
That also means that the class implements the `org.kie.runtime.instance.WorkItemHandler`  interface.
While jBPM provides some custom `WorkItemHandler` instances (listed below),  a Java developer with a minimal knowledge of jBPM can easily create a new work item handler class  with its own custom business logic.

Among others, jBPM offers the following `WorkItemHandler` implementations: 

* In the [path]_jbpm-bpmn2_ module, `org.jbpm.bpmn2.handler`  package:
+
** ReceiveTaskHandler (for use with BPMN element ``<receiveTask>``)
** SendTaskHandler (for use with BPMN element ``<sendTask>``)
** ServiceTaskHandler (for use with BPMN element ``<serviceTask>``)
* In the [path]_jbpm-workitems_ module, in various packages under the `org.jbpm.process.workitem` package:
+
** ArchiveWorkItemHandler
There are a many more `WorkItemHandler` implementations present in the [path]_jbpm-workitems_ module.
If you're looking for specific integration logic with Twitter, for example, we recommend you take a look at the classes made available there.

In general, a ``WorkItemHandler``'s `$$.$$executeWorkItem(...)` and ``$$.$$abortWorkItem(...)`` methods will do the following: 

. Extract information about the task being executed (or aborted) from the `WorkItem` instance
. Execute the necessary business logic. This might be mean interacting with a web service, database, or other technical component.
. Inform the process engine that the work item has been completed (or aborted) by calling one of the following two methods on the `WorkItemManager` instance passed  to the method: 


[source,java]
----
WorkItemManager.completeWorkItem(long workItemId, Map<String, Object> results)
WorkItemManager.abortWorkItem(long workItemId)
----

In order to make sure that your custom work item handler is used for a particular process instance, it's necessary to register the work item handler before starting the process.
This makes the engine aware of your `WorkItemHandler` so that the engine can use it for the proper node.
For example:

[source,java]
----
ksession.getWorkItemManager().registerWorkItemHandler("Notification",
    new NotificationWorkItemHandler());
----

The `ksession` variable above is a `StatefulKnowledgeSession` (and also a ``KieSession``) instance.
The example code above comes from the example that we will go through in the next session.

*Work item handler life cycle management*

Work item handler is registered on kie session and then can be used whenever process engine encounters a node that should be handled by that handler.
Depending on the implementation of the handler (e.g.
some handler might keep state or depend on some resources such as data base connection) there might be a need to maintain life cycle of the handler.
To ease the way of doing that jBPM comes with two additional interfaces that handler might implement:

* _org.kie.internal.runtime.Closeable_ - allows auto close of the handler whenever owner (work item handler manager) of it is closed or disposed. This is useful in case a handler can be quickly and frequently recreated so the engine will have it for the execution and when disposed it will dispose as well all handlers of Closeable type.
* _org.kie.internal.runtime.Cacheable_ - allows handlers to be cached and resused to avoid recreation of the objects. There might be several reasons of doing so - expensive bootstrap of the handler, dependency to external resources - socket connections, db connections, web service client. While this brings powerful feature to the work item handler management it does put additional requirement on the implementation - needs to deal with exceptions internally and recover from any failures. In case recovery cannot be performed it needs to remove itself from the cache.


Closeable interface is handled for all use cases, while Cacheable is available only when RuntimeManager is used.
RuntimeManager provides caching capabilities via its CacheManager (available via InternalRuntimeManager in case self removal is required).

[TIP]
====
You can use different work item handlers for the same process depending on the system on which it runs: by registering different work item handlers on different systems, you can customize how a custom work item is processed on a particular system.
You can also substitute mock ``WorkItemHandler`` instances when testing.
====
