= Using {xpaasproduct-shortname} Image Streams and Application Templates
The Red Hat xPaaS middleware images were
https://access.redhat.com/documentation/en/openshift-enterprise/version-3.2/installation-and-configuration/#loading-the-default-image-streams-and-templates[automatically created during the installation]
of OpenShift along with the other default image streams and templates.

= Deployment Considerations for {xpaasproduct-shortname}

== Creating the Service Account
{xpaasproduct-shortname} requires a service account for deployments. For multiple node deployments, the service account must have the *view* role enabled so that it can manage the various pods in the cluster. In addition, you will need to configure SSL to enable connections to Intelligent Process Server from outside of the OpenShift instance.

. Create the service account:
+
[subs="verbatim,macros"]
----
$ echo '{"kind": "ServiceAccount", "apiVersion": "v1", "metadata": {"name": "<pass:quotes[_service-account-name_]>"}}' | oc create -f -
----
+
OpenShift 3.2 users can use the following command to create the service account:
+
[subs="verbatim,macros"]
----
$ oc create serviceaccount <pass:quotes[_service-account-name_]>
----
. Add the *view* role to the service account:
+
[subs="verbatim,macros"]
----
$ oc policy add-role-to-user view system:serviceaccount:<pass:quotes[_project-name_]>:<pass:quotes[_service-account-name_]>
----

== Configuring Keystores 

{xpaasproduct-shortname} requires two keystores:

* An SSL keystore to provide private and public keys for https traffic encryption +
* A JGroups keystore to provide private and public keys for network traffic encryption between nodes in the cluster

These keystores are expected by {xpaasproduct-shortname}, even if the application uses only http on a single-node OpenShift instance. Note that self-signed certificates do not provide secure communication and are intended for internal testing purposes.

[WARNING]
For production environments Red Hat recommends that you use your own SSL certificate purchased from a verified Certificate Authority (CA) for SSL-encrypted connections (HTTPS).

See https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.1/html-single/Security_Guide/index.html#Generate_a_SSL_Encryption_Key_and_Certificate[Generate a SSL Encryption Key and Certificate] for more information on how to create a keystore with self-signed or purchased SSL certificates.

== Generating the Secret

OpenShift uses objects called `Secrets` to hold sensitive information, such as passwords or keystores. See the https://access.redhat.com/documentation/en/openshift-enterprise/version-3.2/developer-guide/#dev-guide-secrets[Secrets chapter] in the OpenShift documentation for more information.

{xpaasproduct-shortname} requires a secret that holds the two keystores described earlier. This provides the necessary authorization to applications in the project.

Use the Java and JGroups keystore files to create a secret for the project:
[subs="verbatim,macros"]
----
$ oc create secret generic <pass:quotes[_ips-secret-name_]> --from-file=<pass:quotes[_jgroups.jceks_]> --from-file=<pass:quotes[_keystore.jks_]>
----

After the secret has been generated, it can be associated with a service account.

== Creating the Service Account

The service account allows users to associate certain secrets and roles with applications in a project namespace. This provides the application with the necessary authorization to run with all required privileges.

. Create a service account to be used for the Intelligent Process Server deployment:
+
[subs="verbatim,macros"]
----
$ oc create serviceaccount <pass:quotes[_service-account-name_]>
----
. Add the *view* role to the service account. This enables the service account to view all the resources in the application namespace in OpenShift, which is necessary for managing the cluster.
+
[subs="verbatim,macros"]
----
$ oc policy add-role-to-user view system:serviceaccount:<pass:quotes[_project-name_]>:<pass:quotes[_service-account-name_]>
----
. Add the secret created for the project to the service account:
+
[subs="verbatim,macros"]
----
$ oc secret add sa/<pass:quotes[_service-account-name_]> secret/<pass:quotes[_ips-secret-name_]>
----

== Configuring the Project Remote Repository

The project must be configured to use a remote repository so that Business Central can push changes and OpenShift can pull the repository to build the application.
In the application repository files:

. The *pom.xml* must be configured to use a remote repository so that OpenShift can access it.
+
[subs="verbatim,macros"]	
----
...
<distributionManagement>
  <repository>
    <id>deployment</id>
    <name>OpenShift Maven repo</name>
    <url>pass:quotes[_http://maven.example/deployment/filepath/_]</url>
  </repository>

  <snapshotRepository>
    <id>deployment</id>
    <name>OpenShift Maven repo</name>
    <url>pass:quotes[_http://maven.example/snapshots/filepath/_]</url>
  </snapshotRepository>
</distributionManagement>
...
----
+
For more information, see https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.3/html/Administration_And_Configuration_Guide/Configuring_deployment_to_a_remote_Nexus_repository.html[the Red Hat JBoss BPM Suite Administration and Configuration Guide].
. The *configuration/settings.xml* file must have the remote repository defined so that OpenShift can download the application artifacts.
+
[subs="verbatim,macros"]
----
...
<profiles>
  <profile>
    <id>openshift-mirror-repositories</id>
    <repositories>
      <repository>
        <id>openshift-mirror</id>
        <url>pass:quotes[_http://maven.example/public/filepath/_]</url>
      </repository>
    </repositories>

    <pluginRepositories>
      <pluginRepository>
        <id>openshift-mirror</id>
        <url>pass:quotes[_http://maven.example/public/filepath/_]</url>
      </pluginRepository>
    </pluginRepositories>
  </profile>
</profiles>
...
----
+
For more information, see https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.3/html/Installation_Guide/Using_the_JBoss_Integration_Maven_Repository_Local_Access.html[the Red Hat JBoss BPM Suite Installation Guide].
. The hidden *.s2i/environment* file defines the KIE container deployment, including which KIE jars to use and the location from which to retrieve them. When OpenShift deploys the built image, the pod name is derived from the deployment alias defined in this file:
+
[subs="verbatim,macros"]
----
KIE_CONTAINER_DEPLOYMENT=<alias>=<group_id>:<artifact_id>:<version>
----
+
For example:
+
----
KIE_CONTAINER_DEPLOYMENT=ApplicationTest=com.example.openshift:example_workflow:1.0
----

[[ds-updating-processes]]
= Updating Processes

Each image is built from a snapshot of a specific Maven repository. When a new process is added, or an existing process modified, a new image must be created and deployed for the modifications to take effect.

*Updating the Application* +
The *KIE_CONTAINER_DEVELOPMENT_OVERRIDE* variable can be used to explicitly override the *KIE_CONTAINER_DEPLOYMENT* variable set in the original deployment. +
When an application has been modified and is ready to be deployed, include the updated version details for the *KIE_CONTAINER_DEPLOYMENT_OVERRIDE* variable in the `.s2i/environment` file. This can then be pushed to your repository to be built as an image. +
Alternatively, start a binary build from the local repo: +
[subs="verbatim,macros"]
----
$ oc start-build <pass:quotes[_RulesTest_]> --from-repo=<pass:quotes[_/repository/filepath_]>
----

This sends the contents of the Git repository directly to OpenShift. If https://docs.openshift.com/enterprise/3.2/dev_guide/builds.html#incremental-builds[Incremental Builds] has been configured, the new build pulls the image previously used, extracts the Maven repository for the new pod, and downloads the missing content.

== Recreate Update Strategy

Use the https://docs.openshift.com/enterprise/3.2/dev_guide/deployments.html#recreate-strategy[Recreate Update Strategy] for the Intelligent Process Server deployment. This update strategy automatically scales down the old deployment to 0 and deploys the new version. After the new version is validated, the new deployment is automatically scaled up to the replica size of the old deployment.

The Recreate update strategy supports https://docs.openshift.com/enterprise/3.2/dev_guide/deployments.html#lifecycle-hooks[Lifecycle Hooks] and is set as the default update strategy in the Intelligent Process Server application templates.

[NOTE]
The Intelligent Process Server will be inactive during the Recreate update process, until the new deployment has been validated and scaled. During this period, REST clients may return *503 service unavailable* errors and A-MQ clients may experience *timeouts*.

[IMPORTANT]
The https://docs.openshift.com/enterprise/3.2/dev_guide/deployments.html#rolling-strategy[Rolling Update Strategy] is not supported for {xpaasproduct-shortname}. Although multiple concurrent versions of an application are supported in a deployment, a cluster can only support valid routing to pods of the same version.

[[Multiple-versions]]
= Multiple Concurrent Versions

An application may contain multiple concurrent KIE containers of different versions. Each container has a classloader environment and a unique identifier. The unique identifier is one of either a container ID or a deployment ID, which are synonymous.

Multiple versions are deployed using the *KIE_CONTAINER_DEPLOYMENT* variable, specifying the _<alias>=<group_id>:<artifact_id>:<version>_ for each version of the application, separated by a pipe ( *|* ) in the *.s2i/environment* file.

For example:
----
KIE_CONTAINER_DEPLOYMENT=ApplicationTest=com.example.openshift:example_workflow:1.0|ApplicationTest=com.example.openshift:example_workflow:1.1
----
would create the following:
----
KIE_CONTAINER_DEPLOYMENT=ApplicationTest=com.example.openshift:example_workflow:1.0|ApplicationTest=com.example.openshift:example_workflow:1.1
KIE_CONTAINER_DEPLOYMENT_ORIGINAL:
KIE_CONTAINER_DEPLOYMENT_OVERRIDE: ApplicationTest=com.example.openshift:example_workflow:1.0|ApplicationTest=com.example.openshift:example_workflow:1.1
KIE_CONTAINER_DEPLOYMENT_COUNT: 2
KIE_CONTAINER_ID_0: be690712c7a5808a0696926088ff18b2
KIE_CONTAINER_KJAR_GROUP_ID_0: com.example.openshift
KIE_CONTAINER_KJAR_ARTIFACT_ID_0: example_workflow
KIE_CONTAINER_KJAR_VERSION_0: 1.0
KIE_CONTAINER_ID_1: 72978ef7154f52df289ef01cbdb51c4d
KIE_CONTAINER_KJAR_GROUP_ID_1: com.example.openshift
KIE_CONTAINER_KJAR_ARTIFACT_ID_1: example_workflow
KIE_CONTAINER_KJAR_VERSION_1: 1.0
KIE_CONTAINER_REDIRECT_ENABLED: true
----
or, as represented in XML format:
----
<kie-server-state>
  <containers>
    <container>
      <containerId>be690712c7a5808a0696926088ff18b2</containerId>
      <releaseId>
        <groupId>com.example.openshift</groupId>
        <artifactId>example_workflow</artifactId>
        <version>1.0</version>
      </releaseId>
      <status>STARTED</status>
      <configItems/>
      <messages/>
    </container>
    <container>
      <containerId>72978ef7154f52df289ef01cbdb51c4d</containerId>
      <releaseId>
        <groupId>com.example.openshift</groupId>
        <artifactId>example_workflow</artifactId>
        <version>1.1</version>
      </releaseId>
      <status>STARTED</status>
      <configItems/>
      <messages/>
    </container>
  </containers>
</kie-server-state>
----

[IMPORTANT]
====
To deploy multiple concurrent versions, the *KIE_CONTAINER_REDIRECT_ENABLED* variable must be set to *true*. This variable defaults to *true* and only needs to be explicitly included in the *.s2i/environment* file if setting to *false*.

The *KIE_CONTAINER_REDIRECT_ENABLED* variable enables override of the container ID. When set to *true*, a unique md5 sum hash is generated from the _<alias>=<group_id>:<artifact_id>:<version>_ for each version of the application. It also enables link:#Alias-Redirection[alias redirection] so that client requests using the deployment alias are redirected to the container of the correct version.

If set to *false*, the deployment alias is used as the container ID and multiple concurrent versions are not possible. If multiple versions of an application are specified for *KIE_CONTAINER_DEPLOYMENT*, and *KIE_CONTAINER_REDIRECT_ENABLED* is set to *false*, only the latest version of the application will be deployed and link:#Alias-Redirection[alias redirection] will be disabled.

Changing the *KIE_CONTAINER_REDIRECT_ENABLED* variable in the *.s2i/environment* file of a running application generates a new container ID for the running application, which may make it incompatible with any clients using the old container ID.
====

== Container ID

The container ID is an md5 sum hash generated from the _<alias>=<group_id>:<artifact_id>:<version>_ of the application, and is used for client communication. In the case of multiple versions, each version of the application will have a unique container ID, but share the deployment alias name.


== Adding, Overriding, or Updating Multiple Versions

If an application has already been deployed, use the *KIE_CONTAINER_DEPLOYMENT_OVERRIDE* variable in the *.s2i/environment* file, and specify the _<alias>=<group_id>:<artifact_id>:<version>_ for each version of the application to override the *KIE_CONTAINER_DEPLOYMENT* variable in the json application template. This is useful for preserving older versions of an application that are still in use.

For example, the _ApplicationTest_ application example:
----
KIE_CONTAINER_DEPLOYMENT=ApplicationTest=com.example.openshift:example_workflow:1.0
----

To maintain this version of the application, but to add an updated version, update the *.s2i/environment* file:
----
KIE_CONTAINER_DEPLOYMENT_OVERRIDE=ApplicationTest=com.example.openshift:example_workflow:1.0|ApplicationTest=com.example.openshift:example_workflow:1.1
----

See link:#Tutorial-Adding_Updgraded_Version[Example Workflow: Deploying an Updated Version Concurrently with Original Application] for an example on deploying an updated application alongside the older version.


[[Request-Targeting]]
== Request Targeting for Multiple Versions

In most cases, clients must target a particular container by name to execute server-side functions. This can be done by specifying the full deployment name, the container ID hash, or the deployment alias.

For example:

* Full Deployment Name: _ApplicationTest=com.example.openshift:example_workflow:1.0_
* Container ID Hash: _be690712c7a5808a0696926088ff18b2_
* Deployment Alias: _ApplicationTest_

Specifying either the full deployment name or the container ID targets the appropriate container. Specifying the deployment alias, which is used by all the containers in the KIE server, requires a multi-stage resolution process to target the correct version container.

[[Alias-Redirection]]
== Alias Redirection

In a multi-version deployment, all applications share the same deployment alias. Requests that use the deployment alias of the application require a resolution process in order to redirect the request to the container of the correct version.

*Resolution Process Hierarchy*

The multi-stage resolution process depends on the method invoked by the client, and the ID associated with the request:

Process Hierarchy (in descending order):

. Process Instance ID (specific to {KIE_SERVER}/{PRODUCT})
. Correlation Key (specific to {KIE_SERVER}/{PRODUCT})
. Task Instance ID (specific to {KIE_SERVER}/{PRODUCT})
. Work Item ID (specific to {KIE_SERVER}/{PRODUCT})
. Job Request ID (specific to {KIE_SERVER}/{PRODUCT})
. Conversation ID
. Default Container ID

*Clients*

Multiple clients can be used to invoke the server, depending on the client interaction type:

[cols="2*", options="header"]
|===
|Client
|Interaction
|*KIE interaction*
|org.kie.server.client.KieServicesClient

|*Intelligent Process Server interaction*
|org.kie.server.client.ProcessServicesClient +
org.kie.server.client.JobServicesClient +
org.kie.server.client.QueryServicesClient +
org.kie.server.client.UserTaskServicesClient
|===

*Conversation ID*

A conversation represents interactions between KIE Services Java clients and the server. When a client initiates a conversation, the response from the server includes an encoded multi-part heading. The client will then use this heading in subsequent requests to the server. This conversation header contains the conversation ID, which is used by the Servlet Filter in the REST interface, or the EJB Interceptor in the JMS interface, to determine the correct version of the application to invoke.

[WARNING]
====
Due to a bug in the KIE client, client classes do not share the conversation ID for all services and therefore, users will be unable to complete the conversation. This issue is fixed in {PRODUCT} 6.3.1 or higher. It is recommended that you use this version of {PRODUCT} in your BOM file, as shown here:

----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.jboss.bom.brms</groupId>
        <artifactId>jboss-brms-bpmsuite-platform-bom</artifactId>
          <version>6.3.1.GA-redhat-2</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----
====

*Default Container ID*

The final stage in the process hierarchy is the default container ID. If a specific container ID cannot be resolved, the default container ID is determined as the application with the latest version (based on _<alias>=<group_id>:<artifact_id>:<version>_).

= Running and Configuring the Intelligent Process Server xPaas Image

You can make changes to the Intelligent Process Server configuration in the xPaaS image using either the S2I templates, or by using a modified Intelligent Process Server image.

== Using the Intelligent Process Server xPaaS Image Source-to-Image (S2I) Process

The recommended method to run and configure the OpenShift Intelligent Process Server xPaaS image is to use the OpenShift S2I process together with the application template parameters and environment variables.

The S2I process for the Intelligent Process Server xPaaS image works as follows:

. If there is a *_pom.xml_* file in the source repository, a Maven build is triggered with the contents of `*$MAVEN_ARGS*` environment variable.

* By default, the `package` goal is used with the `openshift` profile, including the system properties for skipping tests (`*-DskipTests*`) and enabling the Red Hat GA repository (`*-Dcom.redhat.xpaas.repo.redhatga*`).

. The results of a successful Maven build are installed into the local Maven repository, *_/home/jboss/.m2/repository/_*, along with all dependencies for offline usage.  The Intelligent Process Server xPaaS Image will load the created kjars from this local repository.

* In addition to kjars resulting from the Maven build, any kjars found in the deployments source directory will also be installed into the local Maven repository.  Kjars do not end up in the *_EAP_HOME/standalone/deployments/_* directory.

. Any JAR (that is not a kjar), WAR, and EAR in the *_deployments_* source repository directory will be copied to the *_EAP_HOME/standalone/deployments_* directory and subsequently deployed using the JBoss EAP deployment scanner.

. All files in the *_configuration_* source repository directory are copied to *_EAP_HOME/standalone/configuration_*.

[NOTE]
If you want to use a custom JBoss EAP configuration file, it should be named *_standalone-openshift.xml_*.
. All files in the *_modules_* source repository directory are copied to *_EAP_HOME/modules_*.

Refer to the xref:../reference/reference.adoc#ips-artifact-repository-mirrors-section[Artifact Repository Mirrors] section for additional guidance on how to instruct the S2I process to utilize the custom Maven artifacts repository mirror.


== Binary Builds

To deploy existing applications on OpenShift, you can use the link:https://docs.openshift.com/container-platform/latest/dev_guide/builds/build_inputs.html#binary-source[binary source] capability.

_Prerequisite:_

[upperalpha]
. *Get the application archive or build the application locally.*
+
The following example uses both the link:https://github.com/jboss-openshift/openshift-quickstarts/tree/master/processserver/library[library] and link:https://github.com/jboss-openshift/openshift-quickstarts/tree/master/processserver/library-client[library-client] quickstarts.
+
* Clone the source code.
+
[subs="verbatim,macros"]
----
$ git clone https://github.com/jboss-openshift/openshift-quickstarts.git
----
+
* link:https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html-single/development_guide/#use_the_maven_repository[Configure] the link:https://access.redhat.com/maven-repository[Red Hat JBoss Middleware Maven repository].
+
* Build the application -- both the *library* and *library-client* quickstarts.
+
[NOTE]
====
The `mvn clean package` command output below has been shortened to contain just selected information.
====
+
[subs="verbatim,macros"]
----
$ cd openshift-quickstarts/processserver/
----
+
[subs="verbatim,macros"]
----
$ mvn clean package
[INFO] Scanning for projects...
...
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ processserver-timerprocess ---
[INFO] Building jar: /tmp/openshift-quickstarts/processserver/timerprocess/target/processserver-timerprocess-1.4.0.Final.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenShift Quickstarts: Intelligent Process Server: Parent 1.4.0.Final
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ processserver-parent ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OpenShift Quickstarts: Intelligent Process Server: Library SUCCESS [  1.212 s]
[INFO] OpenShift Quickstarts: Intelligent Process Server: Library - Client SUCCESS [  7.827 s]
[INFO] OpenShift Quickstarts: Intelligent Process Server: Timer Process SUCCESS [  1.965 s]
[INFO] OpenShift Quickstarts: Intelligent Process Server: Parent SUCCESS [  0.002 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.759 s
[INFO] Finished at: 2017-06-05T10:26:06+02:00
[INFO] Final Memory: 57M/598M
[INFO] ------------------------------------------------------------------------
----

[[directory-structure-binary-builds]]
[upperalpha, start=2]
. *Prepare the directory structure on the local file system.*
+
Application archives in the *deployments/* subdirectory of the main binary build directory are copied directly to the xref:standard-deployments-folder[standard deployments folder] of the image being built on OpenShift. For the application to deploy, the directory hierarchy containing the web application data must be correctly structured.
+
Create main directory for the binary build on the local file system and *deployments/* subdirectory within it. Copy both the previously built JAR archive for the *library* quickstart (`processserver-library-1.4.0.Final.jar`), and WAR archive for the *library-client* quickstart (`processserver-library-client-1.4.0.Final.war`) to the *deployments/* subdirectory:
+
[subs="verbatim,macros"]
----
$ ls
library  library-client  pom.xml  timerprocess
----
+
[subs="verbatim,macros"]
----
$ mkdir -p ps-bin-demo/deployments
----
+
[subs="verbatim,macros"]
----
$ cp library/target/processserver-library-1.4.0.Final.jar ps-bin-demo/deployments/
----
+
[subs="verbatim,macros"]
----
$ cp library-client/target/processserver-library-client-1.4.0.Final.war ps-bin-demo/deployments/
----
+
[[standard-deployments-folder]]
[NOTE]
====
Location of the standard deployments directory depends on the underlying base image, that was used to deploy the application. See the following table:

.Standard Location of the Deployments Directory
[cols="2", options="header"]
|===
| Name of the Underlying Base Image(s) | Standard Location of the Deployments Directory

| EAP for OpenShift 6.4 and 7.0 | *_$JBOSS_HOME/standalone/deployments_*

| Java S2I for OpenShift | *_/deployments_*

| JWS for OpenShift | *_$JWS_HOME/webapps_*

|===
====

*Perform the following steps to run application consisting of binary input on OpenShift:*

. Login into OpenShift instance.
+
[subs="verbatim,macros"]
----
$ oc login
----
. Create a new project.
+
[subs="verbatim,macros"]
----
$ oc new-project ps-bin-demo
----
. (Optional) Identify the image stream for the particular image.
+
[subs="verbatim,macros"]
----
$ oc get is -n openshift | grep ^jboss-process | cut -f1 -d ' '
jboss-processserver63-openshift
----
. Create new binary build, specifying image stream and application name.
+
[NOTE]
====
You can change the default user name and password to access the REST interface of the KIE server by providing custom values for *_KIE_SERVER_USER_* and *_KIE_SERVER_PASSWORD_* environment variables.
====
+
[[kie-server-credentials]]
[subs="verbatim,macros"]
----
$ oc new-build --binary=true \
--name=ps-l-app \
--image-stream=jboss-processserver63-openshift \
-e KIE_SERVER_USER=kieserveruser \
-e KIE_SERVER_PASSWORD=kieserverPwd1!
--> Found image 78c88f3 (2 months old) in image stream "openshift/jboss-processserver63-openshift" under tag "latest" for "jboss-processserver63-openshift"

    JBoss BPMS Intelligent Process Server 6.3
    -----------------------------------------
    Platform for executing business rules on JBoss BPMS Intelligent Process Server 6.3.

    Tags: builder, processserver, processserver6

    * A source build using binary input will be created
      * The resulting image will be pushed to image stream "ps-l-app:latest"
      * A binary build was created, use 'start-build --from-dir' to trigger a new build

--> Creating resources with label build=ps-l-app ...
    imagestream "ps-l-app" created
    buildconfig "ps-l-app" created
--> Success
----
. Start the binary build. Instruct `oc` executable to use main directory of the binary build we created xref:directory-structure-binary-builds[in previous step] as the directory containing binary input for the OpenShift build.
+
[NOTE]
====
The output of the next command has been shortened for brevity.
====
+
[subs="verbatim,macros"]
----
$ oc start-build ps-l-app \
--from-dir=./ps-bin-demo/ \
--follow
Uploading directory "ps-bin-demo" as binary input for the build ...
build "ps-l-app-1" started
Receiving source from STDIN as archive ...
Copying all war artifacts from /home/jboss/source/. directory into /opt/eap/standalone/deployments for later deployment...
Copying all ear artifacts from /home/jboss/source/. directory into /opt/eap/standalone/deployments for later deployment...
Copying all rar artifacts from /home/jboss/source/. directory into /opt/eap/standalone/deployments for later deployment...
Copying all jar artifacts from /home/jboss/source/. directory into /opt/eap/standalone/deployments for later deployment...
Copying all war artifacts from /home/jboss/source/deployments directory into /opt/eap/standalone/deployments for later deployment...
'/home/jboss/source/deployments/processserver-library-client-1.4.0.Final.war' -> '/opt/eap/standalone/deployments/processserver-library-client-1.4.0.Final.war'
Copying all ear artifacts from /home/jboss/source/deployments directory into /opt/eap/standalone/deployments for later deployment...
Copying all rar artifacts from /home/jboss/source/deployments directory into /opt/eap/standalone/deployments for later deployment...
Copying all jar artifacts from /home/jboss/source/deployments directory into /opt/eap/standalone/deployments for later deployment...
'/home/jboss/source/deployments/processserver-library-1.4.0.Final.jar' -> '/opt/eap/standalone/deployments/processserver-library-1.4.0.Final.jar'
/opt/eap/standalone/deployments/processserver-library-1.4.0.Final.jar is a kjar
...
INFO: org.openshift.quickstarts:processserver-library:1.4.0.Final verified.
Pushing image 172.30.82.129:5000/ps-bin-demo/ps-l-app:latest ...
Pushed 0/9 layers, 0% complete
Pushed 1/9 layers, 12% complete
Pushed 2/9 layers, 33% complete
Pushed 3/9 layers, 45% complete
Pushed 4/9 layers, 64% complete
Pushed 5/9 layers, 71% complete
Pushed 6/9 layers, 80% complete
Pushed 7/9 layers, 88% complete
Pushed 8/9 layers, 100% complete
Pushed 9/9 layers, 100% complete
Push successful
----
. Create a new OpenShift application based on the build.
+
[subs="verbatim,macros"]
----
$ oc new-app ps-l-app
--> Found image 65a8367 (About a minute old) in image stream "ps-bin-demo/ps-l-app" under tag "latest" for "ps-l-app"

    ps-bin-demo/ps-l-app-1:0af8685b
    -------------------------------
    Platform for executing business rules on JBoss BPMS Intelligent Process Server 6.3.

    Tags: builder, processserver, processserver6

    * This image will be deployed in deployment config "ps-l-app"
    * Ports 8080/tcp, 8443/tcp, 8778/tcp will be load balanced by service "ps-l-app"
      * Other containers can access this service through the hostname "ps-l-app"

--> Creating resources ...
    deploymentconfig "ps-l-app" created
    service "ps-l-app" created
--> Success
    Run 'oc status' to view your app.
----
. Expose the service as route.
+
[subs="verbatim,macros"]
----
$ oc get svc -o name
service/ps-l-app
----
+
[subs="verbatim,macros"]
----
$ oc expose svc/ps-l-app
route "ps-l-app" exposed
----
+
[subs="verbatim,macros"]
----
$ oc get route
NAME       HOST/PORT                                    PATH      SERVICES   PORT       TERMINATION   WILDCARD
ps-l-app   ps-l-app-ps-bin-demo.openshift.example.com             ps-l-app   8080-tcp                 None
----
. Access the application.
+
You can get the list of available query string arguments of the *library* application by accessing the URL *\http://ps-l-app-ps-bin-demo.openshift.example.com/library*.
+
Run the *library-client* servlet using the URL *\http://ps-l-app-ps-bin-demo.openshift.example.com/library?command=runLocal*.
+
[NOTE]
====
You may verify the current KIE server state by accessing dedicated *server/* page of the REST API: *\http://ps-l-app-ps-bin-demo.openshift.example.com/kie-server/services/rest/server*. Use xref:kie-server-credentials[aforementioned] user name and password to access this page (or any REST API method of the server in general).
====
