[id='uberjar-friendly-kie-conf']

= Support for `uber-jar` friendly `kie.conf` files

Many modules of {PRODUCT} (e.g. drools-core, drools-compiler) have a file named `kie.conf` containing the names of the classes implementing the services provided by the corresponding module. Those files were all directly placed under the folder `META-INF`, so that when creating an uberjar containing a few {PRODUCT} modules, it was necessary to use the Maven Shade Plugin in order to merge all those `kie.conf` files into a single one.

In this release those files have been respectively moved to `META-INF/kie/{module-name}/kie.conf`. This makes {PRODUCT} more uberjar friendly and in particular is no longer necessary to use any plugin when packaging an uberjar containing {PRODUCT} modules. It is still possible for users to provide their own customized `kie.conf` file putting it under `META-INF/kie/kie.conf`.

Note that this change fixes the problem of creating an uberjar containing a single kjar while packaging multiple kjars into a single uberjar is still not supported.