[[_jbpmreleasenotes7160]]

= New and Noteworthy in jBPM 7.16.0

The following features were added to jBPM 7.16


== jBPM Server Distribution context update

Following up on the recent development to rename jBPM Console to Business Central, the single server zip distribution
has been updated to reflect the new naming convention. Business Central will now be available on http://localhost:8080/business-central.

== Enhanced Kie Controller Swagger documentation

In this release, the Swagger documentation for the Controller REST API endpoints has been enhanced to include more details
such as examples for body payloads and urls.

== New Okta work item handler

This release includes a new work item handler to easily integrate your business application with https://www.okta.com/[Okta]
identity management service. See https://github.com/kiegroup/jbpm-work-items/tree/master/okta-workitem[git repository]
for more details.

== Kie Server rendered forms in Business Central

Following up on the recent enhancements to render forms directly in the Kie Server, two new system properties:
`org.jbpm.wb.forms.renderer.ext` and `org.jbpm.wb.forms.renderer.name` now allow you to switch between Business Central
and Kie Server rendered forms. By default, forms are still rendered by Business Central but you can easily switch to either
one of the standard renderers from Kie Server ('bootstrap' or 'patternfly') or your custom render implementation.
NOTE: When using Business Central rendered forms, only the 'workbench' render fully integrates with all the needed
requirements. Users can, in this case, extend this render for further customization.

== Enhanced data source configuration for SpringBoot

In this release, the jBPM data source configuration has been refactored to allow easier migration to latest SpringBoot.
Data source configuration are now externalised to allow switch of different versions of data sources setup and allow both
easier upgrade to spring boot 2.x and to use the latest versions of jBPM to run with both spring boot 2.x and 1.5.x.