[[_jbpmreleasenotes7120]]

= New and Noteworthy in jBPM 7.12.0

The following features were added to jBPM 7.12

== Business application - first rollout

jBPM with 7.12 introduces concept of Business Applications to enable developers
to take advantage of latest technology and combine it with battle tested business automation.
This brings in brand new approach on how jBPM can be used in enterprise application
and deployed to any environment (primary to cloud) with ease.

This is the first release and is considered beta release so expect some issues but we are
heavily working on them to make it as smooth as possible. Your feedback and any
contribution is welcome (in fact wanted).

Read more about Business Applications and how to get started in following sections of
the documentation

* <<BusinessApplications/Overview-section.adoc#_overview_2,Business Application overview>>
* <<BusinessApplications/CreateApplication-section.adoc#_create_your_business_application,Business Application first steps>>
* <<BusinessApplications/Tutorials-chapter.adoc#_my_first_business_application,Business Application Tutorials>>

== Test helper classes for jBPM Services and Case management

jBPM services are the primary API that developers should use when embedding jBPM.
7.12 provides standalone test helper classes to simplify test cases for jBPM
services and case management services. The aim is to allow developers to quickly test the
APIs with or without additional services.

* `org.jbpm.test.services.AbstractCaseServicesTest`
* `org.jbpm.test.services.AbstractServicesTest`

There are two methods that need to be overridden so the proper business assets are added
to the kjar and maven coordinates for the kjar itself. Everything else will be automatically
configured. All jBPM Services / Case management services will be available for tests.

An example of what it takes to create a test case for jBPM Services

[source, java]
----
public class ProcessServiceImplPerProcessInstanceTest extends AbstractKieServicesTest {

    @Override
    protected DeploymentUnit createDeploymentUnit(String groupId, String artifactid, String version) throws Exception {
        // optionally override createDeploymentUnit method in case runtime strategy should be changed
        DeploymentUnit unit = super.createDeploymentUnit(groupId, artifactid, version);
        ((KModuleDeploymentUnit) unit).setStrategy(RuntimeStrategy.PER_PROCESS_INSTANCE);
        return unit;
    }

    @Override
    protected List<String> getProcessDefinitionFiles() {
        List<String> processes = new ArrayList<String>();
        // add here your process, rules and other business assets that should be added to kjar
        processes.add("repo/processes/general/signal.bpmn");
        return processes;
    }

    @Override
    public DeploymentUnit prepareDeploymentUnit() throws Exception {
        // specify GROUP_ID, ARTIFACT_ID, VERSION of your kjar
        return createAndDeployUnit(GROUP_ID, ARTIFACT_ID, VERSION);
    }
}
----

An example of what it takes to create a test case for Case Management Services

[source, java]
----
public class CaseServiceImplTest extends AbstractCaseServicesTest {

    @Override
    protected List<String> getProcessDefinitionFiles() {
        List<String> processes = new ArrayList<String>();
        // add here your process, case, rules and other business assets that should be added to kjar
        processes.add("cases/EmptyCase.bpmn2");
        return processes;
    }

    @Override
    protected DeploymentUnit prepareDeploymentUnit() throws Exception {
        // specify GROUP_ID, ARTIFACT_ID, VERSION of your kjar
        return createAndDeployUnit(GROUP_ID, ARTIFACT_ID, VERSION);
    }

    @Test
    public void testStartEmptyCase() {
        String caseId = caseService.startCase(deploymentUnit.getIdentifier(), EMPTY_CASE_P_ID);
        assertNotNull(caseId);
        assertEquals(FIRST_CASE_ID, caseId);
        try {
            CaseInstance cInstance = caseService.getCaseInstance(caseId);
            assertNotNull(cInstance);
            assertEquals(deploymentUnit.getIdentifier(), cInstance.getDeploymentId());

            caseService.cancelCase(caseId);
            CaseInstance instance = caseService.getCaseInstance(caseId);
            Assertions.assertThat(instance.getStatus()).isEqualTo(CaseStatus.CANCELLED.getId());
            caseId = null;
        } catch (Exception e) {
            logger.error("Unexpected error {}", e.getMessage(), e);
            fail("Unexpected exception " + e.getMessage());
        } finally {
            if (caseId != null) {
                caseService.cancelCase(caseId);
            }
        }
    }
----

== jBPM Executor Service available in ServiceRegistry

Couple releases back, jBPM introduced ServiceRegistry so developers could easily look up
jBPM services such as ProcessService or UserTaskService. ExecutorService was unfortunately left
out of this registry and thus did not allow to be used easily in custom code.

with 7.12 this has been fixed and developers can get hold of fully configured
instance of jBPM ExecutorService through the registry. It will only be there if it was enabled.

[source, java]
----
ExecutorService executorService = (ExecutorService) ServiceRegistry.get().service(ServiceRegistry.EXECUTOR_SERVICE);
----
