[[_jbpmreleasenotes7190]]

= New and Noteworthy in jBPM 7.19.0

The following features were added to jBPM 7.19


== Simplified access to Task and Process variables in Manage and Task Inbox sections

In this release, the Manage Process Instance, Manage Tasks and Task Inbox, have been enhanced to facilitate access to custom variables.
Previously, the only way to access these custom variables was to create an Advanced Filter using either the Task Name
or the Process Id. Now users can use the newly added pre-defined filters (based on Task Name and Process Id) to filter a
specific instance or task and also make use of the extra variables as columns in the resulting table.

== New predefined filters for process instances and tasks

In this release, a new set of quick-search filters has been created to allow you to easily filter relevant data of process instances and tasks.
These new filters include *SLA Compliance* and *Deployment Id*.

== jBPM XES Export

This release includes a new tool that aims to facilitate exporting XES based logs from the jBPM runtime.
These logs can then be consumed by different process mining tools to analyse different aspects from the process runtime
execution such as conformance, performance, deviations, process discovery and more.
eXtensible Event Stream (XES) is an xml based standard that unifies the interchange event data information between 
information systems on one side and analysis tools on the other side. 
For more information regarding the XES standard, please visit: http://www.xes-standard.org/.
To get started using the export tool, please check instructions in: https://github.com/kiegroup/jbpm/tree/master/jbpm-xes.

== Added color configurations for process instance diagrams

The following new properties were added in *Settings -> Process Administration* in {CENTRAL} to enable you to
change the node colors used in process instance diagrams:

* Completed node color
* Completed node border color
* Active node border color

When you modify these configurations, the change is applied to all process instance diagrams in {CENTRAL}.

