[[_jbpmreleasenotes7110]]

= New and Noteworthy in jBPM 7.11.0

The following features were added to jBPM 7.11

== CMMN support in the jBPM Console

In addition to the recent support for executing CMMN 1.1 models, the jBPM Console now allows you to import, view and modify the content of `.cmmn` files.
When authoring a project, you will be able to import your Case Management Model and select it from the asset list for viewing or modifying using the standard XML editor.

== jBPM Console Task Comments enhancements

In this release, the Task Management, Task Inbox and Task Report sections have been enhanced to display comments from completed tasks.
This allows users to review any relevant mention that was added to accomplish certain task.

Task comments deletion is now restricted to the comment owner and task administrator users only.

* Note: Task comments are available only if the deployment unit where the process lived still active and the task data still persisted.
By default, the Kie Server runs a clean up job that removes any task related data from completed processes.
If you wish to access the task comments once the process is completed, make sure you set the system property: `org.jbpm.task.cleanup.enabled` to `false` once starting the Kie Server instance.

== Spring Boot support for KIE projects enhancements

We have further enhanced the Spring Boot support for KIE projects. Now you have the ability
to use regular Spring beans for:

** Process Event Listeners
** Task Event Listeners
** Case Event Listeners
** KIE Server Event Listeners
** Custom Workitem Handlers

In addition the following features were added:

** Updated to the latest Narayana Spring Boot transaction manager
** Added ability to register custom REST endpoints in KIE Server Spring Boot applications
** Support for adding aliases when interacting with jBPM services from Spring Boot based applications
** Support for Swagger documentation of REST api for custom Spring Boot applications
** Replaced Jersey with the Spring Boot CXF JAX-WS Starter for serving REST endpoints. This enhancement will require
a small change in your existing application.properties, namely remove existing

[source]
----
kieserver.restContextPath=/rest
----

and replace with
[source]
----
cxf.path=/rest
----

== SLA support enhancements
SLA support has been enhanced, it is now possible to define SLA (due date) on intermediate catch event nodes to track SLA on them.

== Business model validation enhancement
Enhanced validation on business models for checks on empty sub-process nodes.

== Runtime engine enhancement
Updated support for broadcasting signals with expressions (e.g myevent-#{variable}). Event sub-processes
receive those correctly now.

== Designer marshalling backend
This version officially switches to a rewritten marshalling backend. If you find any issues, you can temporarily revert to the legacy marshalling backend by setting the system property `bpmn.marshaller.legacy=true`.


