[id='knowledge-store-rest-api-requests-proc_{context}']
= Sending requests with the Knowledge Store REST API using a REST client or curl utility

The Knowledge Store REST API enables you to interact with your projects and spaces in {PRODUCT} without using the {CENTRAL} user interface. You can send Knowledge Store REST API requests using any REST client or curl utility.

.Prerequisites
* {CENTRAL} is installed and running.
* You have `rest-all` user role access to {CENTRAL}.

.Procedure
. Identify the relevant xref:knowledge-store-rest-api-endpoints-ref_kie-apis[API endpoint] to which you want to send a request, such as `[GET] /spaces` to retrieve spaces in {CENTRAL}.
. In a REST client or curl utility, enter the following components for a `GET` request to `/spaces`. Adjust any request details according to your use case.
+
--
For REST client:

* *Authentication*: Enter the user name and password of the {CENTRAL} user with the `rest-all` role.
* *HTTP Headers*: Set the following header:
** `Accept`: `application/json`
* *HTTP method*: Set to `GET`.
* *URL*: Enter the Knowledge Store REST API base URL and endpoint, such as `\http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/spaces`.


For curl utility:

* `-u`: Enter the user name and password of the {CENTRAL} user with the `rest-all` role.
* `-H`: Set the following header:
** `Accept`: `application/json`
* `-X`: Set to `GET`.
* *URL*: Enter the Knowledge Store REST API base URL and endpoint, such as `\http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/spaces`.

[source,subs="attributes+"]
----
curl -u 'baAdmin:password@1' -H "Accept: application/json" -X GET "http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/spaces"
----
--

. Execute the request and review the {KIE_SERVER} response.
+
--
Example server response (JSON):

[source,json]
----
[
  {
    "name": "MySpace",
    "description": null,
    "projects": [
      {
        "name": "Employee_Rostering",
        "spaceName": "MySpace",
        "groupId": "employeerostering",
        "version": "1.0.0-SNAPSHOT",
        "description": "Employee rostering problem optimisation using Planner. Assigns employees to shifts based on their skill.",
        "publicURIs": [
          {
            "protocol": "git",
            "uri": "git://localhost:9418/MySpace/example-Employee_Rostering"
          },
          {
            "protocol": "ssh",
            "uri": "ssh://localhost:8001/MySpace/example-Employee_Rostering"
          }
        ]
      },
      {
        "name": "Mortgage_Process",
        "spaceName": "MySpace",
        "groupId": "mortgage-process",
        "version": "1.0.0-SNAPSHOT",
        "description": "Getting started loan approval process in BPMN2, decision table, business rules, and forms.",
        "publicURIs": [
          {
            "protocol": "git",
            "uri": "git://localhost:9418/MySpace/example-Mortgage_Process"
          },
          {
            "protocol": "ssh",
            "uri": "ssh://localhost:8001/MySpace/example-Mortgage_Process"
          }
        ]
      }
    ],
    "owner": "admin",
    "defaultGroupId": "com.myspace"
  },
  {
    "name": "MySpace2",
    "description": null,
    "projects": [
      {
        "name": "IT_Orders",
        "spaceName": "MySpace",
        "groupId": "itorders",
        "version": "1.0.0-SNAPSHOT",
        "description": "Case Management IT Orders project",
        "publicURIs": [
          {
            "protocol": "git",
            "uri": "git://localhost:9418/MySpace/example-IT_Orders-1"
          },
          {
            "protocol": "ssh",
            "uri": "ssh://localhost:8001/MySpace/example-IT_Orders-1"
          }
        ]
      }
    ],
    "owner": "admin",
    "defaultGroupId": "com.myspace"
  }
]
----
--
. In your REST client or curl utility, send another API request with the following components for a `POST` request to `/spaces/{spaceName}/projects` to create a project within a space. Adjust any request details according to your use case.
+
--
For REST client:

* *Authentication*: Enter the user name and password of the {CENTRAL} user with the `rest-all` role.
* *HTTP Headers*: Set the following header:
** `Accept`: `application/json`
** `Accept-Language`: `en-US`
** `Content-Type`: `application/json`
* *HTTP method*: Set to `POST`.
* *URL*: Enter the Knowledge Store REST API base URL and endpoint, such as `\http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/spaces/MySpace/projects`.
* *Request body*: Add a JSON request body with the identification data for the new project:

[source,json]
----
{
  "name": "Employee_Rostering",
  "groupId": "employeerostering",
  "version": "1.0.0-SNAPSHOT",
  "description": "Employee rostering problem optimisation using Planner. Assigns employees to shifts based on their skill."
}
----

For curl utility:

* `-u`: Enter the user name and password of the {CENTRAL} user with the `rest-all` role.
* `-H`: Set the following headers:
** `Accept`: `application/json`
** `Accept-Language`: `en-US` (If not defined, the default locale from the JVM is reflected)
** `Content-Type`: `application/json`
* `-X`: Set to `POST`.
* *URL*: Enter the Knowledge Store REST API base URL and endpoint, such as `\http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/spaces/MySpace/projects`.
* `-d`: Add a JSON request body or file (`@file.json`) with the identification data for the new project:

[source,subs="attributes+"]
----
curl -u 'baAdmin:password@1' -H "Accept: application/json" -H "Accept-Language: en-US" -H "Content-Type: application/json" -X POST "http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/spaces/MySpace/projects" -d "{ \"name\": \"Employee_Rostering\", \"groupId\": \"employeerostering\", \"version\": \"1.0.0-SNAPSHOT\", \"description\": \"Employee rostering problem optimisation using Planner. Assigns employees to shifts based on their skill.\"}"
----

[source,subs="attributes+"]
----
curl -u 'baAdmin:password@1' -H "Accept: application/json" -H "Accept-Language: en-US" -H "Content-Type: application/json" -X POST "http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/spaces/MySpace/projects" -d @my-project.json
----
--
. Execute the request and review the {KIE_SERVER} response.
+
--
Example server response (JSON):

[source,json]
----
{
  "jobId": "1541017411591-6",
  "status": "APPROVED",
  "spaceName": "MySpace",
  "projectName": "Employee_Rostering",
  "projectGroupId": "employeerostering",
  "projectVersion": "1.0.0-SNAPSHOT",
  "description": "Employee rostering problem optimisation using Planner. Assigns employees to shifts based on their skill."
}
----

If you encounter request errors, review the returned error code messages and adjust your request accordingly.
--
