// To reuse this module, ifeval the title to be more specific as needed.

[id='knowledge-store-rest-api-projects-ref_{context}']
= Projects

The Knowledge Store REST API supports the following endpoints for managing, building, and deploying projects in {CENTRAL}. The Knowledge Store REST API base URL is `\http://SERVER:PORT/{URL_COMPONENT_CENTRAL}/rest/`. All requests require HTTP Basic authentication or token-based authentication for the `rest-all` user role.

[GET] /spaces/{spaceName}/projects::
+
--
Returns projects in a specified space.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`spaceName`
|Name of the space for which you are retrieving projects
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
[
  {
    "name": "Mortgage_Process",
    "spaceName": "MySpace",
    "groupId": "mortgage-process",
    "version": "1.0.0-SNAPSHOT",
    "description": "Getting started loan approval process in BPMN2, decision table, business rules, and forms.",
    "publicURIs": [
      {
        "protocol": "git",
        "uri": "git://localhost:9418/MySpace/example-Mortgage_Process"
      },
      {
        "protocol": "ssh",
        "uri": "ssh://localhost:8001/MySpace/example-Mortgage_Process"
      }
    ]
  },
  {
    "name": "Employee_Rostering",
    "spaceName": "MySpace",
    "groupId": "employeerostering",
    "version": "1.0.0-SNAPSHOT",
    "description": "Employee rostering problem optimisation using Planner. Assigns employees to shifts based on their skill.",
    "publicURIs": [
      {
        "protocol": "git",
        "uri": "git://localhost:9418/MySpace/example-Employee_Rostering"
      },
      {
        "protocol": "ssh",
        "uri": "ssh://localhost:8001/MySpace/example-Employee_Rostering"
      }
    ]
  },
  {
    "name": "Evaluation_Process",
    "spaceName": "MySpace",
    "groupId": "evaluation",
    "version": "1.0.0-SNAPSHOT",
    "description": "Getting started Business Process for evaluating employees",
    "publicURIs": [
      {
        "protocol": "git",
        "uri": "git://localhost:9418/MySpace/example-Evaluation_Process"
      },
      {
        "protocol": "ssh",
        "uri": "ssh://localhost:8001/MySpace/example-Evaluation_Process"
      }
    ]
  },
  {
    "name": "IT_Orders",
    "spaceName": "MySpace",
    "groupId": "itorders",
    "version": "1.0.0-SNAPSHOT",
    "description": "Case Management IT Orders project",
    "publicURIs": [
      {
        "protocol": "git",
        "uri": "git://localhost:9418/MySpace/example-IT_Orders"
      },
      {
        "protocol": "ssh",
        "uri": "ssh://localhost:8001/MySpace/example-IT_Orders"
      }
    ]
  }
]
----
--
[GET] /spaces/{spaceName}/projects/{projectName}::
+
--
Returns information about a specified project in a specified space.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`spaceName`
|Name of the space where the project is located
|String
|Required

|`projectName`
|Name of the project to be retrieved
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "name": "Employee_Rostering",
  "spaceName": "MySpace",
  "groupId": "employeerostering",
  "version": "1.0.0-SNAPSHOT",
  "description": "Employee rostering problem optimisation using Planner. Assigns employees to shifts based on their skill.",
  "publicURIs": [
    {
      "protocol": "git",
      "uri": "git://localhost:9418/MySpace/example-Employee_Rostering"
    },
    {
      "protocol": "ssh",
      "uri": "ssh://localhost:8001/MySpace/example-Employee_Rostering"
    }
  ]
}
----
--
[POST] /spaces/{spaceName}/projects::
+
--
Creates a project in a specified space.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`spaceName`
|Name of the space in which the new project will be created
|String
|Required

|*body*
|The `name`, `groupId`, `version`, `description`, and any other components of the new project
|Request body
|Required
|===

.Example request body (JSON)
[source,json]
----
{
  "name": "Employee_Rostering",
  "groupId": "employeerostering",
  "version": "1.0.0-SNAPSHOT",
  "description": "Employee rostering problem optimisation using Planner. Assigns employees to shifts based on their skill."
}
----

.Example server response (JSON)
[source,json]
----
{
  "jobId": "1541017411591-6",
  "status": "APPROVED",
  "spaceName": "MySpace",
  "projectName": "Employee_Rostering",
  "projectGroupId": "employeerostering",
  "projectVersion": "1.0.0-SNAPSHOT",
  "description": "Employee rostering problem optimisation using Planner. Assigns employees to shifts based on their skill."
}
----
--
[DELETE] /spaces/{spaceName}/projects/{projectName}::
+
--
Deletes a specified project from a specified space.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`spaceName`
|Name of the space where the project is located
|String
|Required

|`projectName`
|Name of the project to be deleted
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "jobId": "1541128617727-10",
  "status": "APPROVED",
  "projectName": "Employee_Rostering",
  "spaceName": "MySpace"
}
----
--
[POST] /spaces/{spaceName}/git/clone::
+
--
Clones a project into a specified space from a specified Git address.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`spaceName`
|Name of the space to which you are cloning a project
|String
|Required

|*body*
|The `name`, `description`, and Git repository `userName`, `password`, and `gitURL` for the project to be cloned
|Request body
|Required
|===

.Example request body (JSON)
[source,json]
----
{
  "name": "Employee_Rostering",
  "description": "Employee rostering problem optimisation using Planner. Assigns employees to shifts based on their skill.",
  "userName": "baAdmin",
  "password": "password@1",
  "gitURL": "git://localhost:9418/MySpace/example-Employee_Rostering"
}
----

.Example server response (JSON)
[source,json]
----
{
  "jobId": "1541129488547-13",
  "status": "APPROVED",
  "cloneProjectRequest": {
    "name": "Employee_Rostering",
    "description": "Employee rostering problem optimisation using Planner. Assigns employees to shifts based on their skill.",
    "userName": "baAdmin",
    "password": "password@1",
    "gitURL": "git://localhost:9418/MySpace/example-Employee_Rostering"
  },
  "spaceName": "MySpace2"
}
----
--
[POST] /spaces/{spaceName}/projects/{projectName}/maven/compile::
+
--
Compiles a specified project in a specified space (equivalent to `mvn compile`).

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`spaceName`
|Name of the space where the project is located
|String
|Required

|`projectName`
|Name of the project to be compiled
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "jobId": "1541128617727-10",
  "status": "APPROVED",
  "projectName": "Employee_Rostering",
  "spaceName": "MySpace"
}
----
--
[POST] /spaces/{spaceName}/projects/{projectName}/maven/test::
+
--
Tests a specified project in a specified space (equivalent to `mvn test`).

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`spaceName`
|Name of the space where the project is located
|String
|Required

|`projectName`
|Name of the project to be tested
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "jobId": "1541132591595-19",
  "status": "APPROVED",
  "projectName": "Employee_Rostering",
  "spaceName": "MySpace"
}
----
--
[POST] /spaces/{spaceName}/projects/{projectName}/maven/install::
+
--
Installs a specified project in a specified space (equivalent to `mvn install`).

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`spaceName`
|Name of the space where the project is located
|String
|Required

|`projectName`
|Name of the project to be installed
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "jobId": "1541132668987-20",
  "status": "APPROVED",
  "projectName": "Employee_Rostering",
  "spaceName": "MySpace"
}
----
--
[POST] /spaces/{spaceName}/projects/{projectName}/maven/deploy::
+
--
Deploys a specified project in a specified space (equivalent to `mvn deploy`).

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Requirement

|`spaceName`
|Name of the space where the project is located
|String
|Required

|`projectName`
|Name of the project to be deployed
|String
|Required
|===

.Example server response (JSON)
[source,json]
----
{
  "jobId": "1541132816435-21",
  "status": "APPROVED",
  "projectName": "Employee_Rostering",
  "spaceName": "MySpace"
}
----
--
