[id='message-send-event-proc_{context}']
= Creating an event that sends Kafka messages

When designing your business process in {CENTRAL}, you can create an event that sends Kafka messages.

The event can have a data object as an input data item. The {PROCESS_ENGINE} sends the content of a data object as a message in the configured topic.

.Prerequisites

* You are logged in to {CENTRAL} and have permission to edit business processes.
* You created a business process.

.Procedure

. In {CENTRAL}, open the project that contains your business process.
. Create a data object defining the data that the message must contain. For instructions about creating data objects, see
ifdef::PAM,DM[]
{URL_DEVELOPING_PROCESS_SERVICES}#assembly-designing-business-processes[_{DESIGNING_BUSINESS_PROCESSES}_].
endif::PAM,DM[]
ifdef::JBPM,DROOLS,OP[]
xref:jBPMBPMN2[].
endif::JBPM,DROOLS,OP[]
+
. Select the business process and open the business process designer.
. Add an intermediate throw event or an end event of the type `message`.
. Open the properties of the event.
. In the *Message* field, select *New* and then enter the name of the message. This name must be the same as the name of the topic to which the event is to send Kafka messages, or else must be defined as `_topic-name_` in an `org.kie.server.jbpm-kafka.ext.topics._topic-name_` {KIE_SERVER} system property.
+
For instructions about using `org.kie.server.jbpm-kafka.ext.topics.*` system properties to define topic names, see xref:kieserver-kafka-proc_{context}[].
+
. Add an input data item and set the type of this data item to the data object that you created.
. Save the business process.

.Next steps

To enable {KAFKA_PRODUCT} integration when running the process, you must configure {KIE_SERVER}. For more information about configuring {KIE_SERVER} for {KAFKA_PRODUCT} integration, see xref:kieserver-kafka-proc_{context}[].
