// IMPORTANT: For 1.10 and later, save each version release notes as its own module file in the release-notes folder that this `ReleaseNotesKogito<version>.adoc` file is in, and then include each version release notes file in the chap-kogito-release-notes.adoc after Additional resources of {PRODUCT} deployment on {OPENSHIFT} section, in the following format:
//include::ReleaseNotesKogito.<version>/ReleaseNotesKogito.<version>.adoc[leveloffset=+1]

[id="ref-kogito-rn-new-features-1.35_{context}"]
= New features in {PRODUCT} 1.35

[role="_abstract"]
The following sections describe some of the new features or enhancements in {PRODUCT} 1.35.

== {PRODUCT} runtimes

=== {PRODUCT} Serverless Workflow

https://kiegroup.github.io/kogito-docs/serverlessworkflow/1.35.0.Final/release_notes.html[New features on 1.35].

=== {PRODUCT} JDBC addon integration with Flyway

Starting from this release, the following addons ( `kogito-addons-quarkus-persistence-jdbc` and `kogito-addons-springboot-persistence-jdbc` ) are now integrated with https://flywaydb.org/[Flyway] for database schema management.
This also means that `kogito.persistence.auto.ddl` property is no longer used. Below is a migration reference for each plugin:

==== kogito-addons-quarkus-persistence-jdbc

This integration is done via Quarkus Flyway and the following https://quarkus.io/guides/flyway[guide] can give extra details about how to use it. In order to achieve the same behavior as `kogito.persistence.auto.ddl=true`, you must add the following properties:

- `quarkus.flyway.migrate-at-start=true`
- `quarkus.datasource.db-kind=postgresql`

NOTE: Flyway integration uses a regular JDBC connection. Depending on your settings it is likely to need to include more JDBC-related properties such as username, password, etc, as shown in https://quarkus.io/guides/flyway#developing-with-flyway[Developing with Flyway].


==== kogito-addons-springboot-persistence-jdbc

Spring Boot comes with out-of-the-box https://documentation.red-gate.com/fd/community-plugins-and-integrations-spring-boot-184127423.html#:~:text=integration%20for%20Flyway[integration for Flyway]. Hence, {PRODUCT} JDBC add-on exposes full compatibility with the settings available. In order to achieve the same behavior as `kogito.persistence.auto.ddl=true`, you must add the following properties:

- `spring.flyway.enabled=true`
- `spring.flyway.locations=classpath:db/{vendor}`

NOTE: Flyway integration uses a regular JDBC connection. Depending on your settings it is likely to need to include more JDBC-related properties such as username, password, etc. For the complete set of properties, visit https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration[SpringBoot Data Migration properties].

== {PRODUCT} supporting services

=== Data Index Oracle integration with Flyway

To create the database for running Data Index Oracle, it is now possible to use https://flywaydb.org/[Flyway]. This is an alternative to manually applying DDL scripts. This integration is done via Quarkus Flyway and the following https://quarkus.io/guides/flyway[guide] can give extra details about how to use it. In a nutshell, to create the required tables for Data Index on an empty database, you must add the `quarkus.flyway.migrate-at-start=true` property. For more details, visit https://quarkus.io/guides/flyway#quarkus-flyway_quarkus.flyway.migrate-at-start[quarkus.flyway.migrate-at-start].
