// IMPORTANT: For 1.10 and later, save each version release notes as its own module file in the release-notes folder that this `ReleaseNotesKogito<version>.adoc` file is in, and then include each version release notes file in the chap-kogito-release-notes.adoc after Additional resources of {PRODUCT} deployment on {OPENSHIFT} section, in the following format:
//include::ReleaseNotesKogito.<version>/ReleaseNotesKogito.<version>.adoc[leveloffset=+1]

[id="ref-kogito-rn-new-features-1.30_{context}"]
= New features in {PRODUCT} 1.30

[role="_abstract"]
The following sections describe some of the new features or enhancements in {PRODUCT} 1.30.

== {PRODUCT} runtimes

=== {PRODUCT} Serverless Workflow

https://kiegroup.github.io/kogito-docs/serverlessworkflow/1.30.0.Final/release_notes.html[New features on 1.30].

== {PRODUCT} supporting services

=== Data Index support to map protobuf kogito.Date types as a graphql DateTime

Instead of returning dates as plain String, the data index will map dates to the appropriate DateTime graphql type.

=== New jobs service image containing all persistence options

Starting from this release, jobs service offers a new image https://quay.io/repository/kiegroup/kogito-jobs-service-allinone[/kogito-jobs-service-allinone], which combines Infinispan, Postgresql, In-memory and MongoDB persistence types.