//attributes: shared/attributes-Compliance.adoc[]
:experimental:

[id="con-compl-assess-overview_{context}"]

= {PRODUCTNAMESHORT} {COMPL} service overview

[role="_abstract"]
The {PRODUCTNAME} {COMPL} service enables IT security and compliance administrators to assess, monitor, and report on the security-policy compliance of {RHELSHORT} systems.

The {COMPL} service provides a simple but powerful user interface, enabling the creation, configuration, and management of SCAP security policies. With the filtering and context-adding features built in, IT security administrators can easily identify and manage security compliance issues in the RHEL infrastructure.

This documentation describes some of the functionality of the {COMPL} service, to help users understand reporting, manage issues, and get the maximum value from the service.

You can also create Ansible Playbooks to resolve security compliance issues and share reports with stakeholders to communicate compliance status.

[role="_additional-resources"]
.Additional Resources

* {COMPL-REMEDIATE}
* {COMPL-REPORT}
