[id='migration-planner-changes-ref_{context}']
= {PLANNER} changes in {PRODUCT} {PRODUCT_VERSION}

{PLANNER} is an embeddable planning engine in {PRODUCT} that optimizes planning problems. {PLANNER} is based on the community OptaPlanner project that is regularly updated and in some cases requires code changes for the latest {PLANNER} features. For an overview of the latest OptaPlanner changes and migration requirements, see the http://www.optaplanner.org/download/upgradeRecipe/upgradeRecipe7.html[OptaPlanner upgrade recipe archive]. OptaPlanner upgrade information for versions
ifeval::["{context}" == "migrate-6.4-to-7.x"]
7.0 through 7.11,
endif::[]
ifeval::["{context}" == "migrate-7.0-to-7.x"]
7.6 through 7.11,
endif::[]
inclusive, is relevant for upgrading from {PRODUCT_OLD} to {PRODUCT} {PRODUCT_VERSION}.

ifeval::["{context}" == "migrate-6.4-to-7.x"]
In {PRODUCT} {PRODUCT_VERSION}, certain {PLANNER} configurations in {CENTRAL} must be updated to accommodate recent OptaPlanner changes.
endif::[]
