[id='migration-non-execution-server-con']
ifdef::DM[]
= {CENTRAL} data migration

You must migrate your {CENTRAL} data from {PRODUCT_OLD} to {PRODUCT} {PRODUCT_VERSION} using the {CENTRAL} migration tool provided with this release to accommodate a new data structure in {PRODUCT} {PRODUCT_VERSION}. Additionally, if any of your applications interact with {CENTRAL} spaces (previously known as organizational units), repositories, and projects through Knowledge Store REST API calls (`/{URL_COMPONENT_CENTRAL}/rest/`), you must update these API references according to the new endpoints supported in {PRODUCT} {PRODUCT_VERSION}.
endif::DM[]

ifdef::PAM[]
= Migrating {CENTRAL} as design environment only

If you use {CENTRAL} to design business assets but do not use {CENTRAL} as an execution server with live tasks and process instances in {PRODUCT_OLD}., then follow the steps in this section to migrate to {PRODUCT} {PRODUCT_VERSION}.

If you use {CENTRAL} as both a design environment and an execution server with live tasks and process instances, follow the migration steps in xref:migration-execution-server-con[]. A separate migration path is required to transfer execution server functionality to {KIE_SERVER} for {PRODUCT} {PRODUCT_VERSION}, in addition to {CENTRAL} data.
endif::PAM[]

.Prerequisites
* A clean {PRODUCT} {PRODUCT_VERSION} installation exists that does not contain a `.niogit` folder. If the {PRODUCT} {PRODUCT_VERSION} installation contains a `.niogit` folder, the migration will fail. For installation options, see {URL_INSTALLING_AND_CONFIGURING}#assembly-planning[_{PLANNING_INSTALL}_].
* All {CENTRAL} data for {PRODUCT_OLD}, including a database used with it (if applicable), has been fully backed up. This is a precaution in case of problems during migration.
