[id='migration-java-dependencies-proc']

= Update Java project dependencies

You must update several dependencies in your Java projects to prepare them for migration to {PRODUCT} {PRODUCT_VERSION}.

.Prerequisites
* The Maven repository for {PRODUCT} {PRODUCT_VERSION} has been downloaded from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Red Hat Customer Portal] and made available to the local Maven installation (as a local or remote repository).

.Procedure
. Open the `pom.xml` file of the project and remove the `<version>` tag from any dependencies under the following groups:
* `org.kie`
* `org.drools`
* `org.jbpm`
* `org.optaplanner`
. Add the {PRODUCT_BA} bill of materials (BOM) dependency under the `<dependencies>` tag within the `<dependencyManagement>` section:
+
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>com.redhat.ba</groupId>
  <artifactId>ba-platform-bom</artifactId>
  <version>{BOM_VERSION}</version>
  <scope>import</scope>
  <type>pom</type>
</dependency>
----
+
The {PRODUCT_BA} BOM applies to both {PRODUCT_DM} and {PRODUCT_PAM}. When you add the BOM files, the correct versions of transitive dependencies from the provided Maven repositories are included in the project. The BOM `<version>` is the version of the `com.redhat.ba:ba-platform-bom` {PRODUCT_BA} artifact in the Maven repository. You can view the version of the artifact by entering the repository and navigating to the `maven-repository/com/redhat/bom/ba/ba-platform-bom` directory.
. If your code uses any Drools CDI annotations (`@KReleaseId` , `@KContainer`, `@KBase`, `@KSession`), also add the following dependency:
+
[source,xml]
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-cdi</artifactId>
</dependency>
----
+
This dependency is necessary because the CDI extension for processing the annotations is now defined using a separate module. Without this dependency, the annotations do not work.
. Replace the legacy `org.guvnor` dependency (if applicable) with the new `org.uberfire` dependency.
+
--
Legacy `org.guvnor` dependency:

[source,xml]
----
<dependency>
  <groupId>org.guvnor</groupId>
  <artifactId>guvnor-rest-client</artifactId>
</dependency>
----

New `org.uberfire` dependency:

[source,xml]
----
<dependency>
  <groupId>org.uberfire</groupId>
  <artifactId>uberfire-rest-client</artifactId>
</dependency>
----
--
ifdef::PAM[]
. Replace the legacy `org.kie.remote` dependency (if applicable) with the new `org.kie.server` dependency.
+
--
Legacy `org.kie.remote` dependency:
[source,xml]
----
<dependency>
  <groupId>org.kie.remote</groupId>
  <artifactId>kie-remote-client</artifactId>
</dependency>
----

New `org.kie.server` dependency:

[source,xml]
----
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-client</artifactId>
</dependency>
----
This dependency is necessary because {CENTRAL} no longer has execution server capabilities nor API endpoints related to the execution server.
--
. Replace the legacy `jbpm-workitems` dependency (if applicable) with one or more of the new dependencies. The new dependencies that you choose depend on the work items that your code uses.
+
--
Legacy `jbpm-workitems` dependency:

[source,xml]
----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems</artifactId>
</dependency>
----

New `jbpm-workitems` dependency options:

[source,xml]
----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-core</artifactId>
</dependency>
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-bpmn2</artifactId>
</dependency>
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-email</artifactId>
</dependency>
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-jms</artifactId>
</dependency>
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-rest</artifactId>
</dependency>
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-workitems-webservice</artifactId>
</dependency>
----
--
endif::PAM[]
. Update the version of the project artifact and save the `pom.xml` file.
