[id='migration-tool-niogit-7.4-proc_{context}']

= Using the migration tool on a `.niogit` directory

The `.niogit` directory of your {CENTRAL} distribution contains all {CENTRAL} data. You can use the {CENTRAL} migration tool on your `.niogit` directory to prepare project data and system configurations for migration to {PRODUCT} 7.5.


.Prerequisites
* {PRODUCT} 7.5 is installed.
+
NOTE: Do not run {PRODUCT} 7.5 {CENTRAL} until you have completed the steps in this section.
* {PRODUCT} 7.4 is installed and {CENTRAL} is not running on {PRODUCT} 7.4.
* JDK 8 is installed and is available on the path where the project migration tool will be installed.

.Procedure

. Locate the `bin/.niogit` directory in your {PRODUCT} 7.4 installation and locate the same directory in your new {PRODUCT} 7.5 installation.

+
--
Example:


[source,subs="attributes+"]
----
$ ~/${PRODUCT_INIT_CAP}_7.4_HOME/bin/.niogit
----

[source,subs="attributes+"]
----
$ ~/${PRODUCT_INIT_CAP}_7.5_HOME/bin/.niogit
----
--
. In your command terminal, copy the `.niogit` directory from your current {CENTRAL} distribution for {PRODUCT} 7.4 to the `bin` folder of the new {PRODUCT} 7.5 installation directory:
+
--

[source,subs="attributes+"]
----
cp -r /${PRODUCT_INIT_CAP}_7.4_HOME/bin/.niogit  /${PRODUCT_INIT_CAP}_7.5_HOME/bin/
----

The copied `.niogit` folder is the directory that the migration tool will prepare for {PRODUCT} 7.5.
. The original `.niogit` folder remains in your {PRODUCT} 7.4 installation and will not be modified by the migration tool in this procedure.
--
. In the {PRODUCT} 7.5. `bin` directory, delete the `.index` directory. You must delete this folder because {PRODUCT} 7.5 comes with certain updates that are not compatible with {PRODUCT} 7.4. The `bin` directory will be re-indexed after the migration when you start {PRODUCT} 7.5.

. Note the path to the copied `.niogit` directory for {PRODUCT} 7.5. The path will be required when you run the migration tool.
. If you have specific `dependencies`, `repositories`, or `pluginRepositories` that you want to add, remove, or update as part of the project migration, create a `pom-migration.json` file containing these elements. When you run the migration tool, the tool will prompt you if you want to include this file in the migration.
+
--
The `pom-migration.json` file requires the following sections:

* `"dependencies":[]`
* `"repositories-add":[]`
* `"repositories-remove":[]`
* `"repositories-update-urls":[]`
* `"pluginRepositories-add":[]`
* `"pluginRepositories-remove":[]`
* `"pluginRepositories-update-urls":[]`


If any of these elements do not apply to your project, include them as empty sections to prevent parsing errors.

Example `pom-migration.json` file:

[source,json,subs="attributes+"]
----
{
  "dependencies":[

    {"groupId":"junit", "artifactId":"junit", "version":"4.12", "scope":"test"},
    {"groupId":"com.thoughtworks.xstream", "artifactId":"xstream", "version":"4.12", "scope":"test"}

  ],

  "repositories-add":[
    {
      "id":"jboss-public-repository-group",
      "name":"JBoss Public Repository Group",
      "url":"http://repository.jboss.org/nexus/content/groups/public/",
      "releasesEnabled":true,
      "releasesUpdatePolicy":"never",
      "snapshotEnabled":true,
      "snapshotUpdatePolicy":"never"
    },
    {
      "id":"kie-internal-staging-repository-group",
      "name":"KIE Internal Staging Repositories",
      "url":"https://origin-repository.jboss.org/nexus/content/groups/kie-internal-group",
      "releasesEnabled":true,
      "releasesUpdatePolicy":"never",
      "snapshotEnabled":false,
      "snapshotUpdatePolicy":"never"
    }
  ],

  "repositories-remove":[
    {
      "id":"productization-repository", "url":"http://download.lab.bos.redhat.com/brewroot/repos/jb-ip-6.1-build/latest/maven/"
    }
  ],

  "repositories-update-urls":[
    {
      "id":"guvnor-m2-repo", "url":"http://localhost:8080/{URL_COMPONENT_CENTRAL}/maven3/"
    }
  ],

  "pluginRepositories-add":[

    {
      "id":"jboss-public-repository-group",
      "name":"JBoss Public Repository Group",
      "url":"http://repository.jboss.org/nexus/content/groups/public/",
      "releasesEnabled":true,
      "releasesUpdatePolicy":"never",
      "snapshotEnabled":true,
      "snapshotUpdatePolicy":"never"
    },
    {
      "id":"kie-internal-staging-repository-group",
      "name":"KIE Internal Staging Repositories",
      "url":"https://origin-repository.jboss.org/nexus/content/groups/kie-internal-group",
      "releasesEnabled":true,
      "releasesUpdatePolicy":"never",
      "snapshotEnabled":false,
      "snapshotUpdatePolicy":"never"
    }

  ],
  "pluginRepositories-remove":[],
  "pluginRepositories-update-urls":[]
}
----

Example `pom-migration.json` file with `dependencies` only:

[source,json]
----
{
  "dependencies":[

    {"groupId":"junit", "artifactId":"junit", "version":"4.12", "scope":"test"},
    {"groupId":"com.thoughtworks.xstream", "artifactId":"xstream", "version":"4.12", "scope":"test"}

  ],
  "repositories-add":[],
  "repositories-remove":[],
  "repositories-update-urls":[],
  "pluginRepositories-add":[],
  "pluginRepositories-remove":[],
  "pluginRepositories-update-urls":[]
}
----
--
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product:* {PRODUCT_SHORT}
* *Version:* 7.5

. Download *{PRODUCT} 7.5 Add-Ons* and extract the downloaded `{PRODUCT_INIT}-7.5.0-add-ons.zip` file to a temporary directory.
. In the extracted `{PRODUCT_FILE}-add-ons` folder, extract the `{PRODUCT_INIT}-7.5-migration-tool.zip` sub-folder. The migration tool is in the `bin` directory.
. In your command terminal, navigate to the temporary directory where you extracted the `{PRODUCT_INIT}-7.5-migration-tool` folder and run the migration tool. The `${PRODUCT_INIT_CAP}_NIOGIT_DIR` portion is the path to the `.niogit` directory that you previously copied to the {PRODUCT} 7.5 installation.
+
--
On Linux or UNIX-based systems:
[source,subs="attributes+"]
----
$ cd $INSTALL_DIR/{PRODUCT_INIT}-7.5-migration-tool/bin
$ ./migration-tool.sh -t ${PRODUCT_INIT_CAP}_NIOGIT_DIR
----

On Windows systems:
[source,subs="attributes+"]
ifdef::DM[]
----
$ cd $INSTALL_DIR\rhdm-7.5-migration-tool/bin
$ migration-tool.bat -t ${PRODUCT_INIT_CAP}_NIOGIT_DIR
----
endif::DM[]
ifdef::PAM[]
----
$ cd $INSTALL_DIR\rhpam-7.5-migration-tool\bin
$ migration-tool.bat -t ${PRODUCT_INIT_CAP}_NIOGIT_DIR
----
endif::PAM[]

In the command prompt that appears, the following options are displayed:

* *Project structure migration*: Migrates the {PRODUCT} 7.4 project repository structure to the new project-oriented structure used in {PRODUCT} 7.4.
* *System configuration directory structure migration*: Migrates the `system.git` repository structure used in {PRODUCT} 7.4 to the new structure used in {PRODUCT} 7.5. This migration option requires the project structure migration to be executed first.
ifdef::PAM[]
* *Forms migration*: Migrates forms created in the {PRODUCT_OLD} forms designer to the new forms designer. With this migration option, you must first complete the project structure migration and system configuration directory structure migration.
endif::PAM[]
* *POMs migration:* Updates `pom.xml` files with dependencies required for {PRODUCT} 7.5. This migration option requires the
ifdef::PAM[]
project structure migration, system configuration directory structure migration, and forms migration
endif::PAM[]
ifdef::DM[]
project structure migration and system configuration directory structure migration
endif::DM[]
to be executed first.
* *All:* Runs all migration options in sequence.
* *Exit:* Exits the migration tool.
--
. Select the option to run *All* migrations in sequence.
+
NOTE: If you prefer to run one migration option at a time, select and run the first individual migration option. After the tool runs, re-run the {CENTRAL} migration tool and select the next individual migration option in the sequence.
+

. Enter `yes` each time you are prompted to run a specific migration option.
+
For the POMs migration option, if you want to include a path to an external `pom-migration.json` file that you created previously, enter `yes` when prompted and enter the path.
+
. After the tool finishes running, enter the option to *Exit* the migration tool.
+
The `.niogit` directory structure is now compatible with {CENTRAL} in {PRODUCT}
7.5.
. Project directories are in separate repositories and all other related configurations have been migrated. You can navigate to the new `.niogit` directory to inspect the restructured contents.
