[id='optimizer-rest-api-for-execution-server-con']
= The REST API for {KIE_SERVER} 

You can communicate with the {KIE_SERVER} through the REST API.

* The base URL for sending requests is the endpoint defined earlier, for example `http://_SERVER:PORT_/kie-server/services/rest/server/`.
* All requests require basic HTTP Authentication or token-based authentication for the role [property]``kie-server``.

Following methods support three formats of the requests: JSON, JAXB, and XSTREAM.
You must provide following HTTP headers:

* `Accept`: set to `application/json` or `application/xml`.
+
When specifying more than one accepted content type in the Accept header, be sure to include the qualifiers of preference (qvalues as defined in the https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html[HTML 1.1 standard]).
If you do not, unexpected behavior can occur. This is an example of a well-formed header with multiple accepted content types:
+
[source]
----
Accept: application/xml; q=0.5, application/json; q=0.9
----

* `X-KIE-ContentType` is required when using the XSTREAM marshaller. In such case, set the header to `XSTREAM`. Values `JSON` and `JAXB` are allowed, but not required. When you set the `Content-type` to `application/xml`, the `JAXB` value is used by default.
* `Content-type`: set to `application/json` or `application/xml`. This header corresponds with the format of your payload.
* `--data`: your payload. If the payload is in a file, start the name with an ampersand `@`. For example:
+
[source]
----
--data @commandsRequest.json
----


To ensure both the request and the response are in the same format, always specify both the `Content-Type` and `Accept` HTTP headers in your application's requests.
Otherwise, you can receive a marshalling-related error from the server.

The examples use the Curl utility. You can use any REST client. Curl commands use the following parameters:

* ``-u``: specifies username:password for the {KIE_SERVER} authentication.
* ``-H``: specifies HTTP headers.
* ``-X``: specifies the HTTP method of the request, that is [GET], [POST], [PUT], or [DELETE].


[NOTE]
====
xref:optmizer-rest-api-execution-server-dm-commands-ref[{PRODUCT_DM} commands] will work only if your {KIE_SERVER} has {PRODUCT_DM} capability.
The rest of the endpoints will work only if your {KIE_SERVER} has {PRODUCT_PAM} capabilities.
Check the following URI for capabilities of your {KIE_SERVER} : __http://_SERVER:PORT_/kie-server/services/rest/server__.
====
