[id='execute-bus-proc']
= Executing a business process in {CENTRAL}

After you build and deploy the project that contains your business process, you can execute the defined functionality for the business process.

As an example, this procedure uses the *Mortgage_Process* sample project in {CENTRAL}. In this scenario, you input data into a mortgage application form acting as the mortgage broker. The *MortgageApprovalProcess* business process runs and determines whether or not the applicant has offered an acceptable down payment based on the decision rules defined in the project. The business process either ends the rule testing or requests that the applicant increase the down payment to proceed. If the application passes the business rule testing, the bank approver reviews the application and either approves or denies the loan.

.Prerequisites
* {KIE_SERVER} is deployed and connected to {CENTRAL}.
ifdef::DM,PAM[]
For more information about {KIE_SERVER} configuration, see {URL_INSTALLING_AND_CONFIGURING}#assembly-install-on-eap[_{INSTALLING_ON_EAP}_].
endif::[]

.Procedure
. In {CENTRAL}, go to *Menu* -> *Projects* and select a space. The default space is MySpace.
. In the upper-right corner of the window, click the arrow next to *Add Project* and select *Try Samples*.
. Select the *Mortgage_Process* sample and click *Ok*.
. On the project page, select *Mortgage_Process*.
. On the *Mortgage_Process* page, click *Build*.
. After the project has built, click *Deploy*.
. Go to *Menu* -> *Manage* -> *Process Definitions*.
. Click anywhere in the *MortgageApprovalProcess* row to view the process details.
. Click the *Diagram* tab to view the business process diagram in the editor.
. Click *New Process Instance* to open the *Application* form and input the following values into the form fields:

* *Down Payment*: `30000`
* *Years of amortization*: `10`
* *Name*: `Ivo`
* *Annual Income*: `60000`
* *SSN*: `123456789`
* *Age of property*: `8`
* *Address of property*: `Brno`
* *Locale*: `Rural`
* *Property Sale Price*: `50000`

. Click *Submit* to start a new process instance. After starting the process instance, the *Instance Details* view opens.
. Click the *Diagram* tab to view the process flow within the process diagram. The state of the process is highlighted as it moves through each task.
. Click *Menu* -> *Manage* -> *Tasks*.
+
--
For this example, the user or users working on the corresponding tasks are members of the following groups:

* *approver*: For the *Qualify* task
* *broker*: For the *Correct Data* and *Increase Down Payment* tasks
* *manager*: For the *Final Approval* task
--
. As the approver, review the *Qualify* task information, click *Claim* and then *Start* to start the task, and then select *Is mortgage application in limit?* and click *Complete* to complete the task flow.
. In the *Tasks* page, click anywhere in the *Final Approval* row to open the *Final Approval* task.
. Click *Claim* to claim responsibility for the task, and click *Complete* to finalize the loan approval process.

NOTE: The *Save* and *Release* buttons are only used to either pause the approval process and save the instance if you are waiting on a field value, or to release the task for another user to modify.
