[id='proc-define-process-variables_{context}']
= Defining process variables

Process variables are defined as properties in the BPMN2 definition file and are visible within the process instance. They are initialized at process creation and destroyed on process completion.

A process variable is a variable that exists in a process context and can be accessed by its process or its child elements. Process variables belong to a particular process instance and cannot be accessed by other process instances.
Every process variable defines its ID and item subject reference: the ID serves as the variable name and must be unique within the process definition.
The item subject reference defines the data type the variable stores.

Process variables are initialized when the process instance is created. Their value can be changed by the process activities using the Assignment, when the global variable is associated with the local Activity context, local Activity variable, or by a direct call to the variable from a child context.

Note that process variables should be mapped to local variables.

.Prerequisites
* You have created a project in {CENTRAL} and it contains at least one business process asset.

.Procedure
. Open a business process asset.
. Click a blank area of the process designer canvas.
. Click the *Properties* icon on the upper-right side of the screen to open the *Properties* panel.
. If necessary, expand the *Process Data* section.
. In the *Process Variables* sub-section, click the plus icon.
. Enter a name for the variable in the *Name* box.
. Select a data type from the *Data Type* menu.
