[id='pmml-support-con_{context}']
= PMML support in {PRODUCT}

{PRODUCT} includes consumer conformance support for the following PMML model types:

* http://dmg.org/pmml/v4-4-1/Regression.html[Regression models]
* http://dmg.org/pmml/v4-4-1/Scorecard.html[Scorecard models]
* http://dmg.org/pmml/v4-4-1/TreeModel.html[Tree models]
* http://dmg.org/pmml/v4-4-1/MultipleModels.html#xsdElement_MiningModel[Mining models] (with sub-types `modelChain`, `selectAll`, and `selectFirst`)

For a list of all PMML model types, including those not supported in {PRODUCT}, see the DMG http://dmg.org/pmml/v4-4-1/GeneralStructure.html[PMML specification].

{PRODUCT} offers two implementations including legacy and trusty:

PMML legacy support::
When you add a PMML file to a project in {PRODUCT}, multiple assets are generated. Each type of PMML model generates a different set of assets, but all PMML model types generate at least the following set of assets:

* A DRL file that contains all of the rules associated with your PMML model
* At least two Java classes:
** A data class that is used as the default object type for the model type
** A `RuleUnit` class that is used to manage data sources and rule execution

If a PMML file has `MiningModel` as the root model, multiple instances of each of these files are generated.

PMML trusty support::
When you add a PMML file to a project in {PRODUCT}, multiple assets are generated. The tree and scorecard models are translated to rules, and regression and mining models are translated to Java classes. Each type of PMML model generates a different set of assets, but all PMML model types generate at least the following set of assets:

* A root package whose name is derived from the PMML file name
* In the root package, a Java factory class that is used to instantiate the model
* A subpackage specific to the model whose name is derived from the model name
* For rule models, two `rule-mapper` classes that are used to instantiate the rule network
* For mining models, children model packages and classes are nested in the parent model

ifdef::DM,PAM[]
[IMPORTANT]
====
The legacy implementation is deprecated with {PRODUCT} 7.10.0 and will be replaced by trusty implementation in a future {PRODUCT} release.
====
endif::[]
ifdef::DROOLS,JBPM,OP[]
[IMPORTANT]
====
The legacy implementation is deprecated with {PRODUCT} 7.48.0 and will be replaced by the trusty implementation in a future {PRODUCT} release.
====
endif::[]

{PRODUCT} does not include a built-in PMML model editor, but you can use an XML or PMML-specific authoring tool to create PMML models and then integrate the PMML models in your decision services in {PRODUCT}. You can import PMML files into your project in {CENTRAL} (*Menu -> Design -> Projects -> Import Asset*) or package the PMML files as part of your project knowledge JAR (KJAR) file without {CENTRAL}.

NOTE: Currently, only one model for each PMML file is allowed. Also, extensions are temporarily not supported.

For more information about including assets such as PMML files with your project packaging and deployment method, see
ifdef::DM,PAM[]
{URL_DEPLOYING_AND_MANAGING_SERVICES}#assembly-packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].
endif::[]
ifdef::DROOLS,JBPM,OP[]
<<_builddeployutilizeandrunsection>>.
endif::[]
