[id='pmml-support-con_{context}']
= PMML support in {PRODUCT}

{PRODUCT} includes consumer conformance support for the following PMML model types:

* http://dmg.org/pmml/v4-4-1/Regression.html[Regression models]
* http://dmg.org/pmml/v4-4-1/Scorecard.html[Scorecard models]
* http://dmg.org/pmml/v4-4-1/TreeModel.html[Tree models]
* http://dmg.org/pmml/v4-4-1/MultipleModels.html#xsdElement_MiningModel[Mining models] (with sub-types `modelChain`, `selectAll`, and `selectFirst`)
* http://dmg.org/pmml/v4-4-1/ClusteringModel.html[Clustering models]

For a list of all PMML model types, including those not supported in {PRODUCT}, see the DMG http://dmg.org/pmml/v4-4-1/GeneralStructure.html[PMML specification].

{PRODUCT} offers two implementations including PMML legacy and PMML trusty.

ifdef::DM,PAM[]
[IMPORTANT]
====
The PMML legacy implementation is deprecated with {PRODUCT} 7.10.0 and will be replaced by PMML trusty implementation in a future {PRODUCT} release.
====
endif::[]
ifdef::DROOLS,JBPM,OP[]
[IMPORTANT]
====
The PMML legacy implementation is deprecated with {PRODUCT} 7.48.0 and will be replaced by the PMML trusty implementation in a future {PRODUCT} release.
====
endif::[]

{PRODUCT} does not include a built-in PMML model editor, but you can use an XML or PMML-specific authoring tool to create PMML models and then integrate the PMML models in your decision services in {PRODUCT}. You can import PMML files into your project in {CENTRAL} (*Menu -> Design -> Projects -> Import Asset*) or package the PMML files as part of your project knowledge JAR (KJAR) file without {CENTRAL}.

For more information about including assets such as PMML files with your project packaging and deployment method, see
ifdef::DM,PAM[]
{URL_DEPLOYING_AND_MANAGING_SERVICES}#assembly-packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].
endif::[]
ifdef::DROOLS,JBPM,OP[]
<<_builddeployutilizeandrunsection>>.
endif::[]

ifdef::DM,PAM[]
You can migrate a PMML service to a {KOGITO} microservice. For more information about migrating to {KOGITO} microservices, see {URL_GETTING_STARTED_KOGITO_MICROSERVICES}#assembly-getting-started-migration-to-kogito-microservices[_{MIGRATION_KOGITO_SERVICES}_].
endif::[]
