[id='pmml-invocation-options-con_{context}']
= PMML model execution

You can import PMML files into your {PRODUCT} project using {CENTRAL} (*Menu -> Design -> Projects -> Import Asset*) or package the PMML files as part of your project knowledge JAR (KJAR) file without {CENTRAL}. After you implement your PMML files in your {PRODUCT} project, you can execute the PMML-based decision service by embedding PMML calls directly in your Java application or by sending an `ApplyPmmlModelCommand` command to a configured {KIE_SERVER}.

For more information about including PMML assets with your project packaging and deployment method, see
ifdef::DM,PAM[]
{URL_PACKAGING_DEPLOYING_PROJECT}[_{PACKAGING_DEPLOYING_PROJECT}_].
endif::[]
ifdef::DROOLS,JBPM,OP[]
<<_builddeployutilizeandrunsection>>.
endif::[]

NOTE: You can also include a PMML model as part of a Decision Model and Notation (DMN) service in {CENTRAL}. When you include a PMML model within a DMN file, you can invoke that PMML model as a boxed function expression for a DMN decision node or business knowledge model node. For more information about including PMML models in a DMN service, see {URL_DMN_MODELS}#dmn-included-models-pmml-proc_dmn-models[_{DMN_MODELS}_].
