[[_drools.workbenchremoteapi]]
= REST


REST API calls to Knowledge Store allow you to manage the Knowledge Store content and manipulate the static data in the repositories of  the Knowledge Store.
The calls are asynchronous, that is, they continue their execution as a job after a call was performed.
The job ID  is returned by every call to allow (after the REST API call was performed) to request the job status and verify whether the job finished successfully.
Parameters of these calls are provided in the form of JSON entities. 

When using Java code to interface with the REST API, the classes used in POST operations or otherwise returned by various operations can be found in the link:https://origin-repository.jboss.org/nexus/#nexus-search;quick~uberfire-rest-client[`(org.uberfire:)uberfire-rest-client`] JAR.
All  of the classes mentioned below can be found in the `org.guvnor.rest.client` package in that JAR.

== Job calls


Every Knowledge Store REST call returns its job ID after it was sent.
This is necessary as the calls are asynchronous and you need  to be able to reference the job to check its status as it goes through its lifecycle.
During its lifecycle, a job can have the  following statuses: 

* ``ACCEPTED``: the job was accepted and is being processed
* ``BAD_REQUEST``: the request was not accepted as it contained incorrect content
* ``RESOURCE_NOT_EXIST``: the requested resource (path) does not exist
* ``DUPLICATE_RESOURCE``: the resource already exists
* ``SERVER_ERROR``: an error on the server occurred
* ``SUCCESS``: the job finished successfully
* ``FAIL``: the job failed
* ``DENIED``: the job was denied
* ``GONE``: the job ID could not be found
+ 
A job can be GONE in the following cases:
** The job was explicitly removed
** The job finished and has been deleted from the status cache (the job is removed from status cache after the cache  has reached its maximum capacity)
** The job never existed


The following `job` calls are provided:

[GET] `/jobs/__{jobID}__`::
  Returns the job status

[DELETE] `/jobs/__{jobID}__`::
  Removes the job: If the job is not yet being processed, this will remove the job from the job queue.
  However, this will not cancel or stop an ongoing job

== Project calls


Project calls to the Knowledge Store allow you to manage Workspace projects.

The following `project` calls are provided:

[GET] `/projects`::
  Gets information about all the projects in the Knowledge Store.

[GET] `/spaces/{spaceName}/projects/{projectName}`::
  Gets information about the project.

[POST] `/spaces/{spaceName}/projects/{projectName}`::
  Creates a new project in given space.

[DELETE] `/spaces/{spaceName}/projects/{projectName}`::
  Removes the project from the Knowledge Store.

[GET] `/spaces/{spaceName}/projects`::
  Gets information about all projects in the space

[POST] `/spaces/{spaceName}/git/clone`::
  Clones a project into the space from provided git address.

[DELETE] `/spaces/{spaceName}/projects/{projectName}`::
  Deletes the project from the space.

== Space calls


Space calls to the Knowledge Store allow you to manage spaces.

The following `spaces` calls are provided:

[GET] `/spaces`::
  Gets all spaces.

[GET] `/spaces/{spaceName}`::
  Gets a single space.

[POST] `/spaces`::
  Creates a space described by `Space` JSON entity.

[DELETE] `/spaces/{spaceName}`::
  Deletes the space.

== Maven calls


Maven calls to a project in the Knowledge Store allow you compile, test, install, and deploy projects.

The following `maven` calls are provided:

[POST] `/spaces/{spaceName}/projects/{projectName}/maven/compile`::
  Compiles the project (equivalent to ``mvn compile``)

[POST] `/spaces/{spaceName}/projects/{projectName}/maven/test`::
  Tests the project (equivalent to ``mvn test``)

[POST] `/spaces/{spaceName}/projects/{projectName}/maven/install`::
  Installs the project (equivalent to ``mvn install``)

[POST] `/spaces/{spaceName}/projects/{projectName}/maven/deploy`::
  Deploys the project (equivalent to  ``mvn deploy``)

== REST summary


The URL templates in the table below are relative the following URL: 

* `http://__{server}__:__{port}__/kie-wb/rest`


== Embedded Kie Server Controller calls

When running the Workbench with the embedded Kie Server Controller mode, a series of endpoints related to managing
all aspects of Kie Server Templates, Kie Server instances and Containers are also available.
See <<_controller_rest_api, Controller REST API>> for more details.
A <<_kie_server_controller_client_api, Java client API>> is also available for interacting with these endpoints.
