[id='kie-dmn-validation-in-maven-plugin-con']

= KIE DMN validation in Maven plugin

The `kie-maven-plugin` component now performs default pre-compilation validation of DMN model assets. The `kie-maven-plugin` component includes the following enhancements:

* DMN model files are verified against the DMN specification XSD schema to ensure that the files are valid XML and compliant with the specification.
* The pre-compilation analysis is performed for the DMN model to ensure that the basic semantic is aligned with the DMN specification.

You can modify the default DMN validation behavior to perform only a specified validation during the project build, or you can disable this default behavior completely, as shown in the following examples:

.Default configuration for DMN validation
[source,xml]
----
<plugin>
  <groupId>org.kie</groupId>
  <artifactId>kie-maven-plugin</artifactId>
  <extensions>true</extensions>
  <configuration>
    <validateDMN>VALIDATE_SCHEMA,VALIDATE_MODEL</validateDMN>
  </configuration>
</plugin>
----

.Configuration to perform only the XSD schema validation
[source,xml]
----
<plugin>
  <groupId>org.kie</groupId>
  <artifactId>kie-maven-plugin</artifactId>
  <extensions>true</extensions>
  <configuration>
    <validateDMN>VALIDATE_SCHEMA</validateDMN>
  </configuration>
</plugin>
----

.Configuration to disable all DMN validation
[source,xml]
----
<plugin>
  <groupId>org.kie</groupId>
  <artifactId>kie-maven-plugin</artifactId>
  <extensions>true</extensions>
  <configuration>
    <validateDMN>disable</validateDMN>
  </configuration>
</plugin>
----

NOTE: If you enter an unrecognized `<validateDMN>` configuration flag, all pre-compilation validation is disabled and the Maven plugin emits related log messages.
