[id='kie-dmn-validation-in-maven-plugin']

= Kie DMN Validation in maven plugin

The `kie-maven-plugin` now performs by default pre-compilation validation of DMN model assets (ref: https://issues.redhat.com/browse/DROOLS-5020[DROOLS-5020]).

Specifically:

- DMN model files will be checked against the DMN specification XSD schema, to check they are XML-valid and conformant to the specification (`VALIDATE_SCHEMA` flag)
- pre-compilation analsys will be performed on the DMN model, to ensure some basic semantic is respected accordingly to the DMN specification (`VALIDATE_MODEL` flag)

It is possible to override the default behavior, to disable completely or perform only a specific check, by supplying `kie-maven-plugin` configuration option `validateDMN`.

The following example illustrates how to instruct the plugin to perform only the XSD schema validation:
```
<plugin>
    <groupId>org.kie</groupId>
    <artifactId>kie-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <validateDMN>VALIDATE_SCHEMA</validateDMN> 
    </configuration>
</plugin>
```

The following example illustrates how to instruct the plugin to disable any pre-compilation validation of DMN model assets:
```
<plugin>
    <groupId>org.kie</groupId>
    <artifactId>kie-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <validateDMN>disable</validateDMN> 
    </configuration>
</plugin>
```

Please notice any non-recognized `validateDMN` configuration flag, will disable any pre-compilation validation; the plugin will emit a log message accordingly.

The default configuration is equivalent to:
```
<plugin>
    <groupId>org.kie</groupId>
    <artifactId>kie-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <validateDMN>VALIDATE_SCHEMA,VALIDATE_MODEL</validateDMN> 
    </configuration>
</plugin>
```