[id='kie-dmn-validation-in-maven-plugin']

= KIE DMN validation in maven plugin

The `kie-maven-plugin` now performs default pre-compilation validation of DMN model assets. It includes the following enhancements:

- DMN model files are verified against the DMN specification XSD schema to ensure that the files are XML valid and compliant to the specification.
- The pre-compilation analysis is performed for the DMN model to ensure that the basic semantic is aligned with DMN specification.

You can also override the default behavior by disabling the feature or performing a specific validation.

For example, use the following configuration to perform only the XSD schema validation:
```
<plugin>
    <groupId>org.kie</groupId>
    <artifactId>kie-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <validateDMN>VALIDATE_SCHEMA</validateDMN> 
    </configuration>
</plugin>
```

Use the following configuration to disable pre-compilation validation of DMN model assets:
```
<plugin>
    <groupId>org.kie</groupId>
    <artifactId>kie-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <validateDMN>disable</validateDMN> 
    </configuration>
</plugin>
```

The default configuration is as follows:
```
<plugin>
    <groupId>org.kie</groupId>
    <artifactId>kie-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <validateDMN>VALIDATE_SCHEMA,VALIDATE_MODEL</validateDMN> 
    </configuration>
</plugin>
```

NOTE: An unrecognized `validateDMN` configuration flag disables any pre-compilation validation and the maven plugin emits related log message.
