[#dmn_support_in_drools]
= DMN Support in Drools
:imagesdir: ..

Drools 7.0 includes full runtime support for DMN 1.1 models at *conformance level 3*. It does not, however, include any editor for DMN models. Editors for DMN models will be
added to the platform in the near future, but meanwhile we recommend looking at one of several DMN compliant editors available in the market.

From a platform perspective, DMN models are just another type of asset that can be included in a Drools kjar and deployed to the runtime. That means Drool 7.0 can consume and
execute DMN models as well as any of the other supported assets (like DRL files, native decision tables, etc) from the same kjar allowing users to always use the best tool for
the job at hand. In fact, it is common to have BPMN models directly invoke DMN decision services from their decision task nodes.

[#dmn_support_in_drools_details]
== DMN Implementation Details

The DMN specification is quite good, doing its best to define both syntax and semantic for the models. It is not perfect
though. There are a few bugs present in the spec as well as some ambiguities.

At the moment, there is no TCK or official reference implementation for DMN v1.1, to resolve these ambiguities. A vendor
neutral effort for a TCK is available https://agilepro.github.io/dmn-tck/index.html[here].

Drools strives to be as compliant as possible with the specification, but there are a few differences that are listed
here. These differences fall into 2 categories: (a) fixes to bugs in the spec, and (b) extensions to the
spec to better support use cases, without prejudice to strict models. We also explicitly categorize the differences
between the FEEL language differences and the DMN model differences.

=== a. Fixes to bugs and changes in the FEEL language

* __Space Sensitivity__: this implementation of the FEEL language is space *__insensitive__*. The goal is to avoid
non-deterministic behavior based on the context and differences in behavior based on invisible characters (e.g.,
 white spaces). This means that for this implementation, a variable named `first name` with one space is exactly
 the same as `first  name` with two spaces in it.

* __List functions `or()` and `and()` __: the spec defines two list functions named `or()` and `and()`, but
according to the FEEL grammar, these are not valid function names, as `and` and `or` are reserved keywords.
 This implementation renamed these functions to `any()` and `all()` respectively, in anticipation for DMN 1.2.

* __Keyword `in` can not be used in variable names__: the spec defines that any keyword can be reused as part
 of a variable name, but the ambiguities caused with the `for ... in ... return` loop prevent the reuse of the `in`
 keyword. All other keywords are supported as part of variable names.

* __Support for date and time literals on ranges__: according to the grammar rules #8, #18, #19, #34 and #62, `date
 and time` literals are supported in ranges (pages 110-111). Chapter 10.3.2.7 on page 114, on the other hand, contradicts
 the grammar and says they are not supported. This implementation chose to follow the grammar and support `date and
 time` literals on ranges, as well as extend the specification to support any arbitrary expression (see extensions below).

* __Invalid time syntax__: chapter 10.3.2.3.4 on page 112 and bullet point about `time` on page 131 both state that
 the `time` string lexical representation follows the XML Schema Datatypes specification as well as ISO 8601. According
 to the XML Schema specification (https://www.w3.org/TR/xmlschema-2/#time), the lexical representation of a time follows
 the pattern `hh:mm:ss.sss` without any leading character. The DMN specification uses a leading "T" in several examples,
 that we understand is a typo a not in accordance with the standard.

=== b. Extensions to the FEEL language specification

* __Support for scientific and hexadecimal notations__: this implementation supports scientific and hexadecimal
  notation for numbers. E.g.: `1.2e5` (scientific notation), `0xD5` (hexadecimal notation).

* __Support for expressions as end points in ranges__: this implementation supports expressions as endpoints
  for ranges. E.g: `[date("2016-11-24")..date("2016-11-27")]`

* __Support for additional types__: the specification only defines the following as basic types of the language:
  ** number
  ** string
  ** boolean
  ** days and time duration
  ** years and month duration
  ** time
  ** date and time
+
For completeness and orthogonality, this implementation also supports the following types:

  ** context
  ** list
  ** range
  ** function
  ** unary test

* __Support for unary tests__: for completeness and orthogonality, unary tests are supported
  as first class citizens in the language. They are effectively functions with an implicit single
  parameter, and can be invoked in the same way as functions are. E.g.:
+
[source,json]
.UnaryTestAsFunction.feel
----
  {
      is minor : < 18,
      Bob is minor : is minor( bob.age )
  }
----

* __Support for additional built-in functions__: additional functions are supported out of the box:

  ** `now()` : returns the current local date and time
  ** `today()` : returns the current local date
  ** `decision table()` : returns a decision table function. Although the spec mentions a decision table
  function on page 114, it is not implementable as defined.
  ** `string( mask, p... )` : returns a string formatted as per the mask. See Java String.format() for
  details on the mask syntax. E.g.: `string( "%4.2f", 7.1298 )` returns the string `"7.12"`.

* __Support for additional date and time arithmetics__: subtracting two dates will return a days and time duration with the number of days between the two
  dates, ignoring daylight savings. E.g.:
+
[source,json]
.DateArithmetic.feel
----
date( "2017-05-12" ) - date( "2017-04-25" ) = duration( "P17D" )
----

=== c. Fixes to bugs and changes to the DMN model

* __Support for types with spaces on names__: the DMN XML schema defines type refs as QNames,
  but QNames do not allow spaces. It is then not possible to use types like FEEL `date and time`,
  `days and time duration` or `years and months duration`. This implementation does parse such
  typerefs as strings and allows type names with spaces, but in order to comply with the XML schema,
  it also added the following aliases to such types that can be used instead:

  ** `date and time` = `dateTime`
  ** `days and time duration` = `duration` or `dayTimeDuration`
  ** `years and months duration` = `duration` or `yearMonthDuration`
+
Please note that for the "duration" types, the user can simply use `duration` and the engine will
infer the proper duration, either `days and time duration` or `years and months duration`.

=== d. Extensions to the DMN model specification

* __Lists support heterogeneous element types__: at the moment, this implementation supports
  lists with heterogeneous element types. This is an experimental extension and does limit the
  functionality of some functions and filters. We will re-evaluate this decision in the future.

* __TypeRef link between Decision Tables and Item Definitions__: on decision tables/input clause,
  if no values list is defined, the engine automatically checks the type reference and apply the
  allowed values check if it is defined.
