[id='processengine-core-con_{context}']
= Core engine API for the {PROCESS_ENGINE}

The {PROCESS_ENGINE} executes business processes. To define the processes, you create _business assets_, including process definitions and custom tasks.

You can use the Core Engine API to load, execute, and manage processes in the {PROCESS_ENGINE}.

Several levels of control are available:

* At the lowest level, you can directly create a _KIE base_ and a _KIE session_. A KIE base represents all the assets in a business process. A KIE session is an entity in the {PROCESS_ENGINE} that runs instances of a business process. This level provides fine-grained control, but requires explicit declaration and configuration of process instances, task handlers, event handlers, and other {PROCESS_ENGINE} entities in your code.

* You can use the _RuntimeManager_ class to manage sessions and processes. This class provides sessions for required process instances using a configurable strategy. It automatically configures the interaction between the KIE session and task services. It disposes of {PROCESS_ENGINE} entities that are no longer necessary, ensuring optimal use of resources. You can use a fluent API to instantiate `RuntimeManager` with the necessary business assets and to configure its environment.

* You can use the _Services_ API to manage the execution of processes. For example, the Deployment service deploys business assets into the engine, forming a _deployment unit_. The Process service runs a process from this deployment unit. 
+
If you want to embed the {PROCESS_ENGINE} in your application, the Services API is the most convenient option, because it hides the internal details of configuring and managing the engine. 

* Finally, you can deploy a _{KIE_SERVER}_ that loads business assets from KJAR files and runs processes. The {KIE_SERVER} provides a REST API for loading and managing the processes. You can also use {CENTRAL} to manage a {KIE_SERVER}.
+
If you use a {KIE_SERVER}, you do not need to use the Core Engine API. 
ifdef::PAM,DM[]
For information about deploying and managing processes on a {KIE_SERVER}, see {URL_DEPLOYING_AND_MANAGING_SERVICES}#assembly-packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].
endif::PAM,DM[]

For the full reference information for all public {PROCESS_ENGINE} API calls, see the https://docs.jboss.org/drools/release/{COMMUNITY_VERSION_FINAL}/kie-api-javadoc/index.html[Java documentation]. Other API classes also exist in the code, but they are internal APIs that can be changed in later versions. Use public APIs in applications that you develop and maintain.  
