[id='service-deployment-con_{context}']
= Deployment service

The deployment service deploys and undeploys units in the {PROCESS_ENGINE}.

A _deployment unit_ represents the contents of a KJAR file. A deployment unit includes business assets, such as process definitions, rules, forms, and data models. After deploying the unit you can execute the processes it defines. You can also query the available deployment units.

Every deployment unit has a unique identifier string, `deploymentId`, also known as `deploymentUnitId`. You can use this identifier to apply anys ervice actions to the deployment unit.

In a typical use case for this service, you can load and unload multiple KJARs at the same time and, when necessary, execute processes simultaneously.

The following code sample shows simple use of the deployment service.

.Using the deployment service
[source,java]
----
// create deployment unit by providing the GAV of the KJAR
DeploymentUnit deploymentUnit = new KModuleDeploymentUnit(GROUP_ID, ARTIFACT_ID, VERSION);
// get the deploymendId for the deployed unit 
String deploymentId = deploymentUnit.getIdentifier();
// deploy the unit
deploymentService.deploy(deploymentUnit);
// retrieve the deployed unit
DeployedUnit deployed = deploymentService.getDeployedUnit(deploymentId);
// get the runtime manager 
RuntimeManager manager = deployed.getRuntimeManager();
----

The following definition shows the complete `DeploymentService` interface:

.Definition of the `DeploymentService` interface
[source,java]
----
public interface DeploymentService {

    void deploy(DeploymentUnit unit);

    void undeploy(DeploymentUnit unit);

    RuntimeManager getRuntimeManager(String deploymentUnitId);

    DeployedUnit getDeployedUnit(String deploymentUnitId);

    Collection<DeployedUnit> getDeployedUnits();

    void activate(String deploymentId);

    void deactivate(String deploymentId);

    boolean isDeployed(String deploymentUnitId);
}
----
