[[ips-artifact-repository-mirrors-section]]
= Artifact Repository Mirrors

// Define required 'bcname' attribute for xpaas_maven_mirror_url.adoc page
:bcname: ips

// Include the Artifact Repository Mirrors section
// (MAVEN_MIRROR_URL variable usage information)
include::../../topics/product-shared-docs/xpaas_maven_mirror_url.adoc[bcname]

= Application Template Parameters

[cols="2*", options="header"]
|===
|Variable
|Description
|*APPLICATION_NAME*
|The name for the application.

|*KIE_SERVER_PROTOCOL*
|The protocol to access the KIE Server REST interface.

|*KIE_SERVER_PORT*
|The port to access the KIE Server REST interface.

|*KIE_SERVER_USER*
|The user name to access the KIE Server REST or JMS interface.

|*KIE_SERVER_PASSWORD*
|The password to access the KIE Server REST or JMS interface. Must be different than username; must not be root, admin, or administrator; must contain at least 8 characters, 1 alphabetic character(s), 1 digit(s), and 1 non-alphanumeric symbol(s).

|*KIE_SERVER_DOMAIN*
|JAAS LoginContext domain that shall be used to authenticate users when using JMS.

|*KIE_SERVER_JMS_QUEUES_REQUEST*
|JNDI name of request queue for JMS.

|*KIE_SERVER_JMS_QUEUES_RESPONSE*
|JNDI name of response queue for JMS.

|*KIE_SERVER_EXECUTOR_JMS_QUEUE*
|JNDI name of executor queue for JMS.

|*KIE_SERVER_PERSISTENCE_DIALECT*
|Hibernate persistence dialect.

|*HOSTNAME_HTTP*
|Custom hostname for http service route. Leave blank for default hostname, e.g., _<application-name>_-_<project>_._<default-domain-suffix>_

|*HOSTNAME_HTTPS*
|Custom hostname for https service route. Leave blank for default hostname, e.g., secure-_<application-name>_-_<project>_._<default-domain-suffix>_

|*SOURCE_REPOSITORY_URL*
|Git source URI for application.

|*SOURCE_REPOSITORY_REF*
|Git branch/tag reference.

|*CONTEXT_DIR*
|Path within Git project to build; empty for root project directory.

|*DB_JNDI*
|Database JNDI name used by application to resolve the datasource, e.g. java:/jboss/datasources/ExampleDS

|*DB_DATABASE*
|Database name.

|*VOLUME_CAPACITY*
|Size of persistent storage for database volume.

|*MQ_JNDI*
|JNDI name for connection factory used by applications to connect to the broker, e.g. java:/JmsXA

|*MQ_PROTOCOL*
|Broker protocols to configure, separated by commas. Allowed values are: `openwire`, `amqp`, `stomp` and `mqtt`. Only `openwire` is supported by EAP.

|*MQ_QUEUES*
|Queue names, separated by commas. These queues will be automatically created when the broker starts. Also, they will be made accessible as JNDI resources in EAP.

|*MQ_TOPICS*
|Topic names, separated by commas. These topics will be automatically created when the broker starts. Also, they will be made accessible as JNDI resources in EAP.

|*HTTPS_SECRET*
|The name of the secret containing the keystore file.

|*HTTPS_KEYSTORE*
|The name of the keystore file within the secret.

|*HTTPS_NAME*
|The name associated with the server certificate.

|*HTTPS_PASSWORD*
|The password for the keystore and certificate.

|*DB_USERNAME*
|Database user name.

|*DB_PASSWORD*
|Database user password

|*DB_MIN_POOL_SIZE*
|Sets xa-pool/min-pool-size for the configured datasource.

|*DB_MAX_POOL_SIZE*
|Sets xa-pool/max-pool-size for the configured datasource.

|*DB_TX_ISOLATION*
|Sets transaction-isolation for the configured datasource.

|*POSTGRESQL_MAX_CONNECTIONS*
|The maximum number of client connections allowed. This also sets the maximum number of prepared transactions.

|*POSTGRESQL_SHARED_BUFFERS*
|Configures how much memory is dedicated to PostgreSQL for caching data.

|*MQ_USERNAME*
|User name for standard broker user. It is required for connecting to the broker. If left empty, it will be generated.

|*MQ_PASSWORD*
|Password for standard broker user. It is required for connecting to the broker. If left empty, it will be generated.

|*AMQ_ADMIN_USERNAME*
|User name for broker admin. If left empty, it will be generated.

|*AMQ_ADMIN_PASSWORD*
|Password for broker admin. If left empty, it will be generated.

|*GITHUB_WEBHOOK_SECRET*
|GitHub trigger secret.

|*GENERIC_WEBHOOK_SECRET*
|Generic build trigger secret.

|*IMAGE_STREAM_NAMESPACE*
|Namespace in which the ImageStreams for Red Hat Middleware images are installed. These ImageStreams are normally installed in the openshift namespace. You should only need to modify this if you've installed the ImageStreams in a different namespace/project.
|===

= Logging
In addition to viewing the OpenShift logs, you can troubleshoot a running
{xpaasproduct-shortname} by viewing the logs that are outputted to the container's
console:

[subs="verbatim,macros"]
----
$ oc logs -f <pass:quotes[_pod-name_]>
----

[[ds-endpoints]]
= Endpoints

Clients can access {xpaasproduct-shortname} via multiple endpoints; by default the provided templates include support for REST, HornetQ, and ActiveMQ.

[[ds-rest]]
== REST

Clients can use the https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.3/html/Development_Guide/index.html#realtime_decision_server[REST API] in various ways:

[[ds-browser]]
=== Browser

. Current server state: \http://host/kie-server/services/rest/server
. List of containers: \http://host/kie-server/services/rest/server/containers
. Specific container state: \http://host/kie-server/services/rest/server/containers/processserver-library

[[ds-java]]
=== Java

[source,java]
----
// LibraryClient.java
KieServicesConfiguration config = KieServicesFactory.newRestConfiguration(
  "http://host/kie-server/services/rest/server", "kieserverUser", "kieserverPassword");
config.setMarshallingFormat(MarshallingFormat.XSTREAM);
ProcessServicesClient client =
  KieServicesFactory.newKieServicesClient(config).getServicesClient(ProcessServicesClient.class);
Map<String,Object> params = new HashMap<String,Object>();
LoanRequest loanRequest = new LoanRequest();
loanRequest.setIsbn("978-0-307-35193-7");
params.put("loanRequest", loanRequest);
Long processInstanceId = client.startProcess("processserver-library", "LibraryProcess", params);
----


[[ds-jms]]
== JMS

Client can also use the Java Messaging Service, as demonstrated below:

[[ds-java-hornetq]]
=== Java (HornetQ)

[source,java]
----
// LibraryClient.java
Properties props = new Properties();
props.setProperty(Context.INITIAL_CONTEXT_FACTORY,
  "org.jboss.naming.remote.client.InitialContextFactory");
props.setProperty(Context.PROVIDER_URL, "remote://host:4447");
props.setProperty(Context.SECURITY_PRINCIPAL, "kieserverUser");
props.setProperty(Context.SECURITY_CREDENTIALS, "kieserverPassword");
InitialContext context = new InitialContext(props);
KieServicesConfiguration config =
  KieServicesFactory.newJMSConfiguration(context, "hornetqUser", "hornetqPassword");
config.setMarshallingFormat(MarshallingFormat.XSTREAM);
ProcessServicesClient client =
  KieServicesFactory.newKieServicesClient(config).getServicesClient(ProcessServicesClient.class);
Map<String,Object> params = new HashMap<String,Object>();
LoanRequest loanRequest = new LoanRequest();
loanRequest.setIsbn("978-0-307-35193-7");
params.put("loanRequest", loanRequest);
Long processInstanceId = client.startProcess("processserver-library", "LibraryProcess", params);
----

[[ds-java-activemq]]
=== Java (ActiveMQ)

[source,java]
----
// LibraryClient.java
props.setProperty(Context.INITIAL_CONTEXT_FACTORY,
  "org.apache.activemq.jndi.ActiveMQInitialContextFactory");
props.setProperty(Context.PROVIDER_URL, "tcp://host:61616");
props.setProperty(Context.SECURITY_PRINCIPAL, "kieserverUser");
props.setProperty(Context.SECURITY_CREDENTIALS, "kieserverPassword");
InitialContext context = new InitialContext(props);
ConnectionFactory connectionFactory = (ConnectionFactory)context.lookup("ConnectionFactory");
Queue requestQueue = (Queue)context.lookup("dynamicQueues/queue/KIE.SERVER.REQUEST");
Queue responseQueue = (Queue)context.lookup("dynamicQueues/queue/KIE.SERVER.RESPONSE");
KieServicesConfiguration config = KieServicesFactory.newJMSConfiguration(
  connectionFactory, requestQueue, responseQueue, "activemqUser", "activemqPassword");
config.setMarshallingFormat(MarshallingFormat.XSTREAM);
ProcessServicesClient client =
  KieServicesFactory.newKieServicesClient(config).getServicesClient(ProcessServicesClient.class);
Map<String,Object> params = new HashMap<String,Object>();
LoanRequest loanRequest = new LoanRequest();
loanRequest.setIsbn("978-0-307-35193-7");
params.put("loanRequest", loanRequest);
Long processInstanceId = client.startProcess("processserver-library", "LibraryProcess", params);
----

[[ds-troubleshooting]]
= Troubleshooting

In addition to viewing the OpenShift logs, you can troubleshoot a running {xpaasproduct-shortname} container by viewing its logs. These are outputted to the container's standard out, and are accessible with the following command:

----
$ oc logs -f <pod_name>
----

[NOTE]
By default, {xpaasproduct-shortname} does not have a file log handler configured. Logs are only sent to the container's standard out.

