// IMPORTANT: For 1.10 and later, save each version release notes as its own module file in the release-notes folder that this `ReleaseNotesKogito<version>.adoc` file is in, and then include each version release notes file in the chap-kogito-release-notes.adoc after Additional resources of {PRODUCT} deployment on {OPENSHIFT} section, in the following format:
//include::release-notes/ReleaseNotesKogito<version>.adoc[leveloffset=+1]

[id="ref-kogito-rn-new-features-1.14_{context}"]
= New features in {PRODUCT} 1.14

[role="_abstract"]
The following sections describe some of the new features or enhancements in {PRODUCT} 1.14.

== {PRODUCT} runtimes

=== Quarkus Dev Service for {PRODUCT} Data Index Service

The {PRODUCT} Process Quarkus extension, can now automatically provision the Data Index Service when running the Quarkus application on Development mode. Once you start your Quarkus project on development mode, an in-memory instance of the Data Index service starts in the background.

The {PRODUCT} Process Quarkus extension sets up your Quarkus application to automatically replicate any {PRODUCT} messaging events into the provisioned Data Index instance. When the service is running, you can query the GraphQL interface directly from your application using `http://localhost:8180/graphql` or use the Quarkus Dev UI console `http://localhost:8080/q/dev/`.

For more information, see {URL_CONFIGURING_KOGITO}#con-data-index-dev-service_kogito-configuring[_Quarkus Dev Service for {PRODUCT} Data Index Service_].

== {PRODUCT} Operator and CLI

=== Improved/new bla bla

Description

== {PRODUCT} supporting services

=== Improved/new bla bla

Description

== {PRODUCT} tooling

=== Improved/new bla bla

Description
