[[_wb.configuration]]
= Configuration

[[_wb.usermanagement]]
== Basic user management


The workbench authenticates its users against the application server's authentication and authorization (JAAS).

On JBoss EAP and WildFly, add a user with the script `$JBOSS_HOME/bin/add-user.sh` (or ``$$.$$bat``):

[source]
----
$ ./add-user.sh
// Type: Application User
// Realm: empty (defaults to ApplicationRealm)
// Role: admin
----


There is no need to restart the application server.

[[_wb.roles]]
== Roles


The Workbench uses the following roles:

* admin
* analyst
* developer
* manager
* user


=== Admin


Administrates the BPMS system.

* Manages users
* Manages VFS Repositories
* Has full access to make any changes necessary


=== Developer


Developer can do almost everything admin can do, except clone repositories.

* Manages rules, models, process flows, forms and dashboards
* Manages the asset repository
* Can create, build and deploy projects
* Can use the JBDS connection to view processes


=== Analyst


Analyst is a weaker version of developer and does not have access to the asset repository or the ability to deploy projects.

=== Business user


Daily user of the system to take actions on business tasks that are required for the processes to continue forward.
Works primarily with the task lists.

* Does process management
* Handles tasks and dashboards


=== Manager/Viewer-only User


Viewer of the system that is interested in statistics around the business processes and their performance, business indicators, and other reporting of the system and people who interact with the system.

* Only has access to dashboards
