[id='integration-kafka-con_{context}']
= Kafka messages in a business process

ifdef::JBPM,DROOLS,OP[]
Apache Kafka
endif::JBPM,DROOLS,OP[]
ifdef::PAM,DM[]
{KAFKA_PRODUCT}, based on Apache Kafka,
endif::PAM,DM[]
is a streaming platform. It acts as a message broker, passing messages, which are sorted into topics, between applications in a software environment.

You can create business processes using {PRODUCT} that send and receive Kafka messages in the following ways:

* Create a start event, intermediate catch event, or boundary event (attached to a human task) of the type `message`. The {KIE_SERVER} automatically subscribes to the Kafka topic that is defined in the message. A message triggers the event. The event node acts as the consumer of the message and can pass the content of the message to the subsequent node in the process.

* Create an end event or intermediate throw event of the type 'message'. When the process triggers the event, the {KIE_SERVER} sends a Kafka message in the topic that is defined in the message. The message contains the data that is configured in the event. The event node acts as the producer of the message.

* Add the `KafkaPublishMessages` custom task to the process. This task does not require the {KIE_SERVER} Kafka capability but can be more complicated to configure than message events. 

* Configure your service and the {KIE_SERVER} to emit Kafka messages about every completed process, case, and task when transactions are committed.

