[id='kieserver-kafka-customformat-proc_{context}']
= Configuring the use a custom message format

By default, when using message events, the {PROCESS_ENGINE} sends and receives messages in a format compliant with the https://github.com/cloudevents/spec[CloudEvents specification] version 1.0.

Optionally, you can configure the use of a raw JSON data format or a custom format for the messages. If you want to use a custom format, you need to implement and provide classes.

.Prerequisites

* Your project uses message events to send or receive messages.

.Procedure

. If you want to use a custom format for sending or receiving messages, implement and provide custom classes:
.. Develop the source code for the classes:
*** To send messages, develop a class that implements the `KafkaEventWriter` interface
*** To receive messages, develop a class that implements the `KafkaEventReader` interface
+
You can download the interface definitons from the https://github.com/kiegroup/droolsjbpm-integration/tree/{COMMUNITY_VERSION_FINAL}/kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka
+
.. Provide the classes to your business application. For instructions, see xref:custom-class-provide-proc_{context}[].
. Set the following {KIE_SERVER} system properties to set the custom writer or reader:
** `org.kie.server.jbpm-kafka.ext.eventWriterClass`: the custom event writer class. Set this property to use a different format to send messages. If you want to use a custom format, set the property to the fully qualified name of your custom event writer class. If you want to use a raw JSON data format, set the property to `org.kie.server.services.jbpm.kafka.RawJsonEventWriter`.
** `org.kie.server.jbpm-kafka.ext.eventReaderClass`: the custom event reader class. Set this property to use a different format to receive messages. If you want to use a custom format, set the property to the fully qualified name of your custom event reader class. If you want to use a raw JSON data format, set the property to `org.kie.server.services.jbpm.kafka.RawJsonEventReader`.
