[id='kieserver-kafka-emit-proc_{context}']
= Configuring a service and the {KIE_SERVER} to emit Kafka messages when a transaction is committed

You can configure the {KIE_SERVER} to emit Kafka messages about every event when a process, case, or task is completed. The {KIE_SERVER} sends the messages when it commits transactions. 

You can use this functionality with any business process or case. You do not need to change anything in the process design.

This configuration is also available if you run your process service using SpringBoot.

By default, the {KIE_SERVER} publishes the messages in the following topics:

* `jbpm-processes-events` for messages about completed processes
* `jbpm-tasks-events` for messages about completed tasks
* `jbpm-cases-events` for messages about completed cases

You can configure the topic names. 

The published messages comply with the https://github.com/cloudevents/spec[CloudEvents specification] version 1.0. Each message contains the following fields:

* `id`: The unique identifier of the event
* `type`: The type of the event (process, task, or case)
* `source`: The event source as a URI
* `time`: The timestamp of the event, by default in the https://tools.ietf.org/html/rfc3339[RFC3339] format
* `data`: Information about the process, case, or task, presented in a JSON format

.Procedure

. To enable emitting Kafka messages, complete one of the following steps:
.. If you deployed the {KIE_SERVER} on {EAP} or another application server: 
ifdef::PAM,DM[]
... Download the `{PRODUCT_FILE}-maven-repository.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.
... Extract the contents of the file.
... Copy the `maven-repository/org/jbpm/jbpm-event-emitters-kafka/{MAVEN_ARTIFACT_VERSION}/jbpm-event-emitters-kafka-{MAVEN_ARTIFACT_VERSION}.jar` file into the `deployments/kie-server.war/WEB-INF/lib` subdirectory of the application server.
endif::PAM,DM[]
ifdef::JBPM,DROOLS,OP[]
... Retrieve the `org.jbpm.jbpm-event-emitters-kafka` JAR file version `{MAVEN_ARTIFACT_VERSION}` from the public Maven repository.
... Copy the file into the `deployments/kie-server.war/WEB-INF/lib` subdirectory of the application server.
endif::JBPM,DROOLS,OP[]
+
.. If you deployed the application using SpringBoot, add the following lines to the `<dependencies>` list in the `pom.xml` file of your service: 
+
[source,xml]
----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-event-emitters-kafka</artifactId>
  <version>${version.org.kie}</version>
</dependency>
----
+
. Configure any of the following system properties for the {KIE_SERVER} as necessary:
* `org.kie.jbpm.event.emitters.kafka.boopstrap.servers`: The host and port of the Kafka broker. The default value is `localhost:9092`. You can use a comma-separated list of multiple host:port pairs.
* `org.kie.jbpm.event.emitters.kafka.date_format`: The timestamp format for the `time` field of the messages. The default value is `yyyy-MM-dd'T'HH:mm:ss.SSSZ` .
* `org.kie.jbpm.event.emitters.kafka.topic.processes`: The topic name for process event messages. The default value is `jbpm-processes-events`. 
* `org.kie.jbpm.event.emitters.kafka.topic.cases`: The topic name for process event messages. The default value is `jbpm-cases-events`. 
* `org.kie.jbpm.event.emitters.kafka.topic.tasks`: The topic name for process event messages. The default value is `jbpm-processes-tasks`. 
* `org.kie.jbpm.event.emitters.kafka.client.id`: An identifier string to pass to the server when making requests. The server uses this string for logging.
