[id='message-receive-event-proc_{context}']
= Creating an event that receives Kafka messages

When designing your business process in {CENTRAL}, you can create an event that receives Kafka messages.

This event is triggered each time a message arrives in the configured topic. The message is expected to contain data that matches a predefined data object. The {PROCESS_ENGINE} parses the message and provides it as an output of the event.

.Procedure

. Open the project that contains your business process in {CENTRAL}.
. Create a data object defining the data that the message will contain. For instructions about creating data objects, see
ifdef::PAM,DM[]
{URL_DEVELOPING_PROCESS_SERVICES}#assembly-designing-business-processes[_{DESIGNING_BUSINESS_PROCESSES}_].
endif::PAM,DM[]
ifdef::JBPM,DROOLS,OP[]
xref:jBPMBPMN2[].
endif::JBPM,DROOLS,OP[]
. Select the business process and open the business process designer.
. Add a start event, an intermediate catch event, or a boundary event (attached to a human task) of the type `message`.
. Open the properties of the event.
. In the *Message* field, select *New* and then enter the name of the message. This name must be the same as the name of the topic from which the event is to receive Kafka messages, or else must be defined in an `org.kie.server.jbpm-kafka.ext.topics._broker-topic-name_` {KIE_SERVER} system property.
+
For instructions about using `org.kie.server.jbpm-kafka.ext.topics.*` system properties to define topic names, see xref:kieserver-kafka-proc_{context}[].
+
. Add an output data item. Select the data object that you created as its type.
. Save the business process.

.Next steps

To enable {KAFKA_PRODUCT} integration when running the process, you must configure {KIE_SERVER} according to instructions in xref:kieserver-kafka-proc_{context}[].
