[id='assembly_integrating-entando']

include::_artifacts/document-attributes.adoc[]

= {INTEGRATING_ENTANDO}
// Context attribute is assembly specific and enables module reuse between assemblies.
:doctype: book
:imagesdir: _images
:context: integrating-with-entando
include::_artifacts/author-group.adoc[]

// Purpose statement for the assembly
As a business processes developer, you can integrate the business assets you have created in {PRODUCT} with AppBuilder. AppBuilder provides an open-source, low-code Digital Experience Platform (DXP) for building modern web, mobile, and IoT applications. With AppBuilder, you can create a custom user experience around your {PRODUCT} business assets and expand your application development strategy.

.Prerequisites
* {PRODUCT} {PRODUCT_VERSION} is installed. For installation options, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].
* A project with business assets has been created in {PRODUCT} and deployed to a {KIE_SERVER}. For instructions, see {URL_PACKAGING_DEPLOYING_PROJECT}[_{PACKAGING_DEPLOYING_PROJECT}_].
* One or more {KIE_SERVERS} are running and contain deployed project data. For instructions, see {URL_PACKAGING_DEPLOYING_PROJECT}[_{PACKAGING_DEPLOYING_PROJECT}_].

// Modules - concepts, procedures, refs, etc.
include::{enterprise-dir}/integration/entando-con.adoc[leveloffset=+1]

include::{enterprise-dir}/integration/entando-integrating-con.adoc[leveloffset=+1]

////
== Next steps
Customizing UI components in AppBuilder
//@link: Doc link not yet available from AppBuilder.
////

// Versioning info
include::_artifacts/versioning-information.adoc[]
