[id='optashift-ER-building-commandline-proc']
= Building and running the employee rostering starter application from the command line
You can use the command line to build the employee rostering starter application and run it.

.Prerequisites
. A Java Development Kit must be installed.
. Maven must be installed.
. A JBoss EAP or WildFly application server must be installed.
. The host must have access to the Internet (for downloading Maven packages from external repositories).

.Procedure
. Enter the `sources` directory.
. Run the following command:
+
[source,bash]
----
mvn clean install
----
+
. Wait for the build process to complete.
. Change to the `optashift-employee-rostering-webapp/target` subdirectory.
. Copy the `optashift-employee-rostering-webapp-7.5.0.Final-redhat-4.war` file into the `<JBOSS_home>/standalone/deployments` directory, where `<JBOSS_home>` is the home directory of the JBoss EAP or WildFly application server.
. Change to the `<JBOSS_home>/standalone/deployments` directory.
. Rename the `optashift-employee-rostering-webapp-7.5.0.Final-redhat-4.war` file to `roster.war`, then create the `roster.war.dodeploy` file: 
+
[source,bash]
----
mv optashift-employee-rostering-webapp-7.5.0.Final-redhat-4.war roster.war
touch roster.war.dodeploy
----
+
. Change to the `<JBOSS_home>/bin` directory and run the `standalone.sh` file.
. Wait for the application server to start.
. Access the application at http://localhost:8080/gwtui/gwtui.html
