[id='optimizer-maven-configuration-proc']
= Setting up {PLANNER} with Maven, Gradle, Ivy, or Buildr

Use the following procedure to use {PLANNER} with Maven, and similarly if you use Gradle, Ivy, or Buildr:

.Prerequisite

Get the {PLANNER} JARs at the https://maven.repository.redhat.com/ga/optaplanner[Red Hat JBoss Maven Repository].

.Procedure
. Identify the latest version by checking the https://maven.repository.redhat.com/ga/optaplanner[Red Hat JBoss Maven Repository].
. Add a dependency to `optaplanner-core` in your project's `pom.xml` :
+

[source,xml]
----

  <dependency>
      <groupId>org.optaplanner</groupId>
      <artifactId>optaplanner-core</artifactId>
      <version>...</version>
  </dependency>
----

[float]
== Ant (without Ivy)

Use the following procedure if you are using Ant (without Ivy):

.Procedure
. Copy all of the JARs from the downloaded ZIP's `binaries` directory.
. Manually verify that your classpath does not contain duplicate JARs.
+
[NOTE]
====
The downloaded ZIP's `binaries` directory contains far more JARs then `optaplanner-core` actually uses.
It also contains the JARs used by other modules, such as `optaplanner-benchmark`.

Check the Maven repository `pom.xml` files to determine the minimal dependency set for a specific version of a specific module.
====
