[id='optmizer-rest-api-execution-server-dm-commands-ref']
= {PRODUCT_DM} commands

[POST] /containers/instances/_CONTAINER_ID_::
+
--
Request Type::
A single `org.kie.api.command.Command` command or multiples commands in `BatchExecutionCommand` wrapper.

Response Type::
`org.kie.server.api.model.ServiceResponse<String>`

Description::
Executes the commands sent to the specified `_CONTAINER_ID_` and returns the commands execution results. For more information, see the supported commands below.
--

List of supported commands:

* `AgendaGroupSetFocusCommand`
* `ClearActivationGroupCommand`
* `ClearAgendaCommand`
* `ClearAgendaGroupCommand`
* `ClearRuleFlowGroupCommand`
* `DeleteCommand`
* `InsertObjectCommand`
* `ModifyCommand`
* `GetObjectCommand`
* `InsertElementsCommand`
* `FireAllRulesCommand`
* `QueryCommand`
* `SetGlobalCommand`
* `GetGlobalCommand`
* `GetObjectsCommand`
* `BatchExecutionCommand`
* `DisposeCommand`

For more information about the commands, see the `org.drools.core.command.runtime` package.

.[POST] Drools Commands Execution

. Change into a directory of your choice and create `commandsRequest.json` :
+
[source,javascript]
----
{
      "lookup" : null,
      "commands" : [ {
        "insert" : {
          "object" : "testing",
          "disconnected" : false,
          "out-identifier" : null,
          "return-object" : true,
          "entry-point" : "DEFAULT"
        }

      }, {
        "fire-all-rules" : { }
      } ]
    }
----
. Execute the following command:
+
[source]
----
$ curl -X POST -H 'X-KIE-ContentType: JSON' -H 'Content-type: application/json' -u 'kieserver:kieserver1!' --data @commandsRequest.json http://localhost:8080/kie-server/services/rest/server/containers/instances/myContainer
----
+
The command generates a request that sends the Insert Object and Fire All Rules commands to the server. `Lookup` specifies a ksession configured in your kjar.
If you use a null lookup value, the default KIE session will be used.

An example response:
[source,javascript]
----
    {
      "type" : "SUCCESS",
      "msg" : "Container hello successfully called.",
      "result" : "{\n  \"results\" : [ ],\n  \"facts\" : [ ]\n}"
    }
----

