[id='optimizer-download-proc']
= Download {PLANNER}

{PLANNER} is production ready, and can be used to optimize business solutions in {CENTRAL}, in your preferred IDE, or on OpenShift.

.Prerequisite
The {PRODUCT} has been downloaded and installed from the https://access.redhat.com[Red Hat Customer Portal]. See Installing Decision Manager for more information about installing {PRODUCT}.
//@doc-link:Add link to Installation assembly above. 

.Procedure
. Download and install {PRODUCT} from the https://access.redhat.com[Red Hat Customer Portal]. See the _Getting started with decision services_ for more information about installing {PRODUCT}.
. Download the {PLANNER} from the https://access.redhat.com[Red Hat Customer Portal].
. Extract the {PLANNER} files to access the complete set of {PLANNER} engine JAR files. 
. xref:optimizer-running-the-examples-proc[Run the examples].

{PLANNER} is production ready.
The API is stable, however, backward incompatible changes can occur.


////
[float]
== Upgrading from previous versions

You can upgrade to a newer version and quickly deal with any backwards incompatibility changes using the https://www.optaplanner.org/download/upgradeRecipe/[UpgradeFromPreviousVersionRecipe.txt].

This recipe file is included in every release.
////
