[id='building-custom-dashboard-widgets-executing-heatmap-component-proc_{context}']

= Executing a heatmap component

You can execute the internal heatmap components locally, outside of {CENTRAL} for testing purpose only. The same API is used to create external components, which you can use to build your own components.
For more information about external components, see <<building-custom-dashboard-widgets-external-components-con_{context}>>

To run the specific heatmap component, complete the following steps:

.Prerequisites

* You have installed npm on your system. For more information about installing npm, see https://docs.npmjs.com/downloading-and-installing-node-js-and-npm[Downloading and installing Node.js and npm].
* You have installed Yarn on your system. For more information about installing Yarn, See https://classic.yarnpkg.com/en/docs/install/#debian-stable[Yarn Installation].
* You have cloned the https://github.com/kiegroup/appformer/[Appformer repository] to run the components outside of {CENTRAL}.

.Procedure

. Go to the `appformer/dashbuilder/dashbuilder-shared/dashbuilder-js` directory.
. Open the terminal in the `dashbuilder-js` directory and enter the following command:
+
[source]
----
yarn run init && yarn run build:fast
----
+
You can see the following components are present in the `dashbuilder-js/packages` directory:

* processes-heatmaps-component
* process-heatmap-component
* logo-component
* heatmap-component

. Go to the `dashbuilder-js/packages` directory, open the desired heatmap component and enter the following command in the terminal:
+
[source]
----
yarn run start
----
. To access the component, enter http://localhost:9001/ in a web browser.
+
The selected component is displayed on the web browser.
