[id='proc_drl-rules-actions_{context}']
= Adding actions in DRL rules

The `then` part of the rule contains the actions to be performed when the conditional part of the rule has been met. For example, when a loan applicant is under 21 years old, the `then` action of an `"Underage"` rule would be `setApproved( false )`, declining the loan because the applicant is under age. Actions consist of one or more methods that execute consequences based on the rule conditions and on available data objects in the package. The main purpose of rule actions is to to insert, delete, or modify data in the working memory of the {DECISION_ENGINE}.

.Prerequisites
* The `package` location and the `import` list of data objects required in the rule are defined at the top of the DRL file.
* The `rule` name is defined in the format `rule "name"` below the `package`, `import`, and other lines that apply to the entire DRL file. The same rule name cannot be used more than once in the same package. Optional rule attributes (such as `salience` or `no-loop`) that define rule behavior are below the rule name, before the `when` section.

.Procedure
. In the DRL file, enter `then` after the `when` section of the rule to begin adding action statements.
. Enter one or more actions to be executed on fact patterns based on the conditions for the rule.
+
The following are some of the keyword options for defining DRL actions:
+
* `set`: Use this to set the value of a field.
+
[source]
----
$application.setApproved ( false );
$application.setExplanation( "has been bankrupt" );
----
+
* `modify`: Use this to specify fields to be modified for a fact and to notify the {DECISION_ENGINE} of the change. This method provides a structured approach to fact updates. It combines the `update` operation with setter calls to change object fields.
+
[source]
----
modify( LoanApplication ) {
        setAmount( 100 ),
        setApproved ( true )
}
----
+
* `update`: Use this to specify fields and the entire related fact to be updated and to notify the {DECISION_ENGINE} of the change. After a fact has changed, you must call `update` before changing another fact that might be affected by the updated values. To avoid this added step, use the `modify` method instead.
+
[source]
----
LoanApplication.setAmount( 100 );
update( LoanApplication );
----
+
* `insert`: Use this to insert a `new` fact into the {DECISION_ENGINE}.
+
[source]
----
insert( new Applicant() );
----
+
* `insertLogical`: Use this to insert a `new` fact logically into the {DECISION_ENGINE}. The {DECISION_ENGINE} is responsible for logical decisions on insertions and retractions of facts. After regular or stated insertions, facts must be retracted explicitly. After logical insertions, the facts that were inserted are automatically retracted when the conditions in the rules that inserted the facts are no longer true.
+
[source]
----
insertLogical( new Applicant() );
----
+
* `delete`: Use this to remove an object from the {DECISION_ENGINE}. The keyword `retract` is also supported in DRL and executes the same action, but `delete` is typically preferred in DRL code for consistency with the keyword `insert`.
+
[source]
----
delete( Applicant );
----

+
NOTE: For more information about DRL rule actions, see xref:con_drl-rules-actions_drl-rules[].

. After you define all action components of the rule, save the DRL file.
