:sectnums!:

[appendix]
[id='_appe_additional_notes']
= Additional Notes

* The Oracle WebLogic Server class-loading mechanism does not provide access to the application JARs located in you application's `WEB-INF/lib` directory, which can cause problems when looking to inject KIE-CDI classes. As a workaround, {PRODUCT} includes a CDI extension that temporarily swaps class loaders to load the application: `org.kie.workbench.backend.weblogic.SwapClassloaderExtension`.
+
--
.Enabling CDI Extension workaround
* Get the extension's class file either by using the pre-compiled `SwapClassloaderExtension.class` file found in {CENTRAL}'s `business-central.war/WEB-INF/classes/org/kie/workbench/backend/weblogic/` subdirectory, or by downloading and compiling its https://github.com/droolsjbpm/kie-wb-common/blob/500f4ab3315f6d1a62f9d20ff0f72372361644b1/kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-backend/src/main/java/org/kie/workbench/screens/workbench/backend/weblogic/SwapClassloaderExtension.java[source]. Put the file in your application's `/WEB-INF/classes/org/kie/workbench/backend/weblogic/` directory.
* Enable the extension by putting its fully qualified name in the `WEB-INF/classes/META-INF/services/javax.enterprise.inject.spi.Extension` file in your application. If the file does not exist, create it.
+
.Contents of javax.enterprise.inject.spi.Extension
----
org.kie.workbench.backend.weblogic.SwapClassloaderExtension
----

NOTE: When using {CENTRAL}, these steps are not necessary--the workaround has already been applied.
--
* If using a non-exploded archive, Weblogic packs contents of {CENTRAL}'s `WEB-INF/classes` into `WEB-INF/lib/_wl_cls_gen.jar`. If a developer aims to create `KieBase` and `KieSession` from resources, KIE-Spring cannot find the classes. For this reason, the recommended deployment method is to use the exploded archives contained within the product's ZIP file.

:sectnums:
