[id='_chap_install']
= Install

Now that the basic configuration is done, the Oracle WebLogic Server is set to deploy {PRODUCT}.

As noted earlier, the {PRODUCT} ZIP file for Oracle WebLogic Server contains the deployable WAR files for
ifdef::BA[]
Business Central, {KIE_SERVER}, and Dashbuilder.
endif::BA[]
ifdef::DM[]
both Business Central and {KIE_SERVER}.
endif::DM[]

== Installing Business Central

Business Central is uploaded as a web archive and then accessed by a familiar through a web browser. Start this deployment by installing the Business Central exploded WAR as a WebLogic Application.

. In your Oracle WebLogic Server administrative console, click *Deployments*. This will show you all the existing applications in the system and allow you to install a new one.
. Click *Install* to start the process.
. Navigate to the exploded archive location for `business-central.war` and select it. Click *Next* to continue.
. Select *Install this deployment as an application* as the targeting style and click *Next*.
. Set the application name to `business-central` and set the security model to `DD Only`. Leave the remaining options as default and click *Next* to continue.
. In the *Additional Configuration* section, choose *No, I will review the configuration later* and click *Finish*.
. To ensure correct functionality of process diagram visualization, copy `xercesImpl.jar` to the server libraries, which is in `/_DOMAIN_HOME_/lib/` by default.

You have now successfully installed Business Central on Oracle WebLogic Server. To access the application, navigate to `http://_TARGET_SERVER_:7001/business-central`.

ifdef::BA[]
[id='_install_dashbuilder']
== Installing Dashbuilder

Dashbuilder is distributed as a deployable WAR. Follow the steps below to install Dashbuilder:

. Navigate to *Deployments*. This will show you all the existing applications in the system and allow you to install a new one.
. Click *Install* to start the process.
. Navigate to the exploded archive location for `dashbuilder.war` and select it. Click *Next* to continue.
. Select *Install this deployment as an application* as the targeting style and click *Next*.
. Set the application name to `dashbuilder` and set the security model to `DD Only`. Leave the remaining options as default and click *Next* to continue.
. In the *Additional Configuration* section, choose *No, I will review the configuration later* and click *Finish*.

You can now login to dashbuilder at `http://_TARGET_SERVER_:7001/dashbuilder`. 
endif::BA[]

ifdef::BA[]
[id='_installing_intelligent_process_server']
== Installing {KIE_SERVER}

The {KIE_SERVER} is distributed as a deployable WAR. Follow the steps below to install the server:

. Navigate to *Deployments*. This will show you all the existing applications in the system and allow you to install a new one.
. Click *Install* to start the process.
. Navigate to the exploded archive location for `kie-execution-server.war` and select it. Click *Next* to continue.
. Select *Install this deployment as an application* as the targeting style and click *Next*.
. Set the application name to `kie-execution-server` and set the security model to `DD Only`. Leave the remaining options as default and click *Next* to continue.
. In the *Additional Configuration* section, choose *No, I will review the configuration later* and click *Finish*.
. To ensure correct functionality of UI extension, copy `xercesImpl.jar` to the server libraries, which is in `/_DOMAIN_HOME_/lib/` by default.

You can now access the {KIE_SERVER} at `http://_TARGET_SERVER_:7001/kie-server`.
endif::BA[]

ifdef::DM[]
[id='_installing_realtime_decision_server']
== Installing {KIE_SERVER}

The {KIE_SERVER} is distributed as a deployable WAR. Follow the steps below to install the server:

. Navigate to *Deployments*. This will show you all the existing applications in the system and allow you to install a new one.
. Click *Install* to start the process.
. Navigate to the exploded archive location for `kie-execution-server.war` and select it. Click *Next* to continue.
. Select *Install this deployment as an application* as the targeting style and click *Next*.
. Set the application name to `kie-execution-server` and set the security model to `DD Only`. Leave the remaining options as default and click *Next* to continue.
. In the *Additional Configuration* section, choose *No, I will review the configuration later* and click *Finish*.
. To ensure correct functionality of UI extension, copy `xercesImpl.jar` to the server libraries, which is in `/_DOMAIN_HOME_/lib/` by default.

You can now access the {KIE_SERVER} at `http://_TARGET_SERVER_:7001/kie-execution-server/services/rest/server`.
endif::DM[]
