[id='_chap_download_and_extract']
= Download and Extract
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

[id='_download_red_hat_jboss_bpm_suite_for_oracle_weblogic_server']
== Download {PRODUCT} for Oracle WebLogic Server

You can download the deployable {PRODUCT} package file for Oracle WebLogic Server from the Red Hat Customer Portal:

. Log in to the https://access.redhat.com[Red Hat Customer Portal].
. Click *DOWNLOADS* at the top of the page.
. On the *Product Downloads* page that opens, navigate to the JBOSS INTEGRATION AND AUTOMATION section, and click *{PRODUCT}*.
. On the *Software Downloads* page, if necessary select *Decision Manager* from the Product menu and *7.0* from the *Version* menu.
. Download the following product distributions:
* *{PRODUCT} {KIE_SERVER} for All Supported EE7 Containers* (`rhdm-7.0.0.GA-kie-server-ee7.zip`)
* *{PRODUCT} 7.0.0 Add Ons* (`rhdm-7.0.0.GA-add-ons.zip`) 
. Extract these files to a temporary directory. In the following examples, this directory is called `__TEMP_DIR__`.


