[id='_chap_download_and_extract']
= Download and Extract
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

[id='_download_red_hat_jboss_bpm_suite_for_oracle_weblogic_server']
== Download {PRODUCT} for Oracle WebLogic Server

You can download the deployable {PRODUCT} package file for Oracle WebLogic Server from Red Hat Customer Portal:

. Go to the https://access.redhat.com[Red Hat Customer Portal] and log in.
. Click *DOWNLOADS* at the top of the page.
. In the *Product Downloads* page that opens, click *{PRODUCT}*.
. From the *Version* drop-down menu, select *{PRODUCT_VERSION}*.
. On the  *Releases* tab, navigate to *{PRODUCT} {PRODUCT_VERSION}.0 Deployable for Oracle Weblogic 12c* and click *Download*.
. On the *Patches* tab, download the latest patch (if applicable).  

[id='_extract_red_hat_jboss_bpm_suite_for_oracle_weblogic_server']
== Extract {PRODUCT} for Oracle WebLogic Server

The installation ZIP file for {PRODUCT} that you have downloaded contains all necessary WAR deployable archives mentioned in <<_about_red_hat_jboss_bpm_suite_for_oracle_weblogic_server>>.

Copy the installation ZIP file to your WebLogic Server host and extract it to a location the server can access.

ifdef::BA[]
----
unzip ~/jboss-bpmsuite-VERSION-deployable-wls12c.zip
----
endif::BA[]
ifdef::DM[]
----
unzip ~/jboss-brms-VERSION-deployable-wls12c.zip
----
endif::DM[]

See the {URL_INSTALLATION_GUIDE}#chap_patching_and_upgrading_red_hat_jboss_bpm_suite[Patching and Upgrading {PRODUCT}] chapter from _{INSTALLATION_GUIDE}_ for instructions on applying the patch updates.
