[id='_chap_configure']
= Configure

[id='_setting_environment_variables']
== Setting Environment Variables

Certain environment variables on your Oracle WebLogic Server require configuration before deploying the application.

[float]
=== JVM Memory Size

With the default JVM memory size, the WebLogic Server freezes and/or causes deployment errors when deploying Business Central. Increase the memory size by setting the following environment variable:

----
USER_MEM_ARGS=-Xms512m -Xmx1024m -XX:MaxPermSize=512m
----

[float]
=== JVM Custom Properties

The following custom properties require configuration on the WebLogic Server:

*Properties Required for Business Central and {KIE_SERVER}*

* `org.kie.executor.jms.cf`: JNDI name of the connection factory for sending messages with job executor requests.

* `org.kie.executor.jms.queue`: JNDI name of the destination (queue) for sending messages with job executor requests.

*Properties Required for Business Central*

ifdef::BA[]
* `kie.services.jms.queues.response`:
JNDI name of the response queue for JMS remote API of Business Central. Set to `jms/KIE.RESPONSE.ALL`.
endif::BA[]

ifdef::DM[]
* `org.jbpm.designer.perspective=ruleflow`:
Changes the default perspective in the designer to `RuleFlow` instead of `Full`.
endif::DM[]

* `org.uberfire.start.method`:
Defines startable beans for Uberfire. Set to `ejb` (Enterprise Java Beans).

* `org.uberfire.domain`:
Sets the domain for Uberfire to use. Set to `OracleDefaultLoginConfiguration`.

* `com.sun.jersey.server.impl.cdi.lookupExtensionInBeanManager`:
Uses `BeanManager` to look up extensions. This avoids conflicts across multiple instances. Set to `true`.

*Properties Required for {KIE_SERVER}*

* `kie.server.jms.queues.response`:
JNDI name of the response queue for the {KIE_SERVER}.  Set to `jms/KIE.SERVER.RESPONSE`.

* `org.kie.server.domain`:
JAAS LoginContext domain used to authenticate users when using JMS. Set to `OracleDefaultLoginConfiguration`.

ifdef::BA[]
* `org.kie.server.persistence.ds`:
Datasource JNDI name.

* `org.kie.server.persistence.tm`:
Transaction manager platform for setting Hibernate properties. Set to `org.hibernate.service.jta.platform.internal.WeblogicJtaPlatform`.

* `org.kie.server.persistence.dialect`:
Specifies Hibernate dialect to be used.
endif::BA[]

For a full list of available {KIE_SERVER} system properties, see chapter {URL_ADMIN_GUIDE}#chap_the_realtime_decision_server[{KIE_SERVER}] of the
_{USER_GUIDE}_.

Set the following custom properties in a single environment variable:
ifdef::BA[]
----
JAVA_OPTIONS="-Dkie.services.jms.queues.response=jms/KIE.RESPONSE.ALL  -Dkie.server.jms.queues.response=jms/KIE.SERVER.RESPONSE  -Dorg.uberfire.start.method=ejb
 -Dorg.uberfire.domain=OracleDefaultLoginConfiguration
 -Dorg.kie.executor.jms.cf=jms/cf/KIE.EXECUTOR
 -Dorg.kie.executor.jms.queue=jms/KIE.EXECUTOR
 -Dorg.kie.server.persistence.ds=jdbc/jbpm
 -Dorg.kie.server.persistence.tm=org.hibernate.service.jta.platform.internal.WeblogicJtaPlatform
 -Dorg.kie.server.persistence.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
 -Dcom.sun.jersey.server.impl.cdi.lookupExtensionInBeanManager=true"
----
endif::BA[]
ifdef::DM[]
----
JAVA_OPTIONS="-Dkie.server.jms.queues.response=jms/KIE.SERVER.RESPONSE
 -Dorg.jbpm.designer.perspective=ruleflow
 -Dorg.uberfire.start.method=ejb
 -Dorg.uberfire.domain=OracleDefaultLoginConfiguration
 -Dorg.kie.executor.jms.cf=jms/cf/KIE.EXECUTOR
 -Dorg.kie.executor.jms.queue=jms/KIE.EXECUTOR
 -Dcom.sun.jersey.server.impl.cdi.lookupExtensionInBeanManager=true"
----
endif::DM[]

[id='_configuring_security_settings']
== Configuring Security Settings

Several security settings on Oracle WebLogic Server must be set for the Business Central application to work. The following settings enable the container managed authentication mechanisms provided by the WebLogic server:

. In the WebLogic administrative console, click *Security Realms*.
. Choose your desired security realm or click *New* to create a new security realm.
. Navigate to *Users and Groups* -> *Groups* to get to the groups list for your security realm.

ifdef::BA[]
. Click *New* to create a new group. Create the following new groups: `admin`, `analyst`, `developer`, `manager`, `user`, and `kie-server`. Also create the REST API groups if you will use API. For further information about API roles, see section {URL_DEVELOPMENT_GUIDE}#sect_rest_api[REST API] of _{DEVELOPMENT_GUIDE}_.
endif::BA[]
ifdef::DM[]
. Click *New* to create a new group. Create the following three new groups: `admin`, `analyst`, and `kie-server`. Also create the REST API groups if you will use API. For further information about API roles, see section {URL_DEVELOPMENT_GUIDE}#sect_rest_api[REST API] of _{DEVELOPMENT_GUIDE}_.
endif::DM[]

. Click on the *Users* tab and click *New* to create a new user. Provide this new user with a name (for example `business-central-admin`) and a password. Click *OK* to save.

+
[IMPORTANT]
====
Make sure that the selected user name does _not_ conflict with any known title of a role or a group.

For example, if there is a role called `admin`, you should _not_ create a user with the user name `admin`.
====

. Click on the newly created user, then click the *Groups* tab. Use the selection tool to move the `admin` group from the *Available* field to the *Chosen* field. Click *Save* to save.

NOTE: You may assign this user to any of the groups previously created and in actual production systems you are likely to create separate users for separate groups that align with business roles. The admin group is all encompassing and is therefore useful for the purposes of this setup.

[id='_creating_a_data_source']
== Creating Data Source

The Business Central application requires a data source which must be created prior to the deployment of the actual WAR file. This also means that you must have access to an underlying database that the data source connects to. Whatever your underlying database, make sure you have the data source ready.

. Navigate to *Services* -> *Data Sources*, which takes you to your JDBC Data Sources list.
. Click *New* -> *Generic Data Source* to start creating a new data source.
. Provide your data source with the following details:
* *Name*: enter a name for your data source.
* *JNDI Name*: set to `jdbc/jbpm`.
* *Database Type*: set to `MySQL`.

+
[NOTE]
====
You can use alternative database types by editing `WEB-INF/classes/META-INF/persistence.xml` in the Business Central WAR archive. Edit the `hibernate.dialect` property to your preferred database.

For example, to change to Oracle 12c, edit the `hibernate.dialect` to the following:

----
<property name="hibernate.dialect" value="org.hibernate.dialect.Oracle10gDialect" />
----
====

+
Click *Next* to advance to the next configuration screen.

. Select your database driver in the drop-down menu. Click *Next* to advance to the next configuration screen.
. Leave the *Transaction Options* as the defaults and click *Next* to advance to the next configuration screen.
. Provide the following *Connection Properties* for your data source:
+
  * *Database Name*: the name of the database to use on your data source.
  * *Host Name*: the hostname or IP address of the system containing the database.
  * *Port*: the port used to connect to the database. Unless you have configured the database to use a different port, use the default port provided in this field.
  * *Database User Name*: the database user that interacts with the database. Make sure the chosen user has the required permissions to access and write to the chosen database.
  * *Password*: the password for the chosen database user.
+
Click *Next* to advance to the next configuration screen.

. The *Test Database Connection* page provides a means to test and confirm your database connection. Click *Test Configuration* and the page will refresh with a valid connection message. Click *Finish* to complete the data source configuration.
. Click on the name of the new data source and navigate to *Targets* tab. Click the checkbox for the server chosen to host the Business Central deployment. Click *Save* to save your selection.

ifdef::BA[]

[IMPORTANT]
====
Dashbuilder requires the same JNDI as Business Central so that it connects to the same datasource. The default JNDI for Dashbuilder `jdbc/dashbuilder` must be changed to `jdbc/jbpm`.

Log in to your WebLogic server, switch to the `dashbuilder.war` directory, and edit the `WEB-INF/etc/hibernate.cfg.xml` file. Find the following line:

----
<property name="connection.datasource">jdbc/dashbuilder</property>
----

Change it to:

----
<property name="connection.datasource">jdbc/jbpm</property>
----

Save the file when complete.
====
endif::BA[]

[id='_configuring_java_message_service_jms']
== Configuring Java Message Service (JMS)

Oracle WebLogic Server must be configured to send and receive JMS messages through {PRODUCT} {KIE_SERVER}.
ifdef::BA[]
JMS must also be configured for Business Central.
endif::BA[]
This requires a JMS server. Follow the steps below to create a JMS server:

. Navigate to *Services* -> *Messaging* -> *JMS Servers*.
. Click *New* to start creating a new JMS Server.
. Provide your JMS Server with a name. Click *Next* to advance to the next configuration screen.
. Select the *Target* server chosen for the Business Central deployment. Click *Finish* to complete the JMS Server creation.

[float]
=== Create JMS Module

A JMS Module stores your JMS resources, such as connection factories and queues. Use the following steps to create a new JMS Module:

. Navigate to *Services* -> *Messaging* -> *JMS Modules*.
. Click *New* to start creating a new module.
. Provide your module with a name and click *Next* to advance to the next configuration screen.
ifdef::BA[]
. Select the *Target* server chosen for the {KIE_SERVER} and Business Central deployment. Click *Finish* to complete the JMS Module creation.
endif::BA[]
ifdef::DM[]
. Select the *Target* server chosen for the {KIE_SERVER} deployment. Click *Finish* to complete the JMS Module creation.
endif::DM[]
. Click on the newly created module's name, then click on *Subdeployments*.
. Click *New* to create a subdeployment for your module.
. Provide your subdeployment with a name and click *Next* to advance to the next configuration screen.
. Choose the previously created JMS Server by marking the checkbox. Click *Finish* to complete the subdeployment configuration.

[float]
=== Create JMS Connection Factories

To send and receive messages from {PRODUCT} {KIE_SERVER} , you will need to create the JMS connection factories &ndash; one for receiving messages and one for sending them.
ifdef::BA[]
You will also need to create several other connection factories for Business Central.
endif::BA[]
The following connection factories are required:

ifdef::BA[]
* `KIE.RESPONSE.ALL`: receiving all responses produced by the Red Hat JBoss BPM Suite.
+
Default value: `jms/cf/KIE.RESPONSE.ALL`.
endif::BA[]

ifdef::BA[]
* `KIE.SESSION`: sending messages to the process engine.
+
Default value: `jms/cf/KIE.SESSION`.
endif::BA[]

ifdef::BA[]
* `KIE.TASK`: sending messages to the task service.
+
Default value: `jms/cf/KIE.TASK`.
endif::BA[]

ifdef::BA[]
* `KIE.AUDIT`: sending messages with audit trail.
+
Default value: `jms/cf/KIE.AUDIT`.
endif::BA[]

ifdef::BA[]
* `KIE.SIGNAL`: sending messages with external scoped signals.
+
Default value: `jms/cf/KIE.SIGNAL`.
endif::BA[]

* `KIE.SERVER.REQUEST`: for all requests to the {KIE_SERVER}.
+
Default value: `jms/cf/KIE.SERVER.REQUEST`.

* `KIE.SERVER.RESPONSE`: receiving all responses produced by the {KIE_SERVER}.
+
Default value: `jms/cf/KIE.SERVER.RESPONSE`.

* `KIE.EXECUTOR`: sending executor requests for jobs running in Business Central.
+
Default value: `jms/cf/KIE.EXECUTOR`.

ifdef::DM[]
* `KIE.SERVER.EXECUTOR`: sending executor requests for jobs running on the {KIE_SERVER}.
+
Default value: `jms/cf/KIE.SERVER.EXECUTOR`.
endif::DM[]


Use the following procedure to create each connection factory:

. Navigate to *Services* -> *Messaging* -> *JMS Modules* to see your list of JMS Modules.
. Click on your previously created module, then click *New* to start creating a new JMS resource.
. Select *Connection Factory* and click *Next*.
. Enter the name of the connection factory (for example
ifdef::BA[]
`KIE.RESPONSE.ALL`)
endif::BA[]
ifdef::DM[]
`KIE.SERVER.REQUEST`)
endif::DM[]
and the JNDI name (for example
ifdef::BA[]
`jms/cf/KIE.RESPONSE.ALL`).
endif::BA[]
ifdef::DM[]
`jms/cf/KIE.SERVER.REQUEST`).
endif::DM[]

+
Click *Next* to advance to the next configuration screen.

. The connection factory automatically selects the servers assigned to the JMS Module as the default. Click *Finish* to complete the connection factory creation.

Repeat the above procedure for each connection factory.

[float]
=== Create JMS Queues

You now need to create the JMS Queues. These queues are the destination end points for point-to-point messaging. You will create:

ifdef::BA[]
* `KIE.RESPONSE.ALL`: for Red Hat JBoss BPM Suite responses.
+
Default value: `jms/KIE.RESPONSE.ALL`.
endif::BA[]

ifdef::BA[]
* `KIE.SESSION`: for process-based operations.
+
Default value: `jms/KIE.SESSION`.
endif::BA[]

ifdef::BA[]
* `KIE.TASK`: for task-based operations.
+
Default value: `jms/KIE.TASK`.
endif::BA[]

ifdef::BA[]
* `KIE.AUDIT`: for asynchronous audit logs.
+
Default value: `jms/KIE.AUDIT`.
endif::BA[]

ifdef::BA[]
* `KIE.SIGNAL`: for external scoped signals.
+
Default value: `jms/KIE.SIGNAL`.
endif::BA[]

* `KIE.SERVER.REQUEST`: for all requests to the {KIE_SERVER}.
+
Default value: `jms/KIE.SERVER.REQUEST`.
* `KIE.SERVER.RESPONSE`: for the {KIE_SERVER} responses.
+
Default value: `jms/KIE.SERVER.RESPONSE`.

* `KIE.EXECUTOR`: sending executor requests for jobs running in Business Central.
+
Default value: `jms/KIE.EXECUTOR`.

ifdef::DM[]
* `KIE.SERVER.EXECUTOR`: sending executor requests for jobs running on the {KIE_SERVER}.
+
Default value: `jms/KIE.SERVER.EXECUTOR`.
endif::DM[]

Use the following procedure to create each queue:

. If you are not there already, navigate to *Services* -> *Messaging* -> *JMS Modules* to see your list of JMS Modules.
. Click on your previously created module, then click *New* to start creating a new JMS resource.
. Select *Queue* and click *Next*.
. Enter the name of the queue (for example
ifdef::BA[]
`KIE.RESPONSE.ALL`)
endif::BA[]
ifdef::DM[]
`KIE.SERVER.REQUEST`)
endif::DM[]
and the JNDI name (for example
ifdef::BA[]
`jms/KIE.RESPONSE.ALL`).
endif::BA[]
ifdef::DM[]
`jms/KIE.SERVER.REQUEST`).
endif::DM[]
+
Click *Next* to advance to the next configuration screen.

. Choose the JMS Module subdeployment that connects to the JMS Server. Click *Finish* to complete the queue creation.

Repeat the above procedure for each queue.

ifdef::BA[]
== Configuring Unified Execution Servers

To configure Business Central to manage the {KIE_SERVER} and use the same data source, follow the instructions in the {URL_ADMIN_GUIDE}#unified_execution_servers[Unified Execution Servers] section of the _{ADMIN_GUIDE}_.
endif::BA[]
