[id='_chap_install']
= Install

Now that the basic configuration is done, the Oracle WebLogic Server is set to deploy {PRODUCT}.

As noted earlier, the {PRODUCT} ZIP file for Oracle WebLogic Server contains the deployable WAR files for
ifdef::BA[]
{CENTRAL}, {KIE_SERVER}, and Dashbuilder.
endif::BA[]
ifdef::DM[]
both {CENTRAL} and {KIE_SERVER}.
endif::DM[]


ifdef::BA[]
[id='_install_dashbuilder']
== Installing Dashbuilder

Dashbuilder is distributed as a deployable WAR. Follow the steps below to install Dashbuilder:

. Navigate to *Deployments*. This will show you all the existing applications in the system and allow you to install a new one.
. Click *Install* to start the process.
. Navigate to the exploded archive location for `dashbuilder.war` and select it. Click *Next* to continue.
. Select *Install this deployment as an application* as the targeting style and click *Next*.
. Set the application name to `dashbuilder` and set the security model to `DD Only`. Leave the remaining options as default and click *Next* to continue.
. In the *Additional Configuration* section, choose *No, I will review the configuration later* and click *Finish*.

You can now login to dashbuilder at `http://_TARGET_SERVER_:7001/dashbuilder`. 
endif::BA[]

ifdef::BA[]
[id='_installing_intelligent_process_server']
== Installing {KIE_SERVER}

{KIE_SERVER} is distributed as a deployable WAR. Follow the steps below to install the server:

. Navigate to *Deployments*. This will show you all the existing applications in the system and allow you to install a new one.
. Click *Install* to start the process.
. Navigate to the exploded archive location for `kie-server.war` and select it. Click *Next* to continue.
. Select *Install this deployment as an application* as the targeting style and click *Next*.
. Set the application name to `kie-server` and set the security model to `DD Only`. Leave the remaining options as default and click *Next* to continue.
. In the *Additional Configuration* section, choose *No, I will review the configuration later* and click *Finish*.

You can now access the {KIE_SERVER} at `http://_TARGET_SERVER_:7001/kie-server`.
endif::BA[]

ifdef::DM[]
[id='_installing_realtime_decision_server']
== Installing {KIE_SERVER}

The {KIE_SERVER} is distributed as a deployable WAR. Follow the steps below to install the server:

. Navigate to *Deployments*. This will show you all the existing applications in the system and allow you to install a new one.
. Click *Install* to start the process.
. Navigate to the exploded archive location for `kie-server.war` and select it. Click *Next* to continue.
. Select *Install this deployment as an application* as the targeting style and click *Next*.
. Set the application name to `kie-server` and set the security model to `DD Only`. Leave the remaining options as default and click *Next* to continue.
. In the *Additional Configuration* section, choose *No, I will review the configuration later* and click *Finish*.

You can now access the {KIE_SERVER} at `http://_TARGET_SERVER_:7001/kie-execution-server/services/rest/server`.
endif::DM[]
