[id='controller-wls-install-proc']
= Installing and running the headless Process Automation Manager controller with {WEBLOGIC}

To use the {KIE_SERVER} REST API or Java Client API to interact with {KIE_SERVER}, install the headless Process Automation Manager controller with {WEBLOGIC}. The headless Process Automation Manager controller manages {KIE_SERVER} configuration in a centralized way so that you can use the controller to create and maintain containers and perform other server-level tasks.

.Prerequisites
* The {WEBLOGIC} instance is configured as described in xref:wls-configure-proc[].
* {KIE_SERVER} is installed on the {WEBLOGIC} instance.
* You have sufficient user permissions to complete the installation.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons*.
. Extract the downloaded `{PRODUCT_FILE}-add-ons.zip` file to a temporary directory.
. In the WebLogic Administration Console, navigate to *Security Realms* -> *Users and Groups*.
. In the *kie-server* group that you created previously, create a user for the controller, such as `controller`, and a password for this new user and click *OK*. For more information about creating groups and users, see xref:wls-users-set-proc[].
. Navigate to *Deployments* to view all existing applications.
. Click *Install*.
. Navigate to the temporary directory where you downloaded and extracted the `{PRODUCT_FILE}-add-ons.zip` file, and go to `{PRODUCT_FILE}-add-ons/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7.zip/controller.war`.
. Select the `controller.war` file and click *Next* to continue.
. Select *Install this deployment as an application* as the targeting style and click *Next*.
. Keep the application name as `controller` and set the security model to `DD Only`. Leave the remaining options as default and click *Next* to continue.
. In the *Additional Configuration* section, choose *No, I will review the configuration later* and click *Finish*.
