[id='controller-wls-was-environment-set-proc_{context}']
= Setting system properties for the headless Process Automation Manager controller

After you install the headless Process Automation Manager controller, set the system properties listed in this section on your application server or servers to enable proper interaction with the headless Process Automation Manager controller.

[NOTE]
====
For optimal results, install {KIE_SERVER} and the headless Process Automation Manager controller on different servers in production environments. In development environments, you can install {KIE_SERVER} and the headless Process Automation Manager controller on the same server. In either case, be sure to make these property changes on all application servers where the controller is installed.
====

.Prerequisite
{KIE_SERVER} and the headless Process Automation Manager controller are installed on the application server instance.

.Procedure
. Specify the following JVM property values on the application server instance where the controller is installed:
+
[cols="40,60", options="header"]
.Required properties for the headless Process Automation Manager controller
|===
|Name
|Requirement

|`org.kie.server.user`
|A user with the `kie-server` role

|`org.kie.server.pwd`
|The password for the user specified in the `org.kie.server.user` property
|===

. Specify the following JVM property values on the application server instance where {KIE_SERVER} is installed:
+
--
[cols="40,60", options="header"]
.Required properties for {KIE_SERVER} when controller is installed
|===
|Name
|Requirement

|`org.kie.server.controller.user`
|A user with the `kie-server` role

|`org.kie.server.controller.pwd`
|The password for the user specified for the `org.kie.server.controller.user` property

|`org.kie.server.id`
|The ID or name of the {KIE_SERVER} installation, such as `rhdm700-decision-server-1`

|`org.kie.server.location`
|The URL of the {KIE_SERVER}, `http://<HOST>:<PORT>/kie-server/services/rest/server`

|`org.kie.server.controller`
|The URL of the headless Process Automation Manager controller, `http://<HOST>:<PORT>/controller/rest/controller`
|===

`<HOST>` is the ID or name of the {KIE_SERVER} host, for example, `localhost` or `192.7.8.9`.

`<PORT>` is the port of the {KIE_SERVER} host, for example, `7001`.
--
