[id='controller-wls-ev-set-proc']
= Setting environment variables for the standalone {KIE_SERVER} Controller

Set the environment variables listed in this section.

.Prerequisites
* {KIE_SERVER} is installed on an {WEBLOGIC} instance.
* The {KIE_SERVER} Controller is installed on an {WEBLOGIC} instance.
+
[NOTE]
====
Red Hat recommends that you install {KIE_SERVER} and the standalone {KIE_SERVER} Controller on different servers in production environments. However, if you install {KIE_SERVER} and the standalone {KIE_SERVER} Controller on the same server, for example in a development environment, make these changes on the same {WEBLOGIC} instance.
====
* You have `kie-server` user role on {KIE_SERVER} nodes.
* You have `kie-server` user role on {KIE_SERVER} Controller nodes.

.Procedure
. Specify the following JVM property values on the {WEBLOGIC} instance where the Controller is installed:
+
* `org.kie.server.user`: A user with the `kie-server` role.
* `org.kie.server.pwd`: The password for the user specified in the `org.kie.server.user` property.

. Specify the following JVM property values on the {WEBLOGIC} instance where {KIE_SERVER} is installed:
+
* `org.kie.server.controller.user`:
A user with the `kie-server` role
* `org.kie.server.controller.pwd`:
The password for the user specified for the `org.kie.server.controller.user` property
* `org.kie.server.id`:  The ID or name of the {KIE_SERVER} installation, for example, `rhdm700-decision-server-1`
* `org.kie.server.location`: `http://<HOST>:<PORT>/kie-server/services/rest/server`
* `org.kie.server.controller`: The URL of the standalone Decision Server Controller, for example `http://<HOST>:<PORT>/controller/rest/controller`
+
In the preceding examples:
* `<HOST>` is the ID or name of the {KIE_SERVER} host, for example, `localhost` or `192.7.8.9`.
* `<PORT>` is the port of the Decision Server host, for example, `7001`.
