[id='wls-jms-queues-create-proc']
= Create JMS queues

JMS queues are the destination end points for point-to-point messaging. You must create certain JMS queues to enable JMS messaging with {KIE_SERVER}
ifdef::BA[]
and {CENTRAL}
endif::BA[]
.

.Prerequisites
* You have created a xref:wls-jms-create-proc[JMS server].
* You have created a xref:wls-jms-create-module-proc[JMS module].

.Procedure
. In the WebLogic Administration Console, navigate to *Services* -> *Messaging* -> *JMS Modules* to see the list of JMS modules.
. Select your previously created module, then click *New* to create a new JMS resource.
. Select *Queue* and click *Next*.
. For each of the following required queues, enter the name of the queue (for example, `KIE.SERVER.REQUEST`) and the JNDI name (for example, `jms/KIE.SERVER.REQUEST`)
and then click *Next*.
. Choose the JMS module subdeployment that connects to the JMS server.
. Click *Finish* to add the queue, and repeat for each required factory.
+
The following are the required queues:

* `KIE.SERVER.REQUEST`: for all requests to the {KIE_SERVER}.
+
Default value: `jms/KIE.SERVER.REQUEST`.
* `KIE.SERVER.RESPONSE`: for the {KIE_SERVER} responses.
+
Default value: `jms/KIE.SERVER.RESPONSE`.
ifdef::BA[]
* `KIE.RESPONSE.ALL`: for Red Hat JBoss BPM Suite responses.
+
Default value: `jms/KIE.RESPONSE.ALL`.
* `KIE.SESSION`: for process-based operations.
+
Default value: `jms/KIE.SESSION`.
* `KIE.TASK`: for task-based operations.
+
Default value: `jms/KIE.TASK`.
* `KIE.AUDIT`: for asynchronous audit logs.
+
Default value: `jms/KIE.AUDIT`.
* `KIE.SIGNAL`: for external scoped signals.
+
Default value: `jms/KIE.SIGNAL`.
endif::BA[]
