[id='wls-jms-factory-create-proc']
= Create JMS connection factories

To enable messaging with {KIE_SERVER}
ifdef::BA[]
and with {CENTRAL}
endif::BA[]
, you must create certain JMS connection factories for sending and receiving messages.

.Prerequisites
* You have created a xref:wls-jms-create-proc[JMS server].
* You have created a xref:wls-jms-create-module-proc[JMS module].

.Procedure
. In the WebLogic Administration Console, navigate to *Services* -> *Messaging* -> *JMS Modules* to see a list of JMS modules.
. Select your previously created module and click *New* to create a new JMS resource.
. Select *Connection Factory* and click *Next*.
. For each of the following required connection factories, enter the name of the connection factory (for example, `KIE.SERVER.REQUEST`) and the JNDI name (for example, `jms/cf/KIE.SERVER.REQUEST`) and click *Next*. The connection factory automatically selects the servers assigned to the JMS Module as the default.
. Click *Finish* to add the connection factory, and repeat for each required factory.
+
The following are the required connection factories:

* `KIE.SERVER.REQUEST`: For all requests to {KIE_SERVER}
+
Default value: `jms/cf/KIE.SERVER.REQUEST`

* `KIE.SERVER.RESPONSE`: For receiving all responses produced by {KIE_SERVER}
+
Default value: `jms/cf/KIE.SERVER.RESPONSE`
ifdef::BA[]
* `KIE.RESPONSE.ALL`: For receiving all responses produced by {PRODUCT}
+
Default value: `jms/cf/KIE.RESPONSE.ALL`
* `KIE.SESSION`: For sending messages to the {ENGINE}
+
Default value: `jms/cf/KIE.SESSION`
* `KIE.TASK`: For sending messages to the task service
+
Default value: `jms/cf/KIE.TASK`
* `KIE.AUDIT`: For sending messages with audit trail
+
Default value: `jms/cf/KIE.AUDIT`
* `KIE.SIGNAL`: For sending messages with external scoped signals
+
Default value: `jms/cf/KIE.SIGNAL`
endif::BA[]
