// IMPORTANT: For 1.10 and later, save each version release notes as its own module file in the release-notes folder that this `ReleaseNotesKogito<version>.adoc` file is in, and then include each version release notes file in the chap-kogito-release-notes.adoc after Additional resources of {PRODUCT} deployment on {OPENSHIFT} section, in the following format:
//include::ReleaseNotesKogito.<version>/ReleaseNotesKogito.<version>.adoc[leveloffset=+1]

[id="ref-kogito-rn-new-features-1.25_{context}"]
= New features in {PRODUCT} 1.25

[role="_abstract"]
The following sections describe some of the new features or enhancements in {PRODUCT} 1.25.

== {PRODUCT} runtimes

=== Introduce HTTP code for Error Handling on {PRODUCT} Serverless Workflows

Added support for handling errors using HTTP codes in Serverless Workflow, for full details, visit https://kiegroup.github.io/kogito-docs/serverlessworkflow/main/core/understanding-workflow-error-handling.html[Error handling in Serverless Workflow].

=== {PRODUCT} Serverless Workflow codestart for Quarkus

The {PRODUCT} Serverless Workflow codestart for Quarkus will allow new projects using the `kogito-quarkus-serverless-workflow` extension to include a basic Serverless Workflow sample file and integration test as a starting point instead of an empty project.

=== {PRODUCT} Serverless Workflow gRPC enhacements

Improved support of gRCP in {PRODUCT} Serverless Workflow, which now follows https://developers.google.com/protocol-buffers/docs/proto3#json[JSON Mapping].

=== {PRODUCT} memory leak fixes when using BusinesRuleTask

Memory has been fixed in this release that affects {PRODUCT} processes using business rules. For more details, visit https://issues.redhat.com/browse/KOGITO-7569[KOGITO-7569]

////

== {PRODUCT} Operator and CLI

=== Improved/new bla bla

Description

== {PRODUCT} supporting services

=== Improved/new bla bla

Description

== {PRODUCT} tooling

=== Improved/new bla bla

Description
////
