
= Building from source

== Getting the sources

The source code of each Maven artifact is available in the JBoss Maven repository as a source JAR.
The same source JARs are also included in the download zips.
However, if you want to build from source, it's highly recommended to get our sources from our source control.

Drools and jBPM use http://git-scm.com/[Git] for source control.
The blessed git repositories are hosted on https://github.com[GitHub]:

* https://github.com/kiegroup

Git allows you to fork our code, independently make personal changes on it, yet still merge in our latest changes regularly and optionally share your changes with us.
To learn more about git, read the free book http://progit.org/book/[Git Pro].

== Building the sources

In essense, building from source is very easy, for example if you want to build the [term]_guvnor_
 project:

[source,shell]
----
$ git clone git@github.com:kiegroup/guvnor.git
...
$ cd guvnor
$ mvn clean install -DskipTests -Dfull
...
----

However, __there are a lot potential pitfalls__, so if you're serious about building from source 
and possibly contributing to the project, *follow the instructions 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/README.md[in the README file in droolsjbpm-build-bootstrap].*
