[id="proc-dmn-bpmn-maven-create_{context}"]
= Creating and executing DMN and BPMN models using Maven

You can use the {PRODUCT} VSCode extension in VSCode to create Maven archetypes to develop DMN and BPMN models instead of developing your models in {CENTRAL}. You can then integrate your archetypes with your {PRODUCT} decision and process services in {CENTRAL} as needed. This method of developing DMN and BPMN models is helpful for building new business applications using the {PRODUCT} VSCode extension.

.Procedure
. In a command terminal, navigate to the local folder where you want to store the new {PRODUCT} project.
. Enter the following command to use a Maven archtype to generate a {PRODUCT} project within a defined folder:
+
[source,subs="attributes+"]
----
mvn archetype:generate \
    -DarchetypeGroupId=org.kie \
    -DarchetypeArtifactId=kie-kjar-archetype \
    -DarchetypeVersion={MAVEN_ARTIFACT_VERSION}
----
+
This command generates a Maven project with required dependencies and generates required directories and files to build your business application. You can use the Git version control system (recommended) when developing a project.
+
If you want to generate multiple projects in the same directory, specify the `artifactId` and `groupId` of the generated business application by adding `-DgroupId=<groupid> -DartifactId=<artifactId>` to the previous command.

. In your VSCode IDE, click *File*, select *Open Folder*, and navigate to the folder that was generated using the previous command.
+
. Before creating the first asset, set a package for your business application, for example, `org.kie.businessapp`, and create respective directories in the following paths:
+
* `PROJECT_HOME/src/main/java`
* `PROJECT_HOME/src/main/resources`
* `PROJECT_HOME/src/test/resources`

+
For example, you can create `PROJECT_HOME/src/main/java/org/kie/businessapp` for the `org.kie.businessapp` package.

. Use VSCode to create assets for your business application. You can create the assets supported by {PRODUCT} VSCode extension using the following ways:
+
* To create a business process, create a new file with `.bpmn` or `.bpmn2` in `PROJECT_HOME/src/main/resources/org/kie/businessapp` directory, such as `Process.bpmn`.
* To create a DMN model, create a new file with `.dmn` in `PROJECT_HOME/src/main/resources/org/kie/businessapp` directory, such as `AgeDecision.dmn`.
* To create a test scenario simulation model, create a new file with `.scesim` in `PROJECT_HOME/src/test/resources/org/kie/businessapp` directory, such as `TestAgeScenario.scesim`.

. After you create the assets in your Maven archetype, use the command line to navigate to the root directory of your project (the directory that contains the `pom.xml` file) and run the following command to build the knowledge JAR (KJAR) file for your project:
+
[source]
----
mvn clean install
----
+
The KJAR file appears in the `PROJECT_HOME/target` directory.
+
NOTE: If the build fails, address any problems described in the command line error messages and run `mvn clean install` again. Use the `mvn clean install` command to validate your project after each major development change.

To deploy the KJAR file on a running {KIE_SERVER}, use the REST API. For more information about using the REST API, see {URL_DEPLOYING_AND_MANAGING_SERVICES}#assembly-kie-apis[_{KIE_APIS}_].
