[id='con-kogito-operator-with-data-index-service_{context}']
= {PRODUCT} Operator interaction with the {PRODUCT} Data Index Service

{PRODUCT} provides a Data Index Service that stores all {PRODUCT} events related to processes, tasks, and domain data. The Data Index Service uses Apache Kafka messaging to consume https://cloudevents.io/[CloudEvents] messages from {PRODUCT} services, and then indexes the returned data for future GraphQL queries and stores the data in the Infinispan persistence store. The Data Index Service is at the core of all {PRODUCT} search, insight, and management capabilities.

You can use the following {PRODUCT} command-line interface (CLI) operation to install the {PRODUCT} Data Index Service for data management in {PRODUCT} services:

.Enable Data Index Service
[source,subs="attributes+,+quotes"]
----
$ {PRODUCT_INIT} install data-index --infra __INFINISPAN_INFRA_NAME__ --infra __KAFKA_INFRA_NAME__ -p __PROJECT_NAME__
----

Instead of using the default Infinispan-based persistence in the {PRODUCT} Data Index Service, you can use the following command to configure the Data Index Service to use https://www.mongodb.com/[MongoDB] persistence storage if needed. A https://www.mongodb.com/try/download[MongoDB Server] 3.6 or later must already be installed, configured, and running. For information about MongoDB installation and configuration, see the https://docs.mongodb.com/manual/installation/[MongoDB documentation].

.Enable Data Index Service with MongoDB connection information
[source,subs="attributes+,+quotes"]
----
$ {PRODUCT_INIT} install data-index --infra __KAFKA_INFRA_NAME__ \
    --image quay.io/kiegroup/kogito-data-index-mongodb:latest \
    --config quarkus.mongodb.connection-string=__MONGODB_SERVER_CONNECTION_STRING__ \
    --config quarkus.mongodb.database=__DATABASE_NAME__ \
    --config quarkus.mongodb.credentials.username=__USER_NAME__ \
    --config quarkus.mongodb.credentials.password=__PASSWORD__ \
    -p __PROJECT_NAME__
----

When you enable the Data Index Service for your {PRODUCT} project, the {PRODUCT} Operator creates a `KogitoDataIndex` custom resource to handle the Data Index Service deployment for you. This resource is added to your {PRODUCT} project and in the {PRODUCT} Operator page of the *Installed Operators* listed in the OpenShift web console, if applicable.

If an Infinispan Server instance and an Apache Kafka cluster are not installed in the OpenShift namespace, you must configure these infrastructure components before installing the Data Index Service:

.Enable Infinispan persistence
[source,subs="attributes+,+quotes"]
----
$ {PRODUCT_INIT} install infra __INFINISPAN_INFRA_NAME__ --kind Infinispan --apiVersion infinispan.org/v1 -p __PROJECT_NAME__
----

.Enable Kafka messaging
[source,subs="attributes+,+quotes"]
----
$ {PRODUCT_INIT} install infra __KAFKA_INFRA_NAME__ --kind Kafka --apiVersion kafka.strimzi.io/v1beta1 -p __PROJECT_NAME__
----

.Additional resources
ifdef::KOGITO[]
* {URL_CONFIGURING_KOGITO}#con-data-index-service_kogito-configuring[{PRODUCT} Data Index Service]
endif::[]
ifdef::KOGITO-COMM[]
* xref:con-data-index-service_kogito-configuring[]
endif::[]

== {PRODUCT} Data Index Service properties configuration

When the {PRODUCT} Data Index Service is deployed, a `configMap` resource is created for the `application.properties` configuration of the Data Index Service.

The name of the `configMap` resource consists of the name of the Data Index Service and the suffix `-properties`, as shown in the following example:

.Example `configMap` resource generated during {PRODUCT} Data Index Service deployment
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: data-index-properties
data:
  application.properties : |-
    property1=value1
    property2=value2
----

The `application.properties` data of the `configMap` resource is mounted in a volume to the container of the Data Index Service. Any runtime properties that you add to the `application.properties` section override the default application configuration properties of the Data Index Service.

When the `application.properties` data of the `configMap` is changed, a rolling update modifies the deployment and configuration of the Data Index Service.

If your {PRODUCT} project uses the `infinispan-persistence-addon` add-on to enable Infinispan persistence explicitly, the {PRODUCT} Operator mounts a volume based on a `configMap` resource created for you during the deployment of the service. This `configMap` resource has the `-protobuf-files` suffix and lists the protobuf (https://developers.google.com/protocol-buffers/[protocol buffers]) files that your service generated during build time.

.Example `configMap` resource with protobuf files listed
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-quarkus-protobuf-files
  labels:
    kogito-protobuf: true
data:
  visaApplications.proto: |-
    syntax = "proto2";
    package org.acme.travels.visaApplications;
    import "kogito-index.proto";
    import "kogito-types.proto";
    option kogito_model = "VisaApplications";
    option kogito_id = "visaApplications";
    ...
----

When a new persistent {PRODUCT} service is deployed, a new set of protobuf files is generated and the Data Index Service creates a new `pod` instance that refers to the new volume.

Updated protobuf files are automatically refreshed by Kubernetes volumes, so if you add a new
property in your domain data, this data is reflected automatically in the Data Index Service without restarts.

If a {PRODUCT} service is removed, the associated protobuf files are also removed and are no longer visible in the Data Index Service, but the data is still persisted in Infinispan.
