[id='con-kogito-operator-with-knative-eventing_{context}']
= {PRODUCT} Operator interaction with Knative Eventing

NOTE: Knative Eventing is currently supported for {PRODUCT} services on Quarkus only. Cretion of Knative objects requires Knative version 0.17.x or later due to its CRD versions used by {PRODUCT} operator.

{PRODUCT} provides a {URL_CONFIGURING_KOGITO}#proc-knative-eventing-process-services[`knative-eventing-addon`] add-on that enables Knative Eventing integration for {PRODUCT} services. The {PRODUCT} Operator uses the  https://knative.dev/docs/eventing/[Knative Eventing] platform to implement an event-driven architecture based on https://github.com/cloudevents/spec/blob/v1.0/spec.md[CloudEvents] with {PRODUCT} services. Due to this dependency, the Knative Eventing platform **must** be installed in the same cluster as your {PRODUCT} project.

When you deploy a {PRODUCT} service that uses the `knative-eventing-addon` add-on you must also deploy a https://knative.dev/docs/eventing/broker/[Knative Eventing Broker] in the same namespace. This broker will be used by the {PRODUCT} service to publish and/or listen to CloudEvents messages. The Broker's implementation won't matter for the {PRODUCT} service: can be used any one being Kafka, InMemory and so on. Here's an example of a default InMemory Broker:

.Example `Broker` resource for Knative Eventing
[source,yaml]
----
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
----

To bind this Knative Eventing Broker instance with the {PRODUCT} service being deployed, you must create a `KogitoInfra` instance, as shown in the example:

.Example `KogitoInfra` resource for {PRODUCT} service
[source,yaml]
----
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoInfra
metadata:
  name: kogito-knative-infra
spec:
  # bind Knative Broker with our own service
  resource:
    apiVersion: eventing.knative.dev/v1
    kind: Broker
    name: default
----

Notice the `spec.resource` field where we bind the deployed Knative Eventing Broker with the `KogitoInfra` resource.

The `KogitoRuntime` resource used to deploy the {PRODUCT} service using the {PRODUCT} operator must have this `KogitoInfra` instance linked to it, for example:


.Example `KogitoRuntime` resource for {PRODUCT} service with `KogitoInfra` bound to it
[source,yaml]
----
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: process-knative-quickstart-quarkus
spec:
  replicas: 1
  image: quay.io/<yournamespace>/process-knative-quickstart-quarkus:latest
  # we bind our application with Knative env
  infra:
  - kogito-knative-infra
----

When applying those resources to Kubernetes namespace, the {PRODUCT} Operator will automatically create the required Knative https://knative.dev/docs/eventing/triggers/[`Triggers`] and https://knative.dev/docs/eventing/samples/sinkbinding/[`SinkBindings`] to the linked Broker if the BPMN or Serverless Workflow files in your project have an event to be consumed (mapped to a `Trigger`) or produced (mapped to the `SinkBinding`).

To consume the events published by your application, just create a new Trigger targeting the just deployed Broker, for example:

.Example `Trigger` resource to consume {PRODUCT} service events
[source,yaml]
----
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display-trigger
spec:
  # the default broker has been enabled in the namespace
  broker: default
  filter:
    # we only listen to events of type success emitted by our ce-processing service
    attributes:
      # the exact same type being generated by our Kogito custom service
      type: process.<your process id>.<your message event id>
  # the subscriber is the deployed displayer service, any event that match the filter above in the broker will be sent to us
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
----

Notice the format of the `spec.filter.attributes.type`. This CloudEvent type is generated by the {PRODUCT} runtime and can be used to filter the messages generated by the deployed {PRODUCT} service.

.Additional resources
ifdef::KOGITO[]
* {URL_CONFIGURING_KOGITO}#proc-knative-eventing-process-services[Enabling Knative Eventing for {PRODUCT} services]
endif::[]
ifdef::KOGITO-COMM[]
* xref:proc-knative-eventing-process-services[]
endif::[]
* https://knative.dev/docs/eventing/[Knative Eventing]
