[id='con-kogito-operator-and-cli_{context}']
= {PRODUCT} Operator and CLI

To help you deploy your {PRODUCT} services on {OPENSHIFT}
ifdef::KOGITO-COMM[]
or Kubernetes
endif::[]
for cloud implementation, {PRODUCT} provides an operator and a command-line interface (CLI):

* *{PRODUCT} Operator*: An operator that guides you through the deployment process. The {PRODUCT} Operator is based on the https://sdk.operatorframework.io/[Operator SDK] and automates many of the deployment steps for you. For example, when you give the operator a link to the Git repository that contains your application, the operator can automatically configure the components required to build your project from source and deploy the resulting services.
* *{PRODUCT} command-line interface (CLI)*: A CLI tool that enables you to interact with the {PRODUCT} Operator for deployment tasks. The {PRODUCT} CLI also enables you to deploy {PRODUCT} services from source instead of relying on custom resources and YAML files. You can use the {PRODUCT} CLI as a command-line alternative for deploying {PRODUCT} services without the {OPENSHIFT} web console.

ifdef::KOGITO-COMM[]
For more information about the {PRODUCT} Operator and {PRODUCT} CLI and how to contribute, see the `README` file in the https://github.com/kiegroup/kogito-cloud-operator[`{PRODUCT_INIT}-cloud-operator`] repository in GitHub.
endif::[]
