[id='con-kogito-operator-with-infinispan_{context}']
= {PRODUCT} Operator interaction with Infinispan

You can use the following {PRODUCT} command-line interface (CLI) operation to install the Infinispan infrastructure for process data persistence in {PRODUCT} services:

.Enable Infinispan persistence
[source,subs="attributes+,+quotes"]
----
$ {PRODUCT_INIT} install infinispan -p __PROJECT_NAME__
----

When you install the Infinispan infrastructure for your {PRODUCT} project, the {PRODUCT} Operator creates a `KogitoInfra` custom resource to handle Infinispan deployment for you. This resource is added to your {PRODUCT} project and in the {PRODUCT} Operator page of the *Installed Operators* listed in the OpenShift web console, if applicable.

The `KogitoInfra` resource uses the https://github.com/infinispan/infinispan-operator[Infinispan Operator] to deploy new Infinispan Server instances when needed. Hence make sure that you have https://infinispan.org/infinispan-operator/master/operator.html[it installed] in the same namespace you deployed the custom {PRODUCT} service. 

You can edit and manage the Infinispan instance. The {PRODUCT} Operator *does not manage* Infinispan instances. For example, if you have plans to scale the Infinispan cluster, you can edit the `replicas` field in the https://github.com/infinispan/infinispan-operator/blob/master/pkg/apis/infinispan/v1/infinispan_types.go[`infinispan_types.go`] custom resource to meet your requirements.

By default, the `KogitoInfra` resource creates a secret that holds the user name and password for Infinispan authentication. To view the credentials, enter the following command:

.View {PRODUCT} Infinispan credentials
[source]
----
$ oc get secret/kogito-infinispan-credential -o yaml

apiVersion: v1
data:
  password: VzNCcW9DeXdpMVdXdlZJZQ==
  username: ZGV2ZWxvcGVy
kind: Secret
...
----

The key values are masked by a Base64 algorithm. To view the password from the previous example output in your terminal, enter the following command:

.Reveal {PRODUCT} Infinispan password
[source]
----
$ echo VzNCcW9DeXdpMVdXdlZJZQ== | base64 -d

W3BqoCywi1WWvVIe
----

== Infinispan persistence in {PRODUCT} services

After you install the Infinispan infrastructure, to enable Infinispan persistence for a {PRODUCT} service using the {PRODUCT} Operator, use the `--enable-persistence` flag during deployment in the {PRODUCT} CLI or edit the `spec.infinispan` configuration in the `KogitoRuntime` custom resource:

* `true`: Infinispan is installed in the namespace and the connection property environment variables are injected into the service.
* `false`: Infinispan is not installed. Use this option only if you do not need persistence or if you intend to deploy your own persistence mechanism and you know how to configure your service to access it.

.Example {PRODUCT} service deployment from local source with Infinispan persistence enabled
[source,subs="attributes+,+quotes"]
----
$ {PRODUCT_INIT} deploy-service travels --enable-persistence
----

.Example {PRODUCT} service custom resource with Infinispan persistence enabled
[source,yaml]
----
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: travels
spec:
  type: RemoteSource
  gitSource:
    uri: "https://github.com/kiegroup/kogito-examples/"
    contextDir: kogito-travel-agency/extended/travels
  envs:
    - name: MAVEN_ARGS_APPEND
      value: -Ppersistence
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: travels
spec:
  infinispan:
    useKogitoInfra: true
----

If your {PRODUCT} project uses the `infinispan-persistence-addon` add-on to enable Infinispan persistence explicitly, the {PRODUCT} Operator installs Infinispan and injects the connection properties as environment variables into the service, depending on the runtime.

The following table lists the injected environment variables for Quarkus and Spring Boot:

.Infinispan environment variables injected by the {PRODUCT} Operator
[cols="30%,30%,20%,25%" options="header"]
|===
|Quarkus environment variable
|Spring Boot environment variable
|Description
|Example value

|`QUARKUS_INFINISPAN_CLIENT_SERVER_LIST`
|`INFINISPAN_REMOTE_SERVER_LIST`
|Service URI from the deployed Infinispan instance
|`kogito-infinispan:11222`

|`QUARKUS_INFINISPAN_CLIENT_AUTH_USERNAME`
|`INFINISPAN_REMOTE_AUTH_USER_NAME`
|Default user name generated by the Infinispan Operator
|`developer`

|`QUARKUS_INFINISPAN_CLIENT_AUTH_PASSWORD`
|`INFINISPAN_REMOTE_AUTH_PASSWORD`
|Random password generated by the Infinispan Operator
|`Z1Nz34JpuVdzMQKi`

|`QUARKUS_INFINISPAN_CLIENT_SASL_MECHANISM`
|`INFINISPAN_REMOTE_SASL_MECHANISM`
|Defaults to `PLAIN`
|`PLAIN`
|===

Ensure that your {PRODUCT} service can read these properties in runtime. These variable names are the same as the names used by Infinispan clients from Quarkus and Spring Boot.

On Quarkus 1.1.0 ({PRODUCT} 0.6.0) or earlier, ensure that your `application.properties` contains the following properties:

.Required Infinispan properties on Quarkus 1.1.0 ({PRODUCT} 0.6.0) or earlier
[source]
----
quarkus.infinispan-client.server-list=
quarkus.infinispan-client.auth-username=
quarkus.infinispan-client.auth-password=
quarkus.infinispan-client.sasl-mechanism=
----

These properties are replaced with the environment variables by the {PRODUCT} Operator at runtime.

[NOTE]
.Infinispan persistence with the {PRODUCT} Data Index Service
====
For the {PRODUCT} Data Index Service, if you do not provide a service URL to connect to Infinispan, a new server is deployed automatically in the `KogitoInfra` custom resource. A random password for the `developer` user is created and injected into the Data Index Service automatically. You do not need to do anything for both services to work together.
====

.Additional resources
ifdef::KOGITO[]
* {URL_CONFIGURING_KOGITO}#con-persistence_kogito-configuring[Persistence in {PRODUCT}]
* {URL_CONFIGURING_KOGITO}#con-data-index-service_kogito-configuring[{PRODUCT} Data Index Service]
endif::[]
ifdef::KOGITO-COMM[]
* xref:con-persistence_kogito-configuring[]
* xref:con-data-index-service_kogito-configuring[]
endif::[]
* https://github.com/infinispan/infinispan-operator/blob/master/README.md[Infinispan Operator]
