[id='con-kogito-operator-with-trusty-service_{context}']
= {PRODUCT} Operator interaction with the {PRODUCT} Trusty Service

{PRODUCT} provides a Trusty Service that stores all {PRODUCT} tracing events related to decisions made in {PRODUCT} services. The Trusty Service uses Apache Kafka messaging to consume https://cloudevents.io/[CloudEvents] messages from {PRODUCT} services, and then processes the tracing events and stores the data in the Infinispan persistence store.

You can use the following {PRODUCT} command-line interface (CLI) operation to install the {PRODUCT} Trusty Service for auditing purposes in {PRODUCT} services:

.Enable Trusty Service
[source,subs="attributes+,+quotes"]
----
$ {PRODUCT_INIT} install trusty -p __PROJECT_NAME__
----

To export tracing events from your {PRODUCT} project, you must additionally add the `tracing-addon` add-on as a dependency to your project.

When you enable the Trusty Service for your {PRODUCT} project, the {PRODUCT} Operator creates a `KogitoTrusty` custom resource to handle the Trusty Service deployment for you. This resource is added to your {PRODUCT} project and in the {PRODUCT} Operator page of the *Installed Operators* listed in the OpenShift web console, if applicable.

The {PRODUCT} Operator depends on the https://github.com/infinispan/infinispan-operator[Infinispan Operator] for persistence infrastructure and on the https://strimzi.io/docs/latest/[Strimzi Operator] for Kafka messaging infrastructure. The {PRODUCT} Operator uses the Infinispan Operator to deploy new Infinispan Server instances when needed, and uses the Strimzi Operator to deploy a Kafka cluster with Zookeeper to support sending and receiving messages within a process. Due to these dependencies, these operators must be installed in the same namespace as the {PRODUCT} project. For information about Infinispan Operator installation, see the https://infinispan.org/infinispan-operator/master/operator.html[Infinispan Operator Guide]. For information about Strimzi Operator installation, see the https://strimzi.io/docs/operators/master/quickstart.html[Strimzi Quick Start guide].

If the {PRODUCT} Explainability Service is enabled, then the Trusty Service also stores the explainability results for all the tracing events.

.Additional resources
ifdef::KOGITO[]
* {URL_CONFIGURING_KOGITO}#con-trusty-service_kogito-configuring[{PRODUCT} Trusty Service and Explainability Service]
endif::[]
ifdef::KOGITO-COMM[]
* xref:con-trusty-service_kogito-configuring[]
endif::[]
