[id='proc-kogito-operator-and-cli-installing_{context}']
= Installing the {PRODUCT} Operator and CLI

The {PRODUCT} command-line interface (CLI) enables you to interact with the {PRODUCT} Operator for deployment tasks. After you install the {PRODUCT} CLI, the first time that you use the CLI to interact with a project or service, the {PRODUCT} Operator is automatically installed and used to execute the relevant tasks.

.Procedure
. Go to the https://github.com/kiegroup/kogito-cloud-operator/releases[`{PRODUCT_INIT}-cloud-operator`] releases page in GitHub and download the latest version of the `{PRODUCT_INIT}-cli-_RELEASE_` binary file that is specific to your operating system.
. Extract the `{PRODUCT_INIT}-cli-_RELEASE_` binary file to a local directory:
+
--
* On Linux or Mac: In a command terminal, navigate to the directory where you downloaded the `{PRODUCT_INIT}-cli-_RELEASE_` binary file and enter the following command to extract the contents:
+
.Extract the {PRODUCT} CLI distribution
[source,subs="attributes+,+quotes"]
----
tar -xvf {PRODUCT_INIT}-cli-_RELEASE_.tar.gz
----

* On Windows: In your file browser, navigate to the directory where you downloaded the `{PRODUCT_INIT}-cli-_RELEASE_` binary file and extract the ZIP file.

The `{PRODUCT_INIT}` executable file appears.
--
. Move the extracted `{PRODUCT_INIT}` file to an existing directory in your `PATH` variable:
+
--
* On Linux or Mac: In a command terminal, enter the following command:
+
.Move the `{PRODUCT_INIT}` file
[source,subs="attributes+,+quotes"]
----
cp /__PATH_TO_{PRODUCT_INIT_CAP}__ /usr/local/bin
----

* On Windows: Update the relevant `PATH` environment variables in your system settings to include the path to the {PRODUCT} CLI folder. For example, on Windows 10, go to *Settings* -> *System Info* -> *Advanced System Settings* -> *Advanced* -> *Environment Variables* and in the *User* or *System* variables, add the path for the {PRODUCT} CLI folder to the `PATH` variable. Close and reopen your Windows command prompt to apply the changes.
--

After you install the {PRODUCT} CLI, the first time that you use the CLI to interact with a project or service, such as `{PRODUCT_INIT} use-project __PROJECT_NAME__`, the {PRODUCT} Operator is automatically installed and used to execute the relevant tasks.

To install the {PRODUCT} Operator manually without using the {PRODUCT} CLI, you can use the OpenShift web console and go to *Operators* -> *OperatorHub* in the left menu, search for and select *Kogito*, and follow the on-screen instructions to install the latest operator version.

If the {PRODUCT} Operator is not available in the *OperatorHub* in the OpenShift web console, in a command terminal, enter the following command to add the operator to the Operator Lifecycle Manager (OLM) and try again to install the operator in the OpenShift web console:

.Adding the {PRODUCT} Operator to the OLM
[source]
----
$ oc create -f deploy/olm-catalog/kogito-operator/kogito-operator-operatorsource.yaml
----

If the OLM is not available in the cluster, you can install the {PRODUCT} Operator manually without the OLM by applying the following YAML files from the operator https://github.com/kiegroup/kogito-cloud-operator/tree/master/deploy[`deploy` directory] to the relevant namespace:

.Applying the {PRODUCT} Operator YAML resources manually without the OLM
[source]
----
$ oc apply -f deploy/service_account.yaml
$ oc apply -f deploy/role.yaml
$ oc apply -f deploy/role_binding.yaml
$ oc apply -f deploy/operator.yaml
----
