[id='proc-kogito-travel-agency-configure-ocp_{context}']

= Configuring access to your {OPENSHIFT} environment

To complete the travel agency tutorial, you must ensure that you have proper access to both the OpenShift web console and to the `oc` CLI.

NOTE: You can use different types of OpenShift 4.x environments, such as a full OpenShift cluster or a small https://github.com/code-ready/crc[CodeReady Containers] environment. However, the OpenShift environment must have access to the public Internet in order to be able to pull in the required container images and build artifacts.

.Procedure
. Log in to the OpenShift web console and in the upper-right corner of the screen, select your profile and click *Copy Login Command*.
. In the new window that appears, log in again to re-authenticate your user and then click *Display Token*.
. Copy the `oc login` command and enter it in a command terminal:
+
--
.Example `oc` CLI login token
[source,subs="+quotes"]
----
oc login --token=__OPENSHIFT_TOKEN__ --server=https://__WEB_CONSOLE_SERVER__
----

If your authentication fails or you do not have `cluster-admin` permissions, contact your OpenShift administrator.
--
