[id='proc_kogito-travel-agency-clone-repo']

= Cloning the travel agency tutorial Git repository

For this travel agency tutorial, you need local access to the example applications, so you must first clone the https://github.com/kiegroup/kogito-travel-agency-tutorial[travel agency tutorial] Git repository to your local system.

.Procedure
In a command terminal, navigate to a directory where you want to store the {PRODUCT} travel agency applications and enter the following command to clone the repository:

.Cloning the travel agency tutorial repository
[source]
----
git clone https://github.com/kiegroup/kogito-travel-agency-tutorial.git
----

The cloned `{PRODUCT_INIT}-travel-agency-tutorial` repository contains a sequence of example applications with {PRODUCT} services, each of them increasing in complexity.

The following applications are the examples that you need for this tutorial:

* `06-kogito-travel-agency`: Application for booking a trip to a specified destination, including flight and hotel
* `06-kogito-visas`: Application for managing travel visas, if required
