[id="chap-kogito-add-ons"]
= {PRODUCT} add-ons
ifdef::context[:parent-context: {context}]
:context: kogito-add-ons

// Purpose statement for the assembly
[role="_abstract"]
You can extend {PRODUCT} core capabilities by using add-ons modules. The add-on modules extend persistence, monitoring, messaging, and other features of {PRODUCT} services.

The following tables list all the supported add-ons:

.{PRODUCT} add-ons for Quarkus
[cols="20%,50%,20%"]
|===
|Name                     |Artifact Id                                          |Since

|Messaging                | kogito-addons-quarkus-messaging                     |1.0.0
|Events Decisions         | kogito-addons-quarkus-events-decisions              |1.2.0
|Events Process           | kogito-addons-quarkus-events-process                |0.3.0
|Explainability           | kogito-addons-quarkus-explainability                |0.15.0
|Jobs Management          | kogito-addons-quarkus-jobs-management               |0.6.0
|Knative Eventing         | kogito-addons-quarkus-knative-eventing              |1.10.0
|Mail                     | kogito-addons-quarkus-mail                          |1.6.0
|Elastic Monitoring       | kogito-addons-quarkus-monitoring-elastic            |1.2.0
|Prometheus Monitoring    | kogito-addons-quarkus-monitoring-prometheus         |0.1.0
|Persistence ISPN Health  | kogito-addons-quarkus-persistence-infinispan-health |0.8.0
|Persistence Kafka        | kogito-addons-quarkus-persistence-kafka             |1.4.0
|Process Management       | kogito-addons-quarkus-process-management            |0.3.0
|Process SVG              | kogito-addons-quarkus-process-svg                   |1.0.0
|Task Management          | kogito-addons-quarkus-task-management               |1.4.0
|Task Notification        | kogito-addons-quarkus-task-notification             |1.6.0
|Tracing Decision         | kogito-addons-quarkus-tracing-decision              |0.11.0
|Events MongoDB           | kogito-addons-quarkus-events-mongodb                |1.11.0
|===

.{PRODUCT} add-ons for Spring Boot
[cols="20%,50%,20%"]
|===
|Name                 |Artifact Id                                    |Since

|Messaging            |kogito-addons-springboot-messaging             |1.0.0
|Events Decisions     |kogito-addons-springboot-events-decisions      |1.2.0
|Events Kafka         |kogito-addons-springboot-events-kafka          |0.3.0
|Explainability       |kogito-addons-springboot-explainability        |0.15.0
|Jobs Management      |kogito-addons-springboot-jobs-management       |0.6.0
|Mail                 |kogito-addons-springboot-mail                  |1.6.0
|Elastic Monitoring   |kogito-addons-springboot-monitoring-elastic    |1.2.0
|Prometheus Monitoring|kogito-addons-springboot-monitoring-prometheus |0.1.0
|Process Management   |kogito-addons-springboot-process-management    |0.3.0
|Process SVG          |kogito-addons-springboot-process-svg           |1.0.0
|Task Management      |kogito-addons-springboot-task-management       |1.4.0
|Task Notification    |kogito-addons-springboot-task-notification     |1.6.0
|Tracing Decision     |kogito-addons-springboot-tracing-decision      |0.11.0
|Events MongoDB       |kogito-addons-springboot-events-mongodb        |1.11.0

|===


== Messaging add-on in {PRODUCT}

The messaging add-on uses events in the {PRODUCT} projects. For more information, see the following sections:

* xref:con-kogito-runtime-events_kogito-configuring[{PRODUCT} runtime events]
* xref:con-kogito-travel-agency_kogito-deploying-on-openshift[Travel agency tutorial for {PRODUCT} services on OpenShift]
* xref:con-data-index-service_kogito-configuring[{PRODUCT} Data Index Service]
* xref:con-trusty-service_kogito-configuring[{PRODUCT} Trusty Service and Explainability Service]

To use the messaging add-on, add the following code to the `pom.xml` file of your project:

.Quarkus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-messaging</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-messaging</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Decision Model and Notation (DMN) event-driven add-on in {PRODUCT}

.Quarkus
To use the DMN event-driven add-on, add the following code to the `pom.xml` file of your project:
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-events-decisions</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-events-decisions</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Explainability add-on in {PRODUCT}

The Explainability add-on in {PRODUCT} provides integration with Explainability and Trusty Services. You can also use https://github.com/kiegroup/kogito-examples/tree/stable/trusty-demonstration[`trusty-demonstration`] example application.

For more information, see the xref:con-trusty-service_kogito-configuring[].

To use the explainability add-on, add the following code to the `pom.xml` file of your project:

.Quarkus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-explainability</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-explainability</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Jobs Management add-on in {PRODUCT}

The Jobs Management add-on provides integration and configuration for a project using the supporting services related to Jobs. You can also use the following example applications: For more information, see the xref:con-jobs-service_kogito-configuring[documentation].

To use the Jobs Management add-on, add the following code to the `pom.xml` file of your project:

.Quarkus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-jobs-management</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-jobs-management</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Knative Eventing add-on in {PRODUCT}

The Knative Eventing add-on is used in the {PRODUCT} project for messaging. The https://github.com/kiegroup/kogito-runtimes/tree/main/addons/common/knative/eventing[{PRODUCT} Knative Eventing] add-on enables your project to connect to a https://knative.dev/docs/developer/eventing/sinks/[sink].

The add-on processes the https://knative.dev/development/developer/eventing/sources/sinkbinding/[`K_SINK`] and https://knative.dev/development/developer/eventing/sources/sinkbinding/reference/#cloudevent-overrides[`K_CE_OVERRIDES`] environment variables injected by Knative Eventing controllers.

The service requires the https://github.com/kiegroup/kogito-runtimes/tree/main/addons/common/messaging[{PRODUCT} Messaging] and https://quarkus.io/guides/reactive-messaging-http.html[Quarkus HTTP connector] libraries to wire the {PRODUCT} service with a given sink. The {PRODUCT} Messaging and Quarkus HTTP connector perform as dependencies for the Knative Eventing add-on.

NOTE: Spring Boot does not support Knative Eventing currently.

For more information, see xref:con-knative-eventing_kogito-developing-process-services[].

To use the Knative Eventing add-on, add the following code to the `pom.xml` file of your project:

.Quarkus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-knative-eventing</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Mail add-on in {PRODUCT}

The mail add-on is used to send emails in a process project. To use the mail add-on, add the following code to the `pom.xml` file of your project:

.Quarkus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-mail</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-mail</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Events add-on in {PRODUCT}

The events add-on provides a default implementation in supported target platforms for EventEmitter and EventReceiver interfaces. You can use EventEmitter and EventReceiver interfaces to enable messaging by process, serverless workflow events, and event decision handling. For more information, see xref:con-knative-eventing_kogito-developing-process-services[], xref:con-serverless-workflow-definitions_kogito-orchestrating-serverless[], and xref:proc-messaging-enabling_kogito-configuring[].

// include::../addons/proc-kogito-implement-message-payload-decorator.adoc[leveloffset=+1]

=== Implementing message payload decorator
Any dependant add-on can implement the https://github.com/kiegroup/kogito-runtimes/blob/main/addons/common/messaging/common/src/main/java/org/kie/kogito/addon/cloudevents/message/MessagePayloadDecorator.java[MessagePayloadDecorator].

.Prerequisites

* You have installed the Events add-on in {PRODUCT}.

.Procedure
. Create a file named `META-INF/services/org.kie.kogito.add-on.cloudevents.message.MessagePayloadDecorator` in your class path.
. Open the file.
. Enter the full name of your implementation class in the file.
. Save the file.

The `MessagePayloadDecoratorProvider` loads the file upon application startup and adds the file to the decoration chain. When {PRODUCT} calls the https://github.com/kiegroup/kogito-runtimes/blob/main/addons/common/messaging/common/src/main/java/org/kie/kogito/addon/cloudevents/message/MessagePayloadDecoratorProvider.java[MessagePayloadDecoratorProvider#decorate], your implementation is part of the decoration algorithm.

To use the events add-on, add the following code to the `pom.xml` file of your project:

.Events smallrye add-on for Quarkus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-events-smallrye</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Events decisions add-on for Quarkus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-events-decisions</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Events Kafka add-on for Spring Boot
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-events-kafka</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Events decisions add-on for Spring Boot
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-events-decisions</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Monitoring add-on in {PRODUCT}

The monitoring add-on provides monitoring capabilities in the {PRODUCT} project. For more information, see xref:_metrics_monitoring_in_kogito_services[Metrics monitoring in {PRODUCT}].

To use the monitoring add-on, add the following code to the `pom.xml` file of your project:

.Quarkus dependency for elastic search
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-monitoring-elastic</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Quarkus dependency for Prometheus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-monitoring-prometheus</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot dependency for elastic search
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-monitoring-elastic</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot dependency for Prometheus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-monitoring-prometheus</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Persistence add-on in {PRODUCT}

The persistence add-on provides persistence capability in your {PRODUCT} project. For more information, xref:con-persistence_kogito-developing-process-services[].

To use the Persistence add-on, add the following code to the `pom.xml` file of your project:

.Quarkus dependency for persistence filesystem
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-filesystem</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot dependency for persistence filesystem
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-filesystem</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Quarkus dependency for persistence Infinispan
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-infinispan</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot dependency for persistence Infinispan
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-infinispan</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Quarkus dependency for persistence JDBC
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-jdbc</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot dependency for persistence JDBC
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-jdbc</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Quarkus dependency for persistence MongoDB
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-mongodb</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot dependency for persistence MongoDB
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-mongodb</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Quarkus dependency for persistence PostgreSQL
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-postgresql</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot dependency for persistence PostgreSQL
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-postgresql</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Quarkus dependency for persistence Kafka
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-kafka</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot dependency for persistence Kafka
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-kafka</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

include::../bpmn/chap-kogito-developing-process-services.adoc[tag=process-man-add-on]

include::../bpmn/chap-kogito-developing-process-services.adoc[tag=process-svg-add-on]

== Task Management add-on in {PRODUCT}

The Task Management add-on provides integration with the https://github.com/kiegroup/kogito-apps/tree/master/task-console[Task Console]. For more information, see xref:con-task-console_kogito-developing-process-services[{PRODUCT} Task Console].

To use the Task Management add-on, add the following code to the `pom.xml` file of your project:

.Quarkus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-task-management</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring Boot
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-task-management</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Tracing add-on in {PRODUCT}

The Tracing add-on provides Decision model and notation (DMN) services tracing capability. For more information, see the [documentation](https://docs.jboss.org/kogito/release/latest/html_single/#con-trusty-service_kogito-configuring).

To use the Tracing add-on, add the following code to the `pom.xml` file of your project:

.Quarkus
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-tracing-decision</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

.Spring boot
[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-tracing-decision</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
