[id="chap-kogito-add-ons"]
= {PRODUCT} add-ons
ifdef::context[:parent-context: {context}]
:context: kogito-add-ons

// Purpose statement for the assembly
[role="_abstract"]
You can extend {PRODUCT} core capabilities by using add-ons modules. Add-on modules extend persistence, monitoring, messaging, and many other features of the {PRODUCT} service.

The following tables list all the add-ons, independent of runtime implementation that the community supports:

.{PRODUCT} Quarkus add-ons
[cols="20%,50%,20%"]
|===
|Name                     |Artifact Id                                          |Since

|Messaging                | kogito-addons-quarkus-messaging                     |1.0.0
|Events Decisions         | kogito-addons-quarkus-events-decisions              |1.2.0
|Events Process           | kogito-addons-quarkus-events-process                |0.3.0
|Explainability           | kogito-addons-quarkus-explainability                |0.15.0
|Jobs Management          | kogito-addons-quarkus-jobs-management               |0.6.0
|Knative Eventing         | kogito-addons-quarkus-knative-eventing              |1.10.0
|Mail                     | kogito-addons-quarkus-mail                          |1.6.0
|Monitoring Elastic       | kogito-addons-quarkus-monitoring-elastic            |1.2.0
|Monitoring Prometheus    | kogito-addons-quarkus-monitoring-prometheus         |0.1.0
|Persistence ISPN Health  | kogito-addons-quarkus-persistence-infinispan-health |0.8.0
|Persistence Kafka        | kogito-addons-quarkus-persistence-kafka             |1.4.0
|Process Management       | kogito-addons-quarkus-process-management            |0.3.0
|Process SVG              | kogito-addons-quarkus-process-svg                   |1.0.0
|Task Management          | kogito-addons-quarkus-task-management               |1.4.0
|Task Notification        | kogito-addons-quarkus-task-notification             |1.6.0
|Tracing Decision         | kogito-addons-quarkus-tracing-decision              |0.11.0
|Events MongoDB           | kogito-addons-quarkus-events-mongodb                |1.11.0
|===

.{PRODUCT} Spring Boot add-ons
[cols="20%,50%,20%"]
|===
|Name                 |Artifact Id                                    |Since

|messaging            |kogito-addons-springboot-messaging             |1.0.0
|Events Decisions     |kogito-addons-springboot-events-decisions      |1.2.0
|Events Kafka         |kogito-addons-springboot-events-kafka          |0.3.0
|Explainability       |kogito-addons-springboot-explainability        |0.15.0
|Jobs Management      |kogito-addons-springboot-jobs-management       |0.6.0
|Mail                 |kogito-addons-springboot-mail                  |1.6.0
|Monitoring Elastic   |kogito-addons-springboot-monitoring-elastic    |1.2.0
|Monitoring Prometheus|kogito-addons-springboot-monitoring-prometheus |0.1.0
|Process Management   |kogito-addons-springboot-process-management    |0.3.0
|Process SVG          |kogito-addons-springboot-process-svg           |1.0.0
|Task Management      |kogito-addons-springboot-task-management       |1.4.0
|Task Notification    |kogito-addons-springboot-task-notification     |1.6.0
|Tracing Decision     |kogito-addons-springboot-tracing-decision      |0.11.0
|Events MongoDB       |kogito-addons-springboot-events-mongodb        |1.11.0

|===


== Messaging

The Messaging add-on handles use cases with events on {PRODUCT} projects. See the following documentation sections to find out more.

- https://docs.jboss.org/kogito/release/latest/html_single/#con-kogito-runtime-events_kogito-configuring[{PRODUCT} runtime events]
- https://docs.jboss.org/kogito/release/latest/html_single/#con-kogito-travel-agency_kogito-deploying-on-openshift[Travel agency tutorial for {PRODUCT} services on OpenShift]
- https://docs.jboss.org/kogito/release/latest/html_single/#con-data-index-service_kogito-configuring[{PRODUCT} Data Index Service]
- https://docs.jboss.org/kogito/release/latest/html_single/#con-trusty-service_kogito-configuring[{PRODUCT} Trusty Service and Explainability Service]

Add the following code to your POM file:

=== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-messaging</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring Boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-messaging</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Decision Model and Notation (DMN) event-driven

- https://github.com/kiegroup/kogito-examples/tree/stable/dmn-event-driven-quarkus[dmn-event-driven-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/dmn-event-driven-springboot[dmn-event-driven-springboot]

=== Quarkus smallrye

- https://github.com/kiegroup/kogito-examples/tree/stable/kogito-travel-agency[kogito-travel-agency]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-mongodb-persistence-quarkus[process-mongodb-persistence-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-quarkus-example[process-quarkus-example]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-quarkus-with-console[process-usertasks-quarkus-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-timer-quarkus-with-console[process-usertasks-timer-quarkus-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-with-security-oidc-quarkus-with-console[process-usertasks-with-security-oidc-quarkus-with-console]

=== Spring Boot Kafka

- https://github.com/kiegroup/kogito-examples/tree/stable/process-mongodb-persistence-springboot[process-mongodb-persistence-springboot]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-springboot-example[process-springboot-example]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-springboot-with-console[process-usertasks-springboot-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-with-security-oidc-springboot-with-console[process-usertasks-with-security-oidc-springboot-with-console]

=== Quarkus
Add the following code to your POM file:

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-events-decisions</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring Boot

Add the following to your POM file:

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-events-decisions</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Explainability

The Explainability add-on provides integration with Explainability and Trusty Services. The https://github.com/kiegroup/kogito-examples/tree/stable/trusty-demonstration[trusty-demonstration] explores explainability further.

For more information, see the https://docs.jboss.org/kogito/release/latest/html_single/#con-trusty-service_kogito-configuring[documentation].

Add the following code to your POM file:

=== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-explainability</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-explainability</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Jobs management

The Jobs Management add-on provides integration and configuration for a project with the Jobs Service supporting service. 

Examples:

- https://github.com/kiegroup/kogito-examples/tree/stable/process-timer-quarkus[process-timer-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-timer-springboot[process-timer-springboot]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-timer-quarkus-with-console[process-usertasks-timer-quarkus-with-console]

For more information, see the https://docs.jboss.org/kogito/release/latest/html_single/#con-jobs-service_kogito-configuring[documentation].

Add the following code to your POM file:

=== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-jobs-management</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-jobs-management</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Knative eventing

You can use Quarkus Knative eventing add-on if your project uses Knative Eventing for messaging.

The https://github.com/kiegroup/kogito-runtimes/blob/main/quarkus/add-ons/knative/eventing[{PRODUCT} Knative Eventing] add-on ensures that your project can connect to a https://knative.dev/docs/developer/eventing/sinks/[sink]. The add-on processes the https://knative.dev/development/developer/eventing/sources/sinkbinding/[K_SINK] and https://knative.dev/development/developer/eventing/sources/sinkbinding/reference/#cloudevent-overrides[K_CE_OVERRIDES] environment variables injected by Knative Eventing controllers.

The service requires the https://github.com/kiegroup/kogito-runtimes/tree/main/addons/common/messaging[{PRODUCT} Messaging] and https://quarkus.io/guides/reactive-messaging-http.html[Quarkus HTTP connector] libraries to wire the {PRODUCT} service with a given sink. Both are dependencies of this add-on.

Examples:

- https://github.com/kiegroup/kogito-examples/tree/stable/process-knative-quickstart-quarkus[process-knative-quickstart-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/serverless-workflow-order-processing[serverless-workflow-order-processing]

For more information, see https://docs.jboss.org/kogito/release/latest/html_single/#con-knative-eventing_kogito-developing-process-services[Knative Eventing in {PRODUCT} services].

Add the following code to your POM file:

=== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-knative-eventing</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

Spring Boot does not support Knative Eventing at this time.

== Mail

With the Mail add-on, you can send emails in a Process project.

Examples:

- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-custom-lifecycle-quarkus[process-usertasks-custom-lifecycle-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-custom-lifecycle-springboot[process-usertasks-custom-lifecycle-springboot]

Add the following code to your POM file:

=== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-mail</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-mail</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Events

The Events add-on provides a default implementation in supported target platforms for EventEmitter and EventReceiver interfaces. You can use EventEmitter and EventReceiver interfaces to enable messaging by process, serverless workflow events, and event decision handling. For more information, see the following sections in the documentation:

- https://docs.jboss.org/kogito/release/latest/html_single/#con-knative-eventing_kogito-developing-process-services[Knative Eventing in {PRODUCT} services]
- https://docs.jboss.org/kogito/release/latest/html_single/#con-serverless-workflow-definitions_kogito-orchestrating-serverless[Serverless Workflow definitions]
- https://docs.jboss.org/kogito/release/latest/html_single/#proc-messaging-enabling_kogito-configuring[Enabling Kafka messaging for {PRODUCT} services]

Examples:

- https://github.com/kiegroup/kogito-examples/tree/stable/kogito-travel-agency[kogito-travel-agency]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-kafka-multi-quarkus[process-kafka-multi-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-kafka-multi-springboot[process-kafka-multi-springboot]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-kafka-quickstart-quarkus[process-kafka-quickstart-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-kafka-quickstart-springboot[process-kafka-quickstart-springboot]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-knative-quickstart-quarkus[process-knative-quickstart-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/serverless-workflow-github-showcase[serverless-workflow-github-showcase]
- https://github.com/kiegroup/kogito-examples/tree/stable/serverless-workflow-service-calls-quarkus[serverless-workflow-service-calls-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/serverless-workflow-temperature-conversion[serverless-workflow-temperature-conversion]

=== Message payload decorator
Any dependant add-on can implement the https://github.com/kiegroup/kogito-runtimes/blob/main/addons/common/messaging/common/src/main/java/org/kie/kogito/addon/cloudevents/message/MessagePayloadDecorator.java[MessagePayloadDecorator].

To implement the MessagePayloadDecorator:

- Create a file named `META-INF/services/org.kie.kogito.add-on.cloudevents.message.MessagePayloadDecorator` in your class path.
- Open the file.
- Enter the full name of your implementation class in the file.
- Save the file.

The `MessagePayloadDecoratorProvider` loads the file upon application startup and adds the file to the decoration chain. When {PRODUCT} calls the https://github.com/kiegroup/kogito-runtimes/blob/main/addons/common/messaging/common/src/main/java/org/kie/kogito/addon/cloudevents/message/MessagePayloadDecoratorProvider.java[MessagePayloadDecoratorProvider#decorate], your implementation is part of the decoration algorithm.

Add the following code to your POM file:

=== Quarkus

==== Events smallrye

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-events-smallrye</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

==== Events decisions

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-events-decisions</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

==== Events kafka

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-events-kafka</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

==== Events decisions

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-events-decisions</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Monitoring

The Monitoring add-on provides monitoring capabilities. For more information, see the https://docs.jboss.org/kogito/release/latest/html_single/#_metrics_monitoring_in_kogito_services[documentation].

Examples:

- https://github.com/kiegroup/kogito-examples/tree/stable/dmn-drools-quarkus-metrics[dmn-drools-quarkus-metrics]
- https://github.com/kiegroup/kogito-examples/tree/stable/dmn-drools-springboot-metrics[dmn-drools-springboot-metrics]
- https://github.com/kiegroup/kogito-examples/tree/stable/dmn-tracing-quarkus[dmn-tracing-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/dmn-tracing-springboot[dmn-tracing-springboot]
- https://github.com/kiegroup/kogito-examples/tree/stable/kogito-travel-agency[kogito-travel-agency]
- https://github.com/kiegroup/kogito-examples/tree/stable/onboarding-example[onboarding-example]

Add the following code to your POM file:

=== Quarkus

==== Elastic search

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-monitoring-elastic</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

==== Prometheus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-monitoring-prometheus</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

==== Elastic search

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-monitoring-elastic</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

==== Prometheus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-monitoring-prometheus</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Persistence

The Persistence add-on provides persistence capability. For more information, see the https://docs.jboss.org/kogito/release/latest/html_single/#con-persistence_kogito-developing-process-services[documentation].

Examples:
                                                                                                                                                                    - https://github.com/kiegroup/kogito-examples/tree/stable/process-infinispan-persistence-quarkus[process-infinispan-persistence-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-infinispan-persistence-springboot[process-infinispan-persistence-springboot]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-kafka-persistence-quarkus[process-kafka-persistence-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-mongodb-persistence-quarkus[process-mongodb-persistence-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-mongodb-persistence-springboot[process-mongodb-persistence-springboot]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-postgresql-persistence-quarkus[process-postgresql-persistence-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-postgresql-persistence-springboot[process-postgresql-persistence-springboot]

Add the following code to your POM file:

=== Persistence filesystem

==== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-filesystem</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-filesystem</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Persistence infinispan

==== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-infinispan</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-infinispan</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Persistence JDBC

==== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-jdbc</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-jdbc</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Persistence MongoDB

==== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-mongodb</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-mongodb</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Persistence postgresql

==== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-postgresql</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-postgresql</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Persistence kafka

==== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-persistence-kafka</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring Boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-persistence-kafka</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Process management

The Process Management add-ons provide process management capability, and they are part of the integration with the
[{PRODUCT} Management Console](https://github.com/kiegroup/kogito-apps/tree/master/management-console). For more information, see the [documentation](https://docs.jboss.org/kogito/release/latest/html_single/#con-bpmn-process-management-add-on_kogito-developing-process-services).

Examples:

- https://github.com/kiegroup/kogito-examples/tree/stable/kogito-travel-agency[kogito-travel-agency]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-quarkus-example[process-quarkus-example]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-springboot-example[process-springboot-example]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-timer-springboot[process-timer-springboot]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-quarkus-with-console[process-usertasks-quarkus-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-springboot-with-console[process-usertasks-springboot-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-timer-quarkus-with-console[process-usertasks-timer-quarkus-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-with-security-oidc-quarkus-with-console[process-usertasks-with-security-oidc-quarkus-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-with-security-oidc-springboot-with-console[process-usertasks-with-security-oidc-springboot-with-console]

Add the following code to your POM file:

=== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-process-management</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring Boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-springboot-management</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Process SVG

The Process SVG add-on provides the capability to enable SVG visualization to process diagrams. For more information, see the https://docs.jboss.org/kogito/release/latest/html_single/#con-bpmn-process-svg-add-on_kogito-developing-process-services[documentation].

Examples:

- https://github.com/kiegroup/kogito-examples/tree/stable/kogito-travel-agency[kogito-travel-agency]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-quarkus-with-console[process-usertasks-quarkus-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-springboot-with-console[process-usertasks-springboot-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-timer-quarkus-with-console[process-usertasks-timer-quarkus-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-with-security-oidc-quarkus-with-console[process-usertasks-with-security-oidc-quarkus-with-console]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-with-security-oidc-springboot-with-console[process-usertasks-with-security-oidc-springboot-with-console]

Add the following code to your POM file:

=== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-process-svg</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring Boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-process-svg</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Task management

The Task Management add-on provides integration with the {PRODUCT} supporting service [Task Console](https://github.com/kiegroup/kogito-apps/tree/master/task-console). For more information, see the [documentation](https://docs.jboss.org/kogito/release/latest/html_single/#con-task-console_kogito-developing-process-services).

Examples

- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-custom-lifecycle-quarkus[process-usertasks-custom-lifecycle-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-custom-lifecycle-springboot[process-usertasks-custom-lifecycle-springboot]

Add the following code to your POM file:

=== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-task-management</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring Boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-task-management</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

== Tracing

The Tracing add-on provides Decision model and notation (DMN) services tracing capability. For more information, see the [documentation](https://docs.jboss.org/kogito/release/latest/html_single/#con-trusty-service_kogito-configuring).

Examples:

- https://github.com/kiegroup/kogito-examples/tree/stable/dmn-tracing-quarkus[dmn-tracing-quarkus]
- https://github.com/kiegroup/kogito-examples/tree/stable/dmn-tracing-springboot[dmn-tracing-springboot]

Add the following code to your POM file:

=== Quarkus

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-quarkus-tracing-decision</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

=== Spring Boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-addons-springboot-tracing-decision</artifactId>
  <version>{PRODUCT_VERSION}</version>
</dependency>
----

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
