[id='assembly_planning']

include::_artifacts/document-attributes.adoc[]

= Planning a {PRODUCT} installation
// Context attribute is assembly specific and enables module reuse between assemblies.
:doctype: book
:imagesdir: _images
:context: planning
include::_artifacts/author-group.adoc[]

// Purpose statement for the assembly
As a system administrator, you have several options for installing {PRODUCT}.


// Modules - concepts, procedures, refs, etc.
//include::product-installation-guide/rules-authoring-assets-ref.adoc[leveloffset=+1]

== {PRODUCT} description
{PRODUCT} is an open source business process management suite that combines business process management and business rules management. It enables business and IT users to create, manage, validate, and deploy business processes and rules.

{PRODUCT} uses a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic and business processes without requiring assistance from IT personnel.

include::installation/components-con.adoc[leveloffset=+1]

//include::product-installation-guide/business-optimizer-con.adoc[leveloffset=+2]


== Available installation platforms

Every {PRODUCT} release is certified on a variety operating systems, JVMs, web browsers, and database combinations. Red Hat provides both production and development support for supported and tested configurations in both physical and virtual environments, according to your subscription agreement. See the following pages for information about supported configurations and version numbers:

* https://access.redhat.com/articles/3405381[Red Hat Process Automation Manager 7 Supported Configurations]
* https://access.redhat.com/articles/3405391[Red Hat Process Automation Manager 7 Component Details]

{PRODUCT} {PRODUCT_VERSION} is available for the following application platforms:

* {EAP} 7.1
* Red Hat OpenShift Container Platform
* Oracle WebLogic Server
* IBM WebSphere Application Server

=== {EAP} 7.1
{EAP_LONG} ({EAP}) 7.1 is a certified implementation of the Java Enterprise Edition 7 (Java EE 7) full and web profile specifications. Red Hat JBoss EAP provides preconfigured options for features such as high availability, clustering, messaging, and distributed caching. It also enables users to write, deploy, and run applications using the various APIs and services that Red Hat JBoss EAP provides.

You can install both {CENTRAL} and {KIE_SERVER} in a single {EAP} instance. However, in production environments you should install them in separate instances.

=== Red Hat OpenShift Container Platform

Red Hat OpenShift Container Platform (OpenShift) brings together Docker and Kubernetes, and provides an API to manage these services. OpenShift Container Platform enables you to create and manage containers.

In this solution, components of {PRODUCT} are deployed as separate OpenShift pods. You can scale each of the pods up and down individually, providing as few or as many containers as necessary for a particular component. You can use standard OpenShift methods to manage the pods and balance the load.

You can install both {CENTRAL} and {KIE_SERVER} on OpenShift.

//=== JBoss Web Server 5 with Tomcat 9

=== Oracle WebLogic server
Oracle WebLogic Server is a Java EE application server that provides a standard set of APIs for creating distributed Java applications that can access a wide variety of services, such as databases, messaging services, and connections to external enterprise systems. User clients access these applications using web browser clients or Java clients.

You can install {KIE_SERVER} in an Oracle Weblogic Server instance and then use the headless {PRODUCT} controller and the REST API or the Process Server Java Client API to interact with {KIE_SERVER}.


=== IBM WebSphere Application Server
IBM WebSphere Application Server is a flexible and secure web application server that hosts Java-based web applications and provides Java EE-certified run time environments. IBM WebSphere 9.0 supports Java SE 8 and is fully compliant with Java EE 7 since version 8.5.5.6.

You can install {KIE_SERVER} in an IBM WebSphere Application Server instance and then use the headless {PRODUCT} controller to interact with {KIE_SERVER}.

=== Development platform option
As a developer, you can develop assets in {PRODUCT}. However, you can optionally integrate Red Hat JBoss Developer Studio with Red Hat Process Automation Manager to write complex applications and leverage code auto-completion.

Red Hat JBoss Developer Studio is an integrated development environment (IDE) based on Eclipse. It integrates tooling and runtime components by combining Eclipse, Eclipse Tooling, and Red Hat JBoss EAP. Red Hat JBoss Developer Studio provides plug-ins with tools and interfaces for Red Hat Process Automation Manager. These plugins are based on the community version of these products. For this reason, the Red Hat Process Automation Manager plug-in is called the Drools plug-in.

== Supported repositories
=== Git repositories
Git is a distributed version control system. It implements revisions as commit objects. When you commit your changes into a repository, a new commit object in the Git repository is created. When you create a project in {CENTRAL} it is added to the Git repository connected to {CENTRAL}.

If you have projects in other Git repositories, you can import them into {CENTRAL} spaces.

include::admin-and-config/maven-con.adoc[leveloffset=+2]

== Installation environment options

With {PRODUCT}, you can set up a development environment to develop decision process applications, a runtime environment to run those applications to support decisions, or both.

A development environment typically consists of one or more {CENTRAL} installations and at least one {KIE_SERVER} installation. {CENTRAL} enables developers to create decision processes, rules, and other artifacts. They use {KIE_SERVER} to test the artifacts that they created.

A runtime environment consists of one or more {KIE_SERVER} instances with or without {CENTRAL}. If {CENTRAL} is not installed, you can use the headless {PRODUCT} controller and the REST API or the Process Server Java Client API to interact with {KIE_SERVERS}.

.Clustered environments
By clustering two or more servers, you have the benefits of high availability, enhanced collaboration, and load balancing. High availability decreases the chance of a loss of data when a single server fails because data on all of the servers (nodes) of the cluster is replicated on each node of the cluster. When a server fails, another server fills the gap by providing a copy of the data that was on the failed server. When the failed server comes online again, it resumes its place in the cluster. Load balancing shares the computing load across the nodes of the cluster. Doing this improves the overall performance of the cluster.

You can cluster both development and runtime environments. The primary benefit of clustering {PRODUCT} development environments is high availability and enhanced collaboration. The primary benefit of clustering a runtime environment is load balancing. If activity on one node of the cluster increases, that activity can be shared among the other nodes of the cluster to improve performance.

Clustering is supported on {EAP} 7.1 and Openshift.

//Difference between a clustered and a standalone environment. Pros and cons of each. Discuss //high availability. Clustering a Development environment vs Clustering a Production environment
//Include a descriptions of NFS, Artemis, Elasticsearch, any other cluster-related tools.

include::installation/roles-users-con.adoc[leveloffset=+1]
== Integrating with Red Hat Single Sign-On
Red Hat Single Sign-On (RH-SSO) is a single sign-on solution that you can use to secure your browser applications with your REST web services and Git access.

When you integrate {PRODUCT} with RH-SSO, you create an SSO and identity management (IDM) environment for {PRODUCT}. The session management feature of RH-SSO enables you to use a single authentication for different {PRODUCT} environments on the internet.

RH-SSO 7.2 is supported with {PRODUCT} on {EAP} 7.1.


//== Putting it all together

== Additional resources

* {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_]
* {URL_INSTALLING_KIE_ON_WAS}[_{INSTALLING_KIE_ON_WAS}_]
* {URL_INSTALLING_KIE_ON_WLS}[_{INSTALLING_KIE_ON_WLS}_]
//* {URL_INSTALLING_PLANNER}[_{INSTALLING_PLANNER}_]
//* {URL_INSTALLING_ON_EAP_CLUSTER}[_{INSTALLING_ON_EAP_CLUSTER}_]
* {URL_INTEGRATING_JBDS}[_{INTEGRATING_JBDS}_]
* {URL_INTEGRATING_SSO}[_{INTEGRATING_SSO}_]
* {URL_DEPLOYING_AUTHORING_ON_OPENSHIFT}[_{DEPLOYING_AUTHORING_ON_OPENSHIFT}_]
* {URL_DEPLOYING_IMMUTABLE_ON_OPENSHIFT}[_{DEPLOYING_IMMUTABLE_ON_OPENSHIFT}_]
* {URL_DEPLOYING_MANAGED_ON_OPENSHIFT}[_{DEPLOYING_MANAGED_ON_OPENSHIFT}_]


// Versioning info
include::_artifacts/versioning-information.adoc[]
