[id='wb-employee-rostering-facts-vs-entities-con']
= Problem facts and planning entities 

Each of the domain classes in the employee rostering planning problem can be categorized as one of the following:

* A unrelated class: not used by any of the score constraints. From a planning standpoint, this data is obsolete.
* A _problem fact_ class: used by the score constraints, but does not change during planning (as long as the problem stays the same), for example, `Shift` and `Employee`. All the properties of a problem fact class are problem properties.
* A _planning entity_ class: used by the score constraints and changes during planning, for example, `ShiftAssignment`. The properties that change during planning are _planning variables_. The other properties are problem properties.
+
Ask yourself the following questions: 
* _What class changes during planning?_
* _Which class has variables that I want the `Solver` to change?_
+
That class is a planning entity.
+
A planning entity class needs to be annotated with the `@PlanningEntity` annotation, or defined in {CENTRAL} using the {PLANNER} dock in the domain designer.
+
Each planning entity class has one or more _planning variables_, and should also have one or more defining properties.
+
Most use cases have only one planning entity class, and only one planning variable per planning entity class.