ifdef::BA[]

= Business Process Scenario

A bank offers a housing mortgage loan service. When a customer wants to buy a new property using credit, they contact a broker at the bank who assists in filing for a mortgage loan. The broker collects extensive information about the property and the customer, such as the salary of the customer, social security number, the property sale price,and the requested loan amount. The broker then submits a request on behalf of the customer. 

Using {PRODUCT}, the housing mortgage department of the bank creates complete business process for the mortgage loan. Whenever a customer submits a request, a new process instance is created. This ensures consistency in the quality of evaluating each request, provides complete visibility into the status of each request, and makes the process efficient and effective.

[float]
= Key Stages

* Collecting data from customers.
* Starting and following a designed process.
* Evaluation of the collected data.
* Informing the customer of the outcome.

endif::BA[]

ifdef::DM[]

= Business Rule Scenario

A US department of motor vehicles has a record of all the licensed drivers in the state. When a driver violates a traffic rule, an update is made to the driver’s record and predetermined actions are triggered, such as fine, suspension, revocation, and disqualification of license. A driver must pay the fine within a specified period after getting a ticket. Otherwise, driver’s license is be suspended. Suspension prohibits the driver from driving any type of vehicle. In such case, the driver should surrender the license within thirty days. 

[float]
= Key Stages

* Continuous data collection.
* Continuous data evaluation.

endif::DM[]
