[[_importing_a_getting_started_business_project]]
= Importing a Getting Started Business Project

The following chapter instructs you how to import an incomplete business process application. You will extend the application in later chapters. 

[float]
== Prerequisites

* Installed Red Hat JBoss EAP 7.0. For further information, see https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/installation_guide/[_Red Hat JBoss EAP 7.0 Installation Guide_].
* Installed {PRODUCT}. For further information, see the {INSTALLATION_GUIDE}.
* {PRODUCT} is running and you can log into Business Central with the `admin` role. For further information, see the {INSTALLATION_GUIDE}.

== Importing the Starter Project

To import the starter project:

. Log into Business Central.
.. Click *Home* -> *Admin*, then *Library*.
.. In the *Repository URL to search for example projects* field, paste the following: `https://github.com/ibek/bpms-getting-started.git`.
.. Click *Save*.
. Click *Authoring* -> *Project Authoring*, then *Import Example* -> *process-app-start*. 
+
If you do not see the *process-app-start*, refresh your Business Central window.  