[[_wb.installation]]
= Installation

[[_wb.warinstallation]]
== War installation


Use the `war` from the workbench distribution zip that corresponds to your application server.
The differences between these `war` files are mainly superficial.
For example, some JARs might be excluded if the application server already supplies them.

* ``eap7``: tailored for Red Hat JBoss Enterprise Application Platform 7
* ``tomcat8``: tailored for Apache Tomcat 8
+

[NOTE]
====
Apache Tomcat requires additional configuration to correctly install the Workbench.
Please consult the `README.md` in the `war` for the most up to date procedure.
====
* ``wildfly10``: tailored for Red Hat JBoss Wildfly 10


[[_wb.workbenchdata]]
== Workbench data


The workbench stores its data, by default in the directory ``$WORKING_DIRECTORY/.niogit``, for example ``wildfly-10.0.0.Final/bin/.niogit``, but it can be overridden with the <<_wb.systemproperties,system property>>``-Dorg.uberfire.nio.git.dir``.

[NOTE]
====
In production, make sure to back up the workbench data directory.
====

[[_wb.systemproperties]]
== System properties


Here's a list of all system properties:

* **``org.uberfire.nio.git.dir``**: Location of the directory ``$$.$$niogit``. Default: working directory
* **``org.uberfire.nio.git.dirname``**: Name of the git directory. Default: `.niogit`
* **``org.uberfire.nio.git.daemon.enabled``**: Enables/disables git daemon. Default: `true`
* **``org.uberfire.nio.git.daemon.host``**: If git daemon enabled, uses this property as local host identifier. Default: `localhost`
* **``org.uberfire.nio.git.daemon.port``**: If git daemon enabled, uses this property as port number. Default: `9418`
* **``org.uberfire.nio.git.ssh.enabled``**: Enables/disables ssh daemon. Default: `true`
* **``org.uberfire.nio.git.ssh.host``**: If ssh daemon enabled, uses this property as local host identifier. Default: `localhost`
* **``org.uberfire.nio.git.ssh.port``**: If ssh daemon enabled, uses this property as port number. Default: `8001`
* **``org.uberfire.nio.git.ssh.cert.dir``**: Location of the directory `$$.$$security` where local certificates will be stored. Default: working directory
* **``org.uberfire.nio.git.ssh.passphrase``**: Passphrase to access your Operating Systems public keystore when cloning `git` repositories with `scp` style URLs; e.g. ``git@github.com:user/repository.git``.
* **``org.uberfire.nio.git.ssh.algorithm``**: Algorithm used by SSH. Default: `DSA`
+

[NOTE]
====
If you plan to use RSA or any algorithm other than DSA, make sure you setup properly your Application Server to use Bouncy Castle JCE library.
====
* **``org.uberfire.metadata.index.dir``**: Place where Lucene `$$.$$index` folder will be stored. Default: working directory
* **``org.uberfire.cluster.id``**: Name of the helix cluster, for example: `kie-cluster`
* **``org.uberfire.cluster.zk``**: Connection string to zookeeper. This is of the form ``host1:port1,host2:port2,host3:port3``, for example: `localhost:2188`
* **``org.uberfire.cluster.local.id``**: Unique id of the helix cluster node, note that '``:``' is replaced with '``\_``', for example: `node1_12345`
* **``org.uberfire.cluster.vfs.lock``**: Name of the resource defined on helix cluster, for example: `kie-vfs`
* **``org.uberfire.cluster.autostart``**: Delays VFS clustering until the application is fully initialized to avoid conflicts when all cluster members create local clones. Default: `false`
* **``org.uberfire.ldap.regex.role_mapper``**: Regex pattern used to map LDAP principal names to application role name.  Note that the variable `role` must be part of the pattern as it is substited by the application role name when matching a principal value to role name. Default: Not used.
* **``org.uberfire.sys.repo.monitor.disabled``**: Disable configuration monitor (do not disable unless you know what you're doing). Default: `false`
* **``org.uberfire.secure.key``**: Secret password used by password encryption. Default: `org.uberfire.admin`
* **``org.uberfire.secure.alg``**: Crypto algorithm used by password encryption. Default: `PBEWithMD5AndDES`
* **``org.uberfire.domain``**: security-domain name used by uberfire. Default: `ApplicationRealm`
* **``org.guvnor.m2repo.dir``**: Place where Maven repository folder will be stored. Default: working-directory/repositories/kie
* **``org.guvnor.project.gav.check.disabled``**: Disable GAV checks. Default: `false`
* **``org.kie.example.repositories``**: Folder from where demo repositories will be cloned. The demo repositories need to have been obtained and placed in this folder. Demo repositories can be obtained from the kie-wb-6.2.0-SNAPSHOT-example-repositories.zip artifact. This System Property takes precedence over org.kie.demo and org.kie.example. Default: Not used.
* **``org.kie.demo``**: Enables external clone of a demo application from GitHub. This System Property takes precedence over org.kie.example. Default: `true`
* **``org.kie.example``**: Enables example structure composed by Repository, Organization Unit and Project. Default: `false`
* **``org.kie.build.disable-project-explorer``**: Disable automatic build of selected Project in Project Explorer. Default: `false`
* **``org.kie.verification.disable-dtable-realtime-verification``**: Disables the realtime validation and verification of decision tables. Default: `false`


To change one of these system properties in a WildFly or JBoss EAP cluster:

. Edit the file ``$JBOSS_HOME/domain/configuration/host.xml``.
. Locate the XML elements `server` that belong to the `main-server-group` and add a system property, for example:
+

[source,xml]
----
<system-properties>
  <property name="org.uberfire.nio.git.dir" value="..." boot-time="false"/>
  ...
</system-properties>
----

[[_wb.troubleshooting]]
== Trouble shooting

[[_wb.troubleshootingloadingspinner]]
=== Loading.. does not disappear and Workbench fails to show


There have been reports that Firewalls in between the server and the browser can interfere with Server Sent Events (SSE) used by the Workbench.

The issue results in the "Loading..." spinner remaining visible and the Workbench failing to materialize.

The workaround is to disable the Workbench's use of Server Sent Events by adding file `/WEB-INF/classes/ErraiService.properties` to the exploded WAR containing the value ``errai.bus.enable_sse_support=false``.
Re-package the WAR and re-deploy.

Some Users have also reported disabling Server Sent Events does not resolve the issue. The solution found to work is to configure the JVM to use a different Entropy Gathering Device on Linux for `SecureRandom`. This can be configured by setting System Property `java.security.egd` to `file:/dev/./urandom`. See http://stackoverflow.com/questions/33166198/kie-workbench-not-loading-after-login/39110177#39110177[this]  Stack Overflow post for details.

Please note however this affects the JVM's random  number generation and may present other challenges where strong cryptography is required. Configure with caution.

=== Not able to clone KIE Workbench Git repository using ssh protocol.
Git clients using ssh to interact with the Git server that is bundled with Workbench are authenticated and authorized to perform git commands by the security API that is part of the Uberfire backend server.  When using an LDAP security realm, some git clients were not being authorized as expected.  This was due to the fact that for non-web clients such as Git via ssh, the principal (i.e., user or group) name assigned to a user by the application server's user registry is the more complex DN associated to that principal by LDAP. The logic of the Uberfire backend server looked for on exact match of roles allowed with the principal name returned and therefore failed.

It is now possible to control the role-principal matching via the system property

[source, property]
----
org.uberfire.ldap.regex.role_mapper
----

which takes as its value a Regex pattern to be applied when matching LDAP principal to role names.  The pattern must contain the literal word variable 'role'.  During authorization the variable is replaced by each of the allow application roles.  If the pattern is matched the role is added to the user.

For instance, if the DN for the admin group in LDAP is

[source, property]
----
DN: cn=admin,ou=groups,dc=example,dc=com
----

and its intended role is admin, then setting `org.uberfire.ldap.regex.role_mapper` with value

[source, regex]
----
cn[\\ ]*=[\\ ]*role
----

will find a match on role 'admin'.
