[id='ba-platforms-con_{context}']

= {PRODUCT} installation platforms

Every {PRODUCT} release is certified on a variety of operating systems, JVMs, web browsers, and database combinations. Red Hat provides both production and development support for supported and tested configurations in both physical and virtual environments, according to your subscription agreement. See the following pages for information about supported configurations and version numbers:
//Comment: update links

//ifdef::PAM[]
* https://access.redhat.com/articles/3405381[{PRODUCT} 7 Supported Configurations]
* https://access.redhat.com/articles/3463751[{PRODUCT} 7 Component Details]
//endif::[]

////
ifdef::DM[]
* https://access.redhat.com/articles/3354301[{PRODUCT_DM} Manager 7 Supported Configurations]
* https://access.redhat.com/articles/3355791[{PRODUCT_DM} 7 Component Details]
endif::[]
////


{PRODUCT} {PRODUCT_VERSION} is available for the following application platforms:

* {EAP}
* Red Hat JBoss Web Server
* Red Hat OpenShift Container Platform
* Oracle WebLogic Server
* IBM WebSphere Application Server
