[id='clustering-bc-testing-proc']
= Verifying the {PRODUCT} cluster

After configuring the cluster for {PRODUCT}, create an asset to verify that the installation is working.

.Procedure
. In a web browser, enter `<node-IP-address>:8080/{URL_COMPONENT_CENTRAL}`. Replace `<node-IP-address>` with the IP address of a particular node.
. Enter the `admin` user credentials that you created during installation. The {CENTRAL} home page appears.
. Select *Menu* -> *Design* -> *Projects*.
. Click *Try Samples* -> *Mortgages* -> *OK*. The Assets window appears.
. Click *Create New Asset* -> *Data Object*.
. Enter `MyDataObject` in the *Data Object* field and click *OK*.
. Click *Spaces* -> *myteam* -> *Mortgages* and confirm that `MyDataObject` is in the list of assets.
. Enter the following URL in a web browser, where `<node_IP_address>` is the address of a different node of the cluster:
+
`http://<node_IP_address>:8080/{URL_COMPONENT_CENTRAL}`
. Enter the same credentials that you used to log in to {CENTRAL} on the first node, where you created the `MyDataObject` asset.
. Select *Menu*-> *Design* -> *Projects*.
. Select the *Mortgages* project.
. Verify that `MyDataObject` is in the asset list.
. Delete the *Mortgages* project.



