[id='clustering-smart-router-install-proc_{context}']
= Clustering {KIE_SERVERS} with Smart Router

You can use Smart Router to aggregate multiple independent {KIE_SERVER} instances as though they are a single server. It performs the role of an intelligent load balancer because it can route requests to individual {KIE_SERVER}s and aggregate data from different {KIE_SERVER}s. Smart Router uses aliases to perform as a proxy.

This section describes how to install Smart Router and configure it for a Red Hat {PRODUCT_SHORT} runtime environment.

.Prerequisites
* {KIE_SERVER} is installed on each node of a {EAP} {EAP_VERSION} cluster.
+
[NOTE]
====
You do not need to configure {KIE_SERVER} as unmanaged for Smart Router.

An unmanaged {KIE_SERVER} does not connect to the controller.

For example, if you connect an unmanaged {KIE_SERVER} to Smart Router and register Smart Router with the controller, then {CENTRAL} contacts the unmanaged {KIE_SERVER} by using Smart Router.
====

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product: {PRODUCT_SHORT}*
* *Version: {PRODUCT_VERSION}*
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons*.
. Extract the downloaded `{PRODUCT_FILE}-add-ons.zip` file to a temporary directory. The `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-smart-router.jar` file is in the extracted `{PRODUCT_FILE}-add-ons` directory.
. Copy the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-smart-router.jar` file to the location where you will run the file.

. Enter the following command to start Smart Router:
+
[source]
----
java
-Dorg.kie.server.router.host=<ROUTER_HOST>
-Dorg.kie.server.router.port=<ROUTER_PORT>
-Dorg.kie.server.controller=<CONTROLLER_URL>
-Dorg.kie.server.controller.user=<CONTROLLER_USER>
-Dorg.kie.server.controller.pwd=<CONTROLLER_PWD>
-Dorg.kie.server.router.config.watcher.enabled=true
-Dorg.kie.server.router.repo=<NFS_STORAGE>
-jar rhpam-7.8.0-smart-router.jar
----
+
The properties in the preceding command have the following default values:
+
[source]
----
org.kie.server.router.host=localhost
org.kie.server.router.port=9000
org.kie.server.controller= N/A
org.kie.server.controller.user=kieserver
org.kie.server.controller.pwd=kieserver1!
org.kie.server.router.repo= <CURRENT_WORKING_DIR>
org.kie.server.router.config.watcher.enabled=false
----
+
`org.kie.server.controller` is the URL of the server controller, for example:
+
[source]
----
org.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller
----
+
`org.kie.server.router.config.watcher.enabled` is an optional settings to enable the watcher service system property.

. To access Smart Router from the client side, use the Smart Router URL instead of the {KIE_SERVER} URL, for example:
+
[source]
----
KieServicesConfiguration config = KieServicesFactory.newRestConfiguration("http://smartrouter.example.com:9000", "USERNAME", "PASSWORD");
----
+
In this example, `smartrouter.example.com` is the Smart Router URL, and `USERNAME` and `PASSWORD` are the log in credentials for the Smart Router configuration.

[NOTE]
====
You must create containers directly against the `kie-server`. For example:

----
$ curl -v -X POST -H 'Content-type: application/xml' -H 'X-KIE-Content-Type: xstream' -d @create-container.xml -u ${KIE_CRED} http://${KIE-SERVER-HOST}:${KIE-SERVER-PORT}/kie-server/services/rest/server/config/
----

----
$ cat create-container.xml
<script>
  <create-container>
    <container container-id="example:timer-test:1.1">
      <release-id>
        <group-id>example</group-id>
        <artifact-id>timer-test</artifact-id>
        <version>1.1</version>
      </release-id>
      <config-items>
        <itemName>RuntimeStrategy</itemName>
        <itemValue>PER_PROCESS_INSTANCE</itemValue>
        <itemType></itemType>
      </config-items>
    </container>
  </create-container>
</script>
----

A message about the deployed container is displayed in the smart-router console. For example:

----
INFO: Added http://localhost:8180/kie-server/services/rest/server as server location for container example:timer-test:1.1
----

To display a list of containers, enter the following command:

----
$ curl http://localhost:9000/mgmt/list
----

The list of containers is displayed:

----
{
  "containerInfo": [{
    "alias": "timer-test",
    "containerId": "example:timer-test:1.1",
    "releaseId": "example:timer-test:1.1"
  }],
  "containers": [
    {"example:timer-test:1.1": ["http://localhost:8180/kie-server/services/rest/server"]},
    {"timer-test": ["http://localhost:8180/kie-server/services/rest/server"]}
  ],
  "servers": [
    {"kieserver2": []},
    {"kieserver1": ["http://localhost:8180/kie-server/services/rest/server"]}
  ]
}
----

To initiate a process using the Smart Router URL, enter the following command:

----
$ curl -s -X POST -H 'Content-type: application/json' -H 'X-KIE-Content-Type: json' -d '{"timerDuration":"9s"}' -u kieserver:kieserver1! http://localhost:9000/containers/example:timer-test:1.1/processes/timer-test.TimerProcess/instances
----
====
