[id='clustering-datagrid-proc_{context}']
= Installing and configuring {DATAGRID}

For more efficient searching across cluster nodes, install {DATAGRID} and configure it for the {PRODUCT} clustered environment.

For information about advanced installation and configuration options and {DATAGRID} modules for {EAP}, see the https://access.redhat.com/documentation/en-us/red_hat_data_grid/7.3/html-single/red_hat_data_grid_user_guide/index#[_{DATAGRID} User Guide_].

NOTE: Do not install {DATAGRID} on the same node as {CENTRAL}.

.Prerequisites
* A Java Virtual Machine (JVM) environment compatible with Java 8.0 or later is installed.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
+
* *Product:* Data Grid
* *Version:* 7.3

. Download and extract the *Red Hat JBoss Data Grid 7.3.0 Server* (`jboss-datagrid-7.3.0-1-server.zip`) installation file to the preferred location on your system. In the following examples, the extracted directory is referred to as `__JDG_HOME__`.
. Update {DATAGRID} to the latest version. For more information, see {DATAGRID} https://access.redhat.com/documentation/en-us/red_hat_data_grid/7.3/html-single/red_hat_data_grid_user_guide/index#[_{DATAGRID} User Guide_].
. To run {DATAGRID}, navigate to `__JDG_HOME__/bin` and enter the following command:
+
[source]
----
$ ./standalone.sh -c clustered.xml -b <HOST>
----
+
Replace `<HOST>` with the IP address or host name of the server where you installed {DATAGRID}.
