[id='clustering-bc-configure-host-proc']
= Configuring {EAP} 7.1 host files for a {CENTRAL} clustered environment

After you have installed {EAP} and configured the `domain.xml` file for a {CENTRAL} clustered environment, complete these steps in the `host.xml` file on the master node and in the `host-slave.xml` file on each slave node.

.Prerequisite
{EAP} 7.1 is installed on each node of the cluster.

.Procedure
. Open the `_EAP_HOME_/domain/configuration/host.xml` file or the `_EAP_HOME_/domain/configuration/host-slave.xml` file in a text editor.
. In the `main-server-group` `<servers>` element, add the servers that will be part of the cluster.
. Add the the system properties listed in
ifdef::PAM[]
<<_cluster_properties_pam>>
endif::PAM[]
ifdef::DM[]
<<_cluster_properties_BRMS>>
endif::DM[]
. Save the `host.xml` or `host-slave.xml` file.

ifdef::PAM[]
[id='_cluster_properties_pam']
.Cluster node properties
[cols="1,1,2", frame="all", options="header"]
|===
|Property name
|Value
|Description

|`jboss.node.name`
|_node name_
|A node name unique within the cluster (optional).

|`org.uberfire.nio.git.daemon.host`
|_node name_
|The name of the daemon host machine in a physical cluster.

|`org.uberfire.nio.git.daemon.port`
|_port number_
|The port used by the VFS repo to accept client connections. The port must be unique for each cluster member. If the default or assigned port is already in use, a new port is automatically selected. Ensure that the ports are available and check the log for more information.

|`org.uberfire.nio.git.ssh.host`
|_SSH host node name_
|The name of the SSH host machine in a physical cluster.

|`org.uberfire.nio.git.ssh.port`
|_port number_
|The unique port number for ssh access to the GIT repo for a cluster running on physical machines. If the default or assigned port is already in use, a new port is automatically selected. Ensure that the ports are available and check the log for more information.

|`org.uberfire.nio.git.dir`
|_.niogit directory_
|The location of Git repositories stored under `.niogit`, on an NFS mounted partition accessible to a {EAP} user.

|`org.uberfire.nio.git.ssh.hostport`
|_SSH host port_
|In a virtualized environment, the outside port to be used.

|`org.uberfire.nio.git.ssh.cert.dir`
|_.security directory_
|The location of the `.security` directory where local certificates will be stored.

|===
endif::PAM[]
ifdef::DM[]
[id='_cluster_properties_BRMS']
.Cluster Node Properties
[cols="1,1,2", frame="all", options="header"]
|===
|Property Name
|Value
|Description

|jboss.node.name
|nodeOne
|Node name unique within the cluster.

|org.uberfire.nio.git.daemon.port
|9418
|Port used by the VFS repo to accept client connections. The port must be unique for each cluster member. If the default or assigned port is already in use, a new port is automatically selected.

|org.uberfire.nio.git.ssh.port
|8003
|The unique port number for ssh access to the Git repo for a cluster running on physical machines. If the default or assigned port is already in use, a new port is automatically selected.

|org.uberfire.nio.git.daemon.host
|nodeOne
|The name of the daemon host machine in a physical cluster.

|org.uberfire.nio.git.ssh.host
|nodeOne
|The name of the SSH host machine in a physical cluster.
|===
endif::DM[]

ifdef::PAM[]

The following examples demonstrate how to configure a three node cluster in the `host.xml` and `host-slave.xml` files:

.Cluster nodeOne Configuration 
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeOne"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeOne"/>
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.host" value="nodeOne"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.dir" value="/mnt/jbpm/niogit" 
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodeone"
           boot-time="false"/>
</system-properties>
----
====
endif::PAM[]

ifdef::PAM[]

.Cluster nodeTwo Configuration
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeTwo"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeTwo" />
 <property name="org.uberfire.nio.git.daemon.port" value="9419" boot-time="false"/>
<property name="org.uberfire.nio.git.ssh.host" value="nodeTwo" />
<property name="org.uberfire.nio.git.ssh.port" value="8004" boot-time="false"/>
<property name="org.uberfire.nio.git.ssh.hostport" value="8004" boot-time="false"/>
 <property name="org.uberfire.nio.git.dir" value="/mnt/jbpm/niogit" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodetwo" boot-time="false"/>
</system-properties>
----
====
endif::PAM[]

ifdef::PAM[]

.Cluster nodeThree Configuration
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeThree"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeThree" />
 <property name="org.uberfire.nio.git.daemon.port" value="9420" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.host" value="nodeThree" />
 <property name="org.uberfire.nio.git.ssh.port" value="8005" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.hostport" value="8005" boot-time="false"/>
 <property name="org.uberfire.nio.git.dir" value="/mnt/jbpm/niogit" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodethree"
           boot-time="false"/>
</system-properties>
----
====
endif::PAM[]
ifdef::DM[]

.Cluster nodeOne Configuration
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeOne" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodeone" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeOne" />
 <property name="org.uberfire.nio.git.ssh.host" value="nodeOne" />
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
</system-properties>
----
====
endif::DM[]

ifdef::DM[]

.Cluster nodeTwo Configuration
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeTwo" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodetwo" boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeTwo" />
 <property name="org.uberfire.nio.git.ssh.host" value="nodeTwo" />
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
</system-properties>
----
====
endif::DM[]

ifdef::DM[]

.Cluster nodeThree Configuration
====
[source,xml]
----
<system-properties>
 <property name="jboss.node.name" value="nodeThree" boot-time="false"/>
 <property 
 <property name="org.uberfire.nio.git.daemon.port" value="9418" boot-time="false"/>
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.cert.dir" value="/tmp/jbpm/nodethree"
           boot-time="false"/>
 <property name="org.uberfire.nio.git.ssh.port" value="8003" boot-time="false"/>
 <property name="org.uberfire.nio.git.daemon.host" value="nodeThree" />
 <property name="org.uberfire.nio.git.ssh.host" value="nodeThree" />
 <property name="org.uberfire.nio.git.ssh.hostport" value="8003" boot-time="false"/>
</system-properties>
----
====
endif::DM[]


