[id='clustering-download-eap-bc-proc']
= Downloading and extracting {EAP} 7.1 and {PRODUCT}

Complete the steps in this section to download and install {EAP} 7.1 and download and repackage {PRODUCT} {PRODUCT_VERSION} for installation in a clustered environment.

.Procedure
. Install {EAP} 7.1 on each node of the cluster:
.. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product: Enterprise Application Platform*
* *Version: 7.1*
.. Click *Download* next to *Red Hat JBoss Enterprise Application Platform 7.1.0*. (`JBEAP-7.1.0/jboss-eap-7.1.0.zip`).
.. Extract the `jboss-eap-7.1.0.zip` file. In the following steps, `_EAP_HOME_` is the `jboss-eap-7.1/jboss-eap-7.1` directory.
. On the cluster node where the {EAP} domain controller will be started (the master node), navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal, and select the product and version from the drop-down options:
* *Product: {PRODUCT_SHORT}*
* *Version: {PRODUCT_VERSION}*
. Download  *{PRODUCT} {PRODUCT_VERSION_LONG}* {CENTRAL} Deployable for {EAP} 7 (`{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`).
. Extract the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip` file to a temporary directory. In the following commands this directory is called `__TEMP_DIR__`.
. Open the `_TEMP_DIR_/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_CENTRAL}-eap7-deployable/jboss-eap-7.1/standalone/deployments/{URL_COMPONENT_CENTRAL}.war/WEB-INF/web.xml/` file, uncomment the `<distributable/>` tag, and save the `web.xml` file.
. Copy the contents of `_TEMP_DIR_/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_CENTRAL}-eap7-deployable/jboss-eap-7.1` to `_EAP_HOME_`.
. Repackage the `{URL_COMPONENT_CENTRAL}.war` file:
.. Navigate to the `_TEMP_DIR_/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_CENTRAL}-eap7-deployable/jboss-eap-7.1/standalone/deployments/{URL_COMPONENT_CENTRAL}.war` directory.
.. Select the contents of the  `_TEMP_DIR_/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_CENTRAL}-eap7-deployable/jboss-eap-7.1/standalone/deployments/{URL_COMPONENT_CENTRAL}.war` directory and create the `{URL_COMPONENT_CENTRAL}.zip` file.
..  Rename `{URL_COMPONENT_CENTRAL}.zip` to `{URL_COMPONENT_CENTRAL}.war`. This is the file that you will use to deploy {CENTRAL} on the cluster nodes.
.. If desired, copy the new `{URL_COMPONENT_CENTRAL}.war` file to a location that is more convenient to deploy from.
