[id='clustering-smartrouter-install-proc']
= Clustering {KIE_SERVERS} with Smart Router

You can use Smart Router to aggregate multiple independent {KIE_SERVER} instances as though they are a single server. It performs the role of an intelligent load balancer because it can route requests to individual {KIE_SERVERS} and aggregate data from different {KIE_SERVERS}. Smart Router uses aliases to perform as a proxy. Smart Router performs the following tasks:

* Collects information from various server instances in a single client request
* Finds the correct server for a specific request
* Aggregates responses from different servers
* Provides efficient load balancing
* Manages changing environments, for example adding and removing server instances
* Manages registration with the {CONTROLLER}

This section describes how to install Smart Router and configure it for a {PRODUCT} runtime environment.

[NOTE]
====
Load balancing requests for Smart router cluster must be managed externally, using standard load balancing tools.
====

.Prerequisites
* {KIE_SERVER} is installed on each node of a {EAP} {EAP_VERSION} cluster.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product: {PRODUCT_SHORT}*
* *Version: {PRODUCT_VERSION}*
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons*.
. Extract the downloaded `{PRODUCT_FILE}-add-ons.zip` file to a temporary directory. The `{PRODUCT_INIT}-{PRODUCT_VERSION}-smart-router.jar` file is in the extracted `{PRODUCT_FILE}-add-ons` directory.
. Copy the `{PRODUCT_INIT}-{PRODUCT_VERSION}-smart-router.jar` file the location where you will run the file.

. From the temporary directory, enter the following command to start Smart Router:
+
[source]
----
java
-Dorg.kie.server.router.host=<ROUTER_HOST>
-Dorg.kie.server.router.port=<ROUTER_PORT>
-Dorg.kie.server.controller=<CONTROLLER_URL>
-Dorg.kie.server.controller.user=<CONTROLLER_USER>
-Dorg.kie.server.controller.pwd=<CONTROLLER_PWD>
-Dorg.kie.server.router.config.watcher.enabled=true
-Dorg.kie.server.router.repo=<NFS_STORAGE>
-jar rhpam-7.6-smart-router.jar
----
+
The properties in the preceding command have the following default values:
+
[source]
----
org.kie.server.router.host=localhost
org.kie.server.router.port=9000
org.kie.server.controller= N/A
org.kie.server.controller.user=kieserver
org.kie.server.controller.pwd=kieserver1!
org.kie.server.router.repo= <CURRENT_WORKING_DIR>
org.kie.server.router.config.watcher.enabled=false
----
+
[NOTE]
====
The router is capable of providing an aggregate sort, however the data returned when used through the management console is in raw format. Therefore, sorting is in whatever way  individual servers return.

Paging is supported in its standard format.
====
. Optional: To start Smart Router from the client side, use the Smart Router URL instead of the {KIE_SERVER} URL, for example:
+
[source]
----
KieServicesConfiguration config = KieServicesFactory.newRestConfiguration("http://smartrouter.example.com:9000", "USERNAME", "PASSWORD");
----
+
In this example, `smartrouter.example.com` is the Smart Router URL, and `USERNAME` and `PASSWORD` are the log in credentials for the Smart Router configuration.
+
`org.kie.server.controller` is the URL of the server controller, for example:
+
[source]
----
org.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller
----
+
`org.kie.server.router.config.watcher.enabled` is an optional setting to enable the watcher service system property.

. Optional: To start Smart Router with HTTPS enabled, use the TLS keystore properties, for example:
+
----
org.kie.server.router.tls.keystore = <KEYSTORE_PATH>
org.kie.server.router.tls.keystore.password = <KEYSTORE_PWD>
org.kie.server.router.tls.keystore.keyalias = <KEYSTORE_ALIAS>
org.kie.server.router.tls.port = <HTTPS_PORT>
-jar kie-server-router-proxy-7.10.0-SNAPSHOT.jar
----
+
`org.kie.server.router.tls.port` is a property used to configure the HTTPS port. The default HTTPS port value is `9443`.
