[id='clustering-ps-con_{context}']
= {KIE_SERVER} clusters in a runtime environment
ifdef::PAM[]
In a runtime environment, {KIE_SERVER} runs services that contain rules and processes that support business decisions.
endif::[]
The primary benefit of clustering a {KIE_SERVER} runtime environment is load balancing. If activity on one node of the cluster increases, that activity can be shared among the other nodes of the cluster to improve performance.

To create a {KIE_SERVER} clustered runtime environment, you download and extract {EAP} {EAP_VERSION} and {KIE_SERVER}. Then, you configure {EAP} {EAP_VERSION} for a cluster, start the cluster, and install {KIE_SERVER} on each cluster node.

ifdef::PAM[]
Optionally, you can then cluster the {HEADLESS_CONTROLLER} and Smart Router.
endif::[]

ifdef::DM[]
Optionally, you can then cluster the {HEADLESS_CONTROLLER}.
endif::[]

[NOTE]
====
Do not connect {KIE_SERVER} to {CENTRAL} in high availability (HA) on premise environments.

{CENTRAL} instances are not able to keep in sync with the status of each  {KIE_SERVER}. For example, if a {KIE_SERVER} is up but not in sync, {CENTRAL} will not be able to deploy through that instance.
====
