[id='clustering-smart-router-install-proc_{context}']
= Load-balancing {KIE_SERVER} instances with Smart Router

You can use Smart Router to aggregate multiple independent {KIE_SERVER} instances as though they are a single server. It performs the role of an intelligent load balancer because it can route requests to individual {KIE_SERVER} instances and aggregate data from different {KIE_SERVER} instances. Smart Router uses aliases to perform as a proxy.

.Prerequisites
* Multiple {KIE_SERVER} instances are installed.
+
[NOTE]
====
You do not need to configure {KIE_SERVER} as unmanaged for Smart Router.

An unmanaged {KIE_SERVER} does not connect to the controller.

For example, if you connect an unmanaged {KIE_SERVER} to Smart Router and register Smart Router with the controller, then {CENTRAL} contacts the unmanaged {KIE_SERVER} by using Smart Router.
====

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product: {PRODUCT_SHORT}*
* *Version: {PRODUCT_VERSION}*
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons*.
. Extract the downloaded `{PRODUCT_FILE}-add-ons.zip` file to a temporary directory. The `{PRODUCT_INIT}-{PRODUCT_VERSION}-smart-router.jar` file is in the extracted `{PRODUCT_FILE}-add-ons` directory.
. Copy the `{PRODUCT_INIT}-{PRODUCT_VERSION}-smart-router.jar` file to the location where you will run the file.

. Enter the following command to start Smart Router:
+
[source]
----
java
-Dorg.kie.server.router.host=<ROUTER_HOST>
-Dorg.kie.server.router.port=<ROUTER_PORT>
-Dorg.kie.server.controller=<CONTROLLER_URL>
-Dorg.kie.server.controller.user=<CONTROLLER_USER>
-Dorg.kie.server.controller.pwd=<CONTROLLER_PWD>
-Dorg.kie.server.router.config.watcher.enabled=true
-Dorg.kie.server.router.repo=<NFS_STORAGE>
-jar rhpam-7.7-smart-router.jar
----
+
The properties in the preceding command have the following default values:
+
[source]
----
org.kie.server.router.host=localhost
org.kie.server.router.port=9000
org.kie.server.controller= N/A
org.kie.server.controller.user=kieserver
org.kie.server.controller.pwd=kieserver1!
org.kie.server.router.repo= <CURRENT_WORKING_DIR>
org.kie.server.router.config.watcher.enabled=false
----
+
`org.kie.server.controller` is the URL of the server controller, for example:
+
[source]
----
org.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller
----
+
`org.kie.server.router.config.watcher.enabled` is an optional settings to enable the watcher service system property.
. On every {KIE_SERVER} instance that must connect to the Smart Router, set the `org.kie.server.router` system property to the Smart Router URL.
. To access Smart Router from the client side, use the Smart Router URL instead of the {KIE_SERVER} URL, for example:
+
[source]
----
KieServicesConfiguration config = KieServicesFactory.newRestConfiguration("http://smartrouter.example.com:9000", "USERNAME", "PASSWORD");
----
+
In this example, `smartrouter.example.com` is the Smart Router URL, and `USERNAME` and `PASSWORD` are the log in credentials for the Smart Router configuration.
