[id='clustering-runtime-managed-proc']
= Clustering a {KIE_SERVER} runtime environment managed by the {HEADLESS_CONTROLLER}

.Prerequiste
* An NFS server with a mounted partition accessible to a {EAP} user is available to the {HEADLESS_CONTROLLER}.

.Procedure
. Install and configure the {HEADLESS_CONTROLLER} as described in <<clustering-standalone-pc-proc_{context}>>.
. Install and configure Smart Router as described in <<clustering-smartrouter-pc-proc_{context}>>.

ifdef::DM[]
[NOTE]
====
This section is specifically intended for {CENTRAL} development environments where you want to cluster the Git repository. It is not necessary to create a clustered environment for {KIE_SERVER} production environments.
====
endif::[]

Red Hat supports clustering {PRODUCT} on {EAP} 7.1. To create a {PRODUCT} cluster, set up a {EAP} 7.1 cluster as described in  https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/configuring_a_red_hat_jboss_eap_7_cluster/[_Configuring a {EAP} 7 Cluster_], then following the instructions in this document.
