[id='clustering-bc-configure-domain-proc']
= Configuring a {EAP} 7.1 domain-mode cluster for {CENTRAL}
Configure the {CENTRAL} cluster in domain mode with Elasticsearch and the JMS broker resource adapter integrated with {EAP}. By using domain mode with a cluster, you can centrally manage and publish configurations for your servers.

[NOTE] 
====
These steps describe a basic cluster configuration. For more complex configurations, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/configuration_guide[_Red Hat JBoss EAP 7.1 Configuration Guide_].
====

.Prerequisites

* Elasticsearch is installed as described in <<clustering-elasticsearch-proc_{context}>>.
* {EAP} is installed on each node of the cluster as described in <<clustering-download-eap-bc-proc>>.
* An NFS server with a mounted partition is available.

.Procedure
. On the the master node of the cluster (where you will run the domain controller), open the `_EAP_HOME_/domain/configuration/domain.xml` file in a text editor.
. Make the following changes for each server group in the `server-groups` element:
.. Specify the `server-group name` and `jvm` name.
.. To enable high availability, change the `profile` to `"full-ha"` and the `socket-binding-group` to `"full-ha-sockets"`.
.. To prevent {CENTRAL} from running out of memory, increase the JVM maximum heap size to `1500m`.
+
[source]
----
<server-group name="some-server-group" profile="full-ha">
    <jvm name="some-jvm">
        <heap size="1000m" max-size="1500m"/>
    </jvm>
    <socket-binding-group ref="full-ha-sockets"/>
</server-group>
----
. Edit or add the following properties to the `<system-properties>` element and replace the following placeholders:
* `<ELASTICSEARCH_NODE_IP>` is the IP addresses where Elasticseach is installed.
* `<JMS_USER>` is a {EAP} application user. It is the user that {CENTRAL} uses to connect to the  embedded JMS broker. 
* `<JMS_USER_PASSWORD>` is the password for `<JMS_USER>`.
+
[source,xml]
----
<system-properties>
  <property name="appformer-jms-connection-mode" value="JNDI"/>
  <property name="appformer-jms-username" value="<JMS_USER>  "/>
  <property name="appformer-jms-password" value="<JMS_USER_PASSWORD>"/>
  <property name="org.appformer.ext.metadata.elastic.port" value="9300"/>
  <property name="org.appformer.ext.metadata.elastic.host" 
      value="<ELASTICSEARCH_NODE_IP>"/>
  <property name="org.appformer.ext.metadata.elastic.cluster" 
      value="kie-cluster"/>
  <property name="org.appformer.ext.metadata.index" value="elastic"/> 
  <property name="org.appformer.ext.metadata.elastic.retries" value="10"/>
  <property name="appformer-jms-connection-factory" value="java:/ConnectionFactory"/> 
</system-properties>
----
.  In the `<subsystem xmlns="urn:jboss:domain:messaging-activemq:2.0">` element, make the following changes:
.. Replace `<cluster password="${jboss.messaging.cluster.password:CHANGE ME!!}"/>` with `<cluster user="<CLUSTER_USER>" password="<CLUSTER_PWD>"/>` where `<CLUSTER_USER>` is the user used by {EAP} to form a messaging cluster and `<CLUSTER_PWD>` is the password for that user.
.. In the `security-setting` element , add the role of the `<JMS_USER>` to a new `role-name` element, for example:
+
[source]
----
<security-setting name="#">
    <role name="guest" send="true" consume="true" create-non-durable-queue="true" delete-non-durable-queue="true"/>
    <role name="admin" send="true" consume="true" create-non-durable-queue="true" delete-non-durable-queue="true"/>
</security-setting>
----
. Save the `domain.xml` file.
