[id='clustering-domain-con']
= Domain mode clusters

You can centrally store, manage, and publish configurations for your servers by using domain mode with a cluster. This section explains key concepts in domain mode clustering.

Domain controller: The domain controller is responsible for storing, managing, and publishing the general configuration for each node in the cluster. It is the central point from which nodes in a cluster obtain their configuration. The node that runs the domain controller is referred to as the master node and the other nodes of the cluster are referred to as slave nodes. The domain controller is configured with the `domain.xml` file.

Host controller: The host controller manages server instances on a specific node. You configure it to run one or more server instances. The domain controller can also interact with the host controllers on each system to manage the cluster. To reduce the number of running processes, a domain controller also acts as a host controller on the system it runs on. On slave nodes, the host controller is configured with the `host.xml` file.

Domain profile: A domain profile is a named configuration that a server can use to boot from. A domain controller can define multiple domain profiles that are consumed by different servers.

Server group: A server group is a set of server instances that are managed and configured together. You can manage configurations, deployments, socket bindings, modules, extensions, and system properties for each server group. You can assign a domain profile to a server group and every service in that group will use that domain profile as their configuration. 

In domain mode, a domain controller is started on the master node of the cluster. The configuration for the cluster is located in the domain controller. Next, a host controller is started on all of slave nodes of the cluster. Each host controller deployment configuration specifies how many server instances will be started on that system. When the host controller boots up, it starts as many server instances as it was configured to do. These server instances pull their configuration from the domain controller.

