[id='clustering-bc-configure-domain-proc_{context}']
= Configuring a {EAP} {EAP_VERSION} domain-mode cluster for {CENTRAL}
Configure the {CENTRAL} cluster in domain mode with {DATAGRID} and the JMS broker resource adapter integrated with {EAP}. By using domain mode with a cluster, you can centrally manage and publish your server configurations.

[NOTE]
====
These steps describe a basic cluster configuration. For more complex configurations, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/{EAP_VERSION}/html/configuration_guide[_Red Hat JBoss EAP {EAP_VERSION} Configuration Guide_].
====

.Prerequisites

* {DATAGRID} {DATAGRID_VERSION} is installed as described in <<clustering-datagrid-proc_clustering>>.
* {EAP} is installed on each node of the cluster as described in <<clustering-download-eap-bc-proc_clustering>>.
* An NFS server with a shared folder is available as described in xref:nfs-server-configure-proc_clustering[].

.Procedure
. On the master node of the cluster (where you will run the domain controller), open the `_EAP_HOME_/domain/configuration/domain.xml` file in a text editor.
. Make the following changes for each server group in the `server-groups` element:
.. Specify the `server-group name` and `jvm` name.
.. To enable high availability, change the `profile` to `"full-ha"` and the `socket-binding-group` to `"full-ha-sockets"`.
.. To prevent {CENTRAL} from running out of memory, increase the JVM maximum heap size to `1500m`.
+
[source]
----
<server-group name="some-server-group" profile="full-ha">
    <jvm name="some-jvm">
        <heap size="1000m" max-size="1500m"/>
    </jvm>
    <socket-binding-group ref="full-ha-sockets"/>
</server-group>
----
. Edit or add the following properties to the `<system-properties>` element and replace the following placeholders:
* `<DATA_GRID_NODE_IP>` is the IP address where {DATAGRID} is installed.
* `<JMS_USER>` is a {EAP} application user. It is the user that {CENTRAL} uses to connect to the  embedded JMS broker.
* `<JMS_USER_PASSWORD>` is the password for `<JMS_USER>`.
+
[source,xml]
----
<system-properties>
  <property name="appformer-jms-connection-mode" value="JNDI"/>
  <property name="appformer-jms-username" value="<JMS_USER>"/>
  <property name="appformer-jms-password" value="<JMS_USER_PASSWORD>"/>
  <property name="org.appformer.ext.metadata.infinispan.port"
     value="11222"/>
  <property name="org.appformer.ext.metadata.infinispan.host"
     value="<DATA_GRID_NODE_IP>"/>
  <property name="org.appformer.ext.metadata.infinispan.realm"
     value="ApplicationRealm"/>
  <property name="org.appformer.ext.metadata.infinispan.username"
     value=""/>
  <property name="org.appformer.ext.metadata.infinispan.password"
     value=""/>
  <property name="org.appformer.ext.metadata.infinispan.cluster"
     value="kie-cluster"/>
  <property name="org.appformer.ext.metadata.index"
     value="infinispan"/>
  <property name="appformer-jms-connection-factory"
     value="java:/ConnectionFactory"/>
</system-properties>
----
.  In the `<subsystem xmlns="urn:jboss:domain:messaging-activemq:2.0">` element, make the following changes:
.. Replace `<cluster password="${jboss.messaging.cluster.password:CHANGE ME!!}"/>` with `<cluster user="<CLUSTER_USER>" password="<CLUSTER_PWD>"/>` where `<CLUSTER_USER>` is the user used by {EAP} to form a messaging cluster and `<CLUSTER_PWD>` is the password for that user.
.. In the `security-setting` element , add the role of the `<JMS_USER>` to a new `role-name` element, for example:
+
[source]
----
<security-setting name="#">
    <role name="guest" send="true" consume="true" create-non-durable-queue="true" delete-non-durable-queue="true"/>
    <role name="admin" send="true" consume="true" create-non-durable-queue="true" delete-non-durable-queue="true"/>
</security-setting>
----
. Save the `domain.xml` file.
