[id='clustering-download-eap-ps-proc_{context}']
= Downloading and extracting {EAP} {EAP_VERSION} and {KIE_SERVER}
Complete the steps in this section to download and install {EAP} {EAP_VERSION} and {KIE_SERVER} for installation in a clustered environment.

.Procedure
. Download {EAP} {EAP_VERSION} on each node of the cluster:
.. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required) and select the product and version from the drop-down options:
* *Product: Enterprise Application Platform*
* *Version: {EAP_VERSION}*
.. Click *Download* next to *{EAP_LONG} {EAP_VERSION_LONG}*. (`jboss-eap-{EAP_VERSION_LONG}.zip`).
. Extract the `jboss-eap-{EAP_VERSION_LONG}.zip` file. The `jboss-eap-{EAP_VERSION}/jboss-eap-{EAP_VERSION}` directory is referred to as `_EAP_HOME_`.
. Download and apply the latest {EAP} patch, if available.
. Download {KIE_SERVER}:
.. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal and select the product and version from the drop-down options:
* *PRODUCT:* {PRODUCT_PAM_SHORT}
* *Version:* {PRODUCT_VERSION_LONG}
.. Download  *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} {KIE_SERVER} for All Supported EE8 Containers* (`{PRODUCT_FILE}-kie-server-ee8.zip`).
. Extract the `{PRODUCT_FILE}-kie-server-ee8.zip` archive to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the
ifdef::PAM[]
`__TEMP_DIR__/{PRODUCT_FILE}-kie-server-ee8/{PRODUCT_FILE}-kie-server-ee8/kie-server.war`
endif::PAM[]
ifdef::DM[]
`__TEMP_DIR__/{PRODUCT_FILE}-kie-server-ee8/{PRODUCT_FILE}-kie-server-ee8/kie-server.war`
endif::DM[]
 directory to `__EAP_HOME__/standalone/deployments/`.
+
WARNING: Ensure the names of the {PRODUCT} deployments you copy do not conflict with your existing deployments in the {EAP} instance.
. Copy the contents of the
ifdef::PAM[]
`__TEMP_DIR__/{PRODUCT_FILE}-kie-server-ee8/{PRODUCT_FILE}-kie-server-ee8/SecurityPolicy/`
endif::PAM[]
ifdef::DM[]
`__TEMP_DIR__/{PRODUCT_FILE}-kie-server-ee8/{PRODUCT_FILE}-kie-server-ee8/SecurityPolicy/`
endif::DM[]
 to `__EAP_HOME__/bin`.
. When prompted to overwrite files, click *Replace*.
. In the `__EAP_HOME__/standalone/deployments/` directory, create an empty file named `kie-server.war.dodeploy`. This file ensures that {KIE_SERVER} is automatically deployed when the server starts.
. Download and apply the latest {PRODUCT} patch, if available.

. Navigate to the `__EAP_HOME__/bin` directory.
. Create a user with the `kie-server` role that you will use to log in to {KIE_SERVER}.
+
ifdef::PAM[]
[source,bash]
----
$ ./bin/jboss-cli.sh --commands="embed-server --std-out=echo,/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity(identity=<USERNAME>),/subsystem=elytron/filesystem-realm=ApplicationRealm:set-password(identity=<USERNAME>, clear={password='<PASSWORD>'}),/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity-attribute(identity=<USERNAME>, name=role, value=['kie-server'])"
----
endif::[]
ifdef::DM[]
[source,bash]
----
$ ./bin/jboss-cli.sh --commands="embed-server --std-out=echo,/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity(identity=<USERNAME>),/subsystem=elytron/filesystem-realm=ApplicationRealm:set-password(identity=<USERNAME>, clear={password='<PASSWORD>'}),/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity-attribute(identity=<USERNAME>, name=role, value=['kie-server'])"
----
endif::[]
. Make a note of your user names and passwords.

ifdef::DM[]
. To start the cluster, navigate to `__EAP_HOME__/bin` and enter one of the following commands:
** On Linux or UNIX-based systems:
+
[source,bash]
----
$ ./standalone.sh -c standalone-full.xml
----
** On Windows:
+
[source,bash]
----
standalone.bat -c standalone-full.xml
----
endif::[]
