[id='components-con']
= {PRODUCT} components

{PRODUCT} is made up of {CENTRAL} and {KIE_SERVER}.

* {CENTRAL} is the graphical user interface where you create and manage business rules. You can install {CENTRAL} in a {EAP} instance or on the Red Hat OpenShift Container Platform (OpenShift).
+
{CENTRAL} is also available as a standalone JAR file. You can use the {CENTRAL} standalone JAR file to run {CENTRAL} without needing to deploy it to an application server.

* {KIE_SERVER} is the server where processes, rules, and other artifacts are executed. It is used to instantiate and execute processes and rules and solve planning problems. You can install {KIE_SERVER} in a {EAP} instance, on OpenShift, in an Oracle WebLogic server instance, in an IBM WebSphere Application Server instance, or as a part of Spring Boot application.
+
You can configure {KIE_SERVER} to run in managed or unmanaged mode. If {KIE_SERVER} is unmanaged, you must manually create and maintain KIE containers (deployment units). A KIE container is a specific version of a project. If {KIE_SERVER} is managed, the {CONTROLLER} manages the {KIE_SERVER} configuration and you interact with the {CONTROLLER} to create and maintain KIE containers.
+
ifeval::["{context}" == "install-on-eap"]
The {CONTROLLER} is integrated with {CENTRAL}. If you install {CENTRAL} on {EAP}, use the Execution Server page to create and maintain KIE containers. However, if you do not install {CENTRAL}, you can install the {HEADLESS_CONTROLLER} and use the REST API or the {KIE_SERVER} Java Client API to interact with it.
endif::[]
ifeval::["{context}" == "install-on-jws"]
On a {JWS} installation, you can install {KIE_SERVER} and the {HEADLESS_CONTROLLER}. Alternatively, you can run the standalone {CENTRAl} JAR file.
endif::[]
ifeval::["{context}" == "planning"]
The {CONTROLLER} is integrated with {CENTRAL}. If you install {CENTRAL} on {EAP}, use the Execution Server page to create and maintain KIE containers. However, if you do not install {CENTRAL}, you can install the {HEADLESS_CONTROLLER} and use the REST API or the {KIE_SERVER} Java Client API to interact with it.

* {PLANNER} is integrated in {CENTRAL} and {KIE_SERVER}. It is a lightweight, embeddable planning engine that optimizes planning problems. {PLANNER} helps Java programmers solve planning problems efficiently, and it combines optimization heuristics and metaheuristics with efficient score calculations.
endif::[]
