[id='controller-eap-users-create-proc']

= Creating a {HEADLESS_CONTROLLER} user
Before you can use the {HEADLESS_CONTROLLER}, you must create a user that has the `kie-server` role.

.Prerequisite
The {HEADLESS_CONTROLLER} is installed in the base directory of the {EAP} installation (`__EAP_HOME__`).

.Procedure
. In a terminal application, navigate to the `__EAP_HOME__/bin` directory.
. Enter the following command and replace `<USER_NAME>` and `<PASSWORD>` with the user name and password of your choice.
+
ifdef::PAM[]
[source,bash]
----
$ ./add-user.sh -a --user <USER_NAME> --password <PASSWORD> --role kie-server
----
endif::[]
ifdef::DM[]
[source,bash]
----
$ ./add-user.sh -a --user <username> --password <password> --role kie-server
----
endif::[]
+
[NOTE]
====
Make sure that the specified user name is not the same as an existing user, role, or group. For example, do not create a user with the user name `admin`.

The password must have at least eight characters and must contain at least one number and one non-alphanumeric character, but not & (ampersand).
====
+
. Make a note of your user name and password.
