[id='controller-eap-install-proc_{context}']

= Installing the {HEADLESS_CONTROLLER}

You can install the {HEADLESS_CONTROLLER} and use the REST API or the {KIE_SERVER} Java Client API to interact with it.

.Prerequisites
* A backed-up {EAP} installation version 7.1 or higher is available. The base directory of the {EAP} installation is referred to as `__EAP_HOME__`.
* Sufficient user permissions to complete the installation are granted.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (the `{PRODUCT_FILE}-add-ons.zip` file).
. Unzip the `{PRODUCT_FILE}-add-ons.zip` file. The `{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7.zip` file is in the unzipped directory.
. Extract the `{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7` archive to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the `__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7/controller.war` directory to `__EAP_HOME__/standalone/deployments/`.
+
WARNING: Ensure that the names of the {HEADLESS_CONTROLLER} deployments you are copying do not conflict with your existing deployments in the {EAP} instance.
. Copy the contents of the `__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7/SecurityPolicy/` directory to `__EAP_HOME__/bin`. When asked to overwrite files, select *Yes*.
. In the `__EAP_HOME__/standalone/deployments/` directory, create an empty file named `controller.war.dodeploy`. This file ensures that the {HEADLESS_CONTROLLER} is automatically deployed when the server starts.
