[id='controller-eap-install-proc_{context}']

= Installing the {HEADLESS_CONTROLLER}

You can install the {HEADLESS_CONTROLLER} and use the REST API or the {KIE_SERVER} Java Client API to interact with it.

.Prerequisites
* A backed-up {EAP} installation version {EAP_VERSION} is available. The base directory of the {EAP} installation is referred to as `__EAP_HOME__`.
* Sufficient user permissions to complete the installation are granted.

.Procedure
. Navigate to the https://www.ibm.com/support/pages/node/6596913[IBM Business Automation Manager Open Editions Download Document]  and follow the instructions to download *{PRODUCT} {PRODUCT_VERSION} - Add-ons*.
. Extract the `{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-AO.zip` file. The `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-ee7.zip` file is in the extracted directory.
. Extract the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-ee7.zip` archive to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the `__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-ee7/controller.war` directory to `__EAP_HOME__/standalone/deployments/`.
+
WARNING: Ensure that the names of the {HEADLESS_CONTROLLER} deployments you copy do not conflict with your existing deployments in the {EAP} instance.
. Copy the contents of the `__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-ee7/SecurityPolicy/` directory to `__EAP_HOME__/bin`.
. When prompted to overwrite files, select *Yes*.
. In the `__EAP_HOME__/standalone/deployments/` directory, create an empty file named `controller.war.dodeploy`. This file ensures that the {HEADLESS_CONTROLLER} is automatically deployed when the server starts.
