[id='controller-eap-users-create-proc_{context}']

= Creating a {HEADLESS_CONTROLLER} user
Before you can use the {HEADLESS_CONTROLLER}, you must create a user that has the `kie-server` role.

.Prerequisites
* The {HEADLESS_CONTROLLER} is installed in the base directory of the {EAP} installation (`__EAP_HOME__`).

.Procedure
. In a terminal application, navigate to the `__EAP_HOME__/bin` directory.
. Enter the following command and replace `<USERNAME>` and `<PASSWORD>` with the user name and password of your choice.
+
ifdef::PAM[]
[source,bash]
----
$ ./bin/jboss-cli.sh --commands="embed-server --std-out=echo,/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity(identity=<USERNAME>),/subsystem=elytron/filesystem-realm=ApplicationRealm:set-password(identity=<USERNAME>, clear={password='<PASSWORD>'}),/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity-attribute(identity=<USERNAME>, name=role, value=['kie-server'])"
----
endif::[]
ifdef::DM[]
[source,bash]
----
$ ./bin/jboss-cli.sh --commands="embed-server --std-out=echo,/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity(identity=<USERNAME>),/subsystem=elytron/filesystem-realm=ApplicationRealm:set-password(identity=<USERNAME>, clear={password='<PASSWORD>'}),/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity-attribute(identity=<USERNAME>, name=role, value=['kie-server'])"
----
endif::[]
+
[NOTE]
====
Make sure that the specified user name is not the same as an existing user, role, or group. For example, do not create a user with the user name `admin`.

The password must have at least eight characters and must contain at least one number and one non-alphanumeric character, but not & (ampersand).
====
+
. Make a note of your user name and password.
