[id='controller-eap-run-proc']
= Running the {HEADLESS_CONTROLLER}
After you have installed the {HEADLESS_CONTROLLER} on {EAP}, use this procedure to run the {HEADLESS_CONTROLLER}.

.Prerequisite
The {HEADLESS_CONTROLLER} is installed and configured in the base directory of the {EAP} installation (`__EAP_HOME__`).

.Procedure
. In a terminal application, navigate to `__EAP_HOME__/bin`.
. Enter the following command:
** On Linux or UNIX-based systems:
+
[source,bash]
----
$ ./standalone.sh
----
** On Windows:
+
[source,bash]
----
standalone.bat
----
ifeval::["{context}" == "install-on-eap"]
. To verify that the {HEADLESS_CONTROLLER} is working on {EAP}, enter the following command where `<CONTROLLER>` and `<CONTROLLER_PWD>` is the user name and password combination that you created in <<controller-eap-users-create-proc>>. The output of this command provides information about the {KIE_SERVER} instance.
endif::[]
ifeval::["{context}" == "execution-server"]
. To verify that the {HEADLESS_CONTROLLER} is working on {EAP}, enter the following command where `<CONTROLLER>` and `<CONTROLLER_PWD>` is the user name and password. The output of this command provides information about the {KIE_SERVER} instance.
endif::[]
+
[source]
----
curl -X GET "http://<HOST>:<PORT>/controller/rest/controller/management/servers" -H  "accept: application/xml" -u '<CONTROLLER>:<CONTROLLER_PWD>'
----

[NOTE]
====
Alternatively, you can use the {KIE_SERVER} Java API Client to access the {HEADLESS_CONTROLLER}.
====
