[id='controller-jws-install-proc']
= Downloading and installing the {HEADLESS_CONTROLLER}

You can configure {KIE_SERVER} to run in managed or unmanaged mode. If {KIE_SERVER} is unmanaged, you must manually create and maintain KIE containers (deployment units). If {KIE_SERVER} is managed, the {CONTROLLER} manages the {KIE_SERVER} configuration and you interact with the {CONTROLLER} to create and maintain KIE containers.

The {CONTROLLER} is integrated with {CENTRAL}. If you install {CENTRAL}, use the *Execution Server* page to create and maintain KIE containers. However, if you do not install {CENTRAL}, you can install the {HEADLESS_CONTROLLER} and use the REST API or the {KIE_SERVER} Java Client API to interact with it.

.Prerequisites
* A {JWS} {JWS_VERSION_LONG} or higher server installation is available. The base directory of the {JWS} installation is referred to as `__JWS_HOME__`.
* Sufficient user permissions to complete the installation are granted.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (the `{PRODUCT_FILE}-add-ons.zip` file).
. Unzip the `{PRODUCT_FILE}-add-ons.zip` file. The `{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7.zip` file is in the unzipped directory.
. Extract the
ifdef::PAM[]
`{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-jws.zip`
endif::PAM[]
ifdef::DM[]
`{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-jws.zip`
endif::DM[]
 archive to a temporary directory. In the following examples this directory is called `__TEMP_DIR__`.
. Copy the
ifdef::PAM[]
`__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-jws.zip/controller.war`
endif::PAM[]
ifdef::DM[]
`__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-jws.zip/controller.war`
endif::DM[]
 directory to the `_JWS_HOME_/tomcat/webapps` directory.
+
[NOTE] 
====
Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the {JWS} instance.
====

. Remove the `.war` extensions from the `controller.war` folder.
. Copy the contents of the
ifdef::PAM[]
`__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-jws/SecurityPolicy/`
endif::PAM[]
ifdef::DM[]
`__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-jws/SecurityPolicy/`
endif::DM[] 
 directory to `__JWS_HOME__/bin`. When asked to overwrite files, select *Yes*.
. Add the `kie-server` role and user to the `_JWS_HOME_/tomcat/conf/tomcat-users.xml` file. In the following example,  `<USERNAME>` and `<PASSWORD>` are the user name and password of your choice:
+
[source]
----
<role rolename="kie-server"/>
<user username="<USER_NAME>" password="<PASSWORD>" roles="kie-server"/>
----

. Complete one of the following tasks in the `_JWS_HOME_/tomcat/bin` directory of the instance running {KIE_SERVER}:
+
* On Linux or UNIX, create the `setenv.sh` file with the following content:
+
ifdef::PAM[]
[source]
----
CATALINA_OPTS="-Xmx1024m -Dorg.jboss.logging.provider=jdk
 -Dorg.kie.server.controller.user=<CONTROLLER_USER> 
 -Dorg.kie.server.controller.pwd=<CONTROLLER_PWD> 
 -Dorg.kie.server.id=<KIE_SERVER_ID>
 -Dorg.kie.server.location=http://<HOST>:<PORT>/kie-server/services/rest/server
 -Dorg.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller"
----
endif::PAM[]
ifdef::DM[]
[source]
----
CATALINA_OPTS="-Xmx1024m 
 -Dorg.jbpm.server.ext.disabled=true 
 -Dorg.jbpm.ui.server.ext.disabled=true 
 -Dorg.jbpm.case.server.ext.disabled=true 
 -Dorg.kie.server.controller.user=<CONTROLLER_USER> 
 -Dorg.kie.server.controller.pwd=<CONTROLLER_PWD> 
 -Dorg.kie.server.id=<KIE_SERVER_ID>
 -Dorg.kie.server.location=http://<HOST>:<PORT>/kie-server/services/rest/server
 -Dorg.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller"
----
endif::DM[]
* On Windows, add the following content to the `setenv.bat` file:
+
ifdef::PAM[]
[source]
----
set CATALINA_OPTS=-Xmx1024m -Dorg.jboss.logging.provider=jdk
 -Dorg.kie.server.controller.user=<CONTROLLER_USER> 
 -Dorg.kie.server.controller.pwd=<CONTROLLER_PWD> 
 -Dorg.kie.server.id=<KIE_SERVER_ID>
 -Dorg.kie.server.location=http://<HOST>:<PORT>/kie-server/services/rest/server
 -Dorg.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller
----
endif::PAM[]
ifdef::DM[]
[source]
----
set CATALINA_OPTS= -Xmx1024m 
 -Dorg.jbpm.server.ext.disabled=true 
 -Dorg.jbpm.ui.server.ext.disabled=true 
 -Dorg.jbpm.case.server.ext.disabled=true 
 -Dorg.kie.server.controller.user=<CONTROLLER_USER> 
 -Dorg.kie.server.controller.pwd=<CONTROLLER_PWD> 
 -Dorg.kie.server.id=<KIE_SERVER_ID>
 -Dorg.kie.server.location=http://<HOST>:<PORT>/kie-server/services/rest/server
 -Dorg.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller
----
endif::DM[]

. In the `_JWS_HOME_/tomcat/bin` directory of the instance running the {HEADLESS_CONTROLLER}, create a readable `setenv.sh` file with the following content:
+
`CATALINA_OPTS="-Dorg.kie.server.user=<USERNAME> -Dorg.kie.server.pwd=<USER_PWD>"`
+
. To start the {HEADLESS_CONTROLLER}, enter one of the following commands in the `_JWS_HOME_/tomcat/bin` directory:
+
** On Linux or UNIX-based systems:
+
[source,bash]
----
$ ./startup.sh
----
** On Windows:
+
[source,bash]
----
startup.bat
----
. After a few minutes, review the the `_JWS_HOME_/tomcat/logs` directory and correct any errors.
. To verify that the {HEADLESS_CONTROLLER} is working on {JWS}, enter the following command. In this command, replace `<CONTROLLER>` and `<CONTROLLER_PWD>` with the values in the `tomcat-users.xml` file. The output of this command provides information about the {KIE_SERVER} instance.
+
[source]
----
curl -X GET "http://<HOST>:<PORT>/controller/rest/controller/management/servers" -H  "accept: application/xml" -u '<CONTROLLER>:<CONTROLLER_PWD>'
----

[NOTE]
====
Alternatively, you can use the {KIE_SERVER} Java API Client to access the {HEADLESS_CONTROLLER}.
====
