[id='controller-jws-install-proc_{context}']
= Downloading and installing the {HEADLESS_CONTROLLER}

You can configure {KIE_SERVER} to run in managed or unmanaged mode. If {KIE_SERVER} is unmanaged, you must manually create and maintain KIE containers (deployment units). If {KIE_SERVER} is managed, the {CONTROLLER} manages the {KIE_SERVER} configuration and you interact with the {CONTROLLER} to create and maintain KIE containers.

The {CONTROLLER} is integrated with {CENTRAL}. If you install {CENTRAL}, use the *Execution Server* page to create and maintain KIE containers. However, if you do not install {CENTRAL}, you can install the {HEADLESS_CONTROLLER} and use the REST API or the {KIE_SERVER} Java Client API to interact with it.

.Prerequisites
* The *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_FILE}-add-ons.zip`) file has been downloaded, as described in <<install-download-proc_{context}>>.
ifeval::["{context}" == "install-on-jws"]
* A {JWS} {JWS_VERSION_LONG} server installation is available. The base directory of the {JWS} installation is referred to as `_JWS_HOME_`.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
* A {TOMCAT} {TOMCAT_VERSION} installation is available. The base directory of the {TOMCAT} installation is referred to as `_TOMCAT_HOME_`.
endif::[]
* Sufficient user permissions to complete the installation are granted.

.Procedure
. Extract the `{PRODUCT_FILE}-add-ons.zip` file. The `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-jws.zip` file is in the extracted directory.
. Extract the
ifdef::PAM[]
`{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-jws.zip`
endif::PAM[]
ifdef::DM[]
`{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-jws.zip`
endif::DM[]
 archive to a temporary directory. In the following examples this directory is called `_TEMP_DIR_`.
. Copy the
ifdef::PAM[]
`_TEMP_DIR_/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-jws.zip/controller.war`
endif::PAM[]
ifdef::DM[]
`_TEMP_DIR_/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-jws.zip/controller.war`
endif::DM[]
 directory to the
ifeval::["{context}" == "install-on-jws"]
`_JWS_HOME_/tomcat/webapps`
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`_TOMCAT_HOME_/tomcat/webapps`
endif::[]
  directory.
+
[NOTE]
====
Ensure the names of the {PRODUCT} deployments you copy do not conflict with your existing deployments in the
ifeval::["{context}" == "install-on-jws"]
{JWS}
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
{TOMCAT}
endif::[]
 instance.
====

. Remove the `.war` extensions from the `controller.war` folder.
. Copy the contents of the
ifdef::PAM[]
`_TEMP_DIR_/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-jws/SecurityPolicy/`
endif::PAM[]
ifdef::DM[]
`_TEMP_DIR_/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-controller-jws/SecurityPolicy/`
endif::DM[]
 directory to
ifeval::["{context}" == "install-on-jws"]
 `_JWS_HOME_/bin`
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
 `_TOMCAT_HOME_/bin`
endif::[]
. When prompted to overwrite files, select *Yes*.
. Add the `kie-server` role and user to the
ifeval::["{context}" == "install-on-jws"]
`_JWS_HOME_/tomcat/conf/tomcat-users.xml`
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`_TOMCAT_HOME_/tomcat/conf/tomcat-users.xml`
endif::[]
 file. In the following example,  `<USER_NAME>` and `<PASSWORD>` are the user name and password of your choice:
+
[source]
----
<role rolename="kie-server"/>
<user username="<USER_NAME>" password="<PASSWORD>" roles="kie-server"/>
----

. Complete one of the following tasks in the
ifeval::["{context}" == "install-on-jws"]
`_JWS_HOME_/tomcat/bin`
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`_TOMCAT_HOME_/tomcat/bin`
endif::[]
 directory of the instance running {KIE_SERVER}:
+
* On Linux or UNIX, create the `setenv.sh` file with the following content:
+
ifdef::PAM[]
[source]
----
CATALINA_OPTS="-Xmx1024m
 -Dorg.jboss.logging.provider=jdk
 -Dorg.kie.server.controller.user=<CONTROLLER_USER>
 -Dorg.kie.server.controller.pwd=<CONTROLLER_PWD>
 -Dorg.kie.server.id=<KIE_SERVER_ID>
 -Dorg.kie.server.location=http://<HOST>:<PORT>/kie-server/services/rest/server
 -Dorg.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller"
----
endif::PAM[]
ifdef::DM[]
[source]
----
CATALINA_OPTS="-Xmx1024m
 -Dorg.jboss.logging.provider=jdk
 -Dorg.jbpm.server.ext.disabled=true
 -Dorg.jbpm.ui.server.ext.disabled=true
 -Dorg.jbpm.case.server.ext.disabled=true
 -Dorg.kie.server.controller.user=<CONTROLLER_USER>
 -Dorg.kie.server.controller.pwd=<CONTROLLER_PWD>
 -Dorg.kie.server.id=<KIE_SERVER_ID>
 -Dorg.kie.server.location=http://<HOST>:<PORT>/kie-server/services/rest/server
 -Dorg.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller"
----
endif::DM[]

* On Windows, add the following content to the `setenv.bat` file:
+
ifdef::PAM[]
[source]
----
set CATALINA_OPTS=-Xmx1024m -Dorg.jboss.logging.provider=jdk
 -Dorg.kie.server.controller.user=<CONTROLLER_USER>
 -Dorg.kie.server.controller.pwd=<CONTROLLER_PWD>
 -Dorg.kie.server.id=<KIE_SERVER_ID>
 -Dorg.kie.server.location=http://<HOST>:<PORT>/kie-server/services/rest/server
 -Dorg.kie.server.controller=http://<HOST>:<PORT>/controller/rest/controller
----
endif::PAM[]
ifdef::DM[]
[source]
----
set CATALINA_OPTS= -Xmx1024m
 -Dorg.jbpm.server.ext.disabled=true
 -Dorg.jbpm.ui.server.ext.disabled=true
 -Dorg.jbpm.case.server.ext.disabled=true
 -Dorg.kie.server.controller.user=<CONTROLLER_USER>
 -Dorg.kie.server.controller.pwd=<CONTROLLER_PWD>
 -Dorg.kie.server.id=<KIE_SERVER_ID>
 -Dorg.kie.server.location=http://<HOST>:<PORT>/kie-server/services/rest/server
 -Dorg.kie.server.controller=http://<CONTROLLER_HOST>:<CONTROLLER_PORT>/controller/rest/controller
----
endif::DM[]
+
In the preceding examples, replace the following variables:

* Replace `<CONTROLLER_USER>` and `<CONTROLLER_PWD>` with the user name and password for the `kie-server` role that you defined earlier in this procedure.
* Replace `<KIE_SERVER_ID>` with a unique identifier.
* Replace `<CONTROLLER_HOST>:<CONTROLLER_PORT>` with the IP address (host and port) of the controller. If you use the same server for {KIE_SERVER} and the controller, `<CONTROLLER_HOST>:<CONTROLLER_PORT>` is `localhost:8080`.

. In the
ifeval::["{context}" == "install-on-jws"]
`_JWS_HOME_/tomcat/bin`
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`_TOMCAT_HOME_/tomcat/bin`
endif::[]
 directory of the instance running the {HEADLESS_CONTROLLER}, create a readable `setenv.sh` file with the following content, where `<USERNAME>` is the {KIE_SERVER} user and `<USER_PWD>` is the password for that user:
+
`CATALINA_OPTS="-Dorg.kie.server.user=<USERNAME> -Dorg.kie.server.pwd=<USER_PWD>"`
+
. To start the {HEADLESS_CONTROLLER}, enter one of the following commands in the
ifeval::["{context}" == "install-on-jws"]
`_JWS_HOME_/tomcat/bin`
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`_TOMCAT_HOME_/tomcat/bin`
endif::[]
directory:
+
** On Linux or UNIX-based systems:
+
[source,bash]
----
$ ./startup.sh
----
** On Windows:
+
[source,bash]
----
startup.bat
----
. After a few minutes, review the
ifeval::["{context}" == "install-on-jws"]
`_JWS_HOME_/tomcat/logs`
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`_TOMCAT_HOME_/tomcat/logs`
endif::[]
 directory and correct any errors.
. To verify that the {HEADLESS_CONTROLLER} is working correctly, enter `\http://<CONTROLLER_HOST>:<CONTROLLER_PORT>/controller/rest/controller/management/servers` in a web browser. If you use the same server for {KIE_SERVER} and the controller, `<CONTROLLER_HOST>:<CONTROLLER_PORT>` is `localhost:8080`.
. Enter the user name and password stored in the `tomcat-users.xml` file.
