[id='eap_execution_server_configure_proc']
= Configuring {KIE_SERVER} with the integrated {CONTROLLER}

[NOTE]
====
Only make the changes described in this section if {KIE_SERVER} will be managed by {CENTRAL} and you installed {PRODUCT} from the ZIP files. If you did not install {CENTRAL}, you can use the {HEADLESS_CONTROLLER} to manage {KIE_SERVER}, as described in <<controller-con>>.
====

{KIE_SERVER} can be managed or it can be unmanaged. If {KIE_SERVER} is unmanaged, you must manually create and maintain KIE containers (deployment units). If {KIE_SERVER} is managed, the {CONTROLLER} manages the {KIE_SERVER} configuration and you interact with the {CONTROLLER} to create and maintain KIE containers.

The {CONTROLLER} is integrated with {CENTRAL}. If you install {CENTRAL}, you can use the *Execution Server* page in {CENTRAL} to interact with the {CONTROLLER}.

If you installed {PRODUCT} from the ZIP files, you must edit the `standalone-full.xml` file in both the {KIE_SERVER} and {CENTRAL} installations to configure {KIE_SERVER} with the integrated {CONTROLLER}.

.Prerequisites
ifeval::["{context}" == "install-on-eap"]
* {CENTRAL} and {KIE_SERVER} are installed in the base directory of the {EAP} installation (`__EAP_HOME__`) as described in the following sections:
+
** <<eap-dm-install-proc>>
** <<eap_execution_server_download_install_proc>>
endif::[]
ifeval::["{context}" == "execution-server"]
* {CENTRAL} and {KIE_SERVER} are installed in the base directory of the {EAP} installation (`__EAP_HOME__`).
endif::[]
+
[NOTE]
====
You should install {CENTRAL} and {KIE_SERVER} on different servers in production environments. However, if you install {KIE_SERVER} and {CENTRAL} on the same server, for example in a development environment, make the changes described in this section in the shared `standalone-full.xml` file.
====
//* On {KIE_SERVER} nodes, a user with the `kie-server` role exists.
* On {CENTRAL} server nodes, a user with the `rest-all` role exists.
+
ifeval::["{context}" == "install-on-eap"]
For more information, see <<eap-users-create-proc>>.
endif::[]

.Procedure
. In the {CENTRAL}  `__EAP_HOME__/standalone/configuration/standalone-full.xml` file, uncomment the following properties in the `<system-properties>` section and replace `<USERNAME>` and `<USER_PWD>` with the credentials of a user with the `kie-server` role:
+
[source,xml]
----
   <property name="org.kie.server.user" value="<USERNAME>"/>
   <property name="org.kie.server.pwd" value="<USER_PWD>"/>
----
. In the {KIE_SERVER}  `__EAP_HOME__/standalone/configuration/standalone-full.xml` file, uncomment the following properties in the `<system-properties>` section.
+
[source,xml]
----
  <property name="org.kie.server.controller.user" value="<CONTROLLER_USER>"/>
  <property name="org.kie.server.controller.pwd" value="<CONTROLLER_PWD>"/>
  <property name="org.kie.server.id" value="<KIE_SERVER_ID>"/>
  <property name="org.kie.server.location" value="http://<HOST>:<PORT>/kie-server/services/rest/server"/>
  <property name="org.kie.server.controller" value="<CONTROLLER_URL>"/>
----
. Replace the following values:
* Replace `<CONTROLLER_USER>` and `<CONTROLLER_PWD>` with the credentials of a user with the `rest-all` role.
* Replace `<KIE_SERVER_ID>` with the ID or name of the {KIE_SERVER} installation, for example, `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_KIE_SERVER}-1`.

* Replace `<HOST>` with the ID or name of the {KIE_SERVER} host, for example, `localhost` or `192.7.8.9`.
* Replace `<PORT>` with the port of the {KIE_SERVER} host, for example, `8080`.
+
[NOTE]
====
The `org.kie.server.location` property specifies the location of {KIE_SERVER}.
====

* Replace `<CONTROLLER_URL>` with the URL of {CENTRAL}. {KIE_SERVER} connects to this URL during startup.
+
** If you installed {CENTRAL} using the installer or {EAP} zip installations, `<CONTROLLER_URL>` has this format:
+
ifdef::PAM[]
`\http://<HOST>:<PORT>/{URL_COMPONENT_CENTRAL}/rest/controller`
endif::[]
ifdef::DM[]
`\http://<HOST>:<PORT>/{URL_COMPONENT_CENTRAL}/rest/controller`
endif::[]
** If you are running {CENTRAL} using the `standalone.jar` file, `<CONTROLLER_URL>` has this format:
+
`\http://<HOST>:<PORT>/rest/controller`
