[id='eap-users-create-proc_{context}']

= Creating users
Before you can log in to {CENTRAL} or {KIE_SERVER}, you must create users. This section shows you how to create a {CENTRAL} user with the `admin`,  `rest-all`, and `kie-server` roles and a {KIE_SERVER} user that has the `kie-server` role. For information about roles, see <<roles-users-con_install-on-eap>>.

.Prerequisites
* {PRODUCT} is installed in the base directory of the {EAP} installation (`_EAP_HOME_`).

.Procedure
. In a terminal application, navigate to the `__EAP_HOME__/bin` directory.
ifdef::PAM[]
. Create a user with the `admin`, `rest-all`, and `kie-server` roles that you will use to log in to {CENTRAL}.
+
NOTE: Users with the `admin` role are {CENTRAL} administrators. Users with `rest-all` role can access {CENTRAL} REST capabilities. Users with the `kie-server` role can access {KIE_SERVER} (KIE Server) REST capabilities. The `kie-server` role is mandatory for users to have access to *Manage* and *Track* views in {CENTRAL}.
endif::[]
ifdef::DM[]
. Create a user with the `admin`, `rest-all`, and `kie-server` roles.
+
NOTE: Users with the `admin` role are {CENTRAL} administrators. Users with `rest-all` role can access {CENTRAL} REST capabilities. Users with the `kie-server` role can access {KIE_SERVER} (KIE Server) REST capabilities.
endif::[]
+
In the following command, replace `<username>` and  `<password>` with the user name and password of your choice.
+
ifdef::PAM[]
[source,bash]
----
$ ./add-user.sh -a --user <USERNAME> --password <PASSWORD> --role admin,rest-all,kie-server
----
endif::[]
ifdef::DM[]
[source,bash]
----
$ ./add-user.sh -a --user <USERNAME>  --password <PASSWORD> --role admin,rest-all,kie-server
----
endif::[]
+
[NOTE]
====
Make sure that the specified user name is not the same as an existing user, role, or group. For example, do not create a user with the user name `admin`.

The password must have at least eight characters and must contain at least one number and one non-alphanumeric character, but not & (ampersand).
====
. Create a user with the `kie-server` role that you will use to log in to {KIE_SERVER}.
+
ifdef::PAM[]
[source,bash]
----
$ ./add-user.sh -a --user <USERNAME> --password <PASSWORD> --role kie-server
----
endif::[]
ifdef::DM[]
[source,bash]
----
$ ./add-user.sh -a --user <USERNAME>  --password <PASSWORD> --role kie-server
----
endif::[]
. Make a note of your user names and passwords.
+
[NOTE]
====
If you installed {CENTRAL} and {KIE_SERVER} in the same server instance, you can create a single user that has both of these roles:
[source,bash]
----
$ ./add-user.sh -a --user <USERNAME>  --password <PASSWORD> --role admin,rest-all,kie-server
----
You should install {CENTRAL} and {KIE_SERVER} on different servers in production environments.
====
