[id='git-import-proc']

= Importing projects from Git repositories
Git is a distributed version control system. It implements revisions as commit objects. When you save your changes to a repository, a new commit object in the Git repository is created. 

{CENTRAL} uses Git to store project data, including assets such as rules and processes. When you create a project in {CENTRAL}, it is added to a Git repository that is embedded in {CENTRAL}. If you have projects in other Git repositories, you can import those projects into the {CENTRAL} Git repository through {CENTRAL} spaces.

.Prerequisites
* {PRODUCT} projects exist in an external Git repository.
* Credentials required for read access to that external Git repository are available.

.Procedure
. In {CENTRAL}, click *Menu* -> *Design* -> *Projects*.
. Select or create the space into which you want to import the projects. The default space is *mySpace*.
. Click the three vertical dots on the right side of the screen and select *Import Project*.
. In the *Import Project* window, enter the URL and credentials for the Git repository that contains the projects that you want to import and click *Import*. The projects are added to the {CENTRAL} Git repository and are available from the current space.

