[id='git-import-proc_{context}']
//Comment - Mark for deletion, duplicate of project-data/git-import-project.adoc
= Importing projects from Git repositories
Git is a distributed version control system. It implements revisions as commit objects. When you save your changes to a repository, a new commit object in the Git repository is created.

{CENTRAL} uses Git to store project data, including assets such as rules and processes. When you create a project in {CENTRAL}, it is added to a Git repository that is embedded in {CENTRAL}. If you have projects in other Git repositories, you can import those projects into the {CENTRAL} Git repository through {CENTRAL} spaces.

.Prerequisites
* {PRODUCT} projects exist in an external Git repository.
* You have the credentials required for read access to that external Git repository.

.Procedure
. In {CENTRAL}, click *Menu* -> *Design* -> *Projects*.
. Select or create the space into which you want to import the projects. The default space is *MySpace*.
. To import a project, do one of the following:
* Click *Import Project*.
* Select *Import Project* from the drop-down list.
. In the *Import Project* window, enter the URL and credentials for the Git repository that contains the projects that you want to import and click *Import*. The projects are added to the {CENTRAL} Git repository and are available from the current space.
