[id='installer-jws-proc']
= Installing {PRODUCT} using the installer in interactive mode

The installer for {PRODUCT} is an executable JAR file. You can use it to install {PRODUCT} in an existing Red Hat JBoss Server 3.1 server installation.

[NOTE]
====
For security reasons, you should run the installer as a non-root user.
====

.Prerequisite

* A backed-up Red Hat JBoss Web Server 5.0 or higher server installation is available.
* Sufficient user permissions to complete the installation are granted.
+
[NOTE]
====
Ensure that you are logged in with a user that has write permission for Tomcat.
====
* The JAR binary inlcuded in `$PATH` environment variable. On Red Hat Enterprise Linux, it is included in the `java-$_JAVA_VERSION_-openjdk-devel` package.
+
[NOTE]
====
{PRODUCT} is designed to work with UTF-8 encoding. If a different encoding system is used by the underlying JVM, unexpected errors might occur. To ensure UTF-8 is used by the JVM, use the `"-Dfile.encoding=UTF-8"` system property.
====

.Procedure
. In a terminal window, navigate to the directory where you downloaded the installer JAR file and enter the following command:
+
[source]
----
java -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
----
+
[NOTE]
====
When running the installer on Windows, you may be prompted to provide administrator credentials during the installation. To prevent this requirement, add the `izpack.mode=privileged` option to the installation command:
[source]
----
java -Dizpack.mode=privileged -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
----
Furthermore, when running the installer on a 32-bit Java virtual machine, you might encounter memory limitations. To prevent this issue, run this command:
[source]
----
java -XX:MaxHeapSize=4g -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
----
====
+
The graphical installer displays a splash screen and a license agreement page.
. Click *I accept the terms of this license agreement* and click *Next*.
. Specify the Red Hat JBoss 5.0 Web Server server home where you want to install {PRODUCT} and click *Next*.
. Select the components that you want to install and click *Next*.
+
You cannot install {CENTRAL} on Red Hat JBoss 5.0 Web Server. You can only install it on {EAP}. However, you can install the {HEADLESS_CONTROLLER} on Red Hat JBoss 5.0 Web Server. The {HEADLESS_CONTROLLER} is used to manage {KIE_SERVER}. Install the {HEADLESS_CONTROLLER} if you plan to manage multiple {KIE_SERVER} instances.
+
[NOTE]
====
You can install {CENTRAL} and {KIE_SERVER} on the same server. However, you should install {CENTRAL} and {KIE_SERVER} on different servers in production environments. To do this, run the installer twice.
====
+
. Create the Decision Manager `admin` user and click *Next*.
+
[NOTE]
====
Make sure that the selected user name is not the same as an existing user, role, or group. For example, do not create a user with the user name `admin`.

The password must have at least eight characters and must contain at least one number and one non-alphanumeric character, but not & (ampersand).
====
+
Make a note of the user name and password. You will need them to access {CENTRAL} and {KIE_SERVER}.
. On the Component Installation page, click *Next* to start the installation. The *Component Installation* page lists the components that you will install.

. When the installation has completed, click *Next* on the *Processing Finished* page. On the next page,you will see the message *Installation has completed successfully*.

. If desired, click *Generate Installation Script and Properties File* to save the installation data in an XML file, then click *Done*. You can use this file to automatically install {PRODUCT} on the same type of server. Note that you must change the `installpath` parameter in the XML file to specify the path of the new server that you want to install {PRODUCT} on. Enter the following command to perform an installation with the XML file:
+
[source]
----
java -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar <path-to-file>
----

You have successfully installed {PRODUCT} using the installer.

To start {PRODUCT}, enter the following command:
* On Linux or UNIX-based systems:
+
[source,bash]
----
JWS_HOME/bin/startup.sh
----
* On Windows:
+
[source,bash]
----
JWS_HOME\bin\startup.sh
----
