[id='install-standalone-properties-con_{context}']
= Supported properties
* `org.uberfire.nio.git.dir`: Location of the `.niogit` directory . Default: working directory
* `org.uberfire.nio.git.dirname`: Name of the Git directory. Default: `.niogit`
* `org.uberfire.nio.git.proxy.ssh.over.http`: Specifies whether SSH uses an HTTP proxy. Default: `false`
* `http.proxyHost`: Defines the host name of the HTTP proxy. Default: `null`
* `http.proxyPort`: Defines the host port (integer value) of the HTTP proxy. Default: `null`
* `org.uberfire.nio.git.proxy.ssh.over.https`: Specifies whether SSH uses an HTTPS proxy. Default: `false`
* `https.proxyHost`: Defines the host name of the HTTPs proxy. Default: `null`
* `https.proxyPort`: Defines the host port (integer value) of the HTTPS proxy. Default: `null`
* `org.uberfire.nio.git.http.enabled`: Enables or disables the HTTP daemon. Default: `true`
* `org.uberfire.nio.git.http.host`: If the HTTP daemon is enabled, it uses this property as the host identifier. This is an informative property that is used to display how to access the Git repository over HTTP.  The HTTP still relies on the servlet container. Default: `localhost`
* `org.uberfire.nio.git.http.hostname`: If the HTTP daemon is enabled, it uses this property as the host name identifier. This is an informative property that is used to display how to access the Git repository over HTTP.  The HTTP still relies on the servlet container. Default: `localhost`
* `org.uberfire.nio.git.http.port`: If the HTTP daemon is enabled, it uses this property as the port number. This is an informative property that is used to display how to access the Git repository over HTTP.  The HTTP still relies on the servlet container. Default: `8080`
* `org.uberfire.nio.git.https.enabled`: Enables or disables the HTTPS daemon. Default: `false`
* `org.uberfire.nio.git.https.host`: If the HTTPS daemon is enabled, it uses this property as the host identifier. This is an informative property that is used to display how to access the Git repository over HTTPS.  The HTTPS still relies on the servlet container. Default: `localhost`
* `org.uberfire.nio.git.https.hostname`: If the HTTPS daemon is enabled, it uses this property as the host name identifier. This is an informative property that is used to display how to access the Git repository over HTTPS.  The HTTPS still relies on the servlet container. Default: `localhost`
* `org.uberfire.nio.git.https.port`: If the HTTPS daemon is enabled, it uses this property as the port number. This is an informative property that is used to display how to access the Git repository over HTTPS.  The HTTPS still relies on the servlet container. Default: `8080`
* `org.uberfire.nio.git.daemon.enabled`: Enables or disables the Git daemon. Default: `true`
* `org.uberfire.nio.git.daemon.host`: If the Git daemon is enabled, it uses this property as the local host identifier. Default: `localhost`
* `org.uberfire.nio.git.daemon.hostname`: If the Git daemon is enabled, it uses this property as the local host name identifier. Default: `localhost`
* `org.uberfire.nio.git.daemon.port`: If the Git daemon is enabled, it uses this property for the port number. Default: `9418`
* `org.uberfire.nio.git.http.sslVerify`: Enables or disables SSL certificate checking for Git repositories. Default: `true`
+
[NOTE]
====
If the default or assigned port is already in use, a new port is automatically selected. Ensure that the ports are available and check the log for more information.
====
* `org.uberfire.nio.git.ssh.enabled`: Enables or disables the SSH daemon. Default: `true`
* `org.uberfire.nio.git.ssh.host`: If the SSH daemon is enabled, it uses this property as local host identifier. Default: `localhost`
* `org.uberfire.nio.git.ssh.hostname`: If the SSH daemon is enabled, it uses this property as local host name identifier. Default: `localhost`
* `org.uberfire.nio.git.ssh.port`: If the SSH daemon is enabled, it uses this property as port number. Default: `8001`
+
[NOTE]
====
If the default or assigned port is already in use, a new port is automatically selected. Ensure that the ports are available and check the log for more information.
====
* `org.uberfire.nio.git.ssh.cert.dir`: Location of the `.security` directory where local certificates will be stored. Default: working directory
* `org.uberfire.nio.git.ssh.passphrase`: Passphrase to access your operating system's public keystore when cloning Git repositories with SCP style URLs, for example `git@github.com:user/repository.git`.
* `org.uberfire.nio.git.ssh.algorithm`: Algorithm used by SSH. Default: `RSA`
* `org.uberfire.nio.git.ssh.ciphers`: A comma-separated string of ciphers. The available ciphers are `aes128-ctr`, `aes192-ctr`, `aes256-ctr`, `arcfour128`, `arcfour256`, `aes192-cbc`, `aes256-cbc`. If the property is not used, all available ciphers are loaded.
* `org.uberfire.nio.git.ssh.macs`: A comma-separated string of message authentication codes (MACs). The available MACs are `hmac-md5`, `hmac-md5-96`, `hmac-sha1`, `hmac-sha1-96`, `hmac-sha2-256`, `hmac-sha2-512`. If the property is not used, all available MACs are loaded.
+
[NOTE]
====
If you plan to use RSA or any algorithm other than DSA, make sure you setup properly your Application Server to use Bouncy Castle JCE library.
====
* `org.uberfire.metadata.index.dir`: Place where the Lucene `.index` folder will be stored. Default: working directory
* `org.uberfire.ldap.regex.role_mapper`: Regex pattern used to map LDAP principal names to application role name. Note that the variable role must be part of the pattern because it is substituted by the application role name when matching a principal value to role name. Default: Not used.
* `org.uberfire.sys.repo.monitor.disabled`: Disable configuration monitor (do not disable unless you know what you are doing). Default: `false`
* `org.uberfire.secure.key`: Password used by password encryption. Default`: `org.uberfire.admin`
* `org.uberfire.secure.alg`: Crypto algorithm used by password encryption. Default: `PBEWithMD5AndDES`
* `org.uberfire.domain`: security-domain name used by uberfire. Default: `ApplicationRealm`
* `org.guvnor.m2repo.dir`: Place where the Maven repository folder will be stored. Default: `working-directory/repositories/kie`
* `org.guvnor.project.gav.check.disabled`: Disable GAV checks. Default: `false`
* `org.kie.demo`: Enables external clone of a demo application from GitHub.
* `org.kie.build.disable-project-explorer`: Disable the automatic build of selected project in *Project Explorer*. Default: `false`
* `org.kie.verification.disable-dtable-realtime-verification`: Disables the realtime validation and verification of decision tables. Default: `false`
* `org.kie.workbench.controller`: URL for connecting with a {CONTROLLER}, for example: `ws://localhost:8080/kie-server-controller/websocket/controller`.
* `kie.maven.offline.force`: Forces Maven to behave as offline. If true, disable online dependency resolution. Default: `false`
+
[NOTE]
====
Use this property for {CENTRAL} only. If you share a runtime environment with any other component, isolate the configuration and apply it only to {CENTRAL}.
====
* `org.uberfire.gzip.enable`: Enables or disables Gzip compression on GzipFilter. Default: `true`
