[id='installing-con_{context}']
= About {PRODUCT}

ifdef::PAM[]
{PRODUCT} is the Red Hat middleware platform for creating business automation applications and microservices. It enables enterprise business and IT users to document, simulate, manage, automate, and monitor business processes and policies. It is designed to empower business and IT users to collaborate more effectively, so business applications can be changed easily and quickly.

endif::[]
ifdef::DM[]
{PRODUCT} is an open source decision management platform that combines business rules management, complex event processing, Decision Model & Notation (DMN) execution, and {PLANNER} for solving planning problems. It automates business decisions and makes that logic available to the entire business.

Business assets such as rules, decision tables, and DMN models are organized in projects and stored in the {CENTRAL} repository. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.
endif::[]

The product is made up of {CENTRAL} and {KIE_SERVER}.

* {KIE_SERVER} is the server where rules and other artifacts are executed. It is used to instantiate and execute rules and solve planning problems. {KIE_SERVER} provides the runtime environment for business assets and accesses the data stored in the assets repository (knowledge store).

ifdef::DM[]
* {CENTRAL} is the graphical user interface where you create and manage business rules that {KIE_SERVER} executes.
endif::[]

ifdef::PAM[]
* {CENTRAL} is the graphical user interface where you create and manage business rules that {KIE_SERVER} executes. It enables you to perform the following tasks:
+
** Create, manage, and edit your rules, processes, and related assets.
** Manage connected {KIE_SERVER} instances and their KIE containers (deployment units).
** Execute runtime operations against processes and tasks in {KIE_SERVER} instances connected to {CENTRAL}.
+
endif::[]

{CENTRAL} is also available as a standalone JAR file. You can use the {CENTRAL} standalone JAR file to run {CENTRAL} without needing to deploy it to an application server.



ifeval::["{context}" == "install-on-eap"]
{EAP_LONG} ({EAP}) {EAP_VERSION} is a certified implementation of the Java Enterprise Edition 8 (Java EE 8) full and web profile specifications. {EAP} provides preconfigured options for features such as high availability, clustering, messaging, and distributed caching. It also enables users to write, deploy, and run applications using the various APIs and services that {EAP} provides.
endif::[]
ifeval::["{context}" == "install-on-jws"]
{JWS} is an enterprise ready web server designed for medium and large applications, based on Tomcat. {JWS} provides organizations with a single deployment platform for Java Server Pages (JSP) and Java Servlet technologies, PHP, and CGI.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
{TOMCAT} is an enterprise ready web server designed for medium and large applications. {TOMCAT} provides organizations with a single deployment platform for Java Server Pages (JSP) and Java Servlet technologies, PHP, and CGI.
endif::[]

ifeval::["{context}" == "install-on-jws"]
On a {JWS} installation, you can install {KIE_SERVER} and the {HEADLESS_CONTROLLER}. Alternatively, you can run the standalone {CENTRAl} JAR file.
endif::[]

ifeval::["{context}" == "install-on-tomcat"]
On an {TOMCAT} installation, you can install {KIE_SERVER} and the {HEADLESS_CONTROLLER}. Alternatively, you can run the standalone {CENTRAl} JAR file.
endif::[]

The instructions in this document explain how to install {PRODUCT_PAM} in
ifeval::["{context}" == "install-on-eap"]
a {EAP} {EAP_VERSION} server instance.
endif::[]
ifeval::["{context}" == "install-on-jws"]
a {JWS} instance.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
an {TOMCAT} instance.
endif::[]
ifdef::DM[]

NOTE: {PRODUCT} is a subset of {PRODUCT_PAM}. You must install {PRODUCT_PAM} in order to use {PRODUCT}.

endif::[]
For instructions on how to install {PRODUCT_PAM} in other environments, see the following documents:

//ifeval::["{context}" == "install-on-eap"]
//* {URL_INSTALL_ON_JWS}[_{INSTALL_ON_JWS}_]
//endif::[]
ifeval::["{context}" == "install-on-jws"]
* {URL_INSTALLING_AND_CONFIGURING}#assembly-install-on-eap[_{INSTALLING_ON_EAP}_]
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
* {URL_INSTALLING_AND_CONFIGURING}#assembly-install-on-eap[_{INSTALLING_ON_EAP}_]
* {URL_INSTALLING_AND_CONFIGURING}#assembly-install-on-jws[_{INSTALLING_ON_JWS}_]
endif::[]
* {URL_INSTALLING_AND_CONFIGURING}#assembly-installing-kie-server-on-was[_{INSTALLING_KIE_ON_WAS}_]
* {URL_INSTALLING_AND_CONFIGURING}#assembly-installing-kie-server-on-wls[_{INSTALLING_KIE_ON_WLS}_]
* {URL_DEPLOYING_ON_OPENSHIFT}#assembly-openshift-operator[_{DEPLOYING_OPENSHIFT_OPERATOR}_]
* {URL_DEPLOYING_ON_OPENSHIFT}#assembly-openshift-templates[_{DEPLOYING_OPENSHIFT_TEMPLATES}_]

For information about supported components, see the following documents:

* https://access.redhat.com/solutions/3405361[What is the mapping between {PRODUCT_PAM} and the Maven library version?]
* https://access.redhat.com/articles/3405381[{PRODUCT_PAM} 7 Supported Configurations]
