[id='installer-run-proc_{context}']
= Using the installer in interactive mode

The installer for {PRODUCT} is an executable JAR file. You can use it to install {PRODUCT} in an existing
ifeval::["{context}" == "install-on-eap"]
{EAP} 7.1
endif::[]
ifeval::["{context}" == "install-on-jws"]
Red Hat JBoss Web Server 5.0
endif::[]
server installation.

[NOTE]
====
For security reasons, you should run the installer as a non-root user.
====

.Prerequisites
* A backed-up
ifeval::["{context}" == "install-on-eap"]
{EAP} 7.1 or higher
endif::[]
ifeval::["{context}" == "install-on-jws"]
Red Hat JBoss Web Server 5.0 or higher
endif::[]
 server installation is available.
* Sufficient user permissions to complete the installation are granted.
+
ifeval::["{context}" == "install-on-jws"]
[NOTE]
====
Ensure that you are logged in with a user that has write permission for Tomcat.
====
endif::[]
* The JAR binary is included in `$PATH` environment variable. On Red Hat Enterprise Linux, it is included in the `java-$_JAVA_VERSION_-openjdk-devel` package.
+
[NOTE]
====
{PRODUCT} is designed to work with UTF-8 encoding. If a different encoding system is used by the underlying JVM, unexpected errors might occur. To ensure UTF-8 is used by the JVM, use the `"-Dfile.encoding=UTF-8"` system property.
====

.Procedure
. In a terminal window, navigate to the directory where you downloaded the installer JAR file and enter the following command:
+
[source,subs="attributes+"]
----
ifdef::PAM[]
java -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::PAM[]
ifdef::DM[]
java -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::DM[]
----
+
[NOTE]
====
When running the installer on Windows, you may be prompted to provide administrator credentials during the installation. To prevent this requirement, add the `izpack.mode=privileged` option to the installation command:
[source,subs="attributes+"]
----
java -Dizpack.mode=privileged -jar
ifdef::PAM[]
{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::PAM[]
ifdef::DM[]
{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::DM[]
----
Furthermore, when running the installer on a 32-bit Java virtual machine, you might encounter memory limitations. To prevent this issue, run this command:
[source,subs="attributes+"]
----
java -XX:MaxHeapSize=4g -jar
ifdef::PAM[]
{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::PAM[]
ifdef::DM[]
{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::DM[]
----
====
+
The graphical installer displays a splash screen and a license agreement page.
. Click *I accept the terms of this license agreement* and click *Next*.
. Specify the
ifeval::["{context}" == "install-on-eap"]
{EAP} 7.1
endif::[]
ifeval::["{context}" == "install-on-jws"]
Red Hat JBoss 5.0 Web Server
endif::[]
 server home where you want to install {PRODUCT} and click *Next*.
. Select the components that you want to install and click *Next*.
+
ifeval::["{context}" == "install-on-jws"]
You cannot install {CENTRAL} on Red Hat JBoss 5.0 Web Server. You can only install it on {EAP}. However, you can install {KIE_SERVER} and the {HEADLESS_CONTROLLER} on Red Hat JBoss 5.0 Web Server. The {HEADLESS_CONTROLLER} is used to manage {KIE_SERVER}. Install the {HEADLESS_CONTROLLER} if you plan to manage multiple {KIE_SERVER} instances.
endif::[]
ifeval::["{context}" == "install-on-eap"]
[NOTE]
====
You can install {CENTRAL} and {KIE_SERVER} on the same server. However, you should install {CENTRAL} and {KIE_SERVER} on different servers in production environments. To do this, run the installer twice.
====
+
endif::[]
. Create a user and click *Next*.  By default, the new user is given the `admin`, `kie-server`, and `rest-all` roles.
ifeval::["{context}" == "install-on-jws"]
The `kie-server` role is required to acces {KIE_SERVER} REST capabilities.
endif::[]
ifeval::["{context}" == "install-on-eap"]
 To select another role, deselect `admin`. For more information, see <<roles-users-con>>.
endif::[]

+
[NOTE]
====
Make sure that the specified user name is not the same as an existing user, role, or group. For example, do not create a user with the user name `admin`.

The password must have at least eight characters and must contain at least one number and one non-alphanumeric character, but not & (ampersand).
====
+
Make a note of the user name and password. You will need them to access {CENTRAL} and {KIE_SERVER}.
. On the *Installation Overview* page, click *Next* to start the installation. The Installation Overview page lists the components that you will install.

. When the installation has completed, click *Next*.

ifdef::PAM[]
. On the *Configure Runtime Environment* page, choose whether to perform the default installation or perform an advanced configuration.
+
If you choose *Perform advanced configuration*, you can
choose to configure database settings or customize certain {KIE_SERVER} options.
+
. If you selected *Customize database settings*, on the *JDBC Drive Configuration* page specify a data source JDBC driver vendor, select one or more Driver JAR files, and click *Next*.
+
A data source is an object that enables a Java Database Connectivity (JDBC) client, such as an application server, to establish a connection with a database. Applications look up the data source on the Java Naming and Directory Interface (JNDI) tree or in the local application context and request a database connection to retrieve data. You must configure data sources for Process Server to ensure proper data exchange between the servers and the designated database.
+
. If you selected *Customize Process Server settings*, change any of the following, if desired:
+
* Change the name of the {KIE_SERVER} property.
* Change the URL of the {HEADLESS_CONTROLLER}.
* Deselect any {KIE_SERVER} server options.
+
. Click *Next* to configure the runtime environment.
endif::[]
. When *Processing finished* appears at the top of the screen, click *Next* to complete the installation.
. If desired, click *Generate Installation Script and Properties File* to save the installation data in an XML file, then click *Done*. You can use this file to automatically install {PRODUCT} on the same type of server. Note that you must change the `installpath` parameter in the XML file to specify the path of the new server that you want to install {PRODUCT} on. Enter the following command to perform an installation with the XML file:
+
[source,subs="attributes+"]
----
ifdef::PAM[]
java -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar <path-to-file>
endif::PAM[]
ifdef::DM[]
java -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar <path-to-file>
endif::DM[]
----

You have successfully installed {PRODUCT} using the installer.
ifdef::PAM[]
If you installed only {CENTRAL}, repeat these steps to install {KIE_SERVER} on a separate server.
endif::PAM[]
