[id='installer-run-proc_{context}']
= Using the installer in interactive mode

The installer for {PRODUCT} is an executable JAR file. You can use it to install {PRODUCT} in an existing
ifeval::["{context}" == "install-on-eap"]
{EAP} {EAP_VERSION}
endif::[]
ifeval::["{context}" == "install-on-jws"]
{JWS} {JWS_VERSION_LONG}
endif::[]
 server installation.

[NOTE]
====
For security reasons, you should run the installer as a non-root user.
====

.Prerequisites
* A supported JDK is installed. For a list of supported JDKs, see https://access.redhat.com/articles/3405381[Red Hat Process Automation Manager 7 Supported Configurations].
* A backed-up
ifeval::["{context}" == "install-on-eap"]
{EAP} {EAP_VERSION}
endif::[]
ifeval::["{context}" == "install-on-jws"]
{JWS} {JWS_VERSION_LONG}
endif::[]
 server installation is available.
* Sufficient user permissions to complete the installation are granted.
+
ifeval::["{context}" == "install-on-jws"]
[NOTE]
====
Ensure that you are logged in with a user that has write permission for Tomcat.
====
endif::[]
* The JAR binary is included in `$PATH` environment variable. On Red Hat Enterprise Linux, it is included in the `java-$_JAVA_VERSION_-openjdk-devel` package.
+
[NOTE]
====
{PRODUCT} is designed to work with UTF-8 encoding. If a different encoding system is used by the underlying JVM, unexpected errors might occur. To ensure UTF-8 is used by the JVM, use the `"-Dfile.encoding=UTF-8"` system property.
====

.Procedure
. In a terminal window, navigate to the directory where you downloaded the installer JAR file and enter the following command:
+
[source,subs="attributes+"]
----
ifdef::PAM[]
java -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::PAM[]
ifdef::DM[]
java -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::DM[]
----
+
[NOTE]
====
When running the installer on Windows, you may be prompted to provide administrator credentials during the installation. To prevent this requirement, add the `izpack.mode=privileged` option to the installation command:
[source,subs="attributes+"]
----
java -Dizpack.mode=privileged -jar
ifdef::PAM[]
{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::PAM[]
ifdef::DM[]
{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::DM[]
----
Furthermore, when running the installer on a 32-bit Java virtual machine, you might encounter memory limitations. To prevent this issue, run this command:
[source,subs="attributes+"]
----
java -XX:MaxHeapSize=4g -jar
ifdef::PAM[]
{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::PAM[]
ifdef::DM[]
{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar
endif::DM[]
----
====
+
The graphical installer displays a splash screen and a license agreement page.
. Click *I accept the terms of this license agreement* and click *Next*.
. Specify the
ifeval::["{context}" == "install-on-eap"]
{EAP} {EAP_VERSION}
endif::[]
ifeval::["{context}" == "install-on-jws"]
{JWS} {JWS_VERSION_LONG}
endif::[]
server home where you want to install {PRODUCT} and click *Next*.
. Select the components that you want to install and click *Next*.
+
ifeval::["{context}" == "install-on-jws"]
You cannot install {CENTRAL} on {JWS}. You can only install it on {EAP}. However, you can install {KIE_SERVER} and the {HEADLESS_CONTROLLER} on {JWS}. The {HEADLESS_CONTROLLER} is used to manage {KIE_SERVER}. Install the {HEADLESS_CONTROLLER} if you plan to manage multiple {KIE_SERVER} instances.
endif::[]
ifeval::["{context}" == "install-on-eap"]
[NOTE]
====
You can install {CENTRAL} and {KIE_SERVER} on the same server. However, you should install {CENTRAL} and {KIE_SERVER} on different servers in production environments. To do this, run the installer twice.
====
+
endif::[]
. Create a user and click *Next*.  By default, if you install both {CENTRAL} and {KIE_SERVER} in the same container the new user is given the `admin`, `kie-server`, and `rest-all` roles. If you install only {KIE_SERVER}, the user is given the `kie-server` role.
ifeval::["{context}" == "install-on-jws"]
The `kie-server` role is required to access {KIE_SERVER} REST capabilities.
endif::[]
ifeval::["{context}" == "install-on-eap"]
 To select another role, deselect `admin`. For more information, see <<roles-users-con_install-on-eap>>.
endif::[]

+
[NOTE]
====
Make sure that the specified user name is not the same as an existing user, role, or group. For example, do not create a user with the user name `admin`.

The password must have at least eight characters and must contain at least one number and one non-alphanumeric character, but not & (ampersand).
====
+
Make a note of the user name and password. You will need them to access {CENTRAL} and {KIE_SERVER}.
. On the *Installation Overview* page, click *Next* to start the installation. The Installation Overview page lists the components that you will install.

. When the installation has completed, click *Next*.

ifdef::PAM[]
. If {KIE_SERVER} is installed, the *Configure Runtime* step appears under *Component Installation*. On the *Configure Runtime Environment* page, choose to perform the default installation or perform an advanced configuration.
+
If you choose *Perform advanced configuration*, you can
choose to configure database settings or customize certain {KIE_SERVER} options.
+
. If you selected *Customize database settings*, on the *JDBC Drive Configuration* page specify a data source JDBC driver vendor, select one or more Driver JAR files, and click *Next*.
+
A data source is an object that enables a Java Database Connectivity (JDBC) client, such as an application server, to establish a connection with a database. Applications look up the data source on the Java Naming and Directory Interface (JNDI) tree or in the local application context and request a database connection to retrieve data. You must configure data sources for {KIE_SERVER} to ensure proper data exchange between the servers and the designated database.
+
. If you selected *Customize {KIE_SERVER} properties*, on the *{KIE_SERVER} Properties Configuration*, change any of the following:
+
* *{KIE_SERVER} ID*: The name of the {KIE_SERVER} property.
ifeval::["{context}" == "install-on-eap"]
* *Controller URL*: The URL of the {HEADLESS_CONTROLLER}.
endif::[]
* Clear any {KIE_SERVER} function you want to disable.
+
. Click *Next* to configure the runtime environment.
endif::[]
. When *Processing finished* appears at the top of the screen, click *Next* to complete the installation.
. Optionally, click *Generate Installation Script and Properties File* to save the installation data in XML files, and then click *Done*.
+
The installer generates two files. The `auto.xml` file automates future installations and the `auto.xml.variables` file stores user passwords and other sensitive variables.
Use the `auto.xml` file on multiple systems to easily repeat a {PRODUCT} installation on the same type of server with the same configuration as the original installation. If necessary, update the `installpath` parameter in the `auto.xml` file. Enter the following command to perform an installation with the XML file:
+
[source,subs="attributes+"]
----
ifdef::PAM[]
java -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar <path-to-auto.xml-file>
endif::PAM[]
ifdef::DM[]
java -jar {PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar <path-to-auto.xml-file>
endif::DM[]
----

You have successfully installed {PRODUCT} using the installer.
ifdef::PAM[]
If you installed only {CENTRAL}, repeat these steps to install {KIE_SERVER} on a separate server.
endif::PAM[]

ifdef::PAM[]

[NOTE]
====
If you use Microsoft SQL Server, make sure you have configured proper transaction isolation for your database. If you do not, you may experience deadlocks. The recommended configuration is to turn on ALLOW_SNAPSHOT_ISOLATION and READ_COMMITTED_SNAPSHOT by entering the following statements:

[source]
----
ALTER DATABASE <DBNAME> SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE <DBNAME> SET READ_COMMITTED_SNAPSHOT ON
----
====

endif::PAM[]
