[id='install-download-proc_{context}']
= Downloading the {PRODUCT} installation files

Depending on your environment and installation requirements, download a {PRODUCT} distribution.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download one of the following product distributions, depending on your preferred installation method:
+
[NOTE]
====
You only need to download one of these distributions. 
====
* If you want to use the installer to install {PRODUCT} on
ifeval::["{context}" == "install-on-eap"]
{EAP} 7.1
endif::[]
ifeval::["{context}" == "install-on-jws"]
Red Hat JBoss Web Server 5.0
endif::[]
, download *{PRODUCT} {PRODUCT_VERSION_LONG} Installer*
ifdef::PAM[]
(`{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar`).
endif::PAM[]
ifdef::DM[]
(`{PRODUCT_INIT}-installer-{PRODUCT_VERSION_LONG}.jar`).
endif::DM[]
The installer graphical user interface guides you through the installation process.
ifeval::["{context}" == "install-on-eap"]
* If you want to install {PRODUCT} on {EAP} 7.1 using the deployable zip files, download the following files:
ifdef::PAM[]
** *{PRODUCT} {PRODUCT_VERSION_LONG} {KIE_SERVER} for All Supported EE7 Containers* (`{PRODUCT_FILE}-kie-server-ee7.zip`)
** *{PRODUCT} {PRODUCT_VERSION_LONG} {CENTRAL} Deployable for EAP 7*
(`{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`)
endif::PAM[]

ifdef::DM[]
** *{PRODUCT} {PRODUCT_VERSION_LONG} {KIE_SERVER} for All Supported EE7 Containers* (`{PRODUCT_FILE}-kie-server-ee7.zip`)
** *{PRODUCT} {PRODUCT_VERSION_LONG} {KIE_SERVER} Deployable for EAP 7*
(`{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`)
endif::DM[]

endif::[]
ifeval::["{context}" == "install-on-jws"]
* To install {KIE_SERVER} on Red Hat JBoss Web Server 5.0 using the deployable zip file, download *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_FILE}-add-ons.zip`).
endif::[]
+
The ZIP files do not require a graphical user interface so you can install {PRODUCT} using SSH.
* To run {CENTRAL} without needing to deploy it to an application server, download *{PRODUCT} {PRODUCT_VERSION_LONG} {CENTRAL} Standalone* (`{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-standalone.jar`).

//ifdef::PAM[]
//* To install {CENTRAL} Monitoring, download *{PRODUCT} {PRODUCT_VERSION_LONG} {CENTRAL} Monitoring*
//(`{PRODUCT_FILE}-monitoring-ee7.zip`).
//endif::PAM[]
