[id='installing-and-configuring-smart-router-con_{context}']
= Installing and configuring Smart Router

Smart Router ({KIE_SERVER} router) is a lightweight Java component that you can use as an integration layer between multiple {KIE_SERVER}s, client applications, and other components. Depending on your deployment and execution environment, Smart Router can aggregate multiple independent {KIE_SERVER} instances as though they are a single server. Smart Router provides the following features:

Data aggregation::
Collects data from all {KIE_SERVER} instances (one instance from each group) when there is a client application request and aggregates the results in a single response.

Routing::
Functions as a single endpoint that receives calls from client applications to any of your services and routes each call automatically to the {KIE_SERVER} that runs the specific service. This means that {KIE_SERVER}s do not need to have the same services deployed.

Load balancing::
Provides efficient load balancing. Load balancing requests for a Smart Router cluster must be managed externally with standard load balancing tools.

Authentication::
Authenticates {KIE_SERVER} instances by using a system property flag and can enable HTTPS traffic.

Environment Management::
Manages the changing environment, for example adding or removing server instances.
