[id='install-options-proc_{context}']
= Installation options

Depending on your environment and project requirements, choose one of the following installation options:

[NOTE]
====
* For information about installing {KIE_SERVER} on {WEBSPHERE}, see {URL_INSTALLING_AND_CONFIGURING}#assembly-installing-kie-server-on-was[_{INSTALLING_KIE_ON_WAS}_].
* For information about installing {KIE_SERVER} on {WEBLOGIC}, see {URL_INSTALLING_AND_CONFIGURING}#assembly-installing-kie-server-on-wls[_{INSTALLING_KIE_ON_WLS}_].
====

* Download and run the executable JAR installer for installation on {EAP} 7.1 or {JWS} {JWS_VERSION}. The installer graphical user interface guides you through the installation process.
* Download one of the following ZIP files:
** To install {PRODUCT} on {EAP} {EAP_VERSION}, download the following files:
ifdef::DM[]
*** `{PRODUCT_FILE}-{URL_COMPONENT_CENTRAL}-eap7-deployable.zip`
*** `{PRODUCT_FILE}-kie-server-ee8.zip`
endif::[]
ifdef::PAM[]
*** `jboss-bpmsuite-{PRODUCT_VERSION}-deployable-eap7.x.zip`: version adapted for deployment on Red Hat JBoss Enterprise Application Platform (EAP 6.4).
*** `jboss-bpmsuite-{PRODUCT_VERSION}-deployable-generic.zip`: the deployable version with additional libraries adapted for deployment on {JWS} (EWS), Apache Tomcat 6, and Apache Tomcat 7.
endif::[]
ifdef::DM[]
** To install {KIE_SERVER} on {JWS} {JWS_VERSION}, download the `{PRODUCT_INIT}-7.0-kie-server-jws.zip` file.
endif::[]
ifdef::PAM[]
** To install {KIE_SERVER} on {JWS} {JWS_VERSION}, download the following files.
*** `jboss-bpmsuite-{PRODUCT_VERSION}-deployable-eap7.x.zip`: version adapted for deployment on Red Hat JBoss Enterprise Application Platform (EAP 6.4).
*** `jboss-bpmsuite-{PRODUCT_VERSION}-deployable-generic.zip`: the deployable version with additional libraries adapted for deployment on {JWS} (EWS), Apache Tomcat 6, and Apache Tomcat 7.
endif::[]

For more information, see https://access.redhat.com/articles/3354301[{PRODUCT_DM} 7 Supported Configurations].

For installation instructions, see <<installing-con_{context}>>.
