[id='install-download-proc_{context}']
= Downloading the {PRODUCT} installation files

You can use the installer JAR file or deployable ZIP files to install {PRODUCT}. You can run the installer in interactive or command line interface (CLI) mode. Alternatively, you can extract and configure the {CENTRAL} and {KIE_SERVER} deployable ZIP files. If you want to run {CENTRAL} without deploying it to an application server, download the {CENTRAL} Standalone JAR file.

Download an {PRODUCT} distribution that meets your environment and installation requirements.

.Procedure
. Navigate to the https://www.ibm.com/support/pages/node/6596913[IBM Support] page and follow the instructions to download the installation files.
////
. Download one of the following product distributions, depending on your preferred installation method:
+
[NOTE]
====
You only need to download one of these distributions.
====
* If you want to use the installer to install {PRODUCT} on
ifeval::["{context}" == "install-on-eap"]
{EAP} {EAP_VERSION},
endif::[]
ifeval::["{context}" == "install-on-jws"]
{JWS},
endif::[]
 download *{PRODUCT} {PRODUCT_VERSION_LONG} Installer*
ifdef::PAM[]
(`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-INS.Jar`).
endif::PAM[]
ifdef::DM[]
(`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-INS.Jar`).
endif::DM[]
The installer graphical user interface guides you through the installation process.
ifeval::["{context}" == "install-on-eap"]
* If you want to install {PRODUCT} on {EAP} {EAP_VERSION} using the deployable ZIP files, download the following files:
ifdef::PAM[]
** *{PRODUCT} {PRODUCT_VERSION_LONG} {KIE_SERVER} for All Supported EE8 Containers* (`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-KS8.Zip`)
** *{PRODUCT} {PRODUCT_VERSION_LONG} {CENTRAL} Deployable for EAP 7*
(`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-BC7.zip`)
** *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-AO.zip`)
endif::PAM[]

ifdef::DM[]
** *{PRODUCT} {PRODUCT_VERSION_LONG} {KIE_SERVER} for All Supported EE8 Containers* (`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-KS8.Zip`)
** *{PRODUCT} {PRODUCT_VERSION_LONG} {KIE_SERVER} Deployable for EAP 7*
(`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-BC7.zip`)
endif::DM[]

endif::[]
ifeval::["{context}" == "install-on-jws"]
ifdef::PAM[]
* To install {KIE_SERVER} on {JWS} using the deployable ZIP files, download the following files:
** *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-AO.zip`)
** *{PRODUCT} {PRODUCT_VERSION_LONG} Maven Repository* (`{PRODUCT_FILE}-maven-repository.zip`)
endif::PAM[]
ifdef::DM[]
* To install {KIE_SERVER} on {JWS} using the deployable ZIP file, download the *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-AO.zip`) file.
+
The ZIP file does not require a graphical user interface.
endif::DM[]
endif::[]

ifeval::["{context}" == "install-on-tomcat"]
ifdef::PAM[]
* To install {KIE_SERVER} on {TOMCAT} using the deployable ZIP files, download the following files:
** *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-AO.zip`)
** *{PRODUCT} {PRODUCT_VERSION_LONG} Maven Repository* (`{PRODUCT_FILE}-maven-repository.zip`)
endif::PAM[]
ifdef::DM[]
* To install {KIE_SERVER} on {TOMCAT} using the deployable ZIP file, download the *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-AO.zip`) file.
endif::DM[]
endif::[]


* To run {CENTRAL} without needing to deploy it to an application server, download *{PRODUCT} {PRODUCT_VERSION_LONG} {CENTRAL} Standalone* (`{PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-BC7.zip`).

//ifdef::PAM[]
//* To install {CENTRAL} Monitoring, download *{PRODUCT} {PRODUCT_VERSION_LONG} {CENTRAL} Monitoring*
//(`{PRODUCT_FILE}-monitoring-EE8.zip`).
//endif::PAM[]
////
