[id='JMS-broker-configure_{context}']
= Downloading and configuring AMQ Broker

AMQ Broker enables your applications to communicate with any messaging provider. It specifies how components such as message-driven beans, Enterprise JavaBeans, and servlets can send or receive messages. Use the following instructions to configure a simplified, non-high availability environment.

To configure AMQ Broker for a high availability {PRODUCT} clustered environment, see  https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_broker[_Using AMQ Broker_].


.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product: AMQ Broker*
* *Version: 7.2.0*
. Click *Download* next to *Red Hat AMQ Broker 7.2.0* (`amq-broker-7.2.0-bin.zip`).
. Extract the `amq-broker-7.2.0-bin.zip` file. 
. Change directory to `amq-broker-7.2.0-bin/amq-broker-7.2.0/bin`.
. Enter the following command and replace the following placeholders to create the broker and broker user:
+
* `<HOST>` is the IP address or host name of the server where you installed AMQ Broker.
* `<AMQ_USER>` and `<AMQ_PASSWORD>` is a user name and password combination of your choice.
* `<BROKER_NAME>` is a name for the broker that you are creating.
+
[source]
----
./artemis create --host <HOST> --user <AMQ_USER> --password <AMQ_PASSWORD> --require-login <BROKER_NAME>
----
+

. To run AMQ Broker, enter the following command in the `amq-broker-7.2.0-bin/amq-broker-7.2.0/bin` directory:
+
[source]
----
amq-broker-7.2.0/bin/<BROKER_NAME>/bin/artemis run
----

