[id='jws-zip-install-proc']

= Installing {KIE_SERVER} with a ZIP file

{KIE_SERVER} provides the runtime environment for business assets and accesses the data stored in the assets repository (knowledge store). You can use the `{PRODUCT_INIT}-{PRODUCT_VERSION}-kie-server-jws.zip` file to install {KIE_SERVER} on an existing {JWS} {JWS_VERSION_LONG} or higher server instance.

[NOTE]
====
To use the installer JAR file to install {KIE_SERVER}, see <<assembly_installing-using-installer_{context}>>.
====

.Prerequisites
* A backed-up {JWS} {JWS_VERSION_LONG} or higher server installation is available. The base directory of the {JWS} installation is referred to as `__JWS_HOME__`. 
* Sufficient user permissions to complete the installation are granted.

.Procedure
. Download the `{PRODUCT_INIT}-{PRODUCT_VERSION}-kie-server-jws.zip` file:
.. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}

.. Click *Download* next to *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_FILE}-add-ons.zip`).
.. Unzip the `{PRODUCT_FILE}-add-ons.zip` file. The
`{PRODUCT_INIT}-{PRODUCT_VERSION}-kie-server-jws.zip`
 file is in the unzipped directory.
. Extract the 
ifdef::PAM[]
`{PRODUCT_INIT}-{PRODUCT_VERSION}-kie-server-jws.zip`
endif::PAM[]
ifdef::DM[]
`{PRODUCT_INIT}-{PRODUCT_VERSION}-kie-server-jws.zip`
endif::DM[]
 archive to a temporary directory. In the following examples, this directory is called `__TEMP_DIR__`.
. Copy the 
ifdef::PAM[]
`__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION}-kie-server-jws/kie-server.war`
endif::PAM[]
ifdef::DM[]
`__TEMP_DIR__/{PRODUCT_INIT}-{PRODUCT_VERSION}-kie-server-jws/kie-server.war`
endif::DM[]
 directory to the `_JWS_HOME_/tomcat/webapps` directory.
+
WARNING: Ensure the names of the {PRODUCT} deployments you are copying do not conflict with your existing deployments in the {JWS} instance.
. Remove the `.war` extensions from the `kie-server.war` folder.
. Open the `_JWS_HOME_/tomcat/conf/tomcat-users.xml` file in a text editor.
. Add users and roles to the `_JWS_HOME_/tomcat/conf/tomcat-users.xml` file. In the following example, `<ROLE_NAME>` is a role supported by {PRODUCT}. 
//For a list of supported roles, see <<dm-roles-con>>.  
`<USER_NAME>` and `<USER_PWD>` are the user name and password of your choice:
+
[source]
----
<role rolename="<ROLE_NAME>"/>
<user username="<USER_NAME> password="<USER_PWD>" roles="<ROLE_NAME>"/>
----
+
If a user has more than one role, as shown in the following example, separate the roles with a comma:
+
[source,subs="attributes+"]
----
<role rolename="admin"/>
<role rolename="kie-server"/>
<user username={PRODUCT_INIT}User password="user1234" roles="admin,kie-server"/>
----
. Complete one of the following steps in the `_JWS_HOME_/tomcat/bin` directory:
+
* On Linux or UNIX, create the `setenv.sh` file with the following content:
+
ifdef::PAM[]
[source]
----
CATALINA_OPTS="-Xmx1024m -Dorg.jboss.logging.provider=jdk"
----
endif::PAM[]
ifdef::DM[]
[source]
----
CATALINA_OPTS="-Xmx1024m 
 -Dorg.jboss.logging.provider=jdk 
 -Dorg.jbpm.server.ext.disabled=true 
 -Dorg.jbpm.ui.server.ext.disabled=true
 -Dorg.jbpm.case.server.ext.disabled=true"
----
endif::DM[]
* On Windows, add the following content to the `setenv.bat` file:
+
ifdef::PAM[]
[source]
----
set CATALINA_OPTS=-Xmx1024m -Dorg.jboss.logging.provider=jdk
----
endif::PAM[]
ifdef::DM[]
[source]
----
set CATALINA_OPTS="-Xmx1024m -Dorg.jboss.logging.provider=jdk -Dorg.jbpm.server.ext.disabled=true -Dorg.jbpm.ui.server.ext.disabled=true -Dorg.jbpm.case.server.ext.disabled=true
----
endif::DM[]
