[id='_setting_up_transaction_manager']
==== Setting up Transaction Manager for Red Hat JBoss Web Server 2.1 (Tomcat 7)

. Extract the generic deployable ZIP package you downloaded from the https://access.redhat.com[Red Hat Customer Portal] to a temporary location. This ZIP package contains the following three web application archives: `{URL_COMPONENT_CENTRAL}.war` , `dashbuilder.war`, and `kie-server.war` in an exploded format. Rename these folders to remove the `war` extension.

. Copy these folders directly under the `$_TOMCAT_DIR_/webapps` folder.
+
You should end up with three folders in an exploded format: `$_TOMCAT_DIR_/webapps/{URL_COMPONENT_CENTRAL}`, `$_TOMCAT_DIR_/webapps/dashbuilder`, and `$_TOMCAT_DIR_/webapps/kie-server`.
+
[NOTE]
====
`$_TOMCAT_DIR_` stands for the home directory where your web server is located. Replace it with the actual path to your web server home directory, for example: `/home/john/jboss-ews-2.1/tomcat7/`.
====

. Extract the contents of the Red Hat JBoss BPM Suite Core Engine files archive to a temporary location from where you can copy the required libraries. This folder now contains all the core Red Hat JBoss BPM Suite libraries under the extracted folder and a `lib` folder.

. Install the transaction manager.
+
[WARNING]
====
Please note that the following section describes the setup of a transaction manager, Bitronix, that is not officially supported by Red Hat.
====
+
Copy the following transaction manager JAR libraries from the `lib` folder to `$_TOMCAT_DIR_/lib/` directory. These JARs are available in `jboss-bpmsuite-_VERSION_-deployable-generic.zip` and `jboss-bpmsuite-_VERSION_-engine.zip`.
+
  * `btm-_VERSION_.jar`
  * `btm-tomcat-lifecycle-_VERSION_.jar`
  * `h2-_VERSION_.jar`
  * `jta-_VERSION_.jar`
  * `slf4j-api-_VERSION_.jar`
  * `slf4j-jdk14-_VERSION_.jar`
+
Additionally, download the following library and copy it into the `$_TOMCAT_DIR_/lib/` folder: http://repository.jboss.org/nexus/content/repositories/central/javax/security/jacc/javax.security.jacc-api/1.5/javax.security.jacc-api-1.5.jar[javax.security.jacc-api.jar]. Add `Valve` configuration into `_TOMCAT_HOME_/conf/server.xml` inside the `<host>` element as last `Valve` definition:
+
[source,xml]
----
<Valve className="org.kie.integration.tomcat.JACCValve" />
----

. Install the driver to your database.
+
Copy the JAR file with the relevant database driver to `$_TOMCAT_DIR_/lib/`.
+
[NOTE]
.Driver to the Embedded H2 Database
====
If using the embedded H2 database, the driver is available in `{URL_COMPONENT_CENTRAL}/WEB-INF/lib/`.
====

. Create the transaction manager configuration files in `$_TOMCAT_DIR_/conf/` :
+
* `btm-config.properties`
+
[source]
----
bitronix.tm.serverId=tomcat-btm-node0
bitronix.tm.journal.disk.logPart1Filename=${btm.root}/work/btm1.tlog
bitronix.tm.journal.disk.logPart2Filename=${btm.root}/work/btm2.tlog
bitronix.tm.resource.configuration=${btm.root}/conf/resources.properties
----
* `resources.properties` (the `resource.ds1.uniqueName` defines the data source name used in Tomcat resource definition later -- make a note of this value).
+
Make sure to change the values in the following definitions to match your environment.
+
.H2 Data Source Definition
====
[source]
----
resource.ds1.className=bitronix.tm.resource.jdbc.lrc.LrcXADataSource
resource.ds1.uniqueName=jdbc/jbpm
resource.ds1.minPoolSize=10
resource.ds1.maxPoolSize=20
resource.ds1.driverProperties.driverClassName=org.h2.Driver
resource.ds1.driverProperties.url=jdbc:h2:file:~/jbpm
resource.ds1.driverProperties.user=sa
resource.ds1.driverProperties.password=
resource.ds1.allowLocalTransactions=true
----
====
+
.MySQL 5.5 Data Source Definition
====
[source]
----
resource.ds1.className=com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
resource.ds1.uniqueName=jdbc/jbpm
resource.ds1.minPoolSize=0
resource.ds1.maxPoolSize=10
resource.ds1.driverProperties.URL=jdbc:mysql://localhost:3306/sampledb
resource.ds1.driverProperties.user=dbuser
resource.ds1.driverProperties.password=dbpassword
resource.ds1.allowLocalTransactions=true
----
====
+
.DB2 Type 4 Data Source Definition
====
[source]
----
resource.ds1.className=com.ibm.db2.jcc.DB2Driver
resource.ds1.uniqueName=jdbc/jbpm
resource.ds1.minPoolSize=0
resource.ds1.maxPoolSize=10
resource.ds1.driverProperties.URL=jdbc:db2://localhost:50000/sampledb
resource.ds1.driverProperties.user=dbuser
resource.ds1.driverProperties.password=dbpassword
resource.ds1.allowLocalTransactions=true
----
====
+
.Oracle Data Source Definition
====
[source]
----
resource.ds1.className=oracle.jdbc.xa.client.OracleXADataSource
resource.ds1.uniqueName=jdbc/jbpm
resource.ds1.minPoolSize=0
resource.ds1.maxPoolSize=10
resource.ds1.driverProperties.URL=jdbc:oracle:thin:@//localhost:1521/bpms
resource.ds1.driverProperties.user=dbuser
resource.ds1.driverProperties.password=dbpassword
resource.ds1.allowLocalTransactions=true
----
====
+
.Microsoft SQL Server Data Source Definition
====
[source]
----
resource.ds1.className=com.microsoft.sqlserver.jdbc.SQLServerDriver
resource.ds1.uniqueName=jdbc/jbpm
resource.ds1.minPoolSize=0
resource.ds1.maxPoolSize=10
resource.ds1.driverProperties.URL=jdbc:sqlserver://localhost:1433;databaseName=bpms;
resource.ds1.driverProperties.user=dbuser
resource.ds1.driverProperties.password=dbpassword
resource.ds1.allowLocalTransactions=true
----
====
+
.PostgreSQL Data Source Definition
====
[source]
----
resource.ds1.className=org.postgresql.xa.PGXADataSource
resource.ds1.uniqueName=jdbc/jbpm
resource.ds1.minPoolSize=0
resource.ds1.maxPoolSize=10
resource.ds1.driverProperties.serverName=localhost
resource.ds1.driverProperties.databaseName=bpm641tomcat
resource.ds1.driverProperties.portNumber=5432
resource.ds1.driverProperties.user=dbuser
resource.ds1.driverProperties.password=dbpassword
resource.ds1.allowLocalTransactions=true
====

. Set up the transaction manager listener in `$_TOMCAT_DIR_/conf/server.xml` to start and stop Bitronix on container startup and shutdown:
+
Add the following element as the last `<Listener>` element into the `<Server>` element:
+
[source]
----
<Listener className="bitronix.tm.integration.tomcat.BTMLifecycleListener" />
----

. Define the `btm.root` system property and location where Bitronix configuration file is placed:
+
In `$_TOMCAT_DIR_/bin/`, create a readable `setenv.sh` file with the following content:
+
[source]
----
CATALINA_OPTS="-Xmx512M -XX:MaxPermSize=512m -Djava.security.auth.login.config=$CATALINA_HOME/webapps/{URL_COMPONENT_CENTRAL}/WEB-INF/classes/login.config -Dbtm.root=$CATALINA_HOME -Dbitronix.tm.configuration=$CATALINA_HOME/conf/btm-config.properties -Dorg.jbpm.designer.perspective=RuleFlow -Djbpm.tsr.jndi.lookup=java:comp/env/TransactionSynchronizationRegistry -Dorg.jboss.logging.provider=jdk"
----
+
The `java.security.auth.login.config` property must be set in order for the `ssh clone` of the Git repository to work.
+
[NOTE]
====
The `-XX:MaxPermSize=512m` JVM property is valid only for JDK 6 and 7. It is _not_ valid for JDK 8+.
====
+
[IMPORTANT]
.Tomcat on Microsoft Windows Systems
====
On Microsoft Windows systems, replace the `$_CATALINA_HOME_` value in the content of the file with the equivalent environment variable name, or use the absolute path and add the values in `setenv.bat` file as shown here in the following example:

[source]
----
set "CATALINA_OPTS=-Xmx512m -XX:MaxPermSize=512m -Djava.security.auth.login.config=C:\apache-tomcat\webapps\{URL_COMPONENT_CENTRAL}\WEB-INF\classes\login.config -Dbtm.root=C:\apache-tomcat -Dbitronix.tm.configuration=C:\apache-tomcat\conf\btm-config.properties -Djbpm.tsr.jndi.lookup=java:comp/env/TransactionSynchronizationRegistry"
----
====
