[id='jws-zip-install-proc_{context}']

= Installing {KIE_SERVER} from ZIP files

{KIE_SERVER} provides the runtime environment for business assets and accesses the data stored in the assets repository (knowledge store). You can use  ZIP files to install {KIE_SERVER} on an existing
ifeval::["{context}" == "install-on-jws"]
{JWS} {JWS_VERSION_LONG} server instance.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
{TOMCAT} {TOMCAT_VERSION} instance.
endif::[]


[NOTE]
====
To use the installer JAR file to install {KIE_SERVER}, see <<assembly_installing-using-installer_{context}>>.
====

ifdef::PAM[]
* The following files have been downloaded, as described in  <<install-download-proc_{context}>>:
** *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_FILE}-add-ons.zip`)
** *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Maven Repository* (`{PRODUCT_FILE}-maven-repository.zip`)
endif::PAM[]
ifdef::DM[]
* The *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_FILE}-add-ons.zip`) file has been downloaded, as described in <<install-download-proc_{context}>>.
endif::DM[]
ifeval::["{context}" == "install-on-jws"]
* A backed-up {JWS} {JWS_VERSION_LONG} server installation is available. The base directory of the {JWS} installation is referred to as `_JWS_HOME_`.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
* A backed-up {TOMCAT} {TOMCAT_VERSION} server installation is available. The base directory of the {TOMCAT} installation is referred to as `_TOMCAT_HOME_`.
endif::[]
* Sufficient user permissions to complete the installation are granted.

.Procedure
. Extract the `{PRODUCT_FILE}-add-ons.zip` file.
. From the extracted `{PRODUCT_FILE}-add-ons.zip` file, extract the following files:
* `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kie-server-jws.zip`
ifdef::PAM[]
* `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_PROCESS_ENGINE}.zip`
endif::PAM[]
ifdef::DM[]
* `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_DECISION_ENGINE}.zip`
endif::DM[]

+
In the following instructions, the directory that contains the extracted `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kie-server-jws.zip` file is called
ifeval::["{context}" == "install-on-jws"]
`JWS_TEMP_DIR`
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`TOMCAT_TEMP_DIR`
endif::[]
 and the directory that contains the extracted
ifdef::PAM[]
`{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_PROCESS_ENGINE}.zip` file is called `ENGINE_TEMP_DIR`.
endif::PAM[]
ifdef::DM[]
`{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-{URL_COMPONENT_DECISION_ENGINE}.zip` file is called `ENGINE_TEMP_DIR`.
endif::DM[]

. Copy the
ifeval::["{context}" == "install-on-jws"]
`JWS_TEMP_DIR/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kie-server-jws/kie-server.war` directory to the `_JWS_HOME_/tomcat/webapps` directory.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`TOMCAT_TEMP_DIR/{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kie-server-jws/kie-server.war` directory to the `_TOMCAT_HOME_/tomcat/webapps` directory.
endif::[]

+
[NOTE]
====
ifeval::["{context}" == "install-on-jws"]
Ensure the names of the {PRODUCT} deployments you copy do not conflict with your existing deployments in the {JWS} instance.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
Ensure the names of the {PRODUCT} deployments you copy do not conflict with your existing deployments in the {TOMCAT} instance.
endif::[]
====
. Remove the `.war` extensions from the `kie-server.war` folder.
ifeval::["{context}" == "install-on-jws"]
. Move the `kie-tomcat-integration-{MAVEN_ARTIFACT_VERSION}.jar` file from the `ENGINE_TEMP_DIR` directory to the `_JWS_HOME_/tomcat/lib` directory.
. Move the `jboss-jacc-api-<VERSION>.jar`, `slf4j-api-<VERSION>.jar`, and `slf4j-jdk14-<VERSION>.jar` files from the `ENGINE_TEMP_DIR/lib` directory to the `_JWS_HOME_/tomcat/lib` directory, where `<VERSION>` is the version artifact file name, in the `lib` directory.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
. Move the `kie-tomcat-integration-{MAVEN_ARTIFACT_VERSION}.jar` file from the `ENGINE_TEMP_DIR` directory to the `_TOMCAT_HOME_/tomcat/lib` directory.
. Move the `jboss-jacc-api-<VERSION>.jar`, `slf4j-api-<VERSION>.jar`, `jboss-logging-<VERSION>.jar`, and `slf4j-jdk14-<VERSION>.jar` files from the `ENGINE_TEMP_DIR/lib` directory to the `_TOMCAT_HOME_/tomcat/lib` directory, where `<VERSION>` is the version artifact file name, in the `lib` directory.
endif::[]
. Add the following line to the `<host>` element in the `_JWS_HOME_/tomcat/conf/server.xml` file after the last Valve definition:
+
[source]
----
<Valve className="org.kie.integration.tomcat.JACCValve" />
----
+
ifeval::["{context}" == "install-on-jws"]
. Open the `_JWS_HOME_/tomcat/conf/tomcat-users.xml` file in a text editor.
. Add users and roles to the `_JWS_HOME_/tomcat/conf/tomcat-users.xml` file.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
. Open the `_TOMCAT_HOME_/tomcat/conf/tomcat-users.xml` file in a text editor.
. Add users and roles to the `_TOMCAT_HOME_/tomcat/conf/tomcat-users.xml` file.
endif::[]
In the following example, `<ROLE_NAME>` is a role supported by {PRODUCT}.
//For a list of supported roles, see <<dm-roles-con>>.
`<USER_NAME>` and `<USER_PWD>` are the user name and password of your choice:
+
[source]
----
<role rolename="<ROLE_NAME>"/>
<user username="<USER_NAME>" password="<USER_PWD>" roles="<ROLE_NAME>"/>
----
+
If a user has more than one role, as shown in the following example, separate the roles with a comma:
+
[source,subs="attributes+"]
----
<role rolename="admin"/>
<role rolename="kie-server"/>
<user username="{PRODUCT_INIT}User" password="user1234" roles="admin,kie-server"/>
----
. Complete one of the following steps in the
ifeval::["{context}" == "install-on-jws"]
`_JWS_HOME_/tomcat/bin` directory:
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`_TOMCAT_HOME_/tomcat/bin` directory:
endif::[]

+
* On Linux or UNIX, create the `setenv.sh` file with the following content:
+
ifdef::PAM[]
[source]
----
CATALINA_OPTS="-Xmx1024m -Dorg.jboss.logging.provider=jdk"
----
endif::PAM[]
ifdef::DM[]
[source]
----
CATALINA_OPTS="-Xmx1024m
 -Dorg.jboss.logging.provider=jdk
 -Dorg.jbpm.server.ext.disabled=true
 -Dorg.jbpm.ui.server.ext.disabled=true
 -Dorg.jbpm.case.server.ext.disabled=true"
----
endif::DM[]
* On Windows, add the following content to the `setenv.bat` file:
+
ifdef::PAM[]
[source]
----
set CATALINA_OPTS=-Xmx1024m -Dorg.jboss.logging.provider=jdk
----
endif::PAM[]
ifdef::DM[]
[source]
----
set CATALINA_OPTS="-Xmx1024m -Dorg.jboss.logging.provider=jdk -Dorg.jbpm.server.ext.disabled=true -Dorg.jbpm.ui.server.ext.disabled=true -Dorg.jbpm.case.server.ext.disabled=true
----
endif::DM[]

ifdef::PAM[]

[NOTE]
====
If you use Microsoft SQL Server, make sure you have appropriate transaction isolation for your database. If you do not, you may experience deadlocks. The recommended configuration is to turn on ALLOW_SNAPSHOT_ISOLATION and READ_COMMITTED_SNAPSHOT by entering the following statements:

[source]
----
ALTER DATABASE <DBNAME> SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE <DBNAME> SET READ_COMMITTED_SNAPSHOT ON
----
====

endif::PAM[]
