[id='patches-applying-proc_{context}']

= Applying patch updates and minor release upgrades to {PRODUCT}

Automated update tools are often provided with both patch updates and new minor versions of {PRODUCT} to facilitate updating certain components of {PRODUCT}, such as {CENTRAL}, {KIE_SERVER}, and the {HEADLESS_CONTROLLER}. Other {PRODUCT} artifacts, such as the {DECISION_ENGINE} and standalone {CENTRAL}, are released as new artifacts with each minor release and you must reinstall them to apply the update.

You can use the same automated update tool to apply both patch updates and minor release upgrades to {PRODUCT} {PRODUCT_VERSION}. Patch updates of {PRODUCT}, such as an update from version {PRODUCT_VERSION} to {PRODUCT_VERSION}.1, include the latest security updates and bug fixes. Minor release upgrades of {PRODUCT}, such as an upgrade from version 7.10.x to 7.11, include enhancements, security updates, and bug fixes.

NOTE: Only updates for {PRODUCT} are included in {PRODUCT} update tools. Updates to {EAP} must be applied using {EAP} patch distributions. For more information about {EAP} patching, see the  https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/{EAP_VERSION}/html/patching_and_upgrading_guide/[_{EAP} patching and upgrading guide_].

.Prerequisites
* Your {PRODUCT} and {KIE_SERVER} instances are not running. Do not apply updates while you are running an instance of {PRODUCT} or {KIE_SERVER}.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options.
+
If you are upgrading to a new minor release of {PRODUCT}, such as an upgrade from version 7.10.x to 7.11, first apply the latest patch update to your current version of {PRODUCT} and then follow this procedure again to upgrade to the new minor release.

. Click *Patches*, download the *{PRODUCT} [VERSION] Update Tool*, and extract the downloaded `{PRODUCT_INIT}-$VERSION-update.zip` file to a temporary directory.
+
This update tool automates the update of certain components of {PRODUCT}, such as {CENTRAL}, {KIE_SERVER}, and the {HEADLESS_CONTROLLER}. Use this update tool first to apply updates and then install any other updates or new release artifacts that are relevant to your {PRODUCT} distribution.

. If you want to preserve any files from being updated by the update tool, navigate to the extracted `{PRODUCT_INIT}-$VERSION-update` folder, open the `blacklist.txt` file, and add the relative paths to the files that you do not want to be updated.
+
When a file is listed in the `blacklist.txt` file, the update script does not replace the file with the new version but instead leaves the file in place and in the same location adds the new version with a `.new` suffix. If you block files that are no longer being distributed, the update tool creates an empty marker file with a `.removed` suffix. You can then choose to retain, merge, or delete these new files manually.
+
Example files to be excluded in `blacklist.txt` file:
+
[source]
----
WEB-INF/web.xml  // Custom file
styles/base.css  // Obsolete custom file kept for record
----
+
The contents of the blocked file directories after the update:
+
[source]
----
$ ls WEB-INF
web.xml web.xml.new
----
+
[source]
----
$ ls styles
base.css base.css.removed
----

. In your command terminal, navigate to the temporary directory where you extracted the `{PRODUCT_INIT}-$VERSION-update.zip` file and run the `apply-updates` script in the following format:
+
[IMPORTANT]
====
Make sure that your {PRODUCT} and {KIE_SERVER} instances are not running before you apply updates. Do not apply updates while you are running an instance of {PRODUCT} or {KIE_SERVER}.
====
+
On Linux or Unix-based systems:
+
[source]
----
$ ./apply-updates.sh $DISTRO_PATH $DISTRO_TYPE
----
+
On Windows:
+
[source]
----
$ .\apply-updates.bat $DISTRO_PATH $DISTRO_TYPE
----
+
The `$DISTRO_PATH` portion is the path to the relevant distribution directory and the `$DISTRO_TYPE` portion is the type of distribution that you are updating with this update.
+
The following distribution types are supported in {PRODUCT} update tool:

* `{PRODUCT_INIT}-{URL_COMPONENT_CENTRAL}-eap7-deployable`: Updates {CENTRAL} (`{URL_COMPONENT_CENTRAL}.war`)
* `{PRODUCT_INIT}-kie-server-ee8`: Updates {KIE_SERVER} (`kie-server.war`)
+
ifeval::["{context}" == "execution-server"]
[NOTE]
====
The update tool will update and replace {EAP} EE7 to {EAP} EE8. {EAP} EE7 is used for WebLogic and WebSphere, whereas version EE8 is used for {EAP}. Make sure that {KIE_SERVER} on WebLogic and WebSphere is not updated by the update tool.
====
endif::[]
ifdef::DM[]
* `{PRODUCT_INIT}-kie-server-jws`: Updates {KIE_SERVER} on {JWS} (`kie-server.war`)
endif::DM[]
ifdef::PAM[]
* `{PRODUCT_INIT}-kie-server-jws`: Updates {KIE_SERVER} on {JWS} (`kie-server.war`)
endif::PAM[]
* `{PRODUCT_INIT}-controller-ee7`: Updates the {HEADLESS_CONTROLLER} (`controller.war`)
ifdef::DM[]
* `{PRODUCT_INIT}-controller-jws`: Updates the {HEADLESS_CONTROLLER} on {JWS} (`controller.war`)
endif::DM[]
ifdef::PAM[]
* `{PRODUCT_INIT}-controller-jws`: Updates the {HEADLESS_CONTROLLER} on {JWS} (`controller.war`)
endif::PAM[]
+
Example update to {CENTRAL} and {KIE_SERVER} for a full {PRODUCT} distribution on {EAP}:
+
[source,subs="attributes+"]
----
./apply-updates.sh ~EAP_HOME/standalone/deployments/{URL_COMPONENT_CENTRAL}.war {PRODUCT_INIT}-{URL_COMPONENT_CENTRAL}-eap7-deployable

./apply-updates.sh ~EAP_HOME/standalone/deployments/kie-server.war {PRODUCT_INIT}-kie-server-ee8
----
+
Example update to {HEADLESS_CONTROLLER}, if used:
+
[source,subs="attributes+"]
----
./apply-updates.sh ~EAP_HOME/standalone/deployments/controller.war {PRODUCT_INIT}-controller-ee7
----
+
The update script creates a `backup` folder in the extracted `{PRODUCT_INIT}-$VERSION-update` folder with a copy of the specified distribution, and then proceeds with the update.

. After the update tool completes, return to the *Software Downloads* page of the Red Hat Customer Portal where you downloaded the update tool and install any other updates or new release artifacts that are relevant to your {PRODUCT} distribution.
+
For files that already exist in your {PRODUCT} distribution, such as `.jar` files for the {DECISION_ENGINE} or other add-ons, replace the existing version of the file with the new version from the Red Hat Customer Portal.
. If you use the standalone *{PRODUCT} {PRODUCT_VERSION_LONG} Maven Repository* artifact (`{PRODUCT_FILE}-maven-repository.zip`), such as in air-gap environments, download *{PRODUCT} {PRODUCT_VERSION}.x Maven Repository* and extract the downloaded `{PRODUCT_INIT}-{PRODUCT_VERSION}.x-maven-repository.zip` file to your existing `~/maven-repository` directory to update the relevant contents.
+
Example Maven repository update:
+
[source,subs="attributes+"]
----
$ unzip -o {PRODUCT_INIT}-{PRODUCT_VERSION}.x-maven-repository.zip 'rhba-{PRODUCT_VERSION}.1.GA-maven-repository/maven-repository/*' -d /tmp/rhbaMavenRepoUpdate

$ mv /tmp/rhbaMavenRepoUpdate/rhba-{PRODUCT_VERSION_LONG}.GA-maven-repository/maven-repository/ $REPO_PATH/
----
+
[NOTE]
====
You can remove the `/tmp/rhbaMavenRepoUpdate` folder after you complete the update.
====

. If you are changing {PRODUCT} from using property-based user storage to file-based user storage, complete the following steps:
+
.. Navigate to the directory where you extracted the `{PRODUCT_INIT}-$VERSION-update.zip` file and run one of the following commands to apply the `kie-fs-realm` patch:
+
* On Linux or Unix-based systems:
+
[source,subs="attributes+"]
----
$ ./elytron/kie-fs-realm-patch.sh ~/$JBOSS_HOME/standalone/configuration/kie-fs-realm-users/
----
+
* On Windows:
+
[source,subs="attributes+"]
----
$ ./elytron/kie-fs-realm-patch.bat $JBOSS_HOME/standalone/configuration/kie-fs-realm-users/
----
+
.. Navigate to the `$JBOSS_HOME` directory and run the following commands:
+
* On Linux or Unix-based systems:
+
[source,subs="attributes+"]
----
./bin/standalone.sh --admin-only -c standalone-full.xml
----
+
[source,subs="attributes+"]
----
./bin/jboss-cli.sh --connect --file={PRODUCT_INIT}-$VERSION-update/rhpam-7.12.0-update/elytron/add-kie-fs-realm.cli
----
+
* On Windows:
+
[source,subs="attributes+"]
----
./bin/standalone.bat --admin-only -c standalone-full.xml
----
+
[source,subs="attributes+"]
----
./bin/jboss-cli.bat --connect --file={PRODUCT_INIT}-$VERSION-update/rhpam-7.12.0-update/elytron/add-kie-fs-realm.cli
----

. After you finish applying all relevant updates, start {PRODUCT} and {KIE_SERVER} and log in to {CENTRAL}.
. Verify that all project data is present and accurate in {CENTRAL}, and in the top-right corner of the {CENTRAL} window, click your profile name and click *About* to verify the updated product version number.
+
If you encounter errors or notice any missing data in {CENTRAL}, you can restore the contents in the `backup` folder within the `{PRODUCT_INIT}-$VERSION-update` folder to revert the update tool changes. You can also reinstall the relevant release artifacts from your previous version of {PRODUCT} in the Red Hat Customer Portal. After restoring your previous distribution, you can try again to run the update.
