[id='patches-notifications-proc_{context}']

= Enabling Red Hat Process Automation Manager notifications in the Red Hat Customer Portal

You can enable notifications in the Red Hat Customer Portal to receive Red Hat Process Automation Manager updates and announcements. These notifications inform you of updated or added documentation, product releases, and patch updates related to Red Hat Process Automation Manager. With notifications enabled, you can more readily apply product updates to Red Hat Process Automation Manager as they become available in the Red Hat Customer Portal to keep your Red Hat Process Automation Manager distribution current with the latest enhancements and fixes.

.Prerequisites
* You have a Red Hat Customer Portal account and are logged in.

.Procedure
. In the top-right corner of the Red Hat Customer Portal window, click your profile name and click *Notifications*.
. Select the *Notifications* tab and click *Manage Notifications*.
. Next to *Follow*, select *Products* from the drop-down menu, and then select *Red Hat Process Automation Manager* from the next drop-down menu that appears.
. Click *Save Notification* to finish.

You can add notifications for any other products as needed in the same way.
