[id='persistance-config-proc_{context}']

= Configuring Persistence for {KIE_SERVER}

{PRODUCT} is configured to use the Java Naming and Directory Interface (JNDI) `java:jboss/datasources/ExampleDS` example data source by default. For production environments, specify an actual data source. Do not use the example data source in production environments.  

.Prerequisites
You have a {PRODUCT} installation.

.Procedure


. Prepare your database:
.. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}.
.. Download `{PRODUCT} {PRODUCT_VERSION}.0 Supplementary Tools`.
.. Unzip `jboss-brms-bpmsuite-{PRODUCT_VERSION}-supplementary-tools/ddl-scripts` in at temporary directory, for example  `/tmp/ddl`.
.. Import the DDL script for your database into the database you want to use, for example:
+
[source,shell]
----
psql jbpm < /tmp/ddl/postgresql/postgresql-jbpm-schema.sql
----
. Run the following command to install the Java Database Connectivity (JDBC) driver onto your application platform:
+
[source,shell]
----
./jboss-cli.sh (no need to actually connect to the server)
module add --name=org.postgresql --resources=/path/to/postgresql-jdbc-driver.jar --dependencies=javax.api,javax.transaction.api
----
. Connect to the running server and create the driver and data source, for example:
+
[source,shell]
----
./jboss-cli.sh --connect --controller=HOST:PORT 
/subsystem=datasources/jdbc-driver=postgresql:add(driver-name=postgresql,driver-module-name=org.postgresql,driver-xa-datasource-class-name=org.postgresql.xa.PGXADataSource)
xa-data-source add --driver-name=postgresql --password=SOME_PASSWORD --user-name=SOME_USERNAME --xa-datasource-properties=url=jdbc:postgresql://localhost:5432/jbpm --name=PostgresqlDS --jndi-name=java:jboss/datasources/PostgresqlDS
----
+
[NOTE]
====
Always use a distributed (XA) data source with the JBoss BPM Suite persistence service. 

In general, you should use an XA data source when multiple resources are involved in a single transaction. For example, if you are using a Java Messege Service (JMS) executor (which is used by default when asynchronous tasks are included) or timers based on Quartz, you should use an XA data source.
====

. Register the data source in {CENTRAL}:
.. Open `_EAP_HOME_/standalone/deployments/business-central.war/WEB-INF/classes/META-INF/persistence.xml`.
.. Locate the `<jta-data-source>` tag and change it to the JNDI name of your data source, for example:
+
[source,xml]
----
<jta-data-source>java:jboss/datasources/PostgresqlDS</jta-data-source>
----
+
.. Locate the `<properties>` tag and change the `hibernate.dialect` property, for example:
+
[source,xml]
----
<property name="hibernate.dialect" value="org.hibernate.dialect.PostgreSQLDialect" />
----

