[id='product-versioning-con_{context}']

= Red Hat Process Automation Manager versioning

Red Hat Process Automation Manager versions are designated with a numerical `Major.Minor.Patch` format, such as `7.11.1`. In this example, the major release is `7.x.x`, the minor release is `7.11.x`, and the patch release is `7.11.1`. Major releases often require data migration, while minor release upgrades and patch updates are typically managed with update tools provided with the Red Hat Process Automation Manager release artifacts.

The following are the general types of releases for Red Hat Process Automation Manager:

Major release migrations::

Major releases of Red Hat Process Automation Manager include substantial enhancements, security updates, bug fixes, and possibly redesigned features and functions. Data migration is typically required when an application is moved from one major release to another major release, such as from {PRODUCT_OLD} 6.4.x to Red Hat Process Automation Manager 7.0. Automated migration tools are often provided with new major versions of Red Hat Process Automation Manager to facilitate migration, but some manual effort is likely required for certain data and configurations. The supported migration paths are specified in product announcements and documentation.
+
For example migration instructions, see
ifdef::PAM[]
link:https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.0/html/migrating_from_red_hat_jboss_bpm_suite_6.4_to_red_hat_process_automation_manager_7.0/[_Migrating from {PRODUCT_OLD} 6.4 to Red Hat Process Automation Manager 7.0_].
endif::[]
ifdef::DM[]
link:https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.0/html-single/migrating_from_red_hat_jboss_brms_6.4_to_red_hat_decision_manager_7.0/[_Migrating from {PRODUCT_OLD} 6.4 to Red Hat Process Automation Manager 7.0_].
endif::[]

Minor release upgrades::

Minor releases of Red Hat Process Automation Manager include enhancements, security updates, and bug fixes. Data migration may be required when an application is moved from one minor release to another minor release, such as from Red Hat Process Automation Manager 7.10.x to 7.11. Automated update tools are often provided with both patch updates and new minor versions of Red Hat Process Automation Manager to facilitate updating certain components of Red Hat Process Automation Manager, such as {CENTRAL}, {KIE_SERVER}, and the {HEADLESS_CONTROLLER}. Other Red Hat Process Automation Manager artifacts, such as the {DECISION_ENGINE} and standalone {CENTRAL}, are released as new artifacts with each minor release and you must reinstall them to apply the update.
+
Before you upgrade to a new minor release, apply the latest patch update to your current version of Red Hat Process Automation Manager to ensure that the minor release upgrade is successful.

Patch updates::

Patch updates of Red Hat Process Automation Manager include the latest security updates and bug fixes. Scheduled patch updates contain all previously released patch updates for that minor version of the product, so you do not need to apply each patch update incrementally in order to apply the latest update. For example, you can update Red Hat Process Automation Manager 7.10.0 or 7.10.1 to Red Hat Process Automation Manager 7.10.2. However, for optimal Red Hat Process Automation Manager performance, apply product updates as they become available. Occasionally, Red Hat might release unscheduled patch updates outside the normal update cycle of the existing product. These may include security or other updates provided by Red Hat Global Support Services (GSS) to fix specific issues, and may not be cumulative updates.
+
Automated update tools are often provided with both patch updates and new minor versions of Red Hat Process Automation Manager to facilitate updating certain components of Red Hat Process Automation Manager, such as {CENTRAL}, {KIE_SERVER}, and the {HEADLESS_CONTROLLER}. Other Red Hat Process Automation Manager artifacts, such as the {DECISION_ENGINE} and standalone {CENTRAL}, are released as new artifacts with each minor release and you must reinstall them to apply the update.

To ensure optimal transition between releases and to keep your Red Hat Process Automation Manager distribution current with the latest enhancements and fixes, apply new product releases and updates to Red Hat Process Automation Manager as they become available in the Red Hat Customer Portal. Consider also enabling product notifications in the Red Hat Customer Portal.

For information about enabling product notifications, see xref:patches-notifications-proc_patching-upgrading[].
