[id='product-versioning-con']

= {PRODUCT} versioning

{PRODUCT} versions are designated with a numerical `Major.Minor.Patch` format, such as `7.1.1`. In this example, the major release is `7.x.x`, the minor release is `7.1.x`, and the patch release is `7.1.1`. Major releases often require data migration, while minor release upgrades and patch updates are typically managed with update tools provided with the {PRODUCT} release artifacts.

The following are the general types of releases for {PRODUCT}:

Major release migrations::

Major releases of {PRODUCT} include substantial enhancements, security updates, bug fixes, and possibly redesigned features and functions. Data migration is typically required when an application is moved from one major release to another major release, such as from {PRODUCT_OLD} 6.4.x to {PRODUCT} 7.0. Automated migration tools are often provided with new major versions of {PRODUCT} to facilitate migration, but some manual effort is likely required for certain data and configurations. The supported migration paths are specified in product announcements and documentation.
+
For example migration instructions, see
ifdef::PAM[]
link:https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.0/html/migrating_from_red_hat_jboss_bpm_suite_6.4_to_red_hat_process_automation_manager_7.0/[_Migrating from {PRODUCT_OLD} 6.4 to {PRODUCT} 7.0_].
endif::[]
ifdef::DM[]
{URL_MIGRATING_64_TO_7X}[_{MIGRATING_64_TO_7X}_].
endif::[]

Minor release upgrades::

Minor releases of {PRODUCT} include enhancements, security updates, and bug fixes. Data migration may be required when an application is moved from one minor release to another minor release, such as from {PRODUCT} {PRODUCT_VERSION}.x to 7.2. Automated update tools are often provided with both patch updates and new minor versions of {PRODUCT} to facilitate updating certain components of {PRODUCT}, such as {CENTRAL}, {KIE_SERVER}, and the {HEADLESS_CONTROLLER}. Other {PRODUCT} artifacts, such as the {ENGINE} and standalone {CENTRAL}, are released as new artifacts with each minor release and you must re-install them to apply the update.
+
Before you upgrade to a new minor release, apply the latest patch update to your current version of {PRODUCT} to ensure that the minor release upgrade is successful.
ifdef::DM[]
+
IMPORTANT: To upgrade from {PRODUCT} 7.0.x to {PRODUCT_VERSION}, you must use a {CENTRAL} migration tool provided with the {PRODUCT} {PRODUCT_VERSION} release to accommodate an improved project data structure in {PRODUCT} {PRODUCT_VERSION}. For migration instructions, see {URL_MIGRATING_70_TO_7X}[_{MIGRATING_70_TO_7X}_].
endif::[]

Patch updates::

Patch updates of {PRODUCT} include the latest security updates and bug fixes. Scheduled patch updates contain all previously released patch updates for that minor version of the product, so you do not need to apply each patch update incrementally in order to apply the latest update. For example, you can update {PRODUCT} {PRODUCT_VERSION}.0 or {PRODUCT_VERSION}.1 to {PRODUCT} {PRODUCT_VERSION}.2. However, for optimal {PRODUCT} performance, you should apply product updates as they become available. Occasionally, unscheduled patch updates may be released outside the normal update cycle of the existing product. These may include security or other updates provided by Red Hat Global Support Services (GSS) to fix specific issues, and may not be cumulative updates.
+
Automated update tools are often provided with both patch updates and new minor versions of {PRODUCT} to facilitate updating certain components of {PRODUCT}, such as {CENTRAL}, {KIE_SERVER}, and the {HEADLESS_CONTROLLER}. Other {PRODUCT} artifacts, such as the {ENGINE} and standalone {CENTRAL}, are released as new artifacts with each minor release and you must re-install them to apply the update.

To ensure optimal transition between releases and to keep your {PRODUCT} distribution current with the latest enhancements and fixes, apply new product releases and updates to {PRODUCT} as they become available in the Red Hat Customer Portal. Consider also enabling product notifications in the Red Hat Customer Portal.

For information about enabling product notifications, see xref:patches-notifications-proc[].
