[id='roles-users-con_{context}']
= {PRODUCT} roles and users

To access {CENTRAL} or {KIE_SERVER}, you must create users and assign them appropriate roles before the servers are started. You can create users and roles when you install {CENTRAL} or {KIE_SERVER}.

If both {CENTRAL} and {KIE_SERVER} are running on a single instance, a user who is authenticated for {CENTRAL} can also access {KIE_SERVER}.

However, if {CENTRAL} and {KIE_SERVER} are running on different instances, a user who is authenticated for {CENTRAL} must be authenticated separately to access {KIE_SERVER}. For example, if a user who is authenticated on {CENTRAL} but not authenticated on {KIE_SERVER} tries to view or manage process definitions in {CENTRAL}, a 401 error is logged in the log file and the `Invalid credentials to load data from remote server. Contact your system administrator.` message appears in {CENTRAL}.

This section describes {PRODUCT} user roles.

[NOTE]
====
The `admin`,  `analyst`,
ifdef::PAM[]
`developer`, `manager`, `process-admin`, `user`,
endif::[]
 and `rest-all` roles are reserved for {CENTRAL}. The `kie-server` role is reserved for {KIE_SERVER}. For this reason, the available roles can differ depending on whether {CENTRAL}, {KIE_SERVER}, or both are installed.
====

* `admin`: Users with the `admin` role are the {CENTRAL} administrators. They can manage users and create, clone, and manage repositories. They have full access to make required changes in the application. Users with the `admin` role have access to all areas within {PRODUCT}.
* `analyst`: Users with the `analyst` role have access to all high-level features. They can model
ifdef::PAM[]
and execute their
endif::PAM[]
projects. However, these users cannot add contributors to spaces or delete spaces in the *Design -> Projects* view. Access to the *Deploy -> Execution Servers* view, which is intended for administrators, is not available to users with the `analyst` role. However, the *Deploy* button is available to these users when they access the Library perspective.
ifdef::PAM[]
* `developer`: Users with the `developer` role have access to almost all features and can manage rules, models, process flows, forms, and dashboards. They can manage the asset repository, they can create, build, and deploy projects. Only certain administrative functions such as creating and cloning a new repository are hidden from users with the `developer` role.
* `manager`: Users with the `manager` role can view reports. These users are usually interested in statistics about the business processes and their performance, business indicators, and other business-related reporting. A user with this role has access only to process and task reports.
* `process-admin`: Users with the `process-admin` role are business process administrators. They have full access to business processes, business tasks, and execution errors. These users can also view business reports and have access to the Task Inbox list.
* `user`: Users with the `user` role can work on the Task Inbox list, which contains business tasks that are part of currently running processes. Users with this role can view process and task reports and manage processes.
endif::PAM[]

* `rest-all`: Users with the `rest-all` role can access {CENTRAL} REST capabilities.
* `kie-server`: Users with the `kie-server` role can access {KIE_SERVER} REST capabilities.
ifdef::PAM[]
This role is mandatory for users to have access to *Manage* and *Track* views in {CENTRAL}.
endif::PAM[]
