[id='securing-passwords-jws-proc_{context}']

= Securing passwords with a keystore

You can use a keystore to encrypt passwords that are used for communication between {CENTRAL} and {KIE_SERVER}. You should encrypt both controller and {KIE_SERVER} passwords. If {CENTRAL} and {KIE_SERVER} are deployed to different application servers, then both application servers should use the keystore.

Use Java Cryptography Extension KeyStore (JCEKS) for your keystore because it supports symmetric keys. Use KeyTool, which is part of the JDK installation, to create a new JCEKS.

[NOTE]
====
If {KIE_SERVER} is not configured with JCEKS, {KIE_SERVER} passwords are stored in system properties in plain text form.
====

.Prerequisites

* {KIE_SERVER} is installed in
ifeval::["{context}" == "install-on-jws"]
{JWS}.
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
{TOMCAT}.
endif::[]
* Java 8 or higher is installed.

.Procedure
ifeval::["{context}" == "install-on-jws"]
. Open the `_JWS_HOME_/tomcat/conf/tomcat-users.xml` file in a text editor.
. Add a {KIE_SERVER} user with the `kie-server` role to the `_JWS_HOME_/tomcat/conf/tomcat-users.xml` file. In the following example, replace `<USER_NAME>` and `<PASSWORD>` with the user name and password of your choice.
+
[source]
----
<role rolename="kie-server"/>
<user username="<USER_NAME>" password="<PASSWORD>" roles="kie-server"/>
----
endif::[]

ifeval::["{context}" == "install-on-tomcat"]
. Open the `_TOMCAT_HOME_/tomcat/conf/tomcat-users.xml` file in a text editor.
. Add a {KIE_SERVER} user with the `kie-server` role to the `_TOMCAT_HOME_/tomcat/conf/tomcat-users.xml` file. In the following example, replace `<USER>` and `<PASSWORD>` with the user and password of your choice.
+
[source]
----
<role rolename="<kie-server>"/>
<user username="<USER_NAME>" password="<PASSWORD>" roles="kie-server"/>
----
endif::[]


. To use KeyTool to create a JCEKS, enter the following command in the Java 8 home directory:
+
[source,bash]
----
$<JAVA_HOME>/bin/keytool -importpassword -keystore <KEYSTORE_PATH> -keypass <ALIAS_KEY_PASSWORD> -alias <PASSWORD_ALIAS> -storepass <KEYSTORE_PASSWORD> -storetype JCEKS
----
+
In this example, replace the following variables:

* `<KEYSTORE_PATH>`: The path where the keystore will be stored
* `<KEYSTORE_PASSWORD>`: The keystore password
* `<ALIAS_KEY_PASSWORD>`: The password used to access values stored with the alias
* `<PASSWORD_ALIAS>`: The alias of the entry to the process

. When prompted, enter the password for the {KIE_SERVER} user that you created.

. To set the system properties, complete one of these steps in the
ifeval::["{context}" == "install-on-jws"]
`_JWS_HOME_/tomcat/bin` directory
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
`_JWS_HOME_/tomcat/bin` directory
endif::[]
and replace the variables as described in the following table:
+
NOTE: If {CENTRAL} or the standalone controller are installed in separate instances from {JWS}, do not add the `kie.keystore.key.server.alias` and `kie.keystore.key.server.pwd` properties to `CATALINA_OPTS`.
+
* On Linux or UNIX, create the `setenv.sh` file with the following content:
+
[source]
----
set CATALINA_OPTS="
-Dkie.keystore.keyStoreURL=<KEYSTORE_URL>
-Dkie.keystore.keyStorePwd=<KEYSTORE_PWD>
-Dkie.keystore.key.server.alias=<KEY_SERVER_ALIAS>
-Dkie.keystore.key.server.pwd=<KEY_SERVER_PWD>
-Dkie.keystore.key.ctrl.alias=<KEY_CONTROL_ALIAS>
-Dkie.keystore.key.ctrl.pwd=<KEY_CONTROL_PWD>
----
* On Windows, add the following content to the `setenv.bat` file:
+
[source]
----
set CATALINA_OPTS="
-Dkie.keystore.keyStoreURL=<KEYSTORE_URL>
-Dkie.keystore.keyStorePwd=<KEYSTORE_PWD>
-Dkie.keystore.key.server.alias=<KEY_SERVER_ALIAS>
-Dkie.keystore.key.server.pwd=<KEY_SERVER_PWD>
-Dkie.keystore.key.ctrl.alias=<KEY_CONTROL_ALIAS>
-Dkie.keystore.key.ctrl.pwd=<KEY_CONTROL_PWD>
----

+
.System properties used to load a {KIE_SERVER} JCEKS
[cols="40%,30%,40%", frame="all", options="header"]
|===
| System property
| Placeholder
| Description

| `kie.keystore.keyStoreURL`
| `<KEYSTORE_URL>`
| URL for the JCEKS that you want to use, for example `\file:///home/kie/keystores/keystore.jceks`

| `kie.keystore.keyStorePwd`
| `<KEYSTORE_PWD>`
| Password for the JCEKS

| `kie.keystore.key.server.alias`
| `<KEY_SERVER_ALIAS>`
| Alias of the key for REST services where the password is stored

| `kie.keystore.key.server.pwd`
| `<KEY_SERVER_PWD>`
| Password of the alias for REST services with the stored password

| `kie.keystore.key.ctrl.alias`
| `<KEY_CONTROL_ALIAS>`
| Alias of the key for default REST Process Automation Controller where the password is stored

| `kie.keystore.key.ctrl.pwd`
| `<KEY_CONTROL_PWD>`
| Password of the alias for default REST  Process Automation Controller with the stored password

|===

. Start {KIE_SERVER} to verify the configuration.
