[id='ssh-configuring-proc_{context}']

= Configuring SSH to use RSA
SSH is used to clone Git repositories. By default, the DSA encryption algorithm is provided by Business Central. However, some SSH clients, for example SSH clients in the Fedora 23 environment, use the RSA algorithm instead of the DSA algorithm. Business Central contains a system property that you can use to switch from DSA to RSA if required.

[NOTE]
====
SSH clients on supported configurations, for example Red Hat Enterprise Linux 7, are not affected by this issue. For a list of supported configurations, see
ifdef::PAM[]
https://access.redhat.com/articles/3405381[{PRODUCT_PAM} 7 Supported Configurations].
endif::[]
ifdef::DM[]
https://access.redhat.com/articles/3354301[{PRODUCT_DM} 7 Supported Configurations].
endif::[]
====

.Procedure

Complete one of the following tasks to enable this system property:

* Modify the `~/.ssh/config` file on the client side as follows to force the SSH client to accept the deprecated DSA algorithm:
+
[source]
----
Host <SERVER_IP>
       HostKeyAlgorithms +ssh-dss
----

* Include the `-Dorg.uberfire.nio.git.ssh.algorithm=RSA` parameter when you start {CENTRAL}, for example:
+
[source]
----
$ ./standalone.sh -c standalone-full.xml
-Dorg.uberfire.nio.git.ssh.algorithm=RSA
----

= Verifying the {PRODUCT} installation

After you have installed {PRODUCT_PAM}, create an asset to verify that the installation is working.

.Procedure
. In a terminal window, navigate to the `_EAP_HOME_/bin` directory and enter the following command to start {PRODUCT_PAM}:
+
[source]
----
./standalone.sh -c standalone-full.xml
----
+
[NOTE]
====
If you deployed {CENTRAL} without {KIE_SERVER}, you can start {CENTRAL} with the `standalone.sh` script without specifying the `standalone-full.xml` file. In this case, ensure that you make any configuration changes to the `standalone.xml` file before starting {CENTRAL}.
====

. In a web browser, enter `localhost:8080/{URL_COMPONENT_CENTRAL}`.


* If you configured {PRODUCT_PAM} to run from a domain name, replace `localhost` with the domain name, for example:
+
ifdef::PAM[]
`\http://www.example.com:8080/{URL_COMPONENT_CENTRAL}`
endif::[]
ifdef::DM[]
`\http://www.example.com:8080/{URL_COMPONENT_CENTRAL}`
endif::[]
* If you configured {PRODUCT_PAM} to run in a cluster, replace `localhost` with the IP address of a particular node, for example:
+
ifdef::PAM[]
`\http://<node_IP_address>:8080/{URL_COMPONENT_CENTRAL}`
endif::[]
ifdef::DM[]
`\http://<node_IP_address>:8080/{URL_COMPONENT_CENTRAL}`
endif::[]
. Enter the `admin` user credentials that you created during installation. The {CENTRAL} home page appears.
. Select *Menu* -> *Deploy* -> *Execution Servers*.
. Confirm that *default-kieserver* is listed under *Server Configurations*.
. Select *Menu* -> *Design* -> *Projects*.
. Open the *MySpace* space.
. Click *Try Samples* -> *Mortgages* -> *OK*. The *Assets* window appears.
. Click *Add Asset* -> *Data Object*.
. Enter `MyDataObject` in the *Data Object* field and click *OK*.
. Click *Spaces* -> *MySpace* -> *Mortgages* and confirm that `MyDataObject` is in the list of assets.
//. If you are verifying a clustered installation:
//* Enter the following URL, where `<node_IP_address>` is the address of a different node of the cluster.
//* Enter same credentials that you used to log in to {CENTRAL} on the first node, where you created the `MyDataObject` asset.
//+
//`http://<node_IP_address>:8080/{URL_COMPONENT_CENTRAL}`
//* Select *Menu*-> *Design* -> *Projects*.
//* Select the *Mortgages* project.
//* Verify that `MyDataObject` is in the asset list.
. Delete the *Mortgages* project.
