[id='troubleshooting-ref_{context}']

= Troubleshooting

IBM DB2 database has problems with Dashbuilder::
If you want to use an IBM DB2 database as the underlying data source for {CENTRAL}, increase the page size for the database. The default page size of 4 kB is not sufficient for the Dashbuilder table columns size.
+
When creating the database, force the page size to 16384, for example:
+
.Adjusting Page Size
====
[source]
----
CREATE DATABASE dashb PAGESIZE 16384
----
====
+
This increase in page size for the underlying database must be performed before {PRODUCT} is run for the first time.

Non-English characters are not displayed in Dashbuilder::
+
--
If you want to use UTF 8 to display non-English characters, set the encoding at the level of database for Dashbuilder to work correctly. For example, in MySQL, add the following to the server configuration file:

[source]
----
[mysqld]
character-set-server=utf8
collation-server=utf8_general_ci
----
--




ifdef::PAM[]
Vacuumlo deletes active large objects of {PRODUCT} CLOB data::
+
--
The vacuumlo utility program removes large objects, whose OIDs are not available in the `oid` or `lo` data columns, from a PostgreSQL database. In {PRODUCT}, the `text` columns hold large object as well. As vacuumlo does not analyze any other columns than `oid` or `lo`, active objects may be deleted.

To prevent vacuumlo from deleting active large objects, run the `postgresql-jbpm-lo-trigger-clob.sql` script:

. Download *{PRODUCT} {PRODUCT_VERSION} Supplementary Tools* from the https://access.redhat.com/downloads/[Red Hat Customer Portal]. The script is located in the `ddl-scripts/postgresql/` directory.
. Make sure that the user which runs the script has the `TRIGGER` privilege on the {PRODUCT} tables and the `USAGE` privilege to allow the use of the PL/pgSQL procedural language.
. Run the script to create triggers and and the `jbpm_active_clob` table:
+
[source]
----
\i postgresql-jbpm-lo-trigger-clob.sql
----

After performing these steps, `jbpm_active_clob` is maintained by the trigger and CLOB references cannot be deleted by vacuumlo.
--
endif::[]
