[id='dependencies_add_proc']

= Adding Dependencies

After you have created a project, you can add dependencies to it to ensure that it builds and deploys properly.

.Procedure
. Open the Project Editor for the given project:
+
.. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name. For example, *MortgageProject*.
.. Click *Settings* -> *Project Settings: Project General Settings* -> *Dependencies*.
.. On the updated *Project Screen*, click the *Add* button to add a maven dependency or click the *Add from repository* button to add a dependency from the Knowledge Store (Artifact repository):
.. When adding a maven dependency, a user has to define the *Group ID*, *Artifact ID*, and the *Version ID* in the *Dependency* dialogue window.
.. When adding a dependency from the Knowledge Store, select the dependency in the displayed dialog box: the dependency will be added to the dependency table.
. Click *Save*, then click *Save* to confirm your changes.

[WARNING]
====
If you are working with modified artifacts, do not re-upload modified non-snapshot artifacts. Maven will not know these artifacts have been updated, and it will not work if it is deployed in this manner.
====
