[id='project-build-deploy-proc_{context}']
= Building and deploying a project in {CENTRAL}

You can build a project in {CENTRAL} and automatically deploy it on a {KIE_SERVER}.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name.
. In the upper-right corner, click *Build* and then *Deploy*.
+
If only one {KIE_SERVER} is connected to {CENTRAL}, or if all connected {KIE_SERVERS} are in the same server configuration, the project is automatically built and deployed.
+
If multiple server configurations are available, {CENTRAL} displays a dialog.
+
. If the dialog appears, verify or set the following values:
* *Deployment Unit Id / Deployment Unit Alias:* Verify the name and alias of the deployment unit (KIE container) running the service within the {KIE_SERVER}. You normally do not need to change these settings.
* *Server Configuration:* Select the server configuration for deploying this project. You can later deploy it to other configured servers without rebuilding the project.
* *Start Deployment Unit?:* Verify that this box is selected to start the deployment unit (KIE container). If you clear this box, the service is deployed onto the server but not started.
