[id='kie-server-wls-install-proc']
= Installing and running {KIE_SERVER} with {WEBLOGIC}

After you have configured all required system properties in {WEBLOGIC}, you can install {KIE_SERVER} with {WEBLOGIC} to streamline {PRODUCT} application management.

.Prerequisite
An {WEBLOGIC} instance is configured as described in xref:wls-configure-proc[].

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} {KIE_SERVER} for All Supported EE7 Containers*.
. Extract the downloaded `{PRODUCT_FILE}-kie-server-ee7.zip` file to a temporary directory.
. In the WebLogic Administration Console, navigate to *Deployments* to view all existing applications.
. Click *Install*.
. Navigate to the temporary directory where you downloaded and extracted the `{PRODUCT_FILE}-kie-server-ee7.zip` file, and go to `{PRODUCT_FILE}-kie-server-ee7/kie-server.war`.
. Select the `kie-server.war` file and click *Next* to continue.
. Select *Install this deployment as an application* as the targeting style and click *Next*.
. Set the application name to `kie-server` and set the security model to `DD Only`. Leave the remaining options as default and click *Next* to continue.
. In the *Additional Configuration* section, choose *No, I will review the configuration later* and click *Finish*.
. Navigate to the {KIE_SERVER} URL `http://<HOST>:<PORT>/kie-server/services/rest/server` to verify that the server is running.
+
If {KIE_SERVER} is not running, stop and restart the {WEBLOGIC} instance and try again to access the {KIE_SERVER} URL.
