[id='product-for-wls']
= {PRODUCT} for {WEBLOGIC}

{PRODUCT} is an open source decision management platform that combines business rules management and complex event processing. It includes decision management and business resource optimization capabilities. With {PRODUCT}, you can automate business decisions and make that logic available to the entire business.

{PRODUCT} uses a centralized repository for storing all resources. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic and business processes without requiring assistance from IT personnel.

{PRODUCT} is made up of {CENTRAL}, {KIE_SERVER}, and {PLANNER}.

* {CENTRAL} is the graphical user interface where you create and manage business rules.
* {KIE_SERVER} is the server where the rules and other artifacts are stored. {KIE_Server} is used to instantiate and execute rules and solve planning problems.
* {Planner} is a lightweight, embeddable planning engine that optimizes planning
problems.

This guide explains how to install Decision Server on a full profile version of {WEBLOGIC}.

For information about running the {CENTRAL} standalone JAR file and other installation options, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].
//For information about installing {PLANNER}, see {URL_INSTALLING_PLANNER}[_{INSTALLING_PLANNER}_].
