[id='wls-stop-start-proc_{context}']
= Stopping and restarting {WEBLOGIC}

After you have configured all required system properties in {WEBLOGIC}, stop and restart the Oracle server to ensure that the configurations are applied.

.Procedure
. In the WebLogic Administration Console, navigate to *Change Center* -> *Lock & Edit*.
. Under *Domain Structure*, click *Environment* -> *Servers* -> *Control*.
. Select the server that you want to stop and click *Shutdown*.
. Select *When Work Completes* to gracefully shut down the server or select *Force Shutdown Now* to stop the server immediately without completing ongoing tasks.
. On the *Server Life Cycle Assistant* pane, click *Yes* to complete the shutdown.
. After the shutdown is complete, navigate to the domain directory in the command terminal, `_WLS_HOME_/user_projects/<DOMAIN_NAME>`. For example:
+
[source]
----
WLS\user_projects\mydomain
----
. Enter one of the following commands to restart {WEBLOGIC} to apply the new configurations:
+
--
On UNIX-based operating systems:

[source]
----
startWebLogic.sh
----
On Windows operating systems:

[source]
----
startWebLogic.cmd
----
--
. Open the Administration Console in a web browser (for example, `http://localhost:7001/console/`) and log in with your credentials.
