// IMPORTANT: For 1.10 and later, save each version release notes as its own module file in the release-notes folder that this `ReleaseNotesKogito<version>.adoc` file is in, and then include each version release notes file in the chap-kogito-release-notes.adoc after Additional resources of {PRODUCT} deployment on {OPENSHIFT} section, in the following format:
//include::ReleaseNotesKogito.<version>/ReleaseNotesKogito.<version>.adoc[leveloffset=+1]

[id="ref-kogito-rn-new-features-1.36_{context}"]
= New features in {PRODUCT} 1.36.0

[role="_abstract"]
The following sections describe some of the new features or enhancements in {PRODUCT} 1.36.0.

== {PRODUCT} runtimes

=== {PRODUCT} Serverless Workflow

https://kiegroup.github.io/kogito-docs/serverlessworkflow/1.36.1.Final/release_notes.html[New features on 1.36.0].

== {PRODUCT} supporting services

=== Jobs Service Embedded Addon

A https://github.com/kiegroup/kogito-apps/tree/main/jobs-service/kogito-addons-jobs-service/kogito-addons-quarkus-jobs-service-embedded[new addon] is available to make Job Service run embedded with the Kogito application, without requiring to deploy it as an external service.

The addon is a Quarkus extension and makes use of the https://github.com/quarkiverse/quarkus-embedded-postgresql[Embedded PostgreSQL extension].

It should be used for development and it is not recommended for production environments.
