[id='business-central-settings-changing-permissions-proc']
= Changing permissions for groups and roles

You cannot change permissions for an individual user. However, you can change permissions for groups and roles. The changed permissions apply to users that have the role or belong to the group that you changed.

.Procedure
. Log in to {CENTRAL} and click *Admin* -> *Roles* or *Groups*.
. Select a role or group.
. In the *Settings* section, set the *Home Page* & *Priority* of the role or group.
. In the *Permissions* section, you can change workbench, page, editor, space, and project permissions. Expand the resource type whose permissions you want to change.
+
The list of current permissions appears.
+
. Make the desired changes.
. Click *Add Exception* to add an item not listed, and then set the permissions as required.
+
[NOTE]
====
You cannot add an exception to the Workbench resource type.
====
+
. Click *Save*.

[NOTE]
====
Any changes you make to roles or groups affect all of the users associated with that role or group.
====
