[id='configuring-environment-mode-proc']
= Configuring the environment mode in {KIE_SERVER} and {CENTRAL}

You can set {KIE_SERVER} to run in `production` mode or in `development` mode. Development mode provides a flexible deployment policy that enables you to update existing deployment units (KIE containers) while maintaining active process instances for small changes. It also enables you to reset the deployment unit state before updating active process instances for larger changes. Production mode is optimal for production environments, where each deployment creates a new deployment unit.

In a development environment, you can click *Deploy* in {CENTRAL} to deploy the built KJAR file to a {KIE_SERVER} without stopping any running instances (if applicable), or click *Redeploy* to deploy the built KJAR file and stop any running instances. The next time you deploy or redeploy the built KJAR, the previous deployment unit (KIE container) is automatically updated in the same target {KIE_SERVER}.

In a production environment, the *Redeploy* option in {CENTRAL} is disabled and you can click only *Deploy* to deploy the built KJAR file to a new deployment unit (KIE container) on a {KIE_SERVER}.

.Procedure

. To configure the {KIE_SERVER} environment mode, set the `org.kie.server.mode` system property to `org.kie.server.mode=development` or `org.kie.server.mode=production`.

. To configure the deployment behavior for a project in {CENTRAL}, go to project *Settings* -> *General Settings* -> *Version* and toggle the *Development Mode* option.
+
NOTE: By default, {KIE_SERVER} and all new projects in {CENTRAL} are in development mode.
+

You cannot deploy a project with *Development Mode* turned on or with a manually added `SNAPSHOT` version suffix to a {KIE_SERVER} that is in production mode.
