[id='configuring-openshift-connection-timeout-proc']
= Configuring OpenShift connection timeout

By default, the OpenShift route is configured to time out HTTP requests that are longer than 30 seconds. This may cause session timeout issues in {CENTRAL} resulting in the following behaviors:

* "Unable to complete your request. The following exception occurred: (TypeError) : Cannot read property 'indexOf' of null."
* "Unable to complete your request. The following exception occurred: (TypeError) : b is null."
* A blank page is displayed when clicking the *Project* or *Server* links in {CENTRAL}.

All {CENTRAL} templates already include extended timeout configuration.

To configure longer timeout on {CENTRAL} OpenShift routes, add the `haproxy.router.openshift.io/timeout: 60s` annotation on the target route:

[source,yaml,subs="attributes+"]
----
  - kind: Route
    apiVersion: v1
    id: "$APPLICATION_NAME-{PRODUCT_INIT}centr-http"
    metadata:
      name: "$APPLICATION_NAME-{PRODUCT_INIT}centr"
      labels:
        application: "$APPLICATION_NAME"
      annotations:
        description: Route for {CENTRAL}'s http service.
        haproxy.router.openshift.io/timeout: 60s
    spec:
      host: "${CENTRAL_CAPITAL_UNDER}_HOSTNAME_HTTP"
      to:
        name: "$APPLICATION_NAME-{PRODUCT_INIT}centr"
----

For a full list of global route-specific timeout annotations, see the https://docs.openshift.com/container-platform/3.3/architecture/core_concepts/routes.html#route-specific-timeouts[OpenShift Documentation].
