[id='configuring-smart-router-behavior-con']
= Configuring Smart Router behavior

In a clustered environment with multiple {KIE_SERVER}s, the default behavior is to send requests to each {KIE_SERVER} in parallel and a host of each {KIE_SERVER} is sent the request using the "round-robin" method. In the following example environment, each {KIE_SERVER} is deployed with the same KJAR but each KJAR version is different:

.Example environment
[cols="20%a,50%a,30%a", frame="all", options="header"]
|===
|Server Name
|KJAR version
|Hosts
|`kie-server1`
|`kjar:1.0` `(alias=kjar, group-id=com.example, artifact-id=sample-kjar, version=1.0)`
|`129.0.1.1, 129.0.1.2, 129.0.1.3`
|`kie-server2`
|`kjar:2.0` `(alias=kjar, group-id=com.example, artifact-id=sample-kjar, version=2.0)`
|`129.0.2.1, 129.0.2.2, 129.0.2.3`
|`kie-server3`
|`kjar:3.0` `(alias=kjar, group-id=com.example, artifact-id=sample-kjar, version=3.0)`
|`129.0.3.1, 129.0.3.2, 129.0.3.3`
|===

If you send a request, the request is sent to `kie-server1 (129.0.1.2)`, `kie-server2 (129.0.2.3)`, and `kie-server3 (129.0.3.1)`.

If you send a second request, that request is sent to the next host of each {KIE_SERVER}. For example, `kie-server1 (129.0.1.3)`, `kie-server2 (129.0.2.1)`, and `kie-server3 (129.0.3.2)`.

Smart Router has three components that you can modify to change this behavior:

ContainerResolver::
The component responsible for finding the container id to use when interacting with servers.
RestrictionPolicy::
The component responsible for disallowing Smart Router to use specific endpoints.
ConfigRepository::
The component responsible for maintaining the Smart Router configuration. This is mainly related to the routing table.
IdentityService::
The component responsible for allowing you to use your own identity provider. This is for {KIE_SERVER} instances.

Smart Router uses the `ServiceLoader` utility to implement these components:

ContainerResolver::
`META-INF/services/org.kie.server.router.spi.ContainerResolver`
RestrictionPolicy::
`META-INF/services/org.kie.server.router.spi.RestrictionPolicy`
ConfigRepository::
`META-INF/services/org.kie.server.router.spi.ConfigRepository`
IdentityService::
`META-INF/services/org.kie.server.router.identity.IdentityService`

For example, for the above scenario, you can customize the `ContainerResolver` to make Smart Router search for the latest version of the KJAR process across all available {KIE_SERVER}s and to always start with that process. This scenario would mean that each {KIE_SERVER} hosts a single KJAR and each version will share the same alias.

Since Smart Router is an executable jar, to include extensions, you need to modify the command. For example:

[source,xml,subs="attributes+"]
----
java -cp LOCATION/router-ext-{BOM_VERSION}.jar:{PRODUCT_INIT}-{ENTERPRISE_VERSION_LONG}-smart-router.jar org.kie.server.router.KieServerRouter
----

Once the service is started you will see log output stating the implementation that is used for the components:

----
Mar 01, 2017 1:47:10 PM org.kie.server.router.KieServerRouter <init>
INFO: KIE Server router repository implementation is InMemoryConfigRepository
Mar 01, 2017 1:47:10 PM org.kie.server.router.proxy.KieServerProxyClient <init>
INFO: Using 'LatestVersionContainerResolver' container resolver and restriction policy 'ByPassUserNotAllowedRestrictionPolicy'
Mar 01, 2017 1:47:10 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.6.Final
Mar 01, 2017 1:47:10 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.6.Final
Mar 01, 2017 1:47:11 PM org.kie.server.router.KieServerRouter start
INFO: KieServerRouter started on localhost:9000 at Wed Mar 01 13:47:11 CET 2017
----
