[id='_custom-tasks-placing-custom-tasks-proc-{context}']
= Placing custom tasks

When a custom task is registered in {PRODUCT} it appears in the process designer palette. The custom task is named and categorized according to the entries in its corresponding WID file.

.Prerequisites
* A custom task is registered in {PRODUCT}. For information about registering custom tasks, see <<registering-custom-tasks-proc-custom-tasks>>.
* The custom task is named and categorized according to the corresponding WID file. For more information about WID file locations or formatting, see <<custom-tasks-work-item-definitions-con-custom-tasks>>.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click a project.
. Select the business process that you want to add a custom task to.
. Select the custom task from the palette and drag it to the BPMN2 diagram.
. Optional: Change the custom task attributes. For example, change the data output and input from the corresponding WID file.

NOTE: If the WID file is not visible in your project and no `Work Item Definition` object is visible in the *Others* category of your project, you must register the custom task. For more information about registering a custom task, see <<registering-custom-tasks-proc-custom-tasks>>.
