[id='datasets-dashbuilder-runtimes-con']
= {KIE_SERVER} datasets on Dashbuilder Runtime

{KIE_SERVERS} use {CENTRAL} as a controller. This means {KIE_SERVER} containers are created by using {CENTRAL}. If other services need to retrieve {KIE_SERVER} information then they should use the {KIE_SERVER} REST API. Dashbuilder Runtime uses the {KIE_SERVER} REST API to run queries from the imported datasets.

When a {KIE_SERVER} dataset is created in {CENTRAL} the server template information is provided and it is used by Runtime to look for the {KIE_SERVER} information. For example:

----
org.dashbuilder.kieserver.serverTemplate.{SERVER_TEMPLATE}.location={LOCATION}
org.dashbuilder.kieserver.serverTemplate.{SERVER_TEMPLATE}.user={USER}
org.dashbuilder.kieserver.serverTemplate.{SERVER_TEMPLATE}.password={PASSWORD}
org.dashbuilder.kieserver.serverTemplate.{SERVER_TEMPLATE}.token={TOKEN}
----

It is also possible to setup {KIE_SERVER} per dataset. For example:

----
org.dashbuilder.kieserver.dataset.{DATA_SET_NAME}.location={LOCATION}
org.dashbuilder.kieserver.dataset.{DATA_SET_NAME}.user={USER}
org.dashbuilder.kieserver.dataset.{DATA_SET_NAME}.password={PASSWORD}
org.dashbuilder.kieserver.dataset.{DATA_SET_NAME}.token={TOKEN}
----

Notice that token authentication is not used if credentials are provided. One may also want to run the dashboard against another {KIE_SERVER} installation. Let’s say that datasets were created on a {KIE_SERVER} in DEV environment, it means that the datasets queries were created on the DEV {KIE_SERVER}. When the dashboards are exported go, let’s say, to PROD, with another {KIE_SERVER}. In that {KIE_SERVER} the queries you created in DEV won't be available, so an error will be thrown. In such cases it is possible to port queries from a dataset to another {KIE_SERVER} by using the replace query functionality. It can also be set by dataset or by server template. For example:

----
org.dashbuilder.kieserver.serverTemplate.{SERVER_TEMPLATE}.replace_query=true
----

Alternatively:

----
org.dashbuilder.kieserver.dataset.{DATA_SET_NAME}.replace_query=true
----

It needs to be set only one time so Runtime creates the queries. Once the queries are created you can remove this system property.
