[id='deployment-unit-create-proc_{context}']
= Creating a deployment unit in {CENTRAL}

One or more deployment units should already exist as part of your {PRODUCT} configuration, but if not, you can create a deployment unit from a project that was previously built in {CENTRAL}.

.Prerequisites
* The project for which you are creating the new deployment unit has been built in {CENTRAL}.

.Procedure

. In {CENTRAL}, go to *Menu* -> *Deploy* -> *Execution servers*.
. Under *Server Configurations*, select an existing configuration or click *New Server Configuration* to create a configuration.
. Under *Deployment Units*, click *Add Deployment Unit*.
. In the table within the window, select a GAV and click *Select* next to the GAV to populate the deployment unit data fields.
. Select the *Start Deployment Unit?* box to start the service immediately, or clear the box to start it later.
. Click *Finish*.
+
The new deployment unit for the service is created and placed on the {KIE_SERVERS} that are configured for this server configuration. If you have selected *Start Deployment Unit?*, the service is started.
