[id='deployment_descriptors-con']
= Deployment descriptors

Processes and rules are stored in Apache Maven based packaging and are known as knowledge archives, or KJAR. The rules, processes, assets, and other project artifacts are part of a JAR file built and managed by Maven. A file kept inside the `META-INF` directory of the KJAR called `kmodule.xml` can be used to define the KIE bases and sessions. This `kmodule.xml` file, by default, is empty.

Whenever a runtime component such as {KIE_SERVER} is about to process the KJAR, it looks up `kmodule.xml` to build the runtime representation.

Deployment descriptors supplement the `kmodule.xml` file and provide granular control over your deployment. The presence of these descriptors is optional and your deployment will proceed successfully without them. You can set purely technical properties using these descriptors, including meta values such as persistence, auditing, and runtime strategy.

These descriptors allow you to configure the {KIE_SERVER} on multiple levels, including server level default, different deployment descriptor per KJAR, and other server configurations. You can use descriptors to make simple customizations to the default {KIE_SERVER} configuration, possibly per KJAR.

You can define these descriptors in a file called `kie-deployment-descriptor.xml` and place this file next to your `kmodule.xml` file in the `META-INF` folder. You can change this default location and the file name by specifying it as a system parameter:

[source]
----
-Dorg.kie.deployment.desc.location=file:/path/to/file/company-deployment-descriptor.xml
----
