= Deployment descriptor configuration

Deployment descriptors allow the user to configure the execution server on multiple levels:

* _Server level_: The main level and the one that applies to all KJARs deployed on the server.
* _KJAR level_: This enables you to configure descriptors on a per KJAR basis.
* _Deploy time level_: Descriptors that apply while a KJAR is being deployed.

The granular configuration items specified by the deployment descriptors take precedence over the server level ones, except in case of configuration items that are collection based, which are merged. The hierarchy works like this: __deploy time configuration > KJAR configuration > server configuration__.

[NOTE]
====
The deploy time configuration applies to deployments done via the REST API.
====

For example, if the persistence mode (one of the items you can configure) defined at the server level is [parameter]``NONE`` but the same mode is specified as [parameter]``JPA`` at the KJAR level, the actual mode will be [parameter]``JPA`` for that KJAR. If nothing is specified for the persistence mode in the deployment descriptor for that KJAR (or if there is no deployment descriptor), it will fall back to the server level configuration, which in this case is [parameter]``NONE`` (or to [parameter]``JPA`` if there is no server level deployment descriptor).




[float]
== What Can You Configure?

High level technical configuration details can be configured via deployment descriptors.
The following table lists these along with the permissible and default values for each.

.Deployment Descriptors
[cols="1,1,1,1", options="header"]
|===
| Configuration
| XML Entry
| Permissible Values
| Default Value

| Persistence unit name for runtime data
| persistence-unit
| Any valid persistence package name
| org.jbpm.domain

| Persistence unit name for audit data
| audit-persistence-unit
| Any valid persistence package name
| org.jbpm.domain

| Persistence mode
| persistence-mode
| JPA, NONE
| JPA

| Audit mode
| audit-mode
| JPA, JMS or NONE
| JPA

| Runtime Strategy
| runtime-strategy
| SINGLETON, PER_REQUEST or PER_PROCESS_INSTANCE
| SINGLETON

| List of Event Listeners to be registered
| event-listeners
| Valid listener class names as [class]``ObjectModel``
| No default value

| List of Task Event Listeners to be registered
| task-event-listeners
| Valid listener class names as [class]``ObjectModel``
| No default value

| List of Work Item Handlers to be registered
| work-item-handlers
| Valid Work Item Handler classes given as [class]``NamedObjectHandler``
| No default value

| List of Globals to be registered
| globals
| Valid Global variables given as [class]``NamedObjectModel``
| No default value

| Marshalling strategies to be registered (for pluggable variable persistence)
| marshalling-strategies
| Valid [class]``ObjectModel`` classes
| No default value

| Required Roles to be granted access to the resources of the KJAR
| required-roles
| String role names
| No default value

| Additional Environment Entries for KIE session
| environment-entries
| Valid [class]``NamedObjectModel``
| No default value

| Additional configuration options of KIE session
| configurations
| Valid [class]``NamedObjectModel``
| No default value

| Classes used for serialization in the remote services
| remoteable-class
| Valid `CustomClass`
| No default value

|===

WARNING: Do not use the Singleton runtime strategy with the EJB Timer Scheduler (the default scheduler in {KIE_SERVER}) in a production environment. This combination can result in Hibernate problems under load. For more information about this limitation, see https://access.redhat.com/solutions/4065521[Hibernate issues with Singleton strategy and EJBTimerScheduler].
