[id='dm-server-configure-proc']
= Configuring the {PRODUCT} server

You can configure Red Hat Developer Studio to run the {PRODUCT} server.

.Prerequisites
* Red Hat Developer Studio is installed with the {PRODUCT} plug-ins.
* {Product} is installed in a {EAP} {EAP_VERSION} server instance.

.Procedure
. Start Red Hat Developer Studio.
. Click *Window* -> *Show View* -> *Other*, select *Server* -> *Servers*, and then click *Open* to add the server view.
. Right-click in the *Servers* pane and select *New* -> *Server* to open the server menu.
. Click *Red Hat JBoss Middleware* -> *JBoss Enterprise Application Platform 7.x* and then click *Next* to define the server.
. In the *Create a new Server Adapter* window, select *Create new runtime (next page)* from the list, and then click *Next*.
. To set the home directory in the *JBoss Runtime* window, click the *Browse* button under *Home Directory* and navigate to the {EAP} directory where {PRODUCT} is installed.
. Enter a name for the server in the *Name* field, ensure that the configuration file is set, and then click *Finish*.
