[id='execution-error-management-con']
= Execution error management

When an execution error occurs for a business process, the process stops and reverts to the most recent stable state (the closest safe point) and continues its execution. If an error of any kind is not handled by the process the entire transaction rolls back, leaving the process instance in the previous wait state. Any trace of this is only visible in the logs, and usually displayed to the caller who sent the request to the {PROCESS_ENGINE}.

Users with process administrator (`process-admin`) or administrator (`admin`) roles are able to access error messages in {CENTRAL}. Execution error messaging provides the following primary benefits:

* Better traceability
* Visibility in case of critical processes
* Reporting and analytics based on error situations
* External system error handling and compensation

Configurable error handling is responsible for receiving any technical errors thrown throughout the {PROCESS_ENGINE} execution (including task service). The following technical exceptions apply:

* Anything that extends `java.lang.Throwable`
* Process level error handling and any other exceptions not previously handled

There are several components that make up the error handling mechanism and allow a pluggable approach to extend its capabilities.

The {PROCESS_ENGINE} entry point for error handling is the `ExecutionErrorManager`. This is integrated with `RuntimeManager`, which is then responsible for providing it to the underlying `KieSession` and `TaskService`.

From an API point of view, `ExecutionErrorManager` provides access to the following components:

* `ExecutionErrorHandler`: The primary mechanism for error handling
* `ExecutionErrorStorage`: Pluggable storage for execution error information
