[id='exporting-importing-dashbuilder-data-proc-{context}']
= Exporting and importing Dashbuilder data

ifdef::PAM[]

Dashbuilder is a dashboard and reporting tool integrated in {CENTRAL} and is used by the Datasets editor and Content Manager page. There are three data types:

* Datasets
* Pages
* Navigation

You can import and export Dashbuilder data as ZIP files in {CENTRAL}.

IMPORTANT: This feature is only accessible by administrator users.

== Exporting Dashbuilder data

You can export the dashbuilder related data such as datasets, pages, and navigation from {CENTRAL} as a ZIP file.

.Procedure
. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Dashbuilder Data Transfer*.

. To export the dashbuilder related data, complete any of the following tasks:
+
--
If you want to export the entire dashbuilder data as a ZIP file, complete the following tasks:

... On the *Dashbuilder Data Transfer* page, click *Export all*.
+
An `export.zip` file containing entire dashbuilder data is downloaded. The `export.zip` file structure is separated by data type. For example:
+
[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
dashbuilder/perspectives/page1/perspective_layout
dashbuilder/perspectives/page1/perspective_layout.plugin
dashbuilder/perspectives/page2/perspective_layout
dashbuilder/perspectives/page2/perspective_layout.plugin
dashbuilder/perspectives/readme.md
dashbuilder/navigation/navigation/navtree.json
dashbuilder/navigation/readme.md
VERSION
----


If you want to export the customized user created and provided dashbuilder data as a ZIP file, complete the following tasks:

... On the *Dashbuilder Data Transfer* page, click *Custom export*.
... Select the datasets and pages that you want to include in a ZIP file in the *Export Wizard* panel and click *Next*.
+
The *Export Wizard* panel validates the selected datasets and pages. The summary of the datasets and pages is available on the panel.
+
NOTE: Navigation is always included in the exported ZIP file.

... If your export is ready, click *Download*.
+
An `export.zip` file containing customized dashbuilder data is downloaded.
+
NOTE: You must select the associated pages and datasets in the *Export Wizard* panel. If you fail to select both datasets and pages, then an error is generated and you cannot download the `export.zip` file. Therefore, you must select at least one page.

... Click *Finish*.

--

== Importing Dashbuilder data

You can import Dashbuilder data to {CENTRAL} from a ZIP file if the archive is structured in the same way as the following example:

[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
dashbuilder/perspectives/page1/perspective_layout
dashbuilder/perspectives/page1/perspective_layout.plugin
dashbuilder/perspectives/page2/perspective_layout
dashbuilder/perspectives/page2/perspective_layout.plugin
dashbuilder/perspectives/readme.md
dashbuilder/navigation/navigation/navtree.json
dashbuilder/navigation/readme.md
VERSION
----

.Procedure
. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Dashbuilder Data Transfer*.
+
WARNING: You must import Dashbuilder data to a clean installation of {PRODUCT} in order to avoid overwriting data on an existing system.

. On the *Dashbuilder Data Transfer* page, click the *Choose File* icon.

. Navigate to the ZIP file you want to import and select the file.

. Click the *Upload* icon.

. Click *Import*.

endif::PAM[]

ifdef::DM[]

Dashbuilder is a dashboard and reporting tool integrated in {CENTRAL} and is used by the Datasets editor. You can import and export Dashbuilder data as ZIP files in {CENTRAL}.

IMPORTANT: This feature is only accessible by administrator users.

== Exporting Dashbuilder data

You can export all the dashbuilder related data such as datasets from {CENTRAL} as a ZIP file.

.Procedure
. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Dashbuilder Data Transfer*.
. On the *Dashbuilder Data Transfer* page, click *Export all*.

+
An `export.zip` file containing all dashbuilder data is downloaded. The `export.zip` file structure is separated by data type. For example:
+
[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
VERSION
----

== Importing Dashbuilder data

You can import Dashbuilder data to {CENTRAL} from a ZIP file if the archive is structured in the same way as the following example:

[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
VERSION
----

.Procedure
. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Dashbuilder Data Transfer*.
+
WARNING: You should only import Dashbuilder data to a clean installation of {PRODUCT} in order to avoid overwriting data on an existing system.

. On the *Dashbuilder Data Transfer* page, click the *Choose File* icon.

. Navigate to the ZIP file you want to import and select the file.

. Click the *Upload* icon.

. Click *Import*.

endif::DM[]

ifdef::PAM[]

== Deploying dashboards from {CENTRAL} on Dashbuilder Runtime

You can automatically deploy the dashboards from {CENTRAl} on Dashbuilder Runtime. {CENTRAl} is linked to Dashbuilder Runtime using a gradual export feature.

.Prerequisites

* Dashbuilder Runtime is configured on your system.
* You have set the `dashbuilder.runtime.multi` system property to `true` in the `standalone.xml` file.
* You have set the value of `dashbuilder.runtime.location` system property to the Dashbuilder Runtime URL. For example:
+
[source]
----
<property name="dashbuilder.runtime.location" value=" http://localhost:8080"
----
* You have set the `dashbuilder.export.dir` system property to the shared directory where Dashbuilder Runtime reads its model. For example:
+
[source]
----
<property name="dashbuilder.export.dir" value="/tmp/dashbuilder/models/"
----


.Procedure

. Start {CENTRAL}, go to *Menu* → *Design* → *Pages*.
. In the *Components* panel, drag and edit the required component types to the canvas.
. Click *Save*.
. Select the *Admin* icon in the top-right corner of the screen and select *Dashbuilder Data Transfer*.
. On the *Dashbuilder Data Transfer* page, click *Custom export*.
. Select the pages that you want to include in the ZIP file in the *Export Wizard* panel, and click *Next*.
. Select *Export Wizard* and click *Open*.
+
You can see the Dashbuilder Runtime home page. If you are not logged in, you are redirected to the login page.
. Log in to the Dashbuilder Runtime.
. Go to *Dashboards* → *Runtime Dashboards* and you can see the pages.
+
The selected data is exported and Dashbuilder Runtime updates the model content when it is opened.

endif::PAM[]
