[id='exporting-importing-dashbuilder-data-proc-{context}']
= Exporting and importing Dashbuilder data

ifdef::PAM[]

Dashbuilder is a dashboard and reporting tool integrated in {CENTRAL} and is used by the Datasets editor and Content Manager page. There are three data types:

* Datasets
* Pages
* Navigation

You can import and export Dashbuilder data as ZIP files in {CENTRAL}.

IMPORTANT: This feature is only accessible by administrator users.

== Exporting Dashbuilder data

You can export the dashbuilder related data such as datasets, pages, and navigation from {CENTRAL} as a ZIP file.

.Procedure
. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Dashbuilder Data Transfer*.

. To export the dashbuilder related data, do any of the following tasks:
+
--
If you want to export all dashbuilder data as a ZIP file, do the following tasks:

... On the *Dashbuilder Data Transfer* page, click *Export all*.
+
An `export.zip` file containing all dashbuilder data is downloaded. The `export.zip` file structure is separated by data type. For example:
+
[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
dashbuilder/perspectives/page1/perspective_layout
dashbuilder/perspectives/page1/perspective_layout.plugin
dashbuilder/perspectives/page2/perspective_layout
dashbuilder/perspectives/page2/perspective_layout.plugin
dashbuilder/perspectives/readme.md
dashbuilder/navigation/navigation/navtree.json
dashbuilder/navigation/readme.md
VERSION
----


If you want to export customized user created dashbuilder data as a ZIP file, do the following tasks:

... On the *Dashbuilder Data Transfer* page, click *Custom export*.
... In *Export Wizard* panel, select the datasets that you want to include in the ZIP file and click *Next*.
... Select the pages that you want to include in the ZIP file and click *Next*.
+
The *Export Wizard* panel validates the selected datasets and pages. The summary of the datasets and pages is available on the panel.
+
NOTE: Navigation is always included in the exported `ZIP` file.

... Click *Download* if your export is ready.
+
An `export.zip` file containing customized dashbuilder data is downloaded.
+
NOTE: You must select the pages and the datasets associated with those pages in the *Export Wizard* panel. You must select at least one page. If you fail to select both datasets and pages, an export error is generated and you can not download the `export.zip` file.

... Click *Finish*.

--

== Importing Dashbuilder data

You can import Dashbuilder data to {CENTRAL} from a ZIP file if the archive is structured in the same way as the following example:

[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
dashbuilder/perspectives/page1/perspective_layout
dashbuilder/perspectives/page1/perspective_layout.plugin
dashbuilder/perspectives/page2/perspective_layout
dashbuilder/perspectives/page2/perspective_layout.plugin
dashbuilder/perspectives/readme.md
dashbuilder/navigation/navigation/navtree.json
dashbuilder/navigation/readme.md
VERSION
----

.Procedure
. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Dashbuilder Data Transfer*.
+
WARNING: You should only import Dashbuilder data to a clean installation of {PRODUCT} in order to avoid overwriting data on an existing system.

. On the *Dashbuilder Data Transfer* page, click the *Choose File* icon.

. Navigate to the ZIP file you want to import and select the file.

. Click the *Upload* icon.

. Click *Import*.

endif::PAM[]

ifdef::DM[]

Dashbuilder is a dashboard and reporting tool integrated in {CENTRAL} and is used by the Datasets editor. You can import and export Dashbuilder data as ZIP files in {CENTRAL}.

IMPORTANT: This feature is only accessible by administrator users.

== Exporting Dashbuilder data

You can export all the dashbuilder related data such as datasets from {CENTRAL} as a ZIP file.

.Procedure
. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Dashbuilder Data Transfer*.
. On the *Dashbuilder Data Transfer* page, click *Export all*.

+
An `export.zip` file containing all dashbuilder data is downloaded. The `export.zip` file structure is separated by data type. For example:
+
[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
VERSION
----

== Importing Dashbuilder data

You can import Dashbuilder data to {CENTRAL} from a ZIP file if the archive is structured in the same way as the following example:

[source]
----
dashbuilder/datasets/definitions/dataset-example1.dset
dashbuilder/datasets/definitions/dataset-example2.dset
dashbuilder/datasets/readme.md
VERSION
----

.Procedure
. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Dashbuilder Data Transfer*.
+
WARNING: You should only import Dashbuilder data to a clean installation of {PRODUCT} in order to avoid overwriting data on an existing system.

. On the *Dashbuilder Data Transfer* page, click the *Choose File* icon.

. Navigate to the ZIP file you want to import and select the file.

. Click the *Upload* icon.

. Click *Import*.

endif::DM[]
