[id='installing-dashbuilder-proc_{context}']
= Installing Dashbuilder Runtime on {EAP}

To install Dashbuilder Runtime, download the Dashbuilder Runtime WAR and create a user with the `admin` role.

.Prerequisites
* You have a {EAP} installation.
* You have created and exported a dashboard in {CENTRAL}.
For more information about exporting Dashbuilder data, see the "Exporting and importing Dashbuilder data" section in the {URL_MANAGING_SETTINGS}[_{CONFIGURING_CENTRAL}_] guide.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
+
* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_FILE}-add-ons.zip`) and extract the ZIP file.
. Navigate to the directory that contains the extracted files and extract the `{PRODUCT_FILE}-dashbuilder-runtime.zip` file.
. Copy the contents of the `dashbuilder-runtime.zip` file that you extracted into the `<EAP_HOME>/standalone/deployments` folder where `<EAP_HOME>` is the {EAP} home directory that contains your {EAP} installation.
. In the {EAP} home directory, enter the following command to create a user with the `admin` role and specify a password. In the following example, replace `<USERNAME>` and `<PASSWORD>` with the user name and password of your choice.
+
[source,bash]
----
$ ./bin/jboss-cli.sh --commands="embed-server --std-out=echo,/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity(identity=<USERNAME>),/subsystem=elytron/filesystem-realm=ApplicationRealm:set-password(identity=<USERNAME>, clear={password='<PASSWORD>'}),/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity-attribute(identity=<USERNAME>, name=role, value=['admin'])"
----
+
. In a terminal application, navigate to `__EAP_HOME__/bin`.
. Enter the following command to start {EAP}:
** On Linux or UNIX-based systems:
+
[source,bash]
----
$ ./standalone.sh -c standalone-full.xml
----
** On Windows:
+
[source,bash]
----
standalone.bat -c standalone-full.xml
----
. In a web browser, open the URL `\http://localhost:8080`.
. Log in using the credentials of the user that you created for Dashbuilder Runtime.
. When promted, upload a dashboard that you exported from {CENTRAL}.  Dashbuilder Runtime uses that dashboard until it is restarted.
