[id='installing-dashbuilder-proc_{context}']
= Installing Dashbuilder Runtime

To install Dashbuilder Runtime, download the Dashbuilder Runtime WAR and create a user with the `admin` role.

.Prerequisites
* You have created and exported a dashboard in {CENTRAL}. For more information about exporting Dashbuilder data, see the "Exporting and importing Dashbuilder data" section in the {URL_MANAGING_SETTINGS}[_{CONFIGURING_CENTRAL}_] guide.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
+
* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add Ons* (`{PRODUCT_FILE}-add-ons.zip`) and extract the ZIP file.
. Navigate to the directory that contains the extracted files and extract the `{PRODUCT_FILE}-dashbuilder-runtime.zip` file.
. copy the content of the dashbuilder-runtime.zip that you unzipped into the <EAP_HOME>/standalone/deployments folder.
. In the {EAP} home directory, enter the following command to create a user with the `admin` role and specify a password. In the following example, replace `<USER_NAME>` and `<PASSWORD>` with the user name and password of your choice.
+
[source,bash]
----
$<EAP_HOME>/bin/add-user.sh -a -e -u <USER_NAME> -p <PASSWORD> -g admin
----
+
. In a terminal application, navigate to `__EAP_HOME__/bin`.
. Enter the following command to start {EAP}:
** On Linux or UNIX-based systems:
+
[source,bash]
----
$ ./standalone.sh -c standalone-full.xml
----
** On Windows:
+
[source,bash]
----
standalone.bat -c standalone-full.xml
----
. In a web browser, open the URL `localhost:8080/{URL_COMPONENT_CENTRAL}`.
. Log in using the credentials of the user that you created for Dashbuilder Runtime.
. If promted, upload a dashboard. If no static dashboards are configured then Dashbuilder Runtime prompts you to upload a dashboard. When the dashboard is uploaded the runtime will use that dashboard until the runtime is restarted.
