[id='kie-server-accessing-runtime-data-proc']
= Accessing runtime data from {CENTRAL}

The following pages in {CENTRAL} allow you to view the runtime data of the {KIE_SERVER}:

* *Process Reports*
* *Task Reports*
* *Process Definitions*
* *Process Instances*
* *Execution Errors*
* *Jobs*
* *Tasks*

These pages use the credentials of the currently logged in user to load data from the {KIE_SERVER}. Therefore, to be able to view the runtime data in {CENTRAL}, ensure that the following conditions are met:

* The user exists in the KIE container (deployment unit) running the {CENTRAL} application. This user must have `admin`, `analyst`, or `developer` roles assigned, in addition to the `kie-server` role, with full access to the runtime data. The `manager` and `process_admin` roles also allow access to runtime data pages in {CENTRAL}.
* The user exists in the KIE container (deployment unit) running the {KIE_SERVER} and has `kie-server` role assigned.
* Communication between {CENTRAL} and the {KIE_SERVER} is established. That is, the {KIE_SERVER} is registered in the {CONTROLLER}, which is part of {CENTRAL}.
* The `deployment.{URL_COMPONENT_CENTRAL}.war` login module is present in the `standalone.xml` configuration of the server running {CENTRAL}:
+
[source,subs="attributes+"]
----
 <login-module code="org.kie.security.jaas.KieLoginModule" flag="optional" module="deployment.{URL_COMPONENT_CENTRAL}.war"/>
----
