[id='kie-server-smart-router-enable-tls-support-proc']
= Configuring Smart Router for TLS support

You can configure Smart Router (KIE Server Router) for TLS support to allow HTTPS traffic.

.Prerequisites
* {KIE_SERVER} is installed on each node of a {EAP} {EAP_VERSION} cluster.
* Smart Router is installed and configured. For more information, see
ifeval::["{context}" == "execution-server"]
{URL_INSTALLING_AND_CONFIGURING}#clustering-smart-router-install-proc_clustering-runtime-standalone[{INSTALLING_ON_EAP_CLUSTER}].
endif::[]
ifeval::["{context}" == "clustering-runtime-standalone"]
xref:clustering-smart-router-install-proc_clustering-runtime-standalone[].
endif::[]

.Procedure
* To start Smart Router with TLS support and HTTPS enabled, use the TLS keystore properties, for example:
+
[source,java]
----
java  -Dorg.kie.server.router.tls.keystore = <KEYSTORE_PATH>
      -Dorg.kie.server.router.tls.keystore.password = <KEYSTORE_PWD>
      -Dorg.kie.server.router.tls.keystore.keyalias = <KEYSTORE_ALIAS>
      -Dorg.kie.server.router.tls.port = <HTTPS_PORT>
      -jar rhpam-7.8.0-smart-router.jar
----
+
`org.kie.server.router.tls.port` is a property used to configure the HTTPS port. The default HTTPS port value is `9443`.
