[id='kie-server-upgrading-containers-proc']
= Upgrading KIE containers in {CENTRAL}

Deployed KIE containers (deployment units) can be updated without restarting the {KIE_SERVER}. This might be required in cases where business rule changes cause new versions of packages to be provisioned. You can have multiple versions of the same package provisioned and deployed.

Use the following procedure to upgrade a KIE container:

.Prerequisites
* The {KIE_SERVER} is configured with a KIE container running in {CENTRAL}.

.Procedure

. Log in to {CENTRAL}.
. In the main menu, click *Menu* -> *Deploy* -> *Execution Servers*.
. Select your server from the *Server Configurations* section on the left side of the page.
. Select the deployment unit (KIE container) you want to upgrade under the *Deployment Units* section on the left.
. Click on the *Version Configuration* tab at the top.
. Enter a new version and click *Upgrade*.
+
. Optionally, if you want a deployed container to always have the latest version of your deployment without manually editing it, set the *Version* value to *LATEST* and click *Scan Now*.
+
If a newer version of a container deployment is found in the repository during the scanning, the container is automatically upgraded to this newer version. To start the scanner in the background, click *Start Scanner* and specify a scan interval in milliseconds.
+
The *Version* value can be set to *LATEST* if you are creating a deployment for the first time.
