[id='kie-server-con_{context}']
= {KIE_SERVER}

{KIE_SERVER} is the server where the rules and other artifacts for {PRODUCT} are stored and run. {KIE_SERVER} is a standalone built-in component that can be used to instantiate and execute rules through interfaces available for REST, Java Message Service (JMS), or Java client-side applications,
ifdef::PAM[]
as well as to manage processes, jobs,
endif::PAM[]
and {PLANNER} functionality through solvers.

Created as a web deployable WAR file, {KIE_SERVER} can be deployed on any web container. The current version of the {KIE_SERVER} is included with default extensions for both {PRODUCT_DM} and {PRODUCT_PAM}.

{KIE_SERVER} has a low footprint with minimal memory consumption and therefore can be deployed easily on a cloud instance. Each instance of this server can open and instantiate multiple containers, which enables you to execute multiple rule services in parallel.

{KIE_SERVER} can be integrated with other application servers, such as {WEBLOGIC} or {WEBSPHERE}, to streamline {PRODUCT} application management.
