[id='kie-server-deactivate-kie-containers-proc']
= Activating or deactivating a KIE container on {KIE_Server}

You can now stop the creation of new process instances from a given container by deactivating it but at the same time continue working on its existing process instances and tasks. In case the deactivation is temporary, you can activate the container again later. The activation or deactivation of KIE containers do not require restarting of KIE server.

.Prerequisites
* A KIE container has been created and configured in {CENTRAL}.

.Procedure
. Log in to {CENTRAL}.
. In the main menu, click *Menu* -> *Deploy* -> *Execution Servers*.
. From the *Server Configurations* pane, which is on the left of the page, select your server.
. From the *Deployment Units* pane, select the deployment unit you want to activate or deactivate.
. Click *Activate* or *Deactivate* in the upper-right corner of the deployment unit pane.
+
You cannot create a process instance from a KIE container once it is deactivated.
