[id='kie-server-smart-router-enable-tls-support-proc_{context}']
= Configuring Smart Router for TLS support

You can configure Smart Router (KIE Server Router) for Transport Layer Security (TLS) support to allow HTTPS traffic. In addition, you can disable non-secure HTTP connections to Smart Router.

.Prerequisites
* {KIE_SERVER} is installed on each node of a {EAP} {EAP_VERSION} cluster.
* Smart Router is installed and configured. For more information, see
ifeval::["{context}" == "execution-server"]
{URL_INSTALLING_AND_CONFIGURING}#clustering-smart-router-install-proc_clustering-runtime-standalone[{INSTALLING_ON_EAP_CLUSTER}].
endif::[]
ifeval::["{context}" == "clustering-runtime-standalone"]
xref:clustering-smart-router-install-proc_clustering-runtime-standalone[].
endif::[]

.Procedure
Use one of the following methods to start Smart Router:

* To start Smart Router with TLS support and HTTPS enabled as well as allowing HTTP connections, enter the following command:
+
[source,java]
----
java  -Dorg.kie.server.router.tls.keystore = <KEYSTORE_PATH>
      -Dorg.kie.server.router.tls.keystore.password = <KEYSTORE_PASSWORD>
      -Dorg.kie.server.router.tls.keystore.keyalias = <KEYSTORE_ALIAS>
      -Dorg.kie.server.router.tls.port = <HTTPS_PORT>
      -jar rhpam-7.9.0-smart-router.jar
----
+
In this example, replace the following variables:

* `<KEYSTORE_PATH>`: The path where the keystore will be stored.
* `<KEYSTORE_PASSWORD>`: The keystore password.
* `<AKEYSTORE_ALIAS>`: The password used to access values stored with the alias.
* `<HTTPS_PORT>`: The HTTPS port. The default HTTPS port is `9443`.
+
* To start Smart Router with TLS support and HTTPS enabled and with HTTP connections disabled, enter the following command:
+
[source,java]
----
java  -Dorg.kie.server.router.tls.keystore = <KEYSTORE_PATH>
      -Dorg.kie.server.router.tls.keystore.password = <KEYSTORE_PASSWORD>
      -Dorg.kie.server.router.tls.keystore.keyalias = <KEYSTORE_ALIAS>
      -Dorg.kie.server.router.tls.port = <HTTPS_PORT>
      -Dorg.kie.server.router.port=0
      -jar rhpam-7.9.0-smart-router.jar
----
+
When the `org.kie.server.router.port` system property is set to `0` or less, then the HTTP listener is not registered. If TLS is configured then Smart Router listens on HTTPS port.
+
NOTE:  If TLS is not configured and you disable HTTP by setting `org.kie.server.router.port` to `0`, then an error occurs and Smart Router stops.
