[id='kie-server-deactivate-kie-containers-proc']
= Activating or deactivating a KIE container on {KIE_Server}

You can now stop the creation of new process instances from a given container by deactivating it but at the same time continue working on its existing process instances and tasks. In case the deactivation is temporary, you can activate the container again later. The activation or deactivation of KIE containers do not require restarting of KIE server.

.Prerequisite
A container has been created and configured in {CENTRAL}.

.Procedure
. Log in to {CENTRAL}.
. In the main menu, click *Menu* -> *Deploy* -> *Execution Servers*.
. Select your server from the *Server Configurations* section on the left side of the page.
. Select the deployment unit (KIE container) you want to activate/deactivate under the *Deployment Units* section on the left.
. Click *Activate* or *Deactivate* at the upper right hand corner.
+
Once you deactivate a given KIE container, you cannot create new process instances from it.
