[id='kie-server-managed-kie-server-con']
= Managed {KIE_SERVER}

A managed instance requires an available {CONTROLLER} to start the {KIE_SERVER}.

A {CONTROLLER} manages the {KIE_SERVER} configuration in a centralized way. Each {CONTROLLER} can manage multiple configurations at once, and there can be multiple {CONTROLLER}s in the environment. Managed {KIE_SERVER} can be configured with a list of {CONTROLLER}s, but will only connect to one at a time.

[IMPORTANT]
====
All {CONTROLLER}s should be synchronized to ensure that the same set of configuration is provided to the server, regardless of the {CONTROLLER} to which it connects.
====

When the {KIE_SERVER} is configured with a list of {CONTROLLER}s, it will attempt to connect to each of them at startup until a connection is successfully established with one of them.
If a connection cannot be established, the server will not start, even if there is a local storage available with configuration.
This ensures consistence and prevents the server from running with redundant configuration.

[NOTE]
====
To run the {KIE_SERVER} in standalone mode without connecting to {CONTROLLER}s, see <<kie-server-unmanaged-server-config-proc>>.
====
