[id='managing-business-central-editing-users-proc']
= Editing users

You can edit the users of {CENTRAL} according to your needs. From the *Users* option in *Settings*, you can change the group and role of a user. All user permissions are based on the group and role permissions of the user. You can view the user permissions from the *Permissions* tab.

.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Users*.
. From *All users*, click on the user you want to edit. All user details are displayed in the right pane.
. Click *Edit*.
* Complete the following steps to add groups to users:
.. From *Groups*, click *Add to groups*. The *Group selection for user* window opens.
.. Select or deselect the groups you want the user to be a part of.
.. Click *Add to selected groups*.
* Complete the following steps to add roles to users:
.. From *Roles* tab, click *Add roles*. The *Role selection for user* window opens.
.. Select or deselect the roles you want to assign to the user.
.. Click *Add to selected roles*.
* Complete the following step to view user permissions:
.. Click on the *Permissions* tab and expand the attributes to view user permissions.
* Complete the following steps to change the user's password,
.. Click *Change Password*. The *Change password for user* window opens.
.. Enter and confirm the new password and click *Change*.
* Complete the following steps to delete the user,
.. Click *Delete* and then click *Yes* to remove the user.
. Click *Save* to apply the changes.
