[id='managing-business-central-customizing-githook-notifications-proc']
= Customizing git hook notifications

{CENTRAL} provides a mechanism to enable users to get feedback about git hook executions using customized
messages based on a hook's `exit code`.

.Procedure

. To enable notifications, in the `standalone.xml` file, set the `appformer.git.hooks.bundle` system property to point to a `*.properties` file containing the custom messages for each `exit code`.
+
For example,
+
[source]
----
<system-properties>
  <property name="appformer.git.hooks.bundle" value="/opt/jboss-as/git-hooks-messages/Messages.properties">
  </property>
  ...
</system-properties>
----

. For displaying the messages, each line of the `*.properties` should have the following format:
+
`<exit code>=<display message>`
+
where
+
`<exit code>` is the git hook exit code
+
`<display message>` is the custom message that will be displayed to a user.
+
For example:
+
[source]
----
0=Success
1=Display Message 1
.
.
.
31=Display Message 31
----

[NOTE]
====
Its not necessary to define all the possible exit codes in the *.properties file. Notifications appear only for
the exit codes defined in the *.properties file.
====
