[id='managing-business-central-GAV-checks-proc']
= GAV check management

In {CENTRAL}, projects are identified by the *Group ID*, *Artifact ID*, and *Version* (GAV) Maven naming convention. GAV values differentiate projects and project versions as well as identify dependencies with particular projects.

By default, {CENTRAL} detects duplicate GAVs. This feature can be disabled by users with the _admin_ role.

== Configuring GAV checks and child GAV edition

This procedure describes how to configure GAV checks in {CENTRAL}.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name.
. In the project window, click the *Settings* tab.
. In the *General Settings* tab, perform any of the following tasks:
** To enable other projects to have the same GAV, select the *Disable GAV conflict check* check box.
** To enable child projects to have GAV edition, select the *Allow child GAV edition* check box.
. Click *Save*.
+
[NOTE]
====
You can click *Reset* to undo all changes.
====
+
. Click *Save* to confirm the changes.

NOTE: Duplicate GAV detection is disabled for projects in *Development Mode*. To enable duplicate GAV detection in {CENTRAL}, go to project *Settings* -> *General Settings* -> *Version* and toggle the *Development Mode* option to *OFF* (if applicable).

== Configuring GAV checks for all projects

This procedure describes how to configure GAV checks for all projects in {CENTRAL}. You can also disable GAV checks at system startup.

.Procedures

. In {CENTRAL}, select the *Admin* icon in the top-right corner of the screen and select *Projects*. The *Projects* window opens.
. In the *Advanced GAV preferences* tab, perform any of the following tasks:
** To enable other projects to have the same GAV, select the *Disable GAV conflict check* check box.
** To enable child projects to have GAV edition, select the *Allow child GAV edition* check box.
. Click *Save*.

[NOTE]
=====
You can also disable the duplicate GAV detection feature by setting the `org.guvnor.project.gav.check.disabled` system property to _true_ for {CENTRAL} at system startup:

[source]
----
$ ~/EAP_HOME/bin/standalone.sh -c standalone-full.xml
-Dorg.guvnor.project.gav.check.disabled=true
----
=====
