[id='managing-business-central-using-settings-xml-ref']
= Configuring Maven using settings.xml file

Java application development uses the Apache Maven build automation tool to build and manage software projects. Maven uses Project Object Model (POM) configuration XML files to define both, the project properties and the build process.

Maven uses repositories to store Java libraries, plug-ins, and other build artifacts. Repositories can be either local or remote. A local repository is a download of artifacts from a remote repository cached on a local machine. A remote repository is any other repository accessed using common protocols, such as `http://` when located on an HTTP server, or `file://` when located on a file server. The default repository is the public remote Maven 2 Central Repository.
Configuration of Maven is performed by modifying the settings.xml file. You can either configure global Maven settings in the `M2_HOME/conf/settings.xml` file, or user-level settings in the `USER_HOME/.m2/settings.xml` file.

[float]
== Additional resources

* {URL_PACKAGING_DEPLOYING_PROJECT}/#maven-external-configure-proc_packaging-deploying[_Configuring an external Maven repository for {CENTRAL} and {KIE_SERVER}_]
* {URL_PACKAGING_DEPLOYING_PROJECT}/#project-build-deploy-maven-proc_packaging-deploying[_Packaging and deploying a {PRODUCT} project in Maven_]
* {URL_INSTALLING_ON_EAP}/maven-repo-using-con/#maven-repo-using-con[_Maven settings and repositories for {PRODUCT}_]
* {URL_MANAGING_KIE_SERVER}/index#maven-integration-ref[_System integration with Maven_]
* http://maven.apache.org/[_Welcome to Apache Maven_]
* https://maven.apache.org/guides/introduction/introduction-to-repositories.html[_Apache Maven Project - Introduction to Repositories_]
* https://maven.apache.org/pom/index.html[_Apache Maven Parent POMs Reference_].
