[id='managing-business-central-artifact-repository-proc']
= Customizing artifact repository properties

Projects require external artifacts in order to build domain model JARs. The artifact repository holds these artifacts. The Artifact Repository is actually a Maven repository. It time stamps all the snapshots. It is mostly stored in the local hard drive. By default, the artifact repository is in ``$WORKING_DIRECTORY/repositories/kie``.

.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Artifact Repository*. The *Artifact Repository* page opens.
. From the *Properties* section,
* In *Global M2 repository directory* field, enter the path to the global repository.
* Select the *Is Global M2 repository directory enabled?* check box to enable the global repository directory.
* In *Workspace M2 repository directory* field, enter the path to the workspace repository.
* Select the *Is Workspace M2 repository directory enabled?* check box to enable the workspace repository directory.
* Select the *Is Distribution Management repository enabled?* check box to enable distribution management repository.
. Click *Save*.
