[id='managing-business-central-configuring-githooks-proc']
= Configuring git hooks

{CENTRAL} can automatically push changes to a remote repository using Git hooks. After you configure the post-commit hook, {CENTRAL} automatically pushes your changes to the remote repository.

[NOTE]
====
Currently only post-commit hooks are supported. Post-commit hooks are triggered after the commit process finishes.
====

.Procedure

. Log in to {CENTRAL}.
. Go to *Authoring* -> *Administration*.
. Below the main menu, click *Repositories* -> *Clone repository*.
. In the displayed Clone repository dialog box, fill in the repository information:
+
* Repository Name
* Organizational Unit
* Git URL: For example, `https://github.com/USERNAME/REPOSITORY_NAME.git`
+
[IMPORTANT]
=====
Use the HTTPS or Git protocol instead of a SCP-style SSH URL. {CENTRAL} does not support the basic SSH URL and an error appears if you use this URL.
=====
+
* User Name: your Git user name
* Password: your Git password

. In a terminal window, change to the created repository.
+
[source]
----
cd JBOSS_HOME/bin/.niogit/REPOSITORY_NAME.git
----

. Change the remote URL:
+
[source]
----
git remote set-url origin git@github.com:USERNAME/REPOSITORY_NAME.git
----
+
Verify that you can access the remote repository through the command line using SSH. The private SSH key for the repository should exist under the `~/.ssh/ directory`.
+
If you created a new repository, you might encounter the following error:
+
[source]
----
fatal: No such remote 'origin'
----
+
To resolve it, add the remote origin URL:
+
[source]
----
git remote add origin git@github.com:USERNAME/REPOSITORY_NAME.git
----

. Verify that the remote repository was successfully added:
+
[source]
----
git remote -v
----
+
This command should return the following output:
+
[source]
----
origin  git@github.com:USERNAME/REPOSITORY_NAME.git (fetch)
origin  git@github.com:USERNAME/REPOSITORY_NAME.git (push)
----

. Create the `post-commit` file in the `JBOSS_HOME/bin/.niogit/REPOSITORY_NAME.git/hooks` directory, set the permissions to `rwxr--r--` and add the following content:
+
[source]
----
#!/bin/sh
git push origin master
----

. Make sure that the configuration was successful by creating a new guided rule in {CENTRAL}:

.. Go to *Authoring* -> *Project Authoring* -> *New Item* -> *Guided Rule*.
.. Fill in the required information in the displayed *Create new Guided Rule* window.
.. Click *Ok*.
+
{CENTRAL} automatically pushes all changes to the remote repository.

You can also specify the `org.uberfire.nio.git.hooks` system property. Specify a directory with default hook files as the value for this property. This directory will be copied to the newly created Git repositories. See the following example of a `standalone.xml` file with this setting below:

[source]
----
<system-properties>
  <property name="org.uberfire.nio.git.hooks" value="/opt/jboss-as/git-hooks">
  </property>
  ...
</system-properties>
----
