[id='managing-business-central-data-sources-proc']
= Managing data sources

{CENTRAL} provides data source management which gives you the ability of defining data sources for accessing a database. These data sources are then used by other {CENTRAL} components like the data sets. A database driver, on the other hand, is used for enabling the communication between a data source and the targeted database.

From the *Data Source Authoring* page you can add data sources and database drivers to {CENTRAL}.

****
[discrete]
==== Adding a data source to {CENTRAL}
.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Data Sources*. The *Data Sources Authoring* page opens.
. In the *DataSource Explorer* pane, click on *+Add DataSource*. The *New data source* window opens.
. In the *New data source* window, enter the *Name*, *Connection URL*, *User*, *Password*, and the *Driver* of the data source.
. Click on *Test Connection* to verify the connection to the database.
. Click *Finish* to add the data source to {CENTRAL}.

[discrete]
==== Editing an existing data source
.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Data Sources*. The *Data Sources Authoring* page opens.
. In the *DataSource Explorer* pane, click on the data source you want to edit. The *Data Source Definition* pane will list the data source details.
. In the *Data Source Definition* pane, make the necessary changes to the *Name*, *Connection URL*, *User*, *Password*, and the *Driver* fields.
. Click on *Test Connection* to verify the connection to the database.
. Click *Update*.
. Click *Save* to confirm the changes to the data source.

[discrete]
==== Deleting a data source
.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Data Sources*. The *Data Sources Authoring* page opens.
. In the *DataSource Explorer* pane, click on the data source you want to delete. The *Data Source Definition* pane will list the data source details.
. Click *Remove*.
. Click on *Delete* to confirm the deletion of the data source.
****

****
[discrete]
==== Adding a database driver to {CENTRAL}
.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Data Sources*. The *Data Sources Authoring* page opens.
. In the *DataSource Explorer* pane, click on *+Add Driver*. The *New driver* window opens.
. In the *New driver* window, enter the *Name*, *Driver Class Name*, *Group Id*, *Artifact Id*, and the *Version* of the database driver.
. Click *Finish* to add the driver to {CENTRAL}.

[discrete]
==== Editing an existing database driver
.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Data Sources*. The *Data Sources Authoring* page opens.
. In the *DataSource Explorer* pane, select the driver you want to edit. The *Driver Definition* pane will list the driver details.
. In the *Driver Definition* pane, make the necessary changes to the *Name*, *Driver Class Name*, *Group Id*, *Artifact Id*, and the *Version* fields.
. Click *Update*.
. Click *Yes* to save the changes to the driver.

[discrete]
==== Deleting a database driver
.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Data Sources*. The *Data Sources Authoring* page opens.
. In the *DataSource Explorer* pane, select the driver you want to delete. The *Data Source Definition* pane will list the driver details.
. Click *Remove*.
. Click on *Delete* to confirm the deletion of the driver.
****
