[id='managing-business-central-GAV-checks-proc']
= Managing GAV checks

In {CENTRAL}, projects identified using GAV data. GAV stands for Group Id, Artifact, and Version.These GAV values are used to differentiate between projects and versions of the same project. Dependencies also use the GAV values to identify the project and its version.

{CENTRAL} allows for duplicate GAV detection but this feature can be over written by _admin_ role users.

[float]
==== Enabling GAV checks and child GAV edition
.Procedure
. Log in to {CENTRAL}.
. Go to *Menu* -> *Design* -> *Projects*.
. Double-click the project to open it.
. In the Project Editor window, click the *Settings* tab.
. From *General Settings*,
** Select *Disable GAV conflict check* to allow other projects to have the same GAV.
** Select *Allow child GAV edition* to allow child projects to have GAV edition.
. Click *Save*.
. Click *Save* again to confirm the changes.

[NOTE]
======
Clicking *Reset* will undo all changes.
======

[NOTE]
======
You can disable the duplicate GAV detection feature by setting the system property, `org.guvnor.project.gav.check.disabled` to _true_. The default value of this property is _false_.
======
