[id='managing-business-central-configuring-git-hooks-system-property-proc-{context}']
= Configuring Git hooks as a system property for {CENTRAL}

If you do not have an existing Git repository project or if you want to apply post-commit Git hooks to a large number of project repositories you can specify a directory containing a hook file for the value of the `org.uberfire.nio.git.hooks` system property. This directory is copied to the Git repositories.

NOTE: If you specify the `org.uberfire.nio.git.hooks` system property, all {CENTRAL} internal repositories and project repositories use the post-commit Git hook. You should only use fully qualified paths in your script.

.Prerequisites
* {PRODUCT_PAM} is installed in a {EAP} {EAP_VERSION} server instance.
* (For Windows operating system) Cygwin is installed with the Git package added during installation and the path to the Cygwin `/bin` folder is added to your environment `PATH` variable. For example, `C:\cygwin64\bin`. For more information about Cygwin installation, see http://www.cygwin.com/install.html[Installing and Updating Cygwin Packages].

.Procedure

. Create a post-commit Git hook in a directory on your local system.
+
For more information about creating post-commit Git hooks, see <<managing-business-central-creating-git-hooks-proc-configuring-central>>.

. To specify the directory with the hook file for the value of the `org.uberfire.nio.git.hooks` system property, do one of the following tasks:
+
* Add the `org.uberfire.nio.git.hooks` system property to the `standalone.xml` file. For example:
+
[source]
----
<system-properties>
  <property name="org.uberfire.nio.git.hooks" value="_EAP_HOME_/hooks">
  </property>
  ...
</system-properties>
----

* Use the `-Dorg.uberfire.nio.git.hooks` environment variable when executing {CENTRAL}. For example:
+
[source]
----
$ ./standalone.sh -c standalone-full.xml -Dorg.uberfire.nio.git.hooks=_EAP_HOME_/hooks
----

. Start {CENTRAL}.
+
The post-commit Git hook is copied to all {CENTRAL} internal repositories and project repositories.

.Additional resources
* https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks/[_Customizing Git - Git Hooks_]
