[id='managing-business-central-git-hooks-con']
= Git hooks and remote Git repository integration

Git hooks are bash scripts that execute before or after Git events such as `git commit` or `git push`. In {CENTRAL}, you can use Git hooks to configure repositories to trigger specified actions every time events happen. For more information about Git hooks, see https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks/[_Customizing Git Hooks_].

You can integrate remote Git repositories with {CENTRAL} by using post-commit Git hooks. This enables you to automate content replication between {CENTRAL} and remote repositories. For example, you can implement a real-time backup strategy where changes you make to your {CENTRAL} projects are replicated to your remote Git repositories.

[NOTE]
====
{CENTRAL} only supports post-commit Git hooks.

A post-commit Git hook executes after every commit as a sync operation. {CENTRAL} waits for the post-commit bash to complete and no other write operation occurs in the repository.
====
