[id='managing-business-central-artifacts-proc']
= Managing artifacts

You can manage artifacts from *Artifacts* page in {CENTRAL}. The Artifact Repository is a Maven repository and there is only one Maven repository for every installation.

The *Artifacts* page lists all the artifacts in the Maven repository. You can also upload a new artifact to the Maven repository using the *Upload* button.

[NOTE]
=====
Only _*.jar_, _*.kjar_, or _pom.xml_ files can be uploaded to the Artifacts repository.
=====

[float]
==== Opening/viewing artifact
.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Artifacts*.
. Click *Open* to view the artifact details.
. Click *Ok* to go back to the *Artifacts* page.

[float]
==== Downloading an artifact
.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Artifacts*.
. Click *Download*.
. Browse to the directory where you wish to save the artifact and click *Save*.

[float]
==== Uploading an artifact
.Procedure
. Log in to {CENTRAL}.
. Go to *Admin* -> *Artifacts*.
. Click *Upload*.
. Click *Choose File...* and browse to the directory from where you want to upload the artifact.
. Click *Upload*.
