[id='maven-settings-configuration-ref_{context}']

= Modifying the Maven settings file

{PRODUCT} uses Maven `settings.xml` file to configure it's Maven execution. You must create and activate a profile in the `settings.xml` file and declare the Maven repositories used by your {PRODUCT} projects.

For information about the Maven `settings.xml` file, see the Apache Maven Project  https://maven.apache.org/settings.html[Setting Reference].

.Procedure
. In the `settings.xml` file, declare the Maven repository that you download from the {PRODUCT_DOWNLOAD_LINK}[IBM Business Automation Manager Open Editions 8.0 downloads] page and any repositories for custom artifacts that you want to use.
. Ensure that {CENTRAL} or {KIE_SERVER} is configured to use the `settings.xml` file. For example, specify the `kie.maven.settings.custom=<SETTINGS_FILE_PATH>` property where `<SETTINGS_FILE_PATH>` is the path to the `settings.xml` file.
+
ifeval::["{context}" == "install-on-jws"]
On {JWS}, for {KIE_SERVER} add `-Dkie.maven.settings.custom=<SETTINGS_FILE_PATH>` to the  `CATALINA_OPTS` section of the `setenv.sh` (Linux) or `setenv.bat` (Windows) file. For standalone {CENTRAL}, enter the following command:
+
[source,subs="attributes+"]
----
java -jar {PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-BCS.Jar --cli-script=application-script.cli -Dkie.maven.settings.custom=<SETTINGS_FILE_PATH>
----
endif::[]
ifeval::["{context}" == "install-on-tomcat"]
On {TOMCAT}, for {KIE_SERVER} add `-Dkie.maven.settings.custom=<SETTINGS_FILE_PATH>` to the  `CATALINA_OPTS` section of the `setenv.sh` (Linux) or `setenv.bat` (Windows) file. For standalone {CENTRAL}, enter the following command:
+
[source]
----
java -jar {PRODUCT_INIT_TOP}-{PRODUCT_VERSION}-BCS.Jar --cli-script=application-script.cli -Dkie.maven.settings.custom=<SETTINGS_FILE_PATH>
----
endif::[]
