[id='maven-external-export-proc_{context}']
= Exporting a {CENTRAL} project to an external Maven repository

If you configured an external Maven repository for {CENTRAL} and {KIE_SERVER}, you must add the repository information in the `pom.xml` file for each {CENTRAL} project that you want to export or push as a KJAR artifact to that external repository. You can then progress the project KJAR files through the repository as necessary to implement your integration process, and deploy the KJAR files using {CENTRAL} or the {KIE_SERVER} REST API.

.Prerequisites
* You configured {CENTRAL} and {KIE_SERVER} to use an external Maven repository. If you deployed {CENTRAL} on-premise, for more information about configuring an external Maven repository, see xref:maven-external-configure-proc_packaging-deploying[]. If you deployed your authoring environment on {OPENSHIFT}, for more information, see the following documents:
+
ifdef::PAM[]
** {URL_DEPLOYING_AUTHORING_ON_OPENSHIFT}#template-deploy-optionalmaven-authoring-proc[_{DEPLOYING_AUTHORING_ON_OPENSHIFT}_]
endif::PAM[]
ifdef::DM[]
** {URL_DEPLOYING_AUTHORING_MANAGED_ON_OPENSHIFT}#template-deploy-optionalmaven-authoring-proc[_{DEPLOYING_AUTHORING_MANAGED_ON_OPENSHIFT}_]
endif::DM[]
** {URL_DEPLOYING_OPENSHIFT_OPERATOR}#operator-deploy-kieserver-proc[_{DEPLOYING_OPENSHIFT_OPERATOR}_]


.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects*, click the project name, and select any asset in the project.
. In the *Project Explorer* menu on the left side of the screen, click the *Customize View* gear icon and select *Repository View* -> *pom.xml*.
. Add the following settings at the end of the project `pom.xml` file (before the `</project>` closing tag). The values must correspond to the settings that you defined in your `settings.xml` file.
+
[source,xml]
----
<distributionManagement>
<repository>
<id>${maven-repo-id}</id>
<url>${maven-repo-url}</url>
<layout>default</layout>
</repository>
</distributionManagement>
----
. Click *Save* to save the `pom.xml` file changes.

Repeat this procedure for each {CENTRAL} project that you want to export or push as a KJAR artifact to the external Maven repository.
