[id='maven-external-configure-proc_{context}']
= Configuring an external Maven repository for {CENTRAL} and {KIE_SERVER}

You can configure {CENTRAL} and {KIE_SERVER} to use an external Maven repository, such as Nexus or Artifactory, instead of the built-in repository. This enables {CENTRAL} and {KIE_SERVER} to access and download artifacts that are maintained in the external Maven repository.

[NOTE]
====
For information about configuring an external Maven repository for an authoring environment on {OPENSHIFT}, see the following documents:

ifdef::PAM[]
* {URL_DEPLOYING_AUTHORING_ON_OPENSHIFT}#template-deploy-optionalmaven-authoring-proc[_{DEPLOYING_AUTHORING_ON_OPENSHIFT}_]
endif::PAM[]
ifdef::DM[]
* {URL_DEPLOYING_AUTHORING_MANAGED_ON_OPENSHIFT}#template-deploy-optionalmaven-authoring-proc[_{DEPLOYING_AUTHORING_MANAGED_ON_OPENSHIFT}_]
endif::DM[]
* {URL_DEPLOYING_OPENSHIFT_OPERATOR}#operator-deploy-central-proc[_{DEPLOYING_OPENSHIFT_OPERATOR}_]
====

.Prerequisites
* {CENTRAL} and {KIE_SERVER} are installed. For installation options, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].

.Procedure
. Create a Maven `settings.xml` file with connection and access details for your external repository. For details about the `settings.xml` file, see the Maven link:https://maven.apache.org/settings.html[Settings Reference].
. Save the file in a known location, for example, `/opt/custom-config/settings.xml`.
. In your {PRODUCT} installation directory, navigate to the `standalone-full.xml` file. For example, if you use a {EAP} installation for {PRODUCT}, go to `$EAP_HOME/standalone/configuration/standalone-full.xml`.
. Open `standalone-full.xml` and under the `<system-properties>` tag, set the `kie.maven.settings.custom` property to the full path name of the `settings.xml` file.
+
--
For example:

[source,xml]
----
<property name="kie.maven.settings.custom" value="/opt/custom-config/settings.xml"/>
----
--
. Start or restart {CENTRAL} and {KIE_SERVER}.

.Next steps
For each {CENTRAL} project that you want to export or push as a KJAR artifact to the external Maven repository, you must add the repository information in the project `pom.xml` file. For instructions, see
ifeval::["{context}" == "packaging-deploying"]
xref:maven-external-export-proc_packaging-deploying[].
endif::[]
ifeval::["{context}" != "packaging-deploying"]
{URL_PACKAGING_DEPLOYING_PROJECT}#maven-external-export-proc_packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].
endif::[]
