[id='proc-configuring-kie-server-persistence_{context}']

= Configuring {KIE_SERVER} persistence

You can configure the {KIE_SERVER} persistence by passing Hibernate or JPA parameters as system properties.

The {KIE_SERVER} can acknowledge the system properties with the following prefixes and you can use every Hibernate or JPA parameters with these prefixes:

* `javax.persistence`
* `hibernate`

.Procedure

. To configure {KIE_SERVER} persistence, complete any of the following tasks:

+
--
If you want to configure {KIE_SERVER} persistence using {EAP} configuration file, complete the following tasks:

... In your {PRODUCT} installation directory, navigate to the `standalone-full.xml` file. For example, if you use {EAP} installation for {PRODUCT}, go to `$EAP_HOME/standalone/configuration/standalone-full.xml` file.
... Open the `standalone-full.xml` file and under the `<system-properties>` tag, set your Hibernate or JPA parameters as system properties.
+
.Example of configuring {KIE_SERVER} persistence using Hibernate parameters
+
[source,xml,subs="attributes+"]
----
<system-properties>
    ...
        <property name="hibernate.hbm2ddl.auto" value="create-drop"/>
    ...
<system-properties>
----
+
.Example of configuring {KIE_SERVER} persistence using JPA parameters
+
[source,xml,subs="attributes+"]
----
<system-properties>
    ...
        <property name="javax.persistence.jdbc.url" value="jdbc:mysql://mysql.db.server:3306/my_database?useSSL=false&serverTimezone=UTC"/>
    ...
<system-properties>
----

If you want to configure {KIE_SERVER} persistence using command line, complete the following tasks:

... Pass the parameters directly from the command line using `-Dkey=value` as follows:
+
.Example of configuring {KIE_SERVER} persistence using Hibernate parameters:
+
[source]
----
$EAP_HOME/bin/standalone.sh -Dhibernate.hbm2ddl.auto=create-drop
----
+
.Example of configuring {KIE_SERVER} persistence using JPA parameters:
+
[source]
----
$EAP_HOME/bin/standalone.sh -Djavax.persistence.jdbc.url=jdbc:mysql://mysql.db.server:3306/my_database?useSSL=false&serverTimezone=UTC
----

--
