[id='safe-points-configuring-proc']
= Configuring safe points

To allow persistence, add the `jbpm-persistence` JAR files to the classpath of your application and configure the {PROCESS_ENGINE} to use persistence. The {PROCESS_ENGINE} automatically stores the runtime state in the storage when the {PROCESS_ENGINE} reaches a safe point.

Safe points are points where the process instance has paused. When a process instance invocation reaches a safe point in the {PROCESS_ENGINE}, the {PROCESS_ENGINE} stores any changes to the process instance as a snapshot of the process runtime data. However, when a process instance is completed, the persisted snapshot of process instance runtime data is automatically deleted.

BPMN2 safe point nodes ensure that the {PROCESS_ENGINE} saves the state of the process definition at the point where the execution stops and the transaction is committed. The following BPMN2 nodes are considered safe points:

* All intermediate CATCH events
** Timer Intermediate event
** Error Intermediate event
** Conditional Intermediate event
** Compensation Intermediate event
** Signal Intermediate event
** Escalation Intermediate event
** Message Intermediate event
* User tasks
* Custom (defined by the user) service tasks that do not complete the task in the handler

If a failure occurs and you need to restore the {PROCESS_ENGINE} runtime from the storage, the process instances are automatically restored and their execution resumes so there is no need to reload and trigger the process instances manually.

Consider the runtime persistence data to be internal to the {PROCESS_ENGINE}. You should not access persisted runtime data or modify them directly because this might have unexpected side effects.

For more information about the current execution state, refer to the history log. Query the database for runtime data only if absolutely necessary.
