[id='safe-points-configuring-proc']
= Configuring safe points

To allow persistence, add the `jbpm-persistence` JAR files to the classpath of your application and configure the {PROCESS_ENGINE} to use persistence. The {PROCESS_ENGINE} automatically stores the runtime state in the storage when the {PROCESS_ENGINE} reaches a safe point.

Safe points are points where the process instance has paused. When a process instance invocation reaches a safe point in the {PROCESS_ENGINE}, the {PROCESS_ENGINE} stores any changes to the process instance as a snapshot of the process runtime data. However, when a process instance is completed, the persisted snapshot of process instance runtime data is automatically deleted.

If a failure occurs and you need to restore the {PROCESS_ENGINE} runtime from the storage, the process instances are automatically restored and their execution resumes so there is no need to reload and trigger the process instances manually.

The runtime persistence data is to be considered internal to the {PROCESS_ENGINE}. You should not access persisted runtime data or modify them directly as this might have unexpected side effects. 

For more information about the current execution state, refer to the history log. Query the database for runtime data only if absolutely necessary.
