[id='service-stop-remove-proc_{context}']

= Stopping and removing a service in {KIE_SERVER}

If you have started {PRODUCT} services from a Maven or Java project outside of {CENTRAL}, you use a {KIE_SERVER} REST API call to stop and remove the KIE container (deployment unit) containing the services. You can use the {KIE_SERVER} REST API to stop services regardless of your deployment type, including deployment from {CENTRAL}, but services from {CENTRAL} can also be stopped within the {CENTRAL} interface.

.Prerequisites
* {KIE_SERVER} is installed and `kie-server` user access is configured. For installation options, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].

.Procedure
In your command terminal, run the following API request to stop and remove a KIE container with services on {KIE_SERVER}:

[source]
----
$ curl --user "<username>:<password>" -X DELETE http://<serverhost>:<serverport>/kie-server/services/rest/server/containers/<containerID>
----

Replace the following values:

* *<username>*, *<password>:* The user name and password of a user with the `kie-server` role.
* *<containerID>:* The identifier for the KIE container (deployment unit). You can use any random identifier but it must be the same in both places in the command (the URL and the data).
* *<serverhost>:* The host name for the {KIE_SERVER}, or `localhost` if you are running the command on the same host as the {KIE_SERVER}.
* *<serverport>:* The port number for the {KIE_SERVER}.

Example:

[source,subs="attributes+"]
----
curl --user "{PRODUCT_INIT}Admin:password@1" -X DELETE http://localhost:39043/kie-server/services/rest/server/containers/kie1
----
