[id='service-start-proc_{context}']

= Starting a service in {KIE_SERVER}

If you have deployed {PRODUCT} assets from a Maven or Java project outside of {CENTRAL}, you use a {KIE_SERVER} REST API call to start the KIE container (deployment unit) and the services in it. You can use the {KIE_SERVER} REST API to start services regardless of your deployment type, including deployment from {CENTRAL}, but projects deployed from {CENTRAL} either are started automatically or can be started within the {CENTRAL} interface.

.Prerequisites
* {KIE_SERVER} is installed and `kie-server` user access is configured. For installation options, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].

.Procedure
In your command terminal, run the following API request to load a service into a KIE container in the {KIE_SERVER} and to start it:

[source]
----
$ curl --user "<username>:<password>" -H "Content-Type: application/json" -X PUT -d '{"container-id" : "<containerID>","release-id" : {"group-id" : "<groupID>","artifact-id" : "<artifactID>","version" : "<version>"}}' http://<serverhost>:<serverport>/kie-server/services/rest/server/containers/<containerID>
----

Replace the following values:

* *<username>*, *<password>:* The user name and password of a user with the `kie-server` role.
* *<containerID>:* The identifier for the KIE container (deployment unit). You can use any random identifier but it must be the same in both places in the command (the URL and the data).
* *<groupID>*, *<artifactID>*, *<version>:* The project GAV values.
* *<serverhost>:* The host name for the {KIE_SERVER}, or `localhost` if you are running the command on the same host as the {KIE_SERVER}.
* *<serverport>:* The port number for the {KIE_SERVER}.

Example:

[source,subs="attributes+"]
----
curl --user "{PRODUCT_INIT}Admin:password@1" -H "Content-Type: application/json" -X PUT -d '{"container-id" : "kie1","release-id" : {"group-id" : "org.kie.server.testing","artifact-id" : "container-crud-tests1","version" : "2.1.0.GA"}}' http://localhost:39043/kie-server/services/rest/server/containers/kie1
----
