[id='viewing-task-variables-advanced-filters-in-bc-proc']
= Viewing task variables using advanced filters

You can use the *Advanced Filters* option in {CENTRAL} to view task variables in *Manage Tasks* and *Task Inbox*. When you create a filter with the task defined, you can view the task variables of the task as columns using *Show/hide columns*.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Manage* -> *Tasks* or  go to *Menu* -> *Track* -> *Task Inbox*.
. On the *Manage Tasks* page or the *Task Inbox* page, click the advanced filters icon to expand the *Advanced Filters* panel.
. In the *Advanced Filters* panel, enter the name and description of the filter, and click *Add New*.
. From the *Select column* list, select the `name` attribute. The value will change to *name != value1*.
. From the *Select column* list, select *equals to* for the logical query.
. In the text field, enter the name of the task.
. Click *Save* and the filter is applied on the current task list.
. Click *Show/hide columns* on the upper right of the tasks list and the task variables of the specified task id will be displayed.
. Click the star icon to open the *Saved Filters* panel.
+
In the *Saved Filters* panel, you can view all the saved advanced filters.
