[id='direct-firing-option']

= New `DirectFiringOption` to fire the activation of a `KieSession`

As per the default configuration, a `KieSession` enqueues activations that need to be fired to an agenda. After that, the same agenda applies a conflict resolution strategy to select the activation that needs to be fired first, for example selecting the activation based on the `salience`. However, a conflict resolution strategy is not required if the order of rules to be fired is not relevant. This entire process requires additional performance costs. Therefore, a new `DirectFiringOption` is introduced, which you can use to optionally disable the agenda that leads to firing each activation directly when the activation is created. The `DirectFiringOption` consists of two values including `YES` and `NO` (default).

You can set the `DirectFiringOption` as `YES` when a conflict resolution strategy is not required, to avoid the additional performance costs. You can set the `DirectFiringOption` for a specific `KieSession` in the `kmodule.xml` file or you can use the following system property to set the option for all KIE sessions.

.Example `kmodule.xml` file
[source,xml]
----
<ksession name="KSession1" directFiring="true">
----

.System property for `DirectFiringOption`
[source,java]
----
drools.directFiring=true
----
