[id='direct-firing-option']

= New `DirectFiringOption`

By default, a `KieSession` enqueues the activations to be fired into an agenda. Then the agenda applies a conflict resolution strategy to decide which activation has to be fired first, for instance based on their `salience`. However, in cases when the order of rules to be fired is not relevant and then no conflict resolution strategy is required, this mechanism imposes an avoidable additional performance cost. Therefore, a new `DirectFiringOption` is introduced to optionally disable the agenda and firing each actvation directly, immediately after it has been created.

The new `DirectFiringOption` consists of two values including `YES` and `NO`.  The default value of `DirectFiringOption` is `NO`. However, when a confict resolution for the activations to be fired is not required, then set the value of `DirectFiringOption` as `YES` to avoid its performance cost. It is possible to set this option either in the `kmodule.xml` file for a specific `KieSession` or using the following system property for all KieSession.

.Example `kmodule.xml` file
[source,xml]
----
<ksession name="KSession1" directFiring="true">
----

.System property for DirectFiringOption
[source,java]
----
drools.directFiring=true
----
