[id='log-to-jms-con_{context}']
= Configuration for sending the process events log to a JMS queue

When the {PROCESS_ENGINE} stores events in the database with the default audit log implementation, the database operation is completed synchronously, within the same transaction as the actual execution of the process instance. This operation takes time, and on highly loaded systems it might have some impact on database performance, especially when both the history log and the runtime data are stored in the same database.

As an alternative, you can use the JMS-based logger that the {PROCESS_ENGINE} provides. You can configure this logger to submit process log entries as messages to a JMS queue, instead of directly persisting them in the database.

You can configure the JMS logger to be transactional, in order to avoid data inconsistencies if a {PROCESS_ENGINE} transaction is rolled back. 

.Using the JMS audit logger
[source,java]
----

ConnectionFactory factory = ...;
Queue queue = ...;
StatefulKnowledgeSession ksession = ...;
Map<String, Object> jmsProps = new HashMap<String, Object>();
jmsProps.put("jbpm.audit.jms.transacted", true);
jmsProps.put("jbpm.audit.jms.connection.factory", factory);
jmsProps.put("jbpm.audit.jms.queue", queue);
ksession.addProcessEventListener(AuditLoggerFactory.newInstance(Type.JMS, ksession, jmsProps));

// invoke methods one your session here
----


This is just one of the possible ways to configure JMS audit logger. You can use the `AuditLoggerFactory` class to set additional configuration parameters.
// I could not find a reference to a recent javadoc
