[id='persistence-processstate-con_{context}']
= Persistence of process runtime states

The {PROCESS_ENGINE} supports persistent storage of the runtime state of running process instances. Because it stores the runtime states, it can continue execution of a process instance if the {PROCESS_ENGINE} stopped or encountered a problem at any point.

The {PROCESS_ENGINE} also persistently stores the process definitions and the history logs of current and previous process states.

You can use the `persistence.xml` file, specified by the JPA framework, to configure persistence in an SQL database. You can plug in different persistence strategies. For more information about the `persistence.xml` file, see xref:persistence-configuration-file-con_{context}[].

By default, if you do not configure persistence in the {PROCESS_ENGINE}, process information, including process instance states, is not made persistent.

When the {PROCESS_ENGINE} starts a process, it creates a _process instance_, which represents the execution of the process in that specific context. For example, when executing a process that processes a sales order, one process instance is created for each sales request.

The process instance contains the current runtime state and context of a process, including current values of any process variables. However, it does not include information about the history of past states of the process, as this information is not required for ongoing execution of a process.

When the runtime state of process instances is made persistent, you can restore the state of execution of all running processes in case the {PROCESS_ENGINE} fails or is stopped. You can also remove a particular process instance from memory and then restore it at a later time.

If you configure the {PROCESS_ENGINE} to use persistence, it automatically stores the runtime state into the database. You do not need to trigger persistence in the code.

When you restore the state of the {PROCESS_ENGINE} from a database, all instances are automatically restored to their last recorded state. Process instances automatically resume execution if they are triggered, for example, by an expired timer, the completion of a task that was requested by the process instance, or a signal being sent to the process instance. You do not need to load separate instances and trigger their execution manually.

The {PROCESS_ENGINE} also automatically reloads process instances on demand.

