[id='cep-event-metadata-ref_{context}']

= Metadata tags for events

The {DECISION_ENGINE} uses the following metadata tags for events that are inserted into the working memory of the {DECISION_ENGINE}. You can change the default metadata tag values in your Java class or DRL rule file as needed.

[NOTE]
====
The examples in this section assume that the application domain model includes the following class:

.The VoiceCall fact class
[source,java]
----
/**
 * A class that represents a voice call in a Telecom domain model
 */
public class VoiceCall {
  private String  originNumber;
  private String  destinationNumber;
  private Date    callDateTime;
  private long    callDuration;  // in milliseconds

  // Constructors, getters, and setters
}
----
====

@role::
This tag determines whether a given fact type is handled as a regular fact or an event.
+
--
Default parameter: `fact`

Supported parameters: `fact`, `event`

[source]
----
@role( <fact_or_event> )
----

.Example: Declare VoiceCall as event type
[source]
----
declare VoiceCall
  @role( event )
end
----
--

@timestamp::
This tag is automatically assigned to every event in the {DECISION_ENGINE}. By default, the time is provided by the session clock and assigned to the event when it is inserted into the working memory of the {DECISION_ENGINE}. You can specify a custom time stamp attribute instead of the default time stamp added by the session clock.
+
--
Default parameter: The time added by the {DECISION_ENGINE} session clock

Supported parameters: Session clock time or custom time stamp attribute

[source]
----
@timestamp( <attributeName> )
----

.Example: Declare VoiceCall timestamp attribute
[source]
----
declare VoiceCall
  @role( event )
  @timestamp( callDateTime )
end
----
--

@duration::
This tag determines the duration time for events in the {DECISION_ENGINE}. Events can be interval-based events or point-in-time events. Interval-based events have a duration time and persist in the working memory of the {DECISION_ENGINE} until their duration time has lapsed. Point-in-time events have no duration and are essentially interval-based events with a duration of zero. By default, every event in the {DECISION_ENGINE} has a duration of zero. You can specify a custom duration attribute instead of the default.
+
--
Default parameter: null (zero)

Supported parameters: Custom duration attribute

[source]
----
@duration( <attributeName> )
----

.Example: Declare VoiceCall duration attribute
[source]
----
declare VoiceCall
  @role( event )
  @timestamp( callDateTime )
  @duration( callDuration )
end
----
--

@expires::
This tag determines the time duration before an event expires in the working memory of the {DECISION_ENGINE}. By default, an event expires when the event can no longer match and activate any of the current rules. You can define an amount of time after which an event should expire. This tag is available only when the {DECISION_ENGINE} is running in stream mode.
+
--
Default parameter: null (event expires after event can no longer match and activate rules)

Supported parameters: Custom `timeOffset` attribute in the format `[##d][#h][#m][#s][#[ms]]`
// I had to put two #'s above for it to render only one. Otherwise removed the # from [d]. (Stetson, 28 May 2019)

[source]
----
@expires( <timeOffset> )
----

.Example: Declare expiration offset for VoiceCall events
[source]
----
declare VoiceCall
  @role( event )
  @timestamp( callDateTime )
  @duration( callDuration )
  @expires( 1h35m )
end
----
--
