[id='ba-fuse-xml-con']
= Installing {PRODUCT} features on Karaf through XML files

Features files are XML files that specify which OSGI bundles are installed for a particular feature. The following features XML files facilitate {PRODUCT} and {FUSE} on Karaf integration:

* `rhba-features-<FUSE-VERSION>-features.xml`
+
This file is part of {FUSE} installed in Karaf where `<FUSE-VERSION>` is the version of Fuse. It is stored in the Karaf system repository, in the `system/org/jboss/fuse/features/rhba-features` directory. This file contains prerequisites for installing {PRODUCT} features.

* `kie-karaf-features-{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-features-fuse.xml`
+
This file is part of {PRODUCT} and provides {PRODUCT} features, which define the OSGi features that can be deployed into {FUSE_LONG}. OSGi users can install features from this file to install {PRODUCT} into {FUSE} and use it in their applications. You can find this features file in the online and offline Maven repository that is distributed with {PRODUCT}. The group ID, artifact ID, and version (GAV) identifier of this file is `org.kie:kie-karaf-features:{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}`.
