[id='ba-fuse-karaf-features-xml']
= {PRODUCT} and {FUSE} on Karaf features XML files

The following features XML files facilitate {PRODUCT} and {FUSE} on Karaf integration:

* `rhba-features-<FUSE-VERSION>-features.xml`
+
This file is part of {FUSE} installed in Karaf where `<FUSE-VERSION>` is the version of Fuse. It is stored in the Karaf system repository, in the `system/org/jboss/fuse/features/rhba-features` directory. This file contains prerequisites for installing of{PRODUCT} features.

* `kie-karaf-features-<VERSION>-features-fuse.xml`
+
COMMENT: What is the version?
This file is part of {PRODUCT} and provides {PRODUCT} features, which define the OSGi features that can be deployed into {FUSE_LONG}. OSGi users can install features from this file to install {PRODUCT} into {FUSE} and use it in their applications. You can find this features file in the online and offline Maven repository that is distributed with {PRODUCT}. The group ID, artifact, and version (GAV) of this file is `org.kie:kie-karaf-features:VERSION`.



