[id='ba-karaf-xml-uninstall-proc']
= Uninstalling obsolete {PRODUCT} features XML files on Karaf

If your installation contains older versions of the {PRODUCT} features XML files (for example, `kie-karaf-features-<VERSION>-features.xml`), you must remove these files and all associated files before installing the most recent features XML files.

.Prerequisites
* Obsolete features XML files exist in your Apache Karaf installation.

.Procedure
. Enter the following commands to determine whether your installation contains obsolete {PRODUCT} features XML files:
+
[source]
----
$ JBossFuse:karaf@root> feature:repo-list
$ JBossFuse:karaf@root> feature:list
----

. Enter the following command, where `<FUSE_HOME>` is the Fuse installation directory, to start the {FUSE_LONG} console:
+
[source]
----
$ ./<FUSE_HOME>/bin/fuse
----
. Enter the following command, where `<FEATURE_NAME>` is the name of the feature that you want to uninstall, to uninstall features or applications that use obsolete features XML files:
+
[source]
----
JBossFuse:karaf@root> features:uninstall <FEATURE_NAME>
----
+
The following example shows how to remove features:
+
[source]
----
JBossFuse:karaf@root> features:uninstall drools-module
JBossFuse:karaf@root> features:uninstall jbpm
JBossFuse:karaf@root> features:uninstall kie-ci
----
. Search Karaf home for references to bundles that use `drools`, `kie`, or `jbpm`. The following example shows how to use `grep` to search for these components:
+
[source]
----
karaf@root> list -t 0 -s | grep drools
karaf@root> list -t 0 -s | grep kie
karaf@root> list -t 0 -s | grep jbpm
----
+
The example shows the output from these commands:
+
[source]
----
250 │ Active   │  80 │ 7.19.0.201902201522          │ org.drools.canonical-model
251 │ Active   │  80 │ 7.19.0.201902201522          │ org.drools.cdi
252 │ Active   │  80 │ 7.19.0.201902201522          │ org.drools.compiler
----
. Enter the following command, where `BUNDLE_ID` is a bundle ID returned in the search, to remove the bundles found in the previous step:
+
[source]
----
karaf@root> osgi:uninstall BUNDLE_ID
----

. Enter the following command to remove the obsolete `drools-karaf-features` URL:
+
[source]
----
karaf@root> features:removeurl
 mvn:org.kie/kie-karaf-features/VERSION.Final-redhat-VERSION/xml/features
----
. Restart {FUSE}.
