[id='ba-karaf-xml-install-proc']
= Installing {PRODUCT} features on Karaf using XML files
You can install {PRODUCT} features on Karaf to create a dynamic runtime environment for your {PRODUCT} processes.


.Prerequisites
* A {FUSE_LONG} installation in an Apache Karaf container is available. For information about installing {FUSE} in Apache Karaf, see https://access.redhat.com/documentation/en-us/red_hat_fuse/{FUSE_VERSION}/html/installing_on_apache_karaf/index[_Installing Red Hat Fuse on the Apache Karaf container_].
* You have removed any obsolete {PRODUCT} features XML files as described in xref:ba-karaf-xml-uninstall-proc[].

.Procedure
To install {PRODUCT} features, enter the following command:

[source]
----
$ JBossFuse:karaf@root> feature:install <FEATURE_NAME>
----

[NOTE]
====
Use `org.drools.osgi.spring.OsgiKModuleBeanFactoryPostProcessor` instead of `org.kie.spring.KModuleBeanFactoryPostProcessor` to postprocess KIE elements in an OSGi environment.

Do not install the `drools-module` feature before the `kie-spring` feature. If you do, the `drools-compiler` bundle will not detect packages exported by `kie-spring`.

If you install the features in the incorrect order, run `osgi:refresh drools-compiler_bundle_ID`  to force the `drools-compiler` to rebuild its `Import-Package` metadata.
====

In this command, `<FEATURE_NAME>` is one of the features listed in  xref:fuse-karaf-ref_{context}[].
