[id='fuse-con']
= {FUSE_LONG} and {PRODUCT}

{FUSE_LONG} is a distributed, cloud-native integration platform that is part of an agile integration solution. Its distributed approach enables teams to deploy integrated services where required. Fuse has the flexibility to service diverse users, including integration experts, application developers, and business users, each with their own choice of deployment, architecture, and tooling. The API-centric, container-based architecture decouples services so they can be created, extended, and deployed independently. The result is an integration solution that supports collaboration across the enterprise.

ifdef::PAM[]
{PRODUCT} is the Red Hat platform for creating business automation applications and microservices. It enables enterprise business and IT users to document, simulate, manage, automate, and monitor business processes and policies. {PRODUCT} is designed to empower business and IT users to collaborate more effectively, so business applications can be changed easily and quickly.

endif::[]
ifdef::DM[]
{PRODUCT} is an open source decision management platform that combines business rules management, complex event processing, Decision Model & Notation (DMN) execution, and {PLANNER} for solving planning problems. It automates business decisions and makes that logic available to the entire business.

Business assets such as rules, decision tables, and DMN models are organized in projects and stored in the {CENTRAL} repository. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.
endif::[]

You can install {FUSE_LONG} on the Apache Karaf container platform and then install and configure {PRODUCT} in that container.

You can also install {FUSE_LONG} on a separate instance of {EAP_LONG} and integrate it with {PRODUCT}. The `kie-camel` module provides integration between {FUSE_LONG} and {PRODUCT}.

[IMPORTANT]
====
For the version of {FUSE_LONG} that {PRODUCT} {ENTERPRISE_VERSION} supports, see
ifdef::PAM[]
https://access.redhat.com/articles/3405381[{PRODUCT} 7 Supported Configurations].
endif::[]
ifdef::DM[]
https://access.redhat.com/articles/3354301[{PRODUCT} 7 Supported Configurations].
endif::[]
====

[NOTE]
====
You can install {FUSE_LONG} on Spring Boot. {PRODUCT} provides no special integration for this scenario.

You can use the `kie-server-client` library in an application running on {FUSE_LONG} on Spring Boot to enable communication with {PRODUCT} services running on a {KIE_SERVER}. There are some dependency version mismatches between {FUSE_LONG} and the `kie-server-client` library. These mismatches cause the following limitations:

* *Jackson version mismatch:* The application cannot use `MarshallingFormat.JSON` with the `kie-server-client` library
* *ActiveMQ version mismatch*: The application cannot use JMS messaging with the `kie-server-client` library

For instructions about using the `kie-server-client` library, see {URL_INTEGRATING}#kie-server-java-api-con_kie-apis[{KIE_APIS}].
====
