[id='installing-on-fuse-eap-proc']
= Installing {FUSE} on {EAP_LONG}
Install {FUSE_LONG} {FUSE_VERSION} on {EAP} 7.2.7 to use with {PRODUCT} to deploy integrated services where required.

[NOTE]
====
{FUSE_LONG} 7.7 is supported on {EAP} 7.2, whereas {PRODUCT} 7.8.x and newer is supported on Red Hat {EAP} 7.3. To ensure a stable deployment environment, install {FUSE} and {PRODUCT} on different instances of {EAP} according to the supported {EAP} versions.

{PRODUCT} 7.8.x and newer components on {EAP} 7.2 are not officially supported. However, Red Hat provides guidance on a commercially reasonable basis until {FUSE} is available on {EAP} 7.3. `MarshallingFormat.JSON` is not supported on {FUSE} integration with {EAP} 7.2 using `kie-camel`. The default is JAXB.
====

.Prerequisites
* A {PRODUCT} installation on {EAP_LONG} {EAP_VERSION} is available. For installation instructions, see {URL_INSTALLING_AND_CONFIGURING}#assembly-install-on-eap[_{INSTALLING_ON_EAP}_].
* A separate instance of {EAP_LONG} 7.2.7 is available.

.Procedure
. Install {FUSE_LONG} {FUSE_VERSION} on {EAP_LONG} 7.2.7. For installation instructions, see the https://access.redhat.com/documentation/en-us/red_hat_fuse/{FUSE_VERSION}/html-single/installing_on_jboss_eap/index[_Installing on JBoss EAP_].

. Open the `pom.xml` file in the {FUSE} home directory in a text editor.
. Create the integration project with a dependency on the `kie-camel` component by editing the `pom.xml` file as shown in the following example:
+
[source,xml]
----
<dependency>
  	<groupId>org.apache.camel</groupId>
  	<artifactId>camel-core</artifactId>
  	<scope>provided</scope>
</dependency>
<dependency>
  	<groupId>org.kie</groupId>
  	<artifactId>kie-api</artifactId>
</dependency>
<dependency>
  	<groupId>org.kie</groupId>
  	<artifactId>kie-ci</artifactId>
  	<exclusions>
    	<exclusion>
      	<groupId>aopalliance</groupId>
      	<artifactId>aopalliance</artifactId>
    	</exclusion>
  	</exclusions>
</dependency>
<dependency>
  	<groupId>org.kie.server</groupId>
  	<artifactId>kie-server-api</artifactId>
  	<exclusions>
    	<exclusion>
      	<groupId>org.jboss.spec.javax.xml.bind</groupId>
      	<artifactId>jboss-jaxb-api_2.3_spec</artifactId>
    	</exclusion>
    	<exclusion>
      	<groupId>javax.activation</groupId>
      	<artifactId>activation</artifactId>
    	</exclusion>
  	</exclusions>
</dependency>
<dependency>
  	<groupId>org.jbpm</groupId>
  	<artifactId>jbpm-bpmn2</artifactId>
	</dependency>
	<dependency>
  	<groupId>org.kie</groupId>
  	<artifactId>kie-camel</artifactId>
  	<exclusions>
    	<exclusion>
      	<groupId>org.apache.cxf</groupId>
      	<artifactId>cxf-core</artifactId>
    	</exclusion>
    	<exclusion>
      	<groupId>org.apache.camel</groupId>
      	<artifactId>camel-cxf</artifactId>
    	</exclusion>
    	<exclusion>
      	<groupId>org.apache.camel</groupId>
      	<artifactId>camel-cxf-transport</artifactId>
    	</exclusion>
    	<exclusion>
      	<groupId>com.thoughtworks.xstream</groupId>
      	<artifactId>xstream</artifactId>
    	</exclusion>
  	</exclusions>
</dependency>
<dependency>
   	<groupId>org.kie.server</groupId>
   	<artifactId>kie-server-client</artifactId>
   	<exclusions>
     	<exclusion>
       	<groupId>org.jboss.spec.javax.ws.rs</groupId>
       	<artifactId>jboss-jaxrs-api_2.0_spec</artifactId>
     	</exclusion>
   	</exclusions>
</dependency>
----
