[id='installing-on-fuse-karaf']
= Installing {PRODUCT} on Apache Karaf with {FUSE}
Install {PRODUCT} on Apache Karaf with {FUSE} to deploy integrated services where required.

.Prerequisites
* A {FUSE_LONG} 7.2 on Apache Karaf installation exists. For installation instructions, see  https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html-single/installing_on_apache_karaf/[_Installing Red Hat Fuse on the Apache Karaf container_] .
* Any obsolete features XML files have been removed, as described in <<features-xml-removing>>.

.Procedure
. To configure the Maven repository, open the `FUSE_HOME/etc/org.ops4j.pax.url.mvn.cfg` file in a text editor and then add the following entry to the `org.ops4j.pax.url.mvn.repositories` variable:
+
----
[source]
`https://maven.repository.redhat.com/ga/`
----
+
[NOTE]
====
Entries are separated by a comma, space, and back slash (, \).
====
. Enter the following command to start {FUSE}:
+
[source]
----
$ ./INSTALLATION_DIRECTORY/bin/fuse
----
COMMENT: Is Installation Direction the FUSE HOME?

. Enter the following command to add a reference to the features file that contains installation prerequisites:
+
[source]
----
$ feature:repo-add mvn:org.jboss.fuse.features/rhba-features/FUSE-VERSION/xml/features
----

. Enter the following command to add a reference to the {PRODUCT} features XML file:
+
[source]
----
$ JBossFuse:karaf@root> features:addurl mvn:org.kie/kie-karaf-features/VERSION/xml/features-fuse
----
+
To see the current `drools-karaf-features` version, see the https://access.redhat.com/articles/3405381#supported_comps[Red Hat Process Automation Manager 7 Supported Configurations] page.COMMENT: Note to MW.
. Enter the following command to install the features provided by {PRODUCT} features XML file:
+
ifdef::PAM[]
[source]
----
JBossFuse:karaf@root> features:install jbpm
----
endif::PAM[]

ifdef::DM[]
[source]
----
JBossFuse:karaf@root> features:install drools-module
----
endif::DM[]
COMMENT: Can we add instructions about how to verify the installation/integration?

