[id='jbpm-workitems-camel-con_{context}']
= The `jbpm-workitems-camel` component


The `jbpm-workitems-camel` component provides {FUSE_LONG} connectors that enable you to connect your {PRODUCT} projects to external services. These connectors are primarily used to perform integrations from within processes, for example sending web service requests or JMS messages. They are embedded in {CENTRAL} and are available as service tasks from the *Admin* -> *Service Tasks Administration* page and from the *Project Settings* pages.

.Red Hat Fuse connectors available in {CENTRAL}
[cols="30%,70%", frame="all", options="header"]
|===
| Connector
| Description

| CamelCXFConnector
| Provides integration with Apache CXF for connecting to JAX-WS services hosted in CXF

| CamelFTPConnector
| Provides access to remote file systems over the FTP and SFTP protocols

| CamelFTPSConnector
| Provides access to remote file systems over the FTPS  protocol

| CamelFileConnector
| Provides access to file systems, allowing files to be processed by any other Camel components or messages from other components to be saved to disk

| CamelGenericConnector
| Sends a payload to a Camel endpoint

| CamelJMSConnector
| Sends messages to a JMS queue or topic

| CamelSQLConnector
| Executes a SQL query at a Camel endpoint and retrieves results

| CamelXSLTConnector
| Processes a message using an XSLT template
|===

[NOTE]
====
You can only install service tasks into a project after they are globally enabled from the from the *Admin* -> *Service Tasks Administration* page.
====
=======
Comment: Maciej, thank you for this section. I suspect that it should be incorporated in chapter 4.1. There appears to be a mapping with the items you list here with the GUI lables on the Service Task Admin page. For example `CXFCamelWorkitemHandler`/CamelCXFConnector.

The `jbpm-workitems-camel` component provides a set of integration-focused work item handlers backed by Apache Camel. These are primarily used for performing integrations from within processes, for example sending web service requests or JMS messages.

The following work item handlers are available out of the box:

* `CXFCamelWorkitemHandler`
* `FTPCamelWorkitemHandler`
* `FTPSCamelWorkitemHandler`
* `FileCamelWorkitemHandler`
* `JMSCamelWorkitemHandler`
* `SQLCamelWorkitemHandler`
* `XSLTCamelWorkitemHandler`

You can configure these work item handlers through the {CENTRAL} *Service Task Administration* and *Project Settings* pages.

Note: Service tasks can only be installed into the project after they are globally enabled (in service task administration).
