[[_jbpmreleasenotes720]]

= New and Noteworthy in jBPM 7.2.0
:imagesdir: ..

The following features were added to jBPM 7.2


== Improved validation in deployment descriptor editor

Deployment descriptor editor in workbench has been improved to validate content of entered data for

- work item handlers
- event listeners
- marshalling strategies
- globals
- environment entries
- configuration

Validation is performed automatically when build is invoked or manually when user clicks on *Validate* button

Validation mainly focuses on checking if data entered are valid based on selected types:

- MVEL type resolver will perform compilation of the expression that was given as identifier, it can produce warning messages as it might not have access to all classes that will be available on runtime, thus it's only warning to not block the build.
- Reflection type resolver will verify if the identifier has valid name according to Java standard (class name)

== Websocket based KIE Server communication with KIE Controller

Default communication mechanism for KIE Server to connect to KIE Controller is HTTP/REST based. This fits well in non-restricted environments where both components can freely talk to each other. Though it requires both components to know how to access and authorize
itself when sending requests. That does not play well in cloud based environments or environments that utilize load balancer.

To overcome this issues, an alternative mechanism was introduced. It is based on Websocket where KIE Server is solely responsible for connection. Thus only KIE Server needs to be aware of controller and it's authentication, while controller
simply reuses already opened communication channel. More on this can be found in this http://mswiderski.blogspot.com/2017/08/managed-kie-server-gets-ready-for-cloud.html[article].
