[[_jbpmreleasenotes600]]
= New and Noteworthy in jBPM 6.0.0
:imagesdir: ..

== KIE API


A new public API has been created for interacting with the core engine (shared between jBPM and Drools).  This not only handles runtime operations to start processes, etc.
but also instantiating sessions, registering listeners, configuration, etc.

New APIs were added in various areas, like for example the TaskService interface was moved to the public API, the new RuntimeManager was introduced and a lot of related interfaces and classes were added as well.

For backwards compatibility with v5, a knowledge-api JAR has been constructed, that implements the old v5 knowledge-api interfaces on top of the v6 engine.
Make sure to include this JAR in your classpath if you want to keep using the v5 API.

== jBPM Core Engine


The execution engine itself has (mostly) remained the same, although we've done various improvements in the following areas:

* RuntimeManager: instantiating a ksession (and an associated task service) has been simplified significantly, by introducing a runtime manager where you can simply ask for a reference to a ksession whenever you need it. The Runtime manager is responsible for initialization, configuration and disposal of the ksession (and task service), and three predefined strategies are available:
** Singleton: the RuntimeManager reused the same ksession for all requests (and executes the requests in sequence, one at a time)
** Session per request: the RuntimeManager instantiates a new ksession per request that will be used for executing that request and disposed at the end. Each request will receive its own ksession and they can all be executed in parallel.
** Session per process instance: the RuntimeManager reuses the same ksession for all requests related to one specific process instance. This might be necessary if you are storing data inside your session (for example for rule evaluations) that you need to be available later in the process as well. Note that the session is disposed after each command but stored in the database so it can be restored whenever necessary.
* jBPM Services (CDI): To simplify integration of jBPM inside CDI-based applications, the jbpm-services module contains various CDI services that you can configure and use inside your application simply by injecting the necessary services (like a RuntimeManager or TaskService for example) inside your application, making integration easier than ever.
* Timer service: a Quartz-based timer service is now available, that allows you to dispose your session at any point in time, and the timer service will be responsible for rehydrating a ksession whenever a timer should be fired. This timer service also works in a clustered environment, where multiple nodes can work together on sharing the work load but timers will only be fired once by one of the nodes.
* Exception and compensation management: various improvements in this area allow you to use more BPMN2 constructs related to exception and compensation management in your processes, and various strategies have been extended and documented to better handle exceptions in different ways.
* Asynchronous handlers: asynchronous execution of interaction with external services can now be implemented by reusing the asynchronous job executor.
* Asynchronous auditing using JMS: audit logging can now also be done asynchronously by sending the events to a JMS queue rather than persisting them as part of the engine transaction.


The task service has been refactored significantly as well, and the TaskService APIs have been moved to the public kie-api.
Although the TaskService interfaces themselves haven't changed a lot, the internal implementation has been simplified.
Auditing for the task-related operations (similar to the runtime engine auditing) has been added.

By default, a local task service will always be used by a ksession to  perform various task-related operations (creating a task, being notified when a task is completed).  Setting up a remote singleton task service and connecting multiple ksessions to this (using Mina or HornetQ) as was possible in jBPM5 is no longer possible, as it introduces more challenges that it brings advantages.
Since the jBPM execution service now also provides a remote API for all task-related operations, we believe this setup is no longer necessary, and has been replaced by the use of a local task service in all use cases.

== jBPM Designer


jBPM designer has been reimplemented and is fully integrated into the workbench.
It now easily integrates with many of the workbench services available.
In addition, the following features were added/improved on:

* Improvement of jBPM Simulation engine and the UI. Added ability to specify simulation properties on more node type and added more results graphs such as the the Total Cost graph.
* Many updates to the Designer Toolbar for usability purposes.
* Visual Validation update - it now is a real-time visualization of issues done during process modeling. 
* Ability to generate task forms for specific task node.
* Integration with the jBPM Form Modeler for both task and process forms.
* Update to process properties - added grouping of properties into sections making it more user friendly to find properties.
* Update to Object Library - added type specific tasks to palette (rather than having to morph to a certain type after adding a task to the canvas).
* Save/Remove/CopyDelete feature have been added directly into Designer and integrate with the workbench services for those operations.
* Autosave - option for users to enable auto-saving of their business process during modeling.
* Two new default Service Tasks (REST and Web Services)


== jBPM Data Modeler


A new web-based data modeler is integrated in the workbench, which allows non-technical users to  create data models (to be used in your processes and rules) in a user-friendly manner.
These models are saved as Java classes (with the necessary annotations) in the project and added to the kjar upon build and deploy.
Check the chapter on Data Modeler in the Workbench Part for all the details.

== Form Modeler


A new web-based form modeler is integrated in the workbench, which allows non-technical users to create forms (for starting processes and/or completing human task).  The form modeler is a WYSIWYG editor where you can drag and drop form elements (text boxes, labels, etc.), link it to data that is expected as input or output of the form, customize properties of each element and the layout, etc.
These forms are then shown when starting the process or completing a task, integrated into the appropriate runtime views.
Check the chapter on Form Modeler in the Workbench Part for all the details.

== jBPM Console


The jBPM console has been reimplemented and is integrated into the workbench as well.
It provides similar features as jBPM5 (starting process instances, inspecting current state and variables, looking at task lists) but is now much more powerful and exposes a lot more features.
Check the chapter on Process and Task Management in the Workbench Part for all the details.

== BAM / Reporting


A new web-based monitoring and reporting tool has been integrated in the workbench.
This displays charts, tables, etc.
about the current status of your application(s).  It comes with some process and task dashboards out-of-the-box (showing for example the number of running process instances, the number of tasks completed per time frame, etc.).  These dashboards however can be fully customized to show the data that is relevant to you, including for example your own data sources, making domain-specific charts (for example showing your key performance indicators (KPIs) instead of generic process-related charts).  Check the chapter on Business Activity Monitoring in the Workbench Part for all the details.

== Workbench


A workbench application, based on the UberFire framework, now unifies all web-based editors and tools into one large, configurable web application.
It has many features, including:

* Configurable workspace where you layout your own views by dragging and dropping
* Unified login and role-based authentication, where what features you see depends on your role (admin, analyst, developer, user, manager, etc.).
* A new home screen that will guide you through the life cycle of your business processes (authoring, deployment, execution, tasks and reporting).
* Git-based repository that supports versioning and collaboration.
* New project structure where artifacts (processes, rules, etc.) are combined into kjars (we removed the custom binary packages and replaced them with a normal JAR, containing the source artifacts) when a  project is built. These kjars now also include not only processes and rules, but also forms, configuration files, data models (Java classes), etc. Kjars are Maven artefacts themselves (they have a group, id and version) and exposed as a Maven repository. When creating a ksession, Maven can be used to download the necessary kjars for your project from this Maven repository.
* Sample `playground` repositories are (optionally) installed when starting up the workbench the first time, to get you started quickly with some predefined examples.


Check the Workbench Part for all the details.

== Remote API


The remote API has been redesigned and allows users to remotely connect to a running execution server and pass commands.
The remote runtime API exposes (almost) the entire KieSession and TaskService API using REST or JMS, so commands can be sent to the remote execution server for processing and the results are returned.
See the chapter on Business Activity Monitoring for all the details.

Guvnor also provides a REST API to access the various repositories, projects and artifacts inside these projects and manage and build them.
