[[_jbpmreleasenotes720]]

= New and Noteworthy in jBPM 7.7.0
:imagesdir: ..

The following features were added to jBPM 7.7

== jBPM executor redesigned

up to version 7.7, jBPM executor used default mechanism based on polling. It periodically polls data base to check if there are any jobs to be
executed. This does not scale too good and was main motivation to approach redesign. With version 7.7, jBPM executor is enhanced to remove polling mechanism
and instead relies on specialised ScheduledThreadPoolExecutor that respects job's priority.

This allows to have really efficient processing with less load on the data base (and less locks on data base). New mechanism does cover all
possible types of jobs including retries and requeues. With additional JMS trigger (that was already present since version 6.3) this provides
complete and fast asynchronous job processing solution.
To read up more on this see http://mswiderski.blogspot.com/2018/02/redesigned-jbpm-executor.html[this article] and async section in the docs.

== UserInfo interface allows to get user id by email

Small addition to UserInfo interface (and its default implementations) was provided to allow to find user id by email address. This is the reverse
operation that was already there - get email address by user id. With this, email integration (such as completing task by email) can be
easily implemented.

== Service Level Agreement (SLA) tracking for processes and cases

SLA tracking has been added to jBPM to allow to easily keep track of the execution of:

- processes
- cases
- individual activities of the process/case

This allows administrators to be always up to date with what is happening with running processes and be notified when SLA are violated.
More can be found in http://mswiderski.blogspot.com/2018/02/track-your-processes-and-activities.html[SLA overview article] and
http://mswiderski.blogspot.com/2018/02/react-to-sla-violations-in-cases.html[SLA with cases article].

== Case stages activation condition

Case stages (ad hoc subprocesses) are equipped (next to completion condition) with activation condition. This means that ad hoc stage
can be automatically activated when defined condition is met. Conditions should be defined as rule expressions and usually refer to
case file data, although are not limited to that.

== NoSQL integration

Initial integration with NoSQL (and not only that) has been introduced. This is based on additional so called Emitters that can be
implemented to receive notifications when process engine executes processes. In general, this allows users to plugin their own
emitters that will be responsible for sending data to externals data stores.
Note that this is integration and not replacement of persistence layer of jBPM. You can read up more about it in
http://mswiderski.blogspot.com/2017/08/nosql-enters-jbpm-as-experiment-so-far.html[this article] and if would like to see an implementation
based on Elasticsearch, take a look at http://mswiderski.blogspot.com/2017/08/elasticsearch-empowers-jbpm.html[this article] 
