[[_jbpmreleasenotes720]]

= New and Noteworthy in jBPM 7.3.0
:imagesdir: ..

The following features were added to jBPM 7.3


=== KIE Server Maven Plugins

With version 7.3 KIE Server has been empowered with additional Maven Plugins that allow to interact with KIE Server and KIE Controller REST api directly from within a build.
This enables easier integration with CI/CD pipelines when building KJars so they can be directly deployed to execution environment (both managed and unmanaged KIE Servers).

KIE Server Deploy Maven Plugin - https://github.com/kiegroup/droolsjbpm-integration/tree/master/kie-server-parent/kie-server-maven-plugin[read more]

- deploy -  deploy kjar to runtime environment
- dispose - dispose running kjar (kie container) in runtime environment
- update - update version of running kjar (kie container) in runtime environment

KIE Server Controller Deploy Maven Plugin - https://github.com/kiegroup/droolsjbpm-integration/tree/master/kie-server-parent/kie-server-controller-plugin[read more]

- get-template - retrieves existing server templates from controller
- create-template - creates new server templates with set of containers
- delete-template - removes server template
- get-containers - retrieves containers in given server template
- get-container - retrieves given container from server template
- create-container - create new container in given server template
- delete-container - delete container from given server template
- start-container - starts container in given server template
- stop-container - stops container in given server template
- deploy-container - creates and starts container in given server template
- dispose-container - stops and removes container from given server template
