[[_jbpmreleasenotes720]]

= New and Noteworthy in jBPM 7.4.0
:imagesdir: ..

The following features were added to jBPM 7.4

== KIE Server Router enhancements

KIE Server Router received number of enhancements where majority of them were around connectivity with KIE Servers and Controller.
Most of the work was to make it more reliable in case of failures of the other components

- when controller is not available during router start a retry mechanism is in place to connect to it as soon as the controller becomes available
- when controller is not available when there are updates to be sent to it a retry mechanism is in place
- when KIE Server that request is sent to does not respond it is removed from the active servers and thus subsequent requests won't target it any more,
at the same time such server is put on a list to be verified if that server was only temporarily unavailable and if so will be put back on the active
servers list

With these enhancements KIE Server Router is more resilient to failures and thus provides much higher level of reliability,
especially important in cloud based environments.


== User task update (properties and data)

Besides regular life cycle of user task, users could set task content while working on the task or change the task priority, name or description.
This is all possible but requires users to do that individually. 7.4 comes with a feature that allows to update certain properties and data in one shot.
Following is a list of user task properties that can be updated:

- name
- description
- priority
- expiration date
- form name

Both user task inputs and outputs can be given to be updated. Data will be merged with existing values if any. That means if there are task inputs
or outputs with same name already present on a task they will be replaced with given values.

== Work Item archetype

To help users build custom service tasks (work items) jBPM 7.4 comes with Work Item Archetype that aims at generating majority
of things required to build a custom service task. It does include:

- WID file (work item definition)
- Work Item Handler implementation class
- WorkItem handler test class
- maven assembly (zip) that will package everything on the build time so it can be consumed by Service Repository and thus used from within Web Designer

A detailed article can be found http://mswiderski.blogspot.com/2017/09/integrate-systems-with-processes-jbpm.html[here]
