[[_jbpmreleasenotes710]]

= New and Noteworthy in jBPM 7.1.0
:imagesdir: ..

The following features were added to jBPM 7.1

== Workbench

The following are the jBPM-specific enhancements made in the workbench.


=== New error handling

Execution errors are now detected and stored by the system (e.g., exceptions while running a process instance or a job once the max retry number has been exceeded).
The process instance list includes a new column that displays the number of errors per process instance which are not marked as acknowledged. When the column is clicked a popup is displayed, which will allow users to navigate to the new error perspective.


=== Advanced Queries with ORDER BY clause

The `QueryService` used in executing advanced queries only supported sorting with ORDER BY clauses having the following pattern:

[source,sql]
----
ORDER BY Column1, Column2, ... ASC|DESC;
----

which limited the sorting to either ascending or descending for all columns.

The desired behavior, that of a full ORDER BY clause

[source,sql]
----
ORDER BY Column1 ASC|DESC, Column2 ASC|DESC, ..., ColumnN ASC|DESC;
----

allowing sort order per column, is now possible.  Please see the documentation for examples of how to apply the new full ORDER BY clause when using the QueryService.
