[id='case-management-dynamic-user-task-API-proc']
= Creating a dynamic user task using the {KIE_SERVER} REST API

You can create a dynamic user task during case run time using the REST API. To create a dynamic user task, you must provide the following information:

* Task name
* Task subject (optional, but recommended)
* Actors or groups (or both)
* Input data


Use the following procedure to create a dynamic user task for the *IT_Orders* sample project available in {CENTRAL} using the Swagger REST API tool. The same endpoint can be used for REST API without Swagger.

.Prerequisites
* You are logged in to {CENTRAL} and an IT Orders case instance has been started using the Showcase application. For more information about using Showcase, see {URL_DEVELOPING_PROCESS_SERVICES}#assembly-showcase-application[_{SHOWCASE_APPLICATION_CASE_MANAGEMENT}_].


.Procedure

. In a web browser, open the following URL:
+
`http://localhost:8080/kie-server/docs`.
. Open the list of available endpoints under *Case instances :: Case Management*.
. Click click the following `POST` method endpoint to open the details:
+
`/server/containers/{id}/cases/instances/{caseId}/tasks`
+
. Click *Try it out* and then input the following parameters:
+
.Parameters
[cols="40%,60%",options="header"]
|===
|Name| Description
|`id` | `itorders`
|`caseId` | `IT-0000000001`
|===
+
.Request body
[source]
----
{
 "name" : "RequestManagerApproval",
 "data" : {
   "reason" : "Fixed hardware spec",
   "caseFile_hwSpec" : "#{caseFile_hwSpec}"
  },
 "subject" : "Ask for manager approval again",
 "actors" : "manager",
 "groups" : ""
}
----
. In the Swagger application, click *Execute* to create the dynamic task.

This procedure creates a new user task associated with case `IT-000000001`. The task is assigned to the person assigned to the `manager` case role. This task has two input variables:

* `reason`
* `caseFile_hwSpec`: defined as an expression to allow run time capturing of a process or case data.

Some tasks include a form that provides a user-friendly UI for the task, which you can locate by task name. In the IT Orders case, the `RequestManagerApproval` task includes the form `RequestManagerApproval-taskform.form` in its KJAR. For example, if the task name is `XXX` the associated form file name is `XXX-taskform.form`.

After it is created, the task appears in the assignee's *Task Inbox* in {CENTRAL}.
