[id='case-management-roles-con-{context}']
= Case roles

Case roles provide an additional layer of abstraction for user participation in case handling. Roles, users, and groups are used for different purposes in case management.

Role::
Roles drive the authorization for the case instance, and can be used for user activity assignments. A user or one or more groups can be assigned to the owner role. The owner is whoever the case belongs to. Roles are not restricted to a single set of people or groups as part of case definition. Use roles for task assignment instead of assigning a specific user or group in order to ensure the case remains dynamic.

Group::
A group is a number of people who are able to carry out a particular task or have a set of specified responsibilities. You can assign any number of people to a group and assign any group to a role. You can add or change members of a group at any time, so you should never hard code a group to a particular task.

User::
A user is an individual who can be given a particular task when you assign them a role or add them to a group.

The following illustrates how the preceding case management concepts apply to a hotel reservation.

* Role = `Guest`
* Group = `Receptionist`, `Maid`
* User = `Marilyn`

The role assignment (`Guest`) affects the specific work of the case and is unique to all case instances. The number of users or groups that can be assigned to a role is limited by the `Case Cardinality`, which is set during role creation in the process designer and case definition. For example, the hotel reservation case has only one guest while the *IT_Orders* sample project has two suppliers of IT hardware.

When the roles are defined, case management must ensure that these are not hard coded to single set of people or groups as part of case definition and that they can differ for each case instance. This is where case role assignments become important.

Role assignments can be assigned or removed when a case starts or at any time when a case is active. Although roles are optional, use roles in case definitions to maintain and organized workflow.

[IMPORTANT]
====
Always use roles for task assignments instead of actual user or group names. This ensures the case remains dynamic and actual user or group assignment can be made as late as possible.
====

Roles are assigned to users or groups and authorized to perform tasks when a case instance is started.
