[id='case-management-case-file-con-{context}']
= Case files

A case instance is a single instance of a case definition and encapsulates the business context. All case instance data is stored in the case file, which is accessible to all process instances that might participate in the particular case instance. Each case instance and its case file are completely isolated from the other cases. Only case instance participants can access the case file.

A case file is used in case management as a repository of data for the entire case instance. It contains all roles, data objects, the data map, and any other data. The case can be closed and reopened at a later date with the same case file attached. A case instance can be closed at any time and does not require a specific resolution to be completed.

The case file can also include embedded documentation, references, PDF attachments, web links, and other options.

The `Case ID prefix` is an optional configurable prefix that enables you to easily distinguish different types of cases. The prefix is followed by a generated ID in the format `ID-XXXXXXXXXX`, where `XXXXXXXXXX` is a generated number that provides a unique ID for the case instance. If a prefix is not provided, the default prefix is `CASE` with the following identifiers:

`CASE-0000000001`

`CASE-0000000002`

`CASE-0000000003`

You can specify any prefix. For example, if you specify the prefix `IT`, the following identifiers are generated:

`IT-0000000001`

`IT-0000000002`

`IT-0000000003`

You can customize the business key, for example the following generates the `HR-TYPE1` prefix.

[source]
----
{
  case variable =>  type = "type1"
  prefix = "HR-@{UPPER(type})"
}
----

.Prefix HR-TYPE1

[source]
----
{
  HR-TYPE1-0000000001
  HR-TYPE1-0000000002
  HR-TYPE1-0000000003
}
----

.Adding a different case variable, for example, ``type = 3type`

[source]
----
{
  HR-3TYPE-0000000001
  HR-3TYPE-0000000002
  HR-3TYPE-0000000003
}
----

If the `CaseIdPrefixIsSequence` case metadata is set to `false` (default value is `true`) it will not create any sequence and the `caseIdPrefix` expression evaluation is the caseId.
[source]
----
{
case var => CORRELATION_KEY=my correlation key
case var => IS_PREFIX_SEQUENCE=false
prefix = @{CORRELATION_KEY}
}
----

.`IS_PREFIX_SEQUENCE` case variable set to `false`
[source]
----
{
caseId = my correlation key
}
----
