[id='case-management-showcase-application-con-{context}']
= Case management Showcase application 


The Showcase application is included in the {PRODUCT} distribution to demonstrate the capabilities of case management in an application environment. Showcase is intended to be used as a proof of concept that aims to show the interaction between business process management (BPM) and case management. You can use the application to start/close, monitor, and interact with cases.

Showcase must be installed in addition to the {CENTRAL} application and {KIE_SERVER}. The Showcase application is required to start new case instances, however the case work is still performed in {CENTRAL}. 

After a case instance is created and is being worked on, you can monitor the case in the Showcase by clicking the case in the *Case List* to open the case *Overview* page. 

[float]
== Showcase Support
The Showcase application is not an integral part of {PRODUCT} and is intended for demonstration purposes for case management. Showcase is provided to encourage customers to adopt and modify it to work for their specific needs. The content of the application itself does not carry product-specific Service Level Agreements (SLAs). We encourage you to report issues, request for enhancements, and any other feedback for consideration in Showcase updates.

Red Hat Support will provide guidance on the use of this template on a commercially reasonable basis for its intended use, excluding the provided example UI code provided within. 

[NOTE]
====
https://access.redhat.com/support/offerings/production/soc[Production support] is limited to the {PRODUCT} distribution.
====