[id='case-management-milestones-con-{context}']
= Milestones

Milestones are a special service task that can be configured in the case definition designer by adding the milestone node to the process designer palette. When creating a new case definition, a milestone configured as `Adhoc autostart` is included on the design palette by default. 
 
Case management milestones usually occurs at the end of a stage, but they can also be the result of achieving other milestones. A milestone always requires a condition to be defined in order to track progress. Milestones react to case file data when data is added to a case. A milestone represents a single point of achievement within the case instance. It can be used to flag certain events, which can be useful for KPI tracking or identifying the tasks that are still to be completed.

  
Milestones can have three states:

* Active - The condition has been defined on the milestone but it has not been met. 
* Completed - The milestone condition has been met, the milestone has been achieved, and the case can proceed to the next task.
* Terminated - The milestone is no longer a part of the case process and is no longer required.
 
While a milestone is available or completed it can be triggered manually using a signal or can be automatically started (by configuring `Adhoc autostart`) when a case instance starts. Milestones can be triggered as many times as required, however, it is directly achieved when the condition is met.
 


