[id='case-management-dynamic-subprocess-API-proc']
= Creating a dynamic subprocess using the REST API

When creating a dynamic subprocess, only optional data is provided; there are no special parameters as there are when creating dynamic tasks.

Use the following procedure use the Swagger REST API to create a dynamic subprocess task for the *IT_Orders* sample project available in {CENTRAL} . The same endpoint can be used for REST API without Swagger.

.Prerequisite
You are logged in to {CENTRAL} and an IT Orders case instance has been started using the Showcase application. For more information about using Showcase, see {URL_USING_SHOWCASE_APPLICATION}[_{USING_SHOWCASE_APPLICATION}_].


.Procedure
. In a web browser, open the following URL:
+
`http://localhost:8080/kie-server/docs`.
. Open the list of available endpoints under *Case instances :: Case Management*.
. Click click the following `POST` method endpoint to open the details:
+
`/server/containers/{id}/cases/instances/{caseId}/processes/{pId}`
+
. Click *Try it out* and complete the following parameters:
+
.Parameters
[cols="40%,60%",options="header"]
|===
|Name| Description
|`id` | `itorders`
|`caseId` | `IT-0000000001`
|`pId` | `itorders-data.place-order`
|===
+
The `pId` is the process ID of the subprocess to be created.
+
body::
+
[source]
----
{
 "placedOrder" : "Manually"
}
----
. In the Swagger application, click *Execute* to start the dynamic subprocess.

In this example, the `place-order` subprocess has been started in the IT Orders case with the case ID `IT-0000000001`. You can see this process in {CENTRAL} under *Menu* -> *Manage* -> *Process Instances*.

If the described example has executed correctly, the `place-order` process appears in the list of process instances. Open the details of the process and note that the correlation key for the process includes the IT Orders case instance ID, and the *Process Variables* list includes the variable `placedOrder` with the value `Manually`, as delivered in the REST API body.
