
= Introduction
:imagesdir: ..


What happens to a business process when something unexpected happens during the process? Most of the time, when creating and designing a new process definition, the first step is to describe the _normative_ or desirable behaviour.
However, a process definition that only describes all of the normal tasks and their execution order is incomplete.

The next step is to think about what might go _wrong_ when the business  process is run.
What would happen if any of the human or technical actors in the process do  _not_ respond in unexpected ways?  Will any of the technical systems that the  process interacts with return unexpected results -- or not return any results at all?

Deviations from the normative or "happy" flow of a business process are called  __exceptions__.
In some cases, exceptions might not be that unusual, such as  trying to debit an empty bank account.
However, some processes might contain many complex  situations involving exceptions, all of which must be handled correctly.

[NOTE]
====
The rest of chapter assumes that you know how to create custom `<task>` nodes and how to implement and register `WorkItemHandler` implementations.
More information about these topics can be found in the <<jBPMDomainSpecificProcesses, Domain-Specific Processes>> chapter.
====
