[id='migration-overview-con']
= Overview

If you use BRMS version 6.4 and install {PRODUCT} version {PRODUCT_VERSION}, you need to migrate your existing projects to the new product. 

You can move the applications (now called _decision services_) that you developed using the Business Central workbench to the new equivalent, {CENTRAL}. You do not need to change the underlying code manually to complete this migration. 

Decision services that you developed in Java code (for example, in Eclipse) require modification for {PRODUCT} {PRODUCT_VERSION}. You must update the dependencies in the `pom.xml` file for each project and rebuild the project. Some changes in the new version might cause known build errors; in this case, you must modify the code.

To migrate your Java client applications, you also must update the dependencies in the `pom.xml` file for each project. If your application uses embedded BRMS engines (Drools, OptaPlanner), this change also updates the engines. If the application calls the {KIE_SERVER}, the API client library is updated.

If your client application is not developed with the Java client library and uses the REST API to interact with the KIE server ({KIE_SERVER}), you might need to modify it to adapt to a small incompatible API change.

You can replace your KIE servers with new {KIE_SERVERS} simply by stopping the old servers and starting the new ones on the same hosts. You can use {KIE_SERVER} {PRODUCT_VERSION} to run KJAR files created in BRMS 6.4. However, for optimal performance, migrate your projects to {PRODUCT} {PRODUCT_VERSION} and rebuild them.

IMPORTANT: If you are using a version of BRMS older than 6.4, migrate your projects to version 6.4 before migrating to 7.0. See the https://access.redhat.com/documentation/en-us/red_hat_jboss_bpm_suite/6.4/html-single/migration_guide/index[Red Hat JBoss BPM Suite 6.4 Migration Guide].