[id='automation-and-ansible-con']
= Automation and Ansible

Ansible is an automation engine that completely automates link:https://www.ansible.com/integrations/networks[network functions], link:https://www.ansible.com/provisioning?hsLang=en-us[cloud provisioning], link:https://www.ansible.com/configuration-management?hsLang=en-us[configuration management], link:https://www.ansible.com/application-deployment?hsLang=en-us[application deployment], link:https://www.ansible.com/orchestration?hsLang=en-us[intra-service orchestration], and all your other automation needs.

Ansible is designed for multi-tier deployments since it models your IT environment by describing how all of your systems interrelate, rather than just managing one system at a time.

Ansible is easy to deploy as it uses no agents or additional custom security infrastructure. Additionally, it uses a simple language (YAML, in the form of Ansible Playbooks) which lets you describe the automation jobs in a language similar to simple English.

Ansible engine has two additional optional components:

* *Ansible Tower*: Red Hat(R) Ansible(R) Tower lets you scale your IT automation, manage complex deployments, and speed up your organization's productivity. You can centralize and control your organization's IT infrastructure by using a visual dashboard, role-based access control, job scheduling, integrated notifications, and graphical inventory management. You can also embed Ansible Tower into existing tools and processes by using its REST API and CLI.
* *Ansible Networking Add-on*: When Ansible Engine is a part of your automation strategy, the Networking Add-on will provide support for select network modules that are developed, tested, and released in-house for popular networking platforms. Network modules ensure that operators and engineers have peace of mind, especially in mixed or hybrid network environments that can have differing needs and implementations.
