[id='closed-loop-OPNFV-components-con']
= Closed loop with OPNFV components

link:https://wiki.opnfv.org/display/fastpath/Barometer%20Home[Barometer] is an OPNFV project that develops features in `collectd` to collect metrics and events suitable for NFV deployments.

Virtual function Event Stream or VES is another ONAP project that provides common model and format for use by NFV Service Providers (SPs), like in managing VNF health and lifecycle. The project’s goal is to enable a significant reduction in the effort to develop and integrate telemetry data from diverse sources (primarily NFVI, VNFs and PNFs) into automated policy based management systems, by promoting convergence toward a common event stream format and collection system.

The Barometer VES Plugin consumes the `collectd` events and forwards them in VES format to a pre-configured VES/DCAE Collector.

The DCAE Collector, which receives events and metrics in the VES format and publishes them on the ONAP message bus, as well as saves them in a database.
