[id='guided-decision-tables-errors-ref']
= Types of problems in guided decision tables

The validation and verification feature detects the following types of problems:

Redundancy:: Redundancy occurs when two rows in a decision table execute the same consequences for the same set of facts.
For example, two rows checking a client's birthday and providing a birthday discount may result in double discount.

Subsumption:: Subsumption is similar to redundancy and occurs when two rules execute the same consequences, but one executes on a subset of facts of the other. For example, consider these two rules:
+
--
* when Person age > 10 then Increase Counter
* when Person age > 20 then Increase Counter
--
+
In this case, if a person is 15 years old, only one rule fires and if a person is 20 years old, both rules fire.
Such cases cause similar trouble during runtime as redundancy.

Conflicts:: A conflicting situation occurs when two similar conditions have different consequences.
Conflicts can occur between two rows (rules) or two cells in a decision table.
+
The following example illustrates conflict between two rows in a decision table:
+
--
* when Deposit > 20000 then Approve Loan
* when Deposit > 20000 then Refuse Loan
--
+
In this case, there is no way to know if the loan will be approved or not.
+
The following example illustrates conflict between two cells in a decision table:
+
--
* when Age > 25
* when Age < 25
--
+
A row with conflicting cells never executes.

Broken _Unique Hit_ Policy:: When the *Unique Hit* policy is applied to a decision table, only one row at a time can be executed and each row must be unique, with no overlap of conditions being met. If more than one row is executed, then the verification report identifies the broken hit policy. For example, consider the following conditions in a table that determines eligibility for a price discount:
+
--
* when Is Student = true
* when Is Military = true
--
+
If a customer is both a student and in the military, both conditions apply and break the *Unique Hit* policy. Rows in this type of table must therefore be created in a way that does not allow multiple rules to fire at one time. For details about hit policies, see xref:hit-policies-con[].

Deficiency:: Deficiency is similar to a conflict and occurs the logic of a rule in a decision table is incomplete.
For example, consider the following two deficient rules:
+
--
* when Age > 20 then Approve Loan
* when Deposit < 20000 then Refuse Loan
--
+
These two rules may lead to confusion for a person who is over 20 years old and has deposited less than 20000.
You can add more constraints to avoid the conflict.

Missing Columns:: When deleted columns result in incomplete or incorrect logic, rules cannot fire properly. This is detected so that you can address the missing columns, or adjust the logic to not rely on intentionally deleted conditions or actions.

Incomplete Ranges:: Ranges of field values are incomplete if a table contains constraints against possible field values but does not define all possible values. The verification report identifies any incomplete ranges provided. For example, if your table has a check for if an application is approved, the verification report reminds you to make sure you also handle situations where the application was not approved.
