[id='test-designer-data-objects-import-proc']
= Importing data objects

The test scenarios designer loads all data objects that are located in the same package as the test scenario. You can view all the data objects from the *Data Objects* tab in the designer. The loaded data objects are also displayed in the *Test Tools* panel.

You need to close and reopen the designer in case the data objects change (for example, when a new data object is created or when an existing one is deleted). Select a data object from the list to display its fields and the field types.

In case you want to use a data object located in a different package than the test scenario, you need to import the data object first. Follow the procedure below to import a data object for rules-based test scenarios.

[NOTE]
====
You cannot import any data objects while creating DMN-based test scenarios. DMN-based test scenarios does not use any data objects from the project but uses the custom data types defined in the DMN file.
====

.Procedure
. Go to *Project Explorer* panel in the test scenarios designer.
. From *Test Scenario*, select a test scenario.
. Select *Data Objects* tab and click *New Item*.
. In the *Add import* window, choose the data object from the drop-down list.
. Click *Ok* and then *Save*.
. Close and reopen the test scenarios designer to view the new data object from the data objects list.
