[id='test-designer-global-settings-panel-rule-based-proc_{context}']
= Configuring global settings for rule-based test scenarios

Follow the procedure below to view and edit the global settings of rule-based test scenarios.

.Procedure
. Click *Settings* tab on the right side of the test scenario designer to display the attributes.
. Configure the following attributes in the *Settings* panel:
* *Name*: You can change the name of the existing test scenarios by using the *Rename* option from the upper-right toolbar in the designer.
* *Type*: This attribute specifies it is a rule-based test scenario and it is read-only.
* *Stateless Session*: Select or clear this check box to specify if the KieSession is stateless or not.
+
[NOTE]
====
If the current KieSession is stateless and the check box is not selected, the tests will fail.
====
* *KieSession*: (Optional) Enter the KieSession for the test scenario.
* *RuleFlowGroup/AgendaGroup*: (Optional) Enter the RuleFlowGroup or AgendaGroup for the test scenario.
. Optional: To skip the entire simulation from project level after test execution, select the check box.
. Click *Save*.
