[[_drools.testscenarioprevieweditor]]
= Test Scenario (Preview)


This new editor is intended to help the user to test if rules and knowledge bases work as expected. Compared to the
current Test Scenario it has a completely new user experience and tabular layout that will guide the user to define
his scenario template and all the different test cases. Run these scenarios will verify that the system works as
expected or has no regression after a change.

.Example Test Scenario (Preview)
PUT IMAGE HERE

Editor layout contains a table where header (scenario template) contains given facts values and expected results and
rows contains all the different test cases (scenarios values).
The editor has also a right panel that can be used to configure data object mappings or to access to the cheatsheet

NOTE: This is a preview of the editor so it is disabled by default. To enable the asset XXXXXXX

NOTE: This editor needs that the project contains a default KieSession to retrieve KieBase to test



[[_drools.testscenariopreviewcreate]]
== Create a new Scenario
Asset Name
Load Data Object
Import Object
Basic interaction (contextual menu)

[[_drools.testscenariopreviewtemplate]]
== Template definition
Create a column workflow

=== Expression editor
Use expression editor

=== Cheatsheet
Information available

[[_drools.testscenariopreviewscenario]]
== Scenario definition
Add a row

[[_drools.testscenariopreviewrun]]
== Run scenario
How to run and how to check result

