
[id='_chap_advanced_migration']
= Advanced Migration


[id='_rest_api_migration']
== REST API Migration

As you know, there are two ways you can use Red Hat JBoss BRMS/{PRODUCT}: in an embedded mode, or in a remote mode.
In the embedded mode, you package the runtime libraries with your application and execute the BPMN processes in the same JVM.
In the remote mode, the business assets are created, deployed and executed on the same server, but they are accessed via a remote client application using the REST or the JMS API.

Both of these modes presents different challenges when it comes to the migration.
In this section we will focus on the migration for the remote usage of {PRODUCT} with the help of a REST example.


[float]
=== REST API Example

This example shows how to:

* Start a process which is already deployed on the {PRODUCT} server.
* Pass parameters to this process during its creation.

The client side for JBoss BRMS 5 can be created using the following code:

[source,java]
----
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.HttpMethod;
import org.apache.commons.httpclient.NameValuePair;
import org.apache.commons.httpclient.methods.GetMethod;
import org.apache.commons.httpclient.methods.PostMethod;
import org.apache.commons.httpclient.methods.multipart.MultipartRequestEntity;
import org.apache.commons.httpclient.methods.multipart.Part;
import org.apache.commons.httpclient.methods.multipart.StringPart;
import org.jboss.bpm.console.client.model.ProcessDefinitionRef;
import org.jboss.bpm.console.client.model.ProcessDefinitionRefWrapper;
import org.jboss.bpm.console.client.model.ProcessInstanceRef;


 public class RestClientStartWithParam {
    private static final String BASE_URL = "http://localhost:8080/business-central-server/rs/";
    private static final String AUTH_URL = BASE_URL + "identity/secure/j_security_check";
    private final String username;
    private final String password;

    private static final String PROCESS_ID = "defaultPackage.hello";

    public RestClientStartWithParam(final String u, final String p) {
        this.username = u;
        this.password = p;
    }

    public static void main(String[] args) throws Exception {

        RestClientStartWithParam client = new RestClientStartWithParam("admin", "admin");

        // get process definitions
        ProcessDefinitionRefWrapper processDefinitionWrapper = client.getProcessDefinitions(client);

        // pick up "com.sample.bpmn.hello"
        ProcessDefinitionRef definitionRef = null;
        for (ProcessDefinitionRef processDefinitionRef : processDefinitionWrapper.getDefinitions()) {
            if (processDefinitionRef.getId().equals(PROCESS_ID)) {
                definitionRef = processDefinitionRef;
                break;
            }
        }
        if (definitionRef == null) {
            System.out.println(PROCESS_ID + " doesn't exist");
            return;
        }

        // start a process instance with parameters
        Map<String, String> params = new HashMap<String, String>();
        params.put("employee", "thomas");
        params.put("reason", "theReason");
        client.startProcessWithParameters(client, definitionRef, params);
    }

        private void startProcessWithParameters(RestClientStartWithParam client, ProcessDefinitionRef def,
            Map<String, String> params) throws Exception {
        String newInstanceUrl = BASE_URL + "form/process/" + def.getId() + "/complete";
        String dataFromService = client.getDataFromService(newInstanceUrl, "POST", params, true);

        System.out.println(dataFromService);
    }

    // get DataFromService method can be implemented like this

    private String getDataFromService(String urlpath, String method, Map<String, String> params, boolean multipart)
            throws Exception {
        HttpClient httpclient = new HttpClient();

        HttpMethod theMethod = null;
        StringBuffer sb = new StringBuffer();

        if ("GET".equalsIgnoreCase(method)) {
            theMethod = new GetMethod(urlpath);
        } else if ("POST".equalsIgnoreCase(method)) {
            theMethod = new PostMethod(urlpath);

            if (params != null) {

                if (multipart) {
                    List<Part> parts = new ArrayList<Part>();
                    for (String key : params.keySet()) {
                        StringPart stringPart = new StringPart(key, params.get(key));
                        stringPart.setCharSet("UTF-8");
                        parts.add(stringPart);
                    }
                    ((PostMethod) theMethod).setRequestEntity(new MultipartRequestEntity(parts.toArray(new Part[0]),
                            theMethod.getParams()));
                } else {

                    List<NameValuePair> nameValuePairList = new ArrayList<NameValuePair>();
                    for (String key : params.keySet()) {
                        nameValuePairList.add(new NameValuePair(key, params.get(key)));
                    }
                    ((PostMethod) theMethod).setRequestBody(nameValuePairList.toArray(new NameValuePair[0]));

                }
            }

        }

        if (username != null && password != null) {

            try {
                int result = httpclient.executeMethod(theMethod);
                System.out.println("result = " + result);
                // System.out.println(theMethod.getResponseBodyAsString());
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                theMethod.releaseConnection();
            }
            PostMethod authMethod = new PostMethod(AUTH_URL);
            NameValuePair[] data = { new NameValuePair("j_username", username),
                    new NameValuePair("j_password", password) };
            authMethod.setRequestBody(data);
            try {
                int result = httpclient.executeMethod(authMethod);
                System.out.println("result = " + result);
                // System.out.println(theMethod.getResponseBodyAsString());
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                authMethod.releaseConnection();
            }
        }

        try {
            int result = httpclient.executeMethod(theMethod);
            System.out.println("result = " + result);
            sb.append(theMethod.getResponseBodyAsString());
            String rawResult = sb.toString();
            return rawResult;

        } catch (Exception e) {
            throw e;
        } finally {
            theMethod.releaseConnection();
        }
    }
----
The JBoss BRMS 5 endpoints are documented in https://access.redhat.com/documentation/en-US/JBoss_Enterprise_BRMS_Platform/5/html/BRMS_User_Guide/sect-Rest_API.html[BRMS 5.0 User Guide] and https://access.redhat.com/documentation/en-US/JBoss_Enterprise_BRMS_Platform/5/html/BRMS_Business_Process_Management_Guide/REST_interface.html[BRMS 5.0 Business Process Management Guide].

As you can see, even this very simple example looks rather complex when implemented. The reason for this is partially that there is no native client for JBoss BRMS 5 server.  You can however choose the optional web client--Apache HttpClient, RestEasy or even use just plain `java.net` libraries. This applies in {PRODUCT}/BRMS 6 as well--you can still choose the web client--however, there is also a native java client provided for remote communication with version 6 which is much simpler to use.


[float]
=== Migrating to JBoss BRMS/{PRODUCT} 6

Let us migrate the same use case to {PRODUCT} 6:

- process is already deployed in the {PRODUCT} server

- we want to start it with some parameters

- this time, there are some human tasks in this process, so we want to complete those.

All of the available REST endpoints for Red Hat JBoss BRMS and {PRODUCT} are documented {URL_DEVELOPMENT_GUIDE}#sect_rest_api[here].

You can use either the Business Central remote API, or the {KIE_SERVER} remote API. Unless you configure the {KIE_SERVER} and Business Central to use the same data source, choose migration API based on what you are using at the moment. See chapter {URL_ADMIN_GUIDE}#unified_execution_servers[Unified Execution Servers] of the _{ADMIN_GUIDE}_ for more details.

[float]
=== {KIE_SERVER} API Example

To migrate using the {KIE_SERVER} API, see the following example:


[source,java]
----
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.kie.server.api.model.instance.TaskSummary;
import org.kie.server.client.KieServicesClient;
import org.kie.server.client.KieServicesConfiguration;
import org.kie.server.client.KieServicesFactory;
import org.kie.server.client.ProcessServicesClient;
import org.kie.server.client.UserTaskServicesClient;
 
public class Main {
  
    private static final String APP_URL = "http://localhost:8080/kie-execution-server/services/rest/server";
    private static final String USER = "john";
    private static final String PASSWORD = "john";

    // Container ID in the Intelligent Process Server/Realtime Decision Server
    private static final String CONTAINER_ID = "sample-container";
    private static final String PROCESS_DEFINITION_ID = "sample-project.sample-process";

    public static void main(String[] args) {
        // Configuration can be used for additional settings, like timeout, marshalling format...
        KieServicesConfiguration configuration = KieServicesFactory.newRestConfiguration(APP_URL, USER, PASSWORD);
        KieServicesClient kieServicesClient = KieServicesFactory.newKieServicesClient(configuration);
        ProcessServicesClient processClient = kieServicesClient.getServicesClient(ProcessServicesClient.class);
        UserTaskServicesClient taskClient = kieServicesClient.getServicesClient(UserTaskServicesClient.class);
 
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("employee", "thomas");
        params.put("reason", "theReason");
        processClient.startProcess(CONTAINER_ID, PROCESS_DEFINITION_ID, params);

        List<TaskSummary> tasks = taskClient.findTasksAssignedAsPotentialOwner(USER, 0, 10);
        taskClient.startTask(CONTAINER_ID, tasks.get(0).getId(), USER);
        // not passing any data = null
        taskClient.completeTask(CONTAINER_ID, tasks.get(0).getId(), USER, null);
    }
}
----
For a list of Maven dependencies, see example {URL_DEVELOPMENT_GUIDE}#dependency_management[Client Application {KIE_SERVER} Dependencies] of the _{DEVELOPMENT_GUIDE}_.  


[float]
=== Business Central API Example

To migrate using the Business Central API, see the following example:

[source,java]
----

import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.kie.api.runtime.KieSession;
import org.kie.api.task.TaskService;
import org.kie.api.task.model.TaskSummary;
import org.kie.api.runtime.manager.RuntimeEngine;
import org.kie.remote.client.api.RemoteRuntimeEngineFactory;

 public class Main {

	public static void main(String[] args) throws MalformedURLException {

		/*
		 * Set the parameters according to your installation
		 */

		String APP_URL = "http://localhost:8080/business-central/";

		URL url = new URL(APP_URL);
		String USER = "anton";
		String PASSWORD = "password1!";
        
    RuntimeEngine engine = RemoteRuntimeEngineFactory
                    .newRestBuilder()
                    .addUrl(url)
                    .addUserName(USER)
                    .addPassword(PASSWORD)
                    .addDeploymentId("org.redhat.gss:remote-test-project:3.0")
                    .build();

    KieSession kSession = engine.getKieSession();
    TaskService taskService = engine.getTaskService();

		 // start a process instance with parameters
     Map<String, Object> params = new HashMap<String, Object>();
     params.put("employee", "thomas");
     params.put("reason", "theReason");
     kSession.startProcess("com.sample", params);
    
     List<TaskService> taskSummaryList = taskService.getTasksAssignedAsPotentialOwner("anton","en-UK");
     taskService.claim(taskSummaryList.get(0).getId(), "anton");
     taskService.start(taskSummaryList.get(0).getId(), "anton");
     taskService.complete(taskSummaryList.get(0).getId(), "anton", null); // not passing any data = null
  }
}
----

For a list of Maven dependencies, see example {URL_DEVELOPMENT_GUIDE}#dependency_management[Client Dependencies] of the _{DEVELOPMENT_GUIDE}_. 


As you can see, this example is much more simple and readable than the one for JBoss BRMS 5.
The [class]``RemoteRuntimeEngine`` gives us direct access to the [class]``TaskService``/[class]``KieSession`` and [class]``AuditLogService`` API.

However, it is still possible to use your arbitrary Java web client and achieve the same scenario by sending GET/POST requests to the appropriate endpoints.

[NOTE]
====
While the basic functionality is provided by both APIs--JBoss BRMS{nbsp}5 and JBoss BRMS/{PRODUCT}{nbsp}6, (starting the process, completing the tasks and so on) not all endpoints from BRMS{nbsp}5 have their replacement in JBoss BRMS/{PRODUCT}{nbsp}6.

If in doubt, consult the corresponding documentation of the REST API.
====

[id='_knowledgeagent_to_kiescanner_migration']
== KnowledgeAgent to KieScanner Migration


KnowledgeAgent is a component of JBoss BRMS 5 which allows you to obtain Knowledge Bases dynamically as it gets updated.
If you correctly configure an instance of [class]``KnowledgeAgent`` and then you try to obtain the [class]``KnowledgeBase`` from the agent, you will be able to receive the latest version of the [class]``KnowledgeBase`` including updated resources - whether it is a freshly built package (*.PKG) in Business Central or BPMN process definition updated via the Eclipse designer tool.

See a working example of how this works in version 5 here: https://access.redhat.com/documentation/en-US/JBoss_Enterprise_BRMS_Platform/5/html/BRMS_User_Guide/chap-Integrating_Rules.html#The_Knowledge_Agent[KnowlegeAgent Example].

In JBoss BRMS and {PRODUCT} 6, it is also possible to obtain [class]``KieBase`` (instead of [class]``KnowledgeBase``) dynamically as it gets updated.
However, the migration is not so straightforward, because of a few things:

* In JBoss BRMS 5, the native storage for packages was Guvnor--which used JackRabbit repository underneath. You could also point to a single resource (drl, bpmn..) with any valid URL (i.e. `file://`, `http://`, ...).
* The API is completely different as there is no direct mapping between KnowledgeAgent API in JBoss BRMS/{PRODUCT} 6.

The component which replaces the [class]``KnowledgeAgent`` in BRMS 6 is called [class]``KieScanner``, and therefore you need to include `kie-ci` library on classpath if you want to use it.

See an example of how this works in version 6 here: {URL_DEVELOPMENT_GUIDE}#kiescanner[KieScanner Example].

In version 6, you no longer refer to `*.PKG`
 files or specific business resources such as drl, bpmn.
Instead you configure your [class]``KieScanner`` with a specific KJAR, which is a Maven artifact including your resources, identified by GAV (Group, Artifact, Version). [class]``KieScanner`` uses the Maven Repository to figure out where to look for these built KJARs.
If not specified otherwise, it will look into your local Maven repository (by default stored under `~/.m2/` directory on your filesystem).

A typical scenario will be where you set GAV so it identifies the project created in Business Central. [class]``KieScanner`` is now bound to this project, and once you make changes to this project in Business Central and build the project, its latest build will be stored into the local Maven repository (this is the default). [class]``KieScanner`` scans the local Maven repository and picks up the changes.
If you want to configure KieScanner in a way that it scans other repositories besides your local one you can do so by setting a system property: [property]``kie.maven.settings.custom`` which can point to the custom settings.xml (a standard Maven configuration file where you include all repositories which should be taken into consideration).

[class]``KieScanner`` invokes Maven under the hood for artifact lookup by following known Maven conventions and rules. For example:

* If the remote repository requires authentication, you need to configure this authentication in a Maven way by updating `settings.xml` .
* If you point your [class]``KieScanner`` to a KJar with GAV `org.my:project:1.0`, your KieBase will never get updated even if you build the project with the same GAV again. This is because Maven will resolve the artifact to a fixed version.
* If you point your [class]``KieScanner`` to a KJar with GAV `org.my:project:1.0-SNAPSHOT`, your KieBase will get updated for any new build of the project with that GAV--it will be resolved to the LATEST build of that GAV, identified by the timestamp.

A KCS article which discuss various scenarios and configurations is available at https://access.redhat.com/solutions/710763.

[id='_database_migration']
== Database Migration


The default underlying database in {PRODUCT} is an instance of H2. This is fine for most test systems, but production systems are generally based around MySQL, PostgreSQL, Oracle, or others databases. This section lists some of the tips and tricks related to databases when migrating from BRMS 5 to {PRODUCT} 6.x.

[float]
=== Include hbm.xml for PostgreSQL

If the underlying database on which the migration is being performed is PostgreSQL, you will need to include an additional configuration file, called `hbm.xml`
inside the `META-INF` directory, next to `persistence.xml`, with the following contents:

[source,xml]
----

<?xml version="1.0"?>
<!DOCTYPE hibernate-mapping PUBLIC
    "-//Hibernate/Hibernate Mapping DTD 3.0//EN"
    "http://hibernate.sourceforge.net/hibernate-mapping-3.0.dtd">
<hibernate-mapping>
  <typedef name="materialized_clob" class="org.hibernate.type.TextType" />
</hibernate-mapping>
----

This file instructs Hibernate to use `TextType` for materialized CLOBS and solves an issue where Hibernate incorrectly tries to interpret the type of a parameter as Long when it should be String based.


[float]
=== Avoid ID constraint violations in PostgresSQL and Oracle

[class]``NodeInstanceLog`` in BRMS 5.2.x does not have a sequence generator associated with it and was added to have more consistent behavior with multiple databases.
Since not all databases initialize the id sequence correctly on migration it is necessary to update the [property]``NODE_INST_LOG_ID_SEQ`` id manually.
The two databases that are affected are: PostgreSQL and Oracle.

* PostgreSQL: In PostgreSQL two actions are required:
** Find the `id` with the biggest value in the `NodeInstanceLog` table:
+
[source]
----
SELECT MAX(id) FROM nodeinstancelog;
----
** Restart sequence [property]``NODE_INST_LOG_ID_SEQ`` using the result from the previous step, increased by 1. For example, if the command in the previous step returned the number `10`, you will use `11` in the following command.
+
[source]
----
ALTER SEQUENCE node_inst_log_id_seq RESTART WITH 11;
----
+
The reason to increase the result from the first step by `1` is that restarting the sequence sets the [property]``is_called`` flag to ``false``, which tells the system that the sequence was not yet used.
* Oracle: In Oracle, the following steps are required:
** Find the `id` with the biggest value in the `NodeInstanceLog` table:
+
[source]
----
SELECT MAX(id) FROM nodeinstancelog;
----
** Execute the following commands in SQL:
+
[source]
----
-- Re-create the sequence by first dropping it and then creating a new one.
DROP SEQUENCE NODE_INST_LOG_ID_SEQ;
CREATE SEQUENCE NODE_INST_LOG_ID_SEQ START WITH 11 INCREMENT BY 1 NOCYCLE;

-- Increase the sequence (the result must be greater then the result obtained in step 1)
ALTER SEQUENCE NODE_INST_LOG_ID_SEQ INCREMENT BY 100;
----