[id='_chap_the_migration_process']
= Migrating from JBoss Enterprise BRMS Platform 5.3.1 to {PRODUCT} 6.x


[id='_what_has_changed']
== What has changed?

Before starting the migration process, let us find out what exactly has changed between the 5 and 6 branches of Red Hat JBoss BRMS/{PRODUCT}.

[float]
=== Naming Changes

First and foremost it is important to understand how older components in the 5 branch that you were familiar with relate to in the 6 branch.
The biggest change, of course, is the name of the product and its structure.

_JBoss Enterprise BRMS_ is now called _Red Hat JBoss BRMS_.
Red Hat JBoss BRMS, or JBoss BRMS, is a standalone product with its own workbench and is used solely to create and manage your business rules.

A new product, called _JBoss BPM Suite_, or _{PRODUCT}_ encapsulates the JBoss BRMS product and on top of that provides Business Process Management which allows you to create, manage, validate, and deploy Business Processes _and_ Rules.


[float]
=== Component Name Migration

Several components from the 5 branch to 6 branch have been renamed or merged with other components to provide a better working environment.
The figure below captures these changes.


[float]
=== API Name Changes

[cols="1,1", options="header"]
|===
| 5.x API (deprecated in 6.x)
| Replaced in 6.x by

| org.drools.KnowledgeBase
| org.kie.api.KieBase

| org.drools.runtime.StatefulKnowledgeSession
| org.kie.api.runtime.KieSession

| org.drools.runtime.StatelessKnowledgeSession
| org.kie.api.runtime.KieSession

| org.drools.builder.KnowledgeBuilderFactory
| org.kie.internal.builder.KnowledgeBuilderFactory

| org.drools.io.ResourceFactory
| org.kie.internal.io.ResourceFactory

| org.drools.io.ResourceType
| org.kie.internal.io.ResourceType

| org.drools.runtime.Environment
| org.kie.api.runtime.Environment

| org.drools.runtime.EnvironmentName
| org.kie.api.runtime.EnvironmentName

| org.drools.runtime.KnowledgeSessionConfiguration
| org.kie.api.runtime.KieSessionConfiguration

| org.drools.event.AgendaEventListener
| org.kie.api.event.rule.AgendaEventListener

| org.drools.event.rule.AgendaEventListener
| org.kie.api.event.rule.AgendaEventListener

| org.drools.event.DefaultAgendaEventListener
| org.kie.drools.core.event.DefaultAgendaEventListener

| org.drools.event.rule.DefaultAgendaEventListener
| org.kie.api.event.rule.DefaultAgendaEventListener

| org.drools.event.process.ProcessEventListener
| org.kie.api.event.process.ProcessEventListener

| org.drools.event.process.DefaultProcessEventListener
| org.kie.api.event.process.DefaultProcessEventListener

| org.drools.logger.KnowledgeRuntimeLogger
| org.kie.api.logger.KieRuntimeLogger

| org.drools.logger.KnowledgeRuntimeLoggerFactory
| org.kie.api.logger.KieLoggers
|===


[float]
=== Repository Change

Red Hat JBoss BRMS and {PRODUCT} 6 are backed by a Git repository for source management while JBoss BRMS 5 was backed by a JCR/JackRabbit implementation.
A tool to migrate the repository to Git is provided and discussed later in this guide.


[float]
=== Changes to the REST API

The base url for working with the REST API has changed from `\http://_SERVER_ADDRESS:PORT_/jboss-brms/rest/` to `\http://_SERVER_ADDRESS:PORT_/business-central/rest/`.


[float]
=== Migrating Task Service

JBoss BPMS 6 provides support for a locally running task server only.
This means that you do not need to setup any messaging service in your project.
This differs from JBoss BRMS 5 because it provided a task server that was bridged from the core engine by using, most commonly, the messaging system provided by HornetQ.

To help you bridge the gap until you can migrate this in your current architecture, there is a helper or utility method, [class]``LocalHTWorkItemHandler`` located in ``org.jbpm.services.task.wih``.

Since the TaskService API is part of the public API you will now need to refactor your imports because of package changes, and refactor your methods due to API changes themselves.

[float]
=== Logging factory


Besides the API name change, logging is now implemented through the `org.kie.api.logger` package, which contains the factory class [class]``KieLoggers`` that can be used to create instances of the [class]``KieRuntimeLogger``.


[id='_sect_how_to_migrate']
== How To Migrate

Migrating your projects from {PRODUCT} 5 to {PRODUCT} 6 requires careful planning and step by step evaluation of the various issues.
You can plan for migration either manually, or by using automatic processes.
Most real world migration will require a combination of these two processes.

Because {PRODUCT} 6 uses Git for storing assets, artifacts and code repositories including processes and rules, you should start by creating an empty project in {PRODUCT} 6 as the basis for your migration with dummy files as placeholders for the various assets and artifacts.
Running a Git clone of this empty project into your favorite IDE will initiate the migration process.

Based on the placeholder files in your cloned project, you can start adding assets at the correct locations.
The {PRODUCT} 6 system is smart enough to pick these changes and apply them correctly.
Ensure that when you are importing old rule files that they are imported with the right package name structure.

Since Maven is used for building projects, the projects assets like the rules, processes and models are accessible as a simple jar file.

This section lists the generally accepted step by step ways to migrate your project.
These are just guidelines though, and actual migration may vary a lot from this.

In general, you should:

. Migrate the data first: These are your business assets.
. Next, migrate your runtime processes.
. Finally, convert old API calls to new ones one by one.

Let us look at these steps in more detail in the next few sections:


=== Data Migration

To migrate data from {PRODUCT} 5, do the following:

. Download the migration tool by logging in at the https://access.redhat.com/downloads/[Red Hat Customer Portal] and then navigating to {PRODUCT} Software Downloads section. Click on _{PRODUCT} Migration Tool_ to download the zip archive.
. Unzip the downloaded zip archive in a directory of your choice and navigate to this directory in a command prompt. This directory contains four folders:
+
* `bin` - contains the launch scripts.
* `jcr-exporter-libs` - contains the libs specific to the `export-from-JCR` part of the migration.
* `vfs-importer-libs` - contains the libs specific to the `import-into-Git` part of the migration.
* `conf` - contains global migration tool configuration.
. For production databases, copy the JDBC driver for the database that is used by the JCR repository into the `jcr-exporter-libs` directory of the migration tool.
. Execute the following command:
+
[source]
----
./bin/runMigration.sh -i <source-path> -o <destination-path> -r <repository-name>
----
+

--
Where:

* `<source-path>` is a path to a source JCR repository.
* `<desintation-path>` is a path to a destination Git VFS. This folder must not exist already.
* `<repository-name>` an arbitrary name for the new repository.
--


The repository is migrated at the specified destination.

Besides the `-i` command, you can also use `-h` to print out a help message and `-f` which forces an overwrite of the output directory, thus eliminating the need for manual deletion of this directory.


[float]
==== Importing the repository in Business Central

The repository can be imported in business central by cloning it.
In the Administration page, click on the *Repositories*
 menu and then click on *Clone Repository*
 menu to start the process.

[NOTE]
====
Assets can also be migrated manually as they are just text files.
The BPMN2 specification and the DRL syntax did not change between the different versions.
====


[float]
==== Importing the repository in JBDS

To import the repository in JBoss Developer Studio, do the following

. Start JBoss Developer Studio.
. Start the {PRODUCT} server (if not already running) by selecting the server from the server tab and click the start icon.
. Select *File* -> *Import...* and navigate to the Git folder. Open the Git folder to select *Projects from Git* and click next.
. Select the repository source as *Existing local repository* and click next.
. Select the repository that is to be configured from the list of available repositories.
. Import the project as a general project in the next window and click next. Name this project and click Finish.


[id='_runtime_migration']
=== Runtime Migration

To run {PRODUCT} 5 processes in {PRODUCT} 6, do the following:

. Set the system property `jbpm.v5.id.strategy` to true in the {PRODUCT} `standalone.xml` file:
+
[source]
----
<property name="jbpm.v5.id.strategy" value="true"/>
----
. Load the KieSession as shown here:
+
[source]
----
KieSession ksession = JPAKnowledgeService.loadStatefulKnowledgeSession(sessionID, kbase, sessionConf, env);
----
. Continue the normal execution of the process using KieSession methods:
+
[source]
----
ksession.signalEvent("SomeEvent", null);
----


[id='_api_and_backwards_compatibility']
=== API and Backwards Compatibility

[float]
==== Migrating to Version 6.1 and later

In version 6.1, 5.x{nbsp}APIs are no longer officially supported.

{PRODUCT} no longer provides backward compatibility with the rule, event, and process application programming interface (API) from JBoss BRMS&nbsp;5. The content of the `knowledge-api` JAR file is no longer supported in version&nbsp;6.1 and onward, and is replaced by APIs contained in the `kie-api` JAR file that were introduced in {PRODUCT} 6.0.

If you used the legacy 5.x API (located in `knowledge-api.jar`), please migrate (rewrite) the API&nbsp;calls to the new KIE&nbsp;API. Please be aware that several other APIs have changed between JBoss BRMS 5.x and {PRODUCT} 6.x, namely the task service API and the REST API.

[float]
==== Migrating to Version 6.0


The {PRODUCT} 6 system provides backward compatibility with the rule, event and process interactions from JBoss BRMS 5. You should eventually migrate (rewrite) these interactions to the all new revamped core API because this backward compatibility is likely to be deprecated.

If you cannot migrate your code to use the new API, then you can use the API provided by the purpose built `knowledge-api` jar for backwards compatible code.  This API is the public interface for working with {PRODUCT} and JBoss BRMS and is backwards compatible.

If you are instead using the REST API in {PRODUCT} 5, note that this has changed as well and there is no mechanism in it for backwards compatibility.
