[id='migration-steps-proc']
= Migration steps

An upgrade is when an application is moved from one major release to another, for example, from Red Hat JBoss BRMS 6.3 to Red Hat JBoss BRMS 6.4. Migrations involve moving data and other artifacts to a separate software environment. Migrations usually include upgrades, updates, or a completely new software installation. 

You cannot upgrade from BRMS 6.4 to {PRODUCT} {PRODUCT_VERSION}. You must install {PRODUCT} {PRODUCT_VERSION} then migrate your data and other artifacts from BRMS 6.4 to the new installation as described in this guide.

.Prerequisite
* You have installed {PRODUCT} {PRODUCT_VERSION}, either on premise or on OpenShift.
* You have a Red Hat BRMS 6.4 installation that contains data and other artifacts that you want to migrate to {PRODUCT} {PRODUCT_VERSION}.

[NOTE]
====
If your Red Hat BRMS installation is lower than 6.4, you must migrate to Red Hat BRMS 6.4 before you migrate to {PRODUCT} {PRODUCT_VERSION}. For details, see the _Red Hat JBoss BPM Suite Migration Guide 6.4_.
====

.Procedure
. Migrate KIE projects from BRMS 6.4 to {PRODUCT} {PRODUCT_VERSION}.
. Migrate the local artifact repository.
. Update the embedded engines.
. Review changes in the engines.

[NOTE]
====
KJARS created with Red Hat BRMS 6.4 are not supported with {PRODUCT} {PRODUCT_VERSION}.
====

