
[id='_bxms_rn_whats_new_con.adoc']
= What's New

This section highlights changes between releases of {PRODUCT} {PRODUCT_VERSION} Limited Availability.

[discrete]
== Limited Availability Beta Build 1
OpenShift::
* Business Central and Runtime Monitoring are now available as separate OpenShift images.
* An image for the standalone controller is available.
* OpenShift Source-To-Image (S2I) is available.

Aliases::
You can now use aliases instead of container IDs in the remote REST APIs of the execution server.

Guided Decision Table::
* Guided Decision Table has a new wizard for creating and editing columns.
* Hit policies are now available. Hit policies determine the order in which rules (rows) in a guided decision table are applied.
* New support to display multiple linked guided decision tables in the Guided Decision Table Editor has been added.

Business Resource Planner::
The Business Resource Planner execution server now supports real-time planning.

Welcome Page::
The {PRODUCT} welcome page has been redesigned for easier navigation.

[discrete]
== Limited Availability Alpha Build 2
Project Metrics Dashboard::
A new dashboard is now available for every project listed in the authoring library. When the project details page is opened, a metrics card appears on the right side of the screen. The card shows the history of contributions (commits) made to that specific project over time. Click the *View All* link to access the full dashboard which shows several metrics about the project’s contributions. Different filter controls are available for selecting the contributions made either by a specific user or in a specified time frame.

Teams Metrics Dashboard::
A  new dashboard has been added to the *Teams* page. A metrics card on the right side shows the history of all contributions (commits). Click the *View All* link to access a full dashboard showing overall contributions metrics. You can filter the contributions by specifying the following criteria:

* User
* Time frame
* Team
* Project

This dashboard replaces  the former *Authoring->Contributors* dashboard, which is no longer available at the workbench’s top menu bar.

Improved Features::
The existing features have been stabilized with several bug fixes and usability related enhancements. 

[discrete]
== Limited Availability Alpha Build 1
Improved Navigation::
You can now navigate:
* From a process instance to the associated jobs
* From a job to the associated process instance
* From a process instance to the associated tasks

Improved Process Status Reporting::
The process status now reports when a process has errors associated with it.

Latest Improvements:: Feature development and bug fixes.
[discrete]
== Limited Availability CAP Build 2

ifdef::BA[]
Improved Search::
+
--
You can now search the following instances by the following fields:

[cols="1,2",options="header"]
|===
| Type of Instance
| Fields

.7+| Processes
| Process instance ID
| Process ID
| Status
| Initiator
| Correlation Key
| Creation Date
| Process Description

.7+| Tasks
| Task ID
| Task Name
| Status
| Correlation Key
| Assigned to
| Creation Date
| Process Description

.6+| Jobs
| Process instance ID
| Process ID
| Job Type
| Correlation Key
| Creation Date
| Process Description
|===
--

Configurable Error Handling::
+
If an error happens, an event is generated that holds the following data:
+
--
[cols="1,2",options="header"]
|===
| Data
| Fields

.3+| Process model
| processModelID
| processModelVersion
| processModelName

.2+| Process instance that has failed
| processInstanceID
| customProcessID

.5+| Activity that has failed
| activityID
| activityName
| activityType
| iteration
| status

.2+| Error data
| errorMessage: Message with the error that has occurred.
| errorStack: Stack with error detail.
|===
--

Advanced Queries Decoupled from the Database Model:: With this new API, you can make advanced queries using filters on process instances or tasks, independently of the instance field names. The API is accessible in the `org.kie.server.client.impl.SearchServicesClientImpl` class, which has the following methods:
+
--
* `findProcessInstanceWithFilters`: Accepts a filter created with the `org.kie.server.api.util.ProcessInstanceQueryFilterSpecBuilder` class.
* `findHumanTaskWithFilters`: Accepts a filter created with the `org.kie.server.api.util.TaskQueryFilterSpecBuilder`
class.
+
You can also create filters manually and submit them through the REST API.
--
endif::[]

Latest Improvements:: Feature development and bug fixes.

[discrete]
== Limited Availability CAP Build 1

* Process Admin Console improvements:
+
--
ifdef::BA[]
* New fields in the process instance list:
** *Last Modified:* The date of the last modification of the process instance.
** *Correlation Key:* The business correlation key of the process instance.
endif::[]

ifdef::BA[]
* New fields in the task list:
** *Modification Date:* The date of the last modification of the task.
** *Correlation ID:* The process instance business correlation key of the task.
** *Assigned to:* The actual owner of the task.
** *Process Description:* The process instance description.
endif::[]

ifdef::BA[]
* New fields in the jobs list:
** *Process Name:* The name of the process definition.
** *Task ID:* The job business key, that is the combination of the process instance ID and the work item ID. This field can be empty.
** *Process Description:* The process instance description.
endif::[]

* A unified management console for managing multiple KIE servers that contain different sets of containers.
--
* Latest feature development and bug fixes.
* Pre-alpha installation issues stabilized.

