
[id='_bxms_rn_introduction_con.adoc']
[id='_jboss_brms']
= About {PRODUCT}

ifdef::BA[]
{PRODUCT} is an open source business process management suite that combines Business Process Management and Business Rules Management. It enables business and IT users to create, manage, validate, and deploy business processes and rules.

{PRODUCT} uses a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic and business processes without requiring assistance from IT personnel.

To facilitate the Business Rules component, Red Hat JBoss BPM Suite includes integrated Red Hat JBoss BRMS.
endif::BA[]

ifdef::DM[]
Red Hat JBoss BRMS is an open source decision management platform that combines Business Rules Management and Complex Event Processing. It automates business decisions and makes that logic available to the entire business.

Red Hat JBoss BRMS uses a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.

The list of supported configurations for Red Hat JBoss BRMS is available at the https://access.redhat.com/articles/705183[Red Hat Customer Portal].
endif::DM[]

