[appendix]
[[_appe_simulation_data]]
= Simulation Data

[[_process2]]
== Process

[float]
=== Simulation Attributes
Base currency::
The currency used for simulation.
+
Base time unit::
The time unit to apply to all the time definitions in the process.

[[_activity1]]
== Activities

All the activities available in {PRODUCT}, except for the human task, share the following properties. See <<_human_tasks1>> for properties specific to human tasks.

[float]
=== Simulation Attributes

Cost per time unit::
The cost for every time unit lapsed during simulation.

Distribution Type::
For information about the `Distribution type` property, and the `Processing time` property if applicable, see <<_sect_distribution_types>>.

[[_start_event1]]
== Start Event

[float]
=== Simulation Attributes

Distribution Type::
For information about the `Distribution type` property, and the `Processing time` property if applicable, see <<_sect_distribution_types>>.

Probability (Boundary Event only)::
The probability of triggering the element.


[[_catching_intermediate_events1]]
== Catching Intermediate Events

[float]
=== Simulation Attributes

Distribution Type::
For information about the `Distribution type` property, and the `Processing time` property if applicable, see <<_sect_distribution_types>>.

Probability (Boundary Event only)::
The probability of triggering the element.

[[_sequence_flow1]]
== Sequence Flow

[float]
=== Simulation Attributes

Probability (Boundary Event only)::
The percentual probability that the flow is taken.
+
The probability value is applied only if the flow's source element is a gateway and there are multiple flow elements leaving the gateway.
When defining flow probabilities, ensure their sum is 100.


[[_throwing_intermediate_events1]]
== Throwing Intermediate Events

[float]
=== Simulation Attributes

Distribution Type::
For information about the `Distribution type` property, and the `Processing time` property if applicable, see <<_sect_distribution_types>>.

[[_human_tasks1]]
== Human Tasks

[float]
=== Simulation Attributes

Cost per time unit::
The cost for every time unit lapsed during simulation.

Distribution Type::
For information about the `Distribution type` property, and the `Processing time` property if applicable, see <<_sect_distribution_types>>.

Staff availability::
The number of actors available to work on the given task.
+

.Staff Availability Impact
[example]
--
Assume a simulation of 3 instances of a process. A new instance is created every 30 minutes.
The process contains a None Start Event, a Human Task, and a Simple End Event.

* The Human Task takes 3 hours to complete; the [property]``Working hours`` property is set to ``3``.
* Only one person is available to work on the Human Tasks; the [property]``Staff availability`` property is set to ``1``.

That results in the following:

* The Human Task generated by the first process instance will be executed in 3 hours.
* The Human Task generated by the second process instance will be executed in approx. 6 hours. The second process instance is created after 30 minutes. However, the actor is busy with the first Task and becomes available only after another 2.5 hours. It takes 3 hours to execute the second Task.
* The Human Task generated by the third process instance will be executed in approx. 9 hours. The second Human Task instance is finished after 3 hours. The actor needs another 3 hours to complete the third Human Task.
--
Working hours::
A time period after which the task completes in a simulation. If the task should take an hour to complete, set this property to `1`.

[[_end_events1]]
== End Events

[float]
=== Simulation Attributes

Distribution Type::
For information about the `Distribution type` property, and the `Processing time` property if applicable, see <<_sect_distribution_types>>.


[[_sect_distribution_types]]
== Distribution Types


The [property]``Distribution type`` property defines the distribution of possible time values, that is scores, of process elements.

The elements might use one of the following score distribution types on simulation:

* `Normal`: the values are distributed on a bell-shaped, symmetrical curve.
* `Uniform`: the values have a rectangular distribution, that means every value is applied the same number of times.
* `Poisson`: the values are distributed on a negatively-skewed normal distribution curve.


[[_normal]]
=== Normal

The element values are picked based on the normal distribution type, which is bell-shaped and symmetrical.

[float]
==== Normal Distribution Attributes

Processing time (mean)::
The mean processing time that the element needs in order to be processed. The value uses the time unit defined in the `Base time unit` property.


Standard deviation::
The standard deviation of the processing time. The value uses the time unit defined in the `Base time unit` property.



[[_uniform]]
=== Uniform

The Uniform distribution or rectangular distribution returns the possible values with the same levels of probability.

[float]
==== Uniform Distribution Attributes

Processing time (max)::
The maximum processing time of the element.

Processing time (min)::
The minimum processing time of the element.


[[_poisson]]
=== Poisson

The Poisson distribution returns the possible values similarly as normal distribution. However, the distribution is negatively skewed, not symmetrical. The mean and the variant are equal.

==== Poisson Distribution Attributes
Processing time (mean)::
The mean time for the element processing. The value uses the time unit defined in the `Base time unit` property.


:sectnums:
