[[applying_6.4_update_4]]
= Applying 6.4 Update 4

This tool updates an existing Red Hat JBoss BPM Suite or Red Hat JBoss BRMS installation version 6.4.0 through 6.4.3  to version 6.4.4. The update is distributed in a ZIP file that includes `.sh` and `.bat` scripts that automatically apply the updates.

.Prerequisites
You have a backed up Red Hat JBoss BPM Suite or Red Hat JBoss BRMS installation, version 6.4.0 through 6.4.3.

.Procedure

. Do one of the following, depending on the installation type that you want to update.
+
--
[NOTE]
====
To update your Maven repository, if you use the publicly hosted repository, update the BOM version in your `pom.xml` file. Otherwise, if a local Maven repository is used, download the incremental Maven repository as described in the following section, then extract it in your existing repository.
====
.Red Hat JBoss BPM Suite
.. Navigate to the Security Advisories section of the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=bpm.suite&version=6.4[Red Hat JBoss BPM Suite 6.4 Software Downloads] page on the Red Hat Customer Portal.
.. Download the following files:
* https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=52491[Red Hat JBoss BPM Suite 6.4 Update 4], file name `jboss-bpmsuite-6.4.4-patch.zip`
* https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=52481[Red Hat JBoss BPM Suite 6.4 Update 4 Incremental Maven Repository], file name `jboss-bpmsuite-6.4.4.GA-incremental-maven-repository.zip`

.Red Hat JBoss BRMS
.. Navigate to the Security Advisories section of the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=brms&version=6.4[Red Hat JBoss BRMS Suite 6.4 Software Downloads] page on the Red Hat Customer Portal.
.. Download the following files:
* https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=52471[Red Hat JBoss BRMS 6.4 Update 4], file name `jboss-brms-6.4.4-patch.zip`
* https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=52461[Red Hat JBoss BRMS 6.4 Update 4 Incremental Maven Repository], file name `jboss-brms-6.4.4.GA-incremental-maven-repository.zip`
--
+
. Shut down the server. Do not apply updates while you are running an instance of Red Hat JBoss BRMS or Red Hat JBoss BPM Suite. 
. Extract the downloaded ZIP files. 
+
--
[NOTE]
====
If you are using the local Maven repository, extract the Maven repository ZIP file in the existing Maven repository directory.
====
--
+
. Run the following command, where `<path-to-distribution-root>`  is the root directory of your current installation and `<type-of-distribution>` is your distribution type:
+
--
``$  apply-updates.sh <path-to-distribution-root> <type-of-distribution>``

See <<supported-6.4-distributions>> for a list of supported distribution types.

For example, the following command applies the updates to the Red Hat JBoss EAP 6.4 bundle:

`$ /apply-updates.sh ~/EAP_HOME/jboss-eap-6.4 eap6.x`
--
+

. Examine `.new` and `.remove` configuration files as described in <<new_and_remove_configuration_files>>.

.Related Information

* <<migrating_from_6.3_to_6.4_with_upgrade_tool>>
* <<new_and_remove_configuration_files>> 

