[id='assets-executing-proc_{context}']

ifeval::["{context}" == "execute-rules"]
= Executing rules

After you have created your rules in {CENTRAL}, you can build and deploy your project and execute rules locally or on {KIE_SERVER} to test rules.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name.
. In the upper-right corner, click *Build* and then *Deploy* to build the project and deploy it to {KIE_SERVER}. If the build fails, address any problems described in the *Alerts* panel at the bottom of the screen. For more information about deploying projects, see {URL_PACKAGING_DEPLOYING_PROJECT}[_{PACKAGING_DEPLOYING_PROJECT}_].
. Open the project `pom.xml` file and add `kie-server-client` as a dependency (if not added already). This dependency enables you to interact with assets on {KIE_SERVER}.
+
--
[source,xml]
----
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-client</artifactId>
</dependency>
----
////
.Dependencies for model classes
[NOTE]
====
[source,xml]
----
<dependency>
 <groupId>com.myspace</groupId>
 <artifactId>SimpleRule</artifactId>
 <version>1.0.0</version>
</dependency>
----

====
////
--
. Create a `.java` main class and save it to the same directory as the Java object in your project that you want to execute. The main class will load the knowledge base and execute rules.
. Configure the main class with the necessary imports and with a `main()` method to load the knowledge base, insert facts, and execute the rules.
+
--
For example, a `Person.java` class in the project contains getter and setter methods to set and retrieve the first name, last name, hourly rate, and the wage of a person. The following `Wage` rule in the project calculates the wage and hourly rate values and displays a message based on the result:

[source,java]
----
rule "Wage"
  when
    Person(hourlyRate * wage > 100)
    Person(name : firstName, surname : lastName)
  then
    System.out.println("Hello" + " " + name + " " + surname + "!");
    System.out.println("You are rich!");
end
----

To test this rule locally outside of {KIE_SERVER} (if desired), import KIE services, a KIE container, and a KIE session, and then use the `main()` method to fire all rules against a defined fact model:

.Execute rules locally
[source,java]
----
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;

public class RulesTest {
  public static final void main(String[] args) {
    try {
      // Identify the project in the local repository:
      ReleaseId rid = new ReleaseId();
        rid.setGroupId("com.myspace");
        rid.setArtifactId("MyProject");
        rid.setVersion("1.0.0");

      // Load the knowledge base:
      KieServices ks = KieServices.Factory.get();
      KieContainer kContainer = ks.newKieContainer(rid);
      KieSession kSession = kContainer.newKieSession();

      // Set up the fact model:
      Person p = new Person();
      p.setWage(12);
      p.setFirstName("Tom");
      p.setLastName("Summers");
      p.setHourlyRate(10);

      // Insert the person into the session:
      kSession.insert(p);

      // Fire all rules:
      kSession.fireAllRules();
    }

    catch (Throwable t) {
      t.printStackTrace();
    }
  }
}
----

To test this rule on {KIE_SERVER}, add the imports and rule execution details similarly to the local example, and additionally include KIE services configuration and KIE services client details:

.Execute rules on {KIE_SERVER}
[source,java]
----
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;
import org.kie.server.api.marshalling.MarshallingFormat;
import org.kie.server.client.KieServicesClient;
import org.kie.server.client.KieServicesConfiguration;
import org.kie.server.client.KieServicesFactory;
import org.kie.server.client.RuleServicesClient;

public class RulesTest {
  public static final void main(String[] args) {
    try {
      // Identify KIE services configuration and client:
      KieServicesConfiguration config = KieServicesFactory
			   .newRestConfiguration("http://$SERVER:$PORT/kie-server/services/rest/server", "$USER", "$PASSWORD");
		       config.setMarshallingFormat(MarshallingFormat.JSON);
		  KieServicesClient client = KieServicesFactory.newKieServicesClient(config);

      // Set up the fact model:
      Person p = new Person();
      p.setWage(12);
      p.setFirstName("Tom");
      p.setLastName("Summers");
      p.setHourlyRate(10);

      // Fire all rules:
      kSession.fireAllRules();
    }

    catch (Throwable t) {
      t.printStackTrace();
    }
  }
}
----
--
. Run the configured `.java` class from your project directory. You can run the file in your development platform (such as Red Hat JBoss Developer Studio) or in the command line.
+
--
Example Maven execution (within project directory):

[source]
----
mvn clean install
mvn exec:java -Dexec.mainClass="com.sample.app.RulesTest"
----

Example Java execution (within project directory)

[source]
----
javac -classpath "./$DEPENDENCIES/*:." RulesTest.java
javac -classpath "./$DEPENDENCIES/*:." RulesTest
----
--
. Review the rule execution status in the command line and in the server log. If any rules do not execute as expected, review the configured rules in the project and the main class configuration to validate the data provided.

ifeval::["{context}" == "execute-assets"]
= Executing assets deployed to {KIE_SERVER}

After you
endif::[]
