[id='_assets_projects_gloss_{context}']

= Projects

ifdef::BA[]
Projects are containers for asset packages (business processes, rules, work definitions, decision tables, fact models, data models, and DSLs) that are housed in a knowledge repository within a defined team in Business Central. Projects define the properties of the KIE Base and KIE Session that are applied to their content. In the GUI, you can edit these entities in the Project Editor.
endif::BA[]

ifdef::DM[]
Projects are containers for asset packages (business rules, decision tables, fact models, data models, and DSLs) that are housed in a knowledge repository within a defined team in Business Central. Projects define the properties of the KIE Base and KIE Session that are applied to their content. In the GUI, you can edit these entities in the Project Editor.
endif::DM[]

Because a project is a Maven project, it contains the Project Object Model file (`pom.xml`) with information on how to build the output artifact. It also contains the Module Descriptor file, `kmodule.xml`, that contains the KIE Base and KIE Session configuration for the assets in the project.

.Only packaged assets can be deployed
[IMPORTANT]
====
If an asset, such as a Process or Rule definition, is not placed in a package with a Project, it cannot be deployed.
Therefore, you must organize your assets in packages.
====
