[id='assets-executing-proc_{context}']

ifeval::["{context}" == "execute-rules"]
= Executing rules

After you have created your rules in {CENTRAL}, you can build and deploy your project and execute rules locally or on {KIE_SERVER} to test rules.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name.
. In the upper-right corner, click *Build* and then *Deploy* to build the project and deploy it to {KIE_SERVER}. If the build fails, address any problems described in the *Alerts* panel at the bottom of the screen. For more information about deploying projects, see {URL_PACKAGING_DEPLOYING_PROJECT}[_{PACKAGING_DEPLOYING_PROJECT}_].
. Open the `pom.xml` file of your client application and add the following dependencies, if not added already:
+
--
* `kie-ci`: Enables your client application to build {CENTRAL} project data locally using `ReleaseId`
* `kie-server-client`: Enables your client application to interact with assets on {KIE_SERVER}

[source,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-ci</artifactId>
</dependency>
<dependency>
  <groupId>org.kie.server</groupId>
  <artifactId>kie-server-client</artifactId>
</dependency>
----

NOTE: If the Bill of Materials (BOM) in {PRODUCT} is not specified in your dependency management, then you need to also specify the `<version>` value for these artifacts. For more information about Maven dependencies and the BOM in {PRODUCT}, see link:https://access.redhat.com/solutions/3405361[What is the mapping between {PRODUCT} and Maven library version?].

--
. Ensure also that the dependencies for artifacts containing model classes are defined the same way in the client application `pom.xml` file as they appear in the `pom.xml` file of the deployed project. If dependencies for model classes differ between the client application and your projects, execution errors can occur.
+
--
For example, the following is a `Person` class dependency as it appears in both the client and deployed project `pom.xml` files:

[source,xml]
----
<dependency>
 <groupId>com.person</groupId>
 <artifactId>Person</artifactId>
 <version>1.0.0</version>
</dependency>
----
--
. In your client application, create a `.java` main class containing the necessary imports and a `main()` method to load the knowledge base, insert facts, and execute the rules.
+
--
For example, a `Person` object in a project contains getter and setter methods to set and retrieve the first name, last name, hourly rate, and the wage of a person. The following `Wage` rule in a project calculates the wage and hourly rate values and displays a message based on the result:

[source,java]
----
rule "Wage"
  when
    Person(hourlyRate * wage > 100)
    Person(name : firstName, surname : lastName)
  then
    System.out.println("Hello" + " " + name + " " + surname + "!");
    System.out.println("You are rich!");
end
----

To test this rule locally outside of {KIE_SERVER} (if desired), configure the `.java.` class to import KIE services, a KIE container, and a KIE session, and then use the `main()` method to fire all rules against a defined fact model:

.Execute rules locally
[source,java]
----
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;

public class RulesTest {
  public static final void main(String[] args) {
    try {
      // Identify the project in the local repository:
      ReleaseId rid = new ReleaseId();
        rid.setGroupId("com.myspace");
        rid.setArtifactId("MyProject");
        rid.setVersion("1.0.0");

      // Load the knowledge base:
      KieServices ks = KieServices.Factory.get();
      KieContainer kContainer = ks.newKieContainer(rid);
      KieSession kSession = kContainer.newKieSession();

      // Set up the fact model:
      Person p = new Person();
      p.setWage(12);
      p.setFirstName("Tom");
      p.setLastName("Summers");
      p.setHourlyRate(10);

      // Insert the person into the session:
      kSession.insert(p);

      // Fire all rules:
      kSession.fireAllRules();
    }

    catch (Throwable t) {
      t.printStackTrace();
    }
  }
}
----

To test this rule on {KIE_SERVER}, configure the `.java` class with the imports and rule execution details similarly to the local example, and additionally include KIE services configuration and KIE services client details:

.Execute rules on {KIE_SERVER}
[source,java]
----
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;
import org.kie.server.api.marshalling.MarshallingFormat;
import org.kie.server.client.KieServicesClient;
import org.kie.server.client.KieServicesConfiguration;
import org.kie.server.client.KieServicesFactory;
import org.kie.server.client.RuleServicesClient;

public class RulesTest {
  public static final void main(String[] args) {
    try {
      // Identify KIE services configuration and client:
      KieServicesConfiguration config = KieServicesFactory
        .newRestConfiguration("http://$SERVER:$PORT/kie-server/services/rest/server", "$USER", "$PASSWORD");
        config.setMarshallingFormat(MarshallingFormat.JSON);
		  KieServicesClient client = KieServicesFactory.newKieServicesClient(config);

      // Set up the fact model:
      List<Command> commandList = new ArrayList<Command>();
      Person p = new Person();
      p.setWage(12);
      p.setFirstName("Tom");
      p.setLastName("Summers");
      p.setHourlyRate(10);

      // Insert the person into the session:
      commandList.add(KieServices.Factory.get().getCommands().newInsert(p));

      // Fire all rules:
      commandList.add(KieServices.Factory.get().getCommands().newFireAllRules());
      BatchExecutionCommand batch = KieServices.Factory.get().getCommands().newBatchExecution(commandList,
				"KSession1");
    }

    catch (Throwable t) {
      t.printStackTrace();
    }
  }
}
----
--
. Run the configured `.java` class from your project directory. You can run the file in your development platform (such as Red Hat JBoss Developer Studio) or in the command line.
+
--
Example Maven execution (within project directory):

[source]
----
mvn clean install exec:java -Dexec.mainClass="com.sample.app.RulesTest"
----

Example Java execution (within project directory)

[source]
----
javac -classpath "./$DEPENDENCIES/*:." RulesTest.java
java -classpath "./$DEPENDENCIES/*:." RulesTest
----
--
. Review the rule execution status in the command line and in the server log. If any rules do not execute as expected, review the configured rules in the project and the main class configuration to validate the data provided.

ifeval::["{context}" == "execute-assets"]
= Executing assets deployed to {KIE_SERVER}

After you
endif::[]
