[id='_building_custom_dashboard_widgets_components_con']
= Components

A page is a collection of different types of components. There are three types of components we can choose from, for creating a page using the *Page Authoring* tool in *Workbench*.

The component types and their sub-types are as follows:

* *Core* components - can be either be a new, blank HTML page or an existing user created page. There are two types of core components.

.Core components sub-types
[cols="1,1", options="header"]
|===
| Core component sub-types
| Description

|*HTML*
|This component opens a HTML editor widget. This can be used to easily create HTML pages using text, images, tables, links, colors, and so on. You can customize the page as per your requirements.
|*Page*
|This component allows you to add previously created pages to a new dashboard. You can use this component to nest custom pages you have already created in your newly-created dashboard.

|===

[NOTE]
=======
Core components are not mandatory. A page can have zero instance of core component as well.
=======

* *Navigational* components - is used for navigating between pages. There are six types of navigational components.

.Navigational components sub-types
[cols="1,1", options="header"]
|===
| Navigational component sub-types
| Description

|*Target Div*
|This component is used by other components (Tab list, Menu bar, Tree navigator) to display their entries and keep track of the content of the last item clicked.
|*Menu Bar*
|This component displays the entries of a navigation tree in the form of a Menu bar. There is no limit to the number of levels supported.
|*Tile Navigator*
|This component displays the navigation group in the form of tiles. *Workbench* is the default navigation group, when you create a new tile navigator. Groups are displayed as folders but for single entries, its content is displayed when selected.
|*Tree*
|This component displays the entries in a vertical tree structure format.
|*Carousel*
|This component displays or cycles through the selected perspectives like a carousel or a slide show.
|*Tab List*
|This component displays selected menu perspectives as tabs at the top of the widget.

|===

[NOTE]
=======
Target div setting is *not* available for non target div components like Carousel or Tile navigator.
=======

* *Reporting* components - is used for displaying data from the data sources graphically as graphs, tables, maps, and so on. There are ten types of reporting components. The reporting components can be configured using the *New Displayer* widget, which has the following three tabs:

** *Type*: Choose how to display custom data graphically.
** *Data*: Choose a data set from the list of custom data sets you have previously created in the *DataSource Explorer* or added to the *Data Sets* in the *Settings* menu.
** *Display*: Edit and customize the way the content is displayed by adding titles, changing colors, size, and so on.
