[id='building-custom-dashboard-widgets-reordering-entries-navigation-tree-proc']
= Reordering a navigation tree

In the *Navigation* panel you can reorder the navigation trees as well as its entries.

[NOTE]
====
The reordering options of tree entries will differ according to their position in the tree hierarchy.
====

[float]
== Reordering navigation trees
.Procedure
. Go to *Menu* -> *Design* -> *Pages*.
. Click the *Navigation* panel and then select the navigation tree you want to reorder.
. Click the gear icon of the tree and then move up or down as required.
+
[NOTE]
=======
First and last entries of a navigation tree have only two reordering options available.
=======
+
. Click *Save*.

[float]
== Reordering the entries of a navigation tree
.Procedure
. Go to *Menu* -> *Design* -> *Pages*.
. Click the *Navigation* panel and then expand the navigation tree.
. Click the gear icon of the entry you want to reorder and then move up or down as required.
. If desired, click *Goto Page* to view the selected page.
. Click *Save*.
