[id='case-management-stages-con-{context}']
= Stages

Case management stages are a collection of tasks. A stage is an ad hoc subprocess that can be defined using the process designer and may include other case management nodes, such as a milestone. A milestone can also be configured as completed when a stage or a number of stages are completed. Therefore, a milestone may be activated or achieved by the completion of a stage, and a stage may include a milestone or a number of milestones.

For example, in a patient triage case, the first stage may consist of observing and noting any obvious physical symptoms or a description from the patient of what their symptoms are, followed by a second stage for tests, and a third for diagnosis and treatment. 

There are three ways to complete a stage:

* By completion condition.
* By terminal end event.
* By setting the `AdHocCompletionCondition` to `autocomplete`, which will automatically complete the stage when there are no active tasks left in the stage. 
