[id='_chap_deploying_projects-{context}']
= Deploying and Managing Projects
:context: chap-deploying-and-managing

After you have created a decision service with your process definition and relevant resources, you must ensure that the service is packaged with the proper GAV settings and then deploy it to the process engine.

After it is deployed, you can create process instances based on the deployed resources.

include::project-packaging-con.adoc[leveloffset=+1]

include::project-gav-setting-proc.adoc[leveloffset=+2]

include::project-duplicate-GAV-con.adoc[leveloffset=+3]

include::project-duplicate-GAV-manage-proc.adoc[leveloffset=+3]

include::project-deploying-con.adoc[leveloffset=+1]

include::project-deploying-central-con.adoc[leveloffset=+2]

include::project-build-deploy-proc.adoc[leveloffset=+3]

include::project-manage-deployment-central-con.adoc[leveloffset=+3]

include::kieserver-configure-central-proc.adoc[leveloffset=+3]

include::project-deploying-maven-con.adoc[leveloffset=+2]

include::maven-external-configure-proc.adoc[leveloffset=+3]

include::service-start-proc.adoc[leveloffset=+3]

include::service-stop-remove-proc.adoc[leveloffset=+3]

ifdef::PAM[]
== Editing Container Aliases Through {CENTRAL}

You can set container aliases when creating containers in the Intelligent Process Server. If you do not provide an alias, the `artifactId` of the project is set as alias by default.

.Prerequisite
* Red Hat JBoss EAP 7 is installed.
* Intelligent Process Server is connected to {CENTRAL}.
* Intelligent Process Server is registered in the server template as a server instance.

To edit the alias value before building your project in {CENTRAL}:

. In {CENTRAL}, select *Menu* -> *Design* -> *Projects*.
. In the *Projects* perspective, select a project.
. On the title bar, click *Build & Deploy*.
+
The *Build & Deploy* window opens with the *Container id* and *Container Alias* fields populated.
. Edit the values of the properties on the *Build & Deploy* window as required then click *Ok*.
. Click *Menu* → *DevOps* -> *Execution Servers*.
. Select your container name listed under *KIE CONTAINERS*.
. In the Status section, click the corresponding link for a given server. A log in window opens.
. Enter the user name and password for the selected server, then click *OK*.
+
A response in xml format opens. You can expand the Response section of the xml file to view the server response.
+
For more information on container aliases, see the http://ccs-jenkins.gsslab.brq.redhat.com:8080/view/Topic%20branches%20-%20BPMS/job/doc-BPMS-Development_Guide-branch-BXMSDOC-1331/lastSuccessfulBuild/artifact/index.html#container_aliases[Container Aliases] section of the _{DEVELOPMENT_GUIDE}_.
endif::PAM[]


== Manage

The following sections describe the features provided by the options available under *Menu* → *Manage* in {CENTRAL}.


include::process-definitions-con.adoc[leveloffset=+1]
include::process-instances-con.adoc[leveloffset=+1]
include::searching-process-instances-partial-key-proc.adoc[leveloffset=+2]
include::searching-process-instances-business-data-proc.adoc[leveloffset=+2]
include::creating-new-process-instance-list-proc.adoc[leveloffset=+2]

ifdef::PAM[]
include::process-instance-filtering-proc.adoc[leveloffset=+2]
endif::PAM[]

include::aborting-process-instances-proc.adoc[leveloffset=+2]

[id='_signaling_a_process_instance']
=== Signaling Process Instance

You can signal a running process instance using either API or {CENTRAL}. For further information about signals, signaling external deployment, catching and processing signals, and more, see <<_sect_collaboration_mechanisms>>.

include::signalling-process-instance-from-API-proc.adoc[leveloffset=+2]
include::signalling-process-instance-from-central-proc.adoc[leveloffset=+3]

[id='_sect_user_tasks']
=== Task Management

The following sections describe the features provided by the options available from *Menu* -> *Track* -> *Task Lists*.

include::tasks-inbox-con.adoc[leveloffset=+1]
include::task-client-ref.adoc[leveloffset=+2]
include::creating-custom-task-filters-proc.adoc[leveloffset=+2]

ifdef::PAM[]

include::advanced-search-task-filtering-proc.adoc[leveloffset=+2]
endif::PAM[]


include::task-variables-as-expressions-ref.adoc[leveloffset=+3]
