[id='data_sets_caching_con']
= Caching

{CENTRAL} provides caching mechanisms for storing data sets and performing data operations using the in-memory data. Caching data reduces network traffic, remote system payload, and processing time, among other things. In {CENTRAL}, you have to fine tune the caching settings so as to avoid facing performance issues. For any data look-up call that results in a data set, the caching techniques determine where the data lookup calls are executed and where the resulting data set is stored.

{CENTRAL} data set functionality provides two cache levels:

* Client level
* Back-end level

[float]
== Client cache

When this cache is turned on, the data set is cached in a web browser during the look-up operation. Consequently, further look-up operations do not perform requests to the back end. Data set operations like grouping, aggregations, filtering and sorting are processed in the web browser. Enable client caching only if the data set size is small (for example, less than 10 mb) otherwise for large data sets, browser issues such as slow performance or intermittent freezing can occur. Client caching reduces the number of back-end requests including requests to the storage system.

[float]
== Back-end cache

When this cache is turned on, the data set is cached by the {CENTRAL} engine. Doing this reduces the number of requests to the remote storage system. All data set operations are performed in the {CENTRAL} engine using the in-memory data. Enable back-end caching only if the data set size is not updated frequently and it can be stored and processed in memory. Using back-end caching is also useful in cases with low latency connectivity issues with the remote storage.

[NOTE]
====
The Java and CSV data providers rely on back-end caching.
====

[NOTE]
====
Back-end cache settings are not always visible in the *Advanced* tab of the *Data Set Editor*.
====
