[#data_sets_edit_proc]
= Editing Data Sets

You can edit existing data sets as needed to ensure that fetched data in your Dashboard displayer is updated.

.Procedure
. Log in to Business Central and click *Extensions* -> *Data Sets*.
. In *Data Set Explorer*, click on an existing data set and click *Edit*.
. In the *Data Set Editor*, use the tabs to edit the data as needed. Some of the tabs differ based on the provider type you chose.
+
For example, the following applies to the *CSV* data provider.
+
* *CSV Configuration:* Allows you to change the name of your data set definition, the source file, the separator, and other properties.
* *Preview:* After you click *Test* in the *CSV Configuration* tab, the system executes the data set lookup call and if the data is available, you will see a preview. Notice two subtabs:
** *Data columns:* Allows you to customize what columns are part of your data set definition.
** *Filter:* Allows you to add a new filter.
* *Advanced:* Allows you to manage:
** *Caching:* See <<data_sets_caching_con>> for more information.
** *Cache life-cycle* See <<data_sets_refresh_con>> for more information.
