[id='data_sets_con']
= Data sets authoring

A data set is a collection of related sets of information. It can be stored in many ways, such as, in a database, in an excel file, in memory and so on.

A data set definition, on the other hand, instructs {CENTRAL} on how to access, read, and parse a data set.

{CENTRAL} does not store data. It provides a way to define access to a data set regardless of where the data is stored.

For example, take an example of data stored in a database. A valid data set could be, the entire database or a subset of the database (the result of an SQL query). In both cases, the database will return data in the form of a matrix of rows and columns. This data is used as input for the reporting components which then displays the information graphically.

To access a data set, you must create and register a data set definition, which will define, where the data set is stored, how it can be accessed, read, and parsed, and what columns it contains.

[NOTE]
====
The *Data Sets* page is visible only to users with *admin* group.
====
