[id='drl-rules-maven-create-proc']
= Creating and executing DRL rules using Maven

You can use Maven archetypes to create DRL files with rules and integrate the archetypes with your {PRODUCT} decision service. This method of creating DRL rules is helpful if you already use external Maven archetypes for your decision service and want to continue with the same work flow. If you do not already use this method, then the {CENTRAL} interface of {PRODUCT} is recommended for creating DRL files and other rule assets.

.Procedure
. Navigate to a directory where you want to create a Maven archetype and run the following command:
+
[source]
----
mvn archetype:generate -DgroupId=com.sample.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
----
+
This creates a directory `my-app` with the following structure:
+
[source]
----
my-app
|-- pom.xml
`-- src
    |-- main
    |   `-- java
    |       `-- com
    |           `-- sample
    |               `-- app
    |                   `-- App.java
    `-- test
        `-- java
            `-- com
                `-- sample
                    `-- app
                        `-- AppTest.java
----
+
The `my-app` directory contains the following key components:
+
* A `src/main` directory for storing the application sources
* A `src/test` directory for storing the test sources
* A `pom.xml` file with the project configuration

. Create a Java object on which the rule or rules will operate within the Maven archetype.
+
In this example, a `Person.java` file is created in the directory `my-app/src/main/java/com/sample/app`. The `Person` class contains getter and setter methods to set and retrieve the first name, last name, hourly rate, and the wage of a person:
+
[source,java]
----
package com.sample.app;

  public class Person {

    private String firstName;
    private String lastName;
    private Integer hourlyRate;
    private Integer wage;

    public String getFirstName() {
      return firstName;
    }

    public void setFirstName(String firstName) {
      this.firstName = firstName;
    }

    public String getLastName() {
      return lastName;
    }

    public void setLastName(String lastName) {
      this.lastName = lastName;
    }

    public Integer getHourlyRate() {
      return hourlyRate;
    }

    public void setHourlyRate(Integer hourlyRate) {
      this.hourlyRate = hourlyRate;
    }

    public Integer getWage(){
      return wage;
    }

    public void setWage(Integer wage){
      this.wage = wage;
    }
  }
----
+
. Create a rule file in `.drl` format in `my-app/src/main/resources/rules`. The DRL file must contain at minimum a package specification, an import list of data objects to be used by the rule or rules, and one or more rules with `when` conditions and `then` actions.
+
The following `Wage.drl` file contains a `Wage` rule that imports the `Person` class, calculates the wage and hourly rate values, and displays a message based on the result:
+
[source,java]
----
package com.sample.app;

import com.sample.app.Person;

dialect "java"

rule "Wage"
  when
    Person(hourlyRate * wage > 100)
    Person(name : firstName, surname : lastName)
  then
    System.out.println("Hello " + name + " " + surname + "!");
    System.out.println("You are rich!");
end
----
+
. In the `my-app/src/main/resources/META-INF` directory, create a `kmodule.xml` metadata file with the following content:
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<kmodule xmlns="http://www.drools.org/xsd/kmodule">
</kmodule>
----
+
This `kmodule.xml` file is a KIE module descriptor that selects resources to knowledge bases and configures sessions. This file enables you to define and configure one or more KIE bases, and to include DRL files from specific `packages` in a specific KIE base. You can also create one or more KIE sessions from each KIE base.
+
The following example shows a more advanced `kmodule.xml` file:
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<kmodule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.drools.org/xsd/kmodule">
  <kbase name="KBase1" default="true" eventProcessingMode="cloud" equalsBehavior="equality" declarativeAgenda="enabled" packages="org.domain.pkg1">
    <ksession name="KSession1_1" type="stateful" default="true" />
    <ksession name="KSession1_2" type="stateful" default="true" beliefSystem="jtms" />
  </kbase>
  <kbase name="KBase2" default="false" eventProcessingMode="stream" equalsBehavior="equality" declarativeAgenda="enabled" packages="org.domain.pkg2, org.domain.pkg3" includes="KBase1">
    <ksession name="KSession2_1" type="stateless" default="true" clockType="realtime">
      <fileLogger file="debugInfo" threaded="true" interval="10" />
      <workItemHandlers>
        <workItemHandler name="name" type="new org.domain.WorkItemHandler()" />
      </workItemHandlers>
      <listeners>
        <ruleRuntimeEventListener type="org.domain.RuleRuntimeListener" />
        <agendaEventListener type="org.domain.FirstAgendaListener" />
        <agendaEventListener type="org.domain.SecondAgendaListener" />
        <processEventListener type="org.domain.ProcessListener" />
      </listeners>
    </ksession>
  </kbase>
</kmodule>
----
+
This example defines two KIE bases. Two KIE sessions are instantiated from the `KBase1` KIE base, and one KIE session from `KBase2`. The KIE session from `KBase2` is a `stateless` KIE session, which means that data from a previous invocation of the KIE session (the previous session state) is discarded between session invocations. Specific `packages` of rule assets are included with both KIE bases. When you specify packages in this way, you must organize your DRL files in a folder structure that reflects the specified packages.
+
. In the `my-app/pom.xml` configuration file, specify the libraries that your application requires. Provide the {PRODUCT} dependencies as well as the `group ID`, `artifact ID`, and `version` (GAV) of your application.
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>com.sample.app</groupId>
<artifactId>my-app</artifactId>
<version>1.0.0</version>
<repositories>
  <repository>
    <id>jboss-ga-repository</id>
    <url>http://maven.repository.redhat.com/ga/</url>
  </repository>
</repositories>
<dependencies>
  <dependency>
    <groupId>org.drools</groupId>
    <artifactId>drools-compiler</artifactId>
    <version>VERSION</version>
  </dependency>
  <dependency>
    <groupId>org.kie</groupId>
    <artifactId>kie-api</artifactId>
    <version>VERSION</version>
  </dependency>
  <dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.11</version>
    <scope>test</scope>
  </dependency>
</dependencies>
</project>
----
+
For information about Maven dependencies and the BOM (Bill of Materials) in {PRODUCT}, see link:https://access.redhat.com/solutions/3405361[What is the mapping between {PRODUCT} and Maven library version?].
+
. Use the `testApp` method in `my-app/src/test/java/com/sample/app/AppTest.java` to test the rule. The `AppTest.java` file is created by Maven by default.
+
. In the `AppTest.java` file, add the required `import` statements to import KIE services, a KIE container, and a KIE session. Then load the knowledge base, insert facts, and execute the rule from the `testApp()` method that passes the fact model to the rule.
+
[source,java]
----
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;

public void testApp() {

  // Load the knowledge base:
  KieServices ks = KieServices.Factory.get();
  KieContainer kContainer = ks.getKieClasspathContainer();
  KieSession kSession = kContainer.newKieSession();

  // Set up the fact model:
  Person p = new Person();
  p.setWage(12);
  p.setFirstName("Tom");
  p.setLastName("Summers");
  p.setHourlyRate(10);

  // Insert the person into the session:
  kSession.insert(p);

  // Fire all rules:
  kSession.fireAllRules();
  kSession.dispose();
}
----
+
. After you create and save all DRL assets in your Maven archetype, navigate to the `my-app` directory in the command line and run the following command to build your files:
+
[source]
----
mvn clean install
----
+
If the build fails, address any problems described in the command line error messages, and try again to validate the files until the build is successful.
. After your files build successfully, run the following command to execute the rules locally. Replace `com.sample.app` with your package name.
+
[source]
----
mvn exec:java -Dexec.mainClass="com.sample.app"
----
. Review the rules to ensure that they executed properly, and address any needed changes in the files.

To integrate the new rule assets with an existing project in {PRODUCT}, you can compile the new Maven project as a knowledge JAR (KJAR) and add it as a dependency in the `pom.xml` file of the project in {CENTRAL}.
