[id='drl-rules-java-create-proc']
= Creating and executing DRL rules using Java

You can use Java objects to create DRL files with rules and integrate the objects with your {PRODUCT} decision service. This method of creating DRL rules is helpful if you already use external Java objects for your decision service and want to continue with the same work flow. If you do not already use this method, then the {CENTRAL} interface of {PRODUCT} is recommended for creating DRL files and other rule assets.

.Procedure
. Create a Java object on which the rule or rules will operate.
+
In this example, a `Person.java` file in a directory `my-project` is created. The `Person` class contains getter and setter methods to set and retrieve the first name, last name, hourly rate, and the wage of a person:
+
[source,java]
----
  public class Person {
    private String firstName;
    private String lastName;
    private Integer hourlyRate;
    private Integer wage;

    public String getFirstName() {
      return firstName;
    }

    public void setFirstName(String firstName) {
      this.firstName = firstName;
    }

    public String getLastName() {
      return lastName;
    }

    public void setLastName(String lastName) {
      this.lastName = lastName;
    }

    public Integer getHourlyRate() {
      return hourlyRate;
    }

    public void setHourlyRate(Integer hourlyRate) {
      this.hourlyRate = hourlyRate;
    }

    public Integer getWage(){
      return wage;
    }

    public void setWage(Integer wage){
      this.wage = wage;
    }
  }
----

. Create a rule file in `.drl` format under the `my-project` directory.
+
The following `Person.drl` rule calculates the wage and hourly rate values and displays a message based on the result:
+
[source,java]
----
dialect "java"

rule "Wage"
  when
    Person(hourlyRate * wage > 100)
    Person(name : firstName, surname : lastName)
  then
    System.out.println("Hello" + " " + name + " " + surname + "!");
    System.out.println("You are rich!");
end
----
. Create a main class and save it to the same directory as the Java object that you created. The main class will load the knowledge base and execute rules.
. In the main class, add the required `import` statements to import KIE services, a KIE container, and a KIE session. Then load the knowledge base, insert facts, and execute the rule from the `main()` method that passes the fact model to the rule.
+
In the following example, the required imports are listed and a main class `DroolsTest.java` is created:
+
[source,java]
----
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;

public class DroolsTest {
  public static final void main(String[] args) {
    try {
      // Load the knowledge base:
      KieServices ks = KieServices.Factory.get();
      KieContainer kContainer = ks.getKieClasspathContainer();
      KieSession kSession = kContainer.newKieSession();

      // Go!
      Person p = new Person();
      p.setWage(12);
      p.setFirstName("Tom");
      p.setLastName("Summers");
      p.setHourlyRate(10);

      kSession.insert(p);
      kSession.fireAllRules();
    }

    catch (Throwable t) {
      t.printStackTrace();
    }
  }
}
----
+
. Download the *{PRODUCT} {PRODUCT_VERSION} Core Engine* ZIP file from the https://access.redhat.com/downloads/[Red Hat Customer Portal] and extract it under
ifdef::PAM[]
`my-project/bas-engine-jars/`.
endif::[]
ifdef::DM[]
`my-project/dm-engine-jars/`.
endif::[]
+
. In the `my-project/META-INF` directory, create a `kmodule.xml` metadata file with the following content:
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<kmodule xmlns="http://www.drools.org/xsd/kmodule">
</kmodule>
----
+
This `kmodule.xml` file is a descriptor that selects resources to knowledge bases and configures sessions. This file enables you to define and configure one or more KIE bases, and to include DRL files from specific `packages` in a specific KIE base. You can also create one or more KIE sessions from each KIE base.
+
The following example shows a more advanced `kmodule.xml` file:
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<kmodule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.drools.org/xsd/kmodule">
  <kbase name="KBase1" default="true" eventProcessingMode="cloud" equalsBehavior="equality" declarativeAgenda="enabled" packages="org.domain.pkg1">
    <ksession name="KSession1_1" type="stateful" default="true" />
    <ksession name="KSession1_2" type="stateless" default="false" beliefSystem="jtms" />
  </kbase>
  <kbase name="KBase2" default="false" eventProcessingMode="stream" equalsBehavior="equality" declarativeAgenda="enabled" packages="org.domain.pkg2, org.domain.pkg3" includes="KBase1">
    <ksession name="KSession2_1" type="stateful" default="false" clockType="realtime">
      <fileLogger file="debugInfo" threaded="true" interval="10" />
      <workItemHandlers>
        <workItemHandler name="name" type="new org.domain.WorkItemHandler()" />
      </workItemHandlers>
      <listeners>
        <ruleRuntimeEventListener type="org.domain.RuleRuntimeListener" />
        <agendaEventListener type="org.domain.FirstAgendaListener" />
        <agendaEventListener type="org.domain.SecondAgendaListener" />
        <processEventListener type="org.domain.ProcessListener" />
      </listeners>
    </ksession>
  </kbase>
</kmodule>
----
+
This example defines two KIE bases. Two KIE sessions are instantiated from the `KBase1` KIE base, and one KIE session from `KBase2`. Specific `packages` of rule assets are included with both KIE bases. When you specify packages in this way, you must organize your DRL files in a folder structure that reflects the specified packages.
+
. After you create and save all DRL assets in your Java object, navigate to the `my-project` directory in the command line and run the following command to build your Java files. Replace `DroolsTest.java` with the name of your Java main class.
+
ifdef::PAM[]
[source]
----
javac -classpath "./bas-engine-jars/*:." DroolsTest.java
----
endif::[]

ifdef::DM[]
[source]
----
javac -classpath "./dm-engine-jars/*:." DroolsTest.java
----
endif::[]
+
If the build fails, address any problems described in the command line error messages, and try again to validate the Java object until the object passes.
+
. After your Java files build successfully, run the following command to execute the rules. Replace `DroolsTest` with the prefix of your Java main class.
+
ifdef::PAM[]
[source]
----
javac -classpath "./bas-engine-jars/*:." DroolsTest
----
endif::[]

ifdef::DM[]
[source]
----
javac -classpath "./dm-engine-jars/*:." DroolsTest
----
endif::[]
+
. Review the rules to ensure that they executed properly, and address any needed changes in the Java files.

To integrate the new rule assets with an existing project in {PRODUCT}, you can compile the new Java project as a knowledge JAR (KJAR) and add it as a dependency in the `pom.xml` file of the project in {CENTRAL}.
