[id='entando-app-building-proc_{context}']

= Building pages with {PRODUCT} data in Entando

After you integrate your {KIE_SERVERS} in Entando, you can use BPM widgets in Entando to build pages with data from {PRODUCT}.

.Prerequisites
* One or more {KIE_SERVERS} containing project data have been configured in Entando App Builder.
* All necessary page models and pages have been set up in Entando App Builder. For instructions, see Getting started with Entando App Builder.
* You are logged in to the Entando Admin Console.

.Procedure
. In the Entando Admin Console, go to *Page Designer* -> *Page Tree*.
. Next to the page in which you want to add {PRODUCT} data, click the icon in the *Actions* column and click *Edit*.
. Review all existing page data and ensure that the most appropriate *Page Model* is specified. For example, a *BPM layout* page model with default widgets is ideal for BPM pages. To create or modify page models, go to *Page Designer* -> *Page Models*.
. Click *Save and configure*.
+
The page is displayed with vacancies where widgets can be placed according to the defined page model. Available widgets are displayed on the right side of the screen. Widgets listed under *jpkiebpm* are the BPM-specific widgets that enable you to implement {PRODUCT} data in pages.
. If applicable, click *Apply the default widgets* in the upper left corner of the screen to apply any default widgets defined in the page model.
. Select and drag the desired BPM widgets onto a vacancy on the page.
. In the widget configuration window that appears, specify the following details that apply
+
* *knowledgeSource:* Select the {KIE_SERVER} from which data will be pulled for this widget.
* *container-id:* Select the KIE container (deployment unit) that contains the project with the relevant data for this widget.
* *Channel:* Select a data channel that will be used for this widget on the page. All widgets on the same page must use the same channel.
. Click *Save* to save the widget configurations.
. Continue dragging, dropping, and configuring widgets as needed to populate the page.
. Click *Preview* to preview page data, and click *Publish* to publish the page.
