[id='entando-widgets-con_{context}']

= Entando application widgets

In Entando App Builder, widgets are the building blocks for your applications. A widget is an independent software component configured and executed within the page configured for your application to build UX/UI blocks of functionality.

The following are some of the types of widgets in Entando:

* Stock widgets: Widgets provided by App Builder to implement common functions
* User widgets: Widgets created by the user in the App Builder Admin Console
* Specific application widgets: Widgets provided by installed applications. For example, if the CMS module is installed, the App Builder provides widgets related to Content Management.
* Plugin widgets: Widgets provided by installed plugins. For example, if the KIE BPM plugin is installed, the App Builder provides widgets related to BPM.

When {PRODUCT} is integrated with Entando, the KIE BPM plugin widget enables you to implement {PRODUCT} applications in the Entando App Builder.

For more information about Entando App Builder widgets, see Getting started with Entando App Builder.
