[id='entando-app-building-proc_{context}']

= Building pages with {PRODUCT} asset data in Entando

After you integrate your {KIE_SERVERS} in Entando, you can use BPM widgets in Entando to build pages with asset data from {PRODUCT}.

.Prerequisites
* One or more {KIE_SERVERS} containing your project data have been configured in Entando App Builder.
* All necessary page models and pages have been set up in Entando App Builder. For instructions, see Getting started with Entando App Builder.
* You are logged in to the Entando Admin Console.

.Procedure
. In the Entando Admin Console, go to *Page Designer* -> *Page Tree*.
. Next to the page in which you want to add {PRODUCT} data, click the icon in the *Actions* column and click *Edit*.
. Review all existing page data and ensure that the most appropriate *Page Model* is specified. For example, you can use the *BPM layout* page model with default widgets or a custom BPM page model for BPM pages. To create or modify page models, go to *UX Patterns* -> *Page Models*.
. Click *Save and configure*.
+
The application page is displayed with frames where widgets can be placed according to the defined page model. Available widgets are displayed on the right side of the screen. Widgets listed under *jpkiebpm* are the BPM-specific widgets that enable you to implement {PRODUCT} data in pages.
. If applicable, click *Apply the default widgets* in the upper left corner of the screen to apply any default widgets defined in the page model.
. Select and drag a BPM widget from the widget menu onto a frame on the page.
. In the widget configuration window that appears, specify the following details that apply to this widget. Options vary based on the type of widget.
+
* *knowledgeSource:* Select the {KIE_SERVER} from which data will be pulled for this widget.
* *container-id:* Select the KIE container (deployment unit) that contains the project with the relevant data for this widget.
* *Channel:* Select the data channel that will be used by all widgets on the page. You can select any channel, but all widgets on the same page must use the same channel.
. Click *Save* to save the widget configurations.
. Continue dragging, dropping, and configuring widgets as needed to populate the page.
. Click *Preview* to preview page data, and click *Publish* to publish the page.
. After you finish building your pages with {PRODUCT} data, go to *<?>* and review your published pages.
+
*<@Ken or @Ben: Where can users go to see their published pages/applications?>*
