[id='guided-decision-tables-columns-attribute-con']
= "Add an Attribute column"

With this column option, you can add one or more attribute columns representing any of the DRL rule attributes, such as Saliance, Enabled, Date-Effective, and others.

Example:

[source,java]
----
rule "Rule1"
salience 100 // This rule has the highest priority
when
  $i : IncomeSource( type == "Asset" )
then
  ...
end
----

For descriptions of each attribute, select the attribute from the list in the wizard.

.Hit policies and attributes
[NOTE]
====
Note that depending on the hit policy that you have defined for the decision table, some attributes may be disabled because they are internally used by the hit policy. For example, if you have assigned the *Resolved Hit* policy to this table so that rows (rules) are applied according to a priority order specified in the table, then the Salience attribute would be obsolete. The reason is that the Salience attribute escalates rule priority according to a defined salience value, and that value would be overridden by the *Resolved Hit* policy in the table.
====

.Required Column Parameter
The following parameter is required in the *Add a new column* wizard to set up this column type:

* *Attribute:* Select the attribute to be applied to the column.
