[id='guided-decision-tables-types-con']
= Types of guided decision tables

Two types of decision tables are supported in {PRODUCT}: Extended entry and Limited entry tables.

* *Extended entry:* An Extended Entry decision table is one for which the column definitions specify Pattern, Field, and Operator but not value.
The values, or states, are themselves held in the body of the decision table.

* *Limited entry:* A Limited Entry decision table is one for which the column definitions specify value in addition to Pattern, Field, and Operator.
The decision table states, held in the body of the table, are boolean where a positive value (a marked check box) has the effect of meaning the column should apply, or be matched. A negative value (a cleared check box) means the column does not apply.

// This was under "Extended entry", but applies to both. Since we aren't documenting details around these yet, removing for now.
////
It is normal, but not essential, for the range of possible values to be restricted by limiting entry to values from a list.
{CENTRAL} supports use of Java enumerations or decision table "optional value lists" to restrict value entry.
////
