[id='guided-decision-tables-columns-condition-con']
= "Add a Condition"

Conditions represent fact patterns defined in the left ("WHEN") portion of a rule. With this column option, you can define one or more condition columns that check for the presence or absence of data objects with certain field values, and that affect the action ("THEN") portion of the rule. You can define a binding for the fact in the condition table, or select one that has previously been defined. You can also choose to negate the pattern.

Example:

[source,java]
----
when
  $i : IncomeSource( type == "Asset" ) // Binds the IncomeSource object to the $i variable
then
  ...
end
----

[source,java]
----
when
  not IncomeSource( type == "Asset" ) // Negates matching pattern
then
  ...
end
----

After a binding is specified, you can define field constraints. If two or more columns are defined using the same fact pattern binding, the field constraints become composite field constraints on the same pattern. If you define multiple bindings for a single model class, each binding becomes a separate model class in the condition ("WHEN") side of the rule.

.Required column parameters
The following parameters are required in the *Add a new column* wizard to set up this column type:

* *Pattern:* Select from the list of fact patterns already used in conditions in your table or create a new fact pattern. A fact pattern is a combination of an available data object in the package (see the note on xref:required-data-objects[Required data objects] for details) and a model class binding that you specify. (Examples: `LoanApplication [application]` or `IncomeSource [income]` where the bracketed portion is the binding to the given fact type)
* *Entry point:* Define the entry point for the fact pattern, if applicable. An entry point is a gate or stream through which facts enter the {PRODUCT} rule engine, if specified. (Examples: `Application Stream`, `Credit Check Stream`)
* *Calculation type:* Select one of the following calculation types:
** *Literal value:* The value in the cell will be compared with the field using the operator.
** *Formula:* The expression in the cell will be evaluated and then compared with the field.
** *Predicate:* No field is needed; the expression will be evaluated to `true` or `false`.
* *Field:* Select a field from the previously specified fact pattern. The field options are defined in the fact file in the *Data Objects* panel of your project. (Examples: `amount` or `lengthYears` fields within the `LoanApplication` fact type)
* *Binding (optional):* Define a binding for the previously selected field, if needed. (Example: For pattern `LoanApplication [application]`, field `amount`, and operator `equal to`, if binding is set to `$amount`, the end condition will be `application : LoanAppplication($amount : amount == [value])`.)
* *Operator:* Select the operator to be applied to the fact pattern and field previously specified.
* *Value list (optional):* Enter a list of value options, delimited by a comma and space, to limit table input data for the condition ("WHEN") portion of the rule. When this value list is defined, the values will be provided in the table cells for that column as a drop-down list, from which users can select only one option. (Example list: `Monday, Wednesday, Friday` to specify only these three options)
* *Default value (optional):* Select one of the previously defined value options as the default value that will appear in the cell automatically in a new row. If the default value is not specified, the table cell will be blank by default. You can also select a default value from any previously configured data enumerations in the project, listed in the *Enumeration Definitions* panel of the Project Explorer. (You can create enumerations in *Menu* -> *Design* -> *Projects* -> *_[select project]_* -> *Add Asset* -> *Enumeration*.)
* *Header (description):* Add header text for the column.
* *Hide column:* Select this to hide the column, or clear this to display the column.
