[id='interacting-with-processes-delegating-claiming-releasing-tasks-proc']
= Delegating, claiming, and releasing tasks

After tasks are created in {CENTRAL}, you can delegate them to others, claim released tasks, and release your tasks for others to claim. Only users with admin or process-admin permissions can delegate, claim, or release tasks.

[NOTE]
====
In *Task Inbox* page, *Actual Owner* column displays the name of the current owner of the task.
====

[float]
== Delegating a task

.Procedure
. Go to *Menu* -> *Track* -> *Task Inbox*.
. On the *Task Inbox* page, click the task to open it.
. On the task page, click the *Assignments* tab.
. In the *User* field, enter the name of the user or group you want to delegate the task to.
. Click *Delegate*. Once a task is delegated, the owner of the task changes.

[float]
== Claiming a task

.Procedure
. Go to *Menu* -> *Manage* -> *Tasks*.
. On the *Manage Tasks* page, click the task to open it.
. On the *Work* tab of the task page, click *Claim*. Alternatively, on the *Manage Tasks* page, click *Claim* from the three dots in the *Actions* column.
+
The user who claims a task becomes the owner of the task.

[float]
== Releasing a task

.Procedure
. Go to *Menu* -> *Track* -> *Task Inbox*.
. On the *Task Inbox* page, click the task to open it.
. On the task page, click *Release*. A released task has no owner.
