[id='interacting-with-processes-process-instances-advanced-filters-proc']
= Filtering process instances using advanced filters

You can create custom process instance filters using the *Advanced* filters option in {CENTRAL}.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Manage* -> *Process Instances*.
. On the *Manage Process Instances* page, click on *Advanced Filters* icon.
. In the *Advanced Filters* pane, enter the name and description of the filter, and click *Add New*.
. Select an attribute from the *Select column* drop-down list, for example, *processName*. The content of the drop-down changes to *processName != value1*.
. Click the drop-down again and choose the required logical query. For the *processName* attribute, choose *equals to*.
. Change the value of the text field to the name of the process you want to filter.
+
[NOTE]
====
The _processName_ must match the value defined in the business process of the project.
====
+
. Click *Save* and the processes are filtered according to the filter definition.
. Click on the star icon to open the *Saved Filters* pane.
+
In the *Saved Filters* pane, you can view all the saved advanced filters.
