[id='_interacting_with_processes_migrating_process_designer_proc']
= Migrating business processes from new to legacy process designer

You can migrate a business process from the new process designer in {CENTRAL} to the legacy process designer. By default, all business processes open in the new process designer. But once you migrate a business process, it will always open in the legacy designer.

[NOTE]
====
Migrating business processes is an irreversible process.
====

.Procedure
. Log in to {CENTRAL} and go to *Menu* -> *Projects*.
. From *Assets* tab, select the business process. It will open in the new process designer.
. Click *Migrate* and a warning will appear.
. Click *Migrate Diagram*.
+
The process designer will restart and the business process will re-open in the legacy process designer.

*Migrating* a business process will result in two changes:

* The name of the business process in the process designer will change, for example,

** Naming convention in new process designer - business-process-name.bpmn - Business Processes

** Naming convention in legacy process designer - business-process-name.bpmn2 - Business Processes (legacy)

* The extension of the business process will change from *.bpmn to *.bpmn2.
