[id='interacting-with-processes-starting-stopping-tasks-proc']
= Starting and stopping tasks

You can start and stop user tasks from the *Tasks* and *Task Inbox* page.

[NOTE]
====
Ensure that you are logged in and have appropriate permissions for starting and stopping tasks.
====

[float]
== Starting a task

.Procedure
. Go to *Menu* -> *Track* -> *Task Inbox*.
. On the *Task Inbox* page, click the task to open it.
. On the *Work* tab of the task page, click *Start*. Once you start a task, its status changes to *InProgress*.
+
You can view the status of tasks on the *Task Inbox* as well as on the *Manage Tasks* page.

[NOTE]
====
Only users with process-admin role can view the task list on the *Manage Tasks* page. Though admin role users can also access the page but they will always see an empty task list unless an additional role permission setup is performed on the Process Server.
====

[float]
== Stopping a task

.Procedure
. Go to *Menu* -> *Track* -> *Task Inbox*.
. On the *Task Inbox* page, click the task to open it.
. On the *Work* tab of the task page, click *Complete*.
