[id='kie_bases_create_con']

= Defining KIE Bases and Sessions

A _KIE base_ contains rules, processes, functions, and type models. A KIE base does not contain runtime data, instead sessions are created from the KIE base into which data can be inserted and process instances started.

A _KIE session_ stores runtime data created from a KIE base. For more information, see {URL_DEVELOPMENT_GUIDE}#sect_kie_sessions[KIE Sessions] of the _{DEVELOPMENT_GUIDE}_.

You can define KIE bases and sessions by editing the `kmodule.xml` file in the *Project View* of the project.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name. For example, *Evaluation*.
. Click *Settings* -> *Project Settings: Project General Settings* -> *Knowledge bases and sessions*. This view provides a user interface for changing `kmodule.xml`.
. Click *Add* to define and add your bases.
.. After you enter a name for your Knowledge Base, add Packages. For including all packages, click *Add* below *Packages* and enter asterisk `*`.
. Below *Knowledge Sessions*, click *Add* and enter the name of your session.
. Mark it `Default` and select appropriate state. For Red Hat JBoss BPM Suite, use `stateful` sessions.
. Click *Save*, then click *Save* to confirm your changes.
