[id='maven-external-configure-proc_{context}']
= Configuring an external Maven repository for {CENTRAL} and {KIE_SERVER}

You can configure {CENTRAL} and {KIE_SERVER} to use an external Maven repository instead of the built-in repository. In this case, all built project KJAR files are pushed into this repository. You can progress these files through the repository as necessary to implement your integration process.

IMPORTANT: Using an external Maven repository with {CENTRAL} deployed on OpenShift is not supported. Using an external Maven repository with {KIE_SERVER} deployed on OpenShift is supported but differs from this procedure. For more information, see {URL_DM_ON_OPENSHIFT}[_{DM_ON_OPENSHIFT}_].

//@link: Update PAM on OpenShift link above.

.Prerequisite
{CENTRAL} and {KIE_SERVER} are installed. For installation options, see Planning a {PRODUCT} installation.
//@link: Add installation planning link.

.Procedure
. Create a Maven `settings.xml` file with connection and access details for your external repository. For details about the `settings.xml` file, see the Maven link:https://maven.apache.org/settings.html[Settings Reference].
. Save the file in a known location, for example, `/opt/custom-config/settings.xml`.
. In your {PRODUCT} installation directory, navigate to the `standalone.xml` file. For example, if you use a {EAP} installation for {PRODUCT}, go to `$EAP_HOME/standalone/configuration/standalone.xml`.
. Open `standalone.xml` and under the under the `<system-properties>` tag, set the `kie.maven.settings.custom` property to the full path name of the `settings.xml` file.
+
For example:
+
[source,xml]
----
<property name="kie.maven.settings.custom" value="/opt/custom-config/settings.xml"/>
----
+
. Start or restart {CENTRAL} and {KIE_SERVER}.
