[[_organizational_unit_REST_create_proc]]

= ⁠⁠Creating an Organizational Unit Using the Knowledge Store REST API

{PRODUCT} supports several REST APIs for individual application components. With the Knowledge Store REST API, you can make API calls to create (`POST`) organizational units in {PRODUCT}.

.Prerequisite
You have `rest-all` role permissions for Business Central, as described in the {URL_INSTALLATION_GUIDE}#users_create_proc[_{INSTALLATION_GUIDE}_].

.Procedure
Issue a `POST` API request to `/organizationalunits/` in the Knowledge Store REST API. This creates an organizational unit in the Knowledge Store. The organizational unit is defined as a JSON entity. The call requires an `OrganizationalUnit` instance and returns a `CreateOrganizationalUnitRequest` instance.

Example curl `POST` request:

[source]
----
curl -X POST 'localhost:8080/business-central/rest/organizationalunits/' -u USERNAME:PASSWORD -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{"name":"testgroup","owner":"tester","description":null,"repositories":["testGroupRepository"]}'
----

Example JSON entity containing details of an organizational unit to be created:

[source]
----
{
	"name"         : "testgroup",
	"owner"        : "tester",
	"description"  :  null,
	"repositories" :  ["testGroupRepository"]
}
----

For more details, see {URL_DEVELOPMENT_GUIDE}#organizational_unit_calls[Organizational Unit Calls] in the  _{DEVELOPMENT_GUIDE}_.
