[id='_project_REST_create_proc']

= ⁠⁠Creating a Project Using the Knowledge Store REST API

{PRODUCT} supports several REST APIs for individual application components. With the Knowledge Store REST API, you can make API calls to create (`POST`) projects in {PRODUCT}.

.Prerequisite
You have `rest-all` role permissions for {CENTRAL}, as described in the {URL_INSTALLATION_GUIDE}#users_create_proc[_{INSTALLATION_GUIDE}_].

.Procedure
Issue a `POST` API request to `/projects/` for a new project in the Knowledge Store REST API. This creates a project for the specified organizational unit in the Knowledge Store. The project is defined as a JSON entity. The call requires an `Entity` instance and returns a `CreateProjectRequest` instance.

Example curl `POST` request:

[source]
----
curl -X POST 'localhost:8080/business-central/rest/repositories/REPOSITORY_NAME/projects/' -u USERNAME:PASSWORD -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{"name":"MortgageProject","description":null,"groupId":"org.mycompany.commons","version":"2.1.1"}'
----

Example JSON entity containing details of a project to be created:

[source]
----
{
	"name"        : "Evaluation",
	"description" :  null,
	"groupId"     : "org.mycompany.commons",
	"version"     : "2.1.1"
}
----

For more details, see {URL_DEVELOPMENT_GUIDE}#sect_knowledge_store_rest_api[Knowledge Store REST API] in the  _{DEVELOPMENT_GUIDE}_.
