[id='project-gav-setting-proc_{context}']
= Setting the Group ID, Artifact ID, and Version (GAV) values in a project

The GAV values are the identifier for the project in a Maven repository. In any deployment method, the project containing your developed business assets is identified by the GAV. If you build a new version of your project without changing the GAV values, the old version of the project is displaced in the Maven repository and on any {KIE_SERVERS}. However, if you change any value in the GAV (usually the version), the result is seen as a different artifact and can exist alongside the old version.

When developing a decision service in {CENTRAL}, you can set the GAV in the project *Settings* screen.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name.
+
Alternatively, click *Add Project* to create a new project.
. Click the project *Settings* tab.
. In *General Settings*, modify the *Group ID*, *Artifact ID*, or *Version* fields as necessary. If you have deployed the project and are developing a new version, usually you need to increase the version number.
. Click *Save* to finish.
