[id='project-gav-setting-proc_{context}']
= Setting the Group ID, Artifact ID, and Version (GAV) values in a project

The GAV values identify the project in a Maven repository. If you build a new version of your project without changing the GAV values, the project might not be updated in the Maven repository or on any {KIE_SERVERS}; the new project version might also displace an old version of the project. However, if you change any value in the GAV (usually the version), the result is seen as a different artifact and can exist alongside the old version.

You can set the GAV values in the project *Settings* screen.

.Procedure
. In {CENTRAL}, go to *Menu* -> *Design* -> *Projects* and click the project name.
+
Alternatively, click *Add Project* to create a new project.
. Click the project *Settings* tab.
. In *General Settings*, modify the *Group ID*, *Artifact ID*, or *Version* fields as necessary. If you have deployed the project and are developing a new version, usually you need to increase the version number.
. Click *Save* to finish.
