[id='project-deploying-maven-con_{context}']
= Using an external Maven repository to deploy a project

You can use an external Maven repository (for example, Nexus) to set up an integration process. You can configure {CENTRAL} to push project files into the external repository instead of the built-in repository. You can still use {CENTRAL} to deploy projects on a test {KIE_SERVER}. However, in this process, other {KIE_SERVERS} (for example, staging and production) are not connected to {CENTRAL}. Instead, they retrieve the project KJAR files and any necessary dependencies from your Maven repository. You can progress the KJAR versions through your repository as necessary, in line with the integration process that you want to implement.

When you set up a {KIE_SERVER}, you can configure access to a Maven repository and then you can use the REST API of the server to load and start a KIE container (deployment unit) with the services from the project. If you deploy a {KIE_SERVER} on OpenShift, you can configure it to load and start a service from a Maven repository automatically. A Maven project and a Java client library for automating the API calls are available.
