[[_repository_REST_clone_proc]]

= Cloning a Repository Using the Knowledge Store REST API

{PRODUCT} supports several REST APIs for individual application components. With the Knowledge Store REST API, you can make API calls to clone (`POST`) repositories in {PRODUCT}.

.Prerequisite
You have `rest-all` role permissions for Business Central, as described in the {URL_INSTALLATION_GUIDE}#users_create_proc[_{INSTALLATION_GUIDE}_].

.Procedure
Issue a `POST` API request to `/repositories/` for a cloned repository in the Knowledge Store REST API. The request is the same as the request for a new repository, except that you set `requestType` to `clone` instead of `create`. This clones an existing repository for the specified organizational unit in the Knowledge Store. The organizational unit is defined as a JSON entity. The call requires an `RepositoryRequest` instance and returns a `CreateOrCloneRepositoryRequest` instance.

Example curl `POST` request:

[source]
----
curl -X POST 'localhost:8080/business-central/rest/repositories/' -u USERNAME:PASSWORD -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{"name":"myClonedRepository","description":null,"requestType":"clone","gitURL":"git://localhost/example-repository","organizationalUnitName":"testGroup"}'
----

Example JSON entity containing details of a repository to be cloned:

[source]
----
{
  "name": "myClonedRepository",
  "organizationalUnitName": "testGroup",
  "description": "",
  "userName": "",
  "password": "",
  "requestType": "clone",
  "gitURL": "git://localhost/example-repository"
}
----

For more details, see {URL_DEVELOPMENT_GUIDE}#repository_calls[Repository Calls] in the  _{DEVELOPMENT_GUIDE}_.
