[id='service-packaging-con_{context}']
= Packaging decision services

A decision service is always packaged into a _KJAR file_. This file is a version of a Java JAR file. A {KIE_SERVER} runs the service from its KJAR file. However, you never need to work with KJAR files directly.

Instead, {PRODUCT} stores KJAR files in _Maven repositories_. Maven is a comprehensive system for automating Java package lifecycle and dependency management. Among other features, Maven supports a repository system where JAR files (including KJAR files) can be uploaded and downloaded.

In Maven, a KJAR file is not identified by its name, but instead using the following three values: `GroupId`, `ArtifactId`, and `Version` (GAV). Normally, the Group ID is the identifier for a project and the Artifact ID identifies a particular artifact (for example, a decision service) within the project. The Version value must be unique for every new version that might need to be deployed.

To identify an artifact (including a KJAR file) in Maven, you need all three of these variables. This set of information is often named GAV (for Group, Artifact, Version).

When developing a decision service in {CENTRAL}, you can set the GAV in the project settings screen.
