[id='using-standalone-perspectives-standalone-editor-proc']
= Using standalone editor perspective

You can use the standalone editor perspective of {CENTRAL} to access an asset's specific editor. By using this perspective, you can open an asset's editor and can modify the asset as required.

The web link for accessing an asset's standalone editor perspective contains the `standalone` and `path` parameters. The `path` parameter must contain the complete path to the asset and then link must end with `_#StandaloneEditorPerspective_` string. Also, by varying the `path` parameter, you can access a specific asset's editor in the standalone mode.

.Procedure
. Login to {CENTRAL}.
. In a web browser, enter the appropriate link as required, for example,

.. For editing a process:
+
`http://localhost:8080/business-central/kie-wb.jsp?standalone&path=default://master@MySpace/Shop/src/main/resources/com/purchase.bpmn#StandaloneEditorPerspective`
+
This will open the _Process Designer_ in the standalone editor perspective.
+

.. For editing a form:
+
`http://localhost:8080/business-central/kie-wb.jsp?standalone&path=default://master@MySpace/Shop/src/main/resources/com/mortgage_app/Applicant.frm#StandaloneEditorPerspective`
+
This will open the _Form Modeler_ in the standalone editor perspective.
