[id='er-contracts-proc']
= Entering the list of contracts

You must enter the list of all of the types of contracts that the business uses for employees.

A contract determines the maximum time that the employee can work in a day, calendar week, calendar month, or calendar year.

When creating a contract, you can set any of the limitations or none at all. For example, a part-time employee might not be allowed to work more than 20 hours in a week, while a full-time employee might be limited to 10 hours in a day and 1800 hours is a year. Another contract might include no limitations on worked hours.

You must enter all work time limits for contracts in minutes.

.Procedure

. To enter or change the list of contracts in the Optaweb employee rostering application web interface, click the *Contracts* tab.
+
You can see the numbers of currently visible contracts in the top right part of the browser window, for example, `1-15 of 34`. You can use the *<* and *>* buttons to display other contracts in the list.
+
You can enter any part of an contract name in the *Search* box to search for contracts.
+
. Complete the following steps to add a new contract:
.. Click *Add Contract*.
.. Enter the name of the contract in the text field under *Name*.
.. Enter the required time limits under *Maximum minutes*:
*** If the employee must not work more than a set time per day, enable the check box at *Per Day* and enter the amount of minutes in the field next to this check box.
*** If the employee must not work more than a set time per calendar week, enable the check box at *Per Week* and enter the amount of minutes in the field next to this check box.
*** If the employee must not work more than a set time per calendar month, enable the check box at *Per Month* and enter the amount of minutes in the field next to this check box.
*** If the employee must not work more than a set time per calendar year, enable the check box at *Per Year* and enter the amount of minutes in the field next to this check box.
+
.. Click *Save*.
+
. To edit the name and time limits for an contract, click the *Edit Contract* icon (pencil shape) next to the name of the contract.
. To delete an contract, click the *Delete Contract* icon (trashcan shape) next to the name of the contract.

NOTE: Within each tenant, contract names must be unique. You cannot delete contracts if they are rostered to any shifts.
