[id='er-deploy-script-proc']
= Deploying the application using the provided script

You can deploy the Employee Rostering starter application to {OPENSHIFT} using the provided script. The script builds and packages the application source code locally and uploads it to the OpenShift environment for deployment.

.Prerequisites
* You are logged in to the target OpenShift environment using the `oc` command line tool. For more information about this tool, see the https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html-single/cli_reference/[_OpenShift Container Platform CLI Reference_].
* OpenJDK {OPTAPLANNER_JDK_VERSION} or later is installed. Red Hat build of Open JDK is available from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required).
* Apache Maven {OPTAPLANNER_MAVEN_VERSION} or higher is installed. Maven is available from the https://maven.apache.org/[Apache Maven Project] website.

* A `bash` shell environment is available on your local system.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* Product: {PRODUCT_SHORT}
* Version: {PRODUCT_VERSION_LONG}
. Download the *{PRODUCT} {PRODUCT_VERSION} Maven Repository Kogito and {PLANNER_SHORT} 8 Maven Repository* (`{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-maven-repository.zip`) file.
. Extract the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-maven-repository.zip` file.
. Copy the contents of the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-maven-repository/maven-repository` subdirectory into the `~/.m2/repository` directory.
. Download the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-decision-services-quickstarts.zip` file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.
. Extract the downloaded archive.
. Navigate to the `optaweb-employee-rostering` folder.
. To build the Employee Rostering application, run the following command:
+
[source]
----
mvn clean install -DskipTests -DskipITs
----
. Log in to an OpenShift account or a Red Hat Code Ready Container instance. In the following example, `<account-url>` is the URL for an OpenShift account or Red Hat Code Ready Container instance and `<login-token>` is the login token for that account:
+
[source]
----
oc login <account-url> --token <login-token>
----
. Create a new project to host Employee Rostering:
+
[source]
----
oc new-project optaweb-employee-rostering
----
. Run the provision script to build and deploy the application:
+
[source]
----
./runOnOpenShift.sh
----
+
Compilation and packaging might take up to 10 minutes to complete. These processes continually show progress on the command line output.
+
When the operation completes, the following message is displayed, where `<URL>` is the URL for the deployment:
+
[source]
----
You can access the application at <URL> once the deployment is done.
----
. Enter the URL that you used earlier in the procedure, for either an OpenShift account or Red Hat Code Ready Container instance, to access the deployed application. The first startup can take up to a minute because additional building is completed on the OpenShift platform.
+
[NOTE]
====
If the application does not open a minute after clicking the link, perform a hard refresh of your browser page.
====
