[id='er-deploy-prepare-proc']
= Preparing deployment files

You must download and prepare the deployment files before building and deploying the application.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:

* Product: {PRODUCT_SHORT}
* Version: {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION} Decision Services Quick Starts* (`kogito-1.5.0-decision-services-quickstarts.zip`).
. Download *{PRODUCT} {PRODUCT_VERSION} Maven Repository Kogito and {PLANNER_SHORT} 8 Maven Repository* (`kogito-1.5.0-maven-repository.zip`).
. Extract the `kogito-1.5.0-maven-repository.zip` file.
. Copy the contents of the `kogito-1.5.0.GA-maven-repository/maven-repository` subdirectory into the `~/.m2/repository` directory.
. Extract the `kogito-1.5.0-decision-services-quickstarts.zip` file.
. Navigate to the `optaweb-{OPTAPLANNER_BOM_VERSION}/optaweb-employee-rostering` directory. This folder is the base folder in subsequent parts of this document.
+
[NOTE]
====
File and folder names might have higher version numbers than specifically noted in this document.
====
