[id='er-deploy-script-proc']
= Deploying the application using the provided script

You can deploy the {PLANNER} Employee Rostering starter application to {OPENSHIFT} using the provided script. The script builds and packages the application source code locally and uploads it to the OpenShift environment for deployment.  

.Prerequisites
* You must be logged in to the target OpenShift environment using the `oc` command line tool. For more information about this tool, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.10/html-single/cli_reference/[CLI Reference].
. Java Development Kit and Maven must be installed on your local machine. 
. A `bash` shell environment must be available on your local machine.

.Procedure
. Download the `{PRODUCT_FILE}-add-ons.zip` file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page for {PRODUCT} {PRODUCT_VERSION}.
. Unzip the downloaded archive.
. Unzip the employee rostering zip file (`{PRODUCT_FILE}-employee-rostering.zip`) that is extracted from the add-ons archive.
. Using the command line, change to the `optashift-employee-rostering-{MAVEN_ARTIFACT_VERSION}/sources` folder.
. Run the provision script to build and deploy the application:
+
[source]
----
./provision.sh setup employee-rostering --binary
----
+
[NOTE]
====
If the current OpenShift user name contains characters that are not letters or numbers, the deployment might fail. You can resolve this issue by providing an additional parameter: `./provision.sh setup employee-rostering --binary --project-suffix optaweb`.  This example uses "optaweb", but you can use any value for the suffix.
====
+
Compilation and packaging might take several minutes to complete. They  continually show progress on the command line output.
+
When the operation is completed, the following message is displayed: `Uploading file "target/ROOT.war" as binary input for the build ...`.
. Use the OpenShift web UI to view the details for the deployed application. Click the link in the *Routes* section to open the starter application. The first startup can take up to a minute as additional building is completed on the OpenShift platform. 
[NOTE]
====
If the application does not open for more than a minute after clicking the link, perform a hard refresh of your browser page.
====
. Optionally, you can use other actions provided by the provision script:
.. Deploy updates to the code to an existing deployment: 
[source,bash]
----
./provision.sh deploy employee-rostering --binary
----
+
.. Remove the application: 
[source,bash]
----
./provision.sh delete employee-rostering
----
