[id='er-deploy-template-proc']
= Deploying the OpenShift template

You can deploy an OpenShift template to create an environment running the Employee Rostering starting application.

.Procedure
. Download the `rhdm-{PRODUCT_VERSION_LONG}-openshift-templates.zip` file from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=rhdm&productChanged=yes[Software Downloads] page for Red Hat Decision Manager {PRODUCT_VERSION}.
. Unzip the downloaded archive and locate the `rhdm{ENTERPRISE_VERSION_SHORT}-optaweb-employee-rostering.yaml` file.
. Use one of the following methods to deploy the template:
* In the OpenShift Web UI, select *Add to Project -> Import YAML / JSON* and then select or paste the `rhdm{ENTERPRISE_VERSION_SHORT}-optaweb-employee-rostering.yaml` file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
* To use the OpenShift command line console, prepare the following command line:
+
[subs="attributes,verbatim,macros"]
----
oc new-app -f <template-path>/rhdm{ENTERPRISE_VERSION_SHORT}-optaweb-employee-rostering.yaml -p OPTAWEB_HTTPS_SECRET=optaweb-employee-rostering-app-secret
----
+
In this command line:
+
** Replace `<template-path>` with the path to the downloaded template file.
** Add as many `-p PARAMETER=value` pairs as needed to set the required parameters. You can view the template file to see descriptions for all parameters.
+
. Set the following parameters as necessary:
+
** *KIE Server Keystore Secret Name* (`OPTAWEB_HTTPS_SECRET`): The name of the secret for HTTPS connections, as created in <<secrets-employeerostering-create-proc>>.
** *Application Name* (`APPLICATION_NAME`): The name of the OpenShift application. It is used in the default URL for the application.
** *OptaWeb Admin User* (`OPTAWEB_ADMIN_USER`): The user name for the administrative user in the application. The default user name is `adminUser`.
** *OptaWeb Admin Password* (`OPTAWEB_ADMIN_PWD`): The password for the administrative user in the application. The default password is `RedHat`.
** *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`): The namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-er-proc>>), the namespace is `openshift`. If you installed the image streams file, the namespace is the name of the OpenShift project.
** *Optaweb Employee Rostering Container Memory Limit* (`OPTAWEB_MEMORY_LIMIT`): The memory limit for the application container. The higher the limit, the more employees and shifts are supported. The default is 1 Gi.
** *Optaweb Employee Rostering Generator Zone ID* (`OPTAWEB_GENERATOR_ZONE_ID`): The time zone that is set in the generated example data sets in the application. The default is the local time zone of the OpenShift server.
. Complete the creation of the environment, depending on the method that you are using:
* In the OpenShift Web UI, click *Create*.
** If the `This will create resources that may have security or project behavior implications` pop-up message is displayed, click *Create Anyway*.
* Complete and run the command line.
