[id='er-deploy-script-proc']
= Deploying the application using the provided script

You can deploy the Employee Rostering starter application to {OPENSHIFT} using the provided script. The script builds and packages the application source code locally and uploads it to the OpenShift environment for deployment.

.Prerequisites
* You are logged in to the target OpenShift environment using the `oc` command line tool. For more information about this tool, see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html-single/cli_reference/[CLI Reference].
* Maven and a Java Development Kit are installed on your local system.
* A `bash` shell environment is available on your local system.

.Procedure
. Download the `kogito-1.5.0-maven-repository.zip` file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.
. Expand the downloaded archive.
. Copy the contents of the `kogito-1.5.0.GA-maven-repository/maven-repository` subdirectory into the `~/.m2/repository` directory.
. Download the `kogito-1.5.0-decision-services-quickstarts.zip` file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.
. Extract the downloaded archive.
. Navigate to the `optaweb-employee-rostering` folder.
. To build the Employee Rostering application, run the following command:
+
[source]
----
mvn clean install -DskipTests -DskipITs
----
. Log in to an OpenShift account or a Red Hat Code Ready Container instance. In the following example, `<account-url>` is the URL for an OpenShift account or Red Hat Code Ready Container instance and `<login-token>` is the login token for that account:
+
[source]
----
oc login <account-url> --token <login-token>
----
. Create a new project to host Employee Rostering:
+
[source]
----
oc new-project optaweb-employee-rostering
----
. Run the provision script to build and deploy the application:
+
[source]
----
./provision.sh
----
+
Compilation and packaging might take up to 10 minutes to complete. These processes continually show progress on the command line output.
+
When the operation completes, the following message is displayed, where `<URL>` is the URL for the deployment:
+
[source]
----
You can access the application at <URL> once the deployment is done.
----
. Enter the URL that you used earlier in the procedure, for either an OpenShift account or Red Hat Code Ready Container instance, to access the deployed application. The first startup can take up to a minute because additional building is completed on the OpenShift platform.
+
[NOTE]
====
If the application does not open a minute after clicking the link, perform a hard refresh of your browser page.
====
