[id='er-rotation-edit-proc']
= Viewing and editing the rotation pattern
The rotation pattern enables you to add, move, and delete shifts so you can manage your employee resources efficiently.

The rotation pattern is defined by time buckets and seats. A time bucket describes a particular time slot, for example  9:00 a.m. to 5:00 p.m., for a particular spot, for example Airport South, and any skills that are required, for example firearm training.

A seat is an employee assignment for a particular day in a specific time bucket.

A stub list is a list of employees available to be assigned to a time bucket.

For more information about the rotation pattern, see <<er-rotation-con>>.

.Procedure
. To view and edit the rotation pattern in the Employee Rostering application web interface, click the *Rotation* tab.
. Select a spot form the *Rotation* menu.
. To add a time bucket, click *Add New Time Bucket*. The *Creating Working Time Bucket* dialog appears.
. Specify a start and end time, select any additional required skills, select the days for this time bucket, and click *Save*. The time bucket appears on the *Rotation* page.
. To create an employee stub list to add employees to the rotation, click *Edit Employee Stub List*.
. In the *Edit Employee Stub List* dialog, click *Add Employee* and select an employee from the list.
. Add all of the employees required for this stub list and click *Save*. The employees appear above the time buckets on the *Rotation* page.
. Drag an employee to a time bucket. The time bucket is populated with the employee icon.
+
NOTE: A time bucket can only have one employee assigned to it for each day. To add multiple employees to the same time bucket, copy the time bucket and change the employee name as required.
. To save the changes, click *Apply*.
. To provision the schedule, click *Scheduling* and select the spot that you created the rotation for.
. Click *Provision* and specify the date range.
. Deselect the spots that you do not want to include in this schedule.
. Click the arrow next to the selected spot and deselect any time buckets that you do not want to use in your schedule.
. Click *Provision Shifts*. The calendar is populated with the time buckets.
. Click a time bucket on the calendar to edit that time bucket.
