[id='optashift-ER-building-commandline-db-proc']
= Building and running the employee rostering starter application with persistent data storage from the command line

If you use the command line to build the employee rostering starter application and run it, you can provide a database server for persistent data storage.

.Prerequisites
* You have prepared the deployment files as described in <<er-deploy-prepare-proc>>.
* A Java Development Kit is installed.
* Maven is installed.
* The host has access to the Internet. The build process uses the Internet for downloading Maven packages from external repositories.
* You have a deployed MySQL or PostrgeSQL database server.


.Procedure
. In a command terminal, navigate to the `optaweb-employee-rostering-standalone/target` directory.
. Enter the following command to run the Employee Rostering JAR file:
+
[source,bash]
----
java \
-Dquarkus.datasource.username=<DATABASE_USER> \
-Dquarkus.datasource.password=<DATABASE_PASSWORD> \
-Dquarkus.datasource.jdbc.url=<DATABASE_URL> \
-jar quarkus-app/quarkus-run.jar
----
+
In this example, replace the following placeholders:

* `<DATABASE_URL>`: URL to connect to the database
* `<DATABASE_USER>`: The user to connect to the database
* `<DATABASE_PASSWORD>`: The password for `<DATABASE_USER>`

[NOTE]
======
The value of the `quarkus.datasource.db-kind` parameter is set to `H2` by default at build time. To use a different database, you must rebuild the standalone module and specify the database type on the command line. For example, to use a PostgreSQL database, enter the following command:

`mvn clean install -DskipTests -Dquarkus.profile=postgres`

======
