[id='optashift-ER-building-commandline-db-proc']
= Building and running the employee rostering starter application with persistent data storage from the command line

If you use the command line to build the employee rostering starter application and run it, you can provide a database server for persistent data storage.

.Prerequisites
* You prepared the deployment files as described in <<er-deploy-prepare-proc>>.
* A Java Development Kit is installed.
* Maven is installed.
* The host has access to the Internet. The build process uses the Internet for downloading Maven packages from external repositories.
* You have a deployed WildFly or {EAP} application server and a deployed MySQL or PostrgeSQL database server.
* You have set up a JDBC data source in the application server for the database server.

.Procedure
. In a terminal window, change to the `sources` directory.
. Run the following command:
+
[source,bash]
----
mvn clean install -Dproductized -Dorg.optaweb.employeerostering.persistence.datasource=<dsname> -Dorg.optaweb.employeerostering.persistence.dialect=<dialect>
----
+
In the preceding command, replace the following values:
+
** _<dsname>_ with the name of the data source in the application server.
** _<dialect>_ with one of the following strings, depending on the type of database server:
*** For MySQL, `org.hibernate.dialect.MySQL5Dialect`
*** For PostgreSQL, `org.hibernate.dialect.PostgreSQLDialect`
+
. Wait for the build process to complete.
. Deploy the `optaweb-employee-rostering-webapp/target/optaweb-employee-rostering-{MAVEN_ARTIFACT_VERSION}.war` directory into the application server and start the application server.
. To access the application, enter http://localhost:8080/gwtui/gwtui.html in a web browser.
