[id='optashift-ER-running-jar-proc']
= Running the Employee Rostering starter application JAR file
You can run the Employee Rostering starter application from a JAR file included in the reference implementation download.

.Prerequisites
* You have downloaded and extracted the `{PRODUCT_FILE}-reference-implementation.zip` file as described in <<er-deploy-prepare-proc>>.
* A Java Development Kit is installed.
* Maven is installed.
* The host has access to the Internet. The build process uses the Internet for downloading Maven packages from external repositories.

.Procedure
. In a terminal window, change to the `sources` directory.
. Enter the following command:
+
[source,bash]
----
mvn clean install
----
+
. Wait for the build process to complete.
. Navigate to the`employee-rostering-distribution/target/` directory.
. Enter the following command to run the Employee Rostering JAR file:
+
[source,bash]
----
run employee-rostering-distribution-STAR.jar
----
. To access the application, enter `http://localhost:8080/` in a web browser.
. To stop the Employee Rostering application, enter the following command:
+
[source,bash]
----
mvn -N wildfly:shutdown
----
