[id='optashift-ER-building-commandline-proc']
= Building and running the Employee Rostering starter application using Maven
You can use the command line to build and run the employee rostering starter application.

If you use this procedure, the data is stored in memory and is lost when the server is stopped. To build and run the application with a database server for persistent storage, see <<optashift-ER-building-commandline-db-proc>>.

.Prerequisites
* You have prepared the deployment files as described in <<er-deploy-prepare-proc>>.
* A Java Development Kit is installed.
* Maven is installed.
* The host has access to the Internet. The build process uses the Internet for downloading Maven packages from external repositories.

.Procedure
. Navigate to the `optaweb-employee-rostering-backend` directory.
. Enter the following command:
+
[source,bash]
----
mvn quarkus:dev
----
. Navigate to the `optaweb-employee-rostering-frontend` directory.
. Enter the following command:
+
[source,bash]
----
npm start
----
+
[NOTE]
====
If you use `npm` to start the server, `npm` monitors code changes.
====
+

. To access the application, enter `\http://localhost:3000/` in a web browser.
