[id='optashift-ER-building-commandline-db-proc']
= Building and running the employee rostering starter application with persistent data storage from the command line

If you use the command line to build the employee rostering starter application and run it, you can provide a database server for persistent data storage.

.Prerequisites
* You prepared the deployment files as described in <<er-deploy-prepare-proc>>.
* A Java Development Kit is installed.
* Maven is installed.
* The host has access to the Internet. The build process uses the Internet for downloading Maven packages from external repositories.
* You have a deployed MySQL or PostrgeSQL database server.


.Procedure
. In a terminal window, navigate to the`employee-rostering-distribution/target/` directory.
. Enter the following command to run the Employee Rostering JAR file:
+
[source,bash]
----
java -jar employee-rostering-distribution-*-exec.jar --spring.datasource.url=${<DATABASE_URL>} --spring.datasource.username=${<DATABASE_USER>} --spring.datasource.password=${<DATABASE_PASSWORD>}
----
+
In this example, replace the following placeholders:

* Replace `<DATABASE_URL>` with the URL to connect to the database, for example `jdbc:postgresql://postgresql:5432/MY_DATABASE`.
* Replace `<DATABASE_USER>` with the user to connect to the database.
* Replace `<DATABASE_PASSWORD>` with the password for `<DATABASE_USER>`.
