[id='optashift-ER-running-jar-proc']
= Running the Employee Rostering starter application JAR file
You can run the Employee Rostering starter application from a JAR file included in the *{PRODUCT_PAM} {PRODUCT_VERSION_LONG} Kogito and OptaPlanner 8 Decision Services Quickstarts* download.

.Prerequisites
* You have downloaded and extracted the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts.zip` file as described in <<er-deploy-prepare-proc>>.
* A Java Development Kit is installed.
* Maven is installed.
* The host has access to the Internet. The build process uses the Internet for downloading Maven packages from external repositories.

.Procedure
. In a command terminal, change to the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts/optaweb-{OPTAPLANNER_BOM_VERSION}/optaweb-employee-rostering` directory.
. Enter the following command:
+
[source,bash]
----
mvn clean install -DskipTests
----
+
. Wait for the build process to complete.
. Navigate to the `{PRODUCT_INIT}-{PRODUCT_VERSION_LONG}-kogito-and-optaplanner-quickstarts/optaweb-{OPTAPLANNER_BOM_VERSION}/optaweb-employee-rostering/optaweb-employee-rostering-standalone/target` directory.
. Enter the following command to run the Employee Rostering JAR file:
+
[source,xml,subs="attributes+"]
----
java -jar quarkus-app/quarkus-run.jar
----
+
[NOTE]
======
The value of the `quarkus.datasource.db-kind` parameter is set to `H2` by default at build time. To use a different database, you must rebuild the standalone module and specify the database type on the command line. For example, to use a PostgreSQL database, enter the following command:

`mvn clean install -DskipTests -Dquarkus.profile=postgres`
======
. To access the application, enter `\http://localhost:8080/` in a web browser.
