[id='optashift-ER-modifying-sample-weekend-proc']
= Sample modification: do not make employees work two weekends in a row  
With this sample modification, the employee rostering starter application does not place people on a roster for two weekends in a row. If a person is rostered for a Saturday or Sunday shift, the next Saturday and Sunday are guaranteed to be free. 

The new rule relies on the information that is already available in the application. No changes to data structures or to the user interface are required. It is an example of a simple change in the starter application.

You can review the full change and apply it by using the ??? patch file, available from ???

.Procedure

. Add the determination of whether the shift is a weekend shift to the `src/main/java/org/optaweb/employeerostering/shared/shift/Shift.java` class of the `employee-rostering-shared` package. Add the following method:
+
[source,java]
----
public boolean onWeekend() {
    return startDateTime.getDayOfWeek().equals(DayOfWeek.SATURDAY) || startDateTime.getDayOfWeek().equals(DayOfWeek.SUNDAY)
    || endDateTime.getDayOfWeek().equals(DayOfWeek.SATURDAY) ||endDateTime.getDayOfWeek().equals(DayOfWeek.SUNDAY);
}
----
+
[NOTE]
====
You can modify this method to hardcode public holidays as weekend days.
====
+
. In the `src/main/resources/org/optaplanner/openshift/employeerostering/server/solver/employeeRosteringScoreRules.drl` file of the `optashift-employee-rostering-shared` module, add a rule that triggers a hard constraint if there are two shifts for the same employee, both are on weekends, and less than 9 days have passed between them.
+
[source,java]
----
rule "No weekends closer than 9 days apart"
when Shift($e : employee,
                     $endDateTime : endDateTime,
                    onWeekend())
           Shift(employee == $e,
                    onWeekend(),
                    Duration.between($endDateTime,startDateTime).toDays() >= 9)
then
                    scoreHolder.addHardConstraintMatch(kcontext, -50);
----
