[id='wb-employee-rostering-data-model-proc']
= Creating the data model for the employee rostering project

Use this section to create the data objects required to run the employee rostering sample project in {CENTRAL}.

.Prerequisite
You have completed the project set up described in <<wb-employee-rostering-example-setup-proc>>.

.Procedure
. With your new project, either click *Data Object* in the project perspective, or click *Add Asset* -> *Data Object* to create a new data object.
. Name the first data object `Timeslot`, and select `employeerostering.employeerostering` as the *Package*.
+
Click *Ok*.
. In the *Data Objects* perspective, click *+add field* to add fields to the `Timeslot` data object.
. In the *id* field, type `endTime`.
. Click the drop-down menu next to *Type* and select `LocalDateTime`.
. Click *Create and continue* to add another field.
. Add another field with the *id* `startTime` and *Type* `LocalDateTime`.
. Click *Create*.
. Click *Save* in the upper-right corner to save the `Timeslot` data object.
. Click the *x* in the upper-right corner to close the *Data Objects* perspective and return to the *Assets* menu.
. Using the previous steps, create the following data objects and their attributes:
+
.Skill
[cols="1.1",options="header"]
|===
| id | Type
| `name` | `String`
|===
+
.Employee
[cols="1.1",options="header"]
|===
| id | Type
| `name` | `String`
| `skills` | `employeerostering.employeerostering.Skill[List]`
|===
+
.Shift
[cols="1.1",options="header"]
|===
| id | Type
| `requiredSkill` | `employeerostering.employeerostering.Skill`
| `timeslot` | `employeerostering.employeerostering.Timeslot`
|===
+
.DayOffRequest
[cols="1.1",options="header"]
|===
| id | Type
| `date` | `LocalDate`
| `employee` | `employeerostering.employeerostering.Employee`
|===
+
.ShiftAssignment
[cols="1.1",options="header"]
|===
| id | Type
| `employee` | `employeerostering.employeerostering.Employee`
| `shift` | `employeerostering.employeerostering.Shift`
|===



For more examples of creating data objects, see  {URL_GETTING_STARTED_DECISION_SERVICE}[_{GETTING_STARTED_DECISION_SERVICE}_].
