[id='wb-employee-rostering-solver-configuration-proc']
= Creating a solver configuration for employee rostering 

You can create and edit Solver configurations in {CENTRAL}. The Solver configuration designer creates a solver configuration that can be run after the project is deployed.

.Prerequisite
{PRODUCT} has been downloaded and installed. You have created and configured all of the relevant assets for the employee rostering example.
 
.Procedure

. In {CENTRAL}, click *Menu* -> *Projects*, and click on your project to open it.
. In the *Assets* perspective, click *Add Asset* -> *Solver configuration*
. In the *Create new Solver configuration* window, type the name `EmployeeRosteringSolverConfig` for your Solver and click *Ok*.
+
This opens the *Solver configuration* designer.

. In the *Score Director Factory* configuration section, define a KIE base that contains scoring rule definitions. The employee rostering sample project uses `defaultKieBase`.
.. Select one of the KIE sessions defined within the KIE base. The employee rostering sample project uses `defaultKieSession`.
. Click *Validate* in the upper-right corner to check the *Score Director Factory* configuration is correct. If validation fails, address any problems described in the error message, and try again to validate until the configuration passes.
. Click *Save* to save the Solver configuration.

//For more information about configuring a Solver, see {URL_INSTALLING_PLANNER}[_{INSTALLING_PLANNER}_].
