[id='wb-employee-rostering-example-deploying-in-central-proc']
= Deploying the employee rostering sample project in {CENTRAL}

{CENTRAL} includes a number of sample projects that you can use to get familiar with the product and its features. The employee rostering sample project is designed and created to demonstrate the shift rostering use case for {PLANNER}. Use the following procedure to deploy and run the employee rostering sample in {CENTRAL}.

.Prerequisites

* {PRODUCT} has been downloaded and installed. For installation options, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].
* You have started the decision server and logged in to {CENTRAL} with a user that has `admin` permissions. For more information about getting started, see  {URL_GETTING_STARTED_DECISION_SERVICE}[_{GETTING_STARTED_DECISION_SERVICE}_].

.Procedure
. In {CENTRAL}, click *Menu* -> *Design* -> *Projects*.
. In the preconfigured `MySpace` space, click *Try Samples*.
. Select *employee-rostering* from the list of sample projects and click *Ok* in the upper-right corner to import the project.
. After the asset list has complied, click *Build & Deploy* to deploy the employee rostering example.

The rest of this document explains each of the project assets and their configuration.
