[id='assembly_case-management-showcase']

include::_artifacts/document-attributes.adoc[]

= Using the Showcase application for case management
// Context attribute is assembly specific and enables module reuse between assemblies.
:doctype: book
:imagesdir: _images
:context: case-management-showcase
include::_artifacts/author-group.adoc[]


// Purpose statement for the assembly

As a case worker or process administrator, you can use the Showcase application to manage and monitor case management applications while case work is carried out in {CENTRAL}.

Case management differs from business process management (BPM) in that it focuses on the actual data being handled throughout the case and less on the sequence of steps taken to complete a goal. Case data is the most important piece of information in case handling, while business context and decision-making is in the hands of the human case worker.

Use this document to install the Showcase application and start a case instance using the IT Orders sample case management project in {CENTRAL}. Use {CENTRAL} to complete the tasks required to complete an IT Orders case.

.Prerequisites

* {EAP_LONG} 7.1.0 is installed. For installation information, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.1/html-single/installation_guide/[_Red Hat JBoss EAP 7.1.0 Installation Guide_].
* {PRODUCT} is installed and configured with {KIE_SERVER}. For more information see {URL_INSTALLING_ON_EAP}[_{INSTALLING_ON_EAP}_].
* `KieLoginModule` is configured in `standalone-full.xml`. This required to connect to the {KIE_SERVER}. For more information about configuring the {KIE_SERVER}, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].
* {PRODUCT} is running and you can log in to {CENTRAL} with a user that has both `kie-server` and `user` roles. For more information about roles, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].
* The IT Orders sample project has been imported in {CENTRAL} and deployed to the {KIE_SERVER}. For more information about case management, see {URL_GETTING_STARTED_CASES}[_{GETTING_STARTED_CASES}_].

// modules
include::{enterprise-dir}/cases/case-management-overview-con.adoc[leveloffset=+1]
// include::{enterprise-dir}/cases/case-management-case-file.con.adoc[leveloffset=+1]
include::{enterprise-dir}/cases/case-management-showcase-application-con.adoc[leveloffset=+1]
include::{enterprise-dir}/cases/case-management-install-and-login-to-showcase-proc.adoc[leveloffset=+1]
include::{enterprise-dir}/cases/case-management-roles-con.adoc[leveloffset=+1]
include::{enterprise-dir}/cases/case-management-adhoc-con.adoc[leveloffset=+1]
include::{enterprise-dir}/cases/case-management-dynamic-tasks-proc.adoc[leveloffset=+1]
include::{enterprise-dir}/cases/case-management-starting-itorders-in-showcase-proc.adoc[leveloffset=+1]
include::{enterprise-dir}/cases/case-management-showcase-completing-itorders-proc.adoc[leveloffset=+1]

//include::{enterprise-dir}/cases/case-management-comments-con.adoc[leveloffset=+1]
// include::{enterprise-dir}/cases/case-management-itorders-adding-a-comment-proc.adoc[leveloffset=+2]
// include::{enterprise-dir}/cases/case-management-close-case-proc.adoc[leveloffset=+1]
// include::{enterprise-dir}/cases/case-management-cancel-case-proc.adoc[leveloffset=+1]
// include::{enterprise-dir}/cases/case-management-destroy-case-proc.adoc[leveloffset=+1]


include::_artifacts/versioning-information.adoc[]
