[id='_chap_download_and_extract']
= Download and Extract

Follow the steps outlined in this chapter to download and extract {PRODUCT} for IBM WebSphere Application Server.

[id='_download_red_hat_jboss_bpm_suitebrms_for_ibm_websphere_8']
== Downloading {PRODUCT} for IBM WebSphere Application Server

To download the deployable {PRODUCT} package file for IBM WebSphere Application Server from the Red Hat Customer Portal:

. Go to the https://access.redhat.com[Red Hat Customer Portal] and log in.
. Click *DOWNLOADS* at the top of the page.
. In the *Product Downloads* page that opens, click *{PRODUCT}*.
. From the *Version* drop-down menu, select *{PRODUCT_VERSION}*.
. Navigate to *{PRODUCT} {PRODUCT_VERSION}.0 Deployable for WebSphere 8.5* and click *Download*.

[id='_extract_product_for_ibm_websphere_8']
== Extracting {PRODUCT} for IBM WebSphere Application Server

ifdef::BA[]
The downloaded installation ZIP file for {PRODUCT} (`jboss-bpmsuite-{PRODUCT_VERSION}.0.GA-deployable-was8.zip`) contains the Business Central WAR deployable archive (`business-central.war`), the {KIE_SERVER} WAR deployable archive (`kie-execution-server.war`), and the Dashbuilder WAR deployable archive (`dashbuilder.war`) in an unextracted format.
endif::BA[]

ifdef::DM[]
The downloaded installation ZIP file for {PRODUCT} (`jboss-brms-{PRODUCT_VERSION}.0.GA-deployable-was8.zip`) contains the Business Central WAR deployable archive (`business-central.war`) and the {KIE_SERVER} WAR deployable archive (`kie-execution-server.war`) in an unextracted format.
endif::DM[]

Extract the downloaded ZIP file so that you have access to the deployable WAR files:

ifdef::BA[]
[source]
----
unzip jboss-bpmsuite-VERSION-deployable-was8.zip
----
endif::BA[]

ifdef::DM[]
[source]
----
unzip jboss-brms-VERSION-deployable-was8.zip
----
endif::DM[]
