[id='controller-was-install-proc']
= Installing and running the {KIE_SERVER} Controller with {WEBSPHERE}

To use the {KIE_SERVER} REST API or Java Client API to interact with {KIE_SERVER}, you can install the {KIE_SERVER} Controller with {WEBSPHERE}. The {KIE_SERVER} Controller manages {KIE_SERVER} configuration in a centralized way so that you can use the Controller to create and maintain containers and perform other server-level tasks.

[NOTE]
====
Red Hat recommends that you install {KIE_SERVER} and the {KIE_SERVER} Controller on different servers in production environments. In development environments, you can install {KIE_SERVER} and the {KIE_SERVER} Controller on the same server.
====

.Prerequisites
* An {WEBSPHERE} instance is configured as described in xref:was-configure-proc[].
* You have sufficient user permissions to complete the installation.

.Procedure
. Navigate to the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page in the Red Hat Customer Portal (login required), and select the product and version from the drop-down options:
* *Product:* {PRODUCT_SHORT}
* *Version:* {PRODUCT_VERSION}
. Download *{PRODUCT} {PRODUCT_VERSION_LONG} Add-Ons*.
. Extract the downloaded `{PRODUCT_FILE}-add-ons.zip` folder to a temporary directory.
. In the WebSphere Integrated Solutions Console, navigate to *Applications* -> *Application Types* -> *WebSphere Enterprise Applications*.
. Click *Install*.
. Navigate to the temporary directory where you downloaded and extracted the `{PRODUCT_FILE}-add-ons.zip` folder, and go to `{PRODUCT_FILE}-add-ons/{PRODUCT_INIT}-{PRODUCT_VERSION}-controller-ee7.zip/controller.war`.
. Select the `controller.war` file to upload it.
. Select *Fast Path* and click *Next*.
+
The *Install New Application* wizard opens.
+
. Change the *Application Name* to `controller` and click *Next*.
. Map the {KIE_SERVER} Controller modules to servers according to your specific requirements and click *Next*.
. For *Bind Listeners for Message-Driven Beans*, select *Activation Specification* for both beans, enter `jms/activation/KIE.SERVER.REQUEST` in the *Target Resource JNDI Name* field, and enter the `jms/cf/KIE.SERVER.REQUEST` JNDI name for the `KIE.SERVER.REQUEST` connection factory.
. In the *Map Virtual Hosts for Web Modules* section, keep the default values and click *Next*.
. Set the context root to `controller`.
. In the *Metadata for Modules* section, keep the default values and click *Next*.
. Click *Finish* to install the {KIE_SERVER} Controller and click *Save* to save the changes to the master configuration.
