[id='download-extract']
= Downloading and extracting {KIE_SERVER}

You must download and extract {KIE_SERVER} prior to installing it on WAS.

== Downloading {KIE_SERVER}

Download the deployable {KIE_SERVER} package file for WAS from the Red Hat Customer Portal:

. Log in to the https://access.redhat.com[Red Hat Customer Portal].
. Click *DOWNLOADS* at the top of the page.
. On the *Product Downloads* page that opens, navigate to the JBOSS INTEGRATION AND AUTOMATION section, and click *{PRODUCT}*.
. On the *Software Downloads* page, if necessary select *BRMS* from the Product menu and *7.0* from the *Version* menu.
. Download the following product distributions:
* *{PRODUCT} {KIE_SERVER} for All Supported EE7 Containers* (`rhdm-7.0.0.GA-kie-server-ee7.zip`)
* *{PRODUCT} 7.0.0 Add Ons* (`rhdm-7.0.0.GA-add-ons.zip`)
. Extract these files to a temporary directory. In the following examples, this directory is called `__TEMP_DIR__`.

== Extracting {KIE_SERVER}

ifdef::BA[]
The downloaded installation ZIP file for {PRODUCT} (`jboss-bpmsuite-{PRODUCT_VERSION}.0.GA-deployable-was9.zip`) contains the {PRODUCT} WAR deployable archive (`business-central.war`), the {KIE_SERVER} WAR deployable archive (`kie-server.war`), and the Dashbuilder WAR deployable archive (`dashbuilder.war`).
endif::BA[]

ifdef::DM[]
The downloaded installation ZIP file for {KIE_SERVER} (`rhdm-7.0.0.GA-kie-server-ee7.zip`) contains the {PRODUCT} WAR deployable archive (`kie-server.war`).
endif::DM[]

Extract the downloaded ZIP file so that you have access to the deployable WAR files:

ifdef::BA[]
[source]
----
unzip rhdm-7.0.0.GA-kie-server-ee7.zip -d `__TEMP_DIR__`
----
endif::BA[]

ifdef::DM[]
[source]
----
unzip rhdm-7.0.0.GA-kie-server-ee7.zip -d `__TEMP_DIR__`
----
endif::DM[]

From the command line, navigate to the `__TEMP_DIR__` > `kie-server.war` folder. Run the following command:
zip -r kie-server.war ./*

//What have done: So, we have downloaded the kie server file, unzipped it, packaged it again to create a war file to deploy to WebSphere
