[id='install-on-ibm-websphere']
= Installing {KIE_SERVER}

Now that the basic configuration is done and WAS is set to deploy {PRODUCT}, you can upload the WAR deployable that was extracted earlier.

As noted previously, the {PRODUCT} ZIP file for WAS contains the deployable WAR file for {KIE_SERVER}.

The {KIE_SERVER} is distributed as a web application archive file (`kie-server.war`) and is present in your {PRODUCT} {PRODUCT_VERSION}.0 Deployable for WebSphere 9.0 download.

[NOTE]
====
It is assumed that you followed the steps described in <<_create_users_and_groups>> to create the role `kie-server` required by the {KIE_SERVER}.
ifdef::BA[]
Similarly, the JMS connection factories, queues, and activation specifications required by the {KIE_SERVER} need to be created.
endif::BA[]
If you have not done so, revisit the respective sections in this guide.
====

. In the main menu on the left, go to *Applications* -> *Application Types* -> *WebSphere Enterprise Applications*.
+
This will show you all the existing applications in the system and allow you to install a new one.

. Click *Install* to start the installation process.

. Upload the {KIE_SERVER} WAR file (`kie-server.war`) from the local file system.

. Select the *Fast Path* radio button and click *Next*.
+
The *Install New Application* wizard opens.

. Change the *Application Name* to `kie-server` in the first step and click *Next*.

. In the next step, map the {KIE_SERVER} modules to servers according to your requirements and click *Next*.

. In the *Bind Listeners for Message-Driven Beans* step, select the *Activation Specification* radio button for both beans and enter `jms/activation/KIE.SERVER.REQUEST` as *Target Resource JNDI Name*.

. In the next step, map resource references to actual resources. Enter the JNDI name for the `KIE.SERVER.REQUEST` connection factory that you created earlier: `jms/conn/KIE.SERVER.REQUEST`.

. In the *Map Virtual Hosts for Web Modules* step, leave the default values and click *Next*.

. In the next screen, set the context root to `kie-server`.

. In the *Metadata for Modules* step, leave the default values and click *Next*.

. Click *Finish* to install the {KIE_SERVER}.  Save the changes to the master configuration at the end of this process.

== Mapping Groups to Roles

If you have already mapped the `kie-server` role to a user or a group, you can ignore this procedure. Otherwise, do the following:

. Go back to the main configuration page for the newly installed `kie-server` application (*Applications* -> *Application Types* -> *WebSphere Enterprise Applications*). Click *Security Role to User/Group Mapping* under the *Detail Properties* heading on the left.
. Select the `kie-server` role, click *Map Groups...* and search for the `kie-server` group in the next screen (or just click the *Search* button).
. Move it from the *Available* list to the *Selected* list. Click *OK*.

This mapping gives the previously created administrator user access to the {KIE_SERVER}.
You can now save the changes and start the `kie-server` application.

Check whether the {KIE_SERVER} REST API works by sending a GET request at `http://_TARGET_SERVER:PORT_/kie-server/services/rest/server`.
