[id='introduction']
= Introduction

[id='_jboss_brms']
== {KIE_SERVER}

ifdef::BA[]
{PRODUCT} is an open source business process management suite that combines Business Process Management and Business Rules Management and enables business and IT users to create, manage, validate, and deploy business processes and rules.
endif::BA[]
ifdef::DM[]
{KIE_SERVER} is an open source decision management platform that combines Business Rules Management and Complex Event Processing. It automates business decisions and makes that logic available to the entire business.
endif::DM[]
ifdef::BA[]
{PRODUCT} uses a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic and business processes without requiring assistance from IT personnel.
endif::BA[]
ifdef::DM[]
{KIE_SERVER} uses a centralized repository where all resources are stored. This ensures consistency, transparency, and the ability to audit across the business. Business users can modify business logic without requiring assistance from IT personnel.
ifdef::BA[]
To accommodate Business Rules component, {PRODUCT} includes integrated {KIE_SERVER}.
endif::BA[]


== IBM WebSphere Application Server

IBM WebSphere Application Server (WAS) is a flexible and secure web application server that hosts Java-based web applications and provides Java EE-certified runtime environments. WAS 9.0 supports Java SE 8 and is fully compliant with Java EE 7 since version 8.5.5.6.
