[id='was-install-start-proc']
= Installing and running {WEBSPHERE}

{WEBSPHERE} must be installed and running for you to apply many of the configurations that accommodate {KIE_SERVER}. This section describes how to install and start {WEBSPHERE_SHORT}.

For the most up-to-date and detailed installation instructions, see the https://www.ibm.com/support/home/product/C578916B44100K52/WebSphere%20Application%20Server[{WEBSPHERE} product page].

.Procedure
. Download IBM Installation Manager version 1.8.5 or later from the http://www-01.ibm.com/support/docview.wss?uid=swg27025142[IBM Installation Manager and Packaging Utility download links] page. IBM Installation Manager is required for installing {WEBSPHERE_SHORT}.
. Extract the downloaded archive and run the following command as the root user in the new directory:
+
[source]
----
sudo ./install
----
+
The *IBM Installation Manager* opens.
. Go to *File* -> *Preferences* and click *Add Repository*.
+
. In the *Add Repository* window, enter the repository URL for {WEBSPHERE_SHORT} 9.0. You can find all the repository URLs in the https://www.ibm.com/support/knowledgecenter/SSEQTJ_9.0.0/com.ibm.websphere.installation.nd.doc/ae/cins_repositories.html[Online product repositories for {WEBSPHERE} offerings] page of the IBM Knowledge Center. For example:
+
[source]
----
http://www.ibm.com/software/repositorymanager/V9WASILAN
----
. In your command terminal, navigate to the {WEBSPHERE} folder location that you specified during the installation.
. Change to the `/bin` directory and run a command similar to the following example to create an {WEBSPHERE_SHORT} profile, user name, and password. A profile defines the run time environment. The profile includes all the files that the server processes in the runtime environment and that you can change. The user is required for login.
+
[source]
----
sudo ./manageprofiles.sh -create -profileName testprofile -adminUserName websphere -adminPassword password123
----
. In your command terminal, navigate to the `bin` directory within the profile that you created (for example, `/profiles/testprofile/bin`) and run the following command to start the {WEBSPHERE} instance:
+
[source]
----
sudo ./startServer.sh <SERVER_NAME>
----
+
`<SERVER_NAME>` is the {WEBSPHERE} name defined in *Servers* -> *Server Types* -> *{WEBSPHERE}s* of the WebSphere Integrated Solutions Console.
+
. Open the following URL in a web browser:
+
[source]
----
http://<HOST>:9060/ibm/console
----
+
`<HOST>` is the system name or IP address of the target server.
+
For example, to start the WebSphere Integrated Solutions Console for a local instance of {WEBSPHERE_SHORT} running on your system, enter the following URL in a web browser:
+
[source]
----
http://localhost:9060/ibm/console
----
+
. When the login page of the WebSphere Integrated Solutions Console appears, enter your administrative credentials.
