= Configure business application

There are several components that can be configured in the business application.
Depending on selected capabilities during application generation, a number of components can differ.

Entire configuration of the business application (service project) is done via application.properties
file that is a standard way to configure SpringBoot applications. It is located under the
`src/main/resources` directory of _{your business application}-service_ folder.

== Configuring core components

=== Configuring server

One of the most important configuration is actually the server itself. That is the host, port and path for the REST endpoints.

[source, bash]
----
# used for server binding
server.address=localhost
server.port=8090

# used to define path for REST apis
cxf.path=/rest
----

=== Configure authentication and authorization

Business application is secured by default by protecting all REST endpoints
(URL pattern `/rest/*`).

Authentication is enabled for single test user named `user` with password `user`.
Additionally there is a default `kieserver` user that allows to easily connect to
{CENTRAL} in development mode.

Both authentication and authorization is based on Spring Security and can be
configured in `DefaultWebSecurityConfig.java` that is included in the generated
service project (`src/main/java/com/company/service/DefaultWebSecurityConfig.java`)

[source, java]
----
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;


@Configuration("kieServerSecurity")
@EnableWebSecurity
public class DefaultWebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
        .csrf().disable()
        .authorizeRequests()
        .antMatchers("/rest/*").authenticated()
        .and()
        .httpBasic();
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        auth.inMemoryAuthentication().withUser("user").password("user").roles("kie-server");
        auth.inMemoryAuthentication().withUser("kieserver").password("kieserver1!").roles("kie-server");
    }
}
----

NOTE: This security configuration is just starting point and should be altered
for all business applications going to production like setup.

==== Use Keycloak as authentication provider


Configuring business applications to use Keycloak as authentication and authorisation
requires few steps

* Install Keycloak - follow official documentation at http://keycloak.org[keycloak.org]
* Configure Keycloak once started
** Use default master realm or create new one
** Create client named springboot-app and set its AccessType to public
** Set Valid redirect URI and Web Origin according to your local setup - with default setup they should be set to
** Valid Redirect URIs: http://localhost:8090/*
** Web Origins: http://localhost:8090
** Create realm roles that are used in the application
** Create users used in the application and assign roles to them
* Configure dependencies in service project pom.xml

[source, xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.keycloak.bom</groupId>
      <artifactId>keycloak-adapter-bom</artifactId>
      <version>${version.org.keycloak}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

  ....

<dependency>
  <groupId>org.keycloak</groupId>
  <artifactId>keycloak-spring-boot-starter</artifactId>
</dependency>
----

Business application includes jBPM (KIE) execution server that can be configured to be better identified

[source,bash,subs="attributes+"]
----
kieserver.serverId=business-application-service
kieserver.serverName=business-application-service
kieserver.location=http://localhost:8090/rest/server
kieserver.controllers=http://localhost:8080/{URL_COMPONENT_CENTRAL}/rest/controller
----

* Configure application.properties

[source, bash]
----
# keycloak security setup
keycloak.auth-server-url=http://localhost:8100/auth
keycloak.realm=master
keycloak.resource=springboot-app
keycloak.public-client=true
keycloak.principal-attribute=preferred_username
keycloak.enable-basic-auth=true
----

* Modify `DefaultWebSecurityConfig.java` to ensure that Spring Security will work correctly with Keycloak

[source, java]
----
import org.keycloak.adapters.KeycloakConfigResolver;
import org.keycloak.adapters.springboot.KeycloakSpringBootConfigResolver;
import org.keycloak.adapters.springsecurity.authentication.KeycloakAuthenticationProvider;
import org.keycloak.adapters.springsecurity.config.KeycloakWebSecurityConfigurerAdapter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.core.authority.mapping.SimpleAuthorityMapper;
import org.springframework.security.core.session.SessionRegistryImpl;
import org.springframework.security.web.authentication.session.RegisterSessionAuthenticationStrategy;
import org.springframework.security.web.authentication.session.SessionAuthenticationStrategy;

@Configuration("kieServerSecurity")
@EnableWebSecurity
public class DefaultWebSecurityConfig extends KeycloakWebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);
        http
        .csrf().disable()
        .authorizeRequests()
            .anyRequest().authenticated()
            .and()
        .httpBasic();
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        KeycloakAuthenticationProvider keycloakAuthenticationProvider = keycloakAuthenticationProvider();
        SimpleAuthorityMapper mapper = new SimpleAuthorityMapper();
        mapper.setPrefix("");
        keycloakAuthenticationProvider.setGrantedAuthoritiesMapper(mapper);
        auth.authenticationProvider(keycloakAuthenticationProvider);
    }

    @Bean
    public KeycloakConfigResolver KeycloakConfigResolver() {
       return new KeycloakSpringBootConfigResolver();
    }

    @Override
    protected SessionAuthenticationStrategy sessionAuthenticationStrategy() {
        return new RegisterSessionAuthenticationStrategy(new SessionRegistryImpl());
    }
}
----

These are the steps to configure you business application to use Keycloak as
authentication and authorisation service.

=== Configuring execution server

*server id and server name* refer to how the business application will be identified when connecting to the {CONTROLLER}
({CENTRAL}) and thus should provide as meaningful information as possible.

*location* is used to inform other components that might interact with REST api where the execution server is accessible.
It should not be the exact same location as defined by server.address and server.port especially when running
in containers (Docker/OpenShift).

*controllers* allows to specify a (comma separated) list of URLs.

=== Configuring capabilities

In case your business application selected 'Business Automation' as the capability then there you can control which of them
should actually be turned on on runtime.

[source, bash]
----
# used for decision management
kieserver.drools.enabled=true
kieserver.dmn.enabled=true

# used for business processes and cases
kieserver.jbpm.enabled=true
kieserver.jbpmui.enabled=true
kieserver.casemgmt.enabled=true

# used for planning
kieserver.optaplanner.enabled=true
----

=== Configuring data source

NOTE: Data source configuration is only required for business automation (meaning when jBPM is used)

[source, bash]
----
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.url=jdbc:h2:./target/spring-boot-jbpm;MVCC=true
spring.datasource.driver-class-name=org.h2.Driver
----

Above configures shows the basic data source settings, next section will deal with
connection pooling for efficient data access.

NOTE: Depending on the driver class selected, make sure your application adds correct
dependency that include the JDBC driver class or data source class.

[source, bash]
----
narayana.dbcp.enabled=true
narayana.dbcp.maxTotal=20
----

this configuration enables the data source connection pool (that is based on
commons-dbcp2 project) and a complete list of parameters can be found on
https://commons.apache.org/proper/commons-dbcp/configuration.html[configuration page].
All parameters from the configuration page must be prefixed with `narayana.dbcp.`


=== Configuring JPA

jBPM uses Hibernate as the database access layer and thus needs to be properly configured

[source, bash]
----
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
----

NOTE: JPA configuration is completely based on SpringBoot so all options for both hibernate and
JPA can be found as https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties[SpringBoot configuration page]

Application with business automation capability creates entity manager factory based on persistence.xml that comes with jBPM.
In case there are more entities that should be added to this entity manager factory (e.g. custom entities for the business application)
they can easily be added by specifying a comma separated list of packages to scan

[source, bash]
----
spring.jpa.properties.entity-scan-packages=org.jbpm.springboot.samples.entities
----

All entities found in that package will be automatically added to entity manager factory and thus used in the same manner as any other JPA entity in the application.

=== Configuring jBPM executor

jBPM executor is the backbone for asynchronous execution in jBPM. By default it is disabled, but can easily be turned on by configuration parameters.

[source, bash]
----
jbpm.executor.enabled=true
jbpm.executor.retries=5
jbpm.executor.interval=0
jbpm.executor.threadPoolSize=1
jbpm.executor.timeUnit=SECONDS
----

* *jbpm.executor.enabled* = true|false - allows to completely disable executor component
* *jbpm.executor.threadPoolSize* = Integer - allows to specify thread pool size where default is 1
* *jbpm.executor.retries* = Integer - allows to specify number of retries in case of errors while running a job
* *jbpm.executor.interval* = Integer - allows to specify interval (by default in seconds) that executor will use to synchronize with database - default is 0 seconds which means it is disabled
* *jbpm.executor.timeUnit* = String - allows to specify timer unit used for calculating interval, value must be a valid constant of java.util.concurrent.TimeUnit, by default it's SECONDS.


=== Configuring distributed timers - Quartz

In case you plan to run your application in a cluster (multiple instances of it at the same time)
then you need to take into account the timer service setup. Since the business application is running
on top of Tomcat web container the only option for timer service for distributed setup is Quartz based.

[source, bash]
----
jbpm.quartz.enabled=true
jbpm.quartz.configuration=quartz.properties
----

Above are two mandatory parameters and the configuration file that need to be either on the classpath
or on the file system (if the path is given).

For distributed timers database storage should be used and properly configured via
quartz.properties file.

[source, bash]
----
#============================================================================
# Configure Main Scheduler Properties
#============================================================================
org.quartz.scheduler.instanceName = SpringBootScheduler
org.quartz.scheduler.instanceId = AUTO
org.quartz.scheduler.skipUpdateCheck=true
org.quartz.scheduler.idleWaitTime=1000
#============================================================================
# Configure ThreadPool
#============================================================================
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 5
org.quartz.threadPool.threadPriority = 5
#============================================================================
# Configure JobStore
#============================================================================
org.quartz.jobStore.misfireThreshold = 60000
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreCMT
org.quartz.jobStore.driverDelegateClass=org.jbpm.process.core.timer.impl.quartz.DeploymentsAwareStdJDBCDelegate
org.quartz.jobStore.useProperties=false
org.quartz.jobStore.dataSource=myDS
org.quartz.jobStore.nonManagedTXDataSource=notManagedDS
org.quartz.jobStore.tablePrefix=QRTZ_
org.quartz.jobStore.isClustered=true
org.quartz.jobStore.clusterCheckinInterval = 5000
#============================================================================
# Configure Datasources
#============================================================================
org.quartz.dataSource.myDS.connectionProvider.class=org.jbpm.springboot.quartz.SpringConnectionProvider
org.quartz.dataSource.myDS.dataSourceName=quartzDataSource
org.quartz.dataSource.notManagedDS.connectionProvider.class=org.jbpm.springboot.quartz.SpringConnectionProvider
org.quartz.dataSource.notManagedDS.dataSourceName=quartzNotManagedDataSource
----

NOTE: Data source names in quartz configuration file refer to Spring beans. Additionally
connection provider needs to be set to `org.jbpm.springboot.quartz.SpringConnectionProvider`
to allow integration with Spring based data sources.

By default Quartz requires two data sources:

* managed data source so it can participate in transaction of the {PROCESS_ENGINE}
* not managed data source so it can look up for timers to trigger without any transaction handling

jBPM based business application assumes that quartz database (schema) will be collocated
with jBPM tables and by that produces data source used for transactional operations for Quartz.

The other (non transactional) data source needs to be configured but it should point
to the same database as the main data source.

[source, bash]
----
# enable to use database as storage
jbpm.quartz.db=true

quartz.datasource.name=quartz
quartz.datasource.username=sa
quartz.datasource.password=sa
quartz.datasource.url=jdbc:h2:./target/spring-boot-jbpm;MVCC=true
quartz.datasource.driver-class-name=org.h2.Driver

# used to configure connection pool
quartz.datasource.dbcp2.maxTotal=15

# used to initialize quartz schema
quartz.datasource.initialization=true
spring.datasource.schema=classpath*:quartz_tables_h2.sql
spring.datasource.initialization-mode=always
----

The last three lines of the above configuration is responsible for initialising
database schema automatically. When configured it should point to a proper
DDL script.

=== Configuring different databases

Business application is generated with default H2 database - just to get started quickly
and without any extra requirements. Since this default setup may not valid for production use
the generated business applications come with configuration dedicated to:

* MySQL
* PostgreSQL

There are dedicated profiles - both Maven and Spring to get you started
really fast without much work. The only thing you need to do is to alight the
configuration with your databases.

MySQL configuration

[source, bash]
----
spring.datasource.username=jbpm
spring.datasource.password=jbpm
spring.datasource.url=jdbc:mysql://localhost:3306/jbpm
spring.datasource.driver-class-name=com.mysql.jdbc.jdbc2.optional.MysqlXADataSource

#hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
----

PostgreSQL configuration

[source, bash]
----
spring.datasource.username=jbpm
spring.datasource.password=jbpm
spring.datasource.url=jdbc:postgresql://localhost:5432/jbpm
spring.datasource.driver-class-name=org.postgresql.xa.PGXADataSource

#hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
----

Once the updates to the configuration are done you can launch your application via

`./launch.sh clean install -Pmysql` for MySQL on Linux/Unix

`./launch.bat clean install -Pmysql` for MySQL on Windows


`./launch.sh clean install -Ppostgres` for MySQL on Linux/Unix

`./launch.bat clean install -Ppostgres` for MySQL on Windows

=== Configuring user group providers

Business automation capability supports human centric activities to be managed, to provide integration with
user and group repositories there is a built in mechanism in jBPM. There are two entry points

* `UserGroupCallback` - responsible for verification if user/group exists and for collecting groups for given user
* `UserInfo` - responsible for collecting additional information about user/group such as email address, preferred language, etc

Both of these can be configured by providing alternative implementation - either one of the provided out of the box or
custom developed.

When it comes to `UserGroupCallback` it is recommended to stick to the default one as it is based on the security
context of the application. That means whatever backend store is used for authentication and authorisation
(e.g. Keycloak) it will be used as source information for collecting user/group information.

`UserInfo` requires more advanced information to be collected and thus is a separate component. Not all user/group repositories will
provide expect data especially those that are purely used for authentication and authorisation.

Following code is needed to provide alternative implementation of `UserGroupCallback`

[source, java]
----
@Bean(name = "userGroupCallback")
public UserGroupCallback userGroupCallback(IdentityProvider identityProvider) throws IOException {
    return new MyCustomUserGroupCallback(identityProvider);
}
----

Following code is needed to provide alternative implementation of `UserInfo`

[source, java]
----
@Bean(name = "userInfo")
public UserInfo userInfo() throws IOException {
    return new MyCustomUserInfo();
}
----

=== Enable Swagger documentation

Business application can easily enable Swagger based documentation for all endpoints
available in the service project.

==== Add required dependencies to service project pom.xml

[source, xml]
----
<dependency>
  <groupId>org.apache.cxf</groupId>
  <artifactId>cxf-rt-rs-service-description-swagger</artifactId>
  <version>3.1.11</version>
</dependency>
<dependency>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-jaxrs</artifactId>
  <version>1.5.15</version>
  <exclusions>
    <exclusion>
      <groupId>javax.ws.rs</groupId>
      <artifactId>jsr311-api</artifactId>
    </exclusion>
  </exclusions>
</dependency>
----

==== Enable Swagger support in application.properties

[source, bash]
----
kieserver.swagger.enabled=true
----

Swagger document can be found at http://localhost:8090/rest/swagger.json[http://localhost:8090/rest/swagger.json]

==== Enable Swagger UI

To enable Swagger UI add following dependency to pom.xml of the service project.

[source, xml]
----
<dependency>
  <groupId>org.webjars</groupId>
  <artifactId>swagger-ui</artifactId>
  <version>2.2.10</version>
</dependency>
----

Once the Swagger UI is enabled and server is started, complete set of
endpoints can be found at http://localhost:8090/rest/api-docs/?url=http://localhost:8090/rest/swagger.json[http://localhost:8090/rest/api-docs/?url=http://localhost:8090/rest/swagger.json]
