= Configuration

== {CENTRAL} Authentication

The {CENTRAL} web application is using the preinstalled _other_ security domain for authenticating and authorizing users (as specified in the _WEB-INF/jboss-web.xml_ inside the WARs).

The application server uses by default property files based realms - Please note that this configuration is intended only for demo purposes (users, roles and passwords are stored in simple property files on the filesystem).

Authentication is configured in the _standalone.xml_ file as follows:

[source,xml]
----
<security-domain name="other" cache-type="default">
    <authentication>
        <login-module code="Remoting" flag="optional">
            <module-option name="password-stacking" value="useFirstPass"/>
        </login-module>
        <login-module code="RealmDirect" flag="required">
            <module-option name="password-stacking" value="useFirstPass"/>
        </login-module>
        <login-module code="org.kie.security.jaas.KieLoginModule" flag="optional" module="deployment.business-central.war"/>
    </authentication>
</security-domain>
----

[source,xml]
----
<security-realm name="ApplicationRealm">
    <authentication>
        <local default-user="$local" allowed-users="*" skip-group-loading="true"/>
        <properties path="users.properties" relative-to="jboss.server.config.dir"/>
    </authentication>
    <authorization>
        <properties path="roles.properties" relative-to="jboss.server.config.dir"/>
    </authorization>
</security-realm>
----

These are the default users:

.Default users
[cols="1,1,1,1", options="header"]
|===
| Name
| Password
| {CENTRAL} roles
| Task roles

|admin
|admin
|admin,analyst,kiemgmt,rest-all,kie-server
|

|krisv
|krisv
|admin,analyst,rest-all,kie-server
|

|john
|john
|analyst,kie-server
|Accounting,PM

|mary
|mary
|analyst,kie-server
|HR

|sales-rep
|sales-rep
|analyst,kie-server
|sales

|jack
|jack
|analyst,kie-server
|IT

|katy
|katy
|analyst,kie-server
|HR

|salaboy
|salaboy
|admin,analyst,rest-all,kie-server
|IT,HR,Accounting

|kieserver
|kieserver1!
|kie-server
|
|===

Authentication can be customized by using any of the following options:

* The users and groups management screens on the {CENTRAL} web application.

Navigate into the {CENTRAL} web application and click the menu _Home_ -> _Admin_ and selecting _Users_.

* The _jboss-cli.sh_ script that comes by default on Wildfly/EAP.

Example for Linux platforms - run the following command and follow the script instructions:

[source,bash]
----
$ ./bin/jboss-cli.sh --commands="embed-server --std-out=echo,/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity(identity=<USERNAME>),/subsystem=elytron/filesystem-realm=ApplicationRealm:set-password(identity=<USERNAME>, clear={password='<PASSWORD>'}),/subsystem=elytron/filesystem-realm=ApplicationRealm:add-identity-attribute(identity=<USERNAME>, name=role, value=['admin'])"
----

== Using your own database with the jBPM installer

=== Introduction


jBPM uses the Java Persistence API specification (v2) to allow users to configure whatever datasource they want to use to persist runtime data.
As a result, the instructions below describe how you should configure a datasource when using JPA on JBoss application server (e.g.
EAP7 or Wildfly10) using a [path]_persistence.xml_
 file and configuring your datasource and driver in your application server's [path]_standalone.xml_
, similar to how you would configure any other application using JPA on the application server.
The installer automates some of this (like copying the right files to the right location after installation).

By default, the jbpm-installer uses an H2 database for persisting runtime data.
In this section we will:

. modify the persistence settings for runtime persistence of process instance state
. test the startup with our new settings!

You will need a local instance of a database, in this case we will use MySQL.

=== Database setup


In the MySQL database used in this quickstart, create a single user:

* user/schema "jbpm" with password "jbpm" (which will be used to persist all entities)

If you end up using different names for your user/schemas, please make a note of where we insert "jbpm" in the configuration files.

If you want to try this quickstart with _another_ database, a section at the end of this quickstart describes what you may need to modify.

=== Configuration


The following files define the persistence settings for the jbpm-installer demo:

* jbpm-installer/db/jbpm-persistence-JPA2.xml
* Application server configuration
** standalone-*.xml


[TIP]
====
There are multiple standalone.xml files available (depending on whether you are using JBoss EAP or Wildfly and whether you are running the normal or full profile).  The full profile is required to use the JMS component for remote integration, so will be used by default by the installer.
Best practice is to update all standalone.xml files to have consistent setup but most important is to have standalone-full-wildfly-{version}.xml properly configured as this is used by default by the installer.
====


Do the following:

* Disable H2 default database and enable MySQL database in build.properties
+
[source,properties]
----
# default is H2
# H2.version=1.3.168
# db.name=h2
# db.driver.jar.name=${db.name}.jar
# db.driver.download.url=http://repo1.maven.org/maven2/com/h2database/h2/${H2.version}/h2-${H2.version}.jar
#mysql
db.name=mysql
db.driver.module.prefix=com/mysql
db.driver.jar.name=mysql-connector-java-5.1.18.jar
db.driver.download.url=https://repository.jboss.org/nexus/service/local/repositories/central/content/mysql/mysql-connector-java/5.1.18/mysql-connector-java-5.1.18.jar
org.kie.server.persistence.dialect=org.hibernate.dialect.MySQLDialect
----
+
You might want to update the db driver jar name and download url to whatever version of the jar
matches your installation. Look to also update the dialect to what matches your installation if needed (for example
change to MySQL5Dialect for MySQL 5.x specific features).
* [path]_db/jbpm-persistence-JPA2.xml_ :
+
This is the JPA persistence file that defines the persistence settings used by jBPM for the {PROCESS_ENGINE} information, the logging/BAM information, and task service.
+
In this file, you will have to change the name of the hibernate dialect used for your database.
+
The original line is:
+

[source,xml]
----
<property name="hibernate.dialect" value="org.hibernate.dialect.H2Dialect"/>
----
+
In the case of a MySQL database, you need to change it to:
+

[source,xml]
----
<property name="hibernate.dialect" value="org.hibernate.dialect.MySQLDialect"/>
----
+
For those of you who decided to use another database, a list of the available hibernate dialect classes can be found https://docs.jboss.org/hibernate/core/3.3/reference/en-US/html/session-configuration.html#configuration-optional-dialects[
here].
* [path]_standalone-full-wildfly-{version}.xml_ :
+
[path]_Standalone.xml_
and [path]_standalone-full.xml_
are the configuration for the standalone JBoss application server.
When the installer installs the demo, it copies these files to the `standalone/configuration` directory in the JBoss server directory.
Since the installer uses Wildfly by default as application server, you probably need to change [path]_standalone-full-wildfly-{version}.xml_
.
+
We need to change the datasource configuration in `standalone-full.xml` so that the {PROCESS_ENGINE} can use our MySQL database.
The original file contains (something very similar to) the following lines:
+

[source,xml]
----
<datasource jta="true" jndi-name="java:jboss/datasources/jbpmDS" pool-name="H2DS" enabled="true" use-java-context="true" use-ccm="true">
    <connection-url>jdbc:h2:tcp://localhost/~/jbpm-db;MVCC=TRUE</connection-url>
    <driver>h2</driver>
    <security>
       <user-name>sa</user-name>
    </security>
</datasource>
<drivers>
    <driver name="h2" module="com.h2database.h2">
        <xa-datasource-class>org.h2.jdbcx.JdbcDataSource</xa-datasource-class>
    </driver>
</drivers>
----
+
Change the lines to the following:
+

[source,xml]
----
<datasource jta="true" jndi-name="java:jboss/datasources/jbpmDS" pool-name="MySQLDS" enabled="true" use-java-context="true" use-ccm="true">
    <connection-url>jdbc:mysql://localhost:3306/jbpm</connection-url>
    <driver>mysql</driver>
    <security>
       <user-name>jbpm</user-name>
       <password>jbpm</password>
    </security>
</datasource>
----
+
and add an additional driver configuration:
+

[source,xml]
----
<driver name="mysql" module="com.mysql">
    <xa-datasource-class>com.mysql.jdbc.jdbc2.optional.MysqlXADataSource</xa-datasource-class>
</driver>
----
* To install driver jars in JBoss application server (Wildfly, EAP, etc.), it is recommended to install the driver jar as a module. The installer already takes care of this mostly: it will  copy the driver jar (you specified in the [path]_build.properties_ ) to the right folder inside the modules directory of your server and put a matching module.xml next to it. For MySQL, this file is called [path]_db/mysql_module.xml_ . Open this file and make sure that the file name of the driver jar listed there is identical the driver jar name you specified in the [path]_build.properties_ (including the version).  Note that, even if you simply uncommented the default MySQL configuration, you will still need to add the right version here.
* *Starting the demo*
+
We've modified all the necessary files at this point.
Now would be a good time to make sure your database is started up as well!
+
The installer script copies this file into the business-central WAR before the WAR is installed on the server.
If you have already run the installer, it is recommended to stop the installer and clean it first using
+
[source,shell]
----
ant stop.demo
----
+
and
+
[source,shell]
----
ant clean.demo
----
+
before continuing.
+
Run
+
[source,shell]
----
ant install.demo
----
+
to (re)install the wars and copy the necessary configuration files.
Once you've done that, (re)start the demo using
+
[source,shell]
----
ant start.demo
----
* *Problems?*
+
If this isn't working for you, please try the following:
+
** Please double check the files you've modified: I _wrote_ this, but still made mistakes when changing files!
** Please make sure that you don't secretly have another (unmodified) instance of JBoss AS running.
** If neither of those work (and you're using MySQL), then please do let us know.


=== Using a different database


If you decide to use a different database with this demo, you need to remember  the following when going through the steps above:

* Configuring the jBPM datasource in ``standalone.xml``:
+
** After locating the `java:jboss/datasources/jbpmDS` datasource, you need to provide the following properties specific to your database:
+
*** Change the url of your database
*** Change the user-name and password
*** Change the name of the driver (which you'll create next)
+
For example:
+
[source,xml]
----
<datasource jta="true" jndi-name="java:jboss/datasources/jbpmDS" pool-name="PostgreSQLDS" enabled="true" use-java-context="true" use-ccm="true">
    <connection-url>jdbc:postgresql://localhost:5432/jbpm</connection-url>
    <driver>postgresql</driver>
    <security>
        <user-name>jbpm</user-name>
        <password>jbpm</password>
    </security>
</datasource>
----

** Add an additional driver configuration:
+
*** Change the name of the driver to match the name you specified when configuring the datasource in the previous step
*** Change the module of the driver: the database driver jar should be installed as a module (see
    below) and here you should reference the unique name of the module. Since the installer can
    take care of automatically generating this module for you (see below), this should match the
    `db.driver.module.prefix` property in `build.properties` (where forward slashes are replaced
    by a point). In the example below, I used ``org/postgresql`` as `db.driver.module.prefix`
    which means that I should then use  `org.postgresql` as module name for the driver.
*** Fill in the correct name of the XA datasource class to use.

+
For example:
+
[source,xml]
----
<driver name="postgresql" module="org.postgresql">
    <xa-datasource-class>org.postgresql.xa.PGXADataSource</xa-datasource-class>
</driver>
----


* You need to change the dialect in [path]_persistence.xml_ to the dialect for your database, for example:
+
[source,xml]
----
<property name="hibernate.dialect" value="org.hibernate.dialect.PostgreSQLDialect"/>
----

* In order to make sure your driver will be correctly installed in the JBoss application server,
  there are typically multiple options, like install as a module or as a deployment. It is
  recommended to install the driver as a module for EAP and Wildfly.
+
** https://community.jboss.org/wiki/DataSourceConfigurationinAS7#Installing_a_JDBC_driver_as_a_module[Install]
   the driver JAR as a __module__, which is what the install script does.
** https://community.jboss.org/wiki/DataSourceConfigurationinAS7#Installing_a_JDBC_driver_as_a_deployment[Otherwise, you can modify and install]
   the downloaded JAR as a __deployment__. In this case you will have to copy the JAR yourself to
   the `standalone/deployments` directory.

+
If you choose to install driver as JBoss module (recommended), please do the following:
** In ``build.properties``, disable the default H2 driver properties
+
[source,properties]
----
# default is H2
# H2.version=1.3.168
# db.name=h2
# db.driver.jar.name=h2-${H2.version}.jar
# db.driver.download.url=http://repo1.maven.org/maven2/com/h2database/h2/${H2.version}/h2-${H2.version}.jar
----
** Uncomment one of the other example configs (mysql or postgresql) or create your own:
+
[source,properties]
----
#postgresql
db.name=postgresql
db.driver.module.prefix=org/postgresql
db.driver.jar.name=postgresql-9.1-902.jdbc4.jar
db.driver.download.url=https://repository.jboss.org/nexus/content/repositories/thirdparty-uploads/postgresql/postgresql/9.1-902.jdbc4/postgresql-9.1-902.jdbc4.jar
----
*** Change the `db.name` property in `build.properties` to a name for your database.
*** Change the `db.driver.module.prefix` property to a name for the module of your driver. Note
    that this should match the module property when configuring the driver in
    [path]_standalone.xml_ (where forward slashes in the prefix here are  replaced by a point).
    In the example above, I used ``org/postgresql`` as `db.driver.module.prefix` which means that
    I should then use  `org.postgresql` as module name for the driver.
*** Change the `db.driver.jar.name` property to the name of the jar that contains your database driver.
*** Change the `db.driver.download.url` property to where the driver jar can be downloaded. Alternatively, you could manually download the jar yourself, and place it in the `db/drivers` folder, using the same name as you specified in the `db.driver.jar.name` property.

** Lastly, you'll have to create the `db/${db.name}_module.xml` file. As an example you can use db/mysql_module.xml, so just make a copy of it and:
+
*** Change the name of the _module_ to match the  driver module name above
*** Change the name of the module resource path to the name of the  `db.driver.jar.name` property.
** For example, the top of the file would look like:
[source,xml]
----
<module xmlns="urn:jboss:module:1.0" name="org.postgresql">
   <resources>
     <resource-root path="postgresql-9.1-902.jdbc4.jar"/>
   </resources>
----

== jBPM database schema scripts (DDL scripts)


By default the demo setup makes use of Hibernate auto DDL generation capabilities to build up  the complete database schema, including all tables, sequences, etc.
This might not always be welcomed (by your database administrator), and thus the installer provides DDL scripts for most popular databases.

.DDL scripts
[cols="1,1", options="header"]
|===
| Database name
| Location

|db2
|jbpm-db-scripts/db/ddl-scripts/db2

|derby
|jbpm-db-scripts/db/ddl-scripts/derby

|h2
|jbpm-db-scripts/db/ddl-scripts/h2

|hsqldb
|jbpm-db-scripts/db/ddl-scripts/hsqldb

|mysql5
|jbpm-db-scripts/db/ddl-scripts/mysql5

|mysqlinnodb
|jbpm-db-scripts/db/ddl-scripts/mysqlinnodb

|oracle
|jbpm-db-scripts/db/ddl-scripts/oracle

|postgresql
|jbpm-db-scripts/db/ddl-scripts/postgresql

|sqlserver
|jbpm-db-scripts/db/ddl-scripts/sqlserver

|sqlserver2008
|jbpm-db-scripts/db/ddl-scripts/sqlserver2008

|sybase
|jbpm-db-scripts/db/ddl-scripts/sybase
|===


DDL scripts are provided for both jBPM and Quartz schemas although Quartz schema DDL script is only required when the timer service should be configured with Quartz database job store.
See the section on timers for additional details.

This can be used to initially create the database schema, but it can also serve as the basis for any\ optimization that needs to be applied - such as indexes, etc.

[NOTE]
====
If you use MySQL 5.7 or earlier (MariaDB 10.2.3 or earlier), you also need to run [path]_jbpm-db-scripts/db/ddl-scripts/mysql5/mysql-jbpm-amend-auto-increment-procedure.sql_

This script creates a procedure for jBPM tables (ProcessInstanceInfo/WorkItemInfo/Task) to protect AUTO_INCREMENT counter. Without the procedure, ID values of those tables could be reset on MySQL/MariaDB restart (https://dev.mysql.com/doc/refman/8.0/en/innodb-auto-increment-handling.html#innodb-auto-increment-initialization). It would introduce further side effects.

In addition to creating the procedure, you have to call the procedure on MySQL/MariaDB restart. For example,

[path]_/etc/my.cnf_
[source,properties]
----
init-file=/path/to/mysql-jbpm-amend-auto-increment-call.sql
----

Write [path]_mysql-jbpm-amend-auto-increment-call.sql_
[source,sql]
----
call mydatabase.JbpmAmendAutoIncrement;
----
====

[NOTE]
====
If you use PostgreSQL with jBPM, you also need to run jbpm-db-scripts/db/ddl-scripts/postgresql/postgresql-jbpm-lo-trigger-clob.sql

This script creates triggers for jBPM tables to protect CLOB references of large objects. Without the triggers, vacuumlo tool (https://www.postgresql.org/docs/9.4/static/vacuumlo.html) deletes active large objects so causes an issue to jBPM. If you are already running jBPM without the triggers, you also need to run the following SQLs after applying the triggers to protect existing CLOB.
[source,xml]
----
insert into jbpm_active_clob ( loid ) select cast(expression as oid) from booleanexpression where expression is not null;
insert into jbpm_active_clob ( loid ) select cast(body as oid) from email_header where body is not null;
insert into jbpm_active_clob ( loid ) select cast(text as oid) from i18ntext where text is not null;
insert into jbpm_active_clob ( loid ) select cast(text as oid) from task_comment where text is not null;
insert into jbpm_active_clob ( loid ) select cast(qexpression as oid) from querydefinitionstore where qexpression is not null;
insert into jbpm_active_clob ( loid ) select cast(deploymentunit as oid) from deploymentstore where deploymentunit is not null;
----
====

== jBPM installer script


jBPM installer ant script performs most of the work automatically and usually does not require additional attention but in case it does, here is a list of available targets that might be needed to perform some of the steps manually.

.jBPM installer available targets
[cols="1,1", options="header"]
|===
| Target
| Description

|clean.db
|cleans up database used by jBPM demo (applies only to H2 database)

|clean.demo
|cleans up entire installation so new installation can be performed

|clean.demo.noeclipse
|same as clean.demo but does not remove Eclipse

|clean.eclipse
|removes Eclipse and its workspace

|clean.generated.ddl
|removes DDL scripts generated if any

|clean.jboss
|removes application server with all its deployments

|clean.jboss.repository
|removes repository content for demo setup (guvnor Maven repo, niogit, etc)

|download.db.driver
|downloads DB driver configured in build.properties

|download.ddl.dependencies
|downloads all dependencies required to run DDL script generation tool

|download.droolsjbpm.eclipse
|downloads Drools and jBPM Eclipse plugin

|download.eclipse
|downloads Eclipse distribution

|download.eclipse.gef
|downloads Eclipse GEF feature

|download.jboss
|downloads JBoss Application Server

|download.jBPM.bin
|downloads jBPM binary distribution (jBPM libs and its dependencies)

|download.jBPM.casemgmt
|downloads jBPM case management console

|download.jBPM.console
|downloads jBPM process management console

|download.kie.server
|downloads jBPM process execution server

|install.db.files
|installs DB driver as JBoss module

|install.demo
|installs complete demo environment

|install.demo.eclipse
|installs Eclipse with all jBPM plugins, no server installation

|install.demo.noeclipse
|similar to install.demo but skips Eclipse installation

|install.droolsjbpm-eclipse.into.eclipse
|installs droolsjbpm Eclipse plugin into Eclipse

|install.eclipse
|install Eclipse IDE

|install.jboss
|installs JBoss AS

|install.jBPM-casemgmt.into.jboss
|installs jBPM case management application

|install.jBPM-console.into.jboss
|installs jBPM process management console

|install.kie-server.into.jboss
|installs jBPM process execution server
|===
