d[id='assembly_guided-decision-tables']

include::product-shared-docs/document-attributes.adoc[]

= Planning a {PRODUCT} installation
// Context attribute is assembly specific and enables module reuse between assemblies.
:imagesdir: topics/product-shared-docs/images
:context: guided-decision-tables
include::product-shared-docs/author-group.adoc[]

// Purpose statement for the assembly
As a system administrator, you have several options for installing {PRODUCT}.


// Modules - concepts, procedures, refs, etc.
//include::product-installation-guide/rules-authoring-assets-ref.adoc[leveloffset=+1]

== What is {PRODUCT}?

include::product-installation-guide/components-con.adoc[leveloffset=+1]

=== {CENTRAL}
=== {KIE_SERVER}
include::product-installation-guide/business-optimizer-con.adoc[leveloffset=+2]
include::product-installation-guide/roles-users-con.adoc[leveloffset=+1]
== Supported repositories
=== Git repositories
include::product-development-guide/maven-con.adoc[leveloffset=+2]
include::product-installation-guide/dev-studio-con.adoc[leveloffset=+1]

== Available installation plaforms
https://access.redhat.com/articles/3405381[Supported configurations]

https://access.redhat.com/articles/3405391[Components page]

=== {EAP} 7.1

=== OpenShift Container Platform

OpenShift Container Platform (OpenShift) brings together Docker and Kubernetes, and provides an API to manage these services. OpenShift Container Platform enables you to create and manage containers.

In this solution, components of {PRODUCT} are deployed as separate OpenShift pods. You can scale each of the pods up and down individually, providing as few or as many containers as necessary for a particular component. You can use standard OpenShift methods to manage the pods and balance the load.

For more information, see _Deploying {PRODUCT} {PRODUCT_VERSION} on OpenShift_.
//@link

//=== JBoss Web Server 5 with Tomcat 9

=== Oracle WebLogic server
Oracle WebLogic server is a Java EE application server. You can installe

=== IBM WebSphere Application Server

== Installation environment options

=== Development environment

=== Production environment

=== Clustered environment
Difference between a clustered and a standalone environment. Pros and cons of each. Discuss high availability. Clustering a Development environment vs Clustering a Production environment 
Include a descriptions of NFS, Artemis, Elasticsearch, any other cluster-related tools.

== Integrating with Red Hat Single Sign-On

== Putting it all together

== Next steps
Links to installation stories
// Versioning info
include::product-shared-docs/versioning-information.adoc[]
