[id='Deploying-dashbuilder-data-proc_{context}']

ifdef::PAM,JBPM[]

= Deploying dashboards from {CENTRAL} on Dashbuilder Runtime

You can automatically deploy the dashboards from {CENTRAl} on Dashbuilder Runtime. {CENTRAl} is linked to Dashbuilder Runtime using a gradual export feature.

.Prerequisites

* Dashbuilder Runtime is configured on your system.
* You have set the `dashbuilder.runtime.multi` system property to `true` in the `standalone.xml` file.
* You have set the value of `dashbuilder.runtime.location` system property to the Dashbuilder Runtime URL, as shown in the following example:
+
[source]
----
<property name="dashbuilder.runtime.location" value=" http://localhost:8080"
----
* You have set the `dashbuilder.export.dir` system property to the shared directory where Dashbuilder Runtime reads its model, as shown in the following example:
+
[source]
----
<property name="dashbuilder.export.dir" value="/tmp/dashbuilder/models/"
----


.Procedure

. In {CENTRAL}, go to *Menu* → *Design* → *Pages*.
. In the *Components* panel, drag and edit the required component types to the canvas as needed and click *Save* to finish.
. Select the *Admin* icon in the upper-right corner of the screen and select *Dashbuilder Data Transfer*.
. On the *Dashbuilder Data Transfer* page, click *Custom export*.
. Select the pages that you want to include in the ZIP file in the *Export Wizard* panel, and click *Next*.
. Select *Export Wizard* and click *Open*.
+
You can see the Dashbuilder Runtime home page. If you are not logged in, you are redirected to the login page.
. Go to *Dashboards* → *Runtime Dashboards* and you can see the pages.
+
The selected data is exported and Dashbuilder Runtime updates the model content when it is opened.

endif::[]
