[id='access-control-con']
= Access control

ifdef::PAM[]
The access control mechanism includes authorization and authentication. To grant a specific user access to {PRODUCT}, the user needs to have the respective roles assigned:

* `admin`: Administrates {PRODUCT} system and has full access rights to make any changes necessary, including the ability to add and remove users from the system.
* `analyst`: Creates and designs processes and forms, instantiates the processes, and deploys artifacts. This role is very similar to the `developer` role, with the exception that analysts do not have access to the asset repository and deployments.
* `developer`: Implements code required by processes. Users with this role cannot access administration tasks.
* `user`: Claims, performs, and invokes other actions, such as escalation and rejection, on the assigned tasks. The user role grants no access to authoring functions.
* `manager`: Monitors the system and its statistics. Users with this role can access only dashboards.

Creating users is described in section {URL_INSTALLATION_GUIDE}#creating_the_users[Creating Users] of the _{PRODUCT} Installation and Configuration Guide_.

Roles assigned to a user can be updated in the `_EAP_HOME_/standalone/configuration/application-roles.properties` file.
endif::PAM[]


Within {PRODUCT}, users may set up roles using LDAP to modify existing roles. Users may modify the roles in the workbench configuration to ensure the unique LDAP based roles conform to enterprise standards by editing the deployments directory located at `_JBOSS_HOME_/standalone/deployments/business-central.war/WEB-INF/classes/workbench-policy.propeties`.

If authenticating user via LDAP over Git, administrators must set system property [property]``org.uberfire.domain`` to the name of login module it should use to authenticate users via the Git service. This must be set in the ``standalone.xml``file in EAP.
