[appendix]
= Configuration Properties

This chapter contains all public system properties and KIE environment entries that you can use to configure your deployment of {PRODUCT}.


=== System Properties

System properties configure the entire JVM {PRODUCT} runs on. You can either provide them at runtime, or set them in the configuration XML file for your deployment.


==== Runtime Configuration

To set a particular property at runtime, add a flag `-D` with the property's name and value when starting the server. You can list multiple such properties at the same time.

.Configuring System Properties at Runtime (Standalone deployments)
. Navigate to `_SERVER_HOME_/bin`.
. Run the server with the desired flags:
+
[source]
----
./standalone.sh -Dorg.kie.custom.property=value -Dorg.uberfire.switch=false
----
+
NOTE: On Windows, run `standalone.bat` instead of `standalone.sh`.


==== XML Configuration

To set a property in {PRODUCT} configuration, add an entry under the `<system-properties>` section in the `standalone.xml` file:

[source,xml]
----
<system-properties>
  <property name="org.kie.custom.property" value="random_value"/>
  <property name="org.uberfire.switch" value="false"/>
  ...
</system-properties>
----

When running {PRODUCT} in domain mode, add the entries in the `<system-properties>` element of the appropriate node in the `host.xml` file.


==== List of System Properties

This section contains the alphabetically sorted list of all recognized system properties in {PRODUCT} {PRODUCT_VERSION}.

.{PRODUCT} System Properties
*btm.root*::
+
--
Root directory for Bitronix Transaction Manager. The discovery of configuration and other files starts in this location.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--

*drools.propertySpecific*::
+
--
Sets property reactivity behavior of the {PRODUCT} engine. Options are following:

* `DISABLED`: Property reactivity turned off.
* `ALLOWED`: Property reactivity allowed.
* `ALWAYS`: Property reactivity always on.


[cols="1,1", options="header"]
|===
| Values
| Default

| `DISABLED`, `ALLOWED`, or `ALWAYS`
| `ALLOWED`
|===
--

*drools.ruleEngine*::
+
--
Specifies which algorithm the {PRODUCT} rule engine should use.

[cols="1,1", options="header"]
|===
| Values
| Default

| `phreak` or `reteoo`
| `phreak`
|===
--

*drools.sequential*::
+
--
Enables sequential mode for stateless sessions.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--

*drools.sequential.agenda*::
+
--
Selects static or dynamic agenda with sequential mode.

[cols="1,1", options="header"]
|===
| Values
| Default

| `static` or `dynamic`
| `static` for standard mode, `dynamic` for sequential mode
|===
--

*jboss.node.name*::
+
--
A node name unique in a {PRODUCT} cluster.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--

ifdef::BA[]
*jbpm.audit.jms.connection.factory*::
+
--
A link to a JMS connection factory instance.

[cols="1,1", options="header"]
|===
| Values
| Default

| A `javax.jms.ConnectionFactory` instance
| N/A
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.audit.jms.connection.factory.jndi*::
+
--
The JNDI name of the connection factory to look up.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.audit.jms.enabled*::
+
--
Indicates if audit mode is set to JMS.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` if Audit mode is set to JMS, otherwise `false`
| N/A
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.audit.jms.queue*::
+
--
A JMS Queue instance to be used when creating JMS AuditLogger.

[cols="1,1", options="header"]
|===
| Values
| Default

| A `javax.jms.Queue` instance
| N/A
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.audit.jms.queue.jndi*::
+
--
The JNDI name of the JMS queue to look up.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--
endif::BA[]
ifdef::BA[]
*jbpm.audit.jms.transacted*::
+
--
Determines if the JMS session is transacted.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `true`
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.business.calendar.properties*::
+
--
The location of the configuration file with Business Calendar properties.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| `/jbpm.business.calendar.properties`
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.data.dir*::
+
--
The location where data files produced by {PRODUCT} must be stored.

[cols="1,1", options="header"]
|===
| Values
| Default

| `${jboss.server.data.dir}` if available, otherwise `${java.io.tmpdir}`
| `${java.io.tmpdir}`
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.ejb.timer.tx*::
+
--
Marks if the EJB timer service is transactional.  If set to `true`, the EJB time service starts participating in the transactions. Note that this property is available only in {PRODUCT} 6.4.2 and later.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.enable.multi.con*::
+
--
Allows Web Designer to use multiple incoming or outgoing connections for tasks. If not enabled, the tasks are marked as invalid.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.loop.level.disabled*::
+
--
Enables or disables loop iteration tracking to allow advanced loop support when using XOR gateways.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `true`
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.overdue.timer.delay*::
+
--
Specifies the delay for overdue timers to allow proper initialization, in milliseconds.

[cols="1,1", options="header"]
|===
| Values
| Default

| Number (`Long`)
| 2000
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.overdue.timer.wait*::
+
--
A time period in which the timer execution service allows overdue timers to start, in milliseconds.

[cols="1,1", options="header"]
|===
| Values
| Default

| Number (`Long`)
| 20000
|===
--

endif::BA[]

ifdef::BA[]
*jbpm.process.name.comparator*::
+
--
An alternative comparator class to empower the Start Process by Name feature.

[cols="1,1", options="header"]
|===
| Values
| Default

| Fully qualified name
| `org.jbpm.process.instance.StartProcessHelper.NumberVersionComparator`
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.tm.jndi.lookup*::
+
--
Allows setting a specific `TransactionManager` JNDI lookup name as a fallback in case a standard JNDI name is not used. If `java:comp/UserTransaction` does not implement the `org.drools.persistence.TransactionManager` interface, these names are used, in this order:

. `java:comp/TransactionManager`
. `java:appserver/TransactionManager`
. `java:pm/TransactionManager`
. `java:TransactionManager`
. Value of this property

[cols="1,1", options="header"]
|===
| Values
| Default

| JNDI name
| N/A
|===
--
endif::BA[]

ifdef::BA[]
[id='jbpm.usergroup.callback.properties']
*jbpm.usergroup.callback.properties*::
+
--
The location of the usegroup callback property file when <<org.jbpm.ht.callback, `org.jbpm.ht.callback`>> is set to `jaas` or `db`.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| `classpath:/jbpm.usergroup.callback.properties`
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.user.group.mapping*::
+
--
An alternative classpath location of user info configuration (used by `LDAPUserInfoImpl`).

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| `${jboss.server.config.dir}/roles.properties`
|===
--
endif::BA[]

ifdef::BA[]
[id='jbpm.user.info.properties']
*jbpm.user.info.properties*::
+
--
An alternative classpath location for user group callback implementation (LDAP, DB). For more information, see <<org.jbpm.ht.userinfo, `org.jbpm.ht.userinfo`>>.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| `classpath:/userinfo.properties`
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.ut.jndi.lookup*::
+
--
An alternative JNDI name to be used when there is no access to the default one for user transactions (`java:comp/UserTransaction`).

[cols="1,1", options="header"]
|===
| Values
| Default

| JNDI name
| N/A
|===
--
endif::BA[]

ifdef::BA[]
*jbpm.v5.id.strategy*::
+
--
When enabled, {PRODUCT} will use the process ID generation strategy from version 5 when migrating to version 6 and newer.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]

*kie.maven.settings.custom*::
+
--
The location of a custom `settings.xml` file for Maven configuration.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| N/A
|===
--

*kie.server.jms.queues.response*::
+
--
The JNDI name of response queue for JMS.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `queue/KIE.SERVER.RESPONSE`
|===
--

*org.drools.server.ext.disabled*::
+
--
When set to ``true``, disables the BRM support (for example rules support).

[cols="1,1", options="header"]
|===
| Values
| Default

|`true` or `false`
|`false`
|===
--

*org.drools.server.filter.classes*::
+
--
When set to `true`, the Drools {KIE_SERVER} extension accepts custom classes annotated by `XmlRootElement` or `Remotable` annotations only.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
*org.guvnor.inbox.disabled*::
+
--
When set to `true`, this system property disables the Inbox feature and the Inbox mechanism of tracking changes to files is turned off. Doing this enables faster response to file system operations.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
*org.guvnor.m2repo.dir*::
+
--
The location where Maven artifacts are stored. When you build and deploy a project, it is stored in this directory. Change the setting, for example, to allow easier backup of your maven repository.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| `_EAP_HOME_/repositories/kie`
|===
--

*org.guvnor.project.gav.check.disabled*::
+
--
Disables a duplicate `GroupId`, `ArtifactId`, and `Version` (GAV) detection. When you build and deploy a project, Business Central scans the Maven repository for an artifact with the same GAV values. If set to `true`, Business Central silently overrides any previous project. If set to `false`, the user is required to confirm overriding the old project.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--

ifdef::BA[]
*org.jbpm.deploy.sync.enabled*::
+
--
When enabled, {PRODUCT} synchronizes KJAR deployments across Business Central nodes in a cluster, and automatically loads previous deployments.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `true`
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.deploy.sync.int*::
+
--
Interval of KJAR deployment synchronization, in seconds.

[cols="1,1", options="header"]
|===
| Values
| Default

| Number (`Integer`)
| 3
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.executor.service.ejb-jndi*::
+
--
Set this property in the application server in case your application uses EJBs. This property enables you to configure the executor service JNDI name. For example, to have executor available from `ejb-services` application (the deployed war application that uses EJBs), set this system property to `jndi:java:global/ejb-services/ExecutorServiceEJBImpl`.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `jndi:java:module/ExecutorServiceEJBImpl`
|===
--
endif::BA[]

ifdef::BA[]
[id='org.jbpm.ht.callback']
*org.jbpm.ht.callback*::
+
--
Specifies the implementation of user group callback to be used:

 * `mvel`: Default; mostly used for testing.
 * `ldap`: LDAP; requires additional configuration in the <<jbpm.usergroup.callback.properties, `jbpm.usergroup.callback.properties`>> file.
 * `db`: Database; requires additional configuration in the <<jbpm.usergroup.callback.properties, `jbpm.usergroup.callback.properties`>> file.
 * `jaas`: JAAS; delegates to the container to fetch information about user data.
 * `props`: A simple property file; requires additional file that will keep all information (users and groups).
 * `custom`: A custom implementation; you must specify the fully qualified name of the class in the <<org.jbpm.ht.custom.callback, `org.jbpm.ht.custom.callback`>>.

[cols="1,1", options="header"]
|===
| Values
| Default

| `mvel`, `ldap`, `db`, `jaas`, `props`, or `custom`
| `jaas`
|===
--
endif::BA[]

ifdef::BA[]
[id='org.jbpm.ht.custom.callback']
*org.jbpm.ht.custom.callback*::
+
--
A custom implementation of the `UserGroupCallback` interface in case the <<org.jbpm.ht.callback, `org.jbpm.ht.callback`>> property is set to `custom`.

[cols="1,1", options="header"]
|===
| Values
| Default

| Fully qualified name
| N/A
|===
--
endif::BA[]

ifdef::BA[]
[id='org.jbpm.ht.custom.userinfo']
*org.jbpm.ht.custom.userinfo*::
+
--
A custom implementation of the `UserInfo` interface in case the <<org.jbpm.ht.userinfo, `org.jbpm.ht.userinfo`>> property is set to `custom`.

[cols="1,1", options="header"]
|===
| Values
| Default

| Fully qualified name
| N/A
|===
--
endif::BA[]

ifdef::BA[]
[id='org.jbpm.ht.userinfo']
*org.jbpm.ht.userinfo*::
+
--
Specifies what implementation of the UserInfo interface to use for user or group information providers.

* `ldap`: LDAP; needs to be configured in the file specified in `jbpm-user.info.properties`.
* `db`: Database; needs to be configured in the file specified in `jbpm-user.info.properties`.
* `props`: A simple property file; set the property <<jbpm.user.info.properties, `jbpm.user.info.properties`>> to specify the path to the file.
* `custom`: A custom implementation; you must specify the fully qualified name of the class in the <<org.jbpm.ht.custom.userinfo, `org.jbpm.ht.custom.userinfo`>> property.

[cols="1,1", options="header"]
|===
| Values
| Default

| `ldap`, `db`, `props`, or `custom`
| N/A
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.ht.user.separator*::
+
--
An alternative separator when loading actors and groups for user tasks from a `String`.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `,` (comma)
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.rule.task.waitstate*::
+
--
When set to `false`, a business rule task automatically fires all rules instead of waiting to be triggered from the process event listener or an outside call. This behavior prevents errors during heavy multithreaded usage, however if `org.jbpm.rule.task.waitstate` is set to `false`, the business task is no longer a safe point.

For information about safe points, see <<_safe_points>>.

NOTE: Starting with {PRODUCT} 6.4 the default for `org.jbpm.rule.task.waitstate` is `false`. For more information, see the https://access.redhat.com/documentation/en-us/red_hat_jboss_bpm_suite/6.4/html/6.4_release_notes/chap_fixed_issues#miscellaneous[_{PRODUCT} 6.4 Release Notes_].

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.runtime.manager.class*::
+
--
A custom implementation of the `org.kie.api.runtime.manager.RuntimeManagerFactory` interface.

[cols="1,1", options="header"]
|===
| Values
| Default

| Fully qualified name
| `org.jbpm.runtime.manager.impl.RuntimeManagerFactoryImpl`
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.server.ext.disabled*::
+
--
When set to `true`, disables the BPM support (for example, processes support).


[cols="1,1", options="header"]
|===
| Values
| Default

|`true` or `false`
|`true`
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.task.bam.enabled*::
+
--
Enables the `BAMTaskEventListener` class, which populates the `BAMTASKSUMMARY` table to allow the BAM module to query tasks.


[cols="1,1", options="header"]
|===
| Values
| Default

|`true` or `false`
|`true`
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.task.cleanup.enabled*::
+
--
Enables the `TaskCleanUpProcessEventListener` class, which archives and removes completed tasks with the associated process ID.


[cols="1,1", options="header"]
|===
| Values
| Default

|`true` or `false`
|`true`
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.task.assignment.enabled*::
+
--
Enables automatic task assignment.

[cols="1,1", options="header"]
|===
| Values
| Default

|`true` or `false`
|`false`
|===
--

endif::BA[]

ifdef::BA[]
*org.jbpm.task.assignment.strategy*::
+
--
Defines the assignment strategy for automatic task assignment. For more information, see the {URL_DEVELOPMENT_GUIDE}#task_assignment_strategies[Task Assignment Strategies] chapter of the _{DEVELOPMENT_GUIDE}_.

[cols="1,1", options="header"]
|===
| Values
| Default

|`RoundRobin`, `LoadBalance`, or `BusinessRule`
|`BusinessRule`

|`CustomStrategy`
|`IDENTIFIER`
|===
--

endif::BA[]

ifdef::BA[]
*org.jbpm.task.assignment.loadbalance.calculator*::
+
--
A class of the calculator to be used for load balancing for the `LoadBalance` task assignment strategy.

[cols="1,1", options="header"]
|===
| Values
| Default

|A fully-qualified class name
|N/A
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.services.task.assignment.taskduration.timetolive*::
+
--
Specifies the interval after which the task duration is re-calculated for the `LoadBalance` task assignment strategy.

[cols="1,1", options="header"]
|===
| Values
| Default

|A long (in milliseconds)
|1800000 (30 minutes)
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.task.assignment.rules.releaseId*::
+
--
A GAV identifier of the rules that determine the task assignment order for the `BusinessRule` task assignment strategy.

[cols="1,1", options="header"]
|===
| Values
| Default

|A string (`GROUP_ID:ARTIFACT_ID:VERSION`).
|N/A
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.task.assignment.rules.scan*::
+
--
The KIE Scanner polling interval. Set this property to create a KIE Scanner for your `BusinessRule` task assignment strategy.
[cols="1,1", options="header"]
|===
| Values
| Default

|A long (in milliseconds)
|N/A
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.task.assignment.rules.query*::
+
--
Specifies a rule query that returns a subset of task assignments from the session. The query is executed after firing all rules. If you set this property, assignments not matched by the query are not used. Defining a query enables you to select specific assignments when multiple assignments are present in your session for one task.

[cols="1,1", options="header"]
|===
| Values
| Default

|A String (name of the query)
|N/A
|===
--
endif::BA[]

ifdef::BA[]
*org.jbpm.ui.server.ext.disabled*::
+
--
When set to ``true``, disables the {KIE_SERVER} UI extension.

[cols="1,1", options="header"]
|===
| Values
| Default

|`true` or `false`
|`true`
|===
--
endif::BA[]

*org.kie.auto.deploy.enabled*::
+
--
When enabled, issuing a Build & Deploy operation in Business Central always deploys to runtime.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `true`
|===
--

*org.kie.build.disable-project-explorer*::
+
--
Disables automatic build of the selected project in Project Explorer.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--

ifdef::BA[]
*org.kie.dd.mergemode*::
+
--
Selects the method for overriding hierarchical merge mode behavior when managing deployment descriptors.


[cols="1,1", options="header"]
|===
| Values
| Default

| `MERGE_COLLECTIONS`, `KEEP_ALL`, `OVERRIDE_ALL`, or `OVERRIDE_EMPTY`
| `MERGE_COLLECTIONS`
|===
--
endif::BA[]

*org.kie.demo*::
+
--
Enables external cloning of a demo application from GitHub. This System Property takes precedence over `org.kie.example`.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `true`
|===
--

*org.kie.example*::
+
--
When set to `true`, creates an example organization unit and repository. This system property allows you to create projects and assets without creating your custom organization unit and repository. It is useful, for example, to simplify the getting started experience.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--

*org.kie.example.repositories*::
+
--
Sets the path to the directory containing example repositories. If you set this system property, repositories in the specified directory are automatically cloned into Business Central during startup. This property overrides `org.kie.example` and `org.kie.demo`.

WARNING: You must download the example repositories from the https://access.redhat.com/jbossnetwork/restricted/softwareDetail.html?softwareId=48391&product=bpm.suite&version=6.4&downloadType=distributions[Customer Portal] and extract them to this directory before setting this system property.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| N/A
|===
--

*org.kie.executor.disabled*::
+
--
Disables the {PRODUCT} executor.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--

*org.kie.executor.initial.delay*::
+
--
The initial delay before the {PRODUCT} executor starts a job, in milliseconds.

[cols="1,1", options="header"]
|===
| Values
| Default

| Number (`Integer`)
| 100
|===
--

[id='org.kie.executor.interval']
*org.kie.executor.interval*::
+
--
The time between the moment the {PRODUCT} executor finishes a job and the moment it starts a new one, in a time unit specified in <<org.kie.executor.timeunit, `org.kie.executor.timeunit`>>.


[cols="1,1", options="header"]
|===
| Values
| Default

| Number (`Integer`)
| 3
|===
--

*org.kie.executor.pool.size*::
+
--
The number of threads used by the {PRODUCT} executor.

[cols="1,1", options="header"]
|===
| Values
| Default

| Number (`Integer`)
| 1
|===
--

*org.kie.executor.retry.count*::
+
--
The number of retries the {PRODUCT} executor attempts on a failed job.

[cols="1,1", options="header"]
|===
| Values
| Default

| Number (`Integer`)
| 3
|===
--

[id='org.kie.executor.timeunit']
*org.kie.executor.timeunit*::
+
--
The time unit in which the <<org.kie.executor.interval, `org.kie.executor.interval`>> is specified.

[cols="1,1", options="header"]
|===
| Values
| Default

| A https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/TimeUnit.html[`java.util.concurrent.TimeUnit`] constant
| `SECONDS`
|===
--

*org.kie.git.deployments.enabled*::
+
--
When enabled, {PRODUCT} uses a Git repository for storing deployments instead of a database.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--

ifdef::BA[]
*org.kie.mail.debug*::
+
--
When enabled, `EmailWorkItemHandler` produces debug logging for `javax.mail.Session`.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]

*org.kie.mail.session*::
+
--
The JNDI name of the mail session as registered in the application server, for use by `EmailWorkItemHandler`.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `mail/jbpmMailSession`
|===
--

ifdef::BA[]
*org.kie.override.deploy.enabled*::
+
--
Allows overwriting deployments with the same GAV (not allowed by default).

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]

ifdef::BA[]
*org.kie.server.bypass.auth.user*::
+
--
Allows to bypass the authenticated user for task-related operations, for example queries.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]

*org.kie.server.controller*::
+
--
A comma-separated list of URLs to controller REST endpoints, for example `http://localhost:8080/business-central/rest/controller`. This property is required when using a controller.


[cols="1,1", options="header"]
|===
| Values
| Default

| Comma-separated list
| N/A
|===
--

*org.kie.server.controller.connect*::
+
--
The waiting time between repeated attempts to connect {KIE_SERVER} to the controller when {KIE_SERVER} starts up, in milliseconds.

[cols="1,1", options="header"]
|===
| Values
| Default

| Number (`Long`)
| `10000`
|===
--

*org.kie.server.controller.pwd*::
+
--
The password to connect to the controller REST API. This property is required when using a controller.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `kieserver1!`
|===
--

*org.kie.server.controller.token*::
+
--
This property allows you to use a token-based authentication between the KIE server and the controller instead of the basic user name/password authentication. The KIE server sends the token as a parameter in the request header. Note that long-lived access tokens are required as the tokens are not refreshed.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--

*org.kie.server.controller.user*::
+
--
The user name to connect to the controller REST API. This property is required when using a controller.


[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `kieserver`
|===
--

*org.kie.server.controller.templatefile*::
+
--
The system property required to set a custom `templatefile.xml` template file for use with a standalone controller to store and retrieve container templates.


[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| N/A
|===
--

*org.kie.server.domain*::
+
--
The JAAS `LoginContext` domain used to authenticate users when using JMS.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--

*org.kie.server.id*::
+
--
An arbitrary ID to be assigned to this server. If a remote controller is configured, this is the ID under which the server will connect to the controller to fetch the KIE container configurations. If not provided, the ID is automatically generated.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--

*org.kie.server.location*::
+
--
The URL of the {KIE_SERVER} instance used by the controller to call back on this server, for example: `http://localhost:8230/kie-execution-server/services/rest/server`. This property is required when using a controller.

[cols="1,1", options="header"]
|===
| Values
| Default

| URL
| N/A
|===
--

ifdef::BA[]
*org.kie.server.persistence.dialect*::
+
--
The Hibernate dialect to be used. You must set this property when enabling BPM support.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--
endif::BA[]

ifdef::BA[]
*org.kie.server.persistence.ds*::
+
--
A data source JNDI name. You must set this property when enabling BPM support.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--
endif::BA[]

ifdef::BA[]
*org.kie.server.persistence.schema*::
+
--
The database schema to be used.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--
endif::BA[]

ifdef::BA[]
*org.kie.server.persistence.tm*::
+
--
A transaction manager platform for Hibernate properties set. You must set this property when enabling BPM support.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--
endif::BA[]

*org.kie.server.pwd*::
+
--
The password used to connect with the KIE server from the controller, required when running in managed mode. You must set this property in Business Central system properties, and it is required when using a controller.


[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `kieserver1!`
|===
--

*org.kie.server.repo*::
+
--
The location where {KIE_SERVER} state files will be stored.


[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| `.`
|===
--

*org.kie.server.sync.deploy*::
+
--
Instructs the KIE server to hold the deployment until the controller provides the containers deployment configuration. This property affects only the KIE servers running in managed mode. The options are as follows:

* `false`; the connection to the controller is asynchronous.
The application starts, connects to the controller and once successful, deploys the containers.
The application accepts requests even before the containers are available.

* `true`; the deployment of the KIE server application joins the controller connection thread with the main deployment and awaits its completion.
+
This option can lead to a potential deadlock in case more applications are on the same server instance.
It is strongly recommended to use only one application (the KIE server) on one server instance.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--

*org.kie.server.token*::
+
--
This property allows you to use a token-based authentication between the controller and the KIE server instead of the basic user name/password authentication. The controller sends the token as a parameter in the request header. Note that long-lived access tokens are required as the tokens are not refreshed.


[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--

*org.kie.server.user*::
+
--
The user name used to connect with the KIE server from the controller, required when running in managed mode. This property need to be set in Business Central system properties and is required when using a controller.


[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `kieserver`
|===
--

ifdef::BA[]
*org.kie.task.insecure*::
+
--
Allows an authenticated user to work on tasks on behalf of other users through the Business Central runtime remote API.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]

ifdef::BA[]
*org.kie.timer.ejb.disabled*::
+
--
If you select the Singleton runtime strategy and use the EJB executor of your application server to handle timer events, a race condition may occur since the EJB executor completes a transaction outside the `KieSession`. Set this property to `true` to use the EJB executor bundled with {PRODUCT}, which prevents this situation from happening.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]

*org.kie.tx.lock.enabled*::
+
--
When enabled, {PRODUCT} uses an interceptor that locks the `KieSession` to a single thread for the duration of a transaction, which prevents concurrency errors in Container Managed Transaction (CMT) environments.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--

*org.kie.verification.disable-dtable-realtime-verification*::
+
--
Disables Business Central's decision table verification and validation feature.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--

*org.optaplanner.server.ext.disabled*::
+
--
When set to ``true``, disables the BRP support (for example planner support).

[cols="1,1", options="header"]
|===
| Values
| Default

|`true` or `false`
|``false``
|===
--

ifdef::BA[]
*org.quartz.properties*::
+
--
The location of the Quartz configuration file to activate the Quartz timer service.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| N/A
|===
--
endif::BA[]

*org.uberfire.cluster.autostart*::
+
--
Delays VFS clustering until the application is fully initialized to avoid conflicts when all cluster members create local clones.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--

*org.uberfire.cluster.id*::
+
--
The name of the Helix cluster, for example: `kie-cluster`. You must set this property to the same value as defined in the Helix Controller.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--

*org.uberfire.cluster.local.id*::
+
--
The unique ID of the Helix cluster node. Note that ':' is replaced with '_', for example `node1_12345`.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--

*org.uberfire.cluster.vfs.lock*::
+
--
The name of the resource defined on the Helix cluster, for example: `kie-vfs`.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--

*org.uberfire.cluster.zk*::
+
--
The location of the Zookeeper servers.

[cols="1,1", options="header"]
|===
| Values
| Default

| String of the form ``host1:port1``,``host2:port2``,``host3:port3``,...
| N/A
|===
--

*org.uberfire.domain*::
+
--
The security domain name for Business Central. For more information about security domains, see chapter https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html/Security_Guide/Use_a_Security_Domain_in_Your_Application.html[Use a Security Domain in Your Application] of the _Red Hat JBoss EAP Security Guide_.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `ApplicationRealm`
|===
--

*org.uberfire.metadata.index.dir*::
+
--
The location of the `$$.$$index` directory, which Apache Lucene uses when indexing and searching.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| Current working directory
|===
--

*org.uberfire.nio.git.daemon.enabled*::
+
--
Enables the Git daemon.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `true`
|===
--

*org.uberfire.nio.git.daemon.host*::
+
--
If the Git daemon is enabled, it uses this property as the localhost identifier.

[cols="1,1", options="header"]
|===
| Values
| Default

| URL
| `localhost`
|===
--

*org.uberfire.nio.git.daemon.hostport*::
+
--
When running in a virtualized environment, the host's outside port number for the Git daemon.

[cols="1,1", options="header"]
|===
| Values
| Default

| Port number
| 9418
|===
--

*org.uberfire.nio.git.daemon.port*::
+
--
If the Git daemon is enabled, it uses this property as the port number.

[cols="1,1", options="header"]
|===
| Values
| Default

| Port number
| `9418`
|===
--

[id='org.uberfire.nio.git.dir']
*org.uberfire.nio.git.dir*::
+
--
The location of the directory ``$$.$$niogit``. Change the value for example for backup purposes.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| Current working directory
|===
--

*org.uberfire.nio.git.hooks*::
+
--
The location where default Git hook files are stored. These files will be copied to newly created Git repositories.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| N/A
|===
--

*org.uberfire.nio.git.ssh.cert.dir*::
+
--
The location of the directory `$$.$$security`. Local certificates are stored here.

[cols="1,1", options="header"]
|===
| Values
| Default

| Path
| Current working directory
|===
--

*org.uberfire.nio.git.ssh.enabled*::
+
--
Enables the SSH daemon.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `true`
|===
--

*org.uberfire.nio.git.ssh.host*::
+
--
If the SSH daemon is enabled, it uses this property as the localhost identifier.

[cols="1,1", options="header"]
|===
| Values
| Default

| URL
| `localhost`
|===
--

*org.uberfire.nio.git.ssh.hostport*::
+
--
When running in a virtualized environment, the host's outside port number for the SSH daemon.

[cols="1,1", options="header"]
|===
| Values
| Default

| Port number
| 8003
|===
--

*org.uberfire.nio.git.ssh.passphrase*::
+
--
The passphrase to access your operating system's public keystore when cloning Git repositories with scp-style URLs, for example `git@github.com:user/repository.git`.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| N/A
|===
--

*org.uberfire.nio.git.ssh.port*::
+
--
If the SSH daemon is enabled, it uses this property as the port number.

[cols="1,1", options="header"]
|===
| Values
| Default

| Port number
| `8001`
|===
--

*org.uberfire.secure.alg*::
+
--
The crypto algorithm used by password encryption.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `PBEWithMD5AndDES`
|===
--

*org.uberfire.secure.key*::
+
--
A secret password used by password encryption.

[cols="1,1", options="header"]
|===
| Values
| Default

| String
| `org.uberfire.admin`
|===
--

*org.uberfire.sys.repo.monitor.disabled*::
+
--
Disables the configuration monitor.

WARNING: Do not use unless you are certain what you are doing.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--


=== Environment Properties

As opposed to <<system_properties, system properties>>, environment properties are passed to an individual `KieSession`, allowing you to control its behaviour independently on the rest of the deployment.

The properties available to you are the constants of the class `org.kie.api.runtime.EnvironmentName`.

==== Configuration

To set the environment properties on a `KieSession`, you can create a new session with an instance of the `Environment` or `RuntimeEnvironment` interface:

.Setting Environment Property using `Environment` interface
[source,java]
----
Environment env = EnvironmentFactory.newEnvironment();
env.set(EnvironmentName.SAMPLE_PROPERTY, true);
kbase.newKieSession(null, env);
----

.Setting Environment Property using `RuntimeEnvironment` interface
[source,java]
----
RuntimeEnvironment environment = RuntimeEnvironmentBuilder.Factory.get()
.newDefaultBuilder()
....

environment.getEnvironment().set(EnvironmentName.SAMPLE_PROPERTY, true);
singletonManager = RuntimeManagerFactory.Factory.get().newSingletonRuntimeManager(environment);
----


==== List of Environment Properties

This section contains the alphabetically sorted list of all recognized environment properties in {PRODUCT} {PRODUCT_VERSION}.

.{PRODUCT} Environment Properties
ifdef::BA[]
*APP_SCOPED_ENTITY_MANAGER*::
+
--
The entity manager used for persistence of `SessionInfo`. You can specify it when using Spring with local transactions and a shared entity manager.

[cols="1,1", options="header"]
|===
| Values
| Default

| An instance of `EntityManager`
| Automatically created from the provided `EntityManagerFactory`
|===
--
endif::BA[]

*CALENDARS*::
+
--
This property is not used.
--

ifdef::BA[]
*CMD_SCOPED_ENTITY_MANAGER*::
+
--
The entity manager used for persistence of entities (process instances, tasks, work items). You can specify it when using Spring with local transactions and a shared entity manager.

[cols="1,1", options="header"]
|===
| Values
| Default

| An instance of `EntityManager`
| Automatically created from the provided `EntityManagerFactory`
|===
--
endif::BA[]

*DATE_FORMATS*::
+
--
This property is not used.
--

ifdef::BA[]
*ENTITY_MANAGER_FACTORY*::
+
--
The `EntityManagerFactory` used in the {PRODUCT} engine.

[cols="1,1", options="header"]
|===
| Values
| Default

| An instance of `EntityManagerFactory`
| N/A
|===
--
endif::BA[]

*GLOBALS*::
+
--


[cols="1,1", options="header"]
|===
| Values
| Default

| Any object declared in DRL or BPMN
| N/A
|===
--

*OBJECT_MARSHALLING_STRATEGIES*::
+
--
Enable use of pluggable variable persistence strategies. Allows storing variables in different data stores.
[cols="1,1", options="header"]
|===
| Values
| Default

| An instance of `org.kie.api.marshalling.ObjectMarshallingStrategy`
| Dependent on the engine configuration. If no other strategy is available, `org.drools.core.marshalling.impl.SerializablePlaceholderResolvingStrategy` is used.
|===
--

*PERSISTENCE_CONTEXT_MANAGER*::
+
--
The `ProcessPersistenceContextManager` instance used for process persistence.

[cols="1,1", options="header"]
|===
| Values
| Default

| An instance of `org.jbpm.persistence.ProcessPersistenceContextManager`
| An instance of `org.jbpm.persistence.JpaProcessPersistenceContextManager`
|===
--

ifdef::BA[]
*TASK_PERSISTENCE_CONTEXT_MANAGER*::
+
--
The `TaskPersistenceContextManager` instance used for task persistence.

[cols="1,1", options="header"]
|===
| Values
| Default

| An instance of `org.kie.internal.task.api.TaskPersistenceContextManager`
| An instance of `org.jbpm.services.task.persistence.JPATaskPersistenceContextManager`
|===
--
endif::BA[]

ifdef::BA[]
*TASK_USER_GROUP_CALLBACK*::
+
--
Get the `UserGroupCallback` instance from the environment or context. For example:

[source,java]
----
callback = context.get(EnvironmentName.TASK_USER_GROUP_CALLBACK)
----

[cols="1,1", options="header"]
|===
| Values
| Default

| Configured by {PRODUCT}
| An instance of `org.kie.internal.task.api.UserGroupCallback`
|===
--
endif::BA[]

ifdef::BA[]
*TASK_USER_INFO*::
+
--
Get the `UserInfo` instance from the environment or context. For example:

[source,java]
----
info = context.get(EnvironmentName.TASK_USER_INFO)
----

[cols="1,1", options="header"]
|===
| Values
| Default

| Configured by {PRODUCT}
| An instance of `org.kie.internal.task.api.UserInfo`
|===
--
endif::BA[]

*TRANSACTION*::
+
--
Optional property if `UserTransaction` can not be obtained using JNDI lookup.

[cols="1,1", options="header"]
|===
| Values
| Default

| An instance of `UserTransaction`
| `null`
|===
--

*TRANSACTION_MANAGER*::
+
--
Get the `TransactionManager` instance from the environment or context. For example:

[source,java]
----
info = context.get(EnvironmentName.TRANSACTION_MANAGER)
----

[cols="1,1", options="header"]
|===
| Values
| Default

| An instance of `TransactionManager`
| Depends on your configuration
|===
--

*TRANSACTION_SYNCHRONIZATION_REGISTRY*::
+
--
Allows access to and control of the active transaction. Used by {PRODUCT} to efficiently manage persistence.

[cols="1,1", options="header"]
|===
| Values
| Default

| An instance of `TransactionSynchronizationRegistry`
| Taken from the environment--usually JNDI lookup in JTA environments
|===
--

ifdef::BA[]
*USE_LOCAL_TRANSACTIONS*::
+
--
When enabled, {PRODUCT} uses local transactions as opposed to JTA.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]

ifdef::BA[]
*USE_PESSIMISTIC_LOCKING*::
+
--
When enabled, a database resource can only be accessed by one transaction at a time.

[cols="1,1", options="header"]
|===
| Values
| Default

| `true` or `false`
| `false`
|===
--
endif::BA[]
