
[[event_listeners]]
[[_aries_event_listeners_proc]]
= Adding and Configuring Event Listeners
{PRODUCT} supports adding three types of listeners to KieSessions:

* `AgendaListener`
* `WorkingMemoryListener`
* `ProcessEventListener`

The `kie-aries-blueprint` module enables you to configure the listeners for KIE sessions using XML tags.
The tags have identical names to the listener interfaces:

* `<kie:agendaEventListener>`
* `<kie:ruleRuntimeEventListener>`
* `<kie:processEventListener>`

The `kie-aries-blueprint` module enables you to define listeners as standalone listeners or as a group.

.Procedure
Review the examples in this section and add and configure listeners if necessary.

[float]
== Standalone Listeners

Standalone listeners support the following parameters:


[cols="25%,75%", options="header"]
|===
| Attribute
| Description

|ref
|A reference to a bean.
|===

.Listener Configuration Using bean:ref
====
[source,xml]
----
<bean id="mock-agenda-listener" class="mocks.MockAgendaEventListener"/>
<bean id="mock-rr-listener" class="mocks.MockRuleRuntimeEventListener"/>
<bean id="mock-process-listener" class="mocks.MockProcessEventListener"/>

<kie:kmodule id="listeners_kmodule">
  <kie:kbase name="drl_kiesample" packages="drl_kiesample">
    <kie:ksession name="ksession2">
      <kie:agendaEventListener ref="mock-agenda-listener"/>
      <kie:processEventListener ref="mock-process-listener"/>
      <kie:ruleRuntimeEventListener ref="mock-rr-listener"/>
    </kie:ksession>
  </kie:kbase>
</kie:kmodule>
----
====

[float]
== Multiple Listeners of One Type

You can also define multiple listeners of one type for a KIE session.

.Listener Configuration: Multiple Listeners of One Type.
====
[source,xml]
----
<bean id="mock-agenda-listener1" class="mocks.MockAgendaEventListener"/>
<bean id="mock-agenda-listener2" class="mocks.MockAgendaEventListener"/>

<kie:kmodule id="listeners_module">
  <kie:kbase name="drl_kiesample" packages="drl_kiesample">
    <kie:ksession name="ksession1">
      <kie:agendaEventListener ref="mock-agenda-listener1"/>
      <kie:agendaEventListener ref="mock-agenda-listener2"/>
    </kie:ksession>
  </kie:kbase>
</kie:kmodule>
----
====

[float]
[[_kie_grouping_listeners]]
== Listener Groups

The `kie-aries-blueprint` module allows you to group listeners. This is useful when you define a set of listeners that you want to attach to multiple sessions, or when switching from testing to production use. The following attribute is required:


[cols="25%,75%", options="header"]
|===
| Attribute
| Description

|ID
|Unique identifier
|===

Possible children:

* `kie:agendaEventListener`
* `kie:ruleRuntimeEventListener`
* `kie:processEventListener`

[NOTE]
====
The declaration order does not matter. Only one declaration of each type is allowed in a group.
====

.Group of Listeners
====
[source,xml]
----
<bean id="mock-agenda-listener" class="mocks.MockAgendaEventListener"/>
<bean id="mock-rr-listener" class="mocks.MockRuleRuntimeEventListener"/>
<bean id="mock-process-listener" class="mocks.MockProcessEventListener"/>

<kie:kmodule id="listeners_module">
  <kie:kbase name="drl_kiesample" packages="drl_kiesample">
    <kie:ksession name="statelessWithGroupedListeners" type="stateless"
             listeners-ref="debugListeners"/>
  </kie:kbase>
</kie:kmodule>

  <kie:eventListeners id="debugListeners">
  <kie:agendaEventListener ref="mock-agenda-listener"/>
  <kie:processEventListener ref="mock-process-listener"/>
  <kie:ruleRuntimeEventListener ref="mock-rr-listener"/>
</kie:eventListeners>
----
====