[[_chap_process_monitoring]]
= Process monitoring

[[_jboss_operations_network1]]
== JBoss Operations Network

A JBoss Operations Network plug-in can be used to monitor rules sessions for {PRODUCT}.

Due to a limitation of passing the JVM monitoring arguments via the Maven command line, all `com.sun.management.jmxremote.*` parameters must be passed to the {PRODUCT} application via the `pom.xml` configuration file.

See the https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Operations_Network/3.3/html-single/Installation_Guide/index.html[Installation Guide] of _Red Hat JBoss Operations Network_ for installation instructions on the Red Hat JBoss ON server.

[[_installing_the_jboss_operations_network_plug_in]]
== Installing the JBoss BRMS Plug-in into JBoss ON

Red Hat JBoss BRMS plug-in for JBoss Operations Network can be installed by either copying the plug-in JAR files to the JBoss Operations Network plug-in directory or through the JBoss Operations Network GUI.

To copy the plug-in JAR files to the JBoss Operations Network plug-in directory, follow the following procedure:

.Procedure: Copying the JBoss BRMS plug-in JAR files
. Extract the JBoss BRMS plug-in pack archive to a temporary location. This creates a subdirectory with the name `jon-plugin-pack-brms-bpms-3.3.0.GA`. For example:
+
[source]
----
[root@server rhq-agent]# unzip jon-plugin-pack-brms-bpms-3.3.0.GA.zip -d /tmp
----

. Copy the extracted JBoss BRMS plug-in JAR files from the `jon-plugin-pack-brms-bpms-3.3.0.GA/` directory to the JBoss ON server plug-in directory. For example:
+
[source]
----
[root@server rhq-agent]# cp /tmp/jon-plugin-pack-brms-bpms-3.3.0.GA/*.jar /opt/jon/jon-server-3.3.0.GA/plugins
----

. Start the JBoss Operations Network server to update the JBoss BRMS plug-in.

To upload the JBoss BRMS plug-in through the JBoss Operations Network GUI, follow this procedure:

.Procedure: Uploading the JBoss BRMS plug-in through GUI
. Start the JBoss Operations Network Server and Log in to access the GUI.
. In the top navigation of the GUI, open the *Administration* menu.
. In the *Configuration* area on the left, select the *Agent Plugins* link.
. At the bottom of the list of loaded agent plug-ins, click the *Upload a plugin* button and choose the BRMS plugin.
. The JBoss BRMS plug-in for JBoss Operations Network is now uploaded.


[[_monitoring_knowledge_bases_and_knowledge_sessions1]]
== Monitoring Kie Bases and Kie Sessions

In order for JBoss Operations Network to monitor KieBases and KieSessions, MBeans must be enabled.

MBeans can be enabled either by passing the parameter: `-kie.mbeans = enabled` or via the API:

[source]
----
KieBaseConfiguration kbconf = KieServices.Factory.get().newKieBaseConfiguration();
kbconf.setOption(MBeansOption.ENABLED);
----

[NOTE]
====
`Kie Services` have been implemented for JBoss BRMS 6; for JBoss BRMS 5, `Drools Services` was the naming convention used and it had different measurements on sessions. For example, *activation* -> *match* renaming occurred in the updated version.
====

Please refer to the https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Operations_Network/3.3/html-single/Complete_Resource_Reference/index.html[Resource Monitoring and Operations Reference guide] of the _Red Hat JBoss Operations Network_  for information on importing Kie Sessions into the Inventory View for monitoring purposes.
