[id='_chap_localization_and_customization']
= Localization and Customization

[id='_available_languages2']
== Available Languages

The {PRODUCT} web user interface can be viewed in multiple languages:

* United States English (``en_US``)
* Spanish (``es_ES``)
* Japanese (``ja_JP``)
* Simplified Chinese (``zh_CN``)
* Traditional Chinese (``zh_TW``)
* Portuguese (``pt_BR``)
* French (``fr_CA``)
* German (``de_DE``)

[NOTE]
====
If a language is not specified, US English is used by default.
====

ifdef::BA[]
[NOTE]
====
Dashbuilder does not support Traditional Chinese (``zh_TW``).
====
endif::BA[]


[id='_changing_language_settings']
== Changing Language Settings

[float]
=== Changing the User Interface Language in Business Central

By default, Business Central uses the system locale. If you need to change it, then append the required locale code at the end of the Business Central URL. For example, the following URL will set the locale to Portuguese (pt_BR).

`http://_localhost_:8080/business-central/?locale=pt_BR`


ifdef::BA[]
[float]
=== Changing the User Interface Language in Dashbuilder

To change the user interface language in dashbuilder, do the following:

. Log in to the dashbuilder after the server has been successfully started by navigating to http://_localhost_:8080/dashbuilder in a web browser.
. Select the language of your choice by clicking on the available locales on the top center of the dashbuilder user interface to change the language.


[float]
=== Setting a Default User Interface Language in Dashbuilder

Following is an example to set the default user interface language in dashbuilder:

.Procedure: Setting the Default Language as French
. Navigate to `jboss-eap-6.4/standalone/configuration` and define the following in the `standalone.xml` file.
+
[source]
----
<system-properties>
  <property name="org.jboss.dashboard.LocaleManager.installedLocaleIds" value="en,es,de,fr,ja,pt,zh"/>
  <property name="org.jboss.dashboard.LocaleManager.defaultLocaleId" value="fr"/>
</system-properties>
----

. The default user interface language of the dashbuilder is now set to French.


[float]
=== Defining the Installed Locales in Dashbuilder

Following is an example to define the installed locales in dashbuilder:

.Procedure: Defining the Installed Locale
. Navigate to `jboss-eap-6.4/standalone/configuration` and define the following in the `standalone.xml` file:
+
[source]
----
<system-properties>
  <property name="org.jboss.dashboard.LocaleManager.installedLocaleIds" value="en,es,de,fr,ja,pt"/>
   <property name="org.jboss.dashboard.LocaleManager.defaultLocaleId" value="fr"/>
</system-properties>
----

In this example, the Chinese language (zh) has been removed from the list of installed locales so users will not be able to switch the dashbuilder to Chinese. Dashbuilder will show content in French, which is the default locale. Users will be able to select other languages that are defined (en, es, de, ja, pt) in this file.

[NOTE]
====
Within Business Central, the application server does not need to be restarted after changing locale if you append the "locale" parameter to the URL of Business Central. However, with Dashbuilder, the application server should be restarted after the configuration files have been changed.
====
endif::BA[]

[id='_running_the_jvm_with_utf_8_encoding']
== Running the JVM with UTF-8 Encoding

{PRODUCT} is designed to work with UTF-8 encoding. If a different encoding system is being used by the JVM, unexpected errors might occur.

To ensure UTF-8 is used by the JVM, use the JVM option `-Dfile.encoding=UTF-8`.
