[[_chap_integration_with_aries_blueprint]]
= Integration with Aries Blueprint

This chapter explains the integration elements of {PRODUCT} specific to Apache Aries Blueprint.

== KIE Namespace

[float]
=== KieModule

The `<kie:kmodule>` element defines a collection of a KieBase and its associated KieSessions.

[cols="25%,75%", options="header"]
|===
| Attribute
| Description

|id
|The name to which other beans refer. Blueprint ID semantics applies. This attribute is required.
|===


Possible children:

* `kie:kbase`

[float]
=== KieBase

The `<kie:kbase>` element has the following attributes:

[cols="25%,75%", options="header"]
|===
| Attribute
| Description

|name
|The name of the KieBase. This attribute is required.

|packages
|A comma-separated list of the resource packages to be included in the KieBase.

|includes
|KieBase names to be included. All resources from the corresponding KieBases are included in the parent KieBase.

|default
|A Boolean. Sets the `kbase` as default. Set to `false` by default.

|scope
|Possible values: `prototype` or `singleton`. Set to `singleton` by default.

|eventProcessingMode
|Event Processing Mode. Possible values: `STREAM` or `CLOUD`.

|equalsBehavior
|Possible values: `IDENTITY` or `EQUALITY`.
|===

Possible children:

* `kie:ksession`

The `kmodule` element can contain multiple `kbase` elements.

.kbase Definition Example
====
[source,xml]
----
<kie:kmodule id="sample_module">
   <kie:kbase name="kbase1" packages="org.drools.blueprint.sample">
     ...
   </kie:kbase>
</kie:kmodule>
----
====

When you define a `kbase` or a `ksession`, you can set the bean scope:

* Set `scope` to `prototype` to instantiate a new bean instance every time the bean is called.
* Set `scope` to `singleton` to use the same bean instance every time the bean is called.

[float]
=== KieSession

The `<kie:ksession>` element defines both stateful and stateless KieSessions. It has the following parameters:


[cols="25%,75%", options="header"]
|===
| Attribute
| Description

|name
|The name of the KieSession. This attribute is required.

|type
|Possible values: `stateful` or `stateless`. Set to `stateful` by default.

|default
|A Boolean. Sets the `ksession` as default. Set to `false` by default.

|scope
|Possible values: `prototype` or `singleton`. Set to `singleton` by default.

|clockType
|Possible values: `REALTIME` or `PSEUDO`.

|listeners-ref
|Specifies the reference to the event listeners group. For more information, see <<_kie_grouping_listeners>>.
|===

.ksession definition example
====
[source,xml]
----
<kie:kmodule id="sample-kmodule">
  <kie:kbase name="drl_kiesample3" packages="drl_kiesample3">
    <kie:ksession name="ksession1" type="stateless"/>
    <kie:ksession name="ksession2"/>
  </kie:kbase>
</kie:kmodule>
----
====

[float]
=== Kie:ReleaseId

The `kie:releaseId` element represents Maven GAV (Group ID, Artifact ID, and Version). `kie:releaseId` requires the following properties:


[cols="25%,75%", options="header"]
|===
| Attribute
| Description

|id
|The name to which other beans refer. Blueprint ID semantics applies.

|groupId
|Maven `groupId`.

|artifactId
|Maven `artifactId`.

|version
|Maven `version`.
|===

.releaseId Definition Example
====
[source,xml]
----
<kie:releaseId id="beanId" groupId="org.kie.blueprint"
            artifactId="named-artifactId" version="1.0.0-SNAPSHOT"/>
----
====

[float]
== Kie:Import

{PRODUCT} now supports `kie-aries-blueprint` importing KIE objects from KJARs. The `kie:import` element supports the following attributes:

[cols="25%,75%", options="header"]
|===
| Attribute
| Description

|releaseId
|Reference to a bean ID. Standard Blueprint ID semantics applies.

|enableScanner
|Enable Scanner. This attribute is used only if `releaseId` is specified.

|scannerInterval
|Scanning Interval in milliseconds. This attribute is used only if `releaseId` is specified.
|===

{PRODUCT} supports two modes of importing KIE objects:

Global Import::
The `kie:import` element uses the `KieServices.getKieClasspathContainer()` method to import KIE objects. For further information about KIE methods, see the {URL_DEVELOPMENT_GUIDE}#kie[KIE API] section of the _{DEVELOPMENT_GUIDE}_.
+
.Global Import
[source,xml]
----
<kie:import />
----

Specific Import - ReleaseId::
When using the `releaseId-ref` attribute on the import tag, only KIE objects identified by the referenced `releaseId` element are initialized and imported into the Blueprint context.
+
.KIE Objects Import Using releaseId
[source,xml,subs="verbatim,attributes"]
----
<kie:import releaseId-ref="namedKieSession"/>
<kie:releaseId id="namedKieSession" groupId="org.drools"
            artifactId="named-kiesession" version="{revnumber}"/>
----

You can enable the KIE scanning feature, `enableScanner`, for KieBases imported with a specific releaseId. This feature is currently not available for global imports.

.Import KIE Objects using a releaseId - Enable Scanner
[source,xml,subs="verbatim,attributes"]
----
<kie:import releaseId-ref="namedKieSession"
            enableScanner="true" scannerInterval="1000"/>

<kie:releaseId id="namedKieSession" groupId="org.drools"
            artifactId="named-kiesession" version="{revnumber}"/>
----

If you define and enable a scanner, a `KieScanner` object is created with default values and inserted into the Blueprint container. You can get the `KieScanner` object from the Blueprint container using the `-scanner` suffix.

.Retriving the KieScanner from a Blueprint Container
[source,java]
----

// the implicit name would be releaseId-scanner
KieScanner releaseIdScanner = (KieScanner)container.getComponentInstance("namedKieSession-scanner");
releaseIdScanner.scanNow();
----

[NOTE]
====
`kie-ci` must be available on the classpath for the releaseId importing feature to work.
====

== Event Listeners
{PRODUCT} supports adding 3 types of listeners to KieSessions:

* `AgendaListener`
* `WorkingMemoryListener`
* `ProcessEventListener`

The `kie-aries-blueprint` module allows you to configure the listeners for KIE sessions using XML tags.
The tags have identical names to the listener interfaces:

* `<kie:agendaEventListener>`
* `<kie:ruleRuntimeEventListener>`
* `<kie:processEventListener>`

The `kie-aries-blueprint` module allows you to define listeners as standalone listeners or as a group.

[float]
=== Defining Standalone Listeners

Standalone listeners support the following parameters:


[cols="25%,75%", options="header"]
|===
| Attribute
| Description

|ref
|A reference to a bean.
|===

.Listener Configuration Using bean:ref
====
[source,xml]
----
<bean id="mock-agenda-listener" class="mocks.MockAgendaEventListener"/>
<bean id="mock-rr-listener" class="mocks.MockRuleRuntimeEventListener"/>
<bean id="mock-process-listener" class="mocks.MockProcessEventListener"/>

<kie:kmodule id="listeners_kmodule">
  <kie:kbase name="drl_kiesample" packages="drl_kiesample">
    <kie:ksession name="ksession2">
      <kie:agendaEventListener ref="mock-agenda-listener"/>
      <kie:processEventListener ref="mock-process-listener"/>
      <kie:ruleRuntimeEventListener ref="mock-rr-listener"/>
    </kie:ksession>
  </kie:kbase>
</kie:kmodule>
----
====

[float]
=== Defining Multiple Listeners of One Type

You can also define multiple listeners of one type for a KIE session.

.Listener Configuration: Multiple Listeners of One Type.
====
[source,xml]
----
<bean id="mock-agenda-listener1" class="mocks.MockAgendaEventListener"/>
<bean id="mock-agenda-listener2" class="mocks.MockAgendaEventListener"/>

<kie:kmodule id="listeners_module">
  <kie:kbase name="drl_kiesample" packages="drl_kiesample">
    <kie:ksession name="ksession1">
      <kie:agendaEventListener ref="mock-agenda-listener1"/>
      <kie:agendaEventListener ref="mock-agenda-listener2"/>
    </kie:ksession>
  </kie:kbase>
</kie:kmodule>
----
====

[float]
[[_kie_grouping_listeners]]
=== Defining a Group of Listeners

The `kie-aries-blueprint` module allows you to group listeners. This is useful when you define a set of listeners that you want to attach to multiple sessions, or when switching from testing to production use. The following attribute is required:


[cols="25%,75%", options="header"]
|===
| Attribute
| Description

|ID
|Unique identifier
|===

Possible children:

* `kie:agendaEventListener`
* `kie:ruleRuntimeEventListener`
* `kie:processEventListener`

[NOTE]
====
The declaration order does not matter. Only one declaration of each type is allowed in a group.
====

.Group of Listeners
====
[source,xml]
----
<bean id="mock-agenda-listener" class="mocks.MockAgendaEventListener"/>
<bean id="mock-rr-listener" class="mocks.MockRuleRuntimeEventListener"/>
<bean id="mock-process-listener" class="mocks.MockProcessEventListener"/>

<kie:kmodule id="listeners_module">
  <kie:kbase name="drl_kiesample" packages="drl_kiesample">
    <kie:ksession name="statelessWithGroupedListeners" type="stateless"
             listeners-ref="debugListeners"/>
  </kie:kbase>
</kie:kmodule>

  <kie:eventListeners id="debugListeners">
  <kie:agendaEventListener ref="mock-agenda-listener"/>
  <kie:processEventListener ref="mock-process-listener"/>
  <kie:ruleRuntimeEventListener ref="mock-rr-listener"/>
</kie:eventListeners>
----
====

== Loggers

{PRODUCT} supports the following loggers:

* `ConsoleLogger`
* `FileLogger`

The `kie-aries-blueprint` module allows you to configure the loggers using XML tags with identical names:

* `<kie:consoleLogger>`
* `<kie:fileLogger>`

[float]
=== Defining a Console Logger

The `<kie:consoleLogger/>` element has no attributes and must be present directly under a `<kie:ksession>` element.

.Defining a Console Logger
====
[source,xml]
----
<kie:kmodule id="loggers_module">
  <kie:kbase name="drl_kiesample" packages="drl_kiesample">
    <kie:ksession name="ConsoleLogger-statefulSession" type="stateful">
      <kie:consoleLogger/>
    </kie:ksession>
  </kie:kbase>
</kie:kmodule>
----
====

[float]
=== Defining a File Logger

The `<kie:fileLogger/>` element supports the following attributes:

[cols="25%,75%", options="header"]
|===
| Attribute
| Description

|ID
|Unique identifier. This attribute is required.

|file
|Path to the log file on the disk. This attribute is required.

|threaded
|Possible values: `true` or `false`. Set to `false` by default.

|interval
|An Integer. Specifies the interval for flushing the contents from memory to the disk.
|===

.Defining a File Logger
====
[source,xml]
----
<kie:kmodule id="loggers_module">
  <kie:kbase name="drl_kiesample" packages="drl_kiesample">
    <kie:ksession name="ConsoleLogger-statefulSession" type="stateful">
      <kie:fileLogger id="fl_logger" file="#{ systemProperties['java.io.tmpdir'] }/log1"/>
      <kie:fileLogger id="tfl_logger" file="#{ systemProperties['java.io.tmpdir'] }/log2"
                          threaded="true" interval="5"/>
    </kie:ksession>
  </kie:kbase>
</kie:kmodule>
----
====

[float]
=== Closing a FileLogger

It is recommended to close the `<kie:fileLogger>` logger to prevent memory leaks:

[source,java]
----
LoggerAdaptor adaptor = (LoggerAdaptor) container.getComponentInstance("fl_logger");
adaptor.close();
----

[float]
=== Defining Batch Commands
The `<kie:batch>` element allows you to define a set of batch commands for a given KIE session. The `<kie:batch>` element has no attributes and must be placed under a `<kie:ksession>` element.

.Supported Parameters for Initialization Batch Commands
* `insert-object`
** `ref`: String. This parameter is optional.
** `Anonymous bean`.
* `set-global`
** `identifier`: String. This parameter is required.
** `reg`: String. This parameter is optional.
** `Anonymous bean`.
* `fire-all-rules`
** `max`: Integer.
* `fire-until-halt`
* `start-process`
** `identifier`: String. This parameter is required.
** `ref`: String. This parameter is optional.
** `Anonymous bean`.
* `signal-event`
** `ref`: String. This parameter is optional.
** `event-type`: String. This parameter is required.
** `process-instance-id`: Integer. This parameter is optional.

.Batch Commands Example
====
[source,xml]
----
<kie:kmodule id="batch_commands_module">
  <kie:kbase name="drl_kiesample" packages="drl_kiesample">
    <kie:ksession name="ksessionForCommands" type="stateful">
      <kie:batch>
        <kie:insert-object ref="person2"/>
        <kie:set-global identifier="persons" ref="personsList"/>
        <kie:fire-all-rules max="10"/>
      </kie:batch>
    </kie:ksession>
  </kie:kbase>
</kie:kmodule>
----
====
