[id='_chap_scheduler_service']

= Scheduler Service

The {PRODUCT} engine employs scheduler service to execute jobs at a scheduled time and date. {PRODUCT} has 3 types of scheduler service:

ThreadPoolSchedulerService::

Default scheduler service that manages its own thread pool to allocate available worker threads for the scheduled task. This service is best for a single node use case.

EjbSchedulerService::

Scheduler service implementation backed by EJB Timer Service. You can enable this if you have `jbpm-services-ejb-timer-XXX.jar` in your application. This service is only available under Java EE container, and uses the container's thread pool. This service is best for a single node use case.

QuartzSchedulerService::

Scheduler service implementation backed by Quartz job scheduler. You can enable this when Quartz is configured. For details, see {URL_INSTALLATION_GUIDE}#setting_up_quartz[Setting Quartz] in the _{INSTALLATION_GUIDE}_.

NOTE: For WebSphere, use clustered EjbSchedulerService instead of QuartzSchedulerService, even in a cluster use case. For details, see https://access.redhat.com/solutions/2175471[How to set up BPM Suite Timers to work in Websphere Application Server clustering] on our Red Hat website.
