[id='kie-server-managing-containers-proc']
= Managing Containers

Containers within the {KIE_SERVER} can be started, stopped, and updated from Business Central.

== Starting, Stopping, and Deleting Containers

A container is stopped by default. To start the container:

. Log in to Business Central.
. In the main menu on the top, click *Deploy* -> *Execution Servers*.
. Select your server from the *SERVER TEMPLATES* section on the left side of the page.
. Find the container you want to start under the *KIE CONTAINERS* section on the left.
. Click *Start* at the upper right hand corner.
+
Alternatively, click *Stop* to stop a running container. Once a container is stopped, you can click *Remove* to remove it.

== Upgrading Containers

It is possible to update deployed containers without restarting the {KIE_SERVER}, which can be used in cases where business rule changes cause new versions of packages to be provisioned. You can have multiple versions of the same package provisioned and deployed.

To upgrade a container:

. Log in to Business Central.
. In the main menu on the top, click *Deploy* -> *Execution Servers*.
. Select your server from the *SERVER TEMPLATES* section on the left side of the page.
. Find the container you want to upgrade under the *KIE CONTAINERS* section on the left.
. Click on the *Version Configuration* tab at the top.
. Enter a new version and click *Upgrade*.
+
Optionally, if you want a deployed container to always have the latest version of your deployment without manually editing it, set the *Version* value to *LATEST* and click *Scan Now*. If a newer version of a container deployment is found in the repository during the scanning, the container is automatically upgraded to this newer version. To start the scanner in the background, click *Start Scanner* and specify a scan interval in milliseconds.
+
The *Version* value can be set to *LATEST* if you are creating a deployment for the first time.

== Managing Multiple Containers

The {KIE_SERVER} allows you to create and provision multiple containers.

Select your server under the *REMOTE SERVERS* section to view all containers and their statuses.
