[id='kie-server-creating-containers-proc']
= Creating Containers

Containers are self-contained environments that have been provisioned to hold instances of your packaged and deployed rule instances.

.Prerequisite
Once the {KIE_SERVER} is registered, you can start adding containers.

.Procedure
. Log in to {CENTRAL}.
. In the main menu, click *Menu* -> *Deploy* -> *Execution Servers*.
. Click *SERVER TEMPLATES* -> *+ New Server Template*.
. In the *New Server Template* window, click *Container*.
. Enter the *Group Name*, *Artifact Id*, and *Version* manually.
+ 
Alternatively, enter the name of your container and search for the project you want to deploy in the container.

. Click *Select* next to the project to automatically enter the details of the project.

+
[WARNING]
====
When entering the container's version number, do _not_ use the `LATEST` or `RELEASE` keywords. This feature has been deprecated and can cause deployment issues.
====
. To deploy the container automatically, select the *Start Container?* box.
. Click *Finish*.

After the container is successfully created, select the container from the list and click *Start* at the upper right hand corner to start it

To verify that the container is running, send a [GET] request to the endpoint.

.Server Response
====
[source,xml]
----
<response type="SUCCESS" msg="Info for container myContainer">
  <kie-container container-id="myContainer" status="STARTED">
    <messages>
      <content>Container myContainer successfully created with module org.jbpm:CustomersRelationship:1.0.</content>
      <severity>INFO</severity>
      <timestamp>TIMESTAMP</timestamp>
    </messages>
    <release-id>
      <artifact-id>CustomersRelationship</artifact-id>
      <group-id>org.jbpm</group-id>
      <version>1.0</version>
    </release-id>
    <resolved-release-id>
      <artifact-id>CustomersRelationship</artifact-id>
      <group-id>org.jbpm</group-id>
      <version>1.0</version>
    </resolved-release-id>
    <scanner status="DISPOSED"/>
  </kie-container>
</response>
----
====