[id='manage-execution-errors-proc-{context}']
= Manage execution errors

By definition, every error that is caught and stored is unacknowledged, meaning that it is to be handled by someone or something (in case of automatic error recovery). Errors are filtered on the basis of whether or not they have been acknowledged. Acknowledging an error saves the user information and time stamp for traceability.

You can access the *Error Management* view at any time.

. In {CENTRAL}, click *Menu* -> *Manage* -> *Execution Errors*.
. Select an error from the list to open the *Details* tab. This displays information about the error or errors.
. Click the *Acknowledge* button to acknowledge and clear the error. The error can still be viewed later by selecting *Yes* on the *Acknowledged* filter in the *Manage Execution Errors* page.
. If the error was related to a task, a *Go to Task* button is displayed.
+
Click the *Go to Task* button to view the associated job information in the *Manage Tasks* page.
+ 
The *Manage Tasks* page allows you to restart, reschedule, or retry the corresponding task.