[id='console-server-management']
= Administration Console Server Management

The Business Central management console allows you to manage multiple Intelligent Process Server instances through the *Server Templates* page, which you can access by clicking *Deploy* -> *Execution Servers*. The management console allows servers to integrate with Business Central for execution in two ways:

* Server management (that maintains server templates), allowing you to know what servers are available and their location.
* Intelligent Process Server client that interacts with remote servers.

Server management is used to collect information about the following:

* Server templates wherever a project is to be deployed, regardless of whether or not any remote servers exist. 
* Remote servers whenever Intelligent Process Server interaction is required, for example, start and `GET` operations. 

Where multiple server templates are available, you can choose which server template to interact with by selecting the corresponding box on the Server Templates screen. It is not important which server instance is to be used for the request, as long as one is available. Server templates that do not have any remote servers available will not be visible on the list of server templates. Where only one server template exists, it becomes the default for both deployment and runtime operations.

