[id='sso-realm-proc']
= Installing and configuring RH-SSO

A realm is a security policy domain defined for a web or application server. Security realms are used to restrict access for different application resources. You should create a new realm whether your RH-SSO instance is private or shared with other products. You can keep the master realm as a place for super administrators to create and manage the realms in your system. If you are integrating with an RH-SSO instance that is shared with other product installations to achieve single sign-on with those applications, all of those applications must use the same realm. To create an RH-SSO realm, download, install, and configure RH-SSO 7.2.

[NOTE]
====
If {CENTRAL} and {KIE_SERVER} are installed on different systems, complete this procedure on both systems.
====

.Procedure
. Download RH-SSO 7.2:
.. Log in to the https://access.redhat.com[Red Hat Customer Portal].
.. Click *DOWNLOADS* at the top of the page.
.. On the *Product Downloads* page that opens, navigate to the JBOSS INTEGRATION AND AUTOMATION section, and click *Red Hat Single Sign-On*.
.. On the *Software Downloads* page, if necessary select *7.2* from the *Version* menu.
.. Download *Red Hat Single Sign-on 7.2.0 Server* (`rh-sso-7.2.0.GA.zip`).
. To install and configure a basic RH-SSO standalone server, follow the instructions in the https://access.redhat.com/documentation/en/red-hat-single-sign-on/7.0/single/getting-started-guide/#install-boot["Install and Boot"] chapter of the _Red Hat Single Sign On Getting Started Guide_. For advanced settings for production environments, see the https://access.redhat.com/documentation/en/red-hat-single-sign-on/7.0/single/server-administration-guide/[_Red Hat Single Sign On Server Administration Guide_].
+
[NOTE]
====
If you want to run both RH-SSO and {PRODUCT} servers on the same system, ensure that you avoid port conflicts. by doing one of the following:

* Update the `_RHSSO_HOME_/standalone/configuration/standalone.xml` file and set a port offset to 100. For example:
+
[source]
----
<socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:100}">
----

* Use an environment variable to run the server:
+
[source]
----
bin/standalone.sh -Djboss.socket.binding.port-offset=100
----
====
