[id='sso-user-add-proc']
= Adding {PRODUCT} users
Before you can use RH-SSO to authenticate {CENTRAL} or {KIE_SERVER}, you must add users to the realm that you created. To add new users and assign them a role to access {PRODUCT}, complete the following steps:

. Log in to the RH-SSO Admin Console and open the realm to which you want to add a user.
. Click the *Users* menu item under the *Manage* section.
+
An empty user list appears on the *Users* page.

. Click the *Add User* button on the empty user list to start creating your new user.
+
The *Add User* page opens.

. Provide user information on the *Add User* page and click *Save*.
. Select the *Credentials* tab and create a password.
. Assign the new user one of the roles that allow access to {PRODUCT}. For example, assign the `admin` role to access {CENTRAL} or assign the `kie-server` role to access {KIE_SERVER}.
. Define the roles as realm roles in the *Realm Roles* tab under the *Roles* section.
+
. Click the *Role Mappings* tab on the *Users* page to assign roles.