[id='sso-int-points-con']
= RH-SSO integration points
You can integrate RH-SSO with {KIE_SERVER}s using the following integration points:

* *{PRODUCT} authentication through an RH-SSO server*
+
Authenticating {PRODUCT} through RH-SSO involves securing both {PRODUCT} web client and remote services through RH-SSO. This integration enables you to connect to {PRODUCT} using either the web interface or a remote service consumer through RH-SSO.

* *{KIE_SERVER} authentication through an RH-SSO server*
+
Authenticating {PRODUCT} {KIE_SERVER} through RH-SSO involves securing the remote services provided by {KIE_SERVER} because it does not provide a web interface for server authentication. This enables any remote {PRODUCT} service consumer (user or a service) to authenticate through RH-SSO.

* *Third-party client authentication through an RH-SSO server*
+
Authenticating a third-party client through an RH-SSO server requires third-party clients to authenticate themselves using RH-SSO to consume the remote service endpoints provided by {PRODUCT} and {KIE_SERVER}, such as the REST API or remote file system services.

The following sections describe how to achieve RH-SSO integration through these integration points.

