[id='sso-central-client-create-proc']
= Creating the {Central} client for RH-SSO

After the RH-SSO server starts, open http://localhost:8180/auth/admin in a web browser and log in using the admin credentials that you created while installing RH-SSO. When you login for the first time, you can set up the initial user on the new user registration form.

. In the RH-SSO Admin Console, click the *Realm Settings* menu item.
. On the *Realm Settings* page, click *Add Realm*.
+
The *Add realm* page opens.

. On the *Add realm* page, provide a name for the realm and click *Create*.
. Click the *Clients* menu item and click *Create*.
+
The *Add Client* page opens.

. On the *Add Client* page, provide the required information to create a new client for your realm. For example:
* *Client ID*: kie
* *Client protocol*: openid-connect
* *Root URL*: http://_localhost_:8080/business-central

. Click *Save* to save your changes.
+
After you create a new client, its *Access Type* is set to `public` by default. Change it to `confidential`. 
+
The RH-SSO server is now configured with a realm with a client for {CENTRAL} applications and running and listening for HTTP connections at [parameter]``localhost:8180``. This realm provides different users, roles, and sessions for {CENTRAL} applications.

