#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Apache KIE Documentation Preview - Build

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README*"
      - "CONTRIBUTING.md"
jobs:
  build:
    concurrency:
      group: pull_request-nochain-${{ github.head_ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [17]
        maven-version: ['3.9.6']
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    steps:
    - uses: actions/checkout@v4
    - name: Java and Maven Setup
      uses: apache/incubator-kie-kogito-pipelines/.ci/actions/maven@main
      with:
        java-version: ${{ matrix.java-version }}
        maven-version: ${{ matrix.maven-version }}
        cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
        allow-snapshots: true
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml -Dfull
    
    - name: Store PR id
      if: github.event_name == 'pull_request'
      run: |
        echo ${{ github.event.number }} > ./doc-content/apache-kie-kogito/target/generated-docs/pr-id.txt

    - name: Publishing directory for Kogito PR preview
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: kogito-site
        path: ./doc-content/apache-kie-kogito/target/generated-docs
        retention-days: 3

    - name: Publishing directory for JBPM PR preview
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: jbpm-site
        path: ./doc-content/apache-kie-jbpm/target/generated-docs
        retention-days: 3