[id='assembly_kogito-release-notes']

= Release notes for {PRODUCT} {COMMUNITY_VERSION}
// Context attribute is assembly specific and enables module reuse between assemblies.
:context: kogito-release-notes

// Purpose statement for the assembly
These release notes list key features and known issues in {PRODUCT}.

[IMPORTANT]
====
{PRODUCT} is currently available for Development Preview. Development Preview releases contain features and APIs that might not be fully tested and that might change in the final GA version. Users are discouraged from using Development Preview software in production or for business-critical workloads.  Because this is not production-ready software, users are not able to open support tickets. To learn more about {PRODUCT}, please contact your Red Hat representative or send an email to Kogito-earlyaccess@redhat.com. Red Hat will address reported issues at its own discretion.
====

include::release-notes/ref_kogito-rn-key-features.adoc[leveloffset=+1]
include::release-notes/ref_kogito-rn-known-issues.adoc[leveloffset=+1]
